### ISSUE TITLE
Issues with placing Chairs

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1035] opened 2017-01-15 13:43 UTC
http://ecoforum.strangeloopgames.com/topic/1364/stair-placement-could-be-improved

**Comment by MarjieAVolk** [comment] 2017-03-22 18:51
Closing as a duplicate of StrangeLoopGames/EcoIssues#438

**Closed by MarjieAVolk** 2017-03-22 18:51 UTC
