### ISSUE TITLE
Crafting ui inventory count is missing some inventories

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3851] opened 2018-02-04 02:18 UTC
I was on someone else's property where I had auth, and linking their stockpile to a crafting table didn't cause the numbers in the crafting ui to update.  But they were taken when I started a project

**Comment by WeaselDog** [comment] 2020-01-06 00:06
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2638

**Closed by WeaselDog** 2020-01-06 00:06 UTC
Labels: Medium Priority
