### ISSUE TITLE
USER ISSUE: Erro character creation

### ISSUE THREAD

**Issue by AlissonSchel** [StrangeLoopGames/EcoIssues#25319] opened 2024-12-15 17:06 UTC
\
**User Id: (d4865774-3f74-4465-deb9-08dd1cd2fcae)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**
1. Enter avatar customization
2. Edit all body and face characteristics
3. Go to hats and chose any
4. Change the hat to any other
5. The avatar should become all pink without texture

**Expected behavior:**
Should apply hat correctly	

**Actual behavior:**
Change all avatar to pink, removing the textures

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-12-16 12:44
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25311

**Closed by D3nnis3n** 2024-12-16 12:44 UTC
