### ISSUE TITLE
USER ISSUE: Server crashes when trying to dig (dirt)

### ISSUE THREAD

**Issue by zomyjordy** [StrangeLoopGames/EcoIssues#5950] opened 2018-03-12 17:25 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Equip a shovel
2. Left click on the ground (to dig)
3. The player in the server who does this immediately crashes

**Expected behavior:**
Remove 1 square of ground and have it be on the shovel

**Actual behavior:**
The following error message popped up:
"Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.

Stack:
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size)
   at LiteDB.DataService.Insert(CollectionPage col, Byte[] data)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.UsableItemUtils.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   at Eco.Gameplay.Items.ToolItem.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, Single calorieMultiplier, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   at Eco.Mods.TechTree.ShovelItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>"
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.

Stack:
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size)
   at LiteDB.DataService.Insert(CollectionPage col, Byte[] data)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.UsableItemUtils.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   at Eco.Gameplay.Items.ToolItem.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, Single calorieMultiplier, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   at Eco.Mods.TechTree.ShovelItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-13 20:58
Hey, if you could send me the .db file for this save, I can try to debug this issue for everyone.  Would be a huge help.  Thanks!

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5808

**Closed by MarjieAVolk** 2018-03-13 20:58 UTC

**Comment by MarjieAVolk** [comment] 2018-03-13 21:02
If you are running your own server, it should be '[...]\steamapps\common\Eco\Eco_Data\Server\Storage\\[GameName].db'

**Comment by zomyjordy** [comment] 2018-03-14 17:29
It seems this forum doesn't accept .db files, how can I send mine to you, because I have found it (https://gyazo.com/4309c4e791022111185d115a7e3293be)

**Comment by MarjieAVolk** [comment] 2018-03-16 01:23
You can send it to a .zip file.

**Comment by zomyjordy** [comment] 2018-03-16 10:20
[Jordy, Ilse, Mark, Pieter.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1818817/Jordy.Ilse.Mark.Pieter.zip)
okay thanks, here it is. Thank you for helping
