### ISSUE TITLE
Balance house value

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3068] opened 2017-12-11 21:05 UTC
![image](https://user-images.githubusercontent.com/3536496/33853763-f8b490fe-de73-11e7-834a-73fa99045966.png)
Housing starts off useless compared to food, then becomes massively overpowered

**Comment by MarjieAVolk** [comment] 2017-12-11 23:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3063

**Closed by MarjieAVolk** 2017-12-11 23:29 UTC
