### ISSUE TITLE
USER ISSUE: Connection Failed?

### ISSUE THREAD

**Issue by OriginalSphy** [StrangeLoopGames/EcoIssues#4489] opened 2018-02-14 03:00 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
1. click continue

2. everything loads then it minimizes the game

3. open the game back up

4. connection failed

**Expected behavior:**
continued the game I was playing

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-02-14 21:01
Can you send me your server log files?  These are in '[...]\steamapps\common\Eco Server'.

**Comment by OriginalSphy** [comment] 2018-02-14 22:46
[log_180214030832.log](https://github.com/StrangeLoopGames/EcoIssues/files/1725893/log_180214030832.log)
[log_180214041016.log](https://github.com/StrangeLoopGames/EcoIssues/files/1725894/log_180214041016.log)
[log_180214052858.log](https://github.com/StrangeLoopGames/EcoIssues/files/1725895/log_180214052858.log)
[log_180214125659.log](https://github.com/StrangeLoopGames/EcoIssues/files/1725896/log_180214125659.log)

These are all four that are in that folder, but I can make a new world and play on it, but after reloading it a couple of times it gives me the connection failed issue? I just made a new world with a friend after the first one gave me the issue, and this new world gave me the same problem today

**Comment by MarjieAVolk** [comment] 2018-02-14 22:59
Hm so there are no error messages in there, looks like your server is starting up correctly.

For the saves that you can't load, if you use the Eco Server tool to open the save instead, does that work?

**Comment by OriginalSphy** [comment] 2018-02-14 23:07
How do you go about using that?

**Comment by OriginalSphy** [comment] 2018-02-14 23:29
Where does steam normally save the world files for eco? I've opened just about every file related to eco and can't find one for my worlds. I have downloaded the eco server.

**Comment by OriginalSphy** [comment] 2018-02-15 00:51
I don't know if it helps knowing, but before the game minimizes, it always does it when loading 'GameplayStatsPlugin'

**Comment by OriginalSphy** [comment] 2018-02-15 21:15
Bump?

**Comment by OriginalSphy** [comment] 2018-02-15 22:31
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ionic.Zip.ZipException: Could not read Storage\Game.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x00205BAF
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

This shows up when I try to run it with the server tool

**Comment by MarjieAVolk** [comment] 2018-02-16 19:49
Well that is odd, that you would get that when running with the server tool, but not when running via Continue.

So one other thing you can try it to delete C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO.  It seems sometimes the saved preferences for the Continue button get corrupted, this will reset them.  You can also try loading your save in game via Load instead of via Continue

**Comment by OriginalSphy** [comment] 2018-02-17 14:15
Via Load it gives me the same issue 'Connection Failed' even after deleting C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by MarjieAVolk** [comment] 2018-02-23 21:52
I apologize for the long delay, I got very behind on responding to bug reports since there were so many.

I still don't know what is up with your save.  Could you maybe send the save file over?  Unfortunately it looks like your save file is corrupted.  But I would guess or hope that you have been able to play on other saves?

**Comment by MarjieAVolk** [comment] 2018-02-23 23:55
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4665

If you have any more information, or a save file, will still be helpful.

**Closed by MarjieAVolk** 2018-02-23 23:55 UTC

**Comment by OriginalSphy** [comment] 2018-02-24 19:49
https://drive.google.com/file/d/1QBmMTPrfBC1Iq6Az9mevUhTtyG_M8VLM/view?usp=sharing 
Here is the first game file it happened on. I haven't been able to play twice on one game file since this bug, only on servers.

**Comment by MarjieAVolk** [comment] 2018-02-26 18:02
Is it possible that it's special characters in your username or in your deed names, etc, that are causing this?

**Comment by OriginalSphy** [comment] 2018-03-01 02:24
No, my name is strictly 'Pearish' with just regular alphabet characters
