### ISSUE TITLE
New Server Version Not Compatible with Old Worlds 

### ISSUE THREAD

**Issue by JAGGANOT** [StrangeLoopGames/EcoIssues#10001] opened 2018-11-14 05:18 UTC
like in the top section the New Server Version Not Compatible with Old Worlds 
ther is a dump from our server 

> --BEGIN DUMP--
> Dump Time
> 11/14/2018 06:09:11
> 
> Exception
> Exception: NullReferenceException
> Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    at Eco.Gameplay.Utils.PickerTracker.get_Inventories()
>    at Eco.Gameplay.Utils.PickerTracker.SetRemaining(IEnumerable`1 stacks)
>    at lambda_method(Closure , Object[] )
>    at Eco.Core.Serialization.Serializers.ClassSerializer`1.<>c__DisplayClass10_0.<.ctor>b__1()
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.EnumerableSerializer`2.Decode(BinaryReader reader, Object instance)
>    at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.DictionarySerializer`3.Decode(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
>    at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
>    at Eco.Core.Serialization.DataStore.Load[T](String folder, Action`2 createFunc)
>    at Eco.Core.Plugins.StorageManager.CreateOrLoad[StorageType](String folder, Action`1 onCreate)
>    at Eco.Core.Plugins.SimplePlugin`1.DoLoad(String name)
>    at Eco.Core.Plugins.SimplePlugin`1..ctor(String name)
> 
> --END DUMP--
>

**Comment by mirasrael** [comment] 2018-11-14 11:53
Hi @JAGGANOT Please attach save dump.

**Comment by JAGGANOT** [comment] 2018-11-14 16:40
Hi the files are to big i add a link to download it 


https://1drv.ms/u/s!AiWVzbLtAg3Xu17RDihtwOYw4oXP

**Comment by D3nnis3n** [comment] 2018-11-15 00:03
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10018

**Closed by D3nnis3n** 2018-11-15 00:03 UTC
Labels: High Priority

**Comment by JAGGANOT** [comment] 2018-11-15 00:41
well the other post is the duplicat i made this post bevor he made his but ok

**Comment by D3nnis3n** [comment] 2018-11-15 00:42
Yes, i know, but the other one has been created on developers request by a moderator and in order to not confuse them i closed this one. I added your world to that one, too. They'll see it.
