### ISSUE TITLE
Bring back save game renames and deletes

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7407] opened 2018-04-25 22:27 UTC
From user request:
![image](https://user-images.githubusercontent.com/3536496/39276221-15209f9c-489d-11e8-8609-593687828fc0.png)
He who deleteth the feature must recreateth it.

**Comment by metachronism** [comment] 2018-07-12 04:56
dupe of #6984
we actually never supported renames

**Closed by metachronism** 2018-07-12 04:56 UTC
Labels: Feature, Medium Priority

**Comment by MarjieAVolk** [comment] 2018-07-12 18:29
Think you linked the wrong bug here
