### ISSUE TITLE
USER ISSUE: Chopping a tree

### ISSUE THREAD

**Issue by DrPeppiX** [StrangeLoopGames/EcoIssues#3838] opened 2018-02-04 00:10 UTC
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
1. i started chopping a tree and it wount fall down. So i started to chop the root. the root disepears and the tree still standing. I jumped to chop the tree a bit higher and a log was fallen on my head. After that -> Error

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by frozenyuri** [comment] 2018-02-04 00:23
i have this to,,  except the error

https://www.dropbox.com/s/9xs0rblxo2xybm3/2018-02-04%2001-09-35.flv?dl=0

**Comment by MarjieAVolk** [comment] 2018-02-04 00:24
Sounds like another oak problem, probably a duplicate of something else

**Comment by Nanders** [comment] 2018-02-04 04:12
This should be fixed

**Closed by Nanders** 2018-02-04 04:12 UTC
Labels: High Priority
