### ISSUE TITLE
USER ISSUE: Cant connect to a server

### ISSUE THREAD

**Issue by dazump** [StrangeLoopGames/EcoIssues#5013] opened 2018-02-23 21:59 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Start the game from steam library
2. click either new/load/join
3. as the connection window pops up wait till you get the error msg connection failed	

**Expected behavior:**
It should have connected to any server either the game i started or a dedicated server...	

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-02-24 00:05
Since you can't connect to any world, I would try:
* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software

If you are getting an error message that says 'invalid login info' on the other hand, then you may need your Strange Loop account fixed.

**Comment by dazump** [comment] 2018-02-24 09:38
Hello!

So after several further fails yesterday I was able to connect to a random server from the list. others did not work with the same connection failed issue.

Today I tried what you suggested. For now I was able to connect to several servers from the list.
So I turned on my Firewall again and I am still able to connect to online servers.

though generating a new game and/or trying to load one that is already in my list does not work at all. I always get the same connection failed msg. my Gf with whom i would like to play together has the exact same issue. :(

While typing this i found a EcoServer file. I executed it wawited till the server started and I was able to create my own game.

feeling bit dump now ;) Thx for the help anyways,
greetings from DAU dazump! ;)

**Comment by MarjieAVolk** [comment] 2018-02-26 17:53
Ah, okay, glad you found a way to play.  I have had other reports that loading the default world in game does not work, and most of those people found that selecting 'Generate new' when creating a new world in game worked for them.  Or as you did, most people also found that running the server separately worked for them also.  Hopefully we can fix the default world problem O.o

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4935

**Closed by MarjieAVolk** 2018-02-26 17:53 UTC
