### ISSUE TITLE
USER ISSUE: Loading crash bug

### ISSUE THREAD

**Issue by zacpez** [StrangeLoopGames/EcoIssues#12430] opened 2019-05-29 00:11 UTC
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
If you,
1. Start game
2. Load a sigleplayer save via "Continue"
3. Play for a while (not necessary)
4. Disconnect to main menu
5. Reload same save with "Continue"

Then,
Part way through loading , the game fails to load the save.

Notes:
Might be due to a slightly aged save, start a couple months prior to this version. Save data migration might be the cause. Hence a bit less important of an issue. 

**Expected behavior:**
The game should not crash on loading a save through continue a second time. 

**Actual behavior:**
The second load of a saved game should not fail to load. Surprisingly a third load will then work. Its always the second load.

The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
**Answer**: No mods install, straight vanilla downloaded via steam.

The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.
```

**Comment by SlayksWood** [comment] 2019-06-06 09:06
Checked on 8.2.0 staging-983. Wasn't able to reproduce, seems fixed.

- Start Eco 8.1.4
- Generate new world in 8.1.4 version.
- disconect
- Press button "continue". wait for loading world.
- Close game
- Uptade to current version 0.8.2.0 staging-983
- Start game
- Press button "continue"
![image](https://user-images.githubusercontent.com/45708377/59018187-f70a0880-884d-11e9-96ac-f976c7aa68d2.png)
- saved file is loading, all right
- disconnect
- Press button "continue". Saved file is loading, all right.

I tried to migrate from 8.1.0 to 8.1.4 too.

If I rename or delete saved file and click continue, a new world with this name will be created. Everything works well for me. I tried many options, but continue button always works.

@zacpez 
Can you suggest any more useful information or point at my errors in step to reproduce?
How often does it happen?

**Comment by D3nnis3n** [comment] 2019-06-20 10:26
Closing for now due to not being reproducable and no further information available. Reopen when it occurs again and you can provide more information / logfiles.

**Closed by D3nnis3n** 2019-06-20 10:26 UTC
Labels: Investigate, Needs Information
