### ISSUE TITLE
USER ISSUE: Teleporting stones

### ISSUE THREAD

**Issue by RosesOnMyGrave** [StrangeLoopGames/EcoIssues#25057] opened 2024-08-17 19:34 UTC
\
**User Id: (c258d757-3c36-4361-d782-08dcbd395caf)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
1. Play on a local game with other people (We were 3 and 4)
2. Mine stone with a stone pickaxe

**Expected behavior:**
Broken blocks should've spawned in front of the player or nearby.

**Actual behavior:**
Instead, they teleport in weird places, such as in a house, or floating in the air, or ten blocks away from the player.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, I don't have mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log.copy.txt](https://github.com/user-attachments/files/16646297/Player.log.copy.txt)
[Player-prev.log](https://github.com/user-attachments/files/16646298/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-08-18 15:38
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25037

**Closed by D3nnis3n** 2024-08-18 15:38 UTC
