### ISSUE TITLE
Account Icons on SLG Website

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#20490] opened 2021-02-11 20:08 UTC
![Screenshot_20210211-140524_Chrome](https://user-images.githubusercontent.com/36024353/107692493-7e8a5a80-6c72-11eb-9396-ea5b4be76e1f.jpg)
It seems like the Hare and Banner icon are the same as Wolf.

**Comment by D3nnis3n** [comment] 2021-02-17 02:57
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18103

**Closed by D3nnis3n** 2021-02-17 02:57 UTC
Labels: Category: Web, Priority: Medium
