### ISSUE TITLE
Fishing Glitch

### ISSUE THREAD

**Issue by blazevspfister** [StrangeLoopGames/EcoIssues#6430] opened 2018-03-24 02:50 UTC
https://streamable.com/6ecua

Version: Latest

OS: Windows 10

**Comment by MarjieAVolk** [comment] 2018-03-28 19:24
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6322

**Closed by MarjieAVolk** 2018-03-28 19:24 UTC
