### ISSUE TITLE
Users Crash When Crafting 

### ISSUE THREAD

**Issue by NSH4RPY** [StrangeLoopGames/EcoIssues#5925] opened 2018-03-11 21:38 UTC
All my users have had issues where when crafting it kicks them from the game.

Error message:

Caught exception:

<size=60.00%>Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC CreateWorkOrder on CraftingComponent!

Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.

Stack:
at LiteDB.PageService.GetPage[T](UInt32 pageID)
at LiteDB.TransactionService.PersistDirtyPages()
at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func2 action) at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId) at LiteDB.LiteCollection1.Insert(T document)
at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
at Eco.Gameplay.Components.CraftingComponent.CreateWorkOrder(Player player, Recipe recipe, Int32 quantity)

Stack:
at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

Stack:
at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
at Eco.Shared.Networking.NetPort.ProcessBuffer()
at Eco.Shared.Networking.NetPort.Update()
at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

-------------------------------------------------

After reverting to a different back up 20 mins later we get this 

31:15] Caught network exception from Baraki! Disconnecting...
[31:15] Disconnecting client [reason: Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Cannot insert duplicate key in unique index '_id'. The duplicate value is '15690'.

Stack:
at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func2 action) at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId) at LiteDB.LiteCollection1.Insert(T document)
at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
at Eco.Gameplay.Plants.PlantEntity.TryHarvest(Player player, Boolean picked)
at Eco.Mods.TechTree.ShovelItem.OnActLeft(InteractionContext context)
at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
at Eco.Shared.Networking.NetPort.ProcessBuffer()
at Eco.Shared.Networking.NetPort.Update()
at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>]...

**Comment by MarjieAVolk** [comment] 2018-03-12 23:58
First one looks like https://github.com/StrangeLoopGames/EcoIssues/issues/5548

Would you be able to send me the .db file for the save where this happens?  Also, was this save file updated from an older game version?

The second error should be fixed in the next release

**Comment by MarjieAVolk** [comment] 2018-03-13 00:17
Closing as duplicate of #5548, if you have the .db file though, will still be super helpful.

**Closed by MarjieAVolk** 2018-03-13 00:17 UTC
Labels: High Priority

**Comment by NSH4RPY** [comment] 2018-03-13 00:29
Here you go :) 
[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1804991/Game.zip)

**Comment by MarjieAVolk** [comment] 2018-03-13 23:22
Thank you!
