### ISSUE TITLE
USER ISSUE: Chat window scrolls to center of log

### ISSUE THREAD

**Issue by funnybunnyofdoom** [StrangeLoopGames/EcoIssues#8518] opened 2018-07-14 13:15 UTC
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
While gathering wood and cutting debris, the chat scrolls to the center of it's log

**Expected behavior:**
remained at the latest messages

**Actual behavior:**
scrolled up to a later conversation

**Comment by MarjieAVolk** [comment] 2018-07-16 18:47
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8248

**Closed by MarjieAVolk** 2018-07-16 18:47 UTC
Labels: Medium Priority
