### ISSUE TITLE
USER ISSUE: Stuck

### ISSUE THREAD

**Issue by Vinscen** [StrangeLoopGames/EcoIssues#7095] opened 2018-04-09 17:38 UTC
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
Stuck in the pipes in someone else's warehouse, the owner of the warehouse is not online. And I do not know how to get out on my own.

**Expected behavior:**

**Actual behavior:**
![image](https://user-images.githubusercontent.com/38224036/38513111-e465bad6-3c35-11e8-9c44-e9adb7ebec12.png)

**Comment by MarjieAVolk** [comment] 2018-04-09 17:44
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6490

Can you get out using /unstuck?

**Closed by MarjieAVolk** 2018-04-09 17:44 UTC

**Comment by Vinscen** [comment] 2018-04-09 17:47
![image](https://user-images.githubusercontent.com/38224036/38513498-15bd4094-3c37-11e8-8ec8-cbf638bbbcc0.png)
I did it, thanks for the help!

**Comment by MarjieAVolk** [comment] 2018-04-09 18:00
:D
