### ISSUE TITLE
9.4 Dev 272 - Movement direction doesnt correspond to view direction in 3rd person view.

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21700] opened 2021-04-30 18:12 UTC
When in third person view looking left/right or doing A or D does not turn the cart just makes me go 45 degree angle before going back to the original angle i was facing, it strafes but then goes back to the way i was starting to face.

First person is fine though so this is probably related to the new third person view mechanisms

**Comment by IcedForge** [comment] 2021-05-03 13:30
Movement direction doesnt correspond to view direction in 3rd person view.

**Comment by Daniel-Magulado** [comment] 2021-05-31 18:13
Tested on 0.9.4 Staging-1997.

Appears to be fixed at most but the forward and backward controls got reversed for some vehicles such as the Wheelbarrow and the hand plow. Reopening and bumping the priority as this can be really bothering.

Wheelbarrow and Handplow controls are reversed.

Reproduction Steps
1. Obtain a wheelbarrow and a hand plow.
2. Operate these vehicles.
3. Observe.

https://user-images.githubusercontent.com/77248866/120228949-bb5c7a80-c27e-11eb-9ba5-5047f7fbbbd1.mp4

**Comment by Quadbro** [comment] 2021-06-03 07:40
@Daniel-Magulado @SlayksWood Fixed Wheelbarrow and Plow, also added a small dead zone to be able to move straight

**Comment by Daniel-Magulado** [comment] 2021-06-04 17:24
Tested on 0.9.4 Staging-2008.

Awesome fix for the Wheelbarrow and the Hand Plow. Feels nice to use a wheelbarrow and the controls are just right compared to how it was before. 

However, reopening with a few issues noted below:

### Backing up
If you press the S key, the avatar walks backward regardless of the camera mode view. If you move your camera around while walking backward, the avatar will keep walking backward while following the camera. However, this is not the case when holding Wood Cart, Wheelbarrow, and Hand Plow. See the comparison below:

https://user-images.githubusercontent.com/77248866/120835820-675fd780-c597-11eb-96cf-dc1c857e319c.mp4

While holding the said vehicles, moving backward causes the avatar to move away from the camera.

### Moonwalking
If you try to reproduce the same issue above with Hand Plow, you'll find that the avatar performs moonwalking.

https://user-images.githubusercontent.com/77248866/120836256-f240d200-c597-11eb-8125-515dcea67fb5.mp4

### Jerky walking animation and shaky legs
For some reason, using the said vehicles after the changes in controls introduce a jerky walking animation and shaky legs.

https://user-images.githubusercontent.com/77248866/120838022-f0780e00-c599-11eb-8c54-1fc471329e01.mp4

### Avatar Shift Facing
If you pick up the said vehicles and then let them go. You're instantaneously shifted facing one of the cardinal directions, the same behavior is seen here #21802. (Only happens in 3rd person view)

https://user-images.githubusercontent.com/77248866/120840082-56fe2b80-c59c-11eb-9c6e-b717b1f5b688.mp4

**Comment by Quadbro** [comment] 2021-06-07 04:58
@Daniel-Magulado Probably such issues you described in last comment should go as sepaarate ones, because original issue fixed anyways....

**Comment by Quadbro** [comment] 2021-06-07 12:43
Fixed all exept Jerky walking animation and shaky legs, that one really needs a sepparate issue, becasue its unrelated to direction and requires investigation @Daniel-Magulado

**Comment by Daniel-Magulado** [comment] 2021-06-14 09:07
Tested on 0.9.4 Staging-2020.

Separated the jerky walking animation and shaky legs.
However, reopening as there seems to be some kind of new issue when backing up with Wheelbarrow and Hand Plow. Wood Cart is not affected.

With the said build, if you try to walk backward while holding any of the affected vehicles straight, you move backward correctly. However, if you try to move backward while turning left or right by moving your mouse once to initiate a direction, the game shows different behavior with Wood Cart and Wheelbarrow. Hand Plow exhibits the same behavior as with Wheelbarrow. With Wheelbarrow, the avatar get's stuck in one direction and the camera doesn't follow the avatar's movement but with Wood Cart, the avatar keeps backing up and the camera follows it which becomes a backward spin movement. See video recording for difference below:


https://user-images.githubusercontent.com/77248866/121867528-a0840e80-cd32-11eb-83ab-4bc601ead6fc.mp4


Please note that I only moved the mouse to change the camera for the Avatar to move in a different direction. I'm not constantly moving my mouse to follow the avatar movement.

**Comment by Daniel-Magulado** [comment] 2021-06-15 06:58
Closing as fixed on 9.4 Staging-2020

**Closed by Daniel-Magulado** 2021-06-15 06:58 UTC
Labels: Category: Gameplay, Priority: High, Regression, Squad: Otter, Status: Fixed, Type: Bug
