### ISSUE TITLE
USER ISSUE: Crimini mushrooms collision gets wooden cart stuck in tall grass

### ISSUE THREAD

**Issue by pricindalas** [StrangeLoopGames/EcoIssues#23979] opened 2023-08-18 15:19 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
1. Mount any cart and drive through grass.
2. Drive with the cart through grass where crimini mushrooms grow.

Every other musrhoom type or grass does not collide with player or cart but Crimini mushrooms get you stuck on them and it is very annoying.

**Expected behavior:**
As for any other musrhoom or grass type, there is no collision with player or cart, so expected behavior would be to disable collision on crimini mushrooms.

**Actual behavior:**
Collision gets you stuck on Crimini musrhooms. Is it made on purpose for something other important?

**Do you have mods installed? Does the issue happen when no mods are installed?:**
There are no mods installed on my game.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-08-24 12:14
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23915

**Closed by D3nnis3n** 2023-08-24 12:14 UTC
