### ISSUE TITLE
USER ISSUE: Small Hanging Stone Sign offset bug

### ISSUE THREAD

**Issue by Aintence** [StrangeLoopGames/EcoIssues#8195] opened 2018-06-27 20:20 UTC
**Version:** 0.7.5.0 beta

**Steps to Reproduce:**
1. Craft sign in title
2. Try place it on wall
3. See the bug

**Expected behavior:**
It should rotate around the block, look like its hanging off the wall when in correct position

**Actual behavior:**
It seems to be offset by 1/2 block. Placing it in correct rotation will put sign inside block you are hanging it on.

**Comment by elfl0rd** [comment] 2018-06-27 22:48
refers to https://github.com/StrangeLoopGames/EcoIssues/issues/8055

**Comment by MarjieAVolk** [comment] 2018-07-03 17:10
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8055

**Closed by MarjieAVolk** 2018-07-03 17:10 UTC
Labels: Medium Priority
