### ISSUE TITLE
I can't load up Eco!

### ISSUE THREAD

**Issue by Awesomepro247** [StrangeLoopGames/EcoIssues#5812] opened 2018-03-10 00:55 UTC
I try to load Eco but all that appears is a black screen and the cursor. I hear the sound from the title screen but see nothing. I don't know what to do.

**Comment by MarjieAVolk** [comment] 2018-03-10 01:00
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4834 - The workaround posted there might help you.

**Closed by MarjieAVolk** 2018-03-10 01:00 UTC
