### ISSUE TITLE
Hand driven Carts do not break when released while moving

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6199] opened 2018-03-17 18:24 UTC
i released a cart while i still was moving, the cart continued as if it had infinite impulse and no clue on friction

**Comment by Epimetheus89** [comment] 2018-03-17 21:10
I think this is a duplicate of #6104

**Comment by SeanAtr0n** [comment] 2018-03-21 19:43
Fixed 7.3

**Closed by SeanAtr0n** 2018-03-21 19:43 UTC
