### ISSUE TITLE
Stockpile not there but accessible through linked storages

### ISSUE THREAD

**Issue by sagg** [StrangeLoopGames/EcoIssues#5352] opened 2018-03-03 23:19 UTC
i have three stockpiles side by side, but after connecting to the server the third is never there. i can use the items which that stockpile was holding like i put them manually there.
through the linked storages i have still access and everything feels fine.
the stockpile sometimes spawns if i use the workbench, but not always. i dont know what exactly triggers the spawning, it feels a bit random.

unfortunately i dont know how to reproduce this in some simple steps, but if you want i can give you the eco-file?

*edit*
the stockpile spawns if the inventory is changed through the linked storage.

**Comment by sagg** [comment] 2018-03-04 01:29
Cause it's a bit hard to describe here's the file. :)

[sagg's world.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1778066/sagg.s.world.zip)

Another thing: The waypoints are somehow located to the wrong direction.
Just go to the end of the way and turn around to the house. I would expect that the waypoint should be shown up, but instead it shows in the other direction and tells me that i have to go around the world. :D

**Comment by sagg** [comment] 2018-03-28 17:34
hmm, but it spawns correctly if the hold items are changed?
strange, but i'm also not able to reproduce it, i've never had this again. who know's, thanks anyways. :)

**Comment by metachronism** [comment] 2018-07-12 03:40
closing as dupe of stockpile duplication issue

**Closed by metachronism** 2018-07-12 03:40 UTC
Labels: Medium Priority
