### ISSUE TITLE
USER ISSUE: Dupe bug regarding server reopening

### ISSUE THREAD

**Issue by ejfdezrdgz** [StrangeLoopGames/EcoIssues#11045] opened 2019-02-02 16:59 UTC
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
1. Place Electric Stamping Press on the ground (in this case I placed it on top of a full brick room with floor and ceiling made of aqueduct brick)
2. Close server a bit after (not sure exactly how much time, but not even 30 seconds)
3. Reopen server

**Expected behavior:**
It should have either left the press on the ground or in the inventory (quickbar)

**Actual behavior:**
Instead it duplicated the entity and left one on the ground and the other in the inventory (quickbar)

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods, vanilla server. Steam version

**Comment by ejfdezrdgz** [comment] 2019-02-02 17:15
Just noticed that it also dupes the object in the crafting bench. So, in summary, three items: one in the inventory, one placed and one where the object is crafted. I guess the problem is about inventory changes and saves.

Also just reproduced the issue with a Blast Furnace. One on the inventory, one placed and one on the assembly.

**Comment by metachronism** [comment] 2019-02-04 19:46
this would require a large refactor/architecture change - normally server is not intended to be restarted so often, and closing server should use the 'exit' command to save correct state

**Comment by mirasrael** [comment] 2019-04-05 11:52
Pushed to 9.0 because really hard to reproduce (you should crash server) and it requires complete refactoring of existing save system.

**Comment by mirasrael** [comment] 2019-11-01 08:38
Should be fixed with new system. Please re-open if it will happen after 9.0 release.

**Closed by mirasrael** 2019-11-01 08:38 UTC
Labels: Fixed, Low Priority
