### ISSUE TITLE
Invisible Chat

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#6162] opened 2018-03-16 21:47 UTC
From the support queue:

The version of the game: 0.7.2.4 beta

Operating System: Windows 10
Processor model: AMD FX(tm)-6300 Six Core Processor
Graphics card model: GTX 1060
Amount of RAM: 16 GB DDR3

I have the provlem but exactly the same on other PCs.

since I have the problem on other PC, I suspect that it must be the account

I have no error messages

![image](https://user-images.githubusercontent.com/13459026/37546175-b8b123b4-290f-11e8-979a-032c5fa2b9a1.png)

![image](https://user-images.githubusercontent.com/13459026/37546191-c178dfd2-290f-11e8-95e4-3aaa7432d674.png)

![image](https://user-images.githubusercontent.com/13459026/37546239-ed57070a-290f-11e8-865d-a3eb2f693b3e.png)

**Comment by CobaltEcho** [comment] 2018-03-19 01:06
Bump.  Friend having the EXACT same issue.

His specs are:
Windows 8.1
GforceGTX960
AMD4300 3.8ghz
RAM 16gb DDR3

**Comment by MarjieAVolk** [comment] 2018-03-19 20:37
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4160

This has to do with special characters in your name.  Many foreign characters will be fixed in 7.3, but not all.

**Closed by MarjieAVolk** 2018-03-19 20:37 UTC
