### ISSUE TITLE
[0.8.0.5] Direct Transfer doesn't work, currency gets transferred but no currency is recieved

### ISSUE THREAD

**Issue by Noodalie** [StrangeLoopGames/EcoIssues#11559] opened 2019-03-03 21:46 UTC
When attempting to transfer currency via different accounts/bank accounts, the currency says it went through but you won't receive it.

[https://imgur.com/a/kVS2eST](url)

**Comment by D3nnis3n** [comment] 2019-03-03 21:57
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11501

**Closed by D3nnis3n** 2019-03-03 21:57 UTC
