### ISSUE TITLE
 [0.8.2.5 release-preview] The text in the "text" tab of Sign disappears

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12689] opened 2019-07-01 08:16 UTC
Step to reproduce:
- spawn Sign
![image](https://user-images.githubusercontent.com/45708377/60420443-6fb37900-9bf0-11e9-8c47-0af106625602.png)
- write some text on the sign and wait a couple of minutes or relog.
![image](https://user-images.githubusercontent.com/45708377/60420466-81951c00-9bf0-11e9-96e0-678fcfdd9a23.png)
- open the sign, select the text tab. It will be empty until you enter any character.
![image](https://user-images.githubusercontent.com/45708377/60420631-da64b480-9bf0-11e9-8408-00e54d5a3da4.png)

**Comment by D3nnis3n** [comment] 2019-07-01 16:26
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12588
Already persistent in the current patch, no regression.

**Closed by D3nnis3n** 2019-07-01 16:26 UTC
Labels: Medium Priority, QA, Regression
