### ISSUE TITLE
USER ISSUE: Removing residents deletes any tables they have in the residence

### ISSUE THREAD

**Issue by Landro3** [StrangeLoopGames/EcoIssues#22615] opened 2021-08-30 21:42 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Remove residents from property

**Expected behavior:**
removed residents and gave them their tables/beds/toilets back

**Actual behavior:**
the residents were removed and their tables/beds/toilets were deleted and not recoverable

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2021-08-31 09:50
The tables go to the void storage of the player, which the player can find by clicking on the Strange Loop Games icon in the bottom right, next to the map UI part to the left. I can't reproduce the issue you are having, are you sure the former residents checked their void storage?

**Comment by Landro3** [comment] 2021-08-31 10:53
That worked thank you so much

**Comment by Daniel-Magulado** [comment] 2021-08-31 11:02
Hi @Landro3 

Glad that worked for you. I'll go ahead and close this since the behavior here is by design and intended.
Do, however, not hesitate to write another bug report if you ever encounter anything unusual in-game.

Happy playing!

**Closed by Daniel-Magulado** 2021-08-31 11:02 UTC
Labels: Status: Needs Information
