### ISSUE TITLE
Client crash as soon as i try to connect to a server

### ISSUE THREAD

**Issue by xamber123** [StrangeLoopGames/EcoIssues#6539] opened 2018-03-27 17:01 UTC
The client just crashes, no error message or anything.

It crashes when:
I press join
Try to join a server to quickly before letting the client load the server list.
Try to join a server after waiting to long before joining a server.
Trying to join a server
Writing the wrong password into the server.
Also pressing stop while loading the server list.

And sometimes when i press continue. 

In order to work around this it's like goldie locks. I has to be just perfect.

**Comment by MarjieAVolk** [comment] 2018-03-28 19:21
That's very odd.  I am guessing you have a corrupt installation / configuration somehow.  Here are some suggestions:

* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* If none of those work, you might try nuking it all - Uninstall Eco, shut down Steam, delete the AppData folder, restart your computer, reinstall the game.

If this doesn't help you, could you send me your client error log?  It's called 'output_log.txt' and is in %APPDATA%\..\LocalLow\Strange Loop Games\ECO

**Comment by xamber123** [comment] 2018-03-31 11:38
Tried everything you wrote but no bueno.
I thought it was gone when i went from 7.2.5 to staging, but it didn't.

heres the output_log.txt
`Initialize engine version: 2017.4.0f1 (b5bd171ee9ba)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon R9 200 Series (ID=0x67b0)
    Vendor:   ATI
    VRAM:     4072 MB
    Driver:   22.19.677.257
Begin MonoManager ReloadAssembly
- Completed reload, in  0.088 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 4 worker threads for Enlighten.
  Thread -> id: 3468 -> priority: 1 
  Thread -> id: 4068 -> priority: 1 
  Thread -> id: 283c -> priority: 1 
  Thread -> id: 3ca0 -> priority: 1 
UnloadTime: 6.711171 ms
RPC lookup took: 6347.6859ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)`

**Comment by MarjieAVolk** [comment] 2018-04-02 23:12
Okay, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6821

We've realized now this is being seen by a handful of people, so we're increasing the priority.

**Closed by MarjieAVolk** 2018-04-02 23:12 UTC
Labels: Medium Priority
