### ISSUE TITLE
Master: Otter provide meat instead of carcas.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10723] opened 2019-01-17 19:20 UTC
In real life, otter skin used in many valuable products!

https://www.ebay.com/bhp/otter-fur

https://github.com/StrangeLoopGames/EcoIssues/issues/10615

**Comment by craig-jong** [comment] 2019-03-07 21:05
fixed in master

**Comment by Sobaton** [comment] 2019-03-30 16:46
Otter provide meat instead of carcas in 8.1.0 #61937788

**Comment by beastyn** [comment] 2019-05-02 08:54
@craig-jong I can collect two carcasses from one otter.

**Comment by SlayksWood** [comment] 2019-05-17 09:44
Can't reproduce in 0.8.2.0 staging-9-n. Seems fixed

**Closed by SlayksWood** 2019-05-17 09:44 UTC
Labels: Medium Priority
