### ISSUE TITLE
[7.7.0] Audio Options Listed under the Graphics tab

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8898] opened 2018-08-08 23:31 UTC
Most games I have played don't put Audio options in the Graphics section.
![windowed_mode](https://user-images.githubusercontent.com/35509188/43869665-8bb878e0-9b28-11e8-9d3b-2e19f5675fce.PNG)

**Comment by metachronism** [comment] 2018-08-09 21:35
dupe of existing bug

**Closed by metachronism** 2018-08-09 21:35 UTC
Labels: Medium Priority, suggestion
