### ISSUE TITLE
Fps not capping at 60 / using VSync

### ISSUE THREAD

**Issue by EvilKenevil** [StrangeLoopGames/EcoIssues#10328] opened 2018-12-14 18:23 UTC
**Changed number to 60, restarted game and it still is at over 100 FPS -- Steam client FPS counter, matches the Ingame FPS counter, so there is no variations between the 2 which could differ the results.**
![untitled](https://user-images.githubusercontent.com/38164448/50020246-4e30ce00-ffcd-11e8-9132-39679dfcf2a2.png)

**Comment by SeanAtr0n** [comment] 2018-12-17 23:40
works fine in master / 8.0... seems to have been caused by a 7.8 hotfix of some sort

**Comment by Spydarlee** [comment] 2019-07-10 14:00
Seems to be fixed now (on latest master).

**Closed by Spydarlee** 2019-07-10 14:00 UTC
Labels: Medium Priority, Not reproduced
