### ISSUE TITLE
Server Crash on Alpha 6.0 / Store Placement

### ISSUE THREAD

**Issue by excedra** [StrangeLoopGames/EcoIssues#2433] opened 2017-10-02 10:37 UTC
Hello,

i'm using a Dedicated Alpha 6.0 Server on Windows 10. 
When a User places a Store the Client disconnect with the following Message (Client and Server german):
"Caught exception: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt."

On the Serverside the Server Crashes with the following:
![servercrash](https://user-images.githubusercontent.com/923330/31073748-779ff2d4-a76d-11e7-834d-6a6229b473b8.PNG)

I have attached a Crashdump:
[Crash 10022102.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1348601/Crash.10022102.zip)

After the Crash, the Server must be restored from Backup, otherwise it won't start:
![servercrash_restart](https://user-images.githubusercontent.com/923330/31073890-488d0904-a76e-11e7-8811-860eff58d0f0.PNG)

I have attached a Crashdump after the restart of the Server:
[Crash 10023504.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1348613/Crash.10023504.zip)

**Comment by MarjieAVolk** [comment] 2017-10-04 22:21
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2427

**Closed by MarjieAVolk** 2017-10-04 22:21 UTC
