### ISSUE TITLE
invisible block placement

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1741] opened 2017-06-28 20:43 UTC
Happened to me after building for a while, there is a row of invis blocks i could pickup/remove
![image](https://user-images.githubusercontent.com/774628/27659219-853f2402-5c07-11e7-9751-73a953f246ba.png)

stuff that might be related in log:
System.ArgumentException: An element with the same key already exists in the dictionary.

  at System.Collections.Generic.Dictionary`2[BlockKey,ThreadSafeMeshCopy].Add (BlockKey key, .ThreadSafeMeshCopy value) [0x00000] in <filename unknown>:0 

  at CubeBuilder.GetEvaluatedMesh (.Block block, .ChunkRender chunk, Vector3i posLocal, BlockKey key) [0x00000] in <filename unknown>:0 

  at ChunkBuilder.Build (.ChunkRender chunk) [0x00000] in <filename unknown>:0 

  at ChunkRenderer.Build () [0x00000] in <filename unknown>:0 

  at ChunkRenderer+ChunkJobQueue.WorkerThreadProc () [0x00000] in <filename unknown>:0 

  at ChunkRenderer+ChunkJobQueue.<InitializeWorkerThreads>m__0 () [0x00000] in <filename unknown>:0 
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

NullReferenceException: Object reference not set to an instance of an object
  at BlockKey..ctor (.ChunkRender chunk, Vector3i posLocal, Int32 overrideMiddle) [0x00000] in <filename unknown>:0 
  at BlockCursor.UpdatePosition (Vector3i newTargetPos, Vector3i normal, Int32 placedBlockID, Boolean highlightTarget, Color highlightColor) [0x00000] in <filename unknown>:0 
  at InteractionManager.UpdateCursor () [0x00000] in <filename unknown>:0 
  at InteractionManager.Update () [0x00000] in <filename unknown>:0

**Comment by MarjieAVolk** [comment] 2017-08-15 17:12
I was going to say maybe this is a duplicate of StrangeLoopGames/EcoIssues#1812 but actually it's the opposite, isn't it?  Haha

**Comment by metachronism** [comment] 2017-09-26 23:25
fixed in pending pr

**Closed by metachronism** 2017-09-26 23:25 UTC
