### ISSUE TITLE
Browser Graphs Cause Server Lag

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7758] opened 2018-05-14 06:04 UTC
If  you enter a word ending with 'g' into the chat and then hit return and return to game it often registers as the "G" command key and opens the Graph window.  As the graph window is causing exceptional amounts of in-game lag that effects all in the gameno matter who has opened the graphs this is very hard on not just the player that typed but the whole server..  I have been suggesting as a work around that they rebind the graphs command to something other than the "G" key, a key that is not alphabetic at all or if they chose an alphabet key they choose one rarely found on the end of words

**Comment by MarjieAVolk** [comment] 2018-05-14 23:08
Partial duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3522

**Comment by metachronism** [comment] 2018-05-14 23:57
I think the world layers in GIF form also contribute to this.  over time these are huge and bottleneck the server bandwidth

**Comment by MarjieAVolk** [comment] 2018-05-15 00:52
Oh, and we also have this bug open already for laggy graphs: https://github.com/StrangeLoopGames/EcoIssues/issues/7373  So closing this.

**Closed by MarjieAVolk** 2018-05-15 00:52 UTC
Labels: Medium Priority
