### ISSUE TITLE
[0.9.0 staging-1461] Unable to move queues around in crafting tables

### ISSUE THREAD

**Issue by Zoneman81** [StrangeLoopGames/EcoIssues#15118] opened 2020-03-13 11:24 UTC
If you have more then 1 project queued in a crafting table, you cant move those projects around anymore.

**Comment by D3nnis3n** [comment] 2020-03-13 11:33
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14991

**Closed by D3nnis3n** 2020-03-13 11:33 UTC
