### ISSUE TITLE
[0.9.0.4 br-100] Store hints sometimes don't update properly

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18773] opened 2020-10-15 04:28 UTC
Today on Coast Redwood I noticed some of the tooltips / hints for the stores didn't update properly. For example, this one tells me one of the stores wants to buy some items while in reality it doesn't:

![image](https://user-images.githubusercontent.com/964559/96077054-a9e76f00-0e63-11eb-82c9-91edcdc38f63.png)

While this one doesn't say how many items I have in my inventory I can sell:

![image](https://user-images.githubusercontent.com/964559/96077087-be2b6c00-0e63-11eb-9049-93760f0c263b.png)

The thing is, they did display correctly most of the time, it's just that sometimes they are wrong, which is unfortunate.

**Comment by SlayksWood** [comment] 2020-10-15 12:01
Can't reproduce in 0.9.1 staging-1805. But it was a lot of changes in store. So will investigate.

**Comment by ThePiachu** [comment] 2020-10-15 19:29
Oh whops, did a wrong crop on the first screenshot:

![image](https://user-images.githubusercontent.com/964559/96176882-d4780d00-0ee1-11eb-98be-650bc6d0e038.png)

But yeah, not sure what might be causing it, my best guess would be a lengthy game session and a laggy server?

**Comment by TwixterZ** [comment] 2022-04-15 05:16
@ThePiachu With lot of changes to store for 9.5, this issue is no longer prevalent. Closing this as fixed.

**Closed by TwixterZ** 2022-04-15 05:16 UTC
Labels: Status: Investigate
