### ISSUE TITLE
USER ISSUE: Treasury placement box bugged

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#11465] opened 2019-02-23 05:39 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Place a treasure.  Part will phase through a wall.  There is also a 2 block section in front of the 3x3 foot print that is "part" of the treasury, even though nothing is there.

**Expected behavior:**
Treasury should fit in a 3x3 area, and not phase through walls

**Actual behavior:**
Doesn't fit properly.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Doesn't fit properly.
![image](https://user-images.githubusercontent.com/38095046/53282277-265f9400-36fb-11e9-90ec-bac7085d7b11.png)

**Comment by Hydrohawk** [comment] 2019-02-23 05:45
On further review, it appears that any part of the 3x3 part of the treasury phases through building materials.  The only part that doesn't is the two blocks "outside" the foot print.
![image](https://user-images.githubusercontent.com/38095046/53282304-953ced00-36fb-11e9-8cd0-34456f60bcb8.png)

Footprint looks as such:
X= Visible footprint
Y= "Actual" footprint
Front ->
XXX
XXX
XXXY
      Y

**Comment by elfl0rd** [comment] 2019-02-23 07:54
Duplicate of #11465

**Closed by elfl0rd** 2019-02-23 07:54 UTC
