### ISSUE TITLE
[9.2.4] Industrial elevator button range and other glitches

### ISSUE THREAD

**Issue by killerfrienddk** [StrangeLoopGames/EcoIssues#20713] opened 2021-02-23 14:07 UTC
It seems that the Industrial elevator has a problem with its range for the button, it seems like that it is using the wooden elevator range.

It also seems like there are some weird issues with the client-to-client visual and place where the elevator is some times it works and sometimes on their game it is a different place.

**Comment by SlayksWood** [comment] 2021-02-24 06:55
@killerfrienddk Thank you for the report. Can you describe second part more details? maybe provide video or screenshots. 
Also provide log file when it happens next time.  Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

buttons here #20713

**Comment by IcedForge** [comment] 2021-02-24 07:04
Thank you for reporting issues. Will close as this is a duplicate of #20158

**Closed by IcedForge** 2021-02-24 07:04 UTC
Labels: Status: Needs Information
