### ISSUE TITLE
7.2.0 Eco - Running

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#5631] opened 2018-03-07 23:39 UTC
When I quit the game or the game crashes, the game is still running according to steam even though I cannot find any Eco process in the task manager. Upon restarting steam and quitting the game again, it reliably is still running.

This would occasionally happen in previous versions also, only goes away after a system restart.

**Comment by MarjieAVolk** [comment] 2018-03-08 20:00
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4624

**Closed by MarjieAVolk** 2018-03-08 20:00 UTC
