### ISSUE TITLE
UI broken after skipping tutorial

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#9119] opened 2018-08-29 11:50 UTC
Reported through Kayako. Part of the user's UI was missing:
![ecoerror](https://user-images.githubusercontent.com/13459026/44785836-f0679b80-ab2d-11e8-85f6-a7ce680c9272.jpg)

**Comment by johnkslg** [comment] 2018-08-29 19:36
Walker, can you get a repro on this?
Alec can you get the save game from this user?

**Comment by BlazeGuy2** [comment] 2018-08-29 20:11
@GophTheGreat What version is this happening on?

**Comment by BlazeGuy2** [comment] 2018-08-30 18:16
Can't reproduce, bumping down priority until a case comes up.

**Comment by johnkslg** [comment] 2018-08-31 19:50
Probably fixed by Misasrael's changes, closing.

**Closed by johnkslg** 2018-08-31 19:50 UTC
Labels: Medium Priority
