### ISSUE TITLE
Elevator collision mesh not interacting with player. 0.8.1.0 beta release

### ISSUE THREAD

**Issue by ShawnDaGeek** [StrangeLoopGames/EcoIssues#11897] opened 2019-04-05 22:13 UTC
Server: 0.8.1.0 beta release ( windows 10 pro)
Client: 0.8.1.0 steam release ( windows 10 home)

Collision mesh on elevators are not interacting with players making it impossible to use or ride the elevator.  In addition to this, the call buttons stop working after a few minutes of being placed and replaced.
Reproduce: place a new, or replace existing elevator, board and try to go up or down. You will be left standing on collision mesh while the model continues its journey.

forum reference. https://ecoforum.strangeloopgames.com/topic/5405/8-1-0-elevator-seems-to-be-broken
Clip for reference. https://www.facebook.com/shawnsspace/videos/10157246808134577

**Comment by D3nnis3n** [comment] 2019-04-08 00:22
Duplicate of #11870

**Closed by D3nnis3n** 2019-04-08 00:22 UTC
