### ISSUE TITLE
User interaction - Research bench

### ISSUE THREAD

**Issue by TB1990** [StrangeLoopGames/EcoIssues#5642] opened 2018-03-08 01:31 UTC
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Value cannot be null.
Parameter name: item

Stack:
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

**Comment by MarjieAVolk** [comment] 2018-03-08 22:33
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Closed by MarjieAVolk** 2018-03-08 22:33 UTC
