### ISSUE TITLE
Sunflowers not highlighting anymore

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21646] opened 2021-04-29 17:15 UTC
![image](https://user-images.githubusercontent.com/3536496/116591605-db8dc800-a8d3-11eb-899a-f0524fa6b9a7.png)

**Comment by TwixterZ** [comment] 2021-05-03 04:44
Checked in 9.3.3 Release 219, highlight is working when viewed while holding interactable tools (machete, sickles, etc)

**Comment by IcedForge** [comment] 2021-05-06 12:39
Adding triage as this is one of these, should all things highlight? Or should it only highlight when having a tool appropriate for the interaction with the object?

I am in favor of the last one but i can accept a "If holding tool = only correct object will highlight" So if im holding a shovel, i shouldnt be able to highlight anything other then what the shovel can work with. 

This way you could examine everything and see what they are which i assume is @johnkslg concern here?

**Comment by SlayksWood** [comment] 2021-05-06 12:50
no, highlight all is a bad idea. For example, Try to use road tool to any block with plant which you can pick up with E. So I guess it works as intended now.

**Comment by IcedForge** [comment] 2021-05-06 13:29
Closing as somewhat duplicate of #21073

**Closed by IcedForge** 2021-05-06 13:29 UTC
Labels: Status: Needs Triage
