### ISSUE TITLE
USER ISSUE: Crash when unclaiming

### ISSUE THREAD

**Issue by carsonbarlow** [StrangeLoopGames/EcoIssues#8550] opened 2018-07-16 05:44 UTC
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
claim some ground.
put a store in it (may need to have it in a building).
unclaim property.

**Expected behavior:**
not crash

**Actual behavior:**
It crashed

**Comment by Voosle** [comment] 2018-07-16 18:09
similar to #8549 ?

**Comment by MarjieAVolk** [comment] 2018-07-16 18:35
Hm, well I've been trying all kinds of things, and I can't get this to happen.  Do you have any crash or log files from this crash?  If you are playing a local game, they are mostly likely at '[...]\steamapps\common\Eco\Dump'.

**Comment by MarjieAVolk** [comment] 2018-07-16 20:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8549 for now.  Got a couple reports with the same trace as that one at this point

**Closed by MarjieAVolk** 2018-07-16 20:05 UTC
Labels: Critical Priority
