### ISSUE TITLE
[7.7.0] Changing Resolution from menu doesn't actually change the ingame screen resolution for windowed mode

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8993] opened 2018-08-17 18:29 UTC
Can't change if from 1920x1080 in the menu, can only do so manually.

Edit: only occurs in windowed mode

**Comment by metachronism** [comment] 2018-08-17 18:41
seems to work for me

**Comment by metachronism** [comment] 2018-08-17 18:44
unless you mean when in windowed mode only

**Comment by BlazeGuy2** [comment] 2018-08-17 18:44
Yeah, windowed only.  My b, shoulda mentioned that.

**Comment by Nanders** [comment] 2018-08-20 18:03
I'm closing this as intended behavior

**Closed by Nanders** 2018-08-20 18:03 UTC
Labels: Medium Priority
