### ISSUE TITLE
USER ISSUE: slow

### ISSUE THREAD

**Issue by Goddessa39** [StrangeLoopGames/EcoIssues#12144] opened 2019-05-01 17:51 UTC
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
been trying to play this game all day. 12fps.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by D3nnis3n** [comment] 2019-05-01 18:50
Duplicate of #11118

**Closed by D3nnis3n** 2019-05-01 18:50 UTC
