### ISSUE TITLE
5.6.2-5e0d162a out of memory after about 6 hours running

### ISSUE THREAD

**Issue by egburr** [StrangeLoopGames/EcoIssues#1810] opened 2017-07-20 01:56 UTC
Migrated world from 5.6.1 and played for about an hour, then logged off. A little over 6 hours after initial start, the server crashed with "System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown."

dump and game.eco on google drive at
https://drive.google.com/open?id=0By3yTnmDe0ulNnVnRXRES3BNbVE

**Comment by egburr** [comment] 2017-07-20 14:15
Another "out of memory" crash after about only 3 hours of running, in the middle of the night with no users logged on. dump placed in the above google drive location.

**Comment by Amphysbaenas** [comment] 2017-07-24 14:46
i confirm that "out of memory" crash after 10 min server running on a local test. Something goes wrong but what ....?

**Comment by metachronism** [comment] 2017-08-15 22:29
closing as dupe of other OOM issues which have been resolved

**Closed by metachronism** 2017-08-15 22:29 UTC
