### ISSUE TITLE
USER ISSUE: Unable to interact with objects

### ISSUE THREAD

**Issue by SkulReaper1916** [StrangeLoopGames/EcoIssues#23052] opened 2022-03-17 01:52 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
Intermittent, occurs increasingly more often the longer I play. Restarting the game fixes it. 

**Expected behavior:**
Doors should have open/close functionality and textstockpiles should have the option to open/interactgreen object high-light should show up when cross hair is over the objects

**Actual behavior:**
Intermittently will stop having the green box and player becomes unable to interact with the objects. Reboot fixes issue.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8279928/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8279929/Player-prev.log)

**Comment by Formdude** [comment] 2022-04-03 19:35
Duplicate of #20414?

**Comment by D3nnis3n** [comment] 2022-05-02 11:17
Yep.

**Closed by D3nnis3n** 2022-05-02 11:17 UTC
