### ISSUE TITLE
Alpha.6 [d9d6f47c] Torch should not be usable in water

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2322] opened 2017-09-27 15:26 UTC
![image](https://user-images.githubusercontent.com/1900106/30922266-e955b13e-a3a8-11e7-87ab-b47dff843f85.png)

**Comment by keegan-o** [comment] 2017-09-28 18:44
Duplicate of eric's 'torches should not be magical'.

**Closed by keegan-o** 2017-09-28 18:44 UTC
Labels: Enhancement
