### ISSUE TITLE
USER ISSUE: interactables are invisible and unusable

### ISSUE THREAD

**Issue by NotKais** [StrangeLoopGames/EcoIssues#23677] opened 2023-01-22 05:47 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.7 beta release-431

**Steps to Reproduce:**
Unclear, happens at random and restarting the game will sometimes fix and sometimes cause other interactables to disappear.

**Expected behavior:**
All placed interactables should be visible and usable.

**Actual behavior:**
Different interactables will disappear at random and become unusable.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-01-22 11:38
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23132 and similar

**Closed by D3nnis3n** 2023-01-22 11:38 UTC
