### ISSUE TITLE
 System.InvalidOperationException: Cannot Convert Argument Type: Eco.Gameplay.Settlements.Settlement to BSON.

### ISSUE THREAD

**Issue by Arranoa-jolasten** [StrangeLoopGames/EcoIssues#25069] opened 2024-08-18 18:51 UTC
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot Convert Argument Type: Eco.Gameplay.Settlements.Settlement to BSON.

 ---> System.Exception: Error during packaging property 'Leader' of 'Eco.Gameplay.Settlements.Settlement'
 ---> System.Exception: Error during packaging property 'ElectionProcess' of 'Eco.Gameplay.Civics.Titles.ElectedTitle'
 ---> System.Exception: Error during packaging property 'Voters' of 'Eco.Gameplay.Civics.ElectionProcess'
 ---> System.Exception: Error during packaging property 'BackupOwner' of 'Eco.Gameplay.Civics.Demographics.Demographic'
 ---> System.Exception: Error during packaging property 'UserSet' of 'Eco.Gameplay.Civics.Demographics.Demographic'
 ---> System.Exception: Error during packaging property 'HomesteadDeed' of 'Eco.Gameplay.Players.User'
 ---> System.Exception: Error during packaging property 'Ownables' of 'Eco.Gameplay.Property.Deed'
 ---> System.Exception: Error during packaging property 'IsAuthorized' of 'Eco.Gameplay.Property.PropertyPlot'
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method63700(Closure, IMvcNetClient, Object)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   --- End of inner exception stack trace ---
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   at Eco.Core.Controller.ControllerPacker.PackageViewWithMembers(IController controller, BsonSerializationContext& context, IControllerMarshaler marshaler, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.PackageView(IController controller, BsonSerializationContext& context, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.SyncController(IMvcNetClient mvcClient, IController controller, BsonSerializationContext& context, ControllerBoundingLevel requiredSyncLevel)
   at Eco.Core.Controller.ControllerPacker.PackageControllerRecursivelyAndCollectPendingViews(IController controller, BsonSerializationContext& context, PackageFlags flags)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, BsonSerializationContext& context, Boolean useReflection)
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, BsonSerializationContext& context, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, BsonSerializationContext& context, Boolean useReflection)
   at Eco.Core.Controller.BlobController.PackageValue(BsonSerializationContext& context, Object value, Int32 nameID, Boolean clientShouldCacheIt, ControllerPackingPendingViews pendingData)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   --- End of inner exception stack trace ---
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   at Eco.Core.Controller.ControllerPacker.PackageViewWithMembers(IController controller, BsonSerializationContext& context, IControllerMarshaler marshaler, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.PackageView(IController controller, BsonSerializationContext& context, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.SyncController(IMvcNetClient mvcClient, IController controller, BsonSerializationContext& context, ControllerBoundingLevel requiredSyncLevel)
   at Eco.Core.Controller.ControllerPacker.PackageControllerRecursivelyAndCollectPendingViews(IController controller, BsonSerializationContext& context, PackageFlags flags)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, BsonSerializationContext& context, Boolean useReflection)
   at Eco.Core.Controller.BlobController.PackageValue(BsonSerializationContext& context, Object value, Int32 nameID, Boolean clientShouldCacheIt, ControllerPackingPendingViews pendingData)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   --- End of inner exception stack trace ---
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   at Eco.Core.Controller.ControllerPacker.PackageViewWithMembers(IController controller, BsonSerializationContext& context, IControllerMarshaler marshaler, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.PackageView(IController controller, BsonSerializationContext& context, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.SyncController(IMvcNetClient mvcClient, IController controller, BsonSerializationContext& context, ControllerBoundingLevel requiredSyncLevel)
   at Eco.Core.Controller.ControllerPacker.PackageControllerRecursivelyAndCollectPendingViews(IController controller, BsonSerializationContext& context, PackageFlags flags)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, BsonSerializationContext& context, Boolean useReflection)
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, BsonSerializationContext& context, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, BsonSerializationContext& context, Boolean useReflection)
   at Eco.Core.Controller.BlobController.PackageValue(BsonSerializationContext& context, Object value, Int32 nameID, Boolean clientShouldCacheIt, ControllerPackingPendingViews pendingData)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   --- End of inner exception stack trace ---
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   at Eco.Core.Controller.ControllerPacker.PackageViewWithMembers(IController controller, BsonSerializationContext& context, IControllerMarshaler marshaler, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.PackageView(IController controller, BsonSerializationContext& context, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.SyncController(IMvcNetClient mvcClient, IController controller, BsonSerializationContext& context, ControllerBoundingLevel requiredSyncLevel)
   at Eco.Core.Controller.ControllerPacker.PackageControllerRecursivelyAndCollectPendingViews(IController controller, BsonSerializationContext& context, PackageFlags flags)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, BsonSerializationContext& context, Boolean useReflection)
   at Eco.Core.Controller.BlobController.PackageValue(BsonSerializationContext& context, Object value, Int32 nameID, Boolean clientShouldCacheIt, ControllerPackingPendingViews pendingData)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   --- End of inner exception stack trace ---
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   at Eco.Core.Controller.ControllerPacker.PackageViewWithMembers(IController controller, BsonSerializationContext& context, IControllerMarshaler marshaler, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.PackageView(IController controller, BsonSerializationContext& context, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.SyncController(IMvcNetClient mvcClient, IController controller, BsonSerializationContext& context, ControllerBoundingLevel requiredSyncLevel)
   at Eco.Core.Controller.ControllerPacker.PackageControllerRecursivelyAndCollectPendingViews(IController controller, BsonSerializationContext& context, PackageFlags flags)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, BsonSerializationContext& context, Boolean useReflection)
   at Eco.Core.Controller.BlobController.PackageValue(BsonSerializationContext& context, Object value, Int32 nameID, Boolean clientShouldCacheIt, ControllerPackingPendingViews pendingData)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   --- End of inner exception stack trace ---
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   at Eco.Core.Controller.ControllerPacker.PackageViewWithMembers(IController controller, BsonSerializationContext& context, IControllerMarshaler marshaler, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.PackageView(IController controller, BsonSerializationContext& context, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.SyncController(IMvcNetClient mvcClient, IController controller, BsonSerializationContext& context, ControllerBoundingLevel requiredSyncLevel)
   at Eco.Core.Controller.ControllerPacker.PackageControllerRecursivelyAndCollectPendingViews(IController controller, BsonSerializationContext& context, PackageFlags flags)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, BsonSerializationContext& context, Boolean useReflection)
   at Eco.Core.Controller.BlobController.PackageValue(BsonSerializationContext& context, Object value, Int32 nameID, Boolean clientShouldCacheIt, ControllerPackingPendingViews pendingData)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   --- End of inner exception stack trace ---
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   at Eco.Core.Controller.ControllerPacker.PackageViewWithMembers(IController controller, BsonSerializationContext& context, IControllerMarshaler marshaler, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.PackageView(IController controller, BsonSerializationContext& context, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.SyncController(IMvcNetClient mvcClient, IController controller, BsonSerializationContext& context, ControllerBoundingLevel requiredSyncLevel)
   at Eco.Core.Controller.ControllerPacker.PackageControllerRecursivelyAndCollectPendingViews(IController controller, BsonSerializationContext& context, PackageFlags flags)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, BsonSerializationContext& context, Boolean useReflection)
   at Eco.Core.Controller.BlobController.PackageValue(BsonSerializationContext& context, Object value, Int32 nameID, Boolean clientShouldCacheIt, ControllerPackingPendingViews pendingData)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   --- End of inner exception stack trace ---
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
   at Eco.Core.Controller.ControllerPacker.PackageViewWithMembers(IController controller, BsonSerializationContext& context, IControllerMarshaler marshaler, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.PackageView(IController controller, BsonSerializationContext& context, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
   at Eco.Core.Controller.ControllerPacker.SyncController(IMvcNetClient mvcClient, IController controller, BsonSerializationContext& context, ControllerBoundingLevel requiredSyncLevel)
   at Eco.Core.Controller.ControllerPacker.PackageControllerRecursivelyAndCollectPendingViews(IController controller, BsonSerializationContext& context, PackageFlags flags)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, BsonSerializationContext& context, Boolean useReflection)
   at Eco.Shared.Serialization.BsonManipulator.EncodeArgs(INetClient client, Object[] args)
   --- End of inner exception stack trace ---
   at Eco.Shared.Serialization.BsonManipulator.EncodeArgs(INetClient client, Object[] args)
   at Eco.Shared.Networking.RPCEvent..ctor(String methodName, INetObject obj, INetClient target, Object[] args)
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.SetClaimMode(Player player)
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.OnSelected(Player player)
   at Eco.Gameplay.Items.SelectionInventory.UpdateItemSelectionActions(Player player, Item selectedItem)
   at Eco.Gameplay.Items.UserInventory.Validate()
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client, Boolean allowDisconnectionAfterActionFailure, Boolean ignoreTestMode)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)
   at InvokeStub_Client.SpawnPlayer(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Shared.Networking.RPCManager.Invoke(INetClient client, RPCInvocation invocation, Boolean notifyOnPermissionFail)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodName)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONValue bsonValue)
   at Eco.Plugins.Networking.Client.<.ctor>b__86_4(): 2

**Comment by D3nnis3n** [comment] 2024-08-18 20:17
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25063

**Closed by D3nnis3n** 2024-08-18 20:17 UTC
