### ISSUE TITLE
USER ISSUE: Picked up a log and crashed

### ISSUE THREAD

**Issue by kasildun** [StrangeLoopGames/EcoIssues#5201] opened 2018-02-27 23:15 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Pick up an existing log

**Expected behavior:**
Should go to carried items

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-28 19:55
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-28 19:55 UTC
