### ISSUE TITLE
[0.9.3.4 beta release] User report : Issue with connecting to local server via client hosting.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21899] opened 2021-05-17 12:41 UTC
User report about issue with being stuck at "connecting/Loading" screen when trying to load/create/host a local server from inside the game meny

Tried starting up both the 32 bit and 64 bit servers and they worked fine he could start it, and connect via "localhost" from inside the game.

[Player.log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6493797/Player.log.txt)
[log_210517011631.log-1.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6493798/log_210517011631.log-1.txt)

**Comment by mirasrael** [comment] 2021-05-18 12:00
Looks like problem with:
```
[01:18:31.468] [10] [Error] [Eco] Error when verifying login token: The operation has timed out.
```
May be auth server availability problems?

**Comment by WeaselDog** [comment] 2021-07-03 06:15
Closing as not reproduced

**Closed by WeaselDog** 2021-07-03 06:15 UTC
Labels: Category: Tech, Priority: Critical, Squad: Pumpkin, Type: Bug
