### ISSUE TITLE
Rubin

### ISSUE THREAD

**Issue by Rubin0049** [StrangeLoopGames/EcoIssues#24856] opened 2024-04-01 07:33 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-04-01 16:25
What is the range of your computers public IP? Need first and second field, e.g. 123.123.X.X.
Please post in issue https://github.com/StrangeLoopGames/EcoIssues/issues/24850, which this is a duplicate of.

**Closed by D3nnis3n** 2024-04-01 16:25 UTC
