### ISSUE TITLE
Alt+z not hide player nicknames

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14189] opened 2019-12-19 18:37 UTC
![20191219213349_1](https://user-images.githubusercontent.com/4980243/71199746-a87f0180-22a7-11ea-8c41-946502d3db39.jpg)
also...
https://github.com/StrangeLoopGames/EcoSuggestions/issues/931

p.s.
please stop silently moving tickets.

**Comment by D3nnis3n** [comment] 2019-12-20 00:10
No idea who moved it, but it actually is a suggestion for a improvement. We have /record for getting rid of everything and i see how this wouldnt fit if you want to be on the same screenshot, but this is merely a improvement, not an issue, so i'm closing this out as a duplicate of the mention Suggestion 931.

**Closed by D3nnis3n** 2019-12-20 00:10 UTC
