### ISSUE TITLE
9.2.4 Constant Server Crashes on start

### ISSUE THREAD

**Issue by Grimreepr** [StrangeLoopGames/EcoIssues#21233] opened 2021-04-03 05:27 UTC
Everyone was playing just fine, then the server started crashing on restart.  Now it wont run at all an generates a load of red text (see attached Image)
![Crash Report](https://user-images.githubusercontent.com/30789991/113469481-0424be00-940b-11eb-9884-629dd423c493.png)

**Comment by IcedForge** [comment] 2021-04-10 13:06
Thank you for reporting this, seems like it was caused by a executive action article that was passed initially, could you fill in a bit on what transpired up to this ? was there any specific laws or civic objects being voted on ?

Also please provide the save file if possible ( google drive, dropbox or such ) or send this directly to jens@strangeloopgames.com

**Comment by IcedForge** [comment] 2021-05-04 14:12
Will close this issue as there were never a follow up information. Please reopen if you still have problems with this after update 9.3 and add in the requested information.

**Closed by IcedForge** 2021-05-04 14:12 UTC
Labels: Status: Needs Information
