### ISSUE TITLE
USER ISSUE: My House Interior changed to a "Red Room". World/Biome Problem.

### ISSUE THREAD

**Issue by StahlhelmTV** [StrangeLoopGames/EcoIssues#11372] opened 2019-02-17 13:51 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
I will post a setting down below and if needed a Save file to see the Problem because i got more problems with this world!

**Expected behavior:**
Normaly there should be a nice Light room. And a flawless world.

**Actual behavior:**
Room is almost completly red and sometimes glows like hell. There is a Cut/Edge and when i go over it the world sometimes begins to reset the Shadows so everything is black for a second and then the crane is disappearing.

**Do you have mods installed?** 
No only the "mods" from the game itself.

**Does issue happen when no mods are installed?:**
Idk i only have as said the Standart Mods.

**Attachments**
![settings](https://user-images.githubusercontent.com/47715580/52913599-ccf10280-32bf-11e9-9096-5d6ae8ea6be5.jpg)
![interior](https://user-images.githubusercontent.com/47715580/52913605-e2662c80-32bf-11e9-9039-406c4456f41b.jpg)
Video of World Bug: https://vimeo.com/317792907

**World Files**
http://www.mediafire.com/file/dw6dfhhra6wsh4a/World.zip/file

**My Rig**
CPU: Intel Core i7-3770K
Mainboard: ASUS P8Z77-V LX
RAM: Kingston 4x4GB DDR3
GPU: AMD Radeon Rog Strix Rx 580 O8G

**Comment by elfl0rd** [comment] 2019-02-17 13:52
disable global illumination, or selest highter preset.

**Comment by StahlhelmTV** [comment] 2019-02-17 13:54
> disable global illumination, or selest highter preset.

Ill try that Thanks.

**Comment by gjsmo** [comment] 2019-02-17 14:30
Duplicate of #11270 that I posted a few days ago. 

> disable global illumination, or selest highter preset.

This also happens with the highest global illumination setting.

**Comment by D3nnis3n** [comment] 2019-03-12 13:30
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11270

**Closed by D3nnis3n** 2019-03-12 13:30 UTC
