### ISSUE TITLE
Water doesn't pool

### ISSUE THREAD

**Issue by freschmeet** [StrangeLoopGames/EcoIssues#6664] opened 2018-03-29 14:16 UTC
Detailed Description of Issue:
I spent a few hours building a dam to create a lake, but the water does not pool properly. I've checked every square yard/meter/foot/block of surface within the "lake" I had hoped to build, and there are no empty spaces for water to escape, so I cannot understand why the water is not pooling.

Reproducible? How difficult is it to reproduce?
Simple to reproduce - try to make a pond or lake. It doesn't work.

Steps to reproduce bug/issue:
Find flowing water source. Build dam. Water keeps flowing through it.

Additional Comments:
Is this intended performance? I noticed a post elsewhere that "Since BETA 7.2 the functionality of aqueducts has been disabled for performance reasons. Currently, there is no way for the player to influence the moisture value of a ground block." - does this limitation also restrict the manipulation of water in the world?

Server, Client or Website?
Server name "End of the chicken!"

OS/Web Browser?
Windows 10 Professional

Client Version? [Alpha .01 for example]
BETA 7.3.0

**Comment by MarjieAVolk** [comment] 2018-03-30 00:05
Water doesn't really flow right now.  The main way that you can get more water is by using Aqueducts.  You can place bricks as aqueducts using the hammer.  It's possible that lining your lake with aqueducts would work, but you didn't hear it from me :P

Closing as working as intended.  Maybe someday we will have more dynamic water.

**Closed by MarjieAVolk** 2018-03-30 00:05 UTC
