### ISSUE TITLE
Door issue on loading allowing players to go trough them 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#961] opened 2017-01-03 22:10 UTC
http://ecoforum.strangeloopgames.com/topic/1256/5-1-players-able-to-go-through-doors

**Comment by MarjieAVolk** [comment] 2017-03-22 18:56
Closing as a duplicate of StrangeLoopGames/EcoIssues#894

**Closed by MarjieAVolk** 2017-03-22 18:56 UTC
