### ISSUE TITLE
0.8.0.7 Trees can grow on top of stockpiles filled with dirt.

### ISSUE THREAD

**Issue by espoire** [StrangeLoopGames/EcoIssues#11680] opened 2019-03-15 03:24 UTC
When a stockpile has been filled with dirt, trees (and other wild plants) can appear on them following the usual logic for new trees growing naturally. If you then remove the dirt from the stockpile, you will be left with a tree floating in midair.

![image](https://user-images.githubusercontent.com/16272456/54406365-d9daf900-46a7-11e9-808e-a485b304e525.png)

Ideally, either plants should be forbidden from growing on stockpiles, or you should be forbidden from removing the dirt while something is living on it.

**Comment by D3nnis3n** [comment] 2019-03-15 15:10
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6902

**Closed by D3nnis3n** 2019-03-15 15:10 UTC
