### ISSUE TITLE
USER ISSUE: Selling/Buying a lot in a Store lags the Server

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11607] opened 2019-03-08 11:40 UTC
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
Have something in bulk like 1000 wheat
sell it to someone buying Wheat

**Expected behavior:**
it sells the 10x 100 stacks as a whole stack

**Actual behavior:**
seems like it sells every item one by one causing the server to lag that hard that the red connection warning pops up.

**Do you have mods installed? Does issue happen when no mods are installed?:**
none

**Comment by redwyre** [comment] 2019-03-08 13:07
Duplicate of #11585

**Closed by redwyre** 2019-03-08 13:07 UTC
