### ISSUE TITLE
USER ISSUE: plants can grow on dirt in stockpile

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7611] opened 2018-05-07 21:04 UTC
Version: 0.7.5.0 beta staging-7be2f02c
![20180507230241_1](https://user-images.githubusercontent.com/4980243/39725107-6dbc2684-5253-11e8-8665-a45e6ce33288.jpg)

**Comment by metachronism** [comment] 2018-07-12 04:00
dupe of even older #5193

**Closed** 2019-04-10 09:43 UTC
Labels: Medium Priority
