### ISSUE TITLE
USER ISSUE: Random World Generation 

### ISSUE THREAD

**Issue by IronWolf666** [StrangeLoopGames/EcoIssues#24240] opened 2023-12-16 17:09 UTC
\
**User Id: (slg107025)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
Click on Host a World and make a mark on Generate Random Landscape and then start.

**Expected behavior:**
The Game should  start and create a random Landscape.

**Actual behavior:**
It doesn't start at all and It doesn't create a file in the storage folder or a log

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Comment by D3nnis3n** [comment] 2023-12-16 22:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24229

**Closed by D3nnis3n** 2023-12-16 22:22 UTC
