### ISSUE TITLE
Exception when updating object SteamTractorObject: Sequence contains no elements

### ISSUE THREAD

**Issue by TheeJudge** [StrangeLoopGames/EcoIssues#8783] opened 2018-07-28 14:46 UTC
Looking at the server console. The message in the title pops up several times. At one point I got 5 of these exceptions a sec. for about 30 min.

I figured it should be something to look into to prevent future errors/crashes.

**Comment by craig-jong** [comment] 2018-08-16 17:44
I can't reproduce this, so I'm going to downgrade it. Still respond if you have more info, but I'll take a deeper look later on.

**Comment by konstantin90s** [comment] 2019-02-17 17:21
Met this problem now on 0.8.0.2 and 0.8.0.3 (haven't had this world and tractor before)
When steam tractor with sower attached at first I got this in the log
[02:15:31.835] [73] [ Info] [Eco] Exception when updating object SteamTractorObject: Object reference not set to an instance of an object.
   at Eco.Mods.TechTree.SteamTractorHarvesterItem.BlockInteraction(Vector3i pos, Quaternion rot, VehicleComponent vehicle, Inventory inv)
   at Eco.Gameplay.Components.ModularVehicleComponent.OnVehicleMoved()
   at Eco.Gameplay.Components.VehicleComponent.ReceiveUpdate(BSONObject bsonObj)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.ReceiveUpdate(BSONObject bsonObj)
   at Eco.Shared.Networking.NetObjectManager.UpdateObjects(BSONObject bsonRoot)

and then every time you move a tractor log is flooded with exact same exception
[02:24:04.956] [73] [ Info] [Eco] Exception when updating object SteamTractorObject: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Mods.TechTree.SteamTractorSowerItem.BlockInteraction(Vector3i pos, Quaternion rot, VehicleComponent vehicle, Inventory inv)
   at Eco.Gameplay.Components.ModularVehicleComponent.OnVehicleMoved()
   at Eco.Gameplay.Components.VehicleComponent.ReceiveUpdate(BSONObject bsonObj)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.ReceiveUpdate(BSONObject bsonObj)
   at Eco.Shared.Networking.NetObjectManager.UpdateObjects(BSONObject bsonRoot)

We tried to remove this tractor into inventory and place it again after this server seem to have entered half-crashed state and when you try to move this tractor red "disconnected" icon appears and after reconnection tractor stays in the same spot I placed it.

https://drive.google.com/open?id=1ouWvZlh4y6tIfzpIGNmcwq2QtM-AQz43 here's the world with this tractor if it helps to diagnose
https://drive.google.com/open?id=1EbAKnYPLE77UKU1u0At8UyVJDicezrDn config files except network (default), actually everything that might be changed is world size and world tick cpu max set to 0,75 and parallel world object ticks enabled

**Comment by D3nnis3n** [comment] 2019-02-20 14:19
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11422

**Closed by D3nnis3n** 2019-02-20 14:19 UTC
Labels: Medium Priority
