### ISSUE TITLE
Mousing over match score should popup a table showing how it was calculated. 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20552] opened 2021-02-15 01:13 UTC
![image](https://user-images.githubusercontent.com/3536496/107895349-e0072f00-6ee7-11eb-8fe5-a272540d12c2.png)

**Comment by WeaselDog** [comment] 2021-02-16 06:48
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19477

**Closed by WeaselDog** 2021-02-16 06:48 UTC
