### ISSUE TITLE
USER ISSUE: On taking wood

### ISSUE THREAD

**Issue by kingwithou** [StrangeLoopGames/EcoIssues#4237] opened 2018-02-10 11:28 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Trying to take log

**Expected behavior:**
get it in my hand

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment] 2018-02-13 05:26
This sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3668.  Was this a log you had just chopped down, or one that you found on the ground?  Did you also see floating logs?

**Comment by MarjieAVolk** [comment] 2018-02-13 23:23
Going to close this as a duplicate of #3668 until I learn differently :)

**Closed by MarjieAVolk** 2018-02-13 23:23 UTC
