### ISSUE TITLE
USER ISSUE: Research Table missing resources bug.

### ISSUE THREAD

**Issue by TopSecretPorkChop** [StrangeLoopGames/EcoIssues#4046] opened 2018-02-07 16:51 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
Create multiple projects at a research table.  Cycle through projects by clicking on the icon at the bottom of the interface.

**Expected behavior:**
The correct missing requirements should be displayed on the research progress bar.

**Actual behavior:**
Some missing requirements from the research which was displayed prior to switching focus are still displayed on the bar as needed for the new focused research.  E.g. switching from Smelting to Butchery can make it seem that Iron ore is required to complete the Butchery research.

**Comment by Nanders** [comment] 2018-02-07 18:17
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3953

**Closed by Nanders** 2018-02-07 18:17 UTC

**Comment by MarjieAVolk** [comment] 2018-02-07 22:32
This will be fixed in the next hotfix :)
