### ISSUE TITLE
Using the hoe does not level up farming skill

### ISSUE THREAD

**Issue by Ramh5** [StrangeLoopGames/EcoIssues#11986] opened 2019-04-11 17:32 UTC
Contrary to the description of the Farming skill, using the hoe does not give any exp to the skill

**Comment by D3nnis3n** [comment] 2019-12-09 20:58
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/13030

**Closed by D3nnis3n** 2019-12-09 20:58 UTC
Labels: Medium Priority, QA
