### ISSUE TITLE
Excavator and Loader 8.0.7

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoIssues#11690] opened 2019-03-15 20:39 UTC
1.On my server noticed that the excavator and loader poorly collects ore and stone.
In my opinion, the ore and stone become motionless and the bucket of the excavator does not see it.
2.When you stand next to it, the excavator does not make sounds engine.
3.Grass does not disappear

**Comment by D3nnis3n** [comment] 2019-03-16 10:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11654
The others are also duplicates.

**Closed by D3nnis3n** 2019-03-16 10:22 UTC
