### ISSUE TITLE
[7.4.0 #518a927f]   Filter looses settings when in game or leaving server

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7526] opened 2018-05-01 09:45 UTC
Browser filter set:
[![Screenshot from Gyazo](https://gyazo.com/0f976c8e7fbb62297b1a80e054548d23/raw)](https://gyazo.com/0f976c8e7fbb62297b1a80e054548d23)

Browser settings after returning to main menu after being in game:

[![Screenshot from Gyazo](https://gyazo.com/4b7c8e14d8bc1f38a331d0afb1f990e8/raw)](https://gyazo.com/4b7c8e14d8bc1f38a331d0afb1f990e8)

**Comment by MarjieAVolk** [comment] 2018-05-07 21:38
Yes the filters all reset every time you leave the browser window.  I wasn't really sure what people would want, so I had decided to have it this way to prevent people from applying a weird filter and then getting stuck with nothing in their browser forever.

**Comment by MarjieAVolk** [comment] 2018-08-09 00:03
Closing as 'working as intended'

**Closed by MarjieAVolk** 2018-08-09 00:03 UTC
Labels: Medium Priority
