### ISSUE TITLE
Inconsistent Search Functionality in Storage

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#25234] opened 2024-11-01 20:05 UTC
Inconsistent Search Functionality in Storage Tabs

Description:
The search functionality within storage tabs sometimes fails to return expected results for specific items, such as Small Hang Signs. This issue appears intermittently and has been observed primarily with the Masonry Table.

Steps to Reproduce:

Open the Masonry Table and select the Storage tab.

Type "SMALL" in the search bar to locate items like Small Hang Signs.

Notice that no results are displayed, even though the item should be available for selection.

Screenshot of issue in Masonry Table:

![image](https://github.com/user-attachments/assets/b628215c-e77f-49ec-8b9c-7f25f15d353a)

Repeat the search in a different workstation, such as the Tool Bench.

Screenshot of working search in Tool Bench:

![image](https://github.com/user-attachments/assets/ef47fb8b-5347-4f09-a5ac-2769da52902f)

Additional Observations:

When the search feature functions correctly (e.g., in the Tool Bench), a specific "item stacking" sound effect plays.
When the search does not work (as in the Masonry Table), only a single "beep" sound is heard when pressing E, with no item-related audio feedback.
Expected Behavior:
The search in the Storage tab should reliably display relevant items based on typed search terms across all workstations, providing consistent functionality.

Note:
The issue is intermittent and doesn’t consistently fail, which complicates replication. The differing sound effects might indicate an underlying issue affecting the storage search function in some instances.

This is happening in GIANT PANDA.

**Comment by Crazy-Spy** [comment] 2024-11-02 12:05
Additional Information: If we conduct a search, leave text in the search field, then close the stockpile and go do something else, when we return to the stockpile, the text remains in the search field, but the search functionality no longer works.

**Comment by D3nnis3n** [comment] 2024-11-02 12:10
Likely duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25230

**Comment by D3nnis3n** [comment] 2024-11-04 03:12
We're pretty sure it's the same issue, especially with the added comment, hence closing as duplicate.

**Closed by D3nnis3n** 2024-11-04 03:12 UTC
