### ISSUE TITLE
Waterwheel provides power regardless of if it's near water or on your roof in the middle of desert. - 9.0.1

### ISSUE THREAD

**Issue by NaateeD** [StrangeLoopGames/EcoIssues#18212] opened 2020-09-12 20:35 UTC
Noticed this in 9.0.1, Makes windmills kinda useless since a waterwheel can work in it's place and is less resources to craft.
Didn't see this on the current bug tracker.

**Comment by D3nnis3n** [comment] 2020-09-12 21:40
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2105

**Closed by D3nnis3n** 2020-09-12 21:40 UTC
