### ISSUE TITLE
USER ISSUE: Teleport Bug

### ISSUE THREAD

**Issue by RevButcher** [StrangeLoopGames/EcoIssues#25038] opened 2024-08-16 01:33 UTC
\
**User Id: (7772b65e-2a99-4b44-d7cd-08dcbd395caf)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
Stand on a stockpile and place items into the stockpile inventory.

**Expected behavior:**
Should add items to inventory and budge the player off stockpile or move player on top of the stockpiles visual contents.

**Actual behavior:**
When items are placed into the stockpile while the player is standing on the stockpile, the player is teleported to and underground cave space.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, I have no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-08-16 12:45
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24352

**Closed by D3nnis3n** 2024-08-16 12:45 UTC
