### ISSUE TITLE
Server issue: Crash on startup

### ISSUE THREAD

**Issue by EasyMayo** [StrangeLoopGames/EcoIssues#18472] opened 2020-09-25 08:33 UTC
Our dedicated server don't want to boot anymore, tried to solve the problem by reverting to an earlier backup that worked for a day but today it gave the same error after rebooting the server.
I could need some help to understand what this means and hopefully get our server up and running again.

09:57:38.547] [31] [Error] [Eco] Failed to load server, Exception was Exception: ArgumentException
Message:An item with the same key has already been added. Key: Vote
Source:System.Private.CoreLib

System.ArgumentException: An item with the same key has already been added. Key: Vote
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Eco.Shared.Utils.BidirectionalMap`2.Add(TKey key, TVal val)
   at Eco.Stats.ShortNameMap.<Init>b__8_0(ShortNameEntry x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Stats.ShortNameMap.Init(List`1 collection)
   at Eco.Stats.StatInfoManager.Initialize(List`1 entries)
   at Eco.Stats.Stats.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync()
   at Eco.Server.Startup.StartAsync()
 
[09:57:43.557] [1] [Error] [Eco] Unhandled errorSystem.ArgumentException: An item with the same key has already been added. Key: Vote
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Eco.Shared.Utils.BidirectionalMap`2.Add(TKey key, TVal val)
   at Eco.Stats.ShortNameMap.<Init>b__8_0(ShortNameEntry x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Stats.ShortNameMap.Init(List`1 collection)
   at Eco.Stats.StatInfoManager.Initialize(List`1 entries)
   at Eco.Stats.Stats.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync()
   at Eco.Server.Startup.StartAsync()
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)

**Comment by beastyn** [comment] 2020-09-28 09:15
@EasyMayo Thank you for the report. 
Can you provide .eco and .db? (it can contain private info, so you can use my e-mail anna@strangeloopgames.com)

Also You can try to delete .db file (make a backup just in case) and try to start.

**Comment by beastyn** [comment] 2020-09-29 10:06
@EasyMayo Are you ok with your world? I've got saves and will use this issue for some permanent fix.

**Comment by SlayksWood** [comment] 2020-10-21 12:24
[log_201021031925.log](https://github.com/StrangeLoopGames/EcoIssues/files/5415783/log_201021031925.log)
https://drive.google.com/file/d/1HpnVSODKE_1kgcuI2u9VJSx-H9Eh8VTx/view?usp=sharing

**Comment by IcedForge** [comment] 2020-10-23 14:26
Reproduction steps
Start new world, have a player connect to it.
Change localization of server to another language.
Restart server, now change localization back to original language and restart.

Now you will get the exception.

Unhandled errorSystem.ArgumentException: An item with the same key has already been added. Key: Ice Forge
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Eco.Gameplay.Economy.CurrencyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)

**Comment by Quadbro** [comment] 2020-12-21 02:56
Investigated this issue and found it will require some unsafe changes with registrars, so i'm adding push label to push it to 9.3

**Comment by IcedForge** [comment] 2021-01-01 16:39
Server migrations from 9.0.5 -> 9.1.x versions can also be a source for this, i cant migrate my world into 9.1 due to this linking the issue #19890

**Comment by mirasrael** [comment] 2021-01-13 10:30
Original issue already fixed in https://github.com/StrangeLoopGames/Eco/pull/7549, but it doesn't fix already corrupted DB files. You need to delete .db file or restore from backup.

**Closed** 2021-03-05 08:27 UTC
Labels: Category: Localization, Category: Tech, Priority: Medium, Squad: Pumpkin, Status: Fixed
