### ISSUE TITLE
USER ISSUE: can't pick up lumber..lumber floats

### ISSUE THREAD

**Issue by leodimilo** [StrangeLoopGames/EcoIssues#4776] opened 2018-02-18 20:21 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
1. Max level logging
2. chop wood into smaller pieces
	

**Expected behavior:**
pieces land in general vincinity and can be picked up	

**Actual behavior:**
pieces defy gravity and float in the air.  When you try to pick them up, an exception is triggered

**Comment by MarjieAVolk** [comment] 2018-02-20 22:08
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-20 22:08 UTC
