### ISSUE TITLE
Unable To Vote Or Create Laws / empty red bar

### ISSUE THREAD

**Issue by jaxondawg** [StrangeLoopGames/EcoIssues#7990] opened 2018-06-07 20:25 UTC
On Google Chrome It Comes Up With A Red Bar Whenever I Try To Vote or Propose A Law

**Comment by johnkslg** [comment] 2018-06-08 17:04
Got a screenshot?

**Comment by MarjieAVolk** [comment] 2018-06-08 17:16
Presumably this is due to the default Citizenship law, which prevents you from proposing or voting on laws until you have played on a server for 2 hours.  The red bar is supposed to have a helpful error message in it though.  I thought this had been fixed a while ago.  What version are you on?

**Comment by LKLAW** [comment] 2018-06-09 10:05
Red bar often shows up without an error message. It's possible that he already has a proposed vote running, this also gives the red error bar without a message

**Comment by Siavel** [comment] 2018-06-09 17:27
I'm having the same issue on my private server. Just started the map and tried /clearlaws to get rid of the default law so that I could try making an anti-grief law right away. Not sure it liked me doing that as now I can't make any laws (possibly due to being under the default law's specified time?).

**Comment by goertzenator** [comment] 2018-06-25 21:33
I also have the red bar and am unable to create law.  I did successfully create a law a few hours ago... I take it I can only have one at at time?

![image](https://user-images.githubusercontent.com/605072/41876998-598e9544-7895-11e8-9e56-6ff57f52ece4.png)

![image](https://user-images.githubusercontent.com/605072/41876961-4743f46a-7895-11e8-9cc2-184e17a21b98.png)

**Comment by MarjieAVolk** [comment] 2018-06-25 21:35
Yes, you are only allowed to have one proposal per person at a time right now.  It is kind of a silly restriction though, since now you can include as many clauses as you like in a single proposal.

**Comment by rainfarmer** [comment] 2018-06-28 22:56
@jaxondawg @LKLAW @Siavel @goertzenator 
Are any of you still getting the empty red bar?
I'm not able to recreate the issue on newest version, beta 7.6.0

**Comment by MarjieAVolk** [comment] 2018-06-28 23:08
This has been reported by many people regularly for months, and as you can see it was last reported 3 days ago, so I find it unlike that it's gone.

**Comment by rainfarmer** [comment] 2018-06-29 01:12
@goertzenator could you email me a link to your eco gov url? If its not just localhost
jeff@strangeloopgames.com

**Comment by rainfarmer** [comment] 2018-06-29 01:32
@MarjieAVolk I was able to recreate a empty red bar on the user's server (I'll send you a link)

By logging in with real user, that is not a player on their server.
Try to run for election, get incorrect response from query: https://gyazo.com/b657da5c09dadd60f049c33976c0f4f2

**Comment by MarjieAVolk** [comment] 2018-06-29 17:22
Hey @goertzenator, we found we were able to reproduce the issue pretty reliably on your server's web page, but the same thing doesn't happen on my own test server.  Would you be able to send us your save file, so we can check if that is related to the issue?

Also, does this problem go away when you restart the server or anything like that?  Has it been pretty consistent that no error message shows up?

**Comment by eviltek2099** [comment] 2018-07-04 19:47
same here on laws-propose-button:
**NETWORK**:
{Message: "An error has occurred."}
Message
:
"An error has occurred."
**CONSOLE**:
jquery-latest.min.js:4 GET http://71.248.186.93:3001/api/v1/laws/canaddlaw?authtoken=14000000A02D2D576027B2DB831327030100100123C23C5B1800000001000000020000001AA759322101A8C0F68D9F0006000000B80000003800000004000000831327030100100166D505001AA7593291AE1EAC0000000026C23C5BA671585B0100F1170100010006490B00000000006B78B46E459EF17500E9A05BF2721D96D4E18776A51B14F069859DF15FEDEE90D8167041C0B96CB977F46255990FE90C21EC74921C45AC2F655B5622448D93652BECEEAF708FB7AC8945B06B98DD72C9839E103ECAFD8CD8E6977904DAF3AFE1ADA3854D77505419940C43C8FFE603044AC0F78806E4240F9732638145F6904F 500 (Internal Server Error)
send @ jquery-latest.min.js:4
ajax @ jquery-latest.min.js:4
(anonymous) @ VM1089:651
e._execute @ bluebird.min.js:29
r._resolveFromExecutor @ bluebird.min.js:30
r @ bluebird.min.js:30
Variables.PromiseAjax @ VM1089:650
r @ bluebird.min.js:31
r._settlePromiseFromHandler @ bluebird.min.js:30
r._settlePromise @ bluebird.min.js:30
r._settlePromiseCtx @ bluebird.min.js:30
r._drainQueue @ bluebird.min.js:29
r._drainQueues @ bluebird.min.js:29
drainQueues @ bluebird.min.js:29
(anonymous) @ bluebird.min.js:30
attributes (async)
(anonymous) @ bluebird.min.js:30
attributes (async)
o @ bluebird.min.js:30
(anonymous) @ bluebird.min.js:30
r._queueTick @ bluebird.min.js:29
o @ bluebird.min.js:29
p.hasDevTools.r.invoke @ bluebird.min.js:29
r._then @ bluebird.min.js:30
r.then @ bluebird.min.js:30
Variables.canaddlaw @ VM1089:464
(anonymous) @ VM1089:695
dispatch @ jquery-latest.min.js:3
r.handle @ jquery-latest.min.js:3

**Comment by LiaungYip** [comment] 2018-07-17 20:23
This still occurs for me on the Pam's Big World server on 7.6.0. Can post screenshots later.

**Comment by LiaungYip** [comment] 2018-07-17 20:49
Could be related to the default citizenship law, as noted in the
discussions above. Could ask the server administrator to delete the
citizenship law and see if that helps. Deleting the default citizenship law
has resolved the problem for me on previous 7.4 series servers.

**Comment by MarjieAVolk** [comment] 2018-07-17 20:54
You mean it caused the red bar to display error messages again instead of being empty?  Or do you mean it caused you to stop getting error messages?

**Comment by LiaungYip** [comment] 2018-07-17 21:56
Marjie, deleting the default citizenship law on 7.4 series servers has allowed me to create laws successfully. Before deleting the default citizenship law, I got the empty red bar.

The empty red bar also happens on current 7.6 series server when attempting to stand for election as world leader.

**Comment by MarjieAVolk** [comment] 2018-07-17 22:13
Okay, well that is expected, as the default law is supposed to prevent new players from passing laws.  The bug is that it doesn't show the error message in the bar.

**Comment by LiaungYip** [comment] 2018-07-17 22:18
@MarjieAVolk , Additional information; The empty red bar still occurs after 10-20 hours of play time in the world. The Citizenship law should no longer apply after 2 hours of play.

There is certainly a problem where the Citizenship law doesn't give a good error message when a new player (<2 hours) tries to create a law. The behaviour of the law is working as intended, but the error reporting isn't clear.

However there also seems to be an issue that players with >2 hours of play, can't pass laws, because of the Citizenship law. (Some more testing may be required.)

**Comment by MarjieAVolk** [comment] 2018-07-17 22:30
Okay I see.  That is a pretty serious issue.  Just to double check, did you have stat reads/writes disabled when this happened?

**Comment by LiaungYip** [comment] 2018-07-18 09:19
@MarjieAVolk , I've had a quick look at the web user interface for the server I'm currently playing on, and tried to graph some statistics. All the graphs are empty, which suggests that stat read/writes are disabled on this particular server.

![image](https://user-images.githubusercontent.com/2173684/42871506-dfbcb486-8abd-11e8-95e6-e5c44698eb56.png)

Now that you mention it, I think that stat reads and writes were also disabled on the server where I had this issue previously. (That server was running one of the versions where stats logging was disabled out-of-the-box for perf reasons.)

I'll ask the server owner if stats logging has been intentionally disabled, or if it came that way out-of-the-box on 7.6.1, but I think that you've hit the nail on the head.

It's possible that the real "fix" for this issue is to:

1. Clarify (in the server admin interface, and in the config file) that disabling stats will have an adverse interaction with the default Citizenship law.
2. Improve the "red bar" error message to correctly reference the Citizenship law (or other applicable law), AND to flag if the law could not possibly be satisfied because stats logging is disabled.

The current tooltip text mentions that disabling stats may make "some features not function..." such as "laws that reference action counts", but it's not immediately obvious that this will cause a bad interaction with the default Citizenship law, which counts hours of play.

![image](https://user-images.githubusercontent.com/2173684/42872000-0845ceb4-8abf-11e8-9867-efd6fe536177.png)

It's unfortunate that the config files appear to be JSON format, which doesn't allow comments - so there's not much help for people who are running headless servers (`-nogui`).

![image](https://user-images.githubusercontent.com/2173684/42871865-b58cd9b0-8abe-11e8-9d83-1be373d1118e.png)

**Comment by rsdworker** [comment] 2018-08-07 03:46
well i have seen same issue - but however when i clear laws - i unable to create new laws 
as seen here - the red bar appears but no error message on it
![image](https://user-images.githubusercontent.com/6688223/43753197-7a87f050-99fc-11e8-9e37-e489a55d5fd5.png)
my host is GTX hosting UK - its never had happened - before its was fine when i first started with host
see the issue #8851 which i created this one

**Comment by D3nnis3n** [comment] 2018-08-17 06:29
Was able to propose and pass two laws yesterday and the day before, today i get a simple red bar error like ages before since i started playing six months ago :(

Citizenship law not active.
No own or other proposal active.
All field have input.

:(

**Comment by MarjieAVolk** [comment] 2018-08-17 18:12
Does the law have the same name as a previous law that failed/was cancelled?

**Comment by D3nnis3n** [comment] 2018-08-17 18:17
No.






On Fri, Aug 17, 2018 at 8:12 PM +0200, "MarjieAVolk" <notifications@github.com> wrote:












Does the law have the same name as a previous law that failed/was cancelled?

**Comment by johnkslg** [comment] 2018-08-21 05:29
This law is not getting fixed because three people are assigned.  Marjie can you follow through with individuals to work out the fix to this one?

**Comment by MarjieAVolk** [comment] 2018-08-21 17:25
This is already on my radar, and we have an attempted fix planned.

**Comment by CobaltEcho** [comment] 2018-09-07 21:33
Just to add my two cents, the red bar at the top has never worked for me in any version.

Also, if you delete/remove a law,  you CAN NOT remake a law using the same name. You get a blank red bar.

**Comment by D3nnis3n** [comment] 2018-09-07 21:36
The red bar error has not appeared for us anymore the last 21 days – Job well done!

**Comment by rsdworker** [comment] 2018-09-07 21:41
yeah its fixed - the red bar error now no longer shows - just shows why i was unable vote or prospse laws
eg you cant prospse law till 2 hours of playtime

**Comment by rainfarmer** [comment] 2018-09-26 00:39
I was able to recreate the empty red bar:

Go to game's web interface not logged in and try to propose a law.
But this only works with external IP.
If you go to web interface from same network that server is on, it sends you to an internal ip, and the empty red bar doesnt come up on this ip version of web interface

**Comment by johnkslg** [comment] 2018-11-13 19:05
Red bar should be fixed now!

**Closed by johnkslg** 2018-11-13 19:05 UTC
Labels: High Priority
