### ISSUE TITLE
optimize chat history

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19739] opened 2020-12-14 23:12 UTC
@tu: "CW Eco-Server requires around 2 GB mem for Gen2 and LOH, allocate 200MB/3s, so when the server doesn’t have enough memory, the delay will happen (waiting for space in mem). Eventually, the Server crashes when it can’t handle it anymore. 
So my suggestion is to optimize memory usage in the Server. 
We can quickly reduce memory usage by clear chat history or store them in DB instead of caching them."

**Comment by mirasrael** [comment] 2020-12-17 06:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14980

**Closed** 2021-04-19 21:43 UTC
Labels: Category: Optimization, Priority: Medium, Squad: Mountain Goat
