### ISSUE TITLE
USER ISSUE: Tools stay obscured after some time in paused state

### ISSUE THREAD

**Issue by GeertJanVanDerWolf** [StrangeLoopGames/EcoIssues#25122] opened 2024-08-30 18:30 UTC
\
**User Id: (1afcab0b-84f2-4e69-080b-08dcc69e5b43)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
Hit [esc] at any time. Leave the in that state for an hour or so.

**Expected behavior:**
Press [resume] came back into the active GUI of the game with all functionality in tact.

**Actual behavior:**
Toolbar selection works as expected. However, tools are obscured and for instance the bow is unusable. Other tools also are obscured but are less graphical in use. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. So the issue happens with no mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/16820915/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16820918/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-08-31 21:40
Cannot reproduce. Any additional info you can provide, especially what you mean with "obscured"?

**Comment by D3nnis3n** [comment] 2024-09-08 13:26
Closing due to not reproducible and no additional information provided. Feel free to open a new issue if you can provide additional info.

**Closed by D3nnis3n** 2024-09-08 13:26 UTC
Labels: Status: Needs Information
