### ISSUE TITLE
[beta 7.8.0 b7709677] Can't get out of bed (lol) after sleeping

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9571] opened 2018-09-26 21:59 UTC
You are stuck in this screen:
<img width="936" alt="sleep" src="https://user-images.githubusercontent.com/25908592/46111680-2dd04f00-c1e8-11e8-9661-26e0f2f0796e.png">

**Comment by johnkslg** [comment] 2018-09-28 19:32
Check the text not autosizing too, looks like a localization problem.
To test: /spawnbed

**Comment by sidjuego** [comment] 2018-10-01 09:34
We are not able to reproduce the bug and it seems to be working fine in our build .Attaching the video link for your reference.

https://drive.google.com/file/d/1ZhqkUVG4Fu6kA1TZvB0AkIwITGlO_u0O/view

**Comment by D3nnis3n** [comment] 2018-10-01 09:40
Here is my reproduction: https://drive.google.com/file/d/1U-gY16IrKvQSAlfAtK7-aKlUZ0FyZwso/view?usp=sharing

**Comment by D3nnis3n** [comment] 2018-10-01 09:42
Did you note the given version in the title? Sleeping is a in-dev feature and i tested that build, as that was the one up for QA and the only build i have access to.

**Comment by D3nnis3n** [comment] 2018-10-01 09:43
Did you try using german language?

**Comment by johnkslg** [comment] 2018-10-01 16:43
Sounds like its fixed in latest. @D3nnis3n reopen if you repro again

**Comment by johnkslg** [comment] 2018-10-12 20:44
Fixed in master and staging!

**Closed by johnkslg** 2018-10-12 20:44 UTC
Labels: High Priority
