### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by multimattster** [StrangeLoopGames/EcoIssues#4132] opened 2018-02-08 20:34 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Click on Continue in the main menu

**Expected behavior:**
Load into the previously played world

**Actual behavior:**
The following error message popped up:
"Connection Failed"
```

**Comment by MarjieAVolk** [comment] 2018-02-09 02:23
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4092

We have been getting many reports of connection errors; part of the problem is that there is no good error message, so it is hard for us to debug and hard for you to debug.  If you are playing on a local server, you might try disabling NAT on the server.  You can do this in your server window by going to Network tab > Config tab > DetectNAT setting.

**Closed by MarjieAVolk** 2018-02-09 02:23 UTC
