### ISSUE TITLE
7.7 Inventory Dragging Items Popups VERY ANNOYING

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#9198] opened 2018-09-06 00:23 UTC
I cannot easily drag items between inventory slots anymore. it is not reliable and often the popups get in the way. This is make the game feel extremely clunky and it is very frustrating to go from this feature working fine to not working well.
https://vimeo.com/user89199243/review/288459144/af4000e422

**Comment by BlazeGuy2** [comment] 2018-09-06 00:28
@Senlarus Clicked the link and couldn't find the page/

**Comment by Senlarus** [comment] 2018-09-06 00:49
https://vimeo.com/288459144

**Comment by Saternia** [comment] 2018-09-06 07:01
Same issue here, when the popups don't get in the way your aim has to bee 1000% dead on else it does not drop in the slot

**Comment by Nicolausi113** [comment] 2018-09-06 07:42
#9132

**Comment by metachronism** [comment] 2018-09-06 18:05
dupe of #9132 moving discussion there

**Closed by metachronism** 2018-09-06 18:05 UTC
Labels: High Priority, Needs Triage
