### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Eco-LoneWolf** [StrangeLoopGames/EcoIssues#12131] opened 2019-04-29 16:19 UTC
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Get more than 6 storage's.
Fill them Pretty full with junk.	
Baum

**Expected behavior:**
I should be able to see my storage and walk or climb on top of them

**Actual behavior:**
I can see through the ground and if it is tall enough i fall through the ground and appear back up to the surface. some of the "Solid Blocks" i can phase through and get stuck.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods
![20190429091412_1](https://user-images.githubusercontent.com/50113747/56910600-d46f1d80-6a5f-11e9-8eaa-3b858c428590.jpg)
![20190429091504_1](https://user-images.githubusercontent.com/50113747/56910614-d9cc6800-6a5f-11e9-9962-589a6ca4926f.jpg)
![20190429091636_1](https://user-images.githubusercontent.com/50113747/56910616-db962b80-6a5f-11e9-955f-79c9b71f255d.jpg)
![20190429091428_1](https://user-images.githubusercontent.com/50113747/56910624-df29b280-6a5f-11e9-91ee-1e86ba010de7.jpg)
![20190429091419_1](https://user-images.githubusercontent.com/50113747/56910634-e3ee6680-6a5f-11e9-85a2-45f60c409cf9.jpg)

**Comment by redwyre** [comment] 2019-04-29 16:45
Could you please attach your log file after this happens?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2019-06-20 10:24
Closing for now due to not being reproducable and no further information available. Reopen when it occurs again and you can provide more information / logfiles.

**Closed by D3nnis3n** 2019-06-20 10:24 UTC
Labels: Investigate, Needs Information
