### ISSUE TITLE
[7.6.2] Law feature request Important for economy and world management

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#8688] opened 2018-07-23 11:49 UTC
We need a tool to calculate population in law:
-number of plant
-number of animals
-number of every things

Exemple:
We want to pay a player with treasury if he kills and harvest a turtoise if total number of turtoise in the world is >= 800 (law for animals regulation)

So:
OnPlayerAction When attempting to Harvest Where (Species is Turtoise) +
Condition
If Numeric comparison "Population of" Turtoise >= 800
Then Allocate
Currency Name of currency Amount
Otherwise Prevent (or Tax or anything else)

It's important to manage world and quantity of things!

![image](https://user-images.githubusercontent.com/29807119/43075247-83728dec-8e80-11e8-9138-f6b43d335358.png)
On the screenshot you can see that we can not calculate population number and allocate an amount of money from treasury of course

**Comment by Deantwo** [comment] 2018-07-23 12:01
Your old bug report isn't good enough?
See: #8114

**Comment by Myrhaug** [comment] 2018-07-23 12:09
@Deantwo Im the one who proposed a law function about it.
But it is still an good idea to have this.

**Comment by Deantwo** [comment] 2018-07-23 12:11
But why make a report about the same thing again?

**Comment by Myrhaug** [comment] 2018-07-23 12:16
I did not.
Our avatars is the same but we are 2 diffrent people. Look on my name and reporters name.

**Comment by Deantwo** [comment] 2018-07-23 12:17
Ok, i feel stupid now. 😓

**Comment by MarjieAVolk** [comment] 2018-07-23 18:43
Hahaha this doesn't happen every day.  Okay closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8114

**Closed by MarjieAVolk** 2018-07-23 18:43 UTC
Labels: Feature, Laws, Needs Triage
