### ISSUE TITLE
Contract not recognizing items transfer via right-click

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6196] opened 2018-03-17 17:34 UTC
our "major" decided to distribute a bunch of coins via contract in exchange for 1 stack stones, i accepted the contract and dropped it into the designated stock-pile using right-cklick and not the GUI

the contract was not finished and i could retrieve the stack using left-click and inserted the stone via GUI and it worked

**Comment by MarjieAVolk** [comment] 2018-03-21 19:38
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6050

Should be fixed in 7.3

**Closed by MarjieAVolk** 2018-03-21 19:38 UTC
