### ISSUE TITLE
Consistent Bug with door collision

### ISSUE THREAD

**Issue by WhAtEvErYoUmEaN** [StrangeLoopGames/EcoIssues#6732] opened 2018-03-30 12:12 UTC
I can consistently reproduce getting stuck in the ceiling or making the game i'm falling great heights by running into an opening door from the right angle (jumping optional).

Quick video of it:
https://youtu.be/7Nt-u__sYeM

**Comment by MarjieAVolk** [comment] 2018-04-03 23:51
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4140

I will share your video there.  Thanks

**Closed by MarjieAVolk** 2018-04-03 23:51 UTC
