### ISSUE TITLE
Feature request : Import law

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#6036] opened 2018-03-14 12:30 UTC
We regulary restart server with a list of basic law to set the world.
We have a lot of law to limit number of professions, harvest capacity, furniture production to adjust world settings and we want to be able to import previous law to new server but currently it's not possible.
It would be a nice feature to allow server manager to import law ( and a big gain of time )
Current interface is cool to set new law, but when you have a batch of X laws to set at start it take a LOT of time.

Thx

**Comment by fillion07** [comment] 2018-03-14 13:28
Do you think you can share those laws by taking a snapshot of the law interface?
It will be nice to have a plateform where players can share law ideas with the implemented logic.

**Comment by Kastuk** [comment] 2018-03-14 14:23
You can just look into our challenged server panel.
http://play.ecotopia.games:4001

**Comment by MarjieAVolk** [comment] 2018-03-16 01:35
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4090

**Closed by MarjieAVolk** 2018-03-16 01:35 UTC
