### ISSUE TITLE
SUGGESTION: Special characters in chat

### ISSUE THREAD

**Issue by GibsonSWE** [StrangeLoopGames/EcoIssues#4043] opened 2018-02-07 15:51 UTC
I'd simply like to see support for special characters in the in game chat. Like Å, Ä, Ö for example...

**Comment by Nanders** [comment] 2018-02-07 18:31
This is planned to be added.

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2656

**Closed by Nanders** 2018-02-07 18:31 UTC
