### ISSUE TITLE
USER ISSUE: detatching laws and districts

### ISSUE THREAD

**Issue by Mdye99** [StrangeLoopGames/EcoIssues#24905] opened 2024-04-23 01:21 UTC
\
**User Id: (slg217017)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
creat a law and or district, pick up the corresponding table

**Expected behavior:**
reattatch the law and districts when placing the table back down

**Actual behavior:**
shows a pop up for reattatching but after clicking yes the lawas and districts remain unattatched and become invalid after the timer

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and i dont know

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-04-24 03:20
Wasn't able to reproduce this. Does it happen with all civics? Is this a normal town, what are the server settings? Can you give us any more details on what the setup is?

**Comment by D3nnis3n** [comment] 2024-04-30 16:36
Closing due to not reproducible and no further information provided - please feel free to open a new issue when you can provide more info or a reproduction case.

**Closed by D3nnis3n** 2024-04-30 16:36 UTC
Labels: Status: Needs Information, Status: Not reproduced
