### ISSUE TITLE
USER ISSUE: Roadtool: Red Background incorrect

### ISSUE THREAD

**Issue by LEGIONDE** [StrangeLoopGames/EcoIssues#5834] opened 2018-03-10 11:58 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Have a broken road tool in your taskbar
2. Have a working road tool in your backpack
3. Change the broken roadtool out with the working road tool, per drag and drop

**Expected behavior:**
The broken roadtool has a red background. When i change it out for the new road tool, the background should turn blue again

**Actual behavior:**
Instead, although the new roadtool had full health, the background remained red

**Comment by MarjieAVolk** [comment] 2018-03-12 22:43
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/2544, these might be better repro steps though.

**Comment by MarjieAVolk** [comment] 2018-06-25 17:58
I'm going to go ahead and close this as a duplicate of #2544 - I'm copying your comments over there.

**Closed by MarjieAVolk** 2018-06-25 17:58 UTC
Labels: Medium Priority
