### ISSUE TITLE
Font disappears

### ISSUE THREAD

**Issue by mastercake10** [StrangeLoopGames/EcoIssues#5860] opened 2018-03-10 21:42 UTC
After playing the game for ca. 10 minutes, the font disappears.

![image](https://user-images.githubusercontent.com/16278273/37247006-4729aa7c-24b4-11e8-9134-0fc33898327d.png)

**Comment by MarjieAVolk** [comment] 2018-03-12 22:05
What operating system are you on?

Could you attach your log file? 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by mastercake10** [comment] 2018-03-12 23:25
I'm on Linux 4.14 Ubuntu 16.04 Xenial.
I've checked the ~/.local/share/ directory for a "Strange Loop Games" folder, but it seems to be missing.
However, the game is very buggy and almost unplayable on Linux.

**Comment by MarjieAVolk** [comment] 2018-03-13 18:47
Okay, if you're on linux, then closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5749

Yeah, I'm sorry about that; mac and linux clients are not well supported right now.  Servers are alright on mac/linux I believe.  We do want to support linux clients better eventually, but it's not high on our priority list right now.

**Closed by MarjieAVolk** 2018-03-13 18:47 UTC
