### ISSUE TITLE
[0.8.0.5 beta] Cutting trees - on dismemberment disappear completely when pickup button is being held

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#11622] opened 2019-03-10 04:45 UTC
If you're holding down the object pickup button (E by default), when dismembering a fallen tree to the pickup-able chunks, sometimes it can result in a remaining cuttable tree to completely disappear. Multiplayer-tested only, works with stone and iron axe, hadn't tested the rest of them (tools). Occured multiple times with the spiked trees

**Comment by SlayksWood** [comment] 2019-04-29 07:33
Checked on 8.1.4. Wasn't able to reproduce.
Do you have this problem now?

**Comment by HetNeSS** [comment] 2019-04-29 16:32
Can't say, it's been a long time since i've last played Eco. I guess they would patch something in any of the upcomed updates.

**Comment by D3nnis3n** [comment] 2019-05-16 11:16
Closing for now, feel free to create a new issue if this reoccurs.

**Closed by D3nnis3n** 2019-05-16 11:16 UTC
Labels: Investigate, Needs Information

**Comment by Deantwo** [comment] 2019-08-17 10:48
Duplicate of #11487
