### ISSUE TITLE
Invisible stump 7.0.3

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3986] opened 2018-02-06 18:49 UTC
I chopped down of the new oak tree's and removed the stump, but the stump is still there. I cannot see it, but I cannot walk through where it used to be. I can dig the ground up around it, but I still collide with it. When I move my axe over it I get the chop command and I can see splinters flying but no amount of chopping removes the stump.

![image](https://user-images.githubusercontent.com/1503963/35877836-78e419b4-0b44-11e8-9a6d-5770084a84c6.png)

**Comment by Nanders** [comment] 2018-02-06 19:26
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3827

**Closed by Nanders** 2018-02-06 19:26 UTC
