### ISSUE TITLE
USER ISSUE: Chest tells me that it should be on the ground but i can still access it and also place another one in the air

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#6594] opened 2018-03-28 21:36 UTC
**Version:** 0.7.3.0 beta

![snap2093](https://user-images.githubusercontent.com/29383891/38057737-43e56040-32d8-11e8-92f2-46e257787eed.png)
![snap2094](https://user-images.githubusercontent.com/29383891/38057738-4402a42a-32d8-11e8-8af2-e3a24f875f5a.png)
as you can see Chest is up in the air , another on the ground and the Workbench can see them both and send any item to each
![snap2096](https://user-images.githubusercontent.com/29383891/38057851-a8df429a-32d8-11e8-89f6-2afec24a5664.png)

i can understand why this was done to stop the cheating of furniture but it is a bit confusing with Storage (as that we need to place sometimes up in the air to save on space)

**Comment by darkshad9999** [comment] 2018-03-28 21:40
The same as what I reported already #6572
 
https://github.com/StrangeLoopGames/EcoIssues/issues/6572

**Comment by MarjieAVolk** [comment] 2018-03-28 21:49
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6572

**Closed by MarjieAVolk** 2018-03-28 21:49 UTC
