### ISSUE TITLE
Minimap land sometimes disappears

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2820] opened 2017-11-14 22:44 UTC
![image](https://user-images.githubusercontent.com/774628/32809034-31d6b770-c94a-11e7-85d3-41d298398d30.png)
Seems to happen when slowly zooming out on some worlds w/ minimum minimap detail

**Comment by johnkslg** [comment] 2017-11-17 02:07
![image](https://user-images.githubusercontent.com/3536496/32925840-f237bf14-caf8-11e7-89d0-68db1109e391.png)
Getting this as well.

**Comment by johnkslg** [comment] 2017-11-17 02:08
From a small world though

**Comment by BlazeGuy2** [comment] 2018-06-05 23:40
Can't reproduce on a small world, im assuming it's fixed.  Closing

**Closed by BlazeGuy2** 2018-06-05 23:40 UTC
