### ISSUE TITLE
[0.9.3 develop-180] Fishing Pole controls issue

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20452] opened 2021-02-09 07:11 UTC
- [x] 1. Work in tab mode. Steps:
- select fishing pole in active cell.
- open any UI (ESC menu). Use LBM to change something in settings, fishing pole will be used too.

- [x] 2. Doesn't work with second binding. Steps:
- open Esc Menu -> controls.
- add second binding to Use Tool:
![image](https://user-images.githubusercontent.com/45708377/107326901-468de680-6abd-11eb-89cd-2c70a3670fb8.png)
- try to use fishing pole with this binding. You can't, but another tools are usable.

- [x] 3. Sometimes after casting the pole, reel starts to twist itself

- [ ] 4. Fishing looks strange: when the fish bite, the bobber will teleport. I can't pull the fish. It is located in one place. But if I pull, I'll pull it out (it just disappears and an item will be added to me):
https://drive.google.com/file/d/1mwUJXCcJ8RM1qufPTuL-Ggp8GjsQNut1/view?usp=sharing

**Comment by ptitducanh** [comment] 2021-03-03 16:11
I can't reproduce the 3rd case. Can you give me more detail (when it happens? Any special conditions?).

**Comment by SlayksWood** [comment] 2021-03-05 08:41
@ptitducanh I can't reproduce it too, it might have been related to my mouse, I had problems with the LMB and had to change it. Skip this one I will test it again more after changes.

**Comment by IcedForge** [comment] 2021-03-09 11:08
This was merged on develop and not staging, this can be pushed i believe if risky to rework of mapping @ptitducanh @WeaselDog

**Comment by Daniel-Magulado** [comment] 2021-03-17 04:47
Unable to test.

As of build 0.9.3 Staging-1955, Fishing Pole is not working. Blocked by #20977.
Unable to verify the fix on Develop since Develop is still broken.

**Comment by SlayksWood** [comment] 2021-03-17 05:14
Reopen, it was merged to Develop

**Comment by ptitducanh** [comment] 2021-03-19 16:30
I pushed those changes to staging (both SVN and git). I've tested it myself.
Can you guys give it another shot.

**Comment by Daniel-Magulado** [comment] 2021-03-20 17:46
Tested on 0.9.3 Staging-1960.

Task 1 and task 2 are fixed.
Unable to reproduce task 3.
Task 4 is still happening.

Resolution: Reopening.

Attaching video for proof.

https://user-images.githubusercontent.com/77248866/111880542-1c4a1580-89e7-11eb-9a09-31d245bc875b.mp4

**Comment by Daniel-Magulado** [comment] 2021-03-20 18:59
Oh wait, I think I can reproduce task 3. Apparently, if you cast the fishing line, there's a certain situation where the bobber returns to its uncasted state or to the Fishing Pole without reeling the fishing line.

Tested on 0.9.3 Staging-1960

Repro:
1. Select the fishing pole and start casting by clicking LMB.
2. Move sideward and try to move the bobber near you without reeling it in. Or, jump on the water and get the tip top portion of the Fishing Pole near the bobber.
3. Move the tip-top portion of the fishing pole near the bobber.

Actual Result:
The bobber returns to the fishing pole in its uncasted state.

Expected Result: 
Nothing, the fishing line should not be affected even if the fishing pole and the bobber gets near each other.

Video:
https://images.zenhubusercontent.com/47210472/6d506468-bd36-4e0d-9845-3dad2a7664fc/2021_03_21_02_50_trim.mp4

**Comment by TwixterZ** [comment] 2021-05-05 03:50
fix tested and confirmed as of 9.4 Develop 277 for all 4 tasks

**Closed by TwixterZ** 2021-05-05 03:50 UTC
Labels: Category: Gameplay, Priority: Low, Squad: Wild Turkey, Status: Fixed, Type: Bug
