### ISSUE TITLE
USER ISSUE: Accessing Fishing Traps

### ISSUE THREAD

**Issue by billybones458** [StrangeLoopGames/EcoIssues#5359] opened 2018-03-04 06:07 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Place Trap at bottom of lake.
2. Catch a fish it in
3. Try to access it before floating away and not being fast enough to drag the fish to your inventory/bar.
4. Repeat until you get it, or give up.

**Expected behavior:**
Able to move the fish into inventory without frustration.

**Actual behavior:**
Frustration.

**Comment by MarjieAVolk** [comment] 2018-03-06 02:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4275

**Closed by MarjieAVolk** 2018-03-06 02:13 UTC
