### ISSUE TITLE
USER ISSUE: Error on joining a server where I had 2 Characters

### ISSUE THREAD

**Issue by Fightera100** [StrangeLoopGames/EcoIssues#4246] opened 2018-02-10 13:33 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. Join a server where you had 2 characters (name#2 for example)
2. Get the error

**Expected behavior:**
I should join the server

**Actual behavior:**
The following error message popped up:
```<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Ein Aufrufziel hat einen Ausnahmefehler verursacht.
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Plugins.Networking.Clients.Client.ShouldSelectUser()

<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Ein Aufrufziel hat einen Ausnahmefehler verursacht.
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Plugins.Networking.Clients.Client.ShouldSelectUser()

```

**Comment by MarjieAVolk** [comment] 2018-02-13 05:18
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4413.  You can track the issue progress there.

We already have a fix for this, which will go out in the next update.  Unfortunately, until then you may not be able to play on this server.  You should be able to play on other servers.

**Closed by MarjieAVolk** 2018-02-13 05:18 UTC
