### ISSUE TITLE
Synced physics objects not settling properly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17960] opened 2020-08-29 00:33 UTC
![image](https://user-images.githubusercontent.com/3536496/91624325-8b312580-e954-11ea-8260-4d929fa1b7be.png)
Watching Sekoris mine, these rocks where floating and never came to rest on the ground. They were also flying around all crazy.

**Comment by MazonDel** [comment] 2020-09-03 22:10
@johnkslg @mirasrael 

Upon investigation, the system for deciding if a piece of rubble should freeze/unfreeze is arranged in a way that doesn't feel quite in keeping with some other things we do.

Namely, only the client that broke the block and created the rubble is going to be the one to check if the rubble block in question should "Thaw" and start moving again. As it stands, the issue is that the way its set up is once a client freezes the rubble the client itself is not thought of as "in control" of the rubble anymore so no client is running the Thaw-check. But even if that error wasn't true, if a player makes a bunch of rubble and disconnects, then nobody will run the checks on that rubble to Thaw it.

So effectively, if a player makes a bunch of rubble and leaves, if some other player digs out the space beneath the rubble, then it'll just float there. Worse, if the original player comes back in, their client won't recognize that rubble as 'theirs' to check.

The "Thaw" check operates by raycasting downward to determine if there is more distance downwards than there used to be. So it makes sense we don't have that check happening on the server.

My proposal is that we could implement a system where rubble is assigned a controlling client (by default the player making it?) to run the ThawCheck, this owning player is stored in the Freezable component itself. If that player leaves the area or disconnects, then another player in the area is assigned to run the ThawChecks. This keeps the server load light but makes sure that SOMEONE is always in charge of checking if the rubble should unfreeze.

**Comment by mirasrael** [comment] 2020-09-04 06:18
Probably it may be fixed much more simpler way if you will just re-enable physic on collision exit (not sure though if it will fire an event). It works this way for player interaction. If you noticed when block frozen and you touch it then it unfreezes.

**Comment by johnkslg** [comment] 2020-09-04 18:35
Yes, agree with Alex. Frozen physics doesnt need an owner, whoever wakes it up with a colllision can become the owner.
But there seems to be some other problem here; the blocks seem to be freezing by the owner, but then not sending their final position to the clients watching, thus theyre hovering in a position just above where they were last synced, probably.  I bet the solution is to make sure that when an object freezes, it sends a final update to other clients, and those other clients dont 'freeze' the block until its reached that position (its probably detcting 'sekoris froze the block, freeze it now!' without first lerping to the final position and orientation on sekrois's client).

**Comment by MazonDel** [comment] 2020-09-05 02:28
@mirasrael @johnkslg 

After doing a bit of testing I've come up with a relatively good solution to the actual bug here, but I think I've come across a slightly different issue as well.

I've got things going such that now the rubble is appropriately performing its thaw-checks when rubble underneath falls away, and syncphysics is mostly managing to shove the rubble where it's supposed to go between the two. However there is an interesting behavior that I noticed when the player that created the rubble disconnects. Some amount of the rubble will "unfreeze" for the other players, except that it doesn't involve the Freezable code. I'm investigating the SyncPhysics code right now, but right now the discrepancy is REALLY small, much less noticeable than the issue indicates.

**Comment by beastyn** [comment] 2020-09-28 11:22
First test attempt:
1) Rubbles from other person behave strange, they are freeze and twitch.
https://drive.google.com/file/d/1qaL40FGao7PAYAYQy8caScV3KW_jOTEP/view?usp=sharing
2) Trees won't fall down.
![bandicam 2020-09-28 10-19-26-036](https://user-images.githubusercontent.com/27898520/94426262-b81c6680-01a6-11eb-80c5-cceae63876b0.jpg)
3) Not sure if this is caused by these changes, but excavator behaves strange too. (stranger that usual)
https://drive.google.com/file/d/1xU8aPtmo4JxV13l-aKB7KV4x73hfw1kf/view?usp=sharing
4) we have a lot of collision-physics exceptions,
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5291838/Player.log)

**Comment by beastyn** [comment] 2020-10-08 10:00
Trees are still in troubles, will make separate issue

And rubles are quite better. but still have a little freeze which make their physics kind of animated.
https://drive.google.com/file/d/1VUNzR5Kz2CNio9E6YYKp6WbVfZuyHXI1/view?usp=sharing
Also they still can stuck in the air after excavator dropping.

https://drive.google.com/file/d/1-F0dFyWVjKNUYp1780ooV92L3HuuPtY6/view?usp=sharing

**Comment by SlayksWood** [comment] 2020-11-05 13:16
Still need improvement:
https://drive.google.com/file/d/1tA_BHrj6Y2wOVXKZXvLhqy1KfkxcNjov/view?usp=sharing

**Comment by SlayksWood** [comment] 2020-12-01 10:39
check after merging https://github.com/StrangeLoopGames/Eco/pull/7272

**Comment by SlayksWood** [comment] 2020-12-02 11:44
we still have issues, but it's better now. We will open a separate issues.

**Closed by SlayksWood** 2020-12-02 11:44 UTC
Labels: Category: Gameplay, Priority: Medium
