### ISSUE TITLE
Double Stacked clothing able to be worn.

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#20297] opened 2021-02-01 02:58 UTC
![image](https://user-images.githubusercontent.com/36024353/106409717-d3bea480-6406-11eb-95f6-b53582e0a2e1.png)
I dragged clothes onto my person, I had 2 Work packs and 2 Work Boots, and the number 2 popped up underneath. As if I am wearing two of them.   They are no longer in my Inventory.  In their spots are the removed Basic backpack and Tall Boots.

**Comment by Daniel-Magulado** [comment] 2021-02-01 05:02
Hi there, thank you for reporting this. However, we are unable to reproduce this issue. For us to further investigate this, we kindly request that you provide us the following:

- Your game log files.
- Steps on how to reproduce the issue.
- Video recording of how the issue is occurring.

To provide log files. please follow the instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by sirPattrick** [comment] 2021-02-01 05:15
Daniel, I will get you the game log tomorrow.  I did have the void storage screen open while I was equipping the doubled up item.

**Comment by IcedForge** [comment] 2021-02-17 10:39
Can not reproduce this on 9.3-staging 1931, will close this as logs were never uploaded. If this is still something you experience please reopen the issue and post further information.

**Closed by IcedForge** 2021-02-17 10:39 UTC
Labels: Status: Needs Information
