### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Klemms** [StrangeLoopGames/EcoIssues#4401] opened 2018-02-12 19:08 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   à Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   à Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-12 23:22
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752 . You can track the issue's progress there.

If you have any additional information about when or why this happens, or what kinds of trees it happens on, it would be very helpful if you posted that on the linked bug ^

**Closed by MarjieAVolk** 2018-02-12 23:22 UTC
