### ISSUE TITLE
Skill at level 2 shown at incorrect level, failing Work-Party Skill Requirement

### ISSUE THREAD

**Issue by KevinGelking** [StrangeLoopGames/EcoIssues#22960] opened 2022-02-04 18:47 UTC
Note: I tried using the in-game reporting but it didn't open the browser after confirming.

Description:

> Unsure how to reproduce, Sorry :(
> 
> What happened is that my friend learned Carpentry by investing a star the other day. She has since raised it to level 2. In my skill view, it shows one person has Carpentry and the max level is 2, hovering over that it also shows 'Faye0111 - Level 2'.
> 
> On her end, the skill view on the right reads "Carpentry Level 2: Specialized". The section on the left shows one person has the skill and their level is 2. Hovering over it, it shows "Faye0111 - Level 2"  - just like mine.
> 
> HOWEVER!
> The skills shown at the bottom of the skill window read "Carpentry Level 1" when hovered over, despite her being at roughly level 2.25f already.
> 
> We noticed this because I created a work party with Carpentry 2 requirement and she couldn't accept it as the game said she doesn't have the skill - but she could perform the labor which requires level 2... so there seems to be some discrepancy for the same skill when looked at in different sources.

Expected Behaviour:

> Carpentry Skill should show Level 2 in HUD, Skill Specialization Name, World Details (profession list) and the kind of superfluous skills shown at the bottom of the skill dialog.
> Additionally, all sources (Contract & work order) should use the same data/logic to determine qualification.

Actual Behaviour:

> Instead, it displayed a different level when hovering over the bottom list on the skill dialog than it does in all other places.
> 
> A work party requiring level 2 carpentry could not be accepted, but a work order at a carpentry bench requiring level 2 could be completed.

Mods installed:
No, completely vanilla. Version 0.9.4.6 beta release-285

![TeamViewer_WL4iNjgVSo](https://user-images.githubusercontent.com/30538130/152585467-3ff42d36-d2a6-46fb-860b-e0b6359de641.png)
![ApplicationFrameHost_Mr0eAcFVS6](https://user-images.githubusercontent.com/30538130/152585472-d2b8ad56-ef30-4a8e-83e2-ca602e286f77.png)
![ApplicationFrameHost_13b9t5ng02](https://user-images.githubusercontent.com/30538130/152585474-ea5cf846-3ec6-4af0-9257-aa96dfcd2d4f.png)
![Eco_LOTMOXz5Bp](https://user-images.githubusercontent.com/30538130/152585668-6f6334f9-499a-4c70-9666-586e22edd82f.gif)

**Comment by IcedForge** [comment] 2022-02-08 15:33
Hello, sorry for the confusion and we are looking a bit into more ways of refining how we display and word things
But for this scenario everything is working 100% correctly (mechanically speaking) as what you selected as restriction in the work party is "Carpenter - the profession" not "Carpentry - the actual specialty skill
![Screenshot_42](https://user-images.githubusercontent.com/24981362/153019261-3370a75e-8409-4f57-ae92-5e795cde3f5e.jpg)
![Screenshot_43](https://user-images.githubusercontent.com/24981362/153019749-d6faceed-99e1-469b-b53d-4e981fe6e73f.jpg)

As you can see in the next one, i dont have carpentry but i have logging which is a carpenter profession resulting in me having level 1 due to 1 skill learned in it (represented by stars next to them in the skill ui
![Screenshot_44](https://user-images.githubusercontent.com/24981362/153019974-3f89c3f2-74e2-4825-ba2d-d59d24fcb3db.jpg)
Will close this as working as intended but we do want to change the names of some of the professions in the future to avoid confusions and also make them a lot easier to understand the difference between the two.

**Closed by IcedForge** 2022-02-08 15:33 UTC

**Comment by KevinGelking** [comment] 2022-02-08 15:46
No need to reopen the issue, but perhaps it would already help if the progress bars towards the next level were shown 'in bigger' in the header section of each page, respectively.

This way, it might be clearer that there are two separate levels involved - the accumulated profession skill and a selection of specialties.
Currently, the progress bars don't seem to move, are very tiny and the number on them is also quite hard to read, especially for older people that might be interested in the game.

E.g. something like
![image](https://user-images.githubusercontent.com/30538130/153022596-1b97fc14-cc30-4d39-b4ae-951c21977e40.png)


Thanks for taking the time to get back to me so thoroughly about the issue I reported; it had started making sense to me only yesterday when I first set up a demographic and saw there's Carpenter and Carpentry separately.
