### ISSUE TITLE
Prevent pollution - Owner not recognized

### ISSUE THREAD

**Issue by surcoufx83** [StrangeLoopGames/EcoIssues#7923] opened 2018-05-28 13:19 UTC
Dear support,

we created a new law that should prevent emitting polution if taxes are not paid.
That worked fine but for the cars. If you use a car that emitts polution you won't be able using it, as it always states, that no owner is defined. Also placing it in your claimed land wont help
![2018-05-28 15_17_01-eco](https://user-images.githubusercontent.com/1303974/40616150-395db316-628a-11e8-92a5-fafb95f26c86.png)

The only thing that helped was:
- Shutdown server
- Make myself Admin (in Users.eco file)
- Start server
After that I was able paying taxes and driving the car. But that's not as expected and should be fixed.

**Comment by MarjieAVolk** [comment] 2018-05-31 17:54
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7931

**Closed by MarjieAVolk** 2018-05-31 17:54 UTC
Labels: Medium Priority
