### ISSUE TITLE
USER ISSUE: Getting disconnected while reparing road tool

### ISSUE THREAD

**Issue by GibsonSWE** [StrangeLoopGames/EcoIssues#3820] opened 2018-02-03 06:46 UTC
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
I just try to repair the road tool in the repair table. But Im getting disconnected and getting an error. Any other tool is fine.

**Expected behavior:**
It should just repair the tool.

**Actual behavior:**
It gives me this:

Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on LimitedInventory!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Skills.RequiresSkillAttribute.get_Description()
   at Eco.Gameplay.Components.RepairComponent.RepairSlotChanged(User user)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by Conchipedia** [comment] 2018-02-03 16:20
duplicate of 
**USER ISSUE: Road Tool + Repair Station, Game Crach #3485**

**Comment by MarjieAVolk** [comment] 2018-02-03 22:12
This is fixed in the latest staging

**Closed by MarjieAVolk** 2018-02-03 22:12 UTC
Labels: High Priority
