### ISSUE TITLE
Server website can't login Query string

### ISSUE THREAD

**Issue by Tisax190** [StrangeLoopGames/EcoIssues#6195] opened 2018-03-17 17:32 UTC
Steam autorise special char that are used into the querry string to login on the server website.
Then i can't login to the site and can't vote for a law or smth else.

My steam name was .#Tisax190

**Comment by MarjieAVolk** [comment] 2018-03-22 21:35
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6206.  Thanks for the name example.

**Closed by MarjieAVolk** 2018-03-22 21:35 UTC
Labels: Medium Priority
