### ISSUE TITLE
USER ISSUE: Item Transfer Bug

### ISSUE THREAD

**Issue by Fyredrake** [StrangeLoopGames/EcoIssues#5210] opened 2018-02-28 05:15 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Move an item between any two inventories

**Expected behavior:**
The item should have moved

**Actual behavior:**
Does not move. Item icon gets stuck floating onscreen and the items are not moved. Alt-tabbing is a temp "reset" from the bug, but it will always happen again.

**Comment by MarjieAVolk** [comment] 2018-02-28 20:10
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-02-28 20:10 UTC
