### ISSUE TITLE
Alpha.6 [B8ce025e] Weird fuel consumtion

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2302] opened 2017-09-26 19:30 UTC
Crafted:
![image](https://user-images.githubusercontent.com/1900106/30880089-c0f72da0-a301-11e7-8f55-137089234d6e.png)

Fuel consumtion while crafting:
![peek 2017-09-26 21-27](https://user-images.githubusercontent.com/1900106/30880067-b2bb1472-a301-11e7-854e-e2dd718b0ab0.gif)

**Comment by MarjieAVolk** [comment] 2017-09-26 20:28
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1893

**Closed by MarjieAVolk** 2017-09-26 20:28 UTC
