### ISSUE TITLE
USER ISSUE: Torch Sound Looping

### ISSUE THREAD

**Issue by Datsun-Drift** [StrangeLoopGames/EcoIssues#24165] opened 2023-12-13 05:06 UTC
\
**User Id: (slg214322)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Equip then un-equip the torch.

**Expected behavior:**
Sound stops when torch is put away.

**Actual behavior:**
Sound continues

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13656336/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13656337/Player-prev.log)

**Comment by Datsun-Drift** [comment] 2023-12-13 05:08
Additional Info: Torch sound is location based. Where you are when un-equipping is where the sound remains afterwards.

**Comment by D3nnis3n** [comment] 2023-12-15 14:01
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24155

**Closed by D3nnis3n** 2023-12-15 14:01 UTC
