### ISSUE TITLE
Barrels broken in 9.4

### ISSUE THREAD

**Issue by RancidMilk** [StrangeLoopGames/EcoIssues#22556] opened 2021-08-22 11:59 UTC
When my Oil refinery consumes barrels of petroleum, I no longer get the barrels back.

**Comment by SlayksWood** [comment] 2021-08-23 11:00
@RancidMilk Thank you fro the report. Can you provide more details? I can't reproduce:
- start Epoxy order:
![image](https://user-images.githubusercontent.com/45708377/130435858-d29de939-3820-4a78-950b-a4776dc9fe2c.png)
![image](https://user-images.githubusercontent.com/45708377/130435891-a6ac9671-df36-4a94-a66a-b554595f958a.png)
- Barrels was returned:
![image](https://user-images.githubusercontent.com/45708377/130436494-0ad007eb-0d55-4435-85a7-07f4c132ef91.png)
![image](https://user-images.githubusercontent.com/45708377/130436730-ca5614e3-1364-4435-9eaf-fc0f8b4d7470.png)

**Comment by RancidMilk** [comment] 2021-08-23 11:47
I have 4 jacks feeding from and to a stockpile, and a refinery that is
feeding from and to the same stockpile. I have been producing epoxy when I
noticed the issue.

One comment I read was that barrels dissappear if the
production/consumption value is non whole, barrels will dissappear.  This
likely points to a rounding error. For instance, if with modules, it takes
0.9 barrels to produce an epoxy, a floor or loss of precision due to a
float being stored to an int would lead to 0 being output.

Hope that helps!

**Comment by D3nnis3n** [comment] 2021-08-29 11:02
Do ALL barrels disappear or just some? The latter is intended.

**Comment by RancidMilk** [comment] 2021-08-29 16:54
I just checked into it, and this could be the issue I was seeing. I didn't
realize you got less barrels out then what you put in. Feel free to close
this issue.

**Comment by D3nnis3n** [comment] 2021-08-29 18:16
Around 25% of barrels are lost due to wear and tear, that is intended. Given you state this would likely be the cause, I'm closing this issue :)

**Closed by D3nnis3n** 2021-08-29 18:16 UTC
Labels: Status: Needs Information
