### ISSUE TITLE
USER ISSUE: Tool Durability Display Bug

### ISSUE THREAD

**Issue by echoAwoo** [StrangeLoopGames/EcoIssues#23598] opened 2022-11-30 21:42 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.3 beta release-391

**Steps to Reproduce:**
Insert tool into Repair slot in Repairbench
Repair is optional
Remove tool from Repair slot in Repairbench
Observe Tool Durability display bar is missing, whether repaired or not. 
Stays this way until used. 

**Expected behavior:**
Always display durability bar

**Actual behavior:**
Hides durability bar after removing tool from repairbench, whether repaired or not

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment] 2022-12-01 08:47
@echoAwoo Thank you for the report. I can confirm the issue, you will lost durability bar if you move item to toolbar from any storage.
Internal: ECO-25781

**Comment by D3nnis3n** [comment] 2024-11-29 10:52
Closing due to issue no longer applicable, as a new durability system was introduced.

**Closed by D3nnis3n** 2024-11-29 10:52 UTC
Labels: Type: Bug
