### ISSUE TITLE
USER ISSUE: Chopping tree throws you back to the main menu

### ISSUE THREAD

**Issue by Mezilsa** [StrangeLoopGames/EcoIssues#5853] opened 2018-03-10 18:56 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Host a game
2. Kill a tree
3. close the game
4. reopen the game
5. Hit the tree with an axe and watch you getting thrown back to the main menu

**Expected behavior:**
The axe should have cut the tree.

**Actual behavior:**
The following error message popped up:
```Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   bei Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   bei Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   bei Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   bei Eco.M

**Comment by MarjieAVolk** [comment] 2018-03-12 22:07
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-03-12 22:07 UTC
