### ISSUE TITLE
USER ISSUE: Bug Menu no show

### ISSUE THREAD

**Issue by koondiwza2015** [StrangeLoopGames/EcoIssues#4032] opened 2018-02-07 06:16 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Comment by midn8t** [comment] 2018-02-07 06:25
its user tooken login issue 

https://github.com/StrangeLoopGames/EcoIssues/issues/4027

**Comment by Nanders** [comment] 2018-02-07 18:16
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4027

**Closed by Nanders** 2018-02-07 18:16 UTC
