### ISSUE TITLE
USER ISSUE: Fish Trap not placeable under water

### ISSUE THREAD

**Issue by Irawulf** [StrangeLoopGames/EcoIssues#11452] opened 2019-02-21 21:33 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
try to place a fish trap in the ocean, a lake or river

**Expected behavior:**
you should be able to place it under water

**Actual behavior:**
an error message says "object can not be placed"

**Do you have mods installed? Does issue happen when no mods are installed?:**
an error message says "object can not be placed"

**Comment by elfl0rd** [comment] 2019-02-21 22:28
Duplicate of #10849

**Closed by elfl0rd** 2019-02-21 22:28 UTC
