### ISSUE TITLE
[7.4 bleeding edge] Server crashing on load after garbage bags have decomposed(?)

### ISSUE THREAD

**Issue by turnburgler** [StrangeLoopGames/EcoIssues#7567] opened 2018-05-03 13:28 UTC
After restarting the server today i keep getting this message followed by "ecoserver has stopped working". 

7.4 bleeding edge dedicated launcher through steam.

> [27:14] Loading Rooms... Finished in 8,3ms
> [27:14] Starting ObjectivePlugin... Finished in 17,0ms
> [27:14] Loading Objectives... Finished in 0,9ms
> [27:14] Starting Legislation... Finished in 347,6ms
> [27:14] Loading Laws... Finished in 9,4ms
> 
> Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Eco.Gameplay.Items.GarbageBagBlock.UpdateVisuals()
>    at Eco.Gameplay.Garbage.GarbageManager.Initialize()
>    --- End of inner exception stack trace ---
>    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    at System.Activator.CreateInstance(Type type, Object[] args)
>    at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
>    at System.Threading.Tasks.Task.Execute()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at Eco.Server.PluginManager..ctor()
>    at Eco.Server.Startup.Start(String[] args)
>    at Eco.Server.MainClass.Main(String[] args)

**Comment by turnburgler** [comment] 2018-05-08 18:42
Eco Server 0.7.5.0 beta staging-7be2f02c

Still cannot launch my previous world after converting to 7.5...

> Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Items.DecayingInventory.get_AverageDecay()
   at Eco.Gameplay.Items.GarbageBagBlock.UpdateVisuals()
   at Eco.Gameplay.Garbage.GarbageManager.Initialize()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

**Comment by craig-jong** [comment] 2018-05-14 21:28
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7687

But this is also fixed in the latest build.

**Closed by craig-jong** 2018-05-14 21:28 UTC
Labels: High Priority
