### ISSUE TITLE
Add ability to join servers via weblink

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#20799] opened 2021-03-02 05:05 UTC
Steam offers the ability to join servers directly via a link. Large servers have requested this feature so their can feature their Eco servers on their website. If we can do this directly through Steam, it would be ideal.  If we can do it without Steam, that is good too. Here is an example link:

steam://connect/xxx.xxx.xxx.xxx:xxxx

Something many of these games have in common, the servers are viewable directly by Steam. From the Steam Client, you can go to View -> Servers to see a list of servers. This part is not necessary, but it might be required to enable this feature.

**Comment by mirasrael** [comment] 2021-03-02 12:32
steam://run/382310//+connect=server_id
may be used (we already have lobby support from command arg, it may be extended for server id support).
It will ask user for confirmation for extra argument though (for security reasons)

**Comment by redwyre** [comment] 2021-03-02 12:57
A steam link will only work with steam installs, if we create our own it will work for all users. While non-steam is a supported option I think we should be creating solutions that work for all users.

Also IPs should be avoided when connecting to eco servers as using a server ID will work in cases where IP will not.

So my suggestion is:
`eco://join/server_id` eg `eco://join/1901d46d-d6e9-4bd6-8c66-c05d59d59e69`

Which is a bit more work:
* windows implementation (I already have the research done for this)
* linux implementation
* macOS implementation

**Comment by redwyre** [comment] 2021-04-18 16:33
Some resources:
**Linux:** 
https://askubuntu.com/questions/514125/url-protocol-handlers-in-basic-ubuntu-desktop
**macOS:**
https://support.shotgunsoftware.com/hc/en-us/community/posts/209485898-Launching-External-Applications-using-Custom-Protocols-under-OSX
https://hublog.hubmed.org/archives/001154
**Windows:**
https://www.meziantou.net/registering-an-application-to-a-uri-scheme-using-net.htm
https://www.brad-smith.info/blog/archives/842

**Comment by IcedForge** [comment] 2021-06-03 13:09
Ran this through the ringer today and there is a few issues with it.

1. The parameter is dependent on the new ClientSetupUtility.exe to be run beforehand (Manually).
2. If files are moved, or installed in another directory/changed in ANY way this will no longer work.
3. If it is not linked in the first place, its just gonna poof it in the browser as a search attempt.

Solutions -
1. This needs to be ran on install or co executed when starting Eco.exe.
2. As per above having it automatically run each time you start up the game would guarantee that its always synced to the correct location and is user friendly from QA point of view as well where "If it doesnt work, try start the game once and try again"
3. Not sure if this is solvable as its on user end but the 2 above mentioned solutions should eliminate this in 99% cases.

**Comment by IcedForge** [comment] 2021-06-03 13:10
Error if i move install folder which is confusing since i have the game installed?
![Screenshot_73.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f60eaf61-ceb8-49b2-9abb-a3b6f0e5f560)

**Comment by thetestgame** [comment] 2021-06-03 15:45
> Ran this through the ringer today and there is a few issues with it.
> 
> 1. The parameter is dependent on the new ClientSetupUtility.exe to be run beforehand (Manually).
> 2. If files are moved, or installed in another directory/changed in ANY way this will no longer work.
> 3. If it is not linked in the first place, its just gonna poof it in the browser as a search attempt.
> 
> Solutions -
> 
> 1. This needs to be ran on install or co executed when starting Eco.exe.
> 2. As per above having it automatically run each time you start up the game would guarantee that its always synced to the correct location and is user friendly from QA point of view as well where "If it doesnt work, try start the game once and try again"
> 3. Not sure if this is solvable as its on user end but the 2 above mentioned solutions should eliminate this in 99% cases.

Its supposed to be running with the game every launch. I will have to look into it. Do you have any logs of the client? If its failing to execute ClientSetupUtility it should be logging in there.

**Comment by SlayksWood** [comment] 2021-06-11 10:44
Still doesn't work if I am not using "ClientSetupUtility.exe" by myself:
![image](https://user-images.githubusercontent.com/45708377/121674766-2564f300-cabb-11eb-9409-cddf15bf37f8.png)

**Comment by thetestgame** [comment] 2021-06-12 16:39
I am unable to reproduce on my end. Do you have any logs? I need to see why its not launching the setup utility

**Comment by Daniel-Magulado** [comment] 2021-06-18 04:35
Tested on 0.9.4 Staging-2025.

I am able to join a running server without the need to run the ClientSetupUtility.exe anymore.
Closing for now as fixed.

I'm not sure what fixed it but will keep an eye on this and will reopen it if needed.

**Closed by Daniel-Magulado** 2021-06-18 04:35 UTC
Labels: Category: Tech, Squad: Pumpkin, Status: Not reproduced, Status: Reopen, Type: Feature
