### ISSUE TITLE
USER ISSUE: DM are redirected

### ISSUE THREAD

**Issue by HNKOP** [StrangeLoopGames/EcoIssues#24834] opened 2024-03-19 07:41 UTC
\
**User Id: (slg228272)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
1. On the server we have a man with two squares as his nickname (id 18281334)
2. Was trying to DM Mavr, another guy in the server (id 1644897)
3. After sending the message to Mavr, two squares became a receiver

**Expected behavior:**
While DM to Mavr, the receiver should be Mavr

**Actual behavior:**
The receiver is Two Squares

**Do you have mods installed? Does the issue happen when no mods are installed?:**
The issue is reproduced on coast redwood official server

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

<img width="96" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/22029556/558c88a0-96b9-4559-984f-51dc0877d437">
<img width="92" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/22029556/f5d4871e-824e-4751-a136-c3b321b77c02">

**Comment by D3nnis3n** [comment] 2024-03-19 15:50
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24832

**Closed by D3nnis3n** 2024-03-19 15:50 UTC
