### ISSUE TITLE
[0.8.1.1 release-preview] Can`t launch server

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11928] opened 2019-04-09 06:42 UTC
[0.8.1.1 release-preview]
no mods

Trying to launch server with empty storage folder and getting error

> [11:40:05] Failed to load server, Exception was Exception: ArgumentException
> Message:World layer TunaCapacity voxels-per-entry (40) must evenly divide the world size ((700, 700))!
> Source:Eco.Simulation
> 
> System.ArgumentException: World layer TunaCapacity voxels-per-entry (40) must evenly divide the world size ((700, 700))!
>    at Eco.Simulation.WorldLayers.WorldLayerManager.InitLayers(LayerInitOperation operation)
>    at Eco.Simulation.EcoSim.Regenerate()

*Steps*
1) check if  \Steam\steamapps\common\Eco\Eco_Data\Server\Storage is empty
2) Launch EcoServer

**Comment by mirasrael** [comment] 2019-04-09 07:55
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11927

**Comment by mirasrael** [comment] 2019-04-09 07:56
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11576

**Closed** 2019-04-09 07:57 UTC
Labels: High Priority, Quality Assurance
