### ISSUE TITLE
Server - Network plugin randomly spiking to high utilisation, causing frequent block lag and timeouts.

### ISSUE THREAD

**Issue by vsysio** [StrangeLoopGames/EcoIssues#11405] opened 2019-02-19 01:14 UTC
Hey folks,

Got a weird one here. Maybe. Not sure if it's a VM artifact or a legit known issue. Posted this on #server-talk in Discord and had no response so I'm assuming it's not.

Observe (ignore the CPU usage graph as when I took the screen shot the VM was doing something else and is thus not representative of the issue):

Tick times (not sure if high or what):
![image](https://user-images.githubusercontent.com/40701885/52983513-7c5dd000-33b9-11e9-81bd-de49b6ac9049.png)

CPU usage of Network threads (ignore task manager CPU graph; the server was also doing something else):
![image](https://user-images.githubusercontent.com/40701885/52983537-93042700-33b9-11e9-9ba9-3469d5cb7743.png)

Maybe relevant; Wireshark indicates about 10-15% of DIS packets are malformed (although apparently this is common as I guess Wireshark's DIS interpreter sucks). This does not appear to increase in frequency while the server is going all apey.
![image](https://user-images.githubusercontent.com/40701885/52983561-aca56e80-33b9-11e9-827f-94f1060c0a86.png)

When the server has more than a couple of people on it, dozens of times times per hour and for upwards of a minute each time in the worst case, the following symptoms are observed:

* As shown in the above screenshot, the "CPU" for several players spikes to a high amount and stops "updating" for a period of time (sometimes affects all players, sometimes does not)
* Players attempting to join the server are either met with a timeout or a load time in excess of several minutes
* As discovered through process explorer, several threads (up to 15 in the worst cases) spike to high utilization. Getting a stack trace for these threads is tricky because process explorer has difficulty keeping up, but judging from the function names it seems to possibly be related to route probing in clr.dll?
* VM CPU utilization also increases to a high amount, and appears to "plateau" at a point, but rarely hits 100%, often settling between 50-85%
* Ticking times don't seem to increase significantly (other than a a slight increase possibly due to resource contention)
* Speaking of tick times, they're about 90 seconds (also in attached image)

The database is also fairly large (approaching a gig at this point). The server has 8 GB of RAM without a pagefile and has never exceeded 6 GB of usage.

Server configuration:

* XenServer 7.5
* CPU: Xeon E5-1680-v4 (8 cores 16 threads @ 3.40Ghz and 20MB of L3)
* 64GB ECC RAM
* Paravirtualised Windows drivers (Switching to HVM made no difference)
* IOMMU is used (obviously) and Xen is working with EPT
* SR-IOV is not being used  
* Hosted in a datacenter in Montreal and has a gigabit connection; essentially zero observable packetloss (and is about the same when checking domU or dom0)
* Very light load - Server was originally used by me to crunch numbers for a client of mine but they went out of business but is still under lease (I'm also using it for E-mail, Single-Sign-On and ownCloud for 4 of my employees)

VM configuration:

* Windows Server 2016
* 8 vCPUs

Game configuration:

* 4k map (200x200)
* No mods
* WaterLevel 60
* Height 160
* Custom spawn location?

Things I have tried:

* Move VM from mag drives to storage array (2x NVMes in hardware RAID0 capable of 2.5GB/sec read/write and over 100k IOPS) - No change
* Reducing save frequency from 60s to 10 minutes - No change
* Adding CPU cores (up to 8 cores 12 threads) - No change
* Reducing simulation time - No change
* Change simulation.RecordEveryLayer from Interval to Every Change - No Change
* Change Network.Rate from 20 to 10 and then 35 - No change
* Change WorldObjects.Parallel World Object Ticks from false to true - No change
* Change WorldTickCPUMax all over the place - 0.50, 0.75, 0.25, 1.0 - No change
* Investigate process with process explorer to see if it's localised to one biome or many - When occurring over a dozen threads hit high utilisation so I'm assuming it's not localised to one biome ie. a bigass pile of 50,000 loose stone

**Comment by vsysio** [comment] 2019-02-19 02:04
Follow-up:

Working to rule out the VM, I copied the entire thing to my local machine, which has an (admittedly) weaker CPU (an AMD Ryzen 2400G). Here's a snapshot of the world layers tab: 

![image](https://user-images.githubusercontent.com/40701885/52985213-d3b36e80-33c0-11e9-817d-462a0e2231a0.png)

**Comment by pamduncan** [comment] 2019-02-19 16:25
Have you tried disabling "UPnPEnabled"  WM has always been a issue for Eco at least in my experience and peaking CPU is one of the many issues that we have seen over the years and why we don't offer VM servers for Eco.  We have see the use of the UPnP device trying to run and creating a error state when it cant find an enabled UPnP device and its an issue especially if you are not behind a NAT or you do not have the UPnP device in the router or if you do its not enabled.  If you have run any other game servers through that router since most disable UPnP you probably have it disabled if your router has the option.   Enabling the UpnP device is to see if that helps servers that have been having connection issues by allowing it to do network mapping.  In cases where a server is in a data center and there is not a router  but as its enabled by default so it tries to do network mapping although there is not really a UPnP device to set it up to do so  and there have been some vert odd networking connection issues.  We have resolved this by disabling the setting.  If you do not have it in your Network.eco it is still enabled by default and you would need to add it and set it to false.  I don't know that that is your full issue as there are also many VM issues that could be op[art of the problem.  But if you do not have a router with an active/enabled UPnP device then I would "UPnPEnabled": false and restart your server and see if that helps you at all.

**Comment by vsysio** [comment] 2019-02-19 23:11
UPnP disabled and server restarted - No change.

**Comment by vsysio** [comment] 2019-02-21 05:20
Moved to new bare metal host with a different hypervisor (before, XenServer, now, ESXi) - No change

**Comment by vsysio** [comment] 2019-02-21 16:23
I 7zipped the complete contents of my server directory into an archive and uploaded it to AWS S3: https://vsysio.s3.amazonaws.com/Eco.7z

Note almost all configuration parameters had been changed at some point to try and debug the problem

**Comment by vsysio** [comment] 2019-02-22 15:47
I enabled Large and Huge Page support in ESXi. Not sure if the game will actually use it, but as I suspect TLB thrashing (since the game spawns so many threads and virtualization typically has issues with TLB thrash) we'll see if this works.

**Comment by vsysio** [comment] 2019-02-22 18:27
https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.resmgmt.doc/GUID-F0E284A5-A6DD-477E-B80B-8EFDF814EE01.html this change was made to the hypervisor.

Entire host box was rebooted after this change. VM memory was also configured to locked so it didn't page to ESXi swap or fall victim to idle reaping. Large (not huge) pages were also confirmed enabled in ESXi's host config.

Within Windows Server, the process user for the server was given permission to lock memory pages via gpedit.msc.

Server has been running for over two hours with no observable thrashing behavior. This is with an average of 2-3 players. 

The issue had been previously exacerbated with more players and became entirely unplayable after about 6-8 players were online. However, with the issue ongoing this week, the server population has effectively moved on and no longer plays on this server, so I am unable to confirm that it is fully corrected under load; although the issue did appear when the server was not under load, it was more infrequent (ie. once every 5 minutes) and resolved much more quickly.

**Comment by vsysio** [comment] 2019-02-22 21:23
Issue still present...

**Comment by lordmampf** [comment] 2019-02-22 21:41
I can now confirm that a huge server also has this issue.
Running on an simimlar environment.

**Comment by lordmampf** [comment] 2019-02-22 23:09
@vsysio Can you check your WorldObject Page?
I have very high campfire ticks..

![campfire](https://user-images.githubusercontent.com/1554111/53276431-3bd6bd00-36ff-11e9-87c5-fef1d1e30c22.png)

**Comment by vsysio** [comment] 2019-02-22 23:13
Cool! Yeah, I had nothing like that. None of my world objects ticks had more than a couple of milliseconds.

**Comment by DragonSupremacy** [comment] 2019-02-23 00:18
After being hit by a similar issue as @vsysio, I too was hit by the sight of 'entering world' for a while before being able to log in again. What seemed to have fixed the issue for now, is to disable stat reads and writes, saving the Server UI, then enabling it back. It caused some major CPU spikes and lag for players shortly after, but it seems to be back to normal. 

DB is in the 1,6gb range and running on Day 16 at the moment

**Comment by vsysio** [comment] 2019-02-23 08:46
Nuked entire host from orbit and installed Windows Server 2016 Standard on bare metal.

Same issue ........ Virtualization ruled out?

**Comment by DragonSupremacy** [comment] 2019-02-24 00:11
Update: stat disabling/re-enabling fixes the issue whenever the CPU is hogged down by "something", however after a few hours the server tends to not like keeping people connected and starts the process of kicking people every few minutes all over again. Noticed below world object ticks to be abnormally high, with chunks not loading properly for a while before giving it another reboot.

I did notice 336 instances of a Null Reference Exception when trying to remove an object in the DB, so I'll be removing those in the morning to see how that helps things. It's likely these are the accumulated stat timeouts over the lifetime of the map, now going into Day 18.

![high tick rate](https://user-images.githubusercontent.com/841990/53293253-b28fbb00-37d0-11e9-95ad-99439a8e2959.jpg)

**Comment by DragonSupremacy** [comment] 2019-02-24 12:31
Spent the better part of 1.5 hours cleaning up all these PlaceActions in the db. Entering world seems to be quicker so far. Remains to be seen how stable the server will be.

**Comment by lordmampf** [comment] 2019-02-25 17:25
What kind of NullReferenceExceptions are there?

If you want to test on other hardware you can contact me on discord: mampf#6606
(Just is case you think this might be a thing)

**Comment by DragonSupremacy** [comment] 2019-02-26 11:20
Basically every time a stat write timeout occurs, the server later tries to reference it when trying to remove/place a block there, thus clogging the server. 

I've later found that a player using the webpage map (serverIP:3001 by default) caused major CPU spikes on the player using it

**Comment by mirasrael** [comment] 2019-02-28 07:39
In next patch we improved World Layers CPU impact and stat db locks. So lets see how it will work on 0.8.0.5.

**Comment by vsysio** [comment] 2019-02-28 13:59
So as an update, we ended up resetting the entire save and starting from scratch, running on bare metal instead of under a hypervisor as before.

This issue has not recurred. Actually, it's been almost a week now and the server has ballooned to over 250 users with zero performance issues.

Excited to see what 0.8.0.5 brings.

**Comment by mirasrael** [comment] 2019-03-01 06:13
Ok. I'm closing this issue for now. Thanks for perfect report. Let see if we will have another similar reports after 8.0.5.

**Comment by Praefator** [comment] 2019-03-01 11:17
If anything it got worse after 8.0.5 - joining the world takes a few minutes, where before the DB cleanup it was 10-20 seconds at most. See included screenshot for the network tab
![capture-high cpu](https://user-images.githubusercontent.com/841990/53634912-dbbeaa00-3c1b-11e9-9151-fe3c75974a8e.JPG)

**Comment by vsysio** [comment] 2019-03-01 13:07
Issue is not fixed, please reopen. It is now occurring on our 8.0.5 world on a bare metal host running Windows Server 2016

**Comment by vsysio** [comment] 2019-03-01 13:14
If the nature of the stat DB writes necessitate them to be globally blocking, is it possible for them to be paced out? Such as, keep the pending changes in memory and write them in chunks as opposed to all at once?

Also, have you (the SLG dev team) considered an In-memory DB instead? Something like Redis, memcached or even (if you want to get real fancy) something like Apache Ignite? They're all document DBs (although Ignite is a bit weird), and while they are file-backed, they may offer much more superior performance than liteDB.

**Comment by D3nnis3n** [comment] 2019-03-01 17:55
LiteDB is not able to support concurrent writes it seems, that needs to be changed.

**Comment by vsysio** [comment] 2019-03-01 18:17
That's nuts for a document store to not do concurrency; the load characteristics pretty much call for it lol. Are you guys using an ORM or something custom? LiteDB talks BSON so MongoDB isn't that far of a stretch.

(Totally not a hint or anything but I am looking for work nudge nudge...)

**Comment by vsysio** [comment] 2019-03-04 00:17
So, I'm not sure if it's a concurrency issue now. 

Yesterday, I did some truly insane things to try and resolve this or at least partially mitigate it since half of the server population has already left to play other games because of this issue. We now have a bunch of Civ and Stonehearth players on our Discord, and Minecraft is starting to gain popularity.

1. I moved the entire server to a RAM drive. No copy-on-write or any fancy persistence features built into the host OS. I wrote a backup script for persistence that runs at idle priority once an hour some ease of mind, plus some shutdown and startup scripts that handle OS reboots gracefully, but for most intents and purposes it was just a good ol' fashioned RAM drive with no fancy features. 
My line of thinking here is if it is a concurrency issue, and it's bound to file access locks, perhaps that can be mitigated by reducing those lock times to sub-microsecond times instead of milliseconds. 
No change (although the server loads in about 6 seconds now).
2. I tried to DOS my own server. Here I tried to reproduce the problem by putting strain on the DB, and I did this by having everybody on the server (about 6 people) load up the stats webpage and just add randomly click on every single graph item they could find, for players, for the world, for food everything etc. While server CPU spiked to 100% across all cores (and this remained consistent for about 15 minutes after browsers were closed), the ingame block-hang and network thread CPU issue could not be reproduced via this method.
3. We instituted an hourly (!) reset practice whereby a script activates every hour and restarts the server. Oddly enough this actually resolved a lot of the network thread issues!
4. Experimenting with stat settings, I noticed that turning off stat writes while this bug is occurring does not stop them, but turning off stat reads kills it immediately (and breaks half the game in the process). If file lock concurrency was a theory, this would not seem to support that theory.

I'm beginning to think that a lot of the characteristics of this bug are actually just symptoms of a much more obscured issue.

Or perhaps we're looking in the wrong direction?

In both cases, the issue occurred almost immediately after a patch was released. Could this be another direction to investigate?

**Comment by mirasrael** [comment] 2019-03-04 07:17
@vsysio 
0.8.0.5 was introduced two things:
- reduced priority for world layers calculation, so they won't stop other threads from processing (including network threads)
- isolated transactions system for LiteDb. It should prevent write operations be blocked by read operations and read operations to not be blocked by any kind of operations (so multiple reads in parallel and reads while writes performed should be possible).
If you disable stat reads and writes at all - do you have this issue?

**Comment by vsysio** [comment] 2019-03-04 08:01
@mirasrael Disabling stat writes has no effect, disabling stat reads stops it immediately.

**Comment by Praefator** [comment] 2019-03-05 00:23
Well I've been thinking - by default the backup kicks in after roughly an hour. Perhaps a solution should be sought in that area? @vsysio perhaps try disabling backups through the server, but make snapshots or other backups externally?

**Comment by D3nnis3n** [comment] 2019-03-05 06:09
Then there are two issues now. Disabling stat WRITES fixes mine. But that one i have since i state hosting Eco Servers with a lot of concurrent players (40 - 70). Mine is not new, but shows the same and even more extreme CPU spikes.

**Comment by D3nnis3n** [comment] 2019-03-05 06:22
I use a pretty similar setup, world is the same, ram is 32 GB. Using a 8700K, allocated 8 vcpus but can also see this directly in a dedicated machine. Using Windows Server 2019 since some months, though. Usually 40% CPU usage with the spikes to 90%, more regularily than backups could be and way more than yours. NVME-SSDs.

**Comment by vsysio** [comment] 2019-03-05 10:39
@Praefator That's what I'm doing. Built-in backups were one of the first things to be disabled when converting things to run on a RAM drive. I'm already doing backups externally.

@D3nnis3n just a thought, but one approach I've seen other developers take to address TLB thrashing (easily caused when there's a crapload of threads switching context around) is to use Huge Pages where you lock entire 1GB chunks in memory and address them as a handful of single 1GB pages instead of breaking things down into hundreds of thousands of tiny itty bitty 4k pieces (each of which requires a row in the TLB). I come from the Linux world where this is done with relative frequency and I'm not sure how close you guys are to the metal, so not sure how well it would play with .NET, but with some multithreaded loads I've seen it deliver massive performance boosts. The 8700K has 12 MB of L3 cache while my server only has 8 MB of L3; this offers some evidence that this may help as my server can only handle a number that seems proportional to the amount of cache you have (starts to grind on day 1 with 40). Note that on Windows you do need to explicitly provide permission to the user running the application through Group Policy as it's an easy way for somebody writing malicious code to DoS a desktop machine.

**Comment by D3nnis3n** [comment] 2019-03-05 10:42
I'll be getting a 9900K for the server next month, will be monitoring changes closely. Has more cache and more single and multi thread power. I wonder if there is any CPU that can handle Eco fine at the moment, lol.

**Comment by vsysio** [comment] 2019-03-05 10:49
You guys wanna run an insane experiment? What about hosting a busy server on a leased machine/AWS VM that uses a CPU with a ludicrous-mode CPU (ie. 35 MB of L3) and limiting the process to only run on a handful of cores? If the problem is linear and related to the amount of CPU cache then that might provide some evidence you can use to build a case for optimization in this direction.

**Comment by Praefator** [comment] 2019-03-05 11:10
I’ll be upgrading to a Threadripper 2920x either by month’s end or month thereafter (depending on when bonus clears), so will post back if the issue still exists by then

**Comment by vsysio** [comment] 2019-03-05 11:14
@Praefator I bet you a buffalo nickle the Threadripper will make the issue 10x worse. It has 32MB of L3 cache which works great if unit sizes are high and context switches are low but suffers in a dramatic way when there's a lot of context switches.

**Comment by Praefator** [comment] 2019-03-05 14:55
We'll find out soon enough. At any rate it will provide a scenario like you proposed with the ludicrous amount of cache and limiting it to let's say 16 out of 24 threads.

**Comment by vsysio** [comment] 2019-03-05 15:00
Perhaps, just keep in mind ThreadRipper’s architecture isn’t exactly standard x86. It’s pretty against the grain, so you might be surprised with the results.

Disclaimer: I’m an AMD guy too (my home machines run on Ryzen) so I’m not just being an Intel boi here :P.

**Comment by maradine** [comment] 2019-03-05 19:10
Hey friends - first time reporter.  We are running a private server with 14 total players that bounces from 1 to 10 active depending on time of day.  The server is an EC2 t3.xlarge instance dedicated to the task.  Access to the web interface is fronted through an ALB to provide encrypted auth token passing.  The host runs Windows Server 2019 v1809.  Local firewall is disabled.

During periods of more than a few players, our CPU usage spikes to around 80% and the server becomes effectively unresponsive.  This occurs intermittently, perhaps once every 5 minutes, and lasts for between 10 and 30 seconds.  During this period, the client does not appear to communicate with the server, though actions taken by the client during the gap eventually reconcile when the server catches up.

The only server console evidence I've been able to detect is in the Network display on the server console.  While the server is spiking, the CPU usage for affected players spikes beyond 1000ms.

https://imgur.com/a/Lizhju7

Interestingly, the effect is not universal to all players, but appears to be geographically bound.  It occurs to players who are in or near our commons area (houses, machinery, long-running automat jobs), but not those off on their own island.  I verified the location factor by transiting between the two groups and noting that my player is no longer affected by the spikes and can play lag free:

https://imgur.com/a/78B9Jt9

What can we do to either fix this, or provide better data so you can isolate it?  Thanks!

**Comment by D3nnis3n** [comment] 2019-03-05 19:48
To be honest, the amazon instances are just too weak to run Eco. They offer only 4vcores on cpus with extremely bad single threaded performance, We've gotten our official servers there and it was a mess. I don't think there is anything we can do about that.

**Comment by mirasrael** [comment] 2019-03-05 19:50
@maradine yes, we tried to run our hosted worlds on AWS, but they really poor in terms of CPU power even with CPU-optimized instances. We migrated to Digital Ocean after all.

**Comment by vsysio** [comment] 2019-03-05 19:55
@maradine this is really fascinating! I have to ask about the reason behind putting an ALB in front of it all. Was there any observable difference?

**Comment by maradine** [comment] 2019-03-05 20:10
Thanks for the quick responses.  I'm sorry you weren't able to get the horsepower you needed for the official servers in AWS and found a better solution.  They have been perfectly capable for our needs in the 6 and 7 alpha branches.  Everything was also going very smoothly under 8.0.5 until yesterday.  Given that I am reproducing an issue that is confirmed above in other server architectures, do you feel that AWS is in play as an issue here?  You have no data collection asks of me?

@vsysio the Eco web server operates in the clear over http, and the game client passes authentication tokens to it.  Standing up an https reverse proxy is a quick and easy fix while the game is still in alpha and the developers have arguably bigger fish to fry.  Another solution is to run an nginx reverse on the host, but I wanted the full performance envelope of the host on the game, not my security enhancements.  You can see the result at https://ecoweb.fkpk.org.

**Comment by vsysio** [comment] 2019-03-05 20:38
@D3nnis3n is there any buy-in on the idea of moving the game from a file-based internal DB to an external memory-based DB? Are we certain the weakness is with liteDB?

**Comment by D3nnis3n** [comment] 2019-03-05 21:08
That's something you would need to ask @mirasrael

**Comment by vsysio** [comment] 2019-03-05 21:27
I'm just thinking because Ark made that decision a long time ago, and while it took a lot of resources, it paid off in spades because now they can load balance servers with an externalised data layer providing global synchronization. You guys are already using BSON which makes me think it might be relatively easy to pull off. 

@mirasrael we beseech thee, enlighten us with your DB goodery

**Comment by maradine** [comment] 2019-03-06 04:51
On a lark, migrated the instance in question to a non-scalable instance class.  No change, but I did instrument it for more analytics, and I can confirm that when the server hangs, it's is definitely an I/O spike.

https://imgur.com/a/FlAJ1hn

**Comment by maradine** [comment] 2019-03-06 06:16
Did a process explore to isolate the IO - reads and writes to game.db.

**Comment by maradine** [comment] 2019-03-06 07:21
Also confirmed that turning off stats read and write seems to eliminate the issue.

**Closed** 2019-03-07 19:37 UTC
Labels: High Priority
