### ISSUE TITLE
USER ISSUE: ground portal

### ISSUE THREAD

**Issue by molliesfund** [StrangeLoopGames/EcoIssues#5143] opened 2018-02-26 22:24 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
if you see a huge hole in the ground tith the sky showing through, if you walk into it, you keep falling until you move out of it, but the animals can walk on it

**Expected behavior:**
sjowed ground

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-26 23:34
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861

**Closed by MarjieAVolk** 2018-02-26 23:34 UTC
