### ISSUE TITLE
USER ISSUE: Teleporting Carts

### ISSUE THREAD

**Issue by AngryW1zard** [StrangeLoopGames/EcoIssues#24782] opened 2024-02-21 11:14 UTC
\
**User Id: (slg241882)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
1. Have any wood cart underground.
2. move items from one inventory to another in the inventory ui.

**Expected behavior:**
Nothing should disappear from where you are and the items should transfer from the inventory with no odd behavior.

**Actual behavior:**
It should have reloaded meshes in the area, to include broken rocks/ore and wooden carts will teleport to the surface. Some rocks will also teleport to the surface as well.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-02-21 13:03
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24363

**Closed by D3nnis3n** 2024-02-21 13:03 UTC
