### ISSUE TITLE
USER ISSUE: Extreme fps drop

### ISSUE THREAD

**Issue by cucu24** [StrangeLoopGames/EcoIssues#7714] opened 2018-05-11 15:55 UTC
**Version:** 0.7.4.2 beta

**Steps to Reproduce:**
Just playing the game more then 10 minutes

**Expected behavior:**
a lag free and fps stable game experience

**Actual behavior:**
game falls every 5 minute to 1 fps for like 15 to 30 seconds

<details>
<summary>Log File</summary>(...previous log truncated...)

57b39>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
[53:35] Exception in view notify: System.Reflection.TargetException: Non-static method requires a target.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0004c] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
[53:35] Exception in view notify: System.Reflection.TargetException: Non-static method requires a target.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0004c] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
[53:35] Exception in view notify: System.Reflection.TargetException: Non-static method requires a target.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0004c] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
[53:35] Exception in view notify: System.Reflection.TargetException: Non-static method requires a target.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0004c] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
</details>

**Comment by metachronism** [comment] 2018-05-11 23:16
dupe of #6775

**Closed by metachronism** 2018-05-11 23:16 UTC
Labels: Critical Priority
