### ISSUE TITLE
Workbench need option to craft Hewn Door

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14894] opened 2020-02-27 05:47 UTC
We have an officially supported server option to not allow any holes in houses for them to be rooms, with that option doors cannot be made, as other tables require them to be in a room. A room cannot be made without doors (or playing idiot i close my room up) That was fixed a while ago, no idea why it's back.

**Comment by WeaselDog** [comment] 2020-02-27 17:16
Will add it today

**Comment by D3nnis3n** [comment] 2020-02-28 10:02
Not fixed. Requires Carpentry, without a room you cannot learn carpentry.

**Comment by SlayksWood** [comment] 2020-02-28 10:24
We have now 2 Hewn log door. Because you can craft hewn log door before.
![image](https://user-images.githubusercontent.com/45708377/75540661-7b7c6700-5a2d-11ea-8256-6f0048649a87.png)

**Comment by D3nnis3n** [comment] 2020-03-03 01:55
We didn't at the moment i reported it. The only door that was available back then was one with carpentry requirement. This must have been changed lately.

**Comment by WeaselDog** [comment] 2020-03-03 04:40
I can confirm this was fixed by https://github.com/StrangeLoopGames/Eco/pull/5699

**Closed by WeaselDog** 2020-03-03 04:40 UTC
Labels: Priority: Medium, Status: Verified
