### ISSUE TITLE
[0.9.3 Staging-1952]Implementing an Amendment followed by an Executive Order breaks the game

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20922] opened 2021-03-12 23:01 UTC
**Build:** 0.9.3 Staging-1952

### Issue
For some reason, implementing an Amendment via finishing the election for it and following it up with an Executive Order breaks the game.

**Note:**
- The issue disconnects the player from the server.
- Trying to reconnect freezes the game in Lobby UI.
- Unable to continue the same world even if it's a solo saved game.

**Repro:**

1. Spawn gov.
2. Interact with Amendments. Draft one and submit. Do not start the election for it.
3. Interact with the Executive table. Draft an Executive order and submit it. Do not start the election for it.
4. Open Pending Elections window.
5. Observe both entries and start the election for the Executive Order first.
6. Finish the election via /fin.
7. Start the election for the Amendments.
8. Finish the election vis /fin.
9. Observe.

**Actual Result:**

1. The issue disconnects the player to the server and breaks the game.
2. The player is unable to reconnect to the same world. Trying to do so freezes the game in Lobby UI.

**Video Repro:**
_PART 1 - Triggering the issue._
https://images.zenhubusercontent.com/42199084/1359fc3f-a9d0-4aa8-a14d-9a1d4f8db5c4/part_1.mp4

_PART 2 - Trying to reconnect after the issue occurred._
https://images.zenhubusercontent.com/42199084/d44835c6-3e0e-45fb-b89b-6167b7ebf03d/part_2.mp4

Clean Game Logs
- [Clean Player Repro.log](https://app.zenhub.com/files/42199084/5ad978c3-a74a-4e98-b534-66ef8bf5d9bc/download)
- [Clean Repro Server Log.log](https://app.zenhub.com/files/42199084/619ebd39-4d85-4094-be12-9f6dc4ace5f9/download)
- [Clean Server Log.log](https://app.zenhub.com/files/47210472/0598c7bc-7be6-45f3-b7cf-75072ca64a87/download)

Supporting Game Logs
[https://app.zenhub.com/files/42199084/3dbd2d0e-5565-4560-878d-03316b9262c5/download](https://app.zenhub.com/files/42199084/3dbd2d0e-5565-4560-878d-03316b9262c5/download)
[https://app.zenhub.com/files/42199084/7fd70df0-21f9-4855-8c37-cef0c4d2892f/download](https://app.zenhub.com/files/42199084/7fd70df0-21f9-4855-8c37-cef0c4d2892f/download)
[https://app.zenhub.com/files/42199084/9f82248e-0f51-4b56-a8a7-5a6f2c3abba5/download](https://app.zenhub.com/files/42199084/9f82248e-0f51-4b56-a8a7-5a6f2c3abba5/download)
[https://app.zenhub.com/files/42199084/01712a6b-e920-4382-bec2-e7c1cd30ffee/download](https://app.zenhub.com/files/42199084/01712a6b-e920-4382-bec2-e7c1cd30ffee/download)
[https://app.zenhub.com/files/42199084/35edaaa7-c393-40fe-ae91-5bff0f2463b2/download](https://app.zenhub.com/files/42199084/35edaaa7-c393-40fe-ae91-5bff0f2463b2/download)
[https://app.zenhub.com/files/42199084/9e2d9ad5-262f-4fe6-aabf-2b6675352218/download](https://app.zenhub.com/files/42199084/9e2d9ad5-262f-4fe6-aabf-2b6675352218/download)
[https://app.zenhub.com/files/42199084/339be090-c11c-439c-af6e-55f839bf3273/download](https://app.zenhub.com/files/42199084/339be090-c11c-439c-af6e-55f839bf3273/download)

**Comment by serpopov** [comment] 2021-03-22 17:46
The issue is "actions to run once" is broken

**Comment by IcedForge** [comment] 2021-03-30 05:19
No longer getting locked outside the game or crashing out of it, only getting a softcrash/NRE

Reproduction
1. Create Executive order
2. Choose Pay/Tax/Transfer Money
3. Select any conditioning and execute


```
[07:12:06.504] [31] [Error] [Eco] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.<>c__DisplayClass12_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass2_0.<RunWithExceptionLog>b__0()
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.Gameplay.Civics.GameValues.GameValueContext`1.Value(IContextObject context)
   at Eco.Gameplay.Civics.GameValues.PersonalCurrency.Value(IContextObject action)
   at Eco.Gameplay.Civics.MoneyTransfer_LegalAction.GetAndCheckValues(IContextObject context)
   at Eco.Gameplay.Civics.AliasMoneyTransfer_LegalAction.GetAndCheckValues(IContextObject context)
   at Eco.Gameplay.Civics.MoneyTransfer_LegalAction.Do(LocString description, IContextObject action, Law law)
   at Eco.Gameplay.Civics.MoneyTransfer_LegalAction.Eco.Gameplay.Civics.Laws.ExecutiveActions.IExecutiveAction.PerformExecutiveAction(User user, IContextObject context)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.PerformBase(User executingUser)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.Perform(User executingUser, Election election)
   at Eco.Gameplay.Civics.Elections.Election.ApplyIfFinished(Boolean forceEnd)
   at Eco.Gameplay.Civics.CivicsCommands.FinishElection(User user, Election election, Boolean addVote)
```

**Comment by IcedForge** [comment] 2021-03-30 06:25
Will recheck this with the new build, it was merged in 1967

**Comment by IcedForge** [comment] 2021-03-30 07:30
Looks like its fixed with that merge, will reopen if it crops up again

**Closed by IcedForge** 2021-03-30 07:30 UTC
Labels: Category: Laws, Priority: Critical, Squad: Mountain Goat, Status: Reopen, Type: Bug
