### ISSUE TITLE
USER ISSUE: Stuck after Store

### ISSUE THREAD

**Issue by D3thM3tal** [StrangeLoopGames/EcoIssues#4805] opened 2018-02-19 05:45 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Interact with store - add some items or change the name.

**Expected behavior:**
Not lock me into place and not allow me to change what item I'm holding or open anything else.

**Actual behavior:**
Locked in place, cat se chat, cannot change hotbar item or interact with anything until I relog.

**Comment by MarjieAVolk** [comment] 2018-02-20 21:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

**Closed by MarjieAVolk** 2018-02-20 21:13 UTC
