### ISSUE TITLE
Investigate: public crafting stations not visible

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13913] opened 2019-11-28 03:50 UTC
some players reported this issue at 0.8
Owner add "everyone" access to workbench, set taxes... But workbench is not appear in public list.

Also not bad if we can see all workbenches we have access to in this tab.
Like stores.

**Comment by elfl0rd** [comment] 2019-11-28 04:00
as I observed, it in "a whole" works in 0.8 but if ceased - more not will.

**Comment by beastyn** [comment] 2019-11-28 04:21
I think this is #11973
Don't have prob;em with public tables.
Or is it something else?

**Comment by elfl0rd** [comment] 2019-11-28 04:25
No, we have public (available for everyone) workbenches, but "public crafting stations" list are empty
https://www.dropbox.com/s/g6l22rseft4xf8d/save_issue_nopubliccraftinglistGame.zip?dl=0

**Comment by WeaselDog** [comment] 2020-05-22 02:56
I am not able to reproduce this in the latest version. Please reply back if you are still experiencing this issue.

**Comment by elfl0rd** [comment] 2020-05-22 07:57
This happened sooner or later on any populated server with a lot of workbenches.

As far as I know, it wasn't fixed on purpose, so the problem probably remained.

Unfortunately, in the past six months, I have already removed the save as I needed a place in the dropbox.

**Comment by IcedForge** [comment] 2021-02-19 06:58
Will close this for now, please reopen if you encounter this problem again. I have not seen it happen on any larger public servers after 9.0 release.

**Closed by IcedForge** 2021-02-19 06:58 UTC
Labels: Status: Investigate
