### ISSUE TITLE
USER ISSUE: crashed on picking up used item

### ISSUE THREAD

**Issue by AndreasGlaser** [StrangeLoopGames/EcoIssues#4938] opened 2018-02-22 08:42 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. choped on a tree chunk
2. instantly after that pick it up
(i think that maybe the chunk object is removed before the function started bei chopping the chunk is done)

**Expected behavior:**
it shoudn't crash

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-23 19:37
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-23 19:37 UTC
