### ISSUE TITLE
Allow custom images to be used in ecopedia

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17417] opened 2020-07-30 18:01 UTC
We'll need a way for images to be sent through modding system and then referenced in the ecopedia.

**Comment by redwyre** [comment] 2020-07-31 00:42
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/17406

**Closed by redwyre** 2020-07-31 00:42 UTC
