### ISSUE TITLE
Blurry Desktop Icon

### ISSUE THREAD

**Issue by Spudmeist3r** [StrangeLoopGames/EcoIssues#11331] opened 2019-02-15 16:12 UTC
So on Medium icon size, the desktop icon is super blurry
![capture](https://user-images.githubusercontent.com/41703282/52868969-3c24f600-310a-11e9-9043-aa9a38752f9b.PNG)

**Comment by elfl0rd** [comment] 2019-02-15 16:50
Duplicate of #7063

**Closed by elfl0rd** 2019-02-15 16:50 UTC
