### ISSUE TITLE
USER ISSUE: Hit and tree and crash

### ISSUE THREAD

**Issue by Zangdar1111** [StrangeLoopGames/EcoIssues#4711] opened 2018-02-17 15:03 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
It's difficult...
We reconnected the server after a break, and we saw a long tree log that have spawned on the grown. We chop it, and it crashed with stack trace below
We were able to reconnect and shop again the log tree, every time we crashed but it chopped the tree.
When taking it into our hand, it crashed too.
We were able to put it in a stock pile
But for a second log we took in our hand, client and server crashed

**Expected behavior:**
tree shouldn't have spawn

**Actual behavior:**
Crash with:

The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   à Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   à Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by Zangdar1111** [comment] 2018-02-17 15:06
Basically seems to be an issue of log tree appearing after server reboot, but shouldn't have exist. In our memories, there was no Tree at this location.

**Comment by MarjieAVolk** [comment] 2018-02-23 21:45
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-23 21:45 UTC
