### ISSUE TITLE
USER ISSUE: Fish Stew

### ISSUE THREAD

**Issue by smatthews0** [StrangeLoopGames/EcoIssues#24883] opened 2024-04-14 10:19 UTC
\
**User Id: (slg236876)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
Open Shop,
Deselect Known item
Search Stew
Stew cannot be found

**Expected behavior:**
Fish Stew should be possible to list on Shop

**Actual behavior:**
Fish Stew Cannot be listed

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Vanilla - no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Fish Stew also isn't auto-linked when typing in in-game chat

**Comment by smatthews0** [comment] 2024-04-14 10:20
Been an issues since 2022
https://github.com/StrangeLoopGames/EcoIssues/issues/23009

**Comment by smatthews0** [comment] 2024-04-14 10:23
Fish Stew when crafted will not produce any items as well.

**Comment by IcedForge** [comment] 2024-04-14 18:50
Hi! Thank you for taking the time to report this however the Fish Stew is only an alternative recipe and the product it outputs is Meaty Stew IE you cant search for it in the list because it doesn't exist as a unique individual item.
Will close the issue as working as intended.

**Closed by IcedForge** 2024-04-14 18:50 UTC
