### ISSUE TITLE
Cannot build underwater

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#2133] opened 2017-09-15 23:05 UTC
Unable to build with dirt/logs underwater or replacing the surface

Version: v0.6.0.0-alpha-staging-3a83dd35

**Comment by MarjieAVolk** [comment] 2017-09-15 23:13
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2029

**Closed by MarjieAVolk** 2017-09-15 23:13 UTC
