### ISSUE TITLE
Glass door recipe lists the wrong glass type

### ISSUE THREAD

**Issue by styles784** [StrangeLoopGames/EcoIssues#7059] opened 2018-04-08 04:55 UTC
The recipe for the glass door says it requires 10 glass (at 0% efficiency), yet hovering over the word "Glass" or the icon at the factory reveals that it actually requires framed glass
Here is an example screenshot:
[https://cdn.discordapp.com/attachments/267240183882055681/432402608284499978/GlassDoorRecipe.jpg](url)

**Comment by MarjieAVolk** [comment] 2018-04-09 20:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6834

This is just a display error, Framed Glass is sometimes called just Glass, due to a typo.

**Comment by MarjieAVolk** [comment] 2018-04-09 20:44
But yeah, it is confusing and an easy fix, so maybe I will up the priority on the other one.

**Closed by MarjieAVolk** 2018-04-09 20:43 UTC
Labels: High Priority

**Comment by styles784** [comment] 2018-04-13 02:09
No wonder I didn't see the duplicate - I searched specifically for the door. It's not a game-breaking issue, to be sure, but I'm glad to see it's being handled :)
