### ISSUE TITLE
USER ISSUE: Error	

### ISSUE THREAD

**Issue by Chellieeeeee** [StrangeLoopGames/EcoIssues#24951] opened 2024-05-24 18:27 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
The game does not want to load into any server

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-05-24 21:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24380

**Closed by D3nnis3n** 2024-05-24 21:22 UTC

**Comment by Chellieeeeee** [comment] 2024-05-25 05:40
Good day.
How can I fix the problem?

**Comment by D3nnis3n** [comment] 2024-05-27 09:57
Please reach out to support@strangeloopgames.com for deeper investigation into your specific issue.
