### ISSUE TITLE
USER ISSUE:  can't always plant something

### ISSUE THREAD

**Issue by jamesmclaren** [StrangeLoopGames/EcoIssues#6530] opened 2018-03-27 12:02 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
sometimes when planting beans on a spot that has already been used, I get a plant already there error, even though the space is clear and hoed

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-04-03 00:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4669

**Closed by MarjieAVolk** 2018-04-03 00:32 UTC
