### ISSUE TITLE
Server keeps crashing on database lock up

### ISSUE THREAD

**Issue by LoyalExpert** [StrangeLoopGames/EcoIssues#6127] opened 2018-03-16 02:58 UTC
--BEGIN DUMP--
Dump Time
03/15/2018 21:46:32

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   at LiteDB.LockService.Read()
   at LiteDB.LiteEngine.<Find>d9.MoveNext()
   at LiteDB.LiteEngine.<Find>d13.MoveNext()
   at LiteDB.LiteCollection1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable1 source)
   at Eco.Stats.ContinuousPlayerStatManager1.RecordAction(T action)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Players.User.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Players.UserManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by Thyriel** [comment] 2018-03-16 10:04
We have the same problem on our server since yesterday. Sometimes it's running stable for hours and then locking only an hour after restart. When this happens you can't do anything in the world but no one get's kicked. If you relogg it's freeting at "entering world" (no percent display, right before it should display how much the world has been loaded).
Around 2-3 mins later the server restarts itself (could have to do with my hoster that it's automatically restarting non reacting servers)

--BEGIN DUMP--
Dump Time
03/16/2018 06:32:10

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   bei LiteDB.LockService.Write()
   bei LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   bei LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   bei LiteDB.LiteCollection`1.Insert(T document)
   bei Eco.Simulation.WorldLayers.WorldLayerStats.<>c__DisplayClass0_0.<CollectStats>b__0(Species species)
   bei Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   bei Eco.Simulation.WorldLayers.WorldLayerStats.CollectStats()
   bei Eco.Simulation.EcoSim.CollectStats()
   bei Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   bei Eco.Simulation.EcoSim.DoTick(TickSample tick)
   bei Eco.Simulation.EcoSim.Run()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by YukanoXX** [comment] 2018-03-16 10:46
same here
System.Exception: Caught exception invoking RPC Hit on ArrowEntity!

--BEGIN DUMP--
Dump Time
03/16/2018 11:34:11

Exception
System.Exception: Caught exception invoking RPC Hit on ArrowEntity!

Timeout. Database is locked for more than 00:01:00.


Stack:
   bei LiteDB.LockService.Write()
   bei LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   bei LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   bei LiteDB.LiteCollection`1.Insert(T document)
   bei Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Gameplay.Animals.AnimalEntity.TryApplyDamage(INetObject damager, Single damage, InteractionContext context)
   bei ArrowEntity.Hit(NetObjAttachInfo hitAttachInfo, Vector3 position)

   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

--BEGIN DUMP--
Dump Time
03/16/2018 11:38:20

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   bei LiteDB.LockService.Write()
   bei LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   bei LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   bei LiteDB.LiteCollection`1.Insert(T document)
   bei Eco.Simulation.WorldLayers.WorldLayerStats.<>c__DisplayClass0_0.<CollectStats>b__0(Species species)
   bei Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   bei Eco.Simulation.WorldLayers.WorldLayerStats.CollectStats()
   bei Eco.Simulation.EcoSim.CollectStats()
   bei Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   bei Eco.Simulation.EcoSim.DoTick(TickSample tick)
   bei Eco.Simulation.EcoSim.Run()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by Ardesy** [comment] 2018-03-16 16:34
same here.

--BEGIN DUMP--
Dump Time
03/16/2018 17:23:46

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC IsRelevant on Law!

Timeout. Database is locked for more than 00:01:00.


Stack:
   bei LiteDB.LockService.Read()
   bei LiteDB.LiteEngine.<Find>d__9.MoveNext()
   bei LiteDB.LiteEngine.<Find>d__13.MoveNext()
   bei LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.Sum(IEnumerable`1 source)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Conditions.NumericComparisonCondition.IsMet(IPlayerAction action)
   bei Eco.Gameplay.LegislationSystem.LawLogic.ControlFlow.LawControlFlowList.IsRelevant(IPlayerAction action)
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   bei System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-20 18:33
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343

We are able to reproduce this pretty consistently - it seems that it doesn't start happening until you have a largish database file (that is, until the server has a pretty large history).

For now, you should be able to avoid these by disabling stats (just disabling writes should be sufficient), although this will mean that graphs and laws won't necessarily work, as you may know.

**Closed by MarjieAVolk** 2018-03-20 18:33 UTC
