### ISSUE TITLE
[Staging Beta 7.3.0 #9969b2e9] Difficulty Setting not showing correctly in server UI

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6445] opened 2018-03-24 09:01 UTC
No matter what you set SkillPointPerCrafttime to in the Difficulty.eco config file (0.0001, 0.0002, 0.0003) on the server UI it shows as being set to 0 so its hard for users to know if the setting is correct or not.  If you edit it in the server UI it will show the decimals and the exact number set and saving it will save it to the config file correctly but when the server restarts the Server UI Difficulty page will show it  set back to 0

**Comment by MarjieAVolk** [comment] 2018-03-30 18:41
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6704

**Closed by MarjieAVolk** 2018-03-30 18:41 UTC
