### ISSUE TITLE
USER ISSUE: Furniture shuffling

### ISSUE THREAD

**Issue by stoopiduk** [StrangeLoopGames/EcoIssues#4986] opened 2018-02-23 08:26 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place multiple pieces of furniture in the different rooms of your house in a particular order (eg: highest value first). Log out overnight (8+ hours)

**Expected behavior:**
Furniture remains in the same order as it was left for the purpose of scoring house value.

**Actual behavior:**
Furniture is shuffled about, often bringing lower value furniture to the first slots, thus reducing house value. [Could it be implemented that furniture in a room is automatically sorted in descending value for scoring purposes?]

**Comment by MarjieAVolk** [comment] 2018-02-23 22:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4583

**Closed by MarjieAVolk** 2018-02-23 22:13 UTC
