### ISSUE TITLE
Black Screen in a special map area

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5157] opened 2018-02-27 00:32 UTC
Whenever i drive with a cart through a special map area my screen turns black (in game - not monitor) and i need to get off the cart and on again to see the world again. This does only happen to me. You got my world, i'll give you the coordinates where it does happen in a comment after searching it out. Funnily this was exactly the place where i landed after my flight from issue https://github.com/StrangeLoopGames/EcoIssues/issues/5156 ended.

**Comment by D3nnis3n** [comment] 2018-02-27 00:34
987,437

**Comment by MarjieAVolk** [comment] 2018-02-27 00:39
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4370 - I will note that your save file also repros this, thanks.

**Closed by MarjieAVolk** 2018-02-27 00:39 UTC
