### ISSUE TITLE
USER ISSUE: Host a Private World - cannot generate new world

### ISSUE THREAD

**Issue by pmcklveen** [StrangeLoopGames/EcoIssues#24241] opened 2023-12-16 18:39 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
1. Go to Host a Private World
2. Entered a World Name.
3. Select "No Collaboration"
4. I changed the Impact Days value to 60, but I don't think that would matter as I tried other values as well.
5. Check "Generate Random Landscape".  I clicked "Random" sometimes -- again I don't think it matters.
6. Clicked the green  "Start" button at the bottom
7.  Clicked "Yes" on the pop-up.

**Expected behavior:**
New world generation should begin.

**Actual behavior:**
Nothing happens.  New world generation process does not initiate.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13693569/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13693570/Player-prev.log)

**Comment by D3nnis3n** [comment] 2023-12-16 22:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24229

**Closed by D3nnis3n** 2023-12-16 22:22 UTC
