### ISSUE TITLE
Claiming a Piece of land already owned crashes Server #d9d6f47

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2327] opened 2017-09-27 15:58 UTC
Claimed some land that was already claimed (wasn't done intentionally) and Server locked up/crashed had to ask Admin to restart

**Comment by Fank** [comment] 2017-09-27 16:02
Can't confirm this one, its working for me.

**Comment by Hanan09** [comment] 2017-09-27 17:14
there was a table on that land crash whole server

**Comment by MarjieAVolk** [comment] 2017-09-27 18:50
I can't repro this either.  Do you have more details about this table that you think was related to the crash?  Do you have a Game.eco save file or error logs, or did you get kicked with an error message or anything?

**Comment by MarjieAVolk** [comment] 2017-09-27 18:55
Was the table on the land 'unowned', according to its UI?

**Comment by Hanan09** [comment] 2017-09-27 18:56
it was a store also  a dude trying to spawn an excavator

**Comment by MarjieAVolk** [comment] 2017-09-27 19:22
I witnessed some problems with table ownership just now, I'm guessing at this point that this is related to that (i.e. that it's throwing at PropertyManager line 262 with Owner == null)

**Comment by MarjieAVolk** [comment] 2017-11-10 20:17
I'm wondering if this issue is actually the same as this one: https://github.com/StrangeLoopGames/EcoIssues/issues/2566

Was this same person experiencing the error all the time?  Or was it tied to the specific plot of land?  Or was it a one time thing?

**Comment by Conchipedia** [comment] 2017-11-10 21:24
i'm not sure as i was asked to put in a github about it by another player so didn't really know all the details
 (some players are maybe just a bit shy or english is not their native language and want to make sure that a problem or question is FULLY understood). If i get something like this asked again i will get the player involved to give me as much details as possible and then see if i can re-produce it, or failing that try and find out ALL the possible details i can.

**Comment by MarjieAVolk** [comment] 2017-11-10 21:26
Okay thank you - Since the other bug I linked was also a server crash when claiming property, I'm going to close this as a duplicate of that.  That issue should be fixed in the next staging also.  Feel free to file another bug if you see the issue again.

**Closed by MarjieAVolk** 2017-11-10 21:26 UTC
Labels: High Priority
