### ISSUE TITLE
you can infinitely dig deep into the stone/iron... until the Clinet has loaded the pieces of stone/iron

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2161] opened 2017-09-17 09:56 UTC
and /unstuck will not work with some pieces of stone / iron ... over you head.
You can relog an swim up until the pieces of stone / iron ... loaded

**Comment by metachronism** [comment] 2017-09-18 16:58
dupe of #678

**Closed by metachronism** 2017-09-18 16:58 UTC
