### ISSUE TITLE
Waterworld

### ISSUE THREAD

**Issue by DeluXXe1986** [StrangeLoopGames/EcoIssues#7878] opened 2018-05-25 09:36 UTC
After Update 7.4.6 our World is completly full of water. But der isn't So Much pollution that water can Be 64 High. Waterlevel was in level 36 before. 
Pipe info:
https://steamuserimages-a.akamaihd.net/ugc/922555190792589681/01292BF6E112A144618CA55E913AD38B3F80BC32/

https://steamuserimages-a.akamaihd.net/ugc/922555190792590072/E0E606962D6D786C016690B2007367CD96E994F2/

https://steamuserimages-a.akamaihd.net/ugc/922555190792589681/01292BF6E112A144618CA55E913AD38B3F80BC32/
https://steamuserimages-a.akamaihd.net/ugc/922555190792874416/F7072326BC3AA2DA3310C9D27FEEA7153CB2FA3A/

Maybe it is the combustion?

**Comment by SeanAtr0n** [comment] 2018-05-25 17:48
Did you have sea level rising disabled before the update and it got enabled when you updated?

**Comment by DeluXXe1986** [comment] 2018-05-25 19:17
Now we disabled the sea rising level at the Moment to work around

**Comment by SeanAtr0n** [comment] 2018-06-21 01:35
looks like the root cause is resolved, we have other bugs open for tracking how janky flooding is so going to close this

**Closed by SeanAtr0n** 2018-06-21 01:35 UTC
Labels: High Priority
