### ISSUE TITLE
USER ISSUE: Can't see anything

### ISSUE THREAD

**Issue by Jigsaw5279** [StrangeLoopGames/EcoIssues#11464] opened 2019-02-23 00:16 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. Starting a new game in a private hosted map

**Expected behavior:**
I should be able to move and look around

**Actual behavior:**
Instead I can walk around (according to the map) and look around, and I can see the UI, but I can't see the world itself. Anythingi behind the UI is black,

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead I can walk around (according to the map) and look around, and I can see the UI, but I can't see the world itself. Anythingi behind the UI is black,

**Comment by Deantwo** [comment] 2019-02-23 09:52
First of all, try restarting the game.

**Comment by Jigsaw5279** [comment] 2019-02-23 10:16
I did, multiple times. Even restarted my PC and reinstalled the game to another drive

**Comment by D3nnis3n** [comment] 2019-02-25 12:59
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11226

**Closed by D3nnis3n** 2019-02-25 12:59 UTC

**Comment by D3nnis3n** [comment] 2019-02-25 21:04
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053

**Comment by Jigsaw5279** [comment] 2019-02-25 21:08
I'm on holidays in Sweden, but yea, I can add you on discord once I'm back in Germany
