### ISSUE TITLE
Nuclear fuel has a typo.

### ISSUE THREAD

**Issue by erraticengineer** [StrangeLoopGames/EcoIssues#11428] opened 2019-02-20 01:34 UTC
```
{
        public override LocString DisplayName { get { return Localizer.DoStr("Nuclear Fuel"); } } 
        public override LocString DisplayNamePlural { get { return Localizer.DoStr("Nuclear Fuel"); } } 
        public override LocString DisplayDescription { get { return Localizer.DoStr("Unstable nucler fuel."); } }

   }
```

"Unstable nucler fuel".  Low priority.  Just would be nice syntactical sugar to have it be right.

**Comment by elfl0rd** [comment] 2019-02-20 06:12
Duplicate of #4488

**Closed by elfl0rd** 2019-02-20 06:12 UTC
