### ISSUE TITLE
[Server] 7.2.0 - All planted trees disappeared

### ISSUE THREAD

**Issue by rorti** [StrangeLoopGames/EcoIssues#5517] opened 2018-03-07 02:55 UTC
Hi,

I have a french server, and we have a big problem with the new update 7.2 ...

All planted trees disappeared BUT
When i want to plant at the same place, that tell to me "**There are a plant here**"
So i tried to remove the dirt where the plant is, and 10 sec after that kick me from the server and tell to me "**Disconnected for inactivity**"
_(I have this problem only with trees)_

_The second problem, is the usage of the CPU at 100%_ **<-- Solved in 7.2.1**

I followed this tutorial to make an correct update => https://eco.gamepedia.com/Updating_a_Server

If you need others informations, tell me.

Regards.

**Comment by rorti** [comment] 2018-03-08 13:38
Tested on the 7.2.2, the problem are not solved for planted trees :/

**Comment by MarjieAVolk** [comment] 2018-03-08 19:30
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5321

**Closed by MarjieAVolk** 2018-03-08 19:30 UTC
Labels: High Priority
