### ISSUE TITLE
USER ISSUE: harvest cut wood

### ISSUE THREAD

**Issue by kish4n** [StrangeLoopGames/EcoIssues#4381] opened 2018-02-12 11:52 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
trying to harvest cut wood

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à TreeEntity.PickupLog(Player player, Guid logID)
   à TreeEntity.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-13 00:23
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668 . You can track the progress of the issue there.

It seems this happens occasionally, especially with logs that have been sitting around when the game is reloaded.  Hopefully we will fix it soon.

**Closed by MarjieAVolk** 2018-02-13 00:23 UTC
