### ISSUE TITLE
ISSUE:  singleplayer "server is full" message

### ISSUE THREAD

**Issue by DubsTheFox** [StrangeLoopGames/EcoIssues#6609] opened 2018-03-29 00:07 UTC
I can't play singleplayer since the latest update.
When I try to load my world it says: Connection failed. Server is full.

**Comment by MarjieAVolk** [comment] 2018-03-29 00:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6608

Here is my suggestion from there, let me know if it works:
You should be able to fix this for yourself by going to steam and selecting browse local files for Eco, then go down into Eco_Data\Server\Configs, opening Users.eco, and looking for the line '"MaxSlots": 0,'. I assume it will be set to 0, meaning no one can play. Set it to '1' if you only want to allow yourself, or '-1' if you want to allow any number of people.

**Closed by MarjieAVolk** 2018-03-29 00:16 UTC

**Comment by DubsTheFox** [comment] 2018-03-29 00:41
It worked. thank you for the quick help ^^

**Comment by MarjieAVolk** [comment] 2018-03-29 01:03
Awesome, thanks for letting me know :)
