### ISSUE TITLE
USER ISSUE: Server wont load

### ISSUE THREAD

**Issue by Skylarhenning** [StrangeLoopGames/EcoIssues#4823] opened 2018-02-19 13:50 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I logged into the server and couldnt move or open any tabs so i was stuck...waited for about 20 mins for it to load or something and it did not so i force restarted my computer and now i cant connect to the server to get back into it and play. 

**Expected behavior:**
Server wont start

**Actual behavior:**
Cannot connect to server

**Comment by MarjieAVolk** [comment] 2018-02-20 20:17
Sounds like it might be related to https://github.com/StrangeLoopGames/EcoIssues/issues/4115?

**Comment by MarjieAVolk** [comment] 2018-02-23 19:45
Okay, I'm going to close as a duplicate of #4115

**Closed by MarjieAVolk** 2018-02-23 19:45 UTC
