### ISSUE TITLE
Grassland Gatherer 5 Provides 80% Yield Bonus on Camas Bulbs in 0.7.3.1

### ISSUE THREAD

**Issue by Legends0** [StrangeLoopGames/EcoIssues#6791] opened 2018-03-31 05:23 UTC
Version: 0.7.3.1 beta

Since upgrading from 0.7.3.0 to 0.7.3.1, Gathering Efficiency 5 appears to be 80% now, but tooltip still shows 100%. Either this is the case, or there is an inaccurate reporting on yeild numbers.

Steps to Reproduce:
Harvest Camas Bulb where Soil Sampler shows 5 yield and maturity is 100%.

Expected behavior:
Receive 10 Camas Bulb.

Actual behavior:
Receive 8 Camas Bulb.

**Comment by craig-jong** [comment] 2018-04-04 00:41
Sounds like theres a bug with yield skills in general... Since the other report is also about this subject.

Might be a dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/6792

I'll look into it more.

**Closed** 2018-04-09 20:47 UTC
Labels: High Priority
