### ISSUE TITLE
USER ISSUE: Audio bug where the chainsaw noise stays even when switching off the chainsaw

### ISSUE THREAD

**Issue by BingusManLeftToenail** [StrangeLoopGames/EcoIssues#22722] opened 2021-10-03 14:08 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
Switch rapidly from the chainsaw to any other tool

**Expected behavior:**
My pickaxe should not make a brbrbrbrbrbrbrbrbrbrbr noise

**Actual behavior:**
My pickaxe indeed does make a brbrbrbrbrbrbrbrbrbrbrbrbr noise

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, I have the industrial rack mod installed as well as a mod to increase the range of the stockpiles

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Acromatic** [comment] 2021-10-08 02:15
I'm pretty sure the startup "birds" sound in the beginning is doubling or tripling over as well

**Comment by Daniel-Magulado** [comment] 2021-10-30 18:26
Hi @BingusManLeftToenail 

Thank you for writing this report. We are actually unable to reproduce this on our end. Could you provide a recorded video? Issue could seem to be only triggerable when playing in hosted servers.

**Comment by BingusManLeftToenail** [comment] 2021-10-30 18:38
Hello! I believe it was a one-off bug that I wasn't able to get back again.
Thank you for your response!

**Comment by D3nnis3n** [comment] 2022-07-18 09:52
Closing issue due to old age and never having been reproduced. If it reappears, please feel free to create a new issue :)

**Closed by D3nnis3n** 2022-07-18 09:52 UTC
Labels: Status: Needs Information
