### ISSUE TITLE
Attempting to vote gave me an invalid error message

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10293] opened 2018-12-12 20:52 UTC
![image](https://user-images.githubusercontent.com/3536496/49898066-c8febb00-fe0c-11e8-8922-9bad8f0197e1.png)

**Comment by johnkslg** [comment] 2018-12-12 20:53
This is most likely due to me not being a citizen, but it should display that in the red bar.  
@mirasrael Jeff and I did some work to make sure this was working, looks like something broke it.  Since Jeff is away can you see if you can figure out the issue?

In current release.

**Comment by johnkslg** [comment] 2018-12-12 20:54
The issue is that the return value for errors was changed from a string to an object. Probably a case of the webcode not getting that update to release.

**Comment by elfl0rd** [comment] 2018-12-12 22:13
https://github.com/StrangeLoopGames/EcoIssues/issues/10154

**Comment by D3nnis3n** [comment] 2018-12-13 02:20
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10020

**Closed by D3nnis3n** 2018-12-13 02:20 UTC
Labels: High Priority
