### ISSUE TITLE
USER ISSUE: Connection Failed (Local Host)

### ISSUE THREAD

**Issue by b0sper** [StrangeLoopGames/EcoIssues#12929] opened 2019-08-21 02:51 UTC
**Version:** 0.8.2.9 beta

**Steps to Reproduce:**
Trying to load into a solo world or creating a new local world (any settings). However loading into an online world works just fine. Log File available. 

**Expected behavior:**
Let me connect to my world -.-

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods. Vanilla Savegame.

[Eco - Connection Timeout Log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3523366/Eco.-.Connection.Timeout.Log.txt)

**Comment by D3nnis3n** [comment] 2019-08-30 04:14
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12982

**Closed by D3nnis3n** 2019-08-30 04:14 UTC
