### ISSUE TITLE
USER ISSUE: Cut Floating Log

### ISSUE THREAD

**Issue by Nashable** [StrangeLoopGames/EcoIssues#5377] opened 2018-03-04 18:19 UTC
**Version:** 0.7.2.0 beta staging-adf7002a

**Steps to Reproduce:**
1. Found floating log piece in the world.
2. Hit with Iron Axe
3. Exception Triggered

**Expected behavior:**
Cut into pieces for pick up.

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-05 23:19
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-03-05 23:19 UTC
