### ISSUE TITLE
Whaterweel works without water

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5815] opened 2018-03-10 01:49 UTC
http://steamcommunity.com/sharedfiles/filedetails/?id=1325844469

It turns around and supplies power even when no water is anywhere near.

**Comment by Conchipedia** [comment] 2018-03-10 02:32
its been this way for awhile that it doesn't need water, maybe they should call it an Airwheel 😄

**Comment by MarjieAVolk** [comment] 2018-03-12 23:38
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2105

**Closed by MarjieAVolk** 2018-03-12 23:38 UTC
