### ISSUE TITLE
USER ISSUE: Not authorized to add items when buying in a store.

### ISSUE THREAD

**Issue by fremenusul** [StrangeLoopGames/EcoIssues#6782] opened 2018-03-30 23:55 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Click on store
Try to purchase an item
Get message "Not authorized to add items"

**Expected behavior:**
Should be able to buy something, i'm not adding anything

**Actual behavior:**
Get the error.

**Comment by MarjieAVolk** [comment] 2018-03-31 00:28
Is the store attempting to place the items directly into an object that belongs to you?  Maybe a cart?

**Comment by fremenusul** [comment] 2018-03-31 17:07
I have no idea. I don't believe so. I have no cart nearby

**Comment by PieShade** [comment] 2018-04-03 13:58
I've had this happen to some stores. All of the stores that this happened at, had storages that I owned linked to it. 

**When I unlinked the storages, I could buy items again.** Relinking the storages didn't reproduce the problem, though.

**Comment by MarjieAVolk** [comment] 2018-04-03 18:10
Yeah okay.  I think I know the issue, it's because now the store is acting as if it is the store owner player, and that player doesn't have auth on your linked storage.  I will look into it.

**Comment by MarjieAVolk** [comment] 2018-04-03 19:18
Fixed in next hotfix

**Closed by MarjieAVolk** 2018-04-03 19:18 UTC
Labels: High Priority
