### ISSUE TITLE
USER ISSUE: Small wooden sign

### ISSUE THREAD

**Issue by InTheNameOfTheEMPEROR** [StrangeLoopGames/EcoIssues#10181] opened 2018-12-03 16:56 UTC
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
1. Place a small wooden sign
2. Type in any text you want 
![2018-12-03 5](https://user-images.githubusercontent.com/45568218/49388594-8d853200-f724-11e8-81f6-c34e9f97d3ef.png)
3. Save
![2018-12-03 6](https://user-images.githubusercontent.com/45568218/49388608-96760380-f724-11e8-98d7-9e40b7f2f54b.png)
4. No text on the sign
![2018-12-03 7](https://user-images.githubusercontent.com/45568218/49388667-befdfd80-f724-11e8-8b96-783edcc767bc.png)

**Expected behavior:**
Text should appear on the placed sign.

**Actual behavior:**
No text will appear on the sign.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed.

**Comment by Nicolausi113** [comment] 2018-12-03 20:54
This is backside you looking to, turn it 180 degree

**Comment by Nicolausi113** [comment] 2018-12-03 21:14
sorry , I was wrong - but i works for me
![sign2](https://user-images.githubusercontent.com/38510829/49401927-c7682f80-f748-11e8-837f-612b483b6b3a.jpg)

**Comment by D3nnis3n** [comment] 2018-12-04 03:30
Duplicate of #10062

**Closed by D3nnis3n** 2018-12-04 03:30 UTC
