### ISSUE TITLE
USER ISSUE: Stockpile tutorial: Reaction timing to chop down tree baely existent

### ISSUE THREAD

**Issue by krys-k89** [StrangeLoopGames/EcoIssues#22636] opened 2021-09-05 03:17 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Make sure ax is in possession
2. Walk up to a tree until highlighted
3. Hold down left button on mouse

**Expected behavior:**
Avatar should chop tree

**Actual behavior:**
Avatar will either remain standing or might react after 30 minutes

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment] 2021-09-06 15:10
Hi @krys-k89

Thank you for writing this bug report.
However, we are unable to reproduce this issue.
Can you upload a recorded video of the issue here?
Additionally, kindly provide the complete specification of your PC including the complete version of its operating system.
Please also upload your game logs here once you encounter the issue. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment] 2021-09-08 07:15
Hi @krys-k89

I just received information that this is related to #22477 based on your hardware from your logs from that report.
Most of the animations issues take too long to respond basically is due to your system being is too weak for Eco.
Closing this as this is a hardware issue.

**Closed by Ry4ndrew** 2021-09-08 07:15 UTC
Labels: Status: Needs Information
