### ISSUE TITLE
Error on joining a server where I had 2 Characters

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoIssues#4251] opened 2018-02-10 15:12 UTC
So there was a bug that created 2 characters on the same server (the one which gave you a new character with "#2" at the end of the name).
So since they "patched" it in the last patch I now get this error upon entering the server:
<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Ein Aufrufziel hat einen Ausnahmefehler verursacht.
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
bei Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
bei Eco.Plugins.Networking.Clients.Client.ShouldSelectUser()

Considering it says "ShouldSelectUser on Client!" my best bet would be that it wants me to select which character I want to play, but this doesn't seem to work.

Reported via http://steamcommunity.com/app/382310/discussions/0/1699416432420796112/.

**Comment by MarjieAVolk** [comment] 2018-02-13 05:18
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4413.  You can track the issue progress there.

We already have a fix for this, which will go out in the next update.  Unfortunately, until then you may not be able to play on this server.  You should be able to play on other servers.

**Closed by MarjieAVolk** 2018-02-13 05:18 UTC
