### ISSUE TITLE
 [0.9.0 Staging 1459] When editing using Claim Tool the claim plot is a long way away from Cursor

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#15086] opened 2020-03-12 00:38 UTC
**Version:** 0.9.0.0 beta staging-1459

as can be seen from this snapshot the actual box to claim is not UNDER the cursor as it should be
![snap6445](https://user-images.githubusercontent.com/29383891/76476325-9bcaff00-63f9-11ea-820f-7b6d7898dfac.png)

no matter where you place the cursor it is always this far away from claim plot being edited

**Comment by Conchipedia** [comment] 2020-03-12 06:47
had been noticing this in PlayTest Server Version as well,

**Comment by SlayksWood** [comment] 2020-03-12 10:37
Can't reproduce.
![image](https://user-images.githubusercontent.com/45708377/76512733-4547da00-6466-11ea-942d-1c97ce6ed645.png)
Can you add more information, and provide your PC specification (include monitors number)?

**Comment by Conchipedia** [comment] 2020-03-12 13:17
Not Sure when this glitch came in, as in previous Version(s) of  Staging i wasn't getting this happening (for me this is not a game killer, just a weird bug)
**PC Specs**
Nvidia GeForce GTX 980 (Monitor 2)
Intel (R) HD Graphics 4600 (Monitor 1)
Intel(R) Core(TM) i7-4790K CPU @ 4.00Hz

all drivers are up to date, only thing for me that changed was Eco Versions

**Comment by MishkaFur** [comment] 2020-03-12 15:03
Experience the same issue myself, seems like the mouse is about two chunks "over" can test further tonight with single monitor setup.

Windows 10, Intel CPU, Geforce 1660, Dual monitors and with latest drivers, both monitors are 1920x1080

**Comment by MishkaFur** [comment] 2020-03-15 09:33
Does not happen on 1464 with a single screen, NMMike has tested on dual screen and also seems okay so appears this is fixed now.

**Comment by Conchipedia** [comment] 2020-03-15 14:45
still an issue for me in 1464

**Comment by Conchipedia** [comment] 2020-03-15 18:18
when zooming in they get closer but not as they should be, they are stll about a deed a
![snap6463edited](https://user-images.githubusercontent.com/29383891/76707690-450b4100-66e9-11ea-9beb-bff150d8935b.png)

**Comment by SlayksWood** [comment] 2020-04-15 09:35
> I played around with editing claims. First of all, the highlight on the map is off-centre from the cursor. This problem is minor, maybe it has something to do with the 4k resolution and UI scaling? Secondly, I think there is a bug that eats the papers that relates to editing claims. I removed a claim entirely with it and it didn't give me my papers back, losing about 10 of them. Couldn't reproduce this bug though...
> 
> 1. Version
>    0.9 Staging-1511
> 2. Steps to reproduce
> 
> * Claim some land
> * Edit the claim with the stake by pressing "e"
> * The map highlight will be off-centre from the mouse cursor
> * Remove claims, remove a claim entirely, maybe add / remove parts of it first?
> * Claim will be gone, but you won't get your papers back
> 
> Video (of the first part, couldn't repo the second one):
> https://youtu.be/ZnFfQkpI42M
> 
> 1. Expected behaviour
>    Map highlights should be underneath the mouse cursor. Editing claims with the edit shouldn't let players lose their claim papers...
> 2. Actual behaviour
>    Map highlight is offset from the cursor, a player can lose their claims.
> 3. Providing Log files
>    (I think it's this one...)
>    [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4479126/Player.log)
> 
> PS: I think I'm down 30+ claims on this test server already :D. Would appreciate getting some back ;)

**Comment by Conchipedia** [comment] 2020-07-13 10:50
been a while since i checked this, for me the claims are now working as intended with them being under the mouse pointer when claiming and unclaiming in *edit* mode
verion 0.9 Staging-1611

**Comment by IcedForge** [comment] 2020-07-29 08:29
Still an issue in current playtest version 0.9.0.0 - beta staging-stable-8
same issue as OP, mouse pointer staying a portion away from the actual interactive tile.
https://cdn.discordapp.com/attachments/680068515658596364/737948660691894308/20200729_102343.jpg
sorry about the crap picture, couldnt grab a screen on the current pc without the pointer dissapearing.

**Comment by SlayksWood** [comment] 2020-09-08 12:42
@Conchipedia @IcedForge Do you still have this issue?

**Comment by Conchipedia** [comment] 2020-09-08 15:40
@SlayksWood not for me anymore, it seems fixed

**Comment by IcedForge** [comment] 2020-09-16 07:44
Running into it still, both with editing Districts as well as claiming land

Displaying what happens in live time, it reminds me of dead zoning where it "moves ahead" the further from the center you go. 
https://i.gyazo.com/796d45618808758d0515f2e8743e1e39.mp4

**Comment by gzatravkin** [comment] 2020-11-09 22:37
@serpopov I discussed it with @mirasrael once. 

It's difficult to make 100% raycaster with low cost. Build full mesh of map and raycast it would be too costly.

If you want you may try to tweak lods and sizes variable from 
![image](https://user-images.githubusercontent.com/53317567/98598258-f5513980-22b8-11eb-8345-67b6d585dc2a.png).

Basicly first it checks for square part of map with length 350, taken 1 from 15 points.
Then after finding intersection point for that one it checks in smaller sqaure (80) taken 1 from 4 points.
And so on. 

You may increase area of check (Y) and decrease X (it mean take 1 from X points of map).
Check perfomance imapct if you will do it.

Also I had idea - to draw another map with encoding in color info about coors. Some gradient map rendering to camera invisible to player, then by getting pixel color it will transform it to 100% matched color. The problem is that colors don't have enough representation for world with 4096*4096. But @mirasrael was against that (because of limit and need render world 2 times).

Alternative idea was to draw some satelite which moves instead of cursor, so it will be no need in calculate real cursor position. Just move left 10 px => 1 plot moves to left.

**Comment by gzatravkin** [comment] 2021-01-29 20:50
Probably gonna work on this by myself, but last time I checked it the problem was about water. 

It calculates position based of relief under water, but since water is not-transparent now in minimap, it seems glitchy. So should be just changed to use sea position instead of underwater land position when it's over water surface.

**Comment by Daniel-Magulado** [comment] 2021-03-07 14:02
Build 0.9.4 Develop-203.

I am unable to test this on the said build. Blocked by #20849
When editing a map via DEED or via Zoning Office, the highlight where you select the area for the selected district is missing.

See the video below:
Via DEED
https://images.zenhubusercontent.com/47210472/d62bc285-8531-4d95-8b34-c18ca961648b/2021_03_07_21_37_trim__3_.mp4

Via Zoning Office
https://images.zenhubusercontent.com/47210472/014d8440-44ca-4a1d-abba-463d4a7e313d/2021_03_07_21_37_trim__4_.mp4

**Comment by TwixterZ** [comment] 2021-04-26 06:01
fix tested and confirmed as of 9.4 Develop 266

**Closed by TwixterZ** 2021-04-26 06:01 UTC
Labels: Category: UI, Priority: Medium, Squad: Wild Turkey, Status: Fixed
