### ISSUE TITLE
SERVER ISSUE: Dump\Crash NullReferenceException 02175142.ecodmp

### ISSUE THREAD

**Issue by yankeejim** [StrangeLoopGames/EcoIssues#4746] opened 2018-02-18 02:07 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
--BEGIN DUMP--
Dump Time
02/17/2018 20:51:42
 
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
 
--END DUMP--

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-20 19:57
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368

**Closed by MarjieAVolk** 2018-02-20 19:57 UTC
