### ISSUE TITLE
USER ISSUE: Dual Playe

### ISSUE THREAD

**Issue by Brotherhood** [StrangeLoopGames/EcoIssues#24821] opened 2024-03-10 22:44 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
I basically have two player playing at the same time, one is always standing and the other one is actually me. so for example if I'm in bed there is one of me sleeping and the other one of me standing on the bed. or If I'm walking there are two of me gwalking anf doing around! This is Always Happening! even when i go out of game restart the computer and come back!

**Expected behavior:**
Having only one player!! 

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Not that I know of!

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14552000/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-03-12 12:14
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24772. A solution can be found there.

**Closed by D3nnis3n** 2024-03-12 12:14 UTC
