### ISSUE TITLE
USER ISSUE: Jumped in river and now falling through world

### ISSUE THREAD

**Issue by Tanner1638** [StrangeLoopGames/EcoIssues#5257] opened 2018-03-01 02:10 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Jump in water
2. walk forward towards side of river (while under water)

**Expected behavior:**
It should have stopped my character from moving any further

**Actual behavior:**
instead it allowed me to continue to walk through the world

**Comment by MarjieAVolk** [comment] 2018-03-01 19:54
Did you see any holes in the world before you started falling?

**Comment by MarjieAVolk** [comment] 2018-03-06 00:45
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4924 or https://github.com/StrangeLoopGames/EcoIssues/issues/4574

**Closed by MarjieAVolk** 2018-03-06 00:45 UTC
