### ISSUE TITLE
USER ISSUE: Brick to dirt doesn't have a texture

### ISSUE THREAD

**Issue by isaakybd** [StrangeLoopGames/EcoIssues#6032] opened 2018-03-14 08:14 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
place a brick block with the hammer next to a dirt square block. World shines through	

**Expected behavior:**
World does not shine through: is dirt.

**Actual behavior:**
Does shine through, eg you should probably get a texture for that :D Love your game ya'll! :D

**Comment by MarjieAVolk** [comment] 2018-03-16 01:45
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4286

**Closed by MarjieAVolk** 2018-03-16 01:46 UTC
