### ISSUE TITLE
USER ISSUE: Exception on cutting a log

### ISSUE THREAD

**Issue by glenwinters** [StrangeLoopGames/EcoIssues#4742] opened 2018-02-17 23:56 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Try to cut a log that's been sitting on the ground for awhile.

**Expected behavior:**
The log should be cut and able to pick up.

**Actual behavior:**
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
```

**Comment by MarjieAVolk** [comment] 2018-02-22 19:55
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-22 19:55 UTC
