### ISSUE TITLE
Tree disappeared while I was chopping it after felling it

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10298] opened 2018-12-12 21:25 UTC

**Comment by BlazeGuy2** [comment] 2018-12-13 01:17
Can you post a video showing this?

**Comment by D3nnis3n** [comment] 2018-12-13 02:16
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8823?

**Comment by BlazeGuy2** [comment] 2018-12-13 21:34
Dup, also couldn't repro from unity.

**Closed by BlazeGuy2** 2018-12-13 21:34 UTC
