### ISSUE TITLE
Server Crush Dump: NullReferenceExceptions

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [StrangeLoopGames/EcoIssues#5962] opened 2018-03-12 21:13 UTC
All errors generate on dedicated server with 20 players on server at random times I am leaving logs in hopes it helps

--BEGIN DUMP--
Dump Time
03/10/2018 09:03:31

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by Edgar-BlipparDev** [comment] 2018-03-12 21:13
--BEGIN DUMP--
Dump Time
03/11/2018 14:48:58

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by Edgar-BlipparDev** [comment] 2018-03-12 21:13
--BEGIN DUMP--
Dump Time
03/11/2018 20:53:33

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-13 21:52
Thanks!  It helps to get a tally of how many people are reporting the error, even if we already know about it.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-13 21:52 UTC
