### ISSUE TITLE
[0.9.0 staging-1526] Mining : Calorie decrease does not function (lvl3)

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#16017] opened 2020-04-26 11:54 UTC
1. I had -15 Calories per hit with Stone Pickaxe.
2. I skilled the lvl 3 talent with 20% calorie decrease.
3. Now i have -14 Calories per hit with Stone Pickaxe.

Also, i cant hover over it to see a tooltip:
![20200426134955_1](https://user-images.githubusercontent.com/63646359/80306720-3d00ef80-87c5-11ea-80ee-ef2dab49520d.jpg)

**Comment by WeaselDog** [comment] 2020-04-27 04:59
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12363

**Closed by WeaselDog** 2020-04-27 04:59 UTC
