### ISSUE TITLE
No main menu buttons.

### ISSUE THREAD

**Issue by gravestristen** [StrangeLoopGames/EcoIssues#4030] opened 2018-02-07 06:08 UTC
this happened when I went to craft hewen planks (or however you spell it), i was tired of hitting the right arrow to go up so i clicked the box with the number in it with the intention of putting a 10 in the box, the second I clicked the box the world crashed (I think?) I was booted to the main menu, no bug prompt or anything and my new load and exit buttons are missing, ive tried restarting my game and my pc.

here is a link to a screenshot as proof
http://steamcommunity.com/sharedfiles/filedetails/?id=1293898899

**Comment by Blanclour** [comment] 2018-02-07 06:15
I also confirm this issue, was also trying to craft hewen planks when clicking on the box resulted in the main menu buttons disappearing. I tried restarting my system and re-installing the game, does not seem to fix the bug.

**Comment by midn8t** [comment] 2018-02-07 06:24
on server side error is invalided user causes this
adding ticket info
https://github.com/StrangeLoopGames/EcoIssues/issues/4027

**Comment by gravestristen** [comment] 2018-02-07 06:25
I was just about to link that ticket, thank you, im looking for the log file so I can show more information.

**Comment by gravestristen** [comment] 2018-02-07 06:35
update, no log seemed to be generated.

**Comment by Nanders** [comment] 2018-02-07 18:15
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4027

**Closed by Nanders** 2018-02-07 18:15 UTC
