### ISSUE TITLE
No way to destroy another player's cart as admin

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#6239] opened 2018-03-18 14:38 UTC
There is no way to destroy another player's cart as admin (no command and devtool does not work on something you dont own).

Only way i know is to unzip game.eco and delete all carts and zip it again. But it's not a good solution at all.

Inactive player's carts are really a problem when you are managing a big server. Please add a way to destroy them.

**Comment by LiaungYip** [comment] 2018-03-18 15:27
Duplicate of #3607.

**Comment by MarjieAVolk** [comment] 2018-03-21 18:51
Thanks, closing as duplicate

**Closed by MarjieAVolk** 2018-03-21 18:51 UTC
