### ISSUE TITLE
Missing/Wrong water on Ramps placed in water

### ISSUE THREAD

**Issue by DragonDev1906** [StrangeLoopGames/EcoIssues#22804] opened 2021-11-24 19:44 UTC
As you can see in the screenshots water is not placed correctly on a ramp if the ramp is more than one block wide.
This is the case in both 9.4.x and 9.5 staging 2157.

![20211124203446_1](https://user-images.githubusercontent.com/8270201/143302699-680e7db2-f307-4e04-9fae-2f31d92bdab2.jpg)
![20211124203733_1](https://user-images.githubusercontent.com/8270201/143302925-fe4d3dfd-f080-4eb1-8bfb-e970d56e8316.jpg)
![20211124203746_1](https://user-images.githubusercontent.com/8270201/143302939-6b7eda23-5818-479a-9f11-c2e52003a0e5.jpg)

The water height also doesn't seem to be set correctly for the ramp block (placed between river and ocean):
![20211124204137_1](https://user-images.githubusercontent.com/8270201/143303350-b2811ecd-6f40-45b9-99cc-68dbd5a352a4.jpg)

Nickname: Zokora

**Comment by TwixterZ** [comment] 2021-11-25 10:08
Hi @DragonDev1906 thank you for reporting this issue, I have forwarded this issue to our developers to investigate

**Comment by TwixterZ** [comment] 2021-11-25 10:51
Closing this as issue as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12471 these are forwarded to our developers

**Closed by TwixterZ** 2021-11-25 10:51 UTC
Labels: Type: Bug
