### ISSUE TITLE
[Art] Hammer picking up Mortared Stone when choosing new type get 10 extra Wood Stairs icon 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3204] opened 2017-12-24 15:36 UTC
when i pick up Mortared Stone i see this when i want to choose another block
![snap790](https://user-images.githubusercontent.com/29383891/34327588-fdcb9596-e8bf-11e7-92b0-4196c75095ff.png)
and if i choose any of the 10 extra wood stairs it can be placed as this
![snap791](https://user-images.githubusercontent.com/29383891/34327590-192199ee-e8c0-11e7-81c8-bdee8cf94cfa.png)

**Comment by Conchipedia** [comment] 2017-12-25 22:36
just noticed that when Carrying Mortared Stone, if Pickaxe, Axe, Hoe, Scythe, Road tool ,Soil Sampler or Bow is selected it will Show the "Old" mortared Stone block and that can be placed as seen.
<img width="1280" alt="snap131" src="https://user-images.githubusercontent.com/29383891/34343352-3ff9a0bc-e9c3-11e7-8f91-65aaa568183d.png">
<img width="1280" alt="snap132" src="https://user-images.githubusercontent.com/29383891/34343353-4017229a-e9c3-11e7-943c-932176793163.png">
<img width="1280" alt="snap134" src="https://user-images.githubusercontent.com/29383891/34343354-4030b156-e9c3-11e7-9111-4d37a13b9061.png">
<img width="1280" alt="snap136" src="https://user-images.githubusercontent.com/29383891/34343355-404d23c2-e9c3-11e7-919e-fcad3c3f1792.png">
<img width="1280" alt="snap137" src="https://user-images.githubusercontent.com/29383891/34343356-4066de20-e9c3-11e7-8bc1-5ea8d526ab08.png">
<img width="1280" alt="snap139" src="https://user-images.githubusercontent.com/29383891/34343357-407ee86c-e9c3-11e7-8f90-2f2ac6356399.png">

**Comment by johnkslg** [comment] 2018-01-12 20:58
Any idea whats going on here?

**Comment by Conchipedia** [comment] 2018-01-13 18:21
from a players point of View the new hammer sees the block correctly but the other tools still see the old version of the block so maybe the other tools are still looking at the previous coding?

**Comment by craig-jong** [comment] 2018-01-14 21:46
This isn't technically incorrect: that block is what mortared stone looks like in a stockpile. The other forms are different blocks entirely.

The stairs bug isn't something I can reproduce - might've been fixed by Eric's stairs changes.

@keegan-o is going to fix this with a stacked mortared stone builder.

**Comment by Conchipedia** [comment] 2018-01-15 03:02
haven't seen that in staging at all yet so far hoping the stairs thing has fixed itself

**Comment by metachronism** [comment] 2018-01-15 19:03
fixed this earlier last week

**Closed by metachronism** 2018-01-15 19:03 UTC
Labels: High Priority
