### ISSUE TITLE
Calorie Scaling with Durability - Unintended Affect: No Reason to Repair Tools Anymore?

### ISSUE THREAD

**Issue by Legends0** [StrangeLoopGames/EcoIssues#6617] opened 2018-03-29 02:07 UTC
Since 7.3.0 removed calorie scaling with durability, there seems to be an unintended change. 0% durability tools no longer change calorie cost. As it is currently, there is no reason to care about durability or the repair system.

Version: 0.7.3.0 beta

Steps to Reproduce:
Use a tool such as Wooden shovel until durability is at 0% and continue using the tool.

Expected behavior:
Some sort of consequence for using a 0% durability tool as there was before 7.3.0.

Actual behavior:
Tool without durability behaves the same as a fully repaired tool.

**Comment by Legends0** [comment] 2018-03-30 22:40
This also leads to the tooltip that is applied to broken tools no longer being true as it isn't any more less efficient than a repaired tool.

**Comment by MarjieAVolk** [comment] 2018-03-30 22:43
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6467

**Closed by MarjieAVolk** 2018-03-30 22:43 UTC
