### ISSUE TITLE
[0.9.2 staging-1852] Float Stairs for Flat Steel can disappear

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19426] opened 2020-11-23 07:46 UTC
Step to reproduce:
- place Float Stairs Corner & Float Stairs Turn:
![image](https://user-images.githubusercontent.com/45708377/99938346-a6a3a500-2d78-11eb-8fca-76d4f35b8acd.png)
- select Float Stairs form and mouseover nearby Float Stairs Turn block:
![image](https://user-images.githubusercontent.com/45708377/99938357-aa372c00-2d78-11eb-81ba-907e4143cce9.png)
- place it. Float Stairs Corner & Float Stairs Turn for Flat Steel disappeared:
![image](https://user-images.githubusercontent.com/45708377/99938367-b0c5a380-2d78-11eb-8666-e17d23b73d7f.png)
- you can highlight them and  they still have occupancy:
![image](https://user-images.githubusercontent.com/45708377/99938374-b327fd80-2d78-11eb-9643-331a822be401.png)
![image](https://user-images.githubusercontent.com/45708377/99938570-23368380-2d79-11eb-8509-0022eef66c96.png)

**Comment by SlayksWood** [comment] 2020-11-23 07:54
After restart client:
![image](https://user-images.githubusercontent.com/45708377/99938921-ef0f9280-2d79-11eb-92ba-8a4ec77ec2be.png)
Some appeared, others disappeared.
Place one block to upfate chunk, Float Stairs Corner & Float Stairs Turn for Flat Steel disappeared again, Other blocks apeared:
![image](https://user-images.githubusercontent.com/45708377/99939019-2bdb8980-2d7a-11eb-8576-72a1ae05a5c1.png)

**Comment by RobertMangano** [comment] 2020-11-24 02:24
![image](https://user-images.githubusercontent.com/26705633/100038740-f0ab8a00-2e4f-11eb-8a8c-8e85666c1423.png)
i do not have the same issue following the steps in your comment

**Comment by keegan-o** [comment] 2020-11-24 02:36
Sekoris also tried to repro and couldn't so this seems to be something with chunks, is what I would guess.

**Comment by SlayksWood** [comment] 2020-11-24 06:32
I'll investigate it again a little later. Perhaps there is no problem in the unity

**Comment by SlayksWood** [comment] 2020-12-07 07:42
I still have problem in staging-1864. And seems this is only one block with that ptoblem.
![image](https://user-images.githubusercontent.com/45708377/101322838-bc38c480-3878-11eb-8bbb-a4dc8e5aec0b.png)

**Comment by keegan-o** [comment] 2021-01-04 19:39
![image](https://user-images.githubusercontent.com/14983165/103572448-6fe5a200-4e81-11eb-9093-7ef2dfca9097.png)

**Comment by keegan-o** [comment] 2021-01-04 21:52
I also went in and fully manually reset the transforms of each mesh, and assigned them one single fresh new material in maya... if this doesn't fix them I am close to out of options on art side other than re-making them or trying entirely different meshes in the same builder.

**Comment by keegan-o** [comment] 2021-01-08 20:26
finally fixed in develop and staging, at least it should be now.

**Comment by Daniel-Magulado** [comment] 2021-01-12 10:53
Build: Staging
Repro: Unable to reproduce following the repro steps.
Additional Steps: Did try to do extra by making long stair lines and spamming corner stairs. The issue is not occurring.

![Disappearing Stairs.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/91eb7e78-72c0-4c55-99cc-4912dda6ebb2)

Resolution: Closing.

**Closed by Daniel-Magulado** 2021-01-12 10:53 UTC
Labels: Category: Art, Category: Gameplay, Priority: Medium, Status: Fixed
