### ISSUE TITLE
When passing a law involving a redefined zone, any change to the law resets the zones to the status quo

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7214] opened 2018-04-15 19:26 UTC
Which means that if you want to set a law that defines a zone and prohibits behaviours in that zone, it needs to be two laws.

**Comment by MarjieAVolk** [comment] 2018-05-08 00:17
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3971

You should still be able to propose them together, you just have to do the districts part last.  But yeah it's annoying.

**Closed by MarjieAVolk** 2018-05-08 00:17 UTC
Labels: Medium Priority
