### ISSUE TITLE
USER ISSUE: Truck deed bug

### ISSUE THREAD

**Issue by Lord-Schwartzy** [StrangeLoopGames/EcoIssues#24557] opened 2024-01-06 21:36 UTC
\
**User Id: (slg232257)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Someone is auth on my truck, but I can't remove them. On the map, we see the person auth on it, but on the deed there is nothing. To fix it, I tried to transfert ownership of the truck to a title but it make me crash with that error.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope, I'm playing on WT right now and I'm not in a company.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-07 09:11
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24536

**Closed by D3nnis3n** 2024-01-07 09:11 UTC
