### ISSUE TITLE
8.0.0 Picking up Rubble lets you pick up more than 20 and stores in your Toolbar and Backpack

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10691] opened 2019-01-15 22:01 UTC
**Version:** 0.8.0.0 beta master-0d4ca997

When mining and you pickup Rubble, it will pickup the Rubble **BUT** it will carry on filling tool bar then start on the backpack, you can even change type of pickup and it will also place that in toolbar and backpack
![snap3827](https://user-images.githubusercontent.com/29383891/51212598-d2e67300-1910-11e9-8c66-27048055a245.png)
in the next 2 shots i changed type of rubble being picked up and it still happy filling up toolbar and backpack
![snap3828](https://user-images.githubusercontent.com/29383891/51212599-d37f0980-1910-11e9-92ac-ac37b5798f53.png)
![snap3829](https://user-images.githubusercontent.com/29383891/51212600-d37f0980-1910-11e9-9085-9ac50d56c932.png)

**Comment by Conchipedia** [comment] 2019-01-15 22:04
just found out this might be to do with using /creative, never seen this before

**Comment by craig-jong** [comment] 2019-01-15 22:17
Creative has removed inventory restrictions for a while. I'm going to close this as the cause since it seems fine in current master to me.

**Closed by craig-jong** 2019-01-15 22:17 UTC
