### ISSUE TITLE
Tuna with Arrow shot down ---> #1854 ??

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2258] opened 2017-09-24 14:41 UTC
![grafik](https://user-images.githubusercontent.com/26040573/30783669-2b648776-a147-11e7-8f1e-f0c6ee370b58.png)

**Comment by Fank** [comment] 2017-09-24 16:57
Relates to #1854

**Comment by MarjieAVolk** [comment] 2017-09-25 17:30
Yep looks like a duplicate of that one - thanks

**Closed by MarjieAVolk** 2017-09-25 17:30 UTC
