### ISSUE TITLE
Player Action Assign Reputation Missing from Laws

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#9166] opened 2018-09-03 14:05 UTC
We cannot make laws that allocate government funding for players who assign reputation. There is little to no incentive for doing this in the game so allocating money for this action would be helpful.

**Comment by Senlarus** [comment] 2018-09-03 14:06
Also this shoudl take into account the number of points assigned, so if someone assigns all 10 points in one action they should get the allocation multiplied by the points assigned. This way people who assign all 10 points or people who assign 2 points 5 times would all get the same allocation.

**Comment by MarjieAVolk** [comment] 2018-09-04 19:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7253

Thanks for your additional thoughts on this.

**Closed by MarjieAVolk** 2018-09-04 19:29 UTC
Labels: Feature, Laws, Medium Priority
