### ISSUE TITLE
Master 8.2 Broken UI

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#11939] opened 2019-04-09 23:06 UTC
UI is broken for opening up for choosing a new game
![image](https://user-images.githubusercontent.com/35509188/55840748-68913900-5ae1-11e9-898c-b922abb1cb83.png)

**Comment by Spydarlee** [comment] 2019-04-11 14:19
Hey @MilenkoTunjic, would you mind taking a look at this?

I had a look and it seems the problem is due to this UI using the 'UI_Elements_02_RecommendedFrame' sprite which lives in the 'UI_Elements_02_TUTORIAL' sprite sheet. However that sprite sheet seems to have changed but the slices haven't been updated and this particular sprite is missing.

![image](https://user-images.githubusercontent.com/553695/55964539-ce5dfc00-5c6c-11e9-8621-9a33b8872c51.png)

If the UI is supposed to be using a new sprite feel free to assign this back and let me know which one and I can hook it up in the prefab. Thank you!

**Comment by redwyre** [comment] 2019-04-12 07:33
Note the tutorial icon images are broken too

**Comment by johnkslg** [comment] 2019-04-16 19:08
@danwheeler can you look through source control history and figure out what happened to break this, and see if theres an easy solution

**Comment by hososugi** [comment] 2019-04-17 05:54
A quick fix is to revert the UI_Elements_02_TUTORIAL.png to the 4780 revision. I tested this and it appears to fix the New Game menu and the tutorial task images:

![image](https://user-images.githubusercontent.com/894215/56263463-db795180-6097-11e9-8572-f37a359dc813.png)

![image](https://user-images.githubusercontent.com/894215/56263542-31e69000-6098-11e9-9946-93687f7e7e5f.png)

I asked Milenko about the spritesheets and he said UI_Elements_02.png is the correct spritesheet to be using (and the most current revision of UI_Elements_02_TUTORIAL.png does look exactly the same as UI_Elements_02.png). This seems like it would require some work:

1. UI_Elements_02_TUTORIAL.png sprites added to UI_Elements_02.png
2. UI_Elements_02.png sprites mapped
3. All the prefabs/objects references updated.

**Comment by mirasrael** [comment] 2019-05-01 10:43
Fixed in SVN

**Closed by mirasrael** 2019-05-01 10:43 UTC
Labels: Art, High Priority
