### ISSUE TITLE
No text in Linux version

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#5991] opened 2018-03-13 08:06 UTC
Posting this for a user from the support queue:

Hello I just bought the game after finding out that there was Linux support only to find that non of the text renders on Linux.  After opening the game for the first time everything looked ok but after a minute of playing all the text diapered and I am unable to fix it without deleting the game data and restarting.  Iv tried troubleshooting a bit and asking on the discord but they haven't herd of the issue before.  Ill attach the player.log file and a screen shot of the issue and am happy to supply other information if needed but If there is nothing that can me done about it at the moment I would like a refund for the game as it dose not work as advertised.  Let me know if you need any other information or have questions.

Thanks,
Kier

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/1805999/Player.log)

**Comment by MarjieAVolk** [comment] 2018-03-13 18:48
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5749

Linked your log file over there, thanks.

**Closed by MarjieAVolk** 2018-03-13 18:48 UTC
