### ISSUE TITLE
USER ISSUE: Sticking Icons

### ISSUE THREAD

**Issue by Hypnotique88** [StrangeLoopGames/EcoIssues#5372] opened 2018-03-04 16:48 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
When moving an object from my backpack to a chest or vise versa

**Expected behavior:**
The object should move from one storage to the next....

**Actual behavior:**
Instead the icon sticks to the screen and the object is gone

**Comment by MarjieAVolk** [comment] 2018-03-05 22:42
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-03-05 22:42 UTC
