### ISSUE TITLE
Increase music frequency somewhat, and force start after avatar selection. 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21653] opened 2021-04-29 17:53 UTC

**Comment by madpingui** [comment] 2021-05-06 20:42
I have been investigating the issue and it turned out that it was summarized in these lines, from the project we sent a trigger to wwise every so often with the time of the game day as a parameter.
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/2d1f2525-529a-4bc2-b78b-b32bcee9bf1f)

It turns out that from the Unity project nothing can be done about it, so I talked to Leonard (lpaul) about it and he confirmed this to me, he will be in charge of talking to John and adjust the parameter to how much music is gonna be listened in the day.

On the part of reproducing the music after the creation of the avatar, Mike (Quadbro) clarified for me that when modifying the frequency of the music this would not be necessary since after the creation of the avatar the music will sound not long after.

**Comment by WeaselDog** [comment] 2021-05-17 01:38
Was fixed by increasing frequency

**Closed by WeaselDog** 2021-05-17 01:38 UTC
Labels: Category: Audio, Priority: High, Type: Task
