### ISSUE TITLE
USER ISSUE: Second Character

### ISSUE THREAD

**Issue by MiLLHA** [StrangeLoopGames/EcoIssues#4130] opened 2018-02-08 20:21 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. Make a game. 
2. Play game.
3. Return to same world the day after
4. Get logged in as another character, and losing progress of first character. "PlayerName#2"
5. Se on the player list your old name "PlayerName"

**Expected behavior:**
I expected to contiue as my own character. 

**Actual behavior:**
But instead ended up as if a new player. PlayerName#2

**Comment by Conchipedia** [comment] 2018-02-08 20:24
duplicate of
Two Ingame Names appeared one for Steam and one for SLG #4045

**Comment by MiLLHA** [comment] 2018-02-08 21:16
SLG?

**Comment by MarjieAVolk** [comment] 2018-02-09 02:19
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4045

This has been happening to people who had already bought the game through our website, and had linked their Strange Loop Games account to their steam account in order to play on steam.  If that is the case, for now, if you want to play as your other character, you will need to play on the build downloaded from our website, instead of on steam.  We are working on a fix for this, which should get rolled out tomorrow, and will allow you to recover your old character and keep playing on steam.

**Closed by MarjieAVolk** 2018-02-09 02:19 UTC
