### ISSUE TITLE
8.0.0 Staging - Chat on Main screen partially hidden by UI bottom Left

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10874] opened 2019-01-24 20:10 UTC
Version: 0.8.0.0 beta staging-4705f5ae-1
![snap3901](https://user-images.githubusercontent.com/29383891/51705817-8f78bc80-2014-11e9-801c-12a3fa2ca054.png)

if you close chat window as its normally in the way, main chat on screen is hidden slightly by the UI bottom left of screen

**Comment by Conchipedia** [comment] 2019-02-17 20:28
the chat is now not hidden behind the Bottom Left UI (looks like that has been fixed) but is Now is hidden behind the Carrying Slot.
![snap4165](https://user-images.githubusercontent.com/29383891/52918734-4d305b80-32f2-11e9-91cb-0df2a4b761fa.png)

**Comment by elfl0rd** [comment] 2019-02-18 06:52
Duplicate of #11292

**Closed by elfl0rd** 2019-02-18 06:52 UTC
Labels: Low Priority
