### ISSUE TITLE
USER ISSUE: Icons being stuck on screen

### ISSUE THREAD

**Issue by sharpshot4321** [StrangeLoopGames/EcoIssues#4299] opened 2018-02-11 07:05 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Have 100+ ping, Drag any item to another spot. If the spot is not a valid item location (backpack, slot in chest, ect.) it occures far more often.

**Expected behavior:**
Items should either move or swap when put into a valid slot. Or return to prior slot if a valid slot is not found.

**Actual behavior:**
The icon remains stuck over the GUI. blocking view of anything under it. Also causes the slot it was in to appear empty,It will not allow the item to be picked up again, and blocks placing of any new items into said slot.

**Comment by MarjieAVolk** [comment] 2018-02-13 04:27
Closing as duplicate of #3841. You can track the issue progress there.

I hadn't heard until today that dragging it into an invalid item slot was related to this issue. That may be helpful. If you have any more details to share, every little bit helps!

**Closed by MarjieAVolk** 2018-02-13 04:27 UTC
