### ISSUE TITLE
crafting tables not progressing 

### ISSUE THREAD

**Issue by true2form** [StrangeLoopGames/EcoIssues#1679] opened 2017-06-19 14:37 UTC
if a crafting table is activated without all the ingredients it causes all tables within the localized area to stop progressing in alpha a88e14f2 even outside in a different room

**Comment by true2form** [comment] 2017-06-19 15:30
followed by this crash dump


[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1085480/output_log.txt)

**Comment by MarjieAVolk** [comment] 2017-06-20 20:42
We recently fixed a problem with crafting tables and carts getting frozen.  But this problem shouldn't have caused a crash.  Not sure what to make of the crash output there (but I see several other bugs in the log that I can fix... ;) )

**Comment by metachronism** [comment] 2017-08-15 23:46
closing as dupe of inventory perf problems fixed in alpha 6

**Closed by metachronism** 2017-08-15 23:46 UTC
