### ISSUE TITLE
USER ISSUE: crash on player init

### ISSUE THREAD

**Issue by XDMounir** [StrangeLoopGames/EcoIssues#18177] opened 2020-09-11 12:11 UTC
[Player.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5208820/Player.zip)

\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Login in the game

**Expected behavior:**
Be able to play

**Actual behavior:**
Not able to move - black sky - Most UI not showing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

NullReferenceException: Object reference not set to an instance of an object.
  at InteractionManager.ProcessInteraction (System.Boolean force) [0x00000] in <00000000000000000000000000000000>:0 
  at InteractionManager.LateUpdate () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
 
(Filename: currently not available on il2cpp Line: -1)

**Comment by beastyn** [comment] 2020-09-11 12:39
@XDMounir Thank you for the report. What server are you trying to connect?
Is it your first play session?

**Comment by XDMounir** [comment] 2020-09-11 12:42
White tiger.
No it happened after last night reset.
I got over 10 hours played on this rotation.



Envoyé depuis mon téléphone intelligent Samsung Galaxy.



-------- Message d'origine --------
De : Anna <notifications@github.com>
Date : 20-09-11 8 h 39 a.m. (GMT-05:00)
À : StrangeLoopGames/EcoIssues <EcoIssues@noreply.github.com>
Cc : Mounir <mounirabdous@hotmail.com>, Mention <mention@noreply.github.com>
Objet : Re: [StrangeLoopGames/EcoIssues] USER ISSUE:  (#18177)


@XDMounir<https://github.com/XDMounir> Thank you for the report. What server are you trying to connect?
Is it your first play session?

**Comment by beastyn** [comment] 2020-09-11 13:25
@XDMounir Did client restart help you?

**Comment by XDMounir** [comment] 2020-09-11 13:36
No restarted multiple time and its not working. If i log in giant panda and come back to white tiger the sky is workig properly and i can move but ui not showing.



Envoyé depuis mon téléphone intelligent Samsung Galaxy.



-------- Message d'origine --------
De : Anna <notifications@github.com>
Date : 20-09-11 9 h 25 a.m. (GMT-05:00)
À : StrangeLoopGames/EcoIssues <EcoIssues@noreply.github.com>
Cc : Mounir <mounirabdous@hotmail.com>, Mention <mention@noreply.github.com>
Objet : Re: [StrangeLoopGames/EcoIssues] USER ISSUE:  (#18177)


@XDMounir<https://github.com/XDMounir> Did client restart help you?

**Comment by beastyn** [comment] 2020-09-11 14:24
looks a bit like #17523 
Had there
``
[01:59:28.054] Caught exception on Otter while in NetObject ReceiveInitialState.
BSON: {
  id: 1546 (int),
  type: 'Otter' (string),
  species: (<Unknown View> 2045),
  controller: 6533 (int),
  state: 2 (int),
  tar: {
    route: 185 bytes (byte[]),
    start: 218539,710521736 (double)
  },
  health: 1 (float),
  a: 0 (float),
  swimming: True (bool)
}
```

**Comment by XDMounir** [comment] 2020-09-11 14:29
I dont have issue connecting to server. The issue seems to be the character state on white tiger. Works fine when on others servers. The ui is not showing up. (Its not a alt-z issue) and cannot move.



Envoyé depuis mon téléphone intelligent Samsung Galaxy.



-------- Message d'origine --------
De : Anna <notifications@github.com>
Date : 20-09-11 10 h 25 a.m. (GMT-05:00)
À : StrangeLoopGames/EcoIssues <EcoIssues@noreply.github.com>
Cc : Mounir <mounirabdous@hotmail.com>, Mention <mention@noreply.github.com>
Objet : Re: [StrangeLoopGames/EcoIssues] USER ISSUE:  (#18177)


looks a bit like #17523<https://github.com/StrangeLoopGames/EcoIssues/issues/17523>
Had there

[01:59:28.054] Caught exception on Otter while in NetObject ReceiveInitialState.
BSON: {
  id: 1546 (int),
  type: 'Otter' (string),
  species: (<Unknown View> 2045),
  controller: 6533 (int),
  state: 2 (int),
  tar: {
    route: 185 bytes (byte[]),
    start: 218539,710521736 (double)
  },
  health: 1 (float),
  a: 0 (float),
  swimming: True (bool)
}

**Comment by XDMounir** [comment] 2020-09-11 15:48
![image](https://user-images.githubusercontent.com/44792025/92946430-a60b9b80-f424-11ea-86ab-a7916de56aa0.png)

**Comment by XDMounir** [comment] 2020-09-11 15:49
![image](https://user-images.githubusercontent.com/44792025/92946628-e703b000-f424-11ea-92d8-f8322cc5f3f2.png)

**Comment by XDMounir** [comment] 2020-09-11 21:23
[05:22:01.621] Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: ArgumentException
Message:Object of type 'Eco.Gameplay.Aliases.AliasSelector' cannot be converted to type 'Eco.Gameplay.Economy.BankAccount'.
Source:System.Private.CoreLib

System.ArgumentException: Object of type 'Eco.Gameplay.Aliases.AliasSelector' cannot be converted to type 'Eco.Gameplay.Economy.BankAccount'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Shared.Networking.RPCManager.TryInvoke(INetClient client, Object target, String methodname, BSONArray bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname)</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
System.Threading.WaitOrTimerCallback:Invoke(Object, Boolean)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass59_0:<Initialize>b__0()
HighlightingSystem.OnEndOfFrame:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
HighlightingSystem.OnEndOfFrame:Invoke()

**Comment by redwyre** [comment] 2020-09-21 19:46
In the meantime you can set your language to English? If that fixes it, it's a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18132

Should be fixed with https://github.com/StrangeLoopGames/Eco/pull/6818 Which will be available in 9.0.3.

**Comment by redwyre** [comment] 2020-09-21 20:17
Duplicate of #18132

**Comment by beastyn** [comment] 2020-09-22 11:12
Let's check after 9.0.3 release. Please, wrtire here if it will appear after 9.0.3 update. Thanks!

**Closed by beastyn** 2020-09-22 11:12 UTC
Labels: Category: Tech, Priority: High
