### ISSUE TITLE
Sychthe bulk harvest causing assert

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22104] opened 2021-06-04 23:49 UTC
![image](https://user-images.githubusercontent.com/3536496/120872869-c94b1d80-c554-11eb-8227-dff608c2b47a.png)

**Comment by johnkslg** [comment] 2021-06-04 23:49
![image](https://user-images.githubusercontent.com/3536496/120872889-d8ca6680-c554-11eb-8251-a9d39d126e48.png)

**Comment by johnkslg** [comment] 2021-06-04 23:50
Its failing something but then continuing to process when it shouldnt.  Probably affects other tools too.

**Comment by Daniel-Magulado** [comment] 2021-06-07 20:20
Might be a duplicate of #22090

**Closed** 2021-06-08 07:05 UTC
