### ISSUE TITLE
9.3.0 1928 Migration 9.2.X to 9.3 = No Hands Mah!

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20517] opened 2021-02-12 17:45 UTC
Migrate a world that is on 9.2.x to 9.3.0 1928 that your character has already joined and you'll get no hands

New 9.3.0 worlds are fine, joning a 9.2.4 world for first time also fine

![image](https://user-images.githubusercontent.com/61889138/107803107-14e57b80-6d5a-11eb-9610-7bb4fb6caa4d.png)

**Comment by MishkaFur** [comment] 2021-02-13 20:03
StalEF found workaround, manually spawning in JazzHands then equipping them into the gloves slot

**Comment by WeaselDog** [comment] 2021-02-22 05:50
There needs to be a migration that checks if a player have Jazz Hands, and if not add them. It could also check if it a user who is migrating to 9.2+ for the first time.

**Comment by StallEF** [comment] 2021-02-23 19:09
@WeaselDog there is also a problem with feet, but FungiFeetItem fix it 
![2021-02-23 (12)](https://user-images.githubusercontent.com/26339332/108894385-42b4a500-7623-11eb-8355-9794c26eb0ab.png)
if during migration the player is wearing any boots, then when they are removed at 9.3 to feet there are no

**Comment by WeaselDog** [comment] 2021-02-25 21:02
Can you test legs as well?

**Comment by beastyn** [comment] 2021-02-26 05:34
@WeaselDog yeah, I brought back both of them.

**Comment by SlayksWood** [comment] 2021-02-26 13:02
Need more migrations and testing to close it, today I don't have it.

**Comment by Daniel-Magulado** [comment] 2021-02-26 20:08
Couldn't reproduce.

Created new world on 0.9.2.4 Release-164. Played an hour or so. Closed the game and then upgraded the client to 0.9.3 Staging 1940 via Steam. My avatar's hands and feet are okay.

Did another test by doing the same thing. Generated world with 0.9.2.4 Release 164 build. Played an hour and removed all clothes first before quitting. Then upgraded to 0.9 Staging. Still not happening.

Video Migration
https://drive.google.com/file/d/1-9Z9ENzbD92AbrhxGD8VN3IEbHdwylIX/view?usp=sharing

**Comment by Daniel-Magulado** [comment] 2021-03-08 10:23
Tested on 0.9.3 Staging-1948 and 0.9.2.4 beta release-156.

Conducted 3 tests.

Created a new game using 0.9.2.4 beta release-156 and played for an hour.
Migrated the save to 0.9.3 Staging-1948.
Unable to reproduce the issue.

Created a new game using 0.9.2.4 Release-164 and played for an hour.
Migrated the save to 0.9.3 Staging-1948.
Unable to reproduce the issue.

Created a new game using 0.9.2.4 beta release-156 and played for an hour.
Migrated the save file to  0.9.2.4 Release-164 and then played for an hour.
And then migrated the save to 0.9.3 Staging-1948.
Unable to reproduce the issue.

Closing.

**Closed by Daniel-Magulado** 2021-03-08 10:23 UTC
Labels: Category: Tech, Priority: High, Squad: Mountain Goat, Status: Fixed
