### ISSUE TITLE
USER ISSUE: Dead Plants, after 24 houres despawn and blocked the filed.

### ISSUE THREAD

**Issue by Skulhero** [StrangeLoopGames/EcoIssues#5573] opened 2018-03-07 12:19 UTC
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
When plant die because there dead since 24 Houres, they despawn, but on the same field u cant plant new plants. There came the message: Plant already exist there.

**Expected behavior:**
It should be posssilble to plant new plants on the same block.

**Actual behavior:**
U cant plant anything on this block. U can also put the earth block out and put another in. Always the Message came: Plant already exist there.

**Comment by MarjieAVolk** [comment] 2018-03-08 19:34
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5522

**Closed by MarjieAVolk** 2018-03-08 19:34 UTC
