### ISSUE TITLE
USER ISSUE: Вылет при разбивании гранита (Departure when breaking granite)

### ISSUE THREAD

**Issue by DJRelax** [StrangeLoopGames/EcoIssues#23841] opened 2023-05-26 17:18 UTC
\
**User Id: (slg216538)**
**Version:** 0.10.0.0 beta staging-2636

**Steps to Reproduce:**
1. Разбиваем гранит и ... (Breaking granite and ...)

**Expected behavior:**
Это уже повторяется второй раз, в одном и том же месте (This is already repeated for the second time, in the same place)

**Actual behavior:**
Было получено следующее сообщение об ошибке: (The following error message was received:)
```
Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'key')
Source:System.Private.CoreLib

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Interactions.Interactors.InteractionDefinitionManager.GetInjectedInteractionMethod(InteractionTarget target, InteractionTriggerInfo triggerInfo, Type associatedType)
   at Eco.Gameplay.Interactions.Interactors.HandsInteractor.Eco.Gameplay.Interactions.Interactors.IInteractor.DoInteraction(Player player, InteractionTriggerInfo trigger, InteractionTarget target)
   at InvokeStub_IInteractor.DoInteraction(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Нет модификаций (No modifications)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Eco_Client.zip](https://github.com/StrangeLoopGames/EcoIssues/files/11578379/Eco_Client.zip)
[ECO_Server.zip](https://github.com/StrangeLoopGames/EcoIssues/files/11578398/ECO_Server.zip)

**Comment by D3nnis3n** [comment] 2023-05-27 22:35
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23816

**Closed by D3nnis3n** 2023-05-27 22:35 UTC
