### ISSUE TITLE
USER ISSUE: Exception error upon execution of task that requires tax

### ISSUE THREAD

**Issue by qlmabry** [StrangeLoopGames/EcoIssues#9887] opened 2018-10-27 22:06 UTC
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Player "Buurtvader Karim" was trying to dump tailings which required tax and they had no currency to pay the tax. This resulted in an exception error and caused the server to crash and reboot

**Expected behavior:**
Player should have been taxed and allowed to dump tailings without server crashing.

**Actual behavior:**
Player action caused an exception error which crashed server.

**Error Message:**
--BEGIN DUMP--
Dump Time
10/27/2018 16:51:29

Exception
Exception: Exception

Message:A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: You cannot afford to pay a tax of <b><link="Currency:18e877de-93c1-428f-976a-f65de55db773"><style="Currency">1 Metros</style></link></b>

Source:Eco.Core

System.Exception: A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: You cannot afford to pay a tax of <b><link="Currency:18e877de-93c1-428f-976a-f65de55db773"><style="Currency">1 Metros</style></link></b>
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.WorkOrder.UpdateCrafted()
   at Eco.Gameplay.Items.WorkOrder.set_Progress(Double value)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by D3nnis3n** [comment] 2018-10-28 07:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9485

**Closed by D3nnis3n** 2018-10-28 07:11 UTC
