### ISSUE TITLE
Oil Refinery has significant issues

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16898] opened 2020-06-28 05:32 UTC
During the most recent playtest, we have tracked the major source of over-pollution to the Oil Refinery. There are a few reasons for this:
- Multiple refineries are running 24/7. With barrels being refunded 100%, we can setup a loop where the oil refineries run indefinitely as long as the labor as been added. 
- It is world object with the highest pollution
- Late game we need a very large supply of Fiberglass & Epoxy for crafting circuits and other recipes, making a huge demand for products made from oil drilling

Edit: This issue is designed to address the oil refinery loop. We have a separate issue for pollution.

**Comment by elfl0rd** [comment] 2020-06-28 11:31
Two things.
1) chemical reagents for oil refining
2) smoke filters

**Comment by mirasrael** [comment] 2020-06-29 07:51
Probably it is good to have pollution as limiting factor for infinite craft? So you may decide to don't control pollution from oil refinery and let the world go underwater or you should add restrictions to oil refinery (like daily quotas) to avoid ecological catastrophe.

**Comment by WeaselDog** [comment] 2020-06-29 17:01
This is only possible through laws. The infinite craft is a separate issue from pollution. Oil refinery infinite craft was one of the main complaints from the last playtest.

**Comment by elfl0rd** [comment] 2020-07-11 16:50
It's a bad and illogical way to fix it.
First of all, eco is not a winwin game, the chance to make a mistake and kill the environment - part of the simulator, players in this case may be limited by themselves or by laws.
Second of all... Instead of fixing the mechanics or the root cause, you make crutches.

"Why do refineries work 24 hours a day?" because their products are needed in huge quantities and they are produced very slowly.

"What is the logical way to limit the continuous production cycle in a refinery?"
Add the chemicals needed to refine the oil.

I do not support or accept this change, I consider it ugly and a thing that will be fixed by administrators as in 8.
(But in that case, why do you need "balancers" in SLG?)

**Comment by WeaselDog** [comment] 2020-07-11 16:57
The plan is to add chemicals for refining in the future.

**Comment by elfl0rd** [comment] 2020-07-11 17:24
In that case, maybe the problem is not with the refinery at all? After all, players may have the same blast furnaces running for a very long time.

In this case it is probably worth checking the functionality of the "optimized" pollution system?

**Comment by WeaselDog** [comment] 2020-07-11 17:28
Yes, there is a seperate issue for this: https://github.com/StrangeLoopGames/EcoIssues/issues/16478

I agree that the values for pollution must be adjusted and that Oil Refinery is not the only issue.

**Comment by WeaselDog** [comment] 2020-07-13 04:49
I will keep this open for now. Ignoring the pollution side of things, we want to fix the oil refinery in a more eloquent way.

**Closed** 2020-07-13 11:18 UTC
Labels: Category: Balance, Priority: Medium
