### ISSUE TITLE
USER ISSUE: crash on pick up wood

### ISSUE THREAD

**Issue by patograso** [StrangeLoopGames/EcoIssues#4700] opened 2018-02-17 12:19 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
pick up wood

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à TreeEntity.PickupLog(Player player, Guid logID)
   à TreeEntity.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à TreeEntity.PickupLog(Player player, Guid logID)
   à TreeEntity.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-23 21:58
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-23 21:58 UTC
