### ISSUE TITLE
Stove output pipe is in the wrong location

### ISSUE THREAD

**Issue by Montresor99** [StrangeLoopGames/EcoIssues#5951] opened 2018-03-12 17:37 UTC
![stove issue](https://user-images.githubusercontent.com/37306594/37299705-6706bdd4-25fa-11e8-92bc-ddc0eebdbe8d.png)
Pic is of the stoves exhaust pipe working properly

**Comment by Montresor99** [comment] 2018-03-12 18:03
This also causes other benches connected to the pipe to exhaust here

**Comment by MarjieAVolk** [comment] 2018-03-13 22:35
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5805

**Closed by MarjieAVolk** 2018-03-13 22:35 UTC
