### ISSUE TITLE
Windows Explorer opened when Eco running causing server list to crash

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6872] opened 2018-04-02 02:50 UTC
Getting reports of ntdll.dll fault being reported by windows when clicking Eco Server list or trying to 'add server' 'refresh' 'stop'.   Upon further investigation it appears that there is a Data execution prevention being set off if explorer is opened when Eco is in use.  For troubleshooting you can disable the data execution in explorer but that is not even necessary; simply making sure windows explorer and any app using windows explorer is close and the error stops happening:  The following lead us to look at this:

Faulting application name: Eco.exe, version: 2017.4.0.48407, time stamp: 0x5aa917c7
Faulting module name: ntdll.dll, version: 10.0.16299.248, time stamp: 0xeffc9126
Exception code: 0xc0000374
Fault offset: 0x00000000000f87bb
Faulting process id: 0x4720
Faulting application start time: 0x01d3ca285f0d45a4
Faulting application path: E:\SteamLibrary\steamapps\common\Eco\Eco.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: a18be2de-3e9a-4c59-98e0-3d6709db3953
Faulting package full name: 
Faulting package-relative application ID:
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Eco.exe
P2: 2017.4.0.48407
P3: 5aa917c7
P4: StackHash_9cf4
P5: 10.0.16299.248
P6: effc9126
P7: c0000374
P8: PCH_E0_FROM_ntdll+0x00000000000A09D4
P9: 
P10: 

Attached files:
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER18A8.tmp.dmp
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E28.tmp.WERInternalMetadata.xml
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E2A.tmp.csv
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E4A.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Eco.exe_5f09e4a4b1fe35c94427b408929538125363a1_7f2d6e50_43a62829

Analysis symbol: 
Rechecking for solution: 0
Report Id: eb941e72-e9a2-4f02-a238-5ea2febb4e9f
Report Status: 97
Hashed bucket:

This might not be the only cause, because some people do not have explorer open that they know of and are having the issue,  and it's not the solution,  but right now it seems to be a work around and so far all instances of this that have had windows explorer open found that shutting it down caused the crashing when using the server list to stop

**Comment by MarjieAVolk** [comment] 2018-04-02 22:27
???

Well, we have been getting a handful of reports about the game crashing in the Join screen or while connecting.

**Comment by MarjieAVolk** [comment] 2018-04-02 23:10
Okay, trying to consolidate these, so closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6821

I'm asking some others to try out your suggestion, see if it repros.  Thanks

**Closed by MarjieAVolk** 2018-04-02 23:10 UTC
Labels: High Priority
