### ISSUE TITLE
USER ISSUE: NullReferenceException while running

### ISSUE THREAD

**Issue by Gareon** [StrangeLoopGames/EcoIssues#6109] opened 2018-03-15 21:34 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Unknown; I was just running (fast) through a newly generated map (140x140).

**Expected behavior:**
NullReferenceException must never raise.

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Object reference not set to an instance of an object


Stack:
  at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates (System.Collections.Generic.IEnumerable`1[T] newObjects, Eco.Shared.Networking.INetObjectViewer viewer, System.Collections.Generic.ICollection`1[T] monitored) [0x0001c] in <226b109000b746a38ec300eaaddcb16d>:0 
  at Eco.Plugins.Networking.Clients.Client.Update (System.Diagnostics.Stopwatch timer) [0x000b9] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1 () [0x00012] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-15 21:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-15 21:40 UTC
