### ISSUE TITLE
USER ISSUE: Black screen

### ISSUE THREAD

**Issue by Witherking99** [StrangeLoopGames/EcoIssues#6431] opened 2018-03-24 02:54 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Pull a cart
2. ???

**Expected behavior:**
You should proceed as normal

**Actual behavior:**
Instead, you can continue moving, but you can't see anything except the sun, the moon and the meteor

**Comment by MarjieAVolk** [comment] 2018-03-28 19:26
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4370

**Closed by MarjieAVolk** 2018-03-28 19:26 UTC
