### ISSUE TITLE
USER ISSUE: Can´t continue game 

### ISSUE THREAD

**Issue by Muman187** [StrangeLoopGames/EcoIssues#5054] opened 2018-02-24 19:33 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. crafted a standing torchlight
2. put a torch as fuel in it
3. computer crashed; totaly frozen
4. had to restart my computer
5. execute game 
6. continue game
7. loading.... than pop up a message "Connection Failed"

**Expected behavior:**
Loading the last save?

**Actual behavior:**
The following error message popped up:
```Connection Failed

**Comment by MarjieAVolk** [comment] 2018-02-26 18:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4995

Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO might help as a workaround.

**Comment by CompactDisc** [comment] 2019-04-12 18:02
This issue still exists in 8.1.0, why is it closed?

**Comment by mirasrael** [comment] 2019-04-12 20:41
@CompactDisc do you have exactly same issue with torchlight as described in description? Can you please attach server crash log then?

**Comment by mirasrael** [comment] 2019-04-12 20:42
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files

**Comment by CompactDisc** [comment] 2019-04-12 20:59
> @CompactDisc do you have exactly same issue with torchlight as described in description? Can you please attach server crash log then?
I had the issue happen while testing the new SLG hosting service. I can't access the logs there. The server didn't even crash, only the client did. Though I couldn't reconnect to the server again. Until I removed the entire server world. Other clients could connect fine though, while I kept having that issue.

Client crash log is available in attachment.
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3075158/output_log.txt)
[output_log_copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3075161/output_log_copy.txt)

**Comment by mirasrael** [comment] 2019-04-13 04:14
@CompactDisc so what about torch? Did you put it before the crash (as said in issues description)? Or you had another actions which caused this problem?

**Comment by CompactDisc** [comment] 2019-04-13 12:24
> @CompactDisc so what about torch? Did you put it before the crash (as said in issues description)? Or you had another actions which caused this problem?

It only happened to me when putting a torch into a standing torch stand. No other ways discovered to do it yet.

**Comment by mirasrael** [comment] 2019-04-15 09:01
@CompactDisc can you say name of the server (or server id) where I can check server log?

**Comment by CompactDisc** [comment] 2019-04-15 09:27
Here's the server ID: 050001645d0e45059a2fcd5517225121

It's the first crash the server ever had. I just logged in the first time and was doing the tutorial :P

**Comment by mirasrael** [comment] 2019-04-15 09:42
Ok. Thanks! I asked QA and they says this issue was in 8.1.0, but in 8.1.2 it seems to be fixed. Can you check?

**Comment by CompactDisc** [comment] 2019-04-15 12:06
> Ok. Thanks! I asked QA and they says this issue was in 8.1.0, but in 8.1.2 it seems to be fixed. Can you check?

I can't update the server hosted by you, because it's bugged atm. But I started my own steam-based server. The issue seems to be gone there, apologies for posting the issue here.

**Comment by beastyn** [comment] 2019-04-15 12:12
@CompactDisc Thank you for your patience and attention, Enjoy the game!

**Closed by beastyn** 2019-04-15 12:12 UTC
Labels: Critical Priority
