### ISSUE TITLE
USER ISSUE: Logs bug with workbench

### ISSUE THREAD

**Issue by hannahbex** [StrangeLoopGames/EcoIssues#4018] opened 2018-02-07 03:56 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
Logs refuse to be put into the workbench.

**Expected behavior:**
It should have been put in the crafting queue (started 25 blocks).

**Actual behavior:**
It refused to go into the workbench.

**Comment by hannahbex** [comment] 2018-02-07 04:00
You can see a small video on it here: https://youtu.be/6rANc2mbDPg

**Comment by MarjieAVolk** [comment] 2018-02-07 23:43
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3010 - You can track the bug there if you are interested.

We have seen this issue off and on for a while, but haven't been able to reliably reproduce it.  If you have any information on when or why this happens, it would be very useful.

In the mean time, can you add your materials to the workbench by right clicking on the workbench while holding them?

**Closed by MarjieAVolk** 2018-02-07 23:43 UTC
