### ISSUE TITLE
USER ISSUE: Items disappear when elevated platform is created.

### ISSUE THREAD

**Issue by PuerNoctis** [StrangeLoopGames/EcoIssues#6922] opened 2018-04-03 13:33 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Build a house with furniture in it (e.g. Chests, Anvils, etc...)
2. Build a platform way up in the sky above the house (I used the unstuck command to get on higher ground, about 60 blocks above the house. The intention was to build "a skycastle"). Note that there were no connecting blocks between the lower house and the upper platform. So basically, build a house with stuff in it and then a floating platform waaaay up in the sky above it.
3. Log out, return after several hours (don't know how long you actually have to wait).

**Expected behavior:**
Everything is fine.

**Actual behavior:**
All furniture/items below the "skycastle" disappeared, this included CHESTS and STOCK PILES with content. The disappearence however seems to be visual only. If I open the blast furnace outside my house I can still see the linked containers with their contents, but they are nowhere to be found in the world to interact with. Tearing down the platform in the sky did not bring them back after immeadiately logoff/login. I am now afraid to build new stuff in the places where the old items used to be.

**Comment by PuerNoctis** [comment] 2018-04-03 15:54
Update: Newly places items under the affected area (where the elevated platform was) disappear immediately. The game reserves the space though, as in if you try to build something else in its place, it will tell you that the item cannot be placed there.

Wasn't able to restart the server to test if it fixes things, the game clearly recognizes that the items are there, it just doesn't render them. Have to wait until our admin gets back.

**Comment by MarjieAVolk** [comment] 2018-04-03 18:03
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6693

If this isn't fixed by a server restart, a save file might be useful.

**Closed by MarjieAVolk** 2018-04-03 18:03 UTC
