### ISSUE TITLE
Plants that die due to overcrowding (no pollution) should either disappear or get stuck at a younger age.

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14673] opened 2020-02-10 20:03 UTC
![image](https://user-images.githubusercontent.com/14983165/74184779-3f0ed580-4bfc-11ea-9584-847585845c1d.png)

Right now the way plants die in groups of plants looks wrong-- if these plants died due to soil nutrient problems, they should all be dead in a blob where the bad soil is-- and if they died due to overcrowding, they should just either disappear or stop growing at a certain age. 

This is mostly an aesthetic problem, but in general we should try to make the simulation have plants die in their dramatic way with the death texture when there is a localized issue, and otherwise we should have them just stop growing rather than die.

Perhaps we can add a sort of 'stunted' status to plants that means they are not dead but have reached the limit for their growth due to lack of resources, overcrowding, or light.

Also, when plants die of old age I think they should be quicker to remove themselves fully.

**Comment by WeaselDog** [comment] 2020-10-12 09:25
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/17012

**Closed by WeaselDog** 2020-10-12 09:25 UTC
Labels: Category: Gameplay, Priority: Low
