### ISSUE TITLE
USER ISSUE: Homestead Stake/Claims

### ISSUE THREAD

**Issue by GodlyTP** [StrangeLoopGames/EcoIssues#23972] opened 2023-08-15 05:52 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-95

**Steps to Reproduce:**
Place down the stake and pick it up while have the maxed out claims.

**Expected behavior:**
Not delete the stake, the returned claims, and the use of claiming.

**Actual behavior:**
Deletes stake, claims are set to 0 of 0, and can't claim cause of lack of claim.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by GodlyTP** [comment] 2023-08-15 05:53
I don't really need help cause it is only playtest, but I ought to let it be known to help assist in the bug fixing.

**Comment by Daniel-Magulado** [comment] 2023-08-24 19:57
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23931/

**Closed by Daniel-Magulado** 2023-08-24 19:57 UTC
