### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by bfaltrep** [StrangeLoopGames/EcoIssues#5076] opened 2018-02-25 12:53 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
cut a tree trunc on the floor

**Expected behavior:**
some pieces of wood separate from the trunc

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-26 19:55
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-26 19:55 UTC
