### ISSUE TITLE
[0.9.0.4] weight inscription does not fit into the cart

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#18670] opened 2020-10-09 17:47 UTC
the inscription does not fit, a line feed occurs
![изображение](https://user-images.githubusercontent.com/13696708/95615205-817d0080-0a70-11eb-99df-195c9ada08a7.png)

**Comment by SlayksWood** [comment] 2020-10-12 06:03
Step to reproduce:
- place stockpile with Sandstone and empty wood cart:
![image](https://user-images.githubusercontent.com/45708377/95710519-8d7fe280-0c69-11eb-89bf-ff872521fdf8.png)
- open stockpile:
![image](https://user-images.githubusercontent.com/45708377/95710556-9d97c200-0c69-11eb-9d51-1895aae4aae6.png)
- drag sandstone to wood cart with Shift:
![image](https://user-images.githubusercontent.com/45708377/95710620-b607dc80-0c69-11eb-9d60-e03eff83c854.png)

**Comment by IcedForge** [comment] 2020-10-28 14:36
Need to check this after sergeys storage fix for any possible localization issues.

**Comment by IcedForge** [comment] 2021-01-26 09:49
This is still being a problem in the initial phase, if you close down the window and reopen it aligns itself but it shouldnt display in such a way in the first place, for instance if you drag to cart, then drag back to stockpile and then to the cart again it updates correctly. 

Needs to solve why this is happening to the initial opening of a ui interface.(9.3 develop build 167)

![Screenshot_18.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/ffe75af6-abf6-48c4-997e-af034c25e490)

**Comment by abaza121** [comment] 2021-01-28 12:24
I couldn't reproduce it on Editor but I think it is an edge case where the initiation is different on editor than IL2CPP, I have adjusted the code to fix it.

**Comment by Daniel-Magulado** [comment] 2021-02-24 08:05
Tested on 0.9.4 Develop - 192

Fixed and closing.

**Comment by TwixterZ** [comment] 2021-06-29 04:28
Fix tested and confirm as of 0.9.4 staging-2037

https://user-images.githubusercontent.com/78054747/123737325-5889ed80-d8d5-11eb-8666-ab35da720dba.mov

**Closed by TwixterZ** 2021-06-29 04:28 UTC
Labels: Category: UI, Priority: Low, Squad: Wild Turkey, Status: Fixed
