### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Cumfast** [StrangeLoopGames/EcoIssues#5327] opened 2018-03-03 12:10 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
чёрный экран

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-03-07 20:32
We will need a lot more details in order to look at this bug.  Do you see a black screen instead of the title screen?  What operating system are you on?

**Comment by MarjieAVolk** [comment] 2018-03-08 21:29
Closing as duplicate of #4834. The workaround posted there may help you.

**Closed by MarjieAVolk** 2018-03-08 21:29 UTC
