### ISSUE TITLE
Store and table causing disconnects

### ISSUE THREAD

**Issue by DiploBlock** [StrangeLoopGames/EcoIssues#4218] opened 2018-02-10 03:01 UTC
UPDATE: Every time i use a table to make a project or to add materials to a current project i am being kicked for inactivity. This is the same for everyone on my server and it is a huge playability issue. 

Adding items to tables while items are being processed is causing huge lag spikes/ game lockup. This is also happening when making store transactions and adding people permissions to deeds. It almost always causes kicks due to inactivity. Issues related to these lockups include other players having chunk loading problems and falling through the world.

**Comment by Blanclour** [comment] 2018-02-10 03:09
I can confirm that this is also happening on my server.

**Comment by MarjieAVolk** [comment] 2018-02-12 20:21
I believe that this behavior was because of other systems lagging the whole server, which caused clients to get blocked waiting for responses from the server.  Over the weekend we released a hotfix that took some emergency steps to improve this.  Are you seeing better behavior now?

**Comment by MarjieAVolk** [comment] 2018-02-13 23:19
Going to close this, as I believe it was resolved.  If that is not the case, let me know.

**Closed by MarjieAVolk** 2018-02-13 23:19 UTC
