### ISSUE TITLE
USER ISSUE: I have Ascended to Heaven

### ISSUE THREAD

**Issue by ConeFiend420** [StrangeLoopGames/EcoIssues#19786] opened 2020-12-18 12:02 UTC
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
Stand on a rock that needs to be cut one more time while your buddy who is one massive drugs smacks it, you will then soar into the sky so fast and so far you see the planet look like the black hole in the movie Interstellar, you know, that one with Anne Hathaway. 

If you havent seen that movie, I highly recommend you should and most certainly be on copious amounts of narcotis, anyways, I am now stuck on what appears to be a plane of existance that is entirely grey with a sunlike light in the "sky." Is this a addon in your latest patch where you fucking die? 

Love to hear from you soon,

Finglebok@hotmail.com

<3

**Expected behavior:**
Not fucking done that

**Actual behavior:**
Done that

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, this game is a fresh install, however, as it was loading it said loading mods, but i do believe that is a normal thing

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment] 2020-12-18 12:39
Duplicate behavior of #18166 has been resolved in 9.2 ( not able to reproduce it on staging at least ).

**Closed by IcedForge** 2020-12-18 12:39 UTC
