### ISSUE TITLE
Authorisation Overlay overlays chat

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10968] opened 2019-01-30 12:45 UTC
This should be solved differently:
![bug1overlay](https://user-images.githubusercontent.com/25908592/51982064-418d0a00-2495-11e9-88b1-13489231ece1.png)

**Comment by elfl0rd** [comment] 2019-01-30 13:13
Duplicate of #10874

**Closed** 2019-01-30 13:22 UTC
Labels: Quality Assurance
