### ISSUE TITLE
9.0 1602 - Unable to have a decimal in law payment/tax

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16655] opened 2020-06-13 17:05 UTC
Trying to add a law that includes payment/tax which includes a deciminal ie 4.75 but it just removes it and goes to 475

![image](https://user-images.githubusercontent.com/61889138/84574738-6d661280-ada0-11ea-82c9-154a1869bb38.png)

Soon as I click away from it, it removes the decimal

![image](https://user-images.githubusercontent.com/61889138/84574743-79ea6b00-ada0-11ea-944a-b6b46e4246f7.png)

**Comment by henrikolsson** [comment] 2020-06-13 22:54
This was supposed to be fixed with #16411...

**Comment by trickenso** [comment] 2020-06-13 23:22
I'm having the opposite problem, where both 1,000 and 1.000 both become 1.
4.75 works fine.

On UK number settings, in case that makes a difference.

**Comment by trickenso** [comment] 2020-06-14 00:00
I'm also on UK number settings (same as Mishka), and this works almost as I would expect on a local game: 4.75 and 4,75 both show 4.75 in the summary on the top left, and in the 'Amount' box:
![image](https://user-images.githubusercontent.com/48172405/84581529-154c0200-adda-11ea-9d0b-dff4c9a51fbd.png)
(Ideally, with these settings 4,75 would become 475)

On the playtest server (which might be on European number settings?) 4.75 and 4,75 both add 4,75 into the summary in the top left, but show 475 in the 'Amount' box, same as in Mishka's screenshots.

**Comment by beastyn** [comment] 2020-06-15 07:45
So, it's from you OS settings? As we don't have this issue.
@johnkslg need some decision here

**Comment by trickenso** [comment] 2020-06-15 11:04
> So, it's from you OS settings?

Not certain it's this, just a suspicion given Mishka and I use the same settings and the playtest server presumably uses European default. Russia also uses decimal comma, so perhaps this is why you're not seeing it?

**Comment by beastyn** [comment] 2020-06-15 11:25
For now its the only theory we have)

**Comment by johnkslg** [comment] 2020-06-16 22:58
@gzatravkin can you take a look?  Maybe related to code that swaps which type of comma is used

**Comment by beastyn** [comment] 2020-06-18 06:34
Will close, but need test on playtest.
Write if happens again.

**Comment by trickenso** [comment] 2020-06-18 08:42
Still a problem in 1605 - after entering '4.75':
![image](https://user-images.githubusercontent.com/48172405/84998465-c7bbf600-b147-11ea-9ded-1a73a7a6c116.png)
I think it's functional, but confusing. The law summary uses comma instead of point, and the 'amount' box doesn't show decimal at all.

**Comment by gzatravkin** [comment] 2020-06-18 10:00
@beastyn do 1605 includes https://github.com/StrangeLoopGames/Eco/pull/6263?

**Comment by beastyn** [comment] 2020-06-18 10:04
Nope, playtest was not updated yet. )

**Comment by trickenso** [comment] 2020-06-18 10:17
Apologies - wasn't aware! Will wait for 1610

**Comment by MishkaFur** [comment] 2020-06-26 20:03
This is still occuring, playtest is on build 1611

Below screenshot is on UK default settings where comma is thousand seperator and dot is decimal
![image](https://user-images.githubusercontent.com/61889138/85896389-45d76700-b7f0-11ea-83b0-dd223facc20a.png)

Below is where in Windows 10 1903 it is set to be that dot is thousand seperator and comma is decimal, looks identical a new law was created each time
![image](https://user-images.githubusercontent.com/61889138/85896447-643d6280-b7f0-11ea-96db-e84c447e018f.png)

**Comment by MishkaFur** [comment] 2020-06-26 20:06
Above two screenshots were doing to set it to be 1100 money

still got my original issue too which was meant to be 12.34 not 1234 money 

![image](https://user-images.githubusercontent.com/61889138/85896687-d615ac00-b7f0-11ea-8de6-cb74f7bc5505.png)

**Comment by MishkaFur** [comment] 2020-06-26 20:08
And if I enter 1000 it shows up as 1  in the law config but 1.000 in the top left where it explains the law :D

**Comment by beastyn** [comment] 2020-06-29 06:02
Ok, let's try something else
@johnkslg @gzatravkin 
still an issue

**Comment by gzatravkin** [comment] 2020-07-01 23:34
After 6332 it should not change amount value after editing. 
The text of description still will have server format (this text is generated at server side). 

And you should be able only to enter in input only symbol of decimal separator, but not thousand separator.

**Comment by beastyn** [comment] 2020-07-03 06:28
Waiting for the playtest update for this. Won't close for now.

**Comment by beastyn** [comment] 2020-07-27 10:54
@MishkaFur Soooo, did you have this decimal issue with the last playtest?

**Comment by MishkaFur** [comment] 2020-07-27 11:34
Yep, I haven’t tried in the newest build since this new cycle started, so it was still affecting 1668, might be sorted in stable3 and newer

Can check tonight

**Comment by beastyn** [comment] 2020-07-29 10:43
@MishkaFur would be much appreciated

**Comment by beastyn** [comment] 2020-08-04 11:16
Will close for now. Tell if the problem is still here.

**Closed by beastyn** 2020-08-04 11:16 UTC
Labels: Category: UI, Priority: High, Status: Fixed
