### ISSUE TITLE
Ping and FPS counter not aligned correctly in escape menu

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#9122] opened 2018-08-29 21:29 UTC
![image](https://user-images.githubusercontent.com/3150561/44816719-eb3f3680-ab97-11e8-893a-3a3084db3e0b.png)

**Comment by metachronism** [comment] 2018-10-16 22:55
unusable in certain resolutions

**Comment by SlayksWood** [comment] 2019-04-18 12:41
FPS and Ping is always displayed correctly on my resolution .

**Comment by SlayksWood** [comment] 2019-04-18 12:43
FPS and Ping is always displayed correctly on my resolution (1680х1050).
I can’t set a resolution other than 16:10.

**Comment by GophTheGreat** [comment] 2019-06-04 09:10
Couldn't reproduce in any resolution. Closing.

**Closed by GophTheGreat** 2019-06-04 09:10 UTC
Labels: Medium Priority, QA
