### ISSUE TITLE
every 10 minute CPU load

### ISSUE THREAD

**Issue by ky0uraku** [StrangeLoopGames/EcoIssues#11706] opened 2019-03-18 12:13 UTC
every 10 minute 100% CPU load (1600% on 16-cores Xeon) in-game stuck and sometimes packet loss, leading to disconnect.

version - 8.0.7
no third-party software on server, no antivirus.

![chart2 php](https://user-images.githubusercontent.com/48658286/54497737-44da3900-490f-11e9-8f5d-88d63ad6a626.png)

_Originally posted by @ky0uraku in https://github.com/StrangeLoopGames/EcoIssues/issues/11468#issuecomment-473713362_

**Comment by faiith** [comment] 2019-03-20 12:15
- ECO-Server-Version 8.0.7
- No Mods
- Dedicated Server Hardware: Intel Core i7-6700 3.4GHz, 64GB Ram, SSD Storage
- Players: 5 to 12, depends on daytime ;)
- WorldSize: 100x100

Regardless of how many players are online on the server, there are massive lags / desyncs every few minutes, ranging from 30 seconds to several minutes. The clients of the players do not react at all during this time, they only show the red warning at the bottom right. The CPU load on the server increases to 90-100%.

The problem is particularly likely to occur when a player approaches a full warehouse, or a larger piece of the world is running. Guaranteed always the problem occurs as soon as another player tries to log on to the server

**Comment by mirasrael** [comment] 2019-03-22 16:37
Let's wait for 8.1. There some performance improvements in this area is coming.

**Comment by mirasrael** [comment] 2019-03-26 15:49
Should be fixed in 8.1. Re-open issue if it will persist.

**Closed by mirasrael** 2019-03-26 15:49 UTC
Labels: High Priority, Optimization
