### ISSUE TITLE
USER ISSUE: Server Crash db corrupt ?

### ISSUE THREAD

**Issue by laradji** [StrangeLoopGames/EcoIssues#4533] opened 2018-02-14 18:55 UTC
Version : 7.1.1

Result : server crash in loop, forced to restore backup ?
```
`
: [44:22] Server Initialization finished in 12,272.0ms
Unhandled Exception: System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state.
at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
at Eco.Gameplay.Items.Inventory.Modify(Action1 callback, User user)
at Eco.Gameplay.Components.StockpileComponent.TryUpdateInventoryFromWorld()
at System.Collections.Generic.List1.ForEach(Action1 action)
at Eco.Gameplay.Objects.WorldObject.Tick()
at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action`1 action)
at Eco.Gameplay.Objects.WorldObjectManager.Run()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart(Object obj)
`
```

**Comment by MarjieAVolk** [comment] 2018-02-14 20:52
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4473

This error shouldn't be affected by the db file, I would say there is something wrong in the .eco file.  Something wrong with a stockpile.  Glad you were able to get it working with a backup.  We will look in to this.

**Closed by MarjieAVolk** 2018-02-14 20:52 UTC
