### ISSUE TITLE
USER ISSUE: Log Pickup

### ISSUE THREAD

**Issue by motzarellagaming** [StrangeLoopGames/EcoIssues#4036] opened 2018-02-07 12:14 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
1. Log was sitting on ground and I walked over and hit e to pickup.  I believe when the auth servers crashed 2/6 into 2/7 this was already picked up and is why this error occured.

**Expected behavior:**
It should have let me pick it up or despawned since it was already picked up.

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-07 22:39
We got a similar stack trace reported over here: https://github.com/StrangeLoopGames/EcoIssues/issues/3668

Did you also see floating logs by any chance?

Going to close this as a duplicate of that one, since the stack trace is the same as the one in the comments

**Closed by MarjieAVolk** 2018-02-07 22:39 UTC

**Comment by motzarellagaming** [comment] 2018-02-07 22:44
Yes there was a flying log as well.
Feel free to close if there is a ticket already.

Awesome game! Keep up the great work!

**Comment by MarjieAVolk** [comment] 2018-02-07 23:37
You can track the bug progress on #3668 if you like :)

**Comment by motzarellagaming** [comment] 2018-02-08 00:08
Definitely Will!

Thanks
