### ISSUE TITLE
Difference between Mechanical and Electrical Power is very unclear

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2767] opened 2017-11-08 22:35 UTC
The mechanical "power grid" shouldn't be called "power grid" and it certainly shouldn't share the same name as Electrical.

**Comment by MarjieAVolk** [comment] 2017-11-08 22:49
There's a difference? >>

**Comment by metachronism** [comment] 2017-11-09 21:56
mechanical energy is meant to be piped into the world objects, but none of the art has been updated as such yet

**Comment by metachronism** [comment] 2017-11-09 22:44
closing as dupe of #1328

**Closed by metachronism** 2017-11-09 22:44 UTC
