### ISSUE TITLE
chat rewinding

### ISSUE THREAD

**Issue by madxmat** [StrangeLoopGames/EcoIssues#8337] opened 2018-07-04 23:33 UTC
After 7.5 update chat started to scroll back on its own. It just rewinds 2-30 lines back. It does that after reinstalling game and deleting files in Low Local folder on Windows. In 7.5.2 it does the same.

**Comment by ClayC90** [comment] 2018-07-05 09:17
A little more info from what I noticed.

- Usually happens when there are temporary messages that fill up a bit of the chat, like picking up many single items from the ground.
- Chat scrolls to 50%.
- Chat scrollbar loses sense of the height of the chat and fills up from top to bottom.

**Comment by madxmat** [comment] 2018-07-05 11:52
And also for split second there is a flash of a column of a small green numbers? Percentages?

**Comment by MarjieAVolk** [comment] 2018-07-05 23:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8248

Thanks for the additional observations.

**Closed by MarjieAVolk** 2018-07-05 23:16 UTC
Labels: Medium Priority
