### ISSUE TITLE
USER ISSUE: [SERVER] Cut a little tree 7.2.3

### ISSUE THREAD

**Issue by rorti** [StrangeLoopGames/EcoIssues#5731] opened 2018-03-09 00:15 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
When i try to remove a little tree I was kick from the server...

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à Eco.Simulation.Agents.Plant.Destroy()
   à Eco.Simulation.Agents.Tree.Destroy()
   à TreeEntity.Destroy()
   à TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   à Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   à Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   à Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   à Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   à Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   à Eco.Shared.Networking.NetPort.ProcessBuffer()
   à Eco.Shared.Networking.NetPort.Update()
   à Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-09 00:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5619

**Closed by MarjieAVolk** 2018-03-09 00:16 UTC
