### ISSUE TITLE
USER ISSUE: Ctrl + Click

### ISSUE THREAD

**Issue by ekuc** [StrangeLoopGames/EcoIssues#25110] opened 2024-08-26 22:17 UTC
\
**User Id: (5a5e0be3-7134-4128-56e4-08dc8d11157e)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
1. Ctrl+Click a production machine (i.e. moving a mill from one plot to another)
2. Move object to another plot

**Expected behavior:**
The power should automatically attach to the new plots power and storages

**Actual behavior:**
The power stays at 0 until picked up and placed back down, and some storage ranges get messed up (storages 3 blocks away cannot be found like iceboxes)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Unknown, on Socialist vs Capitalist Event Server for more info

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2024-08-27 11:36
Hi @ekuc 

Thank you for submitting this bug report.
However, I was not able to reproduce this issue.
Could you provide more information, please?

Please provide a recorded video of this issue.

**Comment by D3nnis3n** [comment] 2024-09-02 04:30
Given no further information was provided and the issue not being reproducible, I'm going to close this task.
Please feel free to open a new task when additional information can be provided.

**Closed by D3nnis3n** 2024-09-02 04:30 UTC
Labels: Status: Needs Information
