### ISSUE TITLE
USER ISSUE: Local Server Crash

### ISSUE THREAD

**Issue by SCETheFuzz1** [StrangeLoopGames/EcoIssues#23856] opened 2023-06-11 23:49 UTC
\
**User Id: (slg227049)**
**Version:** 0.10.0.0 beta staging-2624

**Steps to Reproduce:**
Self hosted Local server

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'key')
Source:System.Private.CoreLib

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Interactions.Interactors.InteractionDefinitionManager.GetInjectedInteractionMethod(InteractionTarget target, InteractionTriggerInfo triggerInfo, Type associatedType)
   at Eco.Gameplay.Interactions.Interactors.HandsInteractor.Eco.Gameplay.Interactions.Interactors.IInteractor.DoInteraction(Player player, InteractionTriggerInfo trigger, InteractionTarget target)
   at InvokeStub_IInteractor.DoInteraction(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-06-12 10:46
What did you do when the crash happened?

**Comment by D3nnis3n** [comment] 2023-06-12 17:05
Looks like duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23800.

**Closed by D3nnis3n** 2023-06-12 17:05 UTC
