### ISSUE TITLE
USER ISSUE: Mining-Level 6- Sweeping hands

### ISSUE THREAD

**Issue by rodneymillerpca** [StrangeLoopGames/EcoIssues#19074] opened 2020-11-03 21:21 UTC
\
**Version:** 0.9.1.0 beta release-105

**Steps to Reproduce:**
Have level 6 mining with sweepings hands option.
Upgrade to 9.1

**Expected behavior:**
Pick up limit of mined rockat one time.

**Actual behavior:**
Picking up rock one by one. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment] 2020-11-04 00:30
Duplicate of #19068 but thank you for reporting this.

**Closed by IcedForge** 2020-11-04 00:30 UTC
