### ISSUE TITLE
USER ISSUE: Inventory Switching

### ISSUE THREAD

**Issue by MotionlessGrins** [StrangeLoopGames/EcoIssues#5114] opened 2018-02-26 05:54 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
There will ocasionally be an inventory desync and I can't grab items that have been desynced. This happens with fishing too.

**Expected behavior:**
It should move inventories and update them.	

**Actual behavior:**
Instead it just sits in the middle of the screen or along the way to the next one.

**Comment by MarjieAVolk** [comment] 2018-02-26 22:38
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588 and https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-02-26 22:38 UTC
