### ISSUE TITLE
USER ISSUE: Srolling in item pick dialog will scroll  through quickslotbar at the same time

### ISSUE THREAD

**Issue by schmidju** [StrangeLoopGames/EcoIssues#5796] opened 2018-03-09 21:06 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
if i create a new contract for delivering items to a desired box i have to open the item pick dialiog.

**Expected behavior:**
Scrolling through the item pick dialog should not scroll threw my quickslot bar

**Actual behavior:**
it scrolls through the quickslotbar and the item pick dialog at the same time

**Comment by MarjieAVolk** [comment] 2018-03-09 21:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3789

**Closed by MarjieAVolk** 2018-03-09 21:13 UTC
