### ISSUE TITLE
USER ISSUE: Players are sometimes not visable on map

### ISSUE THREAD

**Issue by MightyPiggie** [StrangeLoopGames/EcoIssues#3973] opened 2018-02-06 12:33 UTC
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
Don't know, it just happend random. 

**Expected behavior:**
All the players should be visable on the map for everyone on everyone moment.

**Actual behavior:**
Sometimes it doesnt show anyone on the map, or it shows only a few. It seems that only a few people got this problem becuase, my group never had this problem.

**Comment by MarjieAVolk** [comment] 2018-02-06 22:24
I have seen it too O.o Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3770

**Closed by MarjieAVolk** 2018-02-06 22:24 UTC
