### ISSUE TITLE
Linked inventory duplicate bug?

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1593] opened 2017-06-05 19:59 UTC
I started milling 16 flour on someone else's property without any target inventory checked
manually collected 5 flour w/ button
started 6 flatbread (12 flour) without any inventories checked 
checked a public inventory and 3 flour got added that weren't in the public inventory
went to mill and it had 3 flour ready but the public inventory still wasn't checked, manually collected 3 flour then checked the public inventory

So 3 flour got duplicated (in the end I had 6 flat bread + 7 flour = 19 flour)

**Comment by MarjieAVolk** [comment] 2017-06-05 22:04
This is really weird; I can't repro it, and I don't see how this could possibly have happened, since items "in" the collect button aren't items at all and there's no way the other crafting table would have known about them.  So not sure what to do

**Comment by SeanAtr0n** [comment] 2017-06-05 22:15
Guess the other possibility is that the other player had 3 flour in some private inventory I couldn't see and somehow linking a public inventory also linked their private inventory at the same time and stole their items.

**Comment by MarjieAVolk** [comment] 2017-06-05 22:29
Yeah, that seems more plausible... checking the public inventory would cause the crafting component to re-evaluate everything it's connected to.  Still can't find any problems in the code though.

**Comment by MarjieAVolk** [comment] 2017-06-08 00:00
For now, I'm going to call this a duplicate of StrangeLoopGames/EcoIssues#1614 - feel free to reopen if you still see this after my outstanding PR goes in

**Closed by MarjieAVolk** 2017-06-08 00:00 UTC
