### ISSUE TITLE
USER ISSUE: All Servers Offline

### ISSUE THREAD

**Issue by SushySan** [StrangeLoopGames/EcoIssues#6738] opened 2018-03-30 14:26 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Install / Start / Join

**Expected behavior:**
Seeing my Servers or new ones, starting one, play the game

**Actual behavior:**
All Server Favs are OFFLINE, no new / other Servers are loading

**Comment by MarjieAVolk** [comment] 2018-04-03 00:21
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5211

We are working on a rewrite of the join server page, so we will likely not address this until that is released.  Should be soon, fingers crossed.

**Closed by MarjieAVolk** 2018-04-03 00:21 UTC
