### ISSUE TITLE
USER ISSUE: Fell off the planet

### ISSUE THREAD

**Issue by misnor** [StrangeLoopGames/EcoIssues#6055] opened 2018-03-14 20:22 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1. Walked around looking for mushrooms
2. Saw a line and a grey void
3. Walked over the line, fell off the planet	

**Expected behavior:**
Probably shouldnt have had a grey line there, and walking over it should not have thrown me into the void

**Actual behavior:**
threw me into the void

**Comment by MarjieAVolk** [comment] 2018-03-16 01:15
Was it a big hole in the world?  Or just a narrow line of grey?

Does it happen consistently in the same place?  If so, your save file might be useful.

**Comment by misnor** [comment] 2018-03-16 01:27
Oh geez, it was a giant hole and I should have known better to jump into it. 

When i reloaded the game, the chunk loaded properly. (this save file has also been deleted sorry!!)

**Comment by MarjieAVolk** [comment] 2018-03-16 01:28
Okay, thanks!

**Comment by misnor** [comment] 2018-03-18 00:50
I think so, that is a pretty good description of what happened to me.

**Comment by MarjieAVolk** [comment] 2018-03-19 20:33
Okay, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5917 in that case, thanks :)

**Closed by MarjieAVolk** 2018-03-19 20:33 UTC
Labels: High Priority
