### ISSUE TITLE
[Enhancement] Having MORE keys ingame doing stuff and/or Redefine keys menu

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2736] opened 2017-11-04 02:20 UTC
things we know:
ESC = Menu Screen (sometimes has to be pressed twice if Pointer is not showing on screen)
W A S D = movement
Cursor Keys - movement
E = Use Table/Stockpile/Gather/pickup Object (stone/ore/logs/coal)/Rotate objects Clockwise
Q = Rotate objects Anti-Clockwise
1 to 0 to select items on Toolbar
B = Backpack (open/close)
M = Mini Map (on/off)
C = Chat Window (open/close)
O = Objectives Window (open/close)
Y = Economy Viewer Window (open/close)
L = Government Window (open/close)
Left CTRL = Dive (in Water)
SPACE = Jump (Rise Up in Water)
/ = Start typing in chat window starting with a /
Alt+Z = Hides UI for better screenshots (this was only told to us in Discord if i remember correctly)

Would it be possible to have a little menu either ingame or on the launcher (where we can already choose Screen resolution and if we want it Windowed or not) to have possibly a place to redefine the keys that are used in game, and also possibly having the option to program F1 to F12 to do things for example:

/unstuck  

or if like my Server we have things like:

/online   =list of players that are online
/admins   =list of admins
/admins-online =list of admins online
/lastonline [PlayerName] =last time that player was online
/stats [PlayerName]   = that players unspent skillpoints and hours spent online
/population   =list of alive animals
/leader   =display the current leader
/rules    =display a set of server rules, if any are available
/election  =displays election status

/daily =gain 1 Token
/reward =claim votes in return for Tokens
/exchange [number] =trades tokens that you have on your character for Skill Points

/sethome [name]
/home-set [name]
/home-add [name] =saves your current location as a home

/home-list = displays a list of available saved homes

/removehome [name]
/home-remove [name]
/home-delete [name] = will remove the specified home

/home [name] =will teleport to the chosen home

/slap [name]
/punch [name]
/wave [name]
/hug [name]

so if for example i added /wave to F1 it typed it ingame then all i would have to do is add a persons name to the end and hit return

also maybe have an option to Display a mini Help image like a keyboard Overlay for ingame keys

hope this is not too much to ask or too hard to get implemented

**Comment by Conchipedia** [comment] 2017-11-04 02:28
if possible in this Github can you please tell me what keys are used ingame (that i might not know about) thanks

**Comment by MarjieAVolk** [comment] 2017-11-06 18:12
Well here's a couple more I can think of (which you probably already know, but for completeness):
- Enter to start typing in chat (or submit in chat)
- Tab to switch between cursor/FPS mode
- Left click to break & pick up things in the world
- Right click to place & use items in inventory

**Comment by MarjieAVolk** [comment] 2017-11-07 19:00
I'm actually going to close this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/317 - but thanks for the list

**Closed by MarjieAVolk** 2017-11-07 19:00 UTC
Labels: Enhancement
