### ISSUE TITLE
USER ISSUE: Hotbar Drag&Drop

### ISSUE THREAD

**Issue by nickhunter93** [StrangeLoopGames/EcoIssues#5147] opened 2018-02-26 22:31 UTC
#**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.Tutorial Axe : Drag to a different position on hotbar
Possible cause could be that my mouse button sometimes does multiple clicks at once...
So maybe the drop gets broken because it gets a new click before the process is finished

That is all xD

**Expected behavior:**
Switched to a different place on the Hotbar

**Actual behavior:**
Not switch and the Icon of the Axe bugged

**Comment by nickhunter93** [comment] 2018-02-26 22:32
Fix for User is tab to windows and then back into game

**Comment by nickhunter93** [comment] 2018-02-26 22:33
Possible cause could be that my mouse button sometimes does multiple clicks at once...

**Comment by MarjieAVolk** [comment] 2018-02-26 23:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-02-26 23:40 UTC
