### ISSUE TITLE
Staging Alpha 5.6 #Bb668640 - masonry  levels to unlock glass ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1646] opened 2017-06-12 11:07 UTC
so it says  i need masonry level 2 under masonry i cant find anything says that there i mean no skill says masonry

there is a stone working skill that is at level 4 ? so i am not sure what i need to in cress to unlock glass ?

![20170612060551_1](https://user-images.githubusercontent.com/15990789/27031283-4fe9ac0c-4f35-11e7-93f8-7399d9e895e8.jpg)

**Comment by Vigmundr** [comment] 2017-06-12 11:59
yeah you can't train anything for masonry or smithing sadly at the moment. they are broken

**Comment by metachronism** [comment] 2017-06-12 17:22
dupe of #1625

**Closed by metachronism** 2017-06-12 17:22 UTC
