### ISSUE TITLE
USER ISSUE: Cant join via steam

### ISSUE THREAD

**Issue by MOMOD0304** [StrangeLoopGames/EcoIssues#5306] opened 2018-03-02 18:06 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I would like to join via steam my friends game.

**Expected behavior:**
I can connect

**Actual behavior:**
Connection Failed and nothing happen

**Comment by MarjieAVolk** [comment] 2018-03-02 18:31
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4909

Just after seeing this error, could you also send your log file at 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'?  I just want to confirm this is the same error.

**Closed by MarjieAVolk** 2018-03-02 18:31 UTC
Labels: Medium Priority

**Comment by MOMOD0304** [comment] 2018-03-03 13:00
Initialize engine version: 2017.3.0f3 (a9f86dcd79df)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 1060 6GB (ID=0x1c03)
    Vendor:   NVIDIA
    VRAM:     6036 MB
    Driver:   23.21.13.9101
Begin MonoManager ReloadAssembly
- Completed reload, in  0.038 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 4 worker threads for Enlighten.
  Thread -> id: e24 -> priority: 1 
  Thread -> id: 1b44 -> priority: 1 
  Thread -> id: 2ab0 -> priority: 1 
  Thread -> id: 2ef8 -> priority: 1 
UnloadTime: 2.440546 ms
RPC lookup took: 3708.2991ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.1.2 beta

LocalServer -  Server Initialization... 

LocalServer -  Starting ModKitPlugin... 

LocalServer -  Loading mods... 

LocalServer -  Initializing items... 

LocalServer -  Initializing skills... 

LocalServer -  Starting NetworkManager... 

LocalServer -  Starting StorageManager... 

LocalServer -  Starting WorldGeneratorPlugin... 

LocalServer -  Starting GameplayStatsPlugin... 

LocalServer -  Starting StatDatabase... 

LocalServer -  Starting WorldPlugin... 

LocalServer -  Loading World... 

LocalServer -  Initializing world... 

LocalServer -  Starting TimePlugin... 

LocalServer -  Loading Time... 

LocalServer -  Starting ReputationPlugin... 

LocalServer -  Loading Reputation... 

LocalServer -  Starting PlayerHousingManager... 

LocalServer -  Starting UserManager... 

LocalServer -  Loading Users... 

LocalServer -  Initializing inventories... 

LocalServer -  Starting EcoObjectManager... 

LocalServer -  Starting PropertyManager... 

LocalServer -  Starting ControllerManager... 

LocalServer -  Starting ChatServer... 

LocalServer -  Starting EcoSim... 

LocalServer -  Loading Property... 

LocalServer -  Starting DifficultySettings... 

LocalServer -  Starting BackupPlugin... 

LocalServer -  Starting WirePlugin... 

LocalServer -  Starting MinimapManager... 

LocalServer -  Starting DisasterPlugin... 

LocalServer -  Loading Chat... 

LocalServer -  Loading Disasters... 

LocalServer -  Loading Plants... 

LocalServer -  Initializing plants... 

LocalServer -  Starting RouteProbingPlugin... 

LocalServer -  Loading RouteProbing... 

LocalServer -  Starting WorldLayerManager... 

LocalServer -  Loading Layers... 

LocalServer -  Initializing world layers... 

LocalServer -  Starting EconomyTracker... 

LocalServer -  Starting WorldObjectManager... 

LocalServer -  Starting EconomyPlugin... 

LocalServer -  Loading Economy... 

LocalServer -  Starting RoomPlugin... 

LocalServer -  Loading Rooms... 

LocalServer -  Starting ObjectivePlugin... 

LocalServer -  Loading Objectives... 

LocalServer -  Starting Legislation... 

LocalServer -  Loading Laws... 

LocalServer -  Starting WebServerPlugin... 

LocalServer -  Starting DiscordPlugin... 

LocalServer -  Initializing WorldGeneratorPlugin... 

LocalServer -  Initializing WorldObjectManager... 

LocalServer -  Initializing RoomPlugin... 

LocalServer -  Failed to parse IP address for listen server.  Using IPAddress.Any...

LocalServer -  Server Initialization finished in 8.020,8ms

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'TransmissionPoleObject') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'TransmissionPoleObject') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject, WashboardObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Exception: The layer "WaterSpread" does not exist.
  at WorldLayerManager.RequestLayerView (System.String layerName, System.Action`1 ReceiveView) [0x00000] in <filename unknown>:0 
  at WorldLayerManager.RequestLayer (System.String layerName, System.Action`1 ReceiveLayer) [0x00000] in <filename unknown>:0 
  at LayerAudio.Init () [0x00000] in <filename unknown>:0 
  at LayerAudio.GetLayerAudioData (Vector3 position) [0x00000] in <filename unknown>:0 
  at AmbientAudioPlayer.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Shutting down server
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Saving...

Releasing render texture that is set as Camera.targetTexture!
 
(Filename:  Line: 3926)

LocalServer - Done



Do you mean this?

**Comment by MOMOD0304** [comment] 2018-03-03 15:25
???

**Comment by MarjieAVolk** [comment] 2018-03-07 20:34
Yes, that is the right file.  But that looks like you are loading your own game.  Could you send me the file right after you try to connect to your friend's game via steam?
