### ISSUE TITLE
8.0.0 no tooltips on Question mark icons in skill menu

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10752] opened 2019-01-18 13:05 UTC
**Version:** 0.8.0.0 beta master-0d4ca997

![snap3847](https://user-images.githubusercontent.com/29383891/51388464-655d6100-1b21-11e9-96ef-fd05e4c06c19.png)
the ❔ on Skill Menu not giving a tooltip, also the sub window for them where you can choose between two types are not giving any information so it's a bit of a random chance that you are getting something good or bad

**Comment by elfl0rd** [comment] 2019-01-18 13:20
Duplicate of #10730

**Closed by elfl0rd** 2019-01-18 13:20 UTC
