### ISSUE TITLE
Alpha.6 [B8ce025e] Does it make sense ??? Wooden Hoe to cut trees ????

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2301] opened 2017-09-26 19:20 UTC
![grafik](https://user-images.githubusercontent.com/26040573/30879691-692964e0-a300-11e7-8d67-f2866170b58e.png)

**Comment by Fank** [comment] 2017-09-26 19:23
Duplicate of #2243

**Closed** 2017-09-26 20:27 UTC
