### ISSUE TITLE
[0.9.0 staging-1554] Image in news appears with some delay

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16387] opened 2020-05-19 07:14 UTC
https://drive.google.com/file/d/1ZxpWfPh49TzRHu6r8MIiPpbT4qz6yYQk/view?usp=sharing
Maybe it should wait until image will load and then display all. Something like you press ESC in Your Worlds menu: 
![2020 05 19 Image in news appear with some delay](https://user-images.githubusercontent.com/45708377/82296124-632b4100-99b9-11ea-8561-b40f69ad3bce.gif)

**Comment by elfl0rd** [comment] 2020-05-20 08:57
Also not bad if eco cache omages from news.
First time wait is appropriate, but every time - not.

**Comment by madpingui** [comment] 2021-04-01 21:04
the news got changed and now they hide and you cant see the information loading
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/2d257407-8960-48f4-9439-3cdab35f1281)
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/7cb628f9-8202-4b6c-8cc2-b850fa18074a)

**Comment by Daniel-Magulado** [comment] 2021-04-22 11:53
Build: 0.9.3.2 Release-212

I can reproduce this despite the changes in News in the lobby. This could be due to poor connectivity such as unstable internet connection, saturated Wi-Fi bandwidth, LAN neighboring Wi-Fi interference, etc.

Did some test and anything lower than 5Mbps download, there's a noticeable delay for the images to appear.

Maybe the best fix is to drastically reduce image size?

Video

https://user-images.githubusercontent.com/77248866/115709756-2d9a8f00-a3a4-11eb-98df-43dfd83995f2.mp4

On the video, I limited my internet speed down to 5Mbps.

**Comment by gzatravkin** [comment] 2021-05-03 22:17
One possible solution - to wait for all images be downloaded untill we show news button

**Comment by Daniel-Magulado** [comment] 2021-05-21 10:44
Tested on 0.9.4 Staging-1989.

Closing. The fixed implementation of having images with a loading visual sign is there.

**Closed by Daniel-Magulado** 2021-05-21 10:44 UTC
Labels: Category: UI, Priority: Low, Squad: Wild Turkey, Status: Reopen
