### ISSUE TITLE
No Object can be placed in water Staging alpha 6.0.0 #e34aa2e5

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#1989] opened 2017-08-26 06:43 UTC
I tried placing objects in the water, first of all i picked up some stone when i had meant to have picked up iron ore so i tried to place the stone back down, wouldnt let me.
I then tried other objects which i thought would go in like dirt ramp, for example rescuing a cart, still nothing, so i tried an object which most definitely should go into water "Aqueduct" and that wouldnt go into the water either!  I then went through All the items and blocks i could think of and didnt find a single item that could go into the water.
![snap034](https://user-images.githubusercontent.com/29383891/29739298-2dc5b7dc-8a32-11e7-8a30-bb3da63151c1.png)

**Comment by Conchipedia** [comment] 2017-08-26 14:23
sometimes the object can be placed in water if you try to do it loads of times, just had this happen when i picked up some sand

**Comment by Conchipedia** [comment] 2017-08-26 14:24
didnt mean to close this, sorry

**Comment by craig-jong** [comment] 2017-09-07 00:12
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2029

This is important to fix, but all discussion can go in the other issue.

**Closed by craig-jong** 2017-09-07 00:12 UTC
