### ISSUE TITLE
Client crashes randomly

### ISSUE THREAD

**Issue by Pingb4ck** [StrangeLoopGames/EcoIssues#18303] opened 2020-09-16 21:48 UTC
I'm running 0.9.0.1 beta and the client is randomly crashing after some time.
So far I haven't been able to connect the crashes to some specific event but it happens usually after 5-10 minutes in the game.

Upgraded to the latest graphic card drivers already.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5235122/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5235123/Player-prev.log)

**Comment by beastyn** [comment] 2020-09-17 04:15
@Pingb4ck thank you for the report.
Do you have application crash, not server-client crash?
Can you provide you PC specification?

**Comment by Praefator** [comment] 2020-09-17 16:04
Getting similar random crashes ever since an earlier 9.0 Staging build (don't recall which particularly unfortunately)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5240438/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5240439/Player.log)

Specs:
AMD Ryzen 7 1700x
16 GB DDR4-3200 RAM (with tightened subtimings)
2080ti
Running off of Samsung 500GB SSD

**Comment by Pingb4ck** [comment] 2020-09-17 19:36
Hi @beastyn 
these crashes happen when I'm connected to any server - official, private, self hosted.

For my system setup, I'm running on
Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz, 3401 MHz
AMD Radeon 7970 GHz Edition (AMD Radeon R9 200 / HD 7900 Series)
Driver version	27.20.12027.1001
Three screen setup

**Comment by PixlRainbow** [comment] 2020-09-18 19:40
Same issue -- It can occur at random, on any server, and sometimes even before the world loads in.
I'm on 9.0.2, running from Steam, and it does not appear to produce a log -- the client simply closes without warning and steam doesn't seem to think anything wrong has happened either.

Ubuntu 18.04.5 LTS 64-bit
Intel® Core™ i5-3470 CPU @ 3.20GHz × 4
NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
Driver version 440.100 (Nvidia first-party drivers)
One monitor, 1920x1080p
1TB HDD
120GB SSD

**Comment by redwyre** [comment] 2020-09-21 19:36
@Pingb4ck your issue appears to be graphics card related, you are getting the errors caused by:
> The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action. 
This can be caused by hardware or driver issues.

@Praefator your issue... is not clear at all. Please create a new issue if you get it again.

@PixlRainbow your issue appears to be with your drivers, but follow https://github.com/StrangeLoopGames/EcoIssues/issues/18081 for linux issues

**Comment by Pingb4ck** [comment] 2020-09-21 21:34
@redwyre the drivers are up to date - I just installed the latest and even the beta drivers from the AMD website. I don't experience these kinds of problems with any other unity based game and weirdly I have had a good run with version 9.0.0 lately with very little crashes.

I found a post on a unity forum regarding a similar issue:
https://forum.unity.com/threads/d3d11-failed-to-create-2d-texture.392286/
Not sure if that's applicable here but hey ;)

Regards,
Michael

**Comment by redwyre** [comment] 2020-09-22 14:36
@Pingb4ck I've created https://github.com/StrangeLoopGames/EcoIssues/issues/18403 as a possible cause on our side, but the driver still shouldn't crash ;)

**Comment by beastyn** [comment] 2020-09-29 09:31
I'm closing it as we have separate for graphical issues, if anything to add just write in here. Thanks!
@Praefator yours can be this one #18312

**Closed by beastyn** 2020-09-29 09:31 UTC
Labels: Category: Tech, Priority: High
