### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Luzga8** [StrangeLoopGames/EcoIssues#24524] opened 2024-01-03 19:38 UTC
\
**User Id: (slg236747)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Open something that you are not owner of. Try to transfer ownership to yourself. It forced me out of the game or the server did. 

**Expected behavior:**
It should warn me that I dont have permission to do that action I guess. 

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-03 19:53
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24521. Can you try to get your server admin to post the full stacktrace they can find in the dumps folder on the server, it's a server side error.

**Closed by D3nnis3n** 2024-01-03 19:53 UTC
