### ISSUE TITLE
USER ISSUE: Hole under map

### ISSUE THREAD

**Issue by dealtime101** [StrangeLoopGames/EcoIssues#5165] opened 2018-02-27 03:47 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
COOR : 180,47,350 

CHECKING TO WEST

DIG DIG 

**Expected behavior:**
Dirt or no dirt when digging	

**Actual behavior:**
a bug map that permit me to look under the map and get infinite dirt and cant flatten.

**Comment by MarjieAVolk** [comment] 2018-02-27 18:47
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3897 - Is that what you are seeing?  What do you mean by getting infinite dirt?

**Comment by dealtime101** [comment] 2018-02-27 18:57
Yeah same bug, but when I dig in the hole I get dirt everytime. (Infinite Dirt)

**Comment by MarjieAVolk** [comment] 2018-02-27 18:58
Okay, closing as duplicate of #3897, I will add your observations over there.

**Closed by MarjieAVolk** 2018-02-27 18:58 UTC
