### ISSUE TITLE
USER ISSUE: Map error

### ISSUE THREAD

**Issue by Nimeryon** [StrangeLoopGames/EcoIssues#5700] opened 2018-03-08 19:37 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1.Walk untill you find a not charged portion of the map
2.Fall inside
3.Wait

**Expected behavior:**
The sound of falling goes faster and faster, item in hand begin to move in every direction faster and faster.

**Actual behavior:**
The sound of falling goes faster and faster, item in hand begin to move in every direction faster and faster.

**Comment by MarjieAVolk** [comment] 2018-03-09 00:38
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5730

**Closed by MarjieAVolk** 2018-03-09 00:38 UTC
