### ISSUE TITLE
USER ISSUE: Cart disappears, 2 days later there  are carts spawned in all over the place.

### ISSUE THREAD

**Issue by turnburgler** [StrangeLoopGames/EcoIssues#7495] opened 2018-04-30 18:27 UTC
**Version:** 0.7.4.0 beta staging-68e3874b

**Steps to Reproduce:**
I put my cart on a bugged block, and it disappeared. 2 days later the server console prints this message "Failed to sync stockpile inventory with world contents." twice, and when I log in loads of carts have spawned in all over the place.

**Expected behavior:**
Not disappeared and spawned multiple carts.

**Actual behavior:**
Did.
![go karting](https://user-images.githubusercontent.com/38779441/39443426-e038bd02-4cb4-11e8-993c-cfa0f1886892.png)

**Comment by SeanAtr0n** [comment] 2018-04-30 22:40
sounds like something weird happened w/ the stockpile?

**Comment by turnburgler** [comment] 2018-04-30 23:47
Yeah it seemed as if the cart that had disappeared reappeared when I put a stockpile touching it later on. I am not positive of this though, as there were carts all over the place and I don't remember exactly where it disappeared.

**Comment by SeanAtr0n** [comment] 2018-04-30 23:55
was someone placing / picking up carts there a lot before the server reset?

**Comment by metachronism** [comment] 2018-05-09 22:17
this is a dupe of the other dupe bug

**Comment by metachronism** [comment] 2018-05-09 22:17
#5090

**Closed by metachronism** 2018-05-09 22:17 UTC
Labels: High Priority
