### ISSUE TITLE
[0.9.0 staging-1569] New map: don't see layer with district drawing

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16509] opened 2020-05-28 07:27 UTC
You don't see what you are painting in zoning office
![bandicam 2020-05-28 12-26-06-954.jpg](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/62794829-5736-46ae-914c-23a15ddf5eba)

**Comment by mirasrael** [comment] 2020-05-29 07:28
Can't reproduce in latest version. Probably fixed.

**Comment by SlayksWood** [comment] 2020-06-01 06:56
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/83383571-164e5e00-a3ee-11ea-9eba-e446adffc095.png)
/togglenewminimap:
![image](https://user-images.githubusercontent.com/45708377/83383604-28c89780-a3ee-11ea-83d4-f86c93182cf6.png)

**Comment by SlayksWood** [comment] 2020-06-01 11:31
fixed in 0.9.0 staging-1574.

**Closed by SlayksWood** 2020-06-01 11:31 UTC
Labels: Priority: Medium, Status: Reopen, Week Task
