### ISSUE TITLE
No food consuption im wearing special shoos and backpack

### ISSUE THREAD

**Issue by faiith** [StrangeLoopGames/EcoIssues#11754] opened 2019-03-25 18:27 UTC
Version: 0.8.7
Mods: None

If i wear 'worker shoes' + 'worker backpack', i'm not burning calories at all, even if i use broken tools. I can literally work endless using broken tools and not getting hungry.

**Comment by D3nnis3n** [comment] 2019-03-26 03:41
Duplicate of #11293

**Closed by D3nnis3n** 2019-03-26 03:41 UTC
