### ISSUE TITLE
USER ISSUE: "Plant already exists"

### ISSUE THREAD

**Issue by proggler23** [StrangeLoopGames/EcoIssues#5718] opened 2018-03-08 21:43 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Build a farm with hoe and plant some stuff.
take away the plants again.
wait some time (some update maybe)
try planting new seeds on same spot (no plants there)
it says "plant already exists"

**Expected behavior:**
if there is no plant, "plant already exists" should not be displayed.

**Actual behavior:**
it is displayed

**Comment by MarjieAVolk** [comment] 2018-03-09 00:17
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5607

**Closed by MarjieAVolk** 2018-03-09 00:17 UTC
