### ISSUE TITLE
USER ISSUE: Joining friends server

### ISSUE THREAD

**Issue by gomer0605** [StrangeLoopGames/EcoIssues#5398] opened 2018-03-05 01:52 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Clicked on Join through Steam chat
Received error message below

**Expected behavior:**
I should have joined the server

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by kerediansaar** [comment] 2018-03-05 02:25
Same here, tell me if you have a fix! :)

**Comment by GibsonSWE** [comment] 2018-03-05 22:39
Same here

**Comment by MarjieAVolk** [comment] 2018-03-05 22:46
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4909

For everybody that is having this issue, right after this happens, if you could send us your log file ('C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'), we can see if your error looks the same.

**Closed by MarjieAVolk** 2018-03-05 22:46 UTC

**Comment by GibsonSWE** [comment] 2018-03-05 22:51
Where do I send it?

**Comment by GibsonSWE** [comment] 2018-03-05 22:51
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1782895/output_log.txt)

**Comment by GibsonSWE** [comment] 2018-03-05 22:55
Further information:
If you've somehow managed to join the game earlier, you can join the game via the "continue" button on the main screen. But joining via steam "join game" doesn't work.

**Comment by MarjieAVolk** [comment] 2018-03-05 22:56
If steam join isn't working, you can also try connecting via ip address.  Have your friend look up what their ip address is, and in game go to Join > Add Server and enter the ip address there.  This often seems to work when the steam join feature doesn't

**Comment by MarjieAVolk** [comment] 2018-03-05 22:58
Also @GibsonSWE You do have the same stack trace as the linked bug in your log file.  So it is probably the same issue.  You can follow the bug there for updates.

**Comment by MarjieAVolk** [comment] 2018-03-05 23:00
Oh, @GibsonSWE I notice you have a whole bunch of timeouts in your log too.  Had you gone to the 'Join' window in game at all during that play session?  I'm wondering if those timeouts are from connecting to your friend or from loading the server list.

**Comment by gomer0605** [comment] 2018-03-07 16:11
So when I try to use the add feature and I type in the IP address all of
the serves disappear and his server does not come up

**Comment by MarjieAVolk** [comment] 2018-03-07 23:27
Did you type the ip address into the search box, instead of the add server popup, by chance?

**Comment by gomer0605** [comment] 2018-03-11 19:52
No I used the add server button, it also says you need the port number too
but we couldn't find the port number.

**Comment by MarjieAVolk** [comment] 2018-03-13 00:08
The default port number is 3001, you could also try 3000.  If you haven't messed with it, then you shouldn't need the port number though.
