### ISSUE TITLE
Sign 8.0.7

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoIssues#11691] opened 2019-03-15 20:45 UTC
The picture in the sign goes beyond.

![20190313030054_1](https://user-images.githubusercontent.com/36518011/54461024-29dfbb80-478d-11e9-9c17-db959054cf51.jpg)

**Comment by D3nnis3n** [comment] 2019-03-16 10:24
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11661

**Closed by D3nnis3n** 2019-03-16 10:24 UTC
