### ISSUE TITLE
Can't remove Bloomery w/ Hammer

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#2013] opened 2017-08-29 09:24 UTC
Related to #2001
and           #2012 

Staging Alpha 6.0.0 #E34aa2e5

**Comment by MarjieAVolk** [comment] 2017-08-30 00:23
Picking up the bloomery works fine for me.  Is your server freezing?

**Comment by EmuLegs** [comment] 2017-08-30 00:50
looking into it for more information

**Comment by EmuLegs** [comment] 2017-08-30 01:03
no, just fails to pick up, same effect as the camp fire

**Comment by EmuLegs** [comment] 2017-08-30 01:06
i'm about to update to the latest patch to see if there was a fix included

**Comment by MarjieAVolk** [comment] 2017-08-30 01:09
Another thing to check - is your inventory full?  Might be a messaging problem

**Comment by EmuLegs** [comment] 2017-08-30 02:00
no not at all, 

http://i.imgur.com/U1HIXKe.gifv

**Comment by MarjieAVolk** [comment] 2017-08-30 02:03
Ah, that gif is very helpful, thanks!

**Comment by EmuLegs** [comment] 2017-08-30 02:06
welcome, my first one ever o.O
also when i updated the server and client to the newest patch, the server just dumped on me
should i post a new issue with the file?

[Crash 08300328.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1262248/Crash.08300328.txt)

**Comment by MarjieAVolk** [comment] 2017-08-30 02:12
Yeah, that looks like a separate issue.  I will create the issue

**Comment by MarjieAVolk** [comment] 2017-09-07 01:00
Well I can't figure this one out still :(  If this consistently happens for your bloomery, could you give me your Game.eco save file?  If not, maybe a screenshot of the bloomery's ui?

**Comment by EmuLegs** [comment] 2017-09-07 04:21
Sure thing check out #2025

**Comment by MarjieAVolk** [comment] 2017-09-07 17:42
Aha right, thanks!

**Comment by MarjieAVolk** [comment] 2017-09-07 20:30
Okay, I figured it out.  This will be fixed in the next staging release - but for now, this is caused by the type of fuel you have in the fuel supplies for these objects.  If you remove the fuel, you should be able to pick them up and/or get error messages as normal.

**Closed** 2017-09-11 19:49 UTC
