### ISSUE TITLE
USER ISSUE: While Mining Stone

### ISSUE THREAD

**Issue by lifezoned4** [StrangeLoopGames/EcoIssues#23816] opened 2023-05-08 02:29 UTC
\
**User Id: (slg202514)**
**Version:** 0.10.0.0 beta staging-2611

**Steps to Reproduce:**
1. Stone with Stone Pick Axe mining
2. Some stone appear unpickable
3. Continue Mining
4. Crash

**Expected behavior:**
Stone should be pickable and no crash happens

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'key')
Source:System.Private.CoreLib

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at Eco.Gameplay.Interactions.Interactors.InteractionDefinitionManager.GetInjectedInteractionMethod(InteractionTarget target, InteractionTriggerInfo triggerInfo, Type associatedType)
   at Eco.Gameplay.Interactions.Interactors.HandsInteractor.Eco.Gameplay.Interactions.Interactors.IInteractor.DoInteraction(Player player, InteractionTriggerInfo trigger, InteractionTarget target)
   at InvokeStub_IInteractor.DoInteraction(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, appears with no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-05-22 14:06
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23800

**Closed by D3nnis3n** 2023-05-22 14:06 UTC
