### ISSUE TITLE
[0.9.3.5 release-231] - civic objects get removed instead of orphaned when picking up table

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoIssues#22443] opened 2021-07-05 14:41 UTC
1. pick up table (our table was a district table containing "Altaica Roads" and "Virgata State Zoning")
2. objects are just removed and not orphaned, immediately after picking it up (not after countdown has ended)
![grafik](https://user-images.githubusercontent.com/34270661/124488132-ca6ba680-ddaf-11eb-9405-8e16f7e22354.png)
this was seconds after pickup of the district table
![grafik](https://user-images.githubusercontent.com/34270661/124488213-deafa380-ddaf-11eb-87eb-b1e7cbed72d4.png)

**Comment by Azzurite** [comment] 2021-08-31 00:58
Just had the same issue /complain ;) just kidding. Hope this gets fixed soon.

**Comment by Daniel-Magulado** [comment] 2022-10-06 04:09
Hello

This should be fix now. I am unable to reproduce. I'll be closing this but please feel free to open a new one if this is still the case for you.

**Closed by Daniel-Magulado** 2022-10-06 04:09 UTC
Labels: Priority: High, Category: Laws, Type: Bug
