### ISSUE TITLE
USER ISSUE: Mini Game freeze

### ISSUE THREAD

**Issue by MurdocZA** [StrangeLoopGames/EcoIssues#22942] opened 2022-01-16 19:55 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.5 beta release-278

**Steps to Reproduce:**
Ummm I dont know, I was busy in our landfill area with all the large stock piles, and was moving stuff from one to the other, then it started getting worse.  and freezes after a couple	

**Expected behavior:**
no game freeze	

**Actual behavior:**
has like a little freeze like 2 seconds every now and then, if you are on the move

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have NO mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment] 2022-01-17 16:03
Hey @MurdocZA ,

Thank you very much for your report.

* Have you been able to reproduce this issue again?
* Please, could you share your PC specs?
* Could you tell if other players from the server have been suffering the same issue?

**Comment by D3nnis3n** [comment] 2022-07-18 09:58
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)

**Closed by D3nnis3n** 2022-07-18 09:58 UTC
Labels: Status: Needs Information
