### ISSUE TITLE
[0.9.0 Staging-1494] Turning off Photo mode (Alt+Z) pulls up skill list (Z)

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15590] opened 2020-04-07 09:18 UTC
I played around with the photo mode a bit. Turns out when you exit the photo mode with Alt + Z, the game automatically brings up the skill list (Z).

Also, the Photo Mode is not listed under keybindings. It should be listed there. A few games I played (Oxygen Not Included, Stellaris) default to F9 being the photo mode, so it would be nice to be able to check the keybinding from the options.

**Comment by elfl0rd** [comment] 2020-04-07 09:41
Duplicate of #4485

**Closed** 2020-04-07 09:44 UTC
