### ISSUE TITLE
USER ISSUE: Disappearing Objects

### ISSUE THREAD

**Issue by mkeire** [StrangeLoopGames/EcoIssues#11237] opened 2019-02-10 11:58 UTC
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**

**Expected behavior:**
Objects such as wood carts and steam trucks should not disappear.

**Actual behavior:**
Objects disappear and do not materialize. "click to show in minimap" function, however, provides a location to the lost object.

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by elfl0rd** [comment] 2019-02-10 15:06
Duplicate of #11108

**Closed by elfl0rd** 2019-02-10 15:06 UTC
