### ISSUE TITLE
USER ISSUE: World overlay

### ISSUE THREAD

**Issue by kythwilde** [StrangeLoopGames/EcoIssues#20258] opened 2021-01-30 00:28 UTC
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
1.) Click the option to open world map
2.) Click on World Layers
3.) Click on Plant
4.) Click on any of the plant species
5.) Toggle either population or yield potential.

**Expected behavior:**
Up until today (01/29/2021) the World Layer option would give you an overlay of what yields you get for certain plants in certain areas via either the minimap or the world map. 

**Actual behavior:**
For the last 4 hours (since 2pm CST), the options to review the world layer map options are not toggling at all, despite multiple log outs and logins. I do not have any of the other overlays toggled. I can see properties, and biomes, but the other toggles do not work. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes/yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment] 2021-02-01 10:46
@kythwilde Thank you for the report. Can you provide log files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Can you also provide more details because I can't reproduce it:
![image](https://user-images.githubusercontent.com/45708377/106448477-e206d200-6493-11eb-9f45-3d28ed6583bd.png)

**Comment by IcedForge** [comment] 2021-03-09 07:24
Closing this due to lack of reply, please reopen with requested information if you still encounter this problem.

**Closed by IcedForge** 2021-03-09 07:24 UTC
Labels: Status: Needs Information
