### ISSUE TITLE
Tree planting issue

### ISSUE THREAD

**Issue by zawe6t** [StrangeLoopGames/EcoIssues#4571] opened 2018-02-15 07:48 UTC
I use a soil sampler to identify if the soil is usable for the trees. I've planted trees in places that are 100% optimal but die within 10 minutes. It's making it very hard to repopulate the trees.
![plant1](https://user-images.githubusercontent.com/32182051/36245754-38924264-11f2-11e8-91fd-180109e6ab06.png)
![plant2](https://user-images.githubusercontent.com/32182051/36245760-3db7d218-11f2-11e8-997f-953aa1c2ca7b.png)

**Comment by Thyriel** [comment] 2018-02-15 13:00
I can confirm that. To me it seems something is buggy about that. We have plenty of trees through all growing stages (even fully grown) that are shown as dead with the soil sampler. Even a lot of the trees in forest that are still there from worldspawn are shown as dead. These trees seem to never drop saplings/seeds but still give wood too.

**Comment by Thesam1798** [comment] 2018-02-17 16:22
Hello, can you confirm that this is a bug or something?

**Comment by knexer** [comment] 2018-02-23 23:00
There are some issues with dead plants right now - they aren't ever removed from the world unless they are replaced by another plant (or chopped by players).  They also keep growing even though they're dead, and trees still give logs when dead.  The first two issues will be fixed in the next release, the last issue is I believe intended.

As for why the trees are dying, and if it's happening more than it should be or not, I have to leave that up to @craig-jong .

**Comment by Thyriel** [comment] 2018-02-24 12:05
> As for why the trees are dying, and if it's happening more than it should be or not

As i played a lot with ecosim.eco configs to make farming a less frustrating experience to me it seems that there is some kind of bug involved here that only seems to affect trees and tomatoes.
While i was trying to figure out what the various configs do i was able to run a test with potentially immortal plants by changing ShrubSpace to 1 (CanopySpace for trees), MaxDeathRate to 0.000001.
In all my test fields (with one kind of each plant) not a single died then, only tomatoes still had the very same death rate as with ShrubSpace 1 and MaxDeathRate 0.005. I even tried increasing their optimal / extreme temp/moisture values without any noticeable influence on their death rate.
With trees it seems to be very same. No matter what i set their MaxDeathRate or their optimal/extreme temp/moist about 9 of 10 die within an hour.

**Comment by craig-jong** [comment] 2018-03-30 19:21
Farming was modified to prevent this - if it still occurs post 7.3, please reopen the bug.

**Closed by craig-jong** 2018-03-30 19:21 UTC
Labels: High Priority
