### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by NytoO** [StrangeLoopGames/EcoIssues#4827] opened 2018-02-19 16:10 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**
![first bug graphique](https://user-images.githubusercontent.com/36629711/36386905-ae68d806-1597-11e8-8510-3910bfe71c56.jpg)

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-20 20:01
Can you give some more details about when and how this happened?  What is supposed to be in that space?

**Comment by NytoO** [comment] 2018-02-25 13:26
I don t know, maybe a flying water... it was my first bug.

**Comment by NytoO** [comment] 2018-02-25 13:37
i found it after few minutes when i create a new world.

**Comment by metachronism** [comment] 2018-03-16 18:39
looks like an awesome chunk builder exception - closing as a dupe of those :P

**Closed by metachronism** 2018-03-16 18:39 UTC
Labels: Medium Priority
