### ISSUE TITLE
USER ISSUE: Invisible Washboard

### ISSUE THREAD

**Issue by Lagicrus** [StrangeLoopGames/EcoIssues#5239] opened 2018-02-28 19:56 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Pickup washboard

**Expected behavior:**
It should have looked normal

**Actual behavior:**
Instead it was transparent

https://imgur.com/a/XlDMN

**Comment by MarjieAVolk** [comment] 2018-02-28 19:59
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4318

**Closed by MarjieAVolk** 2018-02-28 20:00 UTC
