### ISSUE TITLE
USER ISSUE: Can't connect to a server anymore

### ISSUE THREAD

**Issue by Sephidane** [StrangeLoopGames/EcoIssues#4258] opened 2018-02-10 17:07 UTC
Hi guys, I got this bug to submit. First of all it asked me to chose a profile to connect to the server because I had the second character problem but was ok. I was connected then it disconnected me for inactivity (I was not inactive) and now I can't connect anymore and I got this message : 
For more precision I was crafting arrows (in case it's due to that). My steam account and Eco account is Sephidane

**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManage

**Comment by MarjieAVolk** [comment] 2018-02-13 04:14
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4413

We have a fix for this, which should go out in our next hotfix.  Unfortunately you may not be able to connect to this server until the fix goes out.  You should be able to play on other servers though.

**Closed by MarjieAVolk** 2018-02-13 04:14 UTC
