### ISSUE TITLE
[0.9 Staging-1515] Creating two water connections one tile apart causes the pipes to appear to be leaking

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15874] opened 2020-04-19 01:05 UTC
Ran into this weird bug twice. When you set up water consumers / generators, feed it water and then add another water connection one tile off, it makes the pipe appear to be leaking:

![image](https://user-images.githubusercontent.com/964559/79676796-79699580-819e-11ea-9a25-2f6bb6d7b072.png)

![image](https://user-images.githubusercontent.com/964559/79676827-d5ccb500-819e-11ea-9396-668e0ac5fd77.png)

![image](https://user-images.githubusercontent.com/964559/79676831-f98ffb00-819e-11ea-8d56-21c8a32142bb.png)

It's not the case if the connection is straight on:

![image](https://user-images.githubusercontent.com/964559/79676805-969e6400-819e-11ea-86c9-5e8473c6e2d7.png)

Nor when it's just pipes:

![image](https://user-images.githubusercontent.com/964559/79676813-b9c91380-819e-11ea-9c2a-f64dc9cb6f81.png)

1) Version
0.9 Staging-1515

2) Steps to reproduce
- Connect water producers / consumers as shown
- Pipes appear to be leaking

3) Expected behaviour
- Pipes shouldn't be leaking in this configuration

4) Actual behaviour
- Pipes appear to be leaking

**Comment by D3nnis3n** [comment] 2020-04-19 01:07
This looks like https://github.com/StrangeLoopGames/EcoIssues/issues/11846, can you confirm?

**Comment by ThePiachu** [comment] 2020-04-19 01:28
Looks like it might be the same bug...

**Comment by D3nnis3n** [comment] 2020-04-19 01:29
Then i'm closing this as Duplicate of #11846

**Closed by D3nnis3n** 2020-04-19 01:29 UTC
