### ISSUE TITLE
7.7 - Failure to convert the world

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9196] opened 2018-09-05 23:48 UTC
Seems, the world is a bit too big, eh?
<img width="1920" alt="error" src="https://user-images.githubusercontent.com/25908592/45127087-fdf8d300-b176-11e8-8b74-118601bb40f4.png">

**Comment by D3nnis3n** [comment] 2018-09-06 00:06
The world is a 16 km² world. If you need it, i can give you a link once again :)

**Comment by johnkslg** [comment] 2018-09-07 00:17
@LucasDomberg can you attach your smaller world to this?

**Comment by LucasDomberg** [comment] 2018-09-07 15:01
I hope you mean this
![ecofailurebigworld](https://user-images.githubusercontent.com/32537640/45226637-aca82b00-b2bf-11e8-9d66-840db22b4d3b.PNG)

**Comment by D3nnis3n** [comment] 2018-09-07 16:28
He means the Content of your storage Folder.

**Comment by johnkslg** [comment] 2018-09-07 16:58
@LucasDomberg yes need the game.eco file, though that is helpful too.

**Comment by johnkslg** [comment] 2018-09-07 16:58
@D3nnis3n yours as well plz!

**Comment by johnkslg** [comment] 2018-09-07 16:59
Tagging for hotfix

**Comment by SeanAtr0n** [comment] 2018-09-07 19:51
looks like vehicles were spawning occupancy blocks that they shouldn't have & you had a cart flying several km above the surface, will be fixed in a hotfix soon

**Comment by LucasDomberg** [comment] 2018-09-07 20:03
Thank you very much :D

**Closed** 2018-09-08 00:15 UTC
Labels: Critical Priority, Fixed

**Comment by D3nnis3n** [comment] 2018-09-10 18:37
@SeanAtron
This is not fixed for my save. Probably has to do with and is unfixable therefore, e.g. my world is fucked up?
I can start it on 0.7.6.3 just fine, though - as of your answer in the other issue it should crash then, like it did.

**Comment by D3nnis3n** [comment] 2018-09-10 18:40
Should i open a new issue, will you reopen this or is it just unfixable and stays closed therefore?

**Comment by SeanAtr0n** [comment] 2018-09-10 18:43
i couldn't download your world to verify, should be fixed in 7.7.2

**Comment by D3nnis3n** [comment] 2018-09-10 18:44
Oh, well probably you tried when the backup ran. It should be downloadable now.

**Comment by CobaltEcho** [comment] 2018-10-12 01:10
Has this been fixed in a release?  It looks like the excavator is the cause of these invisable blocks on our server.

**Comment by D3nnis3n** [comment] 2018-10-12 01:33
We didn't have an excavator at that time.
