### ISSUE TITLE
USER ISSUE: Unable to connect to server

### ISSUE THREAD

**Issue by plex68** [StrangeLoopGames/EcoIssues#24768] opened 2024-02-14 21:08 UTC
\
**User Id: (slg103069)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
connection to my game server

**Expected behavior:**
Be able to be in game on my server

**Actual behavior:**
World loading blocked at 100%. I was stuck loading for more than 3 hours to get this error message.

I have already reinstalled my game server, as well as the game. Cleared the game cache and updated my drivers. Friends of mine have access to the server, but me and two other players have the same problem as me.

My friends who are lucky enough to be able to play them see me online and my characters are physically present on the map when I am stuck loading the world.I also tested in local server, and launched without any mod and I am also stuck on loading. I am currently completely blocked and I would like to have access to the map so as not to lose all my constructions.

If you wish I could provide you with a complete backup of the server privately.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes I have mods installed on the server here is the list:

- DiscordLink
-ElixirMods Pack
- jcdcdev.Eco.Core
- jcdcdev.Eco.Sign
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14288582/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14288583/Player-prev.log)

-MightyMoose
- NestToolBox
-PlaceableStone
- RoadExtension
-WorldEdit

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-02-15 05:48
Duplicate of #24671

**Closed by D3nnis3n** 2024-02-15 05:48 UTC
