### ISSUE TITLE
[10.1.1] Dissolved/Unfounded Settlements Treasuries left orphaned and visible to all Mayors on the server.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24664] opened 2024-01-20 20:21 UTC
Dissolved/Unfounded Settlements Treasuries left orphaned and visible to all Mayors on the server.
Persistent after server restart.
Removing all mods from the server doesnt fix it either.

world save: https://drive.google.com/file/d/1loumOD3v_Q6-U1KweKPavGbid4JQe3ri/view?usp=sharing

![image3](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/4ee76277-a801-40d1-90af-34ef4357082f)
![image2](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/d868cd6e-d724-4ec5-811a-581e3d811005)

**Comment by padmanek** [comment] 2024-01-21 15:50
The list of orphaned treasuries is growing as more towns dissolve or fail to found. Thankfully regular players don't see them and Town Mayors are all informed not to try to use those treasuries.

**Comment by D3nnis3n** [comment] 2024-02-05 04:01
Not reproducible, including on the save provided.

**Comment by IronyTroll** [comment] 2024-02-05 05:48
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/71368607/e7779d73-7355-4f9c-94e6-085ffd48b4c1)

Same issue. Build Eco Server 0.10.1.3 beta release-592

**Comment by padmanek** [comment] 2024-02-05 06:09
I mean we have like 15+ bugged treasuries like that just hanging there by now. I'll join the server with an alt account and try to make the treasuries visible for him and post reproduction steps later today.

**Comment by D3nnis3n** [comment] 2024-02-05 06:48
> ![image](https://private-user-images.githubusercontent.com/71368607/302187140-e7779d73-7355-4f9c-94e6-085ffd48b4c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTU5NTYsIm5iZiI6MTcwNzExNTY1NiwicGF0aCI6Ii83MTM2ODYwNy8zMDIxODcxNDAtZTc3NzlkNzMtNzM1NS00ZjljLTk0ZTYtMDg1ZmZkNDhiNGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA2NDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMDBlZmU0ZGVlYWQ1YWFjMmZiOWU0NDdjMjBjNzc1MWI1YTY0MjFlZDExNmMwNDZiMDZiMmRlYzI3NmU3ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6X2lf0mPJqgBqtOt2ZFLKE0PLMPg7Xq7XFI6QUwwyBk)
> 
> Same issue. Build Eco Server 0.10.1.3 beta release-592
Save game?

> I mean we have like 15+ bugged treasuries like that just hanging there by now. I'll join the server with an alt account and try to make the treasuries visible for him and post reproduction steps later today.
Your save does not contain any irregular treasuries when loaded locally. We also found no way how to create some, a settlement deleting due to invalidity timer will not create such treasuries locally.

**Comment by padmanek** [comment] 2024-02-05 07:19
@D3nnis3n You made me insecure so I downloaded my own savefile from the link above.

Reproduction steps:
1. log in and spawn anywhere
2. /titles assign President, yourname
3. check your accounts

Video recording proving this:



https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/46562c91-abb9-4305-ac61-514978bffd9c

**Comment by IronyTroll** [comment] 2024-02-05 07:36
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/71368607/c5e64d88-373f-4bc6-81c9-4cbab4117477)

In addition to this, which is likely very much related, deleted accounts are also showing up in player's lists of accounts.

**Comment by MonzUn** [comment] 2024-02-06 13:21
I can't attest to the STR, but I can say that I have also been seeing this on my server as a town mayor.
I see a lot of random accounts that I shouldn't have access to.

**Comment by D3nnis3n** [comment] 2024-02-26 21:21
Fixed in https://github.com/StrangeLoopGames/Eco/pull/13792

**Closed by D3nnis3n** 2024-02-26 21:21 UTC
Labels: Status: Not reproduced
