### ISSUE TITLE
Dead plant does not look dead

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9016] opened 2018-08-21 00:49 UTC
![image](https://user-images.githubusercontent.com/3536496/44374097-68d0bb80-a4a1-11e8-9717-2f6a20604c6b.png)

**Comment by BlazeGuy2** [comment] 2018-08-21 17:49
@johnkslg can you prioritize it?

**Comment by WeaselDog** [comment] 2020-05-21 03:16
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4887

**Closed by WeaselDog** 2020-05-21 03:16 UTC
Labels: Priority: Medium
