### ISSUE TITLE
USER ISSUE: Game crasht while Jumping on a Stockpile with Glass

### ISSUE THREAD

**Issue by MarviBiene** [StrangeLoopGames/EcoIssues#6423] opened 2018-03-23 23:27 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
I was walking and jumping on a stockpile filled with Glass.

**Expected behavior:**
Not crashing

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei Eco.Simulation.Agents.AI.AITarget.<UpdatePosition>b__32_0()
   bei Eco.Shared.Utils.LockUtils.TryLock(Object lockObject, Action ifLockAcquired, Int32 millisecondsTimeout)
   bei Eco.Simulation.Agents.AI.AITarget.UpdatePosition()
   bei Eco.Simulation.Agents.AI.AITarget.get_Position()
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-23 23:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6393

**Closed by MarjieAVolk** 2018-03-23 23:32 UTC
