### ISSUE TITLE
Spawn Point for Players Still Sometimes has Plants

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#18927] opened 2020-10-26 22:04 UTC
![AvatarCreation](https://user-images.githubusercontent.com/14983165/97233547-5d256180-179c-11eb-8bc6-b7dd160f536f.gif)

Happened on Develop branch on 10/26/2020.

Here's the world save.
[Spawn Point Foliage Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5441800/Spawn.Point.Foliage.Storage.zip)

**Comment by Moritur** [comment] 2021-04-06 10:22
Plant on the screenshot is Ocean Spray and it should be destroyed if player spawns on it, unless UseExactSpawnLocation in server configuration is set to true.
Entering world attached to this issue without changing server configuration spawns player few blocks away from this plant. Changing spawn position to plant's position (256, 70, 39) destroys plant when player spawns.

The only way to spawn player on this plant I found is to set UseExactSpawnLocation to true and set spawn location to plant's location, but in that case this is expected behavior and plant is not rendered until player saves character and starts playing.
This means I can't reproduce situation from provided screenshot.

**Comment by Jason-Skillman** [comment] 2021-05-24 15:38
Another issue I encountered was the player spawning inside of a tree's branch. Another idea might be to have a `Hide Foliage` button in the avatar creation menu.
<img width="644" alt="Screenshot 2021-05-24 111201" src="https://user-images.githubusercontent.com/35405997/119368590-30c5bb00-bc81-11eb-9bb8-d14883e5c2f4.png">

**Comment by Daniel-Magulado** [comment] 2021-05-29 18:06
Tested on 0.9.4 Staging-1995.

The issue is fixed.
I've tested it 30 times by creating 30 new game worlds.
Not even once I spawned on the top of any plants, covered by branches, and not even bushes.
Closing.

**Comment by Daniel-Magulado** [comment] 2021-06-05 12:01
Tested on 0.9.4 Staging-2008

I actually spawned in a place where a branch was next to me which made it difficult to see my backpack.
I did another run of tests and encountered the following that I believe is enough grounds to reopen this.

### Grass Blocking Shoes Visually

![image](https://user-images.githubusercontent.com/77248866/120890200-aa6f8880-c633-11eb-8af3-73372ab6d927.png)
![image](https://user-images.githubusercontent.com/77248866/120890309-6c269900-c634-11eb-904f-7b16421a4bab.png)


Here's the world save where I spawned at the top of grass blocking my shoes visually.
[Shoe Block World.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6602472/Shoe.Block.World.zip)

### Spawning Next to a Branch
There was an instance where I spawned with a Branch at my avatar's back. Not entirely blocking my avatar but it prevented me to view the back of my Avatar.  I can still see my avatar's bag when viewed at the sides. An example is an image below but the chances of it happening is very low. Only encountered it once out of my 45 tries.

![image](https://user-images.githubusercontent.com/77248866/120890905-3edbea00-c638-11eb-8a78-b677b7b7d2a8.png)

@Jason-Skillman, might want to look into this again?

**Comment by Jason-Skillman** [comment] 2021-06-05 22:30
Ah yes, I can see how that impairs the player from viewing the shoes and backpack, I'll take another look at it and see what I can do.

**Comment by TwixterZ** [comment] 2021-06-09 05:17
Fix tested and confirmed as of 9.4 Staging 2012

**Closed by TwixterZ** 2021-06-09 05:17 UTC
Labels: Category: Gameplay, Priority: Medium, Squad: Otter, Status: Fixed, Type: Bug
