### ISSUE TITLE
07.3.3 - Stockpile bug - infinite resources

### ISSUE THREAD

**Issue by edalcin** [StrangeLoopGames/EcoIssues#7175] opened 2018-04-13 12:56 UTC
https://youtu.be/OD8eldmdOUg

**Comment by ecoemmeck** [comment] 2018-04-13 15:02
this is perhaps a duplicate of 
Storage UI Stockpile Duplication bug #7117

**Comment by metachronism** [comment] 2018-07-12 04:31
dupe of stockpile resource bug #5895

**Closed by metachronism** 2018-07-12 04:31 UTC
Labels: Medium Priority
