### ISSUE TITLE
Display key control

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2776] opened 2017-11-09 18:30 UTC
Players have frustration with the keys.  Add a display in the escape menu of the keys, and floating popups to display the way to  open dialogs.

**Comment by metachronism** [comment] 2017-11-09 19:08
this is a partial dupe of #317

**Comment by MarjieAVolk** [comment] 2017-12-06 01:57
I guess I will also comment here, that in addition to 'floating popups to display the way to open dialogs', we should have in those popups icons for what tool to use (eg. to pick up a block, hit a tree)

**Comment by Nanders** [comment] 2017-12-06 01:57
Assigning John re: [...] floating popups to display the way to open dialogs.

**Comment by Nanders** [comment] 2018-01-26 21:40
this has been added

**Closed by Nanders** 2018-01-26 21:40 UTC
Labels: Feature
