### ISSUE TITLE
"That inventory can only store carried items"

### ISSUE THREAD

**Issue by FilldasBill** [StrangeLoopGames/EcoIssues#1729] opened 2017-06-26 09:39 UTC
We have started a new world. First day we began to build a new home without problems. At the second day, if i want pick "log" out of my stockpile into my inventory, it says: "That inventory can only store carried items".

**Comment by FilldasBill** [comment] 2017-06-26 10:05
![grafik](https://user-images.githubusercontent.com/29703909/27534578-c2813b3a-5a67-11e7-9403-872ad6f9e528.png)

**Comment by chrisbraidsw** [comment] 2017-06-26 10:58
It has to go into your Carrying slot on your actionbar, not your inventory. Not a bug, it's the way the items are designed to be stored. Logs, Ore, Coal, Stone, Mortar, Bricks etc all live in the carrying slot and cannot be placed into the Inventory of a Player or Chest.

**Comment by FilldasBill** [comment] 2017-06-26 13:25
Yeah i did it into my carring slot. same problem! if i want to move the box into my "Fillmobil", same problem. everything what i do with that stockpile. nothing works!

**Comment by Lardyking** [comment] 2017-06-26 19:34
We got a user on our server with exactly the same issue. Theres also somehow food in his Stockpile and noone can take anything out of it. The food inside is infinite also. Workbench also has a issue - cant take items out of it. Only one of 8 users have it. Gets same error with cannot carry - we know how carry and such works.

**Comment by SeanAtr0n** [comment] 2017-06-26 20:33
Could you attach your server's Game.eco file to this bug?

**Comment by MarjieAVolk** [comment] 2017-06-26 22:50
Ah you've got non-carried things in your stockpile - same as StrangeLoopGames/EcoIssues#1708

**Comment by true2form** [comment] 2017-06-27 07:42
iv had the same issue it seems if your storage chests in your linked inventories are full whilst crafting it tries to put an item into the stockpile causing all the linked inventories and crafting stations to lock up requiring adding more storage chests to the inventories and a server restart for it to unlock otherwise you cant take anything out

**Comment by Lardyking** [comment] 2017-06-27 09:25
Here is my game.eco file. Its the user Capail that have the issues with his stockpile.
[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1104792/Game.zip)

**Comment by FilldasBill** [comment] 2017-06-30 08:39
will it be fixed soon?

**Comment by craig-jong** [comment] 2017-07-10 19:06
So it's pretty simple.
We will use a quarry for our example since it's the most common issue.
Have 1 slot in a chest linked to said quarry.
Have space available in linked stockpile.
Begin crafting pitch from sand from linked stockpile.
Craft more than 99 pitch as to overload linked chest i.e. request 200 pitch.
Before pitch is completed order, start a new project of mortared stone even though there's not enough pitch. But only request say... 25 mortared stone so there's 100+ pitch still.
Once pitch exceeds 99, it will attempt to go to stockpiles since it's a free inventory slot. 
Once pitch is in stockpile it's now unable to be removed and quarry goes into a crafting loop.
Thus inventoried items now are in stockpile while quarry attempts to pull pitch from stockpile but cannot as it's codded for carried only items.
Thus server crash.

**Comment by Witchfire** [comment] 2017-07-23 07:43
Same issue. I used a friends white listed Blast furnace. It appears when doing so, i must toggle the storage linked for the projects independently of the owners linking. I had only stockpiles selected and was smelting Gold ore and Iron ore. The gold bars went into the stockpile and became non-removable with the same error of "That inventory can only store carried items".

Seems this bug is activated by a person using a machine they do not own and not selecting proper flow. When a chest was selected it ended up going to the chest, however this was after clicking a "collect button" which was only apparent to me and not the owner. The gold bars lay in the stockpile and the stockpile is bugged and cannot have inventory transferred either way, in or out.

**Comment by MarjieAVolk** [comment] 2017-07-24 17:18
Aha, you think it's related to not owning the storage/bloomery - that would make sense

**Comment by MarjieAVolk** [comment] 2017-08-03 21:59
I figured out what causes this - when you reload the server with projects sitting finished in tables with only invalid inventories to get put into, they'll get output there on server load, before the inventory restrictions are set up.  Not sure if that will be helpful for playing around the bug in the mean time.

I've got a fix for it, will definitely be fixed in the next release.

**Closed** 2017-08-07 18:05 UTC
Labels: High Priority
