### ISSUE TITLE
Server crash by homestead annexing

### ISSUE THREAD

**Issue by Demiden** [StrangeLoopGames/EcoIssues#24356] opened 2023-12-22 05:28 UTC
v10.0.3
Possible duplicate of
https://github.com/StrangeLoopGames/EcoIssues/issues/24351

If a town has such kind of law

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/19950239/7bc291f4-980e-4871-9123-b30ad22b6a82)

and the town tried to annex a homestead it cause a server crash:
```
[792] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>cDisplayClass42_0.<<Initialize>b7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>cDisplayClass42_0.<<Initialize>b7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[792] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>cDisplayClass42_0.<<Initialize>b7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>cDisplayClass42_0.<<Initialize>b7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

![eco server crash](https://github.com/StrangeLoopGames/EcoIssues/assets/19950239/4ad82aed-14fa-4e3e-b2fb-27e61ae3d149)

**Comment by D3nnis3n** [comment] 2023-12-22 16:02
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24351

**Closed by D3nnis3n** 2023-12-22 16:02 UTC
