### ISSUE TITLE
USER ISSUE: Visual issues!

### ISSUE THREAD

**Issue by Flortrax** [StrangeLoopGames/EcoIssues#7559] opened 2018-05-03 01:24 UTC
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Place stockpiles right next to the house, fill it up to the roof and you can see the roof merge with the stockpile 'what ever material it is.
![eco2](https://user-images.githubusercontent.com/16627095/39556557-b0e59e0e-4e70-11e8-9b79-a861d32261c7.png)
![eco1](https://user-images.githubusercontent.com/16627095/39556559-b1087744-4e70-11e8-9b50-fce2b3c69e91.png)

**Expected behavior:**
Not to merge with the house and destroy the look and feel of the building.

**Actual behavior:**
They merge, very annoying.

**Comment by keegan-o** [comment] 2018-05-10 22:30
Closing as duplicate of other bugs for bad roof behavior.

**Closed by keegan-o** 2018-05-10 22:30 UTC
Labels: Medium Priority
