### ISSUE TITLE
USER ISSUE: 7.0 Mechanics Conversion

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#3856] opened 2018-02-04 03:24 UTC
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
When the File tranfered from 6.4.2 to 7.0, The changes made to the skill tree made it so I cannot learn Mechanics anymore.  I had level 5 Mechanics, and all Mechanics Efficiencies.  Now I have level 5 for all the Efficienceies, but I have level 0 Mechanics, and Its says Not Learned Yet

**Expected behavior:**
I should already know or at least be able to repurchase Mechanics

**Actual behavior:**
I no longer have the skill, and cannot relearn it, even if I had the SP.

**Comment by MarjieAVolk** [comment] 2018-02-05 03:18
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3808

**Closed by MarjieAVolk** 2018-02-05 03:18 UTC
