### ISSUE TITLE
USER ISSUE: work bench

### ISSUE THREAD

**Issue by Badante75** [StrangeLoopGames/EcoIssues#6270] opened 2018-03-19 08:09 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Unable to collect crafted items off the masonary work bench

**Expected behavior:**
Allow me to collect crafted masonary pitch i created

**Actual behavior:**
just stays in 100% crafted and never allows me to collect

**Comment by MarjieAVolk** [comment] 2018-03-19 19:32
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3240.  This will be fixed in 7.3

**Closed by MarjieAVolk** 2018-03-19 19:32 UTC
