### ISSUE TITLE
9.0.3 Law election looks incorrect count wise

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18493] opened 2020-09-27 14:26 UTC
It is making it look like a lot more people have voted yes than no whereas it is actually 10 in total

To the casual user this would make it seem like 10 people have voted yes and 4 no.

![image](https://user-images.githubusercontent.com/61889138/94367281-9bfcc480-00d5-11eb-9426-46df37db730e.png)

![image](https://user-images.githubusercontent.com/61889138/94367291-a61ec300-00d5-11eb-997b-7e6f8d9dbcc2.png)
![image](https://user-images.githubusercontent.com/61889138/94367299-adde6780-00d5-11eb-87d0-b318f69bae0b.png)

**Comment by olegshegai** [comment] 2020-10-12 18:23
Seems to be fixed within new election system introduced by @johnkslg 
@tuha263 try to reproduce, inspect related prefabs and see where the values are taken from
Some tips:
- `/civics spawngov false` will allow current user start elections (instead of insta-perform actions);
- you can disable auth and login with different names to vote;
- you can adjust settings of basic elections using server UI (though default values should be okay for this particular test).

**Comment by johnkslg** [comment] 2020-10-12 22:35
Actually Tu if you want to make this better, you can have a portion of the bar stay black to represent uncast votes, and the rest is divided between yes and no.

**Comment by SlayksWood** [comment] 2020-11-05 09:24
Can't check because election bar is missing. Seems fixed by tooltip, but want toc check after fixing this one #19133

**Closed** 2020-11-20 10:39 UTC
Labels: Category: Laws, Priority: Medium, Status: Fixed
