### ISSUE TITLE
USER ISSUE: Periodical heavy FPS drops

### ISSUE THREAD

**Issue by semirotta** [StrangeLoopGames/EcoIssues#7683] opened 2018-05-10 12:06 UTC
We have noticed periodical fps drops that happen every 30-45 seconds or so. Fps is fine over 60 and then drops to 11-14 for while then goes back up to what it was. This is nothing too serious I suppose but it is god darn annoying. Especially when you're trying to hunt animals.

It has happened now on friends server with more than 2 players, my friends local hosted server which we play together while I stream and it happens there quite often (feels like more often than the other server that is paid server I believe) and it also happens on singleplayer but not that often.

All I have is this video proof of it; https://www.twitch.tv/videos/259764090 if you keep watching, you can see the random fps drops.

It can't be "normal" that the game runs over 60 fps normally and just drops to 11-14 fps for short while then goes back up to 60.

**Comment by metachronism** [comment] 2018-05-10 22:18
closing as dupe of #6775 
fps is something we are always looking to improve

**Closed by metachronism** 2018-05-10 22:18 UTC
Labels: High Priority
