### ISSUE TITLE
USER ISSUE: Registrar is not working

### ISSUE THREAD

**Issue by LucasDomberg** [StrangeLoopGames/EcoIssues#11365] opened 2019-02-16 20:44 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. Build a Registrar
2. Create a title
3. Try to add Title Holders

**Expected behavior:**
It should show the users of the server in the title holders list.

**Actual behavior:**
The title holders list is empty. Typing in the name of a user is also not working.

**Do you have mods installed? Does issue happen when no mods are installed?:**
There are no mods installed.

**Comment by LucasDomberg** [comment] 2019-02-16 20:46
![20190216212644_1](https://user-images.githubusercontent.com/32537640/52905028-49d69a80-3234-11e9-9770-278aea27b021.jpg)

Here a screenshot of the problem.

**Comment by elfl0rd** [comment] 2019-02-16 20:51
Duplicate of #11251

**Comment by elfl0rd** [comment] 2019-02-16 20:51
@LucasDomberg can you attach your world save in #11251 ?

**Comment by elfl0rd** [comment] 2019-02-16 22:01
Thx for save! i close this as duplicate. (don't worry, all work will continue on the main)

**Closed by elfl0rd** 2019-02-16 22:01 UTC
