### ISSUE TITLE
USER ISSUE: Game Crash on Chopping Log

### ISSUE THREAD

**Issue by cwells1298** [StrangeLoopGames/EcoIssues#6886] opened 2018-04-02 13:39 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Went to chop up a fallen log after a crash

**Expected behavior:**
Sliced the log into smaller pieces

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment] 2018-04-02 21:56
Does this same log stay bugged when you restart your server?  If so, a save file would be awesome.

Also, since your server was restarted because of a crash - what caused that first crash?  Was it related to this tree?

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-04-02 21:56 UTC

**Comment by cwells1298** [comment] 2018-04-02 23:09
It does stay bugged on server restart. Find the save file attached.

Initially I restarted the game due to a world chunk (containing my house) being unloaded, upon reloading, when I went to chop the tree it began crashing with the previous error code.
[ChopBugSave.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1869663/ChopBugSave.zip)

**Comment by cwells1298** [comment] 2018-04-02 23:26
425, 580

**Comment by MarjieAVolk** [comment] 2018-04-02 23:29
Thank you!
