### ISSUE TITLE
USER ISSUE: Cart disapears

### ISSUE THREAD

**Issue by JoeBlack67** [StrangeLoopGames/EcoIssues#4708] opened 2018-02-17 14:45 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Carts keeps disapearing

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-23 21:48
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4802 and/or https://github.com/StrangeLoopGames/EcoIssues/issues/4991

**Closed by MarjieAVolk** 2018-02-23 21:48 UTC
