### ISSUE TITLE
Alpha 6.0.0 - Always stuck at the beginning of a stair block

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#2392] opened 2017-09-29 03:53 UTC
**Version:** Alpha 6.0.0
**Description:**
Always stuck at the beginning of a stair block.
You have to jump to be able to walk in the stair.

![image](https://user-images.githubusercontent.com/7052045/31000172-bea89e74-a4a7-11e7-8673-eb05eafb8584.png)

**Comment by Fank** [comment] 2017-09-29 08:43
Duplicate of #1915

**Comment by MarjieAVolk** [comment] 2017-09-29 17:32
If you turn on the "Clambering" option, stairs will work.  Closing as duplicate

**Closed by MarjieAVolk** 2017-09-29 17:32 UTC
