### ISSUE TITLE
Investigate: some players reports "freezing" or "micro lag"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10136] opened 2018-11-27 09:13 UTC
As i see, @D3nnis3n have similar problem.
In addition, two player on my community reported this.
Both have high-end PC, 
1) Win 10, ASUS GeForce RTX 2070, i7, 32gb RAM, 512GB SSD - freezes for ~1s every ~1-2 min
2) Win 10, Gigabyte GeForce GTX 1070 Ti, i7-6900k, 16gb ram, 1tb HDD - freezes every 3-5 min for 2-3s

changing the settings doesn't help, it happens even at ultra-low resolution.
Reports of "lag" more, but these caught my attention, not an ordinary configuration.

**Comment by D3nnis3n** [comment] 2018-11-27 09:15
I pretty much get short 1/4 s freezes every ~ 30 seconds, no matter the graphic settings or resolution.

Win 10, Gigabyte GeForce RTX 2080, AMD Ryzen 2700X, 32 GB RAM, 1 TB SSD

**Comment by seccombew** [comment] 2019-01-16 20:45
Closing as dupe of #10566

**Closed by seccombew** 2019-01-16 20:45 UTC
Labels: Investigate
