### ISSUE TITLE
USER ISSUE: Bug

### ISSUE THREAD

**Issue by Konripapa** [StrangeLoopGames/EcoIssues#6030] opened 2018-03-14 06:53 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
I don't know what happened, becouse I left my computer running all night while I was sleeping (I play solo).

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Az objektumhivatkozás nincs beállítva semmilyen objektumpéldányra.


Stack:
   a következő helyen: Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   a következő helyen: Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   a következő helyen: Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>

<size=60,00%>Az objektumhivatkozás nincs beállítva semmilyen objektumpéldányra.


Stack:
   a következő helyen: Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   a következő helyen: Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   a következő helyen: Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-15 21:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-15 21:40 UTC
