### ISSUE TITLE
7.1.1 Server crash (3 in 5 mins)

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4491] opened 2018-02-14 03:21 UTC
three different crashes, first two are the image third is the two dump reports. server has been 7.1.1 for 5 mins...

![2018-02-13](https://user-images.githubusercontent.com/20627148/36186280-4e63f1ac-10fb-11e8-963f-5f1cf0b6718e.png)

`--BEGIN DUMP--
Dump Time
02/13/2018 20:18:20

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Objects.RubbleObject.get_Active()
   at Eco.Shared.Networking.NetObjectManager.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--
`
`--BEGIN DUMP--
Dump Time
02/13/2018 20:18:28

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
`

**Comment by MarjieAVolk** [comment] 2018-02-14 22:05
Bottom one is duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368

For the screenshot, are you saying that disconnecting the invalid user caused the server to crash?  Or are those two separate issues?

**Comment by stormoffires** [comment] 2018-02-14 22:53
I do not know, I since I can not tell for sure. I just wanted to provide as much information as I can to help :)

**Comment by MarjieAVolk** [comment] 2018-02-14 22:57
Okay thanks :)  I think the middle one does not have a bug of its own, so I am going to close this one and make a bug for just that middle one.  https://github.com/StrangeLoopGames/EcoIssues/issues/4542

**Closed by MarjieAVolk** 2018-02-14 22:57 UTC
