### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Dragonshold** [StrangeLoopGames/EcoIssues#4255] opened 2018-02-10 16:09 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
flying log, tried to pick it up with E it crashed the game

**Expected behavior:**

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-13 00:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668 . You can track the progress of the issue there.

It seems this happens occasionally, especially with logs that have been sitting around when the game is reloaded.  Hopefully we will fix it soon.

**Closed by MarjieAVolk** 2018-02-13 00:25 UTC
