### ISSUE TITLE
USER ISSUE: Hanging logs in the air

### ISSUE THREAD

**Issue by DeVviL** [StrangeLoopGames/EcoIssues#4987] opened 2018-02-23 08:55 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I have a forest and a house a short distance away
Went down a tree
He cut the whole trunk to pieces
Took a few pieces and carried home
I return back to the trunk and on the way I see that the logs fly to meet me. Flying a bit they were hanging in the air

**Expected behavior:**
had to lie still

**Actual behavior:**
flew away and hovered in the air

**Comment by DeVviL** [comment] 2018-02-23 08:57
Screenshot
![20180223115541_1](https://user-images.githubusercontent.com/30007632/36585891-b23aa6a2-1890-11e8-9a71-89df4341ebce.jpg)

**Comment by MarjieAVolk** [comment] 2018-02-23 22:48
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-23 22:48 UTC
