### ISSUE TITLE
Law for all plants and all animals

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#9076] opened 2018-08-25 09:34 UTC
Version: 0.7.6.3 beta

Steps to Reproduce:
Login to the game and hit L to open up the law window
Try and specify a law for all animals or all plants

Expected behavior:
To write a law that would cover all plants or all animals. 

Actual behavior:

Well the actual behavior right now is to do a law for each one of the species 
of animals separately it makes it for a novel of a law trust me I did it. 

An example of this is: 

When attempting to Harvest where (species is Bison)
If in district Hunting District #1
Then allow
Otherwise If in district Hunting District #2
Then allow
Otherwise If in district Hunting District #3
Then allow
Otherwise prevent

Ok so basically what this law does is if the species is a Bison and you are in one 
of the three hunting districts which are already setup on this server then 
allow the hunting to occur but if you are outside of these three hunting zones 
prevent the player from killing the bison. 

Now I had to specify each species separately  because there
was no way to say "all animals" in the law 

So you end up doing a law for Bison, Elk, Wolves, Turkey, Fox, Tortoise, Hare
all separately the same way as above all in one big long rule. 

It would really be easier if we could specify either "all animals" or "all plants" 
and would shorten the law a lot . 

Make it so that all animals or plants are included so that you can just
do this once instead of having to repeat it over and over again. 

An example of what the law may look like may be: 

For an animal: 

When attempting to Harvest where (species is Animal)
If in district Hunting District #1
Then allow
Otherwise If in district Hunting District #2
Then allow
Otherwise If in district Hunting District #3
Then allow
Otherwise prevent

And one for plants: 

When attempting to Harvest where (species is Plant)
If in district Gathering District #1
Then allow
Otherwise If in district Gathering District #2
Then allow
Otherwise If in district Gathering District #3
Then allow
Otherwise prevent

It would make things so much easier and simpler can you please
fix the laws this would be a great fix if you can do this because it will
shorten down the laws a lot when writing laws like this! 

My law for animals is massive right now so big I couldn't even get the whole thing 
in the screenshot.  you only see a couple of the laws for the animals. 

![hunting laws aug 25 2018](https://user-images.githubusercontent.com/38896397/44616950-5cd55880-a817-11e8-98fc-a7f5c8066372.jpg)

**Comment by MarjieAVolk** [comment] 2018-08-28 17:59
Thanks for the detailed description.  This issue is on my radar, but always useful to hear what players want most.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4088

**Closed by MarjieAVolk** 2018-08-28 17:59 UTC
Labels: Feature, Laws, Medium Priority, Needs Triage
