### ISSUE TITLE
USER ISSUE: Renaming Chest

### ISSUE THREAD

**Issue by Stixz** [StrangeLoopGames/EcoIssues#5310] opened 2018-03-02 21:17 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Stack 3 chest one on top of the other. Stand in front of them and rename one. Close the menu.	

**Expected behavior:**
Have the chest renamed and allow me to continue to play.	

**Actual behavior:**
Chest gets renamed, I become stuck in place and can no longer do anything except turn the camera.

**Comment by MarjieAVolk** [comment] 2018-03-03 00:44
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

This is fixed in the current staging build.

**Closed by MarjieAVolk** 2018-03-03 00:44 UTC
