### ISSUE TITLE
Learn Specialty where skill is

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#12955] opened 2019-08-23 09:32 UTC
Since v0.8.0.0 we have been unable to select specific specialties in the `where` clause of a `Learn Specialty` law trigger.
![image](https://user-images.githubusercontent.com/2676134/63582451-6532b180-c599-11e9-92a2-05c608b4509e.png)
This makes it impossible to make laws the limit learning of specialties/skills in any meaningful way.

I am unsure if #8183 is still an issue, but that could make this even worse.

Don't know why we hadn't made a bug report about it at all until now. I assume there isn't time to fix this before v0.9.0.0, but still good to have a bug report for it finally.

**Comment by Deantwo** [comment] 2019-08-23 09:34
It would be a nice feature to have a `skill category is` where clause. So we can make laws that target all skills in a profession category.

PS: Also some confusion between the use of the word "skill" and "specialty" in this.

**Comment by D3nnis3n** [comment] 2019-08-26 08:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11951?

**Closed** 2019-08-26 08:25 UTC
Labels: Laws, Medium Priority
