### ISSUE TITLE
USER ISSUE: Exception: Object ref not set to an instance ob an object

### ISSUE THREAD

**Issue by Krabjuk** [StrangeLoopGames/EcoIssues#5832] opened 2018-03-10 11:39 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Digging earth, running around. Random error. Not exactly reproducable.

**Expected behavior:**
I should have no exception.

**Actual behavior:**
Caught exception:

<size=60.00%>Object reference not set to an instance of an object

```
Stack:
  at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates (System.Collections.Generic.IEnumerable`1[T] newObjects, Eco.Shared.Networking.INetObjectViewer viewer, System.Collections.Generic.ICollection`1[T] monitored) [0x0001c] in <87b449fa3be548e4a9bca65d2ad34821>:0 
  at Eco.Plugins.Networking.Clients.Client.Update (System.Diagnostics.Stopwatch timer) [0x000b9] in <cb46936a53a64832a4f16709d80dbff3>:0 
  at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1 () [0x00012] in <cb46936a53a64832a4f16709d80dbff3>:0 
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-12 18:33
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-12 18:33 UTC
