### ISSUE TITLE
USER ISSUE: Buggy Law Menu

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#11745] opened 2019-03-24 14:30 UTC
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
1. Try to make a long law.

**Expected behavior:**
It should have worked like any other law.

**Actual behavior:**
Instead it takes forever for selected options to stick, often reverting to the previous selection where I would have to keep setting it to the desired option. Upon finally fighting and winning against the option resets and making it to law publishing, the "Propose Law" has an extremely long delay between clicking it and the actual action it is associated with.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead it takes forever for selected options to stick, often reverting to the previous selection where I would have to keep setting it to the desired option. Upon finally fighting and winning against the option resets and making it to law publishing, the "Propose Law" has an extremely long delay between clicking it and the actual action it is associated with.

**Comment by Blanclour** [comment] 2019-03-24 15:02
I would like to mention that it would frequently give me node errors after setting options upon their reversion to the previous setting.

**Comment by D3nnis3n** [comment] 2019-03-25 09:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10144

**Closed by D3nnis3n** 2019-03-25 09:22 UTC
