### ISSUE TITLE
Reconsider Spread of Ore

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12119] opened 2019-04-26 17:23 UTC
(v0.8.1.4)
I zapped down a big mountain with Devtool and this were the extract: 9 pieces copper ore, no veins, no clusters, but single separate pieces.
To research Mechanics Skill, 200 copper and iron ore are needed each (20 ingots iron and copper).
How can this be achieved with means of early game?
![copper ore](https://user-images.githubusercontent.com/38510829/56825165-b71c3280-6858-11e9-9a44-0bec55c5a09e.jpg)

**Comment by tehflambo** [comment] 2019-04-27 00:54
fwiw my own experience is that at the appropriate depth in Boreal Forest there's more Copper than i can figure out what to do with. Outside that narrow band, the copper is like this post: almost none.

**Comment by D3nnis3n** [comment] 2019-04-27 02:25
Which is intended behaviour, therefore i gave a suggestion label.

**Comment by D3nnis3n** [comment] 2019-04-30 09:43
I'm actually closing this out as this was a recent design decision that worked out well and you are actually able to adjust this for yourself in your server configuration for world gen. If you still want this being kept as suggestion, feel free to open a suggestion on the suggestion tracker.

**Closed by D3nnis3n** 2019-04-30 09:43 UTC
Labels: Suggestion
