### ISSUE TITLE
USER ISSUE: Water fillage

### ISSUE THREAD

**Issue by tboyer83** [StrangeLoopGames/EcoIssues#11566] opened 2019-03-04 13:25 UTC
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
1. Dig a hole next to a body of water.
2. knock out wall connecting body of water to the hole

**Expected behavior:**
The hole should fill up with water

**Actual behavior:**
Waterfalls to bottom of the hole and stops, hole never fills up

**Do you have mods installed? Does issue happen when no mods are installed?:**
Waterfalls to bottom of the hole and stops, hole never fills up

**Comment by D3nnis3n** [comment] 2019-03-04 19:37
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1424

**Closed by D3nnis3n** 2019-03-04 19:37 UTC
Labels: Low Priority
