### ISSUE TITLE
Deleted district showing up in law

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15333] opened 2020-03-26 02:30 UTC
In the playtest server (save located here: https://download.godsofwar.de/eco/anotherexception.zip) there is a law which references a deleted district.  
![image](https://user-images.githubusercontent.com/3536496/77601169-367e1000-6ec7-11ea-9ea2-3f15842e620a.png)

This shouldn't be possible, it may be 'removed' but never deleted.

Please see if you can find a repro case for this. I think it's some combination of adding and revising laws, and restarting the server, possibly with incomplete saves.  Can also chat to the people on the playtest server to get more info how to trigger it.

**Comment by Daelmaron** [comment] 2020-03-26 11:53
OOH I got IT!

I have been the one setting districts. That "Deleted" district came about because we revised the district map, which created a whole new map altogether (dumb really) but then the server crashed while the new map was being voted on and when everything came back up the revised map had been erased from the zoning table but that "deleted" district was showing instead which as far as I could tell was the old district (which had been renamed in the revised map) but everything concerning that district was broken hard.

**Comment by SlayksWood** [comment] 2020-03-26 12:50
@Daelmaron 
But for me it's still removed , not deleted(

**Comment by Daelmaron** [comment] 2020-03-26 14:17
@SlayksWood yeah, the deleted didn't happen until the crash. not sure beyond that what caused it. I have changed other districts and it doesn't make them do that.

I can play with it on the zoning table on Royal Otter in a little bit and see if I can force it to replicate on a new map. Will let you know my results.

**Comment by mirasrael** [comment] 2020-06-15 13:29
Two cases:
1. District can't be removed if it used somewhere. So add a validation which prevents District remove if it referenced in active law.
2. If District was removed (in old version) or because of some migration then it should be invalid and reset to Draft on server load.

**Comment by gzatravkin** [comment] 2020-06-21 20:00
I need world saves and all logs from Server/Logs folder.

Save from issues is not avaliable 
![image](https://user-images.githubusercontent.com/53317567/85233642-3f0ab780-b3de-11ea-85b5-db7c7e7c3bf8.png)

@mirasrael There are already system that should prevent it. 

It works in this way:
You can remove active district map and after that all related laws will became invalid (with references to district map as Invalid). But this will let it as Removed, not Deleted.

Possible way to get Deleted is by removing a draft with no references. Or by using admin commands.

Maybe in logs there are some exception that will clear it.

**Comment by gzatravkin** [comment] 2020-07-27 13:12
Can't reproduce it, no data to dig it depper. 
Will close it for now, please reopen if occur again

**Closed by gzatravkin** 2020-07-27 13:12 UTC
Labels: Priority: Low, Status: Investigate, Status: Needs Information
