### ISSUE TITLE
USER ISSUE: No Plants or Animals and full grown trees only give ONE log

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3621] opened 2018-01-25 13:45 UTC
**Version:** 0.7.0.0 beta staging-b1111b5c

![snap1293](https://user-images.githubusercontent.com/29383891/35391455-a6f46ac4-01d6-11e8-8b9b-1c597f4b6922.png)

it is only Day 1 and there is Nothing Alive on it

![snap1288](https://user-images.githubusercontent.com/29383891/35390693-2f9ba89a-01d4-11e8-9f66-cedd9783ba15.png)
![snap1289](https://user-images.githubusercontent.com/29383891/35390717-490fbc6c-01d4-11e8-921f-ef39f80c462f.png)

Everything seems Dead
![snap1290](https://user-images.githubusercontent.com/29383891/35391045-60410e9e-01d5-11e8-970d-9d6099da6d6d.png)
Trees look full Grown and it takes the normal amount of time to chop them down
![snap1291](https://user-images.githubusercontent.com/29383891/35391085-8706b3ee-01d5-11e8-9e88-bb3896f2fded.png)
but it will allow you to pick up the whole tree
![snap1292](https://user-images.githubusercontent.com/29383891/35391173-cbab804c-01d5-11e8-9b6a-d99feeebd2a4.png)
and you **ONLY** get one log

As there is no food you cannot gather and continue working

**Comment by FRodz80** [comment] 2018-01-25 17:20
Confirmed also get the tree issue. But it doesn't always happen. Sometimes I can chop the tree up like normal and other times it just gives one log like above (playing on friend's server).

**Comment by midn8t** [comment] 2018-01-25 18:09
I just seen this before I posted it for our server.
https://github.com/StrangeLoopGames/EcoIssues/issues/3628 

we have some what of same problem but little different.

we had no issues with planets spawning they spawned fine but animals did not spawn.
also as stated on our ticket world generation seem to take hour or longer before completed if we logged in to soon it seem to mess up generation.

**Comment by knexer** [comment] 2018-01-26 21:42
The animals side of this has been fixed.  I haven't been able to reproduce plants dying right after worldgen.  Plants having the wrong yield is known and tracked [here](https://github.com/StrangeLoopGames/EcoIssues/issues/3630) (along with other issues with the recent changes to plants and world layers)

**Comment by knexer** [comment] 2018-01-26 21:42
Going to close this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3630

**Closed by knexer** 2018-01-26 21:42 UTC
Labels: High Priority
