### ISSUE TITLE
USER ISSUE: Not receiving all plants

### ISSUE THREAD

**Issue by ContessaChaos** [StrangeLoopGames/EcoIssues#6581] opened 2018-03-28 19:32 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Starting a game.

**Expected behavior:**
Should at least receive the edible plants required for the researches.	

**Actual behavior:**
No crimini mushrooms, no rice, no prickly pears.

**Comment by MarjieAVolk** [comment] 2018-03-28 22:04
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5092

You can try typing '/regenlayer CriminiMushroom' to try to bring mushrooms into your life.  Same for other plants.

**Closed by MarjieAVolk** 2018-03-28 22:04 UTC
