### ISSUE TITLE
USER ISSUE: Floating grass

### ISSUE THREAD

**Issue by Geonorad** [StrangeLoopGames/EcoIssues#24750] opened 2024-02-07 23:47 UTC
\
**User Id: (slg233752)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
1. Put enough dirt in stockpile to fill up stockpile
2. Leave in stockpile until grass grows
3.  Remove dirt 

**Expected behavior:**
Grass on top should be removed with dirt

**Actual behavior:**
Dirt is removed but grass remains above stockpile floating in the air

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-02-08 06:35
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24646

**Closed by D3nnis3n** 2024-02-08 06:35 UTC
Labels: Status: Won't Fix
