### ISSUE TITLE
USER ISSUE: Testcontracts throws exception

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4424] opened 2018-02-12 23:00 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
type /testcontracts

IS THIS DUE TO STATS BEING OFF?

**Expected behavior:**
test contracts

**Actual behavior:**
--BEGIN DUMP--
Dump Time
02/12/2018 16:57:29

Exception
System.Exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()

--END DUMP--

Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invo

**Comment by MarjieAVolk** [comment] 2018-02-13 22:03
It seems this problem happens when you try to use a chat command without passing it the parameters it wants. To get around this, for now, you can type /help and the command name in order to figure out how to use the command.

Closing as duplicate of #4391

**Closed by MarjieAVolk** 2018-02-13 22:03 UTC
Labels: Low Priority
