### ISSUE TITLE
Truck flies up

### ISSUE THREAD

**Issue by WolfChieftain** [StrangeLoopGames/EcoIssues#8190] opened 2018-06-27 18:07 UTC
Steps to Reproduce:
Get a truck, drive it.

Expected behavior:
Truck drives around corners and straight roads without problems.

Actual behavior:
Every time you make a turn on a stone road, it glitches and flies up in the air.

**Comment by Amphysbaenas** [comment] 2018-06-28 02:06
suprised that it's just medium priority, we can not use anymore trucks so on 4km² world with road cities etc people stop to play because they can not transport things as before and wait for a patch .....

**Comment by WolfChieftain** [comment] 2018-06-28 16:14
We need to have patience until the devs fix it. the steam truck doesnt seem to have this problem @Amphysbaenas

**Comment by SeanAtr0n** [comment] 2018-06-28 18:56
If you can reliably reproduce the behavior somewhere in your world could you send us your Game.eco file and the coordinates?

**Comment by Myrhaug** [comment] 2018-06-28 19:00
We got the same problem at our server.
When we drive upwards on a ramp, the trucks flipping evrywhere (you can land several hundred yards from where you tried to drive).
As for now I only have tested Truck and it seems to be problem on almost all ramps.

**Comment by elfl0rd** [comment] 2018-06-28 19:09
Looks like this - https://github.com/StrangeLoopGames/EcoIssues/issues/7612 ?

**Comment by Myrhaug** [comment] 2018-06-28 19:18
Yes! And sometimes even worse then your clip about it

**Comment by SeanAtr0n** [comment] 2018-06-28 20:47
fixed in svn for 7.5.1

**Closed by SeanAtr0n** 2018-06-28 20:47 UTC
Labels: Medium Priority
