### ISSUE TITLE
Fix docker and s3 uploads on jenkins release pipeline

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#21427] opened 2021-04-16 23:31 UTC
they are both failing for some reason.

**Comment by redwyre** [comment] 2021-04-17 07:21
There is no issue with release pipeline, the real problem is https://github.com/StrangeLoopGames/SLG/issues/1

**Comment by redwyre** [comment] 2021-04-17 07:21
Duplicate of https://github.com/StrangeLoopGames/SLG/issues/1

**Comment by j3fffff** [comment] 2021-04-19 17:45
this issue happened after, abhi's credentials fix from https://github.com/StrangeLoopGames/SLG/issues/1

so seems to be secondary issue with uploads

**Comment by redwyre** [comment] 2021-04-20 10:40
They are still failing for the same reason, nothing has been fixed

**Comment by Abhiw205** [comment] 2021-04-22 19:02
[fixed]  https://github.com/StrangeLoopGames/SLG/issues/1

Unable to test because Jenkins permission level changed for my user, due to which i can't rerun the failed job with modification.

**Closed** 2021-04-28 23:07 UTC
Labels: Category: DevOps, Priority: Critical, Squad: Lattice Mushroom
