### ISSUE TITLE
Can't open or close doors while holding an EMPTY shovel

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5181] opened 2018-02-27 15:28 UTC
See the title. I know you can't do much things when you got something on your shovel, but closing and opening doors with an EMPTY shovel in hand should work like with any other tool.

**Comment by MarjieAVolk** [comment] 2018-02-27 18:24
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3868

**Closed by MarjieAVolk** 2018-02-27 18:24 UTC

**Comment by D3nnis3n** [comment] 2018-02-27 21:24
Funny note: I can open doory with a full shovel :D

Gesendet von Mail für Windows 10

Von: MarjieAVolk
Gesendet: Dienstag, 27. Februar 2018 19:25
An: StrangeLoopGames/EcoIssues
Cc: D3nnis3n; Author
Betreff: Re: [StrangeLoopGames/EcoIssues] Can't open or close doors whileholding an EMPTY shovel (#5181)

Closed #5181.

**Comment by MarjieAVolk** [comment] 2018-02-28 22:31
:D lol
