### ISSUE TITLE
Incorrect room tier calculations with stairs.

### ISSUE THREAD

**Issue by JustinGianelloni** [StrangeLoopGames/EcoIssues#18093] opened 2020-09-08 17:09 UTC
This has been a tricky one to duplicate, but it looks like when two sets of stairs occupy the same room and are placed above each other in a shared stairwell, they lower the tier value of rooms they lead to. In the pictures attached, there are two stacked staircases going between three floors. The middle level is isolated behind a wall, while the stairs on the first and third floor are not. This causes the tier level of the first and third floor to drop below the expected number (2.0 in this case). The only way I found to correct for this was to either wall up the stairwell on all three floors (sacrificing room volume) or placing another block directly under each stair block (I used lumber fence pieces since I could still walk under them). This fixes the tier value of the room ABOVE the stairs, but not the room underneath them. I've attached four screenshots to help illustrate. Floor 1 with an open stair case leading down (below 2.0), the stairwell itself (also below 2.0), the second floor, which is correct because it is separated by a wall, and the third floor (also below 2.0). To be clear, deleting the stairs and sealing the floors does remove the issue and restore the room tier to 2.0, so the issue appears to be with the stair blocks themselves. I have been able to duplicate the issue with Hewn Stairs, Brick Stairs, and Lumber Stairs in both the latest version of 0.8.3 and the latest version of the 0.9 playtest.

![floor 2 stairwell](https://user-images.githubusercontent.com/22803114/92507093-723a3700-f1d4-11ea-9f30-21944613517a.jpg)
![floor 2](https://user-images.githubusercontent.com/22803114/92507097-736b6400-f1d4-11ea-96fe-21fdd4901aa7.jpg)
![floor 3](https://user-images.githubusercontent.com/22803114/92507099-736b6400-f1d4-11ea-8939-0ff9e607a33a.jpg)
![floor 1](https://user-images.githubusercontent.com/22803114/92507101-749c9100-f1d4-11ea-9d96-2bdf9f7aca2d.jpg)

**Comment by JustinGianelloni** [comment] 2020-09-08 17:35
[debug.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5190020/debug.zip)

Attaching a new 0.9 save with an example building illustrating the issue.

**Comment by IcedForge** [comment] 2020-09-09 01:45
The issue is that the stairs are causing it to count as part of the room, and not just an opening so its adding the empty spaces as blocks part of the structure, and "AirBlock" is t0 and thats causing the room quality to drop.

**Comment by SlayksWood** [comment] 2020-09-09 04:54
@JustinGianelloni Thank you for the report. Place 2 block here:
![image](https://user-images.githubusercontent.com/45708377/92555993-8718d800-f271-11ea-93ce-e776cff26447.png)
And maybe you should add 3rd block too.
Did this solve your problem?

**Comment by JustinGianelloni** [comment] 2020-09-09 13:15
Adding blocks to those locations doesn't not resolve the issue. Adding blocks in the same location to the staircase above it, however, does correct the tier level for the third floor, but not the stairwell itself (inconsequential) or the first floor (pictured).

Also, is needing to place a block under stairs within a room expected behavior? This only seems to be necessary when there are two staircases stacked (although there may be some other edge cases), so the behavior is not consistent.

**Comment by SlayksWood** [comment] 2020-09-22 10:48
@JustinGianelloni Do you still have problem? 
I will merged this issue to #14233 and will investigate it here. 
Will be great if you add save files to #14233

**Closed by SlayksWood** 2020-09-22 10:48 UTC
Labels: Status: Needs Information
