### ISSUE TITLE
USER ISSUE: No wetland biome

### ISSUE THREAD

**Issue by Abricheno** [StrangeLoopGames/EcoIssues#7007] opened 2018-04-05 20:05 UTC
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
Created a new world and it spawned without working wetland biome (Shows up under water. And now we dont have any mushrooms to loot

**Expected behavior:**
It souldn't have spawned it all under water.
It sould spawn some of everything on dry land.

**Actual behavior:**
No proper wetland biome spawned out of the water

**Comment by MarjieAVolk** [comment] 2018-04-06 01:26
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Closed by MarjieAVolk** 2018-04-06 01:26 UTC
