### ISSUE TITLE
USER ISSUE: Chopping Tree Disconnected Client

### ISSUE THREAD

**Issue by Soaryn** [StrangeLoopGames/EcoIssues#6850] opened 2018-04-01 16:50 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
I actually don't know to be honest.

I chopped a tree (on a server) that was partially falling in a pit. Upon hitting the tree I was disconnected.

**Expected behavior:**
Tree should chop

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object

  at TreeEntity.TrySliceTrunk (Eco.Gameplay.Players.Player player, System.Single slicePoint) [0x001be] in <a0cb3314f4eb4a8fabae7722e517bfcf>:0 
  at TreeEntity.TryApplyDamage (Eco.Shared.Networking.INetObject damager, System.Single amount, Eco.Gameplay.Interactions.InteractionContext context) [0x0012b] in <a0cb3314f4eb4a8fabae7722e517bfcf>:0 
  at Eco.Gameplay.Items.WeaponItem.OnActLeft (Eco.Gameplay.Interactions.InteractionContext context) [0x00034] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at Eco.Mods.TechTree.AxeItem.OnActLeft (Eco.Gameplay.Interactions.InteractionContext context) [0x000c5] in <a0cb3314f4eb4a8fabae7722e517bfcf>:0 
  at Eco.Gameplay.Players.Player+<>c__DisplayClass51_0.<PlayerInteract>b__0 (Eco.Gameplay.Interactions.IInteractable inter) [0x00000] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions+<>c__DisplayClass0_1`1[T].<ExecuteUntilSuccess>b__1 () [0x00000] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess (System.Collections.Generic.IEnumerable`1[T] results) [0x00016] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, System.Func`2[T,TResult] resultFunc) [0x0001f] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at Eco.Gameplay.Players.Player.PlayerInteract (Eco.Shared.Items.InteractionInfo info) [0x000fe] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <b64e2aa77b4f4d60b739d6ceaf49caa4>:0 
</size>
```

**Comment by Soaryn** [comment] 2018-04-01 16:52
As a note, Relogging, resulted in the tree being chopped, but further interaction with said tree Disconnects again

```
Caught exception

<size=60.00%>Object reference not set to an instance of an object

  at TreeEntity.PickupLog (Eco.Gameplay.Players.Player player, System.Guid logID) [0x002af] in <a0cb3314f4eb4a8fabae7722e517bfcf>:0 
  at TreeEntity.OnActInteract (Eco.Gameplay.Interactions.InteractionContext context) [0x0004d] in <a0cb3314f4eb4a8fabae7722e517bfcf>:0 
  at Eco.Gameplay.Players.Player+<>c__DisplayClass51_0.<PlayerInteract>b__2 (Eco.Gameplay.Interactions.IInteractable inter) [0x00000] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions+<>c__DisplayClass0_1`1[T].<ExecuteUntilSuccess>b__1 () [0x00000] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess (System.Collections.Generic.IEnumerable`1[T] results) [0x00016] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, System.Func`2[T,TResult] resultFunc) [0x0001f] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at Eco.Gameplay.Players.Player.PlayerInteract (Eco.Shared.Items.InteractionInfo info) [0x000fe] in <c4ebfc6c72004536b8f5a7c00ad5cd48>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <b64e2aa77b4f4d60b739d6ceaf49caa4>:0 
</size>
```

**Comment by MarjieAVolk** [comment] 2018-04-02 21:54
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-04-02 21:54 UTC
