### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by xxex0tiik77xx** [StrangeLoopGames/EcoIssues#11560] opened 2019-03-03 22:01 UTC
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by D3nnis3n** [comment] 2019-03-03 22:02
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11548

**Closed by D3nnis3n** 2019-03-03 22:02 UTC
