### ISSUE TITLE
USER ISSUE: Wind Turbine & Solar Generator

### ISSUE THREAD

**Issue by LordLump** [StrangeLoopGames/EcoIssues#4598] opened 2018-02-15 19:50 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Both Wind Turbine & Solar Generator fail to provide power to my tier 2 house, only windmill & waterwheel works.

**Expected behavior:**
should provide power to the power grid

**Actual behavior:**
Says it's operational and provides power, but in the machines in the house it's not providing anything?

**Comment by UnknownViper** [comment] 2018-02-15 21:15
There's two different types of power in the game: Mechanical and electricty. Different machines require different types of power.

**Comment by LordLump** [comment] 2018-02-15 21:18
Ah! 
Well that explains things!

**Comment by MarjieAVolk** [comment] 2018-02-16 20:05
Closing as intended behavior :)  It should display the power type required / provided on each object's 'Power' tab.  But possibly this still needs to be displayed more obviously.

**Closed by MarjieAVolk** 2018-02-16 20:05 UTC
