### ISSUE TITLE
USER ISSUE: Not given Stone Axe during Tutorial because Inventory full

### ISSUE THREAD

**Issue by denriktiga** [StrangeLoopGames/EcoIssues#4005] opened 2018-02-06 23:28 UTC
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
1. Run tutorial until Chop Down a Tree
2. Have full inventory when clicking the icon

**Expected behavior:**
It should have known I was not given the Stone Axe and give it to me when clicking the icon again after making space.

**Actual behavior:**
Instead the Axe disappeared and made me unable to finish the tutorial

**Comment by MarjieAVolk** [comment] 2018-02-06 23:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3915

Hopefully we can address this soon

**Closed by MarjieAVolk** 2018-02-06 23:40 UTC
