### ISSUE TITLE
USER ISSUE: Item-Icon "hanging" around

### ISSUE THREAD

**Issue by sagg** [StrangeLoopGames/EcoIssues#5265] opened 2018-03-01 12:33 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. open inventory
2. open chest with 14 charred meat in
3. drag&drop meat into the first inventory slot (was empty)

it's hard to reproduce, i had this only one time.

**Expected behavior:**
the meat should drop into inventory

**Actual behavior:**
the drag&drop-action ends while dragging the item (like loosing focus) over the inventory. then the icon of the charred meat hangs around, but is not useable and has no amount of units. after disconnecting the icon is still there and the meat is back in the chest. the icon has no actions (not clickable, dragable, etc.). i see that the icon now (while i'm writing this) is gone..but i dont know why. :/ maybe one of those three actions triggers something which "fixes" this behavior: tabbing into another app, open steam-overlay or taking screenshot with F12.
or it's just fixed by time, don't know. i hope this helps and you know what i mean. :)

**Comment by LiaungYip** [comment] 2018-03-01 17:58
I've also observed this on Windows 10.

Alt-Tab fixes it (mostly), though the stack is missing the item count (i.e. `100`) even after Alt-Tab.

**Comment by MarjieAVolk** [comment] 2018-03-01 18:30
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

People have been observing that minimizing the game clears the icons.

**Closed by MarjieAVolk** 2018-03-01 18:30 UTC
