### ISSUE TITLE
How to remove from Office

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#20693] opened 2021-02-21 17:21 UTC
Hello,
 i have the needed permissions to remove someone from elected title at the ballot box.
![image](https://user-images.githubusercontent.com/47274045/108632822-283aca00-7471-11eb-9e10-d73c451a20ea.png)

At the ballot box I cannot find any option to do so:
![image](https://user-images.githubusercontent.com/47274045/108632862-57e9d200-7471-11eb-82d5-2fe9ff49c9e7.png)

Although I cannot find somewhere else how to execute this permission to remove someone from office.

**Comment by D3nnis3n** [comment] 2021-02-21 22:43
That is an executive action, hence you find it at the executive office.
Closing, as this is a question, not a bug.

**Closed by D3nnis3n** 2021-02-21 22:43 UTC

**Comment by Alteraner** [comment] 2021-02-22 00:09
![image](https://user-images.githubusercontent.com/47274045/108643341-7a4c1180-74aa-11eb-960f-e5901ad4fae1.png)
Sorry, cannot find the option in the Executive Office. Further, I would recommend changing the description as it states it can be done at the ballot box.

**Comment by D3nnis3n** [comment] 2021-02-22 00:39
Sorry, I meant the government office, always confusing those two, haha:
![image](https://user-images.githubusercontent.com/25908592/108644294-b3868080-74ae-11eb-87d1-0c01cd0d3bfb.png)
