### ISSUE TITLE
Fish does not appear in backpack after catching it with a fishing pole

### ISSUE THREAD

**Issue by kasildun** [StrangeLoopGames/EcoIssues#5155] opened 2018-02-27 00:13 UTC
Only after relogging it shows up in my inventory.

**Comment by MarjieAVolk** [comment] 2018-02-27 00:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

**Closed by MarjieAVolk** 2018-02-27 00:32 UTC
