### ISSUE TITLE
[0.8.2 Staging -5] Lamp lights

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12252] opened 2019-05-10 15:53 UTC
The Ceiling lamps Wooden or Steel have no Light Effect.

And the Game is somestimes slow to notice that objects have been switched off. The Light effect is showing some time even though the lights have been turned off

https://youtu.be/CJftLW9a_iE

**Comment by D3nnis3n** [comment] 2019-05-13 07:58
Second part is working as intended, for performance reasons.

**Comment by redwyre** [comment] 2019-11-12 14:15
@keegan-o you know what needs to happen for these to work?

**Comment by keegan-o** [comment] 2019-12-07 00:32
This was happening because the GI sub game objects were missing their emmisive meshes, which is what constitutes the light when GI is on in-game.
![image](https://user-images.githubusercontent.com/14983165/70364924-ad719900-1843-11ea-9588-1842d921a5bb.png)
![image](https://user-images.githubusercontent.com/14983165/70365346-c8450d00-1845-11ea-8c46-1b92a0e6583d.png)

Fixed in staging.

**Closed by keegan-o** 2019-12-07 00:32 UTC
Labels: Medium Priority, Push Candidate, Staging
