### ISSUE TITLE
USER ISSUE: Stove missing

### ISSUE THREAD

**Issue by NortonDK** [StrangeLoopGames/EcoIssues#4929] opened 2018-02-22 03:25 UTC
**Version:** 0.7.2.0 beta staging-08551408
https://media.discordapp.net/attachments/258375026435162112/416039237561876481/20180222020803_1.jpg?width=1051&height=657

**Steps to Reproduce:**
1. Place a stove(Stove, not cast iron stove)

**Expected behavior:**
Being able to see and interact with the stove

**Actual behavior:**
Its invisible, apart from the stove pipe ending

Game version: 0.7.2.0 beta staging

**Comment by MarjieAVolk** [comment] 2018-02-23 00:01
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4927

**Closed by MarjieAVolk** 2018-02-23 00:01 UTC
