### ISSUE TITLE
Tool background changes to red if you have another broken tool of that kind

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2544] opened 2017-10-13 19:59 UTC
It was blue when crafted, but when I selected it it turned red.

Not sure if the broken tool needs to be on the hotbar or just anywhere in your inventory.

![image](https://user-images.githubusercontent.com/609510/31564024-447509ba-b016-11e7-9bba-d8b072ad1c72.png)

**Comment by knexer** [comment] 2017-10-13 21:04
Just fyi, the conditions I specified here don't seem to be quite right, since I can't repro it now.  All I know is a short while after I craft and start using a new tool it always turns red.

**Comment by metachronism** [comment] 2017-11-09 23:10
also the recoloring of this is a bit extreme and looks bad - should only affect the bar
can't assume all icons will have the same sprite layout

**Comment by MarjieAVolk** [comment] 2018-01-24 01:52
Hm I can't repro this either

**Comment by elfl0rd** [comment] 2018-06-25 17:49
Haha, confirm.
Video later))

**Comment by MarjieAVolk** [comment] 2018-06-25 17:59
> Version: 0.7.2.3 beta
> 
> Steps to Reproduce:
> 
> Have a broken road tool in your taskbar
> Have a working road tool in your backpack
> Change the broken roadtool out with the working road tool, per drag and drop
> Expected behavior:
> The broken roadtool has a red background. When i change it out for the new road tool, the background should turn blue again
> 
> Actual behavior:
> Instead, although the new roadtool had full health, the background remained red
-- @LEGIONDE

**Comment by elfl0rd** [comment] 2018-06-25 18:02
![error](https://user-images.githubusercontent.com/4980243/41867186-04129f04-78bb-11e8-82f9-e7b74230253d.gif)

**Comment by elfl0rd** [comment] 2018-06-25 18:03
These happens if you have tools in backpack and change broken on the fly.

**Comment by elfl0rd** [comment] 2019-02-16 09:50
Another side from Splutty

When your inventory is full, and you drag a tool into it that has a red background due to being dead, it'll change it back to the normal blue background before placing it back in the chest you were dragging it from.
100% reproduceable.

Easy to replicate, I'm not currently in game. Drag a broken tool from a chest into your inventory when your inventory is full. The tool will return to the chest and now have a blue background, but still be broken.

The other reports all reference a healthy tool getting a red background. So the exact opposite :)

It's probably a similar cause, though, somehow losing the colour status when shifting things around.

Broken tool in Chest
![npnlkdh](https://user-images.githubusercontent.com/4980243/52897862-bb88f700-31e8-11e9-89a2-9c88f2055eee.png)

Inventory Full
![hb3fvk2](https://user-images.githubusercontent.com/4980243/52897875-bd52ba80-31e8-11e9-8686-138028d35272.png)

Broken tool in Chest with blue background after trying to drag into full inventory
![w2xevcy](https://user-images.githubusercontent.com/4980243/52897878-bfb51480-31e8-11e9-9d05-d6273c1a6785.png)

**Comment by SlayksWood** [comment] 2019-04-26 14:39
Still an issue 0.8.1.4
![image](https://user-images.githubusercontent.com/45708377/56815461-1888d500-684a-11e9-907c-131868dcc8e7.png)

**Comment by SlayksWood** [comment] 2019-08-06 05:58
merged with #12149

**Closed by SlayksWood** 2019-08-06 05:58 UTC
Labels: Medium Priority, QA
