### ISSUE TITLE
[SERVER ISSUE] Crash due to Eco.Simulation.Agents.Animal.Kill ?

### ISSUE THREAD

**Issue by Ekkelus** [StrangeLoopGames/EcoIssues#5754] opened 2018-03-09 09:03 UTC
**Version:** 
0.7.2.3 beta

**Steps to Reproduce:**
No idea, I wasn't on when the server crashed.

**Expected behavior:**

**Actual behavior:**
Crashed

--BEGIN DUMP--
Dump Time
03/09/2018 09:56:26

```
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Simulation.Agents.Animal.Damage(Single amount, DeathType damageSource)
   at Eco.Simulation.WorldLayers.Layers.AnimalLayer.DamageAnimals(Vector2i layerPos, Single maxDamage)
   at Eco.Simulation.WorldLayers.Layers.AnimalLayer.Push(Vector2i layerPos)
   at Eco.Simulation.WorldLayers.Layers.AnimalLayer.Push()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Simulation.WorldLayers.WorldLayerSync.<>c.<Tick>b__11_5()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerSync.Tick()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.TryTick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
```

**Comment by MarjieAVolk** [comment] 2018-03-09 19:33
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4860

**Closed by MarjieAVolk** 2018-03-09 19:33 UTC

**Comment by Ekkelus** [comment] 2018-03-09 20:01
@MarjieAVolk please notice that this made the server crash, the other one was a client issue.

**Comment by MarjieAVolk** [comment] 2018-03-09 20:12
Yes you are right.  I believe it's the same error, experienced in two different contexts (Eg. one animal died by arrow, one died of natural causes), but I will make a note of it.

**Comment by Ekkelus** [comment] 2018-03-09 20:25
Thank you :)

**Comment by Ekkelus** [comment] 2018-03-09 22:30
--BEGIN DUMP--
Dump Time
03/09/2018 23:22:37

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Gameplay.Components.AnimalTrapComponent.LayerTick()
   at System.Action.Invoke()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerSync.Tick()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.TryTick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
