### ISSUE TITLE
[0.9.0 staging-1245] Empty header for the candidate voting

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13656] opened 2019-11-12 08:00 UTC
I have title Mayor. And election for it.
But header on the web is looking like that (Details of - )
![bandicam 2019-11-12 12-56-18-555](https://user-images.githubusercontent.com/27898520/68652965-7235c000-054c-11ea-98d1-02115bd4ee9d.jpg)

**Comment by beastyn** [comment] 2019-11-16 08:50
Can't reproduce anymore. close for now

**Comment by beastyn** [comment] 2019-12-10 09:36
Have met again. Save in private.

**Comment by SlayksWood** [comment] 2020-01-23 10:40
In laws for example: Details of "Law Name"
in Elected title: Details of "elected title discription":
![image](https://user-images.githubusercontent.com/45708377/72977538-ccbd8900-3de5-11ea-95b5-ebd542875fee.png)
It should be:
![image](https://user-images.githubusercontent.com/45708377/72977450-a39cf880-3de5-11ea-8167-036f7d4ad164.png)

**Comment by gzatravkin** [comment] 2020-06-11 12:01
Looks be already fixed by design changes:
![image](https://user-images.githubusercontent.com/53317567/84383166-23273a80-abc2-11ea-9919-14e37e1e108e.png)

**Closed** 2020-06-15 11:05 UTC
Labels: Category: Web, Priority: Low, Status: Fixed, Week Task
