### ISSUE TITLE
USER ISSUE: Shop Bug

### ISSUE THREAD

**Issue by Sirisma** [StrangeLoopGames/EcoIssues#4740] opened 2018-02-17 22:40 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Open Shop GUI, click Add Entity, do not click on the Add Entity GUI, scroll mouse.

**Expected behavior:**
Scroll Add Entity GUI

**Actual behavior:**
Scroll both Add Entity menu and scroll through hotbar until you click on Add Entity GUI

**Comment by ecoemmeck** [comment] 2018-02-18 02:57
This also happens when scrolling through tables

**Comment by MarjieAVolk** [comment] 2018-02-23 19:49
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3789

**Closed by MarjieAVolk** 2018-02-23 19:49 UTC
