### ISSUE TITLE
EcoServer.exe stopped responding

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#4476] opened 2018-02-13 22:26 UTC
Hello there. Recently my sever begun to crash and it happened twice already in just a small period of only 12 hours. Its running on Windows Server 2016. The dumps seem to be identical:

```
--BEGIN DUMP--
Dump Time
02/13/2018 05:37:36
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
at System.Collections.Immutable.ImmutableList1.Node.RemoveAll(Predicate1 match)
at System.Collections.Immutable.ImmutableList1.RemoveAll(Predicate1 match)
at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
at Eco.Core.Controller.ControllerManager.Run()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart(Object obj)
--END DUMP--

--BEGIN DUMP--
Dump Time
02/13/2018 15:09:22
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
at System.Collections.Immutable.ImmutableList1.Node.RemoveAll(Predicate1 match)
at System.Collections.Immutable.ImmutableList1.RemoveAll(Predicate1 match)
at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
at Eco.Core.Controller.ControllerManager.Run()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart(Object obj)
--END DUMP--

```

Thanks.

**Comment by MarjieAVolk** [comment] 2018-02-13 22:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368.  You can track the issue progress there.

**Closed by MarjieAVolk** 2018-02-13 22:29 UTC
