### ISSUE TITLE
Server Crash - Unknown Cause: Argument Out of Range

### ISSUE THREAD

**Issue by Harkole** [StrangeLoopGames/EcoIssues#5891] opened 2018-03-11 12:46 UTC
I don't know if it's related to the server back up but don't believe it is as there were no crashes earlier, two players connected one was manipulating landscape with shovel the other was pulling a cart.

![image](https://user-images.githubusercontent.com/3703699/37253482-25b75b52-252a-11e8-8c50-17660ae3d1ce.png)

**Comment by MarjieAVolk** [comment] 2018-03-13 00:48
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5527

**Closed by MarjieAVolk** 2018-03-13 00:48 UTC
