### ISSUE TITLE
USER ISSUE: Tutorial doesn't end

### ISSUE THREAD

**Issue by MrMagolor** [StrangeLoopGames/EcoIssues#4735] opened 2018-02-17 20:32 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Play through tutorial enough

2.Decide that you've done enough

3. Try to skip

4. Fail

**Expected behavior:**
Removed all the tutorial tabs and ended the tutorial

**Actual behavior:**
May have ended the tutorial, but the tabs were still open

**Comment by aphadeon** [comment] 2018-02-19 06:30
I can confirm this issue.  Of three playthroughs, one of them left the tutorials incompletable and they would not go away even when I hit skip.  Restarting tutorial "fixed" it.

**Comment by MarjieAVolk** [comment] 2018-02-20 21:05
The next time this happens, could you guys send your client output log?  It is at C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

You could try sending it now, although I fear if you've played a couple times since seeing the error, it won't be there any more.

**Comment by johnkslg** [comment] 2018-02-20 21:39
Should be fixed in master

**Comment by MarjieAVolk** [comment] 2018-02-23 02:10
I believe that didn't make it in to the next release in that case.  So will be fixed in two releases.

**Closed by MarjieAVolk** 2018-02-23 02:10 UTC
Labels: High Priority
