### ISSUE TITLE
USER ISSUE: Can't enter Third Person View

### ISSUE THREAD

**Issue by hastenfist** [StrangeLoopGames/EcoIssues#24496] opened 2024-01-01 16:33 UTC
\
**User Id: (slg204456)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Press Third Person View button (F5 for me) or check "Third Person" box in the backpack.

This doesn't occur all of the time, only sporatically, but the issue lasts for several minutes and then the third person option works again. I have no idea how to reliably reproduce the issue.

**Expected behavior:**
Enter third person view.

**Actual behavior:**
View stays in first person.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-02 02:03
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24243

**Closed by D3nnis3n** 2024-01-02 02:03 UTC
