### ISSUE TITLE
Recipies not finishing crafting

### ISSUE THREAD

**Issue by akutamatata** [StrangeLoopGames/EcoIssues#6100] opened 2018-03-15 21:03 UTC
Tables sometimes don't allow crafting orders to finish because they supply too many resources

Perhaps this is because of 'eff' skills math is incorrect when creating orders? I'm not sure, but I noticed this when going into the tables which said 100% time 100% resources, the bar completely yellow, hours after it was meant to be finished and gone.

So I cancelled the orders and extra stone ended up into my stockpiles as I cancelled the 'finished' orders.

**Comment by MarjieAVolk** [comment] 2018-03-15 21:18
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3240

(I wrote a fix for this, should be fixed in next release :) )

**Closed by MarjieAVolk** 2018-03-15 21:18 UTC
