### ISSUE TITLE
7.0 Tier 3 Progression only available through glass

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3728] opened 2018-01-30 23:27 UTC
Version: staging-7da08558

Tier 3 Materials: Lumber, Brick, Glass, Iron Pipe

To get to Lumber you need Cloth
![image](https://user-images.githubusercontent.com/1503963/35594509-75ca31d6-05e1-11e8-900f-c55202a8a8e3.png)

To get to cloth you need a Tailoring table in a room with  32 Tier 3 materials.
![image](https://user-images.githubusercontent.com/1503963/35594880-b92697ca-05e2-11e8-8bf5-6ba1f521acbe.png)

Since we cannot make Lumber lets try Brick.

To get Brick, you need to research bricklaying and the book requires cloth, see above.
![image](https://user-images.githubusercontent.com/1503963/35594746-368f3740-05e2-11e8-9035-7f052122edba.png)

Ok... how about iron pipe? Iron pipe is crafted at an anvil, which requires 18 tier 3 materials.
![image](https://user-images.githubusercontent.com/1503963/35594833-915cf2f2-05e2-11e8-8462-464ec252773c.png)

So we're left with glass to use to be able to make cloth. So we need a room with 32 glass in it. Please don't tell me that is the only option to get to Tier 3 materials.

**Comment by MarjieAVolk** [comment] 2018-01-30 23:29
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3715

**Closed by MarjieAVolk** 2018-01-30 23:29 UTC
