### ISSUE TITLE
USER ISSUE: crash while picking up wood

### ISSUE THREAD

**Issue by larsonj** [StrangeLoopGames/EcoIssues#5349] opened 2018-03-03 20:37 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
pick up wood after chopping tree	

**Expected behavior:**
wood in inv

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-03-05 20:04
Fixed in next release

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-03-05 20:04 UTC
