### ISSUE TITLE
Allow openings for roofs in rooms to allow for interior stairs 

### ISSUE THREAD

**Issue by babare** [StrangeLoopGames/EcoIssues#3659] opened 2018-01-27 13:05 UTC
In 6.4.1 we can't make interior stairs to connect vertical rooms because the room system doesn't allow any opening in the roof.
It would be great to be able to !

**Comment by craig-jong** [comment] 2018-07-27 00:32
Closing this as not a bug - should go into suggestions. Room detection in general needs a good luck at.

**Closed by craig-jong** 2018-07-27 00:32 UTC
Labels: Medium Priority
