### ISSUE TITLE
USER ISSUE: CriminiMushroom Spores Non Existant

### ISSUE THREAD

**Issue by albertkun** [StrangeLoopGames/EcoIssues#6492] opened 2018-03-25 16:06 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
When starting a new world there are no mushroom spores.

**Expected behavior:**
There should be crimini mushroom spores in world because farming research requires it.

**Actual behavior:**
They do not exist.

**Comment by MarjieAVolk** [comment] 2018-03-26 18:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5092

**Closed by MarjieAVolk** 2018-03-26 18:40 UTC
