### ISSUE TITLE
[8.3.0] Transfer Menu with no GUI

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14199] opened 2019-12-21 21:43 UTC
Sea Otter - but not Giant Panda which shares the exact same files despite the save has an issue that the transfer dialog has no UI, both servers use no mods

![tax](https://user-images.githubusercontent.com/25908592/71314134-507d0200-2443-11ea-8f5a-ec4d5ecb9dd7.png)

**Comment by SlayksWood** [comment] 2019-12-23 08:26
8.3.2:
![image](https://user-images.githubusercontent.com/45708377/71345640-04cb7500-2577-11ea-95c3-be0e656f3206.png)
Can you provide save files?

**Comment by SlayksWood** [comment] 2020-01-10 09:06
Can't reproduce. Close for now
![image](https://user-images.githubusercontent.com/45708377/72140360-a2a9a700-33a1-11ea-8c3d-50fbb8d10d60.png)

**Comment by D3nnis3n** [comment] 2020-01-10 10:08
Sorry,
i've already been on vacation when you asked for a savegame. Here it is:
https://download.godsofwar.de/eco/seaotter6.zip

**Comment by D3nnis3n** [comment] 2020-01-10 10:09
Dropping to Medium, as it is no longer occuring on the new world. It must have to do with the specific world save / db. Should be looked into to prevent a potential issue in 9.0.

**Comment by mirasrael** [comment] 2020-04-20 09:11
Many things was changed in 9.0 since that and we haven't any reproduce info. So closing it until we can confirm it in 9.0.

**Closed by mirasrael** 2020-04-20 09:11 UTC
Labels: Priority: Medium, Status: Investigate
