### ISSUE TITLE
Brodie Bug: No feedback on table place failure

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3103] opened 2017-12-12 23:10 UTC
-tried to place a workbench but it wouldn't do it - need info on why immediately. maybe network lag?

-It turned out I had to Right Click to place the work bench. I feel like the UI relies too much on memory. ECO would benefit by including prompts for what actions each control button does. Lego Worlds does this well on consoles - they have a side UI with the control reminders on screen, that you can hide once you become advanced.

**Comment by MarjieAVolk** [comment] 2017-12-12 23:22
All of these bugs are not actually well defined tasks :/  This sounds like a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2776 and maybe also a bug report?  But I don't think it was actually a bug in this case, just confusion

**Closed by MarjieAVolk** 2017-12-12 23:22 UTC
