### ISSUE TITLE
 0.9.0.0 beta staging-1554. White line marking of the Asphalt Concrete White Ramp Edge Line gets broken/displaced

### ISSUE THREAD

**Issue by CorsarSPb** [StrangeLoopGames/EcoIssues#16418] opened 2020-05-20 12:01 UTC
**Version:** 0.9.0.0 beta staging-1554

**Steps to Reproduce:** 
![image](https://user-images.githubusercontent.com/65302234/82443749-af09e300-9aaa-11ea-970d-2df3454f4938.png)

**Expected behavior:**

**Comment by SlayksWood** [comment] 2020-05-20 12:31
@CorsarSPb Can't reproduce.
Can you provide save files with coordinates. Or provide more information about nearest blocks. What kind of blocks under this ramp?

**Comment by CorsarSPb** [comment] 2020-05-20 12:40
![image](https://user-images.githubusercontent.com/65302234/82446815-05c5eb80-9ab0-11ea-9d3d-e5fa62160e20.png)

built in the air so that there were no blocks nearby. nothing changed

**Comment by Daniel-Magulado** [comment] 2021-03-17 23:13
Tested on 0.9.3 Staging-1955

I am able to reproduce it.

Repro:
1. Grab some Asphalt Concrete, carry as much as the maximum allowed.
2. Select any type of hammer tool.
3. Select Rectangle as Fill Type.
4. Use all the Asphalt Concrete that you are currently carrying to layout a complete set of ramps as much as possible.
5. Give yourself another set of Asphalt Concrete.
6. This time, layout another set of complete Asphalt Concrete ramp but facing the other way. Make sure, these sets of Ramps are next to each other.
7. Observe.

![Untitled.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/238b73e9-6062-4b73-9d62-6942b0b20d05)

Video Repro:
https://images.zenhubusercontent.com/47210472/e9c84543-a408-49ce-a1cf-879eb89c11dd/2021_03_18_07_04.mp4

**Comment by keegan-o** [comment] 2021-03-29 21:41
fixed in staging and develop branches (so will hopefully be fixed in 9.3)

**Closed by keegan-o** 2021-03-29 21:41 UTC
Labels: Category: Art, Category: Gameplay, Priority: Medium, Squad: Saguaro, Type: Bug
