### ISSUE TITLE
USER ISSUE: error code when relogging to server

### ISSUE THREAD

**Issue by Stressinout** [StrangeLoopGames/EcoIssues#4379] opened 2018-02-12 07:48 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
okays so I'm stuck to where I cannot get on my server, the last thing I did was accept a contract and logged off a few mins later. Go to log back on and is given some error message, I'm one of the players that have to select their character due to that steam release issue. I've tried relaunching the game, verifying the game, launch both through steam and download from the site, and restart both my pc and the server and I'm still stuck with this error message. Wondering where I can go from here to be able to play again?

<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.

Stack:
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
at Eco.Plugins.Networking.Clients.Client.ShouldSelectUser()

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Plugins.Networking.Clients.Client.ShouldSelectUser()

```

**Comment by Stressinout** [comment] 2018-02-12 07:52
now coincidently the person who started the contract is also receiving the same error. This is their error <size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Plugins.Networking.Clients.Client.ShouldSelectUser()

**Comment by MarjieAVolk** [comment] 2018-02-13 01:36
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4413

We have a fix for this, which will be released in the next update.  As you noted, it is related to accepting the contract in this case.  Unfortunately I don't think there is a good workaround.  You should still be able to play on other servers in the mean time.

**Closed by MarjieAVolk** 2018-02-13 01:36 UTC
