### ISSUE TITLE
USER ISSUE: Stockpile eat items

### ISSUE THREAD

**Issue by Kirthos** [StrangeLoopGames/EcoIssues#7845] opened 2018-05-23 14:01 UTC
**Version:** 0.7.4.5 beta

I've searched from a duplicate, but not sure if it's the same problem.
Maybe related to #7785 or #5895

**Steps to Reproduce:**
Build one of the 2 stockpiles in the screen below with the exact same amount of items, the place where you put the items is not important from the test I've made.
![image](https://user-images.githubusercontent.com/5023261/40426896-8105d67c-5e9c-11e8-93f7-e81b789f1701.png)
The first stockpile eat hewn log. 
The second stockpile eat dirt.

After more experimenting, I've found what seems to cause the problem, the stockpile sometime don't sort the block correctly, and when trying to sort, if the block that can't be placed anywhere already exist in the stockpile it's disappeared (I.e If I try to put log instead of hewn log here, the log disappear)

![image](https://user-images.githubusercontent.com/5023261/40428840-7f4d8910-5ea1-11e8-84ff-b5d111daa221.png)

<details>
<summary>Log File</summary>(...previous log truncated...)

ngine.Component.GetComponentInParent (System.Type t) [0x00001] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at UnityEngine.Component.GetComponentInParent[T] () [0x00001] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at UI.BaseItemUI.OnChange () [0x00000] in <2c9362ff3b6f4767b4b44352d17195ba>:0 
  at UI.ItemCollectionUI.OnChange () [0x00000] in <2c9362ff3b6f4767b4b44352d17195ba>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <522b50c462ea4e44bfad45c74e5ed0ae>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <522b50c462ea4e44bfad45c74e5ed0ae>:0 
[16:16] Exception in view notify: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component:get_gameObject (UnityEngine.Component)
  at UI.BaseUI.Close () [0x00005] in <2c9362ff3b6f4767b4b44352d17195ba>:0 
  at SplitStackUI.StackChanged () [0x00016] in <2c9362ff3b6f4767b4b44352d17195ba>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <522b50c462ea4e44bfad45c74e5ed0ae>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <522b50c462ea4e44bfad45c74e5ed0ae>:0 
Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by gabeux** [comment] 2018-05-23 20:37
+1 we've done it on my server too

**Comment by metachronism** [comment] 2018-07-12 05:11
yes, this is a dupe of #5895

**Closed by metachronism** 2018-07-12 05:11 UTC
Labels: Medium Priority
