### ISSUE TITLE
Game Finished and everthing Bugs

### ISSUE THREAD

**Issue by mcenderdragon** [StrangeLoopGames/EcoIssues#5628] opened 2018-03-07 21:33 UTC
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
We finished the game, so we lasered the meteorid

**Expected behavior:**
well less weirdness

**Actual behavior:**
Everything desynced extremly so none of the players saw each other, after disconnecting the server was offline. We had to kill and restart it to join again. After joining the server as not playable the world did not load poperly and some holes spawned. It seemed like mini parts from the metorid but everything was buggy and crashed.

Your game is fun though so please continue improving it :)

**Comment by mcenderdragon** [comment] 2018-03-07 21:33
```
<size=150%>Connection Failed</size>

Caught exception:

<size=60,00%>Der Wert darf nicht NULL sein.
Parametername: item


Stack:
   bei System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   bei System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   bei Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   bei Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Gameplay.Players.Player.SendInitialState(BSONObject obj, INetObjectViewer viewer)
   bei Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by johnkslg** [comment] 2018-03-14 00:22
Closing as duplicate of #5628
Couldnt find anything specific to end of world scenario, tested a bunch.

**Closed** 2018-03-14 17:43 UTC
Labels: High Priority

**Comment by mcenderdragon** [comment] 2018-03-14 21:30
well thats the same crash but the crash has nothing to do with the stuff happened on our server...
