### ISSUE TITLE
USER ISSUE: Create Law but doesnt know what is false

### ISSUE THREAD

**Issue by Geuthur** [StrangeLoopGames/EcoIssues#4529] opened 2018-02-14 17:13 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
http://prntscr.com/iepzul

Here is my step when i define the law i doesnt see whats wrong no text on top of the Red Line ....
i think on red line is the error text but it display nothing....
![jwaztns4qi_ptv0xun2dja](https://user-images.githubusercontent.com/761682/36217854-c704d092-11b2-11e8-945b-84b1a10a16df.png)

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-14 21:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4094

Chances are, you are having a real normal issue of some kind, and it's just impossible to tell because the error message it not showing up. Likely candidates for issues are:

*There's already a law with this name. Even if a law did not pass or was deleted, you can't make another law with the same name.
*You are not logged in to the game. Currently you must actually be running Eco in order to propose laws and do other government things (This was an undesired side effect of some changes we needed to make to support steam logins, which we will hopefully be changing in the future)
*You are not allowed to propose a law because of another law that is preventing it. For example, the default Citizenship law.

**Closed by MarjieAVolk** 2018-02-14 21:12 UTC
