### ISSUE TITLE
[0.9.0 Staging-1506] Composites, Adv. Masonry Research should require Oil Drilling / Adv. Smelting skills

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15739] opened 2020-04-13 10:47 UTC
Most research follows a good rule of hand - in order to start a research you need to have the skill required to perform a given job. Composites and Adv. Masonry, do not. The first one relies heavily on Oil, while the second one on Steel, yet you can start researching them way before you have access to those. Heck, you need those skills to make the products required for the research.

1) Version
0.9.0 Staging-1506

2) Expected behaviour
Research should have prerequisites that match what the skill will be using and which skills are involved in their research.

3) Actual behaviour
Composites and Advanced Masonry (at least) are available for Research way before they can be used or completed.

**Comment by WeaselDog** [comment] 2020-05-11 17:22
Thanks for the feedback. After looking into this more it looks like Steel is already a requirement for researching these skills. Advanced Masonry recipes do not require Oil Drilling and we decided to not delay Composites research as we want this to be an early Tier 4 skill. 

There are other examples where the research does not involved the ingredients used for recipes, for example Cooking and Electronics, We are looking at ways to introduce Oil Drilling earlier in the progression which will make Composites available earlier so this should solve this problem. For now I am going to close this issue as the research is working as intended.

**Closed by WeaselDog** 2020-05-11 17:22 UTC
Labels: Category: Balance, Priority: Low, Week Task
