### ISSUE TITLE
Issue with Steel Tooltip display

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3818] opened 2018-02-03 05:36 UTC
![image](https://user-images.githubusercontent.com/1503963/35763434-3bc2766a-087a-11e8-86ca-77d1261cae90.png)

**Comment by MarjieAVolk** [comment] 2018-02-03 22:18
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3251

**Closed by MarjieAVolk** 2018-02-03 22:18 UTC
