### ISSUE TITLE
Hold Ctrl to select subtooltips some things will Not display the Main tooltip when selected unless you hold ctrl

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#19624] opened 2020-12-06 15:13 UTC
\
**Version:** 0.9.1.8 beta release-130
![snap7728](https://user-images.githubusercontent.com/29383891/101282085-d320dd80-37ca-11eb-8d9b-66a5e9ea1d6f.png)

had this on by mistake but did notice that quite a few things will not show up the Main tool-tip if hovered over unless CTRL is pressed

some will not show main tool-tip in status window some will not show when typed into chat, i didnt check them all as the following bug with Mill in chat window caught my attention

example of this **Mill** will not show Main tooltip on status tab

and if you type Mill into chat it WILL NOT show 1st main tool-tip unless you type mill 5 times and then hover over 1st one typed
![snap7729](https://user-images.githubusercontent.com/29383891/101283426-28acb880-37d2-11eb-8cc2-fb65e3858db2.png)

this gif shows what i mean
![eco CTRL option 1](https://user-images.githubusercontent.com/29383891/101283894-44fe2480-37d5-11eb-8d00-f83c4680230b.gif)

**Comment by Conchipedia** [comment] 2020-12-06 15:20
i had to shorten the gif as it got huge, but with Ctrl option selected in options, i already typed Mill 4 times then recorded me typing it in for the 5th time and then hovering mouse over each one and showing that the 1st one will show main tooltip while others wont

i didnt fancy looking at every Status tab of every table that mentions the table name and then hovering mouse over it to see if it works or not then also type that name in chat

**Comment by Conchipedia** [comment] 2020-12-06 15:54
can sort of duplicate this by typing blast furnace but this one acts differently
type Blast furnace once, shows tool-tip
type Blast furnace twice shows tool-tip for both
type blast furnace third time will show tool-tip but not tool-tip for 1st blast furnace typed

**Comment by SlayksWood** [comment] 2020-12-07 07:02
Can't reproduce in staging-1864.

**Comment by Conchipedia** [comment] 2020-12-16 14:46
also another thing that happens with the CTRL option on
the last order on the right top of the screen will not show
![Uploading snap7822.png…]()

**Comment by Daniel-Magulado** [comment] 2021-07-29 23:02
Closing due to changes in tooltip.

**Closed by Daniel-Magulado** 2021-07-29 23:02 UTC
Labels: Status: Investigate, Status: Not reproduced
