### ISSUE TITLE
[8.1.0 Staging-1] Meteor Tutroial - Cutscene didn't show.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11724] opened 2019-03-21 13:40 UTC
Saw the meteor, objective got ticked, tutorial done. No cutscene.

**Comment by SeanAtr0n** [comment] 2019-03-21 18:57
Also noticed this, looks like the build machine isn't picking up changes to the build settings that added the MeteorIntroScene:
```
Scene 'MeteorIntroScene' couldn't be loaded because it has not been added to the build settings or the AssetBundle has not been loaded.
To add a scene to the build settings use the menu File->Build Settings...
UnityEngine.SceneManagement.SceneManager:LoadSceneAsync(String, LoadSceneMode)
Assets.UI.Scripts.TutorialTaskUI:OpenPopup()
LZ4.Action:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
System.Xml.Schema.ValidationEventHandler:Invoke(Object, ValidationEventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
```

**Comment by redwyre** [comment] 2019-03-27 18:12
Confirmed on staging 8.1-4, same error as Sean pasted

**Comment by beastyn** [comment] 2019-03-29 09:46
Update
0.8.1.0 staging-6

Confirmed, but in my case tutorial wasn`t ending. Objective got ticked.

![after_meteor_first_look](https://user-images.githubusercontent.com/27898520/55224050-69001900-5231-11e9-87d2-53daa8794391.jpg)

**Comment by beastyn** [comment] 2019-03-29 10:07
клиентский лог
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3022074/output_log.txt)

**Comment by BlazeGuy2** [comment] 2019-03-29 21:18
Someone moved the tutorial to a separate scene and forgot to update the build function to include it.  Should be fixed in the next build.

**Comment by beastyn** [comment] 2019-04-01 04:14
Still no cut scene in 0.8.1.0 staging-7 regardless it was meged.

**Closed** 2019-04-01 17:13 UTC
Labels: Staging

**Comment by BlazeGuy2** [comment] 2019-04-01 17:57
@beastyn Fix was merged in before new build.
