### ISSUE TITLE
USER ISSUE: the elevator does not work 

### ISSUE THREAD

**Issue by elray23234** [StrangeLoopGames/EcoIssues#11946] opened 2019-04-10 02:37 UTC
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
the elevator doesnt work 		

**Expected behavior:**
please help 

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by beastyn** [comment] 2019-04-10 03:54
Duplicate of #11870
Should work in 8.1.1, may have some issues with button targeting, will be fixed soon.

**Closed by beastyn** 2019-04-10 03:54 UTC
