### ISSUE TITLE
Devtool fix for Restrictet claims and Carts

### ISSUE THREAD

**Issue by Geuthur** [StrangeLoopGames/EcoIssues#4820] opened 2018-02-19 11:07 UTC
Devtool not working on Carts and claims who you are not have permissions

Its very bad at big server with many people 
Who place some carts

Hope they fix this

**Comment by ecoemmeck** [comment] 2018-02-19 15:53
This is deffenatly an issue.

I almost think that as an admin the authorization system should not affect us as it limits what we can do to admins on the servers we run.

I had a workbench tonight that I couldn't smite with the devtool after unclaiming the land it was on i believe it was because the user had probably changed the authorization on the table. 

But we also have carts parked in bad places and duplicated carts left right and center we can't do anything about

**Comment by Geuthur** [comment] 2018-02-19 16:07
Yeah same Problem i have with carts the are bugged and i, cant remove it
With devtool 
And the server has 10-20 players ... so chaos is big

**Comment by ecoemmeck** [comment] 2018-02-20 02:54
we have 172 citizens and about 20-30 active players

**Comment by CompactDisc** [comment] 2018-02-20 16:16
Fixing this should be a high priority issue. It's been completely ruining servers. It's easy to put carts in a crucial location so nobody can pass anymore.

**Comment by MarjieAVolk** [comment] 2018-02-26 22:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3607

**Closed by MarjieAVolk** 2018-02-26 22:32 UTC
Labels: Suggestion
