### ISSUE TITLE
9.5 Staging 2179 - "System" admin commands get duplicated

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22852] opened 2021-12-20 15:39 UTC
Commands get duplicated easily, especially if you click from it into chat tab, they either duplicate next to each other or its like the list is appearing twice

![image](https://user-images.githubusercontent.com/61889138/146793436-f9d81105-eddd-411a-a810-4df3181a9e6f.png)

**Comment by Daniel-Magulado** [comment] 2021-12-31 10:08
Hi @MishkaFur 

Thank you for this report but we can't seem to reproduce this issue on 0.9.5 Staging-2189.
Could you check and verify that this issue still persists on your end?

Thank you.

**Comment by MishkaFur** [comment] 2022-01-02 15:44
Appears to be sorted in 2191

**Comment by D3nnis3n** [comment] 2022-07-18 10:01
Closing due to being resolved.

**Closed by D3nnis3n** 2022-07-18 10:01 UTC
Labels: Status: Needs Information
