### ISSUE TITLE
Workbench making hammering noise with only finished job

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10488] opened 2019-01-03 01:24 UTC
[Hammering noises]
![image](https://user-images.githubusercontent.com/431728/50620224-0bb63d80-0f4a-11e9-971b-9235b323614f.png)

**Comment by elfl0rd** [comment] 2019-01-03 05:58
Duplicate of #10402

**Comment by SeanAtr0n** [comment] 2019-01-16 21:42
separate issue

**Comment by SeanAtr0n** [comment] 2019-01-16 21:51
![image](https://user-images.githubusercontent.com/774628/51280945-de2fb200-1995-11e9-9c81-0d5b2161975d.png)
seems related to ^

**Comment by johnkslg** [comment] 2019-01-17 23:52
Can you help me sort this one out Sean? Since you were doing stuff with workorders recently.

**Closed** 2019-01-22 22:13 UTC
Labels: Medium Priority
