### ISSUE TITLE
[0.9.2.4] Ownership icons make minimap unusable on dense servers

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21061] opened 2021-03-23 04:23 UTC
When I checked out White Tiger today, I was a bit astonished by how cluttered the minimap in the capitol got:

![image](https://user-images.githubusercontent.com/964559/112092336-82a07680-8b54-11eb-9cd7-b89109ca86d6.png)

I checked the map display options and couldn't find a way to disable the player ownership orbs from displaying on the minimap (heck, how relevant are they for a minimap, rather than something you usually hover over?). It would be nice to be able to hide them from the map view, otherwise the minimap becomes rather unusable in dense areas.

**Comment by TwixterZ** [comment] 2021-03-23 09:50
@ThePiachu you may remove those by unselect "deeds" in map screen

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/748d516c-ebe6-436a-940d-0f5a9e7b8204)

Below is taken from White Tiger
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/99be93c7-ea08-4a9b-a31d-815d8a1049dd)

I will close this issue as working as intended

**Closed by TwixterZ** 2021-03-23 09:50 UTC

**Comment by ThePiachu** [comment] 2021-03-24 00:02
Thanks! Turns out there was an issue with map refresh that made it appear as if that option didn't do anything - #21071
