### ISSUE TITLE
USER ISSUE: Wooden Cart Likes to Fly

### ISSUE THREAD

**Issue by Darkrade** [StrangeLoopGames/EcoIssues#4635] opened 2018-02-16 11:02 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.Own a wooden cart
2.Leave cart 
3.Wait

**Expected behavior:**
Cart should just sit and await my return.

**Actual behavior:**
Gets thrown into the air.

**Comment by MarjieAVolk** [comment] 2018-02-16 23:49
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4249

**Closed by MarjieAVolk** 2018-02-16 23:49 UTC
