### ISSUE TITLE
Wooden cart's are broken!

### ISSUE THREAD

**Issue by Ermagain** [StrangeLoopGames/EcoIssues#22547] opened 2021-08-20 23:39 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.0 beta release-237

**Steps to Reproduce:**
1.

**Expected behavior:**
The cart's (small and normal) should move in all directions. Or any direction that I move.

**Actual behavior:**
It only moves forward and backwards, in a straight line.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. 100% vanilla.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Noneforu** [comment] 2021-08-21 22:29
They changed how the carts are controlled. It used to be realistic, now it drives like a car and what is the 'front' of that car is where you are looking.

**Comment by Daniel-Magulado** [comment] 2021-08-22 06:25
Hello @Ermagain 

Thank you for writing this report. There has been a couple of changes on how Wood Carts and similar vehicle works especially with the controls. To turn with your cart, move your camera to your desired path. I'll be closing this as this is not a bug and is intended.

**Closed by Daniel-Magulado** 2021-08-22 06:25 UTC
