### ISSUE TITLE
USER ISSUE: False flag

### ISSUE THREAD

**Issue by MACROSSBR** [StrangeLoopGames/EcoIssues#23507] opened 2022-10-20 18:43 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
Shift+running shoes+foward

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes, server modded

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-12-02 21:46
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23508

**Closed by D3nnis3n** 2022-12-02 21:46 UTC
