### ISSUE TITLE
FPS drop (to 10-12fps) after open a chest/stockpile (with many items) and it does not recover after closing till restarting the game.

### ISSUE THREAD

**Issue by Snakekill** [StrangeLoopGames/EcoIssues#7151] opened 2018-04-12 09:41 UTC
The problem occurs only when opening the boxes / stockpiles and it does not recover after closing till restarting the game.
Before that I have a fps of 80-90. But this makes the endgame unplayeable for me. Even if I have all settings on very low.

**Comment by MarjieAVolk** [comment] 2018-04-12 23:06
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/6319

**Comment by MarjieAVolk** [comment] 2018-05-15 00:46
In fact, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6319

**Closed by MarjieAVolk** 2018-05-15 00:46 UTC
Labels: High Priority, Optimization
