### ISSUE TITLE
Fishing bug where fish overwrite toolbar?

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#4437] opened 2018-02-13 04:32 UTC
http://steamcommunity.com/app/382310/discussions/4/1699416432430619785/

**Comment by VAlex0** [comment] 2018-02-17 20:57
hey craig, referenced all related issues to this one: #4588

have a good day! Alex

**Comment by MarjieAVolk** [comment] 2018-02-20 21:54
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

**Closed by MarjieAVolk** 2018-02-20 21:54 UTC
Labels: High Priority
