### ISSUE TITLE
[Bug] [6.4.1] User gets kicked if tries to repair RoadTool [duplicate of #3485]

### ISSUE THREAD

**Issue by kkusch** [StrangeLoopGames/EcoIssues#3555] opened 2018-01-20 20:47 UTC
As soon as one puts the roadtool inside the repair table, user will get kicked from server.
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on ToolbarInventory!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Skills.RequiresSkillAttribute.get_Description()
   at Eco.Gameplay.Components.RepairComponent.RepairSlotChanged(User user)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)
```

**Comment by Conchipedia** [comment] 2018-01-20 21:33
duplicate of

**Comment by TimmayTim** [comment] 2018-01-21 04:45
same issue 

Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Repair on RepairComponent!

Value cannot be null.
Parameter name: key


Stack:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Skills.Skillset.GetSkill(Type skillType)
   at Eco.Gameplay.Skills.RequiresSkillAttribute.IsMet(User user)
   at Eco.Gameplay.Components.RepairComponent.Repair(Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by MarjieAVolk** [comment] 2018-01-22 19:09
Duplicate of #3485 as stated above

Will be fixed in next staging build for sure, we're talking about whether to hotfix the current release.

**Closed by MarjieAVolk** 2018-01-22 19:09 UTC
