### ISSUE TITLE
Waypoint on map join gives weird information 6.2.0 #737b5d74 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3011] opened 2017-12-05 07:10 UTC
i placed a waypoint at my doorway
<img width="1280" alt="snap119" src="https://user-images.githubusercontent.com/29383891/33594176-c3791628-d98a-11e7-8e5d-138bc2253b9f.png">
then i stepped backwards across the join and waypoint disappears (actually it shows slightly on the left or right depending the slight angle i am)
<img width="1280" alt="snap120" src="https://user-images.githubusercontent.com/29383891/33594210-e9e6d53e-d98a-11e7-9079-c40992d6567b.png">
but then if i do 180 degree view the waypoint then tells me that my home is 997m away
<img width="1280" alt="snap121" src="https://user-images.githubusercontent.com/29383891/33594267-2ba2a73c-d98b-11e7-9c61-acd3564c3885.png">
Until i did this i hadn't really realised i was on a join (i don't often take note of co-ordinates unless i'm off gathering and need to find my way back)

**Comment by Conchipedia** [comment] 2017-12-05 07:14
i think this needs to show the "shortest route" but because of the join it just shows the "longest"

**Comment by Nanders** [comment] 2017-12-05 19:10
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2910 ?

**Comment by MarjieAVolk** [comment] 2017-12-05 19:25
Yep, closing as duplicate

**Closed by MarjieAVolk** 2017-12-05 19:25 UTC
