### ISSUE TITLE
Mesh issue [with video]

### ISSUE THREAD

**Issue by Mansitos** [StrangeLoopGames/EcoIssues#4383] opened 2018-02-12 12:15 UTC
**Version: 0.7.1.0 beta**

**Steps to Reproduce:**
Blocks placed like in the video 👍 

_**Watch the video:**_
[https://www.youtube.com/watch?v=IIXl4f2_ldk&feature=youtu.be](url)

**Expected behavior:**

**Actual behavior:**

**Comment by Nanders** [comment] 2018-02-12 18:11
Character controller is too tall. Although I think this is also a minor problem for artside as well.

**Comment by keegan-o** [comment] 2018-02-13 21:46
Video is a 404 link for me so will not know what this is about until described. But if it's about Road blocks, workin' on it!

**Comment by Mansitos** [comment] 2018-02-13 21:50
Sorry, try now:
(Yes is about that)

https://youtu.be/IIXl4f2_ldk

Il 13 feb 2018 10:46 PM, "keegan-o" <notifications@github.com> ha scritto:

**Comment by MarjieAVolk** [comment] 2018-02-13 22:06
Ah if it's roads, then we've got another bug for that.  Thought it was to do with the glass walls.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3582

**Closed by MarjieAVolk** 2018-02-13 22:06 UTC
Labels: Medium Priority
