### ISSUE TITLE
[0.9.0 beta staging 1695] Flying crop : tilled soil should be squarified (like road tool)

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17475] opened 2020-08-02 00:45 UTC
![image](https://user-images.githubusercontent.com/339611/89112883-18727e80-d46a-11ea-806c-d10631ba672e.png)

![image](https://user-images.githubusercontent.com/339611/89112892-3c35c480-d46a-11ea-93e6-fc2439e9af98.png)

To avoid that, I think using hoe should square the block.

**Comment by keegan-o** [comment] 2020-10-20 18:48
Duplicate of flying plants and terrain builders issue.

**Closed by keegan-o** 2020-10-20 18:48 UTC
Labels: Category: Gameplay
