### ISSUE TITLE
Can't convert eco linux mono to Windows eco server

### ISSUE THREAD

**Issue by quequiere** [StrangeLoopGames/EcoIssues#5168] opened 2018-02-27 07:26 UTC
Hello,
I started my server on linux with mono and I tried to transfert it on a windows server.

But when I start the eco windows server with my save created by mono I got this error

> Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Eco.Core.Serialization.EcoSerializer.Initialize()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] 

> 

Can someone explain to me how I can convert my data to be supported by windows ?

**Comment by quequiere** [comment] 2018-02-27 07:55
Ok, I solve the first part of this problem. But I got new errors, I will post them tonight (dont got the time now)
To solve the first error you need to go on the Eco storage then open the Game.eco like a ZIP.
Then open the file named "version".
You should see something like "2.2" you need to replace it by "2,2".

**Comment by quequiere** [comment] 2018-02-27 17:40
The new error is:

> Exception non gérée : System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.IO.EndOfStreamException: Impossible de lire au-delà de la fin du flux.
>    à System.IO.__Error.EndOfFile()
>    à System.IO.BinaryReader.FillBuffer(Int32 numBytes)
>    à System.IO.BinaryReader.ReadDouble()
>    à Eco.Core.Serialization.Serializers.DoubleSerializer.Decode(BinaryReader reader)
>    à Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
>    à Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
>    à Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
>    à Eco.Core.Serialization.DataStore.Load[T](String folder, Action`2 createFunc)
>    à Eco.Core.Plugins.StorageManager.CreateOrLoad[StorageType](String folder, Action`1 onCreate)
>    à Eco.Simulation.Time.TimePlugin..ctor()
>    --- Fin de la trace de la pile d'exception interne ---
>    à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    à System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    à System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>    à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    à System.Activator.CreateInstance(Type type, Object[] args)
>    à Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
>    à Eco.Server.PluginManager.<.ctor>b__10_1()
>    à System.Threading.Tasks.Task.Execute()
>    --- Fin de la trace de la pile d'exception interne ---
>    à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    à Eco.Server.PluginManager.<.ctor>b__10_0()
>    à System.Threading.Tasks.Task.Execute()
>    --- Fin de la trace de la pile d'exception interne ---
>    à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    à Eco.Server.PluginManager..ctor()
>    à Eco.Server.Startup.Start(String[] args)
>    à Eco.Server.MainClass.Main(String[] args)

**Comment by MarjieAVolk** [comment] 2018-02-27 17:55
Re the solution to your first problem - thanks, that will help us with this bug also: https://github.com/StrangeLoopGames/EcoIssues/issues/4305

It sounds like the second error is similar, a comma instead of a period somewhere else.  I'm guessing this is not an issue with converting from linux to windows, but rather with converting from one locale to another - probably English to French, given your stack traces.

**Comment by quequiere** [comment] 2018-02-27 18:18
Ok working propely on English system :) Thx !

**Comment by MarjieAVolk** [comment] 2018-02-27 18:21
Okay, closing as duplicate of #4305 since that worked.  Thanks for helping us figure it out!

**Closed by MarjieAVolk** 2018-02-27 18:21 UTC
Labels: Medium Priority

**Comment by quequiere** [comment] 2018-02-27 18:29
But now got the problem is that the server is online, but i can't connect on it. I'm stuck on "connecting ..." Then "connection failed".
Got no crash and no error

**Comment by MarjieAVolk** [comment] 2018-02-27 18:33
Noooooo lol

So how are you launching the server?  Via the game menu 'Load' option, or standalone?

**Comment by quequiere** [comment] 2018-02-27 18:35
You can errase this message ;) It's was just a stupid firewall problem ;)

**Comment by MarjieAVolk** [comment] 2018-02-27 18:35
Okay great, phew :)
