### ISSUE TITLE
USER ISSUE: Bug when picking up plants

### ISSUE THREAD

**Issue by meffie96** [StrangeLoopGames/EcoIssues#5791] opened 2018-03-09 19:49 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. My PC stopped working, and i had to reset it.
2. I loaded my last save and lost up to a minute of progress.
3. Before the restart, i had picked up some plants and when i try to pick up the plants again after loading the game again,this bug appeares.

**Expected behavior:**
Picked up the plants

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Cannot insert duplicate key in unique index '_id'. The duplicate value is '90'.


Stack:
   bei LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   bei LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   bei LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   bei LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   bei LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   bei LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   bei LiteDB.LiteCollection`1.Insert(T document)
   bei Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Gameplay.Plants.PlantEntity.TryHarvest(Player player, Boolean picked)
   bei Eco.Gameplay.Plants.InteractablePlantBlock.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-09 20:20
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5611

**Closed by MarjieAVolk** 2018-03-09 20:20 UTC

**Comment by MarjieAVolk** [comment] 2018-03-09 20:22
If this error is preventing you from playing, you can try disabling stat writes, which you can now do in the server window on Stats>Config tab.  You can open the server window using /openserverui
