### ISSUE TITLE
Tailings don't need sealing, just a roof > 10 blocks above

### ISSUE THREAD

**Issue by FishAus** [StrangeLoopGames/EcoIssues#5753] opened 2018-03-09 07:40 UTC
![tailings pollution](https://user-images.githubusercontent.com/35624562/37196078-7e28d1d8-23c9-11e8-9be6-6cd94f020cb4.png)

Image shows a stockpile on surface with no roof creating pollution (distance). Also a stockpile with a greater number of Tailings that had been there longer but has a simple structure creating a roof 13 blocks higher than the top of the Tailings in the stockpile. It is clearly not sealed, and it creates no pollution.

Feature to enable storage of tailings in surface silos?

**Comment by MarjieAVolk** [comment] 2018-03-09 19:47
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4992

**Closed by MarjieAVolk** 2018-03-09 19:47 UTC
