### ISSUE TITLE
Exception for user generated on Update loop

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [StrangeLoopGames/EcoIssues#5710] opened 2018-03-08 20:50 UTC
Generated 
World generated fresh 200 x 200
10 players joined one player triggered this error when trying to spin globe on minimap while its generating

The server started to have random things happening like chunks not generating, dsyncs, players getting stuck in loop

--BEGIN DUMP--
Dump Time
03/08/2018 20:14:41

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-08 22:41
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496.

7.2.3 hotfix should fix many of the desync and performance problems

**Closed by MarjieAVolk** 2018-03-08 22:41 UTC
