### ISSUE TITLE
USER ISSUE: Map don't load

### ISSUE THREAD

**Issue by MigzGit** [StrangeLoopGames/EcoIssues#6410] opened 2018-03-23 16:17 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Run in a direction where you do not usually go, a place not loaded.

**Expected behavior:**
Let the soil appear as you move in that direction.

**Actual behavior:**
The map does not download, the ground disappears, in fact everything disappears except the map behind us. If we contiue in the direction where it is "empty" we fall to infinity and we are forced to restart the game.

**Comment by MarjieAVolk** [comment] 2018-03-23 18:15
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5917

Does logging out and back in make the world load?

**Closed by MarjieAVolk** 2018-03-23 18:15 UTC
