### ISSUE TITLE
USER ISSUE: Logged onto a server as a different (new) character.

### ISSUE THREAD

**Issue by Coldroth** [StrangeLoopGames/EcoIssues#4039] opened 2018-02-07 15:16 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
- Disconnected from server
- Connected to same server

**Expected behavior:**
Connect to the server on my character.

**Actual behavior:**
Connected to the server on a new character that had my same name (Tobithiel) 
but with a '#2' added to it.

**Comment by Huntermeign** [comment] 2018-02-07 15:22
I noticed this as well with on of my users. I think it has to do with ur steam id and SLG id. When he logged in using the SLG client as opposed to steam he went back to his origional name, even though he used steam the first two times.

**Comment by Coldroth** [comment] 2018-02-07 15:35
I've deleted all game files and reinstalled.
On that particular server im still 'Tobithiel#2', but on other servers I'm 'Tobithiel'.

I guess I'll wait for more patches and fixes before I really get into eco again.
Hope they can pull it off in reasonable time.

**Comment by Conchipedia** [comment] 2018-02-07 20:49
looks the same as this Issue
Two Ingame Names appeared one for Steam and one for SLG #4045

**Comment by MarjieAVolk** [comment] 2018-02-07 22:31
Yes, that sounds like the same issue as that one.

Do you have an slg account?  And is it linked to your steam account?  Are you running from steam or downloading from our site?

If you are not seeing the issues on new servers, I would guess that you had a steam + slg account, and during the auth issues last night, your accounts got unlinked.  You may be able to access your other character by using steam or downloading from our website - whatever the opposite of what you are currently using is.

We are working on a better long term solution for this

**Comment by Coldroth** [comment] 2018-02-07 23:08
To clarify things: 
- I have an slg account that was linked to my steam account.

So far the issue happened on only one server.

I don't mind it though, as long as you'll fix it from happening again.

Keep at it and make a great and smooth game! ^^

Thanks for the replies!

**Comment by Coldroth** [comment] 2018-02-07 23:10
Ps: I was running the game from steam when the issue happened.

**Comment by MarjieAVolk** [comment] 2018-02-07 23:32
Okay, that definitely sounds like your accounts got unlinked.  We had some problems with linking slg & steam accounts, and a lot of people who had already linked got unlinked again.  We are still working some things out, so you can't re-link your accounts yet, so in the mean time you should be able to access your other character if you download the game from our website instead of running from steam.

Once we get our auth stuff all patched up, you can re-link your accounts to fix the problem.  Again, we are working on a better fix for this, this is just a workaround.

Closing this as a duplicate of the other bug

**Closed by MarjieAVolk** 2018-02-07 23:32 UTC
