### ISSUE TITLE
Can't do anything after log in a server

### ISSUE THREAD

**Issue by Blaireau37** [StrangeLoopGames/EcoIssues#25109] opened 2024-08-26 13:21 UTC
We are a group of friend playing on a server, all going fine and tonight, we got a bug with a stockpile or wheelbarrow around it. When you are in range of those stockpile/wheelbarrow, you get stuck in game. By stuck i mean, you can run but you can't use action bars, can't acces at anything in the world. You have to exit server, exit steam for complete shutdown of eco, relaunch game and maybe you will be able to do something. I try to move some block from this stock pile in my inventory, the value from the stockpile and my inv is different and now, i d'ont have those block on my inv anymore, i can't litteraly do anything, even with the deco/relaunch. I try to put those invisible block on an another far awar stockpile and now i can't acces to any stockpile. 
[Player-prev.log](https://github.com/user-attachments/files/16749092/Player-prev.log)
[Player.log](https://github.com/user-attachments/files/16749095/Player.log)

**Comment by Daniel-Magulado** [comment] 2024-08-28 18:47
Hi @Blaireau37 

Thank you for submitting this bug report.
However, we are unable to reproduce this issue.
Can you provide more information?
A recording video of the issue as it happens, before it happens too if you can reproduce it.
A copy of your world server save file for reproduction of the issue.

Thank you.

**Comment by D3nnis3n** [comment] 2024-09-04 19:56
Closing due to not being reproducible and no further information provided. Feel free to open a new issue once you can provide the requested information.

**Closed by D3nnis3n** 2024-09-04 19:56 UTC
Labels: Status: Needs Information
