### ISSUE TITLE
USER ISSUE: Sending Money doesnt work

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11573] opened 2019-03-05 03:10 UTC
**Version:** 0.8.0.5 beta

this only seems to happen in this late game stage on the server im playing on.
someone made a law that gave you money for a specific action, lots of actions have been done until the law was repealed days later, so lots of transactions were made.   
this may have crashed the money system somehow.  the transactions window doesnt show any new transactions anymore.
transfering money doenst work anymore
buying/selling over shops does work on the other hand.

**Steps to Reproduce on this specific server:**
Send someone Money over the Y - Make a transfer menu
(your currency or someone else's, doesnt matter)

**Expected behavior:**
money will be tranfered

**Actual behavior:**
no transfer happens.

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods, vanilla game, server with handful of players @ day 12.

theres no entry in your transactions list, aswell on the receiving players transactions list

Also the
"... and x more transactions" in the Transactions for "player xy" personal account cannot be accessed.
https://i.imgur.com/JFUvAPs.png
(its day 12 allready, the list is somehow stuck at 6d 1h)

**Comment by redwyre** [comment] 2019-03-05 15:25
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11501

Fixed in 0.8.0.6

**Comment by redwyre** [comment] 2019-03-05 15:25
Duplicate of #11501

**Closed by redwyre** 2019-03-05 15:25 UTC
