### ISSUE TITLE
USER ISSUE: The ground is not existing

### ISSUE THREAD

**Issue by MisterUU** [StrangeLoopGames/EcoIssues#5236] opened 2018-02-28 19:16 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
the ground is invisible and when i go in i infinity fall

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-28 19:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861

**Closed by MarjieAVolk** 2018-02-28 19:16 UTC
