### ISSUE TITLE
USER ISSUE: Cant interact with objects

### ISSUE THREAD

**Issue by Matej47** [StrangeLoopGames/EcoIssues#22055] opened 2021-06-01 22:05 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
After having game launched for a long time some entities start to not work properly, for example carts, doors, elevators. I cant interact with them, and hitboxes start work weirdly like falling trough elevator or cart get some ragdoll-looklike phisics, plus picking up rocs begin a bit harder to hit hitbox or cant even cut log of wood it just is there and move if i move into it.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment] 2021-06-02 04:32
Hi @Matej47, thanks for making a report regarding this issue. 

Unfortunately, we are not able to reproduce this.
Can you provide us with a recorded video of the issue as it happens and an approximate on how long have you left the game on? 
This will help us further investigate this issue and what's causing it.

Thank you.

**Comment by Matej47** [comment] 2021-06-03 21:52
Yes today it happened with 2 cart and excavator, i just remember it stopped working when excavator fell on side.

https://youtu.be/WXyanxQfCAQ

**Comment by SlayksWood** [comment] 2021-06-04 07:36
merged to #20414

**Closed by SlayksWood** 2021-06-04 07:36 UTC
Labels: Status: Needs Information
