### ISSUE TITLE
USER ISSUE: Fell off map

### ISSUE THREAD

**Issue by APinkGamer** [StrangeLoopGames/EcoIssues#4774] opened 2018-02-18 20:01 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Find a unloaded piece of the world.
2. Walk on it

**Expected behavior:**
Let me walk on it even though it didn't show up	

**Actual behavior:**
Made me fall through the map

**Comment by Naheulf** [comment] 2018-02-18 20:32
And TP on top if it's only a partial block.

**Comment by MarjieAVolk** [comment] 2018-02-20 22:06
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861

**Closed by MarjieAVolk** 2018-02-20 22:06 UTC
