### ISSUE TITLE
Server Dump: ClientUpdateException NullReferenceException

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [StrangeLoopGames/EcoIssues#6105] opened 2018-03-15 21:25 UTC
Version: 0.7.2.4 beta

Full Stack Trace:

Server Crush Dump: 

--BEGIN DUMP--
Dump Time
03/13/2018 23:48:56

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-15 21:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-15 21:40 UTC
