### ISSUE TITLE
Waterpump is invisible

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#11344] opened 2019-02-15 23:05 UTC
Currently on 8.1 master
![image](https://user-images.githubusercontent.com/35509188/52889043-1bbd6180-3133-11e9-9a28-a6ee4fb3b772.png)

**Comment by keegan-o** [comment] 2019-02-20 00:12
water pumps are being updated to include a mechanical version and an electric version, closing this as a duplicate of the critical bug for water pumps.

**Closed by keegan-o** 2019-02-20 00:12 UTC
Labels: High Priority
