### ISSUE TITLE
USER ISSUE: Unable to Move Linked Storage Up In List

### ISSUE THREAD

**Issue by Nornec** [StrangeLoopGames/EcoIssues#5281] opened 2018-03-02 00:12 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1) Look at the inventory of a stockpile
2) Try to drag the storage container for a Powered Cart up in the list

**Expected behavior:**
Dragged storage container should remain where dropped.

**Actual behavior:**
Storage container "snaps" back to its starting position. In this instance, it was at the bottom of the linked storage list and remained there when the drag was attempted.

**Comment by D3nnis3n** [comment] 2018-03-02 01:20
Don't think this is a bug. You need to make sure that the line at where you want to drop it is marked green, otherwise it snaps back. A bit enerving, but not a bug.

**Comment by MarjieAVolk** [comment] 2018-03-02 01:37
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5087

Had a couple people complain about it, so I'm planning to look into making it easier to use.

**Closed by MarjieAVolk** 2018-03-02 01:37 UTC
