### ISSUE TITLE
USER ISSUE: Unable to create world

### ISSUE THREAD

**Issue by Slothski** [StrangeLoopGames/EcoIssues#4008] opened 2018-02-06 23:57 UTC
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
1. Click New
2. Create game, (Happened with both generating new and keeping default)
3. fin

**Expected behavior:**
it should have put me into a world...

**Actual behavior:**
tabbed me out, put me back to main menu. I clicked load the world and it repeated the same

**Comment by Litschi123** [comment] 2018-02-07 01:11
Sounds like the same problem as https://github.com/StrangeLoopGames/EcoIssues/issues/3997

**Comment by MarjieAVolk** [comment] 2018-02-07 01:41
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3982

**Closed by MarjieAVolk** 2018-02-07 01:41 UTC
Labels: Medium Priority
