### ISSUE TITLE
USER ISSUE: Object Reference Bug

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#5646] opened 2018-03-08 02:19 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1. Walk through the desert.

**Expected behavior:**
It should have let me continue on my merry way.

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Object reference not set to an instance of an object


Stack:
  at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates (System.Collections.Generic.IEnumerable`1[T] newObjects, Eco.Shared.Networking.INetObjectViewer viewer, System.Collections.Generic.ICollection`1[T] monitored) [0x0001c] in <9b451c7cf73d4796af591ff0427a2c70>:0 
  at Eco.Plugins.Networking.Clients.Client.Update (System.Diagnostics.Stopwatch timer) [0x000b9] in <12df95ead3f14bad827b69c761f852fb>:0 
  at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1 () [0x00012] in <12df95ead3f14bad827b69c761f852fb>:0 
</size>
```

**Comment by AndyClausen** [comment] 2018-03-08 21:56
The exception means that the game is trying to access an object that's not there.

This could be caused by many things, both UI, visual game objects or even something in the game's engine.

What happens when you go to the same spot now?

**Comment by Blanclour** [comment] 2018-03-08 22:24
It only happens some times, it does not reliably occur every time.

**Comment by MarjieAVolk** [comment] 2018-03-08 22:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-08 22:40 UTC
