### ISSUE TITLE
Duplicate users not removed from currency system

### ISSUE THREAD

**Issue by Zenairo** [StrangeLoopGames/EcoIssues#4652] opened 2018-02-16 18:58 UTC
My user is Zenairo and the duplicate resulting from the steam issues was Zenairo#2, there is an issue with the fixes to the duplicate users where the currency (even if 0) for that user remains in the treasury. I have tried removing every piece of content with the duplicate users name from the server files in Game.eco but have had no luck, they just reappear. See attached.

![image](https://user-images.githubusercontent.com/13290213/36324167-8d8b62d4-1321-11e8-8c83-ba80e79664a5.png)

**Comment by Zenairo** [comment] 2018-02-16 18:59
Covered property name as it was my real address lol

**Comment by MarjieAVolk** [comment] 2018-02-17 00:06
Duplicate users are not currently deleted from the save at all.  We originally tried to delete them, but found this broke a lot of people's saves, and we don't yet have a full implementation of deleting a user.

If in your case, your #2 doesn't have anything on it (property, etc), then you can try to delete its file under Users.  The file name will be by the character's id (your steam id or slg id) rather than by its username.  Have you tried that yet?  As always, back up your save first though.

**Comment by Zenairo** [comment] 2018-02-17 01:06
I've deleted the file under users as well as any entries for Zenairo#2 in any of the Data files throughout the Game.eco directory. Would you like me to attach my Storage and Configs folders?

**Comment by MarjieAVolk** [comment] 2018-02-27 01:15
Closing as working as intended.  Deleting users is not really supported, so it might do weird things.

**Closed by MarjieAVolk** 2018-02-27 01:15 UTC
