### ISSUE TITLE
USER ISSUE: Bugged trees

### ISSUE THREAD

**Issue by 1337phreak** [StrangeLoopGames/EcoIssues#6830] opened 2018-04-01 08:08 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Two trees on different parts of the map have bugged causing the client to disconnect when chopping into logs or when picking up the logs from the bugged tree (after you reconnect)
The trees were felled by another player who left them on the ground. Server has been restarted since they were felled.

**Expected behavior:**
Not disconnect.

**Actual behavior:**
The following error message popped up:
```

When chopping felled tree into logs:

Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>

When picking up said log:

Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment] 2018-04-02 21:51
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-04-02 21:51 UTC
