### ISSUE TITLE
[0.9.0 Staging-1494] Upgrade Modules are a bit misnamed / out of whack

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15597] opened 2020-04-07 12:23 UTC
There is something up with the Upgrade Modules:

- Adv Masonry Table takes Modern Upgrades, but Adv Masonry Upgrade
- Cement Kiln takes Advanced Upgrades, but Modern Masonry Upgrade
- Smelting Upgrade requires Advanced Upgrade 4, same as Advanced Smelting Upgrade, even though you make it in a Bloomery, which only takes that and Basic Upgrade Modules

In general, the Module names are a bit clashing with names for various tables and skills. Would be nice to revise these a bit.

**Comment by SlayksWood** [comment] 2020-04-07 12:50
1. Used ModernUpgrade1-4 and AdvancedMasonry(this taken from specialty name)Upgrade, but it's crafted from ModernUpgrade4:
![image](https://user-images.githubusercontent.com/45708377/78670340-4396f800-78e6-11ea-97a2-7b15ab35e578.png)
So it's intended behavior.
2. All's right with balance, but I think we should rename ModernMasonryUpgrade to CementUpgrade or something like this. People confused. Or we should change and Advanced Masonry specialty should use ModernMasonryUpgrade and then rename this upgrade to Advanced.
3. Fixed in staging-1501
Revising will, but not now.

**Comment by Engimage** [comment] 2020-04-08 09:42
The confusion comes from the name of a specialty "Advanced Masonry" using the same word as an upgrade tier "Advanced Upgrade"

To remove the confusion I would suggest naming T5 upgrade as follows:
Modern Upgrade 5 (Advanced Masonry)
instead of "Advanced Masonry Upgrade"

This will help players understand what tier is the module straight away. Also it makes sense to move all specialty modules into their general tags like make Modern Upgrade 5 (Advanced Masonry) belong to the "Modern Upgrade" tag and get over with it, not bothering to filter those out for specific tables. Specific modules do already effect only recipes for their specialty only.

**Comment by mirasrael** [comment] 2020-04-08 10:18
I guess naming something like "Advanced Masonry Modern Upgrade" looks better. Also we need to change naming for all professional upgrades:
Masonry Basic Upgrade
Masonry Advanced Upgrade
Masonry Modern Upgrade
etc.

**Comment by Engimage** [comment] 2020-04-08 10:22
As I said having it like
Modern Upgrade 5 (Advanced Masonry)
will greatly help grouping up modules in the economy viewer. You should consider this. Also having a "5" in the name helps players understand the progression chain.

**Comment by WeaselDog** [comment] 2020-04-27 04:25
It is improved but this issue must be solved before it can be completely fixed: https://github.com/StrangeLoopGames/EcoIssues/issues/15964

**Comment by WeaselDog** [comment] 2020-05-04 16:24
Previous issue was fixed but now we need this one fixed before closing: https://github.com/StrangeLoopGames/EcoIssues/issues/16118

**Closed** 2020-05-06 06:09 UTC
Labels: Priority: Low, Week Task
