### ISSUE TITLE
Minimap gets resized all weird when zooming to a position

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8931] opened 2018-08-10 00:44 UTC
This happens the first time zooming to a position after recently opening/closing the settings panel.  It might also happen similarly after resizing or re-positioning the minimap window.  After this happens, the map image will be stretched or squished until the next time you resize or otherwise modify the window size.

It kind of looks like a unity internal bug, similar to the resizing issues we were seeing before, where a recttransform is mysteriously reset to a recent state.

**Comment by GophTheGreat** [comment] 2019-05-31 11:25
Could not reproduce. Closing.

**Closed by GophTheGreat** 2019-05-31 11:25 UTC
Labels: Medium Priority
