### ISSUE TITLE
Black screen only

### ISSUE THREAD

**Issue by mam241** [StrangeLoopGames/EcoIssues#3978] opened 2018-02-06 17:26 UTC
I have the identical system listed in this post: https://github.com/StrangeLoopGames/EcoIssues/issues/3903 
I turned all Anti Virus software off and re-downloaded and unzipped the game and still get the same result. A black scree, modified pointer and birds chirping but that's it.

**Comment by Nanders** [comment] 2018-02-06 19:27
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3903

**Comment by MarjieAVolk** [comment] 2018-02-06 22:13
Closing as duplicate

**Closed by MarjieAVolk** 2018-02-06 22:13 UTC
Labels: High Priority
