### ISSUE TITLE
World generation not always delivering playable world

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6401] opened 2018-03-23 07:38 UTC
From 5 generated worlds, 2 were rather unplayable due to

-Zero mushrooms (required for some skills)
-Zero elks (required for some skills)

Suggestion:
Add a "play-ability" check after the world generation, that checks if the basic needs are full-filled to have a good and fun experience with the generated world. And if that is not the case, re-generate the world. 
(And let the user know why it takes longer in the loading screen).

**Comment by MarjieAVolk** [comment] 2018-03-23 18:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Closed by MarjieAVolk** 2018-03-23 18:53 UTC
