### ISSUE TITLE
Crash in Server Browser

### ISSUE THREAD

**Issue by Soonergymnast** [StrangeLoopGames/EcoIssues#6821] opened 2018-03-31 22:41 UTC
Every time I try to join a server my game crashes. After it crashes I lose connection to my internet. 

Eco Version: 7.3.1

**Comment by H4nSolo** [comment] 2018-04-01 00:48
Steam version?
Starting Game with Administrator Rights?

**Comment by darkshad9999** [comment] 2018-04-01 08:04
Really give the devs a lot more than this to go on.. this is in no way a proper bug report 

What do you think a poor developer could do with a report like this by Soonergymnast
other than close it off as incomplete. 

What Operating System are you using.

This on Steam or did you download and register directly though
Strangeloop Games? 

What are the stats of the machine you are running? CPU, Memory 

you didn't even give the devs a dxdiag with all your system specs
to try and help troubleshoot the issue. 


How many different servers have you tried or are you trying just one server?

What was the exact error message that you were getting? 

Did you bother to take a screenshot of the error and post it here so the devs
could see it or at least put the error message you are getting here in this ticket.

I can tell you that I am running 0.7.3.1 Beta myself and I don't lose access to the 
internet.  Also the Internet is not crashing LOL 

With tickets like this if I was the developer of this game I would just close off 
complaints like this when the people don't even bother to give you any information
to go on. Come on people lets be smart and at least give the developers enough information
to try and troubleshoot the problem! 

I also work on the in the computer field and hate getting tickets like this where they 
give you nothing to go on as to what the problem is I am a trained Network Admin 
myself and have done deskside support and phone support as well in the past.

**Comment by Soonergymnast** [comment] 2018-04-01 14:28
I haven’t posted a lot of bug reports before. I apologize for not giving a lot of information because I don’t know what information to give. I don’t know what information is good and what is too much. I wasn’t trying to come across as being annoying I just don’t know what to report. I’m all that good with computers and I really don’t know what is going on. I didn’t say the internet was crashing I just said that I lose connection to it for a minute or two. I will get on my computer and look at all that info that you said I should give and make a better report. Sorry for any inconvenience.

**Comment by darkshad9999** [comment] 2018-04-02 18:57
To me this sounds more like a PC issue than an issue with the actual game itself.

**Comment by Dreepa** [comment] 2018-04-02 20:48
Same issue here. When ECO is polling the server list, or connecting to a server, the browser no longer is able to establish a connection up until the connection attempt ECO made is closed.

**Comment by MarjieAVolk** [comment] 2018-04-02 21:20
@Soonergymnast I assume the game is crashing to desktop?  Does it give any error messages?  And you say this happens when you click 'Connect' on a server listing?  Or does it happen while loading the Join window?

**Comment by Soonergymnast** [comment] 2018-04-02 23:04
@darkshad9999 I think so too. I had master reset my PC a while back because I couldn’t connect to the internet but it said I was connected. Same problem I’m having here. 

@Dreepa it’s ok. I unstand where he was coming from. I would be very annoyed if someone gave me little information to there problem. I was just posting this to see if I could get a quick response and see if anyone has fixed it. 

@MarjieAVolk So I just got on it to see if it would give me a error code and it didn’t. I loaded the game up and I can load a solo game, but right when I clicked on “join” to try any connect to a server, I couldn’t even click on “connect” before it stopped responding. A message came up saying “Eco.exe has stopped responding, please wait while we this this crash report to Microsoft”. 

That’s about it. If you need any information on my router or PC specs just let me know.

**Comment by MarjieAVolk** [comment] 2018-04-02 23:08
Okay great, so we've got a few reports of crashing while in the join screen over the weekend.  Time to start consolidating those.

This is kind of a crazy suggestion, but it's the only thing I've got so far - While these crashes were happening, did you have Windows Explorer open?  If so, can you try the same thing with Windows Explorer closed?

**Comment by Soonergymnast** [comment] 2018-04-03 01:39
I think I actually figured it out. Sadly it’s not an easy fix. I deleted my LocalLow file a long time ago when I didn’t know much about PC. SO now I need to figure out how to get it back.

**Comment by KlausT** [comment] 2018-04-03 04:31
Short summary:
0.7.2.5 worked
0.7.3.0 crashed last weekend
0.7.3.1 crashed last weekend

Some minutes ago I have tested it again:
0.7.3.1 doesn't crash now

I have not changed anything on my end.
Explorer window is open,
Chrome, Thunderbird, Hexchat and a lot of other stuff is still running in the background.

My idea:
It has something to do with the number of servers
Last weekend there were probably more servers online than now

**Comment by MarjieAVolk** [comment] 2018-04-03 20:38
Hmmm @KlausT yeah that would make sense, especially if the two of you both suddenly saw the problem go away.

**Comment by johnkslg** [comment] 2018-04-05 19:36
Negative review from this:
http://steamcommunity.com/profiles/76561198044857424/recommended/382310/#developer_response
![image](https://user-images.githubusercontent.com/3536496/38387814-000e024a-38ce-11e8-9826-341e49a14570.png)
****

**Comment by MarjieAVolk** [comment] 2018-05-08 01:50
Got confirmation this is fixed for another player in 7.4

**Closed by MarjieAVolk** 2018-05-08 01:50 UTC
Labels: Critical Priority, Steam Report
