### ISSUE TITLE
USER ISSUE: Sprung in der Luft

### ISSUE THREAD

**Issue by EiKiDa** [StrangeLoopGames/EcoIssues#23834] opened 2023-05-22 16:38 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
1. Von einer Anhöhe LAUFEN.
2. In der Luft SPRINGEN.

**Expected behavior:**
Man sollte weiter fallen.

**Actual behavior:**
Man erhält einen Sprung mitten in der Luft

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ohne Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-06-22 06:07
Thanks for the report.

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4021.
Very low priority, so unfortunately unlikely to being fixed anytime soon.

**Closed by D3nnis3n** 2023-06-22 06:07 UTC
