### ISSUE TITLE
[0.9.2 staging-1896] Client crash when try to create skill scroll with active tutorial.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19974] opened 2021-01-11 07:44 UTC
Step to reproduce:
- research any skill book:
![image](https://user-images.githubusercontent.com/45708377/104156033-61efce00-53f9-11eb-8b2f-e47f32774444.png)
- if you don't have any active tutorial then restart it:
![image](https://user-images.githubusercontent.com/45708377/104156064-6ddb9000-53f9-11eb-807b-7bfc760c61b7.png)
- press RMB to create skill scroll:
![image](https://user-images.githubusercontent.com/45708377/104156129-89469b00-53f9-11eb-904c-d34091684289.png)
- I have crash:
```
<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Tutorial.TutorialTasks.<>c__DisplayClass20_0.<TrySubscribeTutorials>b__3(User u)
   at Eco.Core.Utils.SubscriptionExtensions.<>c__DisplayClass5_0`1.<SubscribeAndTrack>b__0(T t)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.InventoryChangeSet.TryApply()
   at Eco.Gameplay.Items.Inventory.TryAddItem(Type itemType, User user)
   at Eco.Gameplay.Items.SkillBook.OnUsed(Player player, ItemStack itemStack)
   at Eco.Gameplay.Items.Inventory.UseStack(Player player, ItemStack stack)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```
[Book crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5794455/Book.crash.txt)

**Comment by Daniel-Magulado** [comment] 2021-01-12 08:32
Build: Staging
Repro: Unable to reproduce after following the repro steps. Appears to be fixed.

![Crash creating skill scroll.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/73d42d20-859f-407a-ac45-de3d0109dc09)

https://images.zenhubusercontent.com/47210472/98699de9-e1a1-42b4-a8f8-e2489112a37a/repro_steps.mp4

Resolution: Closing.

**Comment by tuha263** [comment] 2021-01-12 14:58
@Daniel-Magulado this still happen on staging if you did if before the Food tutorial
![FoodTur](https://user-images.githubusercontent.com/9598614/104331110-48e23c80-5521-11eb-9376-cf6aeec614ba.png)

**Comment by Daniel-Magulado** [comment] 2021-01-12 15:35
@tuha263 You're right. Thank you for catching that. Also happening on my end. After **Forage for Food** tutorial, it works as intended. But I'm not sure if it's the same. In the bug reported here, you need to make a scroll after obtaining a research book skill while having a tutorial. For this one, clicking order for the research skill book causes the crash.

Attached is a log file just in case it might help.

[https://app.zenhub.com/files/47210472/f6349169-52dc-475f-b775-a51c45a678a6/download](https://app.zenhub.com/files/47210472/f6349169-52dc-475f-b775-a51c45a678a6/download)

### Before Forage For Food Tutorial.
https://images.zenhubusercontent.com/47210472/30a72c54-15e7-4154-82e2-a8b5fe3cd46c/before_forage_for_food_tutorial.mp4

### After Forage For Food Tutorial.
https://images.zenhubusercontent.com/47210472/cfa6d7ea-682a-4c81-a7c1-8bf408083dcd/after_forage_for_food_tutorial.mp4

**Closed** 2021-01-14 08:48 UTC
Labels: Category: Gameplay, Priority: High, Squad: Mountain Goat, Status: Fixed
