### ISSUE TITLE
USER ISSUE: Door-Glitch

### ISSUE THREAD

**Issue by annoxoli** [StrangeLoopGames/EcoIssues#6278] opened 2018-03-19 16:27 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Build a House or what ever
2. Use a Door and build it.
3. stand before the closed door and open it

**Expected behavior:**
The door move me right/left from the door

**Actual behavior:**
It glitch me up - on sometimes i stuck in the wall / mountain etc.

**Comment by MarjieAVolk** [comment] 2018-03-19 19:15
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4140

**Closed by MarjieAVolk** 2018-03-19 19:15 UTC
