### ISSUE TITLE
USER ISSUE: Cant move after renaming chest

### ISSUE THREAD

**Issue by severnia** [StrangeLoopGames/EcoIssues#5094] opened 2018-02-25 20:45 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
In someone elses claim, where you have rights, rename a chest - cant move without disconnecting

**Expected behavior:**
Rename successfully and move	

**Actual behavior:**
Rename successfully and unable to move or do anything else

**Comment by MarjieAVolk** [comment] 2018-02-26 18:59
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

**Closed by MarjieAVolk** 2018-02-26 18:59 UTC
