### ISSUE TITLE
My cart deed looked like this.

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2537] opened 2017-10-13 18:46 UTC
The cart is nowhere to be found - and it doesn't display the location of my cart in any way that I can find.

![image](https://user-images.githubusercontent.com/609510/31561156-d8dde5b4-b00b-11e7-9452-717ac23f2f5f.png)
![image](https://user-images.githubusercontent.com/609510/31561204-fb0bc728-b00b-11e7-83db-fc73ae99951e.png)

**Comment by MarjieAVolk** [comment] 2017-10-14 00:04
We've both seen several problems with auth on server reload - ownership of deeds being given to other players, or to no one, etc

**Comment by MarjieAVolk** [comment] 2017-10-26 17:25
Gonna close this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2599 since I think we've confirmed that now

**Closed by MarjieAVolk** 2017-10-26 17:25 UTC
