### ISSUE TITLE
Object exception causing player to be dumped to menu

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6124] opened 2018-03-16 02:24 UTC
--BEGIN DUMP--
Dump Time
03/15/2018 20:46:55

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-20 22:33
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-20 22:33 UTC
