### ISSUE TITLE
USER ISSUE: logged in as wrong user

### ISSUE THREAD

**Issue by brandenthomas** [StrangeLoopGames/EcoIssues#5146] opened 2018-02-26 22:30 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
log into the game	

**Expected behavior:**
I am logged in as my user

**Actual behavior:**
I am logged in as blue

**Comment by MarjieAVolk** [comment] 2018-02-26 23:38
Is 'blue' the name of the person you logged in as?  Was this your first time on this server?  Had this server had 'require authentication' disabled, either at that time or previously?  Check /whoami while logged in, and see if those ids match your steam and/or Strange Loop account information.

**Comment by MarjieAVolk** [comment] 2018-02-26 23:47
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5150

**Closed by MarjieAVolk** 2018-02-26 23:47 UTC
