### ISSUE TITLE
[Art] Looking Through a Window makes all water invisible

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3747] opened 2018-01-31 22:05 UTC
**Version:** 0.7.0.0 beta staging-71fcbff4

![snap1474](https://user-images.githubusercontent.com/29383891/35650035-c7bc36e6-06d2-11e8-89b7-d8db191e3c49.png)
![snap1475](https://user-images.githubusercontent.com/29383891/35650036-c7daf6a8-06d2-11e8-8db7-143d8b2302a6.png)

**Comment by MarjieAVolk** [comment] 2018-01-31 22:11
I swear there was a duplicate of this bug, but can't find it

**Comment by Nanders** [comment] 2018-01-31 22:16
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3418

**Closed by Nanders** 2018-01-31 22:16 UTC
Labels: Medium Priority
