### ISSUE TITLE
USER ISSUE: Calories cannot be added to an order.

### ISSUE THREAD

**Issue by Sethur90** [StrangeLoopGames/EcoIssues#25082] opened 2024-08-20 02:43 UTC
**User Id: (a0f277fe-6cca-45e7-43f7-08dc8d11157e)**
**Version:** 0.11.0.1 beta release-702

**Steps to Reproduce:**
1. Start a work order at a table

**Expected behavior:**
Order should be started normally and the possibility to add calories should be given.

**Actual behavior:**
![Eco_bKtInjctXq](https://github.com/user-attachments/assets/c865c2f0-125e-4460-9aee-6939c40b8d80)
\
1. Every now and then the icon of the order does not match the order and simply becomes the icon of the campfire.
2. 1234 is the number of items to be crafted.
3. 13 sec seems to be the crafting time.
4. It permanently says “+50 cal labor” as text underneath.
5. The work order is not processed.

The only fix at the moment is a reconnect.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, I don't have any mods installed and I don't know if the problem exists with mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/16668095/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16668097/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-08-20 12:55
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24886

**Closed by D3nnis3n** 2024-08-20 12:55 UTC
