### ISSUE TITLE
Waterwheels as goto mechanical power

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#15868] opened 2020-04-19 00:29 UTC
Staging 1515

Waterwheels is very prevalent in the later builds of ECO, they are cheap and easy to place sources of mechanical power. They do however work even when not in contact with water, or even flowing water.

For players that expect a certain amount of immersion, they feel very out of place now.

Reproduce by placing them out of water.

**Comment by D3nnis3n** [comment] 2020-04-19 00:58
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2105

**Closed by D3nnis3n** 2020-04-19 00:58 UTC
