### ISSUE TITLE
Random crash while walking around

### ISSUE THREAD

**Issue by tyrope** [StrangeLoopGames/EcoIssues#1735] opened 2017-06-27 13:54 UTC
[Gist of the logfiles](https://gist.github.com/tyrope/f1bc78cd21522daedf068de2563d91e5)

**Comment by MarjieAVolk** [comment] 2017-08-04 18:48
Duplicate of StrangeLoopGames/EcoIssues#1734 - I copied your link over there

**Closed by MarjieAVolk** 2017-08-04 18:48 UTC
