### ISSUE TITLE
Server Crash: ClientNetworkException Exception

### ISSUE THREAD

**Issue by DrPeppiX** [StrangeLoopGames/EcoIssues#6363] opened 2018-03-22 10:40 UTC
--BEGIN DUMP--
Dump Time
03/21/2018 21:17:20

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC IsRelevant on Law!

Timeout. Database is locked for more than 00:01:00.

Stack:
   at LiteDB.LockService.Read()
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at Eco.Gameplay.LegislationSystem.LawLogic.Conditions.NumericComparisonCondition.IsMet(IPlayerAction action)
   at Eco.Gameplay.LegislationSystem.LawLogic.ControlFlow.LawControlFlowList.IsRelevant(IPlayerAction action)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-22 18:18
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343

This should be fixed in 7.3

**Closed by MarjieAVolk** 2018-03-22 18:18 UTC
