### ISSUE TITLE
Database locked up causing multiple crashes

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#5881] opened 2018-03-11 07:00 UTC
Servers keep crashing every few minutes with an error that the database has locked up:

--BEGIN DUMP--
Dump Time
03/10/2018 22:59:40

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   at LiteDB.LockService.Write()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Simulation.WorldLayers.WorldLayerStats.<>c__DisplayClass0_0.<CollectStats>b__0(Species species)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Simulation.WorldLayers.WorldLayerStats.CollectStats()
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

The only option that works to stop the crashing was to turn stats off

**Comment by pamduncan** [comment] 2018-03-12 05:14
Just as an update to this.  We hand quite a few servers - all ones with worlds over 140X140 and good sized population with lots of claimed land experience this crashinga nd the crashes all coincided with times the auto-save happened.  The trace was the same on all servers/crashes.  Changing compression or 'best speed' and disabling stats has been the work around that stopped the crashing.  Re-enabling stats with best speed set worked if there were no or very few players on the world and not much happening.  Once the active number of players increase the crashes started happening and so deabling stats was done again.  All servers that were crashing like this have been up now without crashing now for many hours.  lag spikes are occuring around auto-save but the server stays up.

**Comment by Yorkforce** [comment] 2018-03-12 15:22
We have had 16 of these crashes in the last 2 days

Can you clarify what you mean by 'best speed'?

**Comment by MarjieAVolk** [comment] 2018-03-12 17:37
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343, thanks for the additional info.

**Closed by MarjieAVolk** 2018-03-12 17:37 UTC
