### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Geuthur** [StrangeLoopGames/EcoIssues#4531] opened 2018-02-14 17:49 UTC
![screenshot_15](https://user-images.githubusercontent.com/761682/36219444-b90cc490-11b7-11e8-8daa-f6f17859d90d.png)

Server Crashes with this error hope it helps
For fixing it

**Comment by MarjieAVolk** [comment] 2018-02-14 21:10
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368

**Closed by MarjieAVolk** 2018-02-14 21:10 UTC
