### ISSUE TITLE
USER ISSUE: loss of graphics ingame

### ISSUE THREAD

**Issue by dingle666** [StrangeLoopGames/EcoIssues#4710] opened 2018-02-17 14:52 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
walking pulling large cart over an artea of the map	

**Expected behavior:**
i should be able to see the game enviroment normally

**Actual behavior:**
screen goes black but i can see a blurred view of the sun and i can still walk around but have no idea where im going - i have to relog to resolve

**Comment by NathanWheeler** [comment] 2018-02-18 21:36
This seems to be happening as you pull a cart across a property line, entering or leaving, but not consistently. Screen always flickers a bit as you cross property lines. Same type of thing happens with the excavator as you cross property lines, but with the excavator, it seems to just disappear completely, kicking the player off and returning the normal toolbars. If you were digging when this happens, it locks the view rotation of the player so that you're stuck looking whatever direction you were looking until you spawn a new excavator (NOTE: Logging out and back in does not fix this). Building a new excavator could prove to be extremely difficult if your workstation happens to be on the side of a room where it would be behind you.

**Comment by MarjieAVolk** [comment] 2018-02-20 21:48
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4370

**Closed by MarjieAVolk** 2018-02-20 21:48 UTC
