### ISSUE TITLE
Possibility to reference to amount of elections of a title

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17445] opened 2020-07-31 18:09 UTC
- In Elected Titles: Making the Vice-President requiring to not have been elected President twice
- In Laws: Paying someone that has been elected and is now out of office with a pension

**Comment by johnkslg** [comment] 2020-07-31 23:17
There are some stats with term limits, did you try those?

**Comment by WeaselDog** [comment] 2020-09-18 06:10
Duplicate of https://github.com/strangeloopgames/ecoissues/issues/14182

**Closed by WeaselDog** 2020-09-18 06:10 UTC
Labels: Category: Laws, Priority: Medium
