### ISSUE TITLE
Irritating roads

### ISSUE THREAD

**Issue by ChrisIds** [StrangeLoopGames/EcoIssues#5570] opened 2018-03-07 12:08 UTC
So, I just wanted to say that you should fix it so that roads are no higher than normal blocks!
I tried to make a road into my storage mountain which is connected to my smith's house, there is just one problem.. i can barely get the cart out from there, because the ramp is higher and my cart makes me stop.
This also happens in the dooropening, where we cannot use roads at all, because it's too high and we will stop at the doorframe..
Please do something about this! Would be awesome to lay roads everywhere and not only where it fits.
I need nice roads in my land!

**Comment by MarjieAVolk** [comment] 2018-03-08 00:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3582

**Closed by MarjieAVolk** 2018-03-08 00:53 UTC
