### ISSUE TITLE
USER ISSUE: Fishing 

### ISSUE THREAD

**Issue by hoiikmaak** [StrangeLoopGames/EcoIssues#4447] opened 2018-02-13 14:16 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. Start fishing works fine.
2. When catching a fish the fish is realy glitchy when pulling in.
3. When you get the fish in your inventory it turns invisible.
4. After disconnect and connect it is fixed

**Expected behavior:**
1. The fish should act normal and not flying around.
2. Fish is extual in inventory

**Actual behavior:**
You can't see the fish in your inventory.
Fishy is flying like a mad man.

**Comment by VAlex0** [comment] 2018-02-17 20:56
-> see #4588

**Comment by MarjieAVolk** [comment] 2018-02-20 21:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

**Closed by MarjieAVolk** 2018-02-20 21:53 UTC
Labels: Medium Priority
