### ISSUE TITLE
White Tiger Crash after Autorestart - not coming up

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17476] opened 2020-08-02 01:38 UTC
[03:30:07.842] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[03:30:07.856] [1] [ Info] [Eco] [Eco Server 0.9.0.0 beta staging-1695]
 
[03:30:08.058] [4] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[03:30:08.058] [4] [ Info] [Eco] [Server Initialization]...  
[03:30:08.520] [4] [ Info] [Eco] Starting LocalizationPlugin...  
[03:30:08.639] [4] [ Info] [Eco] Loading mods...  
[03:30:23.682] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[03:30:23.754] [4] [ Info] [Eco] Loading mods... Finished in 15,115.3ms
 
[03:30:23.754] [4] [ Info] [Eco] Starting ModKitPlugin...  
[03:30:23.754] [4] [ Info] [Eco] Initializing Simulation Types...  
[03:30:23.913] [4] [ Info] [Eco] Starting NetworkManager...  
[03:30:23.934] [4] [ Info] [Eco] Starting BackupPlugin...  
[03:30:24.361] [4] [ Info] [Eco] Initializing items...  
[03:30:24.378] [4] [ Info] [Eco] Starting WorldGeneratorPlugin...  
[03:30:26.423] [4] [ Info] [Eco] Starting StorageManager...  
[03:30:26.423] [4] [ Info] [Eco] Loading GameData...  
[03:30:26.477] [4] [ Info] [Eco] Starting GameDataPlugin...  
[03:30:26.477] [4] [ Info] [Eco] Loading Pause...  
[03:30:26.519] [4] [ Info] [Eco] Starting Stats...  
[03:30:26.519] [4] [ Info] [Eco] Starting PausePlugin...  
[03:30:28.088] [4] [ Info] [Eco] Initializing skills...  
[03:30:28.127] [4] [ Info] [Eco] Starting DifficultySettings...  
[03:30:28.149] [4] [ Info] [Eco] Loading World...  
[03:30:34.212] [4] [ Info] [Eco] Initializing world...  
[03:30:34.379] [4] [ Info] [Eco] Starting WorldPlugin...  
[03:30:34.379] [4] [ Info] [Eco] Loading Time...  
[03:30:34.379] [4] [ Info] [Eco] Starting TimePlugin...  
[03:30:34.379] [4] [ Info] [Eco] Loading Reputation...  
[03:30:34.379] [4] [ Info] [Eco] Starting ReputationPlugin...  
[03:30:34.379] [4] [ Info] [Eco] Starting PlayerHousingManager...  
[03:30:34.415] [4] [ Info] [Eco] Loading Users...  
[03:30:34.560] [4] [ Info] [Eco] Initializing inventories...  
[03:30:34.591] [4] [ Info] [Eco] Starting UserManager...  
[03:30:34.591] [4] [ Info] [Eco] Loading Objects...  
[03:30:34.623] [4] [ Info] [Eco] Starting EcoObjectManager...  
[03:30:34.623] [4] [ Info] [Eco] Starting DataExporter...  
[03:30:34.623] [4] [ Info] [Eco] Loading Garbage...  
[03:30:34.629] [4] [ Info] [Eco] Starting GarbagePlugin...  
[03:30:34.649] [4] [ Info] [Eco] Starting VoiceManager...  
[03:30:34.649] [4] [ Info] [Eco] Loading EconomyManager...  
[03:30:34.724] [4] [ Info] [Eco] Starting EconomyPlugin...  
[03:30:34.724] [4] [ Info] [Eco] Loading Disasters...  
[03:30:34.724] [4] [ Info] [Eco] Loading ViewTypeData...  
[03:30:34.724] [4] [ Info] [Eco] Starting DisasterPlugin...  
[03:30:34.724] [4] [ Info] [Eco] Loading Chat...  
[03:30:36.371] [4] [ Info] [Eco] Starting ChatServer...  
[03:30:36.371] [4] [ Info] [Eco] Loading Property...  
[03:30:37.161] [4] [ Info] [Eco] Starting ControllerManager...  
[03:30:37.542] [4] [ Info] [Eco] Starting PropertyManager...  
[03:30:37.542] [4] [ Info] [Eco] Starting MinimapManager...  
[03:30:37.599] [4] [ Info] [Eco] Loading Plants...  
[03:30:38.540] [4] [ Info] [Eco] Initializing plants...  
[03:30:44.736] [4] [ Info] [Eco] Starting EcoSim...  
[03:30:44.736] [4] [ Info] [Eco] Loading RouteProbing...  
[03:30:46.190] [4] [ Info] [Eco] Starting RouteProbingPlugin...  
[03:30:46.190] [4] [ Info] [Eco] Loading Layers...  
[03:30:46.418] [4] [ Info] [Eco] Initializing world layers...  
[03:30:46.418] [4] [ Info] [Eco] Loading ClimateSim...  
[03:30:54.316] [4] [ Info] [Eco] Starting WorldLayerManager...  
[03:30:54.316] [4] [ Info] [Eco] Starting EconomyTracker...  
[03:30:54.316] [4] [ Info] [Eco] Starting UserTracker...  
[03:30:54.333] [4] [ Info] [Eco] Loading Civics...  
[03:30:54.382] [4] [ Info] [Eco] Starting CivicsPlugin...  
[03:30:54.548] [4] [ Info] [Eco] Loading WorldObjects...  
[03:30:54.625] [4] [ Info] [Eco] Starting WorldObjectManager...  
[03:30:54.625] [4] [ Info] [Eco] Loading Rooms...  
[03:30:54.625] [4] [ Info] [Eco] Starting RoomPlugin...  
[03:30:54.643] [4] [ Info] [Eco] Loading Objectives...  
[03:30:54.643] [4] [ Info] [Eco] Starting ObjectivePlugin...  
[03:30:54.643] [4] [ Info] [Eco] Loading Sleep...  
[03:30:54.643] [4] [ Info] [Eco] Starting SleepPlugin...  
[03:30:54.643] [4] [ Info] [Eco] Starting WebServerPlugin...  
[03:30:54.643] [4] [ Info] [Eco] Starting IntegrationTestsPlugin...  
[03:30:54.673] [4] [ Info] [Eco] Initializing registrars for CivicsPlugin...  
[03:30:54.699] [4] [ Info] [Eco] Initializing registrars for GameDataPlugin...  
[03:30:54.706] [4] [ Info] [Eco] Initializing registrars for EconomyPlugin...  
[03:30:54.743] [37] [Error] [Eco] Missing reference Eco.Gameplay.Civics.Titles.AppointedTitle:16 wasn't added to the collection. It will be ignored, but may cause inconsistency and errors in other entities.
 
[03:30:54.743] [4] [ Info] [Eco] [Server Initialization]... Finished in 46,688.2ms
 
[03:30:54.753] [37] [Error] [Eco] Failed to load server, Exception was Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'key')
Source:System.Collections.Immutable

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
   at Eco.Core.Utils.ThreadSafeDictionary`2.<>c__DisplayClass22_0.<Add>b__0(ImmutableDictionary`2 x)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ThreadSafeDictionary`2.Add(TKey key, TValue value)

**Comment by D3nnis3n** [comment] 2020-08-02 01:42
Save: https://download.godsofwar.de/eco/wtcrashed2.zip

**Comment by Hiroyugane** [comment] 2020-08-02 15:00
Looked for clues regarding AppointedTitle:16 and looked up Chat/Data. 
The section of the whole chat in which AppointedTitle:16 is found is in the attached file (made readable). There are 5 Occurences.
Every mention was at least between 3:46pm - 5:36pm CEST - the last backup that is in working condition is from 4:26pm. It's probable that it happened between the 4:26pm-backup (working) and the 5:26-backup (not working/crashing). 

What Nibbly told us (quote): 
> I just went to the registar? or whatever in the capital and i made it on accident
> it was originally called ministers [renamed to "super cool people"] and only had (hiro?) in it
> I renamed it, maybe that has something to do with it
> I created the title and put Hiro in it
> I originally planned to have us both in it but I didn't realize that the person that created it wasn't in it :)
> i don't think ice was in it i think there were only the two
> but after renaming it and mentioning it in chat so it highlighted i deleted it
> maybe it was because it was mentioned then deleted? or the rename broke it?
> Hmmmmm. I think that I deleted it at the desk? I don't recall deleting it via the mention being possible but not 100% sure

The exact occurences are [Tick1, Line7, 3x], [Tick6, Line51, 1x], [Tick32, Line372, 1x] 

[ChatData-Highlighted-withoutBrackets.log](https://github.com/StrangeLoopGames/EcoIssues/files/5012319/ChatData-Highlighted-withoutBrackets.log)
[ChatData-Highlighted.log](https://github.com/StrangeLoopGames/EcoIssues/files/5012320/ChatData-Highlighted.log)

**Comment by gzatravkin** [comment] 2020-08-02 19:49
Looks like some desync in data (maybe caused by actions during save operation).
Deserializer was working on WageManager.TimedSet<IWageEarningGroup> Groups. Which acording EnumerableSerializer contains entry.Id == 16. 

But there are no element with id 16. Registrar contained element with id 15 instead (which was not present in EnumberableSerializer). 

So maybe it serialized WageManager and Registrar<Title> before and after renaming, which caused desync in data

**Comment by WeaselDog** [comment] 2020-08-03 05:01
Source account invalid error is caused by pressing "Advanced Settings" in registrar and then not selecting a bank account. We need a seperate fix for this. It is possible this is related to the Registrar, but having this error does is not enough to replicate it on local.

**Comment by mirasrael** [comment] 2020-08-03 06:15
Technically this crash already fixed in `develop` branch, but we need to investigate how we get to this condition. Seems it related to title renaming which probably causes reassigning ID to entity.

**Comment by mirasrael** [comment] 2020-08-03 09:00
Yeah, from log analyze now I can see it was removed. Previously it was possible to remove title without updating wages. In `develop` branch it was fixed. So assume this issue already fixed, just needs latest updates.

**Comment by mirasrael** [comment] 2020-08-03 09:05
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/17399

**Closed** 2020-08-05 11:31 UTC
Labels: Priority: Critical, Priority: High, Status: Investigate
