### ISSUE TITLE
[9.3.6] Irrelevant block lowering room tier

### ISSUE THREAD

**Issue by ChickenHacker1** [StrangeLoopGames/EcoIssues#22535] opened 2021-08-17 03:11 UTC
We've got a block here that has no right lowering the room tier, but sure enough it does! Makes no sense.

I saved a copy of the world in this moment, if it's needed for a proper diagnosis.

![Screenshot (120)](https://user-images.githubusercontent.com/80280848/129657758-996fc475-d704-4ced-abf4-de4b9f9bdf68.png)
![Screenshot (121)](https://user-images.githubusercontent.com/80280848/129657762-bcc4ff8d-970a-41a0-9f80-0c22af0e7fd3.png)

**Comment by Daniel-Magulado** [comment] 2021-08-17 06:34
Hi @ChickenHacker1 

Is this a locally hosted server or one of our official servers?
From the looks of it, that block separates one room into two and this is based on the amount of room volume deducted from the room you are in. If you're hosting this server, mind inviting me in so I can check further? Otherwise, you can share the saved file of that world and we can investigate it from there.

**Comment by ChickenHacker1** [comment] 2021-08-17 10:43
@Daniel-Magulado It is not official, just something we run for fun. It shouldn't technically separate the room, since removing it looks like it just opens up a 2x1 gap with a room at tier .96. Yet, removing it raises the room tier to 1. You can join at any time, 198.71.48.41:3000. The room is actually right next to spawn at 969,66,278. You can DM me in discord if you want me to be there to give you admin privileges, chickenclucker#0968

**Comment by Daniel-Magulado** [comment] 2021-08-18 08:08
Hi @ChickenHacker1 

I checked the area and I kind of have an idea what's going on. Mind giving me admin privileges so I can do some further test? I tried to add you on Discord but something seems to be wrong as I can't proceed to add you. You can, however, add me instead Nielzx#6566

**Comment by ChickenHacker1** [comment] 2021-08-18 14:28
@Daniel-Magulado 

I've added you as admin and added you in discord. Please keep me updated with your findings and I appreciate you looking into this.

**Comment by Daniel-Magulado** [comment] 2021-08-19 07:23
Hi @ChickenHacker1 

Thanks for making me an admin. However, I checked again today and I can't test the area since I don't have access to The Cubic Office property. As much as possible, I do not want to make any changes in your world. So I would be requesting access to the property from you. Once test is done and I can confirm the issue, I'll leave the property.

**Comment by ChickenHacker1** [comment] 2021-08-21 16:47
Hi @Daniel-Magulado ,

Sorry I've been a bit distracted the last few days with the 9.4 update. You are added to access the land claim now.

**Comment by Daniel-Magulado** [comment] 2021-08-22 06:15
Hi @ChickenHacker1 

Great, thank you. I'll be checking it today. One of the key features of 0.9.4 is how we implemented a new tooltip for room recognition. This will help determine what's wrong.

**Comment by Daniel-Magulado** [comment] 2021-08-22 12:40
Hi @ChickenHacker1 

Alright, I figured out what's wrong. The culprit here that causes the tier level of the room to decrease is the stairs.
![image](https://user-images.githubusercontent.com/77248866/130355248-0007a1d0-9811-4371-9de4-ceda9e3b5755.png)
Basically, once you place the blocks on the area of the issue;
![image](https://user-images.githubusercontent.com/77248866/130355096-8f6d14d3-d3ce-4b7f-bf38-a8f266be3c80.png)
this satisfies the condition of a room. This then separates the courtroom from the room that has the two carpentry tables in it resulting in 2 separate rooms. Because the whole building itself houses 3 rooms, the wall in the middle now is considered as a wall that separates the rooms from each other.

The lack of a base block to connect each stair block to one another causes the tier of both rooms to decrease.
This is by far still considered as a wall thus the reason why the rooms are created but it's a wall with missing blocks. Thus, the reason why the room indicates "Missing Corner Block".

Now observe the Tier level of the Courtroom here:
![image](https://user-images.githubusercontent.com/77248866/130355423-5516187c-dc63-40c2-ba86-a8096d4f82a6.png)


And observe the Tier level of the accepting room here:
![image](https://user-images.githubusercontent.com/77248866/130355437-9c5e6564-5408-4d5b-9fe3-924266d0f1dd.png)


Now, observe the tier value once I fill out the stairs with blocks.
![image](https://user-images.githubusercontent.com/77248866/130355480-bea23f9a-3fb0-40c4-acb2-1887d805c5b6.png)

![image](https://user-images.githubusercontent.com/77248866/130355490-9d3becf7-427a-4688-a41a-744f0fb7548a.png)

I hope I was clear and understandable. And I also hoped that I was of help to you. Let me know if you have any questions or if there's anything else I can do for you.

I'll be closing this ticket as the issue is intended and by design.

**Closed** 2021-08-22 12:42 UTC
Labels: Status: Investigate
