### ISSUE TITLE
USER ISSUE: Loss of veggies in Inventory (SP - Bleeding Edge)

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#11023] opened 2019-02-02 04:43 UTC
**Version:** 0.8.0.0 beta staging-1785734b-2

**Steps to Reproduce:**
Started new, local world.  Collected veggies to cook.  Had to log-out and back in.  Appears auto save did not kick in at the moment of log-out.  When I logged back in, all my tomatoes, corn and ferns were gone.  Only beans, berries and single pumpkin remained.  Seeds also remained.

**Expected behavior:**
Expected inventory to remain after re-log

**Actual behavior:**
Veggies dissappeared.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Veggies dissappeared.

**Comment by metachronism** [comment] 2019-02-04 19:50
dupe of other save issues - verify server 'exit' command used to close server saves state

**Comment by beastyn** [comment] 2019-04-30 09:06
Didn't meet in 0.8.1.4

**Closed by beastyn** 2019-04-30 09:06 UTC
Labels: Investigate
