### ISSUE TITLE
USER ISSUE: Disappearing property of a registered player

### ISSUE THREAD

**Issue by SERGZV** [StrangeLoopGames/EcoIssues#23039] opened 2022-03-06 10:33 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
1) Claim the territory.
2) Write a player in it
3) This person must place a chest or cart on your territory and put some things in it
4) Discharge a person from the territory and things belonging to him with all the contents will disappear from your territory to nowhere.

**Expected behavior:**
I think that either the player's things should be transferred to me. Either they should remain in his possession on my territory, but certainly not disappear into nowhere.

**Actual behavior:**
When I write out a person from the property, all his things disappear. Carts, chests... from my property. As far as I'm concerned this is a bug. But if this is such a feature. Then in this way I can put the waste in the carts belonging to the player being issued and thus get rid of the pollution. This was definitely not planned.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
There are no mods. We play on our server together.

**Comment by TwixterZ** [comment] 2022-03-07 00:51
@SERGZV thank you for raising this issue to us, to help us understand this issue better please help to clarify what do you mean by "Write a player in it"? Did you invite other player as a resident or did you give another player authorization to your deed?

IF its an invitation as a resident, then this is working as intended as all their belonging will be moved into Void Storage (bottom right, see SLG logo) 
![image](https://user-images.githubusercontent.com/78054747/156950235-92e51161-531f-4a3c-8a69-7835f8a8ab01.png)

do note, things like tailings will not be moved into void storage.

**Comment by D3nnis3n** [comment] 2022-07-18 10:14
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)

If you ejected a person from residency all the things the person placed go to their void storage, which is intended behaviour, as TwixterZ already mentioned.

**Closed by D3nnis3n** 2022-07-18 10:14 UTC
Labels: Status: Needs Information
