### ISSUE TITLE
USER ISSUE: Ground Bug

### ISSUE THREAD

**Issue by Kurnathral** [StrangeLoopGames/EcoIssues#4930] opened 2018-02-22 03:38 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I spawned at a Beach, so i claimed ground and tried to flatten the ground. While moving dirt from the center to the beach, the ground bugged

**Expected behavior:**
Gone away	

**Actual behavior:**
The ground is physically away but the texture is still there, and doesnt goes away. At the sides you can look through the map, and when you place something in it its behind the dirt texture. Plus flying gras

**Comment by Kurnathral** [comment] 2018-02-22 03:39
![20180222043907_1](https://user-images.githubusercontent.com/36720739/36519177-606c1d26-178a-11e8-9f87-c5d1e131af37.jpg)

**Comment by MarjieAVolk** [comment] 2018-02-23 00:03
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3897

**Closed by MarjieAVolk** 2018-02-23 00:03 UTC
