### ISSUE TITLE
USER ISSUE: Stone ramp can be digged with an iron shovel, but stone road can not be

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#11620] opened 2019-03-10 03:38 UTC
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
1. Equip a shovel
2. Dig up a piece of a stone ramp
3. Receive 1 stone road segment

**Expected behavior:**
It should have be undiggable, but breakable by hammer

**Actual behavior:**
Instead it digs it

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead it digs it

**Comment by HetNeSS** [comment] 2019-03-10 04:56
![20190310083652_1](https://user-images.githubusercontent.com/18286472/54080830-bc5e0600-431a-11e9-9cd3-0875f30a9dfa.jpg)

![20190310083650_1](https://user-images.githubusercontent.com/18286472/54080831-be27c980-431a-11e9-82be-33158a061a51.jpg)

**Comment by D3nnis3n** [comment] 2019-03-11 11:45
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11384

**Closed by D3nnis3n** 2019-03-11 11:45 UTC
