### ISSUE TITLE
Empty handed take doesn't do anything on mini stockpile

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10486] opened 2019-01-03 01:14 UTC
![image](https://user-images.githubusercontent.com/431728/50620018-b9285180-0f48-11e9-90ec-aeaaff7e2e8c.png)

**Comment by D3nnis3n** [comment] 2019-01-07 05:54
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10374?

**Comment by Quadbro** [comment] 2019-01-07 07:06
yeah, see the problem with carried items only, and yes, its related to that issue

**Closed** 2019-01-07 18:52 UTC
Labels: Fixed
