### ISSUE TITLE
USER ISSUE: Housing skill point reduction

### ISSUE THREAD

**Issue by DrCarsonBeckett** [StrangeLoopGames/EcoIssues#8276] opened 2018-07-02 14:26 UTC
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Build a home and after that change the windows from hewnlog to framed glass as an example.

**Expected behavior:**
The skillpoints for housing should be the same or even increased due the higher tier materials used.

**Actual behavior:**
The skillpoints were decreased from 80 to 34. No matter what I do I dont get the points back. Thats super annoying and totally destroying the fun.
That happend on different servers now. Theres even a topic but no one cares:
http://ecoforum.strangeloopgames.com:4567/topic/4685/massive-drop-in-skill-point-from-housing/2

Best regards

**Comment by DrCarsonBeckett** [comment] 2018-07-14 10:20
When is it going to be fixed?!

**Comment by GophTheGreat** [comment] 2019-05-24 04:53
Can't reproduce -- skill points go up as expected. Closing.

**Closed by GophTheGreat** 2019-05-24 04:53 UTC
Labels: Medium Priority
