### ISSUE TITLE
USER ISSUE: No Rice, Crimini Mushrooms or Camas Bulb

### ISSUE THREAD

**Issue by kathomm27** [StrangeLoopGames/EcoIssues#6945] opened 2018-04-03 23:06 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
As I move through my game I am trying to build on skills and so far I have been missing Rice - Crimini Mushrooms and Camas Bulbs. I have looked for hours for these items and tried to display them on my map and the map shows they do not exist in my world. 

**Expected behavior:**
I should be able to look on the map or in the world and find these items. 

**Actual behavior:**
They dont exist in my world.

**Comment by MarjieAVolk** [comment] 2018-04-04 01:03
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Closed by MarjieAVolk** 2018-04-04 01:03 UTC
