### ISSUE TITLE
USER ISSUE: Unable to vote on law in browser.

### ISSUE THREAD

**Issue by GibsonSWE** [StrangeLoopGames/EcoIssues#4257] opened 2018-02-10 16:13 UTC
When trying to vote on a law, it seems like Im getting an error or something in the upper section of the "main box" `<div id="page-wrapper">` but with no text visible.

Im using Google Chrome 64.0.3282.140 64-Bit on Windows

![image](https://user-images.githubusercontent.com/33501602/36064051-9f514538-0e85-11e8-919a-4b9bb206d8b3.png)

**Comment by GibsonSWE** [comment] 2018-02-10 16:23
Might be same as #4104 actually

**Comment by th3t0mb0mb** [comment] 2018-02-11 00:29
I have run into this issue as well.

**Comment by MarjieAVolk** [comment] 2018-02-13 04:46
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4094

You are right that it is trying to show you an error message, but the text is not being displayed.  We are looking into a fix for this.

Since you are trying to vote, my guess would be that you are not allowed to vote because of the default Citizenship law.

In order to see the message, you might try refreshing the page with alt+f5, closing and reopening it, clearing your browser cache, or opening the page with another browser.  If you do find any more information about the issue, please share!

**Closed by MarjieAVolk** 2018-02-13 04:46 UTC
