### ISSUE TITLE
USER ISSUE: floating tree piece? 

### ISSUE THREAD

**Issue by kazenokizu** [StrangeLoopGames/EcoIssues#5284] opened 2018-03-02 02:12 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
chop tree wait for log to float in air and take it. 

**Expected behavior:**
went in my carry slot 

**Actual behavior:**
The following error message popped up:
```Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by SeanAtr0n** [comment] 2018-03-02 04:24
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by SeanAtr0n** 2018-03-02 04:24 UTC
