### ISSUE TITLE
Invisible trees with road tool glitch (roots are too strong)

### ISSUE THREAD

**Issue by DarkIrata** [StrangeLoopGames/EcoIssues#10550] opened 2019-01-07 22:39 UTC
When using the road tool underneath a tree it turns invisible and has no colliders. 
The place where the tree was, can't be digged since the stump is still "there".
Found no way to remove the dirt.

Reproduce
1. Get the "Road Tool"
2. Find Oak Tree
3. Use the Road Tool undearneath Oak Tree stump
4. Try dig dirt street

Video: (https://img.gwa.app/w/FiYks.webm)

Happened in version 0.7.8.8 beta - Steam Version

Could be possible abused

**Comment by DurtyFree** [comment] 2019-01-07 22:42
This is a very critical issue IMO. There is no way to fix the "invisible tree". The spot ends up beeing unusable.

**Comment by Deantwo** [comment] 2019-01-07 22:55
Duplicate of #10069

**Comment by DurtyFree** [comment] 2019-01-07 22:58
Btw its a duplicate
![grafik](https://user-images.githubusercontent.com/20757266/50798273-1cfba300-12d8-11e9-8793-ba1e6dd2d6cd.png)

**Comment by D3nnis3n** [comment] 2019-01-08 07:01
Does restarting the server fix this issue?

**Comment by D3nnis3n** [comment] 2019-01-08 07:05
AS Deantwo said in the other issue,

"A "the roots are too strong" error would likely be a good idea in this situation.

This should appear instead of making the tree invisible. I'll merge the other issue into this one as it seems the tree does not get deleted, but blocks the plot which is a more major issue. (If it is not fixed on a server restart)

**Comment by elfl0rd** [comment] 2019-01-08 07:08
hmm, why you merge to new issue without priority tag?

**Comment by D3nnis3n** [comment] 2019-01-08 07:11
Cause i waited for an answer on the question if a server restart does fix it or not *g*

**Comment by Deantwo** [comment] 2019-01-08 07:21
@D3nnis3n, if we are metging into this issue, can you maybe change the issue title and opening post to correctly refer to the tool as a "Road Tool"? It is not called a "street tool".

**Comment by DarkIrata** [comment] 2019-01-08 21:00
Sorry for the late response, work and stuff.
Since it isn't my server i couldn't restart it. What i later checked was a client restart to see if it is a client side error. Nope, server side. 
Fixed the name. Was to lazy to check the correct english name at midnight. Sorry

**Comment by D3nnis3n** [comment] 2019-01-09 08:01
If you can get the owner to restart the server to see if it's fixed, that would be good.

**Comment by elfl0rd** [comment] 2019-02-14 16:53
After 0.8 - mentioned multiple times.
Also require server restart to fix.
Bumping prior to SH

**Closed** 2019-06-17 05:47 UTC
Labels: Fixed, High Priority, QA
