### ISSUE TITLE
Alpha.6 Initialization failure

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2418] opened 2017-09-30 19:12 UTC
Unable to interact or see Player:
![image](https://user-images.githubusercontent.com/1900106/31048733-f09e7fe8-a623-11e7-89ca-18314f152671.png)

I see following in Player.log while joining, which does appear normally
```
Caught exception on OtherPlayer(Clone) while in NetObject ReceiveInitialState.
Exception: Object reference not set to an instance of an object
Callstack:   at Eco.Shared.Voxel.World.ClosestWrappedLocation (Vector3 viewPosition, Vector3 position) [0x00000] in <filename unknown>:0 
  at AutoWrapper.Wrap (Vector3 pos) [0x00000] in <filename unknown>:0 
  at SyncPhysics.ReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) System.Action`1<Eco.Shared.Serialization.BSONObject>:invoke_void__this___BSONObject (Eco.Shared.Serialization.BSONObject)
  at NetObjComponent.OnReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <filename unknown>:0 
  at NetObjComponent.Eco.Shared.Networking.INetObject.ReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <filename unknown>:0 
BSON: Eco.Shared.Serialization.BSONObject
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```

Reproduce:
- Download ftp://eco.fankserver.com/Game-2418.eco
- Join and go to 975,148 with view distance 60
- See error in chat and notice nothing is interactable around you

**Comment by MarjieAVolk** [comment] 2017-10-02 17:50
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2394

**Closed by MarjieAVolk** 2017-10-02 17:50 UTC

**Comment by Fank** [comment] 2017-10-02 20:54
🤦‍♂️ i forgot about the dup.... but i hope the info will help to fix
