### ISSUE TITLE
5.6.2 staging 8802b6fc wainwright table inserting carry-only items into chests

### ISSUE THREAD

**Issue by Ciannicay** [StrangeLoopGames/EcoIssues#1832] opened 2017-08-01 20:57 UTC
The wainwright table die repeatedly inset asphalt roads into linked chest after all linked stockpiles were filled.

**Comment by MarjieAVolk** [comment] 2017-08-04 17:27
Duplicate of StrangeLoopGames/EcoIssues#1729

**Closed by MarjieAVolk** 2017-08-04 17:27 UTC
