### ISSUE TITLE
USER ISSUE: Locked camera after running out of fuel while excavating

### ISSUE THREAD

**Issue by Frosty939** [StrangeLoopGames/EcoIssues#6358] opened 2018-03-22 03:40 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Get in a fueled excavator
2. start mining
3. while still holding down the mouse button, run out of fuel
4. get out of the excavator
5. freak out because your camera is locked
Fix. if you are able to refuel it and remount, you can continue to mine, then stop and get out. Your camera is now back to normal	

**Expected behavior:**
You run out of fuel while excavating, you get out and can continue to move your camera like normal.

**Actual behavior:**
It locks your camera to the direction you were looking when you ran outof fuel in the excavator

**Comment by MarjieAVolk** [comment] 2018-03-22 18:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6281 -- I will note that your repro steps are similar to theirs

**Closed by MarjieAVolk** 2018-03-22 18:32 UTC
