### ISSUE TITLE
Logs not breaking down - 6.0.3

### ISSUE THREAD

**Issue by Dreconic** [StrangeLoopGames/EcoIssues#2674] opened 2017-11-01 01:32 UTC
After MAB updated to 6.0.3 we have several members reporting that logs won't break down into singles at all, double logs are very rare, with sets of 3 being rare. Most common cuts are 4 and 5 without being able to cut lower.

Tried myself on multiple logs hacking 20+ times in one area to try to get 1's, 2's, or 3's out of 4's and 5's.

**Comment by MarjieAVolk** [comment] 2017-11-01 17:35
Yes, the minimum log size was increased.  Closing as intended behavior

**Comment by MarjieAVolk** [comment] 2017-11-01 18:14
Okay we talked about this more, and we actually agreed that this needs some re-examining :P

**Comment by metachronism** [comment] 2017-11-02 19:47
this is intended.
slicing logs as small as possible isnt the goal, and the efficiency stuff (to get more logs from raw mats) will be very soon moved to a different skillset

**Comment by SeanAtr0n** [comment] 2017-11-02 22:04
This seems like a bug to me, and it will seem like a bug to many other players.

It might not be as annoying/confusing if cuts were restricted to even numbers.

**Comment by MarjieAVolk** [comment] 2017-11-02 22:05
Yeah that's what I was thinking too - whatever the minimum size is, only allow cuts at multiples of that size

**Comment by metachronism** [comment] 2017-11-02 23:53
I still have no idea what the request is.

the min log size was intended.  This is an optimization as logs of too small size cause stalling on player clients.  We are not going to be adding the ability to get single-log chops anymore.

**Comment by MarjieAVolk** [comment] 2017-11-03 00:09
The request is to not have the chop size be so confusing.  It's confusing because there's kind of a minimum size, but you can get under the minimum size if you do weird things, and you can get stuck with a piece that's ~1.5x the minimum size in other cases, and it's just really difficult to chop them to a size you want.  Maybe that matters less now since we don't have yield based on chop size anymore, but it's still relevant for things like stack size (like if I want to try to pick up exactly 10 logs, that's basically impossible and a very unpleasant experience).  And also players are going to notice it because they're used to noticing the chop size.

My suggestion, and I think Sean's suggestion, was to enforce the minimum size more consistently, by only allowing chops at specified places on the tree, so that basically if you randomly chop at the tree for a while, all the pieces will be the same size - the minimum size, whatever that is.

**Closed** 2017-11-27 20:06 UTC
Labels: Low Priority
