### ISSUE TITLE
USER ISSUE: Logs not going into stockpiles

### ISSUE THREAD

**Issue by tenpigs** [StrangeLoopGames/EcoIssues#23985] opened 2023-08-22 12:41 UTC
\
**User Id: (slg110466)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
2nd camp. Tent put up with stockpiles just outside tent and also workbench there as well. Work bench recognises linked stock piles (all storage is linked) and starts the work order.

**Expected behavior:**
The hewn logs should go into linked stockpile/storage

**Actual behavior:**
It waits to be collected by me and doesn't go into the stockpile as it has done in the previous camp. I have tried all sorts of ways to fix this and none has worked so far

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-08-24 12:08
Unable to reproduce, need more information.

**Comment by D3nnis3n** [comment] 2023-09-01 04:45
Closing due to no further information provided, feel free to reopen if you can provide further information.

**Closed by D3nnis3n** 2023-09-01 04:45 UTC
Labels: Status: Not reproduced
