### ISSUE TITLE
voting page states feature is in progress, but its done

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#10472] opened 2019-01-03 00:47 UTC
![image](https://user-images.githubusercontent.com/3150561/50619441-1cb17100-0eae-11e9-9e99-2dc2d5db9222.png)

**Comment by elfl0rd** [comment] 2019-02-12 21:16
Duplicate of #11282

**Closed by elfl0rd** 2019-02-12 21:16 UTC
Labels: Low Priority
