### ISSUE TITLE
Ramload Issue not enough Memory

### ISSUE THREAD

**Issue by Tikkar-Anatol** [StrangeLoopGames/EcoIssues#7692] opened 2018-05-10 16:58 UTC
https://www.dropbox.com/s/3vowaf98uax9lsw/Kauhali.db?dl=0

https://www.dropbox.com/s/nmrrus4dgczrxyp/Kauhali.eco?dl=0

.o(not sure those Links are working .. )

Hello, i have a problem with the Ramload. In Multiplayer as Client on my Brothers Server after 60 to 90 Minutes from the 16 GB ram are around 14 GB in use and Windows kicks the Game off. 
It happens also in Singleplayer but takes much more time. 
I dont see the Problem on my Hardware, 

Windows 7 64bit Ultimate, 16 GB DDr3 Ram 1600 mhz, Nvidia GTX 660 Ti. 

I installed the Game via Steam a couple of times new after some changes on the Driver, but i cant find the Problem on my side. 

So the question is there possibly a bigger Ram issue in the Game or the Engine itself?

Thx for Help :)

**Comment by metachronism** [comment] 2018-05-10 22:14
closing as dupe of #6973

**Closed by metachronism** 2018-05-10 22:14 UTC
Labels: High Priority
