### ISSUE TITLE
USER ISSUE: Lost steam tractor plough

### ISSUE THREAD

**Issue by Kimrian** [StrangeLoopGames/EcoIssues#8953] opened 2018-08-12 17:12 UTC
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
have the tractor out mith the module plough, use the hammer on the tractor to get it into inventory, plogh disapears

**Expected behavior:**
the tractor and plough both should have gone into inventory/backpack

**Actual behavior:**
only steam tractor into inventory/backpack, plough disapeared

**Comment by elfl0rd** [comment] 2018-08-15 00:29
dupe, https://github.com/StrangeLoopGames/EcoIssues/issues/8219

**Comment by craig-jong** [comment] 2018-09-04 23:57
Fixed - not sure why this was open when its a dupe of a closed bug.

**Closed by craig-jong** 2018-09-04 23:57 UTC
Labels: High Priority
