### ISSUE TITLE
USER ISSUE: Guide how to destroy any city

### ISSUE THREAD

**Issue by Kopnu** [StrangeLoopGames/EcoIssues#24232] opened 2023-12-16 09:17 UTC
**User Id: (slg231063)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
1. You are founding a city
2. Leave the received claim papers and stakes in the "Spawned Claims" tab
3. A new resident appears in the city and steals all claims and stakes
4. He is removing his citizenship

**Expected behavior:**
Claim papers and stakes have been returned because they can ONLY be used on the territory of the city, and the player is no longer a citizen of that city.

**Actual behavior:**
"Property crisis" in the city that you can't prevent

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, vanila

**Comment by johnkslg** [comment] 2023-12-16 18:52
The town defaults to only giving the mayor access to the spawned plots not sure how this happens, unless you open it up to any citizen manually?

**Comment by johnkslg** [comment] 2023-12-16 18:53
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3536496/334f976e-2b71-4716-88dd-a1fb20a6d43b)

**Comment by Kopnu** [comment] 2023-12-17 07:59
> The town defaults to only giving the mayor access to the spawned plots not sure how this happens, unless you open it up to any citizen manually?

There was a problem that a citizen could not renounce his citizenship (player could not enter the "Civic Actions" tab). And the mayor was setting up the rights. I admit that this could happen due to incorrectly configured permissions. It's not entirely clear how to set up permissions for different tabs for the Town Foundation. 

Yesterday, a player got in touch who claimed that he had claim papers of our city, although because of the panic we destroyed the old city and built a new one. I will try to clarify if this is true.

**Comment by Daniel-Magulado** [comment] 2023-12-18 15:52
@Kopnu Hi, can we request the save file where this issue has occurred? We'd like to get a look into it and what's causing it to allow citizens who are not title holders or have no permission to have access to claim items.

**Comment by Kopnu** [comment] 2023-12-19 09:03
The player I wrote about above never got in touch.
About save. I'll ask admins of the server I'm playing on to share the save.

**Comment by Kopnu** [comment] 2023-12-19 12:26
Save file: https://drive.google.com/file/d/10eE3-3arVTS-q1TMiKozjzw1aaNuvMwJ/view?usp=sharing

**Comment by D3nnis3n** [comment] 2024-01-02 02:37
The savefile unfortunately can no longer be used to investigate, as the town was destroyed. We are not able to reproduce this issue with a newly found town with default permissions, though. With default permissions only the mayor can take out claims while anyone is able to access the civic tabs. Closing.

If you ever see the issue again, please let us know reproduction steps and attach a save that has the town in the state the problem occurs.

**Closed by D3nnis3n** 2024-01-02 02:37 UTC
