### ISSUE TITLE
Got exception at processing message from Steam:

### ISSUE THREAD

**Issue by Arranoa-jolasten** [StrangeLoopGames/EcoIssues#25067] opened 2024-08-18 18:22 UTC
[
[message.txt](https://github.com/user-attachments/files/16650975/message.txt)
08:54:22.237] [332] [Error] [Eco] Got exception at processing message from Steam:76561197992488304:        [Ping: 120 ms]  [CPU: 0.5 ms]   [In: ∞ k/s]     [Out: ∞ k/s]    . Exception: System.Exception: Don't know elementType = 101
   at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeObject(MemoryStream stream, BSONObject obj)
   at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
   at Eco.Shared.Networking.NetMessage.DecodePacket(ReadOnlySpan`1 message)
   at Eco.Plugins.Networking.NetworkServer.HandleIncomingDataMessage(UdpDataMessage& message). The message length is: 69 and text representation is id��	methodViewRPCargs���
13818args��v  
query�(

**Comment by D3nnis3n** [comment] 2024-08-18 20:17
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25063

**Closed by D3nnis3n** 2024-08-18 20:17 UTC
