### ISSUE TITLE
[8.2.3] Waypoints names issue when changing language.

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#12619] opened 2019-06-21 17:28 UTC
When I change the language every waypoint is shown as "my waypoint" even though the name is correct on the minimap.

**Comment by D3nnis3n** [comment] 2019-06-21 20:17
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9956

**Closed by D3nnis3n** 2019-06-21 20:17 UTC
