### ISSUE TITLE
USER ISSUE: Game freezing over and over again

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#5421] opened 2018-03-05 17:32 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Log into my world and wait until you freeze after a few moments without obvious reason and no log files at all ... i don't even know where to find those logs, i already made a report because there is no information where to find log data

and the response behaviour in this git is also very disappointing

just tell me where i can see logs or how to enable a log console or somethign that is actually helpfull

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-03-05 19:32
Client log file is 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'.

Server log files, if you are running your own server, are in '[...]\steamapps\common\Eco Server'.

**Comment by mindforger** [comment] 2018-03-05 20:16
okay there is no file :( do i have to enable logging ?

i forgot to mention playing via steam

**Comment by MarjieAVolk** [comment] 2018-03-05 20:27
Yeah those directories are for steam.  Are you on windows?  You should basically always have an output_log.txt, if you have played the game recently.  You can try to reproduce the error first, and then look for the log, maybe it didn't have any output yet.

**Comment by mindforger** [comment] 2018-03-05 20:39
creating an empty file with that name did the trick, now i got a log but unfortunately i already lost my world because i wanted to play so badly and reset it

will try to post the log when it hangs again, but there is an update tomorrow afaik (pastebin link for the logokay?)

**Comment by MarjieAVolk** [comment] 2018-03-05 23:49
Oh that's odd, that creating the file yourself would change it.

Yes, I believe we are still planning to release tomorrow.  And a pastebin link is also fine.

So since you are not having the problem right now, I'm going to close this bug for now.  If you get the problem again, you can keep commenting here and I will see it; we can reopen it when we have more data.

**Closed by MarjieAVolk** 2018-03-05 23:49 UTC
