### ISSUE TITLE
Game crashes after 15-25 mins on playtime

### ISSUE THREAD

**Issue by Imbawolf** [StrangeLoopGames/EcoIssues#5780] opened 2018-03-09 16:12 UTC
Pam, from support discord channel section, tell me this is a unity error and ask me post this log here 

[Crash_2018-03-09_180718.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1797509/Crash_2018-03-09_180718.zip)

**Comment by MarjieAVolk** [comment] 2018-03-09 21:29
Thanks!  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5793

**Closed by MarjieAVolk** 2018-03-09 21:29 UTC
