### ISSUE TITLE
USER ISSUE: Window opacity

### ISSUE THREAD

**Issue by Gab-Bryan** [StrangeLoopGames/EcoIssues#13349] opened 2019-10-15 19:36 UTC
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
Create a room, closed with walls and windows.

**Expected behavior:**
The windows should have sunlight going throught and entering inside the room

**Actual behavior:**
Bounce back like a plain wall. No light goes inside

**Do you have mods installed? Does issue happen when no mods are installed?:**
Bounce back like a plain wall. No light goes inside

**Comment by SlayksWood** [comment] 2019-10-16 05:14
@Gab-Bryan 
Can you provide a couple of screenshots?
What type of material are you using?
Please, provide the graphics settings and log files:
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Gab-Bryan** [comment] 2019-10-17 02:01
I've created this room made of all sorts of glass materials. As you can see, none of them can do exactly what it should do.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3737072/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3737073/Player-prev.log)
![Capture d’écran (19)](https://user-images.githubusercontent.com/56608487/66971777-73182680-f060-11e9-8ff1-478641f63f69.png)
![Capture d’écran (18)](https://user-images.githubusercontent.com/56608487/66971778-73182680-f060-11e9-9125-83374c852339.png)

**Comment by Gab-Bryan** [comment] 2019-11-04 01:49
Is there an update on that issue?

**Comment by redwyre** [comment] 2019-11-29 15:16
Hi @Gab-Bryan, what is your shadows set to in the graphics settings, and what video card do you have?

**Comment by Gab-Bryan** [comment] 2019-12-01 02:04
> Hi @Gab-Bryan, what is your shadows set to in the graphics settings, and what video card do you have?

I tried every graphic settings I could change, nothing seems to turn it back on. I have a GTX 960

**Comment by SlayksWood** [comment] 2020-02-15 07:19
Can't reproduce in staging-1402
![image](https://user-images.githubusercontent.com/45708377/74583840-9e922a00-4fdc-11ea-81fb-e534508f892e.png)

**Comment by Gab-Bryan** [comment] 2020-02-28 16:50
I see you have a recent version of the game? My layout is not the same. Perhaps it will be fixed with 9.0

**Comment by WeaselDog** [comment] 2020-05-22 02:46
We have been doing a lot of updates on lighting. Just wanted to follow up and say it will be fixed in the latest version so I am going to close.

Thanks for you report!

**Closed by WeaselDog** 2020-05-22 02:46 UTC
Labels: Priority: Low, Status: Not reproduced
