### ISSUE TITLE
USER ISSUE: Crafting Storage Input and Output are reversed

### ISSUE THREAD

**Issue by Xiarno** [StrangeLoopGames/EcoIssues#24419] opened 2023-12-28 17:46 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Open crafting table.
2. Select storage tab.
3. Attempt to mark a storage as input.

**Expected behavior:**
The storage should act as input for craft.

**Actual behavior:**
It act as output even though input was selected.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No I do not have mods installed.
Yes it happens without mods.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13788413/Player.log)

**Comment by D3nnis3n** [comment] 2023-12-28 18:09
Cannot reproduce, are you sure you marked them correctly? Please provide a screenshot, at best a video showing the behaviour during craft.

**Comment by D3nnis3n** [comment] 2024-01-16 01:45
Closing due to no further information for reproduction provided, issue is not reproducible.

**Closed by D3nnis3n** 2024-01-16 01:45 UTC
Labels: Status: Needs Information, Status: Not reproduced
