### ISSUE TITLE
USER ISSUE: Invisible plants

### ISSUE THREAD

**Issue by Kharomoth** [StrangeLoopGames/EcoIssues#6592] opened 2018-03-28 21:29 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Try to plant something

**Expected behavior:**
It should plant the plant

**Actual behavior:**
It says plant already exists there, even though there isn't anything

**Comment by MarjieAVolk** [comment] 2018-03-28 21:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5887

**Closed by MarjieAVolk** 2018-03-28 21:53 UTC
