### ISSUE TITLE
USER ISSUE: Falling through world

### ISSUE THREAD

**Issue by carter0599** [StrangeLoopGames/EcoIssues#4881] opened 2018-02-20 21:26 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place dirt while falling/place dirt where you stand

**Expected behavior:**
just land on the placed dirt

**Actual behavior:**
fall through world. after falling you do apear where you should though

**Comment by MarjieAVolk** [comment] 2018-02-20 22:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3897

**Closed by MarjieAVolk** 2018-02-20 22:05 UTC
