### ISSUE TITLE
USER ISSUE: Server list empty

### ISSUE THREAD

**Issue by Babacar62** [StrangeLoopGames/EcoIssues#5073] opened 2018-02-25 09:27 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
When i click  on join menu, the game return 0 server.
If I add an ip, he tell me the server is offline 

**Expected behavior:**
It should have a server list.... to let me play in multi

**Actual behavior:**
0 server, i cannot play... the game is update in the last version, he is authorized on firewall, i reinstall it ...but always the same problem .. Last week the game work fine but today I cant play. Can you help me please?

**Comment by MarjieAVolk** [comment] 2018-02-26 21:35
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4995

If you delete the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO, that should get you around the problem for now.

**Closed by MarjieAVolk** 2018-02-26 21:35 UTC
