### ISSUE TITLE
Banning players can cause to spawn an invalid ban, leading to steam players not being able to vote

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21541] opened 2021-04-23 19:13 UTC
I banned two players on Tiger today, between the first and the second a third ban without ID was introduced, leading to a 'Banned from this server' error for every steam-only player on voting.

`            {
              "UserName": "76561197995459782",
              "ReleaseDate": new Date(
                1781175153275
              )
            },
            {
              "ReleaseDate": new Date(
                1781175183627
              )
            },
            {
              "UserName": "76561197995682294",
              "ReleaseDate": new Date(
                1781175183627
              )`

Admin Log that shows that _exactly_ two ban commands were executed, no third one, no wrong one.
Simon says the 'bad ban' and the second ban i actually executed have the same time, so might be related.

[2021-04-23 00:44:35.803][ Info] KatFish invoked admin command 'addaccountmanager' 
[2021-04-23 00:45:57.414][ Info] KatFish invoked admin command 'deleteaccount' 
[2021-04-23 01:47:37.769][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 01:49:31.999][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 01:50:58.229][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 01:51:37.454][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 01:51:41.503][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 01:52:31.836][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 01:53:05.681][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 01:53:39.819][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 01:57:02.014][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 01:57:53.788][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 02:13:16.018][ Info] -=GoW=-Dennis invoked admin command 'fly' 
[2021-04-23 03:08:47.328][ Info] KatFish invoked admin command 'unassign' 
[2021-04-23 04:33:16.740][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 04:34:19.081][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 04:34:21.219][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 04:34:53.059][ Info] [PMD]Daniel93a invoked admin command 'edit' 
[2021-04-23 04:35:20.865][ Info] [PMD]Daniel93a invoked admin command 'unassign' 
[2021-04-23 04:36:10.870][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 04:56:35.962][ Info] [PMD]Daniel93a invoked admin command 'assign' 
[2021-04-23 04:56:51.939][ Info] [PMD]Daniel93a invoked admin command 'assign' 
[2021-04-23 05:07:35.158][ Info] [PMD]Daniel93a invoked admin command 'toplayer' 
[2021-04-23 05:16:01.696][ Info] [PMD]Daniel93a invoked admin command 'toworldposition' 
[2021-04-23 05:21:45.495][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 07:22:06.001][ Info] KatFish invoked admin command 'fly' 
[2021-04-23 07:53:18.770][ Info] KatFish invoked admin command 'fly' 
[2021-04-23 12:48:41.103][ Info] Ice Forge invoked admin command 'whois' 
[2021-04-23 12:48:50.852][ Info] Ice Forge invoked admin command 'whois' 
**[2021-04-23 12:52:33.272][ Info] -=GoW=-Dennis invoked admin command 'ban' 
[2021-04-23 12:53:03.626][ Info] -=GoW=-Dennis invoked admin command 'ban'** 
[2021-04-23 12:53:28.397][ Info] -=GoW=-Dennis invoked admin command 'whois' 
[2021-04-23 12:55:52.648][ Info] -=GoW=-Dennis invoked admin command 'whois' 
[2021-04-23 12:56:34.786][ Info] -=GoW=-Dennis invoked admin command 'setreputation' 
[2021-04-23 12:56:40.277][ Info] -=GoW=-Dennis invoked admin command 'setreputation' 
[2021-04-23 12:57:02.119][ Info] Hiroyugane invoked admin command 'setreputation' 
[2021-04-23 12:59:33.344][ Info] -=GoW=-Dennis invoked admin command 'tagstaggrant' 
[2021-04-23 14:49:46.725][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 16:16:09.252][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 16:17:33.780][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 17:58:18.127][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 18:07:04.531][ Info] KatFish invoked admin command 'fly' 
[2021-04-23 18:08:41.887][ Info] KatFish invoked admin command 'fly' 
[2021-04-23 18:26:33.276][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 18:43:11.822][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 18:45:27.099][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 18:50:07.439][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 18:51:11.129][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 20:14:00.622][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 20:14:48.146][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 20:24:51.387][ Info] [PMD]Daniel93a invoked admin command 'assign' 
[2021-04-23 20:25:54.515][ Info] [PMD]Daniel93a invoked admin command 'unassign' 
[2021-04-23 20:26:36.099][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 20:28:27.203][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 20:36:41.630][ Info] [PMD]Daniel93a invoked admin command 'assign' 
[2021-04-23 20:37:16.115][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 20:42:31.367][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 20:43:03.127][ Info] [PMD]Daniel93a invoked admin command 'give' 
[2021-04-23 20:45:11.819][ Info] Kaapo invoked admin command 'fly' 
[2021-04-23 20:46:07.761][ Info] [PMD]Daniel93a invoked admin command 'unassign' 
[2021-04-23 20:52:58.405][ Info] [PMD]Daniel93a invoked admin command 'give' 
[2021-04-23 20:53:08.136][ Info] [PMD]Daniel93a invoked admin command 'assign' 
[2021-04-23 20:59:33.850][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 20:59:44.622][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 20:59:52.053][ Info] [PMD]Daniel93a invoked admin command 'fly' 
[2021-04-23 21:05:52.239][ Info] [PMD]Daniel93a invoked admin command 'toworldposition' 
[2021-04-23 21:07:00.899][ Info] [PMD]Daniel93a invoked admin command 'toworldposition'

**Comment by D3nnis3n** [comment] 2021-04-23 19:18
I confirmed via testing that this happens when you ban someone via name, it does not happen when you ban via account id.

**Comment by IronyTroll** [comment] 2021-04-28 14:19
Since banning a player on our server, players who have NOT linked their Steam and SLG account have been unable to vote also. 

4 players have linked their Steam account to their SLG account and the problem is resolved for those players.

**Comment by SlayksWood** [comment] 2021-05-05 11:04
Pretty hard to check this issue. So I tried to ban different Users(standalone, steam, steamlinked) by id/name and tried to vote. I don't have any problem in 0.9.3.4 release-226. 
@D3nnis3n seems fixed. I closed it for now.

**Closed by SlayksWood** 2021-05-05 11:04 UTC
Labels: Category: Tech, Priority: Critical, Priority: High, Squad: Mountain Goat, Status: Fixed, Type: Bug
