### ISSUE TITLE
USER ISSUE: Dead Trees

### ISSUE THREAD

**Issue by katabare** [StrangeLoopGames/EcoIssues#4679] opened 2018-02-17 05:05 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Plant a tree seeds in the same condition. 
Check it with the soil sampler

**Expected behavior:**
The trees shouldnt die.

**Actual behavior:**
Some of the trees are dead despite being in the exact condition as other trees that live.

**Comment by Meronantes** [comment] 2018-02-17 08:25
not everything will grow even in if it's conditions are met (temperature, moisture, mineral levels i.e Nitrogen). The World Layers that show YieldPotential (all the way at the bottom) highlights the best locations/worst locations to plant. This DOES NOT guarantee 100% that the plant will not die. It just lets you know that it has a much higher/lower chance of it living

**Comment by Khazul01** [comment] 2018-02-18 03:16
I haven't seen any of my trees grow, area is 100% in good yield area and everything dies. Is there some magical way to get trees to grow this is frustrating?

**Comment by Khazul01** [comment] 2018-02-18 20:10
Why did the changes to growing everything have to go so drastic. Crops and trees alike.  I planted some trees in 100% for Temp/Moisture/Pollution. The area is yellow for Yield Potential. Come back later and get like 3 trees that are still growing and 22 dead trees. I think that at least if they die they should show up as so, you cant even tell if they are dead without a soil sampler. It's quite frustrating trying to get trees to grow. On top of that it takes nearly 5 days to grow fully if you can even get a tree to grow in the first place.

**Comment by MarjieAVolk** [comment] 2018-02-20 22:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4577

Farming and the plant sim changed a lot recently, and we're aware that it ended up pretty unbalanced.  We are working on tuning it up for the next release, and making its behavior more clear.

**Closed by MarjieAVolk** 2018-02-20 22:12 UTC
