### ISSUE TITLE
USER ISSUE: Object reference not set to an instance

### ISSUE THREAD

**Issue by SilverSatin** [StrangeLoopGames/EcoIssues#5070] opened 2018-02-25 07:29 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
My current situation.
1 Steam account connected to dedicated game server online.
and a non-steam account connected to the same server online.
Both players using same home internet connection.

Steam account player is using wooden cart  suddenly freezes.  I disconnect ( menu -> disconnect )   then in main menu "continue" to get back on the server.

I see myself (my character) still frozen holding the cart but i'm not the one holding the cart anymore I'm just looking at my previous-self.   suddenly that ghost vanish   and I get exception.  

**Expected behavior:**
Continue playing without an exception

**Actual behavior:**
The following error message popped up:
Caught exception: Object reference not set to an instance of an object.
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment] 2018-02-26 21:37
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4842

Did this happen once?  Or does it happen repeatedly?

**Closed by MarjieAVolk** 2018-02-26 21:37 UTC
