### ISSUE TITLE
USER ISSUE: Fishing

### ISSUE THREAD

**Issue by beardedjon21** [StrangeLoopGames/EcoIssues#4525] opened 2018-02-14 15:49 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
i went fishing and never recieved a fish

**Expected behavior:**
give me fish	

**Actual behavior:**
didnt give me a fish

**Comment by VAlex0** [comment] 2018-02-17 20:56
-> see #4588

**Comment by MarjieAVolk** [comment] 2018-02-20 21:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

**Closed by MarjieAVolk** 2018-02-20 21:53 UTC
Labels: Medium Priority
