### ISSUE TITLE
Anticheat spams log

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21425] opened 2021-04-16 21:38 UTC
[log_210416074832.log](https://github.com/StrangeLoopGames/EcoIssues/files/6327978/log_210416074832.log)

**Comment by mirasrael** [comment] 2021-04-19 12:51
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/21421

**Closed by mirasrael** 2021-04-19 12:51 UTC
