### ISSUE TITLE
Error creating new law

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11784] opened 2019-03-27 19:46 UTC
![image](https://user-images.githubusercontent.com/431728/55107298-b8a0f080-511c-11e9-96f8-4984e0c03bce.png)

**Comment by redwyre** [comment] 2019-03-27 19:46
After refreshing the page I could fill in the name and reasoning again and create it

**Comment by D3nnis3n** [comment] 2019-03-27 21:28
Also sometimes get this in complex laws WHILE editing, but can save just fine.

**Comment by mirasrael** [comment] 2019-03-28 06:27
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11742
Fixed in master. @redwyre during creation of the law did you switch to districts view?

**Comment by redwyre** [comment] 2019-03-28 16:26
@mirasrael I believe the default action is to add a district, so it started on that

**Comment by mirasrael** [comment] 2019-03-29 05:54
@johnkslg @seccombew Should we back port fix from master to the staging?

**Comment by mirasrael** [comment] 2019-04-01 10:00
Fix backported from master.

**Closed by mirasrael** 2019-04-01 10:00 UTC
Labels: Medium Priority, Staging
