### ISSUE TITLE
Prairie Dogs on an old server

### ISSUE THREAD

**Issue by SVZh** [StrangeLoopGames/EcoIssues#22633] opened 2021-09-03 13:52 UTC
It seems we can't populate our world with Prairie Dogs no matter what we try. I spawn them in spades in different biomes with different plants for them to eat - including tomatoes, corn, and such. But no matter what they disappear in a few minutes and their population is constant zero on a statistics screen.

What should we do? Is there a way to inject those dogs into our world?

**Comment by Daniel-Magulado** [comment] 2021-09-06 17:16
Hello @SVZh

If you're migrating an old server from 0.9.3 to the latest official version of the game, 0.9.4, it's normal that there won't be any Prairie Dogs since it's an existing world that started without these species.

To populate your current world with Prairie Dogs, you can use the command simulate "/sim setlayer PrairieDogCapacity, 0.6, 0.8" without the parenthesis.

This will generate a layer in the server UI for the species capacity enabling them to populate your world. However, it doesn't end there. The next thing you need to do is to open the serverUI via /serverui command. Once the Server UI pops up outside of the game, you need to make your way to the World Layers tab and then on to the sub tab with the same name.

From there, you need to look for Prairie Dogs layer as show in the image below:
![image](https://user-images.githubusercontent.com/77248866/132247931-22ee8e2a-e6a3-4230-920b-d4fa7f0eb45b.png)

Hover your mouse icon over the white area and click on it like your painting in a Microsoft Windows Paint. By doing so, this will populate your world with the species. Be mindful of this step though. Please note that since the small white box is a representation of layers of the server, this will cause the Prairie Dogs to spawn and populate in weird locations such as underwater, mountains, etc.

If you have any other questions, don't hesitate to ask.

Here's a screenshot of a world migrated from 9.3 to 9.4 where we populated it with Prairie Dogs.
![image](https://user-images.githubusercontent.com/77248866/132248223-c72579c7-4ec7-4662-ac8f-109ece972f6b.png)

**Comment by Daniel-Magulado** [comment] 2021-09-06 17:17
Closing this as this is not a bug.

**Closed by Daniel-Magulado** 2021-09-06 17:17 UTC

**Comment by D3vil787** [comment] 2021-09-17 08:11
Hi Daniel!
Our server runs on Linux and does not have a graphical interface. How to add a prairie dog layer?

**Comment by D3vil787** [comment] 2021-09-17 08:13
> Closing this as this is not a bug.

Hi Daniel!
Our server runs on Linux and does not have a graphical interface. How to add a prairie dog layer?
