### ISSUE TITLE
tree trunks sometimes not targetable

### ISSUE THREAD

**Issue by Gemji1990** [StrangeLoopGames/EcoIssues#12104] opened 2019-04-24 19:28 UTC
when i chop a tree trunk to smaller pieces the wood sometimes cant be be targeted anymore (you can still see the trunk but there is no highlight and collision).
the only fix i found so far is a client restart. 
it might be related with the invisible problem.

**Comment by SlayksWood** [comment] 2019-04-25 05:09
What version of the game are you using?
If it happens again, please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2019-04-25 23:20
Probably Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11487

@SlayksWood Check that. The other issue also mentions them vanishing, which is a separate issue, though.

**Comment by SlayksWood** [comment] 2019-04-26 14:53
Yes, It's dup #11487, but in latest version i don't see it.
#6223 is not, I will  recheck it.

**Closed by SlayksWood** 2019-04-26 14:53 UTC
Labels: Investigate, Needs Information
