### ISSUE TITLE
USER ISSUE: Aqueduct does not work it does not move water any better than a normal block

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5051] opened 2018-02-24 19:14 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
use hammer and unlock skill to get Aqueduct block

**Expected behavior:**
make water flow along the  complete length of Aqueduct

**Actual behavior:**
does not flow any better than just a dirt trench, it just goes a short distance and stops

this is aqueduct as you can see it flows to a certain point and then just stops
![snap1819](https://user-images.githubusercontent.com/29383891/36633999-f801462c-1995-11e8-9cd4-848b3fcb12ef.png)
![snap1822](https://user-images.githubusercontent.com/29383891/36634045-94552eda-1996-11e8-8df3-cc68e9186987.png)

and then this next picture is to show that Water on Aqueduct flows no better than the dirt trench
![snap1823](https://user-images.githubusercontent.com/29383891/36634020-4e3cc3cc-1996-11e8-8aed-1eac390609e8.png)

i have even tried Giving myself a water block and getting it to flow, it flows a short distance and still stops no matter how extreme i make the end
![snap1824](https://user-images.githubusercontent.com/29383891/36634104-95ee94ec-1997-11e8-9ed7-7543d951f23f.png)

**Comment by LiaungYip** [comment] 2018-02-25 01:56
Related to #4478 .

**Comment by MarjieAVolk** [comment] 2018-02-26 22:01
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4478

Will copy some of your screenshots over there

**Closed by MarjieAVolk** 2018-02-26 22:01 UTC
