### ISSUE TITLE
USER ISSUE: Elevator Broken

### ISSUE THREAD

**Issue by TOTRanger** [StrangeLoopGames/EcoIssues#11870] opened 2019-04-04 20:55 UTC
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
use the elevator

**Expected behavior:**
you should be able to ride the elevator

**Actual behavior:**
you fall trough the floor of the leevator cart

**Do you have mods installed? Does issue happen when no mods are installed?:**
you fall trough the floor of the leevator cart

**Comment by SeanAtr0n** [comment] 2019-04-04 20:57
Any other details you can give? This doesn't happen all of the time

**Comment by TOTRanger** [comment] 2019-04-04 20:59
wood carts can use the elevator but player's can not we just testet 3 players and 2 re logs just in case

**Comment by SeanAtr0n** [comment] 2019-04-04 21:10
hmm, looks like the fix for this isn't in the release build

**Comment by TOTRanger** [comment] 2019-04-04 21:12
Anything we can do to help?

**Comment by ojemineh** [comment] 2019-04-04 21:49
happens (everytime) in 0.8.0.7 too
see video
https://youtu.be/b1rPJ0RSgmY

**Comment by SeanAtr0n** [comment] 2019-04-04 21:52
looks like the root cause is exceptions from https://github.com/StrangeLoopGames/EcoIssues/issues/11866

a prefab was somehow modified during the build process, @BlazeGuy2 is looking into it

**Comment by TOTRanger** [comment] 2019-04-04 21:58
yeah its been working all day with no problems until tonight after the update

**Comment by SlayksWood** [comment] 2019-04-05 09:42
If I use new preview-release client it works.

**Comment by D3nnis3n** [comment] 2019-04-05 17:24
Fixed in release_preview, presumably via PR#4205

**Closed by D3nnis3n** 2019-04-05 17:24 UTC
Labels: High Priority
