### ISSUE TITLE
Background colour on tools changes.

### ISSUE THREAD

**Issue by Splutty** [StrangeLoopGames/EcoIssues#11351] opened 2019-02-16 07:38 UTC
When your inventory is full, and you drag a tool into it that has a red background due to being dead, it'll change it back to the normal blue background before placing it back in the chest you were dragging it from.

100% reproduceable.

**Comment by elfl0rd** [comment] 2019-02-16 08:53
Duplicate of #2544

**Closed by elfl0rd** 2019-02-16 08:53 UTC

**Comment by Splutty** [comment] 2019-02-16 09:17
Not sure if this is a duplicate, since all the other reports in #2544 show the exact opposite.

**Comment by elfl0rd** [comment] 2019-02-16 09:18
okay, can you write video\gif?

**Comment by Splutty** [comment] 2019-02-16 09:26
Easy to replicate, I'm not currently in game. Drag a broken tool from a chest into your inventory when your inventory is full. The tool will return to the chest and now have a blue background, but still be broken.

The other reports all reference a healthy tool getting a red background. So the exact opposite :)

It's probably a similar cause, though, somehow losing the colour status when shifting things around.

**Comment by Splutty** [comment] 2019-02-16 09:29
https://imgur.com/a/5FNl98S

Broken tool in Chest
Inventory Full
Broken tool in Chest with blue background after trying to drag into full inventory

**Comment by elfl0rd** [comment] 2019-02-16 09:38
yes, same root issue, i copy your comment to #2544

**Comment by Splutty** [comment] 2019-02-16 10:14
Perfect! Hope it helps.
