### ISSUE TITLE
Stone Road missing?

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#2054] opened 2017-09-05 07:15 UTC
Is there anyway to make stone into road after moving the stone ?

**Comment by MarjieAVolk** [comment] 2017-09-22 22:56
Currently you can make a road from a placed stone block, then pick that up and put it elsewhere.  You can't turn stone rubble back into stone to make a road.  Which is a bit odd.

Maybe we can add a crafting recipe for a stone road?

**Comment by EmuLegs** [comment] 2017-09-23 00:53
it never entered my mind to dig the premade road o.O

**Comment by Frozen-byte** [comment] 2017-09-23 08:43
indeed receipts for stoneroad would be a cool step between dirt and concrete!

**Comment by craig-jong** [comment] 2017-09-27 19:14
dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/2232

**Closed by craig-jong** 2017-09-27 19:14 UTC
Labels: Enhancement
