### ISSUE TITLE
USER ISSUE: Truck Fast Taking - Useless taking bug

### ISSUE THREAD

**Issue by Julot135** [StrangeLoopGames/EcoIssues#8548] opened 2018-07-15 22:13 UTC
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
1. Have a truck fill with fuel (Logic :D) and some blocks, press right clicks, it's normally give you blocks in, but always the fuel (Useless)

**Expected behavior:**
It should give to us blocks in truck's storage

**Actual behavior:**
It give you to us fuel same if there is other importants things in the truck storage

**Comment by MarjieAVolk** [comment] 2018-07-16 18:50
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8529

**Closed by MarjieAVolk** 2018-07-16 18:50 UTC
Labels: High Priority
