### ISSUE TITLE
USER ISSUE: 7.0 attempting to connect to server

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#3864] opened 2018-02-04 04:02 UTC
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
I was falling through an endless hole, when I tried to log in I received the following error	

**Expected behavior:**
I should have logged in.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment] 2018-02-13 04:15
Closing as duplicate of #4144 . You can continue tracking the issue there.

**Closed by MarjieAVolk** 2018-02-13 04:15 UTC
Labels: High Priority
