### ISSUE TITLE
Issue with law or lack of understanding ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4390] opened 2018-02-12 14:51 UTC
so what we wanted to do was craft law, where

- for each day that went by you could cut down 1 tree, or if  2 or 3 days went by 2 or 3 trees could be cut down, but it was a over all

so in zone if no trees in that zone harvest < number total number days went by then you able to harvest if that amount is = or great then it would not allow any one to cut.

there is an exception where if its on your own land then you can cut no matter what.

other whys every one gets denied

here screen shoot of how the law was crafted.
long story short this does not seem to work, the law seems to do nothing at all in that zone royal.

![20180211195036_1](https://user-images.githubusercontent.com/15990789/36102392-cc85ae98-0fd1-11e8-8157-46843eed650f.jpg)

I also was not sure hot create a counter 

example

harvest elk in zone if elk < then total elk in Zone then deny

how would one make that law ?

we spent two almost full days trying figure it out and could not.

how the DNR does this stuff is via number checks so

if specis is less then certain amount then it just cant be harvest or killed anymore till the level rises above certain amount, so we really like craft laws that work like that- using a check sum against total amount.

**Comment by Dr-Hardware** [comment] 2018-02-12 18:59
ok couple of things;

the way i read that setup you've got nothing happening unless you try to harvest Fir.

if you're in the Royal district, and haven't harvested more trees than days, then it will allow you to harvest any tree but only checks if your attempt the Fir)

if you're not in Royal, if your own your own property, all, if on any property allow.......

**Comment by midn8t** [comment] 2018-02-12 23:30
see thats not way i read it.

i read this if in district royal then harve actions where birch < current time days
and Harvest action cedar < current time days
and harvest actions where specie fir < current time days then allow

other whys prevent

other whys if own own property then then allow and if not in the district royal 
then allow.

**Comment by MarjieAVolk** [comment] 2018-02-12 23:36
So there is one major issue I see with the law, which is that your condition does not check 'harvest actions where performed by you', so this will get the harvest actions performed by all players on the server.

However, since as you say the law is doing nothing, I assume you are on 7.1.0.  People were experiencing bad lag due to our action count database, so in that version we have disabled querying the database, meaning any laws that reference how many actions you have performed will not work in this version.  It's not a good situation :'( We are prioritizing improving the performance for querying the database, so that we can re-enable this.

**Comment by midn8t** [comment] 2018-02-12 23:38
well i want it to check action of all players on server, not just preson who is doing the action was trying to do check sum.

so that if more then 1 tree day was remove then no one can harvest check it against every one who could taken tree out of that area. 

so i take it Marjieavolk that then law is written correctly ?

**Comment by MarjieAVolk** [comment] 2018-02-12 23:42
Okay so you want the whole server to only be able to cut down 1 tree of each kind per day in this district?  I think the law is still going to have some unexpected behaviors compared to what you want (for example, right now that on your own property thing won't do anything), but if the database were enabled you would definitely see it doing something, at least something pretty close to what you want :P

**Comment by midn8t** [comment] 2018-02-12 23:53
well was a test law, just trying to make laws see how law system work how they are writting.

Ideally be nice to implement care takes of certain areas under government control and or create laws where an action like planting takes place before allowed to cut.

or if waste in area like twigs = higher then certain amount  then not cutting can take place till someone clears it.

**Comment by MarjieAVolk** [comment] 2018-02-12 23:57
Glad you are playing with the law system.  At this time you should still be able to do something similar, but just not use the 'actions performed' condition.  Eg. if in district Royal (if on own property allow otherwise prevent) otherwise allow.

Once we get the action count stuff working again, you should be able to do this law, and you should be able to require people to plant more trees than they cut down, etc.  Your suggestion about not allowing chopping in areas where there are too many twigs is not supported though.  That is an interesting suggestion.

I'm going to close this bug for now, since the only issue is the known problem of action counts being disabled.

**Closed by MarjieAVolk** 2018-02-12 23:57 UTC
