### ISSUE TITLE
Add small detail rising bar on Skill point button

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#3909] opened 2018-02-05 05:30 UTC
**Version:** 0.7.0.1 beta

Small Skill point button just shows you how many you got. I kinda miss the little bar that slowly grew full till you got a point.

What if we just add inside the button a little graph of it rising up until the point is given?

**Comment by Nanders** [comment] 2018-02-05 11:05
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3877

**Closed by Nanders** 2018-02-05 11:05 UTC
