### ISSUE TITLE
Spawned Industry speciality using /give

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11777] opened 2019-03-27 18:55 UTC
/give industry

Doesn't seem like I should be able to...
![image](https://user-images.githubusercontent.com/431728/55104171-98216800-5115-11e9-970c-8f238c3acb3d.png)

**Comment by D3nnis3n** [comment] 2019-03-27 20:53
Duplicate of #10117

**Closed by D3nnis3n** 2019-03-27 20:53 UTC
Labels: Low Priority, Staging
