### ISSUE TITLE
Staging: 0.8 weight in storages issue

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10901] opened 2019-01-26 09:50 UTC
Periodically happens after fast move (shift+drag)
![20190125233337_1](https://user-images.githubusercontent.com/4980243/51785445-ea232d00-2168-11e9-8ae4-bf2aa47f79c9.jpg)

(happens with backpack too)

**Comment by mirasrael** [comment] 2019-02-04 09:08
Duplicate of #10373

**Closed by mirasrael** 2019-02-04 09:08 UTC
Labels: High Priority
