### ISSUE TITLE
USER ISSUE: solar panel wont connect

### ISSUE THREAD

**Issue by Kuroooooooooooooooooooo** [StrangeLoopGames/EcoIssues#24704] opened 2024-01-28 11:20 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
Tried conecting solar panel on a roof to salt water below (copper pipes are 3 blocks deep in the water)

**Expected behavior:**
solar panel should work

**Actual behavior:**
status says water is disconnected and solar panel cant be turned on

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods at all

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by padmanek** [comment] 2024-01-28 16:36
I dont see any mentions of using Water Pump? Water wont flow on its own. Show picture of the setup.

**Comment by D3nnis3n** [comment] 2024-01-28 22:25
Not reproduced, needs more information - a screenshot of the setup would be good.

**Comment by D3nnis3n** [comment] 2024-02-05 03:54
Closing due to no reproduction steps provided and issue not reproducible.

**Closed by D3nnis3n** 2024-02-05 03:54 UTC
Labels: Status: Needs Information, Status: Not reproduced
