### ISSUE TITLE
USER ISSUE: Unauthorised Storages showing from Truck storage

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#22657] opened 2021-09-12 02:08 UTC
**Version:** 0.9.4.1 beta release-242

This is a strange one that I just noticed, and wasn't able to immediately reproduce so I have no idea what could of caused it.

I noticed that when I was driving my truck and parked it outside another players store, (gas truck not steam), that when I checked the vehicle's storage I was able to see the unlinked stockpiles of other players, though I was not able to interact with it in any way as trying to do so I would receive the message that I was not authorised. Upon clicking the tick icon to link the inventory, it caused all of the stockpiles to disappear. I tried recreating the steps I had taken just before but was not able to reproduce the bug.

As the issue seems to only be visual and how not able to be reproduced it would be an extremely minor thing, though I still wanted to submit a report just in case it may be useful in the future.

**Player Logs:**
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7148867/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7148868/Player-prev.log)

**Comment by Dave247** [comment] 2021-09-12 03:27
I think I might have figured it out. I believe t might be due to having the devtool selected previously, as even after selecting something else or getting rid of it, you will still see other unauthorised storages until something causes it to update.

**Comment by MishkaFur** [comment] 2021-09-12 09:15
> 
> 
> I think I might have figured it out. I believe t might be due to having the devtool selected previously, as even after selecting something else or getting rid of it, you will still see other unauthorised storages until something causes it to update.

Devtool overrides auth that will be why

**Comment by Daniel-Magulado** [comment] 2021-09-12 15:04
Hi @Dave247 

Thank you for writing this report. Devtool ignores auth when selected and active. Thus the reason why you can view the storage of other players while interacting with the storage UI of your truck. This is intended and by design. Another possible cause is that the storage is situated in a public property which is unlikely in this case. Closing as this is not a bug.

**Closed by Daniel-Magulado** 2021-09-12 15:04 UTC
