### ISSUE TITLE
Brodie Bug: Avatar screen had a gray color behind the avatar

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3096] opened 2017-12-12 23:05 UTC
.., which made it feel less alive and a little unfinished.

**Comment by MarjieAVolk** [comment] 2017-12-12 23:16
Not sure what would fix this, just like a different color?  Or are we thinking like some kind of simple scene with grass or something?  Think an artist should think about that

**Comment by MarjieAVolk** [comment] 2018-01-13 05:40
closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3097

**Closed by MarjieAVolk** 2018-01-13 05:40 UTC
Labels: Feature
