### ISSUE TITLE
[CLIENT/SERVER] Fail to rejoin local game - 

### ISSUE THREAD

**Issue by pmeyerson** [StrangeLoopGames/EcoIssues#5297] opened 2018-03-02 13:55 UTC
Sometimes if I quit my client and try to Continue later I am unable to do so.  Server 0.7.1.2 beta
All the status popups show progress.  The only way to resolve is to quit the server and re-start.  The last line in the log is:

> Server Initialization finished in 14,988.7ms
> Caught update exception from Rhekis!  Disconnecting...
> Disconnecting client [reason: Caught exception: Collection was modified; enumeration operation may not execute.]...

Dump file:

> Dump Time
> 03/02/2018 08:22:47
> 
> Exception
> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
>    at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
>    at Eco.Gameplay.Minimap.MinimapManager.GetChangesSince(ChunkMap chunkMap, Double time, String valueTypeName)
>    at Eco.Gameplay.Minimap.MinimapManager.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
>    at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
>    at Eco.Plugins.Networking.Clients.Client.Update()
>    at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()
> 
> --END DUMP--
> 

Thank you!  Good luck!

**Comment by MarjieAVolk** [comment] 2018-03-02 18:53
Thanks for finding the stack trace!  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4865

**Closed by MarjieAVolk** 2018-03-02 18:53 UTC
