### ISSUE TITLE
USER ISSUE: Joining Friend on Steam: Connection Failed

### ISSUE THREAD

**Issue by 1ucket** [StrangeLoopGames/EcoIssues#5965] opened 2018-03-12 21:18 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1.		Open Steam Overlay while Ingame
2.		Invite friend to join game
3.		Friend accepts invitation

**Expected behavior:**
Eco opens (if not already running) and a connection is established

**Actual behavior:**
The following Error message pops up:
`Connection Failed`

output_log.txt lists the error:
```
Could not get server info
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```

which I suppose is linked to this error (there's no times or dates in the log but the count fits)
This error occurs in both ways. Disabling the Firewall and Antivirus Software on both sides doesn't change this issue. We also deleted the Eco folder in the AppData and did a file check on Steam.

**Comment by alecpura** [comment] 2018-03-12 22:30
+1'ing this with another report from benlemay@outlook.com:

My 3 friends and me have bought Eco on steam, but we still can’t play together. Each time one of us try to join the world of a other one it won’t work and we received a error message with connection failed.

---

I've asked the user for more info in the meantime

**Comment by GophTheGreat** [comment] 2018-03-13 03:32
One more from cupcakes1132@gmail.com:

"Hello I bought the game on steam and I loaded up the game and tried to invite my friend to the game through steam and every time it said Connection Failed. I want to play this game with a friend but I can't and it's frustrating."

**Comment by MarjieAVolk** [comment] 2018-03-13 23:03
I would say try connecting directly by entering the server's IP address in the 'Join' screen.  The steam invite/join features are buggy.

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5238 and https://github.com/StrangeLoopGames/EcoIssues/issues/4909

**Closed by MarjieAVolk** 2018-03-13 23:03 UTC
