### ISSUE TITLE
tried to sell 1100 wheat at a store

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2872] opened 2017-11-21 01:12 UTC
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Value cannot be null.
Parameter name: key


Stack:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Eco.Gameplay.Items.InventoryChangeSet.MoveItemsInternal[TKey](Type itemType, Int32 quantity, Inventory source, Inventory destination, Func`2 sourceStackPredicate, Func`2 sourceStackOrder)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

```

**Comment by Arend90** [comment] 2017-11-21 01:37
https://www.dropbox.com/s/000o6jcada6441z/NewGame.eco?dl=0

**Comment by MarjieAVolk** [comment] 2017-11-29 18:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2936

**Closed by MarjieAVolk** 2017-11-29 18:29 UTC
Labels: Medium Priority
