### ISSUE TITLE
USER ISSUE: Repair Station and Research Table  won't work in room non existant Tier

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3362] opened 2018-01-11 19:28 UTC
**Version:** 0.6.4.0 alpha staging-9d99a945

![snap996](https://user-images.githubusercontent.com/29383891/34843043-494e30f2-f705-11e7-9686-e6de163572f7.png)
![snap997](https://user-images.githubusercontent.com/29383891/34843044-4966935e-f705-11e7-8381-f1973e417d55.png)
![snap999](https://user-images.githubusercontent.com/29383891/34843119-7ccd4e86-f705-11e7-8e91-eee834528d1c.png)
![snap1002](https://user-images.githubusercontent.com/29383891/34843120-7cebb3a8-f705-11e7-9ac1-6dd441f65218.png)
as you can see it requires +materials (whatever they may be)

**Comment by MarjieAVolk** [comment] 2018-01-11 19:29
I just saw this too O.o

**Comment by MarjieAVolk** [comment] 2018-01-11 19:39
Okay looks like this is because there isn't anything in the indicated tier >>  So caused by https://github.com/StrangeLoopGames/EcoIssues/issues/3229

But I'm going to add better handling for this case anyway

**Comment by MarjieAVolk** [comment] 2018-01-11 19:41
In case you haven't heard this yet, the tier thing is just a display problem in the tooltips.  You should be able to build a house out of hewn logs

**Comment by Conchipedia** [comment] 2018-01-11 19:44
i was just following the Tutorial so it came up this way, i didn'
t want to try a workaround

**Comment by Conchipedia** [comment] 2018-01-11 21:16
i don't see this as a tool tip problem as its is showing that it needs 18 (+ materials) in both the Tooltip and table status (which is red meaning that a room totally made of logs using a hammer is not being detected as any type of material that the tables require)

**Comment by MarjieAVolk** [comment] 2018-01-11 21:24
Are you using logs or hewn logs?

**Comment by Conchipedia** [comment] 2018-01-11 21:28
logs as i cannot make hewn logs as i dont have 38 points to make them on a table that wont work on a room that will not see logs

**Comment by MarjieAVolk** [comment] 2018-01-11 21:37
Yeah logs are no longer going to be a valid material, only hewn logs count.  Think you are getting this figured out in discord though now.

**Comment by Conchipedia** [comment] 2018-01-12 18:12
i realised i had a Hewn Log in a stockpile and i used it in the room as part of wall seen in picture bottom left
![snap1044](https://user-images.githubusercontent.com/29383891/34888795-855e1f44-f7c3-11e7-8827-b0718c8cd029.png)
but the table is still Not seeing this as part of it's  needs (1 hewn log should equal 1 /18 +materials)

**Comment by MarjieAVolk** [comment] 2018-01-12 18:47
Yeah, you guys were right, it wasn't just a display bug >> lolol.  I've got a PR out to fix this, so it will be fixed in the next staging build

**Comment by MarjieAVolk** [comment] 2018-01-12 21:52
Fixed in next staging build

**Closed by MarjieAVolk** 2018-01-12 21:52 UTC
Labels: High Priority
