### ISSUE TITLE
Resizing a full economy viewer is too slow

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2064] opened 2017-09-07 19:33 UTC
Need to disable re-layout when resizing, at least for this window, and probably most.

**Comment by MarjieAVolk** [comment] 2017-10-12 20:55
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2491

**Closed by MarjieAVolk** 2017-10-12 20:55 UTC
