### ISSUE TITLE
Lag returns?

### ISSUE THREAD

**Issue by Gjafar** [StrangeLoopGames/EcoIssues#4120] opened 2018-02-08 17:38 UTC
Same lag is back on my server as 7.0.2 had. 
Can anybody confirm?

**Comment by ChrisMayhew** [comment] 2018-02-08 18:10
People on my server are reporting issues with lag

**Comment by Gjafar** [comment] 2018-02-09 16:13
I figured out another lag wich comes from, when someone claims something.

**Comment by MarjieAVolk** [comment] 2018-02-09 19:19
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4097

We have had a couple reports of lag when claiming property

**Closed by MarjieAVolk** 2018-02-09 19:19 UTC
