### ISSUE TITLE
Beet Campfire Salad inside an Icebox, approx 7 second delay to showing card. reproducible

### ISSUE THREAD

**Issue by MNight75** [StrangeLoopGames/EcoIssues#25130] opened 2024-09-03 04:31 UTC
This started at the latest update today. 
It happens only for Beet Campfire Salad, other foods tested did not display this behavior.  
It happens only when Beet Campfire Salad is inside an Icebox, any slot gives same results, and happens in a predictable reproducible and consistent manner. 

If the Beet campfire Salad  inside the icebox is hovered over, the tool tip box is delayed while a pointer flashes for approximatly 7 seconds before displaying the tool tip. All over foods, and all other containers (with beet campfire salad) do not display this abberant behavior and their tooltips pop up promptly.

**Comment by D3nnis3n** [comment] 2024-09-03 04:55
Not reproducible:

https://github.com/user-attachments/assets/69926c0a-39dc-4179-a1a0-4f95de48e64f

Would need consistent repro steps.

**Comment by D3nnis3n** [comment] 2024-09-08 22:20
Closing due to not being reproducible.

**Closed by D3nnis3n** 2024-09-08 22:20 UTC
Labels: Status: Needs Information, Status: Not reproduced
