### ISSUE TITLE
Storage UI is expensive in CPU terms on the clientside to open

### ISSUE THREAD

**Issue by dimensionwizard** [StrangeLoopGames/EcoIssues#6220] opened 2018-03-18 03:41 UTC
Accessing certain UIs causes a significant CPU spike and stalls for a somewhat sizable length of time. On my i7 4770k, it's usually slightly less than a second which isn't a huge deal, but on older processors this can be significantly time-consuming. For my sister's old core 2 q6600, the length of time is several seconds. I would guess that the issue here is that there are a lot of UI elements are being constructed and there is no kind of caching or object recycling involved to reduce the amount of work done each time... but that's just speculation on my part. I'm assuming it's UI related mostly just on account of stuff like moving items from stockpile to stockpile with a shovel not incurring such a penalty.

I don't know enough about the underlying code here to know why this is really, but specifically it seems like anything with a lot of linked stockpiles/containers is subject to these sorts of slowdowns.

**Comment by MarjieAVolk** [comment] 2018-03-21 21:01
You mean opening the ui is expensive, right? Not leaving it open?

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3110

**Closed by MarjieAVolk** 2018-03-21 21:01 UTC

**Comment by dimensionwizard** [comment] 2018-03-21 22:59
Yep, only the initial creation. I guess I didn't look far enough back in the bug tracker. Thanks.

**Comment by MarjieAVolk** [comment] 2018-03-21 23:17
Yep it's been slow for a while :P
