### ISSUE TITLE
Iron Hoe doesnt show in hand and only shows green out line not clickeble

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2877] opened 2017-11-21 11:10 UTC
![image](https://user-images.githubusercontent.com/31536813/33069430-d4180c90-ceb4-11e7-933f-57ca9c1deb2b.png)

we cant use the Iron Hoe it just gives a unclickeble greenline

**Comment by Arend90** [comment] 2017-11-21 14:07
![image](https://user-images.githubusercontent.com/31536813/33076696-b92bc7a0-cecd-11e7-8b0f-3e42e24d5574.png)
steel hoe does the same

**Comment by Arend90** [comment] 2017-11-21 14:09
![image](https://user-images.githubusercontent.com/31536813/33076769-f861ad22-cecd-11e7-999d-58e4a9a044fc.png)
and the modern hoe

**Comment by Conchipedia** [comment] 2017-11-21 16:08
just used an Iron hoe, it IS usable just very slow (might be due to the Lag) and not visible in hand
![snap609](https://user-images.githubusercontent.com/29383891/33083006-1eecf192-ced6-11e7-8b5b-de365498af5a.png)
![snap610](https://user-images.githubusercontent.com/29383891/33083037-30143be2-ced6-11e7-839c-a255bb8ba22a.png)

**Comment by Arend90** [comment] 2017-11-21 16:28
sorry i just clicked to short as the hoe takes longer to hold the mouse then a axe or something

**Comment by MarjieAVolk** [comment] 2017-11-21 18:25
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2478 - we haven't got models for all the new tools yet, working on it

**Closed by MarjieAVolk** 2017-11-21 18:25 UTC
