### ISSUE TITLE
USER ISSUE: Crash When Posting a Contract

### ISSUE THREAD

**Issue by DeXr0** [StrangeLoopGames/EcoIssues#12686] opened 2019-07-01 06:41 UTC
**Version:** 0.8.2.4 beta

**Steps to Reproduce:**
1.Click Create Contract.
2.Select anything that requpres a player to have a drop off location, 
3.Click Doposit in
4. BOOM CRASH, no error, nothing.

I have been able to reproduce this sevreal times
NOTE: my Brothers game dont do this, 

**Expected behavior:**
I asume i would be able to select a storage box for player to drop off. 

**Actual behavior:**
crash to desktop. 

**Do you have mods installed? Does issue happen when no mods are installed?:**
crash to desktop.  EDIT: NO mods installed Client side i have a server mod for discord.

**Comment by SlayksWood** [comment] 2019-07-01 06:57
@DeXr0 
please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
What language of server? What language do you have at client?

**Comment by DeXr0** [comment] 2019-07-01 08:06
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3344479/Player.log)
English for both Client and Sever, Also i can give server logs i own the server.

Thank you :D

**Comment by beastyn** [comment] 2019-07-01 09:27
@DeXr0 
I need some more information if you don't mind.
Can you show some screenshots?
- window with contacr posting process and inputed data
- map with property location which is used in the crashed contract (and property coordinates).
- is it new server or migrated from old version?
Thank you!

**Comment by beastyn** [comment] 2019-07-01 09:34
Also it would be great to have your save with .db and server log.
https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by mirasrael** [comment] 2019-07-01 15:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12667

**Closed by mirasrael** 2019-07-01 15:23 UTC
Labels: Fixed, Investigate, Needs Information

**Comment by DeXr0** [comment] 2019-07-02 01:03
window with contact posting process and inputted data
https://gyazo.com/257bfb4406c8aef760da4877f1d46c11
map with property location which is used in the crashed contract (and property coordinates).
https://gyazo.com/89f3f2b1f017f6d688ae4ee19082576c
The Server is brand new, 

Here is the server save, and Db file. 

https://drive.google.com/drive/folders/1a7nPpQGXj7taAlVCj0xviVHcNEvHeRrI?usp=sharing

**Comment by DeXr0** [comment] 2019-07-02 01:11
Oof, I just seen this was closed, was this resovled ? and are the files still needed @

**Comment by beastyn** [comment] 2019-07-02 03:41
@DeXr0 
Crash is fixed and fix will be released with the next update.
But your information is still valuable for checking and testing purposes, Thank you.
