### ISSUE TITLE
USER ISSUE: pls ae oe ue

### ISSUE THREAD

**Issue by ownyHD** [StrangeLoopGames/EcoIssues#4507] opened 2018-02-14 09:53 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**

**Expected behavior:**
german letters pls

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-14 21:37
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2656

If you want to make a note of specific characters that you want, I can make sure those get added when we address that.

**Closed by MarjieAVolk** 2018-02-14 21:37 UTC
