### ISSUE TITLE
Water World Bug

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#2485] opened 2017-10-09 04:22 UTC
For some odd reasons my server, and a few others are flooding. Co2 Jumps up like crazy for no reasons and floods the world. This has happened in a world with no Blasters or pollutions.

**Comment by MasterWhoMW** [comment] 2017-10-09 05:28
https://drive.google.com/file/d/0B5OT8hSaePzAbjVFX21YcWJSUE0/view?usp=sharing

Here are the server files, along with the backup so you can see before and after, as well as watch the world drown itself

**Comment by MarjieAVolk** [comment] 2017-10-09 17:16
Got a couple reports of this, closing this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2486 - I'll copy your link over there, thanks

**Closed by MarjieAVolk** 2017-10-09 17:16 UTC
