### ISSUE TITLE
Can't claim property if stockpile is centered on plot

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3077] opened 2017-12-11 21:31 UTC
![image](https://user-images.githubusercontent.com/6262198/33854696-706a86a0-de77-11e7-9283-160f3c66aeb4.png)

There is no way to claim this land as long as this stockpile is here

**Comment by MarjieAVolk** [comment] 2017-12-11 21:39
Actually, duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1493

**Closed by MarjieAVolk** 2017-12-11 21:39 UTC
