### ISSUE TITLE
USER ISSUE: Broke the Vote system

### ISSUE THREAD

**Issue by MasterJochen** [StrangeLoopGames/EcoIssues#4441] opened 2018-02-13 07:27 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Add new Law. Type the word "für" in 

**Expected behavior:**
Law should work 

**Actual behavior:**
It did break the DB i gues no other votes where exepted. The web browser allway returned the red line wich normaly shows an error but this time its just empty without message

**Comment by MasterJochen** [comment] 2018-02-13 14:08
I fixed it with the /clearlaws command. Before noone was abel to vote on anything

**Comment by MarjieAVolk** [comment] 2018-02-13 21:00
Sounds like the law system doesn't like the umlaut.

**Comment by MasterJochen** [comment] 2018-02-14 05:30
Some Update from the steam Forums: Users wrote

My name has an accent mark in it. will that mess it up?
I changed my name and now its working

**Comment by MarjieAVolk** [comment] 2018-02-14 21:47
Yeah it seems that will mess things up.  We are having a variety of issues with special characters and foreign characters, since the number of Europeans playing the game has gone up like crazy this week.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4242

**Closed by MarjieAVolk** 2018-02-14 21:47 UTC
Labels: Medium Priority
