### ISSUE TITLE
server crash dumps Possible new issue

### ISSUE THREAD

**Issue by Stressinout** [StrangeLoopGames/EcoIssues#4444] opened 2018-02-13 10:19 UTC
asked my server company whats going on when we start getting 10+ people on the server as to why we are getting crashes all when we start getting that kind of people. They told me that it isn't hardware and we are not maxing out our server hardware and that there is a crash dump that comes up with most of the crashes. So just wanted to add this and see if you guys have this issue already or if you need it to help with a fix. Here is there a message with the crash dump issue.

2/13/2018 6:25:26 AM - Pam D:
Hi Doug

This is a known issue and several bugs reports already have been logged about it.  You might want to go an add your comments about.

You are running world sizes that are known to be less stable and has more performance issues then the smaller worlds.    One of the reasons the default would size was dropped in 7.0 was due to performance.  There is a very big difference just in load times between a 2X world and 4X world

Because performance was so ghastly in 7.08 and SLG recognized that it was game, not hardware thy turned off all the stat reporting systems in 7.10 - you can read about this in the announcement channel.  They are working hard on this and have a new update scheduled for later today, again more performance enhancements.  Currently, some of the biggest concurrent servers are running about 20 people and they are stating they are totally unplayable, are maxed on TAM and CPU any time they get over 15 people.  I have checked you activity graphs and that does not seem to be your issue.  

Also, you need to look into the crash files that are generated and get them to the devs,  Most of that does not appear to be resource issue but actual problems in the code that need to be addressed.  The devs may very well want a copy of your world so they can install it and repro your issues. 

This is the most common report of what is happening when you.  It's a bit hard to figure out what is happening without knowing what was happening that set this error to happen and shut the server down:

```
Dump Time
02/13/2018 01:44:54

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
```

 We actually are running latest gen Intel in out Houston dc and there is not really any way we can get better.  We are neither RAM or CPU bound.  We have noticed that out UK dc does seem to handle Eco better although it is 1-year-old Tech but it is AMD and not INTEL - it may be that at this time the threading done AMD's way just is a better environment for ECO.

You definitely were experiencing the stats system caused lag spikes that lead to that system being shut off and as you can see they have dropped off.  https://gyazo.com/84bf8d112ec3c0908a7c8462d224026e

**Comment by MarjieAVolk** [comment] 2018-02-13 22:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368.  You can track the issue progress there.

**Closed by MarjieAVolk** 2018-02-13 22:29 UTC
Labels: High Priority
