### ISSUE TITLE
USER ISSUE: Dissapearing trees

### ISSUE THREAD

**Issue by CherokeeSpiritBear** [StrangeLoopGames/EcoIssues#11704] opened 2019-03-18 03:23 UTC
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
Cut down tree

**Expected behavior:**
Tree should fell down and let me cut it into logs

**Actual behavior:**
Tree will dissapear or become untargetable. Which a dc/rc will normally fix.

**Do you have mods installed? Does issue happen when no mods are installed?:**
^^^ The above section is not located on the ingame "report a bug" option, but no. There are no mods installed.

**Comment by D3nnis3n** [comment] 2019-03-19 14:37
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11487

**Closed by D3nnis3n** 2019-03-19 14:37 UTC
