### ISSUE TITLE
Really really bad Frame Rate 0.7.4.4 Beta

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#7800] opened 2018-05-17 03:52 UTC
Version: 0.7.4.4 Beta

Steps to Reproduce:

Just try and play the game and watch it lag to hell

Expected behavior:

An actual half decent frame rate of maybe around 32 FPS. 

Actual behavior:

Wow this is just horrible getting between  6 - 9 Frames per second (FPS) 

You really need to work on this game and make it a heck of a lot better.

Wow this is just horrible and I am running on an I7 as well here.. with 16 GB of RAM
AMD Radeon HD 7700 Video card. 

Intel Core i7-2600 3.40 GHZ 
16 GB RAM
AMD Radeon HD 7700 Series Video Card
DirectX 12
Page File: 9809 MB used out of 13963 MB
Windows 10 Pro (64 bit) Build 16299

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2011561/DxDiag.txt)

And I have my settings turned down a lot as well Here are the screenshots of my 
Graphics settings and Advanced Graphics settings. 

![eco graphics settings may 16 2018](https://user-images.githubusercontent.com/38896397/40155659-38f8e224-5952-11e8-959b-284bda7fbea3.jpg)

![eco advanced graphics settings may 16 2018](https://user-images.githubusercontent.com/38896397/40155662-3db92e54-5952-11e8-91fb-a3bf726f9ed7.jpg)

Please fix your game immediately this is just horrible it gets to the point where it just
unplayable! 

This is more than just optimization this is a totaly overhaul of your graphics system
and how things are handled this is absolutely no good the way things are now. 

Please fix this immediately!

**Comment by metachronism** [comment] 2018-05-30 19:13
closing as dupe of #6775

**Closed by metachronism** 2018-05-30 19:13 UTC
Labels: High Priority

**Comment by thereporter42** [comment] 2018-08-31 15:18
Why was this closed.. the issue was never resolved!  The problem is still ongoing!
