### ISSUE TITLE
USER ISSUE: Icon of items

### ISSUE THREAD

**Issue by Emposa** [StrangeLoopGames/EcoIssues#4875] opened 2018-02-20 19:40 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Sometimes when you click and drag items it gets dropped and the icon stays on the screen at all times and you have to relog in order to get the item back and completely reboot the game to get the icon to go away.

**Expected behavior:**
Icon shouldn't have stayed on screen.

**Actual behavior:**
Icon persists on screen even when relogged. Dissappears when game is rebooted.

**Comment by sirPattrick** [comment] 2018-02-21 01:45
Is this in Multiplayer or Single Player?  And if it happens again, Pictures are always nice :)

**Comment by Emposa** [comment] 2018-02-21 17:21
This happened in multiplayer, but ever since I linked my steam account to the game for the life of me I couldn't replicate this issue. It only happened on the game downloaded from the official Strange Loops Eco website.

**Comment by MarjieAVolk** [comment] 2018-02-22 23:23
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-02-22 23:23 UTC
