### ISSUE TITLE
USER ISSUE: Lost ability to click on hotkeys again

### ISSUE THREAD

**Issue by github-center** [StrangeLoopGames/EcoIssues#24979] opened 2024-06-13 00:20 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
I went to place settlement table this time. It placed but I then clicked on hammer to pick it back up and it wouldn't.

**Expected behavior:**
That I can continue playing and pick up the table

**Actual behavior:**
I can no longer pick up anything or press any hotkeys. I have to logout to get back to normal.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-06-13 05:49
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24977, please answer the request for information there.

**Closed by D3nnis3n** 2024-06-13 05:49 UTC
