### ISSUE TITLE
Water rendering tied to camera

### ISSUE THREAD

**Issue by OscarRexid** [StrangeLoopGames/EcoIssues#11041] opened 2019-02-02 14:05 UTC
as you can see by this gif the position of the water is tied to the camera and it is kinda annoying, the water also has no eart curvature like the rest of the world has

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/42250699/52165053-cbd6a780-26fb-11e9-8e34-1065e2c0f5f9.gif)

**Comment by redwyre** [comment] 2019-02-02 16:03
What version are you running?

**Comment by OscarRexid** [comment] 2019-02-02 16:31
bleeding edge (8.0.0 atm)

**Comment by OscarRexid** [comment] 2019-02-02 16:31
I restarted server + game and now it is gone

**Comment by OscarRexid** [comment] 2019-02-02 16:32
let me know if you need anything like specs or settings etc

**Comment by redwyre** [comment] 2019-02-02 17:05
can you upload your log file from C:\Users\[YOUR_USERNAME]\AppData\LocalLow\Strange Loop Games\ECO ?

**Comment by SeanAtr0n** [comment] 2019-02-02 21:09
duplicate of the transparency shader issue, should be resolved next build

**Closed by SeanAtr0n** 2019-02-02 21:09 UTC
