### ISSUE TITLE
Server Crash - Corrupt backups - InvalidCastException

### ISSUE THREAD

**Issue by ThatOneDolpgin** [StrangeLoopGames/EcoIssues#24900] opened 2024-04-21 09:13 UTC
SERVER FILES - https://drive.google.com/file/d/1_x9YtFBKqfRBhhIYdcDkfZOZ2m2gMtRU/view?usp=sharing
[log_240420083900.log](https://github.com/StrangeLoopGames/EcoIssues/files/15051268/log_240420083900.log)

[08:53:06.174] [38] [Error] [Eco] Failed to start the server. Exception was Exception: InvalidCastException
Message:Object cannot be stored in an array of this type.
Source:System.Private.CoreLib

System.InvalidCastException: Object cannot be stored in an array of this type.
   at System.Array.InternalSetValue(Object value, IntPtr flattenedIndex)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToArray(BinaryReader reader, Array array, Int32 index)
   at Eco.Core.Serialization.Serializers.DefaultArraySerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.BasicSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo member)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeReferenceableEnumerable(BinaryReader reader, Object decodeTarget, Int32 numElements)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream)
   at Eco.Core.Serialization.DataStore.<>c__DisplayClass49_1`1.<LoadAsync>b__1()
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Error(s) occurred when loading World (Object cannot be stored in an array of this type.)

**Comment by D3nnis3n** [comment] 2024-04-22 03:35
Please provide more context to the error, especially when it appeared and what was done before that.

**Comment by ThatOneDolpgin** [comment] 2024-04-22 09:32
Hi D3nnis3n

Essentially nothing was done at all. The server is run 24/7. We use the eco integrated maintenance file to manage the shutdown of the server at which point we give it a few minutes to fully close before a cronjob brings the server back online. For whatever reason the server then didn't come back up and was corrupt up until around 9 hours before. It must have crashed somewhere around 00:00 because all backups after that time didn't work but the 23:00ish one did.

**Comment by D3nnis3n** [comment] 2024-04-22 10:32
Is there a logfile of that server crash at 0:00? There is not enough information to even start an investigation, all info so far rather tends to point to some issue outside of Eco, given the savegames did no longer get stored correctly on disk to which Eco does nothing but requesting to write on storage.

**Comment by D3nnis3n** [comment] 2024-04-24 03:25
That logfile does not indicate any form of crash whatsoever, it is a normal shutdown. With the server not being able to load directly after this successful shutdown, it seems something has failed the write operation of this save (and all backups before) silently, which doesn't happen when Eco causes a failure in saving.

Unfortunately there currently is absolutely no hint towards any fault on Eco's side or anything we could investigate. Feel free to provide any further information you think could help. We'll keep the issue open a few more days to see if someone else had a similar experience, but otherwise it would be a "not reproduced" closure.

**Comment by D3nnis3n** [comment] 2024-04-30 16:37
Closing due to not reproducible and no further information provided - please feel free to open a new issue when you can provide more info or a reproduction case. It does seem like something went wrong on the host system at that time though, given all the backups in that time span were saved as corrupted files, as in the data state in the saves was not only corrupted, but the files itself were simply not complete and considered a valid save game at all anymore.

**Closed by D3nnis3n** 2024-04-30 16:37 UTC
Labels: Status: Needs Information
