### ISSUE TITLE
USER ISSUE: Settlement > Influence tab make me crash

### ISSUE THREAD

**Issue by Eliatrom** [StrangeLoopGames/EcoIssues#24199] opened 2023-12-14 15:52 UTC
\
**User Id: (slg91675)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Open Ecopedia
2. Go to Settlement tab
3. Click on Influence

**Expected behavior:**
Open Influence tab so we can read it

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Server encountered an exception:

<size=60.00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.EcopediaSettlementConfigData.GetEcopediaData(Player player, EcopediaPage page)
</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13675442/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13675443/Player-prev.log)

**Comment by D3nnis3n** [comment] 2023-12-14 16:37
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24116

**Closed by D3nnis3n** 2023-12-14 16:37 UTC
