### ISSUE TITLE
USER ISSUE: Floating Grass

### ISSUE THREAD

**Issue by Brianqq3** [StrangeLoopGames/EcoIssues#4261] opened 2018-02-10 17:26 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Dig any tiles that have grass growing on top - the grass does not disappear after removing all ground blocks

**Expected behavior:**
Grass should disappear - floating grass is kind of creepy

**Actual behavior:**
Grass remains floating in the air.

**Comment by ecoemmeck** [comment] 2018-02-10 18:14
I've noticed this as well. Usually a quick disconnect and reconnect does the truck and the grass is gone

**Comment by MarjieAVolk** [comment] 2018-02-13 05:07
@metachronism I believe this is a duplicate of another bug, but couldn't find it.  I think I might have closed it.  Anyway another person said re-logging fixed the issue, so I thought maybe they were just seeing that the world tick destroyed the plant and it happened to be correlated with re-logging since that just took time.  But I made sure that plants were explicitly deleted when using tools, so I believe this is some kind of client sync problem.

**Comment by metachronism** [comment] 2018-03-15 23:49
pretty sure this is resolved now with server optimizations

**Closed by metachronism** 2018-03-15 23:49 UTC
Labels: Medium Priority
