### ISSUE TITLE
7.2.0 Staging 08551408-Players being kicked with "the given key was not present in the dictionary"

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#4921] opened 2018-02-22 00:12 UTC
I was just standing there, doing nothing. I was the first one to be kicked, then other players were randomly kicked. 
[ClientUpdateException KeyNotFoundException 02210524.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1746165/ClientUpdateException.KeyNotFoundException.02210524.txt)
[ClientUpdateException KeyNotFoundException 02210441.ecodmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1746168/ClientUpdateException.KeyNotFoundException.02210441.ecodmp.txt)
[ClientUpdateException KeyNotFoundException 02210434.ecodmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1746170/ClientUpdateException.KeyNotFoundException.02210434.ecodmp.txt)
[ClientUpdateException KeyNotFoundException 02210407.ecodmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1746172/ClientUpdateException.KeyNotFoundException.02210407.ecodmp.txt)

**Comment by Quicksilv3r710** [comment] 2018-02-22 01:04
Update: Happens when a player tries to hunt. Everyone will keep getting kicked. Doesn't seem to happen everytime though.

**Comment by MarjieAVolk** [comment] 2018-02-22 22:44
```
Exception
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Plugins.Networking.QuadTree`1.Remove(T item)
   at Eco.Shared.Networking.NetObjectManager.Remove(INetObject netObject)
   at ArrowEntity.Destroy()
   at ArrowEntity.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
```

**Comment by MarjieAVolk** [comment] 2018-02-22 22:46
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4951

**Closed by MarjieAVolk** 2018-02-22 22:46 UTC
