### ISSUE TITLE
Avatar-Creation broken

### ISSUE THREAD

**Issue by Fjokki** [StrangeLoopGames/EcoIssues#25316] opened 2024-12-14 11:29 UTC
I created a Avatar, by setup clothes (hat) the Avatar goes compleatly pink. Now the Avatar-Menu is a blue screen (with the eco-Symbol) and no options.
![grafik](https://github.com/user-attachments/assets/0a6b8fa9-b482-4232-9b14-61091896e13c)
![grafik](https://github.com/user-attachments/assets/89f22a04-35e6-4e75-8990-8f34bae5d838)

**Comment by D3nnis3n** [comment] 2024-12-14 12:33
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25311

**Closed by D3nnis3n** 2024-12-14 12:33 UTC
