### ISSUE TITLE
USER ISSUE: Cannot pick up items / Struggling to

### ISSUE THREAD

**Issue by jackadgery** [StrangeLoopGames/EcoIssues#23430] opened 2022-09-10 08:05 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.6.1 beta release-337

**Steps to Reproduce:**
Unsure. I've dug deep in sandstone and reached iron, and that's when it started

**Expected behavior:**
I should be able to look at an item and then interact with it, like pieces of iron ore, or animal corpses.

**Actual behavior:**
Instead, I look at the item, and it doesn't register as something I can interact with, until I change tool, or just not at all.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-09-10 13:10
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20414

**Closed by D3nnis3n** 2022-09-10 13:10 UTC
