### ISSUE TITLE
USER ISSUE: Avatar froze after pulling wheelbarrow

### ISSUE THREAD

**Issue by powergungirl** [StrangeLoopGames/EcoIssues#23384] opened 2022-09-01 11:35 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.6.0 beta release-334

**Steps to Reproduce:**
1. Press E Avatar pulled wheelbarrow = ok
2. Press E Avatar parked wheelbarrow but Avatar froze and cant use tools = fault

**Expected behavior:**
2. Press E second time Avatar parked wheelbarrow, arms in normal position and it can use tools

**Actual behavior:**
2. Press E second time Avatar parked wheelbarrow, froze in position like pulling wheelbarrow and can´t use tools.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-09-01 17:44
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23376

**Closed by D3nnis3n** 2022-09-01 17:44 UTC
