### ISSUE TITLE
[0.9.3.0 beta staging-1964]Hide Settlement ecopedia entry

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21091] opened 2021-03-25 14:27 UTC
Need to hide Settlement entry in ecopedia(blank) as its not used currently.

**Comment by WeaselDog** [comment] 2021-03-26 00:33
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20858

**Closed by WeaselDog** 2021-03-26 00:33 UTC
Labels: Category: Ecopedia, Priority: High, Squad: Redwood, Type: Bug
