### ISSUE TITLE
Singleplayer didnt work, server no start up

### ISSUE THREAD

**Issue by DrPeppiX** [StrangeLoopGames/EcoIssues#4278] opened 2018-02-11 00:15 UTC
This happen after name the world and pick the specs and click to create it.

[Crash_AggregateException_02113133.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1713897/Crash_AggregateException_02113133.zip)

**Comment by MarjieAVolk** [comment] 2018-02-13 04:52
Closing as duplicate of #4305. You can continue tracking the issue there.

If you generate a new world instead, it may work for you. If that still doesn't work, you can try launching the Eco Server tool separately and generating the world there. Other players have reported that that works for them.

**Closed by MarjieAVolk** 2018-02-13 04:52 UTC
