### ISSUE TITLE
USER ISSUE: The Hole in the Ground[EDIT: Definitiv Problems with 0,0 blending of the World]

### ISSUE THREAD

**Issue by Leviatay** [StrangeLoopGames/EcoIssues#4948] opened 2018-02-22 13:38 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Just Walk on tis weired place ...
No serious, i've made the beginning for a street. So i take my shovel and made a phat for a stone way, and you can say 1 of 3 times around this one place u fall into the void, or all light (sun) and graphics are gone and u see the the skybox (Moon + Stars+Black )all around you. Mostly such things happens when i take my wooden cart (idk if its also with a small or with the even better one(the one with the engine). And yes u can see ground and everything but you still fall. 
May Coordinates Helps Center:0,719. Should help at 0,x 
Just tried something, your main Foxus should be on 0,x 
Think you could have a problem with the blending of the world :s

**Expected behavior:**
Standing on the Ground

**Actual behavior:**
Insted u fall :) see Steps to reproduce

**Comment by Leviatay** [comment] 2018-02-22 13:54
Tested it now on a new World, there are too some Points along 0,x and x,0 where this happens. Seems like there is the Problem

**Comment by metachronism** [comment] 2018-03-22 17:27
closing as dupe of prior chunk issues, most resolved in 7.3

**Closed by metachronism** 2018-03-22 17:27 UTC
Labels: High Priority
