### ISSUE TITLE
real estate desk ignores room requirements

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#10735] opened 2019-01-18 02:01 UTC
placed one outside and it works fine

**Comment by Conchipedia** [comment] 2019-01-27 16:38
also the Map Disappears from it when restarting a singleplayer game
![snap3990](https://user-images.githubusercontent.com/29383891/51803812-1b772800-2251-11e9-8245-2cb08ae4dbf3.png)
first tried disconnecting then reconnecting (nothing appeared) but does reappear as soon as minimap is opened.
![snap3991](https://user-images.githubusercontent.com/29383891/51803854-888abd80-2251-11e9-8ef4-7fc79f0b63da.png)
this happens after every new load of game, and as far as i can tell if you close the minmap screen that will also stop the map from opening to full size
![snap3992](https://user-images.githubusercontent.com/29383891/51803888-eae3be00-2251-11e9-8588-5ed23f1be9f7.png)

**Comment by DragonSupremacy** [comment] 2019-02-04 00:35
Just tried to transfer ownership from a player to me, both being admin. Tried relogging, replacing the real estate desk, changing currency type, currency amount, but none of them allow the actual buying of deeds

**Comment by D3nnis3n** [comment] 2019-04-26 11:13
I'm closing this issue for working as intended, Sean. The actualy functionality of selling does not work, the only thing that works is sorting your property - and considering the only way to do this is the real estate desk i don't feel that should be limited to a housing tier. (It's really the only way to claim a big city and divide the plots) The bank and registrar aren't either.

If you are unhappy with that, you can just reopen it.

**Closed by D3nnis3n** 2019-04-26 11:13 UTC
Labels: Investigate
