### ISSUE TITLE
Please add Korean font to main font

### ISSUE THREAD

**Issue by ciizel** [StrangeLoopGames/EcoIssues#4490] opened 2018-02-14 03:20 UTC
![2018-02-14 12 00 35](https://user-images.githubusercontent.com/1397782/36186241-19b2cd44-1181-11e8-8e35-0524a50460ca.png)

Please add Korean font to main font
The other Italic language is Korean Chinese.
I can not even check the names of people.

If it is difficult, please make a nickname setting function in game.

**Comment by MarjieAVolk** [comment] 2018-02-14 22:09
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4160

We do hope to support setting a nickname / changing your display name eventually.  I am going to look into non-english character support soon; I will see what I can do for Asian language support also.

**Closed by MarjieAVolk** 2018-02-14 22:09 UTC
