### ISSUE TITLE
Eco Tree - Foundation section has missing image

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17850] opened 2020-08-21 22:18 UTC
![image](https://user-images.githubusercontent.com/3536496/90939750-74715880-e3c1-11ea-9b8b-e843a9a7046d.png)

It appears if you click it though:

![image](https://user-images.githubusercontent.com/3536496/90939768-7cc99380-e3c1-11ea-82a7-c38ed53f02f5.png)

Check other pages for similar problem

**Comment by beastyn** [comment] 2020-08-24 04:32
Did not have it too. 
@johnkslg which browser do you use?

**Comment by j3fffff** [comment] 2020-09-14 17:44
It's probably because a lot of the blog images are located on steam's servers.
Because its a lot easier for @D3nnis3n to copy blog posts from steam to wordpress.
Otherwise, he would have to download each image and reupload into wordpress. 
Tedious, but then again, those steam links could stop being supported any time.
And it would help with load times probably.

**Comment by D3nnis3n** [comment] 2020-09-14 17:59
Try this: https://wordpress.org/plugins/automatic-upload-images/

**Comment by SlayksWood** [comment] 2020-10-02 12:45
Closing as not reproducable.

**Closed by SlayksWood** 2020-10-02 12:45 UTC
Labels: Category: Accounts, Status: Investigate, Status: Needs Information
