### ISSUE TITLE
USER ISSUE: Opening a storage chest makes it difficult to see items in backpack and toolbar

### ISSUE THREAD

**Issue by MKVangen** [StrangeLoopGames/EcoIssues#15795] opened 2020-04-15 11:05 UTC
**Version:** 0.9.0.0 beta staging-1512

**Steps to Reproduce:**
When opening a storage chest the screen around the storage window goes into a shade of gray / "dims". This does also effect the backpack window and the toolbar

**Expected behavior:**
The toolbar and backpack window should not be less invisible than the storage window. It makes moving around items between windows difficult

**Actual behavior:**
Everything around the storage window goes gray / "dims"

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. Issue happens without mods
![20200415130202_1](https://user-images.githubusercontent.com/37910364/79330385-b6712600-7f19-11ea-9bc1-bccd42c76d33.jpg)

**Comment by elfl0rd** [comment] 2020-04-15 11:32
Duplicate of #15765

**Closed** 2020-04-15 11:41 UTC
