### ISSUE TITLE
USER ISSUE: Auto Crop Growth

### ISSUE THREAD

**Issue by RnTmErr** [StrangeLoopGames/EcoIssues#4179] opened 2018-02-09 14:15 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. Plant Crops
2. Quit Game
3. Re-load Game

**Expected behavior:**
Crops should be at growth stage:seedling

**Actual behavior:**
Crops render fully grown ready to harvest

**Comment by MarjieAVolk** [comment] 2018-02-09 19:26
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4003

I assume you were playing on a local server?  That is, when you quit and reload, that also restarts the server?

**Closed by MarjieAVolk** 2018-02-09 19:26 UTC
