### ISSUE TITLE
Main menu layers after direct connection fail

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10868] opened 2019-01-24 13:45 UTC
![default](https://user-images.githubusercontent.com/4980243/51682020-6138b400-1ff7-11e9-9b02-69a4d02cc441.png)
(After attempt to direct connect to server with uncompatible version)

**Comment by metachronism** [comment] 2019-02-19 22:42
dupe of issue I wrote a design doc for, so closing

https://docs.google.com/document/d/1C_ioc-QGzcYjqG8MyKmXnPUUsZnj11dMPPJgRu01Nw0/edit#heading=h.fpa3wavstetd

**Closed by metachronism** 2019-02-19 22:42 UTC
Labels: Low Priority
