### ISSUE TITLE
USER ISSUE : Server Crash every X minutes, followed by a second one 2 min after

### ISSUE THREAD

**Issue by MorenaDaniel** [StrangeLoopGames/EcoIssues#6010] opened 2018-03-13 21:18 UTC
Hi everyone !

I'm making this issue because me and my friends are both being kicked of my server every X minutes and shortly after there is always a second kick. X minutes represent between 10 and 20 minutes.

Here is a log of the dump : 
--BEGIN DUMP--
Dump Time
03/13/2018 20:10:42

Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

La valeur ne peut pas être null.
Nom du paramètre : item

Stack:
   à System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   à System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   à Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   à Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   à Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   à Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   à Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   à Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   à Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   à Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   à Eco.Shared.Networking.NetPort.ProcessBuffer()
   à Eco.Shared.Networking.NetPort.Update()
   à Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

It is Always the same DUMP.

Thanks and have a good evening.

**Comment by MarjieAVolk** [comment] 2018-03-13 23:50
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5804 - Although that one is only kicking people, not crashing the server, so that is odd.  I guess it must be because you are running the server locally, so when you get kicked the server goes down.

**Comment by MarjieAVolk** [comment] 2018-03-13 23:51
If that is indeed the case, you may have a better experience if you run the server standalone, using the Eco Server tool, since that will mean you can just rejoin when this happens instead of having to restart the server.  Other than that, I don't yet know how to fix this.

**Closed by MarjieAVolk** 2018-03-13 23:50 UTC
