### ISSUE TITLE
USER ISSUE: Inventory Bug

### ISSUE THREAD

**Issue by MSemelka** [StrangeLoopGames/EcoIssues#5439] opened 2018-03-05 21:34 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Pull an item over a chest, or inventory, make it stuck if you want to place it. Aftert you close the chest the item will constantly stuck in your feeld of view. After a reconnect to the serve, it will mostly disappear. 

**Expected behavior:**
The item should be placet in the selectet inventory.

**Actual behavior:**
It stuck in a position between the to inventorys (backpack/chest).

**Comment by MarjieAVolk** [comment] 2018-03-05 23:04
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

Minimizing the game and reopening it should clear stuck icons, as a workaround.  It may also be the case that using a different mouse will make you see this problem less often.

**Closed by MarjieAVolk** 2018-03-05 23:04 UTC
