### ISSUE TITLE
USER ISSUE: Can't login

### ISSUE THREAD

**Issue by 007GaminG** [StrangeLoopGames/EcoIssues#5303] opened 2018-03-02 15:31 UTC
**Version:** 0.7.0.1 beta

**Steps to Reproduce:**
Im typing the correct password (i have registered on eco) but its still wrong!	

**Expected behavior:**
i should be able to login everytime

**Actual behavior:**
doesn't make me login!!

**Comment by 007GaminG** [comment] 2018-03-02 15:48
i have also tried 2 different profiles. ended with no luck!. should i take a refund?

**Comment by 007GaminG** [comment] 2018-03-03 01:46
username: Puddingen
where i bought it: Steam, got it yesterday ;)

**Comment by 007GaminG** [comment] 2018-03-03 01:51
its quite frustrating when you buy a game for 20 dollars and you can't even play it....hopefully this get fixed ;)

**Comment by MarjieAVolk** [comment] 2018-03-03 01:53
Oh, if you bought it on steam and you are being asked for your strange loop login information, then your steam login information is failing.  We need to figure out why your steam credentials are failing.  @Nanders ?

**Comment by 007GaminG** [comment] 2018-03-03 01:58
if this helps : http://steamcommunity.com/id/Tor-Andre/

**Comment by MarjieAVolk** [comment] 2018-03-03 01:59
In the mean time, you might try logging out and back in to steam, that sort of thing.

**Comment by 007GaminG** [comment] 2018-03-03 02:02
ok, im'a try

**Comment by 007GaminG** [comment] 2018-03-03 02:06
it works now <3 thanks for your work ;)

**Comment by 007GaminG** [comment] 2018-03-03 02:13
hmmm, i just opened the game, and now i can press new, join, and quit, etc. but when i try to make a world it just can't connect. what is the problem here?? wierd right!!?

**Comment by MarjieAVolk** [comment] 2018-03-07 20:15
Sorry for the delayed response - If you are still having this problem, you can try selecting 'Generate new' when creating the world.  If that doesn't work, you can also try creating a world with the 'Eco Server' tool.

**Comment by MarjieAVolk** [comment] 2018-03-07 20:22
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4935

**Closed by MarjieAVolk** 2018-03-07 20:22 UTC
Labels: High Priority
