### ISSUE TITLE
[0.9.2.x beta] Pending Elections icon always visible

### ISSUE THREAD

**Issue by Asharas** [StrangeLoopGames/EcoIssues#20262] opened 2021-01-30 11:10 UTC
The Pending Elections icon on the right side of the screen is always visible since 0.9.2

Seen on two different servers (launched pre 0.9.2 then upgraded) and a fresh 0.9.2.2 (for testing purpose).

**Comment by SlayksWood** [comment] 2021-02-01 11:42
I don't know why it appeared again. Seems it was fixed here #18393, but currently we have it again.

**Comment by SlayksWood** [comment] 2021-02-01 11:43
#18380

**Comment by beastyn** [comment] 2021-06-03 04:21
Could not reproduce on develop

**Comment by IcedForge** [comment] 2021-06-04 04:50
Seems like its fixed as a side effect, its working correctly on both staging and develop so will close this for now.

**Closed by IcedForge** 2021-06-04 04:50 UTC
Labels: Category: UI, Priority: Medium, Squad: Mountain Goat, Status: Not reproduced, Type: Bug
