### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by gopherkeeper** [StrangeLoopGames/EcoIssues#4755] opened 2018-02-18 06:14 UTC
I'm not sure what I did to cause this. I opened a store to browse, and the game crashed.
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1734449/error.log)

**Comment by MarjieAVolk** [comment] 2018-02-21 00:14
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4861

**Closed by MarjieAVolk** 2018-02-21 00:14 UTC
