### ISSUE TITLE
Black 'shadow' mesh planes appear in block geometry independent of block meshes.

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#18617] opened 2020-10-06 19:55 UTC
Not sure who is best to investigate solutions to this one since it's something fundamental with block meshes/chunks.

These have been around for a long time now, and they are always annoying to see because there is nothing you can do to remove them from the art side-- they are something going wrong with the shadow mesh builder, or something else in code. Basically, little planes of black will extend beyond the interior of block meshes in various consistent (when a particular arrangement of blocks exists, it seems) spots.

![image](https://user-images.githubusercontent.com/14983165/95250523-14970b80-07cf-11eb-8f13-9d8864b28f18.png)

**Comment by redwyre** [comment] 2020-10-14 14:42
@keegan-o 
That picture hurts my brain, the shadow mesh should only be generated from geometry that is along the face that would normally get removed. Can you provide more examples of blocks that cause it? Also if you could capture it in the scene view and turn on wireframe overlay that would help too.

**Comment by redwyre** [comment] 2020-10-27 17:38
Oh, I think I understand the picture now, the cladding is a texture with alpha that just makes a thin box? So the black part is because there is actually two thin boxes touching?

**Comment by redwyre** [comment] 2020-10-27 17:41
For this case specifically the only options would be on or off, but that's probably ok since the main wall would be casting a shadow. And other transparent materials like glass don't need a shadow.

**Comment by keegan-o** [comment] 2020-10-27 17:46
This does appear on other blocks with no transparency, I used to see it all the time on the ashlar stone ramp forms. Will keep an eye out for where it appears today, I know Rob encountered it when making flat steel blocks as well.

**Comment by keegan-o** [comment] 2020-10-27 20:47
![image](https://user-images.githubusercontent.com/14983165/97360060-e602d280-185a-11eb-9ebf-652240e71f5f.png)

Another example with framed glass roof and framed glass cube forms

**Comment by redwyre** [comment] 2020-10-28 06:44
can you show the wireframes? I can't see that's going on in that one

**Comment by MishkaFur** [comment] 2020-11-09 11:43
Happening with the new thicker glass (I believe this is the same issue)

![image](https://user-images.githubusercontent.com/61889138/98537136-b606f680-2280-11eb-9e59-c1ae9d8144ea.png)

**Comment by keegan-o** [comment] 2020-11-17 23:53
![image](https://user-images.githubusercontent.com/14983165/99464471-1505e480-28ed-11eb-8580-d4a0d80bc4d0.png)
Reinforced Concrete Road Barrier form

**Comment by Dave247** [comment] 2021-03-04 19:18
After testing the glass wall blocks I found that an issue will consistently happen when you have two blocks that connect through any of the three coordinates that are in multiples of 10.  For example, in the below screenshot the two separators that appear between 405,71,489/490 and 405,71,499/500 which makes me think it could have something to do with how the game processes chunks.
![20210305061259_1](https://user-images.githubusercontent.com/10183015/110017663-94270780-7d7a-11eb-9049-928df9a46d8d.jpg)

**Comment by StallEF** [comment] 2021-03-09 18:22
view from a solid block at the border of a chunk
![2021-03-09](https://user-images.githubusercontent.com/26339332/110518288-fbe3a680-811c-11eb-80a5-c5579de16711.png)

**Comment by mirasrael** [comment] 2021-03-19 14:26
@namquang93 can you investigate this task with help of Simon, but don't spend too much time on this. So if it can be fixed within a day then fix otherwise just add investigation results.

**Comment by StallEF** [comment] 2021-03-20 12:27
[0.9.3 staging-1959]  Corrugated Steel wall have it too - every 10 blocks in any direction (including height)
![black](https://user-images.githubusercontent.com/26339332/111869354-17a64280-8990-11eb-83d0-1954c7955c4f.jpg)

at the intersection of three directions 10x coordinates:
![glasswall](https://user-images.githubusercontent.com/26339332/111869434-85526e80-8990-11eb-9aa1-761ed275f060.png)

**Comment by TwixterZ** [comment] 2021-05-18 10:42
Fix tested and observed as of 9.4 Staging 1986.

Black border between glass is now fixed, however connecting glass on top of a lumber wall, still does not work properly (refer picture below)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/b095db0d-c767-4100-82e1-d49359d73dc2)

black line on corrugated steel wall still exist when looking at it from an angle (at border of 9th tile to 10th tile (height))

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ac1e2bea-add2-4206-ad0c-aa2e822b572f)

similar applies to reinforced concrete (road barrier) but lengthwise

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/b23de6e0-14d4-49ce-97c4-15335901a455)

**Comment by redwyre** [comment] 2021-05-18 14:32
Connecting glass on top of a lumber wall is working correctly, the lumber not showing the top is a separate issue.

The little black triangles on solid objects is probably a separate (though related) issue to the one that was fixed.

**Comment by SlayksWood** [comment] 2021-05-19 06:08
glass issue here#19427

**Comment by SlayksWood** [comment] 2021-05-26 06:39
Seems to be fixed for me. Waiting to another QA check and close it.

**Comment by TwixterZ** [comment] 2021-05-26 06:57
Fix checked and confirmed as of 9.4 Staging 1992

**Closed by TwixterZ** 2021-05-26 06:57 UTC
Labels: Category: Tech, Priority: Medium, Squad: Pumpkin, Status: Fixed
