### ISSUE TITLE
[Suggestion] Auto-Fuel

### ISSUE THREAD

**Issue by Molowa** [StrangeLoopGames/EcoIssues#4692] opened 2018-02-17 09:03 UTC
I would love to see the ability for something like the blast furnace to be automatically fueled by a nearby connected stockpile that has coal or another fuel resource in it. I hate having to stop and check on it every so often. Our server uses the blast furnace as a community furnace and having to constantly manually place fuel in it is tiresome.

**Comment by MarjieAVolk** [comment] 2018-02-23 22:31
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3225

**Closed by MarjieAVolk** 2018-02-23 22:31 UTC
Labels: Feature
