### ISSUE TITLE
USER ISSUE: Duplicate Carrying Resources

### ISSUE THREAD

**Issue by Trenix** [StrangeLoopGames/EcoIssues#5160] opened 2018-02-27 02:36 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Got disconnected from server.
2. Logged into server.
3. Two of my stockpiles were ontop of each other.
4. Move a pile of any resource in the stock pile into the other stockpile that is ontop of it and the resources duplicate indefinitely.

**Expected behavior:**
Two stockpiles should never be allowed to be ontop of each other. When they overlap in any way, blocks get duplicated.

**Actual behavior:**
Stockpiles were ontop of each other and allowed me to duplicate my resources.

**Comment by MarjieAVolk** [comment] 2018-02-27 18:41
This sounds like something that would happen when the server crashes and is reloaded - Did the server go down, in addition to you disconnecting?

**Comment by Trenix** [comment] 2018-03-02 02:48
Yes the server went down.

**Comment by metachronism** [comment] 2018-03-27 21:48
closing as dupe of #5090

**Closed by metachronism** 2018-03-27 21:48 UTC
Labels: High Priority
