### ISSUE TITLE
Water Not refilling gaps underwater or when taken from the shore

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#11132] opened 2019-02-07 09:13 UTC
**Version:** 0.8.0.0 beta

![snap4089](https://user-images.githubusercontent.com/29383891/52400834-30a54f80-2ab8-11e9-83c6-d103fc38ef5f.png)
![snap4090](https://user-images.githubusercontent.com/29383891/52400835-313de600-2ab8-11e9-86f9-fa45d3a83708.png)
![snap4091](https://user-images.githubusercontent.com/29383891/52400836-313de600-2ab8-11e9-88d7-942920ce183a.png)
this can often be resolved on a server restart, but holes in the surface sometimes refuse to fill in

Linking this to this as well as same pictures are in this
You cannot place fish trap underwater #10849

**Comment by Conchipedia** [comment] 2019-02-07 20:10
![snap4097](https://user-images.githubusercontent.com/29383891/52429453-fcec1900-2afb-11e9-814d-d8a92e03665d.png)
![snap4098](https://user-images.githubusercontent.com/29383891/52429480-0e352580-2afc-11e9-86b9-c86b51b2af83.png)

**Comment by elfl0rd** [comment] 2019-02-08 16:19
Duplicate of #10683

**Closed by elfl0rd** 2019-02-08 16:19 UTC

**Comment by Conchipedia** [comment] 2019-02-08 18:40
i thought i had already done one, but searching failed to find this one, Good find @elfl0rd 👍
