### ISSUE TITLE
plants on other people's property show up as harvestable

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1591] opened 2017-06-05 18:29 UTC
![image](https://cloud.githubusercontent.com/assets/774628/26797616/4355ef44-49e2-11e7-91e3-b14996070d2d.png)

**Comment by MarjieAVolk** [comment] 2017-06-05 18:54
Can you actually harvest them?  Or is it just the outline that's green?

**Comment by SeanAtr0n** [comment] 2017-06-05 20:08
can't harvest, the outline is just green

**Comment by metachronism** [comment] 2017-06-05 21:11
dupe of #1535

**Closed by metachronism** 2017-06-05 21:11 UTC
