### ISSUE TITLE
Carts wobbling and eventually disappearing or flying away

### ISSUE THREAD

**Issue by 42656e** [StrangeLoopGames/EcoIssues#5590] opened 2018-03-07 16:21 UTC
After used a wooden cart once, it wobbles always. Eventually the cart is flying away then or it just disappears.

**Comment by MarjieAVolk** [comment] 2018-03-07 23:26
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5492

**Closed by MarjieAVolk** 2018-03-07 23:26 UTC
