### ISSUE TITLE
USER ISSUE: Game crashes when trying to access influence tab in ecopedia.

### ISSUE THREAD

**Issue by iwazaru-codes** [StrangeLoopGames/EcoIssues#24185] opened 2023-12-13 21:45 UTC
\
**User Id: (slg60707)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
open upp ecopedia, go to settlement, click on influence .. the game crashes.

**Expected behavior:**
show u the contents of the influence tab?

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.EcopediaSettlementConfigData.GetEcopediaData(Player player, EcopediaPage page)
</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13666012/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13666013/Player-prev.log)

**Comment by D3nnis3n** [comment] 2023-12-13 22:39
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24116

**Closed by D3nnis3n** 2023-12-13 22:39 UTC
