### ISSUE TITLE
USER ISSUE: freezing items icons

### ISSUE THREAD

**Issue by SheedLa** [StrangeLoopGames/EcoIssues#4912] opened 2018-02-21 20:55 UTC
**Version:** 0.7.2.0 beta staging-08551408

**Steps to Reproduce:**
drag something from backpack over fast access slot or to the hand

**Expected behavior:**
switched slots contents

**Actual behavior:**
freezes dragged icon where you left. Item itself disappears from the game until you reconnect (but freezed icon remain) or restart (fixes until next time).
I play on dedicated server on my own machine, my partner doesn't report such behavior.

**Comment by MarjieAVolk** [comment] 2018-02-22 19:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-02-22 19:32 UTC
