### ISSUE TITLE
USER ISSUE: Exception when hitting a log with an axe

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6895] opened 2018-04-02 19:53 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Fell a tree
2. Small part of the log landed on a player-crafted pot with tomatoes in it
3. Log was still too big to be picked up
4. Server restarted
5. Went back to that place
6. I then hit the small log on the pot with the axe to break it into 2 carry-able pieces.

-> Exception -> Back to main menu

**Expected behavior:**
Split the log

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by Dreepa** [comment] 2018-04-02 20:09
Trying to pick up that same piece of log:


<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>

**Comment by MarjieAVolk** [comment] 2018-04-02 21:55
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

Are you able to restart your server and still see this bugged log?  If so, a copy of the save file would be awesome.

**Closed by MarjieAVolk** 2018-04-02 21:55 UTC

**Comment by Dreepa** [comment] 2018-04-02 22:11
Unfortunately no, I had successfully picked up the log, despite the exception and disconnect. So when I returned the log was no longer in the world, and a carry item appeared.

**Comment by MarjieAVolk** [comment] 2018-04-02 22:12
Okay, thanks anyway
