### ISSUE TITLE
Contract UI inserts extra whitespace

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7507] opened 2018-04-30 23:57 UTC
![image](https://user-images.githubusercontent.com/6262198/39455817-6af95b04-4c97-11e8-9ef0-ebf1efeb56eb.png)

(Different from other bugs, this window allows the content to fit, but still breaks)

**Comment by johnkslg** [comment] 2018-05-02 01:33
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/7400

**Closed by johnkslg** 2018-05-02 01:33 UTC
Labels: Medium Priority
