### ISSUE TITLE
USER ISSUE: Dont see my person

### ISSUE THREAD

**Issue by digruberg** [StrangeLoopGames/EcoIssues#11440] opened 2019-02-21 08:47 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
First start the game
Enter to default game server

**Expected behavior:**
Black screen with blured land down

**Do you have mods installed? Does issue happen when no mods are installed?:**
no

**Comment by elfl0rd** [comment] 2019-02-21 09:26
game restart help for you.

**Comment by elfl0rd** [comment] 2019-02-21 09:28
Duplicate of #11226

**Closed by elfl0rd** 2019-02-21 09:28 UTC

**Comment by D3nnis3n** [comment] 2019-02-25 21:04
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053
