### ISSUE TITLE
USER ISSUE: Dedoubled character in Third person view

### ISSUE THREAD

**Issue by bnema** [StrangeLoopGames/EcoIssues#23587] opened 2022-11-27 13:10 UTC
\
**User Id: (slg225265)**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
Sometimes my character is dedoubled when I use the 3rd person view. 

the game breaking bug is that I can fire 2 arrow at once, so double damage on animals.

However I can't double pick items.

**Expected behavior:**
Should only see your character 1 time

**Actual behavior:**
Same character stack on each other with a slight delay in the animation.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-11-29 09:09
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23555

**Closed by D3nnis3n** 2022-11-29 09:09 UTC
