### ISSUE TITLE
USER ISSUE: Unknowed bug

### ISSUE THREAD

**Issue by Devilz80** [StrangeLoopGames/EcoIssues#5477] opened 2018-03-06 17:04 UTC
**Version:** 0.7.2.0 beta staging-fe15b4f1

**Steps to Reproduce:**
Just play.

**Expected behavior:**
Just play.

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>La valeur ne peut pas être null.
Nom du paramètre : item


Stack:
   à System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   à System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   à Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   à Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   à Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   à Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   à Eco.Mods.TechTree.StockpileObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   à Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   à Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   à Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-07 20:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Closed by MarjieAVolk** 2018-03-07 20:29 UTC
