### ISSUE TITLE
Currency Precision and Credit

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#9280] opened 2018-09-09 07:09 UTC
Version: 7.7.1
Server: Stuffed Elk

![image](https://user-images.githubusercontent.com/2676134/45262045-dd4aaa80-b40e-11e8-8b39-3cea5af1f241.png)
Not sure how this happened. I seem to own a very very small amount of credit, no idea how much and I can't `/pay` him any amount above `0.00001` or so.
Also the "currency in circulation" counter seem to have gone berserk as a side-effect.

**Comment by D3nnis3n** [comment] 2018-09-09 09:10
I'll join in on that issue with loans:
![joinin](https://user-images.githubusercontent.com/25908592/45262949-ff4d2880-b420-11e8-8083-0b7869e9f0f7.png)

**Comment by D3nnis3n** [comment] 2018-09-09 09:11
https://github.com/StrangeLoopGames/EcoIssues/issues/9218

**Comment by johnkslg** [comment] 2018-09-10 22:09
Dupe of #9218

**Closed by johnkslg** 2018-09-10 22:09 UTC
Labels: Investigate, Semi-High Priority

**Comment by Deantwo** [comment] 2018-11-13 12:21
Very tiny currency amounts is stll possible, would the world end if you used a [fixed-point number](https://en.m.wikipedia.org/wiki/Fixed-point_arithmetic) for currency?
I can't think of a good reason to use any currency amount smaller than `0.01` or at most `0.001`.
