### ISSUE TITLE
[9.0 Staging-1477] Steam Truck Driver Becomes Passenger

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15254] opened 2020-03-22 00:07 UTC
Whilst driving the steam truck if you clip a corner of a block just right and your character model manages to collide your steam truck will catch and it will shove you into the passenger seat where you will be unable to control the vehicle and your only choice is to dismount.

This initiates the 'passenger crash without a driver present' and upon logging back into the server you are generally in orbit and come down somewhere at random.

**Comment by SlayksWood** [comment] 2020-03-23 11:11
@Daelmaron 
Can you provide some video or screenshots?

**Comment by Daelmaron** [comment] 2020-03-23 13:03
Will see if I can replicate it again, it only happened to me and another person by accident because we got stuck on a sharp corner trying to navigate around a building.

**Comment by Daelmaron** [comment] 2020-03-23 23:40
![20200323183929_1](https://user-images.githubusercontent.com/1329717/77373230-af4d6280-6d35-11ea-82e8-535f3699ca9c.jpg)

So, I just got into the vehicle on the driver side and it threw me into the passenger seat here.

**Comment by Daelmaron** [comment] 2020-03-24 01:18
Double pressing E **(accidentally)** moves you straight past the driver to the passenger seat

**Comment by Daniel-Magulado** [comment] 2021-01-22 10:09
Build: 0.9.2 Release-140

Issue: The player does get seated on the passenger seat but rarely.

Feedback: There's not a concrete reproduction step to trigger this issue but here are my findings.
1. It doesn't happen when riding the vehicle normally. Normally, as in approaching the vehicle and pressing E. I tried it 100 times and it never occurred once.
2. There's a higher chance for the issue to occur when you try to ride the vehicle while performing other actions such as jumping or when the vehicle is in an odd position. For example, the vehicle is on its side, tilted, or falling off the edge.

Here's a video recording of the issue.
https://images.zenhubusercontent.com/47210472/1af0b990-3ab5-403d-bb65-c477464f2846/player_seats_on_passenger.mp4

**Comment by WeaselDog** [comment] 2022-08-28 23:01
Thank you for reporting this bug! I can confirm this bug has been fixed in the upcoming 9.6 release

**Closed by WeaselDog** 2022-08-28 23:01 UTC
Labels: Priority: Low, Status: Fixed, Type: Bug, Category: Gameplay
