### ISSUE TITLE
USER ISSUE: Keyboard shortcuts not working

### ISSUE THREAD

**Issue by mawissacee** [StrangeLoopGames/EcoIssues#24552] opened 2024-01-06 13:43 UTC
\
**User Id: (slg240521)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Clicking any of the numbers does not reflect in the hotbar. "E" doesn't open up anything either. Tried restaring the game with the same issue. Unplayable.	

**Expected behavior:**
That the keyboard shortcuts should work

**Actual behavior:**
Clicking any of the numbers does not reflect in the hotbar. "E" doesn't open up anything either. Tried restaring the game with the same issue. Unplayable.	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-07 09:12
Cannot reproduce. Please attach your logs as described in the issue form.

Can you do any interactions?

**Comment by D3nnis3n** [comment] 2024-01-16 01:43
Closing due to no further information provided. Please reopen if you do in the future, without additional info we can't do anything.

**Closed by D3nnis3n** 2024-01-16 01:43 UTC
Labels: Status: Needs Information, Status: Not reproduced
