### ISSUE TITLE
[0.7.0.8] Unable to purpose law

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#4259] opened 2018-02-10 17:14 UTC
I am connected to game server
i push G to open panel on browser
I try to purpose this law:
![image](https://user-images.githubusercontent.com/29807119/36064653-805a7056-0e8e-11e8-9dc5-e4f17035c7df.png)

And i have as answer a red bar or a red bar with this message: "you must complete the form"
![image](https://user-images.githubusercontent.com/29807119/36064658-8d0a62ca-0e8e-11e8-9ed9-2c8115603509.png)

**Comment by th3t0mb0mb** [comment] 2018-02-11 00:21
I have had this happen as well. It seems to happen when the server is having latency/response issues.

**Comment by Amphysbaenas** [comment] 2018-02-11 19:18
seems changing browser can help. ( i used chrome before ) but it is not normal.
Some people explain to me that they have the problem with Mozilla and have to go on Chrome

**Comment by MarjieAVolk** [comment] 2018-02-13 02:57
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4094 . You can track the issue progress there.

Chances are, you are having a real normal issue of some kind, and it's just impossible to tell because the error message it not showing up.  Likely candidates for issues are:
* There's already a law with this name.  Even if a law did not pass or was deleted, you can't make another law with the same name.
* You are not logged in to the game.  Currently you must actually be running Eco in order to propose laws and do other government things (This was an undesired side effect of some changes we needed to make to support steam logins, which we will hopefully be changing in the future)
* You are not allowed to propose a law because of another law that is preventing it.  For example, the default Citizenship law.

**Closed by MarjieAVolk** 2018-02-13 02:57 UTC
