### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by Arranoa-jolasten** [StrangeLoopGames/EcoIssues#25070] opened 2024-08-18 18:52 UTC
Got exception at processing message from Steam:76561198012910116:        [Ping: 36 ms]   [CPU: 0.0 ms]   [In: ∞ k/s]     [Out: ∞ k/s]    . Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Eco.Shared.LZ4.LZ4Utils.ReadBlock(ByteSpanReader& reader, LZ4Descriptor descriptor, ILZ4Decoder decoder)
   at Eco.Shared.LZ4.LZ4Utils.StreamDecode(ReadOnlySpan`1 compressed, MemoryStream decompressed)
   at Eco.Shared.Networking.NetMessage.DecodePacket(ReadOnlySpan`1 message)
   at Eco.Plugins.Networking.NetworkServer.HandleIncomingDataMessage(UdpDataMessage& message). The message length is: 458762 and text representation is �"M@@�M�  �
query�result8ConstructionMining$Choose a Specialty&Material ProcessingEcopediaDiggingThe MeteorStockpiles Getting EquippedS �Up CampForage For FoodWork OrdersExhaus� �Claiming Land. �Build a HouseControlsDiscord"Gain� �
 XPFoodIntroUIHousing *� TLevel i ( �   �Scene*TownFoundation �UI$PlayerN XSwimmN AWork� 7 ��@0011ba184faf5febf6c56f6e813267ec" �76de49743fa8e621f92c9f3955444" �/a1c0a28f5a270ba2e5ddd25aca62d@0023d4ee803326692b073c8b1d412ccf �12b93741903be29d7baa9925abc18c7@003167187311c56cde0b436bfa572a08" �23ac96eb2d6c6ff3657bd4e6536da" �c3758cd33919d2dc170bb6a361e16" �d15371956ea830340c27e823a96fb" �/8845808b473288338a40a2dfd401@0040e0bce445f0d6dadeae500e0f3009" �5ee34f287ea05a8ee2ceacac2a910" �bf04678bdab8b9c9d55a88fb0c8D �
cd87636245644f1e50d530bfaea1f �55052ad7e64d8da6e4bd5b6d4c8f8f �5b8d887eb67cc022a09e3db8cb8cdv�5c06adc8a078e342d854528a4dd26" �
f991043aca651b2b25823732c6682�6285475dba9d0cd39d4add59b7e1c2�06d5f22b8b1d6f504685ab7268a631e@006dc47ee0766a1572895848e0f11ac��73792b70c05952087cef3da39e486��757819b142e9e62a3b7fad834bab0 �7ccbd8f21555a285b3116ab8e771dT�084713588e6fbab8e65410b2fec8642@008c0d681615bf2ec1a9dba61a543a2� �92c81f4bf0843d1b4be7cb61a702e� �0975e310a220dd7f4fe391dd63a6e1f@009c1eb93546693ca09cbfb598d4b3c��a28c3e4da6dbd1ddf2d4e988b2b44��a4b229a726e27a19232c403783056��0ab946d8201ce81a5f7b41c7ced7b47@00ac0444ae763edfd0bcef7ac7071eb��0b2dd3a59ef473a74eb28db4ee416b5@00b32af5134c8a793079900293b96992�
b6bac1a2ae1e96908c9b98f4bf89 �b8c60d228d55ba820aa3cc5416157f �/c470c0e5f7040105eb4335c2a7c9f3@00c7479c59197ae7e89c9bfb6243f0� �c9b1d1a4edc1f864c6d184a542092f �
c21a9e03de2888ce1b45d0640c67B�
ce2f24c355362a148b03c01b5ae1��d71faeeccdac7�0b341f10112��
dcc8259e502ecbe01c0b85905fe4v�de69331674fea2f21a7d01983f5� �e89bd3a810b86cb11090e6c8a2cf6�e9d7add0ec6124a9a7a300db6a850.�
efae707879632d4f2f2e0dc16651��
f0b71b10614e18c0c5456f26ce3ab�
f341a1da06a8158cef460b56a507��f5c4599810e281de1ca3920069110v�f6664ae0b8f8de389e4a02f9740e32�f7032d9fa89e83c68a00d0e22783fD �08d85dbaf603f56585934be2c88e8d@01002582fcf528cb4c6e85a3a767d113" �47c140aafe7ec123fc38918c8b6ac" �
5bb8d858edb16a0531187a4bf58b" �70934f7c61919ab3dba104a285c2fD �
87ed1bb08f6325f8e3afedad49b5" �0106637bbcf9cdfc89c44ca852950d0@01123bc4e13ae1a1b14cdb5dcdbfdc1� �13b754f5c87ca05386dd39bace76abD �
8432234307d751bcafccb700eb99" �edaadfd1bce2ea14acb2a6d5a4��211f212ca6379425c9a6ee49556fbbe5@012174f5264558343f297d906cc4b6a7" �
7313b354fd6ed0266d1d9aa17e5a��2d45e8d61797f2a37e86bc7efcda2�2df94a3a0f8c0756b43375b7e4afaaf �fb916d289e71de8240f9e9c7b53D �38ec7046a7f4979d1ea4fabefec �
39648d0a9ed4d1f3b56dd69a0b1b2�045dc5f0071a6c7cabcd473a6527461@0146880e2934aa7abad461c982ea7db� �4838f3716b685023cd968cc0ce650D �d0b66beab3c867eac6dc3fc769074f �/f34310d7441200fd66244d6ce9c92@01538b8a5dcfcf72fea0b41db0e07fdD �
56b1f0b14517dee7fd06e458be3d��
5788cdf091fbc80cfad6ffd5ead3p�1582534056eea1c70618f4eee786778� �
981a346d9901f42907da7b652569� �608b6cc0e13f9ec267f38489d54ad��

**Comment by D3nnis3n** [comment] 2024-08-18 20:20
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25063

**Closed by D3nnis3n** 2024-08-18 20:20 UTC
