### ISSUE TITLE
USER ISSUE: Cart bug - unable to move/interact

### ISSUE THREAD

**Issue by AlbeyAl** [StrangeLoopGames/EcoIssues#4170] opened 2018-02-09 08:49 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1.) Placed cart on ground
2.) Went into cart gui

**Expected behavior:**
Allowed me to continued to move/interact

**Actual behavior:**
Stopped working all together. Now is a lifeless entity. Almost like the scripts attatched to cart stopped working.

**Comment by AlbeyAl** [comment] 2018-02-09 08:55
Was able to find a fix. After disconnecting, I connected to the world again, and it seemed to refreshed the cart. Now working.

**Comment by MarjieAVolk** [comment] 2018-02-13 22:56
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

If you have any more information about when or why this happens, please let me know :)

**Closed by MarjieAVolk** 2018-02-13 22:56 UTC
