### ISSUE TITLE
Windows populating admin values with all players in server

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#11325] opened 2019-02-15 04:51 UTC
I have been told that an admin is seeing all players joining his server being populated in the admin values.  Says this is not happening on Linux servers.  Unable to get information hon how his users accounts are set up on the Windows OS. Do not know if mods are in use.  Unable to reproduce this in anyway even with altering windows users permissions.

**Comment by BlazeGuy2** [comment] 2019-02-15 18:57
Will be difficult to fix w/o a reproduction case.  DM on discord if a potential repro case comes up.

**Comment by D3nnis3n** [comment] 2019-04-23 04:39
Closing for now, as i cannot reproduce this. Feel free to reopen when you get another case or any more information / reproduction steps.

**Closed by D3nnis3n** 2019-04-23 04:39 UTC
Labels: Low Priority, Not reproduced
