### ISSUE TITLE
Campfire Recipes give 100 per craft instead of one!

### ISSUE THREAD

**Issue by Senbotsu** [StrangeLoopGames/EcoIssues#2197] opened 2017-09-20 04:19 UTC
Newest staging, I just queued up 5x campfire beans, 5x corn, etc. to research cooking.  However I got 100-stacks of everything instead of a single craft.  max rank campfire cooking, 4/5 efficiency in case that's the cause:

![image](https://user-images.githubusercontent.com/30206504/30626659-2ae2209e-9d80-11e7-94cf-cb0299627175.png)

**Comment by MarjieAVolk** [comment] 2017-09-20 17:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2201

**Closed by MarjieAVolk** 2017-09-20 17:22 UTC
Labels: High Priority
