### ISSUE TITLE
USER ISSUE: [Dedicated, 7.2.3] Rice won't disappear after picking it

### ISSUE THREAD

**Issue by lefavilla** [StrangeLoopGames/EcoIssues#5829] opened 2018-03-10 10:51 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Find rice
2. Harvest / pick it up by "E"

**Expected behavior:**
It should disappear instant or fast

**Actual behavior:**
Instead it disappears after 3-10 seconds. Sometimes you need to reconnect.(Not an Hardwareproblem)

**Comment by MarjieAVolk** [comment] 2018-03-12 23:15
@lefavilla also saw plants taking several seconds to appear after planting them.  Could just be network problems, idk.

**Comment by metachronism** [comment] 2018-07-12 03:53
dupe of #5036

**Closed by metachronism** 2018-07-12 03:53 UTC
Labels: Medium Priority
