### ISSUE TITLE
Multiple server crashes.  Unable to pinpoint issue

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4619] opened 2018-02-16 03:39 UTC
--BEGIN DUMP--
Dump Time
02/15/2018 20:58:13

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList1.Node.RemoveAll(Predicate1 match)
   at System.Collections.Immutable.ImmutableList1.RemoveAll(Predicate1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by alexandrage** [comment] 2018-02-16 07:49
The same happens. One player said that this is from archery to players.

**Comment by MarjieAVolk** [comment] 2018-02-16 19:09
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368

**Closed by MarjieAVolk** 2018-02-16 19:09 UTC
