### ISSUE TITLE
Missing Large Lumberstockpile Object

### ISSUE THREAD

**Issue by houseofdoggus** [StrangeLoopGames/EcoIssues#23374] opened 2022-08-31 15:48 UTC
Updated from previous version to 9.6 and the Large Lumber Stockpile does not appear. The items in the stockpile are there, but the object itself is missing or invisible.

**Comment by D3nnis3n** [comment] 2022-09-06 10:38
Also likely a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19797 then.

**Closed by D3nnis3n** 2022-09-06 10:38 UTC
