### ISSUE TITLE
9.5 staging 2221 - "Eat a balanced diet" tutorial step accepts seeds for mouseover step

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#22969] opened 2022-02-06 11:56 UTC
When prompted to examine the nutrients of food in their inventory, the tutorial step triggers when hovering seeds, which may be confusing as they don't have any nutritional value.

![image](https://user-images.githubusercontent.com/11805935/152679647-e34e6744-0fc4-4549-8117-f4ae5a77dd06.png)
![image](https://user-images.githubusercontent.com/11805935/152679651-81007b71-90f0-46bf-bd1c-ae5ca02451be.png)

**Comment by Daniel-Magulado** [comment] 2022-02-06 16:31
Hi @MonzUn 

Thank you for this report. Seeds are still considered food regardless of whether they have nutritional value or none. Thus the reason why it meets the requirement of the task for the related tutorial.

Closing as not a bug.

**Closed by Daniel-Magulado** 2022-02-06 16:31 UTC

**Comment by MonzUn** [comment] 2022-02-06 20:40
I know that they are technically counted as a food item, but they are also made exceptions in many cases.
In this tutorial, you aim to teach the player how to find nutritional value and to then accept an item that lacks nutritional value should be considered a bug, as the tutorial will not teach the player what it's designed to teach them.
