### ISSUE TITLE
Carrying Weight

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#2424] opened 2017-10-01 00:03 UTC
Haven't found the cause but we're regularly getting phantom weight added until we suddenly can't carry anything.  even naked....

the solution so far is a server reboot, but we just had it reoccur 5 minutes later......

**Comment by Fank** [comment] 2017-10-01 00:05
Duplicate of #2386

**Comment by noblackthunder** [comment] 2017-10-01 00:30
Closing because of dube, thanks @Fank !

**Closed by noblackthunder** 2017-10-01 00:30 UTC
