### ISSUE TITLE
[0.9.0.1] Object placing owner tracking( regardless of claims )

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18216] opened 2020-09-12 23:25 UTC
We used to have a display of who built / placed an object in 8.3 which is no longer the case in 9.0
so a stockpile for example showed who placed it down so it could be tracked by gm's for people griefing with tailings etc.

This is how an object is displayed ingame currently and it is impossible for an admin ingame to tell who actually placed the object down.
![Screenshot_301](https://user-images.githubusercontent.com/24981362/93006655-4960cb80-f55f-11ea-9217-ce9b3833eab9.jpg)

vs 8.3
you can clearly see who was the player responsible for placing down the object(regardless of type)
![Screenshot_336](https://user-images.githubusercontent.com/24981362/93006695-e9b6f000-f55f-11ea-9c53-0e1ef6c088db.jpg)

**Comment by D3nnis3n** [comment] 2020-09-12 23:58
This is a regression and i believe there is already an issue for it around somewhere.

**Comment by WeaselDog** [comment] 2020-09-13 03:21
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14687

**Closed by WeaselDog** 2020-09-13 03:21 UTC
