### ISSUE TITLE
Treasury issues from V10 are back?

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#25080] opened 2024-08-19 20:48 UTC
![image](https://github.com/user-attachments/assets/fe05061e-c2ee-464c-ad98-c326792125dd)

Also when I renamed the Leader title sfrom Silverleaf Federation Treasury General to President that account is now broken:

![image](https://github.com/user-attachments/assets/809e9e8b-fd23-42b1-8e46-fc5bfa6706dd)

release 693 & 702, persists through server restarts, mods are on

**Comment by Daniel-Magulado** [comment] 2024-08-20 05:34
Dear @padmanek,

Thank you for submitting this bug report. I can confirm that this is a known issue. I have escalated the matter and created an internal report for our development team to address it. A fix is expected to be included in an upcoming game update.

QA Reference: ECO-36119

**Comment by D3nnis3n** [comment] 2024-10-04 16:37
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14514 in staging.

**Comment by padmanek** [comment] 2024-10-26 20:45
> Fixed via [StrangeLoopGames/Eco#14514](https://github.com/StrangeLoopGames/Eco/pull/14514) in staging.

Doesn't look like it.

11.1 and orphaned treasuries from towns failed to found are stacking up again:

![image](https://github.com/user-attachments/assets/729e6a10-67cb-4aed-815d-13e4b85dccda)

**Comment by D3nnis3n** [comment] 2024-11-29 10:32
We are still unable to reproduce this and require exact reproduction steps.

**Comment by padmanek** [comment] 2024-12-02 03:55
![image](https://github.com/user-attachments/assets/df3266b1-feea-4c5f-abc3-134ee89044d6)

I wish I could help but the players are unable to tell us what they exactly did. Today this happens from 1 player making a town.

**Comment by padmanek** [comment] 2024-12-02 15:48
> Did you send your save with a town that has that for consistent reproduction to Daniel yet? If not, please do now.

Reproduction steps for the Treasury Duplication issue:

1. Have Global Federation present on the Server
2. Be member of the Federation
3. Place down town foundation
4. Pick up town foundation
5. Run back to Federation Foundation and join the federation
6. Place down town foundation
7. Found town
8. Orphaned Treasury from step 3. appears

I can record the process if needed.

Daniel has my save for the consistent reproduction of the world object loading issue, I've sent him on discord 11th of November.
Do you need a save for this Treasury issue too? The steps are pretty straight forward.

**Comment by Daniel-Magulado** [comment] 2024-12-02 17:31
Hi @padmanek 

Thank you for providing reproduction steps.
We're able to confirm and verify the issue.

QA Ref: ECO-8555

**Closed** 2024-12-04 06:27 UTC
Labels: Type: Bug
