### ISSUE TITLE
[9.3.6] Single Successful Currency Trade Triggers One Law Multiple Times

### ISSUE THREAD

**Issue by Bazookar** [StrangeLoopGames/EcoIssues#22504] opened 2021-08-03 05:56 UTC
This test is done on White Tiger official server where the law records custom stat sales tax as 15% of the currency trade. 
Trade amount: $1
Expected custom stat recorded: 0.15
Actual custom stat recorded: 0.45
Ping: 153 ms

Steps to replicate:
1. Go to a store and attempt to sell all of your one item.

2. Spam click trade - Here you see failed message x2 (meaning 1 trade went through, 2 trades failed)
![20210802223739_1](https://user-images.githubusercontent.com/88365511/127964932-2c5205f5-f7d7-404c-857a-bbbfb92c579b.jpg)

3. Query custom stat recorded showing 0.15 recorded 3 times (1 successful, 2 failed)
![20210802223806_1](https://user-images.githubusercontent.com/88365511/127964903-83ff5fa1-f14e-4e3f-ae53-5079ae185af0.jpg)

**Comment by D3nnis3n** [comment] 2021-08-04 16:13
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/22503

**Closed by D3nnis3n** 2021-08-04 16:13 UTC
