### ISSUE TITLE
Reduce hitler mustaches by 100%

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2165] opened 2017-09-18 19:18 UTC
![image](https://user-images.githubusercontent.com/3536496/30560012-6c1d6c78-9c6b-11e7-8aca-052e1a620df3.png)

**Comment by johnkslg** [comment] 2017-09-18 19:18
Its some kind of mesh discoloration

**Comment by metachronism** [comment] 2017-09-18 19:22
dupe of #2065, already fixed

**Closed by metachronism** 2017-09-18 19:22 UTC
