### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#5209] opened 2018-02-28 05:04 UTC
User: 
"Download world and start it either in local, or on a windows RDP, the game crash with this error :
https://i.imgur.com/NN3Sfny.png
World file (if needed) : http://212.47.248.115/EcoWorld/Game.eco"

**Comment by MarjieAVolk** [comment] 2018-02-28 20:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4305

This issue seems to be related to locale - Eg. loading a save file on a machine with a different locale from where it was created.

**Closed by MarjieAVolk** 2018-02-28 20:12 UTC
