### ISSUE TITLE
USER ISSUE: Tomato Texture of Picked is Showing

### ISSUE THREAD

**Issue by skiller185** [StrangeLoopGames/EcoIssues#14286] opened 2020-01-01 00:50 UTC
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
plant a tomato
grow it to full
pick it
look at the field and from 3-4 blocks away, slivers of red texture are appearing

**Expected behavior:**
not been red

**Actual behavior:**
looked red

**Do you have mods installed? Does issue happen when no mods are installed?:**
looked red

**Comment by WeaselDog** [comment] 2020-01-01 15:02
Thanks for your report.
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2825

**Closed by WeaselDog** 2020-01-01 15:02 UTC
