### ISSUE TITLE
USER ISSUE: Chopping a felled tree will kill the client

### ISSUE THREAD

**Issue by dlouwers** [StrangeLoopGames/EcoIssues#6753] opened 2018-03-30 19:00 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Chop a felled tree

**Expected behavior:**
1. 5+ of logs in m hand

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60,00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by dlouwers** [comment] 2018-03-30 19:03
Single player local world. 
No mods loaded.
Willing to upload save files.

**Comment by MarjieAVolk** [comment] 2018-03-30 19:41
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5595

We think we may have fixed this for the next hotfix.  Fingers crossed.

**Closed by MarjieAVolk** 2018-03-30 19:41 UTC
