### ISSUE TITLE
USER ISSUE: charrette qui disparait

### ISSUE THREAD

**Issue by sav73** [StrangeLoopGames/EcoIssues#24055] opened 2023-09-30 14:31 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-169

**Steps to Reproduce:**
mettre des objets dans une brouette style morceau de bois , taper au marteau pour recupere les marchandises jusque au dernier

**Expected behavior:**
la charrette doit reste sur le sol 

**Actual behavior:**
la charrette disparait avec le coup de marteau en recuperant le bois 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-10-02 09:02
The last hit takes the wood cart with you into your inventory if there is enough space for both it and its contents, that works as intended. I cannot reproduce a different behaviour, hence I'm closing this. Please let us know and create a new issue if there is a different bug and you can describe it in more detail.

**Closed** 2023-10-02 09:02 UTC
