### ISSUE TITLE
USER ISSUE: Connection Timeout

### ISSUE THREAD

**Issue by domenictiemo** [StrangeLoopGames/EcoIssues#10007] opened 2018-11-14 12:38 UTC
**Version:** 0.7.8.0 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Verbindung fehlgeschlagen</size>

Failed to connect - connection timed out.
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Verbindung fehlgeschlagen</size>

Failed to connect - connection timed out.
```

**Comment by D3nnis3n** [comment] 2018-11-14 15:10
Could you elaborate a bit on the circumstances this happened? What server did you try to join? Was it your Singleplayer? A Multiplayer Server?

**Comment by D3nnis3n** [comment] 2018-11-14 17:35
I assume this is a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10004 and a issue with the master server responsible for the ingame-server-list.

**Closed by D3nnis3n** 2018-11-14 17:35 UTC
