### ISSUE TITLE
USER ISSUE: Stockpiles dissapeared client side

### ISSUE THREAD

**Issue by irichar1CS1003** [StrangeLoopGames/EcoIssues#23158] opened 2022-05-08 00:33 UTC
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
I'm not aware. But I do host the server so this was surprising

**Expected behavior:**
I wanted to interact with stockpiles.

**Actual behavior:**
The stockpile ropes are invisible and I cannot use the stockpiles

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8646134/Player.log)

Cheers,
Isaac :)

**Comment by D3nnis3n** [comment] 2023-01-02 22:44
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23107

**Closed by D3nnis3n** 2023-01-02 22:44 UTC
