### ISSUE TITLE
Alligators numbers decrease when people get near them

### ISSUE THREAD

**Issue by Krisocka** [StrangeLoopGames/EcoIssues#24804] opened 2024-03-04 01:06 UTC
As soon as players get near zones Alligators have as Habitats their numbers decrease rapidly.
I observed this occuring daily in the current White Tiger cycle. Over the day the number of Alligators steadily increased to nearly 50, only to plummet to 30 as soon as the Jungle people started playing in the evening. When I went into the jungle myself to test this, numbers dropped from 55 to 45 after one run around the jungle. This was not a problem caused by hunting, as laws forbid species with less than 50 individuals to be hunted or gathered.
My guess the same happened with otters going extinct completely, as all of their habitats were near very active people on the first day.

May be related to the issue of Crabs, Alligators and Otters just dropping dead on the ocean, may be not.

**Comment by D3nnis3n** [comment] 2024-03-04 09:59
That's a longer existing issue, duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/21722.

**Closed by D3nnis3n** 2024-03-04 09:59 UTC
