### ISSUE TITLE
8.1.1 Servercrash

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#11961] opened 2019-04-10 18:12 UTC
--BEGIN DUMP--
Dump Time
04/10/2019 11:07:49

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.WorkOrder.set_UncraftedQuantity(Int32 value)
   at Eco.Gameplay.Items.WorkOrder.UpdateCrafted()
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--

**Comment by mirasrael** [comment] 2019-04-11 05:23
Fixed executable, also contains fix for https://github.com/StrangeLoopGames/EcoIssues/issues/11938
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3067025/EcoServer.zip)

**Comment by mirasrael** [comment] 2019-04-11 05:28
Actually duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11899

**Closed** 2019-04-15 19:11 UTC
Labels: Critical Priority, Fixed
