### ISSUE TITLE
USER ISSUE: Items not moving properly

### ISSUE THREAD

**Issue by Kkelly1234** [StrangeLoopGames/EcoIssues#6429] opened 2018-03-24 02:17 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
just moving stuff to your inventory

**Expected behavior:**
It should have moved with ease

**Actual behavior:**
Instead when I try and move something to my inventory it would just keep it there an not have it placed in my inventory but i would still be in the same place when i left my inventory and the only way to get rid of it is to completely relaunch the entire game and it would still continue to happen

**Comment by MarjieAVolk** [comment] 2018-03-28 19:23
This shoooould be fixed in 7.3  Let me know if it is not.

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-03-28 19:23 UTC
