### ISSUE TITLE
USER ISSUE: Ecopedia Influence tab crashes game to main menu

### ISSUE THREAD

**Issue by KevinHavn** [StrangeLoopGames/EcoIssues#24173] opened 2023-12-13 11:30 UTC
\
**User Id: (slg141889)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Enter game
2. Enter Ecopedia
3. Enter "Settlements" tab
4. Enter "Influence" sub-tab

**Expected behavior:**
It should have displayed useful information regarding the new influence system

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.EcopediaSettlementConfigData.GetEcopediaData(Player player, EcopediaPage page)
</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and no.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-13 12:49
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24116

**Closed by D3nnis3n** 2023-12-13 12:49 UTC
