### ISSUE TITLE
Moving Item's to fast in Project call error

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2002] opened 2017-08-27 19:06 UTC
Stack:
   at Eco.Gameplay.Items.WorkOrder.<>c__DisplayClass78_0.<TryToContributeItems>b__1(ItemStack ingredient)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Gameplay.Items.WorkOrder.<>c__DisplayClass78_0.<TryToContributeItems>b__0(IInventoryChangeSet changeSet)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user)
   at Eco.Gameplay.Items.WorkOrder.TryToContributeItems(Player player, ItemStack stack)
   at Eco.Gameplay.Components.CraftingComponent.OnActRight(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnAct(InteractionContext context, Func`2 resultFunc)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2017-08-29 23:31
Ah, I made a bug for this too - closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2022  (Just found a fix, should be available in the next staging)

**Closed by MarjieAVolk** 2017-08-29 23:31 UTC
