### ISSUE TITLE
USER ISSUE: Player has no name

### ISSUE THREAD

**Issue by jtekstar** [StrangeLoopGames/EcoIssues#4677] opened 2018-02-17 04:28 UTC
Trying to /admin my friend, but his player has no name, even though he has a name in Steam. Tried changing Steam name and restarting game but nothing helped. When I do /whois [his Steam name], it says could not find player.

**Comment by jtekstar** [comment] 2018-02-17 05:14
Went ahead and took a screenshot, ignore my name, but my friend below me has no name.
![capture](https://user-images.githubusercontent.com/36557677/36338231-6f68f8c4-1377-11e8-8db4-6f7725376b8a.PNG)

**Comment by Yorkforce** [comment] 2018-02-22 16:23
We had 2 players also with this issue, they mentioned they had russian steam names (special characters maybe?)

**Comment by MarjieAVolk** [comment] 2018-02-23 19:08
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4160

**Closed by MarjieAVolk** 2018-02-23 19:08 UTC
