### ISSUE TITLE
User gets black screen when starting game

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#5858] opened 2018-03-10 21:18 UTC
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1799806/output_log.txt)
Here is their log, appears to be a shader issue.

**Comment by johnkslg** [comment] 2018-03-10 21:20
User has:
1:20 PM] ☐✘[D3V]✘ ☐: intel core I5-4430 CPU 3GHZ  8gb RAM
[1:20 PM] ☐✘[D3V]✘ ☐: gtx 960

**Comment by MarjieAVolk** [comment] 2018-03-12 17:50
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4834

**Closed by MarjieAVolk** 2018-03-12 17:50 UTC
Labels: High Priority
