### ISSUE TITLE
Fallen trees are disappearing/vanishing 6.1.1

### ISSUE THREAD

**Issue by brad992** [StrangeLoopGames/EcoIssues#2860] opened 2017-11-19 16:40 UTC
Repeatable on our server. Server opened 9th Nov 2017 (v6.0.3) and we just updated to v6.1.1. When trees are cut they are repeatedly completely vanishing. Sometimes I cut a tree and it vanishes immediately after falling. Sometimes it vanishes while in the middle or chopping into smaller logs. Can provide more examples if needed.

short version of the bug
https://www.youtube.com/watch?v=tSjBjCHXmDQ&feature=youtu.be

long version (restarting client does nothing)
https://www.youtube.com/watch?v=AgUcuQXJq3Y&feature=youtu.be

Settings I use:
https://i.imgur.com/Fjvtt2G.png

**Comment by Conchipedia** [comment] 2017-11-19 23:53
i have seen that happen but only if i take away the stump before i chopped the tree, as soon as i touch the tree after removing stump the tree Vanishes

**Comment by cuda70** [comment] 2017-11-20 16:53
I placed a complaint about the same problem and was told it was filed before and was closed and removed. I am still experiencing the same problem also some trees when chopped down drop already cut in pieces or if you cut them up and take 10 to your storage and come back your tree is gone but the stupid wood pulp is still there

**Comment by MarjieAVolk** [comment] 2017-11-20 19:34
Thanks - closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2845.  I will copy your comment over there

**Closed by MarjieAVolk** 2017-11-20 19:34 UTC
