### ISSUE TITLE
USER ISSUE: Tidying up Already Felled trees

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3409] opened 2018-01-15 19:23 UTC
**Version:** 0.6.4.0 alpha staging-a6a22be6

**Steps to Reproduce:**
location: 453, 480 part of a tree i was trying to clean up gave me following error:

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Joined again, and then tried to chop it again, gave me same error

**Expected behavior:**
no idea why it is doing this

**Actual behavior:**
should just let me chop it into pieces

**Comment by MarjieAVolk** [comment] 2018-01-15 19:26
Sean just fixed some tree stuff, might already be fixed?

**Comment by Conchipedia** [comment] 2018-01-15 19:37
i just put in when something happens, especially if it was repeatable , had it been a one off error i might have not bothered as things sometimes just happen

**Comment by SeanAtr0n** [comment] 2018-02-03 20:57
might be fixed, think meta changed slice trunk recently

**Comment by MarjieAVolk** [comment] 2018-02-07 23:46
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-02-07 23:46 UTC
Labels: Medium Priority
