### ISSUE TITLE
Double keypress on Ubuntu

### ISSUE THREAD

**Issue by matias-b** [StrangeLoopGames/EcoIssues#6783] opened 2018-03-30 23:56 UTC
on Ubuntu the game detects every keypress  twice, typing 123 shows 112233, also makes moving hard because keypresses get queued and the player keeps moving for a while. This behaviour doesn't appears on Windows

Version info:
Linux ubuntu 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Game: Steam 0.7.3.1 beta

**Comment by MarjieAVolk** [comment] 2018-03-31 00:27
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3580

**Closed by MarjieAVolk** 2018-03-31 00:27 UTC
