### ISSUE TITLE
USER ISSUE: stuck between 2 hammer's block

### ISSUE THREAD

**Issue by Antoine115** [StrangeLoopGames/EcoIssues#4512] opened 2018-02-14 12:24 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
1.put a stone block with a hammer 
2.next to him, put a log block with a hammer
3.walk between them

**Expected behavior:**
walk normaly

**Actual behavior:**
get stuck between the blocks

**Comment by Antoine115** [comment] 2018-02-14 12:26
bonnus this is not my property

**Comment by rsgodkilla** [comment] 2018-02-14 12:45
use /unstuck ?

**Comment by Antoine115** [comment] 2018-02-14 14:03
yes but it change nothing :/

**Comment by Antoine115** [comment] 2018-02-14 14:05
i think i will justt wait the owner of the property and ask him to free me

**Comment by MarjieAVolk** [comment] 2018-02-14 21:22
/unstuck doesn't get you out?  Which blocks did you place specifically?  Hewn Log and Mortared Stone?  And which variants of them did you place?  Walls?  Or cubes?

**Comment by keegan-o** [comment] 2018-02-15 20:40
This is asking to be able to walk between two parallel walls which we will probably never add support for-- the colliders already do match them so if there happened to be enough space it would be possible, but I think the intention is for it not to be.

**Comment by MarjieAVolk** [comment] 2018-02-16 20:09
Oh I thought they were actually getting stuck.  But now I am not sure either.

**Comment by elfl0rd** [comment] 2018-06-25 19:09
Looks fixed
![default](https://user-images.githubusercontent.com/4980243/41870301-5c1bda9a-78c4-11e8-8948-257a86f82a29.png)

**Comment by GophTheGreat** [comment] 2019-05-14 23:39
Could not reproduce. Closing.

**Closed by GophTheGreat** 2019-05-14 23:39 UTC
Labels: Low Priority
