### ISSUE TITLE
Faulty text representation

### ISSUE THREAD

**Issue by Kevster92** [StrangeLoopGames/EcoIssues#6612] opened 2018-03-29 00:38 UTC
![20180329_011848](https://user-images.githubusercontent.com/37886410/38063440-7deb1ca0-32f9-11e8-8614-0a4095e81d77.jpg)
![20180329_022538](https://user-images.githubusercontent.com/37886410/38063441-7e04d5e6-32f9-11e8-9310-a756af85c748.jpg)
![20180329_022657](https://user-images.githubusercontent.com/37886410/38063442-7e215356-32f9-11e8-8d1c-25eca6b2b1b5.jpg)

**Comment by Kevster92** [comment] 2018-03-29 00:39
Version Beta0.7.3

**Comment by MarjieAVolk** [comment] 2018-03-29 01:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6564

This should be fixed in the next hotfix.

**Closed by MarjieAVolk** 2018-03-29 01:05 UTC
