### ISSUE TITLE
Unknown error hope it helps

### ISSUE THREAD

**Issue by Geuthur** [StrangeLoopGames/EcoIssues#6497] opened 2018-03-25 19:17 UTC
![download 1](https://user-images.githubusercontent.com/761682/37879023-d8e3152a-3071-11e8-904b-03a64e5defbd.png)

**Comment by MarjieAVolk** [comment] 2018-03-26 20:38
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6292

**Closed by MarjieAVolk** 2018-03-26 20:38 UTC
