### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by kish4n** [StrangeLoopGames/EcoIssues#4138] opened 2018-02-08 22:03 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
trying to delete empty item to sold

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Delete on StoreComponent!

Specified argument was out of the range of valid values.
Parameter name: index


Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.RemoveAt(Int32 index)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass12_0.<RemoveAt>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Core.Controller.RPCListExtensions.Delete(IContainsRPCLists obj, Int32 iList, Int32 iEntry)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

```

**Comment by MarjieAVolk** [comment] 2018-02-09 02:09
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4048 - You can track the issue progress there if you are interested.

This is caused by double clicking on the x button.  Some mouses may also send duplicate click events, which might also cause this.  I hope to hotfix this soon.

**Closed by MarjieAVolk** 2018-02-09 02:09 UTC
