### ISSUE TITLE
USER ISSUE: Launchpad into sky with wood/rubble

### ISSUE THREAD

**Issue by MarviBiene** [StrangeLoopGames/EcoIssues#18805] opened 2020-10-17 23:38 UTC
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5396857/Player.log)
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
1. Have a ile of chopped wood (round wood)
2. Jump and move on them
3. Have a fly into sky

**Expected behavior:**
it should only move the logs not launch the player into the sky

**Actual behavior:**
it lauches the player into sky

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by MarviBiene** [comment] 2020-10-17 23:41
If that matters. I am doing this with the Redwood logs.

**Comment by SlayksWood** [comment] 2020-10-21 10:37
known issue, has become more after changes with trees in 9.0.
There is a issue with rubbles, I would merged to it. But can't find it now.

**Comment by IcedForge** [comment] 2020-10-27 07:56
related issues have been linked / merged with #12553 i believe they are related somehow with physics but not exactly the same?

**Comment by xplayman** [comment] 2020-11-06 12:28
I had not noticed this activity until after the 9.1.0 patch with the in mine teleport but 9.1.1 with the space teleport.
Before 9.1.0 I usually got teleported to ground lvl from mines if I walked in rubble.

**Comment by SlayksWood** [comment] 2020-11-26 08:37
and alligator:
> Basically I was teleported to z max or something. Everything was a complete black void but when I moved X̄ or ȳ it registered on the map as lateral movement ect. Using Teleport admin commands with Z index moved me back into the game world. As for experience when it happened I shot straight into the air and watched the planet disappear into the darkness. Not even a pale blue dot was visible by the end. I believe it had me a 1511 meters away but on the map directly above where i was.
> 
> To understand this a bit better I was directly at the edge of another players territory line. they had no kill permissions and alligator was crawling back to the line where we wouldn't be able to hurt it. It was almost there when Me and my friend were finally able to kill it. The corpse vanished and I ran up to where it was and jumped as soon as I did my friend reported me being a rocket ship to space. Presumptively, I would assume it would have to do with the corpse vanishing so my character received some sort of bogus collision that applied a max acceleration in z+ to my character.
> 
> **Root cause** more than likely a corpse vanishing or desyncing collision
> 
> Alternative solutions/Suggestion. Add a /stuck that respawns you at your x,y coordinates similar to /tp x, y. Even better if you add a bit of random x,y drift in case someone gets stuck in a pit or something.
> 
> Of course theres always the best UX solution /stuck just respawns you at a bed
> 
> Hope that helps sorry I can't offer more. I was very tired and dying laughing when this happened.

**Comment by SlayksWood** [comment] 2020-11-26 08:38
Maybe we should limit height too?
If you are teleported above 1400, will you appear on the surface like crossing Z zero?

**Comment by SlayksWood** [comment] 2020-12-01 10:39
check after merging https://github.com/StrangeLoopGames/Eco/pull/7272

**Comment by SlayksWood** [comment] 2020-12-02 11:43
Seems fixed in 0.9.2 staging-1861, at least I mine and pick up a lot of rubbles and can't reproduce it (I would have already flown 10 times in 9.1). Closed for now

**Closed by SlayksWood** 2020-12-02 11:43 UTC
Labels: Category: Gameplay, Priority: High, Status: Fixed
