### ISSUE TITLE
Focused Workflow:Farming has not effect

### ISSUE THREAD

**Issue by Ramh5** [StrangeLoopGames/EcoIssues#11987] opened 2019-04-11 17:32 UTC
Same for Fertilizer, according to the description the machine should work twice as fast when alone. Even tried to have it very much alone in its own room.

**Comment by lavishcorgi** [comment] 2019-04-11 21:25
I have the same issue for all crafting specialty talents, regardless of which I picked. 8.1.1 windows 10, medium difficulty

**Comment by Keldoo** [comment] 2019-04-16 07:06
Got the same issue for cooking for exemple meat stock is 10min at lvl 1, 8 min at lvl 3, still 8 min with the talent as you can see on the screenshot.
![20190416085517_1](https://user-images.githubusercontent.com/20174978/56188628-4db14e00-6026-11e9-9da9-f29bdbd9845c.jpg)

**Comment by lavishcorgi** [comment] 2019-04-17 18:21
@Keldoo i think it's certain recipes that aren't being affected by focused workflow (in the case of the cooking skill, haven't tested this with other skills) because the starting time for most salads is 1 minute at level 1, but the items in your screenshot show 24 seconds. However, I can confirm that meat stock is not being reduced by focused workflow for me either.

**Comment by craig-jong** [comment] 2019-04-18 20:51
This is a bug that affects recipes created by very specific templates. This should be fixed in master, but I'll give it a double check - expect the bug to be fixed in 8.2.

**Comment by craig-jong** [comment] 2019-04-18 20:52
Actually, @mirasrael may have pushed those changes into a hotfix for master - I'm not sure.

**Comment by mirasrael** [comment] 2019-04-19 05:37
All changes was delayed for 8.2. I checked code and both Farming and Meat Stock seems fixed in 8.2 (current master).

**Comment by craig-jong** [comment] 2019-04-23 21:10
Will be fixed in 8.2

**Closed** 2019-04-23 21:10 UTC
Labels: High Priority, QA
