### ISSUE TITLE
USER ISSUE: Floating wooden logs in the air

### ISSUE THREAD

**Issue by Frag2000** [StrangeLoopGames/EcoIssues#4517] opened 2018-02-14 13:39 UTC
**Version:** 0.7.1.1 beta staging-12a42dd2

**Steps to Reproduce:**

Physics engine glitch! Look at the screenshot attached. When starting my game this morning (SINGLE PLAYER), all my wood logs started to float in the air. My game was created night on the previous version.
![eco floating log](https://user-images.githubusercontent.com/10600462/36207005-6ff006d2-1162-11e8-8e50-14e35eaf7db3.jpg)

**Expected behavior:**

Logs should stay on the ground.

**Actual behavior:**

Flying logs

**Comment by MarjieAVolk** [comment] 2018-02-14 21:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-14 21:29 UTC
