### ISSUE TITLE
USER ISSUE: Industrial Elevator Get's stuck

### ISSUE THREAD

**Issue by bhughey24** [StrangeLoopGames/EcoIssues#20407] opened 2021-02-06 15:15 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Create industrial elevator in big enough space. 	

**Expected behavior:**
Go up and down. 	

**Actual behavior:**
Gets stuck

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2021-02-07 03:17
Hi, thank you for making a report. However, we are unable to reproduce this.
For us to be able to investigate this issue further, could you provide a video recording of the issue and log files? Here's the instruction on how to provide log files: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Additionally, kindly provide the specification of the PC where you encountered this issue as well as its operating system and version.

Thank you.

**Comment by IcedForge** [comment] 2021-02-09 15:01
Sounds like the same behavior as this one where its intermittently stopping seemingly random ive had it happen before but it seems completely random, its almost like the collision box is causing it to stop as a blocker due to delay or somesuch( me speculating mostly  )?
#18809

**Comment by SlayksWood** [comment] 2021-02-10 05:28
merged to #18809 for investigation.
@bhughey24 You can add details here #18809 too.

**Closed by SlayksWood** 2021-02-10 05:28 UTC
Labels: Status: Needs Information
