### ISSUE TITLE
USER ISSUE : [STAGING] Tutorial Respawn every time a tool is selected

### ISSUE THREAD

**Issue by B1sounours** [StrangeLoopGames/EcoIssues#5253] opened 2018-02-28 23:16 UTC
Version: Staging 7.2 happen on bc863b4b and 733ef85f

Steps to Reproduce:
Toggle skip all tutorial

Expected behavior:
Hide and skip all tutorial

Actual behavior:
Tutorial show everytime a tool is selected 

Actual fix :
Skip all tutorial one by one

**Comment by MarjieAVolk** [comment] 2018-02-28 23:17
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5206

**Comment by MarjieAVolk** [comment] 2018-02-28 23:18
Noting your observations there

**Closed by MarjieAVolk** 2018-02-28 23:17 UTC
