### ISSUE TITLE
USER ISSUE: getting an Error and don't know why or what causes it

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3895] opened 2018-02-04 19:38 UTC
**Version:** 0.7.0.0 beta

Caught exception: Nullable object must have a value.

**Comment by LiaungYip** [comment] 2018-02-04 19:57
We've also been getting this error quite frequently. It causes a crash to menu on the client. You're able to log back into the server immediately with no ill effects.

**Comment by metachronism** [comment] 2018-02-04 20:03
Have you guys tried the hotfix?  it went out late last night, has the same version # for now

**Comment by MarjieAVolk** [comment] 2018-02-05 02:50
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3891

**Closed by MarjieAVolk** 2018-02-05 02:50 UTC
Labels: High Priority
