### ISSUE TITLE
USER ISSUE: bugggg

### ISSUE THREAD

**Issue by NortonDK** [StrangeLoopGames/EcoIssues#4136] opened 2018-02-08 21:50 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Joining the server

**Expected behavior:**
i would like to be able to join the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment] 2018-02-09 02:14
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4144 - you can track the issue there if you are interested.

If you have any additional details, that would be very helpful (can post either here or on the other bug).  For instance, did you see this for only one server, or for every server?  Did you see it many times?  Did the issue ever go away?  Had you logged in to this server before?  Were you logging in via steam or via a download from our website?

**Closed by MarjieAVolk** 2018-02-09 02:14 UTC
