### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by BIGkGaming** [StrangeLoopGames/EcoIssues#6219] opened 2018-03-18 03:30 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Caught exception:

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.SendInitialState(BSONObject obj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>

No Idea what I did

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.SendInitialState(BSONObject obj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-21 20:59
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4860

**Closed by MarjieAVolk** 2018-03-21 20:59 UTC
