### ISSUE TITLE
7.5.0 Textures move when vehicles move

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8120] opened 2018-06-21 00:15 UTC
Placed sand blocks in the trunk of the truck or steam truck.  When the car moves, the texture also moves when the sand texture should stay static.  Similar issue came up with the crane moving dirt in the show 'n tell last week.

**Comment by metachronism** [comment] 2018-06-21 00:28
dupe of other issue, not really high priority

**Closed by metachronism** 2018-06-21 00:28 UTC
Labels: High Priority

**Comment by SeanAtr0n** [comment] 2018-06-21 00:37
kinda makes sense to tag em as high priority if we want it for 7.5

**Comment by elfl0rd** [comment] 2018-06-21 07:51
Duplicate - https://github.com/StrangeLoopGames/EcoIssues/issues/7596
