### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8482] opened 2018-07-13 21:23 UTC
**==Sent from Eco Crash Server==**
**Details:**
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

**Stack:**
at Eco.Gameplay.Economy.Trackers.ExchangeRates.GetExchangeRates(Currency currency)
   at Eco.Gameplay.Economy.Trackers.ExchangeRates.DescribeRatesForCurrency(Currency cur, ExchangeType exchangeType)
   at Eco.Gameplay.Economy.Currency.ShowCurrencyReport(Player player)
   at Eco.Gameplay.Components.CreditComponent.CurrencyReport(Player player)

**Comment by johnkslg** [comment] 2018-07-13 21:57
Dupe of StrangeLoopGames/EcoIssues#8461, fixed already

**Closed by johnkslg** 2018-07-13 21:57 UTC
Labels: Needs Triage
