### ISSUE TITLE
Tooltip hide issue - v.0.7.7.0

### ISSUE THREAD

**Issue by dwujcik** [StrangeLoopGames/EcoIssues#9188] opened 2018-09-05 18:33 UTC
The tooltip cannot hide, when moving the mouse - version 0.7.7.0

![20180905202957_1](https://user-images.githubusercontent.com/17785084/45113456-ae041700-b14a-11e8-8ed3-8ab3298d97de.png)

**Comment by Nicolausi113** [comment] 2018-09-05 19:16
reported in #9132

**Comment by metachronism** [comment] 2018-09-06 18:05
dupe of #9132

**Closed by metachronism** 2018-09-06 18:05 UTC
Labels: Needs Triage
