### ISSUE TITLE
USER ISSUE: Stuck inside a RedWood tree

### ISSUE THREAD

**Issue by apostol1322** [StrangeLoopGames/EcoIssues#12061] opened 2019-04-18 20:55 UTC
**Version:** 0.8.1.3 beta

**Steps to Reproduce:**

**Expected behavior:**
ALREADY tried the unstuck command

**Actual behavior:**
The chunk wasnt load and when it did i was stuck inside the Redwood tree. I tried the unstuck command and nothing happend.

**Do you have mods installed? Does issue happen when no mods are installed?:**
The chunk wasnt load and when it did i was stuck inside the Redwood tree. I tried the unstuck command and nothing happend.

**Comment by D3nnis3n** [comment] 2019-04-18 22:27
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11375

**Comment by D3nnis3n** [comment] 2019-04-18 22:27
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/12053

**Closed by D3nnis3n** 2019-04-18 22:27 UTC
