### ISSUE TITLE
USER ISSUE: Keeps Crashing

### ISSUE THREAD

**Issue by haos200** [StrangeLoopGames/EcoIssues#3752] opened 2018-01-31 23:08 UTC
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-01-31 23:24
Sounds like this is probably a duplicate of some others

**Comment by craig-jong** [comment] 2018-02-05 20:16
Any idea what tree type this was?

**Comment by MarjieAVolk** [comment] 2018-02-12 23:24
@xSuzuka took a video of this happening:
https://www.youtube.com/watch?v=CxDkSDJqEaU&feature=youtu.be

**Comment by MarjieAVolk** [comment] 2018-03-05 23:20
@SeanAtr0n This might be related to/the same as https://github.com/StrangeLoopGames/EcoIssues/issues/3668, some people that reported this also reported floating logs.

**Comment by MarjieAVolk** [comment] 2018-03-09 21:25
By the way, this only seems to happen for existing logs that people find sitting around.  Next time someone tries to repro this, I would suggest cutting down a bunch of trees, then letting them sit there for a while before coming back to check.

**Comment by KenLFG** [comment] 2018-03-19 19:48
At first it seemed like it was localized to Oak trees but then I had it happen to a Birch log. I also thought it was related to exiting and restarting (I'm playing solo so I'm guessing the server gets shut down locally when I exit a game). It's like the log is not getting enumerated right even though it's still loading into the world.  

So at this point, it seems pretty inconsistent. 

- Happens to Oak and Birch tree logs.
- Happens (more readily) after cutting down a tree, quitting and reloading a game but also just randomly without having done so.
- Happens when picking up or chopping up a log (basically any interaction with a fallen log). Have not had it happen when clearing branches off a fallen log (yet).

One thing to note: it eventually passes. For instance, if I'm picking up cut logs, logging back in after the crash will find me carrying the extra logs. Other times, they don't get picked up but I can leave the logs and come back to them a while later and they are either gone or can be picked up (usually the model is weird where the inner face has no texture--it's see-through--but it can be picked up finally).

I don't know how the app/game handles those interactions but is it possible it's just a race condition? Maybe there was just a delay in getting that info updated in whatever array/data store you're running under the hood? And, wouldn't the initial load properly enumerate all objects in the world (or delete/remove them if they aren't valid in some way)?

**Comment by metachronism** [comment] 2018-03-30 18:29
possible fix checked in

**Comment by MarjieAVolk** [comment] 2018-04-02 21:53
FYI reporters of this issue typically will see the above exception when trying to chop the log, or the below exception when trying to pick up the same log.  Multiple people have reported seeing these issues together consistently on the same log.  Typically the log was left lying on the ground during a server restart, and that single log will consistently cause these same exceptions, until it mysteriously disappears.

```
<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment] 2018-04-02 23:29
Got this save file, which supposedly repros the issue: https://github.com/StrangeLoopGames/EcoIssues/files/1869663/ChopBugSave.zip

Broken log is at (425, 580)

**Comment by SeanAtr0n** [comment] 2018-05-14 23:01
Fixed a while back

**Closed by SeanAtr0n** 2018-05-14 23:01 UTC
Labels: High Priority
