### ISSUE TITLE
USER ISSUE: Plant already exists there

### ISSUE THREAD

**Issue by purpleypete** [StrangeLoopGames/EcoIssues#6888] opened 2018-04-02 14:17 UTC
![eco 02_04_2018 15_13_42 2](https://user-images.githubusercontent.com/37105142/38199519-f1fc6bb6-3688-11e8-80f8-11415180af94.png)
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
new update 
causing farm plots of land to not be usuable as it thinks a plant is there,
plant growth of crops at 0.125 so there harvestable every 3 hours.
plant already exists here:
crop 1 -fine
crop 2 -1 plot
 unusable
crop 3 -9 plots
 unusable
crop 4 -43 plots
 unusable
this bug is killing farming

**Expected behavior:**
should be able to plant crops as its empty and hoed

**Actual behavior:**
error stating plant already exists there and it spreads

**Comment by purpleypete** [comment] 2018-04-02 14:18
you can drop soil on the area you can dig it up i have even smited it with the dev tool and replaced new soil but the  error remains.

**Comment by Dreepa** [comment] 2018-04-02 15:27
Might be related: I dug up the broken block, and placed it, then placed another dirt on top of it, and it started to lag like hell. Then disconnected me. After disconnect, couldn't re-enter. Stuck on "entering world".

**Comment by MarjieAVolk** [comment] 2018-04-02 21:27
Thanks for the additional information. Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4669

**Closed by MarjieAVolk** 2018-04-02 21:27 UTC
