### ISSUE TITLE
USER ISSUE: Exception with wood cart

### ISSUE THREAD

**Issue by adraax** [StrangeLoopGames/EcoIssues#6553] opened 2018-03-27 20:43 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
walk with a wood cart and hit a door

**Expected behavior:**
block the cart

**Actual behavior:**
The game crashed

The following error message popped up:
```
Caught exception:

<size=60,00%>Specified argument was out of the range of valid values.
Parameter name: arrayIndex


Stack:
  at System.Collections.Immutable.Requires.FailRange (System.String parameterName, System.String message) [0x00008] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at System.Collections.Immutable.Requires.Range (System.Boolean condition, System.String parameterName, System.String message) [0x00003] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at System.Collections.Immutable.ImmutableList`1[T].CopyTo (T[] array, System.Int32 arrayIndex) [0x00027] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at Eco.Core.Utils.ThreadSafeList`1[T].CopyTo (T[] array, System.Int32 arrayIndex) [0x00000] in <569bab362eba420a9b26a3eab1a624f9>:0 
  at System.Collections.Generic.List`1[T].InsertRange (System.Int32 index, System.Collections.Generic.IEnumerable`1[T] collection) [0x000aa] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Collections.Generic.List`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] collection) [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at Eco.Plugins.Networking.QuadTreeNode`1[T].AddSubTreeContents (System.Collections.Generic.List`1[T] collection) [0x0000e] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Plugins.Networking.QuadTreeNode`1[T].AddSubTreeContents (System.Collections.Generic.List`1[T] collection) [0x0002f] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Plugins.Networking.QuadTreeNode`1[T].AddSubTreeContents (System.Collections.Generic.List`1[T] collection) [0x0002f] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Plugins.Networking.QuadTreeNode`1[T].Query (Eco.Shared.Math.Rect queryArea, System.Collections.Generic.List`1[T] results, System.Boolean rootNode) [0x0019d] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Plugins.Networking.QuadTreeNode`1[T].Query (Eco.Shared.Math.Rect queryArea, System.Collections.Generic.List`1[T] results, System.Boolean rootNode) [0x001bb] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Plugins.Networking.QuadTreeNode`1[T].Query (Eco.Shared.Math.Rect queryArea, System.Collections.Generic.List`1[T] results, System.Boolean rootNode) [0x001bb] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Plugins.Networking.QuadTreeNode`1[T].Query (Eco.Shared.Math.Rect queryArea, System.Collections.Generic.List`1[T] results, System.Boolean rootNode) [0x00181] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Plugins.Networking.QuadTree`1[T].Query (Eco.Shared.Math.Rect area) [0x00006] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects (Eco.Shared.Networking.INetObjectViewer viewer, System.Collections.Generic.ICollection`1[T] alreadyRelevant) [0x00081] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Shared.Networking.NetObjectManager.GetRelevantObjects (Eco.Shared.Networking.INetObjectViewer viewer, System.Collections.Generic.ICollection`1[T] alreadyRelevant) [0x00005] in <226b109000b746a38ec300eaaddcb16d>:0 
  at Eco.Plugins.Networking.Clients.Client.Update (System.Diagnostics.Stopwatch timer) [0x0007d] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
  at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1 () [0x00012] in <49479a30e3dc4cd5becdfe72b76ae4c8>:0 
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-27 23:21
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5932 - should be fixed in latest version.

**Closed by MarjieAVolk** 2018-03-27 23:21 UTC

**Comment by MarjieAVolk** [comment] 2018-03-27 23:22
Sorry, it's actually https://github.com/StrangeLoopGames/EcoIssues/issues/5527
