### ISSUE TITLE
USER ISSUE: Control Pop-up prompts "Right click to place" when action is invalid

### ISSUE THREAD

**Issue by Mirrani0163** [StrangeLoopGames/EcoIssues#4047] opened 2018-02-07 17:18 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
Start a game not on a server, exit the game and the program, re-enter the game.

**Expected behavior:**
World should be saved as it was when exiting, character should be the same, ets. Workbench: Should be able to dump supplies in, unless that has changed. The command is there.

**Actual behavior:**
I was given a totally different world, then a totally different character on my second try. I now do not have my alpha rewards accessable to me. Workbench: Can not put supplies in unless I start up a work project that requires said materials, it will only take materials needed. Why have in inventory button if it won't store what is put in it?

**Comment by Nanders** [comment] 2018-02-07 18:24
Workbenches no longer have local storage, you need to build a nearby storage chest or stockpile.

It is a bug that you get the control pop-up for placing items in the workbench when this is an invalid action, though.

**Comment by Nanders** [comment] 2018-02-07 18:26
Login / name issue is a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3998

**Comment by Mirrani0163** [comment] 2018-02-08 11:09
Thanks. I did seem to recall that actions with workbenches changed at some point, but since the interaction seemed available, it was confusing since I'd never played without benchanting storage. Just proves how long ago I was able to play in alpha.

**Comment by Mirrani0163** [comment] 2018-02-08 11:11
*Workbench storage. It won't let me edit that.

**Comment by johnkslg** [comment] 2018-03-05 23:53
You can still right click to add them to the work order, so it's not inaccurate.  If you dont have a work order running, though it will still display it.  Lowering in priority for now.

**Comment by SlayksWood** [comment] 2019-12-25 08:20
I assume this issue is no longer occurring.

**Closed by SlayksWood** 2019-12-25 08:20 UTC
Labels: Medium Priority
