### ISSUE TITLE
Error: ( object object)

### ISSUE THREAD

**Issue by Dipster1989** [StrangeLoopGames/EcoIssues#10510] opened 2019-01-04 10:26 UTC
When ever I try to vote on elections or laws I fill out entire page then get the error message when I try to submit!

**Comment by elfl0rd** [comment] 2019-01-04 10:46
Duplicate of #10154

**Comment by Dipster1989** [comment] 2019-01-04 16:47
How do I fix this?

**Comment by BlazeGuy2** [comment] 2019-01-04 19:23
There is a fix for it in our master branch.  It should come out with our 8.0 release.

**Closed by BlazeGuy2** 2019-01-04 19:23 UTC
