### ISSUE TITLE
Default World on Steam failing to load causing "Connection Failed" Error

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4825] opened 2018-02-19 15:10 UTC
Been getting a lot of these lately where people go to start up an SP game to try out ECo and immediately get a "Connection Failed" and thing there game is not connecting at all.  After seeing these have been getting the player to choose 'Generate New" and the World Generates and connects just fine and they have no more connection issues.  Is there a problem with the default world?
https://www.dropbox.com/s/1bc3mj41z6q250q/Crash_AggregateException_02191300.ecodmp?dl=0
https://www.dropbox.com/s/q3pdbh15200lspg/Crash_AggregateException_02191457.ecodmp?dl=0
https://www.dropbox.com/s/fjgdajy08arwhtl/Crash_AggregateException_02194105.ecodmp?dl=0
https://www.dropbox.com/s/auov7c7vix224oy/Crash_AggregateException_02194130.ecodmp?dl=0
https://www.dropbox.com/s/0axmvhtqewmxt6n/Crash_AggregateException_02194221.ecodmp?dl=0

**Comment by MarjieAVolk** [comment] 2018-02-20 20:07
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4305

**Closed by MarjieAVolk** 2018-02-20 20:07 UTC
