### ISSUE TITLE
[8.0.0 Bleeding edge] Fish trap not placing

### ISSUE THREAD

**Issue by akutamatata** [StrangeLoopGames/EcoIssues#11046] opened 2019-02-02 18:06 UTC
In bleeding edge(8.0) fish traps seem to not be able to be placed(often), they will place on the rare occasion but it seems random, sometimes multiple can be placed close together and other times it won't let any be placed.

**Comment by SeanAtr0n** [comment] 2019-02-05 19:46
sounded like @craig-jong was looking at this? dual assignment is confusing

**Comment by elfl0rd** [comment] 2019-02-21 22:36
Duplicate of #10849

**Comment by elfl0rd** [comment] 2019-02-21 22:37
@D3nnis3n can you select one? My oldest, this have high priority =)

**Comment by seccombew** [comment] 2019-03-13 07:09
Closing as dupe.

**Closed by seccombew** 2019-03-13 07:09 UTC
Labels: High Priority
