### ISSUE TITLE
Store Buy/Sell: Customer inventory not being checked when buying/selling

### ISSUE THREAD

**Issue by JamesTalon** [StrangeLoopGames/EcoIssues#11201] opened 2019-02-09 03:57 UTC
**Version: 0.8**

**Steps to Reproduce:**
Sell more items than you have in your inventory
Buy more items than you can fit in your inventory

**Expected Behavior:**
Corrects amount to what is in your inventory or tells you that you do not have that much
Tells you that you do not have enough space for the purchase

**Actual Behavior:**
Gives money for amount set (ie 1000) while only taking actual inventory (ie 1)
Deducts money from account for full purchase, only gives what you can hold in personal/linked inventory

**Do you have mods installed? Does issue happen when no mods are installed?:**
DiscordLink is only installed mod

**Comment by elfl0rd** [comment] 2019-02-09 07:39
Duplicate of #11140

**Closed by elfl0rd** 2019-02-09 07:39 UTC
