### ISSUE TITLE
USER ISSUE: Map not showing players

### ISSUE THREAD

**Issue by Annoyed1** [StrangeLoopGames/EcoIssues#4327] opened 2018-02-11 15:12 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Not sure what caused it, was just using it	

**Expected behavior:**
Show players on the map

**Actual behavior:**
There are no players on the map

**Comment by MarjieAVolk** [comment] 2018-02-13 03:28
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3770 . You can track the issue progress there.

**Closed by MarjieAVolk** 2018-02-13 03:28 UTC
