### ISSUE TITLE
Object labels and custom names for items

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6384] opened 2018-03-22 22:54 UTC
I would really like to see objects with labels on them, e.g., when I walk up to a tree, it would be nice to see what kind of tree it is before I start chopping it - same with different types of ores and plants. I suppose even animals (or possibly after it's been killed). 

Also, the ability to name items such as storage chests, buildings with the same idea in mind. I walk up to a stack of 5 chests and before I have to rummage through them all to find what I'm looking for, each one could be named and I'd see that name label on each one if I stand in front of it. "Food", "Finished Items", "Raw Mats", etc.

**Comment by MarjieAVolk** [comment] 2018-05-14 23:36
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7107

**Closed by MarjieAVolk** 2018-05-14 23:36 UTC
Labels: Feature, Suggestion
