### ISSUE TITLE
USER ISSUE: Brick Glitch

### ISSUE THREAD

**Issue by boomy46** [StrangeLoopGames/EcoIssues#7060] opened 2018-04-08 06:28 UTC
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
placed a brick next to coal and could see through the world

**Expected behavior:**
it shouldnt be able to see through the world

**Actual behavior:**
shouldnt see through the world
![20180408142842_1](https://user-images.githubusercontent.com/5836002/38464029-38f61a94-3b39-11e8-9d99-14885561e6f2.jpg)

**Comment by elfl0rd** [comment] 2018-04-08 13:53
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/4286

**Comment by MarjieAVolk** [comment] 2018-04-09 20:29
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4286

**Closed by MarjieAVolk** 2018-04-09 20:29 UTC
Labels: High Priority
