### ISSUE TITLE
Enhancement: Require "Logs" to function

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2560] opened 2017-10-16 22:21 UTC
Some things require having logs built into the building somewhere and when in late game you wish to make modern buildings or something like that you don't really think of logs.
So adding something like "Requires: Logs or Mortared Stone" would be nice to most things.
Things requiring logs to function:
Quarry,
Store,
Mill,
Research Table,
Carpentry Table,
Wainwright Table,
Repair Station,
Farmers Table or Butchery Table
I might have missed some tables but you get my point.

**Comment by MarjieAVolk** [comment] 2017-10-16 23:23
Yes, we agree!  Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1696

**Closed by MarjieAVolk** 2017-10-16 23:23 UTC
