### ISSUE TITLE
Alpha.6 [Cc778b68] - Some tooltips missing on Linux server

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2084] opened 2017-09-10 09:59 UTC
e.g. only the second and third under the right one (also no tooltip) in Agriculture has a tool tip   
![image](https://user-images.githubusercontent.com/1900106/30247944-46c14956-961f-11e7-8b42-75218fa54dbe.png)

Its quite hard to find out what is what if you play the game for the first time (like me).

Client: Linux Ubuntu 64Bit

**Comment by MarjieAVolk** [comment] 2017-09-11 18:46
Hmm, yes they should all have tooltips.  I see tooltips for all of them on my machine.  Maybe this is a linux problem?

**Comment by Fank** [comment] 2017-09-11 18:54
Not sure are tooltips depends on server response?

**Comment by MarjieAVolk** [comment] 2017-09-11 19:06
Yes, the content is received from the server each time they are opened.

I do notice that the tooltip in your screenshot is also missing its title.  Which is very strange.  So that does suggest a server problem

**Comment by Fank** [comment] 2017-09-11 19:07
We dont have a windows server so all runs with mono on linux this may cause issues.

**Comment by Fank** [comment] 2017-09-11 19:20
This maybe related:    
![image](https://user-images.githubusercontent.com/1900106/30292570-f9e5b28e-9736-11e7-93eb-9ce3bebf8542.png)

We noticed some issues with our mono server, but it runs and don't crash so :D

**Comment by MarjieAVolk** [comment] 2017-09-11 19:32
That does look related - so you've got different reflection stuff going on it looks like, which doesn't behave the same way as it does on our machines.  Hmmmmm... maybe that's an argument for not using reflection here

**Comment by Fank** [comment] 2017-09-13 17:06
@MarjieAVolk this is a linux server issue only (got our windows server today and its working fine), normaly it can be closed. But should we keep it open to tracking linux server related issues (for .net core ?)

**Comment by MarjieAVolk** [comment] 2017-09-13 17:18
Good to hear; I'll de-prioritize this for now, but might as well leave it open.

**Comment by Fank** [comment] 2017-09-13 17:19
You should label it with "mono server" or something like that.

**Comment by LiaungYip** [comment] 2018-03-12 13:45
This appears to be fixed on 0.7.2.3. (!!!)

Our 0.7.2.3 server running on Mono / Ubuntu Linux appears to have fully functioning tooltips.

Will track on following releases and check for regression.

**Comment by SeanAtr0n** [comment] 2018-05-14 23:56
sounds like this might be resolved, please reopen if its not

**Closed by SeanAtr0n** 2018-05-14 23:56 UTC
Labels: Low Priority
