### ISSUE TITLE
USER ISSUE: Huckleberry bushes not showing ripe berries.

### ISSUE THREAD

**Issue by TraV9** [StrangeLoopGames/EcoIssues#24742] opened 2024-02-05 14:10 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Not sure, after update ripe berries stopped showing on all natural and planted bushes.

I figured this out by going up to my bare bushes and trying to collect berries, to my surprise the berry animation plays and I am able to collect berries.

**Expected behavior:**
Bushes should show berries 

**Actual behavior:**
Never shows berries ever unless being harvested.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods ever, and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-02-05 16:26
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11288

**Closed by D3nnis3n** 2024-02-05 16:26 UTC
