### ISSUE TITLE
USER ISSUE: extremely slow world loading

### ISSUE THREAD

**Issue by FreshPott** [StrangeLoopGames/EcoIssues#25257] opened 2024-11-15 23:39 UTC
\
**User Id: (d3b8c3de-afc4-4c91-af11-08dcfdbdc43c)**
**Version:** 0.11.1.1 beta release-758

**Steps to Reproduce:**
i select a world to load and it loads in Bytes, not even KBs. Google Speedtest shows 400+ Mb/s download and 20+ Mb/s upload

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Cancelled by user
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-11-24 11:20
Closing due to not being reproducible and no further information provided. Feel free to open a new issue when you can provide the requested information.

**Closed by D3nnis3n** 2024-11-24 11:20 UTC
Labels: Status: Needs Information
