### ISSUE TITLE
Another Server Crash from Sea-Otter

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12325] opened 2019-05-16 16:59 UTC
> --BEGIN DUMP--
> Dump Time
> 05/02/2019 18:08:09
> 
> Exception
> Exception: ArgumentException
> Message:Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
> Source:mscorlib
> 
> System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
>    at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
>    at Lidgren.Network.NetBuffer.ReadBytes(Int32 numberOfBytes)
>    at Eco.Shared.Networking.NetMessage.DecodePacket(NetIncomingMessage message)
>    at Eco.Plugins.Networking.NetworkServer.<Initialize>b__22_0()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 
> --END DUMP--

As ever, feel free to find the cause and fix it, if you can't, close it given i do not have any further information, just pasting it from the dump folder.

**Comment by mirasrael** [comment] 2019-06-26 07:47
Hard to identify root cause for this stack trace. Closing for now.

**Closed by mirasrael** 2019-06-26 07:47 UTC
Labels: High Priority

**Comment by mirasrael** [comment] 2019-06-26 07:49
It won't cause crash in 8.2.1 if client using incompatible binary protocol. So may count is as fixed.

**Comment by D3nnis3n** [comment] 2019-06-26 07:50
As i said, given i only have the dumps but no more information thats the best you could have done.
