### ISSUE TITLE
Can't propose any laws - red bar

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5559] opened 2018-03-07 07:31 UTC
See the screenshot.
<img width="1687" alt="law" src="https://user-images.githubusercontent.com/25908592/37079168-f3c248e6-21e1-11e8-895e-a596ceb9f550.png">

**Comment by CompactDisc** [comment] 2018-03-07 09:43
So this still happens? :( I was hoping that would get fixed this update.

**Comment by D3nnis3n** [comment] 2018-03-07 10:16
I had hoped so, too. :(

**Comment by D3nnis3n** [comment] 2018-03-08 09:52
Fixable by removing the Citizenship law. Should be fixed sooner than later.

**Comment by CompactDisc** [comment] 2018-03-08 10:42
Wow, how did you find that out?

**Comment by MarjieAVolk** [comment] 2018-03-08 20:47
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4094.

The empty red bar seems to be related to login problems, so closing the tab and reopening it from in game again can sometimes refresh it and cause error messages to show again.  Usually there is a valid error message that is supposed to be shown there, but it is just not being shown, as far as we can tell.

**Closed by MarjieAVolk** 2018-03-08 20:47 UTC

**Comment by D3nnis3n** [comment] 2018-03-08 20:51
I tried at least a hundred times to create laws since it stopped working
with this red bar when 7.1 was released. Removing the citizenship law
solved this. Relogging did never help.

Am 08.03.2018 21:47 schrieb "MarjieAVolk" <notifications@github.com>:

**Comment by CompactDisc** [comment] 2018-03-09 00:23
I can confirm, I had the same issue since 7.1.
