### ISSUE TITLE
USER ISSUE: Cannot log in

### ISSUE THREAD

**Issue by Rufusroberts** [StrangeLoopGames/EcoIssues#21596] opened 2021-04-27 05:49 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
Attepmt to login

**Expected behavior:**
Expected to log in even after waiting 2 hours twice and changing username and password.

**Actual behavior:**
The following error message popped up:
```
Too many failed attempts. Blocked for 2 hours.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, however the server i last played on did

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment] 2021-05-03 03:25
@Rufusroberts Thank you for reporting this issue and we apologize you facing this experience.

does this issue persist after this day? are you able to login to the game now?

**Comment by Daniel-Magulado** [comment] 2021-05-11 03:48
Hi, just a follow-up. Are you still experiencing this issue?

**Comment by Rufusroberts** [comment] 2021-05-12 04:29
After changing my username and waiting a further 2 hours I was able to
login.

**Comment by Daniel-Magulado** [comment] 2021-05-26 13:56
Hi @Rufusroberts,


Glad to know that you're able to log in again.
I'll be closing this ticket since the issue is now resolved.
Do not hesitate to write another one if you encounter game issues or game bugs.

**Closed by Daniel-Magulado** 2021-05-26 13:56 UTC
Labels: Status: Needs Information
