### ISSUE TITLE
USER ISSUE: Fish not being updated

### ISSUE THREAD

**Issue by QuantumGO** [StrangeLoopGames/EcoIssues#4653] opened 2018-02-16 19:05 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Catch a fish
2. Hook in the fish

**Expected behavior:**
Get the fish in your inventory

**Actual behavior:**
Doesnt go in your inventory, only after a rejoin

**Comment by VAlex0** [comment] 2018-02-17 20:55
-> already in this isses #4588

**Comment by MarjieAVolk** [comment] 2018-02-20 21:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

**Closed by MarjieAVolk** 2018-02-20 21:53 UTC
