### ISSUE TITLE
[8.0.0 Steam Build] Mining Tutorial does not work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10678] opened 2019-01-15 11:28 UTC
There is no more "Stone". "Sandstone" and other types don't work.

![sandstone](https://user-images.githubusercontent.com/25908592/51177808-feda0800-18c0-11e9-8eaa-c5157ca3b309.png)

**Comment by seccombew** [comment] 2019-01-15 19:05
Closing as dupe of #10552

**Closed by seccombew** 2019-01-15 19:05 UTC
Labels: High Priority, Quality Assurance
