### ISSUE TITLE
[0.8.2.0 staging-3]  Not all Dirt can handled by a hoe

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12224] opened 2019-05-08 13:38 UTC
Step to reproduce:
- Dig the top layer of dirt
![image](https://user-images.githubusercontent.com/45708377/57378543-aa2f0580-71ad-11e9-8ede-208f2cfb8d5d.png)
- You can't handled this Dirt by a Hoe/ Handle Plough / Steam Tractor Plough.

- Sometimes such Dirt appears as an upper layer when generating the world.
![image](https://user-images.githubusercontent.com/45708377/57378521-9f747080-71ad-11e9-9bae-0c6d9e9e615d.png)

It start from 0.8.0.0. You need to dig and place Dirt then you can handled by a hoe.
In 0.8.2.0 only Desert Biome works as in 0.7.8.9

**Comment by redwyre** [comment] 2019-05-08 14:40
This is "rocky soil" which is a different block compared to plain dirt. I think a solution could be hoeing rocky soil could turn it in to normal dirt, which would then be hoed as normal.
I'll downgrade this as it's working correctly, but we can keep the issue as it can be confusing

**Comment by SlayksWood** [comment] 2019-05-08 14:43
@redwyre 
Then we need Steam Tractor Cultivator

**Comment by metachronism** [comment] 2019-05-08 18:14
this is intended.  The top layer is 'topsoil' which is used for planting/etc, below that the soil is not suitable to be used to plant

**Comment by D3nnis3n** [comment] 2019-05-09 05:08
Actually, when you dig the rocky soil up and place it again it magiallcy became dirt so it can be used. Closing for working as intended.

**Closed by D3nnis3n** 2019-05-09 05:08 UTC
Labels: Low Priority, QA

**Comment by redwyre** [comment] 2019-05-09 13:27
Yeah, that's what I said, but it would be _nicer_ if you could just double hoe it instead

**Comment by D3nnis3n** [comment] 2019-05-09 13:28
This still would be a case for a suggestion than, though.

**Comment by redwyre** [comment] 2019-05-09 13:30
The "bug" here would be the confusion of the difference between rocky soil and dirt (which isn't explained, you just have to figure it out)
