### ISSUE TITLE
USER ISSUE: I am falling forever

### ISSUE THREAD

**Issue by grantdwoods** [StrangeLoopGames/EcoIssues#5260] opened 2018-03-01 05:26 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Fall.
Fall forever

**Expected behavior:**
not fallen

**Actual behavior:**
fell forever
![falling](https://user-images.githubusercontent.com/36683196/36828337-fc634e50-1ccd-11e8-8067-9d8d520483fd.png)

**Comment by MarjieAVolk** [comment] 2018-03-01 19:51
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3897, https://github.com/StrangeLoopGames/EcoIssues/issues/4948, and/or https://github.com/StrangeLoopGames/EcoIssues/issues/3861

**Closed by MarjieAVolk** 2018-03-01 19:51 UTC
