### ISSUE TITLE
USER ISSUE: Item in hand

### ISSUE THREAD

**Issue by Dennisd2k** [StrangeLoopGames/EcoIssues#6364] opened 2018-03-22 10:44 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Have an item in your active slot/hand
2. Drag that item into a workbench/repairstation

**Expected behavior:**
Go into the slot where it's being dragged to	

**Actual behavior:**
Bugs out and becomes invisible on your slotbar and the image stays on your hud

**Comment by Dennisd2k** [comment] 2018-03-22 10:46
Apparently alt+tab fixes it

**Comment by MarjieAVolk** [comment] 2018-03-22 18:28
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

I may have found a way to fix this in 7.3

**Closed by MarjieAVolk** 2018-03-22 18:28 UTC
