### ISSUE TITLE
"Roots are too strong"

### ISSUE THREAD

**Issue by Milben** [StrangeLoopGames/EcoIssues#10542] opened 2019-01-06 14:45 UTC
**Version:** 0.7.8.8 beta

**Steps to Reproduce:**
On a 3*3*2 square of dirt in the swamp biome im unable to dig the dirt because "the roots are too deep." there were no trees or similar there

**Expected behavior:**
The blocks of Dirt should be destructable

**Actual behavior:**
Beeing undestroyable like the dirt below a tree

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/46420932/50737470-036c3580-11ca-11e9-9b12-94a0b94894fe.gif)

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by elfl0rd** [comment] 2019-01-06 14:58
server? singleplayer?
Server restart fixes this issue.

**Comment by Milben** [comment] 2019-01-06 15:03
> 
> 
> server? singleplayer?
> Server restart fixes this issue.
> Tree on this position before you dig?
> Looks as #8367

It is a Server of my friend. there wasnt a tree at that position as far as I know. It is not #8367 but I have experienced that often too.

But yea, the Server restart fixed it. Thanks.

**Comment by elfl0rd** [comment] 2019-01-07 06:50
@D3nnis3n if restart fixes it - duplicate of #8367 where i found reproducion way.

**Comment by BitsBytesGaming** [comment] 2019-01-07 15:43
Restarting the server normally fixes this issue, I’ve seen it many times before

**Comment by BlazeGuy2** [comment] 2019-01-07 18:42
Closing as dup of https://github.com/StrangeLoopGames/EcoIssues/issues/8367

**Closed by BlazeGuy2** 2019-01-07 18:42 UTC
Labels: Investigate, Medium Priority
