### ISSUE TITLE
USER ISSUE: Alphabetic list & transaction

### ISSUE THREAD

**Issue by Gaokin** [StrangeLoopGames/EcoIssues#6645] opened 2018-03-29 10:46 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
When i check item listed by alphabetic order, it's on order of english names, not in french

**Expected behavior:**
It should be listed by alphabetic order in french names

**Actual behavior:**
Instead it's listed by english names

**Comment by geeknessfr** [comment] 2018-03-30 01:45
Duplicate of #6599

**Comment by MarjieAVolk** [comment] 2018-04-04 00:04
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6599

**Closed by MarjieAVolk** 2018-04-04 00:04 UTC
