### ISSUE TITLE
Sometimes objects can disappear

### ISSUE THREAD

**Issue by Duffman1200** [StrangeLoopGames/EcoIssues#16480] opened 2020-05-25 22:18 UTC
![20200525181829_1](https://user-images.githubusercontent.com/65468342/82845859-2f1db780-9eb4-11ea-8cdb-200df8365fdc.jpg)

**Version:** 0.9.0.0 beta staging-1554

**Steps to Reproduce:**
have stockpile full of carcasses.  unknown cause

**Expected behavior:**
normal stockpile behavior

**Actual behavior:**
stockpile object disappeared, leaving crates unaccessable

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes

**Comment by MonzUn** [comment] 2020-05-26 07:17
Relogging is a workaround for this issue. It can happen to all kinds of objects.

**Comment by beastyn** [comment] 2020-05-26 12:15
@Duffman1200 thank you for the report. Can you provide a log file from that session?

Instruction:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by WeaselDog** [comment] 2020-06-30 17:48
Hi @Duffman1200 . We are not able to reproduce this issue. Are you still having this problem? If you could provide logs from the session you are having this issue it would be much appreciated.

**Comment by MonzUn** [comment] 2020-07-01 08:49
I get this issue every now and then. happened at least 20 times during the last season we played.
I'll make sure to get a log the next time it happens.

There is a bug that sometimes causes items to not be loaded in fully. They are still there in terms of physics, but they can't be seen or interacted with by the local player (This is actually a reason why we sometimes get stumps left by players who usually always clears them). When that happens to a stockpile, it still renders the items inside of it and it can still be accessed by opening a nearby storage, but it is not possible to interact with it directly via the object in the world.

**Comment by MishkaFur** [comment] 2020-07-01 08:51
I had this happen back in March, believe it was due to placing stockpiles during period of heavy lag and the server then restarting but having not saved the location of them, so soon as it restarts it just empties the contents out of which if its a crate nothing can be picked up.

Dennis had to devtool delete the broken crates, has not happened for me in current playtest 1611 nor seen reports of it

**Comment by MonzUn** [comment] 2020-07-01 10:34
Hm, I think we're looking at different issues @MishkaFur.
The ones I (and at least all my mods and probably most players as well) have had, have always been local only and always fixable via relogging.

**Comment by SlayksWood** [comment] 2020-11-11 06:50
> **Version:** 0.9.1.3 beta release-115
> 
> **Steps to Reproduce:**
> Random bug, don't really know how to reproduce it, just kept playing for a while move around the map do stuff. When return to my food stores - no chests found where i left them (playing solo on private server). If i quit and reenter game chests will respawn where they actually was with all the stuff in. I got this bug for three times - today on 9.1.3, yesterday on 9.1.2 and long ago (when some of tables disappears too may be on 9.1). It's not visual bug, i can move on the chests position and interact, like they are really not here.
> 
> **Expected behavior:**
> Chests be were they should be.
> 
> **Actual behavior:**
> Chests disappearing (and tables possibly too)
> 
> **Do you have mods installed? Does the issue happen when no mods are installed?:**
> no, yes
> 
> **Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5517233/Player.log)
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5517234/Player-prev.log)
> Logs provided before restarting the game.
> 
> bug:
> ![20201110151519_1_chests_disappear](https://user-images.githubusercontent.com/10298859/98675150-ea56e180-236a-11eb-9b14-468a34be88bc.jpg)
> after restart:
> ![20201110153802_1_game_restarted_chests_respawn](https://user-images.githubusercontent.com/10298859/98675147-e925b480-236a-11eb-82d3-52ae7fca1f80.jpg)

**Comment by SlayksWood** [comment] 2021-06-04 07:44
merged to #19797

**Closed by SlayksWood** 2021-06-04 07:44 UTC
Labels: Status: Investigate
