### ISSUE TITLE
USER ISSUE: Tree Disappearing

### ISSUE THREAD

**Issue by iComputerfreak** [StrangeLoopGames/EcoIssues#5098] opened 2018-02-25 21:56 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Fell a tree
2. Cut a piece off and press E to collect it
3. Whole log disappears
4. Reconnect
5. Log visible again
6. Hit the log to cut a piece off
7. Got kicked from the server with the error

**Expected behavior:**
Log should not have disappeared when the first slice got cut off

**Actual behavior:**
Error:
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
   bei TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   bei Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   bei Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-26 19:50
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-26 19:50 UTC
