### ISSUE TITLE
USER ISSUE: Crimini Mushroom

### ISSUE THREAD

**Issue by seene** [StrangeLoopGames/EcoIssues#6247] opened 2018-03-18 17:59 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
there is not a single cimini mushroom in the whole World. So i cant research the farming skill

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-03-21 18:45
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Closed by MarjieAVolk** 2018-03-21 18:45 UTC
