### ISSUE TITLE
USER ISSUE: Visual bug Cranes

### ISSUE THREAD

**Issue by DiendaPhoenix** [StrangeLoopGames/EcoIssues#24606] opened 2024-01-14 16:49 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Go sit in a crane (claimed or unclaimed land) -person 12. Have another person look at your crane -person 23. Move your crane -person 1

**Expected behavior:**
person 2 should see it moving

**Actual behavior:**
person 1 sees it moving, but person 2 does not

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-29 00:07
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24359

**Closed by D3nnis3n** 2024-01-29 00:07 UTC
