### ISSUE TITLE
Game Crashin to desktop in Multiplayer

### ISSUE THREAD

**Issue by TFTManus** [StrangeLoopGames/EcoIssues#22644] opened 2021-09-08 01:16 UTC
Whenever I travel thorugh the MP Server I play on, the game randomly crashes to desktop. Sometimes multiple times into a row. I have attached the last logs right after the most recent crash. 

I would love to hear what the issue is, I'm at a loss. Thank you

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7125061/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7125062/Player-prev.log)

**Comment by Daniel-Magulado** [comment] 2021-09-10 16:45
Hi @TFTManus 

Thank you for writing this bug report. Upon checking the logs that you provided here, it seems that your system do not meet the minimum system requirements of Eco. Your system must be at least running on an i5-6500 3.2 GHz Quad-Core. Playing on a system with lower specification than the minimum system requirement will only result to an unfavorable experience.

Closing this as this is not a bug.

**Closed by Daniel-Magulado** 2021-09-10 16:45 UTC
