### ISSUE TITLE
7.2.0 - Server List Causing Crash

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#5501] opened 2018-03-07 01:34 UTC
In 7.2.0, when I open the server list and it starts parsing servers, it crashes after a few entries have loaded. I restarted the client several times and had the same result.

**Comment by Macmorious** [comment] 2018-03-07 11:41
Same thing here. Its not new to me though.
I have it since i bought the game on steam release.
I find it weired that none of my threads regarding this issue has beentaken seriously or even been looked at. 
Im aware that this is early access and you guys have a lot of stuff to fix, but since i cant join any server and the multiplayer dependency is in the ECOnomy part of the game title, i havent been able to play the game apart from like 20 min singleplayer doodling around.
I'm going on a field trip the next couple of days, and if no admin or developer person has made a statement about this by then, i'm going to give back the game on account that it's simply not playable for me.
As i said before I'm aware that you're busy though.
So enough with the whining! here's my crash report:
Eco [version: Unity 2017.3.0f3 (a9f86dcd79df)]

Unknown caused an Access Violation (0xc0000005)
  in module Unknown at 0033:f5bd1dd3.

Error occurred at 2018-03-07_113054.
D:\SteamLibrary\steamapps\common\Eco\Eco.exe, run by Grego.
32% memory in use.
16240 MB physical memory [10980 MB free].
19568 MB paging file [12472 MB free].
134217728 MB user address space [134215682 MB free].
Read from location 00000018 caused an access violation.

Context:
RDI:    0xaad24618  RSI: 0xba888000  RAX:   0x00000000
RBX:    0xa3ca9390  RCX: 0x00000000  RDX:   0xbb01c400
RIP:    0xf5bd1dd3  RBP: 0xa21bf4f0  SegCs: 0x00000033
EFlags: 0x00010206  RSP: 0xa21bf4b8  SegSs: 0x0000002b
R8:    0x00000000  R9: 0xa21bee50  R10:   0x00000000
R11:    0xf5bd1dd0  R12: 0xa21bfe48  R13:   0xf5d74d48
R14:    0x00000000  R15: 0xaad24618

Bytes at CS:EIP:
48 8b 40 18 48 85 c0 74 01 c3 48 8b c9 e9 65 b5 

Stack:
0xa21bf4b8: f62f6bb5 0000016f aad24618 0000016f .k/.o....F..o...
0xa21bf4c8: 00000000 00000000 f5bd1f50 0000016f ........P...o...
0xa21bf4d8: b7757480 0000016f bb01c400 0000016f .tu.o.......o...
0xa21bf4e8: 00000000 00000000 a21bf5d0 00000051 ............Q...
0xa21bf4f8: 89e04d3b 0000016f 00000000 00000000 ;M..o...........
0xa21bf508: 00000000 00000000 00000000 00000000 ................
0xa21bf518: 00000000 00000000 00000000 00000000 ................
0xa21bf528: da982a00 0000016f aa83d070 0000016f .*..o...p...o...
0xa21bf538: ba888000 0000016f 00000000 00000000 ....o...........
0xa21bf548: da9a9690 0000016f da982a00 0000016f ....o....*..o...
0xa21bf558: da9a5980 0000016f aad24618 0000016f .Y..o....F..o...
0xa21bf568: 0000000f 00000000 00000000 00000000 ................
0xa21bf578: ffef5980 0000016f 89df98d0 0000016f .Y..o.......o...
0xa21bf588: a21bfe48 00000051 f5d74d48 0000016f H...Q...HM..o...
0xa21bf598: 00000000 00000000 aad24618 0000016f .........F..o...
0xa21bf5a8: 0000000f 00000000 f5bd1d10 0000016f ............o...
0xa21bf5b8: a359e130 0000016f 82d39a49 0000016f 0.Y.o...I...o...
0xa21bf5c8: aad940e0 0000016f a21bf610 00000051 .@..o.......Q...
0xa21bf5d8: 89df9905 0000016f 00000000 00000000 ....o...........
0xa21bf5e8: ba6d3660 0000016f f5d74d48 0000016f `6m.o...HM..o...
0xa21bf5f8: a21bfe48 00000051 a21bf5c0 00000051 H...Q.......Q...
0xa21bf608: aab2ab40 0000016f a21bf7a0 00000051 @...o.......Q...
0xa21bf618: 89df83cb 0000016f 00000001 00000000 ....o...........
0xa21bf628: 00000000 00000000 00000000 00000000 ................
0xa21bf638: ab064280 0000016f 00000000 00000000 .B..o...........
0xa21bf648: aab2ab40 0000016f bb5e4380 0000016f @...o....C^.o...
0xa21bf658: aae13a00 0000016f da9a5980 0000016f .:..o....Y..o...
0xa21bf668: aad24618 0000016f aab2ab40 0000016f .F..o...@...o...
0xa21bf678: aad24618 0000016f ba8b1870 0000016f .F..o...p...o...
0xa21bf688: ab064280 0000016f f5d74d48 0000016f .B..o...HM..o...
0xa21bf698: 00000191 00000000 a21bf670 00000051 ........p...Q...
0xa21bf6a8: 00000191 00000000 00000191 00000000 ................
0xa21bf6b8: f5d74d48 0000016f a21bfe48 00000051 HM..o...H...Q...
0xa21bf6c8: da982a00 0000016f a21bf770 00000051 .*..o...p...Q...
0xa21bf6d8: 89dfd5a6 0000016f a3ca9390 0000016f ....o.......o...
0xa21bf6e8: 00000000 00000000 00000000 00000000 ................
0xa21bf6f8: 00000000 00000000 00000000 00000000 ................
0xa21bf708: 0000000d 00000000 aad940e0 0000016f .........@..o...
0xa21bf718: 00000000 00000000 00000000 00000000 ................
0xa21bf728: 00000000 00000000 ba6d3670 0000016f ........p6m.o...
0xa21bf738: ab064280 0000016f 00000000 00000000 .B..o...........
0xa21bf748: f5d74d48 0000016f a21bfe48 00000051 HM..o...H...Q...
0xa21bf758: da982a00 0000016f da982a00 0000016f .*..o....*..o...
0xa21bf768: a3ca9390 0000016f a21bf7b0 00000051 ....o.......Q...
0xa21bf778: 89e046ba 0000016f a3ca9390 0000016f .F..o.......o...
0xa21bf788: bafb90c0 0000016f bbc27528 0000016f ....o...(u..o...
0xa21bf798: a21bfe48 00000051 a21bf7f0 00000051 H...Q.......Q...
0xa21bf7a8: 89df7aac 0000016f a21bf7f0 00000051 .z..o.......Q...
0xa21bf7b8: f6283ab5 0000016f ab064280 0000016f .:(.o....B..o...
0xa21bf7c8: a21bf6f4 00000051 89e044e0 0000016f ....Q....D..o...
0xa21bf7d8: ab064280 0000016f bbc27528 0000016f .B..o...(u..o...
0xa21bf7e8: bafb90c0 0000016f a21bf980 00000051 ....o.......Q...
0xa21bf7f8: 89df54f7 0000016f bafb90c0 0000016f .T..o.......o...
0xa21bf808: a21bfd20 00000051 f5d74d48 0000016f  ...Q...HM..o...
0xa21bf818: a21bfe48 00000051 00000001 00000000 H...Q...........
0xa21bf828: bdd60ec7 00007ff8 a21bf900 00000051 ............Q...
0xa21bf838: bdd60e67 00007ff8 00000000 00000051 g...........Q...
0xa21bf848: ab064280 0000016f da982a00 0000016f .B..o....*..o...
0xa21bf858: f6284f65 0000016f f0740a20 0000016f eO(.o... .t.o...
0xa21bf868: f6282ca5 0000016f aa884700 0000016f .,(.o....G..o...
0xa21bf878: bb67f0e0 00000000 ab064280 0000016f ..g......B..o...
0xa21bf888: 00000000 00000000 00000000 00000000 ................
0xa21bf898: 00000000 00000000 00000000 00000000 ................
0xa21bf8a8: da982a00 0000016f 00000000 00000000 .*..o...........
0xa21bf8b8: 00000000 00000000 00000000 00000000 ................
0xa21bf8c8: 00000000 00000000 a3ca9390 0000009b ................
0xa21bf8d8: 00000000 00000000 00000001 0000022c ............,...
0xa21bf8e8: aab2ab40 0000016f ab064280 0000016f @...o....B..o...
0xa21bf8f8: 89da2f11 0000016f a21bf980 00000051 ./..o.......Q...
0xa21bf908: a3708a20 0000016f b8498480 0000016f  .p.o.....I.o...
0xa21bf918: a3708a20 0000016f b8498480 0000016f  .p.o.....I.o...
0xa21bf928: a3ca9390 0000016f a21bf970 00000051 ....o...p...Q...
0xa21bf938: a21bf8e0 00000051 a21bfe48 00000051 ....Q...H...Q...
0xa21bf948: f5d74d48 0000016f 00000000 00000000 HM..o...........
0xa21bf958: 00000000 00000000 aae6a7b0 0000016f ............o...
0xa21bf968: 00000000 00000000 aae6a7b0 0000016f ............o...
0xa21bf978: bafb90c0 0000016f a21bfa10 00000051 ....o.......Q...
0xa21bf988: 89da2d1b 0000016f 00000000 00000000 .-..o...........
0xa21bf998: 00000000 00000000 89da2cb0 0000016f .........,..o...
0xa21bf9a8: 89da1903 0000016f baec04d0 0000016f ....o.......o...
0xa21bf9b8: a21bfd20 00000051 a3ca9390 0000016f  ...Q.......o...
0xa21bf9c8: aae6a7b0 0000016f a21bfae0 00000051 ....o.......Q...
0xa21bf9d8: f6292900 0000016f a21bf9a0 00000051 .)).o.......Q...
0xa21bf9e8: 00000000 00000000 a21bfd20 00000051 ........ ...Q...
0xa21bf9f8: a21bfe48 00000051 b7f0c4b0 0000016f H...Q.......o...
0xa21bfa08: f6292900 0000016f a21bfa50 00000051 .)).o...P...Q...
0xa21bfa18: 89da592a 0000016f 00000000 00000000 *Y..o...........
0xa21bfa28: a21bfe48 00000051 f5bd1d10 0000016f H...Q.......o...
0xa21bfa38: b860a2b0 0000016f 89da1903 0000016f ..`.o.......o...
0xa21bfa48: bb87e380 0000016f a21bfae0 00000051 ....o.......Q...
0xa21bfa58: f629296b 0000016f d31b0000 00007ff6 k)).o...........
0xa21bfa68: 00000000 00000000 a21bfa98 00000051 ............Q...
0xa21bfa78: bdcf232d 00007ff8 f07408b0 0000016f -#........t.o...
0xa21bfa88: 89da1903 0000016f a21bfe48 00000051 ....o...H...Q...
0xa21bfa98: a21bfd98 00000051 baec04d0 0000016f ....Q.......o...
0xa21bfaa8: 00000000 00000000 00000000 00000000 ................
0xa21bfab8: bdcf228b 00007ff8 b7f0c4b0 0000016f ."..........o...
0xa21bfac8: b7f0c4b0 0000016f f6292900 0000016f ....o....)).o...
0xa21bfad8: a21bfb20 00000051 a21bfb20 00000051  ...Q... ...Q...
0xa21bfae8: bde164af 00007ff8 b7f0c4b0 0000016f .d..........o...
0xa21bfaf8: 00000000 00000051 a3ca9390 0000016f ....Q.......o...
0xa21bfb08: b7f0c4b0 0000016f bbc75cb0 00007ff8 ....o....\......
0xa21bfb18: bb6bc730 0000016f f5d74d48 0000016f 0.k.o...HM..o...
0xa21bfb28: bbbd8afb 00007ff8 00000000 00000000 ................
0xa21bfb38: a3ca9390 0000016f f5dd0d00 0000016f ....o.......o...
0xa21bfb48: baec04d0 0000016f a21bfe48 00000051 ....o...H...Q...
0xa21bfb58: a21bfd20 00000051 00000000 00007ff8  ...Q...........
0xa21bfb68: a21bfc50 00000051 a21bfcb0 00000051 P...Q.......Q...
0xa21bfb78: a21bfc00 00000051 00000003 00000051 ....Q.......Q...
0xa21bfb88: 00000004 00000000 a21bfd01 00000000 ................
0xa21bfb98: 00000000 00000010 00000000 00000000 ................
0xa21bfba8: bbc75dc0 00007ff8 00000000 00000002 .]..............
0xa21bfbb8: f07408b0 0000016f d31b0000 00007ff6 ..t.o...........
0xa21bfbc8: 00000000 00000000 a21bfcb0 00000051 ............Q...
0xa21bfbd8: 00000000 00000000 bbc75dc0 00007ff8 .........]......
0xa21bfbe8: a3bd9be0 0000016f 00000001 00000000 ....o...........
0xa21bfbf8: abbbfb60 0000016f f07408b0 0000016f `...o.....t.o...
0xa21bfc08: 00140012 00000000 f0740840 0000016f ........@.t.o...
0xa21bfc18: 0020001e 00000000 f0740a20 0000016f .. ..... .t.o...
0xa21bfc28: bde6ba35 00007ff8 a3bd9be0 0000016f 5...........o...
0xa21bfc38: 00000000 00000000 a21bfcb0 00000051 ............Q...
0xa21bfc48: 00000000 00000000 a3bd9be0 0000016f ............o...
0xa21bfc58: 2e99cc17 0000b656 2e9ac0bb 0000b656 ....V.......V...
0xa21bfc68: 00000000 00000000 bde84580 00007ff8 .........E......
0xa21bfc78: a21bfd20 00000051 bb54a910 0000016f  ...Q.....T.o...
0xa21bfc88: baec04d0 0000016f b7f0c4b0 0000016f ....o.......o...
0xa21bfc98: a21bfe48 00000051 a21bfd20 00000051 H...Q... ...Q...
0xa21bfca8: b7f0c4b0 0000016f baec04d0 0000016f ....o.......o...
0xa21bfcb8: bdd68a19 00007ff8 00000008 00000000 ................
0xa21bfcc8: 00000000 00000000 f5e397f0 0000016f ............o...
0xa21bfcd8: b860a1e0 0000016f bde82d9d 00007ff8 ..`.o....-......
0xa21bfce8: bdd6ef27 00007ff8 a21bfe48 00000051 '.......H...Q...
0xa21bfcf8: a21bfd20 00000051 8012bfb3 0000016f  ...Q.......o...
0xa21bfd08: a21bfde0 00000051 0003f4f0 00000000 ....Q...........
0xa21bfd18: bdcf232d 00007ff8 00000000 00000000 -#..............
0xa21bfd28: bde473b8 00007ff8 ffe154a0 0000016f .s.......T..o...
0xa21bfd38: a21bfe48 00000051 baec04d0 0000016f H...Q.......o...
0xa21bfd48: 00000000 00000000 b7f0c4b0 0000016f ............o...
0xa21bfd58: 2e9ac6bb 0000b656 b7f0c4b0 0000016f ....V.......o...
0xa21bfd68: ab05c980 0000016f a21bfe48 00000051 ....o...H...Q...
0xa21bfd78: 00000000 00000000 ffe154a0 0000016f .........T..o...
0xa21bfd88: bdd6f1fc 00007ff8 baec04d0 0000016f ............o...
0xa21bfd98: f5e397f0 0000016f 00000000 00000000 ....o...........
0xa21bfda8: f5e163d0 0000016f f5d74d48 0000016f .c..o...HM..o...
0xa21bfdb8: abbbfb50 0000016f ffffffff 00000000 P...o...........
0xa21bfdc8: 00000000 00000000 bde84580 00007ff8 .........E......
0xa21bfdd8: 0003f4f0 00000000 ab05c900 0000016f ............o...
0xa21bfde8: 00000000 00000000 a21bfe28 00000051 ........(...Q...
0xa21bfdf8: bdd8f873 00007ff8 f5d74d48 0000016f s.......HM..o...
0xa21bfe08: aac0a500 0000016f f5d74d48 0000016f ....o...HM..o...
0xa21bfe18: a21bfe50 00000051 bde84580 00007ff8 P...Q....E......
0xa21bfe28: f5d74d48 0000016f bb6bc730 0000016f HM..o...0.k.o...
0xa21bfe38: bdd907db 00007ff8 ab05c900 0000016f ............o...
0xa21bfe48: 00000000 00000000 aa806028 0000016f ........(`..o...
0xa21bfe58: 00000a0c 00000000 00000000 0000016f ............o...
0xa21bfe68: bafb9158 0000016f 00000000 00000000 X...o...........
0xa21bfe78: 00000000 00000000 00000001 00000000 ................
0xa21bfe88: a3b8cad0 0000016f aa867d80 0000016f ....o....}..o...
0xa21bfe98: bdd94017 00007ff8 bb6bc730 0000016f .@......0.k.o...
0xa21bfea8: bdd90674 00007ff8 00000000 00000000 t...............
0xa21bfeb8: 00000000 00000000 f5d8beb0 0000016f ............o...
0xa21bfec8: bde4987d 00007ff8 00000000 00000000 }...............
0xa21bfed8: 00000000 00000000 00000000 00000000 ................
0xa21bfee8: 00000000 00000000 00000000 00000000 ................
0xa21bfef8: bde49eab 00007ff8 00003804 00000000 .........8......
0xa21bff08: 00000000 00000000 f5d8beb0 0000016f ............o...
0xa21bff18: 00000000 00000000 00000000 00000000 ................
0xa21bff28: eef51fe4 00007ff8 f5d8beb0 0000016f ............o...
0xa21bff38: 00000000 00000000 00000000 00000000 ................
0xa21bff48: 00000000 00000000 00000000 00000000 ................
0xa21bff58: f17fefc1 00007ff8 00000000 00000000 ................
0xa21bff68: 00000000 00000000 00000000 00000000 ................
0xa21bff78: 00000000 00000000 00000000 00000000 ................
0xa21bff88: edf993c0 00007ff8 a21be580 00000051 ............Q...
0xa21bff98: a21be580 00000051 00000000 00000000 ....Q...........
0xa21bffa8: 00000000 00000000 00000000 00000000 ................
0xa21bffb8: 00000000 00000000 00000000 00000000 ................
0xa21bffc8: 00000000 00000000 00000000 00000000 ................
0xa21bffd8: 00000000 00000000 00000000 00000000 ................
0xa21bffe8: 00000000 00000000 00000000 00000000 ................
0xa21bfff8: 00000000 00000000                   ........

Module 1
C:\WINDOWS\SYSTEM32\xinput1_3.dll
Image Base: 0x00400000  Image Size: 0x0001e000
File Size:  107368      File Time:  2007-04-04_185422
Version:
   Company:    Microsoft Corporation
   Product:    Microsoft® DirectX for Windows®
   FileDesc:   Microsoft Common Controller API
   FileVer:    9.18.944.0
   ProdVer:    9.18.944.0

Module 2
C:\Program Files (x86)\Steam\vstdlib_s64.dll
Image Base: 0x657d0000  Image Size: 0x0006b000
File Size:  348960      File Time:  2017-12-15_195928
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   vstdlib_ s.dll
   FileVer:    4.28.51.7
   ProdVer:    3.0.0.1

Module 3
C:\Program Files (x86)\Steam\tier0_s64.dll
Image Base: 0x65840000  Image Size: 0x00372000
File Size:  359712      File Time:  2017-12-15_195928
Version:
   Company:    Valve Corporation
   Product:     tier0_s Dynamic Link Library
   FileDesc:   tier0_s Dynamic Link Library
   FileVer:    4.28.51.7
   ProdVer:    1.0.0.1

Module 4
C:\Program Files (x86)\Steam\steamclient64.dll
Image Base: 0x65bc0000  Image Size: 0x00df6000
File Size:  14398016    File Time:  2017-12-15_195928
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   Steamclient.dll
   FileVer:    4.28.51.7
   ProdVer:    3.0.0.1

Module 5
D:\SteamLibrary\steamapps\common\Eco\Eco_Data\Plugins\steam_api64.dll
Image Base: 0x669c0000  Image Size: 0x00040000
File Size:  245536      File Time:  2018-03-06_170118
Version:
   Company:    Valve Corporation
   Product:    Steam Client API
   FileDesc:   Steam Client API
   FileVer:    3.92.72.58
   ProdVer:    1.0.0.1


== [end of error.log] ==

**Comment by Blanclour** [comment] 2018-03-07 12:42
It seems if I check the incompatible servers button then uncheck it doesn't crash most the time if I do it fast enough.

**Comment by Macmorious** [comment] 2018-03-07 14:47
wow that works. thanks man

**Comment by Macmorious** [comment] 2018-03-07 14:53
now the connection is failing :-)

**Comment by MarjieAVolk** [comment] 2018-03-07 21:34
@Macmorious Sorry that you haven't gotten traction with this problem.  I don't see any bugs posted by you on github, so I assume you were reporting it on discord or maybe to support?  We've had some turnover in our support people, so our support it pretty behind, but we are working on getting caught up.  Github reports though I am more or less on top of >> Not to open the floodgates or anything :P

@Blanclour That's a very interesting workaround O.o  Thanks, that may help us figure it out.

Since the game is actually crashing, there proooobably won't be anything useful in here, but just in case, the next time you see this crash, could you guys send your output log?  'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'  @Macmorious If you want to send it after you see 'connection failed' too, I can look at that too.

**Comment by Blanclour** [comment] 2018-03-07 23:17
Even if I join a server and get into the server world, it still crashes around the same time it normally does for the list. The exception is if I manage to get the list to not crash by toggling the "Incompatible Servers" and spamming the stop and refresh buttons, which will not result in a crash afterwords. However the method does not always work, only some of the time.

**Comment by Cookierawks** [comment] 2018-03-21 17:44
Not sure if this is the same issue but i had/have the same problem or it's the one affecting you. But, when i click join and it starts to refresh.. it will randomly crash.

So i found a small work around..

1. Disable your firewall
2. Let the server list load
3. Re-enable firewall

I have the game whitelisted and everything in the firewall (Bitdefender) but it still crashes randomly when refreshing the servers.

I disabled the firewall and the list refreshed without any issues. then i just alt-tab out of the game to re-enable it. 

one of my buddies had the same issue to find our server and he did this and it worked. 

CookieRawks

**Comment by MarjieAVolk** [comment] 2018-03-21 17:59
Thanks @Cookierawks -- Would like to hear whether this works for others.

**Comment by Cookierawks** [comment] 2018-03-21 18:01
I can confirm 1 more instance;

https://www.reddit.com/r/EcoGlobalSurvival/comments/861l3y/anyone_else_crash_on_server_browser/

**Comment by Cookierawks** [comment] 2018-03-21 19:51
@MarjieAVolk A bit more info for you....

At random times i crashed even with my firewall disabled.. after tinkering around for a few hours here are some observations...

- Closing "chrome" seems to help (less crashing)
- When i disabled Bitdefender's firewall i was still sometimes crashing (but a lot less if chrome was closed etc
- When i crash localhost:3001 would no longer load (refused connection)
- I've noticed Windows defender firewall was on (?? why I don't know as i have a 3rd party....)
- Manually disabled windows firewall -> no crashes/worked fine (localhost works again)
- Re-enabled Bitdefender's firewall -> no crashes/worked fine (localhost still works)
- Repeated (x4) login, loading the local map, disconnecting local, join/refresh server list -> no crashes 

*eyes windows defender firewall*

Note: 

- I sometimes still get localhost connection refused when the game is closed (even though i was able in the past. 
- Also, sometimes the game 'crashes' on close. and steam still thinks it is running (task manager has no traces from what i can see) . closing steam (task manager) and relaunching works

Alot of info i know but i hope it helps pinpoint the actual issue. Ill continue to poke around but i have a feeling windows defender may have something to do with it (bad setting?).

hope that helps! LMK if u need/test anything

CookieRawks

**Comment by MarjieAVolk** [comment] 2018-03-21 21:03
Thanks for all the details!

**Comment by metachronism** [comment] 2018-03-27 21:46
give 7.3 a try, should be better, but perhaps not completely fixed

**Closed by metachronism** 2018-03-27 21:46 UTC
Labels: Medium Priority
