### ISSUE TITLE
USER ISSUE: Need to login

### ISSUE THREAD

**Issue by Troelnl** [StrangeLoopGames/EcoIssues#5374] opened 2018-03-04 17:30 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Game crashed after  putting dirt on a wood cart
2. After restart login is needed
3. SL-credentials from website won't work
4. can't play anymore	

**Expected behavior:**
It should work	

**Actual behavior:**
It does not work.

**Comment by Troelnl** [comment] 2018-03-04 17:39
Ow 5. Already restarted Steam. And the whole System. Does not work.

**Comment by Troelnl** [comment] 2018-03-05 10:17
6. Checked integraty through Steam. Does not work
7. Delete the game and reinstall. Does not work

**Comment by MarjieAVolk** [comment] 2018-03-06 00:14
Have you tried deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO?

**Comment by MarjieAVolk** [comment] 2018-03-06 00:15
Also, after getting this problem, could you send me your log file?  'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by Troelnl** [comment] 2018-03-07 12:04
I have like 15 logs now, as soon as it happends again, I will tell you.

Last time I got it working again by deleting steam and Eco, restart the computer and then reinstall.

**Comment by MarjieAVolk** [comment] 2018-03-08 20:13
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5149.  If you find any more details, repro steps, or workarounds, let me know!  Thanks!

**Closed by MarjieAVolk** 2018-03-08 20:13 UTC
