### ISSUE TITLE
USER ISSUE: Tree (Cedar) Always Says Overcrowded

### ISSUE THREAD

**Issue by daltonbohning** [StrangeLoopGames/EcoIssues#12765] opened 2019-07-16 16:53 UTC
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**
1. Find 5x5 plot for 100% Cedar match.
2. Clear plot of all plants.
3. Plant Cedar seed in center of plot.
4. Wait a few days to make sure the simulation is updated.
5. Check the Growing Cedar with a soil sampler

**Expected behavior:**
It should be growing normally, since it is the only plant in the 5x5 plot.

**Actual behavior:**
It says it is very overcrowded.

**Do you have mods installed? Does issue happen when no mods are installed?:**
There are no mods installed.

**Comment by WeaselDog** [comment] 2019-09-07 21:05
I did some experimenting and this issue is directly related to the CanopySpace requirement. Disabling the CanopySpace requirement fixes this issue. There is other unexpected behaivor with the CanopySpace such when you change it to 1 surrounding trees in the area are still marked as Overcrowded when they shouldn't be. This means the issue is related to #12975 and should be solved first.

**Closed** 2020-03-05 07:43 UTC
Labels: Priority: Medium, Status: Fixed
