### ISSUE TITLE
USER ISSUE: Items lost when transferring items

### ISSUE THREAD

**Issue by gerwim** [StrangeLoopGames/EcoIssues#8027] opened 2018-06-11 17:36 UTC
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
I was transferring items between my wooden cart and stockpiles and I lost a full cart of brick. (Note: I relogged to make sure it wasn't a client side issue - so the log file below may not contain useful information).

**Expected behavior:**
Put the items in my stockpile

**Actual behavior:**
They went missing

<details>
<summary>Log File</summary>(...previous log truncated...)

 in <0f129097844e485e9930e88ed3c03017>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <0f129097844e485e9930e88ed3c03017>:0 
[33:53] Exception in view notify: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component:get_gameObject (UnityEngine.Component)
  at UnityEngine.Component.GetComponentInParent (System.Type t) [0x00001] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at UnityEngine.Component.GetComponentInParent[T] () [0x00001] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at UI.BaseItemUI.OnChange () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
  at UI.ItemCollectionUI.OnChange () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <0f129097844e485e9930e88ed3c03017>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <0f129097844e485e9930e88ed3c03017>:0 
Can not play a disabled audio source
 
(Filename:  Line: 707)

[34:02] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by MarjieAVolk** [comment] 2018-06-11 20:46
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5895

We've had several reports of this from various people, but as far as I know we've never reproduced it ourselves.  If you have any more information about how to get this to happen, let me know.

**Closed by MarjieAVolk** 2018-06-11 20:46 UTC
Labels: Medium Priority, Respond ASAP
