### ISSUE TITLE
USER ISSUE: world holes

### ISSUE THREAD

**Issue by JarlGiga** [StrangeLoopGames/EcoIssues#4584] opened 2018-02-15 12:45 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
some blocks are world holes, you mine the block on top and the block below is not there or something and you can fall into them

**Expected behavior:**
well not being a world hole

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-20 22:04
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3897

**Closed by MarjieAVolk** 2018-02-20 22:04 UTC
Labels: High Priority
