### ISSUE TITLE
Talent Issue: Lavish Workspace - broken

### ISSUE THREAD

**Issue by grappyX** [StrangeLoopGames/EcoIssues#11649] opened 2019-03-12 19:26 UTC
After selecting the Talent on Level 6 the Tier Requirement will  increase by 0.2 but the cost won't decrease by 10%.
Testet on Skills: 
- Smelting / Advanced Smelting
- Industry
- Mechanics
- Oil drilling
- Electronics

Happens on Eco 0.8.0.6 / 0.8.0.5 and before

**Comment by D3nnis3n** [comment] 2019-03-13 04:06
Duplicate of #11330

**Closed by D3nnis3n** 2019-03-13 04:06 UTC
