### ISSUE TITLE
USER ISSUE: Camo Shirt Bugs

### ISSUE THREAD

**Issue by Sirisma** [StrangeLoopGames/EcoIssues#4738] opened 2018-02-17 22:09 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Equip camo shirt, then use the Edit button to change your appearance. Cycle through shirt options then save.

**Expected behavior:**
Should have changed appearance of Camo Shirt

**Actual behavior:**
Camo shirt does not have a playermodel texture and using EDIT replaces the camo shirt with a henley, deleting the Camo shirt.

**Comment by MarjieAVolk** [comment] 2018-02-23 19:56
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4717

**Closed by MarjieAVolk** 2018-02-23 19:56 UTC
