### ISSUE TITLE
USER ISSUE: Cart underground teleported to surface

### ISSUE THREAD

**Issue by Eavrusm** [StrangeLoopGames/EcoIssues#17740] opened 2020-08-16 12:06 UTC
\
**Version:** 0.9.0.0 beta staging-1722

**Steps to Reproduce:**
I left a cart in the mine below (Was not clipped on anything) and when I came back the next day it teleported to up ontop of my partially build house. 

**Expected behavior:**
Cart to st ay where I left it. 

**Actual behavior:**
Carts underground sometimes teleporting to surface.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by WeaselDog** [comment] 2020-08-16 19:00
Hi @Eavrusm. Thank you for reporting this issue.

We are aware of this bug and our team is working on a fix for it. Sorry you are experiencing this issue, but you can follow the progress with the link below:

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12099

**Closed by WeaselDog** 2020-08-16 19:00 UTC
