### ISSUE TITLE
Black screen when i launch the game

### ISSUE THREAD

**Issue by Errorj404** [StrangeLoopGames/EcoIssues#4834] opened 2018-02-19 20:09 UTC
Hello ! I want play in Eco but when i launch the game i have the Eco cursor and the sound but a black screen .

My config :

    Intel core i5-4300 (576 vRam allowed)
    Intel hd graphics 4600
    4 GB ram
    Windows 10 64 bit

I try :

  - Update my drivers
  - Allow more vRam
  - Execute as Administrator
  - Windows 7,8 compatibility mod
  - ALT + Enter
  - Disable my Antivirus
  - Launch the game with Dx11
  

But still this problem

CRASH REPORT :   https://pastebin.com/7P8nVSGv

Thanks.

**Comment by MarjieAVolk** [comment] 2018-02-20 19:37
@SeanAtr0n assigning to you because I thought this was usually something to do with shaders?  Although that might have been a mac only thing, so maybe this is something else...

**Comment by fuegas** [comment] 2018-03-06 22:05
Hi, I'm experiencing a black screen when I launch the game as well. 

I installed the game and played it for a little while and then Windows decided it needed to update. Afterwards I was no longer able to start the game without a black screen. I do see the game cursor and hear birds chirp as background sound. 

From the error log I read this:
```
Initialize engine version: 2017.3.0f3 (a9f86dcd79df)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 660 (ID=0x11c0)
    Vendor:   NVIDIA
    VRAM:     1998 MB
    Driver:   23.21.13.9101
Begin MonoManager ReloadAssembly
- Completed reload, in  0.070 seconds
<RI> Initializing input.

<RI> Input initialized.

IndexOutOfRangeException: Array index is out of range.
  at UnityEngine.Display.RecreateDisplayList (System.IntPtr[] nativeDisplay) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 2 worker threads for Enlighten.
  Thread -> id: 2b70 -> priority: 1 
  Thread -> id: 13f0 -> priority: 1 
UnloadTime: 3.103733 ms
RPC lookup took: 3603.1244ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```

Things I've tried to fix it, but did not help:
- Re-install game (from Steam)
- Edit the registry to start fullscreen or windowed
- Edit the registry to use a smaller resolution (fullscreen and windowed)
- Decrease UnityGraphicsQuality
- Change UnitySelectMonitor to a different value (wild guess due to `IndexOutOfRangeException` and `at UnityEngine.Display.RecreateDisplayList`)
- Update graphics card driver
- Rebooted PC multiple times
- Tried different versions of the game (NONE, Latest Staging, 7.1.2, 7.0.XX)
- Disable Firewall

So I'm out of options what to try to get the game working. Do you have any suggestion or a better hint at what goes wrong? Might mono / unity be corrupted due to the update of Windows? I could not trigger a new "first run installation" in Steam, so I can't verify it has something to do with that.

**Comment by SeanAtr0n** [comment] 2018-03-06 22:13
Maybe this will work?
> I went into Nvidia Control Panel. This is where I changed "Aspect ratio" to "No scaling" on the Adjust desktop size and position page (with "perform scaling on Display"). Suddenly everything was okay again. In DS3 I had options for resolutions. If I started up a Unity game with shift, the Select Monitor was no longer empty, but said "Display 1".

https://steamcommunity.com/discussions/forum/1/1480982971174752598/

**Comment by fuegas** [comment] 2018-03-06 22:19
@SeanAtr0n thank you very much for that link, changing the aspect ratio to `No scaling` indeed fixed it! Many thanks 💯

**Comment by alecpura** [comment] 2018-03-10 07:22
Just gonna say I'm seeing a fair amount of this issue in the support queue now. Some of them are using IntelHD and I'm not sure if there's an equivalent control panel for the kind of fix that SeanAtr0n posted.

**Comment by greatmutato** [comment] 2018-03-10 09:32
There is a control panel in intel HD indeed but as far as i can see the workaround doesn't work with the intel scaling system.
All of these people who can't launch the game seems to be able to load it in 7.1.2 - maybe you could ask those people in what quality cause in my case in 7.1.2 it's a little bit laggy, i can't push the quality settings if so the game becomes unplayable.
At first glance it seems all of these issue can be related to the people who are experiencing crash when choosing the server (cpu's temperature goes up when on the server page). The systeme requierement may have been set too high because it looks like the crash occurs mostly on laptops with integreted Intel chipset.

I may be wrong, i just try to gather all the informations i've seen on the issue :)

**Comment by Daniel93a** [comment] 2018-03-10 11:48
Also getting this issue in 7.2.X, game working normally in 7.1.X
Specs: i5-4200u
Intel HD Graphics 4400

main menu stays black in 7.2.X but ingame cursor is visible
tried changing the scaling settings via windows and intel hd settings but no effect

**Comment by EarthBoundMic** [comment] 2018-03-10 23:11
If it helps I've been playing on a surface pro 3 using windows 10...unable to adjust aspect ratio scaling on it.  Perhaps a suggestion to test for installing software that can?

**Comment by MarjieAVolk** [comment] 2018-03-12 17:51
From another report:
"https://github.com/StrangeLoopGames/EcoIssues/files/1799806/output_log.txt

User has:
1:20 PM] ☐✘[D3V]✘ ☐: intel core I5-4430 CPU 3GHZ 8gb RAM
[1:20 PM] ☐✘[D3V]✘ ☐: gtx 960"

**Comment by alecpura** [comment] 2018-03-12 20:15
Posting this from a ticket from floridoo81@googlemail.com: 

everytime I want to start Eco, my screen went black and nothing happens. I just hear the game, but I can't see the title screen. I made a copy of my unity client logs and the DxDiagnostig-File for you, so I look forward for help :)

My PC specs are:
Windows 8.1
Intel(R) Core(TM) i7-4770 CPU @ 3,40GHz
16,0 GB (RAM)
64-Bit-Betriessystem

AMD Radeon R9 200 Series

And here's his output.txt: https://pastebin.com/AyxfsRsQ

**Comment by alecpura** [comment] 2018-03-12 20:51
Another one from mousedsa1@yahoo.com:

device specifications :

dell inspiriron 15 3000 series
intel(r) core(tm) i3-5005U cpu@2.00GHz 2.00 GHz
ram: 8.00 GB
64-bit operating system, x64-based processor
touch support with 10 touch points

after your update ..i tried to log on first the birds chirp and the cursor changes then a black screen appears and nothing else shows up ...ive uninstalled it ...restarted my computer then ..installed it again ...same thing ...birds chirp ...cursor changes ...black screen ...then when i click black screen some times a small blue box in the right corner appears that sayes eco...and the rest of screen black ....please help...

**Comment by dc-50168** [comment] 2018-03-12 23:50
Hey guys, I just wanted to let you know that I found the aspect ratio solution to be working for me pretty good as well.

My Setup:
Lenovo ThinkPad P50
Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
RAM: 16GB
Intel(R) HD Graphics 530 (GPU 0)
NVIDIA Quadro M1000M (GPU1)
Windows 10 (64bit)

The solution I mean is from above:
_I went into Nvidia Control Panel. This is where I changed "Aspect ratio" to "No scaling" on the Adjust desktop size and position page (with "perform scaling on Display")._

With my setup it was also connected with the following:
https://forums.geforce.com/default/topic/547415/nvidia-control-panel-missing-options/

...which was caused by my laptop having 2 GPUs. I had to deactivate the "hybrid graphics mode" in the BIOS to "discrete mode", so my laptop would exclusively work with my nvidia quadro M1000M. After I did that I could finally deactivate the "Aspect Ratio" setting.

And voila, it finally works!

Maybe this proves to be helpfull for others as well or to actually eliminate the cause of this problem.

**Comment by alecpura** [comment] 2018-03-13 00:13
So I believe what that's doing is just swapping you over to the NVidia card, which "fixes" the problem by avoiding it entirely since the bug only seems to be affecting those with IntelHD graphics. It's a fix in the sense that it's causing you to use the card you should've been using in the first place.

**Comment by alecpura** [comment] 2018-03-13 00:16
Another, from jannik160396@gmail.com:

Initialize engine version: 2017.3.0f3 (a9f86dcd79df)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 650 Ti (ID=0x11c6)
    Vendor:   NVIDIA
    VRAM:     2007 MB
    Driver:   23.21.13.9077
Begin MonoManager ReloadAssembly
- Completed reload, in  0.095 seconds
<RI> Initializing input.

<RI> Input initialized.

IndexOutOfRangeException: Array index is out of range.
  at UnityEngine.Display.RecreateDisplayList (System.IntPtr[] nativeDisplay) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 2 worker threads for Enlighten.
  Thread -> id: 2e90 -> priority: 1 
  Thread -> id: 984 -> priority: 1 
UnloadTime: 3.858061 ms
RPC lookup took: 4702.575ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Releasing render texture that is set as Camera.targetTexture!
 
(Filename:  Line: 3926)

Releasing render texture that is set as Camera.targetTexture!
 
(Filename:  Line: 3926)

**Comment by alecpura** [comment] 2018-03-13 00:40
And another from eva.rousset.15@gmail.com.

First 150 lines of the error.log: https://pastebin.com/kE8Fx4ps

**Comment by MelonMan2002** [comment] 2018-03-13 03:36
Hey! I got Eco about 7-8 hours ago, but I went to watch Black Panther and had to leave the issue unsolved. I am also having this issue with Eco, and I can't find a single solution anywhere for it. I don't really know how to go into specifics of my computer but I do know it is a laptop with an Intel graphics card integrated inside. If anybody finds a solution that doesn't involve the NVIDIA thing as I don't have that please tell!

**Comment by GophTheGreat** [comment] 2018-03-13 03:51
One more from justin01@ackermann-saar.com:

I downloaded the game from steam, it's the newest version. I double checked my Antivirus logs, nothing blocked. I even tried uninstalling the AV software, deleting the /LocalLow/Strangeloopgames/Eco folder, reinstalling it afterwards etc. 
My graphic chip driver is also on the newest version...
Can you help me with this? :(

My specs:
intel core i5, Quad Core 2.2Ghz
Intel HD Graphics 5500
8GB Ram

Could the problem be my Intel HD Graphics? because I have seen some guys in the forum and the steam forum running in the same problem also with Intel HD Graphics. 

Best regards,
Justin

**Comment by EarthBoundMic** [comment] 2018-03-13 04:27
It seems like the issue pertains to Intel HD chips in general.  If you only have that as your graphics engine than unfortunately there's nothing you can do apart from attempting to discover a workaround yourself.  The only reason why the nvidia solution works is because it bypasses the intel graphics chip.  Just need to be patient as the devs are working on it.

**Comment by dc-50168** [comment] 2018-03-13 06:10
@GophTheGreat The thing is that my laptop was totally capable of choosing a GPU for processes. It all seems to point in the Intel GPU direction in this thread, but I think that there is also a NVIDIA bug on the go with the aspect ratio setting.

although I must admit that nothing changed when I "chose" the intel graphics to be running the game, same exact effect like with the NVIDIA GPU.

**Comment by GophTheGreat** [comment] 2018-03-14 21:23
Uh oh, got another one that says the bug is still there after 7.2.4:

I downloaded your current version of the game and am still having the same issue with the black screen. I was looking at forums and it may be due to my current graphics card? Many other people seem to be having problems with the similar graphics card I have running right now. 
Attached are my current specs. Is it something to do with my Intel card? 

![screen_shot_2018-03-14_at_5 13 33_pm](https://user-images.githubusercontent.com/13459026/37431585-c09d1fc0-2779-11e8-8762-2fc4951013ee.png)

**Comment by GophTheGreat** [comment] 2018-03-15 23:07
+3, all seem to be using OSX High Sierra:

"I am using macOS Sierra.

I’ve tested the latest release Beta 7.2.4 and it still is „not responding“ after displaying the black screen with a little bit blurred forrest in the background. It’s exactly the issue described here http://ecoforum.strangeloopgames.com/topic/3579/game-not-start-on-mac and here http://ecoforum.strangeloopgames.com/topic/3494/macos-high-sierra-support/2"

**Comment by GophTheGreat** [comment] 2018-03-20 21:14
+1 again, same stuff: 
<img width="491" alt="bildschirmfoto_2018-03-20_um_13 37 29 1" src="https://user-images.githubusercontent.com/13459026/37683118-9d3111b2-2c2f-11e8-9bf6-79980b173e74.png">

**Comment by SeanAtr0n** [comment] 2018-03-28 22:27
Lets try to keep these separate at least based on operating system... tons of things can cause blackscreens

**Comment by MarjieAVolk** [comment] 2018-03-28 23:51
Yeah, original one was for windows, I was assuming the other one I closed as a duplicate was related to the OP

**Comment by Daniel93a** [comment] 2018-03-29 15:53
my black screen issue got resolved with the 7.2.4 patch if that helps in distinguishing between the different issues

**Comment by ShaydenMac** [comment] 2018-03-30 20:09
http://steamcommunity.com/profiles/76561198360886362/recommended/382310/

**Comment by SeanAtr0n** [comment] 2018-05-14 23:01
Most of the issues here should be resolved... Please open a new issue if you still have problems

**Closed by SeanAtr0n** 2018-05-14 23:01 UTC
Labels: High Priority, Steam Report
