### ISSUE TITLE
Second step of Controls tutorial is not working; "use the keys 'w', 's', 'a', 'd' to move around the world" 

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19086] opened 2020-11-04 00:29 UTC
Second step of Controls tutorial is not working; "use the keys 'w', 's', 'a', 'd' to move around the world"

**Comment by IcedForge** [comment] 2020-11-04 03:29
@dmplatten thank you for reporting this. Have you performed the previous objective? (Press tab to toggle mouse cursor)
If you move around more does this still not complete ?

**Comment by dmplatten** [comment] 2020-11-04 03:44
You're welcome. For the movement tutorial there are 3 objectives and i was able to do the 1st one and the 3rd one but not the second.
No, it didn't complete and i was moving around for 5 minutes doing different combinations of the w a s d keys.

**Comment by SlayksWood** [comment] 2020-11-04 07:44
@dmplatten 
Can you provide a little more informetion.
1. Log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Please provide your PC specification (include Operating System).
3. Did you meet this issue after updating to the 0.9.1 or you had it before in 0.9.0.5?

**Comment by dmplatten** [comment] 2020-11-04 23:34
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5490963/Player.log)
HP Omen running Windows 10 
i haven't checked this in a long time but i'm pretty sure it worked before.

**Comment by dmplatten** [comment] 2020-11-06 14:22
This also isn’t working for me on my own server without mods.

**Comment by Daniel-Magulado** [comment] 2021-06-03 13:19
Hi @dmplatten,

We just wanted to check in if you're still experiencing this issue.

Thank you,

**Comment by dmplatten** [comment] 2021-06-03 13:38
Hi Daniel,
I havent tried this in a long time.
thanks,
Dave

Sent from my iPhone

On Jun 3, 2021, at 9:19 AM, Daniel Moises Dizon Magulado ***@***.******@***.***>> wrote:


Hi @dmplatten<https://github.com/dmplatten>,

We just wanted to check in if you're still experiencing this issue.

Thank you,

**Comment by Daniel-Magulado** [comment] 2021-06-03 15:59
Hi @dmplatten,

Thank you for writing back. We deeply apologize if it took us a while to get back to you as we investigate this issue. We also apologize for any inconvenience that this might have caused.
Unfortunately, we will be closing this ticket for now as we could not reproduce this issue using the latest and upcoming Eco builds.
However, please feel free to reopen this ticket if you encounter it again with the latest version of Eco.

Thank you.

**Closed by Daniel-Magulado** 2021-06-03 15:59 UTC
Labels: Status: Investigate

**Comment by dmplatten** [comment] 2021-06-03 16:20
Thank you Daniel, I appreciate that. It didn’t cause much harm, I mainly wrote this bug and all the others as my contribution to helping you guys make a better product. I’m a software tester by trade and enjoyed finding these bugs to help you out. It was a thrill for me to “work together” with real game developers! Normally I just test boring business applications :).

Thanks
Dave

Sent from my iPad

On Jun 3, 2021, at 11:59 AM, Daniel Moises Dizon Magulado ***@***.***> wrote:

﻿

Hi @dmplatten<https://github.com/dmplatten>,

Thank you for writing back. We deeply apologize if it took us a while to get back to you as we investigate this issue. We also apologize for any inconvenience that this might have caused.
Unfortunately, we will be closing this ticket for now as we could not reproduce this issue using the latest and upcoming Eco builds.
However, please feel free to reopen this ticket if you encounter it again with the latest version of Eco.

Thank you.
