### ISSUE TITLE
USER ISSUE: Trees on stockpile of dirt

### ISSUE THREAD

**Issue by kloxi** [StrangeLoopGames/EcoIssues#8134] opened 2018-06-22 15:00 UTC
**Version:** 0.7.4.7 beta

**Steps to Reproduce:**
Fill a stockpile and let grass grow over it. When a tree was harvested in the surrounding area a new one can be grow on the dirt from the stockpile.	Solution: Trees can't grow on stockpiles.

**Expected behavior:**
Shouldn't be possible, because you can still remove the dirt and you have a hovering tree with the roots.

**Actual behavior:**
The tree can grow on there and it is not a problem to remove the dirt below it.

**Comment by elfl0rd** [comment] 2018-06-22 15:09
Duplicate -> https://github.com/StrangeLoopGames/EcoIssues/issues/7611

**Comment by BlazeGuy2** [comment] 2018-06-22 16:46
Closing as a duplicate of #7611.

**Closed by BlazeGuy2** 2018-06-22 16:46 UTC

**Comment by kloxi** [comment] 2018-06-22 19:40
Sry, I didn't knew that it was already reported. I just used the report function ingame without checking the other bug reports. But thanks for your fast response!

**Comment by elfl0rd** [comment] 2018-06-22 19:44
no problem, thx for your help! :)
