### ISSUE TITLE
Steel Plate recipe issue

### ISSUE THREAD

**Issue by smerecz** [StrangeLoopGames/EcoIssues#8659] opened 2018-07-20 18:19 UTC
the Electric stamping press no longer recognizes steel to make steel plate

**Comment by rookhaven** [comment] 2018-07-20 22:01
I'm on 0.7.6.2 Beta through Steam.

I'm having a an issue on the Electric Stamping Press where the storage tab doesn't show up which might be related to the original post here.  When I checked the code, line 36 of ElectricStampingPress.cs was missing the LinkComponent which needed to be added (like it is in the electric lathe).  That made the storage tab show up for me.

    [RequireComponent(typeof(LinkComponent))]                   

Now, I might have broken that myself so if you devs see it in your base, you can ignore this reply.

**Comment by rookhaven** [comment] 2018-07-21 01:46
Looks like the Electric Planer has the same issue.

**Comment by craig-jong** [comment] 2018-07-24 17:32
dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/8547

**Closed by craig-jong** 2018-07-24 17:32 UTC
Labels: High Priority, Needs Triage
