### ISSUE TITLE
USER ISSUE: add tooltip about modifiers (e.g. how to % work) in laws

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8360] opened 2018-07-06 00:00 UTC
**Version:** 0.7.6.0 beta staging-f5159538
Calculating value with % calculated incorrectrly
![20180705171649_1](https://user-images.githubusercontent.com/4980243/42353394-be04cfd0-80c8-11e8-8204-f9ee93e99cc4.jpg)
![20180706025657_1](https://user-images.githubusercontent.com/4980243/42353395-be268f76-80c8-11e8-9064-601d05ad9d6a.jpg)
![20180706025819_1](https://user-images.githubusercontent.com/4980243/42353398-be52d888-80c8-11e8-9bc1-fbd928e8e2a0.jpg)

**Comment by MarjieAVolk** [comment] 2018-07-06 00:12
As discussed on discord, I believe this is working correctly, but the issue is that the behavior of '%' when used as mod is not well known outside programming.  I decided to include mod because it might be useful for things like checking the time of day; though I doubt it sees much use.  I could just remove it if people are finding it confusing.  I could also try to change the text, eg. say 'remainder' instead of '%' or something similar.  I'm not sure if this would be clear.

**Comment by elfl0rd** [comment] 2018-07-06 00:15
Or add a litle help about modifiers work...

**Comment by Deantwo** [comment] 2018-08-24 21:52
This should be a very easy fix, if you just rename the option to `Modulus`.

With the new currency law additions, there will be a lot more people making tax laws, and a lot of them will be trying to use this to make percentage calculations. So fixing this would help a lot with reducing the impending confusion.

**Comment by Deantwo** [comment] 2018-11-07 21:00
Duplicate of #9510
Which has higher priority, so just close this one.

**Closed** 2018-11-12 20:10 UTC
Labels: Laws, Low Priority
