### ISSUE TITLE
[8.0.0] Scrolling or changing the content of the chat window results in icons flashing on the screen

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10283] opened 2018-12-12 05:06 UTC
https://drive.google.com/file/d/1hEwlIsGTY82hpZMGFWAqXC-UQ7VN9UDH/view?usp=sharing

**Comment by elfl0rd** [comment] 2018-12-13 11:38
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/8290

**Comment by beastyn** [comment] 2019-04-17 18:12
copy of #8290
actual in 0.8.1.3

**Comment by Spydarlee** [comment] 2019-07-11 13:40
Can't reproduce this anymore - seems to have been fixed in one of the recent-ish chat UI overhauls.

**Closed by Spydarlee** 2019-07-11 13:40 UTC
Labels: Medium Priority, Not reproduced, QA
