### ISSUE TITLE
Make intra-version migrations work

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13753] opened 2019-11-17 17:20 UTC
Migrations between internal versions shouldnt crash the server.   We can make migration more robust, if something fails it can log it instead of halting.

**Comment by mirasrael** [comment] 2019-11-18 09:00
@johnkslg I don't see how it may be fixed in generic way. It may work in one cases, but fail with very strange and unclear errors in other cases. In example, for referenced issue:
```
System.InvalidCastException: Unable to cast object of type 'Eco.Gameplay.Civics.GameValues.GameValueContext1[Eco.Gameplay.Players.User]' to type 'Eco.Gameplay.Civics.GameValues.GameValue1[Eco.Gameplay.Aliases.IAlias]'.
```
It says it can't convert from GameValue<User> to GameValue<IAlias>. Assume we will just skip this value and put warning in console. Then we will just not initialize the member with user, so it will have `null` value. 
Because it is running in hosted world nobody will see this warning and even so in most cases will just ignore it.
Then at any moment, not necessarily on startup, you will have NullReferenceException when try to perform some action. And you will absolutely no idea why it was crashed. You realize it has null value, but not realize why. Because of wrong logic? Because of thread-concurrency? Because of migration?
We will have an issue in tracker with NullReferenceException, will spend time to investigate it, finish with adding null checks everywhere, but may not realize it was just because of the migration.

**Comment by redwyre** [comment] 2019-11-18 14:48
You could delete the entire law if needed, better than the entire save being useless.

**Comment by johnkslg** [comment] 2019-11-18 21:02
Yes what Simon says is what I was thinking. If something fails to migrate any sub-part, the entire datastore containing it is invalidated.  Or, some sub-level like the entire registrar entry (law, election, etc).

Then we can just ensure proper handling of datastore objects being 'null' on load. This will greatly reduce the set of possible failing things.   Most of the logic for laws for example will detect null references and tag them as invalid.

It's also not quite a case of failing-fast, if we implement intra-migration-fail-handling then we can avoid intra-migration code, which will be much more plentiful and problematic.  And we essentially have to do one or the other in order to be able to properly playtest and keep QA moving rapidly.

Plus, with migration-fail logs, we can then tell what are likely issues if any arise. 

I can help with the handling of null references in the civics system, if a law fails to migrate and is set too null for example.  We can add some test cases for this too once we have the intra-migration safety in.

**Comment by mirasrael** [comment] 2019-11-19 06:20
@johnkslg @redwyre What should happen if User fails to load and another entity (with reference system) expect this user to be set? It will have `null` reference for User in this case anyway (because it expects User to be initialized by reference in post stage).
So it is OK if we will add some *special* handling i.e. for Laws if we know that Laws won't be referenced from other entities. But in *generic* way I don't see how it may be done safely.
About migration fail logs. As I explain it may not be always clear what is root cause of problem. You hay have hundreds of messages in migration log and have no guarantee any of that related to exact fail.
Also we currently doesn't have good logging system for Hosted Worlds. All logs wipes after every server restart. So unless we will be very fast we won't get anything useful from logs.

**Comment by mirasrael** [comment] 2019-11-19 09:45
I added skip for objects failed to load (and reporting), but I still think it may cause more issues than fix.

**Comment by D3nnis3n** [comment] 2019-11-19 14:54
@mirasrael Please note that the linked issue is not from hosted worlds, but the official servers. For me, this behaviour is enough, if QA wants to use that on hosted worlds, i have no idea.

**Closed** 2019-11-21 04:40 UTC
Labels: Fixed, High Priority, Needs Information
