### ISSUE TITLE
Interface ENHANCEMENT

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#2688] opened 2017-11-01 06:38 UTC
•	Add a targeting crosshair so you know what you're pointing at - with the wrong tool selected you never know - with any sort of server lag you have to wait a few seconds to know if you're aiming at the right block or not

**Comment by MarjieAVolk** [comment] 2017-11-01 19:01
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2399

**Closed by MarjieAVolk** 2017-11-01 19:01 UTC
