### ISSUE TITLE
USER ISSUE: joining game error

### ISSUE THREAD

**Issue by celtbane** [StrangeLoopGames/EcoIssues#4194] opened 2018-02-09 21:08 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
attempting to join a game

**Expected behavior:**
joined game

**Actual behavior:**
The following error message popped up:
``` Caught exception: Object reference not set to an instance of an object
<size=150%>Connection Failed</size>

Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment] 2018-02-13 04:15
Closing as duplicate of #4144 . You can continue tracking the issue there.

**Closed by MarjieAVolk** 2018-02-13 04:15 UTC
