### ISSUE TITLE
USER ISSUE: Resolution Setting is ignored

### ISSUE THREAD

**Issue by CCJordan** [StrangeLoopGames/EcoIssues#12067] opened 2019-04-19 22:48 UTC
**Version:** 0.8.1.3 beta

**Steps to Reproduce:**
I set the resolution form 4k to Full HD, click apply and confirm, leave the menu and reopen it.

**Expected behavior:**
Set the resolution to 1920x1080.

**Actual behavior:**
The resolution stays where it was and my frame rate remains low.

**Do you have mods installed? Does issue happen when no mods are installed?:**
The resolution stays where it was and my frame rate remains low.

**Comment by D3nnis3n** [comment] 2019-04-23 04:14
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11909

**Comment by D3nnis3n** [comment] 2019-04-23 04:15
Raising priority to high.

**Comment by D3nnis3n** [comment] 2019-05-01 03:47
Reopen. In exclusive fullscreen changing the resolution does not change the resolution.

**Comment by SlayksWood** [comment] 2019-05-07 06:36
Small bugs(or not) left. I just want to clarify some points. Perhaps It's the intended behavior.
1. In windowed mode
![image](https://user-images.githubusercontent.com/45708377/57275534-8e413c00-70a7-11e9-855b-ba9d058f471d.png)
- Set any resolution excellent basic resolution
![image](https://user-images.githubusercontent.com/45708377/57275583-aa44dd80-70a7-11e9-868e-2fdf82bb6b84.png)
- Close menu and reopen it, resolution will be refreshed to basic resolution.(will be 800x600)
![image](https://user-images.githubusercontent.com/45708377/57275681-ea0bc500-70a7-11e9-88f4-e504d02c3b89.png)
If you manually change the window size, then when you open the menu, the resolution will be set to basic. In many games, if the resolution is different from the standard, then nothing is displayed there.
![image](https://user-images.githubusercontent.com/45708377/57275950-b41b1080-70a8-11e9-9aae-a2fad1a11d41.png)

2. I have the monitor 16:10. My basic resolution 1680x1050, but it supports 1920x1080. For this reason, I have the opportunity to set the resolution of 1920x1080 in ECO. I can set it in Exclusive fullscreen and Windowed mode, but I can't set it in Borderless fullscreen. I undestand why it happens. But must be some notification that I can't set this resolution or I must not see this resolution in Borderless fullscreen. Now it's refreshing to my basic resolution 1680x1050.

3. In Borderless fullscreen: there are black stripes in the edges of the monitor if the side ratio is different from the standard.
In Exclusive fullscreen: the game is flattened or pulled out.
![image](https://user-images.githubusercontent.com/45708377/57276390-1e808080-70aa-11e9-9331-9fb9cddbc151.png)
![image](https://user-images.githubusercontent.com/45708377/57276481-728b6500-70aa-11e9-87cf-d5e1a7039f87.png)

If It's the intended behavior, close issue

**Comment by SeanAtr0n** [comment] 2019-05-07 17:30
The original bug here was fixed, I agree we should look into the remaining unpolished aspects eventually but that should be in a new issue.

@SlayksWood could you copy your findings to a new bug?

**Closed by SeanAtr0n** 2019-05-07 17:30 UTC
Labels: Medium Priority, QA

**Comment by SlayksWood** [comment] 2019-05-07 18:06
open in #12212

**Comment by CCJordan** [comment] 2019-05-08 18:09
Its not the intended behavior. 
I want to reduce my game resolution, because I the FPS drops to 10 when I play in 4K, that’s why I want to play the game in HD and this is currently only possible when I change the resolution in my operating system. 
The windowed mode is not an option. 

Thomas, Papst VI.
Ritter der Whiteboardrunde
Hüter des Schlüssels des Schlosses der Herzen
Hohepriester der Burg Kabale
Fünf Sterne General im Hause der Eris

**Comment by redwyre** [comment] 2019-05-08 18:16
@CCJordan borderless uses the current screen resolution, if you want to change the resolution you need to use fullscreen.

Alternatively, you can turn the "Render scale" down to 50% as this changes the rendered resolution, so that should be rendering around 1080p
