### ISSUE TITLE
Producer/Stockpile linking problem

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7195] opened 2018-04-14 19:14 UTC
So I have a shared workarea with pump jacks and a factory and a stockpile.

The petroleum project was started by a friend, but I inadvertantly removed the stockpile.

Because he has not relinked it the project is halted.

This is a bad workflow. It should not matter who links a project to its sources.

**Comment by MarjieAVolk** [comment] 2018-05-08 00:32
You are right that this is annoying when working cooperatively, but it is necessary when using crafting tables belonging to someone you don't necessarily trust, at least for the output.  Right now output and input settings are the same; if they were separate, then we could have much more convenient default settings - which is what we are planning to do eventually.  This would allow the project to accept the input and continue crafting, but your friend might need to come back on in order to collect the project or select where it is allowed to be output (you can see why this would be necessary on a stranger's property, so they can't just put down a new chest in order to steal everyone's items).  So closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2190, which should improve this experience.

**Closed by MarjieAVolk** 2018-05-08 00:32 UTC
Labels: Medium Priority
