### ISSUE TITLE
USER ISSUE: Chat interacting weird with shortcuts

### ISSUE THREAD

**Issue by LemonMoo** [StrangeLoopGames/EcoIssues#4675] opened 2018-02-17 03:53 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
If you are typing something like the word /Why\ and you hit enter too fast, the game thinks that you clicked the Y button and so it takes a long time to load up the economy viewer because that is the shortcut for it. 

**Expected behavior:**
Just sent the chat message without trying to open up the Economy Viewer

**Actual behavior:**
The following error message popped up:
``` ---- no error message, but very annoying
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-02-23 23:08
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3522

**Closed by MarjieAVolk** 2018-02-23 23:08 UTC
