### ISSUE TITLE
Laws Issue: Change Property Owner

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13737] opened 2019-11-15 20:34 UTC
![law2](https://user-images.githubusercontent.com/25908592/68973789-76cdd300-07ef-11ea-8977-1d79c9029c7e.png)

On the right side i tried to choose "Citizen (that completed contract" for "Currently Owned by Citizen". This is resembled in the left top area in the text, but it does not get entered into the viewable selected dropdown, it still displays "None".

Trying to change "New Owner" brings up a search, but no matter what i type in, no search results are presented and therefore no player or demographics or other possible owner can be chosen.

**Comment by WeaselDog** [comment] 2019-11-17 19:30
This law is not fixed yet. It is related to https://github.com/StrangeLoopGames/EcoIssues/issues/13749

I tested with this law: 
![PropertyTransferLaw](https://user-images.githubusercontent.com/47330823/69012696-763b5680-092d-11ea-9bb0-492b1cfca47c.png)

This is what it looks like in amendment view:
![PropertyTransferAmmendment](https://user-images.githubusercontent.com/47330823/69012702-818e8200-092d-11ea-97db-d9ef37237589.png)

In law view it has two template icons:
![LawView](https://user-images.githubusercontent.com/47330823/69012703-894e2680-092d-11ea-86f5-ebfbc20e6ec2.png)

Testing with this contract does not trigger the law:
![TestContract](https://user-images.githubusercontent.com/47330823/69012706-9ff47d80-092d-11ea-8863-171793579bd6.png)

**Comment by D3nnis3n** [comment] 2019-11-18 08:38
@WeaselDog Can you test with the new build tomorrow?

**Comment by WeaselDog** [comment] 2019-11-18 18:45
Still not fixed, probably for reason above. The conditions still show up as missing in amendment view.

**Comment by johnkslg** [comment] 2019-11-19 23:00
I believe this will be fixed with the other bug, can you check?

**Comment by WeaselDog** [comment] 2019-11-20 16:53
This specific issue is fixed but it exposes a new issue.  When a contract has a condition using a specific currency nothing happens. When the currency is set to "Any" the law is fixed and works as intended.

**Closed** 2019-11-21 07:25 UTC
Labels: Fixed, High Priority

**Comment by D3nnis3n** [comment] 2019-11-21 08:06
Is the other issue reported?

**Comment by beastyn** [comment] 2019-11-21 08:20
yeap
13823
