### ISSUE TITLE
USER ISSUE: Farmer's stand is not visible

### ISSUE THREAD

**Issue by kingwithou** [StrangeLoopGames/EcoIssues#4468] opened 2018-02-13 20:40 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Take the Farmer's stand in hand and place it somewhere

**Expected behavior:**
I should see the Farmer's stand

**Actual behavior:**
it is transparent when I try to place it, and once it's placed it is still transparent

**Comment by kingwithou** [comment] 2018-02-13 20:50
I asked someone on the server to check and he couldn't see it either. But we can climb on it and we see the red or green authorization border

**Comment by ecoemmeck** [comment] 2018-02-13 20:54
I'm pretty sure the farmers stand is part of clays toolkit. The issue is known and being worked on

**Comment by MarjieAVolk** [comment] 2018-02-13 20:57
Ah thought you meant the farmer's table.  Since it's a mod item, then closing.

**Closed by MarjieAVolk** 2018-02-13 20:57 UTC
Labels: High Priority
