### ISSUE TITLE
USER ISSUE: Player Skills Missing Points

### ISSUE THREAD

**Issue by EverisPeace** [StrangeLoopGames/EcoIssues#24927] opened 2024-05-09 14:24 UTC
![Basic Engineering 7 research Table](https://github.com/StrangeLoopGames/EcoIssues/assets/169372020/a68e2315-7306-455d-86c8-b95f444822f8)
![Basic Engineering points 1](https://github.com/StrangeLoopGames/EcoIssues/assets/169372020/d7e25cc6-0700-46b0-9f5b-3624d899b949)
![Basic Engineering points](https://github.com/StrangeLoopGames/EcoIssues/assets/169372020/c2ca5c71-c823-4409-b142-6b2af87fca5e)
![engineering research table](https://github.com/StrangeLoopGames/EcoIssues/assets/169372020/b6263249-8996-4247-8c1a-75e644ea77b7)
![Mechanic Skill Book Project with no points](https://github.com/StrangeLoopGames/EcoIssues/assets/169372020/fc326ecb-e73e-4d4e-9f6b-d5dd6a8fd86b)
![mechanic skill missing engineer points research table](https://github.com/StrangeLoopGames/EcoIssues/assets/169372020/b0c6cb54-cbf1-47df-b0e8-4f0f4f7c5dd1)
\
**User Id: (slg237081)**
**Version:** 0.10.2.2 beta release-660

**Steps to Reproduce:**
Not sure how to reproduce... Says my toon is completed in basic enegeneer.
Sorry I have learning diisabilities and bad shakes so my spelling might bebad.

I was trying to get mechanic skills but couldnt eveb thought it shows that i am level 7, completed, but sauyd i have no experience points.. why 9i. I can also not get glass either due to this

**Expected behavior:**
be able to get the other two skills

**Actual behavior:**
not able to get tghh skills

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods. what should i do?
Thank you

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by EverisPeace** [comment] 2024-05-09 16:28
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15264887/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15264891/Player-prev.log)
Here are my filees,
Thank you
PS LOVE The Game!!

**Comment by EverisPeace** [comment] 2024-05-09 16:31
Also, some info about me, I have some disabilities, am a retired insomniac, so i play games,a lot and at times need different ways explained to me.. head injury, and covid induced coma left me with very low mobiility, so this game os greeat, dont need super fast reflexes 🗡️ Thank you

**Comment by D3nnis3n** [comment] 2024-05-09 17:49
I'm having a hard time following what the problem here is. The only thing I see that there is likely some config setting set to some insane values that creates way too many stars. But I'm not exactly sure what you are trying to do. We'll need a clear description on what is not working.

**Comment by IcedForge** [comment] 2024-05-09 18:36
The work project is paused because no labor has been added, and the required labor is Basic Engineering 1 (which from the screenshots you have but it will generally state what the requirement is) but it only prompts that in the tooltip you need to click the button to add the labor itself.

Do you get an error when trying to click work?
Can you click the work button or does it not let you interact with it?

**Comment by EverisPeace** [comment] 2024-05-09 22:55
Hi 
All the others update, but the others didn't
when i made the world someone asked if i could try adding it so we got bonus points, which is an option.
ohh and one of the workstations doest show a work button for me , i think its the sewing one.

For the issue again, I am trying to get Mechanic, but it is saying i dont have the engineer points, level 7 basic engineer, with 0 points.. how is that possible?
i am just logging into the game will see about trying to get another screenshot

**Comment by D3nnis3n** [comment] 2024-05-09 22:56
It's not saying you have 0 points ... you need to click the work button to add Basic Engineer labour.

**Comment by EverisPeace** [comment] 2024-05-09 23:02
When I am trying to learn Mechanics?

**Comment by EverisPeace** [comment] 2024-05-09 23:09
Ok so when I try to learn the Mechanics Skill Book it says Missing 6000 in Basic Engineering, ask someone else to Create it, and my name is listed as a person to make it. But I cannot make it.

**Comment by EverisPeace** [comment] 2024-05-09 23:10
Do I just need to build more things in Engineering to bring it up?

**Comment by EverisPeace** [comment] 2024-05-09 23:13
Sorry, I clicked work just to see what would happen, and it started and i just had to add food energy, odd non of the other times did that happen.
Sorry for bothering you about this.

**Comment by D3nnis3n** [comment] 2024-05-09 23:38
Glad you figured it out, closing due to not a bug.

**Closed by D3nnis3n** 2024-05-09 23:38 UTC
Labels: Status: Needs Information
