### ISSUE TITLE
Plant alredy exist here (farming issue/bug)

### ISSUE THREAD

**Issue by Swatmo** [StrangeLoopGames/EcoIssues#6997] opened 2018-04-05 15:16 UTC
i plant my seeds and sometimes some of my crops die and i use the shovel to remove the dead plant and refill the hole. when im going to resow on that specific block i get the message, (Plant alredy exist here). no matter what i do i cant plant stuff on that block and it seems to be spreading. right now 25/30% of my crops fields are useless.

This is what i have tried so far:
Server Restart.
Remove Block refill it and resow.
Remove Block get soil from another block to fill it up and resow.
Try plant another plant on that location.
Digg 1 layer down to see if i can plant on that layer wich i could but i still cant plant on the layer i want to plant on tried the same only going 1 layer up.

Some basic Info:
Iam Admin on my own Rented Dedicated Server.
First encounterd the bug at Version 7.3
Iam pretty new to the game, been playing for 1 week + minus.
the plants i think cause the issues (Corn, Wheat, Tomatoes and Beans) maby the others.

**Comment by MarjieAVolk** [comment] 2018-04-05 17:44
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6999

**Comment by MarjieAVolk** [comment] 2018-04-05 17:44
Oh wait a sec, have you seen this issue still on 7.3.2?

**Closed by MarjieAVolk** 2018-04-05 17:44 UTC

**Comment by Swatmo** [comment] 2018-04-06 10:44
yes

**Comment by MarjieAVolk** [comment] 2018-04-06 18:04
I think that we have a fix for this, but if you have a save file and location where it happens, it might be good to double check.  Thanks!

**Comment by Swatmo** [comment] 2018-04-07 10:31
i have to say sorry. it seems to be working now. thanks alot for the help tho :)

**Comment by MarjieAVolk** [comment] 2018-04-09 22:03
Fine with me, haha, glad it is working now :)
