### ISSUE TITLE
freshwater reset

### ISSUE THREAD

**Issue by XTowerX** [StrangeLoopGames/EcoIssues#10133] opened 2018-11-26 15:52 UTC
before the server restart i manage to make a irrigation system with freshwater and alot of bricks(aqueducts)
after the server reset, all the freshwater vanishes and does not return
before server restart
![before reset](https://user-images.githubusercontent.com/31690293/49025419-e7717f00-f19b-11e8-9576-31302961d028.png)

after server restart
![after reset](https://user-images.githubusercontent.com/31690293/49025424-ea6c6f80-f19b-11e8-801f-d650d6c4b8de.png)

**Comment by WeaselDog** [comment] 2020-01-11 06:35
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7263

**Closed by WeaselDog** 2020-01-11 06:35 UTC
Labels: Priority: Medium
