### ISSUE TITLE
5.5.3 opening economy viewer causes disconnection

### ISSUE THREAD

**Issue by Stephenw92-git** [StrangeLoopGames/EcoIssues#1319] opened 2017-04-02 00:26 UTC
Server has just gone live with the 5.5.3 update, players accessing the economy viewer and were diconnected with the following dump file created on the server file:

--BEGIN DUMP--
Dump Time
04/02/2017 01:23:29

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC SelectStack on Inventory!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Items.Actionbar.EconomyViewerItem.OnSelected(ItemCollection stack, Player player)
   at Eco.Gameplay.Items.InventoryBase.SelectStack(ItemCollection stack, Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer(Int64 maxMilliseconds)
   at Eco.Shared.Networking.NetPort.Update(Int64 maxMilliseconds)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_0()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2017-06-02 01:03
Closing as duplicate of StrangeLoopGames/EcoIssues#1444

**Closed by MarjieAVolk** 2017-06-02 01:03 UTC
