### ISSUE TITLE
USER ISSUE: Machines not turning on even with sufficient power

### ISSUE THREAD

**Issue by jazimpac** [StrangeLoopGames/EcoIssues#24691] opened 2024-01-26 18:09 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**

**Expected behavior:**
it should have turned my machine on as there is sufficient power

**Actual behavior:**
my screw press is still off even though it has sufficient power pus extra too.
yes its the corret power type and its above the power suppy needed while opperating

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nope, pure vanilla no mods 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-27 21:50
Cannot reproduce, needs reproduction steps.

**Comment by D3nnis3n** [comment] 2024-02-05 04:02
Closing due to not reproducible and no further information provided.

**Closed by D3nnis3n** 2024-02-05 04:02 UTC
Labels: Status: Needs Information, Status: Not reproduced
