### ISSUE TITLE
Unclear which generators provide which type of power

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1328] opened 2017-04-04 07:19 UTC
Combustion generator should specify that it provides mechanical energy. (or it should provide electrical energy... it's pretty useless when there are other much easier ways to get mechanical energy.)

**Comment by MarjieAVolk** [comment] 2018-01-12 19:24
Partially duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3352, partially already fixed

**Closed by MarjieAVolk** 2018-01-12 19:24 UTC
