### ISSUE TITLE
USER ISSUE: Crash with bow and arrow in hand

### ISSUE THREAD

**Issue by jjcleves** [StrangeLoopGames/EcoIssues#5069] opened 2018-02-25 07:13 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Hunt with bow and arrow in hand
2. Attempt to pick up a log

NOTE: First time this has happened, and I have been playing for a few hours straight in single player.

**Expected behavior:**
Picked up log

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-26 21:38
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-26 21:38 UTC
