### ISSUE TITLE
USER ISSUE: Open door with Shovel

### ISSUE THREAD

**Issue by MisterMarlu** [StrangeLoopGames/EcoIssues#5772] opened 2018-03-09 15:04 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1. Put a wooden shovel into the inventory.
2. Place a door.
3. Try to open/close the door with the shovel on your hand.

**Expected behavior:**
I should be able to open/close the door with a shovel on my hand.

**Actual behavior:**
Instead I'm not able to open/close the door. No interaction.

**Comment by MarjieAVolk** [comment] 2018-03-09 22:14
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3868

**Closed by MarjieAVolk** 2018-03-09 22:14 UTC
