### ISSUE TITLE
USER ISSUE: Crash when looking at Outpost Claim Stake

### ISSUE THREAD

**Issue by timzwiebel** [StrangeLoopGames/EcoIssues#24874] opened 2024-04-10 06:25 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.0 beta release-640

**Steps to Reproduce:**
I don't know what causes the issue, but I opened an Outpost Claim Stake. I believe it had 3 Claim Papers in it and it said 12/9 plots. Then the game crashed. It seems like you're no longer able to put Claim Papers into Outpost Claim Stakes.

**Expected behavior:**
It shouldn't crash

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.PlotsComponent.DescribePlotsClaimed()
   at InvokeStub_PlotsComponent.DescribePlotsClaimed(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-04-10 07:17
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24863

**Closed by D3nnis3n** 2024-04-10 07:17 UTC
