### ISSUE TITLE
USER ISSUE: Blast Furnace bugged after Auth server trouble last night

### ISSUE THREAD

**Issue by bcagle4** [StrangeLoopGames/EcoIssues#11646] opened 2019-03-12 15:23 UTC
**Version:** 0.8.0.6 beta

**Steps to Reproduce:**
Try to cancel job of 99xx steel queued on blast furnace

**Expected behavior:**
Cancelled and returned the hundreds of quicklyme, iron ore and charcoal

**Actual behavior:**
Won't cancel. The furnace is stuck in an "on" state, showing that it is producing steel, but producing nothing. I had 100's of quicklyme and iron ore saved up in the adjacent stockpile, that are now gone (I assume they were consumed in the queue of steel) Please don't let those resources disappear!

**Do you have mods installed? Does issue happen when no mods are installed?:**
Won't cancel. The furnace is stuck in an "on" state, showing that it is producing steel, but producing nothing.

**Comment by redwyre** [comment] 2019-03-12 15:34
Do you have enough room to return all the resources? Was there an error message in the chat?

**Comment by bcagle4** [comment] 2019-03-12 15:56
Hi Simon, thanks for the quick reply!

There is room (an entire empty stockpile). I get the error: "could not
cancel this project: inventory does not contain the items requested to be
removed".

**Comment by bcagle4** [comment] 2019-03-12 16:00
Last night when the Auth servers were down, I would log in for a couple
minutes, feed the furnace, and repeatedly get dc'd. I am running the
automated setup where I have 9999 steel, quicklyme, charcoal, iron and gold
all queued up.

**Comment by Conchipedia** [comment] 2019-03-15 02:39
I had a problem similar to this on a masonry table with it asking for something to be in inventory to cancel order, if I tried placing something in a stockpile that it needed it kept taking it but if I had an item it required in toolbar or backpack it detected this item and I could cancel order

**Comment by Conchipedia** [comment] 2019-03-15 02:53
linking to this one (that i could never reproduce) as it is based on the same problem of requiring an item in inventory to cancel an order
Cannot cancel a project as Inventory does not contain the items requested to be removed #11235

**Comment by bcagle4** [comment] 2019-03-15 02:59
I was eventually able to cancel the queue, not sure what changed.

**Comment by Conchipedia** [comment] 2019-03-15 03:01
you got lucky, i couldn't move a table i was on till i actually carried the item it needed

**Comment by Conchipedia** [comment] 2019-03-15 03:05
but it's weird that it requires an item from inventory to cancel and gives the following message:
![could not cancel](https://user-images.githubusercontent.com/29383891/54405571-fd656a00-46ce-11e9-935f-7ca873377235.png)
so its a part of code somewhere that is actually looking at your inventory for an item

**Comment by D3nnis3n** [comment] 2019-06-20 10:23
Closing for now due to not being reproducable and no further information available. Reopen when it occurs again and you can provide more information / logfiles.

**Closed by D3nnis3n** 2019-06-20 10:23 UTC
Labels: Investigate, Needs Information
