### ISSUE TITLE
3d map - some trees displayed as icon

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13408] opened 2019-10-22 10:33 UTC
Not as 3d tree (like old)
Spruce
![изображение](https://user-images.githubusercontent.com/4980243/67277793-4df83d80-f4d0-11e9-8d97-0ed3bb1b36c4.png)
or Joshua
![изображение](https://user-images.githubusercontent.com/4980243/67277823-5cdef000-f4d0-11e9-867e-f117cfbef9b2.png)
etc...

p.s.
Not bad if we can have two modes, "icon" or "3d" for trees.

**Comment by redwyre** [comment] 2020-03-02 14:01
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14946

**Closed by redwyre** 2020-03-02 14:01 UTC
Labels: Priority: Low
