### ISSUE TITLE
USER ISSUE: Meteor goes behind moon

### ISSUE THREAD

**Issue by matthew7474** [StrangeLoopGames/EcoIssues#14509] opened 2020-01-26 05:30 UTC
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Look at meteor with moon

**Expected behavior:**
go in front of moon

**Actual behavior:**
went behind moon

**Do you have mods installed? Does issue happen when no mods are installed?:**
went behind moon

**Comment by D3nnis3n** [comment] 2020-01-26 10:57
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10579

**Closed by D3nnis3n** 2020-01-26 10:57 UTC
