### ISSUE TITLE
USER ISSUE: Error Massage

### ISSUE THREAD

**Issue by PermanentEdding** [StrangeLoopGames/EcoIssues#6853] opened 2018-04-01 18:03 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
I tried to pick up a log

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60,00%>Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment] 2018-04-02 21:54
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-04-02 21:54 UTC
