### ISSUE TITLE
USER ISSUE: Cannot enter serveur

### ISSUE THREAD

**Issue by rodsmooths** [StrangeLoopGames/EcoIssues#4303] opened 2018-02-11 08:07 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
CLic contiue
Wait for loading

**Expected behavior:**
Enter the game

**Actual behavior:**
The following error message popped up:
Connextion Failed
Caught exception:  object refernrece not set to to an instance of an objevt
```
<size=150%>Connection Failed</size>

Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment] 2018-02-13 04:15
Closing as duplicate of #4144 . You can continue tracking the issue there.

**Closed by MarjieAVolk** 2018-02-13 04:15 UTC
