### ISSUE TITLE
Wall Lights hover in front of thin walls (e.g. ones not full block size).

### ISSUE THREAD

**Issue by kshood** [StrangeLoopGames/EcoIssues#6025] opened 2018-03-14 04:07 UTC
Wall Lights are not flush against thin walls, just full sized blocks.

![wrong_lights](https://user-images.githubusercontent.com/31428664/37382865-9acddb62-271b-11e8-9602-a50c337407b2.png)

**Comment by elfl0rd** [comment] 2018-06-25 19:01
Dupe https://github.com/StrangeLoopGames/EcoIssues/issues/5395 but contain screenshot

**Comment by MarjieAVolk** [comment] 2018-06-25 20:46
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5395

I will paste the screenshot there.

**Closed by MarjieAVolk** 2018-06-25 20:46 UTC
Labels: Feature
