### ISSUE TITLE
Unable to see LAN server

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8404] opened 2018-07-09 09:36 UTC
New user could not get into singleplayer due to the player profile issue.  Started up EcoServer outside of the client, it created game and is loaded without error.  He is able to see remote servers and join but the local server will not show up in the LAN section in the browser.  Deleted appdata but that did not help.  Verify cache - 2 files missing but those were reacquired and he can then join other servers fine.  Cannot determine why he cannot see LAN. Antivirus was suspended and the firewall is not an issue

Any idea what could be blocking LAN from showing in Browser?

**Comment by MarjieAVolk** [comment] 2018-07-09 18:08
Is their server on the default port?  The lan section only searches for servers on the default game port (3000)

**Comment by MarjieAVolk** [comment] 2018-07-09 18:09
Also, does their server console show any errors related to networking?

**Comment by mirasrael** [comment] 2019-06-26 07:54
Can't reproduce and no additional information. Closing for now.

**Closed by mirasrael** 2019-06-26 07:54 UTC
Labels: Medium Priority
