### ISSUE TITLE
USER ISSUE: Wrong inventory weight calculation when moving items to empty slots

### ISSUE THREAD

**Issue by DragonDev1906** [StrangeLoopGames/EcoIssues#21444] opened 2021-04-17 22:35 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
1. Give yourself a heavy item (e.g. wood cart) in your backpack or toolbar
2. Fill your inventory weight so that less than the weight of the heavy item remains (e.g. 25kg for a new character)
3. Move the heavy item to the stack of another item => everything works normal
4. Move the heavy item to an empty stack in your inventory/backpack => "Inventory to Heavy" message

**Expected behavior:**
It should allow me to move items in my inventory, because the resulting weight stays the same.

**Actual behavior:**
Instead it prevent's moving the item to an empty slot and shows the "Inventory to Heavy" message.
My guess: The inventory weight is checked before the weight of the item is removed from it, resulting in the weight of the item beeing added twice in the calculation, which brings it above the max and prevents moving the item.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, but it also happens when no mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment] 2021-04-19 07:29
> Not dragging all items to other slots in inventory when overloaded
> Vid here: [https://www.youtube.com/watch?v=-Knqx0XT1Mk](url)
> (I don't know why the link dosent work. But new tab and enter url works)

**Comment by gzatravkin** [comment] 2021-04-19 21:37
Seems as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/21470

**Closed** 2021-04-22 10:34 UTC
Labels: Category: Gameplay, Priority: Critical, Regression, Squad: Wild Turkey, Status: Fixed, Type: Bug
