### ISSUE TITLE
idk how to delete i realized this is not a bug

### ISSUE THREAD

**Issue by ToxicP1e** [StrangeLoopGames/EcoIssues#22951] opened 2022-01-24 01:28 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.5 beta release-278

**Steps to Reproduce:**
1. Invite another player as a resident
2. have them place down an item (such as a workbench)
3. evict the person from the housing

**Expected behavior:**
Other player is evicted and nothing else happens

**Actual behavior:**
Other player is evicted and anything they placed down is deleted

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-01-24 16:01
This indeed works as intended, hence closing :)

**Closed by D3nnis3n** 2022-01-24 16:01 UTC
