### ISSUE TITLE
USER ISSUE: trees trunks disappearing after chopping

### ISSUE THREAD

**Issue by Melusane** [StrangeLoopGames/EcoIssues#5826] opened 2018-03-10 10:38 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Since yesterday, trees keep disappearing after I take some portions of the trunk. This time half the world disappeared when I moved after a trunk disappearance. I used unstuck and it worked, I saw the trunk back and when I tried to hit it with the axe the message popped up.

**Expected behavior:**

**Actual behavior:**
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.

Stack:
   à TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   à Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   à Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   à Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   à Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   à Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   à Eco.Shared.Networking.NetPort.ProcessBuffer()
   à Eco.Shared.Networking.NetPort.Update()
   à Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

**Comment by MarjieAVolk** [comment] 2018-03-12 22:55
So the felled trees disappear, but later they come back?  Do they disappear before your eyes, or they are gone when you get back?

Your error message looks like https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Comment by MarjieAVolk** [comment] 2018-03-13 18:49
Closing as duplicate of #3752, unless I hear differently :)

**Closed by MarjieAVolk** 2018-03-13 18:49 UTC
