### ISSUE TITLE
Watelevel Waterworld Pollution #2 

### ISSUE THREAD

**Issue by DeluXXe1986** [StrangeLoopGames/EcoIssues#7881] opened 2018-05-25 14:03 UTC
Problem since Update 7.4.6

Waterlevel raised up to over 30 blocks, so we live in waterworld now.
waterlevel was 34 before an now on level 64 at one moment because air pollution raised the level for 1 Meter.
stopped any kind of groundpollution and airpollution (ppm) but it grows and grows.
Plants are always -100 

waterlevel ist now by level 64 before it was moderate on level 34.
Think it is too much.
Please help with hotfix soon as possible that we are able to make a rollback

**Comment by SeanAtr0n** [comment] 2018-06-12 01:30
Actually guess this is a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7878

**Closed by SeanAtr0n** 2018-06-12 01:30 UTC
Labels: Medium Priority
