### ISSUE TITLE
USER ISSUE: I don't know what went wrong, just a crash.

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#5828] opened 2018-03-10 10:47 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Swim in Water while carrying a couple Logs

**Expected behavior:**

**Actual behavior:**
Caught exception:

<size=60,00%>Object reference not set to an instance of an object

```
Stack:
  at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates (System.Collections.Generic.IEnumerable`1[T] newObjects, Eco.Shared.Networking.INetObjectViewer viewer, System.Collections.Generic.ICollection`1[T] monitored) [0x0001c] in <87b449fa3be548e4a9bca65d2ad34821>:0 
  at Eco.Plugins.Networking.Clients.Client.Update (System.Diagnostics.Stopwatch timer) [0x000b9] in <cb46936a53a64832a4f16709d80dbff3>:0 
  at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1 () [0x00012] in <cb46936a53a64832a4f16709d80dbff3>:0 
```
</size>

SIDENOTE: i also having a lot of sync errors, i am in a deset, dig sand and get dirt or i chop a cactus and it keeps staying as it was until i relogg where it then lays on the ground

and while working with tools the selected tool sometimes switches to other tools in my hotbar without touching the mousewheel

**Comment by MarjieAVolk** [comment] 2018-03-12 18:33
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-12 18:33 UTC

**Comment by MarjieAVolk** [comment] 2018-03-12 18:35
The other problems you describe sound like server lag.

Sometimes your tool is switched automatically, for example if you pick up some dirt, your tool might be automatically switched to the shovel.  This is done because there are some limitations on what tool you can use while carrying things.  For example, you have to be holding a shovel in order to carry dirt around.

**Comment by mindforger** [comment] 2018-03-12 18:45
thx for info, still sometimes irritating, weill have a look at it

but the dirt transforming into sand and vice versa (had both happening, mostly after i relogged) still seems strang, how can i distiguish sand and dirt if not from the surface texture?

**Comment by MarjieAVolk** [comment] 2018-03-13 22:32
I assume what you are seeing is the biome changing.  If the biome becomes desert, then the surface dirt will turn into desert sand.  But desert sand will still be treated as dirt when picked up, etc.  This is different from 'real' sand, which can be found mostly on beaches.

**Comment by mindforger** [comment] 2018-03-14 05:16
Yeah, i actually noticed the real sand has quite  the brighter color
