### ISSUE TITLE
USER ISSUE: Changing owner of steam cart

### ISSUE THREAD

**Issue by VytautasEgroup** [StrangeLoopGames/EcoIssues#24578] opened 2024-01-10 01:03 UTC
\
**User Id: (slg237992)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Try to change owner of deed.

**Expected behavior:**
Given ownership to person specified

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by VytautasEgroup** [comment] 2024-01-10 01:07
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13881673/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13881674/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-01-10 09:15
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24536

**Closed by D3nnis3n** 2024-01-10 09:15 UTC
