### ISSUE TITLE
USed hammer on concrete windows, crashed game

### ISSUE THREAD

**Issue by mbenitezmeiss** [StrangeLoopGames/EcoIssues#3226] opened 2017-12-30 06:00 UTC
I am not an admin, but an admin "spawnvillage" command (concrete) and I used my hammer to break the building (was working with them) to create a doorway. Upon using the hammer on the concrete window, game crash. Admin user doesn't get crash. 

Below is the crash log:

Caught exception: Caught exception invoking RPC PlayerInteract on Player!
Object reference not set to an instance of an object
 
Stack:
  at Eco.Gameplay.Items.UsableItemUtils.PlayerDeleteBlock (Eco.Shared.Math.Vector3i blockPosition, Eco.Gameplay.Players.Player player, System.Boolean addToInventory, Eco.Gameplay.Items.Item fallbackGiveItem, Eco.Core.Utils.AtomicAction.IAtomicAction[] additionalActions) [0x000c6] in <3efb6410a2804af180b3a2e45ee271fd>:0
  at Eco.Gameplay.Items.ToolItem.PlayerDeleteBlock (Eco.Shared.Math.Vector3i blockPosition, Eco.Gameplay.Players.Player player, System.Boolean addToInventory, System.Single calorieMultiplier, Eco.Gameplay.Items.Item fallbackGiveItem, Eco.Core.Utils.AtomicAction.IAtomicAction[] additionalActions) [0x00020] in <3efb6410a2804af180b3a2e45ee271fd>:0
  at HammerItem.OnActLeft (Eco.Gameplay.Interactions.InteractionContext context) [0x0003c] in <c34d727ee07c4701bd3e6a8679b80186>:0
  at Eco.Gameplay.Players.Player+<>c__DisplayClass46_0.<PlayerInteract>b__0 (Eco.Gameplay.Interactions.IInteractable inter) [0x00000] in <3efb6410a2804af180b3a2e45ee271fd>:0
  at Eco.Gameplay.Interactions.InteractionExtensions+<>c__DisplayClass0_1`1[T].<ExecuteUntilSuccess>b__1 () [0x00000] in <3efb6410a2804af180b3a2e45ee271fd>:0
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess (System.Collections.Generic.IEnumerable`1[T] results) [0x00016] in <3efb6410a2804af180b3a2e45ee271fd>:0
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, System.Func`2[T,TResult] resultFunc) [0x0001f] in <3efb6410a2804af180b3a2e45ee271fd>:0
  at Eco.Gameplay.Players.Player.PlayerInteract (Eco.Shared.Items.InteractionInfo info) [0x000df] in <3efb6410a2804af180b3a2e45ee271fd>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <01d3ec13f0784c4d88b3e52330d2fa86>:0

----------------
Server running on linux.
Server version: 0.6.3.1-alpha

Client machine stats:
Operating system: Windows 7 x64
Specs:
CPU: intel i7-4790K CPU @4.00GHz
RAM: 16.0GB
GPU: NVIDIA GeForce GTX970
Harddrive 1: SSD 256GB
Harddive 2: HDD 3TB

Reproducible: Yes.

**Comment by MarjieAVolk** [comment] 2018-01-09 23:01
Hm, I tried this both as an admin and as a non admin and didn't see any problems.  I also don't really see anything in that method that would throw for one person and not another.  Did you reproduce this multiple times?  We you consistently unable to hammer a specific block or type of blocks?  Or was this a one time thing?

**Comment by mbenitezmeiss** [comment] 2018-01-09 23:44
Yes, I was able to reproduce this multiple times. I tried 3-4 times under different circumstances. It kicked me out of the hosts server and threw that error log

**Comment by MarjieAVolk** [comment] 2018-01-09 23:47
Okay.  And it was always concrete windows and never anything else?

**Comment by mbenitezmeiss** [comment] 2018-01-10 01:17
Yes, its only on the concrete building's windows.

Its fine on the wooden windows.

**Comment by MarjieAVolk** [comment] 2018-01-10 01:53
Okay one more question - Do you get this problem on all servers?  Or only on that one server?  And if only on the one server, could you give me the game save?  Maybe I can repro if I pretend to be you.

**Comment by MarjieAVolk** [comment] 2018-01-16 23:26
Decreasing priority due to no repro

**Comment by MarjieAVolk** [comment] 2018-01-24 00:33
I'm going to close this due to no repro, and since hammer placement has been revised a few times since this bug, so it might be obsolete anyways.  If it continues to be a problem, let me know.

**Closed by MarjieAVolk** 2018-01-24 00:33 UTC
Labels: Low Priority
