### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Shikula** [StrangeLoopGames/EcoIssues#6059] opened 2018-03-14 21:34 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Aktivni zelezny krumpac.
stale zmackla klavesa E
stal jsem na svahu hliny, ve visce asi tak 1,5 bloku
tezba zlate zily.
2 vytezene a sebrane, po rozbiri treti hra spadla.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Odkaz na objekt není nastaven na instanci objektu.


Stack:
   v Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   v Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   v Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-15 21:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-15 21:40 UTC
