### ISSUE TITLE
USER ISSUE: roadtool repair issue

### ISSUE THREAD

**Issue by annykin** [StrangeLoopGames/EcoIssues#3564] opened 2018-01-21 01:45 UTC
**Version:** 0.6.4.1 alpha

**Steps to Reproduce:**
repair a road tool in a repair bench

**Expected behavior:**
road tool repaired

**Actual behavior:**
kicked from server every time

**Comment by pamduncan** [comment] 2018-01-21 04:34
This was already reported here:  #3555

**Comment by MarjieAVolk** [comment] 2018-01-22 19:11
Duplicate of #3555 / #3485 as stated above

Will be fixed in next staging build for sure, we're talking about whether to hotfix the current release.

**Closed by MarjieAVolk** 2018-01-22 19:11 UTC
