### ISSUE TITLE
USER ISSUE: Crash on Submitting a District

### ISSUE THREAD

**Issue by evanah64** [StrangeLoopGames/EcoIssues#23716] opened 2023-02-24 03:52 UTC
\
**User Id: (slg185685)**
**Version:** 0.9.7.9 beta release-451

**Steps to Reproduce:**
Create a large district (road network) and click submit. Does not repeat every time. This occurance was on the initial creation of the districts.

**Expected behavior:**
Submitted and exited the planning window.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Invalid Query - Query never existed or was already processed
Source:Eco.Shared

System.InvalidOperationException: Invalid Query - Query never existed or was already processed
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__76_4()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, and not sure.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2023-02-24 08:00
Hi @evanah64 

Thank you for submitting this bug report. However, we are unable to reproduce this issue.
Could you provide us with your world save file?
Looking forward to your response.

If you do not wish to share your save file here, you can sent it to me through discord at Nielzx#6566 or at my email address at daniel@strangeloopgames.com

**Comment by D3nnis3n** [comment] 2023-02-24 13:44
There is a similar issue already: https://app.clickup.com/t/10591183/ECO-26934

**Comment by D3nnis3n** [comment] 2023-11-06 11:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23821

**Closed by D3nnis3n** 2023-11-06 11:22 UTC
Labels: Status: Needs Information
