### ISSUE TITLE
USER ISSUE: Broken Personal Currency

### ISSUE THREAD

**Issue by albertmondragon** [StrangeLoopGames/EcoIssues#24167] opened 2023-12-13 06:24 UTC
\
**User Id: (slg82432)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Name is [EDMN]Velcius. Opened store in building, it is green but people are unable to purchase. When switched off and back on an error pops up that says "Target Bank Account is Invalid." When I hover over my Personal Account it says "Invalid! 2 errors: Dual Permissions: Object is not set."

**Expected behavior:**
Store should be able to buy/sell with personal currency

**Actual behavior:**
Error says Target Bank Account is invalid and store does not work.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tbwiiaddict3** [comment] 2023-12-13 18:07
Having the same issue with basically every member of my server. Not sure what the cause is.

**Comment by albertmondragon** [comment] 2023-12-13 18:11
It’s working today when I logged on!  I tried resetting my game last night
and that didn’t work. Maybe the server reset at some point and it resolved
itself?

**Comment by tbwiiaddict3** [comment] 2023-12-13 18:22
Good to know!

**Comment by tbwiiaddict3** [comment] 2023-12-13 22:00
Update: Rebooting the server did indeed fix the issue

**Comment by D3nnis3n** [comment] 2023-12-15 15:38
Fixed in 10.0.1

**Closed by D3nnis3n** 2023-12-15 15:38 UTC
