### ISSUE TITLE
USER ISSUE: Null reference on login attempt

### ISSUE THREAD

**Issue by xreplica** [StrangeLoopGames/EcoIssues#24643] opened 2024-01-18 23:07 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.0 beta release-576

**Steps to Reproduce:**
Try to log in and continue game.

**Expected behavior:**
It should have logged me in.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.UserHelpers.UserAccounts.<UpdateClaimableSettlements>g__Iter|21_0()+MoveNext()
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other, MutationInput origin)
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 items, Boolean avoidWithComparer)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T,TArg](T& original, TArg arg, Func`3 apply)
   at Eco.Core.Utils.ControllerHashSet`1.SetInternal(INetObject caller, IEnumerable`1 entries)
   at Eco.Core.Utils.ControllerHashSet`1.Set(IEnumerable`1 e)
   at Eco.Gamepl</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13982458/Player.log)

**Comment by D3nnis3n** [comment] 2024-01-18 23:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24634

**Closed by D3nnis3n** 2024-01-18 23:43 UTC
