### ISSUE TITLE
USER ISSUE: Tools not working in 1st Person

### ISSUE THREAD

**Issue by mwolf89** [StrangeLoopGames/EcoIssues#25073] opened 2024-08-19 02:08 UTC
\
**User Id: (b31a9c51-1ffc-4820-6c94-08dcbfcf9dd6)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
1.Woke up from sleeping in tent.
2. Ate food in inventory screen.
3. Switched to tool before animation was done.

**Expected behavior:**
Pulled out tool to use.

**Actual behavior:**
In first person, tool is selected, and world objects highlight as if tool can be used. But tool does not show in hand, now interact with world objects. Will work in 3rd person though.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-08-19 20:41
A potential fix for this was shipped with Hotfix 11.0.1, if the issue is still recreatable, please create a new issue.

**Closed by D3nnis3n** 2024-08-19 20:41 UTC
