### ISSUE TITLE
[0.9.1.1/0.9.1.2] "Done" crafting tooltips/bubbles don't vanish

### ISSUE THREAD

**Issue by LsHallo** [StrangeLoopGames/EcoIssues#19112] opened 2020-11-04 14:56 UTC
After the completion of crafting projects the bubble in the top right will not go away.
![image](https://user-images.githubusercontent.com/22171518/98126757-3b239180-1eb6-11eb-9c26-9c030c57b521.png)

All done bubbles have been stuck there for >10min. Constantly getting more and cluttering up the screen while being animated and super distracting because of that.

**Comment by LsHallo** [comment] 2020-11-04 15:36
![image](https://user-images.githubusercontent.com/22171518/98131750-df5c0700-1ebb-11eb-9664-c93d240fd0c2.png)

Quick update after another 30min.

**Comment by LsHallo** [comment] 2020-11-04 15:45
![image](https://user-images.githubusercontent.com/22171518/98132720-06ff9f00-1ebd-11eb-9e88-5ae11b80ed9c.png)
Activity log is having a nice time. Maybe consider adding a second row at some point? Also thinking about smaller screens with maybe 1024 or something width.

**Comment by SlayksWood** [comment] 2020-11-05 05:51
@LsHallo Thank you for the report.
Can't reproduce. Start 40+ orders and complete at least 15, I have only last 5 projects here:
![image](https://user-images.githubusercontent.com/45708377/98202662-846df280-1f43-11eb-8286-0666f4ea687d.png)
1. Do you have it after restart game?
2. Provide log file when it happen next time. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
3. Don't crop the picture, the rest information on the screen can be helpful too.

**Comment by LsHallo** [comment] 2020-11-05 11:23
Ok will do.
It happened after I've slept about 17h. Since then I've disconnected and reconnected and have slept 3 times without the issue reappearing. If it appears again I will let you know.

**Comment by LsHallo** [comment] 2020-11-08 02:32
Had the issue again. I was moving crafting recipes around in a table and the "basic upgrade 3" recipe finished while i was dragging the mortared brick recipe. Then the mortared brick was shown as Done in the top bar.
[Player.log](https://gist.github.com/LsHallo/29b1abe8841c303b4e0c60d6e1f43205)

**Comment by SlayksWood** [comment] 2020-11-09 10:30
Thank you for the information, we will investigate it.

**Comment by webnoob** [comment] 2020-11-11 16:36
I too have had this issue. I'll try and provide some information when it happens again

**Comment by IcedForge** [comment] 2020-11-17 07:45
Looks like there is some map element issues not properly updating and deleting when you move around objects in crafting ui's
I dont have a work order left yet the markers have countdowns and statements saying i am crafting and i have things done
![Screenshot_100](https://user-images.githubusercontent.com/24981362/99360563-11546c80-28b1-11eb-9c54-e2b398b5eed3.jpg)
And if i mouse over the map markers on the map they are not contained by objects.
![Screenshot_102](https://user-images.githubusercontent.com/24981362/99360538-06014100-28b1-11eb-8341-1d475ad47b12.jpg)

**Comment by Pimmeul** [comment] 2020-12-07 18:52
![image](https://user-images.githubusercontent.com/55128050/101392036-80781c00-38c5-11eb-94ee-1a7b0ba1ac22.png)

have the same issue over here. It started when I joined a Work party, then when left after 1 min. the projects from there party were still there and my new project just didn't vansih.

**Comment by TwixterZ** [comment] 2022-05-10 07:50
Closing this issue as no longer happening, feel free to re-open if you faced this issue again

**Closed by TwixterZ** 2022-05-10 07:50 UTC
Labels: Status: Investigate
