### ISSUE TITLE
Double calorie warning

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3587] opened 2018-01-22 21:01 UTC
![image](https://user-images.githubusercontent.com/3536496/35244239-5b12c7b8-ff74-11e7-885d-180067321ad7.png)

**Comment by MarjieAVolk** [comment] 2018-01-22 21:03
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3318

**Closed by MarjieAVolk** 2018-01-22 21:03 UTC
