### ISSUE TITLE
USER ISSUE: Log Not appearing

### ISSUE THREAD

**Issue by ryanelbert5125gmail** [StrangeLoopGames/EcoIssues#23571] opened 2022-11-25 00:57 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
1. I don't really know the first part but my game was lagging pretty bad on a solo local sever 
2. Cut down a tree and the tree hit box outline doesn't show up on the cut down tree
3. Some times fixes it when you hit the left over roots of the tree (When you hit the root the cut down tree gets outlined too) 

**Expected behavior:**
It should just have the tree be interactable

**Actual behavior:**
The tree can be pushed around but can't be cut up 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10087858/Player.log)

**Comment by D3nnis3n** [comment] 2022-12-02 21:58
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23049

**Closed by D3nnis3n** 2022-12-02 21:58 UTC
