### ISSUE TITLE
Entering World

### ISSUE THREAD

**Issue by Alexence** [StrangeLoopGames/EcoIssues#8289] opened 2018-07-03 11:35 UTC
Only just bought this game, have tried creating 3 new worlds. Each time the game generates the world and then says "Entering World" and then crashes. The Eco server appears to be running on my computer but that is all.

**Comment by elfl0rd** [comment] 2018-07-03 13:37
can you attach log, dump and save?

**Comment by MarjieAVolk** [comment] 2018-07-05 17:29
We've had a couple reports like this lately.  We found that deleting a certain file often fixed it.  Open up local files via steam, and then find and delete Eco_Data\Server\Eco.Mods.dll

Let me know if that works.

**Comment by MarjieAVolk** [comment] 2018-07-05 22:21
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8274, unless I hear otherwise

**Closed by MarjieAVolk** 2018-07-05 22:21 UTC
Labels: High Priority
