### ISSUE TITLE
USER ISSUE:  Asphalt ramps 

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#6786] opened 2018-03-31 01:23 UTC
"i have a person on my server who keeps placing asphalt ramps and then getting morphed into it but when they type /unstuck they get kicked and the loading gets stuck on entering world"

"i have no photos but this is what has happened to 2 serperate players, once last night and twice to another today " i have a person on my server who keeps placing asphalt ramps and then getting morphed into it but when they type /unstuck they get kicked and the loading gets stuck on entering world"

From support, the same person.

**Comment by mknechtel7** [comment] 2018-04-01 04:57
When I place a asphalt ramp down while standing where it will be my screen goes gray/black and my coordinates jump into the billions. (see screenshots)
![dth-20180331233311_1](https://user-images.githubusercontent.com/3682661/38169950-1cdeb4f2-353e-11e8-9a55-f9fc18917fe2.jpg)
![dth-20180331233316_1](https://user-images.githubusercontent.com/3682661/38169951-1d04545a-353e-11e8-9c14-1239abd0e5cc.jpg)
![dth-20180331235303_1](https://user-images.githubusercontent.com/3682661/38169995-32a8008a-353f-11e8-818a-f4a6f948295e.jpg)
![dth-20180331235303_1](https://user-images.githubusercontent.com/3682661/38169995-32a8008a-353f-11e8-818a-f4a6f948295e.jpg)

While bugged out I am able to open the map (it shows blank), use and see chat, open the setting and modify them. Teleporting to a player or coordinates will bring me back to the normal world. If I disconnect while bugged I am not able to log back into the server. When attempting to join the server it infinity stays on "loading world." I am able to log into other servers but not the one I bugged out on until my profile is removed/replaced from backup on the server.

**Comment by MarjieAVolk** [comment] 2018-04-04 22:06
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/6882?

**Comment by craig-jong** [comment] 2018-04-04 22:11
Any idea what version of the game this is one?

Sean's depenetration code seems to have fixed being able to be inside placed ramps for me.

If I'm reading this right, it only happens in a very specific location on the map?

**Comment by mknechtel7** [comment] 2018-04-05 01:55
> Any idea what version of the game this is one?
When I encountered the bug I was on version 7.3.1

> If I'm reading this right, it only happens in a very specific location on the map?
It can happen anywhere on the map. It seems to happen when the player is standing in the space where the ramp will be once placed and where there is no room for the player to be moved to once placed.

**Comment by SeanAtr0n** [comment] 2018-04-05 02:16
hmm couldn't reproduce this so far... if you can do it again could you send me your log file afterwards?

paste this in explorer to find it `%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by elfl0rd** [comment] 2018-04-05 02:32
errored user - in world on stuck on loading, admin can teleport it (to normal world) then kick it, then in can join normally.

**Comment by mknechtel7** [comment] 2018-04-05 02:48
Just confirmed I can still reliably make it happen on 7.3.2.

Hmm. It looks like my log is getting spammed with some other error. This only started happening since the 7.3.2 update. Enjoy looking through 35,000 lines to see if you can find something useful.

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1878414/output_log.txt)

**Comment by zEverdeen** [comment] 2018-04-05 14:25
I am pretty sure it was two different people. One who didn't want to make a user, so I posted it for that person, and mknechtel7.

That's why it took two days from the first post to the second. When I saw mknechtel7, I already knew about this bug and sent him straight to this, Especially, because he is able to reproduce it.

**Comment by SeanAtr0n** [comment] 2018-05-10 22:36
should be fixed in 7.4

**Closed by SeanAtr0n** 2018-05-10 22:36 UTC
Labels: High Priority
