### ISSUE TITLE
USER ISSUE: Endless Falling

### ISSUE THREAD

**Issue by kgress** [StrangeLoopGames/EcoIssues#5347] opened 2018-03-03 19:29 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Produce a world where it wasn't completely generated. To tell if the world isn't fully generated, find blocks that are see through.
2. Step on top of a block that is invisible, i.e. not generated
3. Observe the bug. Character will fall endlessly

**Expected behavior:**
The world should have been fully generated 

**Actual behavior:**
The world did not fully generate

**Comment by MarjieAVolk** [comment] 2018-03-07 20:50
Some of these issues were fixed in 7.2, so may already be fixed.

**Comment by metachronism** [comment] 2018-03-19 18:01
closing as dupe of chunk building bug(s)

**Closed by metachronism** 2018-03-19 18:01 UTC
Labels: High Priority
