### ISSUE TITLE
USER ISSUE: This is not where I parked my car

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#5104] opened 2018-02-26 01:57 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
park a cart in front of a pumpjack

**Expected behavior:**
STay put

**Actual behavior:**
Transport when you turn your back on it for more then a few minutes to a random location my was some werid number of (424,-57406,375)

**Comment by MarjieAVolk** [comment] 2018-02-26 21:55
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4991

Will note your negative y coordinate there.

**Closed by MarjieAVolk** 2018-02-26 21:55 UTC
