### ISSUE TITLE
skillui always says "casting" regardless of selected skill

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#10460] opened 2019-01-03 00:18 UTC
![image](https://user-images.githubusercontent.com/3150561/50618820-073a4800-0eaa-11e9-9a1a-12bd6a26896c.png)

**Comment by elfl0rd** [comment] 2019-01-03 06:20
Duplicate of #10250

**Closed** 2019-01-07 05:53 UTC
