### ISSUE TITLE
USER ISSUE: Foundations that are in property that overlaps 0,0 causes the influence to spawn hundreds of blocks away

### ISSUE THREAD

**Issue by jacob28348** [StrangeLoopGames/EcoIssues#24152] opened 2023-12-13 01:24 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Place a town foundation  inside of property that overlaps 0,0.

**Expected behavior:**
Sphere of influence should surround the foundation.

**Actual behavior:**
Sphere of influence spawns several hundred blocks away.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2023-12-13 16:12
Hi @jacob28348 

Thank you for submitting this bug report.
Could you provide your save file where this issue is happening? We are unable to reproduce this one so far.

**Comment by jacob28348** [comment] 2023-12-13 20:02
Sure thing https://mega.nz/folder/XRYjTKQR#ym-TrQgGwUNFAvTkGzqLAQ

The Rainforest Glen Townstone at 1287, 1392 was _originally_ at 1287, 1395. If you remove the Rainforet Glen Townstone and place another townstone at 1287, 1395 everything will be fine until the server restarts. When the server restarts the sphere of influence will move.

**Comment by D3nnis3n** [comment] 2024-01-02 02:33
We have not been able to reproduce this issue, including with your savefile, everything is correct there. Closing.

**Closed by D3nnis3n** 2024-01-02 02:33 UTC
Labels: Status: Needs Information

**Comment by D3nnis3n** [comment] 2024-01-06 13:23
We were able to get a different save that had the same problem reported and also had it reproducable for us, so the issue has been identified and fixed for next patch.
