### ISSUE TITLE
USER ISSUE: Opening Shops Heavily Reduces Frame Rate

### ISSUE THREAD

**Issue by snmr1345** [StrangeLoopGames/EcoIssues#24789] opened 2024-02-23 04:59 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
I'm not really sure, we've run this server for a while and I certainly didn't have this issue prior to the last update but I'm not sure if it's something to do with the server growth or the update.  Doesn't seem to matter how many items are in the shop.  I often have to restart the game to get it to let me use the shop.  When it's that bad, the shop will have items all in the wrong places.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-02-23 09:19
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24381.

Please provide the data we requested in that issue, without it we cannot investigate the issue.

**Closed by D3nnis3n** 2024-02-23 09:19 UTC
