### ISSUE TITLE
Building block stacks should have consistent sizes

### ISSUE THREAD

**Issue by SatsukiShizuka** [StrangeLoopGames/EcoIssues#2366] opened 2017-09-28 06:55 UTC
As of Alpha 6.0 - Stockpiles hold building blocks (Logs, lumber, brick...) in stacks of 5, while player hauling and carts still carry in stacks of 10, which creates confusion and frustration when transferring. Please either revert stockpiles to carry 10, or change carry/cart capacities accordingly. Preferably the former, as it is already frustrating enough with back-and-forth trips gathering materials to build and new maintenance costs.

**Comment by Frozen-byte** [comment] 2017-09-28 12:00
would be easier to have same abillities like Space Engineers to transfer items.

**Comment by Fank** [comment] 2017-09-28 16:33
@Frozen-byte some explanation what that means would be great

**Comment by metachronism** [comment] 2017-09-28 18:43
would drag 'n drop placing the full stack into the destination be sufficient?

**Comment by Fank** [comment] 2017-09-28 18:44
Would improve the usability a lot

**Comment by SatsukiShizuka** [comment] 2017-09-29 06:04
Still leaves the problem of loading a full stack into a cart or onto hands a problem. Not good enough.
*Yes, there's the "axing the stockpile to get wood/lumber" but that's only wood...

**Comment by metachronism** [comment] 2017-11-09 22:14
We aren't going to change how stockpiles have different stack limits; its based on the physical space allowed by the stockpile

marjie/craig not sure how/if you want to handle this or close as a dupe of other issues, such as the shift+click item move and other UI improvments we are planning on doing

**Comment by MarjieAVolk** [comment] 2017-11-09 22:20
Yeah it does seem like fancy new inventory shortcuts will fix these concerns anyway

**Comment by MarjieAVolk** [comment] 2017-11-09 22:22
So sure, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2159 (Is there another issue for that too?  couldn't find it)

**Closed by MarjieAVolk** 2017-11-09 22:22 UTC
