### ISSUE TITLE
USER ISSUE: legacy controls wrong

### ISSUE THREAD

**Issue by murderinspree** [StrangeLoopGames/EcoIssues#22616] opened 2021-08-31 05:26 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
while backing a cart

**Expected behavior:**
looking left and right have the opposite effect they had before

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2021-08-31 09:27
Hi @murderinspree 

Thank you for writing this bug report.
I can confirm that the legacy cart control is actually different than how the cart control is in 9.3.
I've created a bug report for it and have forwarded it to our development team.

[Internal Report](https://app.clickup.com/t/10591183/ECO-14868)

**Comment by D3nnis3n** [comment] 2021-08-31 09:49
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/22588, so closing here as well.

**Closed by D3nnis3n** 2021-08-31 09:49 UTC
Labels: Category: Gameplay
