### ISSUE TITLE
Beta Staging 3-23-18 - Waypoint marker flicker

### ISSUE THREAD

**Issue by bruteman** [StrangeLoopGames/EcoIssues#6428] opened 2018-03-24 02:14 UTC
3 players including myself all have this issue set a waypoint and if you move you'll get a very rapid flicker of the waypoint all over the screen. 

Video Cards involved : Geforce 980 TI / GTX 1070 and GTX 1080

Turn off distance in the WP and the flicker stops.

**Comment by MarjieAVolk** [comment] 2018-03-30 18:39
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6451 - I think this is already fixed, but I haven't checked

**Closed by MarjieAVolk** 2018-03-30 18:39 UTC
