### ISSUE TITLE
USER ISSUE: Elevator does not go up

### ISSUE THREAD

**Issue by ShoppyCodes** [StrangeLoopGames/EcoIssues#24720] opened 2024-02-01 18:05 UTC
\
**User Id: (slg182316)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
Use Elevator (I was using Industrial). Take it to the bottom. Then press the UP arrow on it to move it up. It only moves up 1-2 blocks worth, or it goes down first, or it disappears entirely and teleports to the top but without the vehicles on it. Seems random. 

**Expected behavior:**
Goes up with the vehicles on it until it reaches the top or it gets manually stopped.

**Actual behavior:**
It goes up 1 inch and then stops, or it goes down instead of up. Or it disappears when mining near it and teleports to the top without the vehicles.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't think so.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14129186/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14129187/Player-prev.log)

**Comment by ShoppyCodes** [comment] 2024-02-01 18:08
Sounds like the same issue as #18809

**Comment by D3nnis3n** [comment] 2024-02-02 00:44
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23983

**Closed by D3nnis3n** 2024-02-02 00:44 UTC
