### ISSUE TITLE
Crafting Tables don´t work in claimed Room (8x8x5)

### ISSUE THREAD

**Issue by FlamBeon** [StrangeLoopGames/EcoIssues#5787] opened 2018-03-09 18:28 UTC
I have build an Room after i see that my working process on carpentry table is not running. First Carpentry Table is blocked out, because of working progress and to small Carrying Inventory. So i build a second Carpentry Table to place it in room and build some Doors, because Masonary Table is not working too in Room. At Status there simular standing "Room required"

**Comment by YukiiiDE** [comment] 2018-03-09 19:00
Maybe tue Room is to small for both of them. Ever single table need 25qm place.

**Comment by FlamBeon** [comment] 2018-03-09 20:33
I only try one in this room

**Comment by MarjieAVolk** [comment] 2018-03-09 20:58
Can you show a screenshot of the "Status" tab for the new table?

**Comment by FlamBeon** [comment] 2018-03-09 22:40
![20180309233734_1](https://user-images.githubusercontent.com/37195187/37233370-2e773402-23f3-11e8-8d7b-8fe0d90ab872.jpg)
![20180309233742_1](https://user-images.githubusercontent.com/37195187/37233371-2e985326-23f3-11e8-9b80-81da6a8f1415.jpg)
![20180309233748_1](https://user-images.githubusercontent.com/37195187/37233372-2eb3da56-23f3-11e8-8b68-3f1f485f1ebb.jpg)

**Comment by MarjieAVolk** [comment] 2018-03-10 00:45
Okay, so it hasn't detected a valid room yet.  From your pictures, it looks like you might have 3-wide windows.  You are only allowed to have size 2 windows.  Is that your problem?

**Comment by YukiiiDE** [comment] 2018-03-10 00:48
Try closing the door up to 1 block wide. Close all Window Gaps up to just 2 block wide

**Comment by MarjieAVolk** [comment] 2018-03-10 00:50
Oh yeah duh, you have 2 wide doorways too :P  Thanks @YukiiiDE

**Comment by MarjieAVolk** [comment] 2018-03-10 00:50
Okay, gonna close this as working as intended.

**Closed by MarjieAVolk** 2018-03-10 00:50 UTC
