### ISSUE TITLE
When starting up game, window switches to desktop and then nothing happens.

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6705] opened 2018-03-29 23:14 UTC
http://steamcommunity.com/profiles/76561198038446128/recommended/382310/

"Startet this game for the first time and every time i press start new world the game switches to my dektop and nothing else happens....?"

**Comment by MarjieAVolk** [comment] 2018-03-29 23:29
This will be the local server crashing.  We can't do anything without crash dumps.  These will be in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'

**Comment by ShaydenMac** [comment] 2018-04-02 22:49
I can't find their review now. They must have deleted it.

**Comment by MarjieAVolk** [comment] 2018-04-02 23:33
Okay, well if we don't have logs then we can't fix the root cause.  What will help this though is better error messaging: https://github.com/StrangeLoopGames/EcoIssues/issues/4956

So closing this, that bug is the current action item for this issue ^

**Closed by MarjieAVolk** 2018-04-02 23:33 UTC
Labels: High Priority, Steam Report
