### ISSUE TITLE
USER ISSUE: stuck

### ISSUE THREAD

**Issue by Area1233** [StrangeLoopGames/EcoIssues#5270] opened 2018-03-01 18:22 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
stand on corner of stockpile and put logs on stockpile

**Expected behavior:**
logs on stockpile

**Actual behavior:**
stuck on corner of stockpile. reconnect doesn´t help

**Comment by MarjieAVolk** [comment] 2018-03-01 18:24
You will have to use /unstuck to get out.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4113

**Closed by MarjieAVolk** 2018-03-01 18:24 UTC

**Comment by Area1233** [comment] 2018-03-01 18:28
thank you ;D
