### ISSUE TITLE
ClientUpdateException ArgumentNullException 03085500

### ISSUE THREAD

**Issue by ZeskaN** [StrangeLoopGames/EcoIssues#5767] opened 2018-03-09 13:59 UTC
A player on my dedicated server manged to make this error. I have no intel other than the server is 7.2.3 and a fresh install, one day old.

> --BEGIN DUMP--
> Dump Time
> 03/08/2018 22:55:00
> 
> Exception
> System.ArgumentNullException: Value cannot be null.
> Parameter name: item
>    at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
>    at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
>    at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
>    at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
>    at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
>    at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
>    at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
>    at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
>    at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
> 
> --END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-09 20:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Closed by MarjieAVolk** 2018-03-09 20:05 UTC
