### ISSUE TITLE
Stackable chest/inventory blocks do not restack upon collection

### ISSUE THREAD

**Issue by SatsukiShizuka** [StrangeLoopGames/EcoIssues#2407] opened 2017-09-30 02:15 UTC
As title. e.g. Doors, chests etc. when gathered (ie. hammered) go to separate slot every time rather than stacking upon other similar items.

**Comment by metachronism** [comment] 2017-09-30 02:40
dupe of #1945

**Closed by metachronism** 2017-09-30 02:40 UTC
