### ISSUE TITLE
USER ISSUE: No taxation on secondary account

### ISSUE THREAD

**Issue by dterbeest** [StrangeLoopGames/EcoIssues#24893] opened 2024-04-17 08:08 UTC
Since 10.0 we've been facing an issue where taxation from laws only takes from the citizens personal account, even if that account does not have the required funds. It used to be that it would take from the personal account first, and if that failed it would take from any other account the citizen has ownership of.
This change in how taxation works leads to people creating secondary accounts, just to evade the taxes. Tax evasion leads to unhappy citizens, which leads to us having to police tax evasion.

In my test i made the law from a federation, no other settlements or governments exist on the world. The secondary account was made on a bank that is under federation jurisdiction, and the citizen being taxed is a direct citizen of the federation. This was done to create a clean test case. I've seen this issue happen on bigger world as well, but even if a citizen is part of a child settlement, i still expect the federation to have full jurisdiction

Steps to reproduce:

 - Make secondary account - put money in it
 - try to tax more than you have in your personal account
 - no money is taken from secondary account

expected behavior:
 - money is taken from secondary account.
 
 the law that is used:
 
<img width="686" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/8566385/a42a037c-af2c-49ca-8bc1-c0b48fb4756b">

savegame available for download:
[tax_evasion_test.zip](https://github.com/StrangeLoopGames/EcoIssues/files/15007923/tax_evasion_test.zip)

account balance before tax:
<img width="545" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/8566385/3136520d-4aae-46ec-b51c-c33de29d1120">

account balance after tax:
<img width="559" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/8566385/2d3d1d23-a7cf-4a1a-b83d-6e47f8752300">

message on screen when being taxed:
<img width="457" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/8566385/1a75a22d-4954-46fd-b11c-eed7f71255d8">

If you need more information, please ask me before closing this issue! I really believe some things are not working as intended here, or find me on discord: ghosrath

**Comment by dterbeest** [comment] 2024-04-17 12:09
Law:
<img width="278" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/8566385/1e408a34-c340-43f7-a26f-b72d0d8e22a1">

Situation before taxation:
<img width="551" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/8566385/af23a26f-ebc1-47be-b0ea-434fc3402e2f">

Situation after taxation:
<img width="551" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/8566385/af23a26f-ebc1-47be-b0ea-434fc3402e2f">

Message upon taxation:
<img width="340" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/8566385/4ba9ed53-34be-45a6-8dfc-e0c6d86dbbc8">

This situation also seems to ignore the second account, which should not happen in my opinion

**Comment by D3nnis3n** [comment] 2024-04-26 19:03
After internal discussion we have determined that this change was intended beyond my original statement - to also protect players from the same jurisdiction from surprise taxation without any control, and after further discussion have decided to bring the functionality back as an optional feature that must be checked in the law in the taxation options: https://github.com/StrangeLoopGames/Eco/pull/13963

Given the another goal of this was also to noticably reduce complexity in choosing bank accounts, the new refactored option is considered major and will not be released in a Hotfix, but the next Maintenance or Minor Update.

**Closed by D3nnis3n** 2024-04-26 19:03 UTC
Labels: Status: Needs Triage
