### ISSUE TITLE
Skills missing levels and no longer giving benefits they used to.

### ISSUE THREAD

**Issue by NiveusT** [StrangeLoopGames/EcoIssues#11895] opened 2019-04-05 21:29 UTC
Ever since the update, our skills are not listed in the bottom left corner of the screen anymore.
For example, mining level 7 is no longer showing a toolbar on the lower left.

In addition to this, it seems as though it does not register that my mining level is level 7 as well. The calorie use reduction went from 1.7 calories burned per pick use, to 7 calories burned per pick use. As if there was a roll back of my skills and I no longer have level 7 mining.

The other skills, however, work well. (Sweeping Hands works still). The calorie reduction, however, does not work.

**Comment by espoire** [comment] 2019-04-05 21:57
Is 7 the same amount as it would cost for someone without the perk? I had assumed they just decided to massively increase calorie costs across the board.

**Comment by Ser-Geeves** [comment] 2019-04-06 14:55
Like Espoire said, across the board all calorie costs have gone up by a factor of 4.

**Comment by D3nnis3n** [comment] 2019-04-08 19:37
The calorie cost reduction from Self Improvement - which any player had - was removed. Therefore calorie cost has gone up. The skill list issue is already known, you just need to get new XP in the skills to have them show again. I'm closing this as this is intended behaviour. The calorie cost reduction for mining do work, but the general cost reduction is removed, therefore the values are way higher now.

**Closed by D3nnis3n** 2019-04-08 19:37 UTC
