### ISSUE TITLE
USER ISSUE: No menu at game startup

### ISSUE THREAD

**Issue by Chumannn** [StrangeLoopGames/EcoIssues#9726] opened 2018-10-16 02:23 UTC
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Launch game.

**Expected behavior:**
Show start menu

**Actual behavior:**
No menu listings just background with windmills etc. Nothing to click on. If i hit excape i get the settings menu as normal but n
**Do you have mods installed? Does issue happen when no mods are installed?:**
No menu listings just background with windmills etc. Nothing to click on. If i hit excape i get the settings menu as normal but

**Comment by Deantwo** [comment] 2018-10-17 07:50
Duplicate of closed/solved issue: #9345

Should be fixed in the next update.

**Closed** 2018-10-19 00:57 UTC
Labels: Needs Triage
