### ISSUE TITLE
Tags should be set as buyable items

### ISSUE THREAD

**Issue by XerWolf** [StrangeLoopGames/EcoIssues#18658] opened 2020-10-08 23:49 UTC
Vegetables should cover everything under the tag.  I may not care what type of vegetable im buying.  I just need some for a recipe.  It would help lessen the clutter of stores.

**Comment by D3nnis3n** [comment] 2020-10-09 05:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14630

**Closed by D3nnis3n** 2020-10-09 05:23 UTC
