### ISSUE TITLE
USER ISSUE: Mouse stops working using the excavator

### ISSUE THREAD

**Issue by Narone85** [StrangeLoopGames/EcoIssues#6381] opened 2018-03-22 20:50 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Dig with the excavator i.e turn and dig up dirt or something when the fuel runs out. This will make the mouse function for looking around to stop working (tab and using the cursor still works). It will not work again until you rejoin the server.

**Expected behavior:**
Being able to keep looking around when the fuel runs out.

**Actual behavior:**
When the fuel runs out while digging, or at least when turning at the same time it runs out, the mouse stops being able to look around. Tab and using the cursor still works.

**Comment by Narone85** [comment] 2018-03-22 20:55
Sorry, used the in game bug report and did not search first for similar reports. Found that ticket #6281 is similar to my issue so someone can close this ticket, though still not fix i suppose.

**Comment by MarjieAVolk** [comment] 2018-03-23 00:36
No problem, thanks for finding it.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6281

**Closed by MarjieAVolk** 2018-03-23 00:36 UTC
