### ISSUE TITLE
Steel and Modern axe missing from Logging Efficiency and Logging Damage

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4672] opened 2018-02-17 03:18 UTC
as in pics Steel and Modern axe missing from Logging Efficiency and Logging Damage

![image](https://user-images.githubusercontent.com/29722757/36337573-55ee22cc-13ed-11e8-888b-2427924e484f.png)

![image](https://user-images.githubusercontent.com/29722757/36337577-67360720-13ed-11e8-94ee-57c1bedf6dfc.png)

**Comment by ecoemmeck** [comment] 2018-02-18 06:57
odd today the modern axe is listed but steel is still missing

**Comment by MarjieAVolk** [comment] 2018-02-21 00:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4671 - Will note that this is affecting multiple tools.

**Closed by MarjieAVolk** 2018-02-21 00:11 UTC
