### ISSUE TITLE
USER ISSUE: Hotbar icon display bug?

### ISSUE THREAD

**Issue by MagicBackPack** [StrangeLoopGames/EcoIssues#3841] opened 2018-02-04 00:43 UTC
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
when moving items from backpack to hotbar (or vice versa) sometimes the hotbar item doesn't "snap" to the frame it's supposed to fit in and will then not allow use.

**Expected behavior:**
Drag items to or from hotbar/backpack slots with the icons "snapping" to the appropriate hotbar location.

**Actual behavior:**
"missing" the frame of the hotbar causes the icon to "float" over the slot and be rendered unusable.  you also can't "grab" the icon in order to fit it back in.  attached below is a screenshot of the behavior.  relogging into the server fixes the issue and places the icons into the proper hotbar slot and restores functionality, however it's about 25% of the time or more the issue happens whenever moving items.

![20180203194123_1](https://user-images.githubusercontent.com/36118065/35773253-493d349c-091a-11e8-8549-be0dfa6a7fb1.jpg)

**Comment by MarjieAVolk** [comment] 2018-02-04 00:45
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/2955

Sad day, thought it was fixed

**Comment by MagicBackPack** [comment] 2018-02-04 01:01
update, alt tabbing seems to cause the UI to rerender and can be used as a workaround, will test more

**Comment by MagicBackPack** [comment] 2018-02-04 01:02
also wrong button......

**Comment by MagicBackPack** [comment] 2018-02-04 23:53
alt-tabbing rerenders the UI and fixes the issue consistently as a workaround, I've used it numerous times and it works, so if anyone runs into the issue give that a try.

**Comment by MarjieAVolk** [comment] 2018-02-05 02:26
Yeah there is something wrong in our drag and drop script, and we had a thing on it to cancel the drag and drop if the application loses focus, so I would guess that's what is doing that.  So there's still some corner case where the drag and drop gets stuck.... been looking for it for a long time :/

**Comment by MagicBackPack** [comment] 2018-02-11 15:14
not a huge deal, it still happens but I just alt tab out and back in to fix it, probably just put it up on a known issues for folks so they don't beat their heads into a wall with it, I'm windows 10 pro 64 bit if that helps, I can also provide other information if it would help to pin it down at all.

**Comment by MarjieAVolk** [comment] 2018-02-13 03:28
Thank you.  I will ask if I think of anything to ask!  :P  I'm so stuck on this bug I don't even know what to ask :/

**Comment by MarjieAVolk** [comment] 2018-02-13 22:48
"I know this is closed but this exact thing happens to me sometimes in 7.0.5. It seems to happen most often near my own house. When it happens it's like the mouse is being clicked rapidly. You can see it open and close very fast. When you try to drag something it ends up jumping into a slot along the way or getting stuck like in the picture.

It may have something to do with having a project running on the workbench. That's when I notice it most. Order something on the workbench and take that time to arrange inventory."

**Comment by Senlarus** [comment] 2018-02-23 00:41
I can't wait until this is fixed, I've almost bought a new mouse because of this because it's so annoying.

**Comment by Lagicrus** [comment] 2018-02-28 16:54
Also having this issue and like @Senlarus I thought it was because of my mouse
Not sure what to provide in terms of help bar
Windows 10, 64bit, latest released version (as of 28/02/18)

**Comment by Gringar** [comment] 2018-03-18 14:50
I've noticed something else now. This behavior leaks outside of Eco when the game is running if you have it alt tabbed. I hold left click down while Eco is open and instead it's like I'm clicking rapidly. I close Eco and my mouse returns to normal immediately. I also use Windows 10, 64bit. Up to date on updates. My mouse is a Logitech wireless. M705. Battery is 100% and definitely in range. No issue with the mouse since it works fine while Eco is closed but as soon as the Eco service is running... haywire.

I may have found a workaround that seems to be fixing the problem for me so far. That is to run the game in compatibility mode for Windows 7. Steam version you can right click Eco in the Library > Properties. Local Files and Browse Local Files... Then you can right click the Eco file there and set the Compatibility Mode in Properties. Non-Steam version it's probably easier to find the launcher. You shouldn't need help there.

So Eco must not be playing nice with Windows 10 somehow. I hope you can track it down eventually but I've been testing the workaround while writing this and it seems to be working fine where a few minutes ago, without compatibility mode, it was terrible.

**Comment by MarjieAVolk** [comment] 2018-03-23 20:26
Well guys, I really think this is fixed in 7.3.  Never really figured out what the issue is, but I added some extra checks to cancel the drag when you are no longer holding down the cursor, and when the cursor is hidden.  So that should basically fix this.  Fingers crossed.

**Closed by MarjieAVolk** 2018-03-23 20:26 UTC
Labels: High Priority
