### ISSUE TITLE
USER ISSUE: Dialog box gets in the way

### ISSUE THREAD

**Issue by OsageSparky** [StrangeLoopGames/EcoIssues#9290] opened 2018-09-09 18:34 UTC
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
Open stockpile, grab an item, the dialog box gets in the way and wont dissappear on mouse out.

**Expected behavior:**
Dialog box should dissappear when mouse is moved

**Actual behavior:**
Stays open regardless of mouse move, you must select another item away to force dialog to popup elsewhere

**Comment by Senlarus** [comment] 2018-09-10 02:31
Confirmed, this is still an issue. The patch did make it a little better, but it is still very much happening and very much a problem.

**Comment by TheeJudge** [comment] 2018-09-10 10:37
#9276

**Comment by MarjieAVolk** [comment] 2018-09-10 18:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9132

**Closed by MarjieAVolk** 2018-09-10 18:16 UTC
Labels: Investigate
