### ISSUE TITLE
[0.9.0 Staging - 1494] QoL Draggable Store Items

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15531] opened 2020-04-03 19:45 UTC
Rather than having to repeatably click the tiny arrows to rearrange the order of store sales and purchase items being able to click and drag them would be a miracle and a lifesaver for the life time of every players clicky finger during play sessions on Eco.

![20200403144330_1](https://user-images.githubusercontent.com/1329717/78399018-c142c700-75b9-11ea-808b-a43752258a0a.jpg)
![20200403144338_1](https://user-images.githubusercontent.com/1329717/78399021-c1db5d80-75b9-11ea-8010-d5b9597f45ab.jpg)

**Comment by elfl0rd** [comment] 2020-04-04 05:04
Duplicate of #13558

**Closed** 2020-04-04 06:52 UTC
