### ISSUE TITLE
Exception appears in Client about Water Spread Layer

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3373] opened 2018-01-12 23:56 UTC
Exception: The layer "WaterSpread" does not exist.
WorldLayerManager.RequestLayerView (System.String layerName, System.Action`1 ReceiveView) (at Assets/Scripts/Managers/WorldLayerManager.cs:68)
WorldLayerManager.RequestLayer (System.String layerName, System.Action`1 ReceiveLayer) (at Assets/Scripts/Managers/WorldLayerManager.cs:84)
LayerAudio.Init () (at Assets/Art/Audio/Scripts/LayerAudio.cs:33)
LayerAudio.GetLayerAudioData (Vector3 position) (at Assets/Art/Audio/Scripts/LayerAudio.cs:43)
AmbientAudioPlayer.Update () (at Assets/AmbientAudioPlayer.cs:50)

**Comment by knexer** [comment] 2018-01-12 23:57
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/3246

**Closed by knexer** 2018-01-12 23:57 UTC
Labels: Medium Priority
