### ISSUE TITLE
USER ISSUE: tooltip stops stockpile movement

### ISSUE THREAD

**Issue by ResplendentOwl** [StrangeLoopGames/EcoIssues#9276] opened 2018-09-08 18:45 UTC
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
open a stockpile. Drag items from a lower linked stockpile up to the stockpike you have open.

**Expected behavior:**
let me move things efficiently between linked stockpiles

**Actual behavior:**
the stupid tooltip stays visually in my way, but more importantly stops me from using the squares behind it, preventing me from dragging upward

**Comment by Conchipedia** [comment] 2018-09-08 19:26
linking with #9253

**Comment by MarjieAVolk** [comment] 2018-09-10 18:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9132

**Closed by MarjieAVolk** 2018-09-10 18:16 UTC
Labels: Investigate
