### ISSUE TITLE
Objects, players, building does not render properly

### ISSUE THREAD

**Issue by d4nlo3008** [StrangeLoopGames/EcoIssues#1435] opened 2017-05-03 11:33 UTC
When crossing the border 0/0, buildings, players and structures like the woodcart does not render properly and this things disappear. 

We need a soon fix for that because almost everytime you're loosing your needed stuff. Cant work now and losing time because of this bug. 

kind regards,

a players, who loves eco

**Comment by MarjieAVolk** [comment] 2017-05-04 17:56
Closing as a duplicate of StrangeLoopGames/EcoIssues#1429

**Closed by MarjieAVolk** 2017-05-04 17:56 UTC
