### ISSUE TITLE
USER ISSUE: Everything's Dark

### ISSUE THREAD

**Issue by Skelun** [StrangeLoopGames/EcoIssues#5062] opened 2018-02-24 23:45 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
There's a very specific area in my map, where If I pull the small wooden cart over everything becomes dark

**Expected behavior:**
The games goes normal

**Actual behavior:**
Everything becomes black. Only the night sky with the Sun and the moon are visible.

**Comment by MarjieAVolk** [comment] 2018-02-26 22:03
Is this specific area on a 0 coordinate by any chance?

**Comment by MarjieAVolk** [comment] 2018-02-26 22:03
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4370

**Closed by MarjieAVolk** 2018-02-26 22:03 UTC
