### ISSUE TITLE
(6.1.0 #6680a326) - Failed loading plants

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2661] opened 2017-10-31 18:21 UTC
Hello! I just updated to the latest update and launched the server. Launched the server to let it format the world and then to restart it to fix a setting and then this happens every time i try to launch it:

![nononooo](https://user-images.githubusercontent.com/32855684/32241520-aaa1a37a-be70-11e7-9072-4b902216077f.png)

Is this goodbye world save?..

**Comment by MarjieAVolk** [comment] 2017-10-31 18:30
Looks like this is related to https://github.com/StrangeLoopGames/EcoIssues/issues/2270?  Although that one is on server connect, not server startup.

**Comment by ZebZ** [comment] 2017-10-31 18:31
Gona try do as suggested in 2270 :)

**Comment by MarjieAVolk** [comment] 2017-10-31 18:41
So he's suggesting to try the migration again basically?  Yeah let me know if that works, fingers crossed

**Comment by ZebZ** [comment] 2017-10-31 18:53
It worked, perfectly. But i do not dare to restart the server again.. (premade all the settings instead haha)

**Comment by MarjieAVolk** [comment] 2017-10-31 18:56
Haha okay; glad that's working for now.  I'm going to close this as a duplicate of that bug, since it seems to be the same issue.  Feel free to post more information on #2270 if you have any more problems

**Closed by MarjieAVolk** 2017-10-31 18:56 UTC
