### ISSUE TITLE
USER ISSUE: World fails to load

### ISSUE THREAD

**Issue by dimensionwizard** [StrangeLoopGames/EcoIssues#5842] opened 2018-03-10 14:48 UTC
[JonWorld.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1799451/JonWorld.zip)
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Game crashed while I was playing a world and I think the save file corrupted. Game will no longer load. Shows 'connection failed' at startup and only tries to load a short time.

**Expected behavior:**
Loaded the game.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-03-12 22:46
Could you attach any crash files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?

**Comment by MarjieAVolk** [comment] 2018-03-12 22:48
Never mind, I missed that you attached your save file.  I am able to see the error here.

```
Ionic.Zip.ZipException
  HResult=0x80131500
  Message=Could not read Storage\Game.eco as a zip file
  Source=DotNetZip
  StackTrace:
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Eco.Core.Serialization.DataStore.OpenZipFile() in C:\Projects\Eco\Server\Eco.Core\Serialization\DataStore.cs:line 100
   at Eco.Core.Serialization.DataStore..ctor(String name) in C:\Projects\Eco\Server\Eco.Core\Serialization\DataStore.cs:line 90
   at Eco.Core.Plugins.StorageManager..ctor() in C:\Projects\Eco\Server\Eco.Core\Plugins\StorageManager.cs:line 47

Inner Exception 1:
ZipException: Cannot read that as a ZipFile

Inner Exception 2:
BadReadException:   Bad signature (0x00000000) at position  0x0100E80B
```

**Comment by MarjieAVolk** [comment] 2018-03-12 22:49
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4665 - I will attach your save file over there also.  Thanks!

**Closed by MarjieAVolk** 2018-03-12 22:49 UTC

**Comment by MarjieAVolk** [comment] 2018-03-12 22:52
For now, you may be able to restore a backup of your save.  Look in '[...]\steamapps\common\Eco\Eco_Data\Server\Storage\Backup' for the folder with the most recent time stamp.  Copy those files from inside the folder into '[...]\steamapps\common\Eco\Eco_Data\Server\Storage', replacing the files there.

**Comment by dimensionwizard** [comment] 2018-03-13 02:01
Unfortunately the only backup it made was on the first day. Is that also a bug?

**Comment by dimensionwizard** [comment] 2018-03-13 02:16
Filed a new issue report to describe backup behavior: https://github.com/StrangeLoopGames/EcoIssues/issues/5981
