### ISSUE TITLE
USER ISSUE: Unchoppable Log Piece

### ISSUE THREAD

**Issue by xSuzuka** [StrangeLoopGames/EcoIssues#4298] opened 2018-02-11 07:03 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. (Chop) a small piece of a log on the ground	

**Expected behavior:**
Continued chopping into a smaller piece to pick up.

**Actual behavior:**
Instead it crashes the game to the menu. 

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by xSuzuka** [comment] 2018-02-11 07:16
https://www.youtube.com/watch?v=CxDkSDJqEaU&feature=youtu.be

Have a video of what happens also.

**Comment by MarjieAVolk** [comment] 2018-02-12 23:23
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752 . You can track the issue's progress there.

Thanks for the video, that's a big help.  I will post your link over there.  If you have any additional information about when or why this happens, or what kinds of trees it happens on, it would be very helpful if you posted that on the linked bug ^

**Closed by MarjieAVolk** 2018-02-12 23:23 UTC
