### ISSUE TITLE
USER ISSUE: Keep gaining weight

### ISSUE THREAD

**Issue by sage123232** [StrangeLoopGames/EcoIssues#23141] opened 2022-05-02 08:08 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
I play and as my backpack gets heavier and I remove items to a stockpile, the weight doesn't get subtracted from my backpack and it keeps getting heavier and heavier. I can only fix it by completely clearing my inventory, hotbar and then reloading the world.

**Expected behavior:**
Weight be subtracted when items are removed from hotbar/backpack

**Actual behavior:**
Doesn't subtract weight of items when they're removed

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by sage123232** [comment] 2022-05-02 08:20
Here is a video of myself unequipping items and weight not going down. https://youtu.be/vXWbdWnloqE

**Comment by D3nnis3n** [comment] 2022-05-03 19:14
Did you change any settings from the defaults, especially any of the new ones?
Please also attach your server logs: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by sage123232** [comment] 2022-05-05 00:15
[log_220428085817.log](https://github.com/StrangeLoopGames/EcoIssues/files/8628068/log_220428085817.log)

I did change some of the settings. I remember setting the item weight multiplier to 0.2

**Comment by ShadedFlash** [comment] 2022-05-05 22:18
I can confirm this issue. We set the item weight multiplier on our server to 0.01. Items will weigh almost nothing, but when relogging onto the server, the player's max weight will register as 208kg of 35kg max weight and cannot lower this amount by removing items or relogging. Even when inventory is completely empty, weight will remain over max weight and player cannot pick up any new items.

**Comment by ShadedFlash** [comment] 2022-05-05 22:38
It occurs around a server restart and reproducible in these steps and screenshots:

Inventory weight before server restart:
![2](https://user-images.githubusercontent.com/85042649/167036114-930f5c32-6e34-402d-b284-7b2614d481b5.png)
Inventory weight after server restart:
![3](https://user-images.githubusercontent.com/85042649/167036118-a7ceafd6-05a9-4236-993f-9847d3ce960c.png)
Inventory weight after emptying inventory:
![4](https://user-images.githubusercontent.com/85042649/167036121-c2400ca9-0c68-4bbf-9ab1-fb772227cb15.png)

**Comment by DragonFairyGame** [comment] 2022-05-05 22:39
I can also confirm I've experienced this issue

**Comment by Daniel-Magulado** [comment] 2022-05-06 07:12
Hello @sage123232 

Thank you for submitting this bug report. I can confirm that this is an issue when on server restart when changes are made to item weight multiplier.
I've gone ahead and made an internal report.

[QA Ref. 2qn7v91](https://app.clickup.com/t/2qn7v91)

**Comment by ShadedFlash** [comment] 2022-05-14 05:56
I see this bug did not get fixed in 0.9.5.1 patch, any ETA on when we can expect this to be fixed? Our playerbase voted to pause on any new cycles until this bug is fixed due to how detrimental this bug is to our server.

**Comment by D3nnis3n** [comment] 2022-05-19 12:24
Should be fixed.

**Closed by D3nnis3n** 2022-05-19 12:24 UTC
Labels: Type: Bug
