### ISSUE TITLE
USER ISSUE: unsichtbare tische /lager

### ISSUE THREAD

**Issue by Zeusbrayn** [StrangeLoopGames/EcoIssues#23517] opened 2022-11-02 09:09 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
lager/tische unsichtbar kein zugriff aber matteriallien sichtbar 

**Expected behavior:**
wieder sichtbar und zugriff haben 

**Actual behavior:**
willkürlich 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein und nein keine mods 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![Screenshot (2)](https://user-images.githubusercontent.com/117266781/199449495-927ad824-3495-431d-8f42-5173ce1b9d97.png)

**Comment by Zeusbrayn** [comment] 2022-11-02 09:13
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9918776/Player.log)

**Comment by D3nnis3n** [comment] 2022-12-02 21:50
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/22886

**Closed by D3nnis3n** 2022-12-02 21:50 UTC
