### ISSUE TITLE
Make Building great (Art) - Make Ramps Connect to Terrain

### ISSUE THREAD

**Issue by Quadbro** [StrangeLoopGames/EcoIssues#14399] opened 2020-01-15 10:00 UTC
Divided art stuff from this issue https://github.com/StrangeLoopGames/EcoIssues/issues/13956

- [x] Floor blocks should seal up dirt surrounding (connecting it) - this is not the case for ashlar, but for lumber. 
[EDITED] Adding this to ramps is a separate issue with its own problems. They are the perfect nightmare case for the face remover, that is why they have not been made to connect to terrain.I am still hesitant to make them connect until the new face remover solution is more performant. [EDITED] Also add this to ramps. It's enerving.
[EDITED] Not considering this high pri for 9.0, but will consider (I will say that synthetic painted building materials are in my mind for 10.0, and that I definitely want the stone and wood to match the natural stone and wood in the environment): [EDITED]Most of the new blocks were reported by users to be a bit too bright and pale, loosing their color in comparison with stuff in the prior game versions. A bit more color and darkening could help.
[EDITED] Not considering this high pri for 9.0: [EDITED]New Stuff for future patch: 27.5° (2-tile) slant roofs
- [x] This looks very ugly, not the most intelligent merging, and the blocks are clipping in each other:
![notgood](https://user-images.githubusercontent.com/25908592/69913700-8417ce00-143b-11ea-9a77-2472a75440f9.jpg)
![clipping](https://user-images.githubusercontent.com/25908592/69913762-76af1380-143c-11ea-8628-837d53b5f216.jpg)

(There is also no block that could fill the corner more to the left to make a nice looking connection)

**Comment by keegan-o** [comment] 2020-01-23 18:01
Edited original bug with reasons for not completing various sub-tasks for 9.0. The ramps thing may happen still though. So I will keep the bug open for 9.0 most specifically for the ramps connecting to terrain issue.

**Comment by keegan-o** [comment] 2020-01-23 18:02
(The checked issues were fixed in staging)

**Comment by keegan-o** [comment] 2020-05-26 22:29
Pushing the ramps thing to 9.1 because doing it in a simple way would involve risking degrading performance (would mean removing terrain interior faces would be impossible)

**Comment by keegan-o** [comment] 2020-08-07 18:46
This is now a duplicate of the other ramps connecting to terrain issue open for 9.1

**Closed by keegan-o** 2020-08-07 18:46 UTC
Labels: Category: Art, Priority: Low
