### ISSUE TITLE
USER ISSUE: Butchery - Incorrect ingredients amount

### ISSUE THREAD

**Issue by EdoardoNikolov** [StrangeLoopGames/EcoIssues#14809] opened 2020-02-21 18:00 UTC
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Have Butchery Specialty at level 3
2. Select a butchery project at the butchery table (it doesn't matter which is selected, issue persists with deer, wolves, elk,etc). It doesn't matter if the carcasses are present or missing
3. Select 5 for amount
4. Click Start Project

**Expected behavior:**
Due to Butchery Specialty level 3, 60% efficiency, project should require 2 carcasses to complete. (40% of 5 is exactly 2)

**Actual behavior:**
After step #4, the project is started, but it requires 3 carcasses to complete. 

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods at all.

**Comment by SlayksWood** [comment] 2020-03-20 07:52
Thank you for report.
Can't reproduce in 0.9.0 staging-1473.
Could be fixed with #12540

**Closed by SlayksWood** 2020-03-20 07:52 UTC
Labels: Status: Investigate
