### ISSUE TITLE
[7.6.3] Blask furnace exhaust pipe graphical bug

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8828] opened 2018-08-01 23:56 UTC
See video, top of Exhaust of blast furnace is have a graphical error.
https://youtu.be/GZGgblM1XTo

**Comment by GophTheGreat** [comment] 2019-05-30 08:35
I couldn't reproduce this and I even checked all the various shadow settings. Closing for now.

**Closed by GophTheGreat** 2019-05-30 08:35 UTC
Labels: Low Priority
