### ISSUE TITLE
Server Crash, not sure why

### ISSUE THREAD

**Issue by RamboTron** [StrangeLoopGames/EcoIssues#6157] opened 2018-03-16 19:45 UTC
--BEGIN DUMP--
Dump Time
03/16/2018 15:28:05

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   at LiteDB.LockService.Write()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Simulation.WorldLayers.WorldLayerStats.<>c__DisplayClass0_0.<CollectStats>b__0(Species species)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Simulation.WorldLayers.WorldLayerStats.CollectStats()
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by fisele** [comment] 2018-03-16 19:46
#5343

**Comment by MarjieAVolk** [comment] 2018-03-19 20:39
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343

**Closed by MarjieAVolk** 2018-03-19 20:39 UTC
