### ISSUE TITLE
USER ISSUE: Wood Cart disengages when E key is pressed even when E is rebound to another action

### ISSUE THREAD

**Issue by LotheronPrime** [StrangeLoopGames/EcoIssues#4851] opened 2018-02-20 03:41 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Pull Cart using interact Key (My ineract key is W, and E is move forward)
2. Press E to pull cart forward
3. Cart Drops

**Expected behavior:**
Cart should not drop when E key is pressed when rebound 

**Actual behavior:**
Cart drops when E key is pressed when rebound

**Comment by MarjieAVolk** [comment] 2018-02-20 23:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4412

**Closed by MarjieAVolk** 2018-02-20 23:12 UTC
