### ISSUE TITLE
I think we made to many laws and now the server is unplayable.

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#23808] opened 2023-04-28 23:32 UTC
we have lag moving items
we have lag when people log in
we have lag mining
we have lag logging
we have lag opening the court 
we have lag making laws
we have lag ordering
we have lag in the stores

sadly a lot of lag :(

we have a desent dedicated machine for eco: AMD EPYC 7502P with 32 Cores and 128 GB RAM

I hope you can help us maybe make the laws better or give other tips to make it a little bit more playable

Here is the save , https://we.tl/t-20h2Pep2DM

[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/11357848/Dump.zip)
[Logs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/11357851/Logs.zip)

please contact me if you need more information

**Comment by iuriguilherme** [comment] 2023-04-28 23:35
works for me, lag is constant but it's playable

**Comment by Arend90** [comment] 2023-04-28 23:40
just starting it up takes 10 minutes alone for the civics 🗡️

**Comment by Arend90** [comment] 2023-04-29 17:56
![image](https://user-images.githubusercontent.com/31536813/235317167-e4217c32-3b2a-4776-bc76-0578cc0015f3.png)
ram usage is pretty high?

**Comment by Arend90** [comment] 2023-04-30 15:41
![image](https://user-images.githubusercontent.com/31536813/235362362-f36c3ae3-db8a-4bbb-b8f0-dca3dd622158.png)

**Comment by Arend90** [comment] 2023-05-01 10:55
--BEGIN DUMP--
Dump Time
05/01/2023 10:50:05

Exception
Exception: ArgumentException
Message:The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
Source:System.Collections.Concurrent

System.ArgumentException: The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
   at System.Collections.Concurrent.ConcurrentDictionary2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair2[] array, Int32 index)
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
   at Eco.Shared.Utils.DictionaryExtensions.RemoveWhere[TKey,TValue](IDictionary2 dict, Func3 test)
   at Eco.Gameplay.Systems.NewTooltip.TooltipSubscriptions.ClearCacheForUser(User user)
   at Eco.Gameplay.Players.Player.Destroy()
   at Eco.Plugins.Networking.NetworkServer.OnDisconnected(Object connection, DisconnectReason reason)
   at Eco.Networking.ENet.ENetUdpPeer.Service(Int32 timeoutMs)
   at Eco.Plugins.Networking.NetworkServer.Run(CancellationToken token)

--END DUMP--
--BEGIN DUMP--
Dump Time
05/01/2023 10:50:05

Exception
Exception: ArgumentException
Message:The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
Source:System.Collections.Concurrent

System.ArgumentException: The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
   at System.Collections.Concurrent.ConcurrentDictionary2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair2[] array, Int32 index)
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
   at Eco.Shared.Utils.DictionaryExtensions.RemoveWhere[TKey,TValue](IDictionary2 dict, Func3 test)
   at Eco.Gameplay.Systems.NewTooltip.TooltipSubscriptions.ClearCacheForUser(User user)
   at Eco.Gameplay.Players.Player.Destroy()
   at Eco.Plugins.Networking.NetworkServer.OnDisconnected(Object connection, DisconnectReason reason)
   at Eco.Networking.ENet.ENetUdpPeer.Service(Int32 timeoutMs)
   at Eco.Plugins.Networking.NetworkServer.Run(CancellationToken token)

--END DUMP--

**Comment by Arend90** [comment] 2023-05-01 10:55
at Eco.Gameplay.Players.Player.Destroy() 

destroying gameplay it does well

**Comment by D3nnis3n** [comment] 2023-05-01 20:10
Please provide server profilings at the times of such lags, as described here: https://wiki.play.eco/en/Server_Profiling

**Comment by Arend90** [comment] 2023-05-01 21:05
[PerformanceReports.zip](https://github.com/StrangeLoopGames/EcoIssues/files/11368013/PerformanceReports.zip)
made a random one will do one when there is a lot of lag

**Comment by iuriguilherme** [comment] 2023-05-02 19:16
![image](https://user-images.githubusercontent.com/2027447/235763665-8df35a45-0f57-4fa2-ae27-1d36b0659b62.png)

It's way past 20 minutes now

**Comment by D3nnis3n** [comment] 2023-05-02 20:36
We found the cause for slow startup, which is fixed next Update.

For the rest of the report we still need profilings, the one you attached is just performance reports, but we need the dotTrace profilings at time of high lag.

**Comment by iuriguilherme** [comment] 2023-05-04 01:14
Not sure if related, but I had a crash right now: https://pastebin.com/P9uK0EEQ

**Comment by D3nnis3n** [comment] 2023-05-04 11:33
No, all we need is the profilings.

**Comment by iuriguilherme** [comment] 2023-05-04 22:44
Client crashed again while editing districts in a zoning desk: https://pastebin.com/cpQG9nAN

**Comment by D3nnis3n** [comment] 2023-05-22 03:25
Closing this issue as the startup issue has been fixed and no profilings were provided. Feel free to reopen if issues persist and you have the necessary profilings.

**Closed by D3nnis3n** 2023-05-22 03:25 UTC
Labels: Status: Needs Information
