### ISSUE TITLE
USER ISSUE: Crops and Tree Farm Progress

### ISSUE THREAD

**Issue by Sheadyatwork** [StrangeLoopGames/EcoIssues#22546] opened 2021-08-20 21:56 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.0 beta release-237

**Steps to Reproduce:**
1. Hoe ground
2. Place crop or tree
3. Wait some time (a day or two?)
4. Looks like there has been little progress due to size but in-fact they are ready but not graphically showing they are. (Chopping this "tiny" tree actually gives 20 logs.

**Expected behavior:**
Tree / Crop should full grow to represent that they are fully grow.		

**Actual behavior:**
Stays in a tiny status despite being "ready".

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2021-08-22 06:20
Hi @Sheadyatwork 

Thank you for writing this report. If a tree only gives you 20 logs, then it's not at 100% maturity yet. Furthermore, the visual representation of the trees/plants once fully grown will update along with the in-game timer. It may or may not update in front of you visually but it will. If you're playing on an online server, this could be caused by the latency between the client and the server. Relogging in or unloading the area by moving far away from it should fix it.

**Comment by D3nnis3n** [comment] 2022-07-18 09:57
Closing issue due to old age, also seems to not be an issue.

**Closed by D3nnis3n** 2022-07-18 09:57 UTC
Labels: Status: Needs Information
