### ISSUE TITLE
USER ISSUE: Farming (Inventar)

### ISSUE THREAD

**Issue by Black-Foot666** [StrangeLoopGames/EcoIssues#6864] opened 2018-04-01 23:39 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. plat something in farm
2. let the plant die
3. Server relog
4. plant is invisible
4. try to plant something new (doesn´t work)

ps. the game need an button or an bin icon in the iventar to delete easy unused items.

**Expected behavior:**

**Actual behavior:**

**Comment by PermanentEdding** [comment] 2018-04-02 13:33
english only

**Comment by Black-Foot666** [comment] 2018-04-02 13:51
try my best and update it

**Comment by MarjieAVolk** [comment] 2018-04-02 21:42
We can use google translate, if you are more comfortable typing in your native language :)  Of course it will only be google translate quality communication :P

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4669

**Closed by MarjieAVolk** 2018-04-02 21:42 UTC
