### ISSUE TITLE
USER ISSUE: Skill Point Gain Issue

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4233] opened 2018-02-10 07:20 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Setup we have is skill pre craft .0006 skill pre action .0006  base gain 1 rate 1  - anyways it seem be fine for frist few skill points start 9 earned 2 then all of sudden me and my friend notice the blue bar got stuck at full, and it only showed 1 skill point - so i went and spent skill point and it instantly showed me anther 1 to spend so i spent that and then it showed a third one instantly and now the blue bar is still stuck at full and it shows that i have 0 - disconnect reconnect to server did does not help this.  - no error on the server side. and i wanted leave thanks for pottiong the action and crafint gain as option into the servers... its pretty awesome !

**Expected behavior:**

**Actual behavior:**

**Comment by midn8t** [comment] 2018-02-10 07:20
o my friend was having issue with icons when moving things around on inventory getting stuck in middle of the screen. -

**Comment by MarjieAVolk** [comment] 2018-02-13 01:55
This sounds like it might be related to #4182, which is fixed in the current release.  Since I see this bug was filed on an older version, are you still having this issue?

**Comment by MarjieAVolk** [comment] 2018-02-13 04:18
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4311

**Closed by MarjieAVolk** 2018-02-13 04:18 UTC

**Comment by midn8t** [comment] 2018-02-13 06:53
I want say yah but i have been care full not to try doing this.

i could, go and test this tomorrow.. to make sure there is experience gain
