### ISSUE TITLE
[9.2] Rent Experimental Crash

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#20524] opened 2021-02-12 23:09 UTC
> --BEGIN DUMP--
> Dump Time
> 02/12/2021 23:07:15
> 
> Exception
> Exception: NullReferenceException
> Message:Object reference not set to an instance of an object.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Eco.Gameplay.Property.RentForProperty.ValidateAndGetFeeInfo(User user)
>    at Eco.Gameplay.Property.Residency.BecomeResident(User user)
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> 
> --END DUMP--

**Comment by D3nnis3n** [comment] 2021-02-17 02:53
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20404

**Closed by D3nnis3n** 2021-02-17 02:53 UTC
