### ISSUE TITLE
Store authorization settings, changed after server restarts.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9583] opened 2018-09-27 13:38 UTC
"Everyone" receive access to store, creating "VIP" or "Private" stores is impossible.
Happens on release, staging, BE and master.
Before restart
![default](https://user-images.githubusercontent.com/4980243/46149772-b6e09800-c273-11e8-9d1d-2efe0c50dec7.png)

after restart
![default](https://user-images.githubusercontent.com/4980243/46149788-bfd16980-c273-11e8-8103-aa658d1050b9.png)

**Comment by johnkslg** [comment] 2018-09-28 19:27
Check that only people with consumer rights are allowed to access a store.  
/spawneconomy to create a bunch of stores
Then can login as another user (disable auth as described in wiki to login as another user)

**Comment by Spydarlee** [comment] 2018-10-01 16:04
I can't reproduce this exact issue on master, but I do get a similar one. When I restart the server, the user(s) I've added to the auth settings get forgotten but not replaced with 'Everyone'

This only seems to happen if I restart the server quite soon after making the change. If I make the change but then force save + flush to disk the change sticks after a restart.

Is this expected behaviour, @johnkslg? WorldObject.SaveIfDirty() only gets called periodically, I think, so it's possible for changes just prior to a server reboot/crash to be lost?

**Comment by johnkslg** [comment] 2018-10-01 16:42
Yes it's expected that some recent data will get lost.  I would like to address this though too, but we can do that separately. Closing since no repro in master. @elfl0rd if you still see this in master (even if forcing a save in the server with /save) reopen. Thanks!

**Comment by elfl0rd** [comment] 2018-10-01 16:49
This problem occurs too in cases where the restart occurred after a long time, 1-2 days. (Release server)

p.s.
I cannot _reopen_ issues closed by another.

**Comment by elfl0rd** [comment] 2018-10-01 17:50
Ussue still here.
In video i save server 3!!! times.
https://youtu.be/4M7xxu_sZqs

**Comment by johnkslg** [comment] 2018-10-01 17:52
@Spydarlee can you follow up with @elfl0rd (discord GDragon) to repro

**Comment by Spydarlee** [comment] 2018-10-02 15:06
Managed to get a repro - pull request submitted - thanks, both!

**Comment by Spydarlee** [comment] 2018-10-03 12:53
New pull request for staging.

**Closed** 2018-10-08 12:10 UTC
Labels: Fixed, High Priority
