### ISSUE TITLE
[0.9.0.5 br-100] Strange map glitch when editing claim

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18815] opened 2020-10-19 02:12 UTC
So I'm not sure exactly how this happened. I was editing a claim, trying to claim some land next to someone else, and I think I pressed some shortcut and I got this glitch:

![20201017222938_1](https://user-images.githubusercontent.com/964559/96393960-9abf3480-1175-11eb-8669-b1dd603ad5a4.jpg)

The minimap centred itself on the map I was editing and I couldn't open the map back up, close it or do anything other than quit. Not exactly sure how to reproduce it.

**Comment by SlayksWood** [comment] 2020-10-19 06:01
@ThePiachu 
Provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ThePiachu** [comment] 2020-10-22 00:33
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5419319/Player.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5419329/Player.log)

I think these should have it.

Tested it and managed to reproduce it a few times:
- Open map
- Go over to some area you own
- Click on it, edit
- Click "m" to open / close the map and you get this bug

**Comment by IcedForge** [comment] 2020-10-26 14:16
Nice find, producible in [0.9.1.0 staging-1823]

It is not closing the edit window properly causing the HUD to not properly set itself as you can now move around in the world with this map in front of you.
![Screenshot_14.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/cbfd8204-3dc2-46c8-88ca-d62780145d65)

**Comment by gzatravkin** [comment] 2020-10-29 19:38
@IcedForge since it goes 9.2 which contains minimap refactoring can you re-test it with develop build? Maybe already fixed

**Comment by IcedForge** [comment] 2020-11-12 11:56
Can confirm this is still an issue in latest build ( 0.9.2.0 develop-111 )
@gzatravkin

**Comment by SlayksWood** [comment] 2020-12-03 06:44
Still have problem with open minimap. It should close minimap when I press Submit (and save changes) or 'X' (and don't save changes). But now I still have opened minimap:
![image](https://user-images.githubusercontent.com/45708377/100973647-fb4ed900-354b-11eb-90cb-94a89326203e.png)
If you want to have open minimap we need to delete this strip:
![image](https://user-images.githubusercontent.com/45708377/100973695-13265d00-354c-11eb-88cc-07ec029b09a8.png)

**Comment by SlayksWood** [comment] 2020-12-07 11:36
Still an issue:
- [ ] 1. When I press 'X'
![image](https://user-images.githubusercontent.com/45708377/101345389-03827d80-3898-11eb-8a81-6594fec09f71.png)
press 'Yes':
![image](https://user-images.githubusercontent.com/45708377/101345459-19903e00-3898-11eb-88b7-54bb487e83fe.png)

- [ ] 2. Maybe thi is sound problem, or maybe any other UI opening but I have double opening window sound. Step to reproduce:
- have any non-started election:
![image](https://user-images.githubusercontent.com/45708377/101345952-df736c00-3898-11eb-8be9-1d7e46f2b962.png)
- start to draft a new District map, draw something and press submit:
![image](https://user-images.githubusercontent.com/45708377/101345998-f914b380-3898-11eb-8539-b997fef56534.png)
- you will have double sound:
https://drive.google.com/file/d/1r4syPM9qW00ZqX8CioMfOdfq57cefQ3_/view?usp=sharing

**Comment by gzatravkin** [comment] 2020-12-10 00:26
Maybe the problem with sound is because of double-closing MinimapEditor: 
First, at MinimapEditor.cs it does: 
            this.submitButton.onClick.AddListener(()=> { SentMap(); CloseUI(); MinimapUI.obj.GetComponent<MinimapModeBehaviour>().SetMinimizedMode(); });

And in SetMinimizedMode: 
        if (previousMode == MinimapMode.Editor)
            Assets.UI.Scripts.Minimap.MapEditor.MinimapEditor.obj.CloseUI();
.

For close problem:
Escape does only: 
                Popup.Confirm(Localizer.DoStr("Are you sure to exit from map without saving?"), CloseUI);
CloseUI don't changes mode of map, just hides editor things. You can set minimapMode, as it done at submit button

**Closed** 2020-12-14 11:55 UTC
Labels: Category: UI, Priority: Medium, Status: Fixed
