### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by yummycandy** [StrangeLoopGames/EcoIssues#6328] opened 2018-03-21 02:08 UTC
**Version:** 0.7.3.0 beta staging-eb6e4ece

**Steps to Reproduce:**
Repaired a stone axe

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on ToolbarInventory!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei Eco.Gameplay.Items.DurabilityItem.RepairCost(User user)
   bei Eco.Gameplay.Components.RepairComponent.NeededStack(User user)
   bei Eco.Gameplay.Components.RepairComponent.RepairSlotChanged(User user)
   bei Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   bei Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-21 18:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6252

**Closed by MarjieAVolk** 2018-03-21 18:32 UTC
