### ISSUE TITLE
USER ISSUE: Town foundation isn't center of influence area for new town

### ISSUE THREAD

**Issue by TheEvilGreebo** [StrangeLoopGames/EcoIssues#24609] opened 2024-01-15 20:56 UTC
\
**User Id: (slg233066)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
This one is weird - my players set up a town (Commune) and the influence radius is located far to its west deep in the jungle.  

I can't tell you how to reproduce it - they say they tried everything including completely dissolving and recreating the town, several times, and the influence circle continues to be in the wrong place.  I'm attaching the save game to this issue

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TheEvilGreebo** [comment] 2024-01-15 21:01
Here are the game files.

[Game.db.zip](https://github.com/StrangeLoopGames/EcoIssues/files/13942992/Game.db.zip)

**Comment by D3nnis3n** [comment] 2024-01-15 21:37
That's already fixed in playtest, the cause is the foundation deed being along the 0 border and the influence not wrapping correctly.

**Closed by D3nnis3n** 2024-01-15 21:37 UTC
