### ISSUE TITLE
USER ISSUE: Crash after rejoin, after unexpected logout

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#6468] opened 2018-03-25 00:23 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Occures only one time

**Expected behavior:**
Join and stay in game.

**Actual behavior:**
The following error message popped up:
Caught exception:

<size=60,00%>Der Wert darf nicht NULL sein.
Parametername: item

Stack:
   bei System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   bei System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   bei Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   bei Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   bei Eco.Mods.TechTree.StockpileObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   bei Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-26 20:39
Fixed in 7.3

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Closed by MarjieAVolk** 2018-03-26 20:39 UTC
