### ISSUE TITLE
USER ISSUE: Mortared Stone project not removed when finished

### ISSUE THREAD

**Issue by CiberX15** [StrangeLoopGames/EcoIssues#6250] opened 2018-03-18 19:18 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Begin a project for several mortared stone (60)
2. Ensure project has enough resources and storage
3. Wait for project to finish
4. Observe project finishes, and is stored in available stockpile but project is not removed from queue.

**Expected behavior:**
When a project has finished and there are no items to claim from the project, it should be removed from the queue.

**Actual behavior:**
When the project is completed, it remains in the queue untill the player manually cancles it.

**Comment by gabgab01** [comment] 2018-03-18 19:42
another user here: happens to me too. sometimes, when i cancel it, it drops a few stones into the stockpile too.

**Comment by MarjieAVolk** [comment] 2018-03-20 23:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3240

This should be fixed in 7.3

**Closed by MarjieAVolk** 2018-03-20 23:40 UTC
