### ISSUE TITLE
Server crash trying to open workbench

### ISSUE THREAD

**Issue by Freebios** [StrangeLoopGames/EcoIssues#4375] opened 2018-02-12 04:42 UTC
**Version**: 0.7.1.0 beta

**Steps to Reproduce**:
Randomly happen when I open the workbench

**Crash NullReferenceException 02123210**:
```--BEGIN DUMP--
Dump Time
02/12/2018 05:32:10

Exception
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   à System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   à System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   à Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   à Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   à Eco.Core.Controller.ControllerManager.Run()
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
```

**ClientNetworkException Exception 02123205**
```--BEGIN DUMP--
Dump Time
02/12/2018 05:32:05

Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   à Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   à Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   à Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   à Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   à Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   à Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   à Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   à Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   à Eco.Shared.Networking.NetPort.ProcessBuffer()
   à Eco.Shared.Networking.NetPort.Update()
   à Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()

--END DUMP--
```

**Comment by MarjieAVolk** [comment] 2018-02-13 01:47
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368 - You can track the issue progress there

**Closed by MarjieAVolk** 2018-02-13 01:47 UTC
Labels: High Priority
