### ISSUE TITLE
9.3.0 1928 Invalid Section "Title requirement" in a law after migrating

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20509] opened 2021-02-12 14:12 UTC
After migrating to 9.3.0 1928 from 9.2.4 a law that has been live for a while is showing as invalid sections

Title and registry is still valid,  the exact same title is used in section 2 which it has no issues with, doing NOT demographic or other things is fine its just title requirements it does not play nice with for any title, may be related to https://github.com/StrangeLoopGames/EcoIssues/issues/20456

Other laws with if not title are fine.

![image](https://user-images.githubusercontent.com/61889138/107778196-b01b2880-6d3b-11eb-9e06-d93f9c79f34a.png)

![image](https://user-images.githubusercontent.com/61889138/107778283-cd4ff700-6d3b-11eb-9cd6-9e206caeab7c.png)

It keeps going valid then invalid

![image](https://user-images.githubusercontent.com/61889138/107779411-36843a00-6d3d-11eb-8db5-d4aed2c1c3e2.png)

**Comment by IcedForge** [comment] 2021-03-01 08:02
Looks like a problem with migration not populating the backup owner of titles which is a new feature on them to allow land owned by this title to not get lost when deleting a title that owns property.

On migration,
All titles should be populated with "Everyone" ?

**Comment by Daniel-Magulado** [comment] 2022-05-11 20:13
Tested on 0.9.4.6 Release-285 migrated world to 0.9.5.1 Release-310. Wasn't able to reproduce this issue despite copying 99% of it. 
 Closing for now.
 Also Tested migration from 0.9.4.6 Release-285 to 0.9.5.1 Staging-2298. Was not able to reproduce.
 
![image](https://user-images.githubusercontent.com/77248866/167937260-0acc6182-9b77-48b3-bacd-c469393e18d3.png)

**Closed by Daniel-Magulado** 2022-05-11 20:13 UTC
Labels: Priority: Low, Category: Laws, Type: Bug, Squad: Mountain Goat
