### ISSUE TITLE
Cannot launch server

### ISSUE THREAD

**Issue by Frisasky** [StrangeLoopGames/EcoIssues#13305] opened 2019-10-10 16:26 UTC
Hi, i just installed an Eco server on my linux machine, the eco process crashed after just few second, i got following error message with full log in attachment. hoping this could pinpoint whats going wrong in my server

System: Centos 8
Mono version: 6.4.0 Stable

> [23:52:12.997] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[23:52:13.023] [1] [ Info] [Eco] Eco Server 0.8.3.0 beta
[23:52:13.196] [1] [ Info] [Eco] Server Initialization...  
[23:52:13.198] [1] [ Info] [Eco] Starting LocalizationPlugin...  
[23:52:14.007] [1] [ Info] [Eco] Starting ModKitPlugin...  
[23:52:14.009] [1] [ Info] [Eco] Loading mods...  
[23:52:14.128] [1] [ Info] [Eco] Compiling mods...  
[23:52:18.382] [1] [ Info] [Eco] Mods recompiled with errors.

[log_191010115212.log](https://github.com/StrangeLoopGames/EcoIssues/files/3713593/log_191010115212.log)

**Comment by mirasrael** [comment] 2019-10-14 13:17
Seems Mono 6.4 has System.Range in Core lib which conflicts with own Range implementation.
Last tested Mono version is 5.14. So you can either use it or start server from Docker image.

**Comment by redwyre** [comment] 2019-10-15 18:48
You can see known-good versions at https://github.com/StrangeLoopGames/EcoIssues/wiki/EcoServer-on-Linux

**Comment by redwyre** [comment] 2019-10-24 20:38
Closing this issue as it's caused by a third party tool. If you can revert the changes then use ./install.sh and still have problems, create a new issue.

**Closed by redwyre** 2019-10-24 20:38 UTC
