### ISSUE TITLE
[8.0.0 Steam Beta] Weight is broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10373] opened 2018-12-19 17:06 UTC
See the screenshot, i'm carrying a minus value:
<img width="1237" alt="weight" src="https://user-images.githubusercontent.com/25908592/50235717-d857a880-03b8-11e9-86a6-1cf4c650b3d8.png">

**Comment by mirasrael** [comment] 2019-01-09 04:21
Wasn't able to reproduce on latest master. Either needs steps to reproduce (may be a save file with a problem) or it was already fixed.

**Comment by redwyre** [comment] 2019-02-02 16:00
See https://github.com/StrangeLoopGames/EcoIssues/issues/11040 a log file

**Comment by mirasrael** [comment] 2019-02-04 08:07
@D3nnis3n @redwyre can somebody provide repro case? I'm not able to reproduce it on release branch.
@redwyre I checked your log and nothing seems related to this issue, but I improved logging and added some code to reduce number of exceptions, so they won't hide real exceptions.

**Comment by mirasrael** [comment] 2019-02-04 10:51
Reproduced. Only happens in release mode.

**Comment by redwyre** [comment] 2019-02-04 13:07
What's the repro? My guess would be trying to add stacks that take up more than you can carry (I tried taking stacks of fish that were too heavy to take all at once before it happened)

**Comment by metachronism** [comment] 2019-02-04 19:57
weight-specific fix should be isolated and checked in to release

**Closed** 2019-02-05 19:41 UTC
Labels: Fixed, High Priority
