### ISSUE TITLE
Mint doesnt appear on minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2087] opened 2017-09-11 19:00 UTC
Probably needs to be brought into the tech tree like stores were?

**Comment by johnkslg** [comment] 2017-09-11 19:00
Check other objs while youre at it?

**Comment by craig-jong** [comment] 2017-09-11 19:05
Yea, this is a dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/2080 mostly.

Should be fixed on next PR.

**Closed by craig-jong** 2017-09-11 19:05 UTC
