### ISSUE TITLE
USER ISSUE: Cant join Lan Multiplayer

### ISSUE THREAD

**Issue by Ellicool** [StrangeLoopGames/EcoIssues#4131] opened 2018-02-08 20:31 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
it shows i can join but i can't join or he/she join me i really wanna play this game coop but plz fix this as soon as you can plz

i dont know if it's only maybe because i am live in iceland but im not sure
**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-02-09 02:24
Since you are playing on LAN, you might try disabling NAT on your server.  Sometimes this seems to break local connections.  You can do this in your server window, by going to Network tab > Config tab > DetectNAT setting

**Comment by MarjieAVolk** [comment] 2018-02-09 20:06
Sorry, I realized that the server window has been disabled for local servers, so you can't do this.  What you can try though is to select 'Join' and add a server 'localhost:3001'.  Hopefully you will be able to connect to that.  We are working on a better fix for this.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4056

**Closed by MarjieAVolk** 2018-02-09 20:06 UTC
