### ISSUE TITLE
[Art] Currency Exchange Object no placing model 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3346] opened 2018-01-10 16:13 UTC
When placing the Currency Exchange no model or shape visible as a guide to placement, but when placed (can rotate invisibly) does show as a real world object which can be interacted with.
Not sure how exactly this thing works (but have placed it anyway just in case i find out)

**Comment by MarjieAVolk** [comment] 2018-01-10 18:52
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2830

**Closed by MarjieAVolk** 2018-01-10 18:52 UTC
