### ISSUE TITLE
USER ISSUE: Iron Hammer is invisble in hand

### ISSUE THREAD

**Issue by Kazefune** [StrangeLoopGames/EcoIssues#3812] opened 2018-02-03 02:23 UTC
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Get Iron Hammer and equip it

**Expected behavior:**
See the Iron Hammer in your hand

**Actual behavior:**
Can't see the Iron Hammer in your hand

**Comment by MarjieAVolk** [comment] 2018-02-03 22:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2478

**Closed by MarjieAVolk** 2018-02-03 22:23 UTC
