### ISSUE TITLE
USER ISSUE: sound not working

### ISSUE THREAD

**Issue by BRAVOBANANA** [StrangeLoopGames/EcoIssues#24736] opened 2024-02-04 11:45 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
im using the steam truckter and theres just no sounds only animal and some others

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14156582/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14156583/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-02-05 02:28
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24410

**Closed by D3nnis3n** 2024-02-05 02:28 UTC
