### ISSUE TITLE
USER ISSUE: Stump is invisible I think.

### ISSUE THREAD

**Issue by BizKwikTwist** [StrangeLoopGames/EcoIssues#7346] opened 2018-04-23 02:32 UTC
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
I chopped at a stump and it is gone but it seems like it still has collison.

**Expected behavior:**
It should have completely disappeared.

**Actual behavior:**
It still has collision and shows that I can chop at it, yet it is gone.

**Comment by Hagigamer** [comment] 2018-04-23 14:29
I had the same issue with several stockpiles yesterday. emptied and then removed stockpile, but collision hitbox was still there. restarting the client fixed it for me, but it kept re-appearing with new stockpiles.

**Comment by Nanders** [comment] 2018-06-18 22:04
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4908

**Closed by Nanders** 2018-06-18 22:04 UTC
Labels: Medium Priority
