### ISSUE TITLE
UserManager.OnlineUsers Reporting Offline Users

### ISSUE THREAD

**Issue by Spoffy** [StrangeLoopGames/EcoIssues#6706] opened 2018-03-29 23:15 UTC
UserManager.OnlineUsers seems to give out a list of every user that's logged on since the last server restart, as opposed to users currently logged in.

**Comment by MarjieAVolk** [comment] 2018-03-29 23:27
Thanks for finding the cause!  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6672

**Closed by MarjieAVolk** 2018-03-29 23:27 UTC
Labels: Medium Priority
