### ISSUE TITLE
Cost of chopping a log and chopping a wood pulp

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoIssues#12003] opened 2019-04-13 03:18 UTC
Version: 0.8.1.2 beta

Problem: Calories cost to chop wood

Steps to reproduce: To chop a tree log and to chop a wood pulp. After that, to compare calorie costs

Current calorie cost to chop a **log** with an Iron Axe is **15.3** (using working boots)
Current calorie cost to chop a **Wood Pulp** is **45.9**

Considering wood pulp is softwr than the tree log, shouldn't the wood pulp be much lower?

**Comment by trevelmike** [comment] 2019-04-17 16:52
yeah this balance issue was made during the expansion of our max calories and i brought it up. But there are far more balance issues than this.

**Comment by SlayksWood** [comment] 2019-05-13 13:20
May be merged with # 11093.
Before these changes, calories were consumed less. Perhaps it's intended behavior.

**Comment by Nicolausi113** [comment] 2019-08-09 04:42
still persists for v0.8.2.9
Calorie consumption for logging is 10, for gathering pulp is 30 (iron axe)
![pulp2](https://user-images.githubusercontent.com/38510829/62754586-bc506680-ba70-11e9-988b-ef5879ecdf5d.jpg)

**Comment by WeaselDog** [comment] 2019-12-26 01:52
Moving the Logging talent "Cleanup Crew" to Level 3 instead of Level 6 would help a lot in the short term. Cleaning up Wood Pulp is what makes Logging a viable specialization right now. This is especially true for tree farms.

I like to think it of as anyone can cut a tree easily, but it takes a specialized logger to cut trees in an environmentally friendly way.

**Comment by SlayksWood** [comment] 2020-01-07 10:36
merged to #13148

**Closed by SlayksWood** 2020-01-07 10:36 UTC
Labels: Balance
