### ISSUE TITLE
USER ISSUE: plant

### ISSUE THREAD

**Issue by LuZiferdk** [StrangeLoopGames/EcoIssues#6868] opened 2018-04-02 00:38 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
(plant already existet there)
on the ground a plodet pise off land i see bot no plant in it eving if i use a showel and remove the land and replayes it and re-plowe it is still say's (plant already existet there)
the same somtimes happen whit tree's bot this 1 is Corn

**Expected behavior:**

**Actual behavior:**

**Comment by LuZiferdk** [comment] 2018-04-02 01:00
![skaermbillede 2018-04-02 02 33 49](https://user-images.githubusercontent.com/37664204/38179073-1c17efb6-361f-11e8-9cd3-f63ec0ee1589.png)

**Comment by LuZiferdk** [comment] 2018-04-02 03:01
ok i have just trye this removing the dirt replaysing the dirt whit sand re-logging replaysing the sand whit dirt again and try to repland no go i can remove the dirt and i can plays items on top off it not i cant not plant items

**Comment by MarjieAVolk** [comment] 2018-04-02 22:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4669

**Closed by MarjieAVolk** 2018-04-02 22:25 UTC
