### ISSUE TITLE
USER ISSUE: relogin crash

### ISSUE THREAD

**Issue by tiger-uppercut** [StrangeLoopGames/EcoIssues#5847] opened 2018-03-10 16:04 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
log out, log in again

**Expected behavior:**
logged in

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Der Wert darf nicht NULL sein.
Parametername: item


Stack:
   bei System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   bei Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   bei Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   bei Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by arvalaan** [comment] 2018-03-10 17:05
Also happens on my server.

```
[06:45] Disconnecting client [reason: Caught exception:

<size=60.00%>Specified argument was out of the range of valid values.
Parameter name: arrayIndex


Stack:
  at System.Collections.Immutable.Requires.FailRange (System.String parameterName, System.String message) [0x00008] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0
  at System.Collections.Immutable.Requires.Range (System.Boolean condition, System.String parameterName, System.String message) [0x00003] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0
  at System.Collections.Immutable.ImmutableList`1[T].CopyTo (T[] array, System.Int32 arrayIndex) [0x00027] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0
  at Eco.Core.Utils.ThreadSafeList`1[T].CopyTo (T[] array, System.Int32 arrayIndex) [0x00000] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0
  at System.Collections.Generic.List`1[T].InsertRange (System.Int32 index, System.Collections.Generic.IEnumerable`1[T] collection) [0x000aa] in <2e7c1c96edae44d496118948ca617c11>:0
  at System.Collections.Generic.List`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] collection) [0x00000] in <2e7c1c96edae44d496118948ca617c11>:0
  at Eco.Plugins.Networking.QuadTreeNode`1[T].AddSubTreeContents (System.Collections.Generic.List`1[T] collection) [0x0000e] in <cb46936a53a64832a4f16709d80dbff3>:0
  at Eco.Plugins.Networking.QuadTreeNode`1[T].AddSubTreeContents (System.Collections.Generic.List`1[T] collection) [0x0002f] in <cb46936a53a64832a4f16709d80dbff3>:0
  at Eco.Plugins.Networking.QuadTreeNode`1[T].AddSubTreeContents (System.Collections.Generic.List`1[T] collection) [0x0002f] in <cb46936a53a64832a4f16709d80dbff3>:0
  at Eco.Plugins.Networking.QuadTreeNode`1[T].Query (Eco.Shared.Math.Rect queryArea, System.Collections.Generic.List`1[T] results, System.Boolean rootNode) [0x0019d] in <cb46936a53a64832a4f16709d80dbff3>:0
  at Eco.Plugins.Networking.QuadTreeNode`1[T].Query (Eco.Shared.Math.Rect queryArea, System.Collections.Generic.List`1[T] results, System.Boolean rootNode) [0x001bb] in <cb46936a53a64832a4f16709d80dbff3>:0
  at Eco.Plugins.Networking.QuadTreeNode`1[T].Query (Eco.Shared.Math.Rect queryArea, System.Collections.Generic.List`1[T] results, System.Boolean rootNode) [0x001bb] in <cb46936a53a64832a4f16709d80dbff3>:0
  at Eco.Plugins.Networking.QuadTreeNode`1[T].Query (Eco.Shared.Math.Rect queryArea, System.Collections.Generic.List`1[T] results, System.Boolean rootNode) [0x00181] in <cb46936a53a64832a4f16709d80dbff3>:0
  at Eco.Plugins.Networking.QuadTree`1[T].Query (Eco.Shared.Math.Rect area) [0x00006] in <cb46936a53a64832a4f16709d80dbff3>:0
  at Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects (Eco.Shared.Networking.INetObjectViewer viewer, System.Collections.Generic.ICollection`1[T] alreadyRelevant) [0x00081] in <cb46936a53a64832a4f16709d80dbff3>:0
  at Eco.Shared.Networking.NetObjectManager.GetRelevantObjects (Eco.Shared.Networking.INetObjectViewer viewer, System.Collections.Generic.ICollection`1[T] alreadyRelevant) [0x00005] in <87b449fa3be548e4a9bca65d2ad34821>:0
  at Eco.Plugins.Networking.Clients.Client.Update (System.Diagnostics.Stopwatch timer) [0x0007d] in <cb46936a53a64832a4f16709d80dbff3>:0
  at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1 () [0x00012] in <cb46936a53a64832a4f16709d80dbff3>:0
</size>]...
```

**Comment by MarjieAVolk** [comment] 2018-03-12 19:34
This is probably related to a specific object (eg. a crafting station or cart, not a block) that you were close to when you logged in.  Might also happen when walking near to this object.

@arvalaan duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5527

**Comment by MarjieAVolk** [comment] 2018-03-19 22:14
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Closed by MarjieAVolk** 2018-03-19 22:14 UTC
Labels: High Priority
