### ISSUE TITLE
USER ISSUE: I Am Flying

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#5245] opened 2018-02-28 21:21 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Drive A Cart
2. Get It Stuck
3. Type /unstuck
4. Hold on tight and enjoy the ride

**Expected behavior:**
Go a few feet to the closest road or flat space it can be driven on

**Actual behavior:**
Flys away with you on it sometimes halfway across the world

**Comment by MarjieAVolk** [comment] 2018-02-28 22:00
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4655

**Closed by MarjieAVolk** 2018-02-28 22:00 UTC
