### ISSUE TITLE
Provide togglable control option to return legacy tool action on Mouse Button 0

### ISSUE THREAD

**Issue by brendonofficial** [StrangeLoopGames/EcoIssues#22597] opened 2021-08-27 14:19 UTC
Prior to 9.4, using tools was a breeze with Mouse Button 0 - you could just hold it down and continue to perform the desired tool action.

However, since the 9.4 update, it seems the expectation now is to click on every action you wish to perform with a tool. This makes holding down Mouse Button 0 a nightmare, as you'll frequently encounter an additional unexpected action, and the tools feel more uncontrollable.

It would be nice to have an option under Controls where the legacy function of Mouse Button 0 for tools could be restored, or an option that would, when Mouse Button 0 is released, stop/cancel a current tool action (if Mouse Button 0 was held down).

**Comment by D3nnis3n** [comment] 2021-08-29 10:57
Thank you for the report, as this is working as intended, I'm closing this issue.
We are revisiting the whole behaviour for 9.5 and make changes as necessary, an internal issue is already created for that.

**Closed by D3nnis3n** 2021-08-29 10:57 UTC
