### ISSUE TITLE
USER ISSUE: workbench marker, direction and distance

### ISSUE THREAD

**Issue by bryanB1128** [StrangeLoopGames/EcoIssues#6370] opened 2018-03-22 14:04 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
move to position where 'y' on minimap "center" is high value, highest before resetting to 0 is most noticeable (In my case 719, maybe)
not sure if x or z value makes difference, but error occurs while my position is (502,48,34) and workbench (472,54,21)

**Expected behavior:**
marker should show shortest straightline path to workbench

**Actual behavior:**
marker sends me on straight line path around entire planet to reach workbench, seemingly to avoid crossing the 0 line
after stepping over 0 line, markers behaves normally

**Comment by MarjieAVolk** [comment] 2018-03-22 18:02
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5056

This will be fixed in 7.3

**Closed by MarjieAVolk** 2018-03-22 18:02 UTC
