### ISSUE TITLE
USER ISSUE: Bug Hitbox Menu

### ISSUE THREAD

**Issue by Horodyre** [StrangeLoopGames/EcoIssues#5948] opened 2018-03-12 16:30 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Log in the game
2. Play in windows mode
3. being fucked

**Expected behavior:**
When i click somewhere, the hitbox isnt fucked up	

**Actual behavior:**
The hitbox was downer than the selection. ie When i wanted to report the bug i had to place the cursor at 'disconnect' button to actually select 'report a bug'

**Comment by MarjieAVolk** [comment] 2018-03-13 21:14
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4084

**Closed by MarjieAVolk** 2018-03-13 21:14 UTC
