### ISSUE TITLE
USER ISSUE: Campfire Sound Bug

### ISSUE THREAD

**Issue by Kentoron** [StrangeLoopGames/EcoIssues#20200] opened 2021-01-28 09:19 UTC
\
**User Id: (slg189047)**
**Version:** 0.9.2.0 beta release-144

**Steps to Reproduce:**
1.Produce anything at a Campfire
2. Fuel runs out or Production is finished

**Expected behavior:**
Burning Sound stops

**Actual behavior:**
an endless loop of burning sound until I break the campfire and replace it.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and I don't know because I play on a Server but there are only like 1 or 2 mods that have nothing to do with campfires

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2021-01-28 09:25
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20112

Will be hotfixed.

**Closed by D3nnis3n** 2021-01-28 09:25 UTC
