### ISSUE TITLE
USER ISSUE: Map icons do not show up

### ISSUE THREAD

**Issue by GearHz** [StrangeLoopGames/EcoIssues#24884] opened 2024-04-14 18:39 UTC
\
**User Id: (slg233492)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**

1. launch Eco through steam
2. join any game, single or multiplayer

**Expected behavior:**
upon joining game, all map icons such as stations, deeds, vehicles, and others will show up on the world map.

**Actual behavior:**
none of the icons show up. i have tried checking and unchecking every box in the world layers tab, but nothing works. sometimes, leaving, waiting a minute, and rejoining fixes the issue.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and yes.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14971743/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14971744/Player-prev.log)

**Comment by GearHz** [comment] 2024-04-14 18:42
I understand this may be a dupe, but hopefully my log files provide extra info.

**Comment by D3nnis3n** [comment] 2024-04-14 18:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24131. Thanks for the logs!

**Closed by D3nnis3n** 2024-04-14 18:43 UTC
