### ISSUE TITLE
USER ISSUE: went through world

### ISSUE THREAD

**Issue by hunterkepley** [StrangeLoopGames/EcoIssues#24751] opened 2024-02-08 02:20 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
mine while against a rock

**Expected behavior:**
kept me where i was 

**Actual behavior:**
i am stuck

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by hunterkepley** [comment] 2024-02-08 02:20
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/9747105/99d8ca56-8f15-4839-af27-1769b41b3c6f)

**Comment by hunterkepley** [comment] 2024-02-08 02:22
typed this in-game; for more info, i was digging horizontally and right against the rock kinda like how you would do in minecraft. it shot me downwards rather than above the ground like it seems to do normally. i got stuck in the world in a void, and because it only lets you dig at what you can see (i assume because of raycasting) i could not get out. I logged out of the world and am hoping when i sign back on it will spawn me in a normal place

**Comment by D3nnis3n** [comment] 2024-02-08 06:51
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23840

You can use /unstuck to get out of there.

**Closed by D3nnis3n** 2024-02-08 06:51 UTC

**Comment by hunterkepley** [comment] 2024-02-12 13:19
Thanks for the quick response @D3nnis3n much appreciated
