### ISSUE TITLE
Default law bugging server website & other website problems

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#4565] opened 2018-02-15 07:09 UTC
Seems the server website has some problems.

1) with the default law (citizen > 2hours playtime) most parts of the website generate an error on the server that is returned to javascript calls (an internal server error has occured - HTTP 500) even if players have way longer then 2 hours playtime.
Digging a bit into the code (i'm pretty bad at JS) the problem may be that with the currently deactivated server statistics the server is also not tracking the playtime correctly, so when it's trying to apply the law for access to certain parts of the website (office, new law, elections) it's unable to get an integer value to compare it with the law and therefor throws an error
The problem is also that the orange box at the top of the site that appears to be for error feedback doesn't work when the script itself errors, so you only get an empty orange box with no info. (Had to use the JS console to get behind the problem)

2) Deleting that law with admin rights "repairs" most parts of the website. It's then possible to use office, make new laws and elections are working. The only JS script that still throws an error (no idea why) is the link on the left side menu for "run for office" and "propose new law". Those sites are only accessible with the direct link in the game.

3) Making new law: The site seems overall pretty buggy. 
a) Often it's returning an eror that all fields need to be entered although all fields have been entered. Seems that is happening when fields are changed forth and back so it's then still requiring some fields to be entered that are no longer needed / visible.
b) Also there is law type available to recreate a law like the default one where it restricts citizenship to conditions.
c) I didn't manage yet to define districts. Whatever i do it's always returning a javascript error (empty orange box at the top). Maybe only one law at any time can be proposed ?

**Comment by LiaungYip** [comment] 2018-02-17 16:53
I've reproduced parts 1) and 2) of this issue on 7.1.2.

I spent about 2 hours mucking about with this before thinking to search for open issues.

**Comment by alex-sun** [comment] 2018-02-21 18:55
I think this issue is related to #4704

**Comment by MarjieAVolk** [comment] 2018-02-22 21:03
1. Yes you are right that the default law is broken right now because of stats being deactivated.  Stats will be re-enabled in the next release.

2. That's odd - I am not able to reproduce that error.  Was able to run for office and propose a law using the links on the website's left nav bar.  If you could provide more details about the error you saw, that could be useful.

3.
a. I have seen this a bit.  It seems to be related to proposing districts.  It may be related to proposing multiple districts with the same name.  @rainfarmer the districts PR I sent out, which fixes up some duplicate district name things server side, seemed to prevent me from seeing this message.  But it would still be good for you to look into why this was getting shown, to ensure it doesn't happen at all and/or give a better message.
b. Is that a question?  The default law is made using the normal law options, so yes, you can recreate it using the law system, or recreate it with whatever variations you like.  I also hope to add a 'Demographics' feature to laws in the future, which would make it easy to define what a 'Citizen' is for example, and then reference that in other laws.
c. Yes, you are only allowed to have one law proposed at a time.  Once the voting finishes for your current proposal, you can then propose another one.  It may also be that you have two districts with the same name, either in your proposal or on the server.  This has some strange behavior right now, which will be fixed in the next release.

**Comment by Thyriel** [comment] 2018-02-23 06:03
3b) Yes that should have been a question (sorry obviously it wasn't my best english sentence lol).
Can you give me an example of what i need to select to recreate the default law ? I can't find anything in the dropdown lists related to citizenship or playtime

3c) Is this restricted to one proposal per player or one proposal for the whole world ?
Anyway, i think it would be a nice feature to be able to propose multiple laws. Especially in combination with district definitions. For example if i currently want a certain area to have a hunting protection i need to define a district, wait 24 hours, propose a law for that district, wait another 24 hours. That's a very long time between realizing that you need to protect something before it exitincts until you can do something about it.

**Comment by MarjieAVolk** [comment] 2018-02-23 22:08
3b) No worries :)  It should be possible, using mostly the same language as shown in the law.  What you will need to select in the condition dropdown is 'actions' - as in 'if (actions) play actions > 2'.

3c) This is one proposal per person.  However, as you suggested, it is possible to include multiple clauses in one law; on the law proposal screen, click the '+' at the bottom of the 'Clauses' box, and you will add a second one.  So you can also propose districts and define a law in the same law proposal.
![image](https://user-images.githubusercontent.com/23460210/36619151-9b81274e-18a2-11e8-8a7a-663d20af3f93.png)
^

There are some bugs with defining districts though, which currently will prevent you from defining a district and referencing it in the same law, so this may not give you all the benefits you want until that is fixed :'(  (see https://github.com/StrangeLoopGames/EcoIssues/issues/3971 and https://github.com/StrangeLoopGames/EcoIssues/issues/4096)

**Comment by D3nnis3n** [comment] 2018-03-07 15:39
How were you able to remove the Citizenship law? I don't see any admin commands to do this - which file did you edit?

**Comment by MarjieAVolk** [comment] 2018-03-07 23:28
/clearlaws will remove them all.  Or if you want to just delete one, admins will see a 'Delete' button on the law's web page.

**Comment by rainfarmer** [comment] 2018-04-11 23:44
1) fixed
2) fixed
3a) will look into errors when changing laws back and forth
3b) solved
3c) will be addressed from this issue https://github.com/StrangeLoopGames/EcoIssues/issues/3971

**Closed** 2019-01-15 16:58 UTC
Labels: Medium Priority
