### ISSUE TITLE
Not Able To Walk Around With Land Deed Open To Quickly Pull Up Land Stakes

### ISSUE THREAD

**Issue by MeatHex** [StrangeLoopGames/EcoIssues#3109] opened 2017-12-13 01:40 UTC

**Comment by MeatHex** [comment] 2017-12-13 01:54
White Land Stake Makers are also staying up in the world even after reloading game  and unclaiming land.

**Comment by MarjieAVolk** [comment] 2017-12-13 17:57
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3053 (The bug is about the backpack, but deeds closing is discussed in the comments)

**Closed by MarjieAVolk** 2017-12-13 17:57 UTC
