### ISSUE TITLE
USER ISSUE: plant

### ISSUE THREAD

**Issue by angelocheck** [StrangeLoopGames/EcoIssues#5544] opened 2018-03-07 05:45 UTC
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
1.I plant tomatoes, reboot the server, tomatoes grew by 100%.. This occurs after the last update. If you can fix this tell me where.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-03-07 22:43
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4003

**Closed by MarjieAVolk** 2018-03-07 22:43 UTC
