### ISSUE TITLE
USER ISSUE: Cannot connect, even to my own host and play server

### ISSUE THREAD

**Issue by van-dell** [StrangeLoopGames/EcoIssues#19663] opened 2020-12-08 20:59 UTC
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
a)accept steam invitation to play. game opens to main menu.
or
b) go to "your worlds", click on +, enter ip and port, try to connect

**Expected behavior:**
It should connect to the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods. fresh install, have never played.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment] 2020-12-09 08:13
@van-dell Thank your for the report.
Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
We need some additional infornation:
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers and provide log files too?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. Did you meet this issue after updating to the 9.1.8 or you had it before?
7. Do server owner have external IP address and did he use it in config file? Please provide server ip or id to check connection to this server too.

**Comment by van-dell** [comment] 2020-12-09 10:16
0. Unfortunately, did not manage to catch a log file of this instance, but I saved the copyable log in a text editor from a previous instance. Hope that helps.
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5665006/Player-prev.log)
1. A friend gifted the game to me, and we tried
 a. Host and play, invite through steam (both directions, me as host and him as host)
 b. Dedicated server on his machine, invite through steam
 c. Host and play on his machine, manually forwarding ports TCP/UDP 2999-3001 after uPnP apparently did not, connecting with IPv4 ip. This worked in the end (also set my steam status from invisible to online and changed my steam profile to public while problem solving the other methods, but this afaik should not influence the ip method).
2. Yes.
3. Windows 10 firewall, win 10 Antivirus. No 3rd party.
4. Cable, 1Gbit/50Mbit, Dual Stack lite (this is a huge problem for e.g. Terraria)
5. Win 10 build 19041.630
   i5-6600K, Gigabite GTX 970, 16 GB RAM, Samsung 950 NVMe (how specific do I need to be on the parts - is this sufficient or do you need more exact data?)
6. Have never played before, only just got the game. So 9.1.8 only.
7. Unable. One IP was, of course, localhost, the other server ip is changing and the server only runs when we (try to) play, so no luck on that. As said above, connection via IP was what worked in the end. 

I posted this report here mainly because the game gave me the option quite prominently. Will try again as soon as able due to RL constraints. Will update with additional logs if problem persists. Sorry for the inconvenience of not having given a complete report through the report wizard.

**Comment by D3nnis3n** [comment] 2022-07-18 09:42
Closing issue due to old age and bever being reproduced. If a similar issue reappears for you, please feel free to open a new issue.

**Closed by D3nnis3n** 2022-07-18 09:42 UTC
Labels: Status: Investigate, Status: Needs Information
