### ISSUE TITLE
USER ISSUE: Crash While Building

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#5639] opened 2018-03-08 01:20 UTC
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
1. Log into server.
2. Place a hewn log in foundation form.

**Expected behavior:**
It should have placed the block.

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Value cannot be null.
Parameter name: item


Stack:
  at System.Collections.Immutable.ImmutableHashSet`1[T].Contains (T item) [0x00000] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at Eco.Core.Utils.ThreadSafeHashSet`1[T].Contains (T item) [0x00000] in <b3417d5a52d8404ebae31288b6ca256b>:0 
  at Eco.Core.Controller.ControllerInstanceInfo.TryBind (Eco.Shared.Networking.INetClient client) [0x00006] in <b3417d5a52d8404ebae31288b6ca256b>:0 
  at Eco.Core.Controller.ControllerManager.TryBindController (Eco.Core.Controller.IController controller, Eco.Shared.Networking.INetClient boundClient) [0x00054] in <b3417d5a52d8404ebae31288b6ca256b>:0 
  at Eco.Core.Controller.ControllerManager.PackageController (Eco.Core.Controller.IController controller, Eco.Shared.Networking.INetClient boundClient) [0x00000] in <b3417d5a52d8404ebae31288b6ca256b>:0 
  at Eco.Gameplay.Objects.WorldObject.GetBSON (Eco.Gameplay.Interactions.InteractionContext context) [0x000a1] in <7cb8c410dec04fecaf5c7637b8781b05>:0 
  at Eco.Gameplay.Objects.WorldObject.OnActInteract (Eco.Gameplay.Interactions.InteractionContext context) [0x0005e] in <7cb8c410dec04fecaf5c7637b8781b05>:0 
  at Eco.Gameplay.Players.Player+<>c__DisplayClass45_0.<PlayerInteract>b__2 (Eco.Gameplay.Interactions.IInteractable inter) [0x00000] in <7cb8c410dec04fecaf5c7637b8781b05>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions+<>c__DisplayClass0_1`1[T].<ExecuteUntilSuccess>b__1 () [0x00000] in <7cb8c410dec04fecaf5c7637b8781b05>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess (System.Collections.Generic.IEnumerable`1[T] results) [0x00016] in <7cb8c410dec04fecaf5c7637b8781b05>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, System.Func`2[T,TResult] resultFunc) [0x0001f] in <7cb8c410dec04fecaf5c7637b8781b05>:0 
  at Eco.Gameplay.Players.Player.PlayerInteract (Eco.Shared.Items.InteractionInfo info) [0x000df] in <7cb8c410dec04fecaf5c7637b8781b05>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <997dde78663c4b4bbf4a1f2b8d296905>:0 



Stack:
  at Eco.Shared.Networking.RPCManager.TryInvoke (System.Object controller, System.String methodname, Eco.Shared.Serialization.BSONObject bsonArgs, System.Object& result) [0x00060] in <2943b2c650144488afab48a262344f52>:0 
  at Eco.Shared.Networking.RPCManager.InvokeOn (Eco.Shared.Serialization.BSONObject bson, System.Object controller, System.String methodname) [0x00055] in <2943b2c650144488afab48a262344f52>:0 
  at Eco.Shared.Networking.RPCManager.HandleReceiveRPC (Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson) [0x0003d] in <2943b2c650144488afab48a262344f52>:0 
  at Eco.Plugins.Networking.Clients.ClientManager.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00021] in <ddd2d6248ff04513a78405f340fbdc7f>:0 
  at Eco.Shared.Networking.NetObject.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <2943b2c650144488afab48a262344f52>:0 
  at Eco.Shared.Networking.NetPort.ProcessBuffer () [0x00016] in <2943b2c650144488afab48a262344f52>:0 
  at Eco.Shared.Networking.NetPort.Update () [0x0000a] in <2943b2c650144488afab48a262344f52>:0 
  at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0 () [0x00012] in <ddd2d6248ff04513a78405f340fbdc7f>:0 
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-08 22:35
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Closed by MarjieAVolk** 2018-03-08 22:35 UTC
