### ISSUE TITLE
USER ISSUE: baradah705

### ISSUE THREAD

**Issue by baradah705** [StrangeLoopGames/EcoIssues#3988] opened 2018-02-06 19:04 UTC
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
3879

**Expected behavior:**
1111

**Actual behavior:**
The following error message popped up:
```
Could not create save file: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Server/Storage\baradah705.eco already exists
```

**Comment by baradah705** [comment] 2018-02-06 19:04
hi

**Comment by baradah705** [comment] 2018-02-06 19:05
hi

**Comment by baradah705** [comment] 2018-02-06 19:12
lnvadbaebiaohbidboiEHGVIUnvkbiUJVOBIUJVOBAH[OIVJ OBOIVIUFHBHGIBGIOIJIhhvhvhvhhbhbn

**Comment by Nanders** [comment] 2018-02-06 19:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3984

**Closed by Nanders** 2018-02-06 19:23 UTC
