### ISSUE TITLE
USER ISSUE: Ramps

### ISSUE THREAD

**Issue by Kemboo** [StrangeLoopGames/EcoIssues#4332] opened 2018-02-11 16:01 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. when i put out my ramp the top of the ramp and the block dont connect, so pls fix that

**Expected behavior:**

**Actual behavior:**

**Comment by ecoemmeck** [comment] 2018-02-11 17:03
I'm assuming your talking about dirt ramps.
If you make a road tool and stamp the bits of it that don't touch the gap will be gone

**Comment by MarjieAVolk** [comment] 2018-02-13 03:17
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1550

As suggested, making the dirt into a dirt road will make them connect.  We are still talking about how better to design this experience.

**Closed by MarjieAVolk** 2018-02-13 03:17 UTC
