### ISSUE TITLE
Single Player Max Slots defaults to 1

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#4072] opened 2018-02-07 23:53 UTC
This prevents people from joining their game.

If the set-up indicates "allow friends to join" this should especially be greater than 1.

**Comment by MarjieAVolk** [comment] 2018-02-07 23:56
'Allow friends to join' sets the value to infinite.  Turning it off sets it to 1.  We can have it checked by default though

**Comment by MarjieAVolk** [comment] 2018-02-07 23:56
Do you think this is why people are having connection problems? O.o  I hope that gives a good error message

**Comment by Nanders** [comment] 2018-02-07 23:59
It was the case with more than one of the people I was supporting

**Comment by Nanders** [comment] 2018-02-07 23:59
This case gives error message "connection failed server is full"

**Comment by MarjieAVolk** [comment] 2018-02-08 00:01
Oh okay, that is good.

**Comment by MarjieAVolk** [comment] 2018-02-13 23:35
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4285

**Closed by MarjieAVolk** 2018-02-13 23:35 UTC
Labels: High Priority
