### ISSUE TITLE
Logging into server issue.

### ISSUE THREAD

**Issue by Siegeofavalo** [StrangeLoopGames/EcoIssues#2466] opened 2017-10-05 04:39 UTC
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1358035/output_log.txt)

I try and log into our Server and I'm no longer able to. In the off chance I do connect I'm soon disconnected. I've tried deleting the C:\Users\Sarumann\AppData\LocalLow\Strange Loop Games folder. I've tried fresh game files. unplugging router/modem. Restarting my pc. Even having the server admin delete my character.

**Comment by Dreconic** [comment] 2017-10-05 04:43
I will add that we see him log in, we see his char standing there and as long as he sits on the "entering World" screen it keeps his char in the game. As soon as he closes out of that it shows him logging off and his char disappears.

**Comment by MarjieAVolk** [comment] 2017-10-05 17:53
Ah actually, this looks like a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2404 - Gonna post your information over there

**Closed by MarjieAVolk** 2017-10-05 17:53 UTC
