### ISSUE TITLE
Item Pictures are blocking the view

### ISSUE THREAD

**Issue by FlamBeon** [StrangeLoopGames/EcoIssues#5986] opened 2018-03-13 06:21 UTC
Since Work there are more and more Pictures Blocking the Inventory and View

![20180313063154_1](https://user-images.githubusercontent.com/37195187/37325675-24f2391a-268f-11e8-96a6-e2c727fd86fb.jpg)
![20180313070621_1](https://user-images.githubusercontent.com/37195187/37325676-2510b886-268f-11e8-9f09-bc24d53b0dfc.jpg)

**Comment by tsabata** [comment] 2018-03-13 14:22
I faced same issue. A picture of item stucked on screen

**Comment by MarjieAVolk** [comment] 2018-03-13 23:06
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841.

This issue seems to be related to certain mice, so switching mice might help you avoid it for now.  Also, minimizing the game and reopening it clears stuck icons, according to other reports.

**Closed by MarjieAVolk** 2018-03-13 23:06 UTC
