### ISSUE TITLE
USER ISSUE: Error while connecting to Server

### ISSUE THREAD

**Issue by Deramour** [StrangeLoopGames/EcoIssues#5562] opened 2018-03-07 09:06 UTC
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
We had 3000ms 
Disconnected from Server
Connected to our server and waited
Error popped up

**Expected behavior:**
Should be connected to our Server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Caught exception:

<size=60,00%>Der Wert darf nicht NULL sein.
Parametername: item


Stack:
   bei System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   bei Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   bei Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Gameplay.Players.Player.SendInitialState(BSONObject obj, INetObjectViewer viewer)
   bei Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-07 20:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Closed by MarjieAVolk** 2018-03-07 20:29 UTC
