### ISSUE TITLE
Plot draw distance glitch

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#7960] opened 2018-06-03 08:36 UTC
It's possible for textures to stop load itself at around 50 claims away from the player, in both SP and MP. Happens on a long enough play session. Not sure why.
![20180603125537_1](https://user-images.githubusercontent.com/18286472/40884747-fe9340f4-6732-11e8-9a12-4e8df997cd57.jpg)
![20180525021223_1](https://user-images.githubusercontent.com/18286472/40884755-0f4812ee-6733-11e8-90c5-35bbe62cd75b.jpg)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2065788/output_log.txt)

**Comment by HetNeSS** [comment] 2018-06-03 11:05
![20180603160509_1](https://user-images.githubusercontent.com/18286472/40885861-f2154902-6747-11e8-86a3-6f7ada7d1e3e.jpg)

**Comment by BlazeGuy2** [comment] 2018-06-04 22:06
How long were your long enough play sessions?  Minutes?  Hours?

**Comment by BlazeGuy2** [comment] 2018-06-04 22:07
Also, what version of Eco are you playing on?

**Comment by metachronism** [comment] 2018-06-18 18:11
closing as dupe of other chunk building issues (not yet fixed)

**Closed by metachronism** 2018-06-18 18:11 UTC
Labels: High Priority
