### ISSUE TITLE
USER ISSUE: Smeltery now says "tailings" instead of "iron bar"

### ISSUE THREAD

**Issue by willcallender** [StrangeLoopGames/EcoIssues#9606] opened 2018-09-29 20:33 UTC
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
Order the iron bar project in the smeltery

**Expected behavior:**
Displayed the iron icon and said "iron bar" when mouse hovers over

**Actual behavior:**
Displays tailings icon and says "tailings project" on mouse hover

**Comment by D3nnis3n** [comment] 2018-09-30 01:12
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/9227

**Closed by D3nnis3n** 2018-09-30 01:12 UTC
