### ISSUE TITLE
USER ISSUE: Motion Blurring

### ISSUE THREAD

**Issue by Solego** [StrangeLoopGames/EcoIssues#23239] opened 2022-06-05 21:23 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
When looking around, there is a distinct motion blur that is distracting and makes precision actions during building take a beat longer than it should to line up changes.  In particular, the motion blur implemented in Eco isn't a smooth blurring of objects as you look around, but an echoing of things as your view pans past, reminiscent of poison/nausea effects in other games.

**Expected behavior:**
There should be a check box to turn Motion Blur on and off in the graphical settings.

**Actual behavior:**
Of the many available settings toggles under Graphics, motion blur is distinctly absent. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.  Difficulty settings tweaked, but no other changes to vanilla gameplay.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-06-09 19:40
Hello Solego,
please send an e-mail to support@strangeloopgames.com with a video of what you are experiencing.

Eco itself does not implement motion blur, hence there is also no setting for it.
You probably mean a different effect that I cannot reproduce and hence would need to see what you mean.
I'm personally generally turning off motion blur in any game, but am failing to see any in Eco as well, so we'd need to see what you are experiencing exactly.

That's a case for support to check out, hence I'm closing this issue (which was intended as a suggestion as well and hence on the wrong tracker).

**Comment by D3nnis3n** [comment] 2022-06-09 19:45
Please also check if your issue could be related to this one: https://github.com/StrangeLoopGames/EcoIssues/issues/23229

**Closed by D3nnis3n** 2022-06-09 19:45 UTC
