### ISSUE TITLE
9.0.5 Disconnect under water for atlantis on main menu

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18852] opened 2020-10-20 14:13 UTC
Disconnect whilst head is underwater in 9.0.5 and you'll see Main Menu atlantis theme, reproducable has happened a few times whilst im trying to find a good worldgen for white tiger

![atlantis](https://user-images.githubusercontent.com/61889138/96598402-bd248f80-12e6-11eb-9111-b4af0481ec5b.JPG)

**Comment by SlayksWood** [comment] 2020-10-21 12:52
Should have this issue.

**Comment by Daniel-Magulado** [comment] 2021-05-22 13:56
Tested on 0.9.4 Staging-1990.

100% reproducible.
Simply disconnect while submerged underwater.

**Comment by MishkaFur** [comment] 2022-04-22 14:42
Even worse in 9.5 :D 

![image](https://user-images.githubusercontent.com/61889138/164737522-e5a4d176-d289-4d84-97fb-97ecfdeae83b.png)

**Comment by legionaw** [comment] 2022-05-04 18:36
> Even worse in 9.5 :D
> 
> ![image](https://user-images.githubusercontent.com/61889138/164737522-e5a4d176-d289-4d84-97fb-97ecfdeae83b.png)

This need to be an option, even if this is unintended, to be honest. This actually looks cool. Please make it happen, after this issue is fixed, of course. lol

**Comment by TwixterZ** [comment] 2022-10-13 06:57
Hi @MishkaFur, Rejoice! this issue is now fixed as of our latest Staging build. Please let us know if you facing this still.

**Closed by TwixterZ** 2022-10-13 06:57 UTC
Labels: Priority: Low, Category: UI
