### ISSUE TITLE
USER ISSUE: Fell through the ground in the ocean

### ISSUE THREAD

**Issue by fureter** [StrangeLoopGames/EcoIssues#4895] opened 2018-02-21 04:39 UTC
![20180220224004_1](https://user-images.githubusercontent.com/22617132/36463357-0550c1f4-168f-11e8-8ddd-403cbd3c6d9e.jpg)

![20180220223911_1](https://user-images.githubusercontent.com/22617132/36463338-f6876bd2-168e-11e8-8f10-8ff4a191f938.jpg)

**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
honesty not sure how this happened, had hammer equiped, jumped into water, started heading back to the surface, think I touched the ground and started falling, am currently at [300,-220000,274] and still accelerating. 

**Expected behavior:**
not fall through ground

**Actual behavior:**
fall through ground

**Comment by MarjieAVolk** [comment] 2018-02-22 23:50
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4574

Thanks for the additional details.

**Closed by MarjieAVolk** 2018-02-22 23:50 UTC
