### ISSUE TITLE
[0.9.2 staging-1869] News is missing in Steam when using Gibberish

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19705] opened 2020-12-11 09:00 UTC
Start staging built in Steam, news is missing:
![image](https://user-images.githubusercontent.com/45708377/101883480-5d40bb80-3ba8-11eb-872d-47a920f00658.png)
```
ArgumentException: JSON parse error: Invalid value.
  at UnityEngine.JsonUtility.FromJson[T] (System.String json) [0x00000] in <00000000000000000000000000000000>:0 
  at News.NewsLoader+<SetNews>d__3.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5678150/Player.log)

**Comment by StallEF** [comment] 2020-12-11 19:15
@SlayksWood I think the problem was from the server side

![steam_news](https://user-images.githubusercontent.com/26339332/101944775-52187a80-3bfe-11eb-800e-60b92a23b2ed.jpg)

**Comment by denysaw** [comment] 2020-12-15 13:33
@gzatravkin Tested with Postman. API answer is correct:
![image](https://user-images.githubusercontent.com/5720101/102221413-71572680-3ee2-11eb-8aab-2869eec305e0.png)

Please, add what you get from this endpoint in-game. Some data dump. If data will be incorrect, please add it here and assign me back ;)

**Comment by gzatravkin** [comment] 2020-12-15 13:46
Ok, I can't to reproduce it in staging (client). 

Added json text to error message.

For now will put as Not reproduced, if it will happen after that, json text should help to understand the error.

**Comment by denysaw** [comment] 2020-12-15 14:58
@gzatravkin Perfect ;) Deal 🤝

**Comment by SlayksWood** [comment] 2020-12-16 10:26
Cool! but I still don't have it in staging-1874! and still have this exception:
![image](https://user-images.githubusercontent.com/45708377/102335966-9fe80680-3fa1-11eb-8afa-e5cf7a4a7ec9.png)
@StallEF you don't start game in Steam, you start it in folder (and I don;t have any problem with news when start client in folder), you have logout button:
![image](https://user-images.githubusercontent.com/45708377/102336105-c9089700-3fa1-11eb-8fd3-e256246bff1b.png)
We already had a similar issue #17958.
@denysaw @gzatravkin  Can you check another time?

**Comment by SlayksWood** [comment] 2020-12-16 10:30
And I don't have news in 9.1.8 release-130 too in Steam:
![image](https://user-images.githubusercontent.com/45708377/102336906-da9e6e80-3fa2-11eb-8ded-6a9782c8fa40.png)

**Comment by SlayksWood** [comment] 2020-12-16 13:26
A few hours later I have it:
![image](https://user-images.githubusercontent.com/45708377/102353955-e5fd9400-3fba-11eb-87e9-8926287dca06.png)

**Comment by SlayksWood** [comment] 2020-12-16 13:28
I got it! I don;t have news when I use Gibberish. It's not a big bug now, but will be good to fix it to gibberish too. Maybe any localization have trouble too.
![image](https://user-images.githubusercontent.com/45708377/102354371-86ec4f00-3fbb-11eb-9058-c6da335f8dcf.png)

**Closed** 2020-12-17 11:27 UTC
Labels: Category: UI, Priority: Low, Status: Reopen
