### ISSUE TITLE
Alpha.6 Unable to walk upstairs on wood stairs

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2091] opened 2017-09-11 20:16 UTC
I need to jump on stair to get up. If i try to walk it will block.

**Comment by MarjieAVolk** [comment] 2017-09-11 21:14
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1915

For now, you can turn on the "Clambering" option in the escape menu

**Closed by MarjieAVolk** 2017-09-11 21:14 UTC
