### ISSUE TITLE
[0.9.2.4 beta release-156] Laws: Unable to use trigger specific value when multiple triggers are selected

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#21156] opened 2021-03-30 04:51 UTC
I'm trying to make a law where player's aren't able to claim areas of the map that are inside a certain district, but I also wanted to include an extra trigger that would also stops the starter campsites from being placed down in case the game doesn't recognise that as also calming land. The problem I'm running into is that I only want to prevent claiming and placing, but those special values disappear and can't be used if I have more then one trigger set.

Even if I do not actuality need to be specifying an extra trigger for what I am trying to do, I imagine there would be legitimate use cases where you would want to use the special values for greater control when writing laws, but are unable to.

![image](https://user-images.githubusercontent.com/10183015/112935546-b50f2c80-916f-11eb-8277-f6e272fe4f5b.png)

**Comment by IcedForge** [comment] 2021-03-30 12:09
Thank you for reporting issues you run into.
Will be closing this as it is a duplicate of #17468

**Closed by IcedForge** 2021-03-30 12:09 UTC
