### ISSUE TITLE
You have to reconnect 3 or 4 times to successfully connect occasionally 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11739] opened 2019-03-22 23:14 UTC

**Comment by mirasrael** [comment] 2019-03-25 06:19
Can you provide more details? I don't have such issue.

**Comment by metachronism** [comment] 2019-03-25 18:11
pretty sure this is a dupe of #11163

**Comment by BlazeGuy2** [comment] 2019-03-25 18:26
Closing as dup

**Closed by BlazeGuy2** 2019-03-25 18:26 UTC
Labels: High Priority, Needs Information
