### ISSUE TITLE
USER ISSUE: Store List Bug

### ISSUE THREAD

**Issue by Jimmylurks** [StrangeLoopGames/EcoIssues#4789] opened 2018-02-19 01:03 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Maybe had too many items in store when posting a new item to buy and it didn't show.  Then I tried to delete another item in the store on the buying side a few times which didn't work.  Then it caused the bug.

**Expected behavior:**
It should have added the new item to the list and let me remove the old item.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Delete on StoreComponent!

Specified argument was out of the range of valid values.
Parameter name: index


Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.RemoveAt(Int32 index)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass12_0.<RemoveAt>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Core.Controller.RPCListExtensions.Delete(IContainsRPCLists obj, Int32 iList, Int32 iEntry)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

```

**Comment by MarjieAVolk** [comment] 2018-02-20 20:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4048

This seems to be caused by double clicking delete on the last item in the store list.

**Closed by MarjieAVolk** 2018-02-20 20:32 UTC
