### ISSUE TITLE
USER ISSUE: Stockpiles Tutorial step

### ISSUE THREAD

**Issue by Endante** [StrangeLoopGames/EcoIssues#11570] opened 2019-03-05 00:32 UTC
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
1. Be offered the Stockpiles tutorial quest.
2. Gather wood. (I gathered 18) (fell tree, chop a log, pick up smaller logs)
3. Place wood (18) in tiny stockpile attached to starter camp.

**Expected behavior:**
It should have marked the Stockpiles quest as finished and cleared itself.

**Actual behavior:**
Instead, it has the "Place 10 logs in the stockpile"  highlighted (yellow) but does not acknowledge the ones added to the pile. Even if I remove all and re-add only 10, no good.

**Do you have mods installed? 
NO Mods Installed
Does the issue happen when no mods are installed?: 
N/A

**Comment by BlazeGuy2** [comment] 2019-03-05 01:51
Just performed the stockpile tutorial on 8.0.5 without an issue.  Does this happen to you every time you do the tutorial on a new save?

**Comment by Quadbro** [comment] 2019-03-08 08:16
can't reproduce it too

**Comment by Endante** [comment] 2019-03-08 11:56
Sorry, I have been away from my computer for the week. I'll start a new game and try again as soon as I return from my business trip

Sent from Yahoo Mail on Android 
 
  On Fri, Mar 8, 2019 at 12:16 AM, Mike<notifications@github.com> wrote:   
can't reproduce it too

**Comment by D3nnis3n** [comment] 2019-03-21 13:58
Cannot reproduce this, closing for now. Feel free to open a new issue when it reoccurs.

**Comment by beastyn** [comment] 2019-03-29 08:35
*UPDATE*
0.8.1.0 staging-6
no mods

**Reproduced Steps**
1. Get task for stockpiles
2. Chope Trees
3. Collect 20 logs in hand
4. Placing logs in owned stockpile ( 12 in one slot, 8 in second by on time clicking in carrying cell)

**Expected Result:**
stockpile task will end with success

*Actual Result*
Stockpile quest still have yellow element in list with placing 10 logs in stockpile and not ended

![before_end_stockpile_task](https://user-images.githubusercontent.com/27898520/55219723-787a6480-5227-11e9-8761-9de71061034f.jpg)
![after_end_stockpile_task](https://user-images.githubusercontent.com/27898520/55219728-7adcbe80-5227-11e9-83b1-58ee78ecbdec.jpg)

**Closed** 2019-03-29 18:21 UTC
Labels: Fixed, Medium Priority, Staging
