### ISSUE TITLE
USER ISSUE: Carried resource ignoring water

### ISSUE THREAD

**Issue by JanEberlein** [StrangeLoopGames/EcoIssues#5801] opened 2018-03-09 21:55 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Pick up any caarried resource with a transparent	 preview. (e.g. stone or glass)
2. Stand near water and look at it through the preview.

**Expected behavior:**
The water should be visible through the preview.

**Actual behavior:**
The preview does not show the water.

**PS:** 
This does not affect placed materials like glass.

**Comment by Ministrator03** [comment] 2018-03-09 21:58
#5703

**Comment by MarjieAVolk** [comment] 2018-03-09 22:02
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5703

**Closed by MarjieAVolk** 2018-03-09 22:02 UTC
