### ISSUE TITLE
[7.5.1] Fog/Haze after swimming in the water

### ISSUE THREAD

**Issue by X-ITT** [StrangeLoopGames/EcoIssues#8344] opened 2018-07-05 19:44 UTC
When coming out of the water the view becomes hazzy/foggy upon getting out. Easily seen when in a mine,as it's darker, hard to notice the effect above ground. This has been an issue for quite some time but could never figure out the cause.
Server save: [Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2167986/Game.zip)
(although I think this is a game issue and not a server issue as it has happened on multiple servers and with multiple people.)
Before entering water:
![unknown](https://user-images.githubusercontent.com/11493473/42344293-e383ee26-8069-11e8-9ab0-ad9969f5810b.png)
After entering water:
![unknown 2](https://user-images.githubusercontent.com/11493473/42344587-cb27defe-806a-11e8-90a6-ae6dbdaab10c.png)
Current work around/fix: hit esc twice.

**Comment by GophTheGreat** [comment] 2019-05-29 11:10
Can't reproduce this effect. Closing for now.

**Closed by GophTheGreat** 2019-05-29 11:10 UTC
Labels: Medium Priority
