### ISSUE TITLE
USER ISSUE: desktop access

### ISSUE THREAD

**Issue by chopperprop** [StrangeLoopGames/EcoIssues#6770] opened 2018-03-30 22:00 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
alt-tab

**Expected behavior:**
desktop access

**Actual behavior:**
no acess back to game only

**Comment by MarjieAVolk** [comment] 2018-03-30 22:46
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6582

**Closed by MarjieAVolk** 2018-03-30 22:46 UTC
