### ISSUE TITLE
Mouse cursor should auto-hide when you close the last modal dialog

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17516] opened 2020-08-03 22:10 UTC
IE, open a world object UI, press escape, cursor should hide.
This used to happen.

**Comment by johnkslg** [comment] 2020-08-03 22:11
Related:
- Start chat with enter.
- Press escape. Chat closes, cursor does not hide.

**Comment by johnkslg** [comment] 2020-08-03 22:12
Note for @gzatravkin: Dont just fix this to the letter of the request, make it feel good and polished by your own high standards across all interactions.

**Comment by SlayksWood** [comment] 2020-08-04 05:47
@johnkslg @gzatravkin I can't reproduce it without any additional steps. Seems you find some broken behavior. We had this issue before but you need to make some steps (not very hard) to replicate it.
old issue: #12948, but this steps doesn't work.

**Comment by SlayksWood** [comment] 2020-08-04 10:13
I have this problem a several times today. But don't have 100% reprosteps

**Comment by SlayksWood** [comment] 2020-08-04 10:15
And seems it works wrong when you close Full-size map by ESC, work fine if I close it by hotkey

**Comment by beastyn** [comment] 2020-09-03 06:50
Related:

    Start chat with enter.
    Press escape. Chat closes, cursor does not hide.

Still here, cursor won't hide after ESC chat.
https://i.gyazo.com/e0523dfe8a5e197ffc2a43b5cb4423c3.gif
Also after this changes ESC with opened map  will hide cursor, but hotkey won't. (it was reversed before)

**Comment by SlayksWood** [comment] 2020-09-08 05:43
still an issue.

**Comment by IcedForge** [comment] 2020-09-16 08:17
One issue i see now is that when you have multiple windows open it hides the mouse when exiting ANY menu, if you have a sub menu open this should not be the case.

Open Census Bureau, edit draft, close draft by pressing X in the corner and it hides mouse now you need to hit tab to toggle it back to be able to close the census bureau this does not seem right and is very confusing.
https://i.gyazo.com/6c25db536c88b4ab7063be815447cdd6.mp4

**Comment by IcedForge** [comment] 2020-09-25 10:53
18392 Related issues with UI interface closing etc.

**Closed** 2020-11-10 10:00 UTC
Labels: Category: UI, Priority: Low, Status: Reopen
