### ISSUE TITLE
[Client Bug] [Version 5.5 Staging 516ceabd] tooltips not closing

### ISSUE THREAD

**Issue by daveSparhawk** [StrangeLoopGames/EcoIssues#1157] opened 2017-03-10 06:30 UTC
Tooltip dialogues are sometimes not closing when i have moved on.

They remain on screen (and on top) even after i disconnect and reconnect.

i must close client and open again to clear them.

not sure how to trigger/cause.

**Comment by MarjieAVolk** [comment] 2017-03-24 23:38
Closing as duplicate of StrangeLoopGames/EcoIssues#1196

**Closed by MarjieAVolk** 2017-03-24 23:38 UTC
