### ISSUE TITLE
Bug: Escape key doesn't close bag

### ISSUE THREAD

**Issue by JestinJae** [StrangeLoopGames/EcoIssues#20369] opened 2021-02-05 00:50 UTC
Pressing the escape key doesn't close the bag UI.

Version 0.9.2.4 r-156

1) Open bag UI
2) Press escape
3) Note that bag UI doesn't close and instead the normal escape menu appears
4) Note that either pressing b again or using cursor mode and clicking the bag's close button works

I'm sorry if this is a duplicate, I tried a few different options to find a duplicate and didn't come up with anything.

slgid: slg188711 (primarily a steam user, fyi, I don't know how Steam/SLG accounts are linked so not sure if the icon will credit appropriately in both places)

**Comment by SlayksWood** [comment] 2021-02-05 06:23
@JestinJae Thank you for the report. That works as intended. The backpack window is unique window that ignoring closing with ESC. We fixed it a several times before for example here #18045

**Closed by SlayksWood** 2021-02-05 06:23 UTC
