### ISSUE TITLE
USER ISSUE: Eating animation

### ISSUE THREAD

**Issue by onesketchyguy** [StrangeLoopGames/EcoIssues#24792] opened 2024-02-24 04:39 UTC
\
**User Id: (slg18616)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
1. Being eating something by right clicking on the item in an inventory
2. While animation playing, use keypad to swap to another item in inventory

**Expected behavior:**
Swapped to the equipable item, and displayed that in hand.	

**Actual behavior:**
Showed the empty plate, and prevented further actions with  hands.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-03-07 11:52
We cannot reproduce this, can you provide additional information, specifically:

- Was this in first or third person?
- What food did you eat?
- What tool did you switch to?
- Was this on a server or local game?
- If it was on a server, what was your ping?

**Comment by D3nnis3n** [comment] 2024-03-21 16:33
Closing due to no further information provided and issue not being reproducible.

**Closed as completed by D3nnis3n** 2024-03-21 16:33 UTC
Labels: Status: Needs Information, Status: Not reproduced
