### ISSUE TITLE
USER ISSUE: Character Stuck

### ISSUE THREAD

**Issue by mreil617** [StrangeLoopGames/EcoIssues#5035] opened 2018-02-24 11:12 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Open storage chest (unsure other objects)
Change the name
Close the window	

**Expected behavior:**
Be able to move beacuse the cursor is inactive	

**Actual behavior:**
Character seemingly stuck. Must "click" to move again.

**Comment by mreil617** [comment] 2018-02-24 11:25
Seems to only happen if esc is used to close the inventory menu

**Comment by MarjieAVolk** [comment] 2018-02-26 18:30
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

**Closed by MarjieAVolk** 2018-02-26 18:30 UTC
