### ISSUE TITLE
Upgrade Tooltip UI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20430] opened 2021-02-07 21:43 UTC
Task details here: https://docs.google.com/document/d/1OkcmBbZ-3CA8IHnxVv7PmFVlzzMTUUuqDUAPuyBsXM0/edit#

**Comment by TwixterZ** [comment] 2021-06-13 04:42
Fix tested on 9.5 Develop 297

> Tooltips will be given a ‘countdown’ circle. If it expires, then the tooltip freezes and they can mouse over sub-tooltips (like Crusader Kings style).  Holding ‘control’ will also do this instantly.
Above fix does not apply to all items 
eg: 
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/80ead984-3c5d-4534-9b40-79c1c844e92e)

**Comment by TwixterZ** [comment] 2021-06-23 12:31
Tested as of 0.9.5 Develop-306 

Tooltip upgrade only applies to cartable items.

Given item such as starter camp, backer rewards or wolf whisperer rewards does not have this UI upgrade.
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/b9e20277-e0d5-486a-a612-e78eb46ed171)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/0b848082-3cf6-4193-bb8a-a67694417f32)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/9c9afa9c-9813-47f8-94e7-f6c02f8e4054)

**Comment by Moritur** [comment] 2021-06-24 09:50
> Tested as of 0.9.5 Develop-306
> 
> Tooltip upgrade only applies to cartable items.
> 
> Given item such as starter camp, backer rewards or wolf whisperer rewards does not have this UI upgrade.

This is expected behavior - simple tooltips (tooltips without other tooltips inside) are not supposed to lock in place, because user will never have any reason to move mouse over them as there are no other tooltips or links to open inside them.

**Comment by TwixterZ** [comment] 2021-06-24 11:19
as confirmed that this is a expected behavior, I will proceed to close this issue

**Closed by TwixterZ** 2021-06-24 11:19 UTC
Labels: Category: UI, Needs Task Plan, Priority: Medium, Squad: Mountain Goat, Status: Reopen
