### ISSUE TITLE
Weird lighting

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11767] opened 2019-03-27 18:29 UTC
![image](https://user-images.githubusercontent.com/3536496/55102422-96a75f80-5083-11e9-933f-f573b55680b0.png)

**Comment by johnkslg** [comment] 2019-03-27 18:46
![image](https://user-images.githubusercontent.com/3536496/55103580-fa328c80-5085-11e9-9880-4c0d1ab1588b.png)
This is with fog off

**Comment by johnkslg** [comment] 2019-03-27 18:47
looks like its volumetric fog that does it

**Comment by johnkslg** [comment] 2019-03-27 18:48
![image](https://user-images.githubusercontent.com/3536496/55103715-3f56be80-5086-11e9-83fb-8bb97b92a661.png)

**Comment by johnkslg** [comment] 2019-03-27 18:54
I CANT SEE
![image](https://user-images.githubusercontent.com/3536496/55104157-13880880-5087-11e9-947f-082548913d81.png)

**Comment by mirasrael** [comment] 2019-04-02 05:17
Reopened because Eric reverted the fix. Reassigned because he seems to have a better idea how to fix this.

**Comment by metachronism** [comment] 2019-04-02 19:37
This is intended behavior.  John has brightness setting way up causing blown out lighting.  Keegan can tweak lighting further if he prefers it another way, but dropping it to .05 makes it basically invisible

**Comment by johnkslg** [comment] 2019-04-02 21:06
I dont think I had brightness turned up that high, but will check when I get back to my machine.
In any case, the game should never look like that under user-creatable circumstances.

**Comment by mirasrael** [comment] 2019-04-03 05:24
For me it doesn't seems like "invisible", but may be it just me
![image](https://user-images.githubusercontent.com/475445/55454778-c86f7780-55e9-11e9-86d6-d47ba1bf3854.png)

**Comment by metachronism** [comment] 2019-04-04 22:18
its only high for 2 specific hours of the day.  at .05 you get basically no fog except during those hours
you should have fog at all times of day

**Comment by seccombew** [comment] 2019-04-25 22:31
Fixed by @keegan-o

**Closed by seccombew** 2019-04-25 22:31 UTC
Labels: Medium Priority
