### ISSUE TITLE
USER ISSUE: Fell Through the World Again

### ISSUE THREAD

**Issue by Awesomepro247** [StrangeLoopGames/EcoIssues#5379] opened 2018-03-04 18:35 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I don't exactly know what happen but I went off mining and when I went back to my settlement, my ramps were gone. I went down the space where the ramp should have been (thinking it was a visual glitch) but instead I fell through the world. This was on a single player world, so no one stole the ramps.

**Expected behavior:**
Let me go down the ramp.

**Actual behavior:**
caused me to fall through the world.

**Comment by metachronism** [comment] 2018-03-19 18:03
closing as dupe of chunk building issues

**Closed by metachronism** 2018-03-19 18:03 UTC
Labels: High Priority
