### ISSUE TITLE
[0.8.1.0-release-preview] No road tool animation in 3d person view

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11862] opened 2019-04-04 06:33 UTC
[0.8.1.0-release-preview]
no mods

**Steps**
1. Go in 3d person view mode
2. Take road tool
3. Road it

**Expected result**
animation for road tool

**Actual result**
No actions at all. Not even for picking a tool.

![roadtool-3d](https://user-images.githubusercontent.com/27898520/55534271-5b351280-56cd-11e9-9f22-bf22b25f8a31.gif)

**Comment by beastyn** [comment] 2019-04-04 08:13
The same issue is for land claim stake

**Comment by D3nnis3n** [comment] 2019-04-04 15:06
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9409

**Closed by D3nnis3n** 2019-04-04 15:06 UTC
Labels: Medium Priority, Quality Assurance
