### ISSUE TITLE
I cant start server in game [Sever issue]

### ISSUE THREAD

**Issue by bingliCheng** [StrangeLoopGames/EcoIssues#11199] opened 2019-02-09 03:26 UTC
https://cdn.discordapp.com/attachments/543628644841422867/543628661362917378/unknown.png
i was set chinese as my server language use command /openserverui in game. And i restart my server, but its didn't work. 
https://cdn.discordapp.com/attachments/543628644841422867/543629398704783371/unknown.png
i use ecoserver.exe to start server it's work. But i want to start my server in game not ecoserver.exe. Because it's trouble for me.
https://cdn.discordapp.com/attachments/543628644841422867/543628935406026762/unknown.png

**Comment by elfl0rd** [comment] 2019-02-09 07:26
Duplicate of #10948

**Closed by elfl0rd** 2019-02-09 07:26 UTC
