### ISSUE TITLE
USER ISSUE: Cart loosing deed

### ISSUE THREAD

**Issue by ftemporini** [StrangeLoopGames/EcoIssues#5097] opened 2018-02-25 21:46 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
After a server restart my wood cart looses the deed and says that it's unclaimed and i have a deed in my bag that says Unnamed Area, so i have no way to pickup the cart ever again because i have no deed. Happened to me today twice already (After the 4 pm pST restart and then like 10 hours later after we forced a restart because a high ping issue)

https://cdn.pbrd.co/images/H9kCaRJ.jpg

**Expected behavior:**
Deed for wood cart shouldnt dissapear

**Actual behavior:**
It "unlinks" and creates a "blank deed"

**Comment by MarjieAVolk** [comment] 2018-02-26 19:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4899

**Closed by MarjieAVolk** 2018-02-26 19:11 UTC
