### ISSUE TITLE
USER ISSUE: Game softlock from homestead post

### ISSUE THREAD

**Issue by peoplearestrange** [StrangeLoopGames/EcoIssues#23969] opened 2023-08-13 13:20 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-91

**Steps to Reproduce:**
1. be citizen of a town
2. have homestead area claimed
3. pick up homestead pole using hammer
4. place down elsewhere
5. post disappears
6. hotbar because locked and unable to select any items from it

**Expected behavior:**
Not this

**Actual behavior:**
Completely locks the toolbar, you can remove items from it to your back pack. But you cannot interact with anything, cannot change chat options.
placing an item in the space where the homestead pole was duplicates the item but still remains unusable

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. Vanillia server

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2023-08-24 19:55
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23931

**Closed by Daniel-Magulado** 2023-08-24 19:55 UTC
