### ISSUE TITLE
USER ISSUE: Error when special charakter in World Name

### ISSUE THREAD

**Issue by TimTimBS** [StrangeLoopGames/EcoIssues#5132] opened 2018-02-26 16:59 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Put only special characters in a world name that are not allowed to be in a file	

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: Win32 IO returned ERROR_INVALID_NAME. Path: D:/Steam/steamapps/common/Eco/Eco_Data/Server/Storage\DefaultWorld" or "D:/Steam/steamapps/common/Eco/Eco_Data/Server/Storage\?.eco
```

**Comment by MarjieAVolk** [comment] 2018-02-26 23:04
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4670

**Closed by MarjieAVolk** 2018-02-26 23:04 UTC
