### ISSUE TITLE
0.9 cement feedback

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15175] opened 2020-03-17 16:18 UTC
i love cement recipe with quicklime (nice way to use limestone!) <- pleace return limestone to cement again :)
but...
crushed stone price is really, really high.
just look.
10 reinforced concrete req 5 rebar+19 cement.
19 cement... = 191 crushed stone = ~780 stones
(it's all with 50% modules, talent and 7 lvl profession).

**Comment by WeaselDog** [comment] 2020-03-17 17:49
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/15143

**Closed by WeaselDog** 2020-03-17 17:49 UTC
Labels: Priority: Low

**Comment by WeaselDog** [comment] 2020-03-17 17:51
We have internal discussion about re-adding quicklime and lowering costs, but we are not settled on this yet.  I understand it is not an exact duplicate but we have an ongoing discussion about the costs.

**Comment by elfl0rd** [comment] 2020-03-17 17:57
ofc
