### ISSUE TITLE
USER ISSUE: Steam Truck Text - no update

### ISSUE THREAD

**Issue by hami88** [StrangeLoopGames/EcoIssues#9235] opened 2018-09-07 06:41 UTC
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
1.Change Text at Steam Truck
2.Press Save

**Expected behavior:**
Update to the input

**Actual behavior:**
Not updated (still Eco-Plate for me and you.)

**Comment by Conchipedia** [comment] 2018-09-11 17:00
Still the same in 0.7.7.1
![snap2795](https://user-images.githubusercontent.com/29383891/45375274-62d78180-b5ec-11e8-82a2-0d26d775e6d4.png)

**Comment by zahnee** [comment] 2018-10-17 14:05
Still an issue in 0.7.7.2 beta
![image](https://user-images.githubusercontent.com/18610605/47091980-fb68af00-d1f3-11e8-9d1f-b28b9dfec073.png)

**Comment by elfl0rd** [comment] 2018-10-17 15:48
Wait 7.8
https://github.com/StrangeLoopGames/EcoIssues/issues/9443
https://github.com/StrangeLoopGames/EcoIssues/issues/9333

**Comment by Rambo99** [comment] 2018-10-19 20:55
Confirmed in 0.7.7.2

**Comment by D3nnis3n** [comment] 2018-10-28 15:50
Fixed in 7.8, duplicate of the aforementioned issues.

**Closed by D3nnis3n** 2018-10-28 15:50 UTC
Labels: Medium Priority
