### ISSUE TITLE
USER ISSUE: Stove trading

### ISSUE THREAD

**Issue by gust0357** [StrangeLoopGames/EcoIssues#8861] opened 2018-08-05 21:45 UTC
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Type in stove on the item selection screen in your Store

**Expected behavior:**
Stove should be an option to select, in order to be able to trade them. 

**Actual behavior:**
Stove not an option. Can't trade

**Comment by Deantwo** [comment] 2018-08-06 14:03
Items that no one has any skill to craft, won't appear in most lists.
In some cases it might not show up in the lists until the item has been crafted at least once.

I would very much suggest that this become a filter option rather than a rule, so we can disable it if we want to create a buy order or contract for a future item.
For example it could be a checkbox on the item selector saying "Hide uninvebted items" or something, and check it by default if you think that is a good idea.

**Comment by seccombew** [comment] 2018-08-06 22:04
Possibly by design, Craig review.

**Comment by Deantwo** [comment] 2018-08-15 14:07
Same issue exist with laws. Can't create a law preventing the creation of an item that hasn't been invented yet. It is very confusing in every case.

**Comment by D3nnis3n** [comment] 2019-06-01 06:35
Working as intended, closing out.

**Closed by D3nnis3n** 2019-06-01 06:35 UTC
Labels: Low Priority, Needs Information
