### ISSUE TITLE
USER ISSUE: Disconnect

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7838] opened 2018-05-21 23:25 UTC
**Version:** 0.7.4.5 beta

**Steps to Reproduce:**
Logged into server. Was walking around and attempted to pick some fruit and it wouldn't work. The 'disconnected' icon showed up. I could still walk for a bit but then was disconnected.

**Expected behavior:**
Logged in and not been disconnected.

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```

<details>
<summary>Log File</summary>(...previous log truncated...)

3Item, DebugWrenchItem, ExampleItem, FuelPumpItem, FuelStationSignItem, GrillSalmonItem, HousePlant01Item, InventoryInserterItem, JDGarbageCoal, KitchenCabinetItem, KitchencabinetsingularItem, ModernBookCaseItem, ModernCookerItem, ModernSinkItem, ModernToiletItem, PatchWorkChairItem, PipeEngineerSkillBook, PipeEngineerSkillScroll, RicePilafItem, RicePuddingItem, Statue1Item, TunafishSandwichItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Multiple SampleObject detected, using first object! SampleObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Multiple SampleObject detected, using first object! SampleObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Multiple SampleObject detected, using first object! SampleObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Multiple SampleObject detected, using first object! SampleObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, Bankcounter2Object, BankcounterObject, BasicRedCouchObject, BigStorageChestObject, BirchKitchencabinetObject, BooksDecoration01Object, ButtonObject, Cabinet2Object, Cabinet3Object, CedarbedsidetableObject, Chair1Object, Chair2Object, Chair3Object, Chair4Object, Chair5Object, Chair6Object, CoffeTable1Object, CoffeTable2Object, CoffeTable3Object, CoffeTable4Object, Couch2Object, Couch3Object, ExampleObject, FuelPumpObject, FuelStationSignObject, GasGeneratorObject, HousePlant01Object, InventoryInserterObject, KitchenCabinetObject, KitchencabinetsingularObject, LogicGateObject, ModernBookCaseObject, ModernCookerObject, ModernSinkObject, ModernToiletObject, PatchWorkChairObject, Statue1Object, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at PostProcessingManager.UpdateHypoxia () [0x0002f] in <2c9362ff3b6f4767b4b44352d17195ba>:0 
  at Eco.Shared.View.ISubscriberExtensions.SubscribeAndCall (Eco.Shared.View.ISubscriber s, System.String propname, System.Action changedCallback) [0x00008] in <522b50c462ea4e44bfad45c74e5ed0ae>:0 
  at PostProcessingManager.Start () [0x00081] in <2c9362ff3b6f4767b4b44352d17195ba>:0 
 
(Filename: <2c9362ff3b6f4767b4b44352d17195ba> Line: 0)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[24:31] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by Xelsing** [comment] 2018-05-22 13:15
Same problem.

**Comment by TheRobertsE** [comment] 2018-05-23 16:06
same is problem but instead of multiplayer its happening in singleplayer

**Comment by metachronism** [comment] 2018-05-30 19:20
closing as dupe of other issue(s) #7830

**Closed by metachronism** 2018-05-30 19:20 UTC
Labels: High Priority
