### ISSUE TITLE
Spawn road debug command needs updating for new ramps

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11779] opened 2019-03-27 19:11 UTC
![image](https://user-images.githubusercontent.com/3536496/55105268-5c40c100-5089-11e9-9cdd-8dbd50cd785a.png)

**Comment by D3nnis3n** [comment] 2019-03-27 21:01
Duplicate of #9214

**Closed by D3nnis3n** 2019-03-27 21:01 UTC
Labels: Staging
