### ISSUE TITLE
USER ISSUE: fell into the center of the planet

### ISSUE THREAD

**Issue by pynguin** [StrangeLoopGames/EcoIssues#5730] opened 2018-03-09 00:07 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
find an undrawn portion of the map and walk into it, it will look like a white wall

**Expected behavior:**
should have had the map drawn and not freaked out	

**Actual behavior:**
the coordinates started dropping and now stopped at Center:543, 79.  but the sound is super punchy and the hammer I had out is shaking like crazy hammer I

**Comment by MarjieAVolk** [comment] 2018-03-19 20:34
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5917

**Closed by MarjieAVolk** 2018-03-19 20:34 UTC
Labels: High Priority
