### ISSUE TITLE
[6.0.2 Stable] Someone placed a claim.. Weird stuff happen on the server.

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2599] opened 2017-10-23 23:09 UTC
I cannot explain much exactly as I'm lost with the weirdness it caused.
When someone on the server placed a claim on the server it first caused an error for everyone refusing everyone to get back in, next time they claimed the plot we ended up with a server crash...

So I did some investigation and found out that it's because of deeds that look like this:
![unowned](https://user-images.githubusercontent.com/4078460/31916672-1d952f96-b854-11e7-8d9a-03dce80c8093.PNG)
So all you need is the deed in your inventory and then claim a plot of land and in our case, it was next to already claimed plot.
So after the first server restart when we got the weird kick and refused to let us back on we ended up with clean chat...
![clean chat](https://user-images.githubusercontent.com/4078460/31917101-20003f80-b856-11e7-884a-1949606074a8.PNG)
If you need world save feel free to ask.

Dump files:

[Dumpfiles.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1409028/Dumpfiles.zip)

Too many files to bother changing the .ecodump into .txt.

**Comment by MarjieAVolk** [comment] 2017-10-23 23:20
Might be the same as https://github.com/StrangeLoopGames/EcoIssues/issues/2537

**Comment by wiloxe** [comment] 2017-10-24 06:52
Could very well be.

**Comment by MarjieAVolk** [comment] 2017-11-01 19:24
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2566

**Closed by MarjieAVolk** 2017-11-01 19:24 UTC
