### ISSUE TITLE
USER ISSUE: Camo Pants not showing

### ISSUE THREAD

**Issue by xTrickShotProx** [StrangeLoopGames/EcoIssues#5353] opened 2018-03-04 00:12 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Equip Camo Pants

**Expected behavior:**
Show Camo pants on player

**Actual behavior:**
Item doesn't show up

**Comment by MarjieAVolk** [comment] 2018-03-07 20:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3208

**Closed by MarjieAVolk** 2018-03-07 20:53 UTC
