### ISSUE TITLE
USER ISSUE: unexpected bug

### ISSUE THREAD

**Issue by flop25** [StrangeLoopGames/EcoIssues#4777] opened 2018-02-18 20:31 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
take log of wood?

**Expected behavior:**
not a game crash?

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à TreeEntity.PickupLog(Player player, Guid logID)
   à TreeEntity.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-20 22:08
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-20 22:08 UTC
