### ISSUE TITLE
Exceptions when running workorder tutorial

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8696] opened 2018-07-23 19:20 UTC
Probably an errant recipe UI still on there.
![image](https://user-images.githubusercontent.com/3536496/43098031-bd4418e6-8e72-11e8-8092-53db504d9d47.png)

NullReferenceException: Object reference not set to an instance of an object
UI.WorkOrderUI.Update () (at Assets/UI/Scripts/ItemOrSlot/WorkOrderUI.cs:44)

**Comment by GophTheGreat** [comment] 2019-05-30 07:37
Can't reproduce. Closing.

**Closed by GophTheGreat** 2019-05-30 07:37 UTC
Labels: Medium Priority
