### ISSUE TITLE
Can't remove campfires w/ Hammer

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#2012] opened 2017-08-29 05:29 UTC
Related to #2001 

Staging Alpha 6.0.0 #E34aa2e5

**Comment by MarjieAVolk** [comment] 2017-08-29 22:18
Sounds like it's the same problem as the bug you referenced?  Closing as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2001

**Closed by MarjieAVolk** 2017-08-29 22:18 UTC

**Comment by EmuLegs** [comment] 2017-08-30 00:50
if you say so o.O

"Alright, looks like when you hammer the door, it opens/closes instead" -MarjieAVolk

does not sound like a campfire bug to me o.O

**Comment by MarjieAVolk** [comment] 2017-08-30 00:55
Yeah you are right, I closed it before I examined the bug close enough, sorry about that

**Comment by MarjieAVolk** [comment] 2017-08-30 00:56
So now https://github.com/StrangeLoopGames/EcoIssues/issues/2013 is still open, let's track the other issues with picking up objects there

**Comment by EmuLegs** [comment] 2017-08-30 01:04
all good, if you need me i'm normally at 

https://discord.gg/8cmtSy6

ill be updating to see if that fix's the bug
