### ISSUE TITLE
Version 7.2 Server crashing issue related to Eco.Simulation.Agents.Animal.Tick()

### ISSUE THREAD

**Issue by meonester** [StrangeLoopGames/EcoIssues#5118] opened 2018-02-26 09:50 UTC
Version: Staging Beta 7.2.0 #08551408
I believe I've manage to pinpoint bug causing server crash.
It happens couple times a day on random basis.
I guess it's caused by Animals "dying" in player observable world (Visible == true).

```
// class Eco.Simulation.Agents.Animal ->
public override void Tick()
{
	if (base.Dead)
	{
		this.Destroy(); //<-- Removes object from NetManager dictionary
	}
	if (this.Visible)
	{
                //...
		NetObjectManager.OnObjectMoved(this); //<-- Trying to reinsert(remove+add) removed object -> throwing exception -> crashing server
                //...
	}
	else
	//...
}
```
I hope you can confirm my theory, if it happens to be true fix should be trivial.

**Comment by meonester** [comment] 2018-02-26 10:07
One of dumps:
--BEGIN DUMP--
Dump Time
02/25/2018 03:49:33

Exception
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
at System.Collections.Immutable.ImmutableDictionary<>.get_Item(TKey key) at Eco.Plugins.Networking.QuadTree<>.Remove(T item)
at Eco.Plugins.Networking.QuadTreeNetObjectCollection.OnObjectMoved(INetObjectPosition obj)
at Eco.Simulation.Agents.Animal.Tick()
at Eco.Simulation.Simulation.TickAll()
at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
at Eco.Simulation.EcoSim.DoTick(TickSample tick)
at Eco.Simulation.EcoSim.Run()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-02-26 19:59
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4916 - I have noted your theory over there.

**Closed by MarjieAVolk** 2018-02-26 19:59 UTC
