### ISSUE TITLE
USER ISSUE: Labling of the steam powered car (3 wheeled one) shifts upwards on distance

### ISSUE THREAD

**Issue by Toastvogel480** [StrangeLoopGames/EcoIssues#23814] opened 2023-05-05 09:00 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.12 beta release-482

**Steps to Reproduce:**
Lable the car and increase the distance between you and the car

**Expected behavior:**
Labling should stay in position as you move away of the vehicle

**Actual behavior:**
Labling shifts up as you move away

**Do you have mods installed? Does the issue happen when no mods are installed?:**
ther are no mods installed

**Please provide lo
![Close distance](https://user-images.githubusercontent.com/132655797/236416478-7057d064-be4d-46d2-b679-42e1cc477059.PNG)
![Far Distance](https://user-images.githubusercontent.com/132655797/236416492-ea76cd13-08cf-4db0-be0f-1d8604d6828a.PNG)
g files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![Far distance close up](https://user-images.githubusercontent.com/132655797/236417184-dc62324e-7fc3-491a-9fe8-0a3f72f15d0c.PNG)

**Comment by D3nnis3n** [comment] 2023-05-05 13:46
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5602.

Wontfix for now, as Powered Cart is a legacy vehicle, the first one ever made, it would need a full remake.

**Closed by D3nnis3n** 2023-05-05 13:46 UTC
