### ISSUE TITLE
Excavators and steer skids do not pick up loose rocks

### ISSUE THREAD

**Issue by antimodes221** [StrangeLoopGames/EcoIssues#11729] opened 2019-03-22 01:02 UTC
The excavator and steer skid cannot pickup loose rocks.  They are able to break rocks / dirt however if they fall to the floor they are unable to then pick them up.

This breaks using an excavator and skid in crew tandem.

**Comment by FalkosTMB** [comment] 2019-03-22 12:28
https://github.com/StrangeLoopGames/EcoIssues/issues/11594
same as here

**Comment by D3nnis3n** [comment] 2019-03-22 14:42
Duplicate of #11594

**Closed by D3nnis3n** 2019-03-22 14:42 UTC
