### ISSUE TITLE
USER ISSUE: Torches in chest cannot be moved

### ISSUE THREAD

**Issue by hpeanutly** [StrangeLoopGames/EcoIssues#6626] opened 2018-03-29 06:09 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Partial stack of torches in a chest. Stack has a durability bar so presume one is partially used. Try to drag/drop to either another slot in the chest, another chest or play inventory and it just snaps back to old location.

**Expected behavior:**
Items should move

**Actual behavior:**
It just snaps back to where it started

**Comment by thunderbom** [comment] 2018-03-29 12:18
I got the same situation with stack of 5 torches in backpack. Now it can't be moved anywhere (to chest or inside backpack to other slot) and so 1 backpack slot is wasted.

**Comment by MarjieAVolk** [comment] 2018-04-03 18:14
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6598

**Closed by MarjieAVolk** 2018-04-03 18:14 UTC
