### ISSUE TITLE
[0.9.0 staging-1261] Server crash with demographic creating

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13813] opened 2019-11-20 11:33 UTC
Step to reproduce:
- start new server
- place Capitol, Ratify Constitution, /civics winelection 1
- place census and start to create demographic:
![unknown (4)](https://user-images.githubusercontent.com/45708377/69235361-48ab1300-0ba2-11ea-8204-ab46a7181e68.png)
Server crashes When select Hours played.
[log_191120022429.log](https://github.com/StrangeLoopGames/EcoIssues/files/3868957/log_191120022429.log)

**Comment by johnkslg** [comment] 2019-11-20 22:20
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/13796

**Closed by johnkslg** 2019-11-20 22:20 UTC
Labels: High Priority
