### ISSUE TITLE
9.2.2: exception when hovering over some player names

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoIssues#20269] opened 2021-01-30 18:58 UTC
![grafik](https://user-images.githubusercontent.com/34270661/106365373-79094800-6335-11eb-86be-b715d5d0891e.png)

**Comment by MishkaFur** [comment] 2021-01-30 19:02
Received it once or twice too, received it whilst hovering over daniel's name during WT setup, does not seem to happen only on people with no house XP THOUGH hovering over someone with no house XP does not say 0 it shows nothing 

![image](https://user-images.githubusercontent.com/61889138/106365445-a18d4400-632d-11eb-8feb-b3c84921052b.png)

**Comment by WeaselDog** [comment] 2021-01-30 21:55
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19978

We have a fix for this coming soon.

**Closed by WeaselDog** 2021-01-30 21:55 UTC
