### ISSUE TITLE
8.0.0. Harvesting Huckleberries still shows them on plant

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10743] opened 2019-01-18 10:53 UTC
**Version:** 0.8.0.0 beta master-0d4ca997

![snap3835](https://user-images.githubusercontent.com/29383891/51382434-bd3e9c80-1b0e-11e9-8f24-2af9ce9bbeeb.png)
I think this just might be a mistake, as when we used to harvest them the berries disappeared so at least you could see at a glance when they were ready to be harvested.

**Comment by redwyre** [comment] 2019-01-18 12:04
I also harvested some huckleberry bushes that had no berries shown, so the displayed mesh is somehow out of sync with the state of the plant

**Comment by elfl0rd** [comment] 2019-01-18 12:25
Duplicate of #10713

**Closed by elfl0rd** 2019-01-18 12:25 UTC
