### ISSUE TITLE
USER ISSUE: Fishing/Hunting bugged

### ISSUE THREAD

**Issue by RSpeekenbrink** [StrangeLoopGames/EcoIssues#24238] opened 2023-12-16 15:12 UTC
\
**User Id: (slg195576)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
?Sometimes when shooting arrows or casting a fishing rod the rod or arrow doesnt appear and just takes calories/arrows from the inventory

**Expected behavior:**
Casting of a fishing rod and shooting an arrow

**Actual behavior:**
Takes the resources but nothing happends making it really hard to gather food	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by BlueBukkitDev** [comment] 2023-12-16 16:49
This same thing has happened to my friend, where the arrows are disappearing, the crosshair/target indicator never appears, and there is no arrow in the air after firing.

**Comment by D3nnis3n** [comment] 2023-12-16 22:28
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24133 (Fish issue is also already reported)

**Closed by D3nnis3n** 2023-12-16 22:28 UTC
