### ISSUE TITLE
USER ISSUE: Fish traps catching fish above water

### ISSUE THREAD

**Issue by TryphonX** [StrangeLoopGames/EcoIssues#7037] opened 2018-04-06 23:05 UTC
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
1. Place a fish trap in a small place of land (personally I did it on a pier of hewn logs)

**Expected behavior:**
The trap should not work.

**Actual behavior:**
The trap said it wasn't set on solid ground and caught fish on my pier which is obviously above water

**Comment by Eavrusm** [comment] 2018-09-14 04:08
I am also having this issue. I build a house on the water and placed traps on the edge for looks. 
![screenshot 24](https://user-images.githubusercontent.com/43260258/45529287-f904d680-b7a9-11e8-8ee6-07d6656ae68a.png)

**Comment by elfl0rd** [comment] 2019-02-21 22:38
Duplicate of #5818

**Closed by elfl0rd** 2019-02-21 22:38 UTC
Labels: Medium Priority
