### ISSUE TITLE
USER ISSUE: After eating topped porridge...

### ISSUE THREAD

**Issue by queengeekrose** [StrangeLoopGames/EcoIssues#25183] opened 2024-09-27 03:07 UTC
\
**User Id: (74b54939-afc9-4c0c-8a11-08dc8d1bff58)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
Was mining after getting thrown through the map into an underground space.	 Ate topped porridge from inventory and suddenly ALL food/ energy was gone and I am now stuck- p;ick also broke at the same time, as though I had been using it (it was a new stone pick).

**Expected behavior:**
Porridge should have filled food/ energy by about 1/5th (5 fills completely)

**Actual behavior:**
Everything drained and pick I was holding broke.  Also got thrown further down into the underground space.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO MODS

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-09-27 09:29
Not able to reproduce, is there any way you can reproduce the issue? Do you still have the logfiles from that session?

Insofar you are still stuck, you can use the command /unstuck.

**Comment by D3nnis3n** [comment] 2024-10-04 16:28
Closing due to not being reproducible and no further information provided. Feel free to open a new issue if you can provide reproduction steps.

**Closed by D3nnis3n** 2024-10-04 16:28 UTC
Labels: Status: Needs Information, Status: Not reproduced
