### ISSUE TITLE
USER ISSUE: Soil sampler on dead tree without stump causes crash

### ISSUE THREAD

**Issue by CaitSith2** [StrangeLoopGames/EcoIssues#24529] opened 2024-01-04 02:06 UTC
\
**User Id: (slg237757)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Chop down tree.
2. Chop away the stump.
3. Use soil sampler on tree itself.

**Expected behavior:**
Was expecting soil sampler info for the fallen tree indicating that the tree was killed by logging activity.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Nullable object must have a value.
Source:System.Private.CoreLib

System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Eco.Mods.TechTree.SoilSamplerItem.SampleSoil(Player player, InteractionTrigger</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13824910/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13824911/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-01-04 04:26
Duplicate of **internal issue** ECO-32651.

**Closed by D3nnis3n** 2024-01-04 04:26 UTC
