### ISSUE TITLE
[Server Crashing Steam] When Proposing Laws or Running Goverment 

### ISSUE THREAD

**Issue by YoruBrutality** [StrangeLoopGames/EcoIssues#5491] opened 2018-03-06 21:57 UTC
Anytime one of the above actions is performed the whole server crashes. I just want to say so far your development has been amazing. This is something that is really frustrating though.  Is there any work arounds?

**Comment by MarjieAVolk** [comment] 2018-03-07 21:46
What version of the game is this on?  You can see the version number in the lower left corner of the escape menu.

Also, if you could attach any crash files from the server, that would be useful

**Comment by MarjieAVolk** [comment] 2018-03-09 23:25
Can't repro.  Reducing priority until I get more information.

**Comment by asniper** [comment] 2018-03-16 00:54
I have noticed what I am starting to believe is the same thing on a server that I play on. this is 7.2.5 for me. I ran for office, and it appears that whenever someone votes for the run for leader, server crashes. (not 100% confirmed because I can't tell when someone votes, and not server owner) but this is just a hypothesis from observations last night and today. two people voted, server crashed twice possibly after each single vote. waited, 30 min server running fine again, reminded other player to vote, server crashes soon after reminder. today reminded another player to vote, server crashes again.

**Comment by MarjieAVolk** [comment] 2018-03-16 00:56
If you have crash dumps from the server, we could see whether it's the same issue.

**Comment by asniper** [comment] 2018-03-16 02:37
correction, it was on 7.2.4. I am not sure I will be able to get logs. trying though. did confirm after asking someone else to vote, it does take the server down.

**Comment by SRMM** [comment] 2018-03-18 15:27
Problem still exists on 0.7.2.5
One person could run for office but now everyone else trying to run and every vote make the server crash.
Unfortunaltely I am no admin so I can offer no dumps.

**Comment by MarjieAVolk** [comment] 2018-03-22 21:33
We realized the bad laws performance is probably related to the database timeouts (https://github.com/StrangeLoopGames/EcoIssues/issues/6330).  This should be fixed in 7.3

**Closed by MarjieAVolk** 2018-03-22 21:33 UTC
Labels: Medium Priority
