### ISSUE TITLE
USER ISSUE: Powered Cart Glitch

### ISSUE THREAD

**Issue by ProFatBoi** [StrangeLoopGames/EcoIssues#5392] opened 2018-03-04 23:24 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Exit Powered Cart

**Expected behavior:**
Cart stays where it is

**Actual behavior:**
Cart glitches and seems to bounce on the spot. Very annoying if you are on a cliff side and it jumps off the cliff when you exit it/

**Comment by MarjieAVolk** [comment] 2018-03-05 19:10
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4461

**Closed by MarjieAVolk** 2018-03-05 19:10 UTC
