### ISSUE TITLE
[0.9.0.0 beta staging-1543] prevent law will kill the server

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16214] opened 2020-05-08 20:16 UTC
Hello,
 below law to prevent gathering some fruites without skill gathering will instant kill the server instead to prevent the action.
![image](https://user-images.githubusercontent.com/47274045/81445340-f45c1580-9178-11ea-911a-7722c47f8c9a.png)

Server Dump is following:
--BEGIN DUMP--
Dump Time
05/08/2020 22:08:40

Exception
Exception: SynchronizationLockException
Message:Object synchronization method was called from an unsynchronized block of code.
Source:System.Private.CoreLib

System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Monitor.Exit(Object obj)
   at Eco.Gameplay.Items.InventoryLock.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Finalize()

--END DUMP--

**Comment by D3nnis3n** [comment] 2020-05-08 20:18
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/16140

**Closed by D3nnis3n** 2020-05-08 20:18 UTC
