### ISSUE TITLE
The gravity does not apply when the user digs beneath buildings.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9370] opened 2018-09-14 15:16 UTC
Description: The game has some default gravity system in it which can be observed when felling a tree. But when a building is constructed and the players dig around and beneath it, it is observed to be levitating in mid-air.

STR:
1. Start the game.
2. Create/join a world.
3. Place a building (Campsite would be the earliest of buildings)
4. Start digging below it and clear the are beneath it.
5. Observe the issue with the building levitating in mid air.

Actual Result: The gravity is not functioning when the area beneath the building is dug out.

Expected Result: Either the building should fall down once the last dirt is removed or the player should not be able to dig beneath the buildings.

Screenshot:
![screenshot 382](https://user-images.githubusercontent.com/43132426/45558411-79d0da80-b85d-11e8-8c46-2f42e684dacd.png)
![screenshot 383](https://user-images.githubusercontent.com/43132426/45558412-79d0da80-b85d-11e8-8f27-6898ee9d7c8d.png)
![screenshot 384](https://user-images.githubusercontent.com/43132426/45558413-7a697100-b85d-11e8-8a40-06855fe70ad3.png)
![screenshot 385](https://user-images.githubusercontent.com/43132426/45558414-7a697100-b85d-11e8-8dad-ccac9d3edb70.png)
![screenshot 386](https://user-images.githubusercontent.com/43132426/45558415-7a697100-b85d-11e8-873a-59e5eca3bb6e.png)

**Comment by Conchipedia** [comment] 2018-09-14 16:13
its intended behaviour

**Comment by johnkslg** [comment] 2018-09-14 20:46
Wont be fixing this anytime soon, but perhaps someday.

**Comment by D3nnis3n** [comment] 2018-09-15 22:50
Minecraft had a great mod that enforced physics on buildings and as we got a server rule that buildings may not be flying and should be somewhat physically correct i would be in if this get's changed.

**Comment by johnkslg** [comment] 2018-10-03 20:48
Not fixing for now.

**Closed by johnkslg** 2018-10-03 20:48 UTC
Labels: Low Priority
