### ISSUE TITLE
Regression: avatar visible in world again before "save"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14111] opened 2019-12-11 08:37 UTC
He is attacked by animals, other players see a "afk" (though not actually entered) beginner.

**Comment by SlayksWood** [comment] 2019-12-11 11:15
Animal doesn't attack you.

**Comment by WeaselDog** [comment] 2021-04-16 00:08
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18927

**Closed by WeaselDog** 2021-04-16 00:08 UTC
Labels: Priority: Low
