### ISSUE TITLE
[0.8.0.4] Bank ownership requires relogging

### ISSUE THREAD

**Issue by feildmaster** [StrangeLoopGames/EcoIssues#11500] opened 2019-02-27 05:04 UTC
Upon going to a bank and granting access to an account, the person granted access must relog in order to actually have access.

**Comment by Quadbro** [comment] 2019-03-11 07:42
What access? user or manager?) "must relog in order to actually have access." where? in this ui or in general actions

**Comment by feildmaster** [comment] 2019-03-13 11:48
I was unable to select any account I was given access to until I logged back in, be it in shop, or otherwise. I don't... really understand how to explain it any differently? It's pretty easy to replicate via what I said already...

**Comment by Quadbro** [comment] 2019-03-18 11:19
@feildmaster  thanks for info, was confused a little, but it helped :)

**Comment by feildmaster** [comment] 2019-03-18 13:10
Glad it helped

**Comment by D3nnis3n** [comment] 2019-03-21 13:49
Reopened, not fixed in 8.1.0 Staging-1

**Comment by Quadbro** [comment] 2019-03-21 14:20
so you need to provide more information ^_^, can't reproduce it(

**Comment by Quadbro** [comment] 2019-03-22 07:04
![image](https://user-images.githubusercontent.com/6802030/54805989-4c9d3300-4cab-11e9-9f0b-b8687487e205.png)
![image](https://user-images.githubusercontent.com/6802030/54806052-76eef080-4cab-11e9-9569-10fa85f1be8e.png)

**Comment by Quadbro** [comment] 2019-03-22 07:09
and i think you reoppened it because of a /testtreasury command wasn't working properly (use the way, provided on screenshots for testing bank accounts ownership)

**Comment by D3nnis3n** [comment] 2019-03-29 13:03
Reopened. Treasury still does not show without relogging in 8.1.0-Staging-6.

**Closed** 2019-04-01 17:13 UTC
Labels: Fixed, Medium Priority, Staging
