### ISSUE TITLE
USER ISSUE: Client crash when using any table

### ISSUE THREAD

**Issue by MyQeV** [StrangeLoopGames/EcoIssues#6652] opened 2018-03-29 12:08 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
open masonry table -> order 1 sand to be made pitch -> crash -> see actual behavior for report
This happens with ANY item you try to make in any table.

Extra info:
steam beta version 7.3.0

What we already tried server side:
- multiple backup tries
- Clean installation and then a backup

**Expected behavior:**
It should have made sand into pitch in masonry table

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
Caught exception

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by Troelnl** [comment] 2018-03-29 12:10
It is not only the masonry table, also the workbench and carpentertable

Bugreport from carpentertable building hewnlogs:

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>

**Comment by FinalMedia** [comment] 2018-03-29 14:46
ServerSide dump:
--BEGIN DUMP--
Dump Time
03/11/2018 17:28:32

Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

Cannot insert duplicate key in unique index '_id'. The duplicate value is '32527'.


Stack:
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.UsableItemUtils.PlayerPlaceBlock(Type blockType, Vector3i blockPosition, Player player, Boolean replaceBlock, IAtomicAction[] additionalActions)
   at Eco.Gameplay.Items.BlockItem.PlaceBlock(Type blockType, Vector3i targetPos, Player player, Boolean replaceBlock)
   at Eco.Gameplay.Items.BlockItem.OnActRight(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-29 22:32
Are you the people that were talking with @metachronism earlier?

Looks like this is caused by your law, ''.  I'm assuming you removed a mod you used to use.  Turns out laws don't like it when you remove items they reference.  For now, if you remove this law you should be fine.

I'm going to look into supporting removal of mods in laws.

**Comment by MyQeV** [comment] 2018-03-29 22:38
As i understand it they did indeed remove a law. But im just a player from the server it happend on, so i dont know what else they changed.

I'll let the owners/admins of the server know you responded.

**Comment by MarjieAVolk** [comment] 2018-03-29 23:41
Okay, thanks.  FYI I have written a fix for this, so it should go out in the next hotfix.  It will just automatically repeal any laws that are broken in this way.

**Closed** 2018-03-30 00:02 UTC
Labels: High Priority

**Comment by FinalMedia** [comment] 2018-03-30 06:40
@MarijeAVolk That is correct we did sprak with him/her. We also found the cause of the issue with help of one of the devs. He/she pointed out that it was caused by a law. We had found that we had a law in place related to some of our mods. The mods were removed because of some issues with them. When we removed the law all was fine.
