### ISSUE TITLE
Another black screen issue

### ISSUE THREAD

**Issue by greatmutato** [StrangeLoopGames/EcoIssues#5704] opened 2018-03-08 20:06 UTC
Hi, 
As many before, i'm currently facing the dreadfull black screen with sound and cursor.

I've try many things, refresh drivers, reinstalling the game, forcing another directx, forcing windowed mode, ... i also try the workaround of disabling scalling in my intel chipset parameters, still not loading. Here's the first lines of my log : 

Initialize engine version: 2017.3.0f3 (a9f86dcd79df)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Intel(R) HD Graphics Family (ID=0xa16)
    Vendor:   Intel
    VRAM:     1136 MB
    Driver:   20.19.15.4835
Begin MonoManager ReloadAssembly
- Completed reload, in  1.597 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 2 worker threads for Enlighten.
  Thread -> id: 146c -> priority: 1 
  Thread -> id: 80c -> priority: 1 
UnloadTime: 6.903145 ms
RPC lookup took: 8939.7694ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

D3D11: Failed to create RenderTexture (1600 x 900 fmt 27 aa 1), error 0x887a0005
 

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1794611/output_log.txt)

**Comment by Awesomepro247** [comment] 2018-03-08 20:08
I am having the same exact problem.

**Comment by MarjieAVolk** [comment] 2018-03-08 21:29
Closing as duplicate of #4834. The workaround posted there may help you.

**Closed by MarjieAVolk** 2018-03-08 21:29 UTC

**Comment by greatmutato** [comment] 2018-03-09 11:56
Just to let you know it didn't work for me :(
