### ISSUE TITLE
[7.7.0] Buggy Tooltip behavior

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9132] opened 2018-08-30 13:42 UTC
Version: v0.7.7.0-beta-staging-b938b54c

**Steps to reproduce:**
Move objects from one stockpile/storage to another by drag and drop

**Expected behavior:**
Tooltip should fade out as soon as dragging starts.
If the object is selected fast enough, it shouldn't appear at all.

**Actual behavior**:
Tooltip pops up and often stays very long, in some case it becomes steady until the menu is closed.
There appear two kinds of Tooltip, different in size and text (maybe this is the reason).

![coal 1 2](https://user-images.githubusercontent.com/38510829/44855331-15155d80-ac6b-11e8-9af5-0405704aaea7.jpg)

I also have a short video clip with a “frozen” tooltip, it’s an avi clip, 6 sec, 800 KB, don’t know how to attach here. If you are interested in, let me know how to do.

**Comment by elfl0rd** [comment] 2018-08-30 17:03
youtube

**Comment by Nicolausi113** [comment] 2018-08-30 17:16
Okey, here is the clip
https://youtu.be/3QEyur4KrxI

**Comment by MarjieAVolk** [comment] 2018-08-30 18:14
Thanks for the video and all the details.

Regarding the different kinds of tooltip, as you posted, different tooltip content can show up only in certain contexts.  For example, 'Select on toolbar and rightclick to place' I believe only shows up when it is in your personal inventory, since this information isn't useful to you unless you are carrying the item.  Though in this case, the text is a bit inaccurate since you don't have to select carried items 🤔

**Comment by Nicolausi113** [comment] 2018-08-30 18:35
I only clicked the coal in inventory what you see in the clip, nevertheless popped up different forms. I thought this might be a reason for freezing sometimes.
And yes, the text is not accurate since things are dropped everywhere, but this is not the point I wanted to address.

**Comment by Nicolausi113** [comment] 2018-08-31 13:47
Now I can give one more detail on this problem:
- if the object is selected fast (< 0.5 s), a small Tooltip appears above cursor
  (fast means, no Tooltip has popped up when clicking them)
- if selection time is more leisurely (> 0.5 s), a large Tooltip appears below the cursor.

![dragging fast snip](https://user-images.githubusercontent.com/38510829/44915926-a13f8780-ad34-11e8-9b46-701031640683.jpg)

![dragging slow snip](https://user-images.githubusercontent.com/38510829/44915948-b4525780-ad34-11e8-90d2-20dd563a404b.jpg)

**Comment by elfl0rd** [comment] 2018-08-31 15:50
sounds as duplicate of my - https://github.com/StrangeLoopGames/EcoIssues/issues/8126

**Comment by Nicolausi113** [comment] 2018-08-31 16:01
Not exactly a duplicate, but there other postings and suggestions all concerning with this matter. I’m convinced it could be wiped out with one strike :)

**Comment by Nicolausi113** [comment] 2018-09-02 12:13
Another anomaly: empty inventory slot remembers last content - 
https://www.youtube.com/edit?o=U&video_id=3bO2vTMsjMg

**Comment by metachronism** [comment] 2018-09-06 18:06
bumped priority due to other reported issues

**Comment by elfl0rd** [comment] 2018-09-06 18:08
but my ooold https://github.com/StrangeLoopGames/EcoIssues/issues/8126 stay on low priority, lol

**Comment by Deantwo** [comment] 2018-09-07 21:18
Even in v7.7.1 tooltips are kinda annoying.
Would be nice if tooltips vanished the moment you started dragging an item.

**Comment by D3nnis3n** [comment] 2018-09-07 22:27
The problem persists: 
<img width="1516" alt="stillbugged" src="https://user-images.githubusercontent.com/25908592/45245732-f57ed480-b2fd-11e8-8fc7-2dc8268bf2a4.png">
@MarjieAVolk

**Comment by Senlarus** [comment] 2018-09-10 02:33
Still not resolved.

**Comment by Deantwo** [comment] 2018-09-10 05:04
A couple more miliseconds delay before tooltips show might help too.

**Comment by MarjieAVolk** [comment] 2018-09-10 18:15
Alright, still getting lots of complaints after the fix was rolled out, so taking another look.

**Comment by MarjieAVolk** [comment] 2018-09-10 18:59
Hmm, okay so I am not able to reproduce this easily, the way I could before the fix that went out in 7.7.1, but I did just find a way to trigger an issue.  In my case, the tooltip for the item I was dragging opened after I had already started dragging.  Is this what happens to you?

**Comment by D3nnis3n** [comment] 2018-09-10 19:03
Yes and it happens _every_ single time.

**Comment by Nicolausi113** [comment] 2018-09-10 19:52
Yes, tooltip pops up very short after dragging starts and does not disappear as long as left click is held. Sometimes it freezes steady.

**Comment by Senlarus** [comment] 2018-09-10 21:26
Here's an example of what is happening on the current version.
https://vimeo.com/289168663

**Comment by MarjieAVolk** [comment] 2018-09-10 21:30
Hmmm, it stays open even after you let go of the mouse?  I'm not sure now whether my fix fixes that, I've never seen that happen.

Could you send your output_log.txt file right after that happens?

**Comment by Senlarus** [comment] 2018-09-10 22:01
It doesn't look like the file changes after that happens.... but here it is. I created a fresh one to remove any previous errors from older versions.

https://pastebin.com/TJSXjLC2

**Comment by MarjieAVolk** [comment] 2018-09-10 22:03
That's the whole thing?  Okay you don't have any errors in there, so that's interesting.

**Comment by Senlarus** [comment] 2018-09-10 22:06
I stopped my game, renamed the current output_log.txt and started Eco again. It created a new output_log.txt then I reproduced the frozen popup error in-game multiple times then checked the log. That is all that was in there.

Steps for me to repro frozen dialog:
1. Start to drag item
2. When dialog window open attempt to drop item on top of dialog window
3. Dialog window stays on screen until you mouse over another item to get a new dialog window to open, causing the frozen one to disappear.

**Comment by D3nnis3n** [comment] 2018-09-11 03:51
I can't find something in that file either, but got this moving problem on really every occasion i drag and drop something. In about 1 of 10 tries i also get the stick problem so that the tooltip will not go away even if i no longer click and need to go out of the UI and in again. The video shows the problem really good.

**Comment by elfl0rd** [comment] 2018-09-11 05:12
latest master.
![r](https://user-images.githubusercontent.com/4980243/45339268-60e4d280-b59a-11e8-9981-18d920984088.gif)

**Closed** 2018-09-11 12:17 UTC
Labels: High Priority

**Comment by elfl0rd** [comment] 2018-09-11 14:53
closed?

**Comment by MarjieAVolk** [comment] 2018-09-11 17:43
I've committed another fix, which will go out in the next hotfix.  I'm not completely sure that it will solve all of your problems, since I was never seeing them as badly as all of you, but it did solve another case of tooltips staying open while dragging.

**Comment by D3nnis3n** [comment] 2018-09-11 22:42
Seems fixed.

**Comment by D3nnis3n** [comment] 2018-09-11 22:45
So, after i got woken up to update the server, i'll go back to sleep! Night.

**Comment by elfl0rd** [comment] 2018-09-12 05:32
Yea, fixed! Thx :)
