### ISSUE TITLE
Contract Clause Build Road: Valid road was not detected 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7535] opened 2018-05-01 19:07 UTC
![image](https://user-images.githubusercontent.com/6262198/39488914-a86ee4f8-4d38-11e8-8a4a-2f55341d307f.png)

**Comment by johnkslg** [comment] 2018-05-02 00:25
Got the save for this?  I cant tell from the screen shot how youre using ramps.

**Comment by johnkslg** [comment] 2018-05-02 00:51
My tests with roads succeeded

**Comment by Nanders** [comment] 2018-05-02 17:26
[Gamesave.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1968298/Gamesave.zip)

**Comment by Nanders** [comment] 2018-05-02 17:32
![image](https://user-images.githubusercontent.com/6262198/39539154-c655ac84-4df3-11e8-9a9b-bb59a76712d7.png)
![image](https://user-images.githubusercontent.com/6262198/39539282-0dec7b90-4df4-11e8-806c-959c760d8ee9.png)

**Comment by D3nnis3n** [comment] 2019-05-08 17:06
Caused by a ramp being in it, merged with https://github.com/StrangeLoopGames/EcoIssues/issues/12205

**Closed by D3nnis3n** 2019-05-08 17:06 UTC
Labels: Medium Priority
