### ISSUE TITLE
USER ISSUE: Tax evasion through secondary bank account

### ISSUE THREAD

**Issue by dterbeest** [StrangeLoopGames/EcoIssues#24891] opened 2024-04-16 21:11 UTC
Since 10.0 we've been facing an issue where taxation from laws only takes from the citizens personal account, even if that account does not have the required funds. It used to be that it would take from the personal account first, and if that failed it would take from any other account the citizen has ownership of.
This change in how taxation works leads to people creating secondary accounts, just to evade the taxes. Tax evasion leads to unhappy citizens, which leads to us having to police tax evasion.

Steps to reproduce:
 - Make secondary account - put money in it
 - try to tax more than you have in your personal account
  - no money is taken from secondary account
  
  expected behavior:
   - money is taken from secondary account.
   
   extra hint :)
   TaxPayBase_LegalAction.cs:74

**Comment by iuriguilherme** [comment] 2024-04-16 22:14
Can confirm this on 10.1.5 and 10.2, also prevents one from ex. polluting air when there is no money on personal account to tax from.

**Comment by D3nnis3n** [comment] 2024-04-17 04:02
As per your description this is actually working as intended:

Bank accounts are now bound to a specific settlement and settlements can only generally tax the personal bank account and all bank accounts that are located in their settlement (e.g. were made at a bank in that settlement) or a parent settlement of that settlement.

Example:
Town A taxes the cutting of trees with $5.
Player A is a citizen of Town A and has their bank accounts created in Town A.
Player B is a citizen of Town B and has their bank accounts created in Town A.
Player C is a citizen of Town C and has their bank accounts created in Town C.

Player A will be able to be taxed on all accounts and so will Player B. Player C can only be taxed on their personal account.
This is both a security measure so towns cannot use creative means to tax player funds in a illicit way and also intentionally makes the choice of bank accounts interesting. Tax evasion shouldn't happen - the intention is for such triggers to be otherwise prevented, in that case the player can transfer money to their personal bank account to still be able to do the action. The restriction does only apply to law triggers that are specific actions, not all of them. E.g. such, where an action can be prevented.

Given this works as intended I'm closing this issue. If you see a different behaviour, like Town A not being able to tax Player A in all circumstances, please open a new issue with a detailed description of the problem, the law in question and if possible also a savegame where it was setup for quick checking.

**Closed by D3nnis3n** 2024-04-17 04:02 UTC

**Comment by dterbeest** [comment] 2024-04-17 06:49
The scenario you describe is also not working like you say it. Before I made this issue I tested this scenario:
Player A is secretary General of Federation A
A law made by federation A is trying to tax player A
Money is not taken from player A's secondary account.
The secondary account was made inside the federation, no other settlements exist.

The law is really simple. Trigger citizen timer -> tax 100 currency

**Comment by D3nnis3n** [comment] 2024-04-17 07:13
As mentioned please make sure to provide a screenshot of the law and the savegame in a new issue with a description of who did what when. It is not irrelevant what law it is about and what settlement structure is behind it. That information is required to check anything.

**Comment by ZonbiMako** [comment] 2024-04-27 18:29
We've been having this same issue on the DadSpeed server.  Attached is a picture of a law that would be akin to the most 'common' way we implement taxes on DadSpeed.  I was personally involved in testing this.  On 10.1.4, at the town level, this law would simply not see funds in any account other than the "personal account" regardless of whether the other accounts were inside or outside the "jurisdiction".  I have not personally tested this since 10.1.4, but others have and the behavior seems to remain.
![TaxIssue_DadSpeed](https://github.com/StrangeLoopGames/EcoIssues/assets/168300261/edb15f8b-90c5-42ce-b897-e872f6d5b8eb)

**Comment by D3nnis3n** [comment] 2024-04-27 20:28
See here: https://github.com/StrangeLoopGames/EcoIssues/issues/24893#issuecomment-2079970008
