### ISSUE TITLE
[0.9.4.0-Linux] Can't adjust gpu memory limit in settings

### ISSUE THREAD

**Issue by 99thGamer9** [StrangeLoopGames/EcoIssues#22572] opened 2021-08-24 14:09 UTC
There is a Slider to adjust the Gpu memory limit but the value and slider are just stuck at 2,0GB

**Comment by PixlRainbow** [comment] 2021-08-24 19:24
related to #20298

**Comment by D3nnis3n** [comment] 2021-08-29 11:09
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20298

**Closed by D3nnis3n** 2021-08-29 11:09 UTC
Labels: OS: Linux
