### ISSUE TITLE
You can get stuck in a glass stockpile 

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6567] opened 2018-03-28 11:38 UTC
1. Fill a stockpile with glass
2. Jump on top of it and fall between the glass

-> You are now stuck in a glass prison

![grafik](https://user-images.githubusercontent.com/37662083/38026667-4721d450-328d-11e8-934c-864d925e4ead.png)

**Comment by MarjieAVolk** [comment] 2018-03-28 19:03
Looks like this will be fixed in 7.4 (next release, not the one today)

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4729

**Closed by MarjieAVolk** 2018-03-28 19:03 UTC
