### ISSUE TITLE
USER ISSUE: Special Chars in Name

### ISSUE THREAD

**Issue by Devilz80** [StrangeLoopGames/EcoIssues#4768] opened 2018-02-18 18:55 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Set a special char name before entering a game you never joined before. Ex: <Lambda/> (My everywhere name)

**Expected behavior:**
Possibility to change our name to fix it or simply parse the specials chars to fix this bug.

**Actual behavior:**
Impossible to talk in the chat (blank line) and bugs where your name is showed in game.

**Comment by Dr-Hardware** [comment] 2018-02-20 22:53
had a user with special characters join our server 
![image](https://user-images.githubusercontent.com/32424101/36453647-ec756546-16ec-11e8-911c-2b9561c8a574.png)

**Comment by MarjieAVolk** [comment] 2018-02-23 01:45
We are working on support for non-English characters now.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4160

**Closed by MarjieAVolk** 2018-02-23 01:45 UTC
Labels: Medium Priority
