### ISSUE TITLE
BUG: Server games cause my game to crash

### ISSUE THREAD

**Issue by Minihornet** [StrangeLoopGames/EcoIssues#11581] opened 2019-03-05 20:36 UTC
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2932737/output_log.txt)
Cannot post .DMP files so no crash log. sorry discord is Vinnnnny#3352 if you need it.

**Comment by mirasrael** [comment] 2019-03-06 06:05
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11125

**Closed by mirasrael** 2019-03-06 06:05 UTC
Labels: Investigate
