### ISSUE TITLE
Errors occurring with using Mill

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6132] opened 2018-03-16 05:17 UTC
These errors coincide with trying to use the mill to grind wheat - kicking teh player out

--BEGIN DUMP--
Dump Time
03/16/2018 00:15:07

Exception
System.Exception: Caught exception invoking RPC SendChat on ChatManager!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(String text, Int32 playerID)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

--BEGIN DUMP--
Dump Time
03/16/2018 00:08:45

Exception
System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Eco.Shared.Networking.INetObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-19 22:14
First one related to https://github.com/StrangeLoopGames/EcoIssues/issues/4391?

Second one duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Comment by MarjieAVolk** [comment] 2018-03-20 22:04
Okay I'm gonna close this as duplicates actually.

**Closed by MarjieAVolk** 2018-03-20 22:04 UTC
Labels: High Priority
