### ISSUE TITLE
USER ISSUE: Server crashes when opening a chest

### ISSUE THREAD

**Issue by kaenganxt** [StrangeLoopGames/EcoIssues#5312] opened 2018-03-02 22:26 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Not really sure. One player had the chest already open when the other tried to open it.

**Expected behavior:**
The chest should open.

**Actual behavior:**
Server crash with console log:
```[13:26] Disconnecting client [reason: Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object

Stack:
  at Eco.Core.Controller.ControllerManager.PackageMethodResult (Eco.Shared.Serialization.BSONObject bson, Eco.Shared.Networking.INetClient boundClient, Eco.Core.Controller.IController controller, System.Tuple`2[T1,T2] method) [0x00000] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Core.Controller.ControllerManager.PackageController (Eco.Core.Controller.IController controller, Eco.Shared.Networking.INetClient boundClient) [0x00103] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Core.Controller.ControllerManager.PackageValue (Eco.Shared.Serialization.BSONObject bson, Eco.Shared.Networking.INetClient boundClient, System.Object value, System.Int32 nameID) [0x0001a] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Core.Controller.ControllerManager.PackageProperty (Eco.Shared.Serialization.BSONObject bson, Eco.Shared.Networking.INetClient boundClient, Eco.Core.Controller.IController controller, Eco.Core.Controller.SyncPropertyInfo propertyInfo) [0x00019] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Core.Controller.ControllerManager.PackageController (Eco.Core.Controller.IController controller, Eco.Shared.Networking.INetClient boundClient) [0x000a9] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Gameplay.Objects.WorldObject.GetBSON (Eco.Gameplay.Interactions.InteractionContext context) [0x000a1] in <caaa70cd4e5147e186ad0903763e4c6e>:0
  at Eco.Gameplay.Objects.WorldObject.OnActInteract (Eco.Gameplay.Interactions.InteractionContext context) [0x0005e] in <caaa70cd4e5147e186ad0903763e4c6e>:0
  at Eco.Gameplay.Players.Player+<>c__DisplayClass50_0.<PlayerInteract>b__2 (Eco.Gameplay.Interactions.IInteractable inter) [0x00000] in <caaa70cd4e5147e186ad0903763e4c6e>:0
  at Eco.Gameplay.Interactions.InteractionExtensions+<>c__DisplayClass0_1`1[T].<ExecuteUntilSuccess>b__1 () [0x00000] in <caaa70cd4e5147e186ad0903763e4c6e>:0
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess (System.Collections.Generic.IEnumerable`1[T] results) [0x00016] in <caaa70cd4e5147e186ad0903763e4c6e>:0
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, System.Func`2[T,TResult] resultFunc) [0x0001f] in <caaa70cd4e5147e186ad0903763e4c6e>:0
  at Eco.Gameplay.Players.Player.PlayerInteract (Eco.Shared.Items.InteractionInfo info) [0x000df] in <caaa70cd4e5147e186ad0903763e4c6e>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <949c3de22cbf44a3b580b895dd2d40a6>:0
]...
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at Eco.Core.Controller.ControllerInstanceInfo+<>c.<CleanupBoundClients>b__16_0 (Eco.Shared.Networking.INetClient boundClient) [0x00000] in <61d6f8e3e2354670aeb9311383020549>:0
  at System.Collections.Immutable.ImmutableList`1+Node[T].RemoveAll (System.Predicate`1[T] match) [0x00020] in <36486b016d234fca8cd67892bf29c7b5>:0
  at System.Collections.Immutable.ImmutableList`1[T].RemoveAll (System.Predicate`1[T] match) [0x0000b] in <36486b016d234fca8cd67892bf29c7b5>:0
  at Eco.Core.Utils.ThreadSafeList`1+<>c__DisplayClass14_0[T].<RemoveAll>b__0 (System.Collections.Immutable.ImmutableList`1[T] x) [0x00000] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T] (T& original, System.Func`2[T,TResult] apply) [0x00007] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Core.Utils.ThreadSafeList`1[T].RemoveAll (System.Predicate`1[T] match) [0x0001f] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Core.Controller.ControllerInstanceInfo.CleanupBoundClients () [0x00006] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers () [0x00058] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Core.Controller.ControllerManager.Run () [0x000d0] in <61d6f8e3e2354670aeb9311383020549>:0
  at Eco.Server.PluginManager+<>c__DisplayClass18_0.<StartPlugins>b__0 (System.Object x) [0x00000] in <b4b94cd2c5cd4d04b63c8ec9d80be5c8>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in <949c3de22cbf44a3b580b895dd2d40a6>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <949c3de22cbf44a3b580b895dd2d40a6>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <949c3de22cbf44a3b580b895dd2d40a6>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <949c3de22cbf44a3b580b895dd2d40a6>:0
  at System.Threading.ThreadHelper.ThreadStart (System.Object  obj) [0x0000f] in <949c3de22cbf44a3b580b895dd2d40a6>:0```

**Comment by MarjieAVolk** [comment] 2018-03-03 00:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4222

**Closed by MarjieAVolk** 2018-03-03 00:40 UTC
