### ISSUE TITLE
Game Crash Log

### ISSUE THREAD

**Issue by Litschi123** [StrangeLoopGames/EcoIssues#6123] opened 2018-03-16 02:15 UTC
Suddenly my game crashed and i got the following error message:

```
Caught exception:

<size=60,00%>Das angegebene Argument liegt außerhalb des gültigen Wertebereichs.
Parametername: arrayIndex

Stack:
   bei System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   bei System.Collections.Immutable.ImmutableList`1.CopyTo(T[] array, Int32 arrayIndex)
   bei System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   bei Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   bei Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   bei Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   bei Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   bei Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   bei Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   bei Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by Litschi123** [comment] 2018-03-16 02:59
Happend again after I tried to open a stockpile. Same error message.

**Comment by MarjieAVolk** [comment] 2018-03-20 22:30
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5527

**Closed by MarjieAVolk** 2018-03-20 22:30 UTC
