### ISSUE TITLE
Soil trampling above the mine in desert biome

### ISSUE THREAD

**Issue by hitzu111** [StrangeLoopGames/EcoIssues#12195] opened 2019-05-07 02:51 UTC
On our server, we have mines in different biomes including tundra, grasslands, rainforest, and desert. Only the desert mine have issues with trampling above it. 
![Screenshot_590](https://user-images.githubusercontent.com/50346354/57265204-2840be80-707f-11e9-90ed-9992743639e8.jpg)
![Screenshot_592](https://user-images.githubusercontent.com/50346354/57265210-31319000-707f-11e9-9720-319481fa1d4e.jpg)
![Screenshot_593](https://user-images.githubusercontent.com/50346354/57265216-35f64400-707f-11e9-911a-f6aaac0adf8e.jpg)

The save file:
https://drive.google.com/file/d/1ofz2HwExTfxBqd5G9mZFVy1MRuRmAdGv/view?usp=sharing

Mines coordinates:
Desert 731, 1287
Grasslands 809, 1282
Taiga 892, 1369
Rainforest 742, 1135
Tundra 213, 255

**Comment by D3nnis3n** [comment] 2019-05-07 04:39
Afaik this is working as intended (technical reasons), but i remember craig had at least a partly fix for that some days ago. Probably this is fixed in 8.2, i don't know. I assigned him, he can take a look himself.

**Closed** 2019-12-02 09:25 UTC
Labels: Low Priority
