### ISSUE TITLE
connection failed 

### ISSUE THREAD

**Issue by ppurg** [StrangeLoopGames/EcoIssues#6639] opened 2018-03-29 10:10 UTC
1. Eco opens with steam 
2 .I cant join, load or create a world 
3. After loading it says Connection failed 
4. reinstalled the game 
5. doesnt work 
6. It worked yesterday :)

**Comment by MarjieAVolk** [comment] 2018-04-03 00:02
It doesn't give you the error message until after the world starts loading?

Could you give me any files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?

**Comment by MarjieAVolk** [comment] 2018-04-04 17:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6882

**Closed by MarjieAVolk** 2018-04-04 17:16 UTC
