### ISSUE TITLE
[0.9.0 staging-1392] Skill UI opens if you press ALT+Z.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14685] opened 2020-02-11 06:59 UTC

**Comment by elfl0rd** [comment] 2020-02-11 11:27
really old one https://github.com/StrangeLoopGames/EcoIssues/issues/4485

**Comment by elfl0rd** [comment] 2020-04-07 09:40
Duplicate of #4485

**Closed** 2020-04-07 09:44 UTC
Labels: Priority: Low
