### ISSUE TITLE
USER ISSUE: Vehicule and trailer freeze

### ISSUE THREAD

**Issue by Theo7c2** [StrangeLoopGames/EcoIssues#23664] opened 2023-01-07 12:31 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**
Go on a vehicule and try to move

**Expected behavior:**
We should be able to drive

**Actual behavior:**
The vehicle starts but does not want to move

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-02-08 06:45
Can be caused by having a controller connected, closing for now as not reproducible.

**Closed by D3nnis3n** 2024-02-08 06:45 UTC
