### ISSUE TITLE
6.2.0 - ChatCommands user search

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#3046] opened 2017-12-09 01:35 UTC
When entering a username, the search should be case insensitive, found this on custom commands when testing one of my modded commands as mentioned as a note on #3037

**Comment by MarjieAVolk** [comment] 2017-12-09 01:39
Usernames are case sensitive.  clayc could be a different user from ClayC.  So closing as intended behavior

**Closed by MarjieAVolk** 2017-12-09 01:39 UTC

**Comment by ClayC90** [comment] 2017-12-09 02:02
Sorry to break this to you MarjieAVolk

Usernames are case insensitive, here is how I can tell without looking at code, I own account "ClayC" if you try to register an account "clayc" or "Clayc" or any other case combination I get the below message, issue should remain open.

![image](https://user-images.githubusercontent.com/8785758/33791533-604a2096-dc8d-11e7-8266-dcbd2ca750db.png)

Thanks,

**Comment by noblackthunder** [comment] 2017-12-09 02:11
@MarjieAVolk The web site is not case sensitive , So that people can not make ClayC and clayc account . I think Clay wants it to be the same also ingame. There is no point making it harder ingame and forcing case sensitivity when there should be no chance of double username anyway. It would make commands easier too
