### ISSUE TITLE
USER ISSUE:  Kicked from server with error while revising amendments

### ISSUE THREAD

**Issue by BladeRavinger** [StrangeLoopGames/EcoIssues#24710] opened 2024-01-28 22:29 UTC
\
**User Id: (slg93421)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
Primary constitution restricts all changes to mayor only, amendments allows town members to modify zoning.

attempting to revise the amendments causes me to crash out of server.

**Expected behavior:**
Opened the amendments change panel

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: ArgumentException
Message:Object of type 'Eco.Gameplay.Civics.GameValues.GamePickerList' cannot be converted to type 'Eco.Gameplay.Civics.GameValues.GamePickerListAlias'.
Source:System.Private.CoreLib

System.ArgumentException: Object of type 'Eco.Gameplay.Civics.GameValues.GamePickerList' cannot be converted to type 'Eco.Gameplay.Civics.GameValues.GamePickerListAlias'.
   at System.RuntimeType.CheckValue(Object& value, ParameterCopyBackAction& copyBack, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Span`1 copyOfParameters, IntPtr* byrefParameters, Span`1 shouldCopyBack, ReadOnlySpan`1 parameters, RuntimeType[] sigTypes, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMet</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, Unknown

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-28 22:30
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24709

**Closed by D3nnis3n** 2024-01-28 22:30 UTC
