### ISSUE TITLE
[0.9.1.0 beta develop-77] Civics: Amendments not displaying invalid state in ui

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18622] opened 2020-10-07 10:53 UTC
Invalid amendments are not displaying their state in the amendments table ui properly compared to other civic objects such as laws.
![Screenshot_61.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/0986dead-0c11-4714-8f18-9b5b160d85fa)

**Comment by SlayksWood** [comment] 2020-10-15 13:24
Still an issue:
- make Vice-president in registrar. Make Article in Amendments with Vice-President and them delete it:
![image](https://user-images.githubusercontent.com/45708377/96132156-b66ed480-0f02-11eb-9b32-10e300c6a5ec.png)
- It should return previous article from Capitol, but it doesn't. Open Board of election I will see:
![image](https://user-images.githubusercontent.com/45708377/96132266-dd2d0b00-0f02-11eb-8b71-b9cb94b514a5.png)

**Comment by johnkslg** [comment] 2020-10-18 03:09
Check now

**Comment by SlayksWood** [comment] 2020-10-20 06:58
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/96551330-c435a880-12ba-11eb-914d-826a225d70bd.png)
![image](https://user-images.githubusercontent.com/45708377/96551347-cc8de380-12ba-11eb-86c3-7c7c6dfd10bc.png)
May be related with #18830

**Comment by SlayksWood** [comment] 2021-02-26 06:43
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/109265132-1ceff180-7817-11eb-8f47-68fca12356b1.png)

**Comment by SlayksWood** [comment] 2021-02-26 06:45
looks similar with #18997

**Comment by beastyn** [comment] 2021-06-15 07:23
We can't bring some other article back if this article is invalid. It was replaced previously, so we can't add it back without any election process or something. So, let's just make it invalid and maybe show it additionally in host object (though, civics object will show if it's unreachable due to article lack).

**Comment by Daniel-Magulado** [comment] 2021-06-20 01:52
Tested on 0.9.4 Staging-2027

Still an issue.

![image](https://user-images.githubusercontent.com/77248866/122659702-119d4900-d1ad-11eb-8499-3669a24352c6.png)

**Comment by tuha263** [comment] 2021-06-21 07:43
@Daniel-Magulado Seem It will be applied when a civics tick performs (you can use `/civics ticknow` to test). Is it necessary to apply immediately?

**Comment by Daniel-Magulado** [comment] 2021-06-24 12:15
Tested on 0.9.4 Staging-2030 and 0.9.4 Staging-2034.

Unable to reproduce. Closing as fixed.

**Closed by Daniel-Magulado** 2021-06-24 12:15 UTC
Labels: Category: Laws, Priority: Medium, Squad: Mountain Goat, Status: Not reproduced, Status: Reopen
