### ISSUE TITLE
USER ISSUE: Error connecting to server

### ISSUE THREAD

**Issue by ZackieG** [StrangeLoopGames/EcoIssues#23670] opened 2023-01-15 23:22 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**
1. Start server through Eco Server in steam
2. Try to join server
3. Error popped up with authentication issue

**Expected behavior:**
It shouldn't have given me an authentication error, it didn't give me this for 4 days of running/connecting to server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Aenestan** [comment] 2023-04-29 14:33
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>No response from auth server</size>

Log File:
Initialize engine version: 2021.3.19f1 (c9714fde33b6)
[Subsystems] Discovering subsystems at path D:/SteamLibrary/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1050 Ti (ID=0x1c8c)
    Vendor:   NVIDIA
    VRAM:     4017 MB
    Driver:   31.0.15.3161
Version: 0.9.7.12 beta release-482
RAM: 32641MB Total / 13716MB Free
OS Version: Windows 11  (10.0.22621) 64bit
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 12 Cores - 2.208 Ghz
System bit-ness: 64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)

<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.
UnloadTime: 0.754900 ms
start of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()

end of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
WwiseUnity: Wwise(R) SDK Version 2021.1.6 Build 7774.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Setting Plugin DLL path to: D:/SteamLibrary/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

The referenced script on this Behaviour (Game Object '<null>') is missing!
The referenced script on this Behaviour (Game Object '<null>') is missing!
The referenced script (NotificationsController) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object 'Camera') is missing!
The referenced script on this Behaviour (Game Object 'Table') is missing!
The referenced script on this Behaviour (Game Object 'Notification') is missing!
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
Initializing platform: SteamPlatform
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
PlatformManager:AddPrimaryPlatform(Object[])

Failed to initialize social platform: DiscordSocialNetwork.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
SocialNetworkManager:AddSocialPlatforms()
SocialNetworkManager:Awake()

Uploading Crash Report
ResultException: InternalError
  at Discord.Discord..ctor (System.Int64 clientId, System.UInt64 flags) [0x00000] in <00000000000000000000000000000000>:0 
  at DiscordSocialNetwork.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at SocialNetworkManager.AttemptAddSocialPlatform (System.Type socialPlatformType, System.Object[] p) [0x00000] in <00000000000000000000000000000000>:0 
  at SocialNetworkManager.AddSocialPlatforms () [0x00000] in <00000000000000000000000000000000>:0 
  at SocialNetworkManager.Awake () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
SocialNetworkManager:AddSocialPlatforms()
SocialNetworkManager:Awake()

Initialized social platform: SteamSocialNetwork
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
SocialNetworkManager:AddSocialPlatforms()
SocialNetworkManager:Awake()

OvrLipSync Awake: Queried SampleRate: 48000 BufferSize: 16000
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
OVRLipSync:Initialize()
OVRLipSync:Awake()

Authenticating with our primary platform.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:Login(String, String, Boolean)
NetworkManager:Start()

Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI,AutoViewUI,AutoModalUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.UIManager:Start()

[04:28:46.691] The desired audio input device is not available on the system.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
VoiceManager:SetActiveVoiceInputDevice(String, AsyncCallback)
VivoxUnity.AsyncNoResult:SetComplete()
VivoxUnity.Private.<>c__DisplayClass31_0:<BeginRefresh>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
[04:28:47.780] Received login result from our primary platform. (Succes: True | Message: )
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:HandleLoginResult(LoginResult)
<>c__DisplayClass18_0:<PerformPlatformLogin>b__0(LoginSession, String)
<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[04:28:47.782] Account isn't developer tier.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Authentication.AppAuthentication:SetIdentity(AppIdentity)
NetworkManager:SetSessionAndIdentity(LoginSession)
NetworkManager:HandleLoginResult(LoginResult)
<>c__DisplayClass18_0:<PerformPlatformLogin>b__0(LoginSession, String)
<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[04:28:48.648] LoginSession: connectorHandle=C0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
VivoxUnity.Private.<>c__DisplayClass89_0:<BeginLogin>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.<>c__DisplayClass12_0:<BeginGetConnectorHandle>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

The referenced script on this Behaviour (Game Object '<null>') is missing!
DG.Tweening.DOTween:InitCheck()
DG.Tweening.DOTween:ApplyTo(DOGetter`1, DOSetter`1, T2, Single, ABSTweenPlugin`3)
DG.Tweening.DOTween:To(DOGetter`1, DOSetter`1, Color, Single)
DG.Tweening.DOTweenModuleUI:DOColor(Graphic, Color, Single)
HighlightableUI:Highlight(Boolean)
Eco.Shared.Utils.ArrayExtensions:ForEachIndex(T[], Action`2)
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.BaseInputModule:HandlePointerExitAndEnter(PointerEventData, GameObject)
Eco.UI.EcoInputModule:ProcessMove(PointerEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

[ line 1779360520]

[04:29:45.683] Launching server: 'D:/SteamLibrary/steamapps/common/Eco/Eco_Data\Server\EcoServer.exe -nogui -consoleIPC -parentPID=35400 -loadSave="Trying to make sense of it all" -language="English" -seed=0 -clientActive -sleepEnabled -playTime'.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
LocalServerManager:LaunchServer(ClientServerStartParameters, Action`1, String, Boolean)
ContinueUI:ConnectAndContinue()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

[04:31:10.776] Connecting to local host.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.ConnectionUI:ManualUpdate()
Eco.UI.UIManager:Update()

[04:31:10.776] Connecting to 127.0.0.1:3000...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.UI.ConnectionUI:ManualUpdate()
Eco.UI.UIManager:Update()

[04:31:10.776] Connection complete.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.ConnectionUI:ManualUpdate()
Eco.UI.UIManager:Update()

[04:31:11.077] Nat introduction received with token = 8b1247dc-f4e8-4b97-9dea-d04a98ef0ae4
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(Address&, IntPtr, Int32, Boolean&)
Eco.Networking.ENet.ENetUdpPeer:Intercept(Event&, Address&, IntPtr, Int32)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__78_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

[04:31:20.937] Disconnected with error: Invalid login info.

<size=60.00%>No response from auth server</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
ViewData:CreateView()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__78_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

Unloading 6 Unused Serialized files (Serialized files now loaded: 3)
Unloading 17 unused Assets to reduce memory usage. Loaded Objects now: 137377.
Total: 195.727200 ms (FindLiveObjects: 10.086400 ms CreateObjectMapping: 21.972000 ms MarkObjects: 163.391200 ms  DeleteObjects: 0.276900 ms)

**Comment by D3nnis3n** [comment] 2023-12-20 22:55
This is not a bug but caused by Eco being unable to reach our authentication servers.

Typically this happens when security software or firewalls block the access and can be resolved by exempting Eco in any antivirus software. You can also test by using a VPN (or turning an existing one off that may not be able to reach).

In Eco authentication is done by the server, hence when you play on a online server you're likely not seeing the problem, as those servers have no issues connecting to our authetnication server, while when you play a local game, a local server is run that has the issue.

Further information can be received at [support@strangeloopgames.com](mailto:support@strangeloopgames.com).

**Closed by D3nnis3n** 2023-12-20 22:55 UTC
