### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by Xiermannen** [StrangeLoopGames/EcoIssues#5178] opened 2018-02-27 14:08 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I tried to make a new world but the games "tabes out" to desktop and when opening the game up it says "Connection Failed". I can play on online servers with no problem but not play alone.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```Connection Failed
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-02-27 18:35
Since the game is minimizing, is a firewall or antivirus application blocking the game?  It may be popping up a confirm dialog.

**Comment by Xiermannen** [comment] 2018-02-28 11:05
Actually no, i was looking for a popup window from windows but non what so ever. :/
And it also only says "Connection Failed" and nothing more.

**Comment by MarjieAVolk** [comment] 2018-02-28 18:52
Can you try to run your local game again, and then send me your file 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by MarjieAVolk** [comment] 2018-02-28 22:34
It sounds like others have had success with running the save file with the Eco Server tool.

Going to close this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5007 - But if you have the log file I asked for, or if you have any other information, please share :)  Still trying to figure it out.

**Closed by MarjieAVolk** 2018-02-28 22:34 UTC
