### ISSUE TITLE
USER ISSUE: Failed to connect to an online server

### ISSUE THREAD

**Issue by Krisard** [StrangeLoopGames/EcoIssues#22497] opened 2021-08-01 13:46 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Trying to login to the server

**Expected behavior:**
Login to the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2021-08-01 13:50
Hi @Krisard

Thank you for writing this bug report.
Are you trying to connect to server hosted locally? Or online? If so, is it a server hosted by a friend?


Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Krisard** [comment] 2021-08-01 13:58
I can connect to a local game. The problem happens if I want to connect to a saved server.
If I type in the adress, the connections works
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6912777/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6912778/Player.log)

**Comment by Daniel-Magulado** [comment] 2021-08-01 18:30
Hi @Krisard 

For clarification, when you mentioned saved server, did you mean pressing the **Continue** button?
Does this also mean that you've played on that server before and you can't connect recently?
Mind sharing the server ID with me? If you're not comfortable sharing here, you can do so privately via Discord (Nielzx#6566) or email (daniel@strangeloopgames.com)

**Comment by Daniel-Magulado** [comment] 2021-08-06 16:56
Hi @Krisard 

We discovered an issue with our relay server that affected a number of players preventing them to connect to a friend's server. This should be fixed now. Kindly let us know if you're still having difficulties connecting to an online server.

**Comment by Daniel-Magulado** [comment] 2021-08-11 01:15
Closing for no response. Assuming the issue is fixed for the player.

**Closed by Daniel-Magulado** 2021-08-11 01:15 UTC
Labels: Status: Needs Information
