### ISSUE TITLE
Steam truck cannot be interacted with any longer

### ISSUE THREAD

**Issue by Snow1981m** [StrangeLoopGames/EcoIssues#23815] opened 2023-05-07 16:18 UTC
I've played for about a week (singleplayer) without having any issues, but now the steam truck cannot be loaded or entered. Instead, it can be pushed and flipped around. The green frame that appears if you go near the truck won't appear any more, neither won't pop up any commands to interact with it. So I cannot even pick it up; restarting the game doesn't solve it either.

**Comment by TwixterZ** [comment] 2023-05-09 11:06
@Snow1981m apologies this happens to you, can you share both your player log and server log. and if possible your save file for us to investigate this issue further? 

Please also advise which version did you encounter this issue?

**Comment by Snow1981m** [comment] 2023-05-09 11:54
It occured several times in the current version and suddenly stopped after
two days.
Because I have been unable to reproduce it since the issue solved itself, I
cannot provide any logs.

It is the vanilla version of Eco 0.9.7.12 beta release-482

Khairi ***@***.***> schrieb am Di., 9. Mai 2023, 13:06:

**Comment by D3nnis3n** [comment] 2023-05-22 13:54
Closing due to not having anything we can reproduce with. If it reappears and you can provide logs, please open a new issue.

**Closed by D3nnis3n** 2023-05-22 13:54 UTC
