### ISSUE TITLE
Player housing messages are confusing

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6560] opened 2018-03-27 22:00 UTC
![image](https://user-images.githubusercontent.com/6262198/37997073-b494316e-31ce-11e8-8729-518afb3a630c.png)

What is the +0.5 supposed to mean
My housing went down from 48 to 0, (change of -48, which is correct)
then up +0.5 to 12?

Its hard to tell what is happening in these systems

**Comment by elfl0rd** [comment] 2018-12-05 16:46
@D3nnis3n dupe of fixed issue https://github.com/StrangeLoopGames/EcoIssues/issues/5432

**Comment by D3nnis3n** [comment] 2018-12-05 19:39
Fixed.

**Closed by D3nnis3n** 2018-12-05 19:39 UTC
Labels: Low Priority
