### ISSUE TITLE
USER ISSUE: Disconnect Icon Keeps Appearing

### ISSUE THREAD

**Issue by Armored-Stone** [StrangeLoopGames/EcoIssues#23735] opened 2023-04-01 18:54 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.9 beta release-451

**Steps to Reproduce:**
No idea how to reproduce

**Expected behavior:**
Disconnect icon only shows during moments of lag

**Actual behavior:**
Shows up randomly and stays on screen while the game behaves normally.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NidToolbox on DadSpeed. No idea if it happens without mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Armored-Stone** [comment] 2023-04-01 18:58
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11130358/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11130359/Player.log)

**Comment by D3nnis3n** [comment] 2023-04-03 23:17
Unable to reproduce, need more info or reproduction case, otherwise closing in seven days :(

**Comment by D3nnis3n** [comment] 2023-04-10 15:36
Closing due to no further information or reproduction case provided. Feel free to reopen when you have some.

**Closed by D3nnis3n** 2023-04-10 15:36 UTC
Labels: Status: Needs Information, Status: Not reproduced
