### ISSUE TITLE
Server List

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6772] opened 2018-03-30 22:22 UTC
http://steamcommunity.com/profiles/76561198036748973/recommended/382310/
- The server selection list almost makes the game unplayable. Devs please just append new servers to the list as they load instead of inserting them at random positions. Nobody can read a moving list. Also some filters would be amazing (specialization level, size, day count, population, etc). At this point the start up UI is the worst part of the game by far.

**Comment by metachronism** [comment] 2018-03-30 22:34
dupe of a lot of other server browser issues

**Comment by MarjieAVolk** [comment] 2018-05-08 23:01
Fixed in 7.4

**Closed by MarjieAVolk** 2018-05-08 23:01 UTC
Labels: High Priority, Steam Report, Suggestion
