### ISSUE TITLE
Tortoises overwhelming

### ISSUE THREAD

**Issue by Kastuk** [StrangeLoopGames/EcoIssues#4387] opened 2018-02-12 14:30 UTC
Tortoises growing uncontrollably into the horde, +200 per day.

Same as this issue.
https://github.com/StrangeLoopGames/EcoIssues/issues/4341
With addition.

Looks like  problem is here (in EcoSim.eco):
```
Tortoises "SpeciesChangeRate": 0.9,
Hares "SpeciesChangeRate": 0.05,
Elk "SpeciesChangeRate": 0.02,
Bison "SpeciesChangeRate": 0.01,
```

And here:
```
"Range": {
            "min": 0.0,
            "max": 5.0
```

Lines 8738 and 8745

Also:
```
"FoodSources": {
            "$id": "332",
            "Eco.Simulation.Types.Species": {
              "$type": "System.Collections.Generic.List`1[[Eco.Simulation.Types.Species, Eco.Simulation]], mscorlib",
              "$values": []
            },
            "masterList": {
              "$id": "333",
              "$type": "Eco.Core.Utils.MasterListSurrogate`1[[Eco.Simulation.Types.Species, Eco.Simulation]], Eco.Core",
              "Master": {
                "$ref": "1"
              }
            }
          },
```

Looks like there no determined foodsources for Tortoises. Empty brackets.
Line 4383

Same with Foxes. 
Line 2515 
Wolves control both Hares and Elks.

That's why Tortoises and Foxes raising constantly without any relationship jumps by food source.
And Bisons don't eat too.

It's cause there no predators against them for now and foxes not much completed?

But somehow foodplants dying everywhere with low online of hunger players.

**Comment by MarjieAVolk** [comment] 2018-02-13 00:18
Oh, I see you posted this information also in the other bug.  Okay, I am going to close this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4341  Thanks for finding the weird configuration!

**Closed by MarjieAVolk** 2018-02-13 00:18 UTC
Labels: Medium Priority
