### ISSUE TITLE
Vechicles must save parameters.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11072] opened 2019-02-04 11:49 UTC
Losing authorization and owner after pickup\place produce too many uncomfortable situation. e.g. party in mine, and stucked cart, someone in deed picked up cart - all other lose access, etc...

also do not miss text field, name, and attached deed please.

We already have "mint" it save their parameters after pickup\place, can this mechanics to be expanded to vechicles?

**Comment by johnkslg** [comment] 2019-02-04 16:37
Would be good to make the relationship between items -> world objects more specific, so theres regular data that can be propogated between both an item in its picked up and placed form (a la mint, but made abstract)

**Comment by metachronism** [comment] 2019-02-04 19:38
I believe this is a dupe of another refactor issue as well

**Closed** 2019-04-10 09:29 UTC
Labels: Semi-High Priority, Usability, suggestion
