### ISSUE TITLE
USER ISSUE: Tomatoes are invisible on linux

### ISSUE THREAD

**Issue by douglasg14b** [StrangeLoopGames/EcoIssues#13955] opened 2019-11-30 09:59 UTC
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
Place or have a friend find Tomatoes while you are on the linux clients

**Expected behavior:**
Plants are visible

**Actual behavior:**
They are invisible, but the "E" activation comes up.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods

**Comment by D3nnis3n** [comment] 2019-11-30 13:56
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/13032

**Closed by D3nnis3n** 2019-11-30 13:56 UTC
