### ISSUE TITLE
USER ISSUE: Connection Failed message during world creation

### ISSUE THREAD

**Issue by OfAllTheBars** [StrangeLoopGames/EcoIssues#3925] opened 2018-02-05 17:57 UTC
**Version:** 0.7.0.2 beta

**Steps to Reproduce:**
New world, low interaction, create new selected.
About 30 seconds in to creating new world and the error message Connection Failed appears.
The last message before it fails is 'Compiling Mods'

**Expected behavior:**
Created a world

**Actual behavior:**
Connection Failed
(PS I have now downloaded the latest server build - just the client.  Do I need both still?

**Comment by Nanders** [comment] 2018-02-05 18:27
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3910

**Closed by Nanders** 2018-02-05 18:27 UTC
