### ISSUE TITLE
[0.9.0 staging-1706] 3 Exceptions in view notify: System.NullReferenceException at once.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17577] opened 2020-08-06 07:30 UTC
Step to reproduce:
- first player make Harvest Contract:
![image](https://user-images.githubusercontent.com/45708377/89503674-8d79e700-d7cf-11ea-927d-d5d24cbd70d6.png)
- second player take it. First player have 3 exceptions:
```
Exception in view notify: System.NullReferenceException: Object reference not set to an instance of an object.
  at UnityEngine.UI.Graphic.SetVerticesDirty () [0x00000] in <00000000000000000000000000000000>:0 
  at ContractEntryUI.UpdateEntry () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.ViewManager.ReceiveViewUpdate (Eco.Shared.Serialization.BSONArray updates) [0x00000] in <00000000000000000000000000000000>:0 
  at ClientPacketHandler.ReceiveWhile (Eco.Shared.Networking.NetworkClient client, System.Func`1[TResult] condition) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.OnTimeLimitedUpdate (TimeLimit timeLimit) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.PlannerGroup.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.FramePlannerSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.View.View:NotifyChanged(String)
Eco.Shared.View.ViewManager:ReceiveViewUpdate(BSONArray)
ClientPacketHandler:ReceiveWhile(NetworkClient, Func`1)
NetworkManager:OnTimeLimitedUpdate(TimeLimit)
System.Action`1:Invoke(T)
FramePlanner.PlannerGroup:OnUpdate()
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
System.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Exception in view notify: System.NullReferenceException: Object reference not set to an instance of an object.
  at UI.ViewUIContainer.ListChanged () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.ViewManager.ReceiveViewUpdate (Eco.Shared.Serialization.BSONArray updates) [0x00000] in <00000000000000000000000000000000>:0 
  at ClientPacketHandler.ReceiveWhile (Eco.Shared.Networking.NetworkClient client, System.Func`1[TResult] condition) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.OnTimeLimitedUpdate (TimeLimit timeLimit) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.PlannerGroup.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.FramePlannerSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.View.View:NotifyChanged(String)
Eco.Shared.View.ViewManager:ReceiveViewUpdate(BSONArray)
ClientPacketHandler:ReceiveWhile(NetworkClient, Func`1)
NetworkManager:OnTimeLimitedUpdate(TimeLimit)
System.Action`1:Invoke(T)
FramePlanner.PlannerGroup:OnUpdate()
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
System.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Exception in view notify: System.NullReferenceException: Object reference not set to an instance of an object.
  at UI.ViewUIContainer.ListChanged () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.ViewManager.ReceiveViewUpdate (Eco.Shared.Serialization.BSONArray updates) [0x00000] in <00000000000000000000000000000000>:0 
  at ClientPacketHandler.ReceiveWhile (Eco.Shared.Networking.NetworkClient client, System.Func`1[TResult] condition) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.OnTimeLimitedUpdate (TimeLimit timeLimit) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.PlannerGroup.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.FramePlannerSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.View.View:NotifyChanged(String)
Eco.Shared.View.ViewManager:ReceiveViewUpdate(BSONArray)
ClientPacketHandler:ReceiveWhile(NetworkClient, Func`1)
NetworkManager:OnTimeLimitedUpdate(TimeLimit)
System.Action`1:Invoke(T)
FramePlanner.PlannerGroup:OnUpdate()
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
System.Action:Invoke()
```
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5033226/Player.log)

**Comment by SlayksWood** [comment] 2020-08-06 07:43
After that first player can have this exception when create/delete contract.

**Comment by MazonDel** [comment] 2020-08-17 14:48
I was unable to reproduce this bug using a fresh build of Staging on 8/10/20 and was told to place it into QA with a fixed label for review.

**Comment by beastyn** [comment] 2020-08-20 11:50
@MazonDel Well, I was about just closing it today
But
We had this one again
```
Exception in view notify: System.NullReferenceException: Object reference not set to an instance of an object.
  at UI.ViewUIContainer.ListChanged () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.ViewManager.ReceiveViewUpdate (Eco.Shared.Serialization.BSONArray updates) [0x00000] in <00000000000000000000000000000000>:0 
  at ClientPacketHandler.ReceiveWhile (Eco.Shared.Networking.NetworkClient client, System.Func`1[TResult] condition) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.OnTimeLimitedUpdate (TimeLimit timeLimit) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.PlannerGroup.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.FramePlannerSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.View.View:NotifyChanged(String)
Eco.Shared.View.ViewManager:ReceiveViewUpdate(BSONArray)
ClientPacketHandler:ReceiveWhile(NetworkClient, Func`1)
NetworkManager:OnTimeLimitedUpdate(TimeLimit)
System.Action`1:Invoke(T)
FramePlanner.PlannerGroup:OnUpdate()
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
System.Action:Invoke()
```

It was after Kirill has taken and finished Harvest contract. But we could not repeat it again after client restart. Still need some work here.

**Comment by beastyn** [comment] 2020-08-21 05:19
Ok, we actually have it for Gri already here #17789
I will leave that one,

**Closed by beastyn** 2020-08-21 05:19 UTC
Labels: Category: Tech, Priority: Medium
