### ISSUE TITLE
Fireplace / Brazier / Torch: Auto disable at day

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6399] opened 2018-03-23 07:20 UTC
Currently:
Man-made light sources are turned on as long as they have fuel.

Problem:
Manual management overhead to micro manage the light sources to conserve fuel (also looks weird at day)

Suggestion:
Add function to GUI: "Only add new fuel at night time" which does what is says. :)

**Comment by ecoemmeck** [comment] 2018-03-23 17:32
This would be a good feature for any light source to notice if it's needed or not.
E.g. electric street lamps and wall lights aren't really needed during the day unless under ground or in a place of low lighting.
This would also save your power from different generatorers depending on the time of day

**Comment by MarjieAVolk** [comment] 2018-03-23 17:46
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2739

**Closed by MarjieAVolk** 2018-03-23 17:46 UTC
