### ISSUE TITLE
USER ISSUE: Eating while in a Small Canoe Capsizes

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#23872] opened 2023-06-30 19:09 UTC
\
**User Id: (slg56161)**
**Version:** 0.10.0.0 beta playtest-19

**Steps to Reproduce:**
1. Board a Canoe
2. Paddle Canoe
3. try to eat food to restore calories

**Expected behavior:**
Canoe should have just come to a stop and allowed you to take a bite of food and then continue on	

**Actual behavior:**
Canoe Capsizes and starts spinning on its side perpetually

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods are installed

![20230630140815_1](https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/86811000-1947-46d2-9784-526ac17b6383)
![20230630140816_1](https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/b41c36ac-3d52-4d00-b64a-24d6a664f560)
![20230630140817_1](https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/97f73d41-8ceb-4b09-85d2-15ee699e68ca)
![20230630140818_1](https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/55800e59-8996-4927-bb46-a6081f5531ae)
![20230630140820_1](https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/1b3b905e-7350-4bbf-a5b2-28ee026abe77)

(I tried to take screenshots as the canoe spun)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Sarah-Graesyn** [comment] 2023-06-30 19:10
I was able to get out of the canoe and it returned to an upright position; however trying to eat while in the "Paddle" position capsizes it again.

**Comment by Sarah-Graesyn** [comment] 2023-06-30 21:39
https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/d90a1eed-890e-4e5a-8c92-278d2fcb95a1

**Comment by TwixterZ** [comment] 2023-07-06 07:40
Hi @Sarah-Graesyn , I have not been able to reproduce this on my end on both local and WT. Can you share your log file when this happens to you again?

**Comment by D3nnis3n** [comment] 2023-08-24 12:21
Closing due to being unable to reproduce and no further information provided.

**Closed by D3nnis3n** 2023-08-24 12:21 UTC
Labels: Status: Not reproduced
