### ISSUE TITLE
USER ISSUE: Dupplication of items with wheelbarrow

### ISSUE THREAD

**Issue by JackHD96** [StrangeLoopGames/EcoIssues#7473] opened 2018-04-28 11:52 UTC
**Version:** 0.7.4.0 beta staging-68e3874b

**Steps to Reproduce:**
i placed down the wheelbarrow then picked it up stored it in a chest and when i started my game again today it had dupplicated 2 small wood carts and a wheelbarrow that got placed in my home and i cant take it away

**Expected behavior:**
just been stored not spawn in more stuff	

**Actual behavior:**
spawned in wheelbarrow and 2 small wood carts

**Comment by JackHD96** [comment] 2018-04-28 11:53
![20180428134813_1](https://user-images.githubusercontent.com/38810617/39396272-8727b940-4aeb-11e8-823d-15dceca24e5e.jpg)
![20180428134833_1](https://user-images.githubusercontent.com/38810617/39396273-8f4e13e4-4aeb-11e8-9de9-f598bcba7a2d.jpg)
![20180428134824_1](https://user-images.githubusercontent.com/38810617/39396277-929886f6-4aeb-11e8-9ddb-726cd6ab27d7.jpg)

**Comment by JackHD96** [comment] 2018-04-28 11:56
so oi closed down the game again just to see when happends and it spawned in more wheelbarrows in my wall and carts that i cant take away

**Comment by JackHD96** [comment] 2018-04-28 11:57
![20180428135703_1](https://user-images.githubusercontent.com/38810617/39396303-239b42ec-4aec-11e8-8794-86ba477341ee.jpg)
![20180428135708_1](https://user-images.githubusercontent.com/38810617/39396304-24cf6df0-4aec-11e8-9da5-3684a0eb3ee8.jpg)

**Comment by elfl0rd** [comment] 2018-04-28 12:34
https://github.com/StrangeLoopGames/EcoIssues/issues/7317

**Comment by Elliander** [comment] 2018-04-28 21:35
IMHO, we should have the ability to remove objects from the world without the deed. This bug is literally a server killer, and even if the bug causing the duplication is fixed, unless and until we can remove duplicated objects as users it won't really be fixed. 

I am increasingly of the opinion that the entire deed system needs to be overhauled, replaced with a menu that keeps track of all things we own. Maybe have the deed system exist, but only for cases where we want to sell our land with a covenant, or something like that. We shouldn't need a physical deed to exercise control over objects we own. Only for transfer of ownership.

**Comment by elfl0rd** [comment] 2018-04-29 06:31
@Elliander you already can.
By using devtool.
And you can use another players property if you hold devloot in hand.

**Comment by Elliander** [comment] 2018-04-29 17:01
I don't really consider DevTool an actual solution,  because it requires an
admin to manually clean up everyone's mess and it encourages the server
host to use cheat tools rather than playing like everyone else.

Besides that,  even after using DevTools the objects re-duplicate whenever
this bug crops up so it would still make more sense for all players to have
control of their own objects since that's a much easier bandaid.

https://eco.gamepedia.com/Dev_Tool

**Comment by elfl0rd** [comment] 2018-04-29 17:24
> ability to remove objects from the world without the deed.
> because it requires an admin to manually clean up everyone's
Yes.
Ability to remove objects available to non admin = hello griefers!

but this bug fixed.

**Comment by Elliander** [comment] 2018-04-30 04:54
I don't see how you can grief your own inventory. Just allowing all players
to pick up the items they own without a deed would be perfect.

I'm not saying that everyone should have a DevTool. I'm saying it makes no
sense to need a DevTool to begin with. If we had control over our owned
objects the bug wouldn't have been nearly as serious as it was. At worst it
would have given duplicate items that benefit everyone equally rather than
turning the world into a landfill that would require one player to manually
fix everything.

**Comment by elfl0rd** [comment] 2018-04-30 07:26
Duplicated items - have no owner.

**Comment by Elliander** [comment] 2018-04-30 19:06
Not true. When my objects were duplicated I was the owner of all of them. I
had the ability to use all the dozens of carts, and put items into them, as
well as the duplicated excavators. I just couldn't pick them up because no
deed was generated. Additionally, when vehicles were duplicated they had
fuel in them even though they were put away in a storage chest, and in fact
the only items that were duplicated were items put away. My truck that was
sitting out with items in it was not duplicated.

Of course, I can't discount the possibility of a variation of this bug
where no duplicated objects are bugged, I never encountered that variation.

**Comment by metachronism** [comment] 2018-05-09 22:17
closing as dupe of other dupe objects bugs

**Closed by metachronism** 2018-05-09 22:17 UTC
Labels: High Priority
