### ISSUE TITLE
USER ISSUE: Mining upgrade doesn't lower resource cost of arrastra work orders

### ISSUE THREAD

**Issue by ToxicDK** [StrangeLoopGames/EcoIssues#22465] opened 2021-07-11 13:49 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. Put mining upgrade into arrastra
2. make work order
3. work orders still require same amount of resources

**Expected behavior:**
Required 40% less resources

**Actual behavior:**
Still requires 100% resources

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2021-07-11 16:38
Hi @ToxicDK 

Thank you for writing this bug report.
However, Arrastra's are designed that way. With Arrastra, the mining upgrade module works by reducing the crafting time only.
I'll be closing this ticket as the issue reported is by design.
Do feel free, however, to reply here or create a separate report if you have any form of suggestion.
Thank you and have a wonderful day.

**Closed by Daniel-Magulado** 2021-07-11 16:38 UTC
