### ISSUE TITLE
Storage UI Stockpile Duplication bug

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#7117] opened 2018-04-10 18:19 UTC
I have 2 stockpiles that are bugged a glass and a brick stockpile which show up as doubles in the storage ui.

when I try to consolidate the items into the stockpiles it duplicates the materials.

I'm currently trying to find a fix to remove the stockpiles that duplicate items any ideas would be appreciated

**Comment by ecoemmeck** [comment] 2018-04-11 05:33
after having some sleep i was able to figure out a fix for this problem.

i moved the items to new stockpiles and removed the original stockpiles the issue was that for some reason there was 2 stockpiles on top of each other I'm assuming this happened during a restart where it sometimes duplicates objects

this can probably be closed now

**Comment by metachronism** [comment] 2018-07-12 04:29
closing as dupe of the stockpile/object duplication bug #5895

**Closed by metachronism** 2018-07-12 04:29 UTC
Labels: Medium Priority, Respond ASAP
