### ISSUE TITLE
USER ISSUE: Erth Reset

### ISSUE THREAD

**Issue by saljack86** [StrangeLoopGames/EcoIssues#6169] opened 2018-03-17 00:21 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
I noticed that the lawn is going to be grounded if you have a cane pill underground. when the stockpill's are filled with earth they overgrow with grass. I think the problem is that rasento the top should be to earth. Restrict it on the hittbox and the problem should be solved. Since I have a warehouse under my house it looks very bad in the garden.

**Expected behavior:**
Erth Reset: Restrict it on the hittbox

**Actual behavior:**
Erth Reset: to the top

**Comment by MarjieAVolk** [comment] 2018-03-19 18:20
I'm not sure if I understand.  Sounds like you have grass growing on top of your stockpile?  Is that the only issue?

**Comment by saljack86** [comment] 2018-03-20 18:31
sorry I'm from Germany. I do not speak English very well. The problem is not the grass on the stockpill. but I do an action on this stockpill. change the grass to erth. that's rigth. but my stockpill is in a cellar under the house and the grass outside over the stockpill change too.



Von meinem Samsung Galaxy Smartphone gesendet.

-------- Ursprüngliche Nachricht --------
Von: MarjieAVolk <notifications@github.com>
Datum: 19.03.18 19:20 (GMT+01:00)
An: StrangeLoopGames/EcoIssues <EcoIssues@noreply.github.com>
Cc: saljack86 <saljack@hotmail.de>, Author <author@noreply.github.com>
Betreff: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Erth Reset (#6169)


I'm not sure if I understand. Sounds like you have grass growing on top of your stockpile? Is that the only issue?

**Comment by MarjieAVolk** [comment] 2018-03-20 18:40
Oh, so the problem is you are trampling the grass underground, but the grass above ground is what actually gets trampled?

**Comment by saljack86** [comment] 2018-03-20 18:58
yes the problem is the grass above the ground. But the trigger is the stockpile in the underground. if I put earth in or out the stockpill.


Von meinem Samsung Galaxy Smartphone gesendet.

-------- Ursprüngliche Nachricht --------
Von: MarjieAVolk <notifications@github.com>
Datum: 20.03.18 19:40 (GMT+01:00)
An: StrangeLoopGames/EcoIssues <EcoIssues@noreply.github.com>
Cc: saljack86 <saljack@hotmail.de>, Author <author@noreply.github.com>
Betreff: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Erth Reset (#6169)


Oh, so the problem is you are trampling the grass underground, but the grass above ground is what actually gets trampled?

**Comment by MarjieAVolk** [comment] 2018-03-20 19:07
Okay, I think I understand now.  Thanks.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5101.

Any activities that you do (such as picking up or putting down blocks) can contribute to 'trampling' the grass.  Right now the grass on top will get trampled even if you are doing things below it.

**Closed by MarjieAVolk** 2018-03-20 19:07 UTC
Labels: Low Priority
