### ISSUE TITLE
USER ISSUE: Wainwright placement bug

### ISSUE THREAD

**Issue by GibsonSWE** [StrangeLoopGames/EcoIssues#3919] opened 2018-02-05 12:40 UTC
**Version:** 0.7.0.2 beta

**Expected behavior:**
It should be placed where the ghost is displayed (which is displayed wierdly)

**Actual behavior:**
Instead it gets placed further away and becomes unusable and unclickable...

**Comment by Bazzi89** [comment] 2018-02-05 16:04
Check, same here!

**Comment by Nanders** [comment] 2018-02-05 18:29
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3911

**Closed by Nanders** 2018-02-05 18:29 UTC
