### ISSUE TITLE
using unstuck can jam you in a table in the open and wont work again #4c637828

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2250] opened 2017-09-22 22:40 UTC
i have had this happen to me and also another player (so its not just me) in a river we Unstuck to the surface  above and got jammed inside a table (workbench and also a bloomery) these are the only tables NOT in a room so we wouldnt have appeared on a roof, we then tried to use unstuck again, wouldnt work, only way to get free is to remove the table

**Comment by Conchipedia** [comment] 2017-09-22 22:40
to bypass this happening again, we now have brick placed above the tables

**Comment by MarjieAVolk** [comment] 2017-09-22 22:42
Think this is a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/872

**Closed by MarjieAVolk** 2017-09-22 22:42 UTC

**Comment by Conchipedia** [comment] 2017-09-22 22:54
ok, i normally search, didnt notice that far back

**Comment by MarjieAVolk** [comment] 2017-09-22 22:55
Yeah it's kind of a weird bug I guess.  Been a problem for a long time O.o
