### ISSUE TITLE
USER ISSUE: Teleporting Glitch

### ISSUE THREAD

**Issue by BrockForsythe** [StrangeLoopGames/EcoIssues#24994] opened 2024-07-03 16:07 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Placed items in tiny stockpile while standing on the stockpile.

**Expected behavior:**
Pushed me up above the placed items or to the side of the stockpile

**Actual behavior:**
Sent me from Y level 72 to Y level 13. I'm now stuck below the surface in a random cave.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-07-03 21:41
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24352

**Closed by D3nnis3n** 2024-07-03 21:41 UTC
