### ISSUE TITLE
USER ISSUE: Cann't interact with the world anymore

### ISSUE THREAD

**Issue by Yodaluc** [StrangeLoopGames/EcoIssues#23970] opened 2023-08-14 11:24 UTC
\
**User Id: (slg143992)**
**Version:** 0.10.0.0 beta playtest-91

**Steps to Reproduce:**
test on 2 public server :
1. Place start camp
2. Remove property post
3. Place property post somewhere

**Expected behavior:**
Remover property then create a new one

**Actual behavior:**
Remove property then when placed, the post totaly disapeared. Then i lost all the control over the world, i can do nothing but walk or leave the server and start playing on another one.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i don't think so

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2023-08-24 19:57
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23931

**Closed by Daniel-Magulado** 2023-08-24 19:57 UTC
