### ISSUE TITLE
Giant text can be put in signs

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8069] opened 2018-06-15 18:00 UTC
Sign text is: <size=9999>卐 卍</size>
![image](https://user-images.githubusercontent.com/3536496/41482701-441eeb76-708b-11e8-8341-44c4314b5260.png)

**Comment by MarjieAVolk** [comment] 2018-06-15 18:15
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8046

**Closed by MarjieAVolk** 2018-06-15 18:15 UTC
Labels: Critical Priority
