### ISSUE TITLE
Link between Game and Web Interface ?

### ISSUE THREAD

**Issue by Twelve57** [StrangeLoopGames/EcoIssues#5455] opened 2018-03-06 01:42 UTC
Hi, 
I've bought the game on steam and also rented a nitrado server to play with my friends.
Everything looks fine but the Government part doesn't work at all.

- When I'm in game and I click on Government, "View Data", "Run For Office" and "Propose Law" are completely broken, if I click nothing happened.

- I've got the same problem in the Web Interface (World Status, Elections, Laws), I've tried with safari, chrome and firefox. I cannot even login. 
When I click on something I've got the message : "You must access from the game server" 

It's like ECO doesn't allow my steam ID to use the Web Interface in/out the game.
I've tried to clear the current law after getting admin permissions but no change.

PS : it's the same for my friends and people in my server session. (all steam players)

Do you have any solution for me ?
Thanks for helping !

**Comment by MarjieAVolk** [comment] 2018-03-06 01:54
So when you click on 'Propose Law' for example; you say nothing happens.  Is it possible that your browser is opening behind the game, and you didn't see it?  (All these buttons send you to the browser)

If you are sure it is doing nothing, after you click the button and nothing happens, send me your client log file at 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'.

I have never seen the error message you gave ("You must access from the game server") - unless that is a paraphrase?  You should be able to view the world status without logging in, and just proposing/editing things would require you to log in.

**Comment by MarjieAVolk** [comment] 2018-03-06 02:08
Okay, I see.  So here's a thought, do you have any special characters in your username?

**Comment by Twelve57** [comment] 2018-03-06 02:16
Nope my username is "Twelve".

- I have also this issue :
<img width="1228" alt="screen1" src="https://user-images.githubusercontent.com/12710466/37010588-85d952d4-20ec-11e8-9bf0-58ae1e47a2f7.png">

- And so I can't login here and have the message : 
<img width="1273" alt="screen2" src="https://user-images.githubusercontent.com/12710466/37010615-a910a568-20ec-11e8-8b7d-4cd987145052.png">

**Comment by MarjieAVolk** [comment] 2018-03-06 02:20
Yeah steam linking is disabled for linking from a steam account with a purchase to an slg account with no purchase.  This was because some people had found a way to get the game for free this way.  We are working on closing this security loophole before we re-enable it.  That should not prevent you from playing.

So random other guesses - do you maybe not have a default browser configured on your machine?  Or are your machine's browser preferences somehow weird?  Or maybe a firewall or anti virus software is blocking your browser from opening?

**Comment by Twelve57** [comment] 2018-03-06 02:41
Ok thanks.

So I've checked everything on my computer. Reinstalled firefox. Nothing changes.
Firewall allows steam and ECO.

It's only happened with ECO, I don't have any problem with other steam games, star citizen or battle net.

At this point, I cannot access to the Government part by using the browser only or by clicking in the panel while I'm in game...

**Comment by MarjieAVolk** [comment] 2018-03-06 02:45
Okay, I just realized you said this is happening for all of your friends too.  If you join a different server, are you able to use government features on it?  Also, might be related - what language is your computer set to?

**Comment by MarjieAVolk** [comment] 2018-03-06 18:20
I thought I had repro'ed this, but after re-logging I was able to use law features again.  So yeah, I'm able to use law features when logged in via steam.

Do you have 'Require Authentication' turned off on your server or anything?

**Comment by alecpura** [comment] 2018-03-12 20:40
From a ticket received from maxime.petit.57@gmail.com:

Hi, 

I've started to rent a server for ECO few hours ago, and I still have an annoying problem with the Web Interface.

I rent a nitrado server, everything works fine, I'm online with a friend like expected (during 4 hours)
The problem is my friend and I cannot access to the World Status, Elections and Laws sections. We can't login in the web interface, the login process take 1 minutes and abort itself.

**Comment by pamduncan** [comment] 2018-03-22 00:41
This is usually a hosting service issue.  We have had this issue at killservers and it an issue the hosting service has to resolve

**Comment by rainfarmer** [comment] 2018-04-11 22:40
This should be fixed in the newest version of Eco.
It was an issue on firefox.
let me know if its still not working.

**Closed by rainfarmer** 2018-04-11 22:40 UTC
Labels: Medium Priority
