### ISSUE TITLE
USER ISSUE: Placing Hewn Log Wall ontop of another makes it dissapeard

### ISSUE THREAD

**Issue by IsakViste** [StrangeLoopGames/EcoIssues#6039] opened 2018-03-14 13:59 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1. Place Hewn Log Foundation
2. Place Hewn Log Walls ontop of Foundation
3. Place Hewn Log Wall ontop of previously placed wall
4. Some walls will not appear, but Hewn Logs will be used from my "carry inventory"
5. Breaking Hewn Log Walls will give me back (some of) the placed Hewn Logs that dissapeared

The wall is not invisible, but actually not placed, because I can walk where I tried to place the wall.

**Expected behavior:**
It should be placed and visible.

**Actual behavior:**
Instead it doesn't get placed, but I lose Hewn Logs from my inventory (carrying)

**Comment by MarjieAVolk** [comment] 2018-03-16 01:39
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5906

**Closed by MarjieAVolk** 2018-03-16 01:39 UTC
