### ISSUE TITLE
fast digestion (food , stomach)

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#539] opened 2016-07-26 22:39 UTC
http://ecoforum.strangeloopgames.com/topic/810/potential-digestion-glitch-extremely-fast-digestion

**Comment by jhadred** [comment] 2016-08-01 11:11
More info:
1)  Digestion takes 48 hours from time eaten.  Each item has it's own timer. 
2) Instead of single item digesting at 48 hours (approxmate timer).  All foods of that type are digested.
This impacts all foods and does not matter if there are different kinds of food within stomach.

To reproduce issue:
-Eat any chosen type of food(s) repeatedly for one day:  Example:  Eat 'foodx' and/or 'foody' every 30 minutes starting at 9am.  Assume we now have 20 eaten.
-at 47 hours at 8am:  20 are still in the stomach
-at 48 hours at 9am: 0 are in the stomach of the chosen types.  The first eaten food has cleared all types.
-eat the same foodx and foody at 9:01.  Can eat multiple of the type.  
-at 9:30am the stomach is empty, the calories are at where they were after eating the foods, the skill gain is zero.
-eat foodx and/or foody again
-at 10 am stomach is empty again.
- If instead foodx, foody and new foodz are eaten at 9:01, foodz will remain.

Impacts laborers (anyone that uses calories) the most due to having multiple items eaten.
Less Impact on characters that do not use calorie work as they may have 1 of each high value item eaten at 12 hour intervals and therefore after the inital 48 hour digestion would see the emptying of stomach contents.

Current Workarounds:  
a) do no labor, eat at defined intervals
B) Eat one type of food for one day or two.  When digests, switch to different type of foods for two days.  Alternate every 48 real hours..

**Comment by metachronism** [comment] 2016-10-17 18:29
this is fixed in alpha5

**Closed by metachronism** 2016-10-17 18:29 UTC
Labels: bug
