### ISSUE TITLE
USER ISSUE: Can not move objects: Pumpjack

### ISSUE THREAD

**Issue by Ki-Tan2934** [StrangeLoopGames/EcoIssues#24817] opened 2024-03-08 10:55 UTC
\
**User Id: (slg181583)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Move an Oil pump jack over 60M

**Expected behaviour:**
Uses cal to move the object

**Actual behaviour:**
Can't move objects

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and probs

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/58880823/d63ee355-f776-4284-a7a9-898591a7ca90)

**Comment by D3nnis3n** [comment] 2024-03-08 11:47
The screenshot is unfortunately insufficient, as the rest of your HUD isn't visible. I'm able to move objects fine, as long as the movement is between the distance and calorie limit. The error in your screen says that you don't have enough calories. In your issue report you also say you try to move it over 60m (which is outside the distance limit), but in the screenshot it shows just 14,9m.

Can you provide a screenshot that is more clear on what the problem is?

**Comment by Ki-Tan2934** [comment] 2024-03-08 12:51
I will, but if you look at the bottom it says it uses 745 calories out of 4615 and it still says too hungry to move.

I also di not move it 60M I moved it multiple times to about 60M away from original pos

**Comment by Ki-Tan2934** [comment] 2024-03-08 12:53
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/58880823/00c96537-606d-477b-b3a1-669115d7907c)
Here @D3nnis3n

**Comment by Ki-Tan2934** [comment] 2024-03-08 12:59
So might have to do lots of small movements

**Comment by Ki-Tan2934** [comment] 2024-03-08 14:36
No one can move it if that helps

**Comment by D3nnis3n** [comment] 2024-05-19 01:02
We've unfortunately even after multiple tries not been able to recreate this issue on a vanilla installation and so far have not received any further reports on this matter. I'm hence closing this issue. If you can still reproduce the issue in Update 10.2.4, please open a new issue - we might need access to you server then, though.

**Closed by D3nnis3n** 2024-05-19 01:02 UTC
Labels: Status: Not reproduced
