### ISSUE TITLE
You can sell more items than you have and still get paid

### ISSUE THREAD

**Issue by LucasGod27** [StrangeLoopGames/EcoIssues#11200] opened 2019-02-09 03:53 UTC
Version: 0.8

It's possible to sell more items than you have on stores.

Step 1. Find a Store that buys a lot of a certain item
Step 2. Get one of said item
Step 3. Open store menu
Step 4. Type in a high value on the sell ammount, such as 200
Step 5. You sell 1 item, the buyer gets 1 item, but you get paid for 200 items.

**Comment by elfl0rd** [comment] 2019-02-09 07:38
Duplicate of #11140

**Closed by elfl0rd** 2019-02-09 07:38 UTC
