### ISSUE TITLE
Massive Lag build up 6.1.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2863] opened 2017-11-19 23:58 UTC
Playing on same server Machine, in a smaller world (we have had bigger worlds before) with my Same PC (no settings changed at all either server side or PC side) No different Graphic updates for My PC, but after a short period of time we are experiencing severe lag, it just gets worse and worse until the server either decides to crash or players leave, and we have had on the server a lot more than we have had now, so not sure whats causing this.

**Comment by juur** [comment] 2017-11-20 11:30
Similar (but different) experience on my server. Again, no change other than the version running, intermittent lag lasting 10-20 seconds during which time server responds extremely slowly. Sometimes results in disconnections. Happens periodically (maybe 5-15 minutes apart) but not with regularity.

**Comment by Conchipedia** [comment] 2017-11-20 11:51
we did a little test on our other server running same Game Version (6.1.1) with just 3 players and the Admin, 2 of us was just mining a few stone/ore and then stopping, then starting up again and we noticed a significant lag the more we did mining, this was also happening when chopping trees and logs.
The only conclusion we could come to was that the rubble was somehow causing the lag (this by the way was on a brand new world, with nothing else being crafted)

**Comment by MarjieAVolk** [comment] 2017-11-20 19:21
Sounds like duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2731.  We've been getting lots of complaints about that, hopefully that can get prioritized

**Closed by MarjieAVolk** 2017-11-20 19:21 UTC
Labels: Medium Priority
