### ISSUE TITLE
USER ISSUE: Single-Player Load Game showes only 3 slots

### ISSUE THREAD

**Issue by Geisterlein** [StrangeLoopGames/EcoIssues#5970] opened 2018-03-12 21:45 UTC
**Version:** 0.7.2.3 beta

In the load screen you can only select the first 3 save games for single player - there should be some scrollbar to load other games

**Comment by MarjieAVolk** [comment] 2018-03-13 21:48
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5442

**Closed by MarjieAVolk** 2018-03-13 21:48 UTC
