### ISSUE TITLE
[9.0.2] When revising an elected title while granting it powers through constitutional amendment, both disappear

### ISSUE THREAD

**Issue by nichlas0010** [StrangeLoopGames/EcoIssues#18379] opened 2020-09-21 17:15 UTC
We created a title (Legal Minister) which was approved by election, but since it was using an unapproved voting system, we had to have a second election to actually activate it by switching to another voting method. 

When the first election was done, a constitutional amendment election was made to grant this title the powers to draft laws at the same time as the election to activate it.

After both elections were done, the elected title disappeared from government office, and the amendment disappeared from the amendments table, but are both still in effect, unrevisable, although they can be viewed in the government (L) tab.

See screenshots:

Government office missing title:
![image](https://user-images.githubusercontent.com/20558591/93798712-06c18200-fc36-11ea-9a6b-44d6613c726f.png)

Amendment missing:
![image](https://user-images.githubusercontent.com/20558591/93798803-28226e00-fc36-11ea-8b9e-b280e934d232.png)

Amendment present in the government tab:
![image](https://user-images.githubusercontent.com/20558591/93798902-4d16e100-fc36-11ea-9a53-99f5be189dd1.png)

Title present in the government tab:
![image](https://user-images.githubusercontent.com/20558591/93798983-6a4baf80-fc36-11ea-8649-c2a8812f33c3.png)

**Comment by SlayksWood** [comment] 2020-09-22 12:05
@nichlas0010 Thank you for the report. We need some additional information.
1. Do you use any admin commands?
2. Can you provide log files when it happened? or will happen next time.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
3. How often does this happen to you?
We have issue with this problem #16601, but we can't reproduce it(

**Comment by nichlas0010** [comment] 2020-09-22 13:47
1. No admin commands were used AFAIK, and the host said that all legal configs are default templates.
2. I don't have the log files from when it happened, sorry.
3. Only happened this once, all other titles and amendments work fine. 

The game does seem to know the title's not proper:
![image](https://user-images.githubusercontent.com/20558591/93890540-59587800-fce2-11ea-9987-4dfc21bcf054.png)
Restarting the server fixed the amendment but the title is still absent from the government

**Comment by SlayksWood** [comment] 2020-09-23 08:33
@nichlas0010 thak you for the information. Merged to #16601

**Closed by SlayksWood** 2020-09-23 08:33 UTC
Labels: Status: Needs Information
