### ISSUE TITLE
Waypoints stuck on the other other side of the world

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#5839] opened 2018-03-10 14:17 UTC
walkeed around the planet multiple times and the markers did not refresh, i needed to walk the way back until they reset

sometimes they return when i am alsmot under the marker position

it seems there is something very location specific on when the markers ar updating

**Comment by MarjieAVolk** [comment] 2018-03-12 22:54
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5481

Looks like that was marked as fixed today, so should be fixed in the next release.  (For now, to help you play - they are confused by the '0' border.  They will show you the fastest route that does not cross '0' in either direction)

**Closed by MarjieAVolk** 2018-03-12 22:54 UTC

**Comment by mindforger** [comment] 2018-03-13 06:13
haha :) classic
