### ISSUE TITLE
Sometimes dragging items into work orders does not work

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3990] opened 2018-02-06 19:19 UTC
Selecting and right clicking succeeds though.

**Comment by MarjieAVolk** [comment] 2018-02-06 22:18
Yeah this one has been plaguing me for a long time :'( Can never repro when I need to

**Comment by MarjieAVolk** [comment] 2018-02-06 22:19
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3010

**Closed by MarjieAVolk** 2018-02-06 22:19 UTC
Labels: Medium Priority
