### ISSUE TITLE
USER ISSUE: Wheat grow when you move soil

### ISSUE THREAD

**Issue by Arkadia3** [StrangeLoopGames/EcoIssues#4382] opened 2018-02-12 12:01 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
I don't know is it bug, but I notice that my wheat looks like that doesn't grow but when I dig soil near or use hoe near seeds, they suddenly change and looks more mature

**Expected behavior:**

**Actual behavior:**

**Comment by ecoemmeck** [comment] 2018-02-12 12:04
I used to see this happening in alpha 5 i think it's just that the plants aren't updating through there growth cycle till a user interacts with a nearby object

**Comment by Arkadia3** [comment] 2018-02-15 12:28
Btw, I noticed that the problem applies to all plants - berries, beets, wheat, all do not update their maturity, until you do something near them.

**Comment by knexer** [comment] 2018-02-23 23:09
This is because the chunks aren't pushed to players when plant growth/yield is modified here: https://github.com/StrangeLoopGames/Eco/blob/master/Server/Eco.Simulation/WorldLayers/Pushers/PlantGrower.cs#L56

Can look at PlantSpawner to see an example of how it should work.

**Comment by D3nnis3n** [comment] 2018-10-30 20:32
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3170

**Closed by D3nnis3n** 2018-10-30 20:32 UTC
Labels: Medium Priority
