### ISSUE TITLE
USER ISSUE: utilisation de commande

### ISSUE THREAD

**Issue by Ravenfr31** [StrangeLoopGames/EcoIssues#24415] opened 2023-12-28 15:56 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**

**Expected behavior:**
creation d'un ville

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Server encountered an exception:

<size=60,00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.SettlementSpawnHelper.GetChildCount(Int32 settlementType)
   at Eco.Gameplay.Se</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-28 16:38
Needs the full log and reproduction steps.

**Comment by D3nnis3n** [comment] 2024-01-11 18:24
Closing due to no further information provided.

**Closed by D3nnis3n** 2024-01-11 18:24 UTC
Labels: Status: Needs Information
