### ISSUE TITLE
USER ISSUE: Duplicate tables after placement.

### ISSUE THREAD

**Issue by ph4n70m** [StrangeLoopGames/EcoIssues#7709] opened 2018-05-11 02:29 UTC
**Version:** 0.7.4.2 beta

**Steps to Reproduce:**
Crafted a wairight table after placing it there is still a wainright table in my inventory. It also happened with the research table. I was then able to place the duplicate in a chest.

**Expected behavior:**
should not have remaind in my inventory after placement.

**Actual behavior:**
After placing it there is still a wainright table in my inventory. It also happened with the research table.

<details>
<summary>Log File</summary>(...previous log truncated...)

 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> PasswordRequest
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PasswordRequest -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(File

**Comment by metachronism** [comment] 2018-07-12 05:06
closing as dupe of #5895 (duped world object issues)

**Closed by metachronism** 2018-07-12 05:06 UTC
Labels: Medium Priority
