### ISSUE TITLE
Picking up a log while cutting it sometimes eats the whole tree

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#7661] opened 2018-05-09 19:25 UTC

**Comment by elfl0rd** [comment] 2018-05-09 19:43
if you fast clicking E on cutting.
if you press and hold E on cutting.

and
tree periodically returns after server restart.

**Comment by WeaselDog** [comment] 2019-11-13 20:07
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7661 and seems fixed

**Closed** 2019-11-13 20:17 UTC
Labels: Medium Priority
