### ISSUE TITLE
Block placement shadow is not transparent enough, cant tell difference when placing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3436] opened 2018-01-16 20:26 UTC
This is an unplaced block:
![image](https://user-images.githubusercontent.com/3536496/35010663-761b8f74-fab8-11e7-83c2-33e4a28a9c72.png)

**Comment by MarjieAVolk** [comment] 2018-01-16 20:32
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3239

**Closed by MarjieAVolk** 2018-01-16 20:32 UTC
