### ISSUE TITLE
Master: no "Title Assignments" and "Authorization Settings" in registrar and bank

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10242] opened 2018-12-09 08:38 UTC
If you select anything in top section, you see nothing in down section.

**Comment by D3nnis3n** [comment] 2018-12-09 16:58
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10218 - added to that issue.

**Closed by D3nnis3n** 2018-12-09 16:58 UTC
