### ISSUE TITLE
USER ISSUE: No response from auth server is:open 

### ISSUE THREAD

**Issue by SpitefulFennec** [StrangeLoopGames/EcoIssues#24854] opened 2024-03-31 14:10 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
1. Create local server on PC. 2. Play several days. 3. Close server due night. 4. Try to start server again

**Expected behavior:**
Start server and connect to it

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14816180/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14816181/Player.log)

**Comment by D3nnis3n** [comment] 2024-04-01 16:25
What is the range of your computers public IP? Need first and second field, e.g. 123.123.X.X.
Please post in issue https://github.com/StrangeLoopGames/EcoIssues/issues/24850, which this is a duplicate of.

**Closed by D3nnis3n** 2024-04-01 16:25 UTC
