### ISSUE TITLE
No voting for removing someone from office

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17438] opened 2020-07-31 15:32 UTC
It seems like the supreme court that can remove a president from office can not do so by a majority vote of the three, but the members are only able to remove him from office by themselves - each one can alone.

**Comment by WeaselDog** [comment] 2020-10-13 03:31
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14290

**Closed by WeaselDog** 2020-10-13 03:31 UTC
Labels: Category: Laws, Priority: Medium, Type: Feature
