### ISSUE TITLE
USER ISSUE: Repair station clipping

### ISSUE THREAD

**Issue by TammasDexter** [StrangeLoopGames/EcoIssues#4620] opened 2018-02-16 04:01 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Acquire repair station
2. Attempt to place the repair station with any part of it clipping through solid blocks (hewn logs, dirt etc.)

**Expected behavior:**
Failure to place the repair station along with the appropriate 'Cannot place because blocked' message.

**Actual behavior:**
The Repair station is placed with part of it clipping through the solid blocks.

**Comment by MarjieAVolk** [comment] 2018-02-16 19:15
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4221

**Closed by MarjieAVolk** 2018-02-16 19:15 UTC
