### ISSUE TITLE
USER ISSUE: Crash to Menu

### ISSUE THREAD

**Issue by MittenMarauder** [StrangeLoopGames/EcoIssues#6129] opened 2018-03-16 03:11 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Unknown. Was digging sand and dumping into a stockpile.

**Expected behavior:**
Not crash

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Simulation.Agents.AI.AITarget.<UpdatePosition>b__32_0()
   at Eco.Shared.Utils.LockUtils.TryLock(Object lockObject, Action ifLockAcquired, Int32 millisecondsTimeout)
   at Eco.Simulation.Agents.AI.AITarget.UpdatePosition()
   at Eco.Simulation.Agents.AI.AITarget.get_Position()
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-20 22:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5871

**Closed by MarjieAVolk** 2018-03-20 22:29 UTC
