### ISSUE TITLE
USER ISSUE: Woodcard driving alone

### ISSUE THREAD

**Issue by LostRune** [StrangeLoopGames/EcoIssues#6200] opened 2018-03-17 18:36 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Walk on asphalt with a woodcard.
Let it go while moving.

**Expected behavior:**
stop or at least don't go crazy

**Actual behavior:**
It drives forever, even uphill.

**Comment by Epimetheus89** [comment] 2018-03-17 21:10
I think this is a duplicate of #6104

**Comment by SeanAtr0n** [comment] 2018-03-21 19:42
Fixed 7.3

**Closed by SeanAtr0n** 2018-03-21 19:42 UTC
