### ISSUE TITLE
USER ISSUE: Arrow trajectory not showing with water

### ISSUE THREAD

**Issue by Ardy-LvX** [StrangeLoopGames/EcoIssues#4745] opened 2018-02-18 01:54 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Aim a charged bow at the water.

**Expected behavior:**
Should show trajectory of arrow.

**Actual behavior:**
It doesn't show where the arrow will go.

**Comment by cuda70** [comment] 2018-02-18 17:04
Or sand or yellow dirt

**Comment by D3nnis3n** [comment] 2018-10-30 20:46
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9775

**Closed by D3nnis3n** 2018-10-30 20:46 UTC
Labels: Medium Priority
