### ISSUE TITLE
USER ISSUE: Commants not work on server

### ISSUE THREAD

**Issue by Ferisu** [StrangeLoopGames/EcoIssues#5171] opened 2018-02-27 11:14 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Value cannot be null.
Parameter name: key


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

```

**Comment by MarjieAVolk** [comment] 2018-02-27 18:44
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4391

What is most likely happening is that you are not passing the correct arguments for the chat command.  Use '/help commandname' to figure out what parameters it wants.

**Closed by MarjieAVolk** 2018-02-27 18:44 UTC

**Comment by Ferisu** [comment] 2018-02-27 22:30
i can´t do this because my game crash instant when i type in any command.

**Comment by MarjieAVolk** [comment] 2018-02-28 22:26
Really, any command?  How about something simple like /unstuck?  Do you have the same problem on other servers?

If it is something unique to your save file, can you send over your save file?
