### ISSUE TITLE
[8.0.0 Steam Build] Weird Overlay on the bottom right Menu

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10673] opened 2019-01-15 10:44 UTC
![weirdoverlay](https://user-images.githubusercontent.com/25908592/51175542-e8c94900-18ba-11e9-9fd6-a14c5f0e4e2c.png)

**Comment by elfl0rd** [comment] 2019-01-15 10:56
Duplicate of #10602

**Closed** 2019-01-16 19:08 UTC
Labels: Quality Assurance
