### ISSUE TITLE
Ramp speed randomly goes to 0

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10798] opened 2019-01-21 13:53 UTC
https://drive.google.com/open?id=1SqVqZt87KFXbPwr7aBrMPT_9agbWXCaC

If you watch the UI in the bottom left, the speed sometimes changes to 0 which momentarily stops the cart, then changes back to 1 and I can move freely again.

**Comment by elfl0rd** [comment] 2019-01-21 14:19
Duplicate of #5532

**Closed** 2019-01-21 14:21 UTC
Labels: Low Priority
