### ISSUE TITLE
USER ISSUE: Hovering over "math operation result" on a sidebar message does not work

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22620] opened 2021-08-31 11:55 UTC
Steps to Reproduce:

1. Create a law that runs on "Chat Sent". Set the "Then" action to "Send Notice" with the "Notification Type": "Sidebar message", "Send To": "Citizen" and the "Value to display" to "Arithmetic" and add any arithmetic you want.
2. Send the chat message to get the notification.

Expected Behavior:

You can hover over the "(math operation result)" in the sidebar to see how the calculation was done. This works when the notification type is "Basic Notification".

Actual Behavior: 

When you hover over "(math operation result)", the popup is of the user that received the message, not the details of the math operation.

**Comment by Daniel-Magulado** [comment] 2021-09-04 16:24
Hi @Azzurite 

Thank you for writing this bug report. However, we are unable to reproduce it on our side.
It's working as intended.
![image](https://user-images.githubusercontent.com/77248866/132101547-aced85e4-a0ee-41fa-911e-0c2274a4ec1d.png)

Can you provide a screenshot here? Also, if you can reproduce the issue, please provide your game logs including the complete specification your PC as well as the operating system.

**Comment by Azzurite** [comment] 2021-09-06 10:45
@Daniel-Magulado 

Sorry, I just noticed how it happens: the message has to be very long (I tested with maximum length), and it only happens when having the notifications clicked and in a sidebar, not when the notification just pops up:

https://youtu.be/fHacPLZwBOw

**Comment by Daniel-Magulado** [comment] 2021-09-06 17:38
Hi @Azzurite 

Thank you for providing clarification and a recorded video.
I was able to reproduce it.
I've created an internal report.

[ClickUp Report](https://app.clickup.com/t/10591183/ECO-14931)

**Comment by WeaselDog** [comment] 2022-04-27 05:16
Thanks for you report. This will be fixed in the upcoming 9.5 update.

**Closed by WeaselDog** 2022-04-27 05:16 UTC
Labels: Category: UI
