### ISSUE TITLE
Brick blocks not displaying correctly

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7363] opened 2018-04-24 03:46 UTC
From a Steam comment (https://steamcommunity.com/app/382310/discussions/4/3288067088117724782/):

https://steamcommunity.com/sharedfiles/filedetails/?id=1366419888

Reload of the game not fix it, but i ask for a server restart.
This problem is only with brick-blocks. When i set the normal block or the pillar block (1 height) next to a full block.

https://steamcommunity.com/sharedfiles/filedetails/?id=1367757050

**Comment by metachronism** [comment] 2018-04-24 20:42
closing as dupe of #4286

**Closed by metachronism** 2018-04-24 20:42 UTC
Labels: Medium Priority
