### ISSUE TITLE
CW API not using correct gs versions on /start

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19836] opened 2020-12-23 19:50 UTC
When you use /start and pass a version like '0.9.1.9-beta'
It will incorrectly start a world with version '0.9.1.9 beta release-136'

This error probably also applies to /upgrade

Pretty sure this is a new issue, so likely related to one of your commits.

You may need updated filtering for versions.
The one @denysaw used for auto update, filters by string length

**Comment by redwyre** [comment] 2021-01-05 14:02
repeated what I said in chat:
> "0.9.1.9-beta" is the download name for the build "0.9.1.9-beta release-136"
> there are many "0.9.1.9-beta release-XXX" builds (think of them as release candidates), and one final "0.9.1.9-beta" build which is just a copy of the release build that passes QA
> the image name for production builds are not the same as the version reported from the game, you can't assume they're the same (this changed in the last 6 months to allow us to identify release deployment issues)

**Comment by redwyre** [comment] 2021-01-05 14:06
I'm going to close this as it's currently working as intended, but we can continue discussion about how to deal with it on the accounts side

**Closed by redwyre** 2021-01-05 14:06 UTC
Labels: Category: Cloud Worlds, Priority: High
