### ISSUE TITLE
[0.9.3.3] Signs should use a higher-res version of icons

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21786] opened 2021-05-05 22:12 UTC
It's really neat seeing the various game icons appear on signs. However, those were designed to be mostly UI elements and can get quite pixellated up-close:

![image](https://user-images.githubusercontent.com/964559/117216139-261bb280-adb4-11eb-8131-829217154215.png)

It might be nice to have some higher-res version of those icons for the use on signs. Maybe they would even dynamically adjust based on distance and the size of the sign?

**Comment by IcedForge** [comment] 2021-05-06 12:34
Thanks you for reporting stuff as always! Will close this as duplicate of #18934

**Closed by IcedForge** 2021-05-06 12:34 UTC
