### ISSUE TITLE
USER ISSUE: Seeing Myself then boom

### ISSUE THREAD

**Issue by M1r077** [StrangeLoopGames/EcoIssues#4503] opened 2018-02-14 08:58 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
1. Beeing disconnected , trying to reconnect
2. Conneting and see myself standing where I was when I was disconnected
3.Receiving the following message on client : see Actual Behavior box		
4.The server crashed	

**Expected behavior:**
It shouldn't happen 	

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-14 21:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4222

It sounds like your experience is a little different than what I was expecting for this error though - you got the error on the client, and then afterwards the server crashed?

**Closed by MarjieAVolk** 2018-02-14 21:40 UTC
