### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Duchue01** [StrangeLoopGames/EcoIssues#5643] opened 2018-03-08 01:56 UTC
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-08 22:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-08 22:29 UTC
