### ISSUE TITLE
[Beta 8.1.4] Combustion Generator + Waste Filter produces endless Sewage.

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#12225] opened 2019-05-08 13:43 UTC
When a combustion engine is connected to a waste filter there is continuous generation of sewage, we produced tons of compost over night, even though the combustion generator was out of fuel.

**Comment by johnkslg** [comment] 2019-05-08 16:01
@mirasrael can you help figure out a good solution for this issue.

Problem is this: when flow is low, disabling the world object will stop flow entirely. Then flow will be high enough, so it will enable. It repeats this indefinitely.

**Comment by otting** [comment] 2019-05-08 16:22
My suggestion is to remove the sewage system from the generator completely, I don't know of any generator who uses such a system anyway.

**Comment by SlayksWood** [comment] 2019-05-09 03:58
merged with #12082, #11355

**Comment by SlayksWood** [comment] 2019-05-10 06:31
0.8.2.0 staging-5
Now the generator works like a Blast furnace. It's well. But when you fixed flow of water pump the endless cycle happens.
At the moment, if the Waste filter starts working from the generator, then at the completion of any crafting, the Generator continues to work. Because Waste Filter consumes energy of generator.
If the flow of the water pump were still broken, the generator is working properly.
![image](https://user-images.githubusercontent.com/45708377/57506412-6995d000-7304-11e9-83bf-200a883109ac.png)
![image](https://user-images.githubusercontent.com/45708377/57506438-7d413680-7304-11e9-9d16-52869b13e3ab.png)
![image](https://user-images.githubusercontent.com/45708377/57506475-8af6bc00-7304-11e9-8783-abbd04c27c6b.png)
![image](https://user-images.githubusercontent.com/45708377/57506503-a5c93080-7304-11e9-8f2b-51dc1a97b714.png)
![image](https://user-images.githubusercontent.com/45708377/57506530-b9749700-7304-11e9-96fa-7c091ef891c5.png)
After all the corrections It turned out that you can still make endless compost.
It fixed very easy in game. You need to put separate energy source for Waste Filter (like a wind turbine).
![image](https://user-images.githubusercontent.com/45708377/57506803-9b5b6680-7305-11e9-9d5c-61f774874e88.png)

Step to reproduce:
 - Put system: water pump, combustion generator, waste filter. 
 - Put, for example: Robotic Assembly Line.
 - Start any order at Robotic.
 - When order finished Combustion Generator disabled to save resourses. But it didn't.

**Comment by mirasrael** [comment] 2019-05-16 18:20
In PR fixed problem when Waste Filter active even when no liquid is flowing.
Problem with infinite loop (until out of resources) wasn't fixed though. It is intended behavior for now, we can review it for later. With current architecture it isn't possible to implement it in good way, I'm going to make system review though, but not as part 8.2.

**Closed** 2019-05-16 22:49 UTC
Labels: Fixed, Medium Priority, Push Candidate, QA
