### ISSUE TITLE
Pulling a Wooden Cart on totally Flat surface (Bedrock also Natural Stone) and getting stuck

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8974] opened 2018-08-15 20:28 UTC
**Version:** 0.7.6.3 beta

I have an Iron Ore Mine that is at bedrock (water level is 40, and Bedrock is 8 and 9) but i seem to have trouble Pulling the Cart on it (which shouldnt be a problem as it is a totally flat surface) sometimes its like i hit a dip or a bump and i stop
![snap2397](https://user-images.githubusercontent.com/29383891/44169941-c8a81a80-a0cd-11e8-8dc8-858090f8bbc1.png)

here is a Gif of it happening
![eco 15_08_2018 21_05_02](https://user-images.githubusercontent.com/29383891/44171047-2ab64f00-a0d1-11e8-8206-a354b7fb6ec4.gif)
also the original Video in a zip
[Eco 15_08_2018 21_05_02.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2291571/Eco.15_08_2018.21_05_02.zip)

also another video in another place
[Eco 15_08_2018 21_18_06.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2291595/Eco.15_08_2018.21_18_06.zip)
Only way i know how to reproduce this is to get down to bedrock using Devtool and making a mine

it is really annoying as at times i can't go any further forward (i have to push cart backwards, which sometimes in a narrow pathway it goes a bit haywire against the walls)

**Comment by GophTheGreat** [comment] 2019-06-04 05:15
Best guess is that it was caused by different materials not being exactly flat to each other? Anyway, I can't reproduce it anymore. Closing this for now.

**Closed by GophTheGreat** 2019-06-04 05:15 UTC
Labels: Medium Priority
