### ISSUE TITLE
0.9.0 staging-1511 Grassland biome

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15784] opened 2020-04-14 21:40 UTC
Version: 0.9.0 staging-1512

There are to few trees in grassland,there are more in desert which make no sense to me

**Comment by SlayksWood** [comment] 2020-04-15 08:36
I assume it's intended behavior
@WeaselDog @StanKryvenko 
What do you think?

**Comment by mirasrael** [comment] 2020-04-15 08:59
Guess intended. We are going to make different kinds of Desert in future afaik. And some of kinds will have less plants.

**Comment by WeaselDog** [comment] 2020-04-15 16:05
For now this is intentional. Grasslands are a great source of food & a secondary biome for mining at the cost of having less trees. We have Oak in the grasslands for now, but maybe we can increase their distribution slightly.

We are fine tuning deserts so there is a sub-biome which is the only part of desert Joshua tree can grow in. The desert is not a good source of food which is its main weakness as a biome.

**Comment by WeaselDog** [comment] 2020-04-27 04:24
Going to close this for now as it is intended behavior for the time being.

**Closed by WeaselDog** 2020-04-27 04:24 UTC
Labels: Category: Design
