### ISSUE TITLE
[10.0.4][Server/User issue] Black Screen when logging in. Only server restart fixes it.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24511] opened 2024-01-02 17:41 UTC
Version 0.10.0.3 beta release-547

Sometimes when players are logging in they get just the UI and see black screen. 
It happens randomly to some people. They can be fine for several days and then that one time when they log-in they get black screen and they will not be able to properly play until server is restarted.
They can still chat with everyone, they just can't see what they are doing.
Other people don't see their avatars, just their names.

I've received Player.log from 2 people affected by this:

[Player (8).log](https://github.com/StrangeLoopGames/EcoIssues/files/13812491/Player.8.log)
[Player (7).log](https://github.com/StrangeLoopGames/EcoIssues/files/13812493/Player.7.log)

Both player.log files have this kind common of error:

```
Uploading Crash Report
ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Client.Tools.Utility.AvatarAttachedItemsDisplayer.UpdateAttachedItems () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Client.PlayerAvatar.Components.AvatarSkeleton.CacheBoneMap () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Utils.Initializer.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Avatar.Avatar.CreateAvatar (Eco.Avatar.Avatar avatarPrefab, UnityEngine.GameObject parentObject, UnityEngine.GameObject playerObject, AvatarView avatarView, ClothingInventoryView clothingView, SelectionInventoryView toolbarView, UserView avatarUser) [0x00000] in <00000000000000000000000000000000>:0 
  at ThirdPersonController.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.UI.ConnectionUI.<FadeAndClose>b__66_0 () [0x00000] in <00000000000000000000000000000000>:0 
  at Fader.DoComplete () [0x00000] in <00000000000000000000000000000000>:0 
EcoEngine.Logging.LogManager:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Eco.Shared.Utils.Log:WriteErrorPrivate(String, Exception, Boolean)
Eco.Shared.Utils.Log:WriteError(LocString, Exception, Boolean)
Fader:DoComplete()
```

Logging into the game from a completely diffrent PC that never had Eco installed on it does not fix the issue.

**Comment by D3nnis3n** [comment] 2024-01-03 10:02
This is caused by illegal block placement on the server, the cause is fixed in 10.0.4, but you may need to find the violating blocks yourself and remove them. Make sure no blocks are placed above height 159.

**Comment by padmanek** [comment] 2024-01-03 19:45
The error slighly changed format in 10.0.4 but still persists.

```
Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object.
  at Eco.Avatar.AvatarPuppet.CreateAvatarPuppet (Eco.Avatar.AvatarPuppet avatarPrefab, UnityEngine.GameObject parentObject, AvatarView avatarView, ClothingInventoryView clothingView, Eco.Animation.AnimationStateManager+AvatarState initState, System.Boolean isActive) [0x00000] in <00000000000000000000000000000000>:0 
  at BedController.CreateOrChangeAvatarPuppet (System.Int32 seat, UserView userView) [0x00000] in <00000000000000000000000000000000>:0 
  at BedController.OnAvatarChanged (System.Collections.Generic.KeyValuePair`2[TKey,TValue] seatUserPair) [0x00000] in <00000000000000000000000000000000>:0 
  at BedController+<>c__DisplayClass22_0.<OnUsersSleeps>b__2 () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propertyName) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.ViewManager.ReceiveViewUpdate (Eco.Shared.Serialization.BSONArray updates) [0x00000] in <00000000000000000000000000000000>:0 
  at ClientPacketQueueHandler.ProcessItem (Eco.Shared.Serialization.BSONValue value) [0x00000] in <00000000000000000000000000000000>:0 
  at ClientPacketHandler+RoundRobinQueueConsumer.Consume (ClientPacketQueueHandler[] queueHandlers, Eco.Shared.Time.TimeLimit timeLimit, ClientPacketHandler+IQueueConsumer& nextConsumer) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.OnTimeLimitedUpdate (Eco.Shared.Time.TimeLimit timeLimit) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.PlannerGroup.OnUpdate (System.Int64 reducedTicks) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.FramePlannerSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
EcoEngine.Logging.LogManager:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Eco.Shared.Utils.Log:WriteErrorPrivate(String, Exception, Boolean)
Eco.Shared.Utils.Log:WriteError(LocString, Exception, Boolean)
Eco.Shared.View.View:NotifyChanged(String)
Eco.Shared.View.ViewManager:ReceiveViewUpdate(BSONArray)
ClientPacketQueueHandler:ProcessItem(BSONValue)
RoundRobinQueueConsumer:Consume(ClientPacketQueueHandler[], TimeLimit, IQueueConsumer&)
NetworkManager:OnTimeLimitedUpdate(TimeLimit)
FramePlanner.PlannerGroup:OnUpdate(Int64)
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
```

Our world was generated with Height parameter set to 90
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/75894828-f021-49de-bd72-7f210100b48d)
So it's unlikely any1 placed anything at 159+. We've had several admins flying around them map and looking for any blocks high in the sky and found nothing.
We were also carefully looking on 3D map truying to find something and still nothing.

The Hotifx 10.0.4 changes read: "Fixed: Under specific circumstances it was possible to place blocks outside of the allowed height limits, breaking the savegame and leading to a black screen with HUD **for all players on the server**"

This is not what happens, it happens for maybe 2-3 people over several hours. And they are stuck with black screen until server restarts. Everyone else can log in and play normally.

**Comment by D3nnis3n** [comment] 2024-01-03 19:46
If only specific people are affected and you're seeing an avatar error message, we need a player that actually has the problem, as their avatar will be the issue.

**Comment by padmanek** [comment] 2024-01-03 19:48
Fresh Player.log from the affected player on 10.0.4
[Player (9).log](https://github.com/StrangeLoopGames/EcoIssues/files/13822776/Player.9.log)
This is the only player affected currently.

**Comment by padmanek** [comment] 2024-01-03 19:49
And sorry I deleted my comment because I was about to post a new ticket as this one got closed but its now reopened. Here's the comment I deleted:

Continuation of https://github.com/StrangeLoopGames/EcoIssues/issues/24511 that got closed.

The error slighly changed format in 10.0.4 but still persists.

```
Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object.
  at Eco.Avatar.AvatarPuppet.CreateAvatarPuppet (Eco.Avatar.AvatarPuppet avatarPrefab, UnityEngine.GameObject parentObject, AvatarView avatarView, ClothingInventoryView clothingView, Eco.Animation.AnimationStateManager+AvatarState initState, System.Boolean isActive) [0x00000] in <00000000000000000000000000000000>:0 
  at BedController.CreateOrChangeAvatarPuppet (System.Int32 seat, UserView userView) [0x00000] in <00000000000000000000000000000000>:0 
  at BedController.OnAvatarChanged (System.Collections.Generic.KeyValuePair`2[TKey,TValue] seatUserPair) [0x00000] in <00000000000000000000000000000000>:0 
  at BedController+<>c__DisplayClass22_0.<OnUsersSleeps>b__2 () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propertyName) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.ViewManager.ReceiveViewUpdate (Eco.Shared.Serialization.BSONArray updates) [0x00000] in <00000000000000000000000000000000>:0 
  at ClientPacketQueueHandler.ProcessItem (Eco.Shared.Serialization.BSONValue value) [0x00000] in <00000000000000000000000000000000>:0 
  at ClientPacketHandler+RoundRobinQueueConsumer.Consume (ClientPacketQueueHandler[] queueHandlers, Eco.Shared.Time.TimeLimit timeLimit, ClientPacketHandler+IQueueConsumer& nextConsumer) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.OnTimeLimitedUpdate (Eco.Shared.Time.TimeLimit timeLimit) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.PlannerGroup.OnUpdate (System.Int64 reducedTicks) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.FramePlannerSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
EcoEngine.Logging.LogManager:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Eco.Shared.Utils.Log:WriteErrorPrivate(String, Exception, Boolean)
Eco.Shared.Utils.Log:WriteError(LocString, Exception, Boolean)
Eco.Shared.View.View:NotifyChanged(String)
Eco.Shared.View.ViewManager:ReceiveViewUpdate(BSONArray)
ClientPacketQueueHandler:ProcessItem(BSONValue)
RoundRobinQueueConsumer:Consume(ClientPacketQueueHandler[], TimeLimit, IQueueConsumer&)
NetworkManager:OnTimeLimitedUpdate(TimeLimit)
FramePlanner.PlannerGroup:OnUpdate(Int64)
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
```

Our world was generated with Height parameter set to 90
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/75894828-f021-49de-bd72-7f210100b48d)
So it's unlikely any1 placed anything at 159+. We've had several admins flying around them map and looking for any blocks high in the sky and found nothing.
We were also carefully looking on 3D map truying to find something and still nothing.

The Hotifx 10.0.4 changes read: "Fixed: Under specific circumstances it was possible to place blocks outside of the allowed height limits, breaking the savegame and leading to a black screen with HUD **for all players on the server**"

This is not what happens, it happens for maybe 2-3 people over several hours. And they are stuck with black screen until server restarts. Everyone else can log in and play normally.

**Comment by padmanek** [comment] 2024-01-03 19:54
I can @everyone on my discord if any1 else has the problem **right now** but I only know of this one person https://github.com/StrangeLoopGames/EcoIssues/issues/24511#issuecomment-1875884146

**Comment by WildKakapo** [comment] 2024-01-03 20:05
Hey, it's me whos experiencing this problem atm, this is my player log
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13822917/Player.log)

**Comment by padmanek** [comment] 2024-01-03 21:21
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/a0ac7dc5-75f5-4c8d-819b-cd24844b908a)
Do illegaly placed animals have anything to do with it? This is the result of /fixobjects command. It's 90% Crab, few Snapping Turtles and Otters

**Comment by Dzanidra** [comment] 2024-01-04 11:37
Adding logs from before it happened and a fresh log when I tried again.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13829371/Player.log)

[Player-prev.zip](https://github.com/StrangeLoopGames/EcoIssues/files/13829372/Player-prev.zip)

I've managed to reproduce this with my account on different PCs (one with a fresh Eco install)


We've noticed that the avatars go invisible before this happens. If you do restart the game while your avatar is gone, you get a black screen. But after a while your avatar might return and you're able to restart the game again.

**Comment by D3nnis3n** [comment] 2024-01-04 18:16
@padmanek Please attach the complete savefile of the server (.zip, accessible via a link that can be opened by anyone, for example on Google Drive) and note the exact ingame names of players affected as how they appear on the server. The files we need is Game.eco, Game.db and the UserTextures folder from storage folder.

**Comment by padmanek** [comment] 2024-01-04 19:04
Requested files: https://drive.google.com/file/d/1GXtWgFvT8UgIFjQonU2AuDAHmjvWF6JO/view?usp=sharing
Affected Player during this save period: Wild Kakapo
Her Player.log is here: https://github.com/StrangeLoopGames/EcoIssues/issues/24511#issuecomment-1875903390

**Comment by padmanek** [comment] 2024-01-04 20:47
Got another person with black screen, started getting it 30min ago. 
Everyone else on the server is playing normally, we're ~90 online. 
Visible in game as: Just a name above invisible avatar.
Player name: Tig
Player log: [Player (15).log](https://github.com/StrangeLoopGames/EcoIssues/files/13835341/Player.15.log)
Requested files: https://drive.google.com/file/d/1fTQiRnQ7k9JMLedT7wWrDk2uMugqZavv/view?usp=sharing

**Comment by padmanek** [comment] 2024-01-06 14:33
> @padmanek Please attach the complete savefile of the server (.zip, accessible via a link that can be opened by anyone, for example on Google Drive) and note the exact ingame names of players affected as how they appear on the server. The files we need is Game.eco, Game.db and the UserTextures folder from storage folder.

I assume this can't be reproduced becasue server restart fixes black screen for all the users so if you load one of my saves it's basically like server restart? We still have users randomly affected now and then.

**Comment by D3nnis3n** [comment] 2024-01-09 18:12
You are still on release, right? The only blackscreen issues we could find and reproduce were on playtest and should be fixed with next build release. For release we are unable to reproduce any.

**Comment by padmanek** [comment] 2024-01-09 18:17
Still on Release yes. Our players are still getting Black Scren daily, random people at random times. Around 1-2 players every 2-3 hours. Server restat always fixes the black screen for everyone affected at the time.

**Comment by Meta-WoM** [comment] 2024-01-11 18:07
It seems I have the same problem, but on a different server:
Detailed behaviour described in https://github.com/StrangeLoopGames/EcoIssues/issues/24595

Here my player log (after I killed the game, because closing it with the menu does nothing.)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13906773/Player.log)

**Comment by Meta-WoM** [comment] 2024-01-11 18:26
I don't know if this helps, but I just found out, that if I hover over elements like player names or icons, it still renders the mouseover.

And my player.log seems to be totally spammed full with messages about the color-mod like these:
[07:09:50.234] Upgrading sprite asset [VioletSmallWoodCartItem] to version 1.1.0.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
TMPro.TMP_SpriteAsset:UpgradeSpriteAsset()
TMPro.TMP_SpriteAsset:UpdateLookupTables()
SpriteAssetLoader:BuildSprite(TMP_SpriteAsset)
SpriteAssetLoader:BuildSpriteAssets()
<BuildItems>d__59:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

or these:
[07:10:02.478] Can't combine materials with Crunch compression. Material: Red Corrugated Steel (mapped) Texture: PinkCorrugatedSteelFloor_Albedo.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
VoxelEngine.Materials.MaterialCombiner:VerifyTexture(Material, Texture2D)
VoxelEngine.Materials.MaterialCombiner:GetTextureInfos(Material, IReadOnlyList`1)
VoxelEngine.Materials.MaterialCombiner:Add(MaterialInfo)
MaterialMapper:GetMappedMaterialInfo(Material, Boolean)
MapConfig:InitializeBlockMaterialInfo(BlockInfo, MaterialInfo)
MapConfig:GetBlockInfo(UInt16, Block, MaterialInfo, Int32&)
MapConfig:CreateBlockMapping(String[], UInt16[], IEnumerable`1)
VoxelEngine.Core.NetMapConfig:CreateBlockMapping(BSONObject)
RenderedChunkGrid:ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:HandleNewObject(BSONObject)
ClientPacketQueueHandler:ProcessItem(BSONValue)
ClientPacketQueueHandler:HandleUpdates(TimeLimit)
WaitForConditionQueueConsumer:Consume(ClientPacketQueueHandler[], TimeLimit, IQueueConsumer&)
NetworkManager:OnTimeLimitedUpdate(TimeLimit)
FramePlanner.PlannerGroup:OnUpdate(Int64)
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()

[07:10:02.478] Material Red Corrugated Steel (mapped) wasn't added to combo material, because of non-compatible texture(s)
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
VoxelEngine.Materials.MaterialCombiner:Add(MaterialInfo)
MaterialMapper:GetMappedMaterialInfo(Material, Boolean)
MapConfig:InitializeBlockMaterialInfo(BlockInfo, MaterialInfo)
MapConfig:GetBlockInfo(UInt16, Block, MaterialInfo, Int32&)
MapConfig:CreateBlockMapping(String[], UInt16[], IEnumerable`1)
VoxelEngine.Core.NetMapConfig:CreateBlockMapping(BSONObject)
RenderedChunkGrid:ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:HandleNewObject(BSONObject)
ClientPacketQueueHandler:ProcessItem(BSONValue)
ClientPacketQueueHandler:HandleUpdates(TimeLimit)
WaitForConditionQueueConsumer:Consume(ClientPacketQueueHandler[], TimeLimit, IQueueConsumer&)
NetworkManager:OnTimeLimitedUpdate(TimeLimit)
FramePlanner.PlannerGroup:OnUpdate(Int64)
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()

**Comment by padmanek** [comment] 2024-01-11 18:43
@Meta-WoM The crunch compression errors are from Polychrome mod and should be harmless from what Polychrome author was told by SLG dev.

The only relevant error to your and my issue is:

```
Uploading Crash Report
ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Client.Tools.Utility.AvatarAttachedItemsDisplayer.UpdateAttachedItems () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Client.PlayerAvatar.Components.AvatarSkeleton.CacheBoneMap () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Utils.Initializer.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Avatar.Avatar.CreateAvatar (Eco.Avatar.Avatar avatarPrefab, UnityEngine.GameObject parentObject, UnityEngine.GameObject playerObject, AvatarView avatarView, ClothingInventoryView clothingView, SelectionInventoryView toolbarView, UserView avatarUser) [0x00000] in <00000000000000000000000000000000>:0 
  at ThirdPersonController.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.UI.ConnectionUI.<FadeAndClose>b__66_0 () [0x00000] in <00000000000000000000000000000000>:0 
  at Fader.DoComplete () [0x00000] in <00000000000000000000000000000000>:0 
EcoEngine.Logging.LogManager:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Eco.Shared.Utils.Log:WriteErrorPrivate(String, Exception, Boolean)
Eco.Shared.Utils.Log:WriteError(LocString, Exception, Boolean)
Fader:DoComplete()
```
It is the exact same error that my players are getting and the behaviour is exactly the same.

Can you share the name of the server you're playing on? I'd like to compare the mods.

**Comment by Meta-WoM** [comment] 2024-01-11 18:55
Server is: "[GER/ENG] Ecoville Season 3 / QoL Mods & Settings / Meteor on"

Serveradmin posted on discord:
"Ich denke mal der Server ist startklar, ich bin mir nicht sicher, ob das mit den Angepassten Reichweiten für die Stockpiles funktioniert hat, der Server hat beim Starten Probleme gehabt mit dateien die sich mit der Überschreibung von Objecten wie den Stockpiles befassen, ich habe keine andere Lösung gefunden als diese zu löschen. Wir müssten dafür in jedem Lager jetzt eine Itemstack größe von 40 anstatt 20 haben. Craftingtische und sämtliche anderen Sachen außer den Stockpiles müssten garantiert eine erhöhte Reichweite haben. (wie gesagt ich weiß aktuell noch nicht obs bei den Stockpiles übernommen wurde oder nicht). Wir haben Bigshovel und Polychrome mod, die Hardware des Servers ist genau so stark wie die alte."

With google translate:
"I think the server is ready to go, I'm not sure if the adjusted ranges for the stockpiles worked, the server had problems when starting with files that deal with overwriting objects like the stockpiles, I don't have any Found another solution than deleting it. We would now have to have an item stack size of 40 instead of 20 in each warehouse. Crafting tables and everything else except the stockpiles would have to have a guaranteed increased range. (As I said, I don't currently know whether it was taken over from the stockpiles or not). We have Bigshovel and Polychrome mod, the hardware of the server is just as strong as the old one."

afterwards there was discussion about the following mods:
reggrowing vegetables, easy logging, shipping container 10.0.x
I am not sure about the first 2 ones, but the last one is for sure installed.
I also asked my server admin on discord for the mod list.

**Comment by Meta-WoM** [comment] 2024-01-11 19:12
Our mods:
Bigshovel, Bonus Star, Shipping Container, Fishing unplugged, Polychrome

**Comment by padmanek** [comment] 2024-01-11 19:53
From the list of your mods we only use Fishing Unplugged and Polychrome.
I made my own easy logging and big shovel mods. We dont use Shipping Cointainer or Regrowable Veggies.
if its related to mods at all, my bet is on either Fishing or Polychrome. It might not be mods at all tho.

**Comment by D3nnis3n** [comment] 2024-01-11 21:36
We have made some fixes into the blue on playtest and hope that will address it once it goes to release, but so far still no luck in any reproducable case.

**Comment by padmanek** [comment] 2024-01-14 01:10
> We have made some fixes into the blue on playtest and hope that will address it once it goes to release, but so far still no luck in any reproducable case.

I can now always reproduce the bug on demand. The issue is with **modded food.** Specifically, the unity part of the food was made incorrectly. Author of **Fishing Unplugged mod** did not use FoodItemTemplate from ModKit, he used ItemTemplate which lacks all the food scripts and also the avatar parts things.

The bug triggers if you eat the incorrectly made modded food and log out. Upon log-in you'll have black screen.

You can prevent the bug from triggering if you swtich to any kind of tool after eating the food (so it appears in your hand).

Players that accidentally triggered the bug can also fix it themselves by trying to switch to some tool on their toolbar (while seeing only black screen), then waiting around a minute, then restarting the game.

Server admin can also temporarily remove .unity3d file of the affected mod from the server, force server reload unity files and then the affected player will be able to log in, without black screen.

This is all on release version, I did no test it on the playtest version.

**Comment by Meta-WoM** [comment] 2024-01-14 20:42
> Players that accidentally triggered the bug can also fix it themselves by trying to switch to some tool on their toolbar (while seeing only black screen), then waiting around a minute, then restarting the game.

Thanks for the Info. Already helped one of our players!

**Comment by D3nnis3n** [comment] 2024-01-14 23:06
In that case the issue would be mod-caused though, which means not on our side. Given we still were not able to reproduce any blackscreen issues with just the basegame and our latest fixes, I'd hence close this. I assume you already have made the mod creator aware of the faulty mode?

**Closed by D3nnis3n** 2024-01-14 23:06 UTC
Labels: Status: Not reproduced

**Comment by padmanek** [comment] 2024-01-16 18:28
Tried best I can to contact the mod author. On discord directly DM, tagging on eco discord, DMing on mod.io - no response so far.
There's several servers using the faulty mod. I know my workaround findings have been spreading around the playerbase since I'm getting tagged on diffrent servers. Case closed indeed.
