### ISSUE TITLE
USER ISSUE: "Getting Equipped" tutorial step stuck

### ISSUE THREAD

**Issue by jaxel90** [StrangeLoopGames/EcoIssues#12492] opened 2019-06-06 19:49 UTC
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
take the tools before starting navigating the inventory as tutorial describes and you get stuck on "Drag stone axe to toolbar"

**Expected behavior:**
bin able to put axe  back and pick it up to complete tutorial

**Actual behavior:**
got stuck

**Do you have mods installed? Does issue happen when no mods are installed?:**
got stuck

**Comment by SlayksWood** [comment] 2019-06-07 05:20
@jaxel90 
"Drag stone axe to toolbar and **select it**". Did you choose stone axe on toolbar?
I never have problem with this tutorial.

**Comment by D3nnis3n** [comment] 2019-06-20 10:27
Closing for now due to not being reproducable and no further information available. Reopen when it occurs again and you can provide more information / logfiles.

**Closed by D3nnis3n** 2019-06-20 10:27 UTC
Labels: Investigate, Needs Information
