### ISSUE TITLE
USER ISSUE: Invisible stone/ore

### ISSUE THREAD

**Issue by Lord-Schwartzy** [StrangeLoopGames/EcoIssues#24746] opened 2024-02-07 00:15 UTC
\
**User Id: (slg232257)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Just do some mining and some time ore/stones are invisible.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope, on Coast Redwood. After relaunch of the server of it you go far enough they usually get visible again.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-02-07 00:24
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23400

**Closed by D3nnis3n** 2024-02-07 00:24 UTC
