### ISSUE TITLE
[SERVER ISSUE] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#5620] opened 2018-03-07 20:11 UTC
```
[08:46] Caught network exception from Hudlort!  Disconnecting...
[08:46] Disconnecting client [reason: Caught exception:

<size=60.00%>Caught exception invoking RPC SetTag on ChatManager!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Systems.Chat.ChatManager.SetTag(ChatTagSetting chatTagSetting, Int32 playerID)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>]...
```

**Comment by MarjieAVolk** [comment] 2018-03-08 19:54
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4736.  Do you know what attempted chat message caused this error?

**Closed by MarjieAVolk** 2018-03-08 19:54 UTC
