### ISSUE TITLE
USER ISSUE: Renaming a chest stucks player

### ISSUE THREAD

**Issue by Kombustor** [StrangeLoopGames/EcoIssues#5200] opened 2018-02-27 22:23 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Place a chest
2. Rename it
3. You're stuck, cannot move or open chat
4. After reconnect everything is normal again

**Expected behavior:**
Player shouldn't get stuck

**Actual behavior:**
Player gets stuck

**Comment by jsheldon** [comment] 2018-02-28 16:00
I've seen this on a lot of things, not just the chest.   It seems when you close a window after a text area receives focus.  The text area continues to have focus, and most keys no longer work.

Short Term workaround is to click anywhere to shift focus away from the input box.

**Comment by MarjieAVolk** [comment] 2018-02-28 19:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

This will be fixed in the next staging build.

**Closed by MarjieAVolk** 2018-02-28 19:12 UTC
