### ISSUE TITLE
[Client or Server bug]

### ISSUE THREAD

**Issue by pmeyerson** [StrangeLoopGames/EcoIssues#5305] opened 2018-03-02 17:17 UTC
I have a completed item stuck in my campfire that I can't remove.
Win10
I have only seen this happen once in a few days of playing, appears rare.
0.7.1.2 beta
https://imgur.com/a/XSvyt

Even if I quit the server and restart it, this issue comes back.
You'll note the collect button is not displayed.

**Comment by MarjieAVolk** [comment] 2018-03-02 18:34
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3240

Just to note, this is expected behavior if the project was not started by you.  However, if it was started by you, then it is that bug ^

**Closed by MarjieAVolk** 2018-03-02 18:34 UTC
