### ISSUE TITLE
Minimap lag while mousing over map on low-end graphics cards

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#9110] opened 2018-08-28 20:45 UTC
moving the fetch call or swapping buffers may fix the issue, could also disable the lookup while dragging the world to make it less noticable

**Comment by mirasrael** [comment] 2021-01-25 10:02
QA need to investigate if this is still a case.
@SlayksWood @IcedForge

**Comment by Daniel-Magulado** [comment] 2021-03-12 17:18
Tested on:
- 0.9.3 Staging-1952
- 0.9.2.4 Release-163
- 0.9.2.4 Release-156

Server:
Tested with Solo Game
Joined Existing World with 30+ players online.

System:
Laptop: i5-8250U + Nvidia GeForce MX150 2GB
Desktop: i7-6700k + AMD HD7850 2GB OC

Both graphics cards are considered low-entry level cards.

Tests were done.
1. Mouse over mini-map and clicked dragged to see worlds and markers.
2. Opened Map, checked the content in 3D, dragged the map around.
3. Played for an hour, finished tutorials and performed test 1 again.

The Minimap lag issue is not happening. I am unable to reproduce it. Closing for now. Will reopen if the issue arises or presents itself again.

**Closed by Daniel-Magulado** 2021-03-12 17:18 UTC
Labels: Category: Optimization, Priority: Medium, Squad: Pumpkin, Status: Investigate
