### ISSUE TITLE
USER ISSUE: Fell Through the World

### ISSUE THREAD

**Issue by digitinator** [StrangeLoopGames/EcoIssues#5067] opened 2018-02-25 06:41 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. I fell through the world while walking toward a river

**Expected behavior:**
Should not have fallen through the world

**Actual behavior:**
I did

**Comment by MarjieAVolk** [comment] 2018-02-26 21:48
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4574

If you have a screenshot of the land where you fell through, that might be useful (eg. were there any visible gaps or chunks missing?  Were you near coordinate 0 in any direction?)

**Closed by MarjieAVolk** 2018-02-26 21:48 UTC
