### ISSUE TITLE
7.8 bleeding: Minimap broken

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9394] opened 2018-09-16 16:38 UTC
Version: v0.7.8.0-beta-staging-06184de3
![7 8](https://user-images.githubusercontent.com/38510829/45598639-8846ff80-b9df-11e8-987e-d183fe23711c.jpg)

**Comment by BlazeGuy2** [comment] 2018-09-18 00:26
Just reproduced this in Unity.

**Comment by BlazeGuy2** [comment] 2018-09-18 18:33
Issue is with minimap prefab having the filter panel toggle being set to none.

**Comment by MarjieAVolk** [comment] 2018-09-18 18:58
Already fixed that here, I will move the PR to staging since it hasn't gone in yet: https://github.com/StrangeLoopGames/Eco/pull/3393

**Comment by johnkslg** [comment] 2018-09-18 20:06
Fixed by marjie

**Closed by johnkslg** 2018-09-18 20:06 UTC
Labels: High Priority
