### ISSUE TITLE
USER ISSUE: Water bug

### ISSUE THREAD

**Issue by porfirius1983** [StrangeLoopGames/EcoIssues#8514] opened 2018-07-14 12:31 UTC
**Version:** 0.7.6.0 beta

https://prnt.sc/k6drpk

нет физики?

**Comment by johnkslg** [comment] 2018-07-16 18:38
Whats the issue?

**Comment by porfirius1983** [comment] 2018-07-16 19:13
квадратная вода, не растекается.

**Comment by BlazeGuy2** [comment] 2018-08-01 17:51
Issue is that the square of water isn't spreading properly.

**Comment by D3nnis3n** [comment] 2018-12-05 20:45
Duplicate of #1424

**Closed by D3nnis3n** 2018-12-05 20:45 UTC
Labels: Medium Priority
