### ISSUE TITLE
USER ISSUE: Crash on accessing a shop

### ISSUE THREAD

**Issue by TheEvilGreebo** [StrangeLoopGames/EcoIssues#24104] opened 2023-11-29 10:16 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-268

**Steps to Reproduce:**
One of my players is accessing a shop and every time he does the game crashes

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, 10.0 server, i'm making a backup now including world/players that I can send if you provide a location

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TheEvilGreebo** [comment] 2023-11-29 10:36
The store is called Stuff and more work in progress something like that
It is set up for player named Bell credit but owned by someone else
every time someone tries a trade the server crashes

The server backup is too big to upload the world is here https://drive.google.com/drive/folders/1D01NzNf8x9tLXc6hMqgqmkM3crYJ7Fs5?usp=drive_link 
called foamy nathan drake

**Comment by D3nnis3n** [comment] 2023-12-01 22:46
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24105

**Closed by D3nnis3n** 2023-12-01 22:46 UTC
