### ISSUE TITLE
USER ISSUE: Standing avatar, please help

### ISSUE THREAD

**Issue by gray-mongrel** [StrangeLoopGames/EcoIssues#24985] opened 2024-06-22 09:35 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
I think it happened when I went to sleep.

**Expected behavior:**
Movement when walking and cutting, mining, etc.

**Actual behavior:**
My avatar doesn't make the motions to move, it just stands as it moves without actually walking or making the motions.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/15936038/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/15936040/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-06-22 16:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23981

**Closed by D3nnis3n** 2024-06-22 16:43 UTC
