### ISSUE TITLE
Problems with solid ground

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6904] opened 2018-04-03 00:32 UTC
![image](https://user-images.githubusercontent.com/3536496/38222777-cd55a51c-369b-11e8-9b33-6b01f5b2b139.png)

**Comment by MarjieAVolk** [comment] 2018-04-03 00:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6854

Sounds like the rotation problem craig was talking about earlier

**Closed by MarjieAVolk** 2018-04-03 00:43 UTC
