### ISSUE TITLE
Feature: Being able to delete a world, from the "Load UI", made by the client server.

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#7006] opened 2018-04-05 19:43 UTC
![](https://i.gyazo.com/0b835c96fea24ee747fca1fae215c22a.jpg)

Maybe also list the last backup, and make a "make new backup" button, so people that don't get a lot of backups can choose to make one.

**Comment by MarjieAVolk** [comment] 2018-04-06 01:27
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6964

**Closed by MarjieAVolk** 2018-04-06 01:27 UTC
Labels: Suggestion

**Comment by zEverdeen** [comment] 2018-04-11 19:19
Man, I was a day late.

**Comment by MarjieAVolk** [comment] 2018-04-11 20:28
:P It's okay, good to see if people are wanting the feature
