### ISSUE TITLE
Arrastra not affected by Upgrades

### ISSUE THREAD

**Issue by Delta1136** [StrangeLoopGames/EcoIssues#23491] opened 2022-10-02 18:00 UTC
As shown in the attached Video the amount of ore needed doesn't change when installing an Upgrade.

https://youtu.be/517qRRox3o8 

Version 0.9.6.3 Beta release-343 

ServerID- 9473dac5-Oc35-4737-aec8-7d5ed566d38e

**Comment by Daniel-Magulado** [comment] 2022-10-08 05:41
Hi @Delta1136 

Thank you for submitting this bug report however, this is intended and by design. Arrastra only benefits from upgrades by reducing the crafting time. It does not benefit from resource reduction. This will also be the case for other refining tables. I'll be closing this.

**Closed by Daniel-Magulado** 2022-10-08 05:41 UTC

**Comment by mirasrael** [comment] 2022-10-10 08:13
Can we add Tutorial for Arrastra and static ingredients to avoid confusion? (It may popup when user first time open crafting station with static ingredients)
