### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Bazzi89** [StrangeLoopGames/EcoIssues#23140] opened 2022-05-02 06:22 UTC
After playing ~30mins the game becomes unplayable. Mining & logging starts to lagg, worktables needs time to open etc..

RAM use ~12GB from 32GB, CPU is @30-40% in peak and GPU @60-80%, so everything should be fine

My Specs: AMD Ryzen 7 3700x, 32GB Ram, GTX1080, game and system on nvme ssd, "medium graphic settings" without "special effects", view distance on 100 (same settings in 9.4.6, in 9.4.6 I got it after 1-2h)

A lot of people reporting this, with different systems from "Wooden PC" to "Modern PC"

**Comment by D3nnis3n** [comment] 2022-05-02 11:02
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/22716

**Closed by D3nnis3n** 2022-05-02 11:02 UTC
