### ISSUE TITLE
USER ISSUE: Cart/Wheelbarrow become unusable

### ISSUE THREAD

**Issue by jamesjorgensen** [StrangeLoopGames/EcoIssues#24756] opened 2024-02-09 22:04 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Drop a piece of stone under the cart/wheelbarrow that moves it
Pick the piece of stone up
All carts/wheelbarrows become unusable

**Expected behavior:**
Cart/Wheelbarrow should still have interactions.

**Actual behavior:**
You can no longer interact with any cart/wheelbarrow.  Can't even pick it up.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by jamesjorgensen** [comment] 2024-02-09 22:07
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14226719/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14226720/Player.log)

**Comment by D3nnis3n** [comment] 2024-02-17 15:37
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24726

**Closed by D3nnis3n** 2024-02-17 15:37 UTC
