### ISSUE TITLE
server crashes when cancelling projects

### ISSUE THREAD

**Issue by KyeEco** [StrangeLoopGames/EcoIssues#1743] opened 2017-06-29 05:19 UTC
hey guys, my server members were saying our server crashed quite a few times when the tried to cancel their projects, i have a crash dump file one of many that are logged on the server, all identical, thanks

https://www.dropbox.com/s/wmt3us3ica0xqfr/Crash%2006295912.ecodmp?dl=0

**Comment by MarjieAVolk** [comment] 2017-06-29 22:50
Crash is in PipeEmitterObject.EmitParticles

**Comment by MarjieAVolk** [comment] 2017-07-28 19:03
System.AggregateException: One or more errors occurred. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Pipes.PipeEmitterObject.EmitParticles(Ray ray, Item emissionItem, Single amount)
   at Eco.Gameplay.Wires.WireOutput.SendItem(ItemStack item, Boolean divideAmongOutputs)
   at Eco.Gameplay.Wires.WireOutput.SendItemConsume(ItemStack item, Single maxToSend)
   at Eco.Gameplay.Pipes.LiquidComponents.LiquidTank.Tick(Single delta)
   at Eco.Gameplay.Pipes.LiquidComponents.LiquidProducer.Tick(Single delta)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Pipes.LiquidComponents.PipeComponent.Tick(Single delta)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by SeanAtr0n** [comment] 2017-07-28 23:54
Looks like a dupe of StrangeLoopGames/EcoIssues#1728
Should be fixed in 5.6.1

**Closed by SeanAtr0n** 2017-07-28 23:54 UTC
