### ISSUE TITLE
[7.4.5] Contract has a line of text that isn't where it should be

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#7798] opened 2018-05-17 00:32 UTC
![ui_contractbug](https://user-images.githubusercontent.com/35509188/40150492-bdac4516-592e-11e8-8da2-b8147d89931c.PNG)

The line of text on the left is displaying on the left side, went to contract board generated from the /testcontracts command and opened issue and this came up.  Generated new world and reproduced.

**Comment by MarjieAVolk** [comment] 2018-05-17 17:35
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3295

This happens when the content is too wide for the window.

**Closed by MarjieAVolk** 2018-05-17 17:35 UTC
