### ISSUE TITLE
USER ISSUE: Doubled character model

### ISSUE THREAD

**Issue by JustASparrow** [StrangeLoopGames/EcoIssues#23658] opened 2023-01-04 14:44 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**
IDK it just appeared when i logged on 

**Expected behavior:**
There shoud be only one character

**Actual behavior:**
Instead it shows two models of it

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-01-04 20:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23657

**Closed by D3nnis3n** 2023-01-04 20:43 UTC
