### ISSUE TITLE
Main Menu: Continue doesn't refresh

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#3619] opened 2018-01-25 09:45 UTC
Specifically the continue button,

Since on this screen there is only a single server to check, can this menu be checking the server every few seconds? 
More over, I would like it to display the current state of the server, whether online or offline, and if it's offline, I want to know if it has come back online, at the moment we have to close the game and re-open for it to refresh, or log out and back in.

**Comment by Nes112** [comment] 2018-01-25 17:59
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3616?

**Comment by MarjieAVolk** [comment] 2018-01-25 18:55
Uh I am not sure what that bug is saying, so I'll leave both open :P

+1 Refreshing this would be really helpful, been bothering me too

**Comment by ClayC90** [comment] 2018-01-28 23:10
@Nes112 yes this is like #3616 but it has added information / suggestions to it. :)

**Closed** 2018-07-12 03:30 UTC
Labels: Medium Priority

**Comment by MarjieAVolk** [comment] 2018-07-12 19:56
:'(
