### ISSUE TITLE
Feature Request: Copy whole stack of item from chest to backpack and vise versa

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2159] opened 2017-09-16 12:29 UTC
By using ctrl key for example

**Comment by MarjieAVolk** [comment] 2017-09-18 21:34
I take it this is a feature request and not a bug?

**Comment by Fank** [comment] 2017-09-18 23:22
Yep

**Comment by MarjieAVolk** [comment] 2018-05-14 23:45
Closing in favor of https://github.com/StrangeLoopGames/EcoIssues/issues/4280 since there is more discussion there

**Closed by MarjieAVolk** 2018-05-14 23:45 UTC
Labels: Feature
