### ISSUE TITLE
Mill crashes server when placed 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1065] opened 2017-02-04 02:16 UTC
http://ecoforum.strangeloopgames.com/topic/1502/server-mill-crashes-server-when-placed

**Comment by DMoate** [comment] 2017-02-04 03:32
Seems to be related to type of room it is placed in. Crash was happening when placing in a room made of wood and dirt, worked fine when placed in a room made of wood and mortared stone. Rooms were roughly same size.

**Comment by metachronism** [comment] 2017-03-21 22:55
fixed in 5.5

**Closed by metachronism** 2017-03-21 22:55 UTC

**Comment by MarjieAVolk** [comment] 2017-03-22 18:47
Closing as a duplicate of StrangeLoopGames/EcoIssues#875 - Thanks for the observation about the type of room, that could be very helpful
