### ISSUE TITLE
[7.6.2] Excavator FOV Bugs

### ISSUE THREAD

**Issue by FabiUnne** [StrangeLoopGames/EcoIssues#8658] opened 2018-07-20 17:24 UTC
Hey there,

since version 7.6 (also tested in 7.6.1 and 7.6.2) there are a few FOV bugs when sitting in an Excavator. I dont found this bugs on GitHub, so here is a new issue.

The 1st bug is a very fundamental bug. When sitting in the excavator and switching from excavate-mode to drive-mode, the FOV is rotating about 100 degrees clock wise. Am I doing something wrong? Otherwise please fix this as soon as possible.

The 2nd bug could be a feature, but I do not like it. So I hope, that's a bug. When switching to excavate-mode the FOV a static (in 7.5 and older was this variable). That's very annoying because when I want to look around, I must first switch back to drive mode. If this is actually a feature, you can add a key-binding, for example [shift] or [ctrl], to change the FOV while excavating?

Thank you very much :)

**Comment by FabiUnne** [comment] 2018-07-20 17:31
Addendum to the 1st bug: I just tested it again. It is probably not always 100 degrees and it is not always  rotating clockwise. Depending on how the excavator-shovel is aligned, the number of degrees and whether clockwise or counterclockwise will change.

**Comment by mirasrael** [comment] 2019-04-05 12:37
Checked on 8.1
1. Seems to be fixed
2. Camera behavior was intended, but is going to be fixed in https://github.com/StrangeLoopGames/EcoIssues/issues/11772

**Closed by mirasrael** 2019-04-05 12:37 UTC
Labels: Medium Priority
