### ISSUE TITLE
/fly keybinds AZERTY/QWERTY

### ISSUE THREAD

**Issue by xerrio** [StrangeLoopGames/EcoIssues#11557] opened 2019-03-03 21:02 UTC
Hello!

I am using an AZERTY keyboard and I have an issue when I switch to fly mode.
/fly makes my keybinds ZQSD (movements) switch to WASD! It disturbs me and also is still activating others shortcuts like the skills page on W for instance.
I think WASD is hard-coded instead of looking in the personal settings.

Have a good day and keep doing great updates :D
 I love the game :)

**Comment by D3nnis3n** [comment] 2019-03-03 21:18
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9773

**Closed by D3nnis3n** 2019-03-03 21:18 UTC
