### ISSUE TITLE
Changing item with stockpile

### ISSUE THREAD

**Issue by Infinaty1** [StrangeLoopGames/EcoIssues#11813] opened 2019-03-30 15:04 UTC
This only works for carried items only ( as far as I know )

So if you have Item A in a cart or stock pile. and you are holding Item B (not a full stack) and you attempt to pick up from the stock pile, Item B will turn into item A. 

So if you have 19 Stone and a cart with 1 gold ore in it, if you attempt to get the gold ore out while holding the 19 stone it changes into 20 gold.

**Comment by mirasrael** [comment] 2019-04-01 07:57
@Infinaty1, thanks for report!
Few questions:
1. Which Eco Version?
2. How do you exactly pick up this item? Drag to carried slot or other method?

**Comment by mirasrael** [comment] 2019-04-01 08:03
Tried both staging and release versions. Wasn't able to reproduce. Can you provide more detailed steps? Video would be ideal.

**Comment by D3nnis3n** [comment] 2019-04-01 08:17
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11666, which is fixed in 8.1.

**Closed** 2019-04-01 08:17 UTC
Labels: High Priority, Needs Information, Staging
