### ISSUE TITLE
[0.9.1.8 beta release-130]Elected Title terms extend with changes

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19787] opened 2020-12-18 12:05 UTC
When you have several holders of a title as soon as a player leaves this title it refreshes the term time.

Example: White Tiger Elected Title "Giant Panda Republicans"
Term limit of 7 days
Requirement is ACTIVE demographic holder
A player is no longer active and gets kicked out of the title now it "updates" and extends the title for another 7 days.

![Screenshot_72.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/ad536557-a0d7-446c-9428-926b346e3f5f)

**Comment by SlayksWood** [comment] 2021-01-13 08:03
Time is not updated, but Occupants will not be removed now if they lose demographic. Step to reproduce:
- create an elected title with requirement. 2 Players should occupant it:
![image](https://user-images.githubusercontent.com/45708377/104421965-2ab22600-558d-11eb-8bc8-ad258c94a7c1.png)
- fastforward a several hours:
![image](https://user-images.githubusercontent.com/45708377/104422087-4d443f00-558d-11eb-82e1-faee3f46d74b.png)
- second player should quit.
- fastforward not to be active, devqa still occupant title, but he is not active:
![image](https://user-images.githubusercontent.com/45708377/104423136-c1cbad80-558e-11eb-9ce6-f8049a69d4c3.png)
![image](https://user-images.githubusercontent.com/45708377/104423147-c728f800-558e-11eb-8970-57e11d3ebc33.png)

So we have other bug now. I Reopen it for now, but @IcedForge Can you check it too please?

**Comment by tuha263** [comment] 2021-03-03 15:23
@SlayksWood @serpopov The bug above also happens with TitleRequirement and SkillRequirement.
But the TitleManager will update occupants every 300 seconds. It's not easy to update them immediately. Is it necessary to do it?

**Comment by SlayksWood** [comment] 2021-03-05 11:12
It works, but it triggers in 2 diffenent ticks.
So first tick Devqa became not Active
second tick (5 minutes by default) Devqa removed from Title:
![image](https://user-images.githubusercontent.com/45708377/110107905-8eeaac80-7dbc-11eb-8fa5-49b501dae5bf.png)
If you can do it in one tick, it would be great. If not just close this issue.

**Closed** 2021-03-07 14:49 UTC
Labels: Category: Gameplay, Category: Laws, Priority: Medium, Squad: Mountain Goat, Status: Reopen

**Comment by tuha263** [comment] 2021-03-07 14:57
They can be updated in one tick if I move the Demographic Update above the Title Update, but we also have Title Requirement, Skill requirement,... so it's can't solve the issue thoroughly. I will leave this like this because I think it's not a critical issue.
