### ISSUE TITLE
Rob feedback: Store error for item count

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20432] opened 2021-02-07 21:51 UTC
another thing of my own frustration is, i used the economy viewer to find what someone needed and i wanted to sell it to them so i could get some established currency. So i take 20 basalt to the persons shop, and I cannot figure out how to sell it, im holding it in my hands
when i try to sell basalt that im holding anything above 4 tells me this error
i was triytng to sell 20 at a time
![image](https://user-images.githubusercontent.com/3536496/107160378-b760c180-694a-11eb-9eff-f17a4dd2879a.png)

**Comment by WeaselDog** [comment] 2021-02-07 23:02
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20375

**Closed by WeaselDog** 2021-02-07 23:02 UTC
