### ISSUE TITLE
USER ISSUE: Plants disappearing - Plant exists already

### ISSUE THREAD

**Issue by PrincessCady** [StrangeLoopGames/EcoIssues#5905] opened 2018-03-11 15:50 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Planting trees or vegetables and wait. It probably affects plants that died.

**Expected behavior:**
Plant should grow or die.

**Actual behavior:**
Plant disappears (can't be harvested or removed). Trying to plant a new plant on the empty soil brings error message "plant exists already". Removing block of dirt and readding it to the ground does not fix this problem. can only plant on surrounding blocks, 1 block above or even below.

**Comment by MarjieAVolk** [comment] 2018-03-13 00:30
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5522

**Closed by MarjieAVolk** 2018-03-13 00:30 UTC
