### ISSUE TITLE
0.9 second reap with scythe should not be available

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15028] opened 2020-03-07 14:10 UTC
(second reap - destroy plant, without gathering materials)
We have machete to destroy.

Also with this case, multiple gathering at one place is annoying.

**Comment by WeaselDog** [comment] 2020-03-07 17:49
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10913

I will see about moving forward the milestone but we do plan to change.

**Closed by WeaselDog** 2020-03-07 17:49 UTC
