### ISSUE TITLE
USER ISSUE: dissapearing tree

### ISSUE THREAD

**Issue by zombiepirate03** [StrangeLoopGames/EcoIssues#12021] opened 2019-04-14 14:44 UTC
**Version:** 0.8.1.2 beta

**Steps to Reproduce:**
1.place road under tree with road tool
2.tree dissapears
3.cant dig up dirt under dissapeared tree

**Expected behavior:**
tree shouldnt dissapear and dirt should be able to be dug up

**Actual behavior:**
tree dissapears and dirt cant be dug up

**Do you have mods installed? Does issue happen when no mods are installed?:**
tree dissapears and dirt cant be dug up

**Comment by D3nnis3n** [comment] 2019-04-14 19:24
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10550

**Closed by D3nnis3n** 2019-04-14 19:24 UTC
