### ISSUE TITLE
USER ISSUE: Was jumping and running

### ISSUE THREAD

**Issue by Goreko** [StrangeLoopGames/EcoIssues#5661] opened 2018-03-08 07:13 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Unsure	

**Expected behavior:**
Not crashed? Hope it helps?

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by DumpsterDave** [comment] 2018-03-08 13:43
I also received this same exception, I was pulling a cart of stone at the time of my exception:
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Was pulling a Wooden Cart full of stone (with 20 stone also in my inventory) and the exception showed up.  Have done this multiple times with no error.  This was the first time this error has appeared.

**Expected behavior:**
Continue Pulling Cart

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-08 21:27
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496.  Thanks!

**Closed by MarjieAVolk** 2018-03-08 21:27 UTC
