### ISSUE TITLE
Persistent OutOfMemoryException after about two weeks gametime.

### ISSUE THREAD

**Issue by JordanRL** [StrangeLoopGames/EcoIssues#22099] opened 2021-06-04 22:21 UTC
Seeing a persistent crash in a save for a very large server (in number of players, over 300). It's a 4km world. This is NOT on world generation, this is about day 16 on the server.

> [09:29:53.872] [30] [Error] [Eco] System.AggregateException: One or more errors occurred. (Array dimensions exceeded supported range.)
> 
> System.OutOfMemoryException: Array dimensions exceeded supported range.
>    at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, Boolean zeroingOptional)
>    at System.GC.AllocateUninitializedArray[T](Int32 length)
>    at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
>    at Eco.Shared.Pools.PooledMemoryStream.ReallocateBuffer(Int32 minimumRequired)
>    at Eco.Shared.Pools.PooledMemoryStream.EnsureCapacity(Int32 value)
>    at Eco.Shared.Pools.PooledMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.BinaryWriter.Write(String value)
>    at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
>    at Eco.Core.Serialization.Serializers.EnumerableSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
>    at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
>    at Eco.Core.Serialization.SimpleSerializer.SerializeTo(Stream stream, Object obj)
>    at Eco.Core.Serialization.PersistenceManager.Persist(ContentAccessor& contentAccessor, IStorage storage)
>    at Eco.Core.Serialization.PersistenceManager.ApplyChanges(ContentAccessor& contentAccessor)
>    at Eco.Core.Serialization.DataStore.ContentAccessor.ExecuteAsync(ExclusiveAccess exclusiveAccess, DataStoreContentAccessorDelegate action)
>    at Eco.Core.Serialization.PersistenceManager.PersistAllAsync(ExclusiveAccess exclusiveAccess, Boolean forceFlush)
>    at Eco.Core.Plugins.StorageManager.PersistAsync(Boolean forceFlush)
>    at Eco.Core.Utils.Threading.IntervalActionWorker.DoRepeatableWork(CancellationToken token)
>    at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
>  
> [09:29:53.872] [4] [ Info] [Eco] Saving...  
> [09:30:04.006] [1] [Error] [Eco] Unhandled errorSystem.AggregateException: One or more hosted services failed to stop. (Array dimensions exceeded supported range.)
>    at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
>    at Eco.Server.MainClass.Main(String[] args)
> System.OutOfMemoryException: Array dimensions exceeded supported range.
>    at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, Boolean zeroingOptional)
>    at System.GC.AllocateUninitializedArray[T](Int32 length)
>    at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
>    at Eco.Shared.Pools.PooledMemoryStream.ReallocateBuffer(Int32 minimumRequired)
>    at Eco.Shared.Pools.PooledMemoryStream.EnsureCapacity(Int32 value)
>    at Eco.Shared.Pools.PooledMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.BinaryWriter.Write(String value)
>    at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
>    at Eco.Core.Serialization.Serializers.EnumerableSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
>    at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
>    at Eco.Core.Serialization.SimpleSerializer.SerializeTo(Stream stream, Object obj)
>    at Eco.Core.Serialization.PersistenceManager.Persist(ContentAccessor& contentAccessor, IStorage storage)
>    at Eco.Core.Serialization.PersistenceManager.ApplyChanges(ContentAccessor& contentAccessor)
>    at Eco.Core.Serialization.DataStore.ContentAccessor.ExecuteAsync(ExclusiveAccess exclusiveAccess, DataStoreContentAccessorDelegate action)
>    at Eco.Core.Serialization.PersistenceManager.PersistAllAsync(ExclusiveAccess exclusiveAccess, Boolean forceFlush)
>    at Eco.Core.Plugins.StorageManager.SaveAndFlushAsync(ExclusiveAccess access)
>    at Eco.Core.Plugins.StorageManager.SaveAndFlushAsync()
>    at Eco.Server.Startup.StopAsync()
>    at Eco.Server.Startup.RunAsync(IHostApplicationLifetime applicationLifetime, StartupInfo startupInfo)
>    at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)

I've seen several issues in github related to this or describing something similar ( #8279 and #7866 for instance), but all of them were closed without any kind resolution.

**Comment by TwixterZ** [comment] 2021-06-05 04:22
Hi @JordanRL 

thank you for raising your issue, 

- May I know if any mod is used for this world?
- Can you share your save files preferably ones that is having this crash? 
you may refer to below link for instruction
Save files:  https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by MishkaFur** [comment] 2021-06-06 11:13
Same error as #21966 @TwixterZ

**Comment by D3nnis3n** [comment] 2021-06-06 11:49
Duplicate of #21966

**Closed by D3nnis3n** 2021-06-06 11:49 UTC
Labels: Status: Needs Information
