### ISSUE TITLE
[0.9.3.1 release-204] Excavator cannot dump contents into a lumber stockpile

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#21597] opened 2021-04-27 06:27 UTC
Excavator cannot dump contents into a lumber stockpile however a regular 5x5 stockpile works fine.
![excavatordumpstorage](https://user-images.githubusercontent.com/39825431/116195226-37205000-a732-11eb-8d17-280947a0f8d8.png)

**Comment by Daniel-Magulado** [comment] 2021-04-28 22:19
Hi, thank you for making a report about this.
Unfortunately, we are unable to reproduce this issue.
For us to further investigate this matter, we would like to request more information.

A recorded video of the issue as it happens will be helpful. This will let us figure out what's causing this issue. Additionally, your game logs will also be helpful. To upload your game logs, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment] 2021-05-04 14:31
Will close as fixed by 9.3.3

**Closed by IcedForge** 2021-05-04 14:31 UTC
Labels: Status: Needs Information
