### ISSUE TITLE
Ladder included in room tier

### ISSUE THREAD

**Issue by masterquinn** [StrangeLoopGames/EcoIssues#10193] opened 2018-12-04 17:41 UTC
Build a brick house, add 1 peice of ladder.. assuming it's because ladder is entitled as isMaterial=HewnLog... Either multiple tier ladders or have the ladder ignore tiers in room calcs

Thanks

**Comment by D3nnis3n** [comment] 2018-12-04 18:18
Duplicate of #10123

**Closed by D3nnis3n** 2018-12-04 18:18 UTC
