### ISSUE TITLE
Sawmill can lose connection to carpentry table

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3243] opened 2018-01-03 03:27 UTC
http://ecoforum.strangeloopgames.com/topic/3128/carpentry-table-loose-contact-to-sawmill/2

**Comment by MarjieAVolk** [comment] 2018-01-03 03:29
Sounds like duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3108

**Comment by MarjieAVolk** [comment] 2018-01-03 03:29
pasting discussion link there

**Closed by MarjieAVolk** 2018-01-03 03:29 UTC
