### ISSUE TITLE
Tutorial doesn't disappear after completion of tasks.

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#11776] opened 2019-03-27 18:54 UTC
![image](https://user-images.githubusercontent.com/12839021/55104175-1c78da00-5087-11e9-8e5e-c672ad299ef6.png)

**Comment by D3nnis3n** [comment] 2019-03-27 21:04
Seems to be unspecific to this tutorial: #11725

Also i couldnt reproduce this with any of the tutorials.

**Comment by mirasrael** [comment] 2019-03-28 11:33
@seccombew 
Researched the code and tried different ways to reproduce it, but without success. 

I fixed one very unlikely possible case when it may happens: if tutorial task completed, removed from tasks and then added it back from chained tasks or from another thread. 

I'm not sure if it actually fixed this issue, but if it will happen again to you then please provide more additional context:

1. Can you provide client log when this issue happens? 
2. How regular do you have it?
3. Can you describe previous actions order: which tasks was completed, which was skipped (if any).
4. Do you continue experience this issue after re-log?
5. After server restart?
6. Will this task disappear if you complete/skip another task?

**Closed** 2019-03-28 17:40 UTC
Labels: Fixed, High Priority, Staging
