### ISSUE TITLE
USER ISSUE: Server crashes after work party is posted

### ISSUE THREAD

**Issue by ActuallyHappy** [StrangeLoopGames/EcoIssues#23419] opened 2022-09-06 21:11 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.6.1 beta release-337

**Steps to Reproduce:**
Not sure about the exact steps, but a player on my server posted a work party with 3 different work projects. Shortly after posting this, the server went into a crash-loop where it crashes upon restart without fail. 

**Expected behavior:**
No crash.

**Actual behavior:**
Crash.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods installed.

**Please provide log files.**
[log_220906110419.log](https://github.com/StrangeLoopGames/EcoIssues/files/9500739/log_220906110419.log)

**Comment by Bazzi89** [comment] 2022-09-07 00:48
We have the same issue and for some reasons it only happens if the contract/workparty creator delete the payment option and add a new one, if u only edit instat of deleting the payment option, there is no problem... u can delete the reputation but not the payment option

hope it helps

**Comment by D3nnis3n** [comment] 2022-09-07 03:03
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23399

**Closed by D3nnis3n** 2022-09-07 03:03 UTC
