### ISSUE TITLE
Database Lock causing players to be dumped to  menu

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6080] opened 2018-03-15 09:52 UTC
This is happening during each autosave and when it happens all players on the server are being kicked off the server, although it does not crash, but everyone is disconnected.

--BEGIN DUMP--
Dump Time
03/10/2018 22:54:05

Exception
System.Exception: Caught exception invoking RPC SendChat on ChatManager!

Timeout. Database is locked for more than 00:01:00.

Stack:
   at LiteDB.LockService.Write()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

**Comment by Last2Night** [comment] 2018-03-15 14:29
Getting same problems. Due to constant server crashes and save rollbacks i had to set save and backup to every 5 minutes in order to minimize the rollbacks, now these database lockups kick players all the time.

**Comment by pamduncan** [comment] 2018-03-15 17:49
In some cases I believe the server maybe following this error and kicking people with an undocumented "crash" where the server stops.  A crash report is not written but looking at times in server UI the server does appear to have just been restarted (on systems that auto restart after crashes).  In other cases people are reporting that server is "stopped" and has to be restarted but all they get is a ClientUpdateException NullReferenceExceptionXXXXXX.ecodmp and not a Crash NullReferenceExceptionXXXXX.ecodmp.  Perhaps the server is unable at some times to recover from the locked db state and so shuts down but does not write a crash log?

**Comment by MarjieAVolk** [comment] 2018-03-16 00:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343

**Comment by MarjieAVolk** [comment] 2018-03-16 00:06
@Last2Night I have reason to believe that these crashes tend to happen during saving/backup, so that might be counterproductive unfortunately.

**Closed by MarjieAVolk** 2018-03-16 00:05 UTC
