### ISSUE TITLE
USER ISSUE: Icon Fixed on screen

### ISSUE THREAD

**Issue by alvimpaulo** [StrangeLoopGames/EcoIssues#4569] opened 2018-02-15 07:35 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Happens sometimes when I try to move itens between containers and let go of the mouse button in the middle of slots. Has happend 2 times so far

**Expected behavior:**
The item icon should have gone back to the original positions, or snapped to either "new slot"

**Actual behavior:**
The item icon keeps fixed on screen, even after closing the container. However, it seems to disapear on alt+tab.

Image of the icon fixed to the screen:
http://steamcommunity.com/sharedfiles/filedetails/?id=1301986704

**Comment by MarjieAVolk** [comment] 2018-02-22 23:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-02-22 23:25 UTC
