### ISSUE TITLE
USER ISSUE: Floating Logs that Crash Local Servers

### ISSUE THREAD

**Issue by Belcusas** [StrangeLoopGames/EcoIssues#5382] opened 2018-03-04 19:04 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.Open a local server
2.Chop down a tree
3.Chop tree into small enough sections to grab
4. Leave the server
5.Return to the server
6.The logs will start to float up into the atmosphere 

**Expected behavior:**
Occasionally the logs can be grabbed, but 95% of the time they just instantly crash the server and a popup message appears.

**Actual behavior:**
The following error message popped up:
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-03-05 20:04
Fixed in next release

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-03-05 20:04 UTC
