### ISSUE TITLE
Bank and registrar should not work when the object is disabled 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12759] opened 2019-07-15 22:05 UTC
Currently they work just dandy.
Prevent selecting or adding/removing entries when the object is disabled.

**Comment by D3nnis3n** [comment] 2019-07-16 11:06
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12519

**Closed by D3nnis3n** 2019-07-16 11:06 UTC
