### ISSUE TITLE
Black bar growing during character selection screen (staging 8.1)

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#11795] opened 2019-03-29 06:22 UTC
![image](https://user-images.githubusercontent.com/12839021/55213311-2b0ee080-51b0-11e9-986a-1204945acd6c.png)

**Comment by seccombew** [comment] 2019-03-29 06:23
![image](https://user-images.githubusercontent.com/12839021/55213430-77f2b700-51b0-11e9-9ffe-b10d9144407a.png)

Alt-tab'ed back into game to find this.

**Comment by seccombew** [comment] 2019-03-29 06:24
Black spots were dripping down like ink.
Rotated camera, and now fully black.
![image](https://user-images.githubusercontent.com/12839021/55213494-a8d2ec00-51b0-11e9-9be1-31b814318df4.png)

**Comment by Quadbro** [comment] 2019-03-29 08:51
did you able to reproduce it 2 times?

**Comment by seccombew** [comment] 2019-03-29 08:54
Only occurred once for me.
@SeanAtr0n thought it might have to do with temporal anti-aliasing, which I did have turned on.

**Comment by Quadbro** [comment] 2019-03-29 09:24
nah, tried to reproduce it with different specs and conditions (inc anti-aliasing)... nothing =(

**Comment by SeanAtr0n** [comment] 2019-04-01 18:16
a bug we can't reproduce isn't critical priority

**Comment by SeanAtr0n** [comment] 2019-04-01 18:20
if this happens again the log file might be useful `%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by johnkslg** [comment] 2019-04-02 17:16
Reproducibilty doesnt affect priority.    This will break the game for people and is critical.
@seccombew work with Sean to find a repro case?

**Comment by seccombew** [comment] 2019-04-02 18:38
Moving to milestone 8.2, will be attempting to reproduce.

**Comment by johnkslg** [comment] 2019-04-09 18:22
Closing until its seen a second time.

**Closed by johnkslg** 2019-04-09 18:22 UTC
Labels: Critical Priority, Investigate, Needs Information, Not reproduced
