### ISSUE TITLE
USER ISSUE: Hammer Time

### ISSUE THREAD

**Issue by mjallen26** [StrangeLoopGames/EcoIssues#4111] opened 2018-02-08 11:58 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Forge iron hammer on anvil.

**Expected behavior:**
It should be visible.

**Actual behavior:**
Its Invisible when using.

**Comment by FRodz80** [comment] 2018-02-08 12:46
To clarify, it's invisible in first person view. Other players see you holding a hammer.

**Comment by mjallen26** [comment] 2018-02-08 13:54
Sorry yeah I can see it in third person but not first person, I’m only
playing by my self so don’t have anyone to back me up lol. The stone hammer
is fine as are all the other tools, it’s just the iron hammer.

**Comment by ecoemmeck** [comment] 2018-02-08 17:25
I made a report about this a while ago and apparently it's fixed and should be getting released soon

**Comment by Conchipedia** [comment] 2018-02-08 17:36
Iron hammer has no in hand model #2478

**Comment by ecoemmeck** [comment] 2018-02-08 17:55
Thanks conchipedia

**Comment by Conchipedia** [comment] 2018-02-08 19:59
you are welcome @ecoemmeck , i was scanning githubs anyway 😄

**Comment by MarjieAVolk** [comment] 2018-02-09 02:26
Yes thanks, closing as duplicate of #2478 

This will be fixed in the next hotfix

**Closed by MarjieAVolk** 2018-02-09 02:26 UTC
