### ISSUE TITLE
[ 0.9.0.0 beta staging-1728] Art / Texture issue Ashlar Chimney

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17777] opened 2020-08-18 17:30 UTC
Below is top view of the Chimney block which other then Limestone needs to be looked at in terms of texture resolution and match up to the materials ( sides looks fine just the topside of the block that looks funky )

They could easily be done the same way Limestone variation is doing it, with a separate grid / cover line around; they don't necessarily need to be having the "brick" style art on them ?

![Screenshot_32](https://user-images.githubusercontent.com/24981362/90545416-ea3eaf80-e188-11ea-8bcc-ae390a969088.jpg)
![Screenshot_27](https://user-images.githubusercontent.com/24981362/90545417-ead74600-e188-11ea-80b8-a6b53ed2ba73.jpg)
![Screenshot_28](https://user-images.githubusercontent.com/24981362/90545420-ec087300-e188-11ea-8302-8730b59dacd0.jpg)
![Screenshot_29](https://user-images.githubusercontent.com/24981362/90545422-eca10980-e188-11ea-8f94-9768a1b0e0a3.jpg)
![Screenshot_30](https://user-images.githubusercontent.com/24981362/90545425-ed39a000-e188-11ea-9189-67daca4820b0.jpg)
![Screenshot_31](https://user-images.githubusercontent.com/24981362/90545428-edd23680-e188-11ea-9dff-d420fd9c0bee.jpg)

**Comment by keegan-o** [comment] 2020-09-14 21:12
Phlo, assigning this one to you- compare the limestone chimney top texture/mesh with those used in other blocks and correct them to be like limestone (if it's all the same model, the issue is in the detail textures for sets other than limestone, or if they're different models, make sure the others are set to use the limestone's instead).

**Comment by keegan-o** [comment] 2020-11-30 20:25
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/bc9db354-aa9a-49ab-b388-e79ae66ae5c4)
fixed for 9.3, maybe will put in 9.2 as well.

**Closed by keegan-o** 2020-11-30 20:25 UTC
Labels: Category: Art, Priority: Medium
