### ISSUE TITLE
USER ISSUE: Piping smog moves the visual effect, but air pollution does not relocate

### ISSUE THREAD

**Issue by raymondwilliamskc** [StrangeLoopGames/EcoIssues#19223] opened 2020-11-09 20:53 UTC
\
**Version:** 0.9.1.2 beta release-111

**Steps to Reproduce:**
1. Create a smog polluting item (combustion generator was what I noticed issue on)
2. Pipe the smog output elsewhere
3. Turn on the machine and wait
4. Visual smog will output from pipe, but the air pollution will still be centered upon the machine

**Expected behavior:**
Air pollution should be centered on the smog output

**Actual behavior:**
Air pollution is still centered on the machine instead of the smog output

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment] 2020-11-10 06:55
merged to #17316

**Closed by SlayksWood** 2020-11-10 06:55 UTC

**Comment by Conchipedia** [comment] 2020-11-10 17:58
Werent pipes introduced to **encourage** players to make an effort to **move** pollution away?

**Comment by mirasrael** [comment] 2020-11-11 06:57
@Conchipedia issue was closed because duplicate of another issue. Please continue discussion in #17316
