### ISSUE TITLE
Alpha.6 [B8ce025e] Can't destroy Repair Station with Hammer

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2295] opened 2017-09-26 16:02 UTC

**Comment by Fank** [comment] 2017-09-26 16:20
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2243 ?

**Comment by MarjieAVolk** [comment] 2017-09-26 17:56
Yes, thank you

**Closed by MarjieAVolk** 2017-09-26 17:56 UTC
