### ISSUE TITLE
Law: Species selection not possible when server language is not english

### ISSUE THREAD

**Issue by faiith** [StrangeLoopGames/EcoIssues#11730] opened 2019-03-22 10:16 UTC
I have a problem designing a law to protect a species. There is no possibility to select the species in the mask, even though it should actually be there (see attached screenshot). I have tested with Firefox, IE and MS Edge.

Client and server version: 0.8.7
Installed mods: none

![law_spezies](https://user-images.githubusercontent.com/40213281/54816135-cc1f0800-4c93-11e9-94c3-0970fc8b585d.png)

**Comment by FalkosTMB** [comment] 2019-03-22 12:31
Ernten = harvest

**Comment by D3nnis3n** [comment] 2019-03-22 14:41
As a workaround, change server language to english.

**Comment by D3nnis3n** [comment] 2019-03-22 23:38
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11407

**Closed by D3nnis3n** 2019-03-22 23:38 UTC
Labels: Investigate
