### ISSUE TITLE
Bloomery is invisible

### ISSUE THREAD

**Issue by dwujcik** [StrangeLoopGames/EcoIssues#9291] opened 2018-09-09 18:57 UTC
Bloomery is invisible
Should be visible.
version 0.7.7.0 beta
 
![20180909020933_1](https://user-images.githubusercontent.com/17785084/45267735-cf2e7580-b472-11e8-9e10-4c97d30ebecc.jpg)

**Comment by D3nnis3n** [comment] 2018-09-10 18:43
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/9263

**Comment by craig-jong** [comment] 2018-09-10 22:03
Keegan let me know if this is something code side, but I don't think it is.

**Comment by keegan-o** [comment] 2018-09-11 17:15
![image](https://user-images.githubusercontent.com/14983165/45376026-9f36bd80-b5ab-11e8-902f-46bf45a9e26c.png)
Can't repro this or the blast furnace on release branch....

**Comment by D3nnis3n** [comment] 2018-10-28 15:41
Closed for being a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9263

**Closed by D3nnis3n** 2018-10-28 15:41 UTC
Labels: Low Priority, Needs Information, Not reproduced
