### ISSUE TITLE
USER ISSUE: Value can not ne null

### ISSUE THREAD

**Issue by lethyro** [StrangeLoopGames/EcoIssues#5701] opened 2018-03-08 19:44 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Value cannot be null.
Parameter name: item


Stack:
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-08 22:35
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Closed by MarjieAVolk** 2018-03-08 22:35 UTC
