### ISSUE TITLE
USER ISSUE: Currency duplication bug

### ISSUE THREAD

**Issue by Kudesunik** [StrangeLoopGames/EcoIssues#19725] opened 2020-12-13 20:34 UTC
Currency duplication bug: while pressing Mark Failed button, contract payment currency amount added to user account;

**Version:**
0.9.1.8 beta release-130

**Steps:**
1) Create contract;
2) Acceptor must press complete button;
3) Wait when time left on contract;
4) Press "Mark Failed" button;

**Expected behavior:**
Money returns to account, contract disappear;

**Actual behavior:**
Money returns to account, contract not disappear, can press button again;

**Mods installation:**
No mods;

**Screenshots:**

_Contract:_
![image](https://user-images.githubusercontent.com/3079145/102022989-7cec0580-3d9b-11eb-9dce-aea09ffbded3.png)

_"Mark Failed" button pressing result:_
![image](https://user-images.githubusercontent.com/3079145/102023003-9b520100-3d9b-11eb-8910-d9df803e87a5.png)

**Logs:**
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5685406/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5685407/Player-prev.log)

**Comment by IcedForge** [comment] 2020-12-21 10:53
Thank you for reporting.
This seems to be resolved in 9.2, state updates as failed and removes buttons in the ui

**Comment by IcedForge** [comment] 2020-12-21 11:07
I missed a step in reproduction, seems like there are some underlying issues, i get server error logs with escrow account sum being put into negative as well.
![Screenshot_4](https://user-images.githubusercontent.com/24981362/102770637-c2549800-4384-11eb-91d8-81ca249a4427.jpg)
Yet it still pays out the initial amount each time.

It should verify and remove the contract once you hit mark failed.
It does NOT do this IF the above steps are followed.
![Screenshot_5](https://user-images.githubusercontent.com/24981362/102770859-1cedf400-4385-11eb-8b9f-c6b697231213.jpg)

**Comment by SlayksWood** [comment] 2020-12-25 10:07
![image](https://user-images.githubusercontent.com/45708377/103131519-28595c00-46b2-11eb-99d0-5a16387a6aeb.png)

**Closed by SlayksWood** 2020-12-25 10:07 UTC
Labels: Category: UI, Priority: High, Status: Fixed, Status: Needs Triage, Type: Exploit
