### ISSUE TITLE
[0.9.3 staging-1942] Advanced Settings in Title issue

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20787] opened 2021-03-01 07:55 UTC
- [ ] 1. Missing Submit button:
![image](https://user-images.githubusercontent.com/45708377/109467191-dea73c00-7a7b-11eb-8102-b53751f301f6.png)

- [ ] 2. If you press ESC or 'X' to close Advanced settings window then changes should not be saved. 
Step to reproduce:
- advanced settings window, add any currency to wages, but don't add bank account. You will have error:
![image](https://user-images.githubusercontent.com/45708377/109467522-583f2a00-7a7c-11eb-8733-593a561b4e3e.png)
- press 'X', your changes were saved and your have title with invalid error:
![image](https://user-images.githubusercontent.com/45708377/109467602-7b69d980-7a7c-11eb-9def-f97b7faac9a8.png)

**Comment by tomsseisums** [comment] 2021-03-01 17:25
As part of a fix for https://github.com/StrangeLoopGames/EcoIssues/issues/20666 and prior changereq on https://github.com/StrangeLoopGames/Eco/pull/7794#pullrequestreview-589826330 (assigned via https://github.com/StrangeLoopGames/EcoIssues/issues/20520), we figured that Submit button should be removed and autosave kept as it's the better UX for Appointed Titles.

The Title itself is also valid for use in Law's even if it has invalid Wages setup, as Wages for Appointed Titles go outside the realms of the Law anyway.

Something should be done about the lingering error now. Though, that's how it was before too. The fixes I implemented only hide the Submit button and allow invalid Wages to be passed as valid for use in Law.

**Comment by tomsseisums** [comment] 2021-03-01 18:01
Could you check in a pre-fix version (possibly release) if an invalid Title can be saved and used and the error reproduced?

**Comment by johnkslg** [comment] 2021-03-16 02:17
Editing titles will edit them 'live', thats why theres no submit button.
Thus if you add an error to it and close it, that error sticks around, and thats expected.  Closing as wontfix/by design.
Also we need to not get too tied up in little bugs like this, they suck up time and take away from much more important stuff, like optimization, etc.

**Closed by johnkslg** 2021-03-16 02:17 UTC
Labels: Category: Gameplay, Category: UI, Priority: Medium, Regression, Squad: Mountain Goat, Status: Won't Fix, Type: Bug

**Comment by D3nnis3n** [comment] 2021-03-17 08:25
@johnkslg Respecting your closing of this, but need to give an opinion in favor of players:

We at least should add a text "Changes are saved automatically." somewhere visible. One of our focuses is QoL and UX. A user would not expect that "x" saves the data. Websites currently start to use 'new technology' to do instant saves on settings pages without a submit button and those are still confusing for many users, searching for a submit button. Those, in opposite to Eco, do show hints that stuff has been autosaved and do not save by "x" button, though. So this currently is a UX nightmare.

I get if the submit button is too hard to implement. But if autosaving like that is intended we should at least tell people, so they get it and don't get confused. That just adds to "Eco is confusing, overloaded and I don't get how it works". Especially in the most complex area of Eco - the law system.
