### ISSUE TITLE
USER ISSUE: Cutting down tree

### ISSUE THREAD

**Issue by werkrat** [StrangeLoopGames/EcoIssues#6041] opened 2018-03-14 16:46 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
step 1: hit a tree with a fucking stone axe
step 2: randomly crash, apparently
step 3: restart client
step 4: continue enjoying Eco :dancer: 

**Expected behavior:**
Maybe just cut the tree down next time...

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Specified argument was out of the range of valid values.
Parameter name: arrayIndex


Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.C

**Comment by MarjieAVolk** [comment] 2018-03-16 01:27
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5527

**Closed by MarjieAVolk** 2018-03-16 01:27 UTC
