### ISSUE TITLE
USER ISSUE: No Mushrooms

### ISSUE THREAD

**Issue by Fuchur414** [StrangeLoopGames/EcoIssues#5928] opened 2018-03-11 22:06 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Create a normal World

**Expected behavior:**

**Actual behavior:**
There are no Mushrooms on the entire map

**Comment by rpsiv** [comment] 2018-03-12 00:04
I am also having this issue, which makes it impossible to get the farming skill.

**Comment by PoK-Micky** [comment] 2018-03-12 03:58
Also having this issue, I also cant find rice in my wetlands, unless rice is bunchgrass.

**Comment by MarjieAVolk** [comment] 2018-03-13 00:09
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Closed by MarjieAVolk** 2018-03-13 00:09 UTC
