### ISSUE TITLE
USER ISSUE: Crash when chopping tree

### ISSUE THREAD

**Issue by dlouwers** [StrangeLoopGames/EcoIssues#6805] opened 2018-03-31 15:30 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Chop tree on ground

**Expected behavior:**
Chopped the tree

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60,00%>Object reference not set to an instance of an object.

   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment] 2018-04-02 21:55
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-04-02 21:55 UTC
