### ISSUE TITLE
USER issue - getting hunting xp for every arrow shot instead of when an animal is hit

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19033] opened 2020-11-02 00:39 UTC
USER issue - getting hunting xp for every arrow shot instead of when an animal is hit

maybe this was changed? it used to be gain xp only when an animal is hit

**Comment by SlayksWood** [comment] 2020-11-02 08:16
I have this problem in staging-1831 and don't have it in 0.9.0.5, so regression.

**Comment by SlayksWood** [comment] 2021-01-14 08:07
I have "Double" expirience with bow too like here #19039
![image](https://user-images.githubusercontent.com/45708377/104561134-f48da880-5657-11eb-8341-dd0b3db241a7.png)
per hit and per damage. should be only per damage.

**Comment by MazonDel** [comment] 2021-01-15 08:48
> I have "Double" expirience with bow too like here #19039
> ![image](https://user-images.githubusercontent.com/45708377/104561134-f48da880-5657-11eb-8341-dd0b3db241a7.png)
> per hit and per damage. should be only per damage.

Currently when you use tools you have a specialty in (ex: Bow for Hunting), you get experience every time you use the tool (higher tier tools give more experience) and you get experience for accomplishing something with the tool.

So for the bow, if you fire the bow but miss an animal, you gain experience for using the bow even though you missed the target.

**Comment by mirasrael** [comment] 2021-01-15 09:46
You should get only XP either for shot or for hit. Not both. So if you hit animal then you get full XP, but if you miss then you can get like 10% of XP. 
Also it may be easily abused. You can just find tree and level up hunting on it even with arrows refund (because you can collect them after hit).
So in my opinion it should be:
1. Significantly less experience for miss than for hit. Probably it should give you experience with some chance (not always).
2. It should only allow you to level up with misses first few levels of skill. No high skill leveling with misses. So there is training stages, but then you should master you skill with real results.

With mining sample it isn't totally correct. For mining you get XP for every hit (damage to stone), like for animal you get XP for every hit to animal (damage). But you don't get XP for mining if you just swing in the air :)

**Comment by WeaselDog** [comment] 2021-01-17 17:28
Please remove all experience from using a bow other than the experience from damage. We are not supposed to have double exp.

**Comment by Daniel-Magulado** [comment] 2021-02-24 08:45
Tested on 0.9.4 Develop 192.

Fixed and closing.

**Closed by Daniel-Magulado** 2021-02-24 08:45 UTC
Labels: Category: Balance, Priority: Medium, Regression, Squad: Otter, Status: Fixed, Status: Reopen
