### ISSUE TITLE
Server is not showing up in server list

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#5313] opened 2018-03-02 23:11 UTC
I am attempting to run a dedicated server for my friends and I to try Eco. For whatever reason the server is having a hard time showing on the browser list. I have opened my local firewalls on machine and at the router/firewall level. Port scan shows open for 3000/3001 UDP and TCP.

Similar to issue: https://github.com/StrangeLoopGames/EcoIssues/issues/5085

**Comment by MarjieAVolk** [comment] 2018-03-03 00:37
Just to double check, in your server's window, do you have Network>Config>Public Server set to true?

**Comment by ferPekt** [comment] 2018-03-03 10:23
Hi!
I have experienced the same issue.
Just as ShaydenMac did I opened all the ports necessary and I set the server to show in the public list within the server console.
I have read a lot about setting up ECO servers lately but I haven't found anything that could help me.
I also contacted the support via email but they said they experience a lot of incoming questions so it could take a while to get an answer.
I really don't know what to do - I would love to finally start playing this awesome game but I just can't :'(
Best Regards
ferPekt

**Comment by MarjieAVolk** [comment] 2018-03-06 01:00
Might be related to https://github.com/StrangeLoopGames/EcoIssues/issues/5414

**Comment by MarjieAVolk** [comment] 2018-03-06 01:01
If your friends can't find or see your server, they might also try adding the server via ip address and connecting that way.

**Comment by MarjieAVolk** [comment] 2018-03-06 02:26
Gonna close as a duplicate of #5414 unless I hear differently from you guys ;)

**Closed by MarjieAVolk** 2018-03-06 02:26 UTC
