### ISSUE TITLE
7.0.2 Player is getting kicked and then cannot log back in

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3933] opened 2018-02-05 20:19 UTC
Player is getting kicked form server and then cannot log back in.  At the same time he is reporting being kicked this exception is thrown.  Not sure if its related:

--BEGIN DUMP--
Dump Time
02/05/2018 08:59:00

Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()

--END DUMP--

**Comment by craig-jong** [comment] 2018-02-06 01:58
Any idea what tree type this was?

**Comment by MarjieAVolk** [comment] 2018-02-07 23:46
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-02-07 23:46 UTC
Labels: High Priority
