### ISSUE TITLE
9.5 Staging 2198 - Migration issues with civics (No civic duties at all or elected titles)

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22938] opened 2022-01-12 21:43 UTC
Migration issues with Govt from 9.4.5 > 9.5 staging 2198

Chars lose "Civic duties", elected titles have also vanished, confirmed with Ice Forge/Jens and tested a bit with Khairi

If a new char never before on the server now joins the 9.5 world, they will get civic duties.

Message me on discord mishka#1337 for save file the mods it has (Note it 7.4km so need 16GB+ ram 

Migration Log
[2022-01-12.log](https://github.com/StrangeLoopGames/EcoIssues/files/7857965/2022-01-12.log)

9.4.5 (pics by Ice Forge/Jens)
![image](https://user-images.githubusercontent.com/61889138/149225530-efacd379-dbe2-4c41-a160-a9aed48f98dd.png)

![image](https://user-images.githubusercontent.com/61889138/149225538-696704c6-c9f8-4cb3-aeb0-fdfd6cc22d58.png)

9.5 Staging 2198
![image](https://user-images.githubusercontent.com/61889138/149225564-6d620301-827e-4722-a69d-dec1347096e4.png)

![image](https://user-images.githubusercontent.com/61889138/149225569-e370c84c-37b6-4fe7-8883-4f21c7578868.png)

No elected titles show up in 9.5 anymore but show on the government office

![image](https://user-images.githubusercontent.com/61889138/149225615-988eccd6-9b07-4a72-8711-cc47b2725ffc.png)

**Comment by TwixterZ** [comment] 2022-01-18 10:11
@MishkaFur Thank you for finding the cause of this issue, I have notified our developer accordingly.

For internal use: https://app.clickup.com/t/23zwe3n

**Comment by TwixterZ** [comment] 2022-03-16 07:16
@MishkaFur This is now fixed as of 9.5 Staging - 2252
Thanks for your support as always

**Closed by TwixterZ** 2022-03-16 07:16 UTC
