### ISSUE TITLE
Disconnecting from server makes UI disappear when reconnecting #4c637828

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2248] opened 2017-09-22 20:22 UTC
When i choose option Disconnect on menu, when i return the UI has gone, ive tried 3 times in a row, still no UI, then i choose Quit, Windows says Eco.exe has stopped working (closed it via Task Manager End process). Now the only issue when loading Eco back in is that i have to go into Esc menu (not needing to change any settings) to get my chosen Lock time to Noon to come back on.

**Comment by Conchipedia** [comment] 2017-09-22 20:24
this is an improvement overt issue i had before, if i chose Disconnect it wouldnt load server list in (at least i can get back in)

**Comment by MarjieAVolk** [comment] 2017-09-22 20:26
Does the same thing happen as in https://github.com/StrangeLoopGames/EcoIssues/issues/2231?

**Comment by Conchipedia** [comment] 2017-09-23 05:39
u can only see the co2 ouput yes

**Comment by MarjieAVolk** [comment] 2017-09-25 17:45
Okay then I'm closing this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2231

**Closed by MarjieAVolk** 2017-09-25 17:45 UTC
