### ISSUE TITLE
USER ISSUE: Movement locked after renaming an item when using {ESCAPE} afterwards

### ISSUE THREAD

**Issue by Cyber-Wolf** [StrangeLoopGames/EcoIssues#4264] opened 2018-02-10 18:14 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. Enter the stockpile UI (also happens for chest, etc)
2. Click the rename button and type a new name
3. Hit {Enter}
4. Hit {ESCAPE}

Note, the "fix" is:
Mouse wheel or use an equiped item (IE: using a hoe on dirt) as it seems to "reset" your input.

**Expected behavior:**
Not prevent you from moving/walking

**Actual behavior:**
You cant move or use the number keys to select items.

**Comment by Cyber-Wolf** [comment] 2018-02-10 18:36
Note, this does not happen when closing the window using the mouse.

**Comment by Argetlam-Elda** [comment] 2018-02-11 18:27
This also happens when you open a store and close it without doing anything.

**Comment by MarjieAVolk** [comment] 2018-02-13 03:10
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115 . You can track the issue progress there.

Thanks for the additional details and repro steps.  That should make this much easier to debug.

**Closed by MarjieAVolk** 2018-02-13 03:10 UTC
