### ISSUE TITLE
[0.9.1.8] Beet Greens turn to garbage?

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19806] opened 2020-12-20 21:28 UTC
So I'm in the late game and had a good deal of Beet Greens that I didn't know what to do with. I remembered some people dumping such things on the ground to turn them into compost, so I did that with like, 10-15 stacks. The next day I was surprised to see that some of them turned into garbage, while others turned into compost:

![image](https://user-images.githubusercontent.com/964559/102724742-b4404200-42c6-11eb-9404-9a2d1e28ff3b.png)

Not sure if that's intentional. It might have had something to do with dumping large stacks of them in the same place perhaps? Ideally, such trash would turn into compost regardless of how many you dump.

It would also be nice to have something like https://github.com/StrangeLoopGames/EcoSuggestions/issues/1090 to compost such items, but that's perhaps a feature for another day ;).

**Comment by SlayksWood** [comment] 2020-12-21 13:32
I can't reproduce, did you add only beet greens?

**Comment by ThePiachu** [comment] 2020-12-21 19:52
It was on a private Cloud World, nobody else has been online for 2 weeks. I stood in one spot, dumped like 15 stacks of them until they piled on top of one another and then left it alone overnight.

**Comment by TimoNuernberg** [comment] 2021-01-11 12:00
I have the same garbage problem, 
I put Zedernsamen & Eiche on the same place,
one will be garbage one will be kompost.

**Comment by IcedForge** [comment] 2021-05-03 12:14
Stacked up 2500 beet greens and none of it got turned into garbage, i also tested mixing in other different compost materials as well and non got turned into garbage.

![Screenshot_69](https://user-images.githubusercontent.com/24981362/116874399-8fb38980-ac19-11eb-84c5-508ca06515aa.jpg)
![Screenshot_71](https://user-images.githubusercontent.com/24981362/116874400-904c2000-ac19-11eb-84c4-e32606df3396.jpg)

Are you still running into issues with beet greens?

**Comment by ThePiachu** [comment] 2021-05-05 22:20
I have not tested it since, so maybe it was some weird fluke. I'll report it again if it happens.

**Comment by IcedForge** [comment] 2021-05-06 10:46
Will close it for now then, it might have been fixed by another issue as well or it might have been some item declaration that were changed.

**Closed by IcedForge** 2021-05-06 10:46 UTC
Labels: Status: Investigate
