### ISSUE TITLE
Redwoods and Jacaranda are visually "dead": steam linux runtime visual bug

### ISSUE THREAD

**Issue by dsweber2** [StrangeLoopGames/EcoIssues#22554] opened 2021-08-21 20:35 UTC
Started a brand new world using 0.9.4, and all of the redwoods, old growth redwoods, and joshua trees look dead (but not the other trees), like in the following pictures
![20210820234636_1](https://user-images.githubusercontent.com/7095649/130334078-922fd272-bc2e-4077-95dd-ae976d71e7ae.jpg)
![20210821131107_1](https://user-images.githubusercontent.com/7095649/130334068-375e15c7-77c7-45f6-b304-20bed4f08e24.jpg)

However, they are not, and the soil is generally perfect for them:
![20210821130302_1](https://user-images.githubusercontent.com/7095649/130334070-bd213dfc-c1eb-408a-b6ad-36f16585f2a1.jpg)

The same thing happened when I logged into white tiger. However, switching over to the Proton 6.3-6 compatability tool instead of the steam linux runtime eliminated the problem, so it seems like a purely visual bug limited to the linux runtime.

I was, incidentally, glad to see the upside-down tools were dealt with in this update. Thank you for the effort you all have put into making this game.

**Comment by redwyre** [comment] 2021-11-09 13:34
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18081

**Comment by redwyre** [comment] 2021-11-09 13:35
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18416

**Closed by redwyre** 2021-11-09 13:34 UTC
Labels: OS: Linux
