### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Berbe** [StrangeLoopGames/EcoIssues#24661] opened 2024-01-20 15:04 UTC
User: _Will only disclose privately. How?_
Version: `0.10.1.1 beta release-579`
Mods: `None`

Crash

[Crash_2024-01-20_145426612.zip](https://github.com/StrangeLoopGames/EcoIssues/files/13998317/Crash_2024-01-20_145426612.zip)

**Comment by D3nnis3n** [comment] 2024-01-20 20:06
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24548

**Closed by D3nnis3n** 2024-01-20 20:06 UTC
