### ISSUE TITLE
USER ISSUE: Trying to Join Greenleaf prime server throws up Error

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4320] opened 2018-02-11 14:05 UTC
**Version:** 0.7.0.8 beta

I can Join other servers just Not this one
Add server = **prime.greenleafserver.com**

**Error i get is:-**

<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Plugins.Networking.Clients.Client.ShouldSelectUser()

**Tried Both Steam And SLG version**

**Comment by Phlo123** [comment] 2018-02-11 14:15
The game save:
https://www.dropbox.com/s/dyfr5jc2ndrs0dx/Game.eco?dl=0

**Comment by MarjieAVolk** [comment] 2018-02-13 03:43
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4413

We already have a fix for this, and it should be hotfixed soon.  Unfortunately you may not be able to connect until it rolls out.  :'(  Sorry guys!

**Closed by MarjieAVolk** 2018-02-13 03:43 UTC
