### ISSUE TITLE
USER ISSUE: Upside down tools

### ISSUE THREAD

**Issue by Wmobios1** [StrangeLoopGames/EcoIssues#18401] opened 2020-09-22 13:22 UTC
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
Unknown since it loads like this.

**Expected behavior:**
Tools should be normal on screen.

**Actual behavior:**
Tools are upside down on screen.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5261626/Player.log)
![Screenshot from 2020-09-22 09-20-35](https://user-images.githubusercontent.com/71710194/93887664-fd2b2f00-fcb4-11ea-8094-3f099e60cf0e.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5261649/Player.log)

**Comment by redwyre** [comment] 2020-09-22 19:53
Duplicate of #18414

**Closed by redwyre** 2020-09-22 19:53 UTC
