### ISSUE TITLE
Repeating Contracts are bugged

### ISSUE THREAD

**Issue by CraigCooper1** [StrangeLoopGames/EcoIssues#4211] opened 2018-02-10 01:12 UTC
So I have a contract to put a bison in a chest, I have it repeat ten times so that 10 people can put 10 bisons in, however, once one person accepts the contract it deletes the bison from the item list? is this how it is intended? or am i missing something?

**Comment by LiaungYip** [comment] 2018-02-10 06:10
Duplicate of #4161.

**Comment by MarjieAVolk** [comment] 2018-02-13 05:31
Thanks.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4161.  You can track the issue progress there.

**Closed by MarjieAVolk** 2018-02-13 05:31 UTC
Labels: Medium Priority
