### ISSUE TITLE
Excavators slide down on ramps

### ISSUE THREAD

**Issue by alecpura** [StrangeLoopGames/EcoIssues#5738] opened 2018-03-09 00:51 UTC

**Comment by PerksPrisoner** [comment] 2018-03-09 00:59
While this has no defining information I will mention I am aware of the problem myself. For some reason once it starts going doing the ramp it won't stop you almost can't stop it once it has started on a flat surface until it collides with something. The only way to force it to stop is by pressing "1" to switch it back into "excavating" mode from driving mode and back again.

**Comment by MarjieAVolk** [comment] 2018-03-09 20:09
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4436

**Closed by MarjieAVolk** 2018-03-09 20:09 UTC
