### ISSUE TITLE
Lite DB Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21527] opened 2021-04-23 02:17 UTC
Several reports of this litedb crash:
[message (6).txt](https://github.com/StrangeLoopGames/EcoIssues/files/6362213/message.6.txt)

This happens on loading existing worlds:
[Private (1).zip](https://github.com/StrangeLoopGames/EcoIssues/files/6362219/Private.1.zip)

And on creating new worlds, where a .db file does not get created:
[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6362222/Storage.zip)

**Comment by gzatravkin** [comment] 2021-04-23 04:56
Need some help on repro. Can't reproduce, server starts fine for me (at steam version). @IcedForge any ideas?

**Comment by IcedForge** [comment] 2021-04-23 09:46
Not sure, on the Private(1).zip world i am getting a migration 
so this is clearly not a 9.3.0 world need more extensive information from the affected players.

Fresh player log and server log on a clean load/creation of a world.
DXdiag
OS type and specific version ( we have had issues with worlds created in different windows builds )
```
[2021-04-23 11:42:00.845][ Info] Migration Log:
~ class[Eco.Gameplay.Civics.Demographics.Demographic] migration:
  + added BackupOwner: class[Eco.Gameplay.Aliases.IAlias].
~ class[Eco.Gameplay.Civics.Titles.AppointedTitle] migration:
  + added BackupOwner: class[Eco.Gameplay.Aliases.IAlias].
~ class[Eco.Gameplay.Civics.Titles.PositionHistory] migration:
  + added RemoveOccupant: bool.
~ class[Eco.Gameplay.Civics.Titles.Title] migration:
  + added BackupOwner: class[Eco.Gameplay.Aliases.IAlias].
~ class[Eco.Gameplay.Components.MinimapComponent] migration:
  - removed Category: string.
~ class[Eco.Gameplay.Economy.Jobs.RecurringTransfer] migration:
  + added TimeLastAttempt: double.
~ class[Eco.Gameplay.GameActions.RecurringPayment] migration:
  + added Earner: class[Eco.Gameplay.Aliases.IAlias].
~ class[Eco.Gameplay.GameActions.PayRentOrMoveInFee] migration:
  - removed Landlord: class[Eco.Gameplay.Aliases.IAlias].
  + added Earner: class[Eco.Gameplay.Aliases.IAlias].
~ migrated class[Eco.Gameplay.Items.ClothingInventory]
~ class[Eco.Gameplay.Items.InventoryRelated.VoidStorageWrapper] migration:
  + added Icon: string.
~ class[Eco.Gameplay.Civics.Titles.ElectedTitle] migration:
  + added BackupOwner: class[Eco.Gameplay.Aliases.IAlias].
- class[Eco.Gameplay.Tutorial.UserSubTaskInsertItems+State] removed.
- class[Eco.Mods.TechTree.HuntingUpgradeItem] removed.
```

**Comment by D3nnis3n** [comment] 2021-04-28 21:53
Having received several new reports of this from newly downloaded clients from SLG website.

**Comment by D3nnis3n** [comment] 2021-04-28 22:10
@gzatravkin @IcedForge
Happens on non-english system languages, one confirmed case is turkish.
Changing to english fixes it.

**Comment by redwyre** [comment] 2021-04-30 13:52
move to ready for QA since a fix is checked in

**Closed** 2021-05-05 11:51 UTC
Labels: Priority: Critical, Squad: Pumpkin, Status: Fixed
