### ISSUE TITLE
Server encountered an exception (2019-03-24 <|> 11:4)

### ISSUE THREAD

**Issue by PaffaLon** [StrangeLoopGames/EcoIssues#11721] opened 2019-03-21 10:16 UTC
**Version:** 0.8.0.7 beta

*I was not doing anything special, just moving some dirt from a stockpile to my cart. Wonderful for landfill but that that happened. I've added the log file in a zip file.
[Eco log error.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2991593/Eco.log.error.zip)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed, running pure vanilla here.

**Comment by mirasrael** [comment] 2019-03-21 10:48
Known issue, should be fixed in 8.1. Happens when multiple players removes same item.

**Comment by mirasrael** [comment] 2019-03-21 10:49
```
Server encountered an exception:

<size=60.00%>Exception: ArgumentException
Message:Object of type 'Eco.Gameplay.Items.AuthorizationInventory' cannot be converted to type 'Eco.Gameplay.Items.ItemStack'.
Source:mscorlib

System.ArgumentException: Object of type 'Eco.Gameplay.Items.AuthorizationInventory' cannot be converted to type 'Eco.Gameplay.Items.ItemStack'.
  at System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00071] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Reflection.MonoMethod.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParameterInfo[] pinfo, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00069] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00011] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <2943701620b54f86b436d3ffad010412>:0 
  at Eco.Shared.Networking.RPCManager.TryInvoke (Eco.Shared.Networking.INetClient client, System.Object target, System.String methodname, Eco.Shared.Serialization.BSONObject bsonArgs, System.Object& result) [0x00074] in <8cd268d4a2e24992b5496d02a2959a6f>:0 
  at Eco.Shared.Networking.RPCManager.InvokeOn (Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson, System.Object target, System.String methodname) [0x00056] in <8cd268d4a2e24992b5496d02a2959a6f>:0 
  at Eco.Core.Controller.ControllerManager.HandleViewRPC (Eco.Shared.Networking.INetClient client, System.Int32 controllerID, System.String methodname, Eco.Shared.Serialization.BSONObject bson) [0x00007] in <190c851680184fc897baec0c67196925>:0 
  at Eco.Plugins.Networking.Client.ViewRPC (Eco.Shared.Networking.INetClient client, System.Int32 id, System.String methodname, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <648920bde3a64e55b5764b071042b0b4>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <2943701620b54f86b436d3ffad010412>:0</size>
```

**Comment by mirasrael** [comment] 2019-03-21 10:50
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11695

**Closed by mirasrael** 2019-03-21 10:50 UTC
