### ISSUE TITLE
Tutorial does not teach how to get plant fibers

### ISSUE THREAD

**Issue by genom10** [StrangeLoopGames/EcoIssues#25290] opened 2024-12-04 18:11 UTC
Version: 0.11.1.3 beta release-795

Steps to Reproduce:
1. Log into new server
2. Restart Tutorial in the settings
3. Start following tutorial
4. After **Build a house**, the next quest, **Furnish Your House** asks you to craft a bed, which requires plant fibers

Expected behavior:
Before **Furnish Your House** quest, tutorial should teach you that plant fibers can only be obtained using a Sickle

Actual behavior:
The tutorial skips teaching players how to obtain plant fibers

Do you have mods installed? Does the issue happen when no mods are installed?:
No mods

**Comment by D3nnis3n** [comment] 2024-12-04 19:18
Thanks for the suggestion, I have made an internal note. Given this is not a bug, I'm closing the issue, though.

**Closed by D3nnis3n** 2024-12-04 19:18 UTC

**Comment by genom10** [comment] 2024-12-07 06:28
Thanks for the attention and for the great game!
Is there a better place to report such issues?
