### ISSUE TITLE
ASCII chars and Eco

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4939] opened 2018-02-22 08:50 UTC
Could we make it so that servers will either reject names with ascii char or else display them.  Whe used currently they do not show up in game meaning that the player appears as a blank and the admmin has no way to get a name to do anything with that player.  For example  "_Logins","338737.19874007","","ＭＡＸ  

The admin has to export a chat log and read the log with a text editor to get a players name in this circumstance which does not make for an easy way to ban qucikly if needed

**Comment by MarjieAVolk** [comment] 2018-02-23 19:35
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4160

**Closed by MarjieAVolk** 2018-02-23 19:35 UTC
