### ISSUE TITLE
USER ISSUE: Exception thrown on breaking leaves event

### ISSUE THREAD

**Issue by christianbhill** [StrangeLoopGames/EcoIssues#6933] opened 2018-04-03 17:50 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Ran and jumped off house, hit tree leaves with stone axe. Threw exception right away

**Expected behavior:**
Leaves break and player possibly gets seeds

**Actual behavior:**
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.TryDamageBranch(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>

**Comment by MarjieAVolk** [comment] 2018-04-03 17:51
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6879

**Closed by MarjieAVolk** 2018-04-03 17:51 UTC
