### ISSUE TITLE
Alpha 6.4.0 Stone Road the only Tier 1 Material 

### ISSUE THREAD

**Issue by Darkenwolf90** [StrangeLoopGames/EcoIssues#3291] opened 2018-01-09 09:12 UTC
![eco 6-4 tier 1](https://user-images.githubusercontent.com/35255524/34713029-c61b2140-f4d9-11e7-9e59-f20c8b9ccf02.png)

Tables not working in log house as stone roads are the only tier 1 material for room requirements.

**Comment by Huntermeign** [comment] 2018-01-09 12:09
Repeat of issue #3229

**Comment by Conchipedia** [comment] 2018-01-09 18:07
Duplicate of
Tier 1 materials seem to be just stone road not logs as it should be 6.4.0 #4142876a #3229

**Comment by Nanders** [comment] 2018-01-09 18:39
Duplicate of #3229

**Closed by Nanders** 2018-01-09 18:39 UTC
