### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by flounder922** [StrangeLoopGames/EcoIssues#24896] opened 2024-04-20 03:57 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
I don't know. I played earlier on my save then when I come back and try to load it back up it throws this error. Only way I found to fix it is restart my computer.		

**Expected behavior:**
Let me load into the game.

**Actual behavior:**
The following error message popped up:
```
Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-04-22 03:39
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24380

**Closed by D3nnis3n** 2024-04-22 03:39 UTC
