### ISSUE TITLE
Picking up some items (dirt ramp) ignores correct stacking procedures

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#2003] opened 2017-08-28 01:24 UTC
Staging Alpha 6.0.0 #E34aa2e5

![image](https://user-images.githubusercontent.com/30765409/29755993-28ea0274-8be3-11e7-8e65-23785f9debba.png)

**Comment by MarjieAVolk** [comment] 2017-09-06 18:19
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1945

**Closed by MarjieAVolk** 2017-09-06 18:19 UTC
