### ISSUE TITLE
USER ISSUE: Wood Cart disappeared

### ISSUE THREAD

**Issue by heimskringla** [StrangeLoopGames/EcoIssues#5475] opened 2018-03-06 16:13 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
parked WoodCart on DirtRamp and loaded w. dirt and stone

**Expected behavior:**
should have staid there

**Actual behavior:**
disappeared when I was not looking - I assume if fell through the world? I still have the deed. Parked another Cart nearby but could not access the Inventory of the disappeared Cart

**Comment by MarjieAVolk** [comment] 2018-03-07 22:09
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4249

Sounds like the cart has teleported/flown away.  Can you see where the cart is located by looking at the deed for the cart?

**Closed by MarjieAVolk** 2018-03-07 22:09 UTC
