### ISSUE TITLE
Cast IRON STOVE / HOME Cooking missing --> Recipe

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2426] opened 2017-10-01 15:13 UTC
![grafik](https://user-images.githubusercontent.com/26040573/31056012-bbe4db82-a6cb-11e7-8e8a-a7c4ce55c488.png)

**Comment by Fank** [comment] 2017-10-01 15:56
Duplicate of #2373

**Comment by REPOSEECO** [comment] 2017-10-01 16:09
upps soory i search for Cast IRON STOVE / HOME Cooking nothing was found

**Comment by MarjieAVolk** [comment] 2017-10-02 17:36
Yep probably because it's already been fixed on master.  Will be fixed in the next release

**Closed by MarjieAVolk** 2017-10-02 17:36 UTC
