### ISSUE TITLE
fails to connect to new world seed

### ISSUE THREAD

**Issue by Ghostdk3** [StrangeLoopGames/EcoIssues#12323] opened 2019-05-16 16:12 UTC
After generating a new world i get a cannot connect every time. Here is the log

<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2018.3.12f1 (8afd630d1f5b)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 650 Ti BOOST (ID=0x11c2)
    Vendor:   
    VRAM:     1970 MB
    Driver:   24.21.13.9836
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.499349 ms
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 17 unused Assets to reduce memory usage. Loaded Objects now: 85551.
Total: 295.407132 ms (FindLiveObjects: 8.535963 ms CreateObjectMapping: 7.680820 ms MarkObjects: 278.972541 ms  DeleteObjects: 0.217808 ms)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 1 unused Assets to reduce memory usage. Loaded Objects now: 85553.
Total: 209.976960 ms (FindLiveObjects: 4.834777 ms CreateObjectMapping: 6.299720 ms MarkObjects: 198.565253 ms  DeleteObjects: 0.276591 ms)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

WARNING: Shader Unsupported: 'Curved/Triplanar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Mobile/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Standard (Specular setup)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard (Specular setup)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert' - Pass 'Meta' has no vertex shader
Dimensions of color surface does not match dimensions of depth surface
 
(Filename:  Line: 2511)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 17135 unused Assets to reduce memory usage. Loaded Objects now: 143257.
Total: 374.408260 ms (FindLiveObjects: 11.617140 ms CreateObjectMapping: 12.744233 ms MarkObjects: 322.839162 ms  DeleteObjects: 27.207416 ms)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 1 unused Assets to reduce memory usage. Loaded Objects now: 143402.
Total: 337.484883 ms (FindLiveObjects: 10.846459 ms CreateObjectMapping: 8.258444 ms MarkObjects: 318.056362 ms  DeleteObjects: 0.323309 ms)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 1 unused Assets to reduce memory usage. Loaded Objects now: 143403.
Total: 335.193878 ms (FindLiveObjects: 10.381761 ms CreateObjectMapping: 8.128192 ms MarkObjects: 316.396815 ms  DeleteObjects: 0.286492 ms)

**Comment by D3nnis3n** [comment] 2019-05-16 17:01
How big is your world?

**Comment by Ghostdk3** [comment] 2019-05-16 17:19
16km2

**Comment by D3nnis3n** [comment] 2019-05-16 18:14
The maximum recommended world size for Eco is 4km². The maximum size you can start via in-game is 1km². You can try to start the server directly via EcoServer.exe in your game folder (EcoServer32.exe won't work!) to play on it via "LAN-Servers". This is working as intended, therefore i close the issue.

**Closed by D3nnis3n** 2019-05-16 18:14 UTC
Labels: Investigate
