### ISSUE TITLE
USER ISSUE: Crafting yield of exactly 1000 units display truncated to 100

### ISSUE THREAD

**Issue by Mkorny** [StrangeLoopGames/EcoIssues#22800] opened 2021-11-24 00:06 UTC
\
**User Id: (slg183077)**
**Version:** 0.9.5.0 beta staging-2156

**Steps to Reproduce:**
1 - Go to ANY crafting table
2 - increase any item so that the resulting yield is exactly 1000
3 - confirm that the resulting icon shows "100" instead of 1000.	

**Expected behavior:**
It should show 1000.

**Actual behavior:**
The Icon reads "100" instead of 1000.
Note that you can clearly see it go from 999 > 100 > 1001 ...

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Logs attached on my previous bug:  (potentially related to same root cause) https://github.com/StrangeLoopGames/EcoIssues/issues/22799

Reported just 5 minutes ago.

This is just an example, I confirmed it happens with any other item, and on any crafting table
![image](https://user-images.githubusercontent.com/34373753/143147775-866f5725-3218-4075-9e13-b7c069242a25.png)
![image](https://user-images.githubusercontent.com/34373753/143147788-4ba4e70b-bbb7-4d18-8a82-98bd75ca55b1.png)
![image](https://user-images.githubusercontent.com/34373753/143147801-c3091b87-ad20-41c8-b05d-f3ee2f3133e1.png)

**Comment by TwixterZ** [comment] 2021-11-24 21:18
hi @Mkorny, thank you for raising this, glad to inform issue is known and developers is working on a fix for this.

will keep you updated.

**Comment by TwixterZ** [comment] 2021-12-27 03:52
@Mkorny such cases would be either using admin command or some kind of a mod, because vanilla is set as only 100 wheat (in this instance) per space in quick-bar, hence this is working as intended.

**Closed by TwixterZ** 2021-12-27 03:52 UTC
Labels: Type: Bug
