### ISSUE TITLE
USER ISSUE: Sell fertilizer in the store

### ISSUE THREAD

**Issue by colbacco** [StrangeLoopGames/EcoIssues#4612] opened 2018-02-16 00:23 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
I put 20 fertilizers in sale in my store	

**Expected behavior:**
20 fertiulizer in store

**Actual behavior:**
1 fertilizer with 0-100 status like items.

**Comment by MarjieAVolk** [comment] 2018-02-16 19:42
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3617

**Closed by MarjieAVolk** 2018-02-16 19:42 UTC
