### ISSUE TITLE
USER ISSUE: Contract Board Crash

### ISSUE THREAD

**Issue by TBlueF** [StrangeLoopGames/EcoIssues#5789] opened 2018-03-09 19:34 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
- Place a Contract Board
- Open "Create new Contract" window
- Close the Window without creating the contract
-> the contract board is  now broken
- try to break it
-> game crash

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Value cannot be null.
Parameter name: item


Stack:
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.GetBSON(Player player)
   at Eco.Gameplay.Objects.WorldObject.<Destroy>b__92_1(WeakReference r)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Destroy()
   at Eco.Gameplay.Objects.WorldObject.PickUp(Player player)
   at HammerItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

*PS.: Like the game, keep working! :)*

**Comment by MarjieAVolk** [comment] 2018-03-09 21:01
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Comment by MarjieAVolk** [comment] 2018-03-20 18:30
Gonna close as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5804

**Closed by MarjieAVolk** 2018-03-20 18:30 UTC
Labels: High Priority
