### ISSUE TITLE
USER ISSUE: Tool integrity not working on stores

### ISSUE THREAD

**Issue by mike1-2989** [StrangeLoopGames/EcoIssues#25335] opened 2024-12-24 00:03 UTC
\
**User Id: (1ae652cf-d39e-4b04-66ea-08dc8cbaa722)**
**Version:** 0.11.1.6 beta release-826

**Steps to Reproduce:**
1. Set up a tool store
2. Set several sell orders for different tool integrity.

**Expected behavior:**
Item availability should depend on the desired integrity.

**Actual behavior:**
Integrity has an unexpected behaviour, not showing correct available items for each sell order

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I'm on Giant Panda

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-12-24 13:21
Sounds like a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25300

**Closed by D3nnis3n** 2024-12-24 13:21 UTC
