### ISSUE TITLE
Legacy cart controls is a lie

### ISSUE THREAD

**Issue by Noneforu** [StrangeLoopGames/EcoIssues#22588] opened 2021-08-25 17:23 UTC
So the update claimed that it allowes to "old" cart contols but this is a blatent lie. The old controls was like a trailer following the character. Your looking direction had no influence on the carts steering as it simply followed you as tho it was hitched to you. This "legasy cart control" does NOT make it function like it used to. Its just more new crap controls. The carts are still ruined by the update and it is ruining my experience of the game.

**Comment by Daniel-Magulado** [comment] 2021-08-31 08:15
Hello @Noneforu 

Thank you for writing this report. I understand that the vehicle control for the cart is not the same as it used to be. We will continuously work on these controls to improve the cart experience overall. We apologize if the new controls implemented ruined your gaming experience. We value your feedback and we assure you that we will improve the controls over the coming game updates.

I've created a feedback report internally. I'll be closing this since this is not a bug report. Again, we apologize if this has ruined your gaming experience and I hope you can give Eco a chance as we try our best to improve the game overall.

Thank you.

**Closed by Daniel-Magulado** 2021-08-31 08:15 UTC
