### ISSUE TITLE
Water not seen through glass

### ISSUE THREAD

**Issue by egburr** [StrangeLoopGames/EcoIssues#4854] opened 2018-02-20 04:58 UTC
When placing windows or even just panes of plain glass, water is not seen through it. You just see the exposed riverbed as if the water is gone. See the attached picture for an example...

![image](https://user-images.githubusercontent.com/29808749/36407997-93f9cfd2-15d0-11e8-9fe4-a6470af8d060.png)

**Comment by MarjieAVolk** [comment] 2018-02-20 23:14
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3418

**Closed by MarjieAVolk** 2018-02-20 23:14 UTC
