### ISSUE TITLE
USER ISSUE: No Crimini Mushrooms

### ISSUE THREAD

**Issue by lubahebert** [StrangeLoopGames/EcoIssues#7103] opened 2018-04-10 04:23 UTC
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
1. Open the world map
2. Select CriminiMushroom in the dropdown menu
3. Look around the map - there are no highlighted sections
4. Explore around the game world - no mushrooms to be found

**Expected behavior:**
The world should have generated crimini mushrooms, as their spores are a key to farming

**Actual behavior:**
Does not generate any crimini mushrooms

**Comment by bingliCheng** [comment] 2018-04-10 06:37
You can use admin's permission to plants crimini mushrooms  on the wetlands.
This is about the WIKI of the server icommands https://eco.gamepedia.com/Chat_Commands

**Comment by lightdrawn** [comment] 2018-04-10 07:38
When you enter the world, there is a info mouse over link in general chat, that tells you if there is really no crimini. 
If there is none, a possible admin chat command to fix this is „/give criminimushroomspores,100“

**Comment by MarjieAVolk** [comment] 2018-04-10 18:36
Thanks guys for your advice :)  @lubahebert you can also see a list of chat commands you have access to just by typing /help in game.

In this case /regenlayer CriminiMushroom is probably what you want to try first.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Closed by MarjieAVolk** 2018-04-10 18:36 UTC
