### ISSUE TITLE
UI issue: Unable to scroll in the "Currency Report" window (KoS Server).

### ISSUE THREAD

**Issue by Melerion** [StrangeLoopGames/EcoIssues#7056] opened 2018-04-07 23:20 UTC
Hello,

I am an admin/moderator on the KoS (Katherine of Sky) community server. This latest world has been very popular with 100+ players connecting within the first 2 days of its existence.

Problem is that When I'd need to check the amount a currency a player has, who has a name that starts with a letter at the end of the alphabet I cannot get this information due to this list being truncated and not scrollable.

Fix: Please consider making it scrollable.

Thank you.

**Comment by MarjieAVolk** [comment] 2018-04-09 20:55
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6056

**Closed by MarjieAVolk** 2018-04-09 20:55 UTC
Labels: Medium Priority
