### ISSUE TITLE
USER ISSUE: Chests on wall say not on solid ground

### ISSUE THREAD

**Issue by AndyofBorg** [StrangeLoopGames/EcoIssues#6619] opened 2018-03-29 02:30 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Place a chest on a wall.

**Expected behavior:**
The chest should work and store items appropriately.

**Actual behavior:**
Doesn't work. It says not on solid ground. Chests do not need to be placed on the ground. You can put storage containers on walls. It is onerous to have to put everything on the ground, it just makes a huge cluttered mess. This is a highly negative change and does not contribute to fun gameplay, it's just difficult for the sake of being difficult.

**Comment by MarjieAVolk** [comment] 2018-04-03 00:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6572

**Closed by MarjieAVolk** 2018-04-03 00:29 UTC
