### ISSUE TITLE
USER ISSUE: block placement

### ISSUE THREAD

**Issue by iREDRUIVItv** [StrangeLoopGames/EcoIssues#6237] opened 2018-03-18 13:14 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
No clue, but Im building a roof on a house and a block will not be placed in a spot. Removed all blocks from around it and nothing changed.

**Expected behavior:**
the block should have gone into the spot	

**Actual behavior:**
instead the block just doesnt get placed in the specific spot

**Comment by MarjieAVolk** [comment] 2018-03-21 18:55
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5900

**Closed by MarjieAVolk** 2018-03-21 18:55 UTC
