### ISSUE TITLE
USER ISSUE: Ignore Auth Doesn't work with Mine or Dig Action

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#25297] opened 2024-12-05 07:13 UTC
\
**User Id: (a5038cee-4d8a-4bbb-d631-08dcbd395caf)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
1. Make a Law for the Mine or Dig action where ignore auth is used.
2. Try to mine a block on a property which belongs to a citizen of the town within jurisdiction.

**Expected behavior:**
It should have allowed me to successfully mine blocks within property I'm not authorized on.

**Actual behavior:**
Instead the ignore auth does not work and I cannot mine blocks on property I'm not authorized to.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2024-12-06 23:52
Hi @Blanclour 

Thank you for submitting this bug report. However, we are unable to reproduce this issue.
Mind uploading a screenshot of the law here? or a copy of the world save file would also be great.
Additional information would also be great too.

**Comment by D3nnis3n** [comment] 2024-12-13 12:17
Closing due to not reproducible and no further information provided. Please feel free to open a new issue when you can provide the necessary information.

**Closed by D3nnis3n** 2024-12-13 12:17 UTC
Labels: Status: Needs Information, Status: Not reproduced
