### ISSUE TITLE
USER ISSUE: Bookshelf / Scroll

### ISSUE THREAD

**Issue by wolfie359** [StrangeLoopGames/EcoIssues#4456] opened 2018-02-13 18:21 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1) Open a Bookshelf
2) Drag a research scroll to window

**Expected behavior:**
- None

**Actual behavior:**
- Image stays where dropped, scroll disapears.
- Reconnect to server image stays, have not tried restarting client

**Comment by MarjieAVolk** [comment] 2018-02-13 19:58
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

I have been trying to fix this for a while, but still no dice.  Thanks for the additional example.  Restarting client should fix it.  Some have also said that minimizing the game and then going back to it will fix it.

**Closed by MarjieAVolk** 2018-02-13 19:58 UTC
