### ISSUE TITLE
USER ISSUE: Omnipresent Overcrowding

### ISSUE THREAD

**Issue by MortisLegati** [StrangeLoopGames/EcoIssues#4608] opened 2018-02-15 23:51 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Till a 25x25 centered on an environment 100% hospitable to a tomato plant.
2. Plant a single Tomato	
3. Use a Soil Sampler to check the Tomato

**Expected behavior:**
It should reasonably have enough room to grow.	

**Actual behavior:**
It reads out Overcrowded.

**Comment by midn8t** [comment] 2018-02-16 05:41
https://github.com/StrangeLoopGames/EcoIssues/issues/4579

**Comment by midn8t** [comment] 2018-02-16 05:42
https://github.com/StrangeLoopGames/EcoIssues/issues/4577

**Comment by MarjieAVolk** [comment] 2018-02-16 19:51
Thanks, closing as duplicate of #4577 

This is a new concept, and we are still adjusting it; but FYI plants require more space if they are in a subpar environment.  If you adjust water levels to match what the plant likes, or find a space that is a closer temperature, then the plant will require less space.

**Closed by MarjieAVolk** 2018-02-16 19:51 UTC
