### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by xarnarany** [StrangeLoopGames/EcoIssues#6309] opened 2018-03-20 15:13 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei Eco.Gameplay.Items.EnumerableItemExtensions.<>c.<Describe>b__5_2(IGrouping`2 group)
   bei System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   bei System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   bei System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   bei Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
   bei Eco.Gameplay.Utils.PickerObject.get_Contents()
   bei Eco.Gameplay.Utils.PickerTracker.get_Contents()
   bei Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   bei Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, String memberName)
   bei Eco.Core.Controller.ControllerManager.GetChanges(INetClient client)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-20 22:27
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6064

**Closed by MarjieAVolk** 2018-03-20 22:27 UTC
Labels: Medium Priority
