### ISSUE TITLE
Skill (Carpentry) is undiscovered even after creating the Skill (Carpentry) Book

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19196] opened 2020-11-07 23:56 UTC
Skill (Carpentry) is undiscovered even after creating the Skill (Carpentry) Book

![Untitled](https://user-images.githubusercontent.com/32143431/98453781-f3597000-212a-11eb-9a70-52682e4bdfe2.jpg)
0.9.1.2 beta release-111

**Comment by SlayksWood** [comment] 2020-11-09 08:31
We lost possibility to view research progress:
![image](https://user-images.githubusercontent.com/45708377/98517394-e8afef80-227e-11eb-9d2f-26b3ab276b32.png)
- I start Carpentry researching:
![image](https://user-images.githubusercontent.com/45708377/98517475-067d5480-227f-11eb-9e13-7f3caa81dd7e.png)
- but don;t have any information about it:
![image](https://user-images.githubusercontent.com/45708377/98517512-14cb7080-227f-11eb-8d8f-773f8226e785.png)
- I guess discover means now - someone learn skill.

**Comment by minhnh-10** [comment] 2021-04-04 18:52
I checked around and look like the issue is no longer happen
![image](https://user-images.githubusercontent.com/3883524/113518600-864ee700-95b1-11eb-98f1-1cdd4700ada1.png)

**Comment by IcedForge** [comment] 2021-05-10 10:14
Works as intended on crafted the book
![Screenshot_84](https://user-images.githubusercontent.com/24981362/117642070-343c4b00-b187-11eb-92df-66e7d1b90894.jpg)

![Screenshot_86](https://user-images.githubusercontent.com/24981362/117642050-2dadd380-b187-11eb-90f3-41dc320fbaf4.jpg)

But if i connect with a different user 

![Screenshot_87](https://user-images.githubusercontent.com/24981362/117643786-1243c800-b189-11eb-873f-ad70bff3f04c.jpg)

So even if i craft the book, it still does not count towards global unlock. It is only on right clicking and making an actual scroll (not activating the scroll, just crafting it ) it globally sets discovery.

**Comment by IcedForge** [comment] 2021-05-10 10:15
Will close this as resolved as the initial issue was that it didnt flag discovery at all which it does now once someone crafts the book and uses it.

**Closed by IcedForge** 2021-05-10 10:15 UTC
Labels: Category: UI, Priority: Medium, Regression, Squad: Mountain Goat, Status: Not reproduced
