### ISSUE TITLE
Query Action shouldnt appear in list

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18082] opened 2020-09-08 05:27 UTC
![image](https://user-images.githubusercontent.com/3536496/92436322-3f9f2880-f159-11ea-986e-101726f239ea.png)

**Comment by WeaselDog** [comment] 2020-09-08 07:27
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/17456

**Closed by WeaselDog** 2020-09-08 07:27 UTC
Labels: Category: Laws, Priority: High
