### ISSUE TITLE
No more tools in skills (quality of life change)

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3536] opened 2018-01-19 23:58 UTC
Not being able to unlearn skills is a real pain and very unforgiving to new folks who make mistakes. All tools and items should be removed from the skill tree now that folks start with basic tools and everything can be crafted.

**Comment by MarjieAVolk** [comment] 2018-01-20 00:15
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3517

**Closed by MarjieAVolk** 2018-01-20 00:15 UTC
