### ISSUE TITLE
0.9 - 1464: Stuck on Steam Tractor after seeding

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#15216] opened 2020-03-19 11:09 UTC
When seeding a larger field in 3rd person i can not exit the tractor unless I reconnect.
I always seed in 3rd person so I don't know if it only occurs that way, changing perspective didn't help anyway.

**Comment by SlayksWood** [comment] 2020-03-19 11:33
Can't reproduce in staging-1472. Maybe was fixed with https://github.com/StrangeLoopGames/Eco/pull/5773
Please add  information after updating playtest to new staging. If you will still have this problem please provide log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by BennoHase** [comment] 2020-04-11 08:10
unfortunately not fixed. I have the same in staging-1506

**Comment by BarikSHL** [comment] 2020-05-11 05:01
Same trouble here at 1542. And it's can happen even without seeding (enough to put sower). I can exit with /unstuck, but i have tractor panel instead of player's item menu. 
https://drive.google.com/open?id=1oOOqJOKcHq9RenyUUdI3WsfofCd15ZIe

**Comment by SlayksWood** [comment] 2020-05-14 13:45
merged to #16306

**Closed by SlayksWood** 2020-05-14 13:45 UTC
Labels: Status: Investigate
