### ISSUE TITLE
SERVER DUMP: Version 7.3.0 - staging version

### ISSUE THREAD

**Issue by ZeskaN** [StrangeLoopGames/EcoIssues#6412] opened 2018-03-23 19:11 UTC
--BEGIN DUMP--
Dump Time
03/23/2018 19:52:19

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Property.PropertyManager.IsAuthorized(User user, Vector3i pos, IInteractable target, String action)
   at Eco.Gameplay.Items.AuthorizationInventory.CanMoveItems(Type itemType, Int32 delta, User user)
   at Eco.Gameplay.Items.InventoryChangeSet.ModifyStack(ItemStack stack, Int32 delta, Item newItem, Boolean updateComponents)
   at Eco.Gameplay.Items.InventoryChangeSet.MoveItemsInternal[TKey](Type itemType, Int32 quantity, Inventory source, Inventory destination, Func`2 sourceStackPredicate, Func`2 sourceStackOrder)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-23 20:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6044

**Closed by MarjieAVolk** 2018-03-23 20:13 UTC
