### ISSUE TITLE
reconnect requires hitting continue 3x

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#11163] opened 2019-02-08 01:17 UTC

**Comment by D3nnis3n** [comment] 2019-03-03 21:41
Cannot reproduce, any more information?

**Comment by D3nnis3n** [comment] 2019-03-21 13:59
Closing this, as i cannot reproduce.

**Comment by SeanAtr0n** [comment] 2019-03-21 19:58
Connect to a server on the same LAN as you
hit disconnect 
then hit continue and you get an error msg
hit continue 2 more times and you reconnect

**Comment by D3nnis3n** [comment] 2019-03-21 19:59
Not happening for me. I'm unassigning me therefore and assigning you.

**Comment by SeanAtr0n** [comment] 2019-03-21 20:01
started happening after OpenNAT changes iirc

**Comment by D3nnis3n** [comment] 2019-03-21 20:02
When i disconnect and reconnect i'm back on the server, so can't help with this.

**Comment by mirasrael** [comment] 2019-03-22 11:21
@SeanAtr0n does anything change if you disable UPnP on the server?

**Comment by SeanAtr0n** [comment] 2019-03-25 18:18
![image](https://user-images.githubusercontent.com/774628/54943892-8494b800-4eef-11e9-88cf-99033e84636d.png)

**Comment by mirasrael** [comment] 2019-03-26 07:30
@SeanAtr0n do you have this issue with regular client or only within Unity editor?

**Closed** 2019-03-27 22:08 UTC
Labels: Fixed, Medium Priority
