### ISSUE TITLE
USER ISSUE: Caught exception invoking RPC SendChat on ChatManager

### ISSUE THREAD

**Issue by SanSource** [StrangeLoopGames/EcoIssues#5289] opened 2018-03-02 05:45 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

```

**Comment by Nanders** [comment] 2018-03-02 18:27
What chat command were you trying to invoke?

**Comment by MarjieAVolk** [comment] 2018-03-05 20:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4391

This seems to happen when you pass no arguments in to a command that requires arguments.  Try using /help for the command to see what arguments it requires.

**Closed by MarjieAVolk** 2018-03-05 20:29 UTC
Labels: Medium Priority
