### ISSUE TITLE
USER ISSUE: Backpack won't close with ESC.

### ISSUE THREAD

**Issue by EnderdavidHD** [StrangeLoopGames/EcoIssues#22954] opened 2022-01-29 23:43 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.5 beta release-278

**Steps to Reproduce:**
1: Open the backpack with B 
2: Press ESC

**Expected behavior:**
The Backpack should close.

**Actual behavior:**
Instead the pause menu opens and the backpack interface stays open. also the mouse is locked to the player and disappears in the interface.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No I don't have any mods installed. I only installed the game today.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-01-31 12:21
This works as intended. We have a split in the community between people that wish to keep the backpack open at all times and those that wish the behaviour you suggest. We decided to keep the behaviour we already had, to not close it. Future versions of Eco will allow you to pin and unpin windows at your own decision, so you can configure it for each window yourself.

**Closed by D3nnis3n** 2022-01-31 12:21 UTC
