### ISSUE TITLE
USER ISSUE: Was saving a district map

### ISSUE THREAD

**Issue by Poioioio** [StrangeLoopGames/EcoIssues#23295] opened 2022-07-19 19:10 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
save a wide road system draft

**Expected behavior:**
It should have not crashed.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Invalid Query - Query never existed or was already processed
Source:Eco.Shared

System.InvalidOperationException: Invalid Query - Query never existed or was already processed
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__72_4()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-11-06 11:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23821

**Closed by D3nnis3n** 2023-11-06 11:22 UTC
