### ISSUE TITLE
[User issue] Crash without dump after attempting to load webserverplugin

### ISSUE THREAD

**Issue by Luicetarro** [StrangeLoopGames/EcoIssues#6000] opened 2018-03-13 18:16 UTC
We currently have issues with an windows 10 computer launching Eco.
Wether I'm using the Steam-Version, the direct exe from the developers website, Steam-EcoServer, or the devs Eco-server won't matter.

It will stop loading/creating a world after trying to start the webserverplugin, fonts vanish and the client will pop to the created worlds if pressing the Esc-key. Letting the client run without any fonts (while maybe running some things in the background) won't solve the issue. Copying another local world won't work as well. The world will appear in the list, load it's textures, but the client will freeze/crash once it does attempt webserverplugin.
Joining a premade server is working fine strangely enough.

.net 4 and 4.5 are up to date, drivers are checked and are working fine. Hardware is checked and working fine, requirements for the game are met (and since it's running on a premade server that's doublechecked as well).

The game is running just fine on a window 7.1 computer, had the doublecheck for that on my other computer.

Are any issues known like that, or are we the only ones with that kind of problem?
Seems like that issue appeared already [2 years](http://ecoforum.strangeloopgames.com:4567/topic/134/webserverplugin-program-stopped-working) ago. Maybe there is something now that could be done?

**Comment by MarjieAVolk** [comment] 2018-03-13 23:18
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/5192?  But they have a crash dump so idk.

**Comment by Luicetarro** [comment] 2018-03-14 15:39
I'll test some things noted in the linked topic.
So far I can verify it's not the game-data itself, since they are running fine on my second computer. So it is bound to be something on my side (on my Win 10-computer), just have to track down what does cause this issue exactly
Maybe something will work, maybe I'm able to debug it somehow and state what has fixed it for me (in case I am able to get it running myself) for others to use that.

**Comment by MarjieAVolk** [comment] 2018-03-16 01:32
Okay, closing as duplicate of #5192 in that case.  Thanks!

**Closed by MarjieAVolk** 2018-03-16 01:32 UTC
Labels: Medium Priority
