### ISSUE TITLE
USER ISSUE: Concurrent access to Inventory bug

### ISSUE THREAD

**Issue by Mat0Man** [StrangeLoopGames/EcoIssues#6383] opened 2018-03-22 22:51 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. opened chest
2. ate beet directly from chest
3. a friend of mine took some beet directly from the chest at the same time
4. back to menu

**Expected behavior:**
It should have let me eat the food

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC UseStack on AuthorizationInventory!

Changes could not be applied, the requested operation would result in an invalid inventory state.


Stack:
   bei Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   bei Eco.Gameplay.Items.Inventory.UseStack(ItemStack stack, Player player)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
Caught exception:

<size=60,00%>Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC UseStack on AuthorizationInventory!

Changes could not be applied, the requested operation would result in an invalid inventory state.


Stack:
   bei Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   bei Eco.Gameplay.Items.Inventory.UseStack(ItemStack stack, Player player)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-23 00:34
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6341

**Closed by MarjieAVolk** 2018-03-23 00:34 UTC
