### ISSUE TITLE
Really Nasty Worldgen Issues 

### ISSUE THREAD

**Issue by Bobondacob** [StrangeLoopGames/EcoIssues#5635] opened 2018-03-08 00:34 UTC
So far, I've not had a fresh world generate that includes every biome, plant and animal.

The "terracing" seems to make all of the rivers deep ravines, with near zero flat land, and there are ore veins 100-200 blocks large at the surface.

Most of the worlds I spawn are all ice or birch biome, and I had less than 10 tomatoes over three maps

Something is seriously wrong with worldgen here.
I'm not the only one, either. 

![](http://ecoforum.strangeloopgames.com/uploads/files/1520454229119-capture.png)

![](http://ecoforum.strangeloopgames.com/uploads/files/1520454467321-image.png)

![](http://ecoforum.strangeloopgames.com/uploads/files/1520454590331-capture3.png)

![](http://ecoforum.strangeloopgames.com/uploads/files/1520454511261-capture2.png)

I'm completely unable to make basic recipes and make basic progression in small to large collab, and I'm really getting frustrated.
I mean, I'm struggling to find a piece of ground that is big enough for a single building.

A reversion of the worldgen changes is probably a good plan until you figure out what's going on.

**Comment by Thyriel** [comment] 2018-03-08 00:59
I already reported it here: https://github.com/StrangeLoopGames/EcoIssues/issues/5568

As for the worldgen height problem: Change Config/WorldGenerator.eco
"Height": 100,
back to 80 (value from 7.1, although 70 i find more nice)

**Comment by MarjieAVolk** [comment] 2018-03-08 22:37
Closing as duplicate of #5568.  Improving world generation is a project we would like to work on in the near future.

**Closed by MarjieAVolk** 2018-03-08 22:37 UTC
