### ISSUE TITLE
Connection material issue - Version 0.7.7.0 

### ISSUE THREAD

**Issue by dwujcik** [StrangeLoopGames/EcoIssues#9187] opened 2018-09-05 18:06 UTC
Should be fill between connection of materials.
![20180905200141_1](https://user-images.githubusercontent.com/17785084/45112031-d558e500-b146-11e8-98ed-c32ef996e37f.jpg)

Game version 0.7.7.0 beta

**Comment by metachronism** [comment] 2018-09-06 18:06
dupe of #4286

**Closed by metachronism** 2018-09-06 18:06 UTC
Labels: Needs Triage
