### ISSUE TITLE
Missing Sawmill

### ISSUE THREAD

**Issue by houseofdoggus** [StrangeLoopGames/EcoIssues#23375] opened 2022-08-31 15:46 UTC
Updated to 9.6 from old version 9.5.4(?)

Sawmill is missing.

**Comment by D3nnis3n** [comment] 2022-09-06 10:38
Likely duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19797 then.

**Closed by D3nnis3n** 2022-09-06 10:38 UTC
