### ISSUE TITLE
Can not load a world

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#15305] opened 2020-03-24 22:47 UTC
**Version**: 0.9.0.0 beta staging-1480
**Steps to Reproduce**

1. Load a world either the playtest server or single player

**Expected Behavior**: Able to load a world and play the game
**Actual Behavior**: Not possible to load a world. Loading hangs on 78% which will go to 80% after 30 minutes and then crash. Reproduced 5 times. Tried reinstalling the game (and also deleting appdata/locallow/strangeloopgames folder) but that didn't help either.

[Crash_2020-03-24_202346679.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4377967/Crash_2020-03-24_202346679.zip)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377968/Player.log)

**Comment by revtje** [comment] 2020-03-24 22:48
Tried loading a single player world but that hangs on 92%. Didn't have time to check if it crashes after a while there aswell yet. Can check that tomorrow.

**Comment by SlayksWood** [comment] 2020-03-25 07:04
@revtje 
Thank you for your report. Please, answer some questions
1. Can you see servers in list normally? With ping and server info?
2. Do you have Firewall or Antivirus enabled?
3. Which kind of internet connection are you using?
4. Please provide your PC specification (include Operating System).

**Comment by revtje** [comment] 2020-03-25 07:21
1. Yes I can see Royal Otter, Giant Panda and White Tiger. They show up as normal.
2. I have Windows 10 built in firewall and whatever built in antivirus it has by default
3. I have a 250/250 Mbit Telia connection from Sweden with ~20 ping to the eco official servers
4. Intel I5-9600, 16GB RAM, SSD, Geforce GTX1060Ti, Windows 10

Just tested and I was atleast able to load a single player world after 15-20 minutes stuck at 92% loading. No crash.


[PlayerLogs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4379536/PlayerLogs.zip)

**Comment by revtje** [comment] 2020-03-25 07:25
Tested to change version in steam to 8.3.3 and join white tiger. The world loads fast with no problems

**Comment by revtje** [comment] 2020-03-25 13:04
Today I was able to log on. It took 1,5 hours of loading world but atleast it did not crash. I haven't done anything other than change from 8.3.3 to 0.9.0.0 beta staging-1480. The server has been restarted though

**Comment by revtje** [comment] 2020-03-25 16:36
Just logged on now without any issue. Very strange. I have not done anything on my side. The computer has been left on and not rebooted or anything like that.

**Comment by revtje** [comment] 2020-03-25 19:24
Game crashed while using a stone road tool on grassland. When I started it again the loading was slow. Stuck at 80%. After 1 hour I was at 97% then the game crashed.

[Crash_2020-03-25_191839899.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4383060/Crash_2020-03-25_191839899.zip)
[Player.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4383061/Player.zip)

**Comment by revtje** [comment] 2020-03-25 21:54
I have found the problem. Set view distance to lowest and the loading will be slow. Reset defaults and it will load fast again. Reproduced it 3 times and have had other users confirm it too.

**Comment by revtje** [comment] 2020-03-25 22:08
This ticket can probably be closed since it's probably the same as https://github.com/StrangeLoopGames/EcoIssues/issues/14910

**Comment by D3nnis3n** [comment] 2020-03-25 22:10
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14910

**Closed by D3nnis3n** 2020-03-25 22:10 UTC
Labels: Status: Investigate
