### ISSUE TITLE
Can't skip tutorials

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11705] opened 2019-03-18 11:37 UTC
See this video: https://drive.google.com/open?id=1HkCXxSJqbIo0PiAOPbA6Fiw-qLpLU1uA

Either that is caused by the massive lag on the official servers, or there is some kind of bug.

After i did the controls tutorial, all other tutorials vanished, e.g. i did not need to skip again, but it skipped them afterwards i did that.

**Comment by Quadbro** [comment] 2019-03-19 04:32
@D3nnis3n  Worldsave?)

**Comment by Quadbro** [comment] 2019-04-02 05:20
Probably can be fixed with latest mirasrael changes, can't reproduce it either...

**Closed by Quadbro** 2019-04-02 05:20 UTC
Labels: Investigate
