### ISSUE TITLE
USER ISSUE: Friend keeps losing connection

### ISSUE THREAD

**Issue by inorigj** [StrangeLoopGames/EcoIssues#21753] opened 2021-05-03 16:55 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**
I'm hosting the server.
My friend joins my server over steam.
after exactly 10min they are unable to do anything in-game

**Expected behavior:**
to be able to play without losing connection

**Actual behavior:**
they only get to play for 10 min (EXACTLY 10 MIN) before their they get connection issues and get kicked to the main menu

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here**

**Log files from friends computer_**
[Player_Friendfile.log](https://github.com/StrangeLoopGames/EcoIssues/files/6416342/Player_Friendfile.log)
[Player-prev_Friendfile.log](https://github.com/StrangeLoopGames/EcoIssues/files/6416348/Player-prev_Friendfile.log)
**Log files from my computer_**
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6416350/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6416351/Player-prev.log)

**Comment by Daniel-Magulado** [comment] 2021-05-03 19:56
Hi, thank you for making a report about this.
According to the game log you've provided, there seems to be some bandwidth issue going on.
If you're hosting the server, it could be that your friend is suffering from an unstable connection.
If you and your friend are playing in the same local area network, your router could be suffering from saturated bandwidth.
On the game log, it states "Can't reach news service HTTP/1.1 429 Too Many Requests" before your friend gets disconnected.

Is this the first time you're playing Eco?
If no, we're you able to play with your friends while hosting a server before the 0.9.3.3 update?
If yes, could you tell us what version of the game was it?
Please run an internet speed test. This is to simply narrow down what's causing this issue.
Please provide your PC specification (include Operating System).
Do you have Firewall or Antivirus enabled?
Can you and your friend try to connect to our official servers (Such as White Tiger or Sea Otter) and see if either of you will get disconnected after playing for 10 minutes.

**Comment by inorigj** [comment] 2021-05-03 20:29
**Is this the first time you're playing Eco?**
Yes

**could you tell us what version of the game was it?**
We started playing and still playing on
_0,9,3,3 beta release-219_

**Do you have Firewall or Antivirus enabled?**
Yes, Windows Defender

**Internet speed at the time of the issue**
44.4 mbps DOWN | 18.1 mbps UP

We are going to test if we lose connection to the public servers now. will send the answer here in about 15-20 min

### Specs

**OS:** _Windows 10 home 64-bit_
**RAM:** _32GB_
**CPU:** I_ntel(R) Core(TM) i7-9700K CPU @ 3.60GHz_
**GPU:** _2047MB NVIDIA GeForce RTX 2060_
**Storage type:** _931GB Samsung SSD 970 EVO Plus 1TB_
**Motherboard:** _Micro-Star International Co. Ltd. MPG Z390 GAMING PLUS_

**Comment by inorigj** [comment] 2021-05-03 20:50
Testing on **White Tiger**
There was no connection issues on this server.

**Comment by IcedForge** [comment] 2021-05-05 06:23
Are you connecting over steam friends network?
If this is the case, please try to connect via using the server ID instead.

This can be located in the network.eco file ( inside eco/eco_data/server/config )
and input this using the + button under "Your Worlds" instead of an IP.

**Comment by Daniel-Magulado** [comment] 2021-05-08 07:38
Hi @inorigj,

If you did not encounter any issues connecting to our official servers and using the Server ID did not help, then the most probable cause is the connection between your server and your friend's PC. We recommend having your friend restart his/her network at home.
Restart the modem router, wireless router, and the PC your friend is using.
We also recommend having your friend turn off his/her anti-virus if he/she has one, and other tasks that are running in the background when playing Eco.

**Comment by inorigj** [comment] 2021-05-08 08:02
Could our distance have anything to do with it? 
I'm playing from **Norway**. and They're playing from the **U.S, Florida**

**Comment by Daniel-Magulado** [comment] 2021-05-10 07:56
Hi @inorigj,

Yes, it's possible but highly unlikely. As per the game log, there's something on your friend's PC that's causing it and it's quite impossible for us to determine what's causing the "Can't reach news service HTTP/1.1 429 Too Many Requests" error. In most cases, errors like this are caused by 3rd party software. Since you're hosting the server, it's your PC's way of telling that your friend's PC is requesting too many requests from your server. It can also be caused by a lingering virus or malware on your friend's PC.

We do, however, apologize for any inconvenience that you and your friend have experienced playing Eco. Please, do not hesitate to let us know if there's anything else we can do for you.

**Comment by Daniel-Magulado** [comment] 2021-05-26 13:52
Hi @inorigj,


We'll be closing this ticket now.
Feel free to reopen or write a new ticket again if you ever encounter any bug or issues.

**Closed by Daniel-Magulado** 2021-05-26 13:52 UTC
Labels: Status: Needs Information
