### ISSUE TITLE
Candle stand not placeble on table & if on it candle is not on solid groud

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#7114] opened 2018-04-10 17:29 UTC

**Comment by Arend90** [comment] 2018-04-10 17:32
![image](https://user-images.githubusercontent.com/31536813/38573269-cf622e10-3cf5-11e8-9aa2-2b55398997dd.png)
![image](https://user-images.githubusercontent.com/31536813/38573285-dc37953a-3cf5-11e8-8773-770ca1466188.png)

**Comment by elfl0rd** [comment] 2018-04-10 17:33
Duplicate, https://github.com/StrangeLoopGames/EcoIssues/issues/7065

**Comment by MarjieAVolk** [comment] 2018-04-10 18:01
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7065

**Closed by MarjieAVolk** 2018-04-10 18:01 UTC
