### ISSUE TITLE
Server Crash - 7.1.2 Beta - Crash Dump

### ISSUE THREAD

**Issue by Geuthur** [StrangeLoopGames/EcoIssues#4548] opened 2018-02-15 00:06 UTC
![screenshot_17](https://user-images.githubusercontent.com/761682/36234639-60537224-11ec-11e8-95c9-40b4873beced.png)
New Error 
Version 7.1.2

**Comment by MarjieAVolk** [comment] 2018-02-15 00:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368

**Closed by MarjieAVolk** 2018-02-15 00:11 UTC
