### ISSUE TITLE
USER ISSUE: Trees disappear

### ISSUE THREAD

**Issue by LemonMoo** [StrangeLoopGames/EcoIssues#5003] opened 2018-02-23 19:34 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Cut down tree
2. Go to chop tree up
3. the rest of the tree disappears

**Expected behavior:**
not disappeared	

**Actual behavior:**
it disappeared

**Comment by MarjieAVolk** [comment] 2018-02-23 23:42
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5006

**Closed by MarjieAVolk** 2018-02-23 23:42 UTC
