### ISSUE TITLE
USER ISSUE: Fishing not working

### ISSUE THREAD

**Issue by bejanbogdan93** [StrangeLoopGames/EcoIssues#11401] opened 2019-02-18 21:22 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. I looked for the richest waters in Tuna, on map
2. I used The Fishing Pole and caster about 6 sec.
3. waited for around 5 min...

**Expected behavior:**
A fish should've been caught

**Actual behavior:**
No fish caught

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods

**Comment by D3nnis3n** [comment] 2019-02-18 22:36
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11176

**Closed by D3nnis3n** 2019-02-18 22:36 UTC
