### ISSUE TITLE
USER ISSUE: Rocket Man

### ISSUE THREAD

**Issue by Kofu12** [StrangeLoopGames/EcoIssues#4626] opened 2018-02-16 07:07 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Stand in the doorway with a friend, and spam close/open the door.

**Expected behavior:**
Nothing. 

**Actual behavior:**
We clipped into eachother and the game is bouncing us off of 
![screenshot 9](https://user-images.githubusercontent.com/36530063/36296969-b4f0858c-12b5-11e8-9ae7-4d4dd1e9d3e8.png)
eachother repeatedly for infinity.

**Comment by ecoemmeck** [comment] 2018-02-16 07:26
Doors knock you to space. #4553

**Comment by MarjieAVolk** [comment] 2018-02-16 23:29
Lol okay closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4553

**Closed by MarjieAVolk** 2018-02-16 23:29 UTC
