### ISSUE TITLE
[0.9.3.0 beta release-194] Cannot bulk-move (shift-drag) coal / gold between storages

### ISSUE THREAD

**Issue by bloodymx** [StrangeLoopGames/EcoIssues#21383] opened 2021-04-15 11:26 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
1. Place 2 storages next to each other
2. Place stacks of gold / coal in one storage
3. Try to shift-drag gold / coal to the other storages		

**Expected behavior:**
Should have moved all stacks to the other inventory

**Actual behavior:**
Pops up an empty, stacking error notification.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment] 2021-04-15 11:34
Thank you for reporting this.
We are working on resolving this and will close as duplicate of #21370

**Closed by IcedForge** 2021-04-15 11:34 UTC
