### ISSUE TITLE
USER ISSUE: Day 31 ?? The world have only like 12hours

### ISSUE THREAD

**Issue by OniKirby** [StrangeLoopGames/EcoIssues#25151] opened 2024-09-09 10:37 UTC
\
**User Id: (dcc48a57-20bb-447d-31cf-08dcce89dbe7)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
Day 31 ?? The world have only like 12hours

**Expected behavior:**
no meteor crash

**Actual behavior:**
meteor crash

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-09-09 15:34
Sorry, could you explain in more detail what the issue is?

**Comment by D3nnis3n** [comment] 2024-09-15 15:57
Closing due to no further information provided, feel free to open a new issue if you can provide more information.

**Closed by D3nnis3n** 2024-09-15 15:57 UTC
Labels: Status: Needs Information
