### ISSUE TITLE
Iron tools repair costs vs. crafting costs

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5199] opened 2018-02-27 22:02 UTC
I find it rather strange that iron tools cost 4 iron to be crafted (with max efficiency) but 10 to be repaired.

Either repair costs should be lowered to be equal to crafting costs, metalworking efficiency should affect repair costs too (probably not the best solution as it would punish players with no metalworking) or a generic skill in survival tree should be added for repair efficiency (imho best solution) or crafting costs for the tools should be increased (fine too)

**Comment by ecoemmeck** [comment] 2018-02-28 05:47
duplicate 
Suggestion: Repair needs to be decreased for iron and steel #4247

**Comment by MarjieAVolk** [comment] 2018-02-28 20:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4247

**Closed by MarjieAVolk** 2018-02-28 20:05 UTC
