### ISSUE TITLE
[0.9.0 staging-1542] - Law set to claim all property does not claim vehicles

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16384] opened 2020-05-19 04:20 UTC
Law set to transfer ownership of all property upon meeting certain criteria:
![image](https://user-images.githubusercontent.com/48172405/82284061-fd768f00-998f-11ea-9eda-f05847732f52.png)

Result - When criteria are met, land is transferred, but not wood cart:
![image](https://user-images.githubusercontent.com/48172405/82284134-34e53b80-9990-11ea-9cc1-9a935c3c05dc.png)

Expected behaviour: All property would be transferred.

**Comment by trickenso** [comment] 2020-05-19 16:21
Confirmed for Steam Truck as well:
![image](https://user-images.githubusercontent.com/48172405/82351791-f6359c80-99f4-11ea-8604-dd85a3e452cb.png)

**Comment by SlayksWood** [comment] 2020-06-19 07:23
> "Change property" law only applies to claims not vehicles/carts, it should also apply to them.
> 
> ![image](https://user-images.githubusercontent.com/61889138/85079330-7b5fcd00-b1be-11ea-987e-2a02c30f4606.png)
> 
> When trying to interact with a wood cart
> ![image](https://user-images.githubusercontent.com/61889138/85079446-c8dc3a00-b1be-11ea-9d01-b62cc5409f0d.png)
> 
> Land and all its contents transferred as expected
> ![image](https://user-images.githubusercontent.com/61889138/85079502-e6110880-b1be-11ea-8440-39ff23c05e35.png)

**Comment by Daniel-Magulado** [comment] 2021-05-31 17:46
Tested on 0.9.4 Staging-1997

Tested with transfer to a single account, titles, and demographics. All work as intended. Closing.

**Closed by Daniel-Magulado** 2021-05-31 17:46 UTC
Labels: Category: Laws, Priority: Medium, Squad: Mountain Goat, Status: Fixed, Type: Bug
