### ISSUE TITLE
USER ISSUE: Stove does not output smog

### ISSUE THREAD

**Issue by BoxOfHats** [StrangeLoopGames/EcoIssues#6115] opened 2018-03-15 22:53 UTC
Version: 0.7.2.4 beta

Steps to Reproduce:
Build a stove, with or without pipe connections.
![Stove in room](https://user-images.githubusercontent.com/37423199/37495067-95d14eb2-28a3-11e8-90cf-db61016e464a.PNG)
![Pipe interface in stove](https://user-images.githubusercontent.com/37423199/37495082-a5edcb54-28a3-11e8-8ea0-0064c0437f19.PNG)
![Pipe output](https://user-images.githubusercontent.com/37423199/37495096-b2a4a160-28a3-11e8-8653-d4c862a0aa18.PNG)

Expected behavior:
Smog flows out of the machine, or out of the end of the pipe.

Actual behavior:
Smog builds up inside stove until the machine stops working.

**Comment by MarjieAVolk** [comment] 2018-03-15 23:09
Oh wait, I misunderstood.

Okay, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5805.  This will be fixed in the next hotfix.

**Closed by MarjieAVolk** 2018-03-15 23:09 UTC
Labels: Suggestion

**Comment by Rambo99** [comment] 2018-03-18 19:57
Version game - 0.7.2.5 . Bug not fixing !

**Comment by MarjieAVolk** [comment] 2018-03-20 22:14
Okay, checking up on it.  It might be that it's actually in 7.3

**Comment by MarjieAVolk** [comment] 2018-03-20 22:17
Yeah, team says it will be fixed in 7.3.  Sorry about the mixup!
