### ISSUE TITLE
Duplicate carried items using Stock Pile.

### ISSUE THREAD

**Issue by Ruined1** [StrangeLoopGames/EcoIssues#10925] opened 2019-01-28 06:10 UTC
If you carry items in your hand, and then right-click to place a stockpile, you will place those items in the freshly created stockpile as part of the right click to place it, but there will also be the items still in your hand, thus duplicating the items.

Wasn't able to re-create this, not sure what the conditions of it were.

0.7.8.9 beta

**Comment by johnkslg** [comment] 2019-01-29 16:46
Fixed in master?

**Comment by Spydarlee** [comment] 2019-02-01 16:40
Seems to work fine in master - tried a few permutations but couldn't reproduce this. Assuming I understood the bug correctly and the scenario in this gif is what was causing the issue?

![ecohelditemsplacewithstockpile](https://user-images.githubusercontent.com/553695/52136465-0975fa80-2640-11e9-81bb-551e39cef311.gif)

**Closed** 2019-02-01 20:11 UTC
Labels: Investigate, Not reproduced
