### ISSUE TITLE
[QoL] allow use new district\demographics in same law.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10112] opened 2018-11-22 19:20 UTC
At present, you need pass redefine disctrict law, and ONLY then you can use added district in law.
It make creation law like "add new district "tailings" + prevent place tailings outside" is really, really long (double time) and terribe (you need create 2 law, instead of one).

Please, allow using new proposed districts in same law!

**Comment by D3nnis3n** [comment] 2018-11-22 20:50
And you need to wait double the time.

**Comment by Deantwo** [comment] 2018-11-23 08:44
Same with demographics.

**Comment by johnkslg** [comment] 2019-02-11 21:09
Will be in 9.0 update

**Comment by Deantwo** [comment] 2019-04-10 14:48
Also not fixed/implemented yet. It is mentioned as planned for v0.9.0.0 though.

**Comment by WeaselDog** [comment] 2019-11-27 19:53
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11966. Has been fixed.

**Closed** 2019-11-27 20:55 UTC
Labels: Laws, Usability
