### ISSUE TITLE
USER ISSUE: Composite Filler does not show/stack correctly

### ISSUE THREAD

**Issue by MC2424** [StrangeLoopGames/EcoIssues#4449] opened 2018-02-13 14:23 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
I put 50 composite fillers in storage, I later spilt the stack into 2	

**Expected behavior:**
The store should show 50, when I have 50 fillers in the storage linked to the store (store status is green). 

**Actual behavior:**
The store only shows the no. of stack instead of no. of item. So 1 stack of 50 fillers is only 1 item in my store, and when I split it into 2 stacks of 25 fillers the store shows 2 items on sale. I also cannot re-stack them into a 50 fillers stack.

**Comment by MarjieAVolk** [comment] 2018-02-13 20:56
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4429

**Closed by MarjieAVolk** 2018-02-13 20:56 UTC
