### ISSUE TITLE
USER ISSUE: Aqueduct not working correctly

### ISSUE THREAD

**Issue by 42656e** [StrangeLoopGames/EcoIssues#6846] opened 2018-04-01 16:15 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Let water fall from a higher point straight on a aqueduct block
For example when you want to descend to a lower level

**Expected behavior:**
The aqueduct block "redirects" the water for it's complete line

**Actual behavior:**
The water just falls down and stops there
Look here:
[https://steamuserimages-a.akamaihd.net/ugc/913543086398180384/4BAD77D51121043DF7EB5DE1A5A7FC0A9270307D/](url)

**Comment by craig-jong** [comment] 2018-04-04 20:49
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6851

**Closed by craig-jong** 2018-04-04 20:49 UTC
Labels: High Priority
