### ISSUE TITLE
USER ISSUE: Connection Failed Invalid Login Info No Response from auth server

### ISSUE THREAD

**Issue by xSnowyOwl** [StrangeLoopGames/EcoIssues#24072] opened 2023-10-20 21:46 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Either to join a friend's world or attempt to host your own

**Expected behavior:**
It should load up a new world for me when hosting or load me into my friend's world.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-10-22 04:44
This is not a bug but caused by Eco being unable to reach our authentication servers.

Typically this happens when security software or firewalls block the access and can be resolved by exempting Eco in any antivirus software. You can also test by using a VPN (or turning an existing one off that may not be able to reach).

In Eco authentication is done by the server, hence when you play on a online server you're likely not seeing the problem, as those servers have no issues connecting to our authetnication server, while when you play a local game, a local server is run that has the issue.

Further information can be received at [support@strangeloopgames.com](mailto:support@strangeloopgames.com).

**Closed by D3nnis3n** 2023-10-22 04:44 UTC

**Comment by xSnowyOwl** [comment] 2023-10-26 00:32
What if it is neither? I'm starting to get the same issue more frequently
and I don't have security software nor firewalls running on my computer.

**Comment by regctx** [comment] 2023-12-14 15:27
Is there a port that needs to be opened on the server to allow the connection to the Auth Server?
