### ISSUE TITLE
Soil sampler shows wrong temperature

### ISSUE THREAD

**Issue by GuyMonkey** [StrangeLoopGames/EcoIssues#11290] opened 2019-02-13 04:59 UTC
I'm playing on a server (140x140) and the soil sampler only shows temperature values between 0,2° (snow mountains) and 0,9° (desert).

**Comment by GuyMonkey** [comment] 2019-02-13 05:23
Playing on 0.8.0.1 beta

**Comment by elfl0rd** [comment] 2019-02-13 06:06
Duplicate of #11063

**Closed by elfl0rd** 2019-02-13 06:06 UTC
