### ISSUE TITLE
USER ISSUE: wheelbarrow stuck under land

### ISSUE THREAD

**Issue by hafizalias4484** [StrangeLoopGames/EcoIssues#22775] opened 2021-11-05 21:54 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
use unstuck, but vanishes underwater

**Expected behavior:**
appear on land

**Actual behavior:**
appear under land

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2021-11-13 07:16
Hi @hafizalias4484 

Thank you for this report but could you upload a screenshot and more detailed reproduction steps?
We are unable to replicate this issue and a screenshot or a video will help us to see the issue.

Thank you.

**Comment by D3nnis3n** [comment] 2022-07-18 10:10
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)

**Closed by D3nnis3n** 2022-07-18 10:10 UTC
Labels: Status: Needs Information
