### ISSUE TITLE
USER ISSUE: Loss of Inventory in Stockpiles

### ISSUE THREAD

**Issue by Ironhelix98** [StrangeLoopGames/EcoIssues#5934] opened 2018-03-12 00:12 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Have 2 Stockpiles next to each other
2. Ensure that stockpile 'A' is completely full of something. I've been using Logs.
3. Move the logs from 'A' to 'B'.
4. Repeat until 'B' is empty.

**Expected behavior:**
Stockpile 'B' should have the exact number of items as 'A' did at the beginning.

**Actual behavior:**
While moving items, the game will occasionally move the first partial, or complete if no partials are available, into the slot that you just dragged the item from 'A' into and lose the item from 'A'. This can result in some pretty big losses of inventory. I just lost 6.5 stacks of logs moving from one stockpile to another.

**Comment by MittenMarauder** [comment] 2018-03-12 18:03
Can confirm this happens to several people on our server.

**Comment by MarjieAVolk** [comment] 2018-03-13 22:35
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5895

**Closed by MarjieAVolk** 2018-03-13 22:35 UTC
