### ISSUE TITLE
Server Crash when trying to claim property with a stake. 

### ISSUE THREAD

**Issue by Swiftbiscuits** [StrangeLoopGames/EcoIssues#2628] opened 2017-10-25 19:25 UTC
Hello, on the new eden server we have a reproducible crash when trying to claim a certain piece of land with a stake. Upon crash, all players are receiving the object reference not set to an instance of an object error. 

--BEGIN DUMP--
Dump Time
10/25/2017 14:07:11

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.PropertyManager.ClaimAtomicAction.<TryApply>b__5_0(KeyValuePair`2 x)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Property.PropertyManager.ClaimAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.PropertyClaimItem.TryPlaceObject(Player player, Vector3i position, Quaternion rotation)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass13_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__50_0()

--END DUMP--

--BEGIN DUMP--
Dump Time
10/25/2017 14:20:45

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.PropertyPlot.ToBson()
   at Eco.Gameplay.Minimap.MinimapManager.GetPropertySince(Double time)
   at Eco.Gameplay.Minimap.MinimapManager.SendUpdate(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetObjectUpdates(IEnumerable`1 objects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__50_1()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2017-10-25 19:28
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2566

Working on this issue now

**Closed by MarjieAVolk** 2017-10-25 19:28 UTC
