### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Squirrelmeat27** [StrangeLoopGames/EcoIssues#22492] opened 2021-07-27 22:53 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
used join game through steam friend list isnt responding or will time out

**Expected behavior:**
joined friends server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2021-08-05 18:26
Hi @Squirrelmeat27 

Thank you for writing this report. We recently encountered some issues with our servers and it should be fixed by now.
Our development team has addressed this issue and we would like to kindly ask you to check if you're still encountering or having difficulties with establishing, connecting, or playing with a friend. Do let us know if any issue arises. Looking forward to your reply.

**Comment by Daniel-Magulado** [comment] 2021-08-11 01:16
Closing for no reponse. Assuming the issue is fixed for the player.

**Closed by Daniel-Magulado** 2021-08-11 01:16 UTC
Labels: Status: Needs Information
