### ISSUE TITLE
USER ISSUE: Incorrect Tooltip for gathering

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#25210] opened 2024-10-26 00:07 UTC
\
**User Id: (b3a00080-774a-4d53-fc0d-08dc8cbaa721)**
**Version:** 0.11.1.0 beta release-750

**Steps to Reproduce:**
1. Pickup Fresh Raw Food	

**Expected behavior:**
It should be telling me how much I picked up in the text that pops up

**Actual behavior:**
The pop-up text is totalling the amount I have in my inventory.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes I am on a modded server. I haven't yet been able to test on vanilla.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-10-26 02:57
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25207

**Closed by D3nnis3n** 2024-10-26 02:57 UTC
