### ISSUE TITLE
cart issues 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#425] opened 2016-07-03 22:21 UTC
http://ecoforum.strangeloopgames.com/topic/663/wooden-cart-bugs-4-1

**Comment by craig-jong** [comment] 2016-07-05 17:07
somewhat a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/408

**Comment by metachronism** [comment] 2016-10-27 18:31
fixed/improved in alpha 5

**Closed by metachronism** 2016-10-27 18:31 UTC
Labels: bug, critical
