### ISSUE TITLE
USER ISSUE: Gui Icon Glitch

### ISSUE THREAD

**Issue by Lagicrus** [StrangeLoopGames/EcoIssues#5084] opened 2018-02-25 14:27 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Drag items from hotbar into inv

**Expected behavior:**
It should have moved them

**Actual behavior:**
Instead it glitches out and ends up with a hovering icon which needs a disconnect, reconnect to fix

**Comment by MarjieAVolk** [comment] 2018-02-26 19:18
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

Most people have said that minimizing the game and bringing it back up also fixes it.

**Closed by MarjieAVolk** 2018-02-26 19:18 UTC
