### ISSUE TITLE
USER ISSUE: Open doors with shovel

### ISSUE THREAD

**Issue by Bazzi89** [StrangeLoopGames/EcoIssues#4239] opened 2018-02-10 12:09 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. use shovel to open a door

**Expected behavior:**
open the door	

**Actual behavior:**
not open the door

**Comment by Dr-Hardware** [comment] 2018-02-12 04:09
ROFL, note its only with en EMPTY shovel

**Comment by Bazzi89** [comment] 2018-02-12 14:53
check ;D

**Comment by MarjieAVolk** [comment] 2018-02-13 00:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3868

**Closed by MarjieAVolk** 2018-02-13 00:12 UTC
