### ISSUE TITLE
0.7.4.6 EXCAVATOR can't owned by user.

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#7932] opened 2018-05-29 17:10 UTC
Game version 0.7.4.6

1. build a Excavator
2. put his on the ground
3. open it (press the "E" key)
4. we see in the top the mark "Owned by ."
5. any player can use this Excavator because he has no owner.
![excavator_error](https://user-images.githubusercontent.com/1098421/40674026-40287c88-637c-11e8-9691-aec9b94f157f.jpg)
**Re-entry to the server or restarting the client does not solve the problem**. Sometimes it helps to completely restart the server.

**Comment by Rambo99** [comment] 2018-05-29 17:30
1. I am the creator and owner
2. I tried to place on a plot of land belonging to me and on a free (not in any property) plot of land. Result on the screenshot.

**Comment by MarjieAVolk** [comment] 2018-05-31 17:45
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7931

**Closed by MarjieAVolk** 2018-05-31 17:45 UTC
Labels: High Priority
