### ISSUE TITLE
(6.1.0 #6680a326) - Flying stones

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2662] opened 2017-10-31 19:40 UTC
Well, ive heard stone flipper alot when you login or when the server has recently loaded. Like in this case you can see a stone far up in the air. This stone keeps falling down and then appear back up in the air.

![flyy mi friend fly](https://user-images.githubusercontent.com/32855684/32245347-c7208ea2-be7b-11e7-8456-d92ed396ed17.png)

This save should contain the bug:
http://thegoldyiron.se/downloads/Storage.rar

**Comment by MarjieAVolk** [comment] 2017-10-31 19:44
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2099

**Closed by MarjieAVolk** 2017-10-31 19:44 UTC
