### ISSUE TITLE
[Staging-a5db4bb6] Resolution confirmation button not clickable

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3696] opened 2018-01-29 19:52 UTC
On settings menu, when you change resolutions, the countdown and text is over top of the confirm button and the button cannot be clicked on.
![image](https://user-images.githubusercontent.com/1503963/35531124-15d47a76-0504-11e8-9483-87db931f2f2a.png)

**Comment by MarjieAVolk** [comment] 2018-01-29 21:28
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3661

**Closed by MarjieAVolk** 2018-01-29 21:28 UTC
