### ISSUE TITLE
USER ISSUE: Can't drive any car

### ISSUE THREAD

**Issue by Alexander912** [StrangeLoopGames/EcoIssues#25138] opened 2024-09-05 17:59 UTC
\
**User Id: (21003d7b-3ee5-4527-bef2-08dcbd51a712)**
**Version:** 0.11.0.3 beta release-715

**Steps to Reproduce:**
Hard to describe, happens sometimes on a dedicated server.

**Expected behavior:**
Driving is normally possible

**Actual behavior:**
Driving is sometimes not possible, as every time a vehicle is entered, or a cart is attempted to pull, the character no longer moves.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Modes installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-09-07 08:47
Issue is not reproducible, can you provide reproduction steps or other information?

**Comment by D3nnis3n** [comment] 2024-09-13 05:43
Closing due to not reproducible and no further information provided. Feel free to create a new issue if you can provide reproduction steps.

**Closed by D3nnis3n** 2024-09-13 05:43 UTC
Labels: Status: Needs Information, Status: Not reproduced
