### ISSUE TITLE
USER ISSUE: RoadItem not repairable

### ISSUE THREAD

**Issue by jarckn** [StrangeLoopGames/EcoIssues#3524] opened 2018-01-19 20:45 UTC
**Version:** 0.6.4.0 alpha

**Steps to Reproduce:**
1. Craft your RoadItem with 4 Boards
2. Use it till it breaks
3. Go to Repair Station
4. Try to repair it for stone
5. ???
6. Profit

**Expected behavior:**
Been repaired

**Actual behavior:**
The game crashed.
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Repair on RepairComponent!

Der Wert darf nicht NULL sein.
Parametername: key

Stack:
   bei System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   bei System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   bei System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   bei Eco.Gameplay.Skills.Skillset.GetSkill(Type skillType)
   bei Eco.Gameplay.Skills.RequiresSkillAttribute.IsMet(User user)
   bei Eco.Gameplay.Components.RepairComponent.Repair(Player player)

Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by Conchipedia** [comment] 2018-01-19 21:05
duplicate of
USER ISSUE: Road Tool + Repair Station, Game Crach #3485

**Comment by MarjieAVolk** [comment] 2018-01-19 21:48
Yes, closing as duplicate, thanks.  We already have a fix for this, will be available in the next release

**Closed by MarjieAVolk** 2018-01-19 21:48 UTC
