### ISSUE TITLE
[0.9.0 Staging - 1494] Skid Steer pulls from stockpile under certain situation

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#15559] opened 2020-04-05 08:02 UTC
**Steps to reproduce:** Have a skid steer loaded with items and a nearby stockpile that is almost full. Transfer items from skid steer to stock pile (with Shift or Shift+CTRL to ensure you hit the insufficient space on transfer). If the stockpile fills up and you still had more trying to transfer into the stockpile the storages become linked.
Enter the skid steer and left click to dig (whilst still in range of the stockpile)

**Expected behavior:** Half of the resources would stay in the stockpile and the skid steer would be able to continue digging

**Actual behavior:** It will act as if the skid steer attempted to pick up from stockpile and fill the bucket with anything from the stockpile.
To correct this behaviour, the only fix is to transfer back from the skid steer and then drive out of range of the stockpile

**Comment by elfl0rd** [comment] 2020-04-05 13:13
intended, if you "highlight" storage (including vehicles storages and stockpiles) skidsteer and excavator can grab items\blocks from it.

**Comment by NN-Mike** [comment] 2020-04-06 06:54
Not intended when you’re no where near the stockpile. Not left clicking the stockpile, left click to dig or even just empty space.

**Comment by SlayksWood** [comment] 2020-04-06 07:55
@NN-Mike 
I can't reproduce it with this information. Can your provide video or screenshots?

**Comment by NN-Mike** [comment] 2020-04-08 13:45
Was not able to replicate this again, but had it occur unexpectedly on 3 different occasions and then could consistently reproduce.
May be another factor like a workbench taking items at play here making it harder to spot

**Comment by SlayksWood** [comment] 2020-04-14 10:02
> Ran into a strange bug in the new build (wasn't an issue in the version before 1501). Because of #15525 I sometimes empty my skid by going into its inventory and dragging items out of it into the Truck. This works pretty well. However, today when I did that, the items moved, but when I started digging, the items moved back into the skid and I was out of inventory again. It wouldn't revert if you moved the items to a stockpile from the Truck.
> 
> 1. Version
>    0.9.0 Staging-1501
> 2. Steps to reproduce
> 
> * (be on the test server?)
> * Dig with a Skid, get it full
> * Open Skid's inventory
> * Drag items from Skid's inventory into a Truck
> * Resume digging with a Skid
> * Skid is now instantly full, Truck is empty
> * Drag items from Skid again, deposit items from Truck to Stockpile
> * Resume digging with a Skid, it works fine
> 
> Video: https://youtu.be/3-svJV92hKw
> 
> 1. Expected behavior
>    Items should stay in Truck.
> 2. Actual behavior
>    Items move back from the Truck to Skid
> 3. Providing Log files
>    https://mega.nz/file/8EQQFITL#O1JgcSDXX2RX-7NIM3F6u1mCSy8vr1u2dkYX--0NCh4

**Comment by henrikolsson** [comment] 2020-04-21 21:22
Seeing a similar issue. Skid steer pulling from a stockpile that's not in sight, seems to be selecting it to dig for even though there's layers of rock between the skid and the stockpiles. 

Video: https://www.dropbox.com/s/cv8dtuwl729zb9x/Eco%202020-04-21%2023-11-21.mp4?dl=0

**Comment by ThePiachu** [comment] 2020-11-07 02:37
Still an issue in 0.9.1.2 br-111

[Player - Skid Pulling.log](https://github.com/StrangeLoopGames/EcoIssues/files/5504189/Player.-.Skid.Pulling.log)

https://youtu.be/P4QNSlc0MdA

Fresh after White Tiger server restart too... Happens every now and then when you pick up the skid and place it back down. Maybe it has something to do with a Jaw Crusher being linked to the Skid?

**Comment by MishkaFur** [comment] 2020-11-07 13:31
Very repeatable https://github.com/StrangeLoopGames/EcoIssues/issues/18731

**Comment by SlayksWood** [comment] 2021-02-08 06:44
merged to #18731

**Closed by SlayksWood** 2021-02-08 06:44 UTC
Labels: Status: Investigate
