### ISSUE TITLE
USER ISSUE: Contract

### ISSUE THREAD

**Issue by D3thM3tal** [StrangeLoopGames/EcoIssues#5113] opened 2018-02-26 05:04 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Click on job board, click create contact and then hit escape or close the window.  You can't hit any of the escape menu options or click on anything else in game	

**Expected behavior:**
should have canceled it 

**Actual behavior:**
locks you out of menus - have to alt f4 to get out, log back in to click on contract to cancel it.

**Comment by MarjieAVolk** [comment] 2018-02-26 22:39
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

**Closed by MarjieAVolk** 2018-02-26 22:39 UTC
