### ISSUE TITLE
USER ISSUE: tree entry pick 

### ISSUE THREAD

**Issue by supernova011** [StrangeLoopGames/EcoIssues#4848] opened 2018-02-20 02:33 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
chop log 
log floats up without garvity then bug error

**Expected behavior:**
entered inventory or cut into smaller pieces

**Actual behavior:**
object reference not set to an instance of an object

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-20 21:44
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-20 21:44 UTC
