### ISSUE TITLE
USER ISSUE: Game freeze When clearing tutorials

### ISSUE THREAD

**Issue by ThatGuyMason** [StrangeLoopGames/EcoIssues#21556] opened 2021-04-24 14:40 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
Try to exit a tutorial on the top left

**Expected behavior:**
It should have just cleared the tutorial.

**Actual behavior:**
it blurrs my screen and freezes my input

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no  mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2021-04-24 23:33
Hi, thank you for making a report about this.
Unfortunately, we are unable to reproduce this issue.
Could you provide us with more information, please?

We would appreciate it if you could please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

A recorded video of the issue would also be great.

Looking forward to your response.

**Comment by Daniel-Magulado** [comment] 2021-05-10 08:02
Hello, we haven't received any response from you for a while now.
We'll be closing this ticket but feel free to open it again if this issue persists for you.

**Closed by Daniel-Magulado** 2021-05-10 08:02 UTC
Labels: Status: Needs Information
