### ISSUE TITLE
Plants and trees after reboot ready for harvest

### ISSUE THREAD

**Issue by TapZap1** [StrangeLoopGames/EcoIssues#5976] opened 2018-03-12 23:54 UTC
After a server reboot almost all plants and trees are fully grown. Version 7.2.3

**Comment by alecpura** [comment] 2018-03-13 03:16
Just gonna say I saw another person report this through Kayako.

"but, i found a problem. new plantet tomatos, bets ... they all are instantly ready to harvest after logout / login. and otherwise is no growing progress of any plants ... any solutions for that?"

**Comment by MarjieAVolk** [comment] 2018-03-13 23:07
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4003

**Closed by MarjieAVolk** 2018-03-13 23:07 UTC
