### ISSUE TITLE
USER ISSUE: Plant already exist here

### ISSUE THREAD

**Issue by Duchue01** [StrangeLoopGames/EcoIssues#5688] opened 2018-03-08 17:31 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**

**Expected behavior:**
It should show me the dead plant

**Actual behavior:**
instead i got an invisible dead plant that i can't remove ...

**Comment by Thyriel** [comment] 2018-03-08 18:09
One of our farmers has the same problem with a block. Not even devTool destroying the block can solve it

**Comment by Duchue01** [comment] 2018-03-08 18:16
I have this with the half of my farm.. More than 50 blocks are just unusable :/

**Comment by MarjieAVolk** [comment] 2018-03-08 19:31
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5522

**Closed by MarjieAVolk** 2018-03-08 19:31 UTC
