### ISSUE TITLE
Client crashing on loading a certain world

### ISSUE THREAD

**Issue by Apepotet** [StrangeLoopGames/EcoIssues#8284] opened 2018-07-03 01:08 UTC
My client crashes every time I try to join a certain world, I can make a new one but I can't join the old one without crashing! Got a crash report as well:
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2157280/error.log)

Could not upload the DMP file here tho

**Comment by SeanAtr0n** [comment] 2018-07-03 02:03
could you send us the log file from `%APPDATA%\..\LocalLow\Strange Loop Games\ECO` after crashing?

**Comment by pamduncan** [comment] 2018-07-03 09:20
If you like you can come to the discord #Support channel and we can help you resolved this.

**Comment by pamduncan** [comment] 2018-07-03 09:57
He was on a ramp and crashed out.  Assuming this is the ramp bug again.  He is going to try and get someone to remove the ramp first

**Comment by pamduncan** [comment] 2018-07-03 10:19
The ramp was removed and he was able to get back in the game.

**Comment by Deantwo** [comment] 2018-07-03 13:42
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8273?

**Comment by Leibniz01** [comment] 2018-07-03 14:59
Hey, I crashed after placing a dirt ramp under my feet. I also used /unstuck 2 or 3 times before that. Now I get a crash message everytime I try to join the server. Seems to be the same error so I do not repost. 

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2159898/error.log)

**Comment by Deantwo** [comment] 2018-07-03 15:01
If it is the same error, then it is already fixed, as seen in #8273.

If you are playing multiplayer, you can try to get someone else on the server to remove the dirt ramp.

**Comment by SeanAtr0n** [comment] 2018-07-03 18:24
most likely fixed in next hotfix

**Closed by SeanAtr0n** 2018-07-03 18:24 UTC
Labels: Critical Priority
