### ISSUE TITLE
USER ISSUE: Wheat and Beans Problem

### ISSUE THREAD

**Issue by ericlevy67** [StrangeLoopGames/EcoIssues#19878] opened 2020-12-30 18:46 UTC
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
I am trying to reap/gather beans and wheat.

**Expected behavior:**
Put the beans and wheat in my quickbar inventory.

**Actual behavior:**
Does nothing and the plants disappear from the world.	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment] 2021-01-05 06:50
@ericlevy67 Thank you for reporting, I need some more information for investigating 
could you provide some log files from when you are trying to perform these actions?
Also is the server modded or not?
Is this single player or a multiplayer server?

**Comment by ericlevy67** [comment] 2021-01-05 22:19
Good evening:
I cannot provide log files on the first bug report I submitted because that was a few days ago, and I deleted those worlds. However, I submitted a second bug report on the same issue (except different things were not being put in my inventory) a day or two later, and I did include log files with that report.
The problem occurred on both single player and multi-player servers. They initially occurred on servers with no mods, but recently occurred on one of my solo worlds where I had one mod installed.
Hopefully that helps,
Eric
    On Tuesday, January 5, 2021, 12:50:49 AM CST, Jens <notifications@github.com> wrote:  
 
 


@ericlevy67 Thank you for reporting, I need some more information for investigating
could you provide some log files from when you are trying to perform these actions?
Also is the server modded or not?
Is this single player or a multiplayer server?

**Comment by SlayksWood** [comment] 2021-01-18 09:09
@ericlevy67 I still can't reproduce it in 0.9.2 staging-1902 and 0.9.1.9 release. 
Please provide your PC specification (include Operating System).

**Comment by IcedForge** [comment] 2021-02-17 10:34
Will close this in lack of reply.

**Closed by IcedForge** 2021-02-17 10:34 UTC
Labels: Status: Needs Information
