### ISSUE TITLE
Web Interface Performance Bugs

### ISSUE THREAD

**Issue by SevWren** [StrangeLoopGames/EcoIssues#18711] opened 2020-09-27 22:40 UTC
There's a serious performance bug (at least I'm experiencing) with the web interface system currently that I doubt I'm the minority.

My Specs
- Windows 10 home 64bit
- Intel i7-5500u  @ 2.40GHz
- 8gigs Ram
- GPU'S
- Intel HD Graphics 5500
- Nvidia GeForce 930m
- Chrome - Version 85.0.4183.121 (Official Build) (64-bit)

Using Chrome
_Without hardware acceleration
No extensions
Chrome default config_

**Simply the default landing page becomes unresponsive or a sporadic 1fps on loading the page**
(Cpu 99% cap using my Intel Graphics GPU) when pressing the time-lapse play button.)
![image](https://user-images.githubusercontent.com/4411791/94377215-2ef12b00-00e5-11eb-9354-e813f4c261d1.png)

When using Chrome
_With hardware acceleration (Nvidia GeForce 930m Gpu),_

Within 10 seconds of starting the time-lapse the web interface instantly reserves 100% of my gpu's onboard ram and then starts reserving system ram.

Within minutes this causes Chrome to reserve ALL unreserved ram for simply one tab open. 

Granted this doesn't cause a massive CPU footprint compared to my onboard gpu, to get a simple working model requires using hardware acceleration that reserves almost all system ram for this one tab leaving nothing else for even basic system tasks.

![image](https://user-images.githubusercontent.com/4411791/94377358-762beb80-00e6-11eb-81a0-bbbfa3e3aeaa.png)

**Comment by D3nnis3n** [comment] 2020-10-12 13:50
Can you reproduce this issue with a supported map size of maximum 4 km², e.g. 200x200. The map seems to be way bigger than we support. I cannot see this issue with any supported map size, so it'd be useful to know if it only happens on unsupported sizes, in which it might be a wontfix or a low priority fix.

**Comment by IcedForge** [comment] 2021-02-18 10:23
Will close this issue as there was never a reply from author.

**Closed by IcedForge** 2021-02-18 10:23 UTC
Labels: Status: Investigate
