### ISSUE TITLE
[0.9.3.2] Not all user titles are displayed

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21513] opened 2021-04-22 00:25 UTC
I checked someone's titles and noticed that not all of them were displayed:

![image](https://user-images.githubusercontent.com/964559/115637963-4896d180-a2c6-11eb-82be-153eedae9033.png)

![image](https://user-images.githubusercontent.com/964559/115637977-4df41c00-a2c6-11eb-9688-ed56f127cee4.png)

Not sure what's up with that, maybe it's related to #21511 ?

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6354614/Player.log)

**Comment by D3nnis3n** [comment] 2021-04-22 01:45
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20314

**Closed by D3nnis3n** 2021-04-22 01:45 UTC
