### ISSUE TITLE
USER ISSUE: CRANE

### ISSUE THREAD

**Issue by CocoJambo23CZ** [StrangeLoopGames/EcoIssues#24683] opened 2024-01-23 15:11 UTC
\
**User Id: (slg239804)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
Hello when i picked up with CRANE from stockpile items the game crashed and after i come in CRANE it will freeze and dont respond after it crash

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![20240123160845_1](https://github.com/StrangeLoopGames/EcoIssues/assets/156304788/0d876f62-d759-422f-b8fd-c63fe3abbcfc)

**Comment by D3nnis3n** [comment] 2024-01-23 23:57
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24642

**Closed by D3nnis3n** 2024-01-23 23:57 UTC
