### ISSUE TITLE
Economy viewer and ecopedia cursor should start in search panel

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20431] opened 2021-02-07 21:44 UTC

**Comment by SlayksWood** [comment] 2021-02-08 09:21
Ecopedia issue here #18832

**Comment by WeaselDog** [comment] 2021-02-08 21:36
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18832

**Closed by WeaselDog** 2021-02-08 21:36 UTC
