### ISSUE TITLE
High CPU Performance Issiu

### ISSUE THREAD

**Issue by Finest** [StrangeLoopGames/EcoIssues#5685] opened 2018-03-08 16:57 UTC
Hello,
we host about 1k Eco Server now and we got Massiv CPU Usage problems. Some Server are empty or got 1 - 2 Players on it and use about 25 up to 70 % CPU

here are some screenshots.

https://puu.sh/zDi7r/23e53447de.png

https://puu.sh/zDi4w/9bf821a638.png

this Problems start with Patch 7.2.X

Version 0.7.2.2 beta
Config: Intel Xeon 1270v6 64 gb Ram

**Comment by MarjieAVolk** [comment] 2018-03-08 22:28
Thanks, closing as duplicate of #5640. We are working on fixing performance problems asap.

**Closed by MarjieAVolk** 2018-03-08 22:28 UTC
