### ISSUE TITLE
[7.6.1] Hewn logs efficiency still has issues

### ISSUE THREAD

**Issue by PacifyerGrey** [StrangeLoopGames/EcoIssues#8638] opened 2018-07-19 19:12 UTC
7.6.1, single player new clean unmodded game.
Testing with Hewing Efficiency level 5
1. Workbench recipe is NOT effected by efficiency skill so no matter the efficiency you use 2 Logs per hewn log
2. Carpenter table recipe states 0.4 Logs per hewn log. Ordering 100 hewn logs requires 41 Log, while ordering 99 requires 40. So we have rounding errors.

**Comment by Limelill** [comment] 2018-07-20 18:43
Can confirm that there are rounding errors in many recipes. Seen in both masonry, machinist, cooking, and carpentry.

**Comment by Wally1169** [comment] 2018-07-22 19:42
Confirmed as well.  It seems there is some intermediate rounding going on in the calculations when generally rounding should happen at the very end, if at all

**Comment by Nicolausi113** [comment] 2018-07-25 02:18
Different amount of log and time between workbench and carpentry table, also tool-tip looks different. I’ve commented in #8666 but could not reopen ticket.

![workbench menu](https://user-images.githubusercontent.com/38510829/43175901-a3e0d556-8fc1-11e8-92ba-c18eb6934a56.jpg)

![carpentry menu](https://user-images.githubusercontent.com/38510829/43175916-b2d18bd2-8fc1-11e8-95f7-555ae4bf8a67.jpg)

**Comment by craig-jong** [comment] 2018-07-26 22:35
Rounding errors should be fixed in the most recent version.

The recipes being different on the workbench and carpentry table is intentional and not a bug.

**Closed by craig-jong** 2018-07-26 22:35 UTC
Labels: Medium Priority
