### ISSUE TITLE
USER ISSUE: no idea

### ISSUE THREAD

**Issue by lalawunderland** [StrangeLoopGames/EcoIssues#5081] opened 2018-02-25 13:37 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
i've no idea what has happend

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-26 19:04
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-26 19:04 UTC
