### ISSUE TITLE
Database Lock Up is stopping .Net 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6172] opened 2018-03-17 02:30 UTC
[![Screenshot from Gyazo](https://gyazo.com/a05db275cb59f36d1515e44274b3a6d2/raw)](https://gyazo.com/a05db275cb59f36d1515e44274b3a6d2)

**Comment by MarjieAVolk** [comment] 2018-03-20 23:28
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343

**Closed by MarjieAVolk** 2018-03-20 23:28 UTC
