### ISSUE TITLE
Hammering log to remove from building, switches to axe

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#871] opened 2016-12-03 04:11 UTC
Hammering log to remove from building, switches to axe. Annoying :(

Eco 0.5.0

![image](https://cloud.githubusercontent.com/assets/6193670/20856734/77cb3510-b97b-11e6-83e3-5759e63ed9de.png)

![image](https://cloud.githubusercontent.com/assets/6193670/20856735/7aff0202-b97b-11e6-8582-5112bfcb2b4f.png)

**Comment by noblackthunder** [comment] 2016-12-03 08:32
not really a bug because you are supposed to use the axe on logs now ;)

**Comment by MarjieAVolk** [comment] 2017-02-21 00:35
Closing this as out of date and/or intended behavior.  It seems to be the case now that breaking a log with an axe switches you to the hammer; but you can use either axe or hammer to break logs, so I don't think this is a problem

**Closed by MarjieAVolk** 2017-02-21 00:35 UTC
