### ISSUE TITLE
USER ISSUE: Crimini Mushrooms

### ISSUE THREAD

**Issue by Hezzi6** [StrangeLoopGames/EcoIssues#5732] opened 2018-03-09 00:21 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Start game	

**Expected behavior:**
spawning crimini mushrooms on map

**Actual behavior:**
no crimini mushrooms on map

**Comment by MarjieAVolk** [comment] 2018-03-09 00:24
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Closed by MarjieAVolk** 2018-03-09 00:24 UTC
