### ISSUE TITLE
[0.9.0 Staging-1494] Particle effects going black

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15509] opened 2020-04-02 09:40 UTC
After mining some Basalt for awhile the particle system seems to have gone rather black:

![image](https://user-images.githubusercontent.com/964559/78233675-f00e4f80-748a-11ea-99b8-444612e086b8.png)

The dot denoting the mining position is also black, rather than green. Not sure how to replicate it with just mining (I have mined all day and this rarely happened), but as far as I remember I got the same effect after using the `/fly` command for awhile, going around the place, speeding up, moving through buildings, activating and deactivating `/fly` for awhile, etc. Eventually the particle effects go black with that as well.

Maybe it has something to do with the amount of particles generated?

**Comment by elfl0rd** [comment] 2020-04-02 09:46
Duplicate of #14042

**Closed** 2020-04-02 10:03 UTC
