### ISSUE TITLE
[0.9.1 develop-76] Stockpile Tutorial: Inserting logs counts twice

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#18609] opened 2020-10-06 08:24 UTC
In the stockpile tutorial, when inserting logs into the stockpile it counts as adding two logs.

This is because it runs CheckComplete twice.

**Comment by SlayksWood** [comment] 2020-12-01 11:20
I still ned to place only 5 logs to complete tutorial:
![image](https://user-images.githubusercontent.com/45708377/100734146-4350ed00-33e0-11eb-9671-0c65b01210e3.png)

**Comment by abaza121** [comment] 2021-01-07 19:23
About this issue I can't reproduce it except if I kept moving item from the inventory back and forth, you can technically pass it with 1 log in that case but if in bulk it does work as it should (in order to complete u need to put 10 logs in bulk)

**Comment by Daniel-Magulado** [comment] 2021-02-24 07:07
Tested on 0.9.3 Staging-1938.

Fixed and closing.

**Closed by Daniel-Magulado** 2021-02-24 07:07 UTC
Labels: Category: Gameplay, Priority: Medium, Squad: Wild Turkey, Status: Fixed
