### ISSUE TITLE
Powered Cart's Text label flies in the air at long distance

### ISSUE THREAD

**Issue by geeknessfr** [StrangeLoopGames/EcoIssues#6618] opened 2018-03-29 02:15 UTC
Game Version : 7.3.0 but it happened also on 7.2.5.

I think the Curved Shader is missing on the Text Label Material.

I take some screenshots :

Short distance
![image](https://user-images.githubusercontent.com/28137335/38066508-90926cfa-3308-11e8-931e-f0f9f4b7c394.png)
 
Medium Distance
![image](https://user-images.githubusercontent.com/28137335/38066517-9aff22b4-3308-11e8-88f9-80e808de2af2.png)

Long Distance
![image](https://user-images.githubusercontent.com/28137335/38066522-a488521a-3308-11e8-8d10-40f34e267746.png)

**Comment by MarjieAVolk** [comment] 2018-04-03 00:30
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5602

**Closed by MarjieAVolk** 2018-04-03 00:30 UTC
