### ISSUE TITLE
sewage generated when blastfurnace runs out of coal

### ISSUE THREAD

**Issue by Sn00be** [StrangeLoopGames/EcoIssues#11352] opened 2019-02-16 08:53 UTC
When your using blastfurnace and it runs out of coal.
It still produces sewage to the waste filter. 
It will continue to fill up stockpile.
![blastinfo](https://user-images.githubusercontent.com/47687107/52897087-81136000-31d0-11e9-8403-037cc4880046.png)
![blastflow](https://user-images.githubusercontent.com/47687107/52897089-840e5080-31d0-11e9-81b4-05a8da195c02.png)
![wasteflow](https://user-images.githubusercontent.com/47687107/52897090-85d81400-31d0-11e9-93fa-632ec957f4f8.png)

**Comment by elfl0rd** [comment] 2019-02-16 09:13
Looks as same root issue with https://github.com/StrangeLoopGames/EcoIssues/issues/11213

**Comment by Sn00be** [comment] 2019-02-16 09:44
Might be the same.
I can also tell, that waste plant is still generating compost even tho my steam engine is turn off

**Comment by elfl0rd** [comment] 2019-02-17 23:22
Duplicate of #11268

**Closed by elfl0rd** 2019-02-17 23:22 UTC
