### ISSUE TITLE
[8.2.0 staging-4] quiting the game hangs

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#12236] opened 2019-05-09 14:18 UTC
![image](https://user-images.githubusercontent.com/431728/57460725-0468bd00-72b9-11e9-81e2-8cf1c106eef4.png)

**Comment by D3nnis3n** [comment] 2019-05-15 10:44
Does this still occur on the latest version? Could not reproduce.
Any logs?

**Comment by redwyre** [comment] 2019-05-15 17:13
I've had it once or twice, haven't been testing the steam version since.
Might also be related to Unity Editor hanging after closing the project which is definitely still happening (and hanging builds).

**Comment by madhatr** [comment] 2019-05-17 10:26
My game hangs evertime I quit.  If I continue to click I will get that non responsive window.  I usually Alt-Tab out and do other things while it closes.

**Comment by D3nnis3n** [comment] 2019-06-20 10:22
Closing for now due to not being reproducable and no logs available. Reopen when it occurs again and you can provide more information / logfiles.

**Closed by D3nnis3n** 2019-06-20 10:22 UTC
Labels: Needs Information, Not reproduced, Staging
