### ISSUE TITLE
USER ISSUE: Connection Error

### ISSUE THREAD

**Issue by wyattprice18** [StrangeLoopGames/EcoIssues#24625] opened 2024-01-17 21:34 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
join server

**Expected behavior:**
joined server

**Actual behavior:**
The following error message popped up:
```
Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-18 03:41
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24380

**Closed by D3nnis3n** 2024-01-18 03:41 UTC
