### ISSUE TITLE
USER ISSUE: "put item in" contract

### ISSUE THREAD

**Issue by ownyHD** [StrangeLoopGames/EcoIssues#4254] opened 2018-02-10 15:41 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**

**Expected behavior:**
should be able to only put items in but not to take them out

**Actual behavior:**
contractor is able to take stuff out of the chest/stockpile

**Comment by LiaungYip** [comment] 2018-02-10 22:35
Duplicate of #4270.

**Comment by MarjieAVolk** [comment] 2018-02-13 04:59
Thank you; Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4270.  You can track the issue progress there.

**Closed by MarjieAVolk** 2018-02-13 04:59 UTC
