### ISSUE TITLE
Error while requesting AuthServer endpoint

### ISSUE THREAD

**Issue by D3vil787** [StrangeLoopGames/EcoIssues#24850] opened 2024-03-31 05:35 UTC
Hi!
My server was working fine, but after rebooting without any changes I get the same error.
I have another test server, in a different location with a different Internet provider, which worked fine yesterday and today has the same error.
So, without any changes, today I received two servers with the same problem.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/82601468/a7c1a572-e442-4fc5-b921-6e2e5a5efc31)

\
**User Id: (slg232823)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-04-01 16:21
What is the range of your computers public IP? Need first and second field, e.g. 123.123.X.X.

**Comment by SpitefulFennec** [comment] 2024-04-01 16:34
Looks like i have same problem. My public IP starts with 194.50.X.X. 

Actually, i even try to start server with mobile internet and get same error

**Comment by SentilONE** [comment] 2024-04-01 16:47
> What is the range of your computers public IP? Need first and second field, e.g. 123.123.X.X. Please also note your country of origin and the ISP.

77.51.X.X

**Comment by Pro100-Adm** [comment] 2024-04-01 17:53
46.138.240.54, Russian Federation, ISP:MGTS

**Comment by 69NEPHILIM69** [comment] 2024-04-01 18:09
192.168.X.X Russian Federation, ISP:Rostelecom

**Comment by Mercer12** [comment] 2024-04-01 19:06
192.168.ХХ Российская Федерация, интернет- провайдер  МГТС

**Comment by SpitefulFennec** [comment] 2024-04-01 20:03
The server started via VPN... It turns out that the problem lies in the country where the server is located. Is it possible on your part to make sure that the server can be launched from Russia?

**Comment by D3nnis3n** [comment] 2024-04-01 20:33
No, the issue was caused by Cloudflare dynamically blocking IP ranges. The only way would be to remove Cloudflare, which is not an option.

The block seems to be over, hence I'm closing the issue as resolved. If it appears again, you'll unfortunately need to use a VPN. Cloudflare and some russian ISP's have issues in general, probably due to local legislation. Some ISP's won't work at all.

**Closed by D3nnis3n** 2024-04-01 20:33 UTC
Labels: Status: Needs Information

**Comment by SpitefulFennec** [comment] 2024-04-01 20:37
Yes. all works again. Thx for quick help and for detailed explanations! I really much enjoy to be part ofthat great Eco comunity!

**Comment by roghaldorn** [comment] 2024-04-01 21:05
Fix plz this IP
95.165.X.X
We have a dedicated server, until March 30, 2024 it worked correctly, but yesterday, when I tried to connect any user to the server, the same error Error while requesting AuthServer endpoint

**Comment by VitaliyYa** [comment] 2024-04-15 14:41
@D3nnis3n, greetings!
It looks like I've encountered the same problem, but I'm in Georgia. IP 5.152.33.xxx. When Cloudflare Warp is enabled, it cannot connect to the server. It's strange because I'm playing locally and alone. Do you have any recommendations on what to do in this case, perhaps write to Cloudflare support?
