### ISSUE TITLE
USER ISSUE: catched fish not shown in inventory

### ISSUE THREAD

**Issue by haaileen** [StrangeLoopGames/EcoIssues#4993] opened 2018-02-23 14:30 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
fishing with pole

**Expected behavior:**
fish should appear in inventory

**Actual behavior:**
have to log out and reconnect to see wich fish i got, also not able to use it for cooking without reconnecting

**Comment by MarjieAVolk** [comment] 2018-02-23 23:37
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

**Closed by MarjieAVolk** 2018-02-23 23:37 UTC
