### ISSUE TITLE
USER ISSUE: World disapear

### ISSUE THREAD

**Issue by zeubkiller** [StrangeLoopGames/EcoIssues#4727] opened 2018-02-17 18:36 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
A played solo in a generated world
After 3h of play the world started to disappear around me
Currently I have only my house that is still there
Everytime I step outside I fall in the universe and keep failing until I disconect

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-20 22:06
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861

Does reconnecting help?

**Closed by MarjieAVolk** 2018-02-20 22:06 UTC

**Comment by zeubkiller** [comment] 2018-02-21 08:35
Yes, It's working fine after I close and reopen the game thanks :)
