### ISSUE TITLE
USER ISSUE:  Crash 100% cpu

### ISSUE THREAD

**Issue by laradji** [StrangeLoopGames/EcoIssues#4403] opened 2018-02-12 19:31 UTC
Version: 0.7.1.0 beta

12 players

Stacktrace here : 

> :24] Caught update exception from Hash-K!  Disconnecting...
> [28:25] Disconnecting client [reason: Caught exception: Object reference not set to an instance of an object.]...
> 
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
>    at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
>    at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
>    at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
>    at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
>    at Eco.Core.Controller.ControllerManager.Run()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by laradji** [comment] 2018-02-12 20:20
more log 

`
:24] Caught update exception from Hash-K!  Disconnecting...
[28:25] Disconnecting client [reason: Caught exception: Object reference not set to an instance of an object.]...

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
`

**Comment by MarjieAVolk** [comment] 2018-02-13 22:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368.  You can track the issue progress there.

**Closed by MarjieAVolk** 2018-02-13 22:29 UTC
Labels: High Priority
