### ISSUE TITLE
USER ISSUE: Fish Trap harvesting and floating

### ISSUE THREAD

**Issue by 94cents** [StrangeLoopGames/EcoIssues#5173] opened 2018-02-27 11:47 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Attempt to harvest from a fish trap
2. Automatically float away from the container
3. Contribute salty tears to the ocean

**Expected behavior:**
Tasty fish

**Actual behavior:**
Broken dreams

**Comment by MarjieAVolk** [comment] 2018-02-27 18:54
Hahaha :'D  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4275

**Closed by MarjieAVolk** 2018-02-27 18:54 UTC
