### ISSUE TITLE
USER ISSUE: Gathering lvl. 6 reversed?

### ISSUE THREAD

**Issue by dasl3on** [StrangeLoopGames/EcoIssues#21901] opened 2021-05-17 14:05 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
1. special ability lvl 6 gathering
2. choose 20% more for farmed yield

**Expected behavior:**
5 or 6 beets for farmed / 3 for wild

**Actual behavior:**
5 or 6 beets for wild / 3 for farmed

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, only tested in vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment] 2021-05-18 06:37
Thank you for reporting.
Could you explain a bit on what plants, in what conditions and did you verify with soil sampler for the yields?
As dependent on nutrients in the ground this will also affect harvests.

Tried out 
0 skill : 3 yield
max skill no perks : 6 yield
max skill farm perk on farmed plant : 7 yield
max skill farm perk on wild plant : 6 yield

**Comment by dasl3on** [comment] 2021-05-23 14:24
Yield for farmed beets: 4 beets, 2 greens and 1 seed
For wild beets on the same place: 6 beets, 2 greens and 2 seeds

The yield of both plants should be the same, or the home-grown plants should yield more, as both plants are grown in the same soil.



![Screenshot_14](https://user-images.githubusercontent.com/84331662/119264083-fb1dc500-bbe1-11eb-80d4-5afa08b7afb9.png)

**Comment by TwixterZ** [comment] 2021-06-04 10:13
Tested this issue in 9.3.5 Release 231 , below are my findings 

Wild tomato plant status :
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/f45c525e-84f7-4ae3-a6ef-41994d52aba8)

Wild tomato plant harvest:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/893b4f52-71ca-400c-86a2-f47552499e9c)

Farmed tomato plant status:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/0342c905-00d5-4387-adf3-82a1c8526a40)
_Worth noting I uses fertilizer for it_

Farmed tomato plant harvest:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/24a956e5-6b90-43d9-b2fe-2516522e8c56)

20% from 6 yield = 1.2 

Hence 7 tomato harvested

I will continue testing this with beets and will post my findings in next comment.

**Comment by TwixterZ** [comment] 2021-06-04 10:30
Tested with Beets, results below 

Both farmed and wild beets are 2 blocks apart :

Wild beets status :
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/22e95c6d-90ed-49ba-9468-2cf26783852b)

Wild beets harvest:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/40ee7cc2-9d18-42a9-93ae-77c8b95a9422)

Farmed beets status:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/12daf977-2569-413b-af6d-08f347858a8b)
_No fertilizer used_

Farmed beets harvest:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/8b7cc6be-7bcc-4f66-b7d9-424c81092ee1)

Similar result achieved as per tomato test earlier, we can conclude this talent is working as intended.

**Comment by TwixterZ** [comment] 2021-06-04 10:32
@dasl3on please see my findings above and if you find them satisfactory, we may close this issue.

**Comment by TwixterZ** [comment] 2021-06-17 08:15
Closing issue due to lack of response.

**Closed by TwixterZ** 2021-06-17 08:15 UTC
Labels: Status: Needs Information
