### ISSUE TITLE
USER ISSUE: Got disconnected hitting a small tree.

### ISSUE THREAD

**Issue by ZeskaN** [StrangeLoopGames/EcoIssues#5908] opened 2018-03-11 16:30 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
I tried to hit a small tree that didn't have a hit box, and the game disconnected me. It happened multiple times, and I also had a mate hit the tree for the same result. Couldn't target it with anything.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-12 20:59
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5619 - Noting there that it may be related to young trees.

**Closed by MarjieAVolk** 2018-03-12 20:59 UTC
