### ISSUE TITLE
USER ISSUE: server browser crash

### ISSUE THREAD

**Issue by KlausT** [StrangeLoopGames/EcoIssues#6859] opened 2018-04-01 21:36 UTC
**Version:** 0.7.3.1 beta (0.7.2.5 is ok)

**Steps to Reproduce:**
Start ECO
Click on "Join"

**Expected behavior:**
List all servers

**Actual behavior:**
starts checking servers but crashes after 10 seconds

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1866720/output_log.txt)

OS: Windows 10 Home
CPU: AMD Phenom II X4 910e
RAM: 8 GB
Graphics: Nvidia GTX1070
Internet: 16kbit/s DSL

**Comment by MarjieAVolk** [comment] 2018-04-02 22:41
We've got a few people reporting this, but not many leads yet.

One person says that having Windows Explorer open is related to the problem - so if by chance you have it open, try again with it closed?  This is one of the craziest pieces of advice I have given, but worth a shot I guess.

**Comment by MarjieAVolk** [comment] 2018-04-02 23:08
In the mean time, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6821

**Closed by MarjieAVolk** 2018-04-02 23:08 UTC
