### ISSUE TITLE
Alpha.6 trees growing on stockpile

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2368] opened 2017-09-28 10:52 UTC
![image](https://user-images.githubusercontent.com/1900106/30962912-e32d4e04-a44b-11e7-8b83-597bf8e2b966.png)

**Comment by MarjieAVolk** [comment] 2017-09-28 17:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2352

**Closed by MarjieAVolk** 2017-09-28 17:43 UTC

**Comment by Fank** [comment] 2017-09-28 17:46
:man_facepalming:
