### ISSUE TITLE
Server Crash Dump: Argument Null Exceptions 

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [StrangeLoopGames/EcoIssues#5961] opened 2018-03-12 21:09 UTC
All errors generate on dedicated server with 20 players on server at random times I am leaving logs in hopes it helps

--BEGIN DUMP--
Dump Time
03/12/2018 20:50:48

Exception
System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Eco.Shared.Networking.INetObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by Edgar-BlipparDev** [comment] 2018-03-12 21:10
--BEGIN DUMP--
Dump Time
03/12/2018 20:51:24

Exception
System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Eco.Shared.Networking.INetObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by Edgar-BlipparDev** [comment] 2018-03-12 21:10
--BEGIN DUMP--
Dump Time
03/12/2018 20:51:32

Exception
System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Eco.Shared.Networking.INetObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-13 21:58
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5628

**Closed by MarjieAVolk** 2018-03-13 21:58 UTC
