### ISSUE TITLE
USER ISSUE: Create Law Not Working

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#11742] opened 2019-03-24 02:49 UTC
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
1. Be in the process of making a new and complex law, upon trying to publish it recieve an error message which mentions a district which is unnamed even though there are no district definitions in the law.
2. Refresh the law page.

**Expected behavior:**
It should have reset the page so I can start over.

**Actual behavior:**
The page is missing the section where laws can be configured, it only has the name field and description sections ignoring the middle. (I'm not admin I cannot restart server.)

**Do you have mods installed? Does issue happen when no mods are installed?:**
The page is missing the section where laws can be configured, it only has the name field and description sections ignoring the middle. (I'm not admin I cannot restart server.)

**Comment by Blanclour** [comment] 2019-03-24 14:51
Toggling between different tabs in web interface seemed to have fixed the issue.

**Comment by mirasrael** [comment] 2019-03-26 13:22
@Blanclour actually it shouldn't reset the law, because as you said it may be complex so you don't want to lose it. It seems it has some errors with law logic, so it just should be correctly processed and displayed. 
Is this error 100% reproducible? So can you repeat this law (which causes error), make a screen and post it here. Also the server save will be very useful.

**Comment by Blanclour** [comment] 2019-03-26 16:19
Sadly it was not reproducible when I tried making the law again, there were probably other factors at play that I am not aware of. I'm not the server owner so I do not have access to the save. Here is the law that I was trying to make:

TITLE Economics II: Income Tax USER Auron
LAW 
Every 1 days, for each player
If (your Wulongs > 5,000)
Then tax (your Wulongs % 16) Wulongs
Otherwise If (your Wulongs > 2,500)
Then tax (your Wulongs % 8) Wulongs
Otherwise If (your Wulongs > 1,000)
Then tax (your Wulongs % 4) Wulongs
Otherwise If (your Wulongs > 100)
Then tax (your Wulongs % 2) Wulongs
Otherwise tax 0 Wulongs

**Comment by mirasrael** [comment] 2019-03-27 12:05
Seems I found why it happens. Should be fixed in 8.2.

**Closed** 2019-03-27 16:48 UTC
Labels: Fixed, Medium Priority
