### ISSUE TITLE
Kiln Doesn't Like The Home I Made For It

### ISSUE THREAD

**Issue by PerksPrisoner** [StrangeLoopGames/EcoIssues#5723] opened 2018-03-08 22:31 UTC
Every restart the Kiln decides it doesn't like the home I have made for it that is 156m^3 made from Hewn Logs and Mortared Stone. I have to break it and replace it for it recognize its spacial requirements are met.

**Comment by Ekkelus** [comment] 2018-03-08 23:16
[](https://github.com/StrangeLoopGames/EcoIssues/issues/2876)

**Comment by MarjieAVolk** [comment] 2018-03-09 00:01
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2876

**Closed by MarjieAVolk** 2018-03-09 00:01 UTC
