### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by TheGoodBear** [StrangeLoopGames/EcoIssues#23111] opened 2022-04-28 17:43 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
Sort items in silo

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: DivideByZeroException
Message:Attempted to divide by zero.
Source:Eco.Gameplay

System.DivideByZeroException: Attempted to divide by zero.
   at Eco.Gameplay.Items.InventoryChangeSet.ConsolidateInventory(Inventory inventory, User user)
   at Eco.Gameplay.Components.LinkComponent.ConsolidateLinkedInventory(User user)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-05-02 11:34
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23102

**Closed by D3nnis3n** 2022-05-02 11:34 UTC
Labels: Type: Bug
