### ISSUE TITLE
USER ISSUE: Crash because of repair station

### ISSUE THREAD

**Issue by imdutch21** [StrangeLoopGames/EcoIssues#5047] opened 2018-02-24 17:51 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. open repair station
2. click repair with no items?

**Expected behavior:**
It should not  have crashed

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Repair on RepairComponent!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.Inventory.TryRemoveItems(ItemStack stack, User user)
   at Eco.Gameplay.Components.RepairComponent.Repair(Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

```

**Comment by MarjieAVolk** [comment] 2018-02-26 18:15
When you say no items, do you mean no repair materials, or no tool to repair?

**Comment by MarjieAVolk** [comment] 2018-02-26 18:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4358

**Closed by MarjieAVolk** 2018-02-26 18:16 UTC

**Comment by imdutch21** [comment] 2018-02-26 18:31
Oh sorry, I think someone left there empty hoe in there and there where no repair items
