### ISSUE TITLE
USER ISSUE: kp

### ISSUE THREAD

**Issue by freakfame55** [StrangeLoopGames/EcoIssues#5413] opened 2018-03-05 13:09 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
/authlevel

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Ein Aufrufziel hat einen Ausnahmefehler verursacht.
Der Wert darf nicht NULL sein.
Parametername: key


Stack:
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   bei Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

```

**Comment by MarjieAVolk** [comment] 2018-03-05 20:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4391

This seems to happen when you pass no arguments in to a command that requires arguments.  Try using /help for the command to see what arguments it requires.

**Closed by MarjieAVolk** 2018-03-05 20:29 UTC
