### ISSUE TITLE
USER ISSUE: Can't load world

### ISSUE THREAD

**Issue by fefiischii** [StrangeLoopGames/EcoIssues#6662] opened 2018-03-29 13:57 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. if i am in the main menu and try to load my single player world it won't open it.

**Expected behavior:**
It should havo loaded the game

**Actual behavior:**
Instead the loading time took forever

**Comment by MarjieAVolk** [comment] 2018-04-04 00:45
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6882

Unfortunately I don't have a solution for you right now :'(

**Closed by MarjieAVolk** 2018-04-04 00:45 UTC
