### ISSUE TITLE
Blocks are not properly connecting

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#3529] opened 2018-01-19 22:42 UTC
I think that not all blocks are behaving as expected, see attached screenshot

![image](https://user-images.githubusercontent.com/8785758/35175110-70d408c2-fd72-11e7-9239-a98cecdb9bf9.png)

**Comment by MarjieAVolk** [comment] 2018-01-19 22:50
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3502

**Closed by MarjieAVolk** 2018-01-19 22:50 UTC
Labels: Art
