### ISSUE TITLE
Plant temperatur range does not look right

### ISSUE THREAD

**Issue by Gemji1990** [StrangeLoopGames/EcoIssues#12075] opened 2019-04-20 15:52 UTC
Corn, Pumpkin and Rice optimum temperature range is outside of there max temperature range.

**Comment by beastyn** [comment] 2019-04-22 05:08
@Gemji1990 
Thank you for your report.
What do you mean outside the range?
Pumpkin has 0.38 as maximum for ideal range.
If ground will be 0.6 degrees then current match will be about 0.2 degrees above optimal.

**Comment by Gemji1990** [comment] 2019-04-22 06:32
yes and the extreme temperatur range for it are between 0.4-0.8 same with corn and rice.
this way this happens.
![pumpkin temperatur2](https://user-images.githubusercontent.com/12754908/56486774-2bfa1000-64d9-11e9-82f5-52b9b6270275.png)
![pumpkin temperatur1](https://user-images.githubusercontent.com/12754908/56486777-30262d80-64d9-11e9-9072-44cc5c229028.png)

**Comment by beastyn** [comment] 2019-04-22 11:42
@craig-jong @SeanAtr0n 
Look at this one. please.
Is this intended behaviour?

 this.IdealTemperatureRange = new Range(0.35f, 0.38f);
 this.TemperatureExtremes = new Range(0.4f, 0.8f);

**Comment by mirasrael** [comment] 2020-04-20 16:19
Should be fixed.

**Closed** 2020-04-21 10:38 UTC
Labels: Category: Balance, Priority: Medium, Status: Fixed
