### ISSUE TITLE
[Feature Request] Law to auto-unclaim if user has not logged in in <var> days

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7050] opened 2018-04-07 15:07 UTC
Because unclaiming them one square at a time can be quite tedious.

**Comment by Last2Night** [comment] 2018-04-07 15:26
What if the player informed the admins that he/she will be away longer then <var> days the law has set? The law will unclaim his/her property.

**Comment by ecoemmeck** [comment] 2018-04-07 15:49
related to #6972

**Comment by CuAnnan** [comment] 2018-04-07 17:54
I mean, sorta. I want it as a law. But even as an admin control in the HTML interface would be fine.

The admin tools are shockingly bad.

**Comment by Last2Night** [comment] 2018-04-07 17:56
@CuAnnan Admins abilities is a whole different story and Im 100% with you on that one.

**Comment by MarjieAVolk** [comment] 2018-04-09 20:36
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4549

**Closed by MarjieAVolk** 2018-04-09 20:36 UTC
Labels: Suggestion

**Comment by MarjieAVolk** [comment] 2018-04-09 20:40
Once we add in demographics to the law system (see https://github.com/StrangeLoopGames/EcoIssues/issues/7091 - basically a way to create a whitelist/blacklist using laws), it should also be possible to write exceptions into laws, to handle the case given where you want to allow someone to go on vacation and get an exception from the unclaim law.

Eg. your law might say 'Once per day, for each property plot, if Owner is not a Vacationer, Unclaim'

Of course, we still need to add several features in order for this to work.  But that is my vision.
