### ISSUE TITLE
Lumber Floor and Walls needs updated meshes due to broken face remover behavior.

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#4354] opened 2018-02-11 20:51 UTC
![image](https://user-images.githubusercontent.com/6262198/36078392-4e1929b0-0f2a-11e8-85f3-ad76e7fb574d.png)

**Comment by keegan-o** [comment] 2018-02-12 02:02
Ah yes, alas... it is not the meshes but the face remover code :( Shall have to find a different way for the meshes to be probably.

**Comment by keegan-o** [comment] 2018-02-13 21:48
It would be really nice if we could still find a way to match polygons rather than verts... I don't remember the status of where that got to or where it is exactly. But there is a tri there in the meshes that is obviously not actually matched by the one above it.

**Comment by metachronism** [comment] 2018-03-15 23:51
closing as dupe of #4286

**Closed by metachronism** 2018-03-15 23:51 UTC
Labels: Medium Priority
