### ISSUE TITLE
USER ISSUE: game crash due to picking up large piece of tree log.

### ISSUE THREAD

**Issue by drzendoom** [StrangeLoopGames/EcoIssues#4266] opened 2018-02-10 19:24 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
pick up a yellow piece of log (needs to be chopped up)

**Expected behavior:**
nothing

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by drzendoom** [comment] 2018-02-10 22:42
not that it happens every time, just happened this time.

**Comment by MarjieAVolk** [comment] 2018-02-13 00:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668 . You can track the progress of the issue there.

It seems this happens occasionally, especially with logs that have been sitting around when the game is reloaded.  Hopefully we will fix it soon.

**Closed by MarjieAVolk** 2018-02-13 00:25 UTC
