### ISSUE TITLE
Server crashes with "System.ArgumentException: Object of type 'LiteDB.ObjectId' cannot be converted to type 'System.String'."

### ISSUE THREAD

**Issue by rembomy** [StrangeLoopGames/EcoIssues#24833] opened 2024-03-18 10:45 UTC
Server crashes with following logs after restart, sometimes using restore recovers it, but next time server restarts it crashes again. Started happening after latest update. 

OS: Linux Ubuntu

[logs.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14634963/logs.txt)

**Comment by D3nnis3n** [comment] 2024-03-18 12:09
Please attach the save file and database.

**Comment by rembomy** [comment] 2024-03-18 13:25
Files are too big to upload here so I uploaded to OneDrive: https://1drv.ms/f/s!AojweHpoBzSBmOkdMC_QIRmmSRSUGw?e=VcqBd8

**Comment by D3nnis3n** [comment] 2024-03-21 16:29
I have tried multiple cycles of starting and stopping the server with this savegame and wasn't able to get the error.

Is there anything specific involved in getting it? Your mention of your config to "with this game actually saves and closes properly" sounds like the server was simply not shut down correctly and the database corrupted as a consequence - that is common for ungraceful shutdowns and a setup error, not a bug - though typically shows in different ways.

Could you maybe provide one of the broken saves, so we could look at that?

**Comment by rembomy** [comment] 2024-03-21 17:11
I do not have the broken save at the moment as I did overwrite the save from backup (those things are super btw!)
If it happens again I will provide one and I can open a new ticket if needed.

**Comment by D3nnis3n** [comment] 2024-03-27 21:26
Closing due to not reproducible and no broken save available.

**Closed by D3nnis3n** 2024-03-27 21:26 UTC
Labels: Status: Not reproduced
