### ISSUE TITLE
Unable to set prices in shop below 1. defaults to 0

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#9374] opened 2018-09-14 18:32 UTC
While attempting to set prices below 1 with any system e.g (0,5) and (0.5) they both reverts to 0 in the value slot. This is both for buying and selling prices. Copy pasting in the same values (0,5) and (0.5) will not preserve them either. 

Prices set by other people on this particular server are shown by this system: 0,05 - while view in a particular shop will show the prices listed as this system 0.05

Playing on a English server i presume, with English localization in the game. Norwegian keyboard setup in Windows 10.

**Comment by Knigge** [comment] 2018-09-14 18:36
Not sure how to mark this, but the issue is the same as this: https://github.com/StrangeLoopGames/EcoIssues/issues/9251

Where I can confirm that the workaround with holding CTRL while pressing adjust price will indeed set values below 1 and hold them. 

This still remains an important issue to ensure a fine tuned economy.

**Comment by D3nnis3n** [comment] 2018-09-15 22:47
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/9210

Use CTRL and click minus and plus buttons to change prices until this gets fixed.

**Comment by elfl0rd** [comment] 2018-12-05 18:19
@D3nnis3n fixed in https://github.com/StrangeLoopGames/Eco/pull/3595

**Comment by D3nnis3n** [comment] 2018-12-05 19:52
Indeed.

**Closed by D3nnis3n** 2018-12-05 19:52 UTC
Labels: Medium Priority
