### ISSUE TITLE
USER ISSUE: Corrugated steel transparency penetrates further than most radiation

### ISSUE THREAD

**Issue by klintworthde** [StrangeLoopGames/EcoIssues#4709] opened 2018-02-17 14:46 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Lay reinforced concrete block, plain cube
2. Lay detail-edged corrugated steel block next to it
3. Admire your one-way concrete mirror

**Expected behavior:**
Displayed reinforced concrete through the edges of the corrugated steel block

**Actual behavior:**
Displayed path beyond concrete block

![20180217094331_1](https://user-images.githubusercontent.com/8662864/36342112-628525a6-13c7-11e8-9183-b745844d2dc0.jpg)

**Comment by metachronism** [comment] 2018-03-16 18:34
closing as dupe of face remover bug

**Closed by metachronism** 2018-03-16 18:34 UTC
Labels: Medium Priority
