### ISSUE TITLE
USER ISSUE: picking up tree logs

### ISSUE THREAD

**Issue by Allax82** [StrangeLoopGames/EcoIssues#4633] opened 2018-02-16 10:11 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Tree logs left from a previous session, all chopped and ready to be picked up.

**Expected behavior:**
It should have taken the tree bits as normal, (carrying)

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Thasd=

**Comment by Reelzerz** [comment] 2018-02-16 22:13
Yea I've got this too. And then my friend tried to pick it up and then it happened to him.

**Comment by MarjieAVolk** [comment] 2018-02-17 00:35
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-17 00:35 UTC
