### ISSUE TITLE
USER ISSUE: fell through the world

### ISSUE THREAD

**Issue by Reijm11** [StrangeLoopGames/EcoIssues#3995] opened 2018-02-06 21:08 UTC
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
see title	

**Expected behavior:**
not let me fall through the world	

**Actual behavior:**
let me fall through the world

**Comment by MarjieAVolk** [comment] 2018-02-20 22:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861

**Closed by MarjieAVolk** 2018-02-20 22:05 UTC
Labels: Medium Priority
