### ISSUE TITLE
PC Crash on Entering World

### ISSUE THREAD

**Issue by KolyaEP** [StrangeLoopGames/EcoIssues#11346] opened 2019-02-15 23:47 UTC
I try entering any server (public or private) and my PC crashes completely and reboots. The moment at which the PC crashes is pretty inconsistent. Usually it occurs while the loading pop-up is still doing its thing. Sometimes it happens when I can actually see my character in-game, but it crashes immediately after.

This started happening a couple of updates before 8.0, so I don't think it has anything to do with the 8.0 release. 

This also doesn't happen with any other games. I can play for hours on end with no crashes or anything, but for some reason with Eco, it always happens.

PC Specs:
Operating System: Windows 10 Pro N 64-bit (10.0, Build 16299) (16299.rs3_release_svc.180808-1748)
System Manufacturer: MSI
System Model: MS-7693
Processor: AMD FX(tm)-8350 Eight-Core Processor            (8 CPUs), ~4.0GHz
Memory: 16384MB RAM
Available OS Memory: 16332MB RAM
Card name: NVIDIA GeForce GTX 970
Manufacturer: NVIDIA
Chip type: GeForce GTX 970
DAC type: Integrated RAMDAC
Device Type: Full Device
Display Memory: 12209 MB
Dedicated Memory: 4043 MB
Shared Memory: 8166 MB

**Comment by redwyre** [comment] 2019-02-16 00:01
Do you get a bluescreen or does your computer simply restart?
First thing to try would be a memory test: https://www.windowscentral.com/how-check-your-pc-memory-problems-windows-10 which will probably take a while so best to run it overnight

**Comment by KolyaEP** [comment] 2019-02-16 00:03
**> Do you get a bluescreen or does your computer simply restart?** 
Nope, screen goes black and PC reboots immediately. 

**First thing to try would be a memory test: https://www.windowscentral.com/how-check-your-pc-memory-problems-windows-10 which will probably take a while so best to run it overnight**
Will try this.

**Comment by Secretname2009** [comment] 2019-02-16 11:21
Im having this problem aswell, the game randomly makes the entire PC crash and reboot but i got some information that might help with this. 
Ive had 2 crashes and both of them was caused by the driver named dxgmms2.sys, that file is a part of DirectX.
First crash happened due to the driver trying to access a invalid instruction and the second one was caused by the driver trying to execute a illegal instruction.
I found out all this by myself and using Windows debugger on the dumps.

**Comment by KolyaEP** [comment] 2019-02-16 22:28
I'm glad to see I'm not the only one this is happening too. But sad that it's happening at all :(.
I ran the memory test and no errors turned up. So it doesn't seem to be a memory issue.
Maybe the info @Secretname2009 provided might help out.

**Comment by Secretname2009** [comment] 2019-02-16 23:00
It is indeed quite sad that this is happening at all but atleast i could provide some information to help with fixing this problem. Although it is uncommon this problem happends to me, only a few crashes has happened within a playthrough of 3 sessions with this.
I did find out that the dxgmms2.sys is more related to DirectX Graphics MMS but i dont know what that means.
Im tech savvy enough to understand what happened when it crashed but i dont quite know what this file does specifically, "DirectX Graphics MMS" was in the description of the file itself but i dont know anymore than that.

**Comment by Secretname2009** [comment] 2019-02-16 23:00
It is indeed quite sad that this is happening at all but atleast i could provide some information to help with fixing this problem. Although it is uncommon this problem happends to me, only a few crashes has happened within a playthrough of 3 sessions with this.
I did find out that the dxgmms2.sys is more related to DirectX Graphics MMS but i dont know what that means.
Im tech savvy enough to understand what happened when it crashed but i dont quite know what this file does specifically, "DirectX Graphics MMS" was in the description of the file itself but i dont know anymore than that.

**Comment by redwyre** [comment] 2019-02-17 10:21
Can you guys make sure you have the latest drivers? You can find links at https://github.com/StrangeLoopGames/EcoIssues/wiki/Update-video-drivers

Basically it shouldn't be possible for Eco itself to be crashing your entire PC, but it could be doing something that causes a driver to behave badly, or trigger a hardware problem.

If updating video card drivers doesn't help, you can try running driver verifier to figure out what driver is causing issues, though it's a bit complicate: https://answers.microsoft.com/en-us/windows/forum/windows_10-update/driver-verifier-tracking-down-a-mis-behaving/f5cb4faf-556b-4b6d-95b3-c48669e4c983

**Comment by redwyre** [comment] 2019-04-05 19:49
Hi @KolyaEP and @Secretname2009, we have release 8.1 which has a number of performance improvements, could you try it out and report back?

**Comment by redwyre** [comment] 2019-04-18 01:26
No response, and other people have reported improvements in this area

**Comment by Secretname2009** [comment] 2019-04-28 10:51
Sorry for being inactive, i was quite busy lately but i can now respond to this issue.
Right now im using the latest version of Eco which at the time is 0.8.1.4 and the few times i have started it now ive had about 3 crashes where one of them was fatal and crashed the entire PC.
Should i create a New issue or should i post the information ive got here?

**Comment by beastyn** [comment] 2019-04-28 14:44
@Secretname2009 
I've reopened issue for you. Please provide any information, it will be really helpful, thank you.

**Comment by Secretname2009** [comment] 2019-04-28 15:27
Thanks @beastyn but after i have updated the driver for the Graphics card it doesnt seem to have a issue anymore. It didnt do anything in an hour of play when it usually would crash within 10 minutes with the old driver. Due to this i think this issue is gone for good now.

**Comment by KolyaEP** [comment] 2019-04-28 15:39
Sorry for my inactivity! I have tried playing after updating both the game and my drivers, but it still crashes even before loading the world. Could it be a network issue?

**Comment by beastyn** [comment] 2019-04-28 15:56
@Secretname2009 I'mg glad that your situation was solved )
@KolyaEP Thank you for your attention. Can you provide logs for us? Server and client.
Here is an instruction how to get them  https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files

**Comment by KolyaEP** [comment] 2019-04-28 16:57
Here's the latest Server and Client logs I could find. The Server log is from February, since my PC crashes completely, I think that sometimes the logs don't get created. 

Let me know if you guys need anything else! 

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3125206/output_log.txt)
[log_190217041101.log](https://github.com/StrangeLoopGames/EcoIssues/files/3125204/log_190217041101.log)

**Comment by redwyre** [comment] 2019-11-13 03:56
@KolyaEP is it still an issue for you?

**Comment by KolyaEP** [comment] 2019-11-13 07:06
Unfortunately, yes. I hadn't tried playing it since I last posted in April. The other day I decided to clean my PC both physically and "virtually". I gave it a go, and I was able to play for like 30 minutes. But after 30 minutes or so, the PC just rebooted out of nowhere. I've played several other games with no issues whatsoever; even games like Minecraft which are notoriously demanding. 

I'm not sure what the problem could be :/.

**Comment by mirasrael** [comment] 2019-11-13 07:11
@KolyaEP did you try to run memory test and other system checks on your PC? Eco may use pretty large amount of memory so it may be a reason why it crashes while other games don't.

**Comment by redwyre** [comment] 2020-01-23 01:35
Moving to backlog as this is more of a player setup issue.

**Comment by beastyn** [comment] 2020-05-25 06:52
Due no response I will close it.
Also, in 9.0 we will have some improvements. 
@KolyaEP please write here if you have any updates, thank you

**Closed by beastyn** 2020-05-25 06:52 UTC
Labels: Status: Needs Information
