### ISSUE TITLE
[0.8.2.0 staging-14-n] Useless talent "Frugal Workspace"

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12408] opened 2019-05-24 13:48 UTC
In my opinion, between the two talents of Frugal Workspace and Lavish Workspace, the choice is obvious. Anyone will choose Lavish Workspace. With very few exceptions. It is worth reworking this talent.
Also for some specialty which does't have any related tables It's useless at all:  Bricklaying, Glassworking, Paper Milling, Advanced Baking, Advanced Campfire Cooking (related table is campfire), Oil Drilling (related tables is are oil refinery and pump jack), Farming.

**Comment by elfl0rd** [comment] 2019-12-09 17:52
I'd rather have the ability to change talents.
Frugal is usefull for beginners, lavish is usefull for professionals and experienced.

**Comment by IcedForge** [comment] 2021-10-13 05:06
Will close this in favor of a talent / skill overhaul planned as we intend to scrap frugal/lavish talents into more dynamic and flavorful selections so while they still remain an issue until that point they do function as intended at this time.

**Closed by IcedForge** 2021-10-13 05:06 UTC
Labels: Priority: High, Type: Feature, Category: Balance, Squad: Redwood
