### ISSUE TITLE
USER ISSUE: Connection Failure

### ISSUE THREAD

**Issue by TsukikoFawkes** [StrangeLoopGames/EcoIssues#4063] opened 2018-02-07 20:59 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
Run EcoServer.exe
Run Eco.exe
Click Join on main menu
Double click local server

**Expected behavior:**
Joined the server

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-02-07 22:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4056

We have been getting many reports of connection problems; we are working to resolve these as quickly as we can.  Hopefully it will be hotfixed today.

**Closed by MarjieAVolk** 2018-02-07 22:16 UTC
