### ISSUE TITLE
Plants disappears when cross world border

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22152] opened 2021-06-07 19:24 UTC
https://github.com/StrangeLoopGames/Eco/pull/8719

**Comment by Daniel-Magulado** [comment] 2021-06-07 19:57
Duplicate of #21698, I believe.

**Comment by SlayksWood** [comment] 2021-06-08 06:54
yeah it's a dup, closed.

**Closed** 2021-07-17 01:48 UTC
Labels: Category: Tech, Squad: Pumpkin, Type: Bug
