### ISSUE TITLE
Deadzone in log placement

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8090] opened 2018-06-18 22:59 UTC
![animx](https://user-images.githubusercontent.com/3536496/41566474-7c1c20e8-7310-11e8-8ad4-8fe5540124ad.gif)

**Comment by Nanders** [comment] 2018-06-19 00:01
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6070

**Closed by Nanders** 2018-06-19 00:01 UTC
Labels: Medium Priority
