### ISSUE TITLE
USER ISSUE: CriminiMushroom

### ISSUE THREAD

**Issue by alexyouki** [StrangeLoopGames/EcoIssues#7093] opened 2018-04-09 16:59 UTC
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
je n est aucun dans ma maps 

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-04-09 17:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Closed by MarjieAVolk** 2018-04-09 17:12 UTC
