### ISSUE TITLE
USER ISSUE: SSL Probleme seit letztem Update 9.7.3 nach Benutzung Microsoft Outlook

### ISSUE THREAD

**Issue by Seppel307** [StrangeLoopGames/EcoIssues#23617] opened 2022-12-09 07:26 UTC
\
**User Id: (slg173685)**
**Version:** 0.9.7.3 beta release-391

**Steps to Reproduce:**
Ich starte mein Microsoft Outlook. Danach starte ich das Spiel. Beim laden des Servers (Offline/Local) bricht er das Laden mit der Fehlermeldung "]The Server crashed with error 'App authentication failed: The SSL connection could not be established, see inner exception.' and you cant't play. Check logs in 'ECO_Data\Server\Logs' for more information.[". Behebung nur durch neustart des Computers, danach läuft der Server wieder. Mit Version 9.6.x konnte Microsoft Office parallel im Hintergrund laufen.

**Expected behavior:**

**Actual behavior:**
Kann kein Server laden.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Am Anfang hatte ich Worldedit installiert. Selbes Problem auch ohne Mod.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Seppel307** [comment] 2022-12-09 07:30
Log-File:
[07:52:36.136] [6] [Error] [Eco] ]Failed to start the server. Exception was Exception: ApplicationException
Message:App authentication failed: The SSL connection could not be established, see inner exception.
Source:Eco.Shared

System.ApplicationException: App authentication failed: The SSL connection could not be established, see inner exception.
   at Eco.Shared.Authentication.AppAuthentication.Authenticate(IEnumerable`1 authenticators)
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)[
 
[07:52:36.169] [6] [ Info] [Eco] ]Shutdown finished[

**Comment by D3nnis3n** [comment] 2022-12-09 11:59
I'm unfortunately unable to reproduce this, Outlook and Eco server work fine for me.
This does rather look like some local problem.

**Comment by D3nnis3n** [comment] 2023-01-01 15:41
Closing this due to not being reproducable.

**Closed by D3nnis3n** 2023-01-01 15:41 UTC
Labels: Status: Not reproduced

**Comment by Seppel307** [comment] 2023-01-02 18:11
Danke, das Problem lag an der Portfreigabe für https in der Firewall.
