### ISSUE TITLE
USER ISSUE: Stuck at Entering World screen

### ISSUE THREAD

**Issue by Kitoka** [StrangeLoopGames/EcoIssues#6926] opened 2018-04-03 16:07 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Try connect to our server (.PANDORA.......)

(several of our server players have this issue atm, we contacted server admins and they told us to contact game devs, and we will have to wait for the 1.5h  reboot  of our server)

**Expected behavior:**
Connected to our server and load game world.

**Actual behavior:**
Stays stuck at entering world screen.

**Comment by MarjieAVolk** [comment] 2018-04-03 18:01
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6882

**Closed by MarjieAVolk** 2018-04-03 18:01 UTC
