### ISSUE TITLE
Fast load not working

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19827] opened 2020-12-22 23:45 UTC
![image](https://user-images.githubusercontent.com/3536496/102943374-a75d5300-446c-11eb-8c5f-982f1286f6fc.png)
It used to use a default renderer for the landscape, so you could still see it. Consult @mirasrael

**Comment by WeaselDog** [comment] 2021-01-06 08:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19686

**Closed by WeaselDog** 2021-01-06 08:22 UTC
Labels: Category: Tech, Priority: Medium
