### ISSUE TITLE
USER ISSUE: Sleeping getting stuck

### ISSUE THREAD

**Issue by Anurian** [StrangeLoopGames/EcoIssues#17623] opened 2020-08-08 15:11 UTC
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
First time me and the person i play with slept at the same time. She didnt see the "Real time skip: 2 hour. Stop sleeping" window and i couldnt click it away. And for some reason it stopped again after about 20 sec (window was still there > relogged)
Then i tried it while i was alone and then same thing happened again but this time i couldnt even stop it so had to relog again because time kept skipping.
And after that i couldnt load the world anymore so had to restart the whole game because after loading, it just didnt load (got stuck in the loading background)

**Expected behavior:**
Should be able to sleep and stop it manually.

**Actual behavior:**
Kept sleeping/bugged window/had to restart whole game to load world again

**Do you have mods installed? Does issue happen when no mods are installed?:**
Kept sleeping/bugged window/had to restart whole game to load world again

**Comment by Daniel-Magulado** [comment] 2021-03-13 15:32
Hi @Anurian, you haven't replied for almost 7 months now.
We also couldn't reproduce and haven't encountered this issue during the said time frame.
We're closing the ticket for now. Feel free to reopen if you encountered the same issue again.
Thank you.

**Closed by Daniel-Magulado** 2021-03-13 15:32 UTC
Labels: Status: Investigate
