### ISSUE TITLE
Crash in Game "eco unity 20194 9f1 50fe8a171dd9"

### ISSUE THREAD

**Issue by dobscry** [StrangeLoopGames/EcoIssues#18492] opened 2020-09-27 11:41 UTC
Hi everybody,

I played since 10 days, and i had perma crashed in game.
a little window at the middle appear less than 1s and it's written "eco unity 20194 9f1 50fe8a171dd9"
I had a good computer (AMD R9 280, core i7 4790 3.6Ghz, 16G RAM ...), i don't understand why all this crash...
I'm on windows 10
My friends never crashed on the server.
I try to install the last version of Java, and allow 4096Ms in. Doesn't work...

Thank you for your help

**Comment by D3nnis3n** [comment] 2020-09-27 15:22
Hello,
please provide your log files when after having this crash the next time:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by dobscry** [comment] 2020-09-27 17:04
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5288706/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5288707/Player-prev.log)

this is it :) 

thanks

**Comment by redwyre** [comment] 2020-09-27 19:02
Duplicate of #18403

**Closed by redwyre** 2020-09-27 19:02 UTC

**Comment by redwyre** [comment] 2020-09-27 19:05
Also can you make sure you have the latest graphics drivers?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Update-video-drivers

**Comment by dobscry** [comment] 2020-09-27 19:38
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5288925/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5288926/Player-prev.log)
i do hte update in case but it still crashing

**Comment by redwyre** [comment] 2020-09-27 20:02
Can you open task manager, switch to the "performance" tab and select "GPU 0" and run the game, then when it crashes take a screenshot of task manager?

**Comment by dobscry** [comment] 2020-09-27 20:35
![Sans titre2](https://user-images.githubusercontent.com/71969951/94375105-81484100-0111-11eb-9df1-f51544b18691.png)
![Sans titre](https://user-images.githubusercontent.com/71969951/94375106-81e0d780-0111-11eb-9755-b868eeb00af7.png)

when the crash happen, the GPU go from 60% to 100%

**Comment by redwyre** [comment] 2020-09-27 20:43
Oh, can you do it for GPU 1? Is this a laptop?

**Comment by dobscry** [comment] 2020-09-27 20:50
no its not a laptop
![Sans titre](https://user-images.githubusercontent.com/71969951/94375436-e2711400-0113-11eb-9ea3-aef33a44770f.png)

**Comment by redwyre** [comment] 2020-09-27 20:52
Ok thanks, definitely looks like the same issue.

**Comment by dobscry** [comment] 2020-09-28 08:16
ok but where do i do that : 
The solution would be to enable texture streaming on more textures to allow them to get removed or downgraded when running low on memory. Some candidates are:

Ecopedia textures, they're not needed all the time
world object textures, especially for rarer objects
rare block textures

Cause i already play in so poor quality...
