### ISSUE TITLE
Some Resources not loaing on Linux

### ISSUE THREAD

**Issue by QuietTR55** [StrangeLoopGames/EcoIssues#24810] opened 2024-03-05 13:52 UTC
It doesn't render planted tomatoes for some reason, I see the outline sometimes and it says tomatoes on top but the mesh doesn't render. Also portraits or images won't load. It just shows white/blank canvas

**Comment by D3nnis3n** [comment] 2024-03-05 14:24
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18422

**Closed by D3nnis3n** 2024-03-05 14:24 UTC
