### ISSUE TITLE
Rubble, logs, and debris get stuck in the stockpile

### ISSUE THREAD

**Issue by Hanan09** [StrangeLoopGames/EcoIssues#2893] opened 2017-11-24 02:58 UTC
is there a way to prevent them to stuck on stockpiles  since they are also causing game issues too  or to  be able to pick them up

**Comment by MarjieAVolk** [comment] 2017-11-24 18:12
Sounds like a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1919

What 'game issues' are they causing?

**Closed by MarjieAVolk** 2017-11-24 18:12 UTC
