### ISSUE TITLE
USER ISSUE: Skid steer not emptying

### ISSUE THREAD

**Issue by FlamingDemon** [StrangeLoopGames/EcoIssues#8321] opened 2018-07-04 12:20 UTC
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
1. dig with the skid steer
2. try to empty in container (stockpile or truck)

**Expected behavior:**
it should have dumped the items from it's inventory into the stockpile or truck

**Actual behavior:**
only fuel can be given to vehicles, not other items to trucks or stockpiles

**Comment by GophTheGreat** [comment] 2019-05-24 05:07
Cannot reproduce -- skidsteer was able to deliver both stone and fuel to a truck. Closing.

**Closed by GophTheGreat** 2019-05-24 05:07 UTC
Labels: Medium Priority
