### ISSUE TITLE
USER ISSUE: Any bow doesn't shoot [0.10.0.0 beta release-532]

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#24204] opened 2023-12-14 19:59 UTC
\
**User Id: (slg87516)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Craft any bow and arrow at a workbench.
Pick up a bow
Find a target, aim and shoot.

**Expected behavior:**
When aiming, it should show the flight path of the arrow. After the shot, the arrow must fly away according to its flight path; when it hits the target, the arrow causes damage to the target (animal).

**Actual behavior:**
When you try to shoot from ANY bow, the shot does not fire. The string on the bow is not stretched, the flight path of the arrow is not shown, after the shot the arrow does not fly away (in the general package (stack) of arrows it is deducted (considered used)), accordingly, nothing hits the target and no damage is caused to the target. It's as if the arrow is a phantom.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. I play on a clean client.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Rambo99** [comment] 2023-12-14 20:06
Log file.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13677766/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13677767/Player-prev.log)

**Comment by TwixterZ** [comment] 2023-12-14 20:07
Hi @Rambo99 Thank you for your report, this issue is known currently, and possible fix will be made by our developer for future patch.

**Comment by Rambo99** [comment] 2023-12-14 20:14
Thank you, of course, for the answer. But unfortunately, this bug blocks character development in the game due to the fact that, due to this bug, it is impossible to obtain more than 60 percent of knowledge books (technologies) on the research table since it is impossible to raise the level of the hunting skill because of this bug, and on this skill obsessive about getting almost all the culinary knowledge sheets (sheets with a picture of a plate). So I would like to get a fix for this problem as soon as possible. Thank you.

**Comment by D3nnis3n** [comment] 2023-12-16 22:27
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24133

**Closed by D3nnis3n** 2023-12-16 22:27 UTC
