### ISSUE TITLE
USER ISSUE: Logging back in after internet death

### ISSUE THREAD

**Issue by ewoudje** [StrangeLoopGames/EcoIssues#6375] opened 2018-03-22 18:05 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
disconnect with bad internet
connect back
= Crash

**Expected behavior:**
Do not crash

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Value cannot be null.
Parameter name: item


Stack:
  at System.Collections.Immutable.Requires.FailArgumentNullException (System.String parameterName) [0x00000] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at System.Collections.Immutable.Requires.NotNullAllowStructs[T] (T value, System.String parameterName) [0x00008] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at System.Collections.Immutable.ImmutableHashSet`1[T].Contains (T item) [0x00000] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at Eco.Core.Utils.ThreadSafeHashSet`1[T].Contains (T item) [0x00000] in <57b00a8def6b4559a7ceaa9c2e6ba89d>:0 
  at Eco.Core.Controller.ControllerInstanceInfo.TryBind (Eco.Shared.Networking.INetClient client) [0x00006] in <57b00a8def6b4559a7ceaa9c2e6ba89d>:0 
  at Eco.Core.Controller.ControllerManager.TryBindController (Eco.Core.Controller.IController controller, Eco.Shared.Networking.INetClient boundClient) [0x00054] in <57b00a8def6b4559a7ceaa9c2e6ba89d>:0 
  at Eco.Core.Controller.ControllerManager.PackageController (Eco.Core.Controller.IController controller, Eco.Shared.Networking.INetClient boundClient) [0x00000] in <57b00a8def6b4559a7ceaa9c2e6ba89d>:0 
  at Eco.Gameplay.Objects.WorldObject.SendInitialState (Eco.Shared.Serialization.BSONObject bsonObj, Eco.Shared.Networking.INetObjectViewer viewer) [0x0000d] in <dd6dbb80e71f447883c04f17e49a70ba>:0 
  at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates (System.Collections.Generic.IEnumerable`1[T] newObjects, Eco.Shared.Networking.INetObjectViewer viewer, System.Collections.Generic.ICollection`1[T] monitored) [0x00032] in <83fac361379c404ab41cd5885dc7c72f>:0 
  at Eco.Plugins.Networking.Clients.Client.Update (System.Diagnostics.Stopwatch timer) [0x000b9] in <fd26a1b8615e48f4944afa645abd3cd0>:0 
  at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1 () [0x00012] in <fd26a1b8615e48f4944afa645abd3cd0>:0 
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-22 18:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5804

**Closed by MarjieAVolk** 2018-03-22 18:11 UTC
