### ISSUE TITLE
USER ISSUE: Void zone under a road

### ISSUE THREAD

**Issue by valkner** [StrangeLoopGames/EcoIssues#5100] opened 2018-02-25 22:27 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
made a stone road, went to remove it later and beneath it was a portal to the void.

**Expected behavior:**
fewer portals to the void

**Actual behavior:**
access to forbidden truths

**Comment by MarjieAVolk** [comment] 2018-02-26 19:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3897

But you win the best bug of the week award :P

**Closed by MarjieAVolk** 2018-02-26 19:53 UTC
