### ISSUE TITLE
USER ISSUE: Placing dirt be like bye bye

### ISSUE THREAD

**Issue by gabgoss** [StrangeLoopGames/EcoIssues#20364] opened 2021-02-04 22:32 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. 2 blocks high
2. have a dirt mound below
3. try to dump dirt halfway over the dirt mound below and flat ground next to itXXXXXXX3XXXX23X

**Expected behavior:**
It should have place dirt either on top of existing mound or next to it.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Shared

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.NetObjectManager.GetObjectUpdates(IEnumerable`1 objects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2021-02-05 16:50
Hi @gabgoss, thank you for making a report about this. However, we are unable to reproduce the issue. Could you provide more information about this, please? A video recording of the issue and sending us the game log files when the issue occurred will greatly help us investigate the issue further.

To provide log files, kindly follow the instruction here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment] 2021-02-18 09:01
Closing this in lack of reply please reopen if this is still a problem.

**Closed by IcedForge** 2021-02-18 09:01 UTC
Labels: Status: Needs Information
