### ISSUE TITLE
[0.9.3.1] Property transfer "ignore auth" clause not working

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21564] opened 2021-04-24 21:59 UTC
Recently we introduced some manual abandoned property reclamation law on White Tiger:

http://gs1.play.eco:3031/elections.html?election=37

![image](https://user-images.githubusercontent.com/964559/115973908-54280980-a50d-11eb-9f25-b2a925e2913a.png)

However, it seems the law did nothing - I was unable to edit or delete Abandoned properties:

https://youtu.be/4y3ElKieheE

I would expect the gear for transfering the properties to work with that law in place.

**Comment by Daniel-Magulado** [comment] 2021-04-25 13:58
Hi, thank you for making a report about this.
However, the clause 'Ignore Authentication' only works when the Property Transfer has been made and only at that moment. For example, Trigger is Dig, IF is Yes, and Then is Ignore Auth. In this case, I will be able to Dig in every property regardless if I have access to it or not but I cannot drop the dirt I dug in properties owned by other players.

On your provided video, it looks like Evil Wish still owns the property even after entering the Abandoned Demographic. 

In your given scenario, how I understand it is that you are trying to claim properties of abandoned players that have no On Vacation state or Utility accounts. I recommend using Demographic Change as the Trigger instead and then using Change Property Owner as the **THEN**.

**Comment by ThePiachu** [comment] 2021-04-26 21:21
> In your given scenario, how I understand it is that you are trying to claim properties of abandoned players that have no On Vacation state or Utility accounts. I recommend using Demographic Change as the Trigger instead and then using Change Property Owner as the THEN.

Yes, that's what we ended up using in the end. However, one player was making a fuss that they didn't want automatic transfers, instead of wanting to have manual only, so we would have to have some way of initiating the transfer. It was mostly due to wanting to handle Capital properties separately from everywhere else and so on.

So how would one use the clause to Ignore Auth on Property Transfer if you can't even do Property Transfer if you're not authorised? Seems like that part of the civic might be a Catch 22.

**Comment by Daniel-Magulado** [comment] 2021-04-27 02:28
Hi @ThePiachu,

In that case, maybe this would work for you.
Set Trigger as Claim or Unclaim Property. Then set IF to Unclaiming. Finally, set THEN to Ignore Auth.
This law will allow you to manually remove the deeds of claimed properties from abandoned players.

https://user-images.githubusercontent.com/77248866/116175560-23311a00-a743-11eb-879e-b13ab803d36b.mp4

Furthermore, you will also get Land Claim Papers to reclaim the properties after unclaiming them.

Let me know if this helps you.

**Comment by ThePiachu** [comment] 2021-04-27 21:32
Normally everything you describe makes sense, but we are talking about White Tiger. One of the edge cases is the Capital. We have a GM law that says nobody can unclaim land in the Capital not to mess things up. We had issues in the past where two claims next to one another were reclaimed and merged, but I think that would be addressed in 9.3.

So we have a claim that cannot be unclaimed, that has to be transferred from an abandoned person to someone if it's in the Capital, and somewhere else if it's not. Someone demanded those transfers would be done manually not to mess up the properties.

I know it's a really really specific edge case, sorry about that.

**Comment by Daniel-Magulado** [comment] 2021-05-01 20:41
Hi, thank you for getting back to my message.
We understand the situation.
However, I'll be closing this issue as the condition set to ignore auth is working as intended.

**Closed by Daniel-Magulado** 2021-05-01 20:41 UTC
Labels: Status: Needs Information
