### ISSUE TITLE
USER ISSUE: Item info bubble blocking transfers

### ISSUE THREAD

**Issue by johntanguysonos** [StrangeLoopGames/EcoIssues#9253] opened 2018-09-08 01:46 UTC
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
Open any linked inventory
Hover over any item in first inventory
Drag and drop to alt inventory
Observe info bubble for first item often blocks transfer tiles below & to opposite side of original tile.

**Expected behavior:**
Info bubble should not appear after initial click	

**Actual behavior:**
Info bubble blocks tile you're transfering to

**Comment by TheeJudge** [comment] 2018-09-08 12:36
The 7.7.1 update said that it fixed this. I encountered a difference when I first logged on after the update. However, a lot of people who play on my server were still having issues with tooltips hanging. Now a day later I have also begun to have this issue again with this particular login.

**Comment by elfl0rd** [comment] 2018-09-08 17:14
https://github.com/StrangeLoopGames/EcoIssues/issues/9132 (old one)

**Comment by OsageSparky** [comment] 2018-09-09 18:36
I believe a simple on mouse move event should destruct tooltip dialog.

**Comment by Senlarus** [comment] 2018-09-10 02:33
Agreed, this is still occurring and is still an issue.

**Comment by MarjieAVolk** [comment] 2018-09-10 18:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9132

**Closed by MarjieAVolk** 2018-09-10 18:16 UTC
Labels: Investigate

**Comment by johntanguysonos** [comment] 2018-09-10 18:27
This was happening for everyone on the server I was speaking with and is 100% reproducible. I'm not sure if by the issue being off an on as in it's a recurring problem with some updates or if you meant it's happening inconsistently. For us, it's happening every time we go to move things between inventories. Simply hover over an item in any linked inventories and then attempt to move it. I'll try to get the output_log the next time I log on.

**Comment by MarjieAVolk** [comment] 2018-09-10 18:55
Well @TheeJudge says they stopped seeing it for a while and then saw it again later.  I had another person on a different bug also saying it was off and on.  I haven't been able to reproduce it here since I sent in the fix (which went out in 0.7.7.1).  So if you happen to have an output log from a session where this happened, it might be useful.

**Comment by OsageSparky** [comment] 2018-09-10 21:13
I Just started playing the game 2 days ago, I can tell you it's happening
every time I try to use a stockpile inventory.  IM on beta server.

**Comment by MarjieAVolk** [comment] 2018-09-10 21:16
FYI I think I've got a fix now: https://github.com/StrangeLoopGames/Eco/pull/3367
