### ISSUE TITLE
7.2.0 Staging 08551408 .exe stopped responding. Dump attached.

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#4916] opened 2018-02-21 23:13 UTC
[Crash KeyNotFoundException 02210114.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1746055/Crash.KeyNotFoundException.02210114.txt)

**Comment by MarjieAVolk** [comment] 2018-02-22 22:49
```
Exception
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Plugins.Networking.QuadTree`1.Remove(T item)
   at Eco.Plugins.Networking.QuadTreeNetObjectCollection.OnObjectMoved(INetObjectPosition obj)
   at Eco.Simulation.Agents.Animal.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

```

**Comment by MarjieAVolk** [comment] 2018-02-22 22:51
May be related to https://github.com/StrangeLoopGames/EcoIssues/issues/4951

**Comment by Nashable** [comment] 2018-02-26 00:46
Been getting this pretty regularly on my own headless dedicated server as well (small community of 6 players)

Seems to come in waves. I've attached an entire zip of the past 24 hours of crashes.

[Crash KeyNotFoundException 02253851.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1756902/Crash.KeyNotFoundException.02253851.zip)

**Comment by SeanAtr0n** [comment] 2018-02-26 19:03
Also saw this for Trees

**Comment by MarjieAVolk** [comment] 2018-02-26 19:57
https://github.com/StrangeLoopGames/EcoIssues/issues/5075 - Those people think it can be related to fish traps.

**Comment by MarjieAVolk** [comment] 2018-02-26 19:58
From https://github.com/StrangeLoopGames/EcoIssues/issues/5118 (@meonester):
Version: Staging Beta 7.2.0 #08551408
I believe I've manage to pinpoint bug causing server crash.
It happens couple times a day on random basis.
I guess it's caused by Animals "dying" in player observable world (Visible == true).

```
// class Eco.Simulation.Agents.Animal ->
public override void Tick()
{
	if (base.Dead)
	{
		this.Destroy(); //<-- Removes object from NetManager dictionary
	}
	if (this.Visible)
	{
                //...
		NetObjectManager.OnObjectMoved(this); //<-- Trying to reinsert(remove+add) removed object -> throwing exception -> crashing server
                //...
	}
	else
	//...
}
```
I hope you can confirm my theory, if it happens to be true fix should be trivial.

**Comment by Nashable** [comment] 2018-02-26 22:02
New to Eco so not sure what the team’s philosophy on staging builds is currently. Does staging getting multiple deploys before the move to stable and if so Would a fix for this be deployed on staging branch? (Of course if/when it would be ready?)

Anything we can do to provide additional info?

**Comment by MarjieAVolk** [comment] 2018-02-26 23:28
Yes, staging usually gets several revisions before being released as the official version.  When this is fixed, the fix will be available on staging first.  But I can't really give you an estimate for when that will be in this case.  We've got a lot of important bugs we're juggling.

**Comment by Nashable** [comment] 2018-02-27 03:05
@MarjieAVolk thanks for the response and the awesome game. No expectation of timing I just wanted to understand how you folks worked as I'm new to the community.

Let me know if there is anything else we can provide in terms of info or testing.

**Comment by metachronism** [comment] 2018-03-05 20:23
fixed

**Closed by metachronism** 2018-03-05 20:23 UTC
Labels: High Priority
