### ISSUE TITLE
[0.9.0.0 beta staging 3] Server encountered an exception

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17160] opened 2020-07-17 22:44 UTC
Was cutting wood when I got ejected from the server. I was able to cut wood before without issue.

My girlfriend didn't got ejected.

[serverror.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4940635/serverror.txt)

**Comment by SlayksWood** [comment] 2020-07-20 10:44
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at Eco.Core.DebugStatistic.PerformancePlugin.Log(String name, Int32 count, Double ms, Int32 controllerId, Int32 playerId)
   at Eco.Core.Controller.ControllerManager.NotifyChanged(IController controller, String name)</size>
```

**Comment by redwyre** [comment] 2020-07-20 14:18
Duplicate of #17166

**Closed by redwyre** 2020-07-20 14:18 UTC
Labels: Status: Investigate
