### ISSUE TITLE
USER ISSUE: 999 items in buying tab

### ISSUE THREAD

**Issue by jaymp00** [StrangeLoopGames/EcoIssues#6717] opened 2018-03-30 02:32 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Look at the buying tab at a store

**Expected behavior:**
Shows the amount of items in storage.

**Actual behavior:**
Shows they have 999 items already even if they don't have that much

**Comment by styles784** [comment] 2018-03-30 03:37
It's actually saying that store will buy 999 items, although it's most likely that the store owner has left the limit set to unlimited - one of the changes with the last update was to make the store show how many of an item it will buy, instead of how much it already has

**Comment by darkshad9999** [comment] 2018-03-30 07:04
Ya I see what he is saying though one suggestion would be is can they change it from 999 to an infinity symbol if we are buying an unlimited amount that may clear up this issue and make it a bit clearer when you are looking at the buy side of the screen on your market.  I can see though how this is confusing though because now people look at that and think that it has 999 of the item when that is not the case. 

There must be a better way to handle this I still think that if a person leaves it at 0 to buy and want
to buy an unlimited amount to use the infinity symbol there instead of 999. 

![eco store march 30 2018](https://user-images.githubusercontent.com/4023976/38128058-37c15cea-33b6-11e8-92a6-875eba751341.jpg)

**Comment by MarjieAVolk** [comment] 2018-05-14 23:31
Closing as working as intended.  See also https://github.com/StrangeLoopGames/EcoIssues/issues/5947 for our plans to continue improving the store counts

**Closed by MarjieAVolk** 2018-05-14 23:31 UTC
Labels: Suggestion
