### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8184] opened 2018-06-27 17:12 UTC
**==Sent from Eco Crash Server==**
**Details:**
Message: The array dimensions have exceeded the supported range
Source:mscorlib

**Stack:**
at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at Eco.Simulation.WorldLayers.Pushers.PlantSpawner.Apply(WorldArea area, Single[] layerValues, WorldLayerNeighborInfo[] neighborValues)
   at Eco.Simulation.WorldLayers.Layers.WorldLayer.&lt;&gt;c__DisplayClass141_0.<pushlayersatmygranularity>b__0(Vector2i pos, WorldArea area)
   at Eco.Simulation.WorldLayers.Layers.WorldLayer.ForEachCell(Action`2 action)
   at Eco.Simulation.WorldLayers.NewWorldLayerSync.Push()
   at Eco.Simulation.WorldLayers.WorldLayerSync.&lt;&gt;c.<tick>b__11_3()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerSync.Tick()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.TryTick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)</tick></pushlayersatmygranularity>

**Comment by BlazeGuy2** [comment] 2018-06-27 17:16
As of posting, 144 crashes occurred since release yesterday; new crash

**Comment by SeanAtr0n** [comment] 2018-06-27 17:57
don't think we should do dual assignments on high priority things... @craig-jong you know if anything changed in 7.5 around this?

**Comment by craig-jong** [comment] 2018-06-27 18:04
Nothing changed in 7.5 around the add code that this crash is referencing. The last edits to it were 4 months ago by Eric, Me, and Taylor.

**Comment by craig-jong** [comment] 2018-07-03 00:03
I'm going to lower the priority on this.

**Comment by johnkslg** [comment] 2018-07-17 17:18
This has 5200 occurrences! Raising priority

**Comment by metachronism** [comment] 2018-07-17 17:20
closing as dupe of #8279, which has better information

**Closed by metachronism** 2018-07-17 17:20 UTC
Labels: High Priority, Medium Priority
