### ISSUE TITLE
USER ISSUE: Granite invisible when you break it (coal too)

### ISSUE THREAD

**Issue by TheHitman1982** [StrangeLoopGames/EcoIssues#24575] opened 2024-01-09 22:33 UTC
\
**User Id: (slg235906)**
**Version:** 0.10.0.4 beta playtest-316

**Steps to Reproduce:**
Break granite with a pickaxe

**Expected behavior:**
It should break into smaller pieces and be visible

**Actual behavior:**
It breaks as normal but it is invisible, you can only see the outline when you try to pick it up

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-10 09:15
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24573

**Closed by D3nnis3n** 2024-01-10 09:15 UTC
