### ISSUE TITLE
Can't join my own world, friend's server is offline

### ISSUE THREAD

**Issue by Stadny** [StrangeLoopGames/EcoIssues#7590] opened 2018-05-05 17:19 UTC
1. I can't join my own world
2. I can't join my friend's world
Both saying Connection failed

**Comment by pamduncan** [comment] 2018-05-07 09:57
If you are on version 7.3.3, the game is not broken,  the problem is most likely that the game was unable to use UPnP and forward your ports for the game through your router and configure your firewall to allow connections through and get your client world on the internet.  You friend most likely has the same issue and their client server is not on the internet either so you are unable to join them.  The quickest fix for this is for you to update to the test version that is about to be released as stable, version staging_7.4  (right click on Eco and click properties then choose the beta tab and from there 'opt into beta' and from the drop down list choose "staging_7.4".  This version of Eco uses a different network system that does not require that you do any port forwarding or firewall configuration and will get you and your friend connected like you were expecting by just installing the game like with other steam game.   If you absolutely do not want to go to the beta (its also the version that has the new vehicles and the trash system and other things) then you can check the wiki for how to set up the client server (yes even the world you play through in the Eco client is a server) or you can come to the discord support channel and we can give you the instructions on what you need to know abort setting up 7.3.3 to get connected.  You will need to know how to forward ports through your router (your ISP usually has support pages that will show you how to do this) and you will need to write the correct rules in your firewall to allow the game outbound to the internet.

**Closed** 2018-05-09 22:27 UTC
Labels: High Priority
