### ISSUE TITLE
Double key presses on linux

### ISSUE THREAD

**Issue by ruabmbua** [StrangeLoopGames/EcoIssues#6488] opened 2018-03-25 14:03 UTC
Platform: linux

All keys are in almost all circumstances doubly registered. This started in 0.7.2.5.
I can not type anything, because even backspace refuses to delete only one character.

Btw. I can also not walk staight forward. Lets say I walk 1 min forward, when I stop pressing the 'W' key, the character will proceed running for almost 10 seconds.

Sometimes my walking gets really slow, (really really slow), but I am not starving, seems related.

Generally everything, which has to do with input handling sucks since this release.

**Comment by danielhodder** [comment] 2018-03-25 15:37
This issue also happens if you copy and paste text, like a server name or password.

**Comment by danielhodder** [comment] 2018-03-25 16:27
Looks like this is another occurrence of #3580

**Comment by MarjieAVolk** [comment] 2018-03-26 21:37
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3580

I'm going to copy your comments over there, since it seems you have some new details.

**Closed by MarjieAVolk** 2018-03-26 21:37 UTC
