### ISSUE TITLE
Not authorized to add items there

### ISSUE THREAD

**Issue by Lex1co** [StrangeLoopGames/EcoIssues#7584] opened 2018-05-04 20:47 UTC
Hello guys. Did you guys look into this again? 
I've seen similar issues posted as #7069, #6782 and #7160
We are having the same issue on our server with the following messages:
"Not authorized to remove items there"
and 
"Not authorized to add items there"

We did the following:
We used prepared claims with shops setup by an world admin account. These shops could be bought by buying the deed to the shop property. After buying the claim to the shop slot the user can claim the shop deed and use for himself.

All users are having the issue when trying to buy and sell from there wood carts to these types of shops.

**Comment by SarkonDev** [comment] 2018-05-06 04:41
The cart has to be on the shops property to be able to transfer goods to/from the store.

**Comment by MarjieAVolk** [comment] 2018-05-07 19:35
Thanks for the extra details guys, it sounds like having the cart on the same property as the store might be related.  I will check it out.

Sorry it's been so long, I've been out on vacation for a few weeks so things that were assigned to me got put on the back burner.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7069

**Closed by MarjieAVolk** 2018-05-07 19:35 UTC
Labels: Medium Priority

**Comment by MarjieAVolk** [comment] 2018-05-09 22:56
Actually I think this is related to https://github.com/StrangeLoopGames/EcoIssues/issues/7057, now that I've been working on that.  Think I have a fix for this, although it didn't make it into the 7.4 release.
