### ISSUE TITLE
Linux: text input doubled

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#6121] opened 2018-03-16 01:32 UTC
User says:

i am running the steam version 0.7.1.2 beta on Ubuntu 16.

Whenever i type something in the chat or in any other input text field it doubles my input.

E.g. Hheelllloo aallll..

Even enter or backspace/delete are doubled.

I couldn't find anything on your forum or the github issues that fit this problem.

If that helps you, i am developing in Unity on the exact same Ubuntu system and never had problems regarding the input.

**Comment by MarjieAVolk** [comment] 2018-03-16 01:33
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3580

**Closed by MarjieAVolk** 2018-03-16 01:33 UTC
