### ISSUE TITLE
Stone/Coal/Copper/Gold invisible when placed

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#2131] opened 2017-09-15 23:04 UTC
Stone/Coal/Copper/Gold is invisible when placed in the world.

Version: v0.6.0.0-alpha-staging-3a83dd35

**Comment by metachronism** [comment] 2017-09-18 17:58
dupe of #2127

**Closed by metachronism** 2017-09-18 17:58 UTC
Labels: High Priority
