### ISSUE TITLE
Admins need a way to delete abandoned carts of players who have left or been banned.

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#5072] opened 2018-02-25 09:07 UTC
Have had a player grief by leaving carts of tailings over the world to get around our law of no placing on claims they don't own. They have been banned but we can't remove the carts. We need an urgent way to take control of the carts and remove them or at least be able to relocate the contents. Please.

**Comment by Amphysbaenas** [comment] 2018-02-26 03:21
+1

**Comment by MarjieAVolk** [comment] 2018-02-26 22:32
We are working on supporting special characters in names.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3607

**Closed by MarjieAVolk** 2018-02-26 22:32 UTC
