### ISSUE TITLE
Plants are 100% grow but you can't see it only if take one

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1902] opened 2017-08-19 09:10 UTC
if you pickup one all other will be shown perfect the same happen with beets

![grafik](https://user-images.githubusercontent.com/26040573/29485241-d25c36fe-84ce-11e7-9283-c469c23fb7f9.png)

**Comment by REPOSEECO** [comment] 2017-08-19 09:15
![grafik](https://user-images.githubusercontent.com/26040573/29485284-a8293296-84cf-11e7-9490-16a675e196bc.png)

**Comment by MarjieAVolk** [comment] 2017-08-22 22:26
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1406

**Closed by MarjieAVolk** 2017-08-22 22:26 UTC
