### ISSUE TITLE
USER ISSUE: NAT issue with connecting to server over network

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3648] opened 2018-01-26 17:30 UTC
**Version:** 0.7.0.0 beta staging-e27abc9c

**Steps to Reproduce:**
click on connect

setting DetectNAT to false takes server offline and setting it to true will give this error:
Dump Time
01/26/2018 11:17:38

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__51_1()

--END DUMP--

**Expected behavior:**
server shoudl connect

**Actual behavior:**
Dump Time
01/26/2018 11:17:38

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.Co

**Comment by Senlarus** [comment] 2018-01-26 17:39
This is the same issue I reported in #3647

**Comment by pamduncan** [comment] 2018-01-26 20:23
I think its related but they got a different error and the server acted differently.  I posted the bug through the game and it does not search for possible 'same' bugs before posting

**Comment by Senlarus** [comment] 2018-01-26 22:13
No worries, was just letting them know so they could link them is they are related.

**Comment by metachronism** [comment] 2018-01-26 22:23
dupe of #2816

**Closed by metachronism** 2018-01-26 22:23 UTC
