### ISSUE TITLE
Lamps want to be in a room

### ISSUE THREAD

**Issue by Atome6** [StrangeLoopGames/EcoIssues#25226] opened 2024-10-29 23:08 UTC
Hi! TheoDeThael here, on Eco 0.11.0.1

Steps:
- put a lamp in an outdoor place into your claimed area
- the lamp doesn't switch on and the status says that it's "not in a room"
- tested with various lamps. The streetlamps switch on correctly, but the lamps previously designed for the interior don't
- tested with and without mods
![Capture d’écran (197)](https://github.com/user-attachments/assets/d09fad33-9ad8-45f6-8ba0-22ff70170dc3)

**Comment by D3nnis3n** [comment] 2024-10-30 08:52
Do you actually have an outdoor object that makes the space an outdoor room?

Lamps are of a support type - they cannot create rooms, including "outdoors", they can only add to a an existing "outdoor room".
Before they can work and provide their bonuses the room needs to be designated as "outdoors" already, which can be done by objects that do so, for example a fountain.

If so, this is not a bug, but works as intended.

**Comment by Atome6** [comment] 2024-10-30 11:02
Yes, I'm actually speaking of an outdoor room :)
 Also I made a mistake regarding the version number: I'm in 0.11.1
![Capture d’écran (198)](https://github.com/user-attachments/assets/a40f242c-04b7-4326-82f3-b33a252ffc62)

**Comment by Atome6** [comment] 2024-10-30 11:06
In fact I just saw that there's a lot of items that are considered "not in a room" while there are in the "outdoor room"

**Comment by Atome6** [comment] 2024-10-30 11:07
In fact I just saw that there's a lot of items that are considered "not in a room" while there are in the "outdoor room"
![Capture d’écran (199)](https://github.com/user-attachments/assets/2e9a3c59-c472-4fa3-9862-28419b583baa)

**Comment by D3nnis3n** [comment] 2024-10-30 11:07
Which ones?

Atome6 ***@***.***> schrieb am Mi., 30. Okt. 2024, 12:06:

**Comment by Atome6** [comment] 2024-10-30 11:11
I just added the previously forgotten screenshot ^^
I'd say all the items that needed to be in a room before the update adding the outdoor rooms

**Comment by D3nnis3n** [comment] 2024-10-30 11:16
Unfortunately my french is really bad, but from a quick look over the list,
those contain items not intended for outdoor usage. Pots need room volume
for example, which is only available indoors.

Atome6 ***@***.***> schrieb am Mi., 30. Okt. 2024, 12:12:

**Comment by Atome6** [comment] 2024-10-30 18:22
It seems that all the items previously designed to accept being in the outdoor room don't anymore :/

**Comment by D3nnis3n** [comment] 2024-10-30 19:48
I'm unfortunately not able to reproduce that issue at this moment. Does this happen to you on a different server as well?

**Comment by Atome6** [comment] 2024-10-30 20:18
Yes I just tested it and in 11.1.1, same issue. Cast iron bench and so on, and the electric wall lamp don't work because they're "not in a room"
![Capture d’écran (201)](https://github.com/user-attachments/assets/d93db49e-95c1-4f03-8e29-aaded8b39b9e)

**Comment by D3nnis3n** [comment] 2024-10-30 20:24
I'll have QA take a deeper look, maybe they can figure it out.

**Comment by Atome6** [comment] 2024-10-31 15:28
Spouke has found something here: https://discord.com/channels/254025510651297802/822189714122735626/1301536374763290677

**Comment by D3nnis3n** [comment] 2024-10-31 15:31
Unfortunately that link leads me to some random channel some days ago. Can you provide the info here, please?

**Comment by Atome6** [comment] 2024-10-31 16:20
"On seating does not "detect" the outdoor room while the other does detect it. I have many examples like that.
Is it a known bug?
Ok I found the root cause of this issue and fix it for the Cast Iron Bench:
Outdoor room is not compatible with RequireRoomVolume as this room has kind of unlimited volume."
![image (1)](https://github.com/user-attachments/assets/8e1d4d2b-fd3b-413a-b3e0-1e3767df5e1b)
![image](https://github.com/user-attachments/assets/b2b86844-cbc2-455a-941d-4eecd5355f2c)

**Comment by D3nnis3n** [comment] 2024-10-31 21:50
I've sent Spouke a DM on Discord, but this became horribly confusing.

Objects that have a room requirement are intended for indoors, as outdoors doesn't provide room volume - that isn't a bug.

**Comment by Atome6** [comment] 2024-10-31 22:32
Yes I know, but these objects could be used outdoor before the 0.11, that's why I posted initially. The wall lamps, the brazier, cast iron furnitures, they're typically outdoor items IRL so...

**Comment by D3nnis3n** [comment] 2024-11-01 04:58
Outdoor rooms and as such housing points for objects placed outdoors did not exist before Update 11.
You can still place any objects outdoor, but if they aren't suitable for outdoor rooms they will be considered disabled and not provide housing points.

Unfortunately there is no bug visible here, hence I'm closing the issue.

**Closed by D3nnis3n** 2024-11-01 04:58 UTC
Labels: Status: Needs Information, Status: Not reproduced

**Comment by Atome6** [comment] 2024-11-01 11:23
But the lamps won't still switch on while in outdoor. I assure they did, just take a look at the screenshots of the releases on steam :)
![Capture d’écran (206)](https://github.com/user-attachments/assets/6e4a9209-4987-4f63-82f9-9ebf20b2af70)
![Capture d’écran (207)](https://github.com/user-attachments/assets/efd927d7-2f8b-4e00-a0cb-0e0b701691f3)
