### ISSUE TITLE
Steam Thinks Eco is still running even after game is closed

### ISSUE THREAD

**Issue by gharris02** [StrangeLoopGames/EcoIssues#6464] opened 2018-03-24 22:26 UTC
after i close the game by closing it through the quit game button or by force closing it outside the game steam always thinks its running still i have checked task manager the game isnt running anymore yet steam still thinks it is the only temporary fix i have found is to reset steam and then it says its closed

**Comment by TahuW12** [comment] 2018-03-25 09:58
I am also having this issue, either i have to restart my pc or steam to fix it

**Comment by zoblefu** [comment] 2018-03-27 04:00
I am also having this issue. I re-start steam to fix it. It has happened every time I exit eco since we started playing 4 days ago.

**Comment by PieShade** [comment] 2018-04-06 09:43
My Eco game is always in this limbo state after I close it. It will be still be running in steam, despite the lack of an eco.exe in the task manager.

**Comment by J0SH912** [comment] 2018-04-06 09:45
I am also still having this problem. There are no Eco processes running but it is still 'running'

**Comment by ShaydenMac** [comment] 2018-05-02 18:44
Via Email

"Hi, Shay,

just read your post in the community-updates channel on Discord and saw the topic of Steam thinking Eco is still running after it has been closed.

One thing to know about how Steam does these detections: As soon as a process is detected by Steam as a certain AppID it will also consider all processes started from that first process to belong to the same AppID.

In this case, I would not be surprised if the issue is actually that when you start a server from the client Steam will consider the EcoServer.exe process as the game so if that is not properly shut down on exiting Eco Steam will keep showing the game as running.

Same for any other process, like if you did not have your default system browser open before clicking on one of the buttons in Eco that open a web page (like the voting stuff) the browser will also be considered as part of the game. And most users probably won't close their browser afterward.


Not sure if that helps in any way but I thought sharing these points would not hurt :)

Regards,
Chris"

**Comment by ShaydenMac** [comment] 2018-05-02 18:47
Via Email

"First off, love ECO. Second.. these are my personal observations over the years.

Things I have figured out with steam is that it locks everything down when you run it. Example, I can be running the game WURM Unlimited startup screen, and change settings, and it will work, but ONLY for that game session. So the work around is to close the program after it sets it and then restart steam. Because what happens is, STEAM locks everything in a protection bubble. So if you make changes, and it doesn't save in a proper way, STEAM will revert all changes. STEAM is constantly scanning your system for changes / programs you run. In fact, on startup, it does this first thing. Which is how it knows if you cheat in a game or not. Steam also detects your internet, the kind / speed and mac. This is how it knows how to throttle your downloads or not.

With this info, you can see how ECO has to have workarounds when it comes to steam. When you change settings, is it going to a simple text file, or is it saving in a manner that STEAM sees as a potential change to the system, and then it reverts it once steam closes. This could also be why ECO won't "properly" shut down, according to how Steam sees it. Steam is OVERLY protective. And that has lead to many game developers writing extra code to get around steams protection measures. Which defeats the whole purpose to begin with, which leads steam adding more protective measures. See the catch-22?

Hope this insight helps."

**Comment by ShaydenMac** [comment] 2018-05-02 18:47
Via Email

"It’s caused by a browser tab opened by ECO (i.e. when you press „g“ ingame). As soon as you close all browser Tabs opened by Eco steam recognizes the game as closed too. 

Regards,
Tim"

**Comment by ShaydenMac** [comment] 2018-06-26 01:21
Player reported:

"Yeah, I can only say that I was using Chrome, and that I went into the Windows Task Manager, found all the Google Chrome processes, and hit end task. They closed in a cascade, and Eco ceased showing "running" on the Steam interface."

**Comment by Nanders** [comment] 2018-06-26 16:52
Yes it happens any time you leave the web page open in Eco when exiting the game.

**Comment by elfl0rd** [comment] 2018-06-26 17:15
this is not ECO bug, this is old steam bug.
If any game children process launched = game launched.

**Comment by SeanAtr0n** [comment] 2018-07-11 09:00
should be fixed in 7.6

**Closed by SeanAtr0n** 2018-07-11 09:00 UTC
Labels: Medium Priority, Steam Report
