### ISSUE TITLE
[0.9.2 release-137] Wrong Arrow position in Material Proccesing Tutorial 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20105] opened 2021-01-21 07:27 UTC
![image](https://user-images.githubusercontent.com/45708377/105316116-7ab66b80-5bd1-11eb-8423-d43f7a587a1b.png)
![image](https://user-images.githubusercontent.com/45708377/105317504-52c80780-5bd3-11eb-9d58-a845b04ae105.png)

**Comment by tuha263** [comment] 2021-01-28 00:54
I can't reproduce it in the newest developed branch
![MaterialProcessing](https://user-images.githubusercontent.com/9598614/106074183-f79b9500-613d-11eb-8546-5471cd93822d.png)

**Comment by Daniel-Magulado** [comment] 2021-02-02 21:37
Build: 0.9.3 develop 174

Issue: I am able to reproduce it.

Repro:
1. Follow the Material Processing tutorial.
2. Place down Workbench.
3. Open the workbench and observe the arrow pointing at the Hewn Log recipe.
4. Leave crafting UI and open game settings UI. Change the in-game resolution and apply.
5. Go back to Workbench and open the crafting tab. Observe the Arrow.

Result: The arrow pointing to the correct recipe for the Material Processing tutorial is now pointing at different recipe after changing in-game resolution before completing the MAterial Processing tutorial.

Screenshot:
![Untitled.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/606d68c3-9a41-4ad4-8a35-bc38e365e88f)

![2.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/d9adf2b1-3962-4aa0-a488-550890827c1e)

Note: If you revert the resolution back before the issue occurred, the arrow will still be pointing to a different recipe.

**Comment by tuha263** [comment] 2021-02-04 04:03
Thanks @Daniel-Magulado !

**Comment by Daniel-Magulado** [comment] 2021-03-07 10:58
Tested on 0.9.4 Develop-203.

Appears to be fixed.
Tested changing different in-game resolution and other possible breaking methods such as force closing the game and drastically changing settings.

Resolution: Closing.

**Closed by Daniel-Magulado** 2021-03-07 10:58 UTC
Labels: Category: UI, Priority: Low, Regression, Squad: Mountain Goat, Status: Fixed
