### ISSUE TITLE
Make a transfer button is a bit off

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11060] opened 2019-02-03 13:31 UTC
![transfer](https://user-images.githubusercontent.com/25908592/52177379-5385ea00-27c0-11e9-8971-a381a893f123.png)

**Comment by elfl0rd** [comment] 2019-02-04 10:21
Duplicate of #10835

**Closed by elfl0rd** 2019-02-04 10:21 UTC
Labels: Quality Assurance
