### ISSUE TITLE
Picking up a table while inventory is full destroys it

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18906] opened 2020-10-26 06:46 UTC
> Another bug is that if your inventory is full and you try to pick up the carpentry table, the table disappears but is deleted and gone forever because there was no room in the inventory. I haven't tested this with other workbenches but I would guess that there isn't a check to see if the inventory has room before removing the object from the world.

**Comment by IcedForge** [comment] 2020-10-26 14:30
Duplicate of #18340

**Closed by IcedForge** 2020-10-26 14:30 UTC
