### ISSUE TITLE
USER ISSUE: Laser missing from list of items when proposing laws

### ISSUE THREAD

**Issue by Aintence** [StrangeLoopGames/EcoIssues#8220] opened 2018-06-28 14:33 UTC
**Version:** 0.7.5.0 beta

**Steps to Reproduce:**
Trying to ban lasers until everyone on server is ready. Cannot find laser on the list.
1. Propose new law.
2. prevent player from crafting Laser
3. Try find laser on list of items

**Expected behavior:**
I should be able to find laser on the list.

**Actual behavior:**
I cant find laser on the list

**Comment by MarjieAVolk** [comment] 2018-06-28 17:54
Has your server 'discovered' lasers yet?  Looks like someone needs to have researched Electronics in order to discover lasers.

**Comment by Aintence** [comment] 2018-06-28 18:07
I dont believe anyone did. That would explain this. Still kinda annoying because with the rate of progression we have, it could take couple hours to get to them if someone really wanted.

**Comment by MarjieAVolk** [comment] 2018-06-28 18:33
Okay.  Yeah I have heard a good handful of complaints and confusion about discovering things.  I'm not sure how best to improve this.  The idea with discovering is mostly to prevent information overload for newer players, so your first few laws aren't super overwhelming.  Maybe we could just have a toggle to show undiscovered things 🤔

**Comment by MarjieAVolk** [comment] 2018-09-17 21:58
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9100

**Closed by MarjieAVolk** 2018-09-17 21:58 UTC
Labels: Laws, Medium Priority
