### ISSUE TITLE
SERVER ISSUE : Crash 7.2.3 Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by B1sounours** [StrangeLoopGames/EcoIssues#5729] opened 2018-03-08 23:00 UTC
**Version:** 0.7.3

**Steps to Reproduce:**
- hunting?

**Expected behavior:**

**Actual behavior:**

--BEGIN DUMP--
Dump Time
03/08/2018 23:50:05

Exception
System.ArgumentOutOfRangeException: L'argument spécifié n'était pas dans les limites de la plage des valeurs valides.
Nom du paramètre : arrayIndex
   à System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   à System.Collections.Immutable.ImmutableList`1.CopyTo(T[] array, Int32 arrayIndex)
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   à Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   à Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetObjectsWithin(Vector2 position, Single range)
   à Eco.Simulation.ExternalInputs.PredatorTracker.Tick()
   à Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   à Eco.Simulation.EcoSim.DoTick(TickSample tick)
   à Eco.Simulation.EcoSim.Run()
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-09 00:01
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5527

**Closed by MarjieAVolk** 2018-03-09 00:01 UTC
