### ISSUE TITLE
Error getting response stream (Write: The authentication or decryption has failed.): SendFailure

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#5736] opened 2018-03-09 00:42 UTC
From a user:

Hello there,
I've bought Eco today and I#m not able to login.

The following message appeared when I tried to login:

Failed to login 
Error getting response stream (Write: The authentication or decryption has failed.): SendFailure

I hope you can help me somehow.

best regards

**Comment by MarjieAVolk** [comment] 2018-03-09 00:43
People who have steam login problems have mostly reported that restarting steam has resolved it for them.

**Comment by Nanders** [comment] 2018-06-18 18:41
Adding Jeff as I don't recognize this error

**Comment by FireByTrial** [comment] 2020-01-08 00:53
I was getting a similar error, not sure if it was related but here was the response I got:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Failed to authenticate user ticket with Steam</size>

Log File:
Initialize engine version: 2019.2.17f1 (8e603399ca02)
[XR] Discovering subsystems at path D:/SteamLibrary/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 2060 (ID=0x1f08)
    Vendor:   
    VRAM:     5980 MB
    Driver:   26.21.14.4141
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.502600 ms
Logging in as 76561198019827154 using token 
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Error parsing voice login reponse
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Connecting to 142.66.2.30:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
AddServerUI:OnAddServer()
UnityEngine.Events.UnityAction`1:Invoke(T0)
UnityEngine.Events.InvokableCall`1:Invoke(T1)
UnityEngine.Events.UnityEvent`1:Invoke(T0)
TMPro.TMP_InputField:OnUpdateSelected(BaseEventData)
System.EventHandler`1:Invoke(Object, TEventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Disconnected with error: Invalid login info.

<size=60.00%>Failed to authenticate user ticket with Steam</size>
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
Steamworks.PlayersRefreshComplete:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 89299.
Total: 116.512200 ms (FindLiveObjects: 3.600900 ms CreateObjectMapping: 5.473300 ms MarkObjects: 107.126600 ms  DeleteObjects: 0.311000 ms)

Logging in as 76561198019827154 using token 
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Error parsing voice login reponse
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

I came up in the middle of a game, I had launched the browser to propose a law but it was claiming I wasn't logged in even though it sent the token and was launched from the game. once it came up with the exception I was ejected from the server to the menu and could not connect to any servers until I quit and restarted steam. leaving and restarting Eco didn't seem to help, only fully relaunching steam did the trick.

**Comment by WeaselDog** [comment] 2021-04-19 01:01
Hi there. I am not able to reproduce this in the latest version and am going to close it as resolved. Please let us know if you experience this issue again.

**Closed by WeaselDog** 2021-04-19 01:01 UTC
Labels: Category: Tech, Priority: Medium, Squad: Pumpkin
