### ISSUE TITLE
Waypoints are far off

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5692] opened 2018-03-08 18:12 UTC
In a 100x100 world max x & y coordinated are 1000. When you go over the "line" where coordinated go from 1000 back to 0 waypoints are displayed totally wrong. They only display inside x/y coordinated as if it would be a flat map with edges, so you're getting them displayed over 800m away while in fact they are totally opposite and only 1-200m away (But on the other side of that coordinate switching line)

**Comment by MarjieAVolk** [comment] 2018-03-08 22:26
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5481

**Closed by MarjieAVolk** 2018-03-08 22:26 UTC
