### ISSUE TITLE
Tree stumps causing dirt to not be pickup-able in places where stumps don't exist

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#4107] opened 2018-02-08 08:23 UTC
http://steamcommunity.com/app/382310/discussions/7/1699416432411841337/

Gotta double check if its correctly using planttoarea

**Comment by WeaselDog** [comment] 2019-11-13 19:53
I believe this was caused by road tools and was fixed in 8.2

**Closed** 2019-11-13 20:14 UTC
Labels: Medium Priority
