### ISSUE TITLE
Stuck at "initializing WebServerPlugin"

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10658] opened 2019-01-13 16:39 UTC
Have has several of these  in the  past 48 hours.  Plasyer is star8ing a single player private game and gtes as far as initializing WebServerPlugin and it jsut hangs onm that message.  Moet of these were new purchases of Eco but one has had this issue since they purchased a game a week ago and were told that they needed to email tech support and did not know about discord.  He said this  "One week ago I wrote at the support, because once I press the start button to create a private world, the loading screen "initializing WebServerPlugin" holds on for hours"   "The support says I should ask you here onte the discord server"

We went through all the usual troubleshooting for this kind of problem and no issues showed up until the verified that cache and it said 2 files were missing but the files stayed missing even after trying a clean install with Firewall and AV suspended.  We checked for .Net version.  All servers were windows 10 except one was  8,1. Finally broke it down to server and client separately.  After another reinstall started up server with the EcoServer.exe 'run as administrator' and the server loaded up a new world and popped up the server UI,  The server was up and running and the webserver was running.  He was then able to go into client and go to "My Worlds " and see his server there as a LAN server and he was ab;e to join his server without any further problems.  After that we backed out and shut down the server and loaded it through "My Worlds" and hr immediately got stuck on  initializing WebServerPlugin once again.  He is able to go back to running that server outside of the client - logging in through the client as continued or LAN server and can play fine.  He is playing that way now so that he could at least play as he said he was waiting for a week and then got told to come here and a,, he wanted was a way to play.

The other servers were like this also with a couple files missing and a couple files consistently missing even with Steam saying they would be reacquired.  In one case the player was positive it was windows defender and so she reinstalled Eco after installing Norton and no longer getting 'missing files' and then was able to get  in the world through the client.  In 2 cases they switched to SLG download and those clients worked fine,  The others were like this one and were absolutely not going to run anything but ta steam install  but running the server outside the client is working for them and then just joining by the in client link to My Worlds. the sp server outside the client and connect the client to it as a LAN server.

We did have something like this before where the client kept not allowing people to connect to that LAN or local host.  Making sure they are configuring the Network.eco so they have a chance to set remoteAddress: and some of the other settings from the past week but that was not much help.
No DUMP files were written and the output_log.txrt said nothing except some audio error we see all the time and then the server disconnects with a time out message but no error except to just say it timed put.  

I really don't quite understand if this is a problem with how steam is installing or what else is going on if Steam somehow has the wrong file list and is downloading from that list

**Comment by elfl0rd** [comment] 2019-01-13 18:40
Duplicate of #10399 
(fixed in 0.8)
i'll recommended to play through external launched server, before 0.8 live
(This is issue with get DNS in internal processing, we researched some cases with non-english letters in PC name.)

**Closed by elfl0rd** 2019-01-13 18:40 UTC

**Comment by elfl0rd** [comment] 2019-01-14 00:05
One question, was he trying to run Eco between file verification? I think I found something that it does not like for Steam :D
