### ISSUE TITLE
[9.3.5 Release-213] Government seizure of property by law splits into individual plots

### ISSUE THREAD

**Issue by ROMORC** [StrangeLoopGames/EcoIssues#22004] opened 2021-05-27 11:25 UTC
A law that changes the owner of property from citizens breaks the claim into many individual tiles rather than leaving the plot together. This requires players to deal with many individual plots. 

The triggering law:
![law](https://user-images.githubusercontent.com/13177837/119817884-7e7a3780-bebc-11eb-897b-bb035a06f67b.png)

After executing, the plot is broken up into many individual plots as here:
![property](https://user-images.githubusercontent.com/13177837/119817977-9e116000-bebc-11eb-8918-748804b099cf.png)

Note that the bottom grey section was from another player that had not been claimed yet. This was repeated on another plot claimed latter in the day. This was not the case before 9.3.5.

**Comment by Daniel-Magulado** [comment] 2021-05-30 15:05
Hello @ROMORC,

Thank you for writing a report about this.
I can confirm that it is happening.
I'll be forwarding this to our development team so they can look into it further.

-------------------------------------------
Build: 0.9.3.5 Release-231

## Issue
Abandoned properties are separated into tiles into minimum claiming area. However, not all are separated.

#### Screenshot
![image](https://user-images.githubusercontent.com/77248866/120108613-8e359c80-c198-11eb-86ab-5281b9d72491.png)
![image](https://user-images.githubusercontent.com/77248866/120108645-b4f3d300-c198-11eb-875f-5d88e874f20f.png)

#### Recorded Video

https://user-images.githubusercontent.com/77248866/120108661-cd63ed80-c198-11eb-89c7-f062933a9c94.mp4

#### Saved World and Logs
[Claim.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6566376/Claim.txt)
[Claimed World.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6566377/Claimed.World.zip)

**Note:** I am unable to reproduce this issue in 9.4 Staging-1995.

**Comment by gzatravkin** [comment] 2021-05-31 23:16
Maybe it was fixed by last changes in spliting, not sure. Anyway investigate TrySplitDeed method

**Comment by madpingui** [comment] 2021-06-08 15:43
Tested in staging, with several properties and everything is always transferred to the same color (a single group, example active), seems fixed

**Comment by Daniel-Magulado** [comment] 2021-06-14 22:09
Tested on 0.9.4 Staging-2020

Closing for now as I am unable to reproduce on the latest Staging build.

**Closed by Daniel-Magulado** 2021-06-14 22:09 UTC
Labels: Category: Laws, Priority: High, Squad: Wild Turkey, Status: Not reproduced, Type: Bug
