### ISSUE TITLE
Construction issues, stairs placement

### ISSUE THREAD

**Issue by Egrof** [StrangeLoopGames/EcoIssues#1778] opened 2017-07-06 22:32 UTC
![escaliers](https://user-images.githubusercontent.com/16516876/27935377-16415502-62ab-11e7-9871-424f8cb44a56.jpg)

WHY ???!!!
Those wood stairs only want to be placed this way. I can't press E or A to turn it. It's the same for roofs.

Generally construction can be a painful experience. We need an option for a little cross in the center of the screen to see where we are pointing.

**Comment by MarjieAVolk** [comment] 2017-07-28 21:16
Duplicate of StrangeLoopGames/EcoIssues#438

**Closed by MarjieAVolk** 2017-07-28 21:16 UTC
