### ISSUE TITLE
Not all logs can be picked up 6.2.0 #737b5d74

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3005] opened 2017-12-05 02:06 UTC
chopped trees collecting logs, but some just will NOT let me pick them up, they are highlighted green
<img width="1280" alt="snap109" src="https://user-images.githubusercontent.com/29383891/33586315-c6a166fe-d960-11e7-98d0-645a6313a5f0.png">
was playing on Hoary Marmot.

was also occasionally getting this happen on 6.1.2, if you destroy the stump the log you cannot pick up vanishes ( i always get logs before removing stump)

**Comment by brad992** [comment] 2017-12-06 08:58
I've had this occasionally on previous versions, I think it is caused by lag, the logs have been taken but the tree doesnt disappear. It hasn't happened very many times to me to bother me though

**Comment by Conchipedia** [comment] 2017-12-06 18:26
not sure if it was lag as was Plying on SLG test server and just me online (but there was hundreds of debris and rubble all over the place)

**Comment by MarjieAVolk** [comment] 2018-02-23 23:41
If you haven't been seeing it, think I'm gonna close this one.  It seems likely that it was due to lag.

**Closed by MarjieAVolk** 2018-02-23 23:41 UTC
