### ISSUE TITLE
Keybinding for letting go of a cart not modifiable

### ISSUE THREAD

**Issue by CaptainDumbo** [StrangeLoopGames/EcoIssues#4695] opened 2018-02-17 09:44 UTC
I have rebound the "E" key to something else, and it works fine for everything (so far) except when letting go of a cart I am pulling. In that case, the keybinding is still "E".

Thanks in advance for fixing this when possible! Broken keybindings are a deal breaker for me as I can't use the WASD classic controls!

**Comment by MarjieAVolk** [comment] 2018-02-20 23:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4412

**Closed by MarjieAVolk** 2018-02-20 23:12 UTC
