### ISSUE TITLE
USER ISSUE: Accept residency results in Null Reference Exception

### ISSUE THREAD

**Issue by s-macke** [StrangeLoopGames/EcoIssues#23476] opened 2022-09-20 18:48 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
accept residency

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Private.CoreLib

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.RPCManager.<>c__DisplayClass23_0`1.<Call>b__0(Object o)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__76_4()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-09-20 19:58
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23475

**Closed by D3nnis3n** 2022-09-20 19:58 UTC
