### ISSUE TITLE
USER ISSUE: Skid Steer Collection Bug

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#11860] opened 2019-04-04 02:43 UTC
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
1. Try to mine sandstone (or any rock type) with skid steer.
2. Try to pick up sandstone (or any rock type) by holding down left mouse key while having the bucket in the correct position.

**Expected behavior:**
It should have collected the rubble pieces like it did in previous versions.

**Actual behavior:**
Instead it seems to be picky about which pieces it will scoop up. In fact I think it will only pick up pieces that were created right after breaking blocks while holding the left mouse button. When I break blocks, then release my finger from the left mouse button, then try to hold the left mouse button down and collect the debris I just created, it wont scoop it up.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No Mods

**Comment by Blanclour** [comment] 2019-04-04 02:47
If i scoop the debris I create right after breaking the blocks while continuing to hold down the left mouse key it will collect the debris like it is supposed to.

**Comment by mirasrael** [comment] 2019-04-04 17:20
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11654. Fixed in upcoming 8.1

**Closed by mirasrael** 2019-04-04 17:20 UTC
