### ISSUE TITLE
Land Claiming

### ISSUE THREAD

**Issue by Firestar000** [StrangeLoopGames/EcoIssues#9607] opened 2018-09-29 20:52 UTC
I just build my first building and I thought I claimed all the land I need for my house.  Turns out my house is not on all of my land.  I have 5 deeds and a land claiming post.  *Note the house is built and a roof is on the house*  I can not claim the land.  No one else owns the land because I wont allow anyone on that server but me.  When I walk out side my house I can claim land.  But I can not claim land that my house is built on when I am inside the house.

**Comment by Firestar000** [comment] 2018-09-29 20:59
To add on.  The color will not change from green to yellow.  Yet SOMETIMES not always when I try to place another claim down it will say you already own this property.

**Comment by D3nnis3n** [comment] 2018-09-30 01:14
I have seen the issue that a land gets claimed but the color does not change and on another try you get the message that you already own the property several times, so i can confirm that behaviour.

It happens rarely, though.

**Comment by Firestar000** [comment] 2018-09-30 16:00
>           I have seen the issue that land gets claimed but the color does not change and on another try you get the message that you already own the property several times, so i can confirm that behaviour.
> It happens rarely, though. I never had the issue to not be able to claim at all, though.

I can get it to say my land is claimed but the size of my land claimed will not increase.  And the color does not change to yellow.

**Comment by D3nnis3n** [comment] 2018-10-20 04:57
I was able to get a video from one of the issues mentioned here, the color not changing:
https://drive.google.com/open?id=1ZGq20yPaYC2nC7OON1gCn4KwbIeCAHe0

@BlazeGuy2

**Comment by thereporter42** [comment] 2018-12-12 06:48
Not sure if this is the same or not but I just opened up a ticket for this
in regards to land claiming.  

https://github.com/StrangeLoopGames/EcoIssues/issues/10286

**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
1. Select your Land Claim Stake
2. Go stand on the plot of land you want to claim
3. Right click on the plot of land to claim it.

**Expected behavior:**
That it would go the same color that I have set which is red 
for that plot. 	

**Actual behavior:**
Instead it is staying the same ground color instead of going
red but it insists that I already own that plot if I try and own it a it again it 
it says that I already own that plot. But it refuses to go the same color as the rest
of my plots which I have set to red.

I don't know why and Yes I have tried to unown it and then reown it again with
the same results it won't turn red like the rest of my plots when I have 
my land stake tool selected and I don't know why. I believe this to be some kind of
bug with the game at this point because I have tried everything even unowning it
and then reowning it and it does the same thing!  It just won't turn red.

Now if I stand on the plot and look down and hit E it is listed as me owning it
but why isn't it red like the rest of my plots when  I have my land select tool 
selected. 

Now in the screenshot you can see that I am not standing on it and I did that
on purpose for the screenshot so it wasn't yellow and you can see that 
the plot is just the normal ground color and yes I have my Land Claim Stake
tool selected as you can see all the other ones around me are all red except that 
one.  This is maddening why is it doing this with this one spot. 

This is my own server FYI running on a machine that I have here 
as a test server that I play around with.  Never saw this before 
it has never done this in the past just with this version. 

A copy of the image can also be seen at https://ibb.co/1zy107k

**Do you have mods installed? Does issue happen when no mods are installed?:**
I have no mods installed. 

![land claim issues eco dec 11 2018](https://user-images.githubusercontent.com/38896397/49851346-11cb5b00-fd9e-11e8-94af-fe38d6f1cd25.jpg)

**Comment by D3nnis3n** [comment] 2018-12-12 09:17
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/10286

**Closed by D3nnis3n** 2018-12-12 09:17 UTC
Labels: Needs Information
