### ISSUE TITLE
USER ISSUE: Error opening wainwright table

### ISSUE THREAD

**Issue by MiquelRoan** [StrangeLoopGames/EcoIssues#15778] opened 2020-04-14 17:18 UTC
**Version:** 0.9.0.0 beta staging-1511

**Steps to Reproduce:**
1. open wainwright table	

**Expected behavior:**
It should show all recipes

**Actual behavior:**
Showing few recipes. Everytime I enter the table there's one recipe more loaded correctly
![Captura](https://user-images.githubusercontent.com/61141964/79254217-b2df8f80-7e84-11ea-84d5-9428d8609d2a.JPG)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no. I'm playing in Royal Otter

**Comment by SlayksWood** [comment] 2020-04-15 09:26
Can you provide log files when have this issue?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
such bugs were easily reproduced, possibly fixed in staging-1513. 
@MiquelRoan 
Check it again after updating playtest to new staging.

**Comment by SlayksWood** [comment] 2020-04-21 12:29
@MiquelRoan 
Do you have this issue in new staging?

**Comment by LoBlanc** [comment] 2020-04-21 12:30
It didn't reproduce again to me

**Comment by WeaselDog** [comment] 2020-05-19 23:24
Thanks for your report. We are not able to reproduce this in the latest version and it appears to be fixed. Please let us know if experience this issue again.

**Closed by WeaselDog** 2020-05-19 23:24 UTC
Labels: Status: Investigate
