### ISSUE TITLE
Possible Thought on why we get Wrong Hammer at start of the game (Basic Crafting 1)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3407] opened 2018-01-15 18:27 UTC
Version: 0.6.4.0 alpha staging-d2f49058

was looking through the Tiers to see what they are and it says the following in each:
![snap1083](https://user-images.githubusercontent.com/29383891/34956337-82784462-fa20-11e7-92a3-8c72fbd0528b.png)
![snap1084](https://user-images.githubusercontent.com/29383891/34956338-82940f08-fa20-11e7-89b1-e93d30991571.png)
![snap1085](https://user-images.githubusercontent.com/29383891/34956339-82ade46e-fa20-11e7-8fe8-0a194fc0bef9.png)
![snap1086](https://user-images.githubusercontent.com/29383891/34956340-82c7147a-fa20-11e7-8376-bfa150066c5e.png)
so if you hover over the hammer name in those you see this:
![snap1087](https://user-images.githubusercontent.com/29383891/34956389-b7c57ee6-fa20-11e7-85d5-debb5df2a868.png)
and then if you look at the Hammer itself you see this:
![snap1088](https://user-images.githubusercontent.com/29383891/34956431-ee816ef4-fa20-11e7-9ac5-5dbf0f81dd15.png)

Now in Every game i have played this hammer has Always appeared in The recipes on the Anvil and doesn't belong to any of the groups (Stone, Iron, Steel or Modern) so maybe its like a Placeholder that has turned into a real hammer that now appears in the game.

Maybe use the Stone Hammer as the Example and then add something in Tooltip like: 
Variants: Iron, Steel, Modern

**Comment by MarjieAVolk** [comment] 2018-01-15 18:33
That tooltip isn't causing it.  Think it's just wrong in the spreadsheet.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3361

**Closed by MarjieAVolk** 2018-01-15 18:33 UTC

**Comment by Conchipedia** [comment] 2018-01-15 18:36
ok, was just a thought, have those Occasionally 😄
