### ISSUE TITLE
USER ISSUE: Unity Error when logging onto server

### ISSUE THREAD

**Issue by itstheholyginger** [StrangeLoopGames/EcoIssues#11614] opened 2019-03-08 23:28 UTC
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
Select "continue" to log onto server

**Expected behavior:**
Opened the world

**Actual behavior:**
Stopped at "Loading world 90%", then for a split second a "Unity Error" pops up, then disappears before I can read it, crashing the program.

**Do you have mods installed? Does issue happen when no mods are installed?:**
I do not have any mods installed.

**Comment by D3nnis3n** [comment] 2019-03-09 02:30
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11562

**Closed by D3nnis3n** 2019-03-09 02:30 UTC
