### ISSUE TITLE
USER ISSUE: Being Launched into sky and dropped about 100m away	

### ISSUE THREAD

**Issue by Dubie7910** [StrangeLoopGames/EcoIssues#24948] opened 2024-05-20 20:16 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Twice when bumping into a log that I was trying to pick up I got catapulted into the sky way above the map and dropped about 100 meters from where I was

**Expected behavior:**
It should have just let me pick up the log	

**Actual behavior:**
Instead it launched me into the sky	-

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't know anything about mods and Yes, I guess it happens when no mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Dubie7910** [comment] 2024-05-20 20:22
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15381470/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15381475/Player.log)

**Comment by D3nnis3n** [comment] 2024-05-21 01:16
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/22947

**Closed by D3nnis3n** 2024-05-21 01:16 UTC
