### ISSUE TITLE
Error displaying project information (Icon and quantity)

### ISSUE THREAD

**Issue by hihihehes2** [StrangeLoopGames/EcoIssues#24917] opened 2024-05-01 08:20 UTC
When creating a new Project, the Icon displays the bonfire and quantity 1234 instead of the manufacturing object information. At this point I cannot press the Work button, I have to close the window, then press Alt + Right mouse to add labor.

Machines that encountered this error: Campfire, Cement Kiln, Hydroponics Table, Farmers Table. I have many machines/tables of the same type, but only a few have the above error.

Attached videos:
https://youtu.be/EqxpHXma3Qs

**Comment by hihihehes2** [comment] 2024-05-01 08:22
Version: 10.2 + 10.2.1 + 10.2.2, all of them

**Comment by D3nnis3n** [comment] 2024-05-01 20:50
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24886

**Closed by D3nnis3n** 2024-05-01 20:50 UTC
