### ISSUE TITLE
USER ISSUE: Store causing large FPS drop.

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11697] opened 2019-03-16 18:42 UTC
**Version:** 0.8.1.0 beta staging-ecbd458d

**Steps to Reproduce:**
Create a store
fill in random items, i just clicked Add all.
open it

fps drop to unplayable

remove room and open shop again, fps revert back to normal
same when going to bed, but when waking up its back to low fps again.

see video	
https://www.youtube.com/watch?v=_SXIn8uJ7j4&feature=youtu.be

**Expected behavior:**
no fps impact

**Actual behavior:**
unplayable after opening a few shops

**Do you have mods installed? Does issue happen when no mods are installed?:**
none, new singlepalyer nocollab game

**Comment by redwyre** [comment] 2019-03-17 06:16
Duplicate of #11608

**Closed by redwyre** 2019-03-17 06:16 UTC
