### ISSUE TITLE
USER ISSUE: Interaction Bugs

### ISSUE THREAD

**Issue by DezDotExe** [StrangeLoopGames/EcoIssues#23759] opened 2023-04-08 21:42 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.10 beta release-474

**Steps to Reproduce:**
Trees- Cut down tree with axe
"Walls"- collect hewn logs into inventory and equip hammer

**Expected behavior:**
Trees- an interaction que to chop log into smaller pieces
"Walls"- rotate wall orientation before placing

**Actual behavior:**
Trees- no interaction que, leaving unusable large chopped log laying on the ground.
"Walls"- no "Rotate" que, unable to place in the desired orientation.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. Happens on unmodded, randomly generated world.

Log Files:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11184271/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11184273/Player-prev.log)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-04-10 15:57
Internal report for walls: 27859

**Comment by D3nnis3n** [comment] 2023-04-10 17:52
Walls not being rotatable is working as intended, hence this is not a bug.
Tree interaction issue is related to https://github.com/StrangeLoopGames/EcoIssues/issues/23764 and other issues, hence closing this one.

**Closed by D3nnis3n** 2023-04-10 17:52 UTC
Labels: Type: Bug
