### ISSUE TITLE
USER ISSUE: cannot chop lob

### ISSUE THREAD

**Issue by KlemensM** [StrangeLoopGames/EcoIssues#6230] opened 2018-03-18 11:30 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
there is a tree piece on the ground, if i start to chop it, the game crashes. Next time i log in, i chopped it but if a try to take it, it crashes again.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-21 18:56
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5595

**Closed by MarjieAVolk** 2018-03-21 18:56 UTC
