### ISSUE TITLE
USER ISSUE: Can't See Water Through Unplaced Blocks

### ISSUE THREAD

**Issue by wondernerd14** [StrangeLoopGames/EcoIssues#6437] opened 2018-03-24 04:10 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Take a placeable block (I noticed it with stone)
2. Aim to place your  such that a water block is behind the outline of the placeable block

**Expected behavior:**
You should be able to see everything behind the outline of the placeable block.

**Actual behavior:**
The water becomes invisible behind the outline of the placeable

**Comment by MarjieAVolk** [comment] 2018-03-28 19:28
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5703

**Closed by MarjieAVolk** 2018-03-28 19:28 UTC
