### ISSUE TITLE
USER ISSUE: Can't place a fishing trap underwater

### ISSUE THREAD

**Issue by POC0bob** [StrangeLoopGames/EcoIssues#11129] opened 2019-02-07 05:38 UTC
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
Created a fishing trap from a fishery
Tried to place it anywhere under the ocean, both in my claim and outside of the claim. It says its blocked.	

**Expected behavior:**
Placed the fishing trap underwater

**Actual behavior:**
Only allows me to place it above water, not under water regardless of conditions in the water itself.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Only allows me to place it above water, not under water regardless of conditions in the water itself.

**Comment by elfl0rd** [comment] 2019-02-07 07:12
Duplicate of #10849

**Closed by elfl0rd** 2019-02-07 07:12 UTC
