### ISSUE TITLE
Can't Vote In Government

### ISSUE THREAD

**Issue by Mushmellow318** [StrangeLoopGames/EcoIssues#8728] opened 2018-07-25 01:37 UTC
I attempted to go and vote while in game for a government, but whilst I tried, I couldn't do anything because it kept leading me towards my Docs. Is this a bug or just me? Please help!

**Comment by elfl0rd** [comment] 2018-07-25 05:11
What ECO version you using?

**Comment by MarjieAVolk** [comment] 2018-07-25 17:57
What are 'my Docs'?  Did you make it to your browser?

**Comment by MarjieAVolk** [comment] 2018-07-26 18:37
Closing this for now, until we hear back from @Mushmellow318.  Don't know what the issue is.

**Closed by MarjieAVolk** 2018-07-26 18:37 UTC
Labels: Medium Priority
