### ISSUE TITLE
Input/Output mode for chest/storage link

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2200] opened 2017-09-20 13:53 UTC
It's required if you want to build a crafting chain.   
E.g.:   
Food preparation -> First Tier -> Second Tier -> .... -> Store (because we only want to sell the last one)

**Comment by MarjieAVolk** [comment] 2017-09-20 17:21
Yep, been talking about this for a while

**Comment by MarjieAVolk** [comment] 2018-01-10 22:51
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2190

**Closed by MarjieAVolk** 2018-01-10 22:51 UTC
Labels: Feature
