### ISSUE TITLE
Temperature and Sea-Level Rise is capped

### ISSUE THREAD

**Issue by danisani1** [StrangeLoopGames/EcoIssues#22647] opened 2021-09-08 08:08 UTC
We lit the machinery day and night and our Server of 15 active players looks quite gross now, but we reached 780 ppm in the atmosphere after two days. Yet the temperatur rise was cappedd to +1,5 degree per day and the sea level rise was  capped to +1 meter per day. 

![image](https://user-images.githubusercontent.com/58810286/132471195-e3113862-4312-432a-971f-958711edcf9f.png)

If it was a change on purpose, the display is still old ("Sea level rises 1 meter every 20ppm past 420 ppm). If not, it's a bug :)

**Comment by Daniel-Magulado** [comment] 2021-09-10 20:28
Hi @danisani1 

Thank you for writing this report. However, this is intended. The statement "Sea level rises 1 meter every 20ppm past 420 ppm" is still intended as is but the cap of +1 per day is implemented to prevent a sudden influx or change of temperature and sea level.

Closing this since this is not a bug.

**Closed by Daniel-Magulado** 2021-09-10 20:28 UTC
