### ISSUE TITLE
USER ISSUE: HELP !STUCK!!!!

### ISSUE THREAD

**Issue by lyclyc123** [StrangeLoopGames/EcoIssues#19901] opened 2021-01-04 02:29 UTC
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
IN THE SPACE NOW !!!!

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by lyclyc123** [comment] 2021-01-04 04:59
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5763110/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5763111/Player-prev.log)

**Comment by D3nnis3n** [comment] 2021-01-04 10:12
Try using /unstuck and if that doesn't work /fly to get out. If you're on a multiplayer server you'll need to reach out to an admin to get you down. The issue is already bugged, though, so I'm closing this one.

**Closed by D3nnis3n** 2021-01-04 10:12 UTC
