### ISSUE TITLE
Floating Point Pricing Error

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#12626] opened 2019-06-23 09:25 UTC
Version: 0.8.2.3

Another reason I hate decimal number prices.

The store buys **Logs** for 1 **(Zoneman Credit)**, and sells **Hewn Logs** for 0.6 **(Zoneman Credit)**.
After trading with the store for a while I got this:
![image](https://user-images.githubusercontent.com/2676134/59974157-03f65e00-95a9-11e9-8673-f11604e8c7b6.png)
It clearly says I have 0.6 **(Zoneman Credit)** in all the interfaces, but the store says I don't have enough.
I went to the transfer window to just give the player back their credits so I don't have to look at them, and this is what the transfer window reported back to me when trying to transfer "all":
![image](https://user-images.githubusercontent.com/2676134/59974178-461f9f80-95a9-11e9-92e8-cbcd445b17e0.png)
I have exactly 0.5999998 **(Zoneman Credit)**, which I will agree with the game isn't the same as 0.6 **(Zoneman Credit)**.

I assume this is a floating-point error.

**Comment by Deantwo** [comment] 2019-06-23 09:28
I really wish you would just make currencies into a fixed-point decimal number. And set a hard limit in the game with the amount of decimals you allow. No one is every going to want to mess with prices or money they is 0.000001 or lower. A limit at 0.001 seems more then generous, but even 0.01 is fair.

**Comment by Eforen** [comment] 2019-09-05 20:23
I strongly disagree with 0.001 being more then generous I want access to the 5th decimal place only reason I don't use it now is because I don't have access to make prices that use that price or atleast it does not show up in the gui

**Comment by Deantwo** [comment] 2019-09-05 21:38
Having too many decimal points seems to just be a weird way to save a poorly created currency. But sure I can understand the issue of not wanting to lose the freedom to make a currency like that.
But limitless decimal numbers just really screws up math and causes weird bugs like this one.

A better way of doing it would be to use a fixed-point number, but allow us to set how many decimals the currency should allow when creating it.

Allowing a currency to infinity inflate into one millionth of a $ doesn't make sense. If that happens the citizens should scrap the currency and make a new one.

**Comment by Asharas** [comment] 2021-02-02 11:00
Hi!
I found a related bug where I couldn't transfer the remaining of other players' currency back to their account.
Clicking the `all` button sets the value but the `Send` button does nothing (no transfer, window stays open).  

I agree with Deantwo on the idea of limiting the decimals, I'd arbitrarily say 2 decimals but I don't know if people use thousandths often (I am obviously culturally biaised, European citizen are used to cents as the lowest fraction while Japanese players maybe would not use decimals).  


![image](https://user-images.githubusercontent.com/33208603/106586383-ac6ff080-6548-11eb-82d7-2e6b02ac1330.png)

**Comment by Asharas** [comment] 2021-02-03 14:49
The same thing actually happens with reputation too.
Here a citizen rewarded for work parties participation.
![image](https://user-images.githubusercontent.com/33208603/106763648-58900500-6637-11eb-9ecc-c283bd590e6e.png)

**Comment by IcedForge** [comment] 2021-03-09 08:04
Bumping this in priority as this is the root cause of breaking in a lot of different aspects now with changes to work parties, contracts/loans and a higher frequency use of wages in general. When ever a value goes into deep decimals this causes all kinds of problems all over.

**Comment by IcedForge** [comment] 2021-05-20 13:49
Closing as working but will need more extended real testing for evaluation to make sure it doesn't affect anything unforeseen in an odd way but looks solid.

**Closed by IcedForge** 2021-05-20 13:49 UTC
Labels: Category: Gameplay, Priority: High, QA, Squad: Wild Turkey, Status: Fixed, Type: Bug

**Comment by Deantwo** [comment] 2021-05-20 14:01
If #8518 was only about taxes, then it sounds unrelated to this issue. Since there was no sales taxes involved.

But other changes might have solved this issue, I don't know.

I still really wish that currencies had a fixed-point value. And a limit to currency decimals, as I mentioned in this issue. Even making it an option in the creation of the currency seems really nice,

**Comment by IcedForge** [comment] 2021-05-22 06:31
The fix for it should be extended to cover all of it, so taxes, wages, debt/loans etc as they were all affected by this so it shouldnt be a problem for anything now.

**Comment by Deantwo** [comment] 2021-05-22 06:36
> taxes, wages, debt/loans etc

None of those things were involved with this original bug report. It was just normal trading with credit at the early stage of a world.

But either way, lets just hope it is fixed.
