### ISSUE TITLE
[Client] Inventory menu changes after each game restart

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8856] opened 2018-08-05 14:20 UTC
**Version: 0.7.6.3 beta**

**Steps to reproduce:**
Sort an inventory menu in a certain manner, leave the game and start new.

**Expected behavior:**
The menu should look as I left it.

**Actual behavior:**
The menu has a changed look, all inventory lines are unfolded and must be managed again.

as I left menu:
![workbench1bild](https://user-images.githubusercontent.com/38510829/43686717-b5884cdc-98ca-11e8-86bf-461734643166.jpg)

after game new start:
![workbench2bild](https://user-images.githubusercontent.com/38510829/43686723-d35c4696-98ca-11e8-810b-5bf051db89bc.jpg)

**Comment by seccombew** [comment] 2018-08-06 22:08
This might already be fixed/better with Marjie's recent changes.

**Comment by MarjieAVolk** [comment] 2018-08-06 23:27
Uh oh, well I think I see what the issue is, looks like it's just not always getting saved correctly.

**Comment by MarjieAVolk** [comment] 2018-08-08 00:39
Fixed in the next major release

**Closed** 2018-08-08 00:39 UTC
Labels: Medium Priority
