### ISSUE TITLE
Tooltips should be able to specify which direction to show

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3378] opened 2018-01-13 02:03 UTC
![image](https://user-images.githubusercontent.com/3536496/34901703-b09c6f36-f7c2-11e7-9a4d-d890b0dfac17.png)

These tooltips on skills show up in the way of the next skill I want to look at. If we could specially tag it to appear to the left or right, perhaps in the UI objects, it would make them easier to work with.

**Comment by MarjieAVolk** [comment] 2018-01-13 02:58
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3327

**Closed by MarjieAVolk** 2018-01-13 02:58 UTC
Labels: Suggestion
