### ISSUE TITLE
[Linux] [0.9.6.1] pink screen (video problem)

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#23429] opened 2022-09-10 07:31 UTC
Hello.

Problem in linux version of game.

OS: openSUSE Tumbleweed 20220901
KDE Plasma: 5.25.4
KDE Frameworks: 5.97.0
Kernel: 5.19.2-1-default (64-бита)
GP: X11
CPU: 8 × Genuine Intel® CPU 0000 @ 2.20GHz
Memory: 31,3 Gb
GPU: AMD Radeon RX 5600 XT

Game version: 0.9.6.1

After load of world all pink.

https://user-images.githubusercontent.com/13696708/189473844-f1986d5f-f96e-4921-bb5b-b1ba77355db8.mp4

**Comment by D3nnis3n** [comment] 2022-09-10 13:06
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23334

**Closed by D3nnis3n** 2022-09-10 13:06 UTC
