### ISSUE TITLE
USER ISSUE: vechicle plates broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9443] opened 2018-09-20 10:12 UTC
**Version:** 0.7.7.2 beta
![2018-09-20_14-10-06](https://user-images.githubusercontent.com/4980243/45811809-cb062180-bcd6-11e8-9539-b4d0c41fa596.png)

**Comment by elfl0rd** [comment] 2018-09-20 10:16
@Nanders ? :D

**Comment by D3nnis3n** [comment] 2018-09-20 21:21
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/9333
Give me high priority also! :D

**Comment by craig-jong** [comment] 2018-10-11 18:35
Looks like this is fixed in 7.8

I'm going to close it, but please let me know if this isn't the case.

![image](https://user-images.githubusercontent.com/18184943/46826017-c9fe6800-cd49-11e8-90a5-ead4596d23c7.png)

**Closed by craig-jong** 2018-10-11 18:35 UTC
Labels: High Priority
