### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Almisuifre** [StrangeLoopGames/EcoIssues#23794] opened 2023-04-17 12:01 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.12 beta release-482

**Steps to Reproduce:**
1. Connexion
2. Problem placment bloc
3. Deconnexion
4. Reconnexion -> echec

**Expected behavior:**
1. Connexion
2. Problem placment bloc
3. Deconnexion
4. Reconnexion -> Ok

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Annulé par l'utilisateur
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-05-01 20:29
Can you provide more info? Singleplayer / Multiplayer? What is the exact problem? The error only says you cancelled the connection yourself. What is block placement problem?

**Comment by D3nnis3n** [comment] 2023-05-05 13:47
Closing due to no further information provided and not reproducable.

**Closed by D3nnis3n** 2023-05-05 13:47 UTC
Labels: Status: Needs Information
