### ISSUE TITLE
Issue with EcoServer32 converting client world for 8.0.4

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#11502] opened 2019-02-27 06:51 UTC
Okay world was failing to convert after 8.0.4 was installed and giving an out of memory error on a windows 10 computer with 16GB RAM./  world ws 140X140.  This was on the client server.

--BEGIN DUMP--
Dump Time
02/26/2019 23:16:27

Exception
Exception: OutOfMemoryException
Message:Exception of type 'System.OutOfMemoryException' was thrown.
Source:mscorlib

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
   at System.Exception.ToString()
   at Eco.Shared.Utils.DebugUtils.ToStringPretty(Exception e)
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--

She was doing this through "Continue" and as EcoServer32.exe was supposed to be default for the client  so to make sure that EcoServer32,exe was being used had her tri "Load".  Same Error.

Then ran the Server outside of the client trying to see if this was a EcoServer32 iss and the similar error occurred.  

--BEGIN DUMP--
Dump Time
02/27/2019 01:29:10

Exception
Exception: OutOfMemoryException
Message:Exception of type 'System.OutOfMemoryException' was thrown.
Source:mscorlib

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.ThreadPoolWorkQueue.EnsureCurrentThreadHasQueue()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

--END DUMP--

After that we ran the Ecoserver.exe and the world converted normally and loaded without error.  Once she was able to get the world converted she was able to go back in an dload the world through the client (that would be using EcoServer32,exe at this point) and it loade fine (no conversion) and she was able to get in game

**Comment by Litonius** [comment] 2019-02-27 07:09
Thank you Pam, for making this bug tracker for me! (My old one is here, which is useless by comparison: https://github.com/StrangeLoopGames/EcoIssues/issues/11498) and I'm new to GitHub so I'm unsure if I should delete it/etc (or if I can) but if there's anything more I can provide to help fix this bug let me know. So far, after doing the above steps the world seems to be fine; the conversion was the big issue.

**Comment by redwyre** [comment] 2019-02-27 07:28
Duplicate of #11498

**Closed by redwyre** 2019-02-27 07:28 UTC
Labels: Critical Priority, Needs Triage

**Comment by pamduncan** [comment] 2019-02-27 07:46
It does appear that this was a problem with EcoServer32,exe having a out of memory issue while trying to convert the world from an 8.0.3 world in the client server.  Think we pretty much sowed that whether using continue or load the client was suing the default of EcoServer32.exe and we would get the out of memory failure while it was trying to convert the world to 8.0,4   

Just setting the world name that we wanted to load/convert in the storage.eco config file and then running EcoServer.exe everything went fine.  And interestingly enough that after the server converted and loaded the world we were able to shut down EcoServer.exe and go into the client and use load (which would be running EcoServer32,exe) and without having to run the conversion pass the server just loaded the world and the player was able to join the world.

Nothing else seemed to get around the OoM issue with EcoServer32,exe during the conversion and unfortunately the OoM error is not exceptionally descriptive but for now the work around for anyone in this situation is:

Exist client and go to steamapps/common/Eco_Ecodta/Server/Config and in the Storage.eco set the SaveName to the name of the world you want to load and convert (without the ,eco extension on the world name),  Save the file.

Go to steamapps/common/Eco_Ecodta/Server/ and right client on EcoServer.exe and click "Run as Administrator".  Let the world load and run the conversion, hopefully this will work as well for you too.  Shut the Eco Server ServerUI and Console down so the server is offline.

The go back into the Eco game as you normally world and choose Load or continue or what you usually do to load your world.  this should then load the world without converting, since that already took place and you should be in your game and able to play.  ***Note if you go in on this step and the server tries to convert again, and fails, after it did successfully convert on the previous step please let the devs know here in this bug report and in the official-support channel in discord in there are other steps to try.

**Comment by redwyre** [comment] 2019-02-27 07:51
I already wrote up the work around at https://github.com/StrangeLoopGames/EcoIssues/wiki/Work-around:-Converting-world-to-new-format-crashing-in-0.8.0.4 :)
