### ISSUE TITLE
USER ISSUE: The minimap is not here

### ISSUE THREAD

**Issue by Sigvi05** [StrangeLoopGames/EcoIssues#11078] opened 2019-02-04 20:18 UTC
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
1. "M"

Thats all. When i press m the map does not show up

**Expected behavior:**
Shoving the map

**Actual behavior:**
Showing map settings

**Do you have mods installed? Does issue happen when no mods are installed?:**
Showing map settings

**Comment by D3nnis3n** [comment] 2019-02-13 02:36
Cannot reproduce, any additional info?

**Comment by D3nnis3n** [comment] 2019-02-22 12:41
Closing because happening on a old version and no answer for information request in the last 14 days. Reopen if it reoccurs.

**Closed by D3nnis3n** 2019-02-22 12:41 UTC
Labels: Needs Information, Not reproduced
