### ISSUE TITLE
Single player should start in 32 bit

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11632] opened 2019-03-11 22:03 UTC
This got disabled for today's hotfix, but we need to revive it for the next fix as it give 40% mem savings.

Since migration is the problem, we can skip it for this case and force load the 64 bit version.  So when starting a server:
- If the world is from a prior version, always load 64 bit
- If the world is from current version or later, dynamically choose 32 or 64 bit based on the save
- If the world is brand new, start 32 bit if the size can handle it (and since theres no size option in the client-started worlds, always do 32 bit there)

**Comment by metachronism** [comment] 2019-03-11 23:00
closing as dupe of #11498

**Closed by metachronism** 2019-03-11 23:00 UTC
Labels: High Priority
