### ISSUE TITLE
I turned off the server for an update and it no longer starts. The latest backups are all broken.

### ISSUE THREAD

**Issue by D3vil787** [StrangeLoopGames/EcoIssues#24939] opened 2024-05-16 14:10 UTC
It happened again

[16:47:33.071] [21] [Error] [Eco] Errors report:
Failed to start the server. Exception was Exception: KeyNotFoundException
Message:The given key '0' was not present in the dictionary.
Source:System.Collections.Concurrent

System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToArray(BinaryReader reader, Array array, Int32 index)
   at Eco.Core.Serialization.Serializers.DefaultArraySerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.BasicSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo member)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeReferenceableEnumerable(BinaryReader reader, Object decodeTarget, Int32 numElements)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeEnumerable(BinaryReader reader, Object decodeTarget)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.EcoSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream)
   at Eco.Core.Serialization.DataStore.<>c__DisplayClass49_1`1.<LoadAsync>b__1()
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Error(s) occurred when loading World (The given key '0' was not present in the dictionary.) (Exception has been thrown by the target of an invocation.) (The given key '0' was not present in the dictionary.) (Object cannot be stored in an array of this type.)
: 1

**Comment by D3nnis3n** [comment] 2024-05-16 19:46
Please attach the savegame. But this looks like simple save corruption which hints at something at setup / saving to disk being broken.

**Comment by D3vil787** [comment] 2024-05-17 02:07
@D3nnis3n 
Last work save and last broken save
https://www.dropbox.com/scl/fo/tmefd91nu5fh0uafq674v/AFvIlYEUkXGe9VnIlKc6mBY?rlkey=o3p7ipg3pzu8u9p5b2ebbbyyt&dl=0

**Comment by D3vil787** [comment] 2024-05-21 05:40
@D3nnis3n 
Any news?
We are forced to keep the server offline until you solve the problem.

**Comment by D3nnis3n** [comment] 2024-05-22 17:36
Both savegames have corruptions in them, where things were not correctly saved to disk. While we cannot absolutely exclude that being caused by Eco, that is a very strong hint at something being wrong with the server hosting or hardware. Once wrong data has been saved to disk, from that point on the savegame will stay corrupted as data is saved partially. That explains why all backups from a specific point on were broken - that specific point is the time where the issue appeared.

It is not possible for us to investigate from the savegame why it happened, nor do we have any reproduction of the problem. I had the worlds running for multiple days on hardware of mine and they did not corrupt. Both worlds are also unsupported, as they are modded and surpass the maximum supported world size of 160x160.

The world of D3vil787 has mods on it (EM Mods) and has a world size of 200 x 200, running for more than 150 days with multiple migrations.

The world of Galtsuu also has mods on it (Stack Rack) and has a world size of 252x252.

Taking into account that both worlds are unsupported, the issue not reproducible and likely not related to Eco at all, there is no further investigation into the issue possible from our side, other than if someone can provide a reproduction case. As such I'm closing the issue until such case is available.

**Closed by D3nnis3n** 2024-05-22 17:36 UTC
Labels: Status: Needs Information
