### ISSUE TITLE
Corrupted world(?) leads to falling through blocks on staging version

### ISSUE THREAD

**Issue by NDKilla** [StrangeLoopGames/EcoIssues#3425] opened 2018-01-16 14:26 UTC
I was talking to Pam on discord last night about an issue I was having. I tried deleting some of the log walls of my house and replacing them with shaped hewn logs. After placing several of the hewn logs, large sections of my house and my outdoors stockpile became invisible. Walking into the invisible wall would cause me to fall out of the world in an endless loop (fall for several seconds, teleport to ground level, fall more).

Neither restarting the server or the client fixed the issue.

Server version EcoServer_v0.6.4.0-alpha-staging-ca25d17a downloaded from website.

Comments from discord:
"https://i.imgur.com/HfQcTDH.jpg I can apparently fall through the map (visual glitch) in an endless portal-like loop. The game knows theres blocks there (I can't place anything), I just can't see or touch them anymore."

"https://i.imgur.com/aNTpuro.jpg screenshot after restarting the server and my client"

Not sure how to troubleshoot this any more.

**Comment by MarjieAVolk** [comment] 2018-01-16 21:01
Did you use Hewn Log Windows?  There was an issue with these that caused this behavior, which I believe is fixed in the current staging build, or if not then in the next one that is going out in a few hours.

**Closed** 2018-01-16 22:09 UTC

**Comment by NDKilla** [comment] 2018-01-17 02:16
@MarjieAVolk No windows. Was just spamming e to pick up piles of logs that made up my walls, then using the hammer to place the "shaped" ?? hewn logs

**Comment by MarjieAVolk** [comment] 2018-01-17 18:16
Well a window is one of the 'shapes' (we are calling them forms) so... I guess you weren't using the window form?

**Comment by MarjieAVolk** [comment] 2018-01-17 18:20
We saw someone else complaining about this just now actually, so looks like this issue isn't fixed after all.  Sorry about that.  But leaving this one closed as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3453  (That looks like the same problem, right?)

**Comment by NDKilla** [comment] 2018-01-19 21:53
@MarjieAVolk that looks similar to my issue, yes. I *believe* that all phantom blocks were hewn logs.
