### ISSUE TITLE
Room requirements not met, still processes

### ISSUE THREAD

**Issue by metrotyranno** [StrangeLoopGames/EcoIssues#315] opened 2016-06-17 08:56 UTC
http://puu.sh/pvOJ9/210421e67d.jpg

**Comment by metachronism** [comment] 2016-06-17 16:35
the client timer is counting down, but its not actually doing the work - client bug

**Comment by metachronism** [comment] 2016-06-17 16:44
dupe of #128

**Closed by metachronism** 2016-06-17 16:45 UTC
