### ISSUE TITLE
[0.9.2.0 beta staging-1894]Civics: When removing an object after submission it stays around in pending election

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19948] opened 2021-01-08 14:59 UTC
When you add a civic object such as law, title etc and you submit into an election ( not starting it ) and you have it inside the "Pending elections" ui element and you remove the object from the table completely ( delete it ) it will now stay in that window and cannot be deleted / removed ( it will clear on server restart, reconnecting does not help ).

Add a law, submit it to an election - (Not starting it)
Delete object from containing table
Now try remove from side ui window and it does not work.

In this example, i removed Title 2 but it is still there in my ui, if i reconnect it simply updates status to "Deleted" but it does not vanish until a server restart detects and deletes corrupt object.
![Screenshot_34.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/b7122206-d56d-4f2f-b7e7-3ebe6ce04a6e)

**Comment by serpopov** [comment] 2021-01-11 19:28
This is what was fixed in https://github.com/StrangeLoopGames/Eco/pull/7484
I think that specific case could be just a symptom of another issue.

**Comment by Daniel-Magulado** [comment] 2021-01-12 10:28
Build: Staging
Repro: Unable to reproduce. Appears to be fixed by the fix implemented for https://github.com/StrangeLoopGames/Eco/pull/7484.


Closing.

**Closed by Daniel-Magulado** 2021-01-12 10:28 UTC
Labels: Category: Laws, Category: UI, Priority: High, Squad: Mountain Goat, Status: Not reproduced, Type: Regression
