### ISSUE TITLE
Staging Build 7.2.0 Crash Server

### ISSUE THREAD

**Issue by Malaras** [StrangeLoopGames/EcoIssues#4973] opened 2018-02-23 00:36 UTC
Server crashes with this error, and other dumps
![crash server](https://user-images.githubusercontent.com/1544846/36571985-58e4fd16-1807-11e8-9d2f-dc0516ead1ec.jpg)

[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1750050/Dump.zip)

**Comment by MarjieAVolk** [comment] 2018-02-23 19:20
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4916

**Closed by MarjieAVolk** 2018-02-23 19:20 UTC
