### ISSUE TITLE
Black screen after joining server

### ISSUE THREAD

**Issue by Argethe** [StrangeLoopGames/EcoIssues#23519] opened 2022-11-05 19:41 UTC
Hi, 

few months ago I submitted issue #23385 and hoping, it will help. I little forgot about post and tried to return to game after a while. Tried to turn off Steam overlay, and all other steps I tried before, but none of them helps. Issue persists - after joining server I hear only birds chirping and black screen.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9944606/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9944607/Player-prev.log)

Internal reference was ECO-24374.

Hope you can find some other solution. 

Thanks

**Comment by Argethe** [comment] 2022-11-05 19:45
I noticed sometimes, when I try to turn off game, there is an Error message for a fraction of second, but I didn´t catch some error code, hope it will be in logs.

**Comment by RemonRamy** [comment] 2022-11-08 15:48
Hello again @Argethe,

Can you try the following steps and let us know if they help?

1. Press `Win+R` on your keyboard and type in `regedit`.
![image](https://user-images.githubusercontent.com/15372525/200610797-5cfa9465-4c94-447e-ba96-400f480c7710.png)
3. Navigate all the way to `HKEY_CURRENT_USER\SOFTWARE\Strange Loop Games\Eco`.
![image](https://user-images.githubusercontent.com/15372525/200611059-f4c83713-4132-44ac-859a-41441aee6a18.png)
5. Right click on the `Eco` folder and click `Export`,
![image](https://user-images.githubusercontent.com/15372525/200610738-bb873f6a-5ed9-45ee-9a2e-f5e97704a296.png)
6. It will prompt you to save a registry file, can you send us that file back? I'll help us resolve the issue.
![image](https://user-images.githubusercontent.com/15372525/200611330-1591aa89-4bdd-4353-bf9a-a3cb30d4f211.png)
8. Right click on the same `Eco` folder again and click `Delete`.
![image](https://user-images.githubusercontent.com/15372525/200610770-bcaf680a-a6ec-4260-859c-2b26da6a3f9b.png)
9. Try to play Eco again and check if the problem is fixed.

Cheers,
Remon

**Comment by Argethe** [comment] 2022-11-08 17:50
Words can´t describe how thankful I am... It´s finally working. I wasn´t thinking about registry, I thought/hope, it will rewrite after reinstalling game. Thanks a lot, for me, issue can be closed. 

Since it was something in registry, Im attaching it for investigation, if needed.

Much love <3 Take care and cheers   

[argethe.zip](https://github.com/StrangeLoopGames/EcoIssues/files/9963820/argethe.zip)

**Comment by RemonRamy** [comment] 2022-11-09 01:00
Hey @Argethe,

I'm super glad it worked out, wishing you the best gameplay experience! Thank you for sharing your registry file with us, will definitely help us investigate and fix the cause for this issue.

Feel free to reach out again if you run into any issues or have some feedback or suggestions for us.

Closing as resolved, internal reference: ECO-25271.

Cheers,
Remon

**Closed by RemonRamy** 2022-11-09 01:00 UTC
