### ISSUE TITLE
USER ISSUE: breaking stone

### ISSUE THREAD

**Issue by wajas420** [StrangeLoopGames/EcoIssues#25045] opened 2024-08-16 17:33 UTC
\
**User Id: (3fe1593f-7d9b-4b6a-a702-08dcbd61e506)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
brake stone

**Expected behavior:**
it should have breacked in the same block  

**Actual behavior:**
it teleport the stone to a random location 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no I dont have mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-08-16 18:14
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25037

**Closed by D3nnis3n** 2024-08-16 18:14 UTC
