### ISSUE TITLE
[7.5.0] Wrong Position for WoodSigns

### ISSUE THREAD

**Issue by Rick86** [StrangeLoopGames/EcoIssues#8182] opened 2018-06-27 16:30 UTC
Before 7.5 you could put Signs IN FRONT of Walls or "hang" it on the Wall. Now (because of world convertation) the Signs are IN the Wall :/
This happens on:
SmallStandingHewnLogSign
SmallHangingHewnLogSign
LargeStandingHewnLogSign
LargeHangingHewnLogSign
SmallStandingStoneSign
LargeStandingStoneSign
[...]

I had 100+ Signs on the wall, now they are all IN the wall... Why you changed the position?!

**Comment by funnybunnyofdoom** [comment] 2018-06-27 16:50
I don't know if it's a bug or a feature, but you can no longer place hanging signs against the wall. I also lost many of my signs to this.

**Comment by BlazeGuy2** [comment] 2018-06-27 17:23
@Rick86 Can you post screenshots of the signs?

**Comment by elfl0rd** [comment] 2018-06-27 18:28
Sounds like this - https://github.com/StrangeLoopGames/EcoIssues/issues/8055

**Comment by Rick86** [comment] 2018-06-27 20:31
@elfl0rd Could be the same, yes
@BlazeGuy2 See the screenshots
![sign_position](https://user-images.githubusercontent.com/38107858/41997970-d7604272-7a59-11e8-9754-da678c674463.jpg)

**Comment by MarjieAVolk** [comment] 2018-07-03 17:10
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8055

**Closed by MarjieAVolk** 2018-07-03 17:10 UTC
Labels: Medium Priority
