### ISSUE TITLE
USER ISSUE: Shooting a bow brings you back to the main menu

### ISSUE THREAD

**Issue by vik1ngur** [StrangeLoopGames/EcoIssues#23989] opened 2023-08-23 20:58 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-102

**Steps to Reproduce:**
1. equip the bow (and arrows)
2. shoot 
3. bug occurs

**Expected behavior:**
shooting the bow

**Actual behavior:**
game / world crashes and brings you back to the main menu

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12423287/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12423288/Player-prev.log)

**Comment by D3nnis3n** [comment] 2023-08-24 11:53
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23987

**Closed by D3nnis3n** 2023-08-24 11:53 UTC
