### ISSUE TITLE
On cinematic for meteor, number of days until it hits is hardcoded/wrong

### ISSUE THREAD

**Issue by Trekkan** [StrangeLoopGames/EcoIssues#12141] opened 2019-05-01 04:34 UTC
If you change the number of days in the config until the meteor hits, when watching this in the tutorial, it always says "30 days", regardless of the config setting.  A similar report was already entered it appears, but it was closed without being fixed?

**Comment by D3nnis3n** [comment] 2019-05-01 18:48
Duplicate of #9130

**Closed by D3nnis3n** 2019-05-01 18:48 UTC
