### ISSUE TITLE
USER ISSUE: Falling infinitly becaus the world didn't loaded

### ISSUE THREAD

**Issue by Siedler** [StrangeLoopGames/EcoIssues#5406] opened 2018-03-05 08:40 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Walk into an area that isn't loaded

**Expected behavior:**
Should load the area	

**Actual behavior:**
Let's me fall down

**Comment by MarjieAVolk** [comment] 2018-03-06 00:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861.  Hopefully this will be fixed in 7.2

**Closed by MarjieAVolk** 2018-03-06 00:25 UTC
