### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Necki99** [StrangeLoopGames/EcoIssues#24113] opened 2023-12-05 11:01 UTC
\
**User Id: (slg233060)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Il messaggio d'errore seguente è comparso:
```
<size=150%>Connessione non riuscita</size>

Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-06 16:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23117. Unfortunately no fix possible without reproduction steps.

**Closed by D3nnis3n** 2023-12-06 16:23 UTC
