### ISSUE TITLE
User Issue: Balance for seeds amount from harvesting

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12718] opened 2019-07-05 05:04 UTC
https://steamcommunity.com/app/382310/discussions/4/1642041106353968884/
Seeds and Farming
I'm not sure if this is recent, or even whether it's intended or not, but i've noticed recently that the farming skill effects the seeds received from some (not all) plants detrimentally.

Up until recently i have only had gathering, and found that wheat and corn when harvested have generally given me a seed around 60% of the time, for every hundred plants harvested I've generally received roughly 60 seeds ...

... until i decided to train farming, now that i am level 7 in farming i have found that if i harvest my wheat and corn crop (roughly 400 plants) i'm only getting a seed back every hundred or so plants.

I asked a couple of others i know that are farming and gathering, and they've notice this trend too.

It only appears to be crops that are destroyed when harvesting, like wheat and corn. things like tomatoes and huckleberries seem to give as many if not more than they did before training farming.

Is anyone else finding this? Is it intentional?

**Comment by nitrofenix** [comment] 2019-07-05 15:07
Weighing in on this -- I only seem to get a good number of seeds when the match percentage is >90% for a crop and the nutrients are fairly high.

This is probably by design in order to keep Farming relevant, however I believe the Gathering skill should apply to seeds in a similar way to the Yield attribute for crops and plant fibers, except maybe it should give the same amount of seeds more often, as opposed to just the same ~10% chance for twice the amount of seeds.

This is especially important for those like myself who play the ecological conservation game and attempt to prevent endangered plant species from going extinct (currently trillium, sunflowers and creosote bush on our world); without some form of crop to convert into seeds, your only option is to keep harvesting plants until you get lucky.

From a logic perspective, if Gathering 7 makes you such an efficient gatherer that you get twice the number of crop items, it follows that the net gain in seeds should scale as well, since they are also technically part of the crop yield.

**Comment by SlayksWood** [comment] 2019-07-08 09:44
The yield doesn't affect at harvesting of seeds.
This is a balance component, not a bug. Is it necessary? In the end there will be a lot of seeds that people will just throw out.
Maybe it is just necessary to increase the number of seeds of plants that give plant fiber? So that people can restore their population.

**Comment by nitrofenix** [comment] 2019-07-08 12:35
> The yield doesn't affect at harvesting of seeds.
Understand and agree -- I said I believe that it _should_, not that it does already.

> Maybe it is just necessary to increase the number of seeds of plants that give plant fiber? So that people can restore their population.
That'd be a good start, although increasing the number of seeds per plant rather than increasing the drop-rate wouldn't really fix the "lucky-dip" mechanic we have now, just make you "luckier" when it actually happens; a slight increase to the seed drop-rate for those plants would probably work a little better.

**Comment by WeaselDog** [comment] 2019-11-27 18:12
It is fixed now.

Related to this: https://github.com/StrangeLoopGames/EcoIssues/issues/12833

**Comment by trickenso** [comment] 2020-04-19 11:48
> This is a balance component, not a bug. Is it necessary? In the end there will be a lot of seeds that people will just throw out.

Maybe they could be used in alternative production chains to produce cooking oil, ethanol, fertilizers, pesticides, animal repellents, plant fiber, directly as a fibrous component in mortar or other products. They find lots of uses in industrial processes cooking in real life - presumably because they are so plentiful.
Even if they are just used to make compost it's still a useful fertilizer ingredient.

From here: https://pubs.acs.org/doi/abs/10.1021/np8006217#

> Seeds of many plant species contain uncommon fatty acids and lipids, some of which have found uses in the cosmetic industry or as renewable (non-petroleum based) industrial raw materials.
> [...]
> In addition to proteins and energy storage substances such as carbohydrates and lipids, seeds generally contain, or have the ability to produce, protective compounds that are active as plant growth regulators, fungicides, insecticides, and repellents of herbivores; seeds occasionally contain compounds that are toxic to most other organisms.
> [...]
> Examples of compounds isolated from plant seeds that have served as lead compounds for additional research, or that continue to be of interest to researchers in multiple areas, are reviewed.

**Comment by WeaselDog** [comment] 2021-10-04 19:28
This appears to be fixed in our latest version. Please let us know if you still view this as a problem.

**Closed by WeaselDog** 2021-10-04 19:28 UTC
Labels: Priority: Low, Category: Balance, Squad: Redwood
