### ISSUE TITLE
Server Restart causes all Permissions to be reset

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10025] opened 2018-11-15 10:27 UTC
After our daily server restart all given permission vanished, even shops were no longer public but only accessable by owner. Same for Storage and deeds and other tables.

**Comment by D3nnis3n** [comment] 2018-11-17 11:30
Reopened issue, it is not fixed. I can observe the following:

Restart removes:
- "Everyone" from Objects
- Demographics from Deeds

Restart does not remove
- Players from Objects or Deeds
- "Admin" from Objects or Deeds

**Comment by D3nnis3n** [comment] 2018-11-17 12:03
More testing shows it's especially deeds where the permissions vanish, objects do seem okay now if they have been replaced, not just the auth readded.

**Comment by Quadbro** [comment] 2018-11-18 14:19
Hey @johnkslg  @BlazeGuy2 So here is what i discovered:
Firstly highlighted method executes just before Legislation loaded, an it causes IAlias Valid method to be set False on some Demographics stuff 
![rider64_tggh4hs1aj](https://user-images.githubusercontent.com/6802030/48673637-0bb6d580-eb76-11e8-8278-4fd7980a65b1.png)

But Also the actual behavior: 
No data will be saved on alias selectors, until second restart. So you need, for example claim some deed, save and restart server, and only after that all changes with Auth will be saved. I debugged most of deed/selector stuff, but can't find what is actually wrong with data before first server restart, maybe i don't know some very important stuff about serialize/deserialize processes? 

Probably i need some help with this issue, sorry..

**Comment by msgerbs** [comment] 2018-11-25 16:37
Still not fixed. Our server just crashed and all object permissions were reset.

**Comment by D3nnis3n** [comment] 2018-11-28 21:44
There have been several reports of players still loosing auth, even though i were not able to reproduce it.

**Comment by metachronism** [comment] 2018-12-01 01:34
can't reproduce

**Comment by D3nnis3n** [comment] 2018-12-01 03:54
It's reported every day in discord and players on my own server occur it on every restart, too. It's no longer everyone, but only some people, though.

**Comment by elfl0rd** [comment] 2018-12-04 03:10
Yes i can confirm. It's still happens on fresh master branch.

Before restart
![default](https://user-images.githubusercontent.com/4980243/49416523-42523a00-f78b-11e8-82b7-04f7bc6a1b48.png)

after multiple saves and restart
![default](https://user-images.githubusercontent.com/4980243/49416544-585ffa80-f78b-11e8-8b8a-e9dfe2b8dfe6.png)

**Comment by D3nnis3n** [comment] 2018-12-04 15:32
Getting even worse:
<img width="537" alt="information" src="https://user-images.githubusercontent.com/25908592/49452823-2fb71f80-f7e2-11e8-8700-8c0922713351.png">

**Comment by Spydarlee** [comment] 2018-12-12 13:32
So it looks like some of the previous fixes for this bug were applied to AliasSelector.cs but there are _two_ files with that name in the project.

One in "Server\Eco.Gameplay\Alias" and one in "Eco.Gameplay\Aliases"

The latter is the one actually included in the Visual Studio project, but the former has has several changes over the past month (including as part of the last fix for this issue).

**Comment by D3nnis3n** [comment] 2018-12-12 13:34
If you fix this one, this would be worth a hotfix imo. It's a really enerving bug that should have been fixed long ago.

**Comment by Spydarlee** [comment] 2018-12-20 15:45
Hey @metachronism - would you be able to take a quick look at this again to make sure you're previous fixes haven't got lost in the shuffle? See above comment for some duplicate file weirdness. Also I _am_ able to reproduce this on master now, but I've been digging and can't see what part of your fix is missing. 🤔

**Comment by elfl0rd** [comment] 2019-01-17 13:17
Fixed only for objects, not for deeds.
reopened.

**Comment by D3nnis3n** [comment] 2019-01-24 21:59
Happens again, deed did not save authorisation.

**Comment by mirasrael** [comment] 2019-01-25 09:41
Fixed for deeds.

**Closed** 2019-01-25 19:01 UTC
Labels: D3nnis3n's List, Fixed, High Priority
