### ISSUE TITLE
USER ISSUE: Tractor stuck on barge

### ISSUE THREAD

**Issue by alwaysintreble** [StrangeLoopGames/EcoIssues#24666] opened 2024-01-21 04:08 UTC
\
**User Id: (slg221836)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
1. Lower ramp of barge
2. Drive tractor onto barge
3. Tractor immediately locks into place as soon as it makes contact with the floor of the barge above the ramp, not even fully clearing the ramp
4. Tractor can no longer be moved by driving it, nor by using the hammer movement. Trying to move it with the hammer also consumes the calories necessary.

**Expected behavior:**
Vehicles should not lock into place until after the ramp of the barge has moved, and should be movable when the ramps are down.

**Actual behavior:**
Vehicle locks into place and cannot be moved through any method even with the ramps down.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14000016/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14000017/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-01-21 14:27
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24650

**Closed by D3nnis3n** 2024-01-21 14:27 UTC
