### ISSUE TITLE
Chat box Issues

### ISSUE THREAD

**Issue by Spidey426** [StrangeLoopGames/EcoIssues#10733] opened 2019-01-18 01:22 UTC
7.8.8 
My chat just keeping scrolling back to the same spot it was in when I joined the server. I have to keep scrolling down. It happens when I press C to close it then when I reopen it that's when it backtracks. It's been doing this since i started playing a week ago. Others in my server are experiencing the same thing. When the server was P2P it was doing it as well. (Now we're on a dedicated server) 

Expected: scrolled all the way to the most current entry.

**Comment by D3nnis3n** [comment] 2019-01-18 09:31
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8704

**Closed by D3nnis3n** 2019-01-18 09:31 UTC
