### ISSUE TITLE
Vechicles at 0 - character kicked out.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11071] opened 2019-02-04 09:20 UTC
It now happens after @SeanAtr0n carts fix. Before (after @mirasrael vechicle fix) all fine.
e.g. you drive trough 0 on bridge...
![20190204121110_1](https://user-images.githubusercontent.com/4980243/52199448-2b0cf700-2877-11e9-8fe3-24a0e6b93e76.jpg)
*blink*
you now under bridge.
![20190204121154_1](https://user-images.githubusercontent.com/4980243/52199461-37914f80-2877-11e9-9d0b-7c8a1f850d56.jpg)
![20190204121200_1](https://user-images.githubusercontent.com/4980243/52199466-395b1300-2877-11e9-9161-6fe9aea44fb5.jpg)
Happens not all time, but quite often, to be annoying

**Comment by SeanAtr0n** [comment] 2019-02-04 20:25
hard to reproduce, might require that specific bridge setup so lowering priority

**Comment by elfl0rd** [comment] 2019-02-04 20:39
Kicking out from vechicle happens on flat ground too, but with bridge it's more annoying.

**Comment by SeanAtr0n** [comment] 2019-02-04 21:52
It only happens when you are 1-2 chunks away from unloaded chunks?

**Comment by elfl0rd** [comment] 2019-02-04 21:55
hm... yes, looks like.

**Comment by SeanAtr0n** [comment] 2019-02-08 22:42
silently fixed by eric

The server thought the truck was too far away from you because it didn't receive an update from the truck as you crossed the border and automatically dismounted you. (client was configured to only send updates for 12 objects)

**Closed by SeanAtr0n** 2019-02-08 22:42 UTC
Labels: Medium Priority
