### ISSUE TITLE
USER ISSUE: BUG REPORT

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#6037] opened 2018-03-14 12:30 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Game version 0.7.2.4.
Dug the ground (cleared the site for construction), used a steel shovel for this, and put the land in a warehouse (stockpile). when completing the warehouse about half received an error message.

**Expected behavior:**
Caught exception

**Actual behavior:**
Caught exception:

<size=60,00%>Ссылка на объект не указывает на экземпляр объекта.

Stack:
   в Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   в Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   в Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>

**Comment by MarjieAVolk** [comment] 2018-03-15 21:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-15 21:40 UTC
