### ISSUE TITLE
Eco fails to start game on Intel series video-cards (and rarely on some Radeon models)

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#11125] opened 2019-02-07 04:18 UTC
Player logs into server gets to 90% and gets kicked while others play without issue,  Firewalls and AV software have been suspended.  there is no server error written. Have not had an instance where we ccould roll the server back to they were on.  Clients have been validated, reinstalled and so on and the server   for the most part have reinstalled and used updated config files.

Will have people having issues add to this so you
 have contact with tyhem,

**Comment by aerodynamac** [comment] 2019-02-07 04:48
![eco error](https://user-images.githubusercontent.com/47409024/52391115-aa621c80-2a69-11e9-95d7-18eb40210ac5.png)
Basically, this message pops up when it reaches 90% and then the game crashes

**Comment by Pounce22** [comment] 2019-02-07 05:19
Hello that is the same error message i receive when i attempt to log onto my server.  Earlier this morning i was able to log on to the bleeding stage beta update onto the server with no issues.  but since then i get to 90% then get kicked out.  I did also verify game files found two files were missing i unistalled and reinstalled game to no avail..

**Comment by aerodynamac** [comment] 2019-02-07 16:58
"invalid user trying to connect: AerodynaMac"

Is all our admin is getting from aero logging in. We've tried resets, reinstalls, nothing

**Comment by aerodynamac** [comment] 2019-02-07 18:12
Update: another friend who has Eco tried to run their account on my computer and the same problem happened. The mod said that I log in for 5 seconds then immediately get bumped.

**Comment by GamerPeach** [comment] 2019-02-07 20:06
I would get a similar error where the new server was generated and then when it came time to let me enter the world it would give me the message "connection timed out". 

when consulting with discord they informed me the config files might be out of date but putting in the new files only caused me to not be able to create a server at all.

**Comment by aerodynamac** [comment] 2019-02-07 20:48
--BEGIN DUMP--
Dump Time
02/07/2019 11:53:19

Exception
Exception: NatDeviceNotFoundException
Message:Exception of type 'Open.Nat.NatDeviceNotFoundException' was thrown.
Source:Open.Nat

Open.Nat.NatDeviceNotFoundException: Exception of type 'Open.Nat.NatDeviceNotFoundException' was thrown.
   at Open.Nat.NatDiscoverer.<DiscoverDeviceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Eco.Plugins.Networking.UPnPMapper.<DiscoverNatDeviceAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Eco.Plugins.Networking.UPnPMapper.<CreateAsync>d__3.MoveNext()

--END DUMP--

This is the crash report I get in my dump file

**Comment by Pounce22** [comment] 2019-02-07 21:24
its been a while is anyone going to be assigned to this ticket?

**Comment by swilliams6694** [comment] 2019-02-08 03:49
Also having the same issue

**Comment by gabeux** [comment] 2019-02-08 04:03
+1 Happening with a player on my server

**Comment by ZaldaraBlackstan** [comment] 2019-02-08 04:13
Having this issue as well

**Comment by funnybunnyofdoom** [comment] 2019-02-08 05:08
Several players on my server are experiencing this, and similar issues. I did indeed follow the directions for the config files, and everything works properly except several of my players simply cannot connect.

**Comment by aerodynamac** [comment] 2019-02-08 15:06
Hey! Does everyone know their gpu/CPU type? My friends have been doing some tests with my account and think that my GPU/CPU isnt compatible with 8.0 for some reason. Just reverted myself back to 7.8.9 and it works just fine

**Comment by Pounce22** [comment] 2019-02-08 16:46
wow Aerodynamac i dont know mine either but i will try to revert back to 7.8.9 see if it works as well

**Comment by Pounce22** [comment] 2019-02-08 16:54
aerodynamac it works when you revert back to 7.8.9 woot

**Comment by Alyyyora** [comment] 2019-02-08 19:22
well but reverting back to 7.8.9 doesn't help when you're one of the admins on a big server though. My friend got to the point of frustration where he just wants his money back

**Comment by aerodynamac** [comment] 2019-02-08 19:24
I totally agree. I bought the game because all of my friends are playing in the same server on 8.0

**Comment by aerodynamac** [comment] 2019-02-08 21:37
I totally agree. I bought the game because all of my friends are playing in the same server on 8.0

**Comment by TheAggie2019** [comment] 2019-02-09 23:17
I'm experiencing the same issue, I was able to play fine last night (first time playing on 8.0) logged off for the night and when I attempted to re-connect I froze at the 90%. I uninstalled and re-installed the game, Re- installed steam, verified game files, downloaded the client side, modified config files, etc. Still nothing works. I run a I5-7th gen CPU, which is the same as a friend who can still sign in. It might be a GPU issue (I play on a laptop) but I have no way of testing it.

**Comment by mirasrael** [comment] 2019-02-11 07:29
@TheAggie2019 @aerodynamac do you experience this problem with every server or only with some of them?

**Comment by aerodynamac** [comment] 2019-02-11 11:02
@mirasrael All of the 8.0 servers.

**Comment by TheAggie2019** [comment] 2019-02-11 11:08
All of them.

**Comment by Pounce22** [comment] 2019-02-11 11:11
All of them

**Comment by Pounce22** [comment] 2019-02-11 11:20
Misrael here is what people on server see when i try to log on..
![serverconnection](https://user-images.githubusercontent.com/47409534/52560032-acefa980-2dbc-11e9-9db3-9919a669ae19.png)

**Comment by Pounce22** [comment] 2019-02-11 11:20
the above is me Mitzi logging in and then i crash at 90% load..

**Comment by mirasrael** [comment] 2019-02-11 11:38
@Pounce22 @aerodynamac @TheAggie2019  did you already try with 8.0.1 version? Can you attach client log?

**Comment by Pounce22** [comment] 2019-02-11 11:53
Hello mirasrael yes the above was when i attempted to log onto server with the 8.0.1 version this morning.

**Comment by aerodynamac** [comment] 2019-02-11 12:43
Yes. The same thing is happening to me.

**Comment by mirasrael** [comment] 2019-02-11 13:13
What about `output_log.txt` for your clients?

**Comment by aerodynamac** [comment] 2019-02-11 13:33
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2851219/output_log.txt)

**Comment by mirasrael** [comment] 2019-02-11 13:45
@aerodynamac can you submit info about your video card please? And about driver

**Comment by mirasrael** [comment] 2019-02-11 13:58
@aerodynamac (and other) can you try following work-around:
1. Go to your Eco installation directory
2. Create shortcut for Eco.exe
3. In shortcut settings add following option: -force-d3d9
Try to run Eco from shortcut
![image](https://user-images.githubusercontent.com/475445/52567847-4e5b1780-2e1e-11e9-922d-0f29df160dbb.png)

**Comment by mirasrael** [comment] 2019-02-11 14:00
It seems like a bug in Unity, 
https://steamcommunity.com/app/252470/discussions/4/2217311444321015271/
https://issuetracker.unity3d.com/issues/editor-slash-player-freeze-and-crash-with-error-message-d3d11-failed-to-create-buffer-after-moving-canvas
https://forum.unity.com/threads/d3d11-failed-to-create-buffer.496225/

@redwyre may be you know how to deal with it?

**Comment by aerodynamac** [comment] 2019-02-11 14:04
![image](https://user-images.githubusercontent.com/47409024/52568194-10d59a80-2ddc-11e9-9d6a-00f4cbafe630.png)

**Comment by mirasrael** [comment] 2019-02-11 14:12
@aerodynamac so you're using embedded video card?

**Comment by elfl0rd** [comment] 2019-02-11 14:15
Also addition to @mirasrael workaround.
You can add launch parameters in steam, e.g. if you not have an SLG account!
RMB at Eco in your library, propertions, general, "set launch options": -force-d3d9

**Comment by aerodynamac** [comment] 2019-02-11 14:19
@mirasrael Yes the card is embedded. Also, I tried that method and it did not work. Same error.

**Comment by mirasrael** [comment] 2019-02-11 15:10
@aerodynamac Thanks for information. We will look for solution. 
@TheAggie2019 @Pounce22 can you please provide your video card info and also let us know if work-around works for you?

**Comment by TheAggie2019** [comment] 2019-02-11 15:23
![image](https://user-images.githubusercontent.com/47487783/52572932-98bca400-2dde-11e9-9012-538c8b32f4ce.png)

The work around doesn't seem to work at all.

**Comment by TheAggie2019** [comment] 2019-02-11 15:24
When I first logged in to Eco I was able to play on 8.0 for over 4 hours. It was only when I signed off for the night I wasn't able to play.

**Comment by Pounce22** [comment] 2019-02-11 17:44
Hello i use intel (R)HD Graphics 620...is my video card my laptop is two years old..

**Comment by Pounce22** [comment] 2019-02-11 17:47
Hello no the workaround didnt work still got the same error message....

**Comment by redwyre** [comment] 2019-02-12 08:09
Can someone who's getting this error try changing you graphics settings (by pressing esc while at the main menu) to the following before trying to join a server:
![image](https://user-images.githubusercontent.com/431728/52620784-4ae49080-2ef1-11e9-94f8-feff2aefb594.png)

**Comment by mirasrael** [comment] 2019-02-12 08:25
@Pounce22 @aerodynamac @TheAggie2019 ping :)

**Comment by TheAggie2019** [comment] 2019-02-12 11:36
Already tried that the moment I suspected the GPU but didn't work.

**Comment by aerodynamac** [comment] 2019-02-12 12:45
Yep. I tried that as well. Didn't work.

**Comment by ZaldaraBlackstan** [comment] 2019-02-12 22:51
same here

**Comment by redwyre** [comment] 2019-02-12 23:12
Duplicate of #10891 but I'll leave this one open

**Comment by redwyre** [comment] 2019-02-12 23:20
So far this is confirmed on:
Intel(R) HD Graphics 620
Intel(R) HD Graphics 630
Intel(R) UHD Graphics 630
AMD Radeon(TM) HD 8610G (a little different but has the CreateDirect3D11SurfaceFromDXGISurface crash)

Anyone that hasn't already, can you post your graphics details or post your Eco log (%LOCALAPPDATA%Low/Strange Loop Games/Eco)?

**Comment by loaykr** [comment] 2019-02-13 07:10
@aerodynamac forgot to update this post, she fixed the issue by updating the graphic card driver, and also another friend of mine also fixed it by rolling back his graphic driver to an older version.

**Comment by Pounce22** [comment] 2019-02-13 12:17
hello this morning i rolled back my version of grapics card was able to log into 8.0.1 played ok then i went to nap came back attempted to log in again and i get the same error message. Yes i checked am still using the older version of my graphics card Intel(R) HD Graphics 620.?

**Comment by loaykr** [comment] 2019-02-13 12:34
@Pounce22 try to update it to the latest version that worked for the most players

**Comment by Pounce22** [comment] 2019-02-13 12:37
ok will do

**Comment by TheAggie2019** [comment] 2019-02-13 15:11
I run a Lenovo machine and I'm not sure how to check if my drivers are up to date, or even how to roll back to older drivers.

**Comment by Pounce22** [comment] 2019-02-13 18:57
ok i rolled back my graphics card, played for a few...logged off came back got the error.  So i upgraded to the latest graphics card which was what was installed from the start no newer one out there other than this 
 Intel(R) HD Graphics 620 logged on played for an hour fine now i cant log back in again error msg pops up but i bet if i roll back again it will let me play so what now?

**Comment by mirasrael** [comment] 2019-02-14 06:54
@Pounce22 can you confirm if machine reboot helps or not? From your description I assume it may be driver initialization issue.

**Comment by Pounce22** [comment] 2019-02-14 16:36
sorry no machine reboot does not help i still get the error

**Comment by swilliams6694** [comment] 2019-02-17 22:26
I'm running Intel(R) HD Graphics 620 and I was able to get it working by rolling it back

**Comment by Pounce22** [comment] 2019-02-19 19:19
hello any progress yet, dont want to be rush you or be rude just want to play soo bad its been a while

**Comment by SteelKraken** [comment] 2019-02-25 23:01
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2902986/output_log.txt)
Here is my log file.  Both my desktop and laptop utilize integrated Intel graphics cards.  Just got this game as a gift, and would love to play it.

**Comment by ZaldaraBlackstan** [comment] 2019-02-25 23:06
Not the best option, but a work around for me was to roll back my display driver. I'm able to play with lag while the issue is fixed.

**Comment by seccombew** [comment] 2019-02-27 02:47
@mirasrael Adding you back on here. Very critical issue that could use extra attention.

**Comment by mirasrael** [comment] 2019-02-27 14:16
https://drive.google.com/file/d/1vYQfOUKGHy2mjxLw7tZg7OzLe-b9LjEZ/view?usp=sharing can you download this Eco build (8.0.4 compatible) and try to run Eco using it. 
If it will crash then can you please: 
- go to %LOCALAPPDATA%\Temp\Strange Loop Games\Eco\Crashes
- archive to zip latest directory
- upload somewhere and put link into this issue
@Pounce22 @ZaldaraBlackstan @SteelKraken @aerodynamac

**Comment by P-Hidringer** [comment] 2019-03-02 06:09
I uploaded my crash log [here](https://drive.google.com/open?id=1ko02XMtCCiEa6PhGgwdoTBB64CTtNqxo) using Intel UHD 620 with the eco build you provided

**Comment by redwyre** [comment] 2019-03-02 06:18
Can you try with the command line option -force-glcore, with either that build or 0.8.0.5 (the latest release)

**Comment by P-Hidringer** [comment] 2019-03-02 06:27
I tried both through steam beta 0.8.0.5 and the provided build. In both cases the program now freezes at 90% instead of crashing.

**Comment by P-Hidringer** [comment] 2019-03-02 06:41
I tried around a bit with different open gl context versions. -force-glcore40 loads into the world, but has a lot of graphics artifacts.

**Comment by Yclee0206** [comment] 2019-03-03 08:33
Similar for me. (Intel(R) HD Graphics 5500)

-force-glcore40 works, but -force-glcore20 does not, the screen freezes at 'entering world', which has been my problem since 0.8.0.4

However the game is unplayable on glcore40. https://prnt.sc/msiow0 https://prnt.sc/msip17

**Comment by Pounce22** [comment] 2019-03-03 18:47
[Crashes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2923527/Crashes.zip)
hello here is my crash log data using the build you requested...attached is also a developer error code i noticed when the game was running before it crashed..

![ecoerror](https://user-images.githubusercontent.com/47409534/53699881-73560100-3db2-11e9-945c-575108d45caa.PNG)

**Comment by mirasrael** [comment] 2019-03-06 06:41
Btw, did anyone of you tried to run Eco 32-bit client version?

**Comment by mirasrael** [comment] 2019-03-06 06:42
@redwyre 
![image](https://user-images.githubusercontent.com/475445/53861099-282b3080-3ff4-11e9-9ad2-c97833cda981.png)
I analyzed crash dump, may be it will be useful for your communication with Unity team

**Comment by P-Hidringer** [comment] 2019-03-07 01:40
[Crash_2019-03-07_013705809.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2939075/Crash_2019-03-07_013705809.zip)
I tried the 32 bit version, now it crashes a bit later. In the crash log you can notice that this is probably an out of memory error, as no free RAM is left.

**Comment by mirasrael** [comment] 2019-03-07 05:40
Eco memory issue should be fixed in next patch (0.8.0.6). We also got response from Unity team, they confirmed it is a known issue and should be fixed in Unity 2018.3 (we're currently using 2018.2). We are working hard to migrate project to new version of Unity and expect to have it soon after 0.8.0.6 release (in 0.8.0.7 release).

**Comment by mirasrael** [comment] 2019-03-08 10:12
Btw, @Pounce22 and @P-Hidringer - thanks for trying with this exe and uploading crash logs. They helped with issue identification and was very useful when speaking with Unity support.

**Comment by Pounce22** [comment] 2019-03-08 11:47
You are most welcome thanks for working on this issue for us..

**Comment by P-Hidringer** [comment] 2019-03-12 14:14
Seems to be working on 8.0.6 again. Thanks!

**Comment by mirasrael** [comment] 2019-03-12 14:20
You're welcome! But it shouldn't :-P We didn't delivery yet patch which should fix this, but I suspect it was related to one of Unity plugins we used (which also caused memory leaks). And also probably it only happens under heavy load and memory consumption, so now it can just become more rare.
Anyway, happy to know you can play again!

**Comment by mirasrael** [comment] 2019-03-20 14:28
Does anybody still experiences this issue on latest build?

**Comment by Pounce22** [comment] 2019-03-22 09:51
No i have been able to play as normal.

**Comment by mirasrael** [comment] 2019-03-22 11:19
Closing it for now then. Feel free to re-open issue if you will have such issues again.

**Closed by mirasrael** 2019-03-22 11:19 UTC
Labels: Critical Priority
