### ISSUE TITLE
[0.9.0 staging-1489] Oil Drilling Upgrade

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15461] opened 2020-03-31 08:26 UTC
Version [0.9.0 staging-1489]

Oil Drilling Upgrade require advanced upgrade4 instead of modern upgrade4

**Comment by ThePiachu** [comment] 2020-03-31 08:54
Similarly, Smelting Upgrade requires Advanced Upgrade 4, instead of Basic Upgrade 4.

**Comment by WeaselDog** [comment] 2020-04-02 05:09
Thanks for the feedback. This will be fixed in the next update.

**Comment by beastyn** [comment] 2020-04-03 07:38
Smelting Upgrade works as intended

**Closed by beastyn** 2020-04-03 07:38 UTC
Labels: Priority: Medium, Status: Fixed
