### ISSUE TITLE
USER ISSUE: Player collision box faulty when using Hand Plow

### ISSUE THREAD

**Issue by LaTrissTitude** [StrangeLoopGames/EcoIssues#22673] opened 2021-09-17 01:57 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. have a wall of 3 high blocks
2. place a hand plow in front of it, player-side to the wall
3. pull cart
4. activate plowing (stay clicked)
5. go toward the wall in reverse (back to the wall)

**Expected behavior:**
@5, collision should stop the player from entering the block

**Actual behavior:**
the player enters the block and stays stuck until leaving the hand plow, and gets teleported to the top of the wall

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment] 2021-09-17 10:36
Hi @helldragger, really appreciate you reporting this to us, I can confirmed this is happening not only to dirt wall, but other walls too (brick, flat steel, etc..).

I have forwarded this issue to our devs to look into

**Comment by helldragger** [comment] 2021-09-17 11:27
Collateral issue:
**Steps to Reproduce:**
1. place a ramp and go in the middle of it (wall < 1 block)
2. place a hand plow directly against the wall, player-side to the wall
3. pull cart

**Expected behavior:**
The player should teleport behind the handplow directly without problems.

**Actual behavior:**
Both go flying around, probably due to the aforementioned teleportation giving too much inertia to the player going up

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Comment by WeaselDog** [comment] 2022-04-27 04:37
Thanks for your report. This will be fixed in the upcoming 9.5 update.

**Closed by WeaselDog** 2022-04-27 04:37 UTC
Labels: Category: Tech
