### ISSUE TITLE
USER ISSUE: Cannot Propose New Laws

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#6660] opened 2018-03-29 13:38 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Press Propose a New Law	

**Expected behavior:**
It should have taken me to the propose new law screen	

**Actual behavior:**
Instead it silently fails and adds an orange div to the top of my screen, while a meaningless "An Error has occured" JSON response is passed back with literally no other information. This highlights another problem in your system. Your error messages don't give us any feedback. With that JSON response, beyond knowing that a 500 response was sent, I should be able to say "It gave error code 1d107"

**Comment by MarjieAVolk** [comment] 2018-04-04 00:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4094

Usually, a proper error message shows in that red bar.  But a lot of people are getting this off-and-on issue with the red bar being empty.  Sometimes, if you close the tab and re-open it via the buttons in-game, the error messages will start working again.  (Doing this refreshes your login information on the page.

The most common cause for an error when proposing a new law is the default 'Citizenship' law.  This prevents you from proposing a law until you have played on that server for 2 hours.

**Closed by MarjieAVolk** 2018-04-04 00:53 UTC

**Comment by CuAnnan** [comment] 2018-04-06 17:15
This is not fixed. Please reopen.

**Comment by MarjieAVolk** [comment] 2018-04-06 17:28
I closed it as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4094 -- that is the thread where the issue is being tracked now :)
