### ISSUE TITLE
[0.9.0.1] Cement Kiln pollution not moving via pipes

### ISSUE THREAD

**Issue by Lagicrus** [StrangeLoopGames/EcoIssues#18203] opened 2020-09-12 13:24 UTC
Cement kiln seems to still produce air pollution even when you have a pipe network connected to it and moving it around 20~ blocks to the side and then up.
According to the kiln its valid.
It does the smoke effect.
But the graph still shows in bright colours the kiln being the source of the pollution.

Also, it seems to also produce ground pollution even though it says nothing about this?

**Comment by IcedForge** [comment] 2020-09-14 13:19
Adding pipes on exhaust piece, visually works; the exhaust is coming out of the pipe at the correct location but simulation is ignoring pipes.
This is not just cement kiln, this is any appliance that can connect 
![Screenshot_367.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/4b2dede4-262c-43ff-9dae-b72b39d3c7c7)
![Screenshot_368.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/b36f8cf4-e116-4b5f-b6ee-fbe61372af3c)
![Screenshot_369.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/4c4ca982-e138-41dd-a130-2848b227eb99)

expected results is Smog / Air pollution should come out where the pipe exhaust and visual smoke is happening.

**Comment by WeaselDog** [comment] 2020-09-15 01:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/17316

**Closed by WeaselDog** 2020-09-15 01:43 UTC
Labels: Category: Gameplay, Category: Tech, Priority: High
