### ISSUE TITLE
Cant pick up Fiddleheads

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1109] opened 2017-02-19 19:34 UTC
http://ecoforum.strangeloopgames.com/topic/1718/no-fiddleheads

**Comment by MarjieAVolk** [comment] 2017-02-22 00:22
I'm not able to reproduce this issue.  It may have already been fixed in our unreleased code

**Closed** 2017-02-28 23:54 UTC
