### ISSUE TITLE
7.8 Demographic laws do not show up on the webpage after being passed

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#9934] opened 2018-11-02 20:50 UTC

**Comment by D3nnis3n** [comment] 2018-11-03 05:47
They should get its own page like districts view, showing all demographics with their prerequisites and who is Part of that demographics.

**Comment by Deantwo** [comment] 2018-11-03 09:46
Isn't this a duplicate of #9893?

**Comment by D3nnis3n** [comment] 2018-11-03 09:46
A bit, but i cannot close issues of a developer ;P

**Comment by Deantwo** [comment] 2018-11-04 11:41
When implemented a webpage for this, it might be useful to keep in mind that we would like players with specific government titles to maybe have manually managed demographic groups. If the webpage is made with this in mind, it might be simpler to implement later.

**Comment by BlazeGuy2** [comment] 2018-11-05 18:42
dupe of #9893

**Closed by BlazeGuy2** 2018-11-05 18:42 UTC
