### ISSUE TITLE
Sign title too long, crashes server if removed

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#4974] opened 2018-02-23 01:41 UTC
![image](https://user-images.githubusercontent.com/7343272/36573771-683aab90-17f7-11e8-9cb7-0e59380e0977.png)

Some jerk made a sign with so much text.

When removed it crashed server.

**Comment by KillDevlicious** [comment] 2018-02-23 01:52
it only happens if you try to remove the text :) i took a hammer to the sign

**Comment by MarjieAVolk** [comment] 2018-02-23 20:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3002

**Closed by MarjieAVolk** 2018-02-23 20:25 UTC
