### ISSUE TITLE
USER ISSUE: Building Tutorial not completing

### ISSUE THREAD

**Issue by Regnoraak** [StrangeLoopGames/EcoIssues#23356] opened 2022-08-20 09:09 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
Build a house, with completed walls and roof, no gaps except a 2 block high, 1 block wide space for a door.

**Expected behavior:**
Tutorial should complete and recognise the house

**Actual behavior:**
The tutorial does not complete, the building is not recognised.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-08-22 22:40
Got a screenshot from outside and interior of the house? Not reproducable for me.

**Comment by CedricDx** [comment] 2022-08-25 20:28
@Regnoraak  It's not a bug, it's the building that's not built on your property.

@D3nnis3n A lot of new players are wrong, I had several similar questions on discord, the tutorial should be made clearer at this level

**Comment by D3nnis3n** [comment] 2022-08-31 16:31
Closing due to not reproducable and no further information given. Feel free to reopen if you have new information :)

**Closed by D3nnis3n** 2022-08-31 16:31 UTC
Labels: Status: Needs Information, Status: Not reproduced
