### ISSUE TITLE
USER ISSUE: Flying logs

### ISSUE THREAD

**Issue by Lovi84** [StrangeLoopGames/EcoIssues#4539] opened 2018-02-14 21:20 UTC
![2018-02-14 1](https://user-images.githubusercontent.com/36490090/36228717-9bca8ad8-119a-11e8-9796-8b1026db861c.png)
![2018-02-14](https://user-images.githubusercontent.com/36490090/36228718-9be07b0e-119a-11e8-8337-1fe84a44e5ac.png)
![2018-02-13 2](https://user-images.githubusercontent.com/36490090/36228719-9bfbd9e4-119a-11e8-89a2-3b9e5480b44c.png)

**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
Chop a tree, partially or completely... walk away to take logs to table... come back to flying tree or chopped logs	

**Expected behavior:**
Don't think things should just fly on their own

**Actual behavior:**
Literally flying away into the the atmosphere. Never returning.

**Comment by MarjieAVolk** [comment] 2018-02-14 21:23
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-14 21:23 UTC
