### ISSUE TITLE
USER ISSUE: chop tree crash

### ISSUE THREAD

**Issue by Reijm11** [StrangeLoopGames/EcoIssues#4310] opened 2018-02-11 11:34 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
chop a rondom log on the ground

**Expected behavior:**
give me logs

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-12 23:25
Closing as duplicate of #3752 . You can track the issue's progress there.

If you have any additional information about when or why this happens, or what kinds of trees it happens on, it would be very helpful if you posted that on the linked bug ^

**Closed by MarjieAVolk** 2018-02-12 23:25 UTC
