### ISSUE TITLE
Random Ground Pollution after server crash.

### ISSUE THREAD

**Issue by zinyaftw** [StrangeLoopGames/EcoIssues#24648] opened 2024-01-19 01:24 UTC
I wasn't online when the issue happened, but at some point our server derped and now we have a 300 radius circle of extreme ground pollution. and when i say extreme, I mean 3,000,000,000,000,000,000,000 pollution. Not sure how to provide data on the issue. I can literally upload my server folder if someone wants to run the server and see for themselves.

**Comment by D3nnis3n** [comment] 2024-01-19 04:22
Is that the same as this server? https://www.reddit.com/r/EcoGlobalSurvival/

This looks like a invalid bit flipped the number over.

**Comment by zinyaftw** [comment] 2024-01-19 10:49
Lol, yes, my mate posted that. Yeah, we're pretty sure it overflowed as just before it exploded, it went to a very large negative number first.

Anyone know what info I'd need to provide to possibly help locate the source of this issue?

**Comment by D3nnis3n** [comment] 2024-01-19 21:44
Instructions on how to reproduce, unfortunately. Otherwise it would be closed as one-off. From the savefile we cannot find out why it happened.

**Comment by D3nnis3n** [comment] 2024-01-24 00:01
Closing due to no reproduction steps available and no further reports received.

**Closed by D3nnis3n** 2024-01-24 00:01 UTC
Labels: Status: Needs Information
