### ISSUE TITLE
Server crash caused by law page, version 7.2.3 

### ISSUE THREAD

**Issue by Tinytina79** [StrangeLoopGames/EcoIssues#5757] opened 2018-03-09 11:58 UTC
When a player goes into the laws page to propose a law or vote, they can be  kicked for "Inactivity" from the server, sometime with other users. This prevents them from being able to do anything in the laws page as you need to be logged in. If the any of the players then tries to re-log into the server the whole server will crash. There are a number of crash reports generated related to both the player inactivity and crash event. see attached. We tested this for both closing the law page and not closing the law page before trying to get back onto the server.

[ClientNetworkException Exception 03092030.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1796751/ClientNetworkException.Exception.03092030.txt)

[ClientNetworkException Exception 03092035.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1796752/ClientNetworkException.Exception.03092035.txt)

[ClientNetworkException Exception 03092037.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1796753/ClientNetworkException.Exception.03092037.txt)

[Crash LiteException 03092039.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1796754/Crash.LiteException.03092039.txt)

thank you for your time,

the #1 Aussico Server

**Comment by MarjieAVolk** [comment] 2018-03-09 19:37
Ah man, didn't realize those interacted so badly.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343 and https://github.com/StrangeLoopGames/EcoIssues/issues/4104

**Closed by MarjieAVolk** 2018-03-09 19:37 UTC
