### ISSUE TITLE
[0.8.2.0 Staging-3] Trees Bug in Fastforward mode

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12032] opened 2019-04-15 09:45 UTC
1. Go to sleep
2. /fastforward 1
3. Wait 24 hours.
4. /fastforward 0
5.Wake up
I saw 2 trees missing. I wanted to plant new trees, but there were notifications: "Plants already exists there"
![image](https://user-images.githubusercontent.com/45708377/56121353-9d394080-5f78-11e9-939f-dbefa66d949e.png)
I also saw that the trees planted at the same time have a different size.
![image](https://user-images.githubusercontent.com/45708377/56121804-98c15780-5f79-11e9-8888-88ece68f7909.png)
6. Go to sleep
7. /fastforward 1
8. Wait 24 hours.
9. /fastforward 0
10. Wake up.
All trees are missing. Notification appeare again when I want to plant new trees.
I dug up Dirt. Сultivated Dirt. But I couldn't plant a tree. Notification appeared again.

**Comment by johnkslg** [comment] 2019-04-26 19:34
Reassigning because it will needs lot of knowledge of builders

**Comment by metachronism** [comment] 2019-04-26 19:56
trees dont use builders.  this looks like a simulation problem

**Comment by craig-jong** [comment] 2019-04-30 01:53
I'll look into this, but it sounds like the simulation still thinks theres a tree there.

**Comment by johnkslg** [comment] 2019-04-30 23:44
The problem is that when trees grow during fastforward, they try to rebuild but fail.

**Comment by craig-jong** [comment] 2019-05-02 00:01
It looks like it actually might have something to do with the trees dying.

@keegan-o how do we handle dead trees?

**Comment by SlayksWood** [comment] 2019-05-07 08:16
8.2.0 Staging-3.
1. Current yield is broken only at trees.
![image](https://user-images.githubusercontent.com/45708377/57283584-2810e500-70b8-11e9-9559-fd13b188ef26.png)
2. Trees often die immediately after planting (at least they are not shown in Soil Sampler). Visually, the tree was planted, but the Soil Sampler does not show it died (it was shown earlier)
![image](https://user-images.githubusercontent.com/45708377/57283927-de74ca00-70b8-11e9-99de-3d968116079b.png).
3. Trees don't grow visually in fastforward mode:
 - plant tree
 - /fastforward 1
 - wait some time
 - /fastforward 0
![2019-05-07 (21)](https://user-images.githubusercontent.com/45708377/57284195-57742180-70b9-11e9-997b-9cb2900c9a7a.png)
repeat
![2019-05-07 (23)](https://user-images.githubusercontent.com/45708377/57284235-6d81e200-70b9-11e9-8023-fd5942df6d21.png)

**Comment by craig-jong** [comment] 2019-05-07 18:57
Trees aren't going to grow in fast forward for 8.2. I'll check the other parts of the issue.

**Comment by SlayksWood** [comment] 2019-05-08 08:04
@craig-jong 
They do not grow even after disabling fastforward.
If you take garbage as an example:
- create garbage
- /fastforward 1
- wait 8 hours
- /fastforward 0
- when you disable fastforward garbage is converted to a new look.

**Comment by beastyn** [comment] 2019-05-09 10:50
Ok, so.
Which part should work in 8.2?
Sleeping trees went to the master
And I still see those trees which should be dead, but... well. I see them.
Can we move sleeping trees to staging?

**Comment by metachronism** [comment] 2019-05-09 18:00
also a dupe of #9057

**Comment by beastyn** [comment] 2019-05-09 18:07
Not in all parts. Im still waiting the answer for what should I get fixed in 8.2 about visible-dead-trees part

**Comment by craig-jong** [comment] 2019-05-10 20:50
https://github.com/StrangeLoopGames/Eco/pull/4423
Going into staging in this pull. Plants will disappear properly when they die, but their yield may be incorrect. Once this goes in I'm going to close this bug - if we should open one for displaying this growth visually, but that won't be in staging.

**Closed** 2019-05-14 18:54 UTC
Labels: Fixed, Medium Priority, QA, Staging
