### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by bender49330** [StrangeLoopGames/EcoIssues#6632] opened 2018-03-29 08:45 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**

 tous les serveur offline
**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-04-03 00:21
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5211

We are working on a rewrite of the join server page, so we will likely not address this until that is released.  Should be soon, fingers crossed.

**Closed by MarjieAVolk** 2018-04-03 00:21 UTC
