### ISSUE TITLE
no feedback on how to fuel a powered cart 

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1284] opened 2017-03-28 21:31 UTC
We should provide some sort of feedback to indicate allowed fuel types. Putting that info in the item tooltip would also be helpful.

**Comment by NafenX** [comment] 2017-06-06 18:20
Something like 'Requires **Solid Fuel/Liquid Fuel**' and when you hover over the Solid Fuel/Liquid Fuel text, a tooltip would show you all the different types.

**Comment by metachronism** [comment] 2017-06-07 21:57
dupe of #751

**Closed by metachronism** 2017-06-07 21:57 UTC
