### ISSUE TITLE
USER ISSUE: Bug with elevator

### ISSUE THREAD

**Issue by JU11111** [StrangeLoopGames/EcoIssues#22520] opened 2021-08-11 15:15 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Use elevator with multiple people close to it/ in it.

**Expected behavior:**
The industrial elevator should be working and in the same position for everyone 

**Actual behavior:**
It seems like the position of the elevator is out of sync for the different players and the server. So for one player the elevator is working properly for th otherone it seems like the player and the players vehicle is flying through the stationary elevator. in some sitúations it seems like the position is not updated for the server so the vehicle in the elevator at first moves with the elevator but then it falls through it into the elevator shaft. The problem can be fixed for a while when both players start spamming callpost buttons at the same time.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment] 2021-08-12 02:48
Hey @JU11111 thanks for reporting the issue.

However, this issue is a duplicate of #20738
You may refer to link above to follow up on this issue.

**Closed by Ry4ndrew** 2021-08-12 02:48 UTC
