### ISSUE TITLE
Oaks needs capping

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#5158] opened 2018-02-27 01:31 UTC
![image](https://user-images.githubusercontent.com/3536496/36705581-cc82547e-1b1a-11e8-923b-26cb375afd4e.png)

**Comment by Nanders** [comment] 2018-02-27 01:35
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3793

**Closed by Nanders** 2018-02-27 01:35 UTC
