### ISSUE TITLE
[0.9.4] Shovels don't work when assigned to hotkey 3?

### ISSUE THREAD

**Issue by Raienian** [StrangeLoopGames/EcoIssues#22548] opened 2021-08-21 04:29 UTC
Try: dig dirt with shovel selected when assigned to '3' on hotbar.
Result: nothing is happening.

On any hotkey other than 3, digging with a shovel works.
Using any other tool (pickaxe, axe, sickle, hoe) works on hotkey 3 but not shovel.

Tested with 2 separate players with same result.

**Comment by rmndmtrvch** [comment] 2021-08-21 06:42
Confirming the problem. I have the shovel assigned to a different slot, but the problem still appears. When I try to use the shovel on a block, it doesn't work. The problem is solved by switching to another tool and tapping it on the block (I switched to the hammer). After that, switch to the shovel and it works again. This problem occurs quite often.

**Comment by TwixterZ** [comment] 2021-08-21 15:47
Hi @Raienian & @rmndmtrvch thank you for raising this tickets, 

does this happens immediately after joining a 9.4 server or it is something that would happen occasionally after some time playing? 

Is this happening in specific server? any mods used?

**Comment by rmndmtrvch** [comment] 2021-08-21 16:51
@TwixterZ The problem occurs immediately after connecting to any server. No mods.

**Comment by rmndmtrvch** [comment] 2021-08-21 17:20
I have found several ways to cause the problem:

1 way:
1) go to 3-person view;
2) select Land Claim Stake;
3) point it at a few nearby sectors, but do not use it;
4) select your shovel, and you cannot dig with it;
5) switch to any other tool;
6) select your shovel again, and now you can dig.

2 way:
1) go to 3-person view;
2) select any free slot in your inventory and type the command "/give wooden shovel";
3) you will not be able to dig with it.

Sometimes it may not work, just move to another chunk or repeat the steps again.

**Comment by TwixterZ** [comment] 2021-08-23 08:35
@rmndmtrvch & @Raienian thank you for all the information given above, we confirm this is happening and have alerted our developers.

**Comment by SlayksWood** [comment] 2021-08-23 08:36
@rmndmtrvch Thank you for details. Yes, we have information about the problems of using the tools. I will merge this issue to #22257 and add problem with stake.

**Closed** 2021-08-23 08:37 UTC
Labels: Category: Tech
