### ISSUE TITLE
Minimap tree funkiness

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2172] opened 2017-09-19 00:29 UTC
![image](https://user-images.githubusercontent.com/3536496/30570588-f3287ad4-9c96-11e7-9cca-9c764fb99b43.png)

Floating above the ocean here

**Comment by metachronism** [comment] 2017-09-19 20:19
dupe of #2170

**Closed by metachronism** 2017-09-19 20:19 UTC
