### ISSUE TITLE
Server: rare crash while no players online.

### ISSUE THREAD

**Issue by espoire** [StrangeLoopGames/EcoIssues#11841] opened 2019-04-02 18:21 UTC
Server crashed overnight after multiple weeks of uptime, while either no players were playing, or possibly right at the time when a player attempted to connect. The chat log suggests the former, that this occurred when no players were playing. The most recent chat message was a block of identical periodic law messages:

_Notifications: UserNameREDACTED's property was unclaimed, by law Eminent Domain Act.

Since this law fires every 2.4 hours, and only occured one time in the ~8 hours between the time when I personally logged off, and the time when one of my players contacted me saying the server is offline, I am confident that the server crashed while nobody was playing.

I observed before logging off, that one of the offline player's "dot" was still visible on the map, despite them being offline. Given the nature of the below error message, I retroactively decided that this may be of importance. It is possible that the server crashed immediately after posting the periodic law message, when trying to send the message to the offline-but-dot-still-visible player?

Other things that our server did in the last day or so that weren't being done previously (meaning, they may be related to why this crash happened now, and not before):

New blast furnace (and thus, first-ever air pollution).
New elevator
New water filtration (and first-ever pipes with fluids).
New generator / electric energy sources & consumers

I found the following error upon returning to the server machine in the morning:
Error message details below

Windows error box

EcoServer has stopped working

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	EcoServer.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5c87e780
  Problem Signature 04:	System
  Problem Signature 05:	4.7.3353.0
  Problem Signature 06:	5c1ab603
  Problem Signature 07:	7a8
  Problem Signature 08:	12
  Problem Signature 09:	System.Net.Sockets.Socket
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	5fa7
  Additional Information 2:	5fa7b56217ff8f964c3d43b2ae67f0a0
  Additional Information 3:	7e06
  Additional Information 4:	7e063cb2ce213bcb75412f86360cd433

Windows debug program box

An unhandled Microsoft .NET Framework exception occurred in EcoServer.exe [3376].

Microsoft Visual Studio Debugger

System.Net.Sockets.SocketException was unhandled
Message: An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in Lidgren.Network
Additional information: The requested name is valid, but no data of the requested type was found

**Comment by espoire** [comment] 2019-04-02 18:58
Update: upon returning to the game, the elevator is misbehaving. The elevator car has somehow ended up in a VERY wrong location. The image below are the two elevator cables running diagonally through walls.

![image](https://user-images.githubusercontent.com/16272456/55428705-5185a080-554f-11e9-9dc2-664e4e3ad2a4.png)

**Comment by espoire** [comment] 2019-04-02 19:04
![image](https://user-images.githubusercontent.com/16272456/55428939-da044100-554f-11e9-9623-75706a5ccbfa.png)

![image](https://user-images.githubusercontent.com/16272456/55428950-de305e80-554f-11e9-81d6-663f57ce8bf5.png)

![image](https://user-images.githubusercontent.com/16272456/55429007-facc9680-554f-11e9-96ca-2615e1f41e65.png)

**Comment by espoire** [comment] 2019-04-03 05:01
I have concluded that the elevator nonsense and the server crash are likely unrelated problems. I believe the elevator nonsense is due to physics calculations disagreeing across multiple clients.

**Comment by mirasrael** [comment] 2019-04-04 07:14
Hi @espoire 
Thanks for report!
Did you use any DNS names in your server config? 
Actually this issue very hard to reproduce and identify cause so if it happen again - can you please make a server dump (Process explorer - Right click on EocServer.exe - Create dump file) and attach to this issue?

**Comment by espoire** [comment] 2019-04-04 21:34
Acknowledged regarding the dump file. I'm honestly unsure if I will ever see it again, given how long it took to occur in the first place. It's likely to be very rare.

I do not know if the server is using any DNS names. I never set any, so it would be only the defaults, if any.

**Comment by mirasrael** [comment] 2019-04-05 06:05
@espoire Yes, I understand. Unfortunately without enough information we can't identify and fix this :(

Do you still have an issue with elevator? If no how then did it fixed?

**Comment by mirasrael** [comment] 2019-04-10 12:21
Closed it for now, because don't seems we neither able to reproduce this neither understand if it fixed or not in latest version. If by any chance you will have this issue again and be happy to get a dump, please, feel free to re-open the issue.

**Closed by mirasrael** 2019-04-10 12:21 UTC
Labels: High Priority, Investigate, Needs Information
