### ISSUE TITLE
 [0.9.0 Staging 1446] Mortared Stone Bench (Any type) Hard to find Sit Option and when you do manage to sit down getting up puts you on top of seat also does not score as Furniture

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#15004] opened 2020-03-05 15:25 UTC
**Version:** 0.9.0.0 beta staging-1446

Very hard to find **exact** spot on Bench to Sit Down option
![snap6382](https://user-images.githubusercontent.com/29383891/75992745-520d8080-5ef0-11ea-99af-28c6bdfed73d.png)

If you are in a Room only Two blocks high Getting up from Bench Puts you on **top** of the bench and then you get Stuck with Head in the Roof
![snap6381](https://user-images.githubusercontent.com/29383891/75992861-84b77900-5ef0-11ea-8b5a-987914a1352b.png)

only way to get out of this stuck position is to remove Bench with Hammer or type /unstuck

as far as i can see there are **TWO TINY** hit boxes for the option to sit down
would be better if the whole part you actually sit on is a hit box
![snap6387edited](https://user-images.githubusercontent.com/29383891/75995406-49b74480-5ef4-11ea-8cfd-993c4693b6ae.png)
![snap6392edited](https://user-images.githubusercontent.com/29383891/75995424-5045bc00-5ef4-11ea-9b7d-260174e1cc6f.png)

Also does not count as Furniture for room
![snap6393](https://user-images.githubusercontent.com/29383891/75995991-20e37f00-5ef5-11ea-908e-7e2026aace72.png)

but i think that might be a Bug with **All Furniture** (not checked anything else) as placed a normal wooden chair to test and that doesn't even show up as being Furniture

![snap6394](https://user-images.githubusercontent.com/29383891/75996226-7881ea80-5ef5-11ea-9a34-2b2e6de7e5dc.png)

**Comment by Sekor2600** [comment] 2020-03-05 16:54
What is all in your Room? The Old Char is no longer ingame craftable

**Comment by SlayksWood** [comment] 2020-03-05 17:13
hard to sit #13906
Stuck with Head #10073
this issues closed as dup.
"Chair" isn't furniture now and you can't craft it.
Mortared stone bench give me 1,5 House value:
![image](https://user-images.githubusercontent.com/45708377/76006422-8186b200-5f1d-11ea-8e39-07857087df3d.png)
This issues closed as intended behavior and not reproduced.
If you still have some problem with craftable furniture, please create separate issue.

**Closed by SlayksWood** 2020-03-05 17:13 UTC

**Comment by Conchipedia** [comment] 2020-03-05 17:31
i only tried the Old chair as i have just masonry and not carpentry (so didn't know the recipes.
