### ISSUE TITLE
Staging: Graphical reflection issues

### ISSUE THREAD

**Issue by DragonSupremacy** [StrangeLoopGames/EcoIssues#10904] opened 2019-01-26 15:03 UTC
See screenshots. All bells and whistles enabled at 4K with a Ryzen 7 1700x & 2080ti. Turning down settings and/or disabling graphical options had no effect; only the absence of sunlight caused the issue to disappear, leading me to believe there's an issue with reflections on stone in a stockpile

![20190126155432_1](https://user-images.githubusercontent.com/841990/51788842-e9979000-2182-11e9-8619-7c3bfc5253c6.jpg)

**Comment by DragonSupremacy** [comment] 2019-01-26 15:05
For reference, the same stockpile at night:

![20190126160430_1](https://user-images.githubusercontent.com/841990/51788962-21eb9e00-2184-11e9-92a8-bd19dd394fd5.jpg)

**Comment by DragonSupremacy** [comment] 2019-01-26 17:11
Silhouette of a carpentry table is affected similarly, even when at night:
![20190126181013_1](https://user-images.githubusercontent.com/841990/51790447-c4604d00-2195-11e9-8d77-5ded617215a2.jpg)

**Comment by redwyre** [comment] 2019-01-26 22:48
Duplicate of #10804

**Closed by redwyre** 2019-01-26 22:48 UTC
