### ISSUE TITLE
USER ISSUE: can´t find mushrooms

### ISSUE THREAD

**Issue by Kimberlyv96** [StrangeLoopGames/EcoIssues#5918] opened 2018-03-11 19:09 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
can´t find mushrooms

**Expected behavior:**
should be able to find mushrooms

**Actual behavior:**
can´t find mushrooms

**Comment by MarjieAVolk** [comment] 2018-03-13 00:09
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Closed by MarjieAVolk** 2018-03-13 00:09 UTC
