### ISSUE TITLE
USER ISSUE: free falling

### ISSUE THREAD

**Issue by LoBlanc** [StrangeLoopGames/EcoIssues#4167] opened 2018-02-09 07:34 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. Enter a river
2. Find a broken map place
3. enter the hole

**Expected behavior:**
die after some time falling

**Actual behavior:**
I keep falling to infinite

**Comment by MarjieAVolk** [comment] 2018-02-20 22:04
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861

**Closed by MarjieAVolk** 2018-02-20 22:04 UTC
Labels: High Priority
