### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by DrNanfran85** [StrangeLoopGames/EcoIssues#24477] opened 2023-12-31 07:38 UTC
When building in 1st person, two things may happen depending on how the game wants to work:
1. Facial feature clipping into area, making it hard to see where block is being placed.
2. The block will not place in the correct spot at all and instead flashes on and off repeatedly, then remove a block underneath it.

**Comment by DrNanfran85** [comment] 2023-12-31 07:39
The second part also happens in 3rd person - the block will flash repeatedly and not place but will knock out what is next to it or below it depending on when the lmb is clicked.

**Comment by D3nnis3n** [comment] 2023-12-31 14:19
Cannot reproduce, can you provide a video?

**Comment by Yogu** [comment] 2024-01-01 12:46
I have an issue where the block to be placed flickers between two locations. Your descriptions sounds a little different though. I created a new issue (#24493) and attached a video there. @DrNanfran85 is this the behavior you experience, or do you have a different issue?

https://github.com/StrangeLoopGames/EcoIssues/assets/395810/6a19d16d-195e-4035-9526-5e0f711eca6f

**Comment by D3nnis3n** [comment] 2024-01-11 18:20
Closing due to not further information provided.

**Closed by D3nnis3n** 2024-01-11 18:20 UTC
Labels: Status: Needs Information, Status: Not reproduced
