### ISSUE TITLE
Chat is not showing up correctly

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7626] opened 2018-05-08 00:19 UTC
Via Forum: http://ecoforum.strangeloopgames.com/topic/4417/chat-nachrichten-nicht-lesbar

"Hello

since I play Eco and have a server, I can not communicate with others. I write something, in the server settings in the chat you can see it, but in-game not. Does anyone know advice?

In general, I have definitely written, if I write to people privately, it is not synonymous."

"I have the same problem. Some players on my server cannot read the chat. They can write and other players can see the message in the chat.

The server version is 7.3.3."

**Comment by MarjieAVolk** [comment] 2018-05-09 00:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7338  (I think that's what this person is saying?)

**Closed by MarjieAVolk** 2018-05-09 00:13 UTC
Labels: Medium Priority
