### ISSUE TITLE
World marker direction doesn't wrap

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2993] opened 2017-12-04 22:16 UTC
The world marker will often route you the long way to a point, because it doesn't wrap. 

i.e. in a 1000 x 1000 world, stand at 0, 1000 and place a world marker at 0, 1. The icon will appear to route you around the entire planet and say that you are 1000m away, rather than 1m.

**Comment by SeanAtr0n** [comment] 2017-12-04 22:18
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2910

**Closed by SeanAtr0n** 2017-12-04 22:18 UTC
