### ISSUE TITLE
Steam friend cannot join Singleplayer game but can join if i load the world as a server

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#19899] opened 2021-01-03 18:17 UTC
\
**Version:** 0.9.1.9 beta release-136

**Steps i Did**
A) Loaded up Eco Client Via Steam as normal
B) Created a Single player game under **Host a world** Called **Test** which has allow friends to join allowed
C) Started Playing **Test** world, Friend tried to join my game via Steam under friends using this
![snap7876](https://user-images.githubusercontent.com/29383891/103485422-11bbaf00-4dee-11eb-8a04-5a5b191cb405.png)
D) Friend couldn't join

**Workaround**
E) Renamed **Test.eco** and **Test.db** to **game.eco** and **game.db** in **G:\STEAM\steamapps\common\Eco\Eco_Data\Server\Storage** folder
(reason for this i wanted to make sure it was nothing to do with created world)
F) Ran the file **EcoServer.exe** found in **G:\STEAM\steamapps\common\Eco\Eco_Data\Server** folder 
this will Now load the default files **game.eco** and **game.db** (renamed singleplayer game) as i didn;t want to create a NEW world.
G) Loaded up Eco Client Via steam as normal
H) in **My worlds** joined my world Via LAN
I) Friend used same method to join my game using 
![snap7876](https://user-images.githubusercontent.com/29383891/103485605-74617a80-4def-11eb-815e-5feb40a53f6c.png)
J) Got into my world with no problems whatsoever (he did mention that on the previous attempt to join my singleplayer world Eco Client didnt load in automatically like it did for this workaround

wondering if the **EcoServer32.exe** is not loading in something from setting that the normal **EcoServer.exe** is doing

**Comment by Conchipedia** [comment] 2021-01-03 18:20
a lot of players have been having this problem of joining a Friends game via steam since 9.x version came out, so wondering if something has changed.
and i have never opened ports or portforwarded any since owning this game in 2017, friends could just jump in on my singleplayer world without anything being needed to be done my end.

**Comment by IcedForge** [comment] 2021-01-06 13:27
Not sure me and kirill did a lot of smaller tests in regards for this and we found that there are some circumstantial cases where the clients would not connect out of various reasons, mismatch versions, timeouts or misc but none of these errors were actually showing up, it would only give a generic "timed out" or just no msg at all.

**Comment by IcedForge** [comment] 2021-01-06 13:28
Related to #19598

**Comment by Conchipedia** [comment] 2021-01-06 13:36
quite a lot are New players who bought the game for each other so Mismatch version wouldn't have been an issue, just curious why running the ecoserver.exe will allow friend to join biut not hosting singleplayer (ecoserver32,exe in background)

**Comment by IcedForge** [comment] 2021-01-06 14:42
If you invite players to a server via steam friends, and you have not hosted the server it seems like steam can forget to actually send the server address to the client.
Player5.log
[12:37:26.294] Disconnected with error: The requested server was not found. It either doesn't exist, or is not registered on the master server.
@mirasrael can you take a look at this after you are back from vacation as priority as it is a huge problem for smaller groups and non public server players.

**Comment by mirasrael** [comment] 2021-01-21 08:25
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19598

**Closed** 2021-01-22 07:50 UTC
Labels: Community Manager, Priority: High, Squad: Pumpkin, Status: Investigate
