### ISSUE TITLE
USER ISSUE: Getting stuck while using objects (stockpiles, mill etc.)

### ISSUE THREAD

**Issue by PrincessCady** [StrangeLoopGames/EcoIssues#5422] opened 2018-03-05 17:48 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Open object for example stockpile, click rename button, esc or enter button to cancel.

**Expected behavior:**
Cancel renaming of object, movement allowed.

**Actual behavior:**
Cancels renaming, getting stuck. Can be solved by picking up the object or removing ground you are standing on.

**Comment by MarjieAVolk** [comment] 2018-03-05 19:30
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115.  This will be fixed in the next release.

**Closed by MarjieAVolk** 2018-03-05 19:30 UTC
