### ISSUE TITLE
USER ISSUE: Wanted to chuck a dead plant

### ISSUE THREAD

**Issue by Sebi92** [StrangeLoopGames/EcoIssues#5697] opened 2018-03-08 19:06 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei Eco.Simulation.Agents.Plant.Destroy()
   bei Eco.Simulation.Agents.Tree.Destroy()
   bei TreeEntity.Destroy()
   bei TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   bei Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   bei Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-08 19:57
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5619

**Closed by MarjieAVolk** 2018-03-08 19:57 UTC
