### ISSUE TITLE
USER ISSUE: Stockpile name softlock

### ISSUE THREAD

**Issue by aphadeon** [StrangeLoopGames/EcoIssues#4781] opened 2018-02-18 22:05 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
If you name a stockpile, and while naming press escape, your character becomes nonresponsive.

**Expected behavior:**
Closed the UI and allowed me to move.

**Actual behavior:**
Closes the UI and does not allow me to do anything afterwards until I relog.

**Comment by ecoemmeck** [comment] 2018-02-19 03:34
From what I've read this seems like a common bug with naming anything then pressing escape instead of clucking on the x

**Comment by MarjieAVolk** [comment] 2018-02-20 21:24
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

**Closed by MarjieAVolk** 2018-02-20 21:24 UTC
