### ISSUE TITLE
9.0.1 Sun/Moon light is too bright

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18307] opened 2020-09-17 12:40 UTC
Night time should actually be dark so that using light sources is advantageous and give actual purpose to using braziers and suc

Brightness at 100% in 9.0
![image](https://user-images.githubusercontent.com/61889138/93470943-968bc700-f8ea-11ea-9de0-9c17d443ed00.png)
![image](https://user-images.githubusercontent.com/61889138/93470969-9f7c9880-f8ea-11ea-8ebf-bd46ac25f7eb.png)

Brightness 100% 8.3.3
![image](https://user-images.githubusercontent.com/61889138/93471017-b0c5a500-f8ea-11ea-99f3-74702283510a.png)

Brightness at 300% in 8.3.3 is roughly same as 9.0 at 100%
![image](https://user-images.githubusercontent.com/61889138/93471076-c509a200-f8ea-11ea-85a5-898a499a5a70.png)

Brightness at 0% in 9.0 
![image](https://user-images.githubusercontent.com/61889138/93471111-d488eb00-f8ea-11ea-8f5b-23d43fc9ee7e.png)

Also at 0% but now its daytime, should be darker than this in a forest during the daytime due to tree cover

![image](https://user-images.githubusercontent.com/61889138/93471155-e8345180-f8ea-11ea-917a-604afb2a1842.png)

graphics settings below
![image](https://user-images.githubusercontent.com/61889138/93471207-f6826d80-f8ea-11ea-8b50-1dda269e46a4.png)

GTX 1660 on latest drivers.

**Comment by MishkaFur** [comment] 2020-09-17 12:49
both in 9.0
Midnight in desert in a mine, 0% brightness
![image](https://user-images.githubusercontent.com/61889138/93472334-66ddbe80-f8ec-11ea-948f-11815be9b3d8.png)

Midnight in desert in a mine, 100% brightness
![image](https://user-images.githubusercontent.com/61889138/93472403-7ceb7f00-f8ec-11ea-8237-52de8083ad88.png)

**Comment by TemporalWolf** [comment] 2020-09-17 18:53
If I try to play outside on my laptop midday vs in the darkness of my den drastically changes the experienced light level. The last two images are essentially solid black boxes to me given the bright ambient lightning at my location. If I walk into a dark room they are both easily discernible.

I'd be against artificially limiting brightness for balance reasons, especially given this isn't a competitive game. There are too many "valid" reasons for increasing brightness: ambient light, low hardware screen brightness, visual impairment, etc.

That being said, 9.0 is noticeably brighter than previous versions. Not sure if that is by design.

**Comment by keegan-o** [comment] 2020-09-18 17:37
We specifically decided not to make night and dark areas so dark that they require lighting objects in 9.0-- this decision was based on various things including ease of play, but also limited availability of various items and objects. We may tip the balance more towards requiring such objects for dark areas in the future, but our goal will likely be that they are still not required outside at night-- only inside caves. Things like a headlamp, etc, will probably have to be implemented before then, too. This will not be something we do for 9.1, however we are aware of various issues with lighting and particularly GI, so it will be something I continue to look at and work on. But for now and the medium length future at least, this is intentional.

**Comment by MishkaFur** [comment] 2020-09-18 18:26
Ah interesting yea does make sense though it does kind of mean that braziers, torches, candles, the new modern street lamps are not worth any investment gameplay wise unless you want additional light

re the forest lighting, I do not have GI enabled or is it because its disabled it causes it?

Soon as I enable GI my FPS dies

**Comment by keegan-o** [comment] 2020-09-22 20:17
Thanks, that's good to know as I had thought you had GI on in that screenshot. I recently fixed a bunch of problems with GI (it should also be more performant now) for 9.1 or possibly even an earlier patch. I'll have to investigate why the rainforest looks that bright.

One thing I will also say is that we will probably not be tuning anything to look good at brightnesses other than 100%, those settings exist to help with outlier situations like TemperalWolf described where there is some external situational or hardware reason for wanting to alter the brightness. It's possible the eye-adaptation and other things are interacting with the brightness setting in un-intended ways, too.

**Comment by keegan-o** [comment] 2020-09-22 20:20
In places like mines, it's a matter of balancing the ambient and post processing, since shadows are set to full '1' strength for the sun/moon, meaning no lighting from them is reaching those places directly-- what you are seeing is ambient lighting there (and we do want to tune that to be as dark as possible while still allowing relatively un-hindered play).

**Comment by MishkaFur** [comment] 2020-09-22 21:31
Never play with GI as it kills FPS, low makes it drop by 10 FPS, see GPU settings pic on the first post at the bottom

**Comment by Sarah-Graesyn** [comment] 2020-10-18 21:19
I have an Nvidia RTX 2060 and GI actually makes my PC struggle a bit right now as well so I tend to play with it off as well, I definitely should not be having an issue considering I custom built my tower and dropped $2000 US into it, most of that cost being a GPU, processor, and cooling rig

**Comment by keegan-o** [comment] 2020-10-20 19:11
Closing for now because my changes to the day/night ambient contribution should have fixed things like the overly bright rainforest, I would hope.

**Closed by keegan-o** 2020-10-20 19:11 UTC
Labels: Category: Gameplay, Priority: Medium

**Comment by legionaw** [comment] 2020-11-03 23:18
> We specifically decided not to make night and dark areas so dark that they require lighting objects in 9.0-- this decision was based on various things including ease of play, but also limited availability of various items and objects. We may tip the balance more towards requiring such objects for dark areas in the future, but our goal will likely be that they are still not required outside at night-- only inside caves. Things like a headlamp, etc, will probably have to be implemented before then, too. This will not be something we do for 9.1, however we are aware of various issues with lighting and particularly GI, so it will be something I continue to look at and work on. But for now and the medium length future at least, this is intentional.
> 
> The forest lighting is definitely broken, that falls under GI problems we'll be hoping to address as soon as we can.

@keegan-o First of all, let me apologize for commenting on a closed issue but I'd like to specifically respond to this. I get the ease of play thing as a reason for how bright the night are, I really do, but shouldn't that be up to the players or server owners? I would strongly advocate at least giving us an option to have night dark enough to require outdoor lighting if we want, at our risk. We shouldn't be protected from the perils of things like night being too dark.

On that topic, in absence of settings, world lighting could also be made moddable, assuming that it is currently hardcoded (I have not found any settings specifically for that in /Mods/ folder).
