### ISSUE TITLE
Visual bugs with bricks

### ISSUE THREAD

**Issue by Edgyasme** [StrangeLoopGames/EcoIssues#6257] opened 2018-03-18 21:31 UTC
![20180318140305_1](https://user-images.githubusercontent.com/37518068/37571378-20b25968-2afc-11e8-9aa5-24811c317d26.jpg)
![20180318140113_1](https://user-images.githubusercontent.com/37518068/37571379-20d3d8c2-2afc-11e8-8d75-b11884242abf.jpg)
![20180318140256_1](https://user-images.githubusercontent.com/37518068/37571380-20ef8004-2afc-11e8-8389-7f8bf852b3cf.jpg)

**Comment by CobaltEcho** [comment] 2018-03-18 22:25
Agreed, getting same behavior.

**Comment by MarjieAVolk** [comment] 2018-03-19 20:48
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4286

**Closed by MarjieAVolk** 2018-03-19 20:48 UTC
