### ISSUE TITLE
USER ISSUE: Smoke and water fountains

### ISSUE THREAD

**Issue by Eowarian** [StrangeLoopGames/EcoIssues#25163] opened 2024-09-15 10:21 UTC
\
**User Id: (354ae35c-d3d6-4006-3e4f-08dc8d11157e)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
1. Make a water connection
2. Run water through it
3. Disconnect the pipes so the water streams out of it
4. Reconnect the pipes

1. Do the same with a smoke exhaust

**Expected behavior:**
The water leak should disappear, but it doesn't.

Smoke should  stop coming out of the pipe as soon the engines stop

**Actual behavior:**
Water keep poring out of a connected pipe

The smoke keeps going, polluting the air (and ground) continuously...

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and no.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-09-15 16:51
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25145

**Closed by D3nnis3n** 2024-09-15 16:51 UTC
