### ISSUE TITLE
Contract Clauses break text if the contents strings are too long

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3535] opened 2018-01-19 23:20 UTC
![image](https://user-images.githubusercontent.com/3536496/35176155-42151d32-fd2c-11e7-8263-966b09011a2d.png)
Items In Container clause
I believe some of the others have issues as well, something to do with the table layout.

**Comment by LiaungYip** [comment] 2018-02-08 19:51
Still present in 0.7.0.5:

![image](https://user-images.githubusercontent.com/2173684/35994786-3697bcb2-0d5d-11e8-9ab2-92e7bc815c25.png)

**Comment by MarjieAVolk** [comment] 2018-03-23 19:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3295

**Closed by MarjieAVolk** 2018-03-23 19:11 UTC
Labels: Medium Priority
