### ISSUE TITLE
USER ISSUE: Failed to handle RPC method: OpenUI

### ISSUE THREAD

**Issue by HotBBQChicken** [StrangeLoopGames/EcoIssues#23838] opened 2023-05-24 07:14 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
1. Open shop menu
2. Glitch happenes, the menu says "closed" but the light is green and people can purchase items, however I, the owner, cannot interact with it.
*This all began after I placed a bed in the house that has the shop. The shop was working fine before this happened. Removing the bed does not solve the issue for me*

**Expected behavior:**
Opened the shop menu as normal

**Actual behavior:**
The shop menu says "closed" however the light is green. There are large letters spelling "closed" covering the menu, and everything is grayed out.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
The server I'm playing on uses mods, however it is "Fruity Society" on the official servers and no one else has this issue who I've asked.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-05-24 11:32
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23553. Please add your client logs over there after the issue happened.

**Closed by D3nnis3n** 2023-05-24 11:32 UTC
