### ISSUE TITLE
USER ISSUE: japanese names doesnt show over the characters

### ISSUE THREAD

**Issue by lukiono** [StrangeLoopGames/EcoIssues#7733] opened 2018-05-12 11:20 UTC
**Version:** 0.7.4.2 beta

**Steps to Reproduce:**
A player with a japanese nickname joins the server and has no name over the character

**Expected behavior:**
Name shown over the character

**Actual behavior:**
No name over the character

<details>
<summary>Log File</summary>(...previous log truncated...)

nentInParent[T] () [0x00001] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at UI.BaseItemUI.OnChange () [0x00000] in <45f4aa51d91f4ab1b372adc4941b6e4c>:0 
  at UI.ItemCollectionUI.OnChange () [0x00000] in <45f4aa51d91f4ab1b372adc4941b6e4c>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
[15:51] Exception in view notify: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Animator:SetBoolString (UnityEngine.Animator,string,bool)
  at UnityEngine.Animator.SetBool (System.String name, System.Boolean value) [0x00001] in <631a8b01f775461aaefeab8ef216af40>:0 
  at AvatarAnimationManager.UpdateWorking () [0x00016] in <45f4aa51d91f4ab1b372adc4941b6e4c>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <ed5ae244a8a54911b3c101b5d9e57b39>:0 
Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by Nanders** [comment] 2018-06-18 22:02
Do you know their name?

**Comment by Nanders** [comment] 2018-06-18 22:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6932

**Closed by Nanders** 2018-06-18 22:16 UTC
Labels: Medium Priority
