### ISSUE TITLE
[0.9.4 Develop-274] Unable to place upgrade module on crafting table inside rent property

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21711] opened 2021-05-01 04:04 UTC
Build: 0.9.4 Develop-274

## Issue
If you place a crafting table within the parameters of the rented space, you won't be able to place any upgrade module.

#### Reproduction Steps
1. Rent a property.
2. Place a crafting table with a module slot.
3. Try to place a supported upgrade module.
4. Observe.

#### Actual Result
Unable to place upgrade module to crafting table if the property is rented.

#### Video Repro
https://images.zenhubusercontent.com/42199084/62ef62b1-7125-4b4b-a825-c916bdd23a4e/eco_2021_05_01_11_49.mp4

**Comment by tuha263** [comment] 2021-05-03 15:47
Seem it worked as we expected. Residents (renter) only have `ConsumerAccess`, which can't do the action above.
Only `Onwer` or `UserWithFullAccess` can do it. I don't think we should add `Renter` into `UserWithFullAccess`

**Comment by WeaselDog** [comment] 2021-12-26 22:44
Closing as intended behavior for now.

**Closed by WeaselDog** 2021-12-26 22:44 UTC
Labels: Priority: Medium, Status: Needs Triage, Regression, Type: Bug, Category: Gameplay, Squad: Mountain Goat
