### ISSUE TITLE
Fast digging often catches another block then pointed

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8073] opened 2018-06-16 09:41 UTC
If digging with shovel and move the cursor too early away, a totally other block then original pointed is catched. It shouldn't be difficult to mark the pointed block as target when ticked with mouse. The current behavior can be annoying.

**Comment by Nicolausi113** [comment] 2018-06-16 10:39
I forgot - this happens also with road tool, scythe, maybe others.

**Comment by SeanAtr0n** [comment] 2018-06-18 21:57
This is intentional, the target is picked during the animation impact

**Comment by Nicolausi113** [comment] 2018-06-19 03:38
Hmm – if intention is to break fluency…? :(

**Comment by GophTheGreat** [comment] 2019-05-24 04:20
Not a bug? Closing for now.

**Closed by GophTheGreat** 2019-05-24 04:20 UTC
Labels: Medium Priority
