### ISSUE TITLE
USER ISSUE: Carts rename themselves back to default

### ISSUE THREAD

**Issue by IneaFaedyn** [StrangeLoopGames/EcoIssues#24506] opened 2024-01-02 14:36 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Name a cart, in this case a wood cart

**Expected behavior:**
The cart should be renamed and the name should stick.

**Actual behavior:**
The cart gets renamed, but the name resets itself back to the default "FirstLast's Wood Cart" after a period of time

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-03 10:03
Cannot reproduce, any more information how to get this? Note the name will reset if its picked up and placed again.

**Comment by D3nnis3n** [comment] 2024-01-11 18:18
Closing due to no further information provided.

**Closed by D3nnis3n** 2024-01-11 18:18 UTC
Labels: Status: Needs Information, Status: Not reproduced

**Comment by IneaFaedyn** [comment] 2024-01-11 21:39
Thanks! Yeah sorry, I think it was me picking things up and not realizing. Will re-open if it comes up again.
