### ISSUE TITLE
Users with special characters in their passwords can't log into the game

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#11302] opened 2019-02-13 22:39 UTC
User could log into his account on the website fine.

User couldn't log into the game ("Invalid username or password" error) until he changed his password to one with non-special characters (in this case, his previous password had a "%" and a "-").

**Comment by D3nnis3n** [comment] 2019-02-13 23:00
Have both of these symbols in my password and can log in just fine. Any more Information?

**Comment by D3nnis3n** [comment] 2019-02-22 12:39
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11092

**Closed by D3nnis3n** 2019-02-22 12:39 UTC
Labels: Needs Information
