### ISSUE TITLE
public server crash reports, happening 1 min apart till server is taken off-line

### ISSUE THREAD

**Issue by Tinytina79** [StrangeLoopGames/EcoIssues#5071] opened 2018-02-25 07:40 UTC
i have gotten both of these server crash reports several times today and thought i would seek help for them. server goes down and reboots, just logs are filling up our storage.
-BEGIN DUMP--
Dump Time
02/25/2018 12:15:57
 
Exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
   at System.Linq.Buffer1..ctor(IEnumerable1 source)
   at System.Linq.OrderedEnumerable1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable1 source)
   at Eco.Gameplay.Skills.Skillset.get_Title()
   at Eco.Gameplay.Minimap.MinimapObjectExtensions.ToBson(IMinimapObject minimapObj)
   at Eco.Gameplay.Minimap.MinimapManager.<>cDisplayClass35_0.<GetUpdatedMinimapObjects>b1(IMinimapObject obj)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action1 action)
   at Eco.Gameplay.Minimap.MinimapManager.GetUpdatedMinimapObjects(INetObjectViewer viewer, Boolean only_updated)
   at Eco.Gameplay.Minimap.MinimapManager.SendUpdate(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetObjectUpdates(IEnumerable`1 objects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()
 
--END DUMP--

--BEGIN DUMP--
Dump Time
02/25/2018 16:55:47
 
Exception

   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
 
--END DUMP-- #

**Comment by Tinytina79** [comment] 2018-02-25 09:29
After this happened people on my blacklist could also login to world again even thought there details are still in the blacklist, regardless of SLG id or steam.

**Comment by MarjieAVolk** [comment] 2018-02-26 20:13
@metachronism The first one, I can fix easily, so I have done that.  The second one I am not sure about.

**Comment by MarjieAVolk** [comment] 2018-02-26 20:17
@Tinytina79 The first one at least is related to concurrency problems - in this case, looks like someone was using the minimap at the same time as someone else was learning a new skill.

Oh, I realized the second one is the same as https://github.com/StrangeLoopGames/EcoIssues/issues/4368

So going to close this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368 - The first dump will be fixed in the next release.

**Closed by MarjieAVolk** 2018-02-26 20:17 UTC
Labels: High Priority
