### ISSUE TITLE
USER ISSUE: Stockpile duplication

### ISSUE THREAD

**Issue by Egzee** [StrangeLoopGames/EcoIssues#4133] opened 2018-02-08 21:18 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Just placing it, it stays in inventory.

**Expected behavior:**
Cleaning out from inventory

**Actual behavior:**
Duplicating, cant place, but icon dissapears on placing it in chest altough if i select the slot it still comes up.

**Comment by ecoemmeck** [comment] 2018-02-08 21:30
From what I've seen this is an issue with the icon not disappearing when the item is placed. However if you place something over where the icon is it disappears normally. Perhaps the inventory hotbar isn't updating quickly enough

**Comment by MarjieAVolk** [comment] 2018-02-09 02:17
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3905

We have seen this a bit, and it is a display bug, where the icon in your inventory doesn't go away.  We are still looking for a fix.

**Closed by MarjieAVolk** 2018-02-09 02:17 UTC
