### ISSUE TITLE
[7.6.2] Need additional features with law to fix economy

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#8657] opened 2018-07-20 16:20 UTC
To be able to fix economy, we want to ve able , for exemple to force be people sell items > XX currency
the idea is to force people:
Sell/buy wood for exemple for 5 currency or more
We need a law that be able to check when people buy/sell that item if unit price is > or < or = a certain amount of currency
we need that the system is able to check when people buy/sell one by one or multiple by multiple

**Comment by D3nnis3n** [comment] 2018-11-11 14:09
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9412

**Closed by D3nnis3n** 2018-11-11 14:09 UTC
Labels: Feature
