### ISSUE TITLE
[8.0.7] Tree stump mesh collider lives on

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#11709] opened 2019-03-18 16:45 UTC
Version: 0.8.0.7 beta

Steps to Reproduce:
Cut down a tree, before you cut it into logs, remove the stump.

Expected behavior:
The stump should disappear and no collider should exist where the stump used to be.

Actual behavior:
The model disappears but the mesh collider seems to stay there until you finish cutting the whole tree.

Do you have mods installed? Does issue happen when no mods are installed?:
At time of occurance, only DiscordLink.

**Comment by D3nnis3n** [comment] 2019-03-19 14:34
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11359

(At least i think so, feel free to shout, if not)

**Closed by D3nnis3n** 2019-03-19 14:34 UTC
Labels: Investigate, Medium Priority
