### ISSUE TITLE
7.2.0 Staging Branch - Server Crash (Fishing / Fishing Pole)

### ISSUE THREAD

**Issue by Nashable** [StrangeLoopGames/EcoIssues#5075] opened 2018-02-25 11:58 UTC
5 Players on a server. Seems to be caused when a player was using a fishing pole to catch fish (most times he did not get the fish and then the server would crash shortly afterwards)

> --BEGIN DUMP--
> Dump Time
> 02/25/2018 03:49:33
> 
> Exception
> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
>    at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
>    at Eco.Plugins.Networking.QuadTree`1.Remove(T item)
>    at Eco.Plugins.Networking.QuadTreeNetObjectCollection.OnObjectMoved(INetObjectPosition obj)
>    at Eco.Simulation.Agents.Animal.Tick()
>    at Eco.Simulation.Simulation.TickAll()
>    at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
>    at Eco.Simulation.EcoSim.DoTick(TickSample tick)
>    at Eco.Simulation.EcoSim.Run()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart(Object obj)
> 
> --END DUMP--
>

**Comment by Nashable** [comment] 2018-02-25 19:31
Continued to observe the error and seemed to manifest when the same player opens fish traps and tried to remove trout. Other fish (e.g. Salmon) were fine.

**Comment by Devilz80** [comment] 2018-02-26 02:03
I have the same problem, when my mate trying to catch fish, he don’t get the fish and many seconds later the server crash with the same dump.

**Comment by MarjieAVolk** [comment] 2018-02-26 19:57
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4916 - Will note your observations there.  If you have any more details, feel free to comment.

**Closed by MarjieAVolk** 2018-02-26 19:57 UTC
