### ISSUE TITLE
USER ISSUE: Drag & Drop Item Stuck

### ISSUE THREAD

**Issue by Macludde** [StrangeLoopGames/EcoIssues#5901] opened 2018-03-11 15:18 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Drag an Item
2. Item sometimes get stuck while dragging and stays on the screen where it got stuck. I think mouse is faulty and sends signal that it's not being held down anymore. Item shouldn't get stuck just because of that.

**Expected behavior:**
Item should have not gotten stuck

**Actual behavior:**
Item gets stuck on the screen until you log out and back in again. Server thinks its in its original position, client doesn't. Cannot interact or see item in it's original position.

**Comment by MarjieAVolk** [comment] 2018-03-13 00:38
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

This seems to be related to rapid clicking, which some mice might do without you realizing.  If you use a different mouse, you may see this problem less.

**Closed by MarjieAVolk** 2018-03-13 00:38 UTC
