### ISSUE TITLE
USER ISSUE: disconnect every 10min

### ISSUE THREAD

**Issue by Slamess** [StrangeLoopGames/EcoIssues#4544] opened 2018-02-14 23:31 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
a friend create a new world :
- no collaboration
- authorize friends to join
- world generated
- skill on craft

I get disconnect from my friend's server every 10min on fixed hours (15h10 -> 15h20 -> 15h30 -> ....).
If I reconnect to the server immediately, I can see my character neer me undisconnected, and my friend and I get disconnected because of crash server.
But when I wait until the server inform my friend of my deconnection, and connect after, the server doesn't crash.

**Expected behavior:**
Be able to play on a private server without disconnection every 10min
Doesn't have crash server on immediate reconnection

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   à Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   à Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   à Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   à Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   à Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-15 00:02
Is the error message you posted one that you usually see when this problem happens?  Or is it unrelated to the other behavior you described?

**Comment by Slamess** [comment] 2018-02-15 00:16
This error message appear when the server crash. I've reconnect immediately after being disconnected, and one minute after, my friend and I get disconnected again with this message.

**Comment by MarjieAVolk** [comment] 2018-02-15 00:30
Okay.  Well, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4222

I had some theories about this bug, but I will probably have to re-examine, as I thought it was only seen as a server crash, not as a disconnection message

**Closed by MarjieAVolk** 2018-02-15 00:30 UTC

**Comment by Slamess** [comment] 2018-02-15 00:36
Thanks, I hope the "disconnection every 10min" issue will be resolved with it. Good luck !
