### ISSUE TITLE
USER ISSUE: "Plant already exists there"

### ISSUE THREAD

**Issue by PermanentEdding** [StrangeLoopGames/EcoIssues#6827] opened 2018-04-01 06:14 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Plant tomao seeds normally, let them grow, pick em up.
Repeat a few times. After a while some blocks will say "Plant already exists there" if you want to place seeds again.
Even placing another block there wont fix it. Removing the dirt block wont fix it either.

**Expected behavior:**
Plant seed

**Actual behavior:**
Cant plant seed. ("Plant already exists there")

**Comment by w3re** [comment] 2018-04-02 11:07
Experiencing the same issue. The soil sampler says there's still a dead plant on the tile. We also have an issue with blocks disappearing from the world in some places with seemingly the same cause (soil sampler indicates a dead plant which noone can see).

**Comment by vintrove** [comment] 2018-04-02 19:26
Hey! Same issue here. I've tried planting dirt on top of the broken spots, but post server restart the dirt will vanish and the plant will stay. Also the new plant I planted on top of the dirt spot stayed.

https://cdn.discordapp.com/attachments/258375026435162112/430440594762891264/unknown.png

**Comment by MarjieAVolk** [comment] 2018-04-02 21:28
Thanks for the additional information. Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4669

**Closed by MarjieAVolk** 2018-04-02 21:28 UTC
