### ISSUE TITLE
USER ISSUE: character doesnt move 

### ISSUE THREAD

**Issue by skidz8426** [StrangeLoopGames/EcoIssues#25013] opened 2024-07-25 13:13 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
slept in bed before logging off last night. 
I logged on and my toon was standin in bed but asleep 
I was in 3rd person I play in 1st 
when I changed to 1st person I could see my teeth and eyes 

**Expected behavior:**
be right lol 

**Actual behavior:**
bad 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I do not but I think the server does.   I also don't know 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-07-25 23:36
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23981, workaround is to not log out sleeping currently.

**Closed by D3nnis3n** 2024-07-25 23:36 UTC
