### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Sevidra** [StrangeLoopGames/EcoIssues#6053] opened 2018-03-14 20:05 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Had a cart with stuff in it (mortared stone, gold ore) and had gold ore in hand.  Went into cart inventory near a stockpile.  Went to move stockpile up in the order of things, and click to make it linked.  Suddenly...

**Expected behavior:**
Uh... done what it was supposed to do?  Moved the stockpile up in the order and let me get on with inventory manageme

**Actual behavior:**

Caught exception:

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-15 21:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-15 21:40 UTC
