### ISSUE TITLE
USER ISSUE: Alligators Despawn when stepped upon

### ISSUE THREAD

**Issue by Regonoth** [StrangeLoopGames/EcoIssues#20285] opened 2021-01-31 17:01 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.2.2 beta release-149

**Steps to Reproduce:**
1. Find an alligator
2. tread on it

as a side note, Personally i do not have this happen (server owner) but ive witnessed this happen almost every time anyone else plays with the gators

**Expected behavior:**
Alligators should not despawn when stepped on

**Actual behavior:**
Despawns :|

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2021-01-31 19:32
Hi @Regonoth, thank you for reporting this. However, I am unable to reproduce this issue. Do you mean, by chance, that the Alligators are submerging and passing through a block that makes it look like despawning? If not, could you provide a video of the said issue, please? Thank you.

**Comment by Regonoth** [comment] 2021-02-09 21:49
Hey after much attempted to get it on video it seems like either the player
that reported this to me was lying or a server restart had made the
alligators respect physics.

**Comment by Daniel-Magulado** [comment] 2021-02-16 05:50
Related #19851

**Comment by Daniel-Magulado** [comment] 2021-04-24 11:02
Reopening
Tested on 0.9.3.2 Release-213.

Alligators despawn when stepped on.

To reproduce;
1. Find an Alligator on land.
2. Step on them.
3. Observe.

Video

https://user-images.githubusercontent.com/77248866/115956488-906c6180-a52f-11eb-8a96-634ba50f14b4.mp4

**Comment by WeaselDog** [comment] 2021-06-14 21:47
This should be fixed in 9.4

**Comment by SlayksWood** [comment] 2021-06-15 08:05
Checked on 0.9.4 staging-2021 seems fixed.

**Closed by SlayksWood** 2021-06-15 08:05 UTC
Labels: Category: Gameplay, Priority: Low, Squad: Otter, Status: Fixed, Type: Bug
