### ISSUE TITLE
Crane so big it disappears sometimes.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8105] opened 2018-06-19 22:36 UTC
https://imgur.com/a/5vjd2ka

**Comment by SeanAtr0n** [comment] 2018-06-19 22:40
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8062

**Comment by metachronism** [comment] 2018-06-20 00:11
(closing as dupe)

**Closed by metachronism** 2018-06-20 00:11 UTC
Labels: Medium Priority
