### ISSUE TITLE
USER ISSUE: Impossible to connect

### ISSUE THREAD

**Issue by Kefran1981** [StrangeLoopGames/EcoIssues#4365] opened 2018-02-12 00:28 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
- Have a steam link problem and 2nd char created on a server
- Try to connect on this server

**Expected behavior:**
Sometimes it asks me to choose one of the two characters (the unselected never been deleted as suggested), other time (several hours long) error below occured.

**Actual behavior:**
<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Plugins.Networking.Clients.Client.ShouldSelectUser()

**Comment by MarjieAVolk** [comment] 2018-02-13 02:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4413

We already have a fix for this, which should be available in the next release.  Unfortunately, you may not be able to connect to that server until the fix goes out.  You should be able to play on other servers.

**Closed by MarjieAVolk** 2018-02-13 02:05 UTC
