### ISSUE TITLE
Hard fps drops

### ISSUE THREAD

**Issue by apnotix** [StrangeLoopGames/EcoIssues#6820] opened 2018-03-31 22:36 UTC
Hello.

The performance of the game is horrible since 0.7.3. With "Good" settings there are only 25fps. 

My PC is not the problem. FarCry 5 with ultra settings or Battlefield with ultra settings has no fps problems @ 4k resolution.

**My Specs:**
16 GB DDR 4 - 3000 MHZ 
Intel i7 - 5820k 12 Core @ 3.8 Ghz
Zotac GTX 1080 AMP Extreme

**Comment by H4nSolo** [comment] 2018-03-31 23:41
Confirmed!
always when i am looking to my Claim Area or House on the Claim, my FPS drop dramaticly.... from 40 to 4 - 12

**Comment by MarjieAVolk** [comment] 2018-04-04 21:46
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6957

@H4nSolo A performance problem related to claiming property was fixed recently, have you checked whether this has improved in the latest version?

**Closed by MarjieAVolk** 2018-04-04 21:46 UTC
