### ISSUE TITLE
Vehicles: Disappearing Vehicles until server restart/refresh 8.0

### ISSUE THREAD

**Issue by iForby** [StrangeLoopGames/EcoIssues#11223] opened 2019-02-09 13:36 UTC
After being tested on my server several different ways: It appears vehicles (carts, steam-truck, etc) disappear when you travel with them outside of render-distance and then relog. The only fix is a server restart/refresh, however the issue remains the same if you travel outside of render distance again.

**Comment by elfl0rd** [comment] 2019-02-09 15:59
Duplicate of #11108

**Closed by elfl0rd** 2019-02-09 15:59 UTC
