### ISSUE TITLE
USER ISSUE: Ubuntu Double Type

### ISSUE THREAD

**Issue by JonHoye** [StrangeLoopGames/EcoIssues#4520] opened 2018-02-14 14:03 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
iInnssttaallll  oonn  uubbuunnttuu..  rRuunn..

**Expected behavior:**
tTyyppiinngggn  oonnllyy  pprroodduucceess  oonnee  cchhaarraacctteerr  eeaacchh  kkeeyy  pprreesseedd

**Actual behavior:**
tTyyppiinngg  pprroodduucceess  ttwwoo  cchhaarraacctteerrss  ffoorr  eeaacchh  kkeeyy  pprreesssseedd..

**Comment by JonHoye** [comment] 2018-02-14 14:05
You wouldn't believe how hard it was to get a password with an odd number of characters into the password screen, when backspace and delete also register twice on each press.

Also note: It's on key down that both characters get entered.

**Comment by SeanAtr0n** [comment] 2018-02-14 17:28
this issue seems to be steam related, if you launch with steam it should work normally

**Comment by MarjieAVolk** [comment] 2018-02-14 21:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3580

**Closed by MarjieAVolk** 2018-02-14 21:11 UTC
