### ISSUE TITLE
Some contract clauses breaking table layout

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6388] opened 2018-03-23 01:19 UTC
When shrinking the size of the contract, text in some of the clauses will compress and go vertical. I wasn't able to tell what differentiated the clauses that behaved properly with the ones that failed, they both had the tablelayout assigned the same.    

To repro, drag all contract clauses into a parent gameobject that has vertical sorting, then shrink it horizontally to see the problem.

![image](https://user-images.githubusercontent.com/3536496/37806456-55bcdd00-2dfd-11e8-8671-47b601d29701.png)

**Comment by johnkslg** [comment] 2018-03-23 01:21
In game view:
![image](https://user-images.githubusercontent.com/3536496/37806534-c5ad4366-2dfd-11e8-959f-f0a4bc31a1af.png)

**Comment by MarjieAVolk** [comment] 2018-03-23 19:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3295

This happens if the width of the table is smaller than the preferred width.  It then falls back to minimum width, and TMP text always has a minimum width of 0.

**Closed by MarjieAVolk** 2018-03-23 19:12 UTC
