### ISSUE TITLE
Can't start solo game [Server issue]

### ISSUE THREAD

**Issue by Dem9** [StrangeLoopGames/EcoIssues#4898] opened 2018-02-21 07:54 UTC
When starting solo game ecoserver.exe crashes after starting some plugin

Win10. last version
Before buying game i have a pirate copy. but i unistall it and clears registry.
Reinstall do not help
![default](https://user-images.githubusercontent.com/24937149/36468630-2da07346-16f5-11e8-9c1f-f0952c3f10d0.png)

[Crash AggregateException 02214751.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1743206/Crash.AggregateException.02214751.txt)

**Comment by Dem9** [comment] 2018-02-21 08:25
I can start solo only if i start server from server folder and then connect to localhost via join game

**Comment by MarjieAVolk** [comment] 2018-02-22 23:43
```
   в System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   в Eco.Core.Serialization.EcoSerializer.Initialize()
   в Eco.Core.Plugins.StorageManager..ctor()
```

**Comment by MarjieAVolk** [comment] 2018-02-22 23:43
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4305

**Comment by MarjieAVolk** [comment] 2018-02-22 23:44
Try generating a new world with 'Generate new' checked.  Most people had success with that when they say this problem.

**Closed by MarjieAVolk** 2018-02-22 23:43 UTC
