### ISSUE TITLE
USER ISSUE: Not connecting

### ISSUE THREAD

**Issue by superbumpi** [StrangeLoopGames/EcoIssues#3914] opened 2018-02-05 08:01 UTC
**Version:** 0.7.0.1 beta

**Steps to Reproduce:**
Attempt to join, load or create a game

**Expected behavior:**
load game

**Actual behavior:**
completes all action, attempts to connect. No error, returns to main menu

**Comment by jarckn** [comment] 2018-02-05 08:54
Well, this seems to be pretty similiar to #3910.
You tried this with a local singleplayer game, right?

If you try this with a dedicated server, you may see something in the server console. Something like the message I've appended to the linked issue.

**Comment by MightyPiggie** [comment] 2018-02-05 10:33
Dont load the game on steam. There are some bugs with eco and steam. Download Eco from the official site. Here is 7.0.1: https://s3-us-west-2.amazonaws.com/eco-releases/EcoPC_v0.7.0.1-beta.zip But you might need another version. It depends on how fast the server updates. https://ecoauth.strangeloopgames.com/home Here you can download the latest version.

**Comment by Nanders** [comment] 2018-02-05 11:08
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3910

**Closed by Nanders** 2018-02-05 11:08 UTC
