### ISSUE TITLE
USER ISSUE: Picking up a Log

### ISSUE THREAD

**Issue by Arouko** [StrangeLoopGames/EcoIssues#5240] opened 2018-02-28 20:03 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Loaded my World
2. Walked around
3. Found a piece of Log
4. Picked one Log up
5. Game crashed

**Expected behavior:**
The Game should have added the logs to my carry inventory.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-28 20:04
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-28 20:04 UTC
