### ISSUE TITLE
USER ISSUE: Road tool cant be repaired

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3612] opened 2018-01-24 07:39 UTC
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Road tool cant be repaired when u try it crashes you or gives error it also shows no resrouces to be used to repair it.

**Expected behavior:**

**Actual behavior:**

**Comment by kkusch** [comment] 2018-01-24 08:56
Duplicate of #3845

**Comment by MarjieAVolk** [comment] 2018-01-24 18:52
Yes it's a duplicate, thanks.  This has been fixed but the fix has not yet been released.  It will definitely be fixed in the next release, I'm thinking about how to hot fix it also, so will see

**Closed by MarjieAVolk** 2018-01-24 18:52 UTC
