### ISSUE TITLE
USER ISSUE: Caught Exception

### ISSUE THREAD

**Issue by balloonhead** [StrangeLoopGames/EcoIssues#6231] opened 2018-03-18 11:32 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. hold Shovel
2. grab Treewood from the ground

**Expected behavior:**
Wood goes into Carrying-Inventory

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-21 18:56
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5595

**Closed by MarjieAVolk** 2018-03-21 18:56 UTC
