### ISSUE TITLE
USER ISSUE: Bug chat typing

### ISSUE THREAD

**Issue by Mousstik18** [StrangeLoopGames/EcoIssues#5888] opened 2018-03-11 11:23 UTC
**Version:** 
_Client_ 0.7.2.3 beta
_Server_ 0.7.2.3 beta
_Mods Install_ Clays Toolskit v3.1.1 & DiscordLink v1.1.1

**Steps to Reproduce:**
Exemple in video of the bug
https://mousstik.wesiin.com/eco/index.html

**Expected behavior:**
I try without all mods and problems not fixed

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC SendChat on ChatManager!

La clé donnée était absente du dictionnaire.


Stack:
   à System.ThrowHelper.ThrowKeyNotFoundException()
   à System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   à LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   à LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   à LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   à LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   à LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   à LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   à LiteDB.LiteCollection`1.Insert(T document)
   à Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   à Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   à Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)



Stack:
   à Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   à Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   à Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   à Eco.Shared.Networking.NetPort.ProcessBuffer()
   à Eco.Shared.Networking.NetPort.Update()
   à Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

Sorry i'm french user and my english is limited

**Comment by MarjieAVolk** [comment] 2018-03-13 00:52
Thank you! Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5681

**Closed by MarjieAVolk** 2018-03-13 00:52 UTC
