### ISSUE TITLE
[USER ISSUE][Linux] Very High CPU usage

### ISSUE THREAD

**Issue by Nephitos** [StrangeLoopGames/EcoIssues#5683] opened 2018-03-08 16:46 UTC
**Version** 0.7.2.2 beta

**Config** amd FX6200 (6 x 3.8Ghz) & amd RX480 (open drivers)

The game uses around 60% cpu with view distance at minimum, and around 80% with more normal settings. I think my computer shouldn't be struggling so much with the game, am I right?

**Comment by lefavilla** [comment] 2018-03-08 18:06
#5640

**Comment by MarjieAVolk** [comment] 2018-03-08 22:27
Thanks, closing as duplicate of #5640.  We are working on fixing performance problems asap.

**Closed by MarjieAVolk** 2018-03-08 22:27 UTC

**Comment by Nephitos** [comment] 2018-03-09 15:11
No changes after 0.7.2.3.

I add informations:

I'm only playing with the **client** on **linux** (without steam) and on **someone else server** (that works fine for other people). I tested some other servers and the issue is the same.

Also, sometimes, the writings disappear in the escape menu (and only there). I don't if it has something to do with CPU issues. If it persists, I'll post another bug report.

My CPU usage:
On the main menu : 20%
Ingame : 55% at the very least (with view distance at minimum)



The only thing I get when starting the game command line is (I don't have steam installed) :
Unable to preload the following plugins:
	ScreenSelector.so
	libCSteamworks.so
	libsteam_api.so
Logging to /home/nephitos/.config/unity3d/Strange Loop Games/Eco/Player.log
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.

**Comment by MarjieAVolk** [comment] 2018-03-09 22:11
The text disappearing issue is reported here: https://github.com/StrangeLoopGames/EcoIssues/issues/5749
