### ISSUE TITLE
SUGGESTION: Idle Unclaim

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5222] opened 2018-02-28 14:47 UTC
As seen in other survival games, a configurable idle unclaim with deletion of the users property and belongings (as in a full reset, so if the player comes back he is like a fresh player with claims again and zero skillpoints) seems becoming needed for a good server administration. For every player that stays for a long time, get's big and contributes much to the world there are 4 players that just claim and leave or build a little house and leave. This has lead to place problems especially when trying to centralize in districts in order to cooperate the most. For now, i manually unclaim everything and transport everything  from their belongings to the capital city in form of expropriation - but this can take ages with threehundredfifty trees killed but then leaving the server without even having built a road. A deletion for this would be appreciated.

As we are playing on a 90 Days to Meteor Server, 30 days seems suitable for autodeletion.

**Comment by Huntermeign** [comment] 2018-02-28 14:57
repeat of #4549

**Comment by MarjieAVolk** [comment] 2018-02-28 19:20
Closing as duplicate of #4549 

Thanks for the additional opinion.  I am thinking that we will want a way to delete/reset users.

**Closed by MarjieAVolk** 2018-02-28 19:20 UTC
