### ISSUE TITLE
USER ISSUE: Shot creatures can't be picked up (50% of the time)

### ISSUE THREAD

**Issue by Lawnikky** [StrangeLoopGames/EcoIssues#24923] opened 2024-05-06 13:28 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.2 beta release-660

**Steps to Reproduce:**
shoot the creature

1. you will either get the green outline and be able to pick up
2. you will get the green outline and it will disappear as you approach (can't pick up)
3. you won't get the green outline (can't pick up)

**Expected behavior:**
It should have retained the green outline, thus enabling the creature to be picked up

**Actual behavior:**
Instead, the green outline disappears (around 50% of the time), thus preventing the creature to be picked up

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, but the issue has only just appeared and we have been playing with the current mods for 10 in game days.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-05-06 16:36
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24138

**Closed by D3nnis3n** 2024-05-06 16:36 UTC
