### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by alexandrage** [StrangeLoopGames/EcoIssues#4564] opened 2018-02-15 07:05 UTC
**Version:** 0.7.1.2 beta
--BEGIN DUMP--
Dump Time
02/15/2018 01:39:21

Exception
System.NullReferenceException: Object reference not set to an instance of an object
  at Eco.Core.Controller.ControllerInstanceInfo+<>c.<CleanupBoundClients>b__16_0 (Eco.Shared.Networking.INetClient boundClient) [0x00000] in <61d6f8e3e2354670aeb9311383020549>:0 
  at System.Collections.Immutable.ImmutableList`1+Node[T].RemoveAll (System.Predicate`1[T] match) [0x00020] in <36486b016d234fca8cd67892bf29c7b5>:0 
  at System.Collections.Immutable.ImmutableList`1[T].RemoveAll (System.Predicate`1[T] match) [0x0000b] in <36486b016d234fca8cd67892bf29c7b5>:0 
  at Eco.Core.Utils.ThreadSafeList`1+<>c__DisplayClass14_0[T].<RemoveAll>b__0 (System.Collections.Immutable.ImmutableList`1[T] x) [0x00000] in <61d6f8e3e2354670aeb9311383020549>:0 
  at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T] (T& original, System.Func`2[T,TResult] apply) [0x00007] in <61d6f8e3e2354670aeb9311383020549>:0 
  at Eco.Core.Utils.ThreadSafeList`1[T].RemoveAll (System.Predicate`1[T] match) [0x0001f] in <61d6f8e3e2354670aeb9311383020549>:0 
  at Eco.Core.Controller.ControllerInstanceInfo.CleanupBoundClients () [0x00006] in <61d6f8e3e2354670aeb9311383020549>:0 
  at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers () [0x00058] in <61d6f8e3e2354670aeb9311383020549>:0 
  at Eco.Core.Controller.ControllerManager.Run () [0x000d0] in <61d6f8e3e2354670aeb9311383020549>:0 
  at Eco.Server.PluginManager+<>c__DisplayClass18_0.<StartPlugins>b__0 (System.Object x) [0x00000] in <b4b94cd2c5cd4d04b63c8ec9d80be5c8>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in <2e7c1c96edae44d496118948ca617c11>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <2e7c1c96edae44d496118948ca617c11>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <2e7c1c96edae44d496118948ca617c11>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <2e7c1c96edae44d496118948ca617c11>:0 
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x0000f] in <2e7c1c96edae44d496118948ca617c11>:0 

--END DUMP--

crash every 10 minutes

**Comment by MarjieAVolk** [comment] 2018-02-23 20:07
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368

**Closed by MarjieAVolk** 2018-02-23 20:07 UTC
