### ISSUE TITLE
USER ISSUE: Icon stuck in middle of screen

### ISSUE THREAD

**Issue by dlouwers** [StrangeLoopGames/EcoIssues#6228] opened 2018-03-18 11:07 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
- Have a laggy client 
- Drag item from inventory to store

**Expected behavior:**
Moved from inventory to chest

**Actual behavior:**
Icon got stuck on the screen. Relogging does not fix it. Alt-tabbing does.

**Comment by Gringar** [comment] 2018-03-21 14:53
Looks like the same issue as #3841. I also posted the below comment on #3841 

This behavior also leaks outside of Eco when the game is running if you have it alt tabbed. I hold left click down while Eco is open and instead it's like I'm clicking rapidly. I close Eco and my mouse returns to normal immediately. I also use Windows 10, 64bit. Up to date on updates. My mouse is a Logitech wireless. M705. Battery is 100% and definitely in range. No issue with the mouse since it works fine while Eco is closed but as soon as the Eco service is running... haywire.

I may have found a workaround that seems to be fixing the problem for me so far. That is to run the game in compatibility mode for Windows 7. Steam version you can right click Eco in the Library > Properties. Local Files and Browse Local Files... Then you can right click the Eco file there and set the Compatibility Mode in Properties. Non-Steam version it's probably easier to find the launcher. You shouldn't need help there.

So Eco must not be playing nice with Windows 10 somehow. I hope you can track it down eventually but I've been testing the workaround ~~while writing this~~ for a few days now and it seems to be working fine where without compatibility mode it was terrible.

**Comment by MarjieAVolk** [comment] 2018-03-21 18:10
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

@Gringar thanks for investigating this.  That is interesting.  Most of us develop on Windows 10 and don't see this issue, so that is odd.  I have heard that it is related to specific mice also.

**Closed by MarjieAVolk** 2018-03-21 18:10 UTC
