### ISSUE TITLE
USER ISSUE: possible ghost log?

### ISSUE THREAD

**Issue by TunaOddfellow** [StrangeLoopGames/EcoIssues#4134] opened 2018-02-08 21:39 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
went to pick up a log I had left behind.  The log I remember looked brown, but I just ran up and hit E.  Maybe there was a ghost in the asset server?

**Expected behavior:**
Picked up a log

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-09 02:15
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

We have gotten a number of reports of this.  It seems to be related to logs left lying around, and logs that float in the air.  We are still investigating

**Closed by MarjieAVolk** 2018-02-09 02:15 UTC
