### ISSUE TITLE
After mining block hole left in terrain

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10787] opened 2019-01-20 14:31 UTC
Looks like the chunk didn't re-mesh properly.

![image](https://user-images.githubusercontent.com/431728/51440503-9b623700-1d13-11e9-9dd8-627146ab0e26.png)

After placing block nearby it corrected iteself.

**Comment by seccombew** [comment] 2019-01-24 22:31
Need repro case.

**Comment by D3nnis3n** [comment] 2019-04-23 04:31
No reproduction case found, closing therefore. Please reopen when you reoccur and can reproduce.

**Closed by D3nnis3n** 2019-04-23 04:31 UTC
Labels: Needs Information

**Comment by enexusde** [comment] 2021-02-05 12:32
Request for Reopen: 
![image](https://user-images.githubusercontent.com/6880636/107033484-a5014f00-67b5-11eb-91c5-7fa160708d6a.png)

Op reported me this issue. 

As you might see, there is a big hole in the water on the left, near to the mine on the right. At 1:10pm there was no such hole in the water, at 1:25 there surprisingly exists this hole in the water. The Op guarantees that he did not build that hole on the left but that mine on the right. 

Looks like some kind of floatingpoint-problem?

Server is a linux server. Client is windows.

**Comment by D3nnis3n** [comment] 2021-02-05 16:50
There has been a message for reopen but its now gone? Reopen still needed?

**Comment by redwyre** [comment] 2021-02-06 01:10
The image on the now-removed post shows a different issue, something like a chunk disappeared.

**Comment by enexusde** [comment] 2021-02-06 08:36
Yes, I found a better matching issue and moved my comment to the better matching issue.
