### ISSUE TITLE
USER ISSUE: UNABLE TO JOIN FRIENDS SERVER THROUGH STEAM

### ISSUE THREAD

**Issue by KT99-explorer** [StrangeLoopGames/EcoIssues#25059] opened 2024-08-18 00:21 UTC
\
**User Id: (ed2314dd-84b8-4ef7-59d2-08dcbefc6db7)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
1. OPEN ECO
2. PRESS SHIFT+TAB
3. RIGHT CLICK THE FRIEND WHO IS HOSTING THE SERVER, SCROLL DOWN TO JOIN GAME.
4. CHOOSE JOIN GAME
5. ERROR CODE SHOULD APPEAR.

**Expected behavior:**
JOINED THE HOSTS GAME THROUGH STEAM.

**Actual behavior:**
The following error message popped up:
```
The requested server was not found (ID = 3841ec29-9cb3-48c9-ac68-73f738b47fc3). It either doesn't exist, or is not registered on the master server.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO MODS INSTALLED. THIS ISSUE OCCURS NATURALLY. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-08-18 15:37
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25052

**Closed by D3nnis3n** 2024-08-18 15:37 UTC
