### ISSUE TITLE
Steam (only) user logged in as citizen with limited menu options

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#21632] opened 2021-04-28 21:31 UTC
when user logs into game, on main menu it says in corner `Logged in as limited citizen account Account Name`

so steam user is being detected as a citizen for some reasons.

**Comment by D3nnis3n** [comment] 2022-07-18 09:44
Closing issue due to old age and bever being reproduced.

**Closed by D3nnis3n** 2022-07-18 09:44 UTC
Labels: Status: Needs Information, Squad: Lattice Mushroom
