### ISSUE TITLE
USER ISSUE: Unable to join any coop or servers

### ISSUE THREAD

**Issue by ghostbitingmist** [StrangeLoopGames/EcoIssues#24333] opened 2023-12-20 15:41 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
i have tried joining countless servers and invited my friend to join me in a coop world but they cant join me nore can i join them or any servers

**Expected behavior:**
Joined the servers or coop worlds

**Actual behavior:**
The following error message popped up:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-20 22:55
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24331

**Closed by D3nnis3n** 2023-12-20 22:55 UTC
