### ISSUE TITLE
Duplicate item crash

### ISSUE THREAD

**Issue by efflixi** [StrangeLoopGames/EcoIssues#2975] opened 2017-12-03 19:37 UTC
I made a campfire on a new save, placed the campfire and still had it in my toolbar. I moved it to another slot and my game crashed with this:

```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on ToolbarInventory!

Object reference not set to an instance of an object


Stack:
  at Eco.Gameplay.Items.Inventory.CheckAuthForMove (Eco.Gameplay.Items.ItemStack source, Eco.Gameplay.Items.ItemStack target, Eco.Gameplay.Players.Player player) [0x00078] in <071117917d3e49a6a2afb540ca89a8a8>:0 
  at Eco.Gameplay.Items.Inventory.MoveItems (Eco.Gameplay.Items.ItemStack sourceStack, Eco.Gameplay.Items.ItemStack targetStack, Eco.Gameplay.Players.Player player) [0x0000e] in <071117917d3e49a6a2afb540ca89a8a8>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <a07d6bf484a54da2861691df910339b1>:0 



Stack:
  at Eco.Shared.Networking.RPCManager.TryInvoke (System.Object controller, System.String methodname, Eco.Shared.Serialization.BSONObject bsonArgs, System.Object& result) [0x0007a] in <9af3c5ddab7c4f4eb238d4e1a618b256>:0 
  at Eco.Shared.Networking.RPCManager.InvokeOn (Eco.Shared.Serialization.BSONObject bson, System.Object controller, System.String methodname) [0x0005f] in <9af3c5ddab7c4f4eb238d4e1a618b256>:0 
  at Eco.Core.Controller.ControllerManager.HandleViewRPC (System.Guid controllerID, System.String methodname, Eco.Shared.Serialization.BSONObject bson) [0x00007] in <0c5eb26028c84e10a908f60cff482391>:0 
  at Eco.Plugins.Networking.Clients.Client.ViewRPC (System.Guid guid, System.String methodname, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <614150dd01d94955850170411f5b1280>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <a07d6bf484a54da2861691df910339b1>:0
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on ToolbarInventory!

Object reference not set to an instance of an object


Stack:
  at Eco.Gameplay.Items.Inventory.CheckAuthForMove (Eco.Gameplay.Items.ItemStack source, Eco.Gameplay.Items.ItemStack target, Eco.Gameplay.Players.Player player) [0x00078] in <071117917d3e49a6a2afb540ca89a8a8>:0 
  at Eco.Gameplay.Items.Inventory.MoveItems (Eco.Gameplay.Items.ItemStack sourceStack, Eco.Gameplay.Items.ItemStack targetStack, Eco.Gameplay.Players.Player player) [0x0000e] in <071117917d3e49a6a2afb540ca89a8a8>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <a07d6bf484a54da2861691df910339b1>:0 



Stack:
  at Eco.Shared.Networking.RPCManager.TryInvoke (System.Object controller, System.String methodname, Eco.Shared.Serialization.BSONObject bsonArgs, System.Object& result) [0x0007a] in <9af3c5ddab7c4f4eb238d4e1a618b256>:0 
  at Eco.Shared.Networking.RPCManager.InvokeOn (Eco.Shared.Serialization.BSONObject bson, System.Object controller, System.String methodname) [0x0005f] in <9af3c5ddab7c4f4eb238d4e1a618b256>:0 
  at Eco.Core.Controller.ControllerManager.HandleViewRPC (System.Guid controllerID, System.String methodname, Eco.Shared.Serialization.BSONObject bson) [0x00007] in <0c5eb26028c84e10a908f60cff482391>:0 
  at Eco.Plugins.Networking.Clients.Client.ViewRPC (System.Guid guid, System.String methodname, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <614150dd01d94955850170411f5b1280>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <a07d6bf484a54da2861691df910339b1>:0
```

**Comment by efflixi** [comment] 2017-12-03 20:20
I should note this was on Linux using 6.1.2 also using the server on Linux run with mono and -nogui. Server was up for 7 days straight before I wiped the map to start over.

**Comment by MarjieAVolk** [comment] 2017-12-05 20:12
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2864

We've also seen this on our playtest server, so shouldn't be linux related.

**Closed by MarjieAVolk** 2017-12-05 20:12 UTC
