### ISSUE TITLE
USER ISSUE: Transfer Ownership Bug

### ISSUE THREAD

**Issue by AstralBlader** [StrangeLoopGames/EcoIssues#24527] opened 2024-01-03 22:48 UTC
\
**User Id: (slg219906)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Transfer Owner to someone else

**Expected behavior:**
Ownership transfered

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes but should not interfere

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-04 04:25
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24521

**Closed by D3nnis3n** 2024-01-04 04:25 UTC
