### ISSUE TITLE
USER ISSUE: BUG

### ISSUE THREAD

**Issue by aclard** [StrangeLoopGames/EcoIssues#5867] opened 2018-03-10 23:32 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
I don t know. I was planting Oaks, and came across a piece of logs that i gathered.Then crashed
Everything seemed normal as usual.

**Expected behavior:**
Should have just carry those 5 pieces of lumber

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à TreeEntity.PickupLog(Player player, Guid logID)
   à TreeEntity.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   à Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   à Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   à Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   à Eco.Shared.Networking.NetPort.ProcessBuffer()
   à Eco.Shared.Networking.NetPort.Update()
   à Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by Bobondacob** [comment] 2018-03-11 00:15
related to #5862

**Comment by Bobondacob** [comment] 2018-03-11 00:31
related to #5862 ?

**Comment by aclard** [comment] 2018-03-11 01:10
The conditions in wich I managed to trigger this bug do not seems to be the same.
I let you decide if you attach it to #5862 [https://github.com/StrangeLoopGames/EcoIssues/issues/5862] or not
Le 11/03/2018 01:30:41, G. Bennett <notifications@github.com> a écrit :
related to #5862 [https://github.com/StrangeLoopGames/EcoIssues/issues/5862] ?

**Comment by MarjieAVolk** [comment] 2018-03-12 21:01
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5595

**Closed by MarjieAVolk** 2018-03-12 21:01 UTC
