### ISSUE TITLE
USER ISSUE: new game and ghost door follow me?????????

### ISSUE THREAD

**Issue by MindzEye1** [StrangeLoopGames/EcoIssues#23161] opened 2022-05-11 05:05 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
i hosted a new game and as soon as i logged in i had this image and have no inventory

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no,yes
![newgame](https://user-images.githubusercontent.com/105331555/167773007-7f82f78d-f04e-495a-947d-9507efacef6b.jpg)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-05-12 17:20
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23160

**Closed by D3nnis3n** 2022-05-12 17:20 UTC
