### ISSUE TITLE
USER ISSUE: Connection timed out

### ISSUE THREAD

**Issue by Gamegamb** [StrangeLoopGames/EcoIssues#22505] opened 2021-08-03 09:35 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1.  Join a server and play a bit on it
2. Leave the server and wait sometime
3. Try and connect again

**Expected behaviour:**
It should have let me connect to the server

**Actual behaviour:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I do not have mods installed

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6923095/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6923093/Player.log)

**Comment by Zackey** [comment] 2021-08-05 06:39
Same as https://github.com/StrangeLoopGames/EcoIssues/issues/22500 :)

**Comment by Daniel-Magulado** [comment] 2021-08-05 18:20
Hi @Gamegamb 

Our development team has addressed this issue. Kindly check if you're still encountering or having difficulties with establishing, connecting, or playing with a friend. Do let us know if any issue arises. Looking forward to your reply.

**Comment by Gamegamb** [comment] 2021-08-06 20:32
Hi @Daniel-Magulado 

I havent had any issues in the last 3 days so it seems like the problem is solved. But if i encounter the problem again i Will let you know.

**Comment by Daniel-Magulado** [comment] 2021-08-06 20:42
Hi @Gamegamb 

We're delighted that the issue is now fixed for you. Thank you so much for taking the time to let me know.
If you even encounter any issues in-game, please do not hesitate to file a bug report. I'll be closing this ticket as a fix.

**Closed by Daniel-Magulado** 2021-08-06 20:42 UTC
Labels: Status: Needs Information
