### ISSUE TITLE
USER ISSUE: lag when using crafting bench

### ISSUE THREAD

**Issue by NathanMisset** [StrangeLoopGames/EcoIssues#7327] opened 2018-04-21 17:30 UTC
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
1. press E on craftingbench
2. lag

**Expected behavior:**
no lag

**Actual behavior:**
lag

**Comment by WeaselDog** [comment] 2020-05-17 04:09
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3110

**Closed by WeaselDog** 2020-05-17 04:09 UTC
Labels: Category: Optimization, Priority: Medium
