### ISSUE TITLE
USER ISSUE: Crash to title

### ISSUE THREAD

**Issue by SirKahvi** [StrangeLoopGames/EcoIssues#4707] opened 2018-02-17 14:41 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Gather logs while jumping

**Expected behavior:**
Crash to title

**Actual behavior:**
Crash to title

**Comment by MarjieAVolk** [comment] 2018-02-23 21:49
Did you get any error messages when this happened?

**Comment by MarjieAVolk** [comment] 2018-02-27 01:13
Closing due to not enough information.  Likely a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-27 01:13 UTC
