### ISSUE TITLE
"Report a bug" button on escape menu does not work

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3288] opened 2018-01-09 02:12 UTC
Ironic

**Comment by MarjieAVolk** [comment] 2018-01-09 02:15
Yeeeah there's already a bug for this also, forgot I hadn't fixed this yet

**Comment by MarjieAVolk** [comment] 2018-01-09 02:16
Here it is, dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/3216

**Closed by MarjieAVolk** 2018-01-09 02:16 UTC
Labels: Low Priority
