### ISSUE TITLE
Failed to connect - connection timed out.

### ISSUE THREAD

**Issue by YuukioFR** [StrangeLoopGames/EcoIssues#12678] opened 2019-06-30 00:40 UTC
unable to connect to the server online
I check the firewall and the antivirus that are both disable my pc time and synchronized

------------------------------------------LOG---------------------------------------------------------------
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2019.1.6f1 (f2970305fe1c)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: ASUS Radeon RX Vega (ID=0x687f)
    Vendor:   
    VRAM:     8121 MB
    Driver:   24.20.11016.4
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.769400 ms
The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Logging in as 76561198119379494 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU2MTg1NDY4MCwidnhhIjoibG9naW4iLCJ2eGkiOjIxMTA3OSwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgxMTkzNzk0OTQuQG10MXAudml2b3guY29tIn0.JzsLcimUYe2Knd_3bXIMzYAH3ht8P20Iug4XRzyWpbo
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
TooltipHandler:Invoke(TooltipUI)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_tlsctx_free_t:Invoke(unitytls_tlsctx*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 89881.
Total: 159.397200 ms (FindLiveObjects: 4.396800 ms CreateObjectMapping: 4.119900 ms MarkObjects: 150.680400 ms  DeleteObjects: 0.199600 ms)

**Comment by pamduncan** [comment] 2019-06-30 00:50
Please see #12631  I asked him to update that issue so it could be reopened and it ended up a new bug report

**Comment by D3nnis3n** [comment] 2019-06-30 08:42
Duplicate of #12631

**Closed by D3nnis3n** 2019-06-30 08:42 UTC
