### ISSUE TITLE
[0.8.2.0 release-preview] Titles don't update without relog

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12564] opened 2019-06-18 06:33 UTC
Step to reproduce:
- spawn registrar
- add some titles
- rename titles
- open titles appointers, titles have old name.
![image](https://user-images.githubusercontent.com/45708377/59657834-8f877d80-91aa-11e9-8376-e840edc9e82f.png)
- after relog
![image](https://user-images.githubusercontent.com/45708377/59657870-aa59f200-91aa-11e9-841f-00689803c015.png)
2. Double World Leader. It's regression.
In 8.1.4 one World Leader was.
![image](https://user-images.githubusercontent.com/45708377/59658384-1ab54300-91ac-11e9-8c85-cff7fc510e55.png)

**Comment by mirasrael** [comment] 2019-06-25 11:24
Moved to 9.0, because in current system there is no direct relation from Title to TitleAlias and in 9.0 aliases system was reworked.
Also wasn't able to reproduce double WorldLeader problem,

**Comment by mirasrael** [comment] 2019-10-18 16:35
Fixed in 9.0

**Closed** 2019-11-04 10:05 UTC
Labels: Fixed, Medium Priority, QA, Staging
