### ISSUE TITLE
USER ISSUE: Server Connection fails

### ISSUE THREAD

**Issue by Hasenpriester** [StrangeLoopGames/EcoIssues#12795] opened 2019-07-23 15:16 UTC
**Version:** 0.8.2.8 beta

**Actual behavior:**
After a restart of the game, previously known server in the server list (my worlds) will not show up immediatly, I have to wait a little bit until the server infos get displayed. All infos are correct just the ping is "-".
Ether coninue nor connect in the server list (my world) does work, the connection fails.
Using direct connect with IP and Port (click on the plus icon) work as expected.
I wiped my whole installation, remove steam folder and game data folder in User\AppData and reinstalled the game via steam but failure persists.
This happend today in the early morning MEZ 06:00, before the 8.2.9 Update were roled out.

**Comment by Reyalsorik** [comment] 2019-07-23 20:39
I've made a reference to a similar report. There are multiple issues of these popping up unreported. Thank you for reporting!

**Comment by D3nnis3n** [comment] 2019-07-24 01:17
Duplicate of #12792

**Closed by D3nnis3n** 2019-07-24 01:17 UTC
