### ISSUE TITLE
ECO: Error using shops

### ISSUE THREAD

**Issue by ommfgwtfits** [StrangeLoopGames/EcoIssues#24197] opened 2023-12-14 10:06 UTC
When I try to buy/sell to any other store the below lines of text show and the transaction fails.
"2 errors:
Dual Permissions: Object is not set.
Dual Permissions: Object is not set."

I tried using other shops/items and all had the same issue. However people can buy from my store (I am at the host server location).

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/153779049/33278178-b4ec-48bb-b356-098c25a5fdf6)

**Comment by D3nnis3n** [comment] 2023-12-14 14:06
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24167.

Will be fixed in first hotfix, until then a restart solves the problem for all players that joined the server so far.

**Closed by D3nnis3n** 2023-12-14 14:06 UTC
