### ISSUE TITLE
USER ISSUE: bug picking up cut log

### ISSUE THREAD

**Issue by smartaleq** [StrangeLoopGames/EcoIssues#4981] opened 2018-02-23 06:14 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Attempted to pick up cut piece of log found on ground in area not visited for 2+ hrs. Threw an exception	

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-23 22:09
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-23 22:09 UTC
