### ISSUE TITLE
USER ISSUE: Cannot connect to single player world

### ISSUE THREAD

**Issue by SophieLala** [StrangeLoopGames/EcoIssues#22762] opened 2021-10-27 14:36 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
I just attempted to load into a single-player world. This has been happening for a long while, a couple of months and across versions.

**Expected behavior:**
Loaded me into the world.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-fi
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7427014/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7427015/Player-prev.log)
l

**Comment by Daniel-Magulado** [comment] 2021-10-30 18:21
Hi @SophieLala 

Thank you for writing this report and providing your game logs. However, it appears that the issue is caused by something within your system or network and not the game.

On your logs, it says Curl error 7: Failed to connect to cdp.cloud.unity3d.com port 443 which indicates an error within your local network.

We recommend resetting your network to default, flushing your DNS or changing it to public such as connecting to Google via 1.1.1.1 and resetting your network setup on your PC, allow the game through firewall, and reset your router. Otherwise, this is not a bug caused by the game.

I'll be closing this since this is not a bug and hope that our recommendation be helpful to you.

**Closed by Daniel-Magulado** 2021-10-30 18:21 UTC
