### ISSUE TITLE
[Client] 9.4.1 Environment Statistics GUI in laws is non-functional

### ISSUE THREAD

**Issue by Xenoamor** [StrangeLoopGames/EcoIssues#22571] opened 2021-08-24 10:47 UTC
The Environmental Statistics GUI does not display properly in the law window and only renders an empty search bar at the top left of the screen. This is 100% reproducible and means statistics in laws are currently impossible

![image](https://user-images.githubusercontent.com/7109951/130603363-ba6f3725-1f46-493d-b4db-f1169cc0c1eb.png)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7038560/Player.log)

Steps taken to avoid the issue:
1. Running under Windows
2. Running under Linux
3. Restarting the client
3. Running at different resolutions with a mix of fullscreen or windowed
4. Trying different servers and local servers
5. Trying with different user accounts on different computers
6. Downgrading to 9.3.6 (this works)

This is a possible duplicate of #21752 and #20267. However this bug does not exist on 9.3.6 so I believe it maybe new.

My user id is: slg204596

**Comment by D3nnis3n** [comment] 2021-08-29 11:11
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/21752#issuecomment-904181171

**Closed by D3nnis3n** 2021-08-29 11:11 UTC
Labels: OS: Linux
