### ISSUE TITLE
Server crash, then getting dump error when attempting to restart

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#4697] opened 2018-02-17 10:51 UTC
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList1.Node.RemoveAll(Predicate1 match)
   at System.Collections.Immutable.ImmutableList1.RemoveAll(Predicate1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by ZeelNightwolf** [comment] 2018-02-17 11:56
Thanks to Pam from the Discord server we were able to clear a corrupt Object from world and resolved this.

**Comment by alexandrage** [comment] 2018-02-17 13:28
This is constant. What is the reason?

**Comment by MarjieAVolk** [comment] 2018-02-20 19:57
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368

**Comment by MarjieAVolk** [comment] 2018-02-20 19:58
I will check in with Pam for details about this fix

**Closed by MarjieAVolk** 2018-02-20 19:57 UTC
