### ISSUE TITLE
[9.0.3] Room updates very slowly / blocklag when updating extreme size rooms

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#18616] opened 2020-10-06 19:53 UTC
Edge case for obvious reasons, however editing anything in the room will frequently cause the room not to be recognized, and extensive modification will cause the room calculation to pop in and out repeatedly and cause a disconnection icon to appear

![20201006215019_1](https://user-images.githubusercontent.com/841990/95253039-1f2cc180-081e-11eb-87d8-98b59b7cc3d1.jpg)

**Comment by IcedForge** [comment] 2020-10-07 08:42
Closely related by #18618 might need a lot of work into the room calculation system to further optimize it?

**Comment by mirasrael** [comment] 2020-10-22 14:22
Duplicate of #18857

**Closed** 2020-11-03 00:18 UTC
Labels: Category: Optimization, Category: Tech, Priority: Medium

**Comment by WeaselDog** [comment] 2020-11-03 00:19
Thanks for letting us know. We have a fix for this coming in 9.1
