### ISSUE TITLE
USER ISSUE: Certain wall blocks are see-through 

### ISSUE THREAD

**Issue by aterrell4** [StrangeLoopGames/EcoIssues#6443] opened 2018-03-24 07:13 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
When a foundation block (brick for example) is put down next to a square block (brick as well) you can move around to certain angles and see through the world. Appears to happen most with brick but other materials as well.	

**Expected behavior:**
Wall should
 appear solid from all viewing angles. 

**Actual behavior:**
Wall can be seen through often times clipping all the way through the world. It causes frame loss and occasionally game crashes

![20180324031229_1](https://user-images.githubusercontent.com/37730288/37861492-4c3fa158-2f11-11e8-8a93-81ca4a892f5d.jpg)

**Comment by MarjieAVolk** [comment] 2018-03-30 18:47
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4286

**Closed by MarjieAVolk** 2018-03-30 18:47 UTC
