### ISSUE TITLE
[0.8.2.0 staging-3] Resolution setting bugs

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12212] opened 2019-05-07 18:05 UTC
Small bugs(or not) left. I just want to clarify some points.

1. In windowed mode:
![57275534-8e413c00-70a7-11e9-855b-ba9d058f471d](https://user-images.githubusercontent.com/45708377/57322024-3c320200-710b-11e9-8405-0c1eccc56faf.png)
 - Set any resolution excellent basic resolution
![57275583-aa44dd80-70a7-11e9-868e-2fdf82bb6b84](https://user-images.githubusercontent.com/45708377/57322101-6c79a080-710b-11e9-88df-fba0b0218618.png)
 - Close menu and reopen it, resolution will be refreshed to basic resolution.(will be 800x600)
![57275681-ea0bc500-70a7-11e9-88f4-e504d02c3b89](https://user-images.githubusercontent.com/45708377/57322119-7c918000-710b-11e9-8db6-bee4aad1856b.png)

If you manually change the window size, then when you open the menu, the resolution will be set to basic. In many games, if the resolution is different from the standard, then nothing is displayed there.
![57275950-b41b1080-70a8-11e9-9aae-a2fad1a11d41](https://user-images.githubusercontent.com/45708377/57322146-8ca95f80-710b-11e9-838b-29a936720c5b.png)

2. I have the monitor 16:10. My basic resolution 1680x1050, but it supports 1920x1080. For this reason, I have the opportunity to set the resolution of 1920x1080 in ECO. I can set it in Exclusive fullscreen and Windowed mode, but I can't set it in Borderless fullscreen. I undestand why it happens. But must be some notification that I can't set this resolution or I must not see this resolution in Borderless fullscreen. Now it's refreshing to my basic resolution 1680x1050.

3. In Borderless fullscreen: there are black stripes in the edges of the monitor if the side ratio is different from the standard.
In Exclusive fullscreen: the game is flattened or pulled out.

![57276390-1e808080-70aa-11e9-9331-9fb9cddbc151](https://user-images.githubusercontent.com/45708377/57322177-a054c600-710b-11e9-94c0-875d8f92e193.png)
![57276481-728b6500-70aa-11e9-87cf-d5e1a7039f87](https://user-images.githubusercontent.com/45708377/57322201-a9459780-710b-11e9-8f90-b94e1e001f3a.png)

**Comment by TwixterZ** [comment] 2022-10-04 10:09
Issues with inconsistencies of resolution setting was fixed in recent builds of ECO, the issue with borderless & exclusive full screen currently working as intended

**Closed by TwixterZ** 2022-10-04 10:09 UTC
Labels: Priority: Medium, Type: Bug, Category: Tech, Squad: Mountain Goat
