### ISSUE TITLE
USER ISSUE: Insufficient memory claim

### ISSUE THREAD

**Issue by Auke-Hoekstra** [StrangeLoopGames/EcoIssues#23255] opened 2022-06-23 20:32 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
I tried to host like I done twice before, a single player session to craft and build on my own. This keeps failing...

**Expected behavior:**
A new hosted game

**Actual behavior:**
Error message with multiple instances claiming I do not have enough memory, although I have 16GB which is the recommended amount and it worked before...

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No none, I have not looked into mods so I highly doubt that I have any installed. I often like Vanilla.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Auke-Hoekstra** [comment] 2022-06-23 20:37
[log_220623102239.log](https://github.com/StrangeLoopGames/EcoIssues/files/8970774/log_220623102239.log)
[log_220621093527.log](https://github.com/StrangeLoopGames/EcoIssues/files/8970775/log_220621093527.log)
[log_220621093316.log](https://github.com/StrangeLoopGames/EcoIssues/files/8970776/log_220621093316.log)
[log_220621091403.log](https://github.com/StrangeLoopGames/EcoIssues/files/8970777/log_220621091403.log)

It worked before... I'd played 255 houres on my own, but that was a while ago. Don't know what changed, on my end I only installed a newer GPU card, which is significantly better then the old one.

**Comment by Auke-Hoekstra** [comment] 2022-06-24 06:35
Maybe the switch to Windows 11 could be the source of the problem? But it shouldn't, right?!?

**Comment by D3nnis3n** [comment] 2022-06-24 13:19
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23245

**Closed by D3nnis3n** 2022-06-24 13:19 UTC
