### ISSUE TITLE
USER ISSUE: wrong tooltip in law

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoIssues#19030] opened 2020-11-01 21:45 UTC
Steps I took:
1. create a law draft
2. delete the law draft
3. go to another law draft
4. hover over a tooltip, a tooltip for the wrong law is shown

![grafik](https://user-images.githubusercontent.com/34270661/97816176-ca049400-1c93-11eb-98a4-a0c1ba2b0877.png)

**Comment by IcedForge** [comment] 2020-11-04 03:17
@DanielKispert Thank you for reporting this, can you verify if you still have this issue occur after 9.1 update?

**Comment by DanielKispert** [comment] 2020-11-04 14:22
@IcedForge I originally reproduced it in the staging version 1826 for 9.1 but I was not able to reproduce it in the current live version for steam.

**Comment by IcedForge** [comment] 2020-11-17 10:29
Thank you for following up and taking your time to test it. Yeah i could not reproduce it on 9.1 live either so ill close this, please reopen if you run into it again.

**Closed by IcedForge** 2020-11-17 10:29 UTC
Labels: Status: Needs Information
