### ISSUE TITLE
Sweeping hands no longer works if you try to pick up a piece that needs to be hit again

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11879] opened 2019-04-05 02:36 UTC

**Comment by mirasrael** [comment] 2019-04-05 05:39
I think it should be intended behavior. You should collect blocks in *addition* to collected, but you can't collect non-broken block.

**Comment by redwyre** [comment] 2019-04-05 16:23
Sorry, I wasn't clear: it didn't and shouldn't pick up the non-broken blocks, but previously if you tried to pick up a non-broken rubble sweeping hands would pick up all the broken rubble instead.

**Comment by espoire** [comment] 2019-04-05 21:56
I agree that this change is a nuisance. A huge part of what made this perk good before was that you could easily sweep away all the collectable rubble, leaving behind only the large pieces that needed an additional hit.

The recent patch has added the extra step of first finding one piece of small rubble. I had been timing my mining trips, to collect ore/time data, and while the 0.8.1 changes _feel_ nicer, the time lost to being unable to initiate small-rubble-sweeps by clicking on a piece of large rubble has actually made mining somewhat slower than before.

**Comment by mirasrael** [comment] 2019-04-06 07:12
@redwyre I get you right. I'm saying this talent should work **on pickup**, but you don't pick up big rubble, you just **trying to pick up**. Like you may try to pick up solid stone block.
Talent description: "Picking up rocks also attempts to pick up similar rocks in an area."

**Comment by mirasrael** [comment] 2019-04-06 07:15
And I understand it makes this talent a bit weaker, but in my opinion more correctly working.

**Comment by mirasrael** [comment] 2019-04-06 14:14
@espoire you shouldn't find a smaller one, you can just break big one just before you and pick up. Shouldn't actually slow down too much

**Comment by D3nnis3n** [comment] 2019-04-18 00:02
Intended behaviour, closing this.

**Closed by D3nnis3n** 2019-04-18 00:02 UTC
Labels: Medium Priority, Needs Triage
