### ISSUE TITLE
USER ISSUE: too many clams

### ISSUE THREAD

**Issue by zenwidjet** [StrangeLoopGames/EcoIssues#4256] opened 2018-02-10 16:11 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
/spawnspecies Clams,500

**Expected behavior:**
spawns 500 clams inthe water below me.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Sequence contains no matching element


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

```

**Comment by zenwidjet** [comment] 2018-02-10 16:21
Same happened with an amount of 50

**Comment by MarjieAVolk** [comment] 2018-02-13 22:04
Closing as duplicate of #4391

It seems this problem happens when you try to use a chat command without passing it the parameters it wants. To get around this, for now, you can type /help and the command name in order to figure out how to use the command.  If that isn't the issue, please let us know in the other bug.

**Closed by MarjieAVolk** 2018-02-13 22:04 UTC
Labels: Medium Priority
