### ISSUE TITLE
Camo Pants have no Texture

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5263] opened 2018-03-01 10:54 UTC
You will only wear undies, when you put them on *g* They are so camo, they are invisible! :D

**Comment by MarjieAVolk** [comment] 2018-03-01 19:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3208

**Closed by MarjieAVolk** 2018-03-01 19:40 UTC
