### ISSUE TITLE
[5.5.4] Soil nutrients don't update

### ISSUE THREAD

**Issue by Mosseman** [StrangeLoopGames/EcoIssues#1405] opened 2017-04-22 15:27 UTC
Throughout my current world save, the vast majority of soil nutrient tiles fail to update between ticks. 
![wat](https://cloud.githubusercontent.com/assets/1886646/25305652/69b77b68-2777-11e7-8f47-79efa003d6c6.png)
The image shows a tile with 4 camas bulbs on it, which should draw 16 units of potassium from the soil, which the "drain" part correctly shows. However, the predicted value shows no drain is taking place. This occurs consistently throughout the plants' life and is common to all crop varieties. However, this is not common across all tiles. Approximately 10% of tiles update as expected but the vast majority does not. There does not seem to be any real pattern to which tiles update and which don't, though the ones that do tend to be the ones in the middle of my farms.

**Comment by craig-jong** [comment] 2017-04-28 17:42
This is intended behavior (at least it sounds like it is, its possible it isn't)

Tile's ticked change (and therefore predicted) is based on the sum of all surrounding tiles rather than just on themselves. This may change in the future, but for now that is how it works.

**Comment by Mosseman** [comment] 2017-05-07 21:46
Yes, groups consist of 4x4 blocks. Those groups are not updating as they should, hence the bug report.

**Comment by craig-jong** [comment] 2017-08-16 22:27
The group are 4x4, but they also take into account the nutrients of other 4x4 tiles they're next to. It's why the center of the farm ends up with less nutrients than the edge parts.

This is not well displayed and should be updated.

**Comment by craig-jong** [comment] 2018-02-05 20:17
World layers has changed significantly (Taylor's refactor). I'm going to close this issue since nutrients now functions differently.

**Closed by craig-jong** 2018-02-05 20:17 UTC
Labels: Medium Priority
