### ISSUE TITLE
USER ISSUE: Teleporting Excavator

### ISSUE THREAD

**Issue by Sabbasn** [StrangeLoopGames/EcoIssues#6242] opened 2018-03-18 15:18 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Park an excavator at any given place (flat surface, non-flat surface, anywhere)

**Expected behavior:**
It should have stayed at its location.

**Actual behavior:**
Instead it pops out of existence and teleports to a random place on the map.

**Comment by MarjieAVolk** [comment] 2018-03-21 18:52
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6159

**Closed by MarjieAVolk** 2018-03-21 18:52 UTC
