### ISSUE TITLE
USER ISSUE: Creating Government Bank Account Crash

### ISSUE THREAD

**Issue by vsalyan** [StrangeLoopGames/EcoIssues#23955] opened 2023-08-07 18:57 UTC
\
**User Id: (slg120744)**
**Version:** 0.10.0.0 beta playtest-79

**Steps to Reproduce:**
1. Created country after creating another country.
2. No bank accounts for new country.
3. Try creating a new "Government Bank Account."
4. Boot from server (just me) with this exception.

**Expected behavior:**
Created a bank account for the new country automatically when it was founded (but it didn't). AND if there was no bank account and I tried to create one it should do it instead of booting me to main menu.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Cannot convert value: Government with valuetype String to type: Eco.Gameplay.Players.Player
Source:Eco.Shared

System.InvalidOperationException: Cannot convert value: Government with valuetype String to type: Eco.Gameplay.Players.Player
   at Eco.Sha</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, no idea. No government affecting mods installed that I know of.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment] 2023-08-24 20:11
Hi @vsalyan 

Thank you for submitting this bug report. Unfortunately, we are unable to reproduce so far on  0.10.0.0 beta playtest-107. Mind attempting to reproduce this issue again while recorded? the video will help us to investigate this issue further.

**Comment by D3nnis3n** [comment] 2023-10-09 07:34
Closing due to no further information provided.

**Closed by D3nnis3n** 2023-10-09 07:34 UTC
Labels: Status: Needs Information, Status: Not reproduced
