### ISSUE TITLE
USER ISSUE: active project cant be picked up

### ISSUE THREAD

**Issue by SebastianFranken** [StrangeLoopGames/EcoIssues#6092] opened 2018-03-15 18:13 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
I. Ordering something on a Campfire (Corn) or Crafting Table (Hewn Logs) in a quantity around 20+
II. Wait untill the project would be finished
III. return to the station to find the order "Done." but cant be collected

![troubleshoot](https://user-images.githubusercontent.com/37106169/37482747-503cfde2-2885-11e8-9b9c-fd03c6b44daa.jpg)

** Troubleshooting **
a) Ordering something new wont help, the new order will just complete as usual. Neither does moving the order around (before the "finished" one / behind the "finished" one)

![troubleshoot a](https://user-images.githubusercontent.com/37106169/37482620-fc5d4c72-2884-11e8-9f7e-e6fef1b2313e.jpg)

b) Trying to pick it up with a stone hammer results in picking up the fuel, a message: "This Campfire has active projects and can't be picked up" and it wont be picked up.

![troubleshoot b](https://user-images.githubusercontent.com/37106169/37482618-fc2730f6-2884-11e8-839c-4201bdba55a8.jpg)

c) Checking the connected Storage; none of the chests or stockpiles will accept the item although they have enough space. Ticking them off the network and reconnecting them does not do anything.

![troubleshoot c](https://user-images.githubusercontent.com/37106169/37482619-fc4367d0-2884-11e8-96a5-9c8d3d5e57d1.jpg)

** Additional info **
This happend to me atleast a few times with Hewn Logs and Charred Corn, possibly other projects aswell. 
One thing i figured out is, that if you just order a smaller quantity (15-25) the project seems to always finish correctly. But if i order more (50-100) i figured, that for Hewn logs many projects get stuck.

** Server info **
This happend on a Server i played on before (atleast)7.2.0-7.2.3 and does still happen on the same server (wiped and restarted on 7.2.3, later patched to 7.2.4)

**Comment by SebastianFranken** [comment] 2018-03-15 18:17
This annoys me primarily because i play on a Server with EXP/Craft so i lose out on the exp for the project. I will get all the produce.

**Comment by MarjieAVolk** [comment] 2018-03-16 00:04
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3240

This should be fixed in the next update.

**Closed by MarjieAVolk** 2018-03-16 00:04 UTC
