### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by marcospime** [StrangeLoopGames/EcoIssues#24093] opened 2023-11-17 00:28 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
A seguinte mensagem de erro apareceu:
```
<size=150%>Falha na conexão</size>

Informação de login inválida.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-11-17 19:25
This is not a bug but caused by Eco being unable to reach our authentication servers.

Typically this happens when security software or firewalls block the access and can be resolved by exempting Eco in any antivirus software. You can also test by using a VPN (or turning an existing one off that may not be able to reach).

In Eco authentication is done by the server, hence when you play on a online server you're likely not seeing the problem, as those servers have no issues connecting to our authetnication server, while when you play a local game, a local server is run that has the issue.

Further information can be received at [support@strangeloopgames.com](mailto:support@strangeloopgames.com).

**Closed by D3nnis3n** 2023-11-17 19:25 UTC
