### ISSUE TITLE
Fuel inventories need to tell what they can accept

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#950] opened 2017-01-03 01:34 UTC

**Comment by johnkslg** [comment] 2017-01-03 01:34
I dont know what goes in a tallow lamp and it wont take 'wood' even though wood is fuel, needs to say what it accepts

**Comment by metachronism** [comment] 2017-05-12 19:27
dupe of #751

**Closed by metachronism** 2017-05-12 19:27 UTC
