### ISSUE TITLE
USER ISSUE: placing two blocks using a hammer

### ISSUE THREAD

**Issue by collinticer** [StrangeLoopGames/EcoIssues#24761] opened 2024-02-12 19:02 UTC
\
**User Id: (slg204049)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Try to build a block (I'm using hewn logs) and now it's placing 2 blocks for each one. As in there will be 2 different blocks placed in the world when I try to place just one and I have to remove one now each time.

**Expected behavior:**
It should just place one block with each use of the hammer.

**Actual behavior:**
It places 2 and i have to remove one of them.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
We have some mods, like big shovel. I'm not sure. But this didn't happen until 10.1.4. It worked as expected in 10.1.3.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by collinticer** [comment] 2024-02-12 19:06
So after this was happening consistently, with every single block placement, it suddenly stopped and i'm not sure what could possibly be any different.

**Comment by D3nnis3n** [comment] 2024-02-13 10:30
Not reproducible and unfortunately no logs attached from when it happens. We'll need more info to investigate.

**Comment by collinticer** [comment] 2024-02-17 05:48
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14317853/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14317854/Player-prev.log)

here are those log files - sorry about that. Hope this helps. Anyone on the server is experiencing the issue but it doesn't happen consistently. When it happens it happens for a while and then stops again and goes back to only placing one block at a time.

**Comment by D3nnis3n** [comment] 2024-02-17 15:06
That actually sounds like ordinary itermittent server lag. The logfiles unfortunately don't show anything of interest either.

**Comment by collinticer** [comment] 2024-02-17 21:26
Hmm interesting. It only started after the recent patch but we'll try a server reboot and see if there's anything on the server side that's causing it. Thanks!

**Comment by D3nnis3n** [comment] 2024-02-19 11:11
There is no other reports about this and we can't see it on official servers either. So far there is no hint to a bug.

**Comment by D3nnis3n** [comment] 2024-02-23 09:29
Do you have any new information on this? So far no further reports either, so I would close this issue due to not unlikely to be a bug to begin with, but not being reproducible in any case.

**Comment by collinticer** [comment] 2024-02-24 18:51
I haven't been able to find anything more about this. Server logs seem rather normal. It happens pretty reliably ever since the latest update. Really doesn't seem like server lag since it ran for about 40 days prior (1 previous cycle and this latest one) and with the various patches y'all put out for 10 without this ever happening. I have a gigabit connection up and down and all the server resource usage is low - 2% CPU, 25% RAM, <1% Network, <1% Disk. The server has an SSD too. I've made sure the few mods we use are updated. Not sure what else could cause this. Does seem like the patch introduced it though.

We only have a few mods. DiscordLink, BigShovel, Whetstones and I created an override for Bison carcas to lower the weight. But otherwise it's a fairly standard server install and I did another check this morning for any updates to any of these. All seem to have been updated since the patch.

**Comment by collinticer** [comment] 2024-02-25 22:20
Decided to start a single player instance today to test this further. I'm not hosting on the same server that experiences the issue, but rather just my local gaming PC. No other players or anything.

I admin gave myself hewn logs and an iron hammer right after spawn. Immediately I am met with placing 2 blocks at a time instead of 1.

**Comment by collinticer** [comment] 2024-02-25 22:23
I also reinstalled my Eco client and completely cleared my LocalAppData folder for SLG to ensure it wasn't some setting persisting.

What's also strange is players on my server also experience the same issue. So it's not just me, but it's also not isolated to just my server, since my fresh install of Eco on my gaming PC does the same behavior if I host a local instance.

**Comment by D3nnis3n** [comment] 2024-02-26 11:21
Alright, I'll keep the issue open in case someone can provide additional information and reproduction steps. Without them there is unfortunately nothing we can do, as the issue does is not reproducible for us.

**Comment by D3nnis3n** [comment] 2024-02-26 12:39
Different though: Is it possible you are actually affected by the double character bug mentioned in https://github.com/StrangeLoopGames/EcoIssues/issues/24772?

You could try the steps i posted there in that case.

**Comment by collinticer** [comment] 2024-02-26 14:21
I went ahead and cleared that directory in the registry. Lost a few things like my avatar and some GUI preferences but nothing that really matters. And that appears to have fixed the issue.

So I'm unsure of the exact setting in the registry that caused this behavior, but closing Eco and then clearing `Computer\HKEY_CURRENT_USER\Software\Strange Loop Games\Eco\`  entirely (just right click the Eco "folder" and delete), and then re-start Eco. Have to recreate the avatar on start, but then afterwards I am no longer getting this issue.

Closing this issue. Thanks for all your help on this @D3nnis3n it was greatly appreciated. I wanted to advertise my server, but not if new players were going to be having this issue when they login, as I know they would just find another server. Turns out it's client-side anyways. I can explain this to anyone on my server that was experiencing the same issue.

**Comment by collinticer** [comment] 2024-02-26 14:29
I just wanted to clarify, I did originally try setting the `Computer\HKEY_CURRENT_USER\Software\Strange Loop Games\Eco\Profiles\USERNAME\DropDownToggles\Backpack\Expanded_h1705352275` value to a zero and that didn't have any impact. So it's some other value in there, so clearing the Eco folder worked, but I'm unsure which one it is.

**Comment by collinticer** [comment] 2024-02-28 05:24
Seems to be occurring again. And clearing the same folder in the registry does fix it again temporarily. I'll re-open once I figure out what key in the registry is causing this.

**Comment by collinticer** [comment] 2024-02-28 05:39
Ok I would ignore everything I've said about the registry. I think it was just a placebo effect in me hoping for a fix and noticing it wasn't happening immediately after. Good news - I think I have steps to reproduce this.

It appears that placing blocks in 3rd person view, via pressing F5 to switch to that view, is what causes this to start happening. And switching back to 1st person while building appears to reliably fix it, as far as I can tell.

**Comment by Quadbro** [comment] 2024-03-07 09:45
Problem found, should be fixed i nnext udpate!

**Closed** 2024-03-07 11:52 UTC
Labels: Status: Needs Information, Status: Not reproduced
