### ISSUE TITLE
Client Memory bloat

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1064] opened 2017-02-04 02:15 UTC
5.4 has a huge memory leak again and keeps on growing over time

**Comment by metachronism** [comment] 2017-03-21 22:56
debugging this is a huge PITA

**Comment by MarjieAVolk** [comment] 2017-03-22 19:30
Forum discussions about this issue:
http://ecoforum.strangeloopgames.com/topic/1119/memory-leak-logging-into-server/2
http://ecoforum.strangeloopgames.com/topic/1159/alpha-5-performance-absolutely-worse

**Comment by metachronism** [comment] 2017-03-31 18:21
closing as dupe of #392 #1026 #653

**Closed by metachronism** 2017-03-31 18:21 UTC
Labels: High Priority
