### ISSUE TITLE
Crash while in main menu

### ISSUE THREAD

**Issue by MightyPiggie** [StrangeLoopGames/EcoIssues#4352] opened 2018-02-11 20:28 UTC
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1714801/error.log)

**Comment by MarjieAVolk** [comment] 2018-02-21 23:19
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4357

**Closed by MarjieAVolk** 2018-02-21 23:19 UTC
