### ISSUE TITLE
White Tiger Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12845] opened 2019-08-03 19:24 UTC
> --BEGIN DUMP--
> Dump Time
> 08/03/2019 21:19:28
> 
> Exception
> Exception: NullReferenceException
> Message:Object reference not set to an instance of an object.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Eco.Gameplay.Items.AuthorizationInventory.MakeGameAction(Inventory inventory, Type itemType, Int32 delta, User user)
>    at Eco.Gameplay.Items.AuthorizationInventory.InventoryChanged(User user, IEnumerable`1 changes, Dictionary`2 changedStacks)
>    at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
>    at Eco.Gameplay.Components.AnimalTrapComponent.LayerTick()
>    at System.Action.Invoke()
>    at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
>    at Eco.Simulation.WorldLayers.WorldLayerSync.Tick()
>    at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
>    at Eco.Simulation.WorldLayers.WorldLayerManager.Tick()
>    at Eco.Simulation.WorldLayers.WorldLayerManager.TryTick()
>    at Eco.Simulation.WorldLayers.WorldLayerManager.Run()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 
> --END DUMP--

**Comment by mirasrael** [comment] 2019-09-24 14:46
This logic was reworked in 9.0. Closing for now because unable to reproduce and can't analyze code, because of being rewritten.

**Closed by mirasrael** 2019-09-24 14:46 UTC
Labels: High Priority
