### ISSUE TITLE
Plants glitch for a frame when crossing world border

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21649] opened 2021-04-29 17:51 UTC
![anim](https://user-images.githubusercontent.com/3536496/116595992-c4050e00-a8d8-11eb-9262-8a8ecea7a729.gif)

**Comment by IcedForge** [comment] 2021-05-03 11:09
Will close this as its a duplicate of #9664 its an old reoccuring issue with random stuff being misbehaving on the world border wrap line.

**Closed by IcedForge** 2021-05-03 11:09 UTC
