### ISSUE TITLE
Web Client - unable to find API files - from external domain

### ISSUE THREAD

**Issue by EpsilonCommunity** [StrangeLoopGames/EcoIssues#10647] opened 2019-01-13 05:55 UTC
Created an external copy of the WebClient/WebBin files... include the parent files from WebClient folder.

URL: https://eco.epsilon.community/viewDistricts.html

Steam name shows up, if shown browser from in-game.  NOT like this: https://github.com/StrangeLoopGames/EcoIssues/issues/6206

Here are a few screenshots:
https://gyazo.com/b29f12fc8c2c7223c49fb340bb785458 Error in Google Chrome F12 Debug.

World Ingame: 
https://gyazo.com/5a6b11620139bbcd7d192b0565f000ff

World on WebClient:
https://gyazo.com/96cd461106b4ac88eed1bb8edc99c4d0

Both WebClient and Ingame are the same.

So it's down to the API being missing, that is the issue. I've been unable to find the API file from within the server files downloaded: [Beta 7.8.8] https://ecoauth.strangeloopgames.com/home

**Comment by EpsilonCommunity** [comment] 2019-01-13 05:56
https://gyazo.com/7a597b4e742e9cdf405587f03fe82170 File Manager to show which files are where.

**Comment by redwyre** [comment] 2019-01-13 06:53
You can't just copy the files, they are served through the game server along with the API. You have to connect to the game server's web server port for the API to work.

**Comment by D3nnis3n** [comment] 2019-01-13 10:10
This is definately not a bug, though, so i'll close this issue. Feel free to go on with discussion, if interested.

**Closed by D3nnis3n** 2019-01-13 10:10 UTC

**Comment by EpsilonCommunity** [comment] 2019-01-13 13:13
What do you mean? Can you explain this in techincal terms.

**Comment by EpsilonCommunity** [comment] 2019-01-13 13:14
How would I get eco.epsilon.community to serve the webclient?

**Comment by elfl0rd** [comment] 2019-01-13 13:52
![default](https://user-images.githubusercontent.com/4980243/51086124-6eca8000-1753-11e9-807e-4f5b24b961f5.png)
ofc, you can set it directly in network.eco config.
`"WebServerUrl": "",`

**Comment by redwyre** [comment] 2019-01-13 14:48
The game has a built in web-server that serves the static files (in WebClient) as well as dynamically serves the API (the /api url and others). You can connect to the web server using http://<game server ip>:3001 (for example http://54.245.222.69:3001/ is the official Giant Tortoise server's web interface).

The simplest way to get this to work would be to set your domain to point to your game server ip, however you will have to use the 3001 port. You will have to check with the provider of the domain name for details on how to do this.

**Comment by redwyre** [comment] 2019-01-13 14:50
@elfl0rd Setting that by itself wont help, the domain name has to be set up correctly first.

**Comment by redwyre** [comment] 2019-01-14 08:12
@EpsilonCommunity I recomment joining the discord and asking there, as you'll be able to talk to people with experience setting up their own servers (https://discord.gg/Eco)
