### ISSUE TITLE
[0.9.3 staging-1931] Field of view resets to default when go to 3rd person view.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20593] opened 2021-02-16 06:22 UTC
Step to reproduce:
- be in 1st person view:
![image](https://user-images.githubusercontent.com/45708377/108025868-51ee8e00-7038-11eb-9112-ae0cd2f6e37f.png)
- set field of view different from 60:
![image](https://user-images.githubusercontent.com/45708377/108025827-426f4500-7038-11eb-958a-921a4c12f5df.png)
- go to 3rd person view:
![image](https://user-images.githubusercontent.com/45708377/108025881-56b34200-7038-11eb-9c23-956aba49d02b.png)
- go to 1st person view:
![image](https://user-images.githubusercontent.com/45708377/108025906-5fa41380-7038-11eb-9620-65d076144b21.png)
- check field of view:
![image](https://user-images.githubusercontent.com/45708377/108025945-764a6a80-7038-11eb-857f-4f1a93338b09.png)

**Comment by IcedForge** [comment] 2021-03-08 12:25
This was merged into 9.4 and not into staging, is this intended? @StanKryvenko

**Comment by SlayksWood** [comment] 2021-03-15 05:58
Still have 1 flaws. Step to reproduce:
- be on 1st person view. Set Field of view = 75:
![image](https://user-images.githubusercontent.com/45708377/111109688-47a6ad80-856c-11eb-8412-f8171790dc10.png)
- go to 3rd person view. Field of view will reset to 60:
![image](https://user-images.githubusercontent.com/45708377/111109751-69079980-856c-11eb-88d4-0c215b1e0b3c.png)
This does not greatly affect anything, because when you switch to the first person view, it will again be 75, but can you make only one setting appear?

**Comment by keegan-o** [comment] 2021-03-23 00:38
My suggestion earlier for this same issue in a different github issue that was opened was to re-name the setting to 'First Person FOV' instead of 'Field of View', since our current third person camera alters the FOV on its own based on zoom level, which we would have to override to add FOV control back into third person. It's a question of if we want third person FOV control or not, does it affect the vehicles or not? Etc etc, this needs to be designed and discussed, rather than 'fixed'. In the meantime though the simple re-name would alleviate the confusion over what the setting actually does.

**Comment by IcedForge** [comment] 2021-03-23 06:58
The general problem with it is that it resets its settings, not that it isnt working in 3rd person.

I sit in 1st person and set my FOV
Go into 3rd person to look at stuff or get a more overview.
change back to 1st person, i expect my FOV settngs to stay put, not have to enter options / graphic settings every single time i switch to 3rd person.

Would it be viable to split them if this is not possible?

**Comment by StanKryvenko** [comment] 2021-03-26 15:17
@IcedForge this problem is already fixed (with resetting when you're returning to first-person view)

**Comment by TwixterZ** [comment] 2021-04-16 07:47
fix tested and confirmed for 9.4 Develop 255

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/2669e252-f7e5-4b7c-aa65-0688f3b1899d)

**Closed by TwixterZ** 2021-04-16 07:47 UTC
Labels: Category: Gameplay, Priority: Medium, Squad: Saguaro, Status: Reopen, Type: Bug
