### ISSUE TITLE
USER ISSUE: Vehicles go Flying

### ISSUE THREAD

**Issue by Kosmic0wl** [StrangeLoopGames/EcoIssues#18072] opened 2020-09-07 05:57 UTC
\
**Version:** 0.9.0.0 beta staging-1756

**Steps to Reproduce:**
1. I get in any vehicle I am authorized for
2. I get out - from my POV I am out and walking around, from other player POVs I am sitting in the vehicle and facing whichever way I am looking from my POV
3. Another player gets in the vehicle with my bugged character model

**Expected behavior:**
I should be able to get in and out of any authorized vehicle, without issue

**Actual behavior:**
Instead, the vehicle breaks - sometimes it will shake across the ground, sometimes it will fly, and it won't stop until I disconnect.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Carry quantity increase mods (to hold more rocks etc.), haven't tested on Vanilla as I never expect to play Single Player.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5181267/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5181268/Player-prev.log)

**Comment by IcedForge** [comment] 2021-02-18 09:13
Will close this for now, have not been able to reproduce it since 9.0 release and was able to do it quite frequently in disconnects before that

**Closed by IcedForge** 2021-02-18 09:13 UTC
Labels: Status: Investigate
