### ISSUE TITLE
[7.5.0] Unstuck Doesn't Work For Elevator Shaft

### ISSUE THREAD

**Issue by miketek1** [StrangeLoopGames/EcoIssues#8202] opened 2018-06-27 23:13 UTC
If you fall in an elevator shaft and don't have access to use the elevator you become stuck in a hole. If you use /unstuck it doesn't work because there is no blocks above. The only way to get out would be for the elevator owner to lift it, or for an admin to teleport the player. If no one is on to do this you just become stuck.

**Comment by SeanAtr0n** [comment] 2018-06-27 23:52
unstuck doesn't require blocks above you anymore, are you sure it won't work in the described situation? It works for me

**Comment by miketek1** [comment] 2018-06-28 01:03
@SeanAtr0n It did not work for me. It should put you on top of the elevator frame. https://youtu.be/GkMZBOjjg1s

**Comment by SeanAtr0n** [comment] 2018-06-28 18:47
looks like the bottom of your mine is big enough that pathfinding thinks you aren't really stuck, i'll think about a way to handle this better... in general if you can walk around on 150 different blocks unstuck gets disabled

**Comment by elfl0rd** [comment] 2019-02-09 15:56
Duplicate of #9390

**Closed by elfl0rd** 2019-02-09 15:56 UTC
Labels: Medium Priority
