### ISSUE TITLE
SERVER ISSUE: ClientNetworkException

### ISSUE THREAD

**Issue by yankeejim** [StrangeLoopGames/EcoIssues#4792] opened 2018-02-19 02:08 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
```
--BEGIN DUMP--
Dump Time
02/17/2018 20:50:27

Exception
System.Exception: Caught exception invoking RPC SetTag on ChatManager!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Systems.Chat.ChatManager.SetTag(ChatTagSetting chatTagSetting, Int32 playerID)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()

--END DUMP--
```

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-20 21:32
Any details on when or how this happened?

**Comment by yankeejim** [comment] 2018-02-20 23:15
Unfortunately not, came back and server was restarting from a crash, the server told me there was massive lag and then a crash.

**Comment by MarjieAVolk** [comment] 2018-02-23 01:39
Oh just realized this is a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4736.  Seems I am not very consistent about what I mark as high priority :P

**Closed by MarjieAVolk** 2018-02-23 01:39 UTC
Labels: Medium Priority
