### ISSUE TITLE
USER ISSUE: [<7.2][Dedicated Server]Freeze/Disconnect random player after looting dead animals

### ISSUE THREAD

**Issue by lefavilla** [StrangeLoopGames/EcoIssues#5640] opened 2018-03-08 01:25 UTC
**Version:** 0.7.2.2 beta

Bug known since: 0.7.2.1

**Steps to Reproduce:**
1. 2 or more Player on Server
2. Player A is hunting
3. Player A is looting dead animals (every animal)
4. Player B or C or D.. gets a freeze OR disconnect
5. Player B  or C or D needs to disconnect and reconnect
6. Begin from 1. if hunting goes on

**Expected behavior:**
Normaly one can hunt and loot without disconnecting other player on dedicated server

**Actual behavior:**
One random player sometimes all get a freeze while one player is hunting and looting dead animals

Hardware:
More then enough. Intel, 1000/1000Mbit, SSD and stuff.. 

Software:
2012 R2

Server Network:
All Ports open
No Nat needed because of direct connection

Settings:
Rate: 60
WorldTickCPUMax: 0,75

World:
Seed: 1964165
Dimensions: 128, 128
WaterLevel / Height: 40/80

ERROR from CMD while errors appear "maybe" has to do with it:
Stack:
`Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection `1 monitored) [...]`

Could not post a better log because it didn't create a dmp..

**Comment by ApoRes1337** [comment] 2018-03-08 01:28
I can confirm this error, the players on my server also have such problems

**Comment by MittenMarauder** [comment] 2018-03-08 06:27
Also experiencing this issue. Player reported they were trying to loot a Bison, and the server started to lag out immediately after.

**Comment by destruktoid** [comment] 2018-03-08 08:02
Can confirm this issue. Constant 100% CPU when playing normally, never went above 40% with a 'no hunting' rule active.

**Comment by Thyriel** [comment] 2018-03-08 08:26
Would need to test it but that could explain why we had major lag/desync problems the first time after ~2hours, then again 10min after server restart and later not for 6 hours. At least i know the first one went hunting after ~2 hours and all hunters where offline later when problems where gone

**Comment by Thyriel** [comment] 2018-03-08 18:21
Can confirm that definitly being the cause of the huge server lag / desync issue. The moment our hunter came online and went hunting it started again, after nearly 20 hours of working like a charm with no lags or anything unusual

**Comment by Ekkelus** [comment] 2018-03-08 19:01
There must be something else aswell causing it, we've banned hunting and it worked like a charm but now something is leaking again. We haven't been able to pinpoint the cause though but it looks like it isn't only hunting that causes it.

**Comment by Thyriel** [comment] 2018-03-08 19:04
@Ekkelus have you tried disabling statistics in Config/Stats.eco ?
That was the first thing we did yesterday and i still think that it helped aswell

**Comment by ElTyranos** [comment] 2018-03-08 23:28
Much better here after 7.2.3.
ref : https://github.com/StrangeLoopGames/EcoIssues/issues/5578#issuecomment-371335288

**Comment by metachronism** [comment] 2018-03-09 19:08
should be fixed in 7.2.3

**Closed by metachronism** 2018-03-09 19:08 UTC
Labels: Critical Priority, High Priority
