### ISSUE TITLE
campsite - missing "sleep"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10057] opened 2018-11-17 12:06 UTC
Okay, campsite have bed, but not have ability to sleep :P 
![20181117150603_1](https://user-images.githubusercontent.com/4980243/48660878-59e6ae80-ea7a-11e8-8b14-e6368cad97da.jpg)

**Comment by Deantwo** [comment] 2018-11-18 16:51
That is actually a useful idea for singleplayer game yeah.

**Comment by BlazeGuy2** [comment] 2018-11-21 22:31
This issue was moved to StrangeLoopGames/EcoSuggestions#636

**Comment by elfl0rd** [comment] 2018-11-21 23:17
@BlazeGuy2 this is not suggestion, this is bench without sleep function. In addition, I really do not understand why there is a section of proposals that no one is viewing, reject them immediately maybe?

**Comment by elfl0rd** [comment] 2018-12-06 09:37
@D3nnis3n I believe that this is not a suggestion but a bug. In a single game you may need a lot of time before you can sleep in a separate bed.

**Comment by D3nnis3n** [comment] 2018-12-06 12:40
I don't agree on this one, sorry. As BlazeGuy2 was of the same opinion as me, it stays as is.

**Comment by elfl0rd** [comment] 2018-12-06 13:16
In this case fake "bed" need to be removed from campsite.

**Comment by elfl0rd** [comment] 2018-12-06 13:17
As written in changelog
![default](https://user-images.githubusercontent.com/4980243/49586498-6328b400-f972-11e8-9467-97746c24ff58.png)
this is bed? yes.
![default](https://user-images.githubusercontent.com/4980243/49586516-6f147600-f972-11e8-9e3f-748f636a2a0b.png)
Why i cannot sleep in it?

**Comment by D3nnis3n** [comment] 2018-12-06 13:19
Cause it's not a bed item, but a starter camp item. Please refrain from pressing through your opinion, thank you.

**Comment by elfl0rd** [comment] 2018-12-06 13:19
> As BlazeGuy2 was of the same opinion as me, it stays as is.

Is it? I do not see his opinion, I see the work of the automatic tool.

**Comment by D3nnis3n** [comment] 2018-12-07 10:55
I already told you my argumentation: The "bed" in the changelog is referring explicitly to the furnitures that are solely a bed and / or named like one. I even agree that your idea is a good one - but it is a suggestion and not a bug. As i already told you that and you are still claiming that it's not a suggestion the only thing you are doing at the moment is pressing your opinion on this issue despite it also got a classification. That is neither a style of good communication nor very fair to us - i even consider this disrespectful - so i asked you politely to stop it. If we allow all suggestions to be on the bug tracker, we can close down the other tracker again. If we put the priority you or others would like on every issue here we'd probably only have high priority issues and some issues where people fight if it's high or low priority. It can't work like that.

A Community Manager is not only there to say yes and nod to anything. (Also, on here i'm not CM!) I'm also here to communicate things you probably don't like and to enforce them if needed.

**Comment by elfl0rd** [comment] 2018-12-07 11:06
The suggestions section doesn't work if that. There is no proposal that would be implemented from there and it looks more like a dump.

**Comment by D3nnis3n** [comment] 2018-12-07 11:44
This game is still in early access and there are a lot of things planned that need to be implemented first. Despite that, we still take inspiration from those issues in some changes and even some additions. But i'll bring up a more visible handling of those. Still, i don't think we have any developer with free capacities to just implement some of those very good ideas. Also - recently i did allow a lot of QoL Issues and things that are really more a suggestion to be on this tracker and even tagged it with my list. It's not like we didn't do something.

**Comment by elfl0rd** [comment] 2018-12-07 15:45
In any situation, demanding to stop expressing your opinion is not good. This is especially not good from someone who works with the community.
I'm not saying that the developers do not do anything, do not muddle my words.
And of course I do not require for all these qol\issues any priority, low - quite normal.
The majority does not like "features" which are partially or not completely implemented, for me too. (Steam tractor modules, ladders, seats, etc...)

**Comment by D3nnis3n** [comment] 2018-12-07 22:40
I don't demand that you stop to express your opinion, i asked you to stop saying that your opinion is truth.

"In this case fake "bed" need to be removed from campsite." - This looks like a fact. But it's none.
"this is not suggestion, this is bench without sleep function." - Looks like a fact. But it's none.

You expressed it correctly here:
"I believe that this is not a suggestion but a bug" - You believe so, it's your opinion. Very fine. I did answer that i'm not of your opinion and decided to give it a suggestion label. I also told you why i did so. You then got on pretty much telling me that is "wrong". Which is telling me a fact again, not a opinion.

"The majority does not like "features" which are partially or not completely implemented, for me too. (Steam tractor modules, ladders, seats, etc...)" - This might be true, but the majority also does not like having issues like with the elevator, still you insist on not adding casual elements the majority wants. So whom i'm supposed to listen to now? To your or to the majority?

In any case, we've implemented a priority list for issues that i see reported often and that i see people are bugged most about. As far as that goes, we have improved things. And as far as the suggestion tracker goes, i'll bring that up.

I really appreciate your help to the project, but that does not entitle you to decide what is correct or wrong. And the only thing i asked you to stop was this. You can express your opinion freely as much as you want, as long as you want and where you want.

I'm not going to change my opinion on this issue just because you thing my opinion is wrong, though.

**Comment by D3nnis3n** [comment] 2018-12-07 23:39
As i told you in discord, we'll be opening up this issue and putting it on my list.

**Comment by johnkslg** [comment] 2019-02-19 19:40
@Quadbro can you look at making this bed work like the other beds?
@D3nnis3n @elfl0rd you guys need to calm down

**Comment by elfl0rd** [comment] 2019-02-19 19:52
> 8 Dec 2018

:D

**Comment by D3nnis3n** [comment] 2019-03-09 02:31
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11613

**Closed by D3nnis3n** 2019-03-09 02:31 UTC
Labels: D3nnis3n's List, Medium Priority
