### ISSUE TITLE
USER ISSUE: Unable to Interact after joining server

### ISSUE THREAD

**Issue by J0llywalrus** [StrangeLoopGames/EcoIssues#24545] opened 2024-01-05 18:23 UTC
\
**User Id: (slg233646)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Log into server
Though seems to only be happening to me in our server.

**Expected behavior:**
Allowed me to interact with objects in the world, eat food, change quickslots, view laws/economy

**Actual behavior:**
I am unable to interact with any objects in the world. Tables give options of Turn On and Open, though neither do anything. I can't eat food, or change which quickslot I have selected.
It usually goes away after about 30-90 seconds, but other times needs the server to be restarted.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13845298/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13845299/Player-prev.log)

**Comment by J0llywalrus** [comment] 2024-01-05 18:26
Actions I've tried to resolve the issue:
- Verify game files in Steam
- Restart PC
- Reinstall Eco

**Comment by D3nnis3n** [comment] 2024-01-09 03:28
We are so far unable to reproduce this in any way and seem to have a total of four affected users.

We'll need as much info as you can provide - full PC specs, full list of installed system software, any security software. Full logs.
Hopefully when everyone affected does that we can find a pattern.

**Comment by taker99** [comment] 2024-01-10 10:55
Hello, I don't know if this fits in here. I had a similar problem where it was the activation of Twitch in the game

**Comment by J0llywalrus** [comment] 2024-01-11 19:25
PC Specs:
CPU: i9-10850K CPU @ 3.60GHz
GPU: RTX 2060
RAM: 32GB

Windows 10, 64 bit version 10.0.19041
Security Software: Windows Defender

I have no more logs because the issue has fortunately seemed to resolve itself for me a couple days ago.

**Comment by D3nnis3n** [comment] 2024-02-03 09:43
We had no further reports of this so far, hence closing. If anyone else has a problem with being permanently unable to interact with anything, please open a new issue and make sure to provide all data requested in here.

**Closed by D3nnis3n** 2024-02-03 09:43 UTC
Labels: Status: Needs Information, Status: Not reproduced
