### ISSUE TITLE
USER ISSUE: Crimini Mushroom Time issue

### ISSUE THREAD

**Issue by CricketXO** [StrangeLoopGames/EcoIssues#24620] opened 2024-01-17 05:36 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Planted criminis this AM. Planted more at 9pm. Used soil sampler on ones i planted this AM and it says 9.7hours until maturation. New ones say 9.2. Ones I planted this AM look 2x the size of the new ones and seem to be growing but not sure how they still have longer than the new ones that seems impossible. 

**Expected behavior:**
Been a few hrs to harvest on the ones planted this AM

**Actual behavior:**
No errors. Just it says 9.7hours until maturation. New ones say 9.2. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes Choco Tacco's game though so can't test without mods sorry. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-24 00:05
Not reproducable locally, were any settings changed? Any reproduction steps?

**Comment by D3nnis3n** [comment] 2024-01-28 23:47
Closing due to no further information provided and issue not reproducible.

**Closed by D3nnis3n** 2024-01-28 23:47 UTC
Labels: Status: Needs Information, Status: Not reproduced
