### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by BIGkGaming** [StrangeLoopGames/EcoIssues#6824] opened 2018-04-01 03:03 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Clicked on a log in water

**Expected behavior:**
pick up the log

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment] 2018-04-02 21:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-04-02 21:53 UTC
