### ISSUE TITLE
USER ISSUE: "Camo Pants" does not show.

### ISSUE THREAD

**Issue by MonaMuu** [StrangeLoopGames/EcoIssues#6764] opened 2018-03-30 21:01 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
I put one the clothing items "Camo Pants" and "Camo Shirt" even so they do not show on the character.

**Expected behavior:**
"Camo Pants" and "Camo Shirt" should show on character.

**Actual behavior:**
"Camo Pants" and "Camo Shirt" did not show on character.

**Comment by MarjieAVolk** [comment] 2018-03-30 23:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3208

**Closed by MarjieAVolk** 2018-03-30 23:12 UTC
