### ISSUE TITLE
When equipping any costume with right click, the description pop is not refreshing.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9421] opened 2018-09-18 13:33 UTC
Description: When the user has the backpack open and right clicks any of the costumes, if the description pop up appears before, it is not refreshing or disappearing until the cursor is moved.

STR:
1. Start the game.
2. Create/Join a world.
3. Open the backpack by selecting the B button.
4. Have 2 costumes for the same slot.
5. Right click on a costume to fill the empty slot and observe the issue.
6. Right click on the other costume multiple times and observe that in the general chat it shows the costumes are replaced or equipped.

Actual Result: The pop ups are not refreshing automatically.

Expected Result: As soon as a costume have been equipped, if pop up was present previously, it should disappear. If two or more different costumes are being equipped for the same slot, the pop up description should also refresh when each costume is equipped.

Video Link: 
https://www.dropbox.com/s/hvw987mo87ome88/Unity 2018.2.3f1 Personal (64bit) - Game.unity - Client - PC%2C Mac %26 Linux Standalone _DX11_ 18-09-2018 17_04_56.mp4?dl=0

**Comment by Daniel-Magulado** [comment] 2021-03-12 17:46
Tested on 0.9.3 Staging-1952

The fix [Tooltip doesn't update fix](https://github.com/StrangeLoopGames/Eco/pull/7955) is actually working. When equipping a costume to replace an existing one (ex. Right-clicking on Low Shoes to replace Tall Boots), the ToolTip doesn't disappear anymore unlike the screenshot shown on the PR ticket. However, the ToolTip doesn't update and is still displaying the description of the selected costume before swapping.

Video Repro:
https://images.zenhubusercontent.com/47210472/3f343531-ed96-4014-b331-827e92b6add6/tooltip.mp4

**Comment by madpingui** [comment] 2021-03-12 20:09
It was merged into develop, it works for me.

**Comment by WeaselDog** [comment] 2021-03-23 07:32
@Daniel-Magulado Please recheck on 9.4 build

**Comment by TwixterZ** [comment] 2021-04-07 07:15
tested on 9.4 develop 242 confirmed this is fixed

**Closed by TwixterZ** 2021-04-07 07:15 UTC
Labels: Category: UI, Priority: Low, Squad: Wild Turkey, Status: Fixed
