### ISSUE TITLE
USER ISSUE: Combustion generator produces sewage when connected to water but not on

### ISSUE THREAD

**Issue by crusnak1** [StrangeLoopGames/EcoIssues#11448] opened 2019-02-21 18:13 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**

Connect combustion generator to incoming water via water pump. It will consume water and produce sewage even if unfueled and not running.

**Expected behavior:**

Water should be consumed and sewage produced only when the generator is running.

**Actual behavior:**

Generator produces sewage as soon as water is connected to it, regardless if on or not.

**Do you have mods installed? Does issue happen when no mods are installed?:**

No

**Comment by elfl0rd** [comment] 2019-02-21 18:30
Duplicate of #11213

**Closed by elfl0rd** 2019-02-21 18:30 UTC
