### ISSUE TITLE
Icons get stuck on my screen when dropped while dragging

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#4673] opened 2018-02-17 03:46 UTC
This has been happening for quite some time. When I drag an idea from one slot and let go of the mouse button while I'm dragging it across my screen it gets stuck on my screen and no longer shows in the slot it came from. If I disconnect and reconnect it goes back to how it should be.

![image](https://user-images.githubusercontent.com/1503963/36337721-2d435356-136b-11e8-91ec-a114b5dfdaaa.png)

**Comment by ecoemmeck** [comment] 2018-02-17 04:32
Yer this is quite annoying. To fix atm exit the game client and reload the game

**Comment by SerpentSunrise** [comment] 2018-02-17 05:21
Alt - Tab has worked for me in correcting this issue

**Comment by MarjieAVolk** [comment] 2018-02-22 23:24
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-02-22 23:24 UTC
