### ISSUE TITLE
Ambient sounds stop aburptly when crossing world wrap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17665] opened 2020-08-12 05:50 UTC
crickets at night especially.

**Comment by SlayksWood** [comment] 2020-08-12 07:10
I think it's related with changing environment. #9664
Zero point

**Comment by s3lbie** [comment] 2020-08-13 14:55
Crossing between 720 to 0 in coordinates causes certain ambient noises to stop. A flicker occurs between the two points.

**Comment by WeaselDog** [comment] 2020-10-13 02:39
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/16980

**Closed by WeaselDog** 2020-10-13 02:39 UTC
Labels: Category: Audio, Priority: Medium
