### ISSUE TITLE
USER ISSUE: Log in the water

### ISSUE THREAD

**Issue by DuSxeMan** [StrangeLoopGames/EcoIssues#4374] opened 2018-02-12 04:14 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. I Found a log from the first tree i ever cut down, it was just floating in water.
2. I had just logged back into my server
3. tried to pick up the log
4. gave me error code

**Expected behavior:**
I don't think that log was supposed to be there.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-13 00:24
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668 . You can track the progress of the issue there.

It seems this happens occasionally, especially with logs that have been sitting around when the game is reloaded.  I had not heard anyone suggest that the log was not supposed to have been there at all though.  I will note that in the other bug.  Hopefully we will fix it soon.

**Closed by MarjieAVolk** 2018-02-13 00:24 UTC
