### ISSUE TITLE
Fishing and water bug

### ISSUE THREAD

**Issue by Roby1164** [StrangeLoopGames/EcoIssues#11178] opened 2019-02-08 14:46 UTC
Fishing does not work, the traps are not positioned in the water, but only on dry land, moreover, by digging near the shore, the water remains in its position. not filling the removed areas
![screenshot_2](https://user-images.githubusercontent.com/24955554/52485087-4306b280-2bb8-11e9-8931-152128768c1c.jpg)
Version 0.8.0.0
Dedi Server

**Comment by Roby1164** [comment] 2019-02-08 15:04
![screenshot_3](https://user-images.githubusercontent.com/24955554/52486344-29b33580-2bbb-11e9-977c-12b89f60e7a2.jpg)
![screenshot_4](https://user-images.githubusercontent.com/24955554/52486352-2f108000-2bbb-11e9-8f27-4cebab3fa75e.jpg)
![screenshot_5](https://user-images.githubusercontent.com/24955554/52486360-333c9d80-2bbb-11e9-989a-549e50c5e775.jpg)

**Comment by elfl0rd** [comment] 2019-02-08 16:18
Duplicate of #10849

**Comment by elfl0rd** [comment] 2019-02-08 16:19
Duplicate of #10683

**Closed by elfl0rd** 2019-02-08 16:19 UTC
