### ISSUE TITLE
USER ISSUE: Can't pick up hunted animals

### ISSUE THREAD

**Issue by Jenni709** [StrangeLoopGames/EcoIssues#24975] opened 2024-06-09 13:16 UTC
\
**User Id: (slg81235)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Hunt an animal as usual

**Expected behavior:**
Let me pick up the carcass

**Actual behavior:**
Won't let me pick up the carcass

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-06-11 07:37
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24726

**Closed by D3nnis3n** 2024-06-11 07:37 UTC
