### ISSUE TITLE
USER ISSUE: Player interact on player

### ISSUE THREAD

**Issue by DeusPoulpe** [StrangeLoopGames/EcoIssues#5923] opened 2018-03-11 20:23 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
I don't know, i just spawn

**Expected behavior:**
¯\_(ツ)_/¯

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

La valeur ne peut pas être null.
Nom du paramètre : item


Stack:
   à System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   à System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   à Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   à Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   à Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   à Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   à Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
```

Stack:
   à Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   à Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   à Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   à Eco.Shared.Networking.NetPort.ProcessBuffer()
   à Eco.Shared.Networking.NetPort.Update()
   à Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

La valeur ne peut pas être null.
Nom du paramètre : item

Stack:
   à System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   à System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   à Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   à Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   à Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   à Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   à Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   à Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   à Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   à Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   à Eco.Shared.Networking.NetPort.ProcessBuffer()
   à Eco.Shared.Networking.NetPort.Update()
   à Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-13 00:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5804

**Closed by MarjieAVolk** 2018-03-13 00:05 UTC
