### ISSUE TITLE
[0.8.1.1 release-preview] Can`t create a new random world from client

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11927] opened 2019-04-09 05:57 UTC
[0.8.1.1 release-preview] 
no mods

Can`t create new world from client
**Steps**
- Launch client
- Press "New Game 
- Go to "Host a private world"
- Check Generate new world
- Start

**Expected result**
login in new  world

**Actual result**
Connection failed

> <size=150%>Connection Failed</size>
> 
> Failed to connect - connection timed out.
> 
> Log File:
> Initialize engine version: 2018.3.11f1 (5063218e4ab8)
> GfxDevice: creating device client; threaded=1
> Direct3D:
>     Version:  Direct3D 11.0 [level 11.1]
>     Renderer: Radeon RX 550 Series (ID=0x699f)
>     Vendor:   
>     VRAM:     4044 MB
>     Driver:   22.19.677.257
> <RI> Initializing input.
> 
> <RI> Input initialized.
> 
> <RI> Initialized touch support.
> 
> UnloadTime: 0.538560 ms
> WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Avatar FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness Cutout' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Cutout' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Lambert FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Avatar' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Cutout' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
> Connecting to local host.
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> UI.ConnectionUI:ManualUpdate()
> UI.UIManager:Update()
>  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> Connecting to 127.0.0.1:3000...
> 
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> Eco.Shared.Utils.Log:WriteLine(LocString)
> Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
> Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
> UI.ConnectionUI:ManualUpdate()
> UI.UIManager:Update()
>  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> Connection complete.
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> UI.ConnectionUI:ManualUpdate()
> UI.UIManager:Update()
>  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
> 
> Unloading 17 unused Assets to reduce memory usage. Loaded Objects now: 85550.
> Total: 553.089192 ms (FindLiveObjects: 10.490084 ms CreateObjectMapping: 6.740408 ms MarkObjects: 535.665686 ms  DeleteObjects: 0.192159 ms)

**Comment by beastyn** [comment] 2019-04-09 07:07
server logs
[log_190409105421.log](https://github.com/StrangeLoopGames/EcoIssues/files/3057584/log_190409105421.log)

**Comment by beastyn** [comment] 2019-04-09 07:09
[log_190409095653.log](https://github.com/StrangeLoopGames/EcoIssues/files/3057591/log_190409095653.log)

**Comment by mirasrael** [comment] 2019-04-09 07:57
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11576

**Closed by mirasrael** 2019-04-09 07:57 UTC
Labels: Critical Priority, Quality Assurance
