### ISSUE TITLE
USER ISSUE: Graphic/light issues after teleport

### ISSUE THREAD

**Issue by r0tt3ndr34m5** [StrangeLoopGames/EcoIssues#19876] opened 2020-12-30 14:16 UTC
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
I used the TP command

**Expected behavior:**
Teleport to another location

**Actual behavior:**
Teleport to another location with causes graphic  light issues 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here 
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5754479/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5754480/Player-prev.log)

![20201229233340_1](https://user-images.githubusercontent.com/76781431/103356696-c3d33e00-4ab1-11eb-8dec-8232b29ab82b.jpg)
![20201230151340_1](https://user-images.githubusercontent.com/76781431/103356697-c46bd480-4ab1-11eb-904c-2daa673645a1.jpg)
![20201229181135_1](https://user-images.githubusercontent.com/76781431/103356698-c46bd480-4ab1-11eb-84b6-3c8e09d992d5.jpg)

**Comment by IcedForge** [comment] 2020-12-30 15:26
Thank you for reporting. closing this as it is a duplicate of #14042

**Closed by IcedForge** 2020-12-30 15:26 UTC
