### ISSUE TITLE
(Staging Alpha 6.1.0 #4e325355) Claiming land

### ISSUE THREAD

**Issue by Toooxic** [StrangeLoopGames/EcoIssues#2643] opened 2017-10-27 23:45 UTC
When i claim land the server asigns the land to another player.

**Comment by MarjieAVolk** [comment] 2017-10-27 23:54
Do you have a deed belonging to someone else in your inventory?

**Comment by Toooxic** [comment] 2017-10-28 10:45
No i don't have a deed that belong to another player.

**Comment by wiloxe** [comment] 2017-10-29 09:37
Could this be related to #4626?

**Comment by MarjieAVolk** [comment] 2017-10-30 18:04
Could you provide your server save file?  And/or some screenshots of your deed(s), and the status panel showing the owner of the land after you've claimed it?  I need some more context.

**Comment by Toooxic** [comment] 2017-10-30 19:08
The day after this happened i joined the server and it was my land so i cant really provide any more information.

**Comment by MarjieAVolk** [comment] 2017-10-30 20:55
So the issue isn't still happening?

**Comment by Toooxic** [comment] 2017-10-30 22:23
It isnt happening anymore.

**Comment by MarjieAVolk** [comment] 2017-10-30 22:40
Okay well without more information there's not much I can do, so closing for now; feel free to reopen if you have more problems

**Closed by MarjieAVolk** 2017-10-30 22:40 UTC
