### ISSUE TITLE
USER ISSUE: Sticking Icons

### ISSUE THREAD

**Issue by Hypnotique88** [StrangeLoopGames/EcoIssues#5378] opened 2018-03-04 18:30 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
It is really bad today! I cant get my pickaxe out of the repair table becasue the icon is sticking to the screen and my axe disappears. I have to log out everytime to fix it and now that isnt even fixing it. Please help!

**Expected behavior:**
Move the pickaxe from repair station to my bag....

**Actual behavior:**
Icon sticks in my toolbelt without being accessible. please fix...Logging in and out over and over again this morning play really stinks

**Comment by bootj93** [comment] 2018-03-04 19:46
Have the same issue!

**Comment by MarjieAVolk** [comment] 2018-03-05 22:43
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

As a workaround, it seems that minimizing the game and then opening it again clears stuck icons.  Also, it seems that this problem happens much more frequently with certain mice (eg. mice that send duplicate click events), so if you have another mouse to try, that might reduce this problem.

**Closed by MarjieAVolk** 2018-03-05 22:43 UTC
