### ISSUE TITLE
USER ISSUE: Invalid Login Info on hosting Private Game

### ISSUE THREAD

**Issue by Fischkjopp** [StrangeLoopGames/EcoIssues#24166] opened 2023-12-13 05:38 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Hosting a private Game Session

**Expected behavior:**
The game should load the world an let me join my private Game.

Joining a Multiplayer Server works fine, but Singleplayer/Private Session allways produce this Error. (Same as posted yesterday)

This Error occurs for me every time i try to host a private game. I first experienced this error about a month ago and was never able to fix it, despite trying almost everything I found online.

Sorry for reporting the same issue twice, but the original report was closed, yet the issue remains.

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13656660/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13656661/Player.log)

**Comment by D3nnis3n** [comment] 2023-12-13 12:56
This is not a bug but caused by Eco being unable to reach our authentication servers.

Typically this happens when security software or firewalls block the access and can be resolved by exempting Eco in any antivirus software. You can also test by using a VPN (or turning an existing one off that may not be able to reach).

In Eco authentication is done by the server, hence when you play on a online server you're likely not seeing the problem, as those servers have no issues connecting to our authetnication server, while when you play a local game, a local server is run that has the issue.

Further information can be received at [support@strangeloopgames.com](mailto:support@strangeloopgames.com).

**Closed by D3nnis3n** 2023-12-13 12:56 UTC
