### ISSUE TITLE
Updates/Mode switch blocks MP through Client server "Server is Full" message

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4578] opened 2018-02-15 11:08 UTC
When there is an update and teh client server files are updated the config files are wiped and reinstalled.  This sets the  maxslots back to the default for the client of 1 (single player only).  Apparently, also even if you have been playing MP game, if you start up a SP game it will revert the -1 back to a 1.

SInce all Saved games in the client server share the same set of config files (rather than a set for each world created) the last maxslot setting will apply to any client game started.  So, if after an update or a little game of SP, you go back to your MP saved game,  suddenly none of your friends can get in and get  the message "Server is Full".

This is also a problem when people who have been playing a MP, and then switches back to a SP game where they are playing and suddenly others can join.  Since the configs are shared perhap a check box for when you select the world name you could check or uncheck if its SP or not.  If checked the start up checks maxslots and sets it to 1, and if unchecked it makes sure the setting is -1

**Comment by WeaselDog** [comment] 2020-10-12 02:54
We have templates now for steam updates. For the rest of it, closed as duplicate of above issue.

**Closed by WeaselDog** 2020-10-12 02:54 UTC
Labels: Priority: Medium
