### ISSUE TITLE
SERVER ISSUE TreeEntity.PickupLog

### ISSUE THREAD

**Issue by Ekkelus** [StrangeLoopGames/EcoIssues#4725] opened 2018-02-17 18:04 UTC
Noticed that alot of players have reported this error as a user issue but this one crashed our server and not just the client.

--BEGIN DUMP--
Dump Time
02/17/2018 18:43:47

Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-02-22 19:56
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Comment by MarjieAVolk** [comment] 2018-02-22 19:56
Oh I'm sorry, I didn't realize you had commented this crashed the server too.  Was going too fast.

**Closed by MarjieAVolk** 2018-02-22 19:56 UTC

**Comment by MarjieAVolk** [comment] 2018-02-22 20:00
It looks like exactly the same stack trace, so that is odd that it would crash the server.
