### ISSUE TITLE
Ghost Blocks

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#2137] opened 2017-09-15 23:10 UTC
Sometimes, and I have not noticed a pattern yet, will update here if I do find it, when removing blocks, so far I noticed this with dirt, the block will be visually there, but for the server, it's not.

A simple re-connect will update but it's annoying.

Version: v0.6.0.0-alpha-staging-3a83dd35

**Comment by metachronism** [comment] 2017-09-18 20:46
dupe of #2127

**Closed by metachronism** 2017-09-18 20:46 UTC
