### ISSUE TITLE
USER ISSUE: Text gets smashed in contract creation

### ISSUE THREAD

**Issue by Gilgatex** [StrangeLoopGames/EcoIssues#4289] opened 2018-02-11 03:36 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Try to create a new contract
Select add/remove blocks
Select property

**Expected behavior:**
Continue with contract add

**Actual behavior:**
All the text gets smooshed to the left, making it difficult to complete filling it out.

**Comment by LiaungYip** [comment] 2018-02-11 03:55
Duplicate of #3535.

**Comment by MarjieAVolk** [comment] 2018-02-13 04:35
Yes thank you.  Closing as duplicate of #3535

**Closed by MarjieAVolk** 2018-02-13 04:35 UTC
