### ISSUE TITLE
Wrong durability and nutrition calculation

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11789] opened 2019-03-28 08:02 UTC
**8.0.7 No mods**
**Expected result:**
When you try to gather a granite block with a stone pickaxe you should use two hits. Every hit should consume 10 calories and 1 durability. After breaking a block, a pickaxe should lose 2 durability and calories should lose 20 points.

**Test result:**
A granite block was broken with two hits. But calories and durability was dropped down one time - after breaking a block. A pickaxe has lost 1 durability, calories- 10 points.

![Before_break_calories](https://user-images.githubusercontent.com/27898520/55140269-721db700-5159-11e9-9375-a5eb58e4d84f.jpg)
![after_break_calories](https://user-images.githubusercontent.com/27898520/55140272-7518a780-5159-11e9-86ee-00f4858e2087.jpg)
![before_break_pickaxe](https://user-images.githubusercontent.com/27898520/55140283-83ff5a00-5159-11e9-8a82-2d738fead2ca.jpg)
![after_break_pickaxe](https://user-images.githubusercontent.com/27898520/55140310-94173980-5159-11e9-80e6-ae0389903b92.jpg)

Add: was tested with limestone, issue the same

**Comment by seccombew** [comment] 2019-03-28 17:43
@beastyn Was this on 8.1 staging?

**Comment by beastyn** [comment] 2019-03-28 17:53
@seccombew 
Nope, 8.0.7

**Comment by D3nnis3n** [comment] 2019-03-28 18:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11667

**Closed by D3nnis3n** 2019-03-28 18:23 UTC
Labels: Medium Priority, Needs Triage

**Comment by mirasrael** [comment] 2019-03-28 18:32
@seccombew it also in 8.1 latest staging (tested it today)
