### ISSUE TITLE
USER ISSUE: Masonry Table Unfinished Projects

### ISSUE THREAD

**Issue by DJmRek** [StrangeLoopGames/EcoIssues#5864] opened 2018-03-10 22:21 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Use Masonry Table to produce mortared stone.
2. Table should be linked to a stockpile
3. Produce more than a stack amount of items (over 15  mortared stone)

**Expected behavior:**
Mortared stone should be produced and put/stacked correctly in the stockpile. Project in Mansonry Table should disappear after finishing.

**Actual behavior:**
Randomly stops at a 14th stack or one less than ordered. Projects still shown in Mansonry Table, but as finished. They can be canceld anyway to get rid of them. Could also be reproduced with some other items recently.
![masonry table unfinished projects](https://user-images.githubusercontent.com/16185705/37247304-8de9193e-24b9-11e8-9061-2ac7f50ae3b5.png)

**Comment by Thyriel** [comment] 2018-03-11 10:48
That's sometimes happening in almost all crafting tables. It seems to have something to do with resources being provided while it's crafting. Not sure if that's always the reason but at least a couple times noticed that on cancel it gives a single resource back so probably it's hanging because that item is still inside the job

**Comment by MarjieAVolk** [comment] 2018-03-13 19:40
I'm starting to wonder if this is a rounding error.

**Comment by MarjieAVolk** [comment] 2018-03-13 19:41
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3240

**Comment by MarjieAVolk** [comment] 2018-03-13 19:41
Thank you for all the details by the way, every data point for hard bugs is useful, even if it's already been reported it's good to confirm multiple people see the same thing.

**Closed by MarjieAVolk** 2018-03-13 19:41 UTC
