### ISSUE TITLE
and more crashing :(

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2902] opened 2017-11-26 21:43 UTC
![image](https://user-images.githubusercontent.com/31536813/33244617-421ea4c0-d2fb-11e7-9f8a-0c1d775b19a2.png)

**Comment by MarjieAVolk** [comment] 2017-11-27 18:57
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2899

**Closed by MarjieAVolk** 2017-11-27 18:57 UTC
