### ISSUE TITLE
[0.9.2.4 beta release-156] An election draft can be started by someone else

### ISSUE THREAD

**Issue by thomasfn** [StrangeLoopGames/EcoIssues#20715] opened 2021-02-23 17:10 UTC
If player X creates an election draft via their civic privilege (granted either from a civic article, or the temporary privilege when drafting a constitution ratification), any other player who also has the civic privilege can start the election.

This is problematic when player X intends to add multiple provisions to the election but another player starts their election before player X gets a chance to add all their provisions. This is _especially_ problematic when the election is the constitution ratification, as ANY player is able to start the ratification election, making it very difficult to setup the initial constitution bundled with some other civics like elected titles etc, because you have seconds to add everything to the draft before another random player spots it and clicks start election.

**Reproduction Steps**
1. Have two players X and Y join the same multiplayer server.
2. Player X place a Capitol and create an election draft for the ratification of a constitution
3. Player X observe that the election draft is seen in their civic menu to the right, and that they have the option to "Start Election" as intended
3. Player Y observe that the election draft is also seen in their civic menu, and that they also have the option to "Start Election", even if X isn't ready to start that election yet since they want to add more provisions to it

Note that the current workaround is to draft an invalid constitution (i.e. a civic with a missing election process) and leave it invalid until all provisions are added, as this invalid-ness prevents the election being started prematurely.

Also note that this issue was anecdotally observed in 9.1 and 9.0 also.

**Comment by IcedForge** [comment] 2021-03-01 09:46
@thomasfn Thanks for reporting, will take a look at it in 9.3 after the current run of civic issues are resolved but it looked* like it might be partially resolved already.

**Comment by IcedForge** [comment] 2021-03-09 05:53
Yes, no this is not the intended behavior and will be fixed.

**Comment by IcedForge** [comment] 2021-03-19 11:23
Looks like it is working as intended now, only the individual who starts drafting the constitution sees it as an eligible choice to start it. And if another player tries to start drafting as well, this is not possible as this constitution is already locked up in a draft existing.

**Closed by IcedForge** 2021-03-19 11:23 UTC
Labels: Category: Laws, Priority: High, Squad: Mountain Goat, Status: Fixed, Type: Bug
