### ISSUE TITLE
USER ISSUE: skill scrolls failing to register as learned

### ISSUE THREAD

**Issue by galnicholas** [StrangeLoopGames/EcoIssues#24962] opened 2024-05-31 16:02 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. create skill book
2. learn skill scroll
3. go to skill menu an attempt to learn skill

**Expected behavior:**
the skill should have a "learn box" allowing the skill to be aquired

**Actual behavior:**
the skill box says I need to aquire a skill scroll before it can be learned. When I try using a skill scroll again I can't. Restarting the game appears to correct the issue.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Comment by D3nnis3n** [comment] 2024-06-03 07:37
Not reproducible, any more information?

**Comment by D3nnis3n** [comment] 2024-06-11 07:39
Closing due to necessary information not provided and the issue not being reproducible, please feel free to open a new issue if you are able to provide the required information.

**Closed by D3nnis3n** 2024-06-11 07:39 UTC
Labels: Status: Needs Information, Status: Not reproduced
