### ISSUE TITLE
USER ISSUE: Need to press E twice to interact with Workbench again

### ISSUE THREAD

**Issue by eXifreXi** [StrangeLoopGames/EcoIssues#6254] opened 2018-03-18 20:05 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Place Workbench
2. Interact with the Workbench using E
3. Close the Interaction Window with the X at the top right
4. Try to interact with the Workbench using E again

PS: You probably have a Pointer still filled with the Workbench reference that only gets set to null when pressing E. Just remove the Pointer value when closing the UI and it should be fixed.

**Expected behavior:**
Interaction Window of the Workbench opens

**Actual behavior:**
Requires a second E press to open

**Comment by MarjieAVolk** [comment] 2018-03-20 22:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4918

**Closed by MarjieAVolk** 2018-03-20 22:11 UTC
