### ISSUE TITLE
USER ISSUE: Camo shirt is not camo

### ISSUE THREAD

**Issue by Arturaceloray** [StrangeLoopGames/EcoIssues#6241] opened 2018-03-18 14:51 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Create and equip a camo shirt.

**Expected behavior:**
Camo pattern

**Actual behavior:**
white torso with hot pink arms

**Comment by MarjieAVolk** [comment] 2018-03-21 18:52
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3208

**Closed by MarjieAVolk** 2018-03-21 18:52 UTC
