### ISSUE TITLE
USER ISSUE: crash server

### ISSUE THREAD

**Issue by Sallicze** [StrangeLoopGames/EcoIssues#23427] opened 2022-09-10 04:51 UTC
\
**User Id: (slg221213)**
**Version:** 0.9.6.1 beta release-337

**Steps to Reproduce:**
1. The player on the server caused the server to crash by creating a work party. 
3. The server went down while the website election was going on

**Expected behavior:**
1. The player on the server caused the server to crash by creating a work party. 
4. The server went down while the website election was going on

**Actual behavior:**
After the restart, the server runs, but we had to remove everything that caused the crash.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-09-10 13:08
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23399

**Closed by D3nnis3n** 2022-09-10 13:08 UTC
