### ISSUE TITLE
USER ISSUE: Flying goat

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#11455] opened 2019-02-22 00:10 UTC
![screenshot 2](https://user-images.githubusercontent.com/35748070/53210573-f386a480-3603-11e9-816d-cca19cdbc1bf.png)
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
No clue how this happened just found it in the wild

**Expected behavior:**
be laying on the ground

**Actual behavior:**
look at the screenshot

**Do you have mods installed? Does issue happen when no mods are installed?:**
look at the screenshot

**Comment by D3nnis3n** [comment] 2019-02-22 12:19
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11143

**Closed by D3nnis3n** 2019-02-22 12:19 UTC
