### ISSUE TITLE
USER ISSUE: Placing furniture upstairs produces a net reduction of significant amount to my house

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#6033] opened 2018-03-14 08:24 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1. Have a house with +42 experience value.
2. Go upstairs
3. Place item of furniture	

**Expected behavior:**
Experience value should increase

**Actual behavior:**
Experience value decreases

**Comment by MarjieAVolk** [comment] 2018-03-16 01:44
We are in the process of revisiting housing points, so this might not be relevant anymore.  But could you give more details about what rooms you have in your house, and what the new item you placed was, etc?

**Comment by CuAnnan** [comment] 2018-03-16 05:25
I was placing a chair. It went into a room over a room with a kiln.

**Comment by GophTheGreat** [comment] 2019-05-23 23:41
Can't reproduce. Closing.

**Closed by GophTheGreat** 2019-05-23 23:41 UTC
Labels: Medium Priority
