### ISSUE TITLE
Extremely bad Client performance

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#910] opened 2016-12-20 01:21 UTC
http://ecoforum.strangeloopgames.com/topic/1119/memory-leak-logging-into-server/2

http://ecoforum.strangeloopgames.com/topic/1159/alpha-5-performance-absolutely-worse

**Comment by MarjieAVolk** [comment] 2017-03-22 19:29
Closing as a duplicate of StrangeLoopGames/EcoIssues#1064

**Closed by MarjieAVolk** 2017-03-22 19:29 UTC
Labels: High Priority
