### ISSUE TITLE
USER ISSUE: Changed World Settings.

### ISSUE THREAD

**Issue by Taratsamura** [StrangeLoopGames/EcoIssues#4801] opened 2018-02-19 04:15 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Start a New World
2. Start another World with different Player expectation
3. Load the first World

**Expected behavior:**
Unchanged Skill costs.

**Actual behavior:**
Skill costs from the settings of the second World.

**Comment by MarjieAVolk** [comment] 2018-02-20 21:21
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3768

In order to change the settings back, you should be able to use /openserverui and find the config in the Difficulty tab.  Unfortunately, this setting is shared by all saves right now, so you will need to change it back and forth.

**Closed by MarjieAVolk** 2018-02-20 21:21 UTC
