### ISSUE TITLE
USER ISSUE: Interacted with a toolbench

### ISSUE THREAD

**Issue by PR3SIDENT** [StrangeLoopGames/EcoIssues#3906] opened 2018-02-05 02:54 UTC
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
Interact with a toolbench	

**Expected behavior:**
Toolbench should have opened		

**Actual behavior:**
The following error message popped up:
```Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.BlockItem.OnActRight(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
```

game

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.BlockItem.OnActRight(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-06 01:48
So this stack trace says you were right clicking with a block in your hand.  Do you know what block it was?

**Comment by MarjieAVolk** [comment] 2018-02-06 23:08
Going to close this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3966, since that one has more information on it currently

**Closed by MarjieAVolk** 2018-02-06 23:08 UTC
Labels: High Priority

**Comment by MarjieAVolk** [comment] 2018-02-07 00:02
FYI this will be fixed in the next hotfix
