### ISSUE TITLE
Excavator bug

### ISSUE THREAD

**Issue by christianbhill** [StrangeLoopGames/EcoIssues#6510] opened 2018-03-26 01:30 UTC
While digging in the excavator, it ran out of gas and it locked my camera in the direction of it was facing, I jumped in my car and then got out and it locked it in the direction, I could only unlock it by putting more petrol in the excavator

**Comment by MarjieAVolk** [comment] 2018-03-26 18:22
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6281

**Closed by MarjieAVolk** 2018-03-26 18:22 UTC
