### ISSUE TITLE
USER ISSUE: Log defying gravity

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#4014] opened 2018-02-07 02:32 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
Chop down a tree next to a hill

**Expected behavior:**
the log should sty put when chopping it up	

**Actual behavior:**
causes a crash in some cases when you chop it or it falls off the hill which is okey its after you log back in after the crash that werid stuff happens such as the log vanishing or flying up into the air and sticking on the boundary where players can't reach

**Comment by MarjieAVolk** [comment] 2018-02-07 23:48
Closing as duplicate of #3752

**Closed by MarjieAVolk** 2018-02-07 23:48 UTC
