### ISSUE TITLE
[0.9.0.3 - Beta Release - 78] Repaying a Loan is impossible

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#18498] opened 2020-09-28 06:37 UTC
Got a bit of a doozy on this one fellows, I'll keep testing this one and keep this one flowing as I can recreate and test it further.

**Steps to reproduce:** Take out a Loan
**Expected behavior:** Make enough money to repay the loan, open the loan contract, repay loan, mark loan as completed, continue the happy life of an Eco Citizen
**Actual behavior:** Be Unable to click the Pay button when using the Economy Viewer to try and repay the debt from the Loan
**Providing Log files:** Will Provide these as soon as I able (I have to recreate this in game again as I forgot to get snapshots when I discovered this

**Comment by beastyn** [comment] 2020-09-28 07:34
@Sarah-Graesyn will it work if amount number will be updated?
Button was fine for me after entering amount or clicking "all" button,

**Comment by Sarah-Graesyn** [comment] 2020-09-29 08:42
@beastyn I had been using the full amount I owed and it wouldn't let me repay the loan I had taken from another player. I both hit the all button and manually input the number and then hitting the repay button would not progress the screen.

I will check it again tomorrow when I have a chance to sit down and actually log some time after I do some other work for my businesses

**Comment by beastyn** [comment] 2020-09-30 04:45
@Sarah-Graesyn Thank you.
Also if its still an issue for you It will be nice to have a log file.

**Comment by SlayksWood** [comment] 2020-10-19 07:30
@Sarah-Graesyn Do you still have the problem? Can't reproduce in staging-1806.

**Comment by IcedForge** [comment] 2020-11-05 10:46
Will close this as it has been over 2 weeks with no reply, i will assume this issue is resolved. 
If you are still experiencing this problem please reopen and inform us about it so we can further investigate this issue.

**Closed by IcedForge** 2020-11-05 10:46 UTC
Labels: Status: Needs Information
