### ISSUE TITLE
USER ISSUE: World leader voting page error

### ISSUE THREAD

**Issue by JacobsenDev** [StrangeLoopGames/EcoIssues#15860] opened 2020-04-18 20:13 UTC
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Uncaught Error: Syntax error, unrecognized expression: .current-rankings table tr[data-voter='Kame-Sen'nin'] td
    at Function.fb.error (jquery-latest.min.js:2)
    at fb.tokenize (jquery-latest.min.js:2)
    at fb.select (jquery-latest.min.js:2)
    at Function.fb [as find] (jquery-latest.min.js:2)
    at m.fn.init.find (jquery-latest.min.js:2)
    at new m.fn.init (jquery-latest.min.js:2)
    at m (jquery-latest.min.js:2)
    at tableShow (Election.js:1009)
    at Election.getVote (Election.js:115)
    at showCandidates (Election.js:995)
    at Object.success (Election.js:76)
    at j (jquery-latest.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-latest.min.js:2)
    at x (jquery-latest.min.js:4)
    at b (jquery-latest.min.js:4)
    at Object.send (jquery-latest.min.js:4)

**Expected behavior:**
Player names should be escaped so they work no matter.

**Actual behavior:**
Code breaks with names containing ' character. And thus world leader voting breaks.

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods.

**Comment by D3nnis3n** [comment] 2020-04-19 01:00
Known issue fixed in Update 9.0.

**Closed by D3nnis3n** 2020-04-19 01:00 UTC

**Comment by Deantwo** [comment] 2020-07-05 19:15
Duplicate of #13707
