### ISSUE TITLE
USER ISSUE: wheelbarrow

### ISSUE THREAD

**Issue by mwarnec2** [StrangeLoopGames/EcoIssues#10163] opened 2018-11-30 15:29 UTC
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
pushing wasd 	

**Expected behavior:**
w should go straight, a should go left, s should go back, d should go right.	

**Actual behavior:**
when pressing the buttons the wheelbarrow has a mind of its own going all over the place and not the direction you press and it changes all the time every time you press buttons a new direction
n
**Do you have mods installed? Does issue happen when no mods are installed?:**
when pressing the buttons the wheelbarrow has a mind of its own going all over the place and not the direction you press and it changes all the time every time you press buttons a new direction

**Comment by D3nnis3n** [comment] 2018-12-04 03:46
Duplicate of #10051

**Closed by D3nnis3n** 2018-12-04 03:46 UTC
