### ISSUE TITLE
Hitting a stockpile or Dirt ramp with hammer just throwing into empty slot not stacking with others carried ##e80b350f

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2353] opened 2017-09-27 21:13 UTC
Not sure if this is doiung for other items as this was the only 2 i just tried

**Comment by MarjieAVolk** [comment] 2017-09-27 21:18
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1945

**Closed by MarjieAVolk** 2017-09-27 21:18 UTC

**Comment by Conchipedia** [comment] 2017-09-27 21:21
i tried searching for it under stacks (apologies)

**Comment by MarjieAVolk** [comment] 2017-09-27 21:23
no problem :)
