### ISSUE TITLE
Crash to Desktop on opening server list

### ISSUE THREAD

**Issue by lstanden** [StrangeLoopGames/EcoIssues#5403] opened 2018-03-05 04:24 UTC
Lasts a few seconds, and a few entries appear before immediately crashing.  Sometimes if I stop the auto refresh fast enough, I can keep the GUI open long enough to select my server favorite, but more often than not it crashes.  Easily repeatable with default settings using Steam edition on Windows 10, GTX 1080.

**Comment by MarjieAVolk** [comment] 2018-03-06 01:13
Could you attach your log file? 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by Macmorious** [comment] 2018-03-06 18:13
have the exact same problem here is my log:
Initialize engine version: 2017.3.0f3 (a9f86dcd79df)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 Ti (ID=0x1b06)
    Vendor:   NVIDIA
    VRAM:     11132 MB
    Driver:   23.21.13.8843
Begin MonoManager ReloadAssembly
- Completed reload, in  0.086 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 4 worker threads for Enlighten.
  Thread -> id: 2a40 -> priority: 1 
  Thread -> id: fe0 -> priority: 1 
  Thread -> id: 204 -> priority: 1 
  Thread -> id: 2b50 -> priority: 1 
UnloadTime: 18.555825 ms
RPC lookup took: 2834.1861ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Ping: Error performing ICMP transmission. Possibly because of a timeout

------------------------------------------------------------
I tried accessing the serverlist via browser, no problem there.

**Comment by MarjieAVolk** [comment] 2018-03-07 22:01
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5501

**Closed by MarjieAVolk** 2018-03-07 22:01 UTC
