### ISSUE TITLE
USER ISSUE: Cannot connect to LocalHost dedicated server

### ISSUE THREAD

**Issue by cr0ss0vr** [StrangeLoopGames/EcoIssues#4189] opened 2018-02-09 19:37 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
load localhost server, any map
load game
attempt connection

**Expected behavior:**
should connect, no problems

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-02-09 19:40
Disabling NAT on your server might help.  You can do this in the server window under Network tab > Config tab > DetectNAT setting.

We are working on a better fix.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4056

**Closed by MarjieAVolk** 2018-02-09 19:40 UTC

**Comment by MarjieAVolk** [comment] 2018-02-09 20:07
Sorry, I realized that the server window has been disabled for local servers, so you can't do this. What you can try though is to select 'Join' and add a server 'localhost:3001'. Hopefully you will be able to connect to that.

**Comment by cr0ss0vr** [comment] 2018-02-09 21:21
seeing as how it was a dedicated server hosted on the same machine (bad practice, i know), and not the ingame stuff, it was ok

**Comment by MarjieAVolk** [comment] 2018-02-12 23:47
Hey, I'm sorry, I gave you the wrong port.  It should be localhost:3000.  Have you been able to get this working?

**Comment by MarjieAVolk** [comment] 2018-02-13 22:55
I just messed this one up real bad XD  But anyway, we have released a fix for the NAT issues.  So hopefully your problem is resolved.
