### ISSUE TITLE
[7.7.0] Resolutions options now have become blah and bloe

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8970] opened 2018-08-15 00:53 UTC
Feels like I just got memed. On current bleeding edge.

![resolutionswitching](https://user-images.githubusercontent.com/35509188/44126035-bb288676-9fea-11e8-8f82-0c37a13bd895.PNG)

**Comment by Nanders** [comment] 2018-08-15 05:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8967

**Closed by Nanders** 2018-08-15 05:43 UTC
Labels: Needs Triage
