### ISSUE TITLE
USER ISSUE: Exiting sign menu prevents user from moving/preforming actions

### ISSUE THREAD

**Issue by microtavor5** [StrangeLoopGames/EcoIssues#4109] opened 2018-02-08 10:10 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
First open sign and select the text box (no need to type, you get the same result with or without entering text, you just nned to have the flashing curser).

Then press esc instead of saveing sign text.

**Expected behavior:**
Exit sign menu and go on your merry way.

**Actual behavior:**
You exit the sign menu but you can not move or open any menus (you can look around though). You need to reconnectr to the server to be able to move again.

**Comment by MarjieAVolk** [comment] 2018-02-13 23:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

Thanks for the additional example.  If you have any more information about it, let me know.

**Closed by MarjieAVolk** 2018-02-13 23:11 UTC
