### ISSUE TITLE
USER ISSUE: Stockpile falling through map

### ISSUE THREAD

**Issue by draygen0352** [StrangeLoopGames/EcoIssues#4650] opened 2018-02-16 18:28 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Stockpile, one layer deep, center item is a pile of logs. 

**Expected behavior:**
not fallen through the map

**Actual behavior:**
I fell through the map

**Comment by MarjieAVolk** [comment] 2018-02-20 22:07
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3897

**Closed by MarjieAVolk** 2018-02-20 22:07 UTC
