### ISSUE TITLE
USER ISSUE: Tree falls but logs don't chops

### ISSUE THREAD

**Issue by SiimonnLeGalerien** [StrangeLoopGames/EcoIssues#22983] opened 2022-02-13 15:16 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
start a single player game, follow the tutorial and try cut logs

**Expected behavior:**
cut logs into pieces

**Actual behavior:**
Can't select logs to chop

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment] 2022-02-14 17:38
Hello @SiimonnLeGalerien ,

Thank you very much for your feedback. Could you give us a more detailed explanation of the issue? Maybe a video/screenshot would be even better. We are very interested in improving our game.

**Comment by D3nnis3n** [comment] 2022-12-02 21:58
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23049

**Closed by D3nnis3n** 2022-12-02 21:58 UTC
Labels: Status: Needs Information
