### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by Weissenburger** [StrangeLoopGames/EcoIssues#4283] opened 2018-02-11 01:45 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Can't join any server since Friday so don't know which patch caused it. **edit** what I meant to say is I haven't been able to join any server on Saturday or Sunday, last time I was able to join a server was on Friday morning.

I bought the game on Steam on the 7th of February created an account on your site and linked it to my steam account on the same day.

Anyway have played since launch, but now when I try to join any server it says:

Connection Failed

Login info could not be verified. Our auth servers may be down.

Unexpected character encountered while parsing value: <. Path ", line 0, position 0

**edit** I have also encountered another Connection Failed that says:

Connection Failed

Login info could not be verified. Our auth servers may be down.

Could not convert string to boolean: Invalid ticket.
Path 'status', line 1, position 26. 

The last one happens occasionally, if I try to connect again to the same server that gives me that one, it gives me the first mentioned connection failed.

**Expected behavior:**

**Actual behavior:**

**Comment by Litschi123** [comment] 2018-02-11 17:59
same here

**Comment by MarjieAVolk** [comment] 2018-02-13 02:14
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4426 - you can continue tracking the issue progress there.

Sorry you have both been unable to connect.  To fill you both in, when these messages show up, something strange is being returned from our authentication servers for your login information.  Unfortunately, it looks like the game isn't handling the errors correctly so it isn't showing the real error messages.

Do either of you have accounts with us?  Or are you only using steam?

**Closed** 2018-02-13 02:14 UTC
