### ISSUE TITLE
USER ISSUE: Disconnecting

### ISSUE THREAD

**Issue by SciIIa** [StrangeLoopGames/EcoIssues#5102] opened 2018-02-25 23:37 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**
Connecting

**Actual behavior:**
The following error message popped up:
`Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object

Stack:
  at TreeEntity.TrySliceTrunk (Eco.Gameplay.Players.Player player, System.Single slicePoint) [0x001be] in <0658334011d54ba9b91e9af1809dba80>:0 
  at TreeEntity.TryApplyDamage (Eco.Shared.Networking.INetObject damager, System.Single amount, Eco.Gameplay.Interactions.InteractionContext context) [0x000d9] in <0658334011d54ba9b91e9af1809dba80>:0 
  at Eco.Gameplay.Items.WeaponItem.OnActLeft (Eco.Gameplay.Interactions.InteractionContext context) [0x00034] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Mods.TechTree.AxeItem.OnActLeft (Eco.Gameplay.Interactions.InteractionContext context) [0x0008a] in <0658334011d54ba9b91e9af1809dba80>:0 
  at Eco.Gameplay.Players.Player+<>c__DisplayClass50_0.<PlayerInteract>b__0 (Eco.Gameplay.Interactions.IInteractable inter) [0x00000] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions+<>c__DisplayClass0_1`1[T].<ExecuteUntilSuccess>b__1 () [0x00000] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess (System.Collections.Generic.IEnumerable`1[T] results) [0x00016] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, System.Func`2[T,TResult] resultFunc) [0x0001f] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Players.Player.PlayerInteract (Eco.Shared.Items.InteractionInfo info) [0x000df] in

**Comment by MarjieAVolk** [comment] 2018-02-26 21:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-26 21:32 UTC
