### ISSUE TITLE
Tooltip in skill UI should appear to left or right of skill

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3330] opened 2018-01-10 01:54 UTC
![image](https://user-images.githubusercontent.com/3150561/34752308-4965bc7c-f566-11e7-8c9c-ba1c65a09a5f.png)

they frequently block me from selected the next skill, since its above my current tooltip

**Comment by MarjieAVolk** [comment] 2018-01-10 19:13
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3327

See this is what I was talking about when I increased the tooltip length in the skills ui PR lol.  But yeah having it appear on the side would be better

**Closed by MarjieAVolk** 2018-01-10 19:13 UTC
Labels: Low Priority
