### ISSUE TITLE
9.0.3 <A ITEMNAME shows blank message

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18494] opened 2020-09-27 17:57 UTC
Enter the below into chat, message shows blank, seems to be <X where X is any character as it does the same for <A

<3 I love coal
<3 Iron Pickaxe

![image](https://user-images.githubusercontent.com/61889138/94372139-4800d880-00f3-11eb-8279-6c26f463dbd3.png)

![image](https://user-images.githubusercontent.com/61889138/94372140-4cc58c80-00f3-11eb-9eb3-0b8d62107c1a.png)

**Comment by SlayksWood** [comment] 2020-09-28 05:57
In develop:
![image](https://user-images.githubusercontent.com/45708377/94395429-6228ce00-0168-11eb-9cb8-7afe7dda8ce1.png)

**Comment by madpingui** [comment] 2021-03-30 16:05
Tested on unity editor develop branch
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/cebe8d38-4df1-4fe5-8e5e-23fefd7fa9f2)

**Comment by Daniel-Magulado** [comment] 2021-04-13 15:33
Tested on 0.9.3 Release-189.

Unable to reproduce.
Seems to be fixed.
Closing.

**Closed by Daniel-Magulado** 2021-04-13 15:33 UTC
Labels: Category: UI, Priority: Low, Squad: Wild Turkey, Status: Fixed
