### ISSUE TITLE
Restarted Server, now world won't load and throws this exception

### ISSUE THREAD

**Issue by Trekkan** [StrangeLoopGames/EcoIssues#12123] opened 2019-04-28 22:00 UTC
No mods installed, etc.  World is 8 days old.  We were experiencing some issues where items from workbenches where being created, but not found in linked storage containers, etc.  So we decided to stop and restart the server, we are now getting the below error (full log posted).

I was able to go back to a backup from 21 hours ago and things work (but of course, we lost 21 hours), so if there is any kind of fix, please let me know!  

Also, I wasn't sure if I should attach my database files, etc... as I don't know if they contain passwords, etc.  If you want those, let me know.
```
[11:54:44.447] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[11:54:44.477] [1] [ Info] [Eco] Eco Server 0.8.1.4 beta
 
[11:54:44.555] [1] [ Info] [Eco] Server Initialization...  
[11:54:44.555] [1] [ Info] [Eco] Starting LocalizationPlugin...  
[11:54:44.923] [1] [ Info] [Eco] Starting ModKitPlugin...  
[11:54:44.923] [1] [ Info] [Eco] Loading mods...  
[11:54:45.041] [1] [ Info] [Eco] Compiling mods...  
[11:54:46.958] [1] [ Info] [Eco] Loading mods finished in 2,032.5ms
 
[11:54:46.958] [1] [ Info] [Eco] Starting NetworkManager...  
[11:54:46.969] [5] [ Info] [Eco] Initializing Simulation Types...  
[11:54:47.025] [12] [ Info] [Eco] Starting WorldGeneratorPlugin...  
[11:54:47.025] [8] [ Info] [Eco] Starting BackupPlugin...  
[11:54:47.025] [15] [ Info] [Eco] Starting GameplayStatsPlugin...  
[11:54:47.025] [8] [ Info] [Eco] Starting StorageManager...  
[11:54:47.514] [5] [ Info] [Eco] Initializing items...  
[11:54:49.528] [8] [ Info] [Eco] Starting PausePlugin...  
[11:54:49.542] [8] [ Info] [Eco] Loading Pause...  
[11:54:51.753] [5] [ Info] [Eco] Initializing skills...  
[11:54:51.842] [8] [ Info] [Eco] Starting StatDatabase...  
[11:54:51.842] [5] [ Info] [Eco] Starting WorldPlugin...  
[11:54:51.886] [5] [ Info] [Eco] Loading World...  
[11:54:52.641] [1] [ Info] [Eco] Server Initialization finished in 8,084.9ms
 
[11:54:52.641] [1] [ Info] [Eco] Failed to load server, Exception was Exception: Exception
Message:Error(s) occurred when loading World
Source:Eco.Core

System.Exception: Error(s) occurred when loading World
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.WorldPlugin..ctor() 
```

**Comment by mirasrael** [comment] 2019-04-29 06:03
Hi @Trekkan Yes, please attach your game save to the issue (which fails to load). It doesn't contain any private information.

**Comment by Trekkan** [comment] 2019-04-29 20:03
Attempted to upload the files (zipped), exceeds file limits.  Will contact you on Discord as suggested.

**Comment by mirasrael** [comment] 2019-04-30 14:57
Investigated problem. One of serialized chunks is broken (it has serializer id == 0 for one of blocks), but I didn't find how it may happen. Added some asserts for now to catch the problem.

**Comment by mirasrael** [comment] 2019-04-30 15:17
Removed from 8.2, because we can't reproduce it and find a repro case, but I added assert so hope eventually we will catch it.

**Comment by johnkslg** [comment] 2020-02-07 21:05
Propose closed as no repro/fixed at some point.

**Closed** 2020-02-25 07:25 UTC
Labels: Priority: High
