### ISSUE TITLE
USER ISSUE: Blocks not placed but resources consumed

### ISSUE THREAD

**Issue by CiberX15** [StrangeLoopGames/EcoIssues#6211] opened 2018-03-17 23:22 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Begin building a large structure (Hewn Logs?)
2.Keep building untill you click to place and a block does not appear in the world
3. Observe, attempting to place blocks in that location will cause blocks to be removed from inventory but not be placed in world.

**Expected behavior:**
When right clicking to place a block, the block should be placed in the world, the the resources should be removed.

**Actual behavior:**
When right clickign to place a block in certain locations, the block is never placed but resources are consumed.

**Comment by neyna** [comment] 2018-03-18 12:38
I faced this bug a lot of time too. It's random. Sometimes you can get back some of the resources you lost by removing the invisible block. And sometime if you log out/log in the block will be placed.

**Comment by MarjieAVolk** [comment] 2018-03-21 18:58
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5900

**Closed by MarjieAVolk** 2018-03-21 18:58 UTC

**Comment by CiberX15** [comment] 2018-03-21 21:13
I don't think this is a dupe of #5900 In that bug you had to be at the top of the world, and you got the blocks back. In this bug, it can occur anywhere, and the blocks are permanently lost.

**Comment by MarjieAVolk** [comment] 2018-03-21 21:41
Okay I got the bugs mixed up, I should have linked to this one: https://github.com/StrangeLoopGames/EcoIssues/issues/5906

Does that sound like your problem?
