### ISSUE TITLE
The various early-game construction skills are skill taxes

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7084] opened 2018-04-09 13:13 UTC
Building a staircase, roof, window, column... doesn't really matter what the construction material is.
Raise the price a little and roll all of the tier buildings in together into a single, unified construction tree. Tier 1 construction, tier 2 construction, tier 3 construction. Separate skills, but all significantly more useful and more valuable than they currently are.

Noone on my server is taking them. Because we have actual needs and they're *way* too expensive.

**Comment by Dreepa** [comment] 2018-04-09 17:34
https://github.com/StrangeLoopGames/EcoIssues/issues/6921

**Comment by MarjieAVolk** [comment] 2018-04-09 17:45
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6921

I will paste your suggestion over there.  Thanks!

**Closed by MarjieAVolk** 2018-04-09 17:45 UTC
