### ISSUE TITLE
Can not reconnect to server after getting dropped w/ error msg

### ISSUE THREAD

**Issue by NataSpawN** [StrangeLoopGames/EcoIssues#8854] opened 2018-08-05 05:56 UTC
3 users were on the server and with no warning were dropped due to the following error...

Login token changed.

Please see the notepad attachment for the full log.
[ECO Error (Login Token Changed) - 080418.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2260062/ECO.Error.Login.Token.Changed.-.080418.txt)

**Comment by seccombew** [comment] 2018-08-06 22:09
Likely due to steam going down for a moment. @rainfarmer can we add more tolerance to Auth.

**Comment by metachronism** [comment] 2018-08-14 20:15
dupe of #8835

**Closed by metachronism** 2018-08-14 20:15 UTC
Labels: High Priority
