### ISSUE TITLE
[Client] v0.7.1.2-beta Error getting tooltip text (screenshot)

### ISSUE THREAD

**Issue by kroovysteph** [StrangeLoopGames/EcoIssues#5565] opened 2018-03-07 10:07 UTC
Running v0.7.1.2-beta.
Error getting Wooden Latrine tooltip text while hovering.

![tooltip_exception](https://user-images.githubusercontent.com/8964376/37086214-51244f92-21f7-11e8-96b9-6db4e7398c48.png)

**Comment by MarjieAVolk** [comment] 2018-03-08 20:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2084

**Closed by MarjieAVolk** 2018-03-08 20:29 UTC
