### ISSUE TITLE
Floating baby grass

### ISSUE THREAD

**Issue by stett** [StrangeLoopGames/EcoIssues#641] opened 2016-10-20 19:22 UTC
![image](https://cloud.githubusercontent.com/assets/5872141/19574564/c55e2bd6-96bf-11e6-821d-ac4c2bb93edf.png)
At least I think that's what this is

**Comment by metachronism** [comment] 2016-10-20 20:14
dupe of #626

**Closed by metachronism** 2016-10-20 20:14 UTC
