### ISSUE TITLE
targeted objects dont unhighlight until you look at a block

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2950] opened 2017-11-30 18:22 UTC
regardless of the distance you move away from the object

![image](https://user-images.githubusercontent.com/3150561/33447502-608e2ae2-d5b8-11e7-9e05-581590212d2a.png)

look at a tree trunk, then scoot away from it being careful to not look at any blocks or anything else nearby.  it is supposed to un-highlight once you move out of interaction range

**Comment by SeanAtr0n** [comment] 2017-11-30 20:24
works for me so far... anything else you did?

**Comment by BlazeGuy2** [comment] 2018-06-05 23:15
Can't reproduce, closing.

**Closed by BlazeGuy2** 2018-06-05 23:15 UTC
