### ISSUE TITLE
USER ISSUE: Small wood cart shows inventory that it should not

### ISSUE THREAD

**Issue by RaptorRaptures** [StrangeLoopGames/EcoIssues#11611] opened 2019-03-08 15:53 UTC
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
1. Open cart near your stock pile
2. Drag and drop items to the cart
3. Carry your cart 100m away
4. Use the cart, note that you can still see the inventory from where you dragged the stuff from and you can still access that inventory
5. NOT ALWAYS REPRODUCABLE

**Expected behavior:**
Cart should not have access to inventory not in range

**Actual behavior:**
Cart has access to inventory in range

**Do you have mods installed? Does issue happen when no mods are installed?:**
Cart has access to inventory in range

**Comment by D3nnis3n** [comment] 2019-03-09 02:32
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9289

**Closed by D3nnis3n** 2019-03-09 02:32 UTC
Labels: Investigate, Medium Priority
