### ISSUE TITLE
USER ISSUE: Cannot connect

### ISSUE THREAD

**Issue by kerediansaar** [StrangeLoopGames/EcoIssues#5394] opened 2018-03-05 00:25 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Click connect  with friends tab on steam

Or

Join friend via invite on steam	

**Expected behavior:**
Joined friends world

**Actual behavior:**
Cannot connect

**Comment by MarjieAVolk** [comment] 2018-03-06 02:16
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

For a workaround, I would suggest trying to connect to your friend's server via ip address, by going to Join and then clicking Add Server

**Comment by MarjieAVolk** [comment] 2018-03-06 22:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5238 and/or https://github.com/StrangeLoopGames/EcoIssues/issues/4909

**Closed by MarjieAVolk** 2018-03-06 22:25 UTC
