### ISSUE TITLE
USER ISSUE: Floating Icons

### ISSUE THREAD

**Issue by Loith** [StrangeLoopGames/EcoIssues#5151] opened 2018-02-26 23:13 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Drag an item from your Bar to between two slots in your back.

**Expected behavior:**
Picked a slot (which one was free or put back on bar if none available)

**Actual behavior:**
Created a floating icon. This cannot be moved. Also on the action bar there is now an "empty" slot which is unuseable.

**Comment by MarjieAVolk** [comment] 2018-02-26 23:43
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

Minimizing the game and reopening it has been known to fix stuck icons.

**Closed by MarjieAVolk** 2018-02-26 23:43 UTC
