### ISSUE TITLE
[SERVER ISSUE 7.2.5] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#6298] opened 2018-03-19 22:45 UTC
Brand new "Object reference not set to an instance of an object." that I have never seen before.
```
--BEGIN DUMP--
Dump Time
03/19/2018 22:15:38

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Simulation.Agents.Animal.Damage(Single amount, DeathType damageSource)
   at Eco.Simulation.WorldLayers.Layers.AnimalLayer.DamageAnimals(Vector2i layerPos, Single maxDamage)
   at Eco.Simulation.WorldLayers.Layers.AnimalLayer.Push(Vector2i layerPos)
   at Eco.Simulation.WorldLayers.Layers.AnimalLayer.Push()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Simulation.WorldLayers.WorldLayerSync.<>c.<Tick>b__11_5()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerSync.Tick()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.TryTick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
```

**Comment by MarjieAVolk** [comment] 2018-03-20 00:54
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4860 (seems like this can happen from animals getting killed in a variety of ways).

**Closed by MarjieAVolk** 2018-03-20 00:54 UTC
