### ISSUE TITLE
Relay server masking default WebServerUrl value

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#24723] opened 2024-02-02 14:34 UTC
When connecting through a relay server and no parameter is set in `WebServerUrl`, then players will experience issues when trying to access the web server from in-game, as they will instead be directed to the relay server address instead of the external IP address of the server, which is supposed to be the default.

The aggressive use of relay servers is starting to cause more and more problems, from masking IP addresses, increased player latency, and now a direct negative effect to players that is unintended behaviour.

While this can be easily rectified by simply setting a parameter in `WebServerUrl`, including just putting the external IP address of the server in there, the fact of the unintended effect still remains. I just wonder what will be the next thing that will be negatively affected by the aggressive, forced and seemingly random use of the relay server, as the problem would appear to be getting worse as time has gone on.

**Comment by D3nnis3n** [comment] 2024-02-02 17:58
This works as intended, hence closing.

Relay servers are only used if the player cannot otherwise connect to your server, either due to local connection issues, ISP issues or connection issues with the server being misconfigured (for example not having set RemoteAddress correctly). The relay is never used if the player can connect to the server directly. Our official servers experience basically zero relay users.

When connected via the relay server, the player actually plays through another server and without a WebServerUrl set will use the default settings, which due to the relay server appearing to him as server is the IP of exactly that. It is strongly recommended to set WebServerUrl and considered a user error to not do so.

**Closed by D3nnis3n** 2024-02-02 17:58 UTC

**Comment by Dave247** [comment] 2024-02-04 03:07
Maybe there has been a change of procedure then, as it has always been the case that the remote address and web server url is not necessary to set when it is able to automatically detected.  The description provided in the server UI even states for both "Usually you should ignore it", which is at direct contrast to what you said now that it is considered a user error for not setting a value.

**Comment by D3nnis3n** [comment] 2024-02-04 05:12
Well, in most cases it does not need to be configured, but for example the #server-help channel on discord does mention that it should be set if you experience connection issues for users - which includes them only being able to connect via relay server:

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/0b7c2295-c9e7-4a71-988e-b3ee2647d485)

Insofar the "usually it can be ignored" is not wrong - but if you are experiencing issues, it needs to be set. The reasons why such issues can be experienced are countless and depend highly on how your dedicated server and network is configured.
