### ISSUE TITLE
USER ISSUE: Error when doing nothing

### ISSUE THREAD

**Issue by B1sounours** [StrangeLoopGames/EcoIssues#5577] opened 2018-03-07 12:57 UTC
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
afk

**Expected behavior:**
-

**Actual behavior:**
The following error message popped up:
```Caught exception:

<size=60,00%>L'argument spécifié n'était pas dans les limites de la plage des valeurs valides.
Nom du paramètre : arrayIndex


Stack:
   à System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   à System.Collections.Immutable.ImmutableList`1.CopyTo(T[] array, Int32 arrayIndex)
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   à Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   à Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   à Eco.Plugins.Networking.Qua

**Comment by MarjieAVolk** [comment] 2018-03-08 00:30
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5527

**Closed by MarjieAVolk** 2018-03-08 00:30 UTC
