### ISSUE TITLE
USER ISSUE: Crash while picking up a log

### ISSUE THREAD

**Issue by imdutch21** [StrangeLoopGames/EcoIssues#5086] opened 2018-02-25 15:58 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. have a random log laying around from someone else
2. try to pick it up 
3. crash

**Expected behavior:**
It should have not crashed

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by Mahsaap** [comment] 2018-02-25 17:44
Same here https://github.com/StrangeLoopGames/EcoIssues/issues/5081

**Comment by MarjieAVolk** [comment] 2018-02-26 19:04
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-26 19:04 UTC
