### ISSUE TITLE
Beds are buggy

### ISSUE THREAD

**Issue by Ket-SLG** [StrangeLoopGames/EcoIssues#9632] opened 2018-10-03 01:05 UTC
It toggles off the UI in a weird way. 

Also when you try to finish sleeping you can't leave the bed and there are some issues with the text not going away.

https://www.youtube.com/watch?v=HgQdTeCOg_4

**Comment by D3nnis3n** [comment] 2018-10-04 17:07
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9571

**Comment by johnkslg** [comment] 2018-10-12 20:44
Fixed in master and staging!

**Closed by johnkslg** 2018-10-12 20:44 UTC
Labels: High Priority
