### ISSUE TITLE
USER ISSUE: Invisible Bloomery

### ISSUE THREAD

**Issue by NaNoXiDo** [StrangeLoopGames/EcoIssues#10050] opened 2018-11-17 00:44 UTC
**Version:** 0.7.8.2 beta

**Steps to Reproduce:**
Go far away do unload the Chunk where the Bloomery is in.

**Expected behavior:**
Is should be visible.

**Actual behavior:**
It's "hidden" / not visible but it's there and can be interacted with.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
It's "hidden" / not visible but it's there and can be interacted with.

**Comment by D3nnis3n** [comment] 2018-11-17 09:54
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9263

**Closed by D3nnis3n** 2018-11-17 09:54 UTC
