### ISSUE TITLE
USER ISSUE: Kicked of a server (Failed to handle RPCResponse)

### ISSUE THREAD

**Issue by Maax70** [StrangeLoopGames/EcoIssues#21418] opened 2021-04-16 15:01 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
When I open the economic tab with all the differents trading (Y)
And I put a filter to search a specific category or filter for ascending price
And then scroll and i'm kicked with the following error message.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
The server where i'm playing have better stockpile and carry capacity

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6326059/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6326060/Player-prev.log)

**Comment by D3nnis3n** [comment] 2021-04-16 15:40
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/21382

**Closed by D3nnis3n** 2021-04-16 15:40 UTC
