### ISSUE TITLE
Vehicle problems

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11768] opened 2019-03-27 18:37 UTC
- Can't get out of vehicles
- Putting carried gas into excavator didnt put it in the fuel slot

**Comment by redwyre** [comment] 2019-03-27 18:59
I can get out of my excavator that has fuel, when is unfueled

**Comment by D3nnis3n** [comment] 2019-03-27 21:07
Partly duplicate of #11733

**Comment by D3nnis3n** [comment] 2019-03-27 21:09
Actually the other part is duplicate of #11769

**Closed by D3nnis3n** 2019-03-27 21:09 UTC
Labels: High Priority, Staging
