### ISSUE TITLE
Beta Staging - Repair a Bow throws Exception Error and corrupts the server save.

### ISSUE THREAD

**Issue by bruteman** [StrangeLoopGames/EcoIssues#6433] opened 2018-03-24 03:05 UTC
Try to repair a bow and this exception is thrown by the server and server data from this point forward is corrupt.
[ClientNetworkException Exception 03230148.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1843976/ClientNetworkException.Exception.03230148.zip)

**Comment by bruteman** [comment] 2018-03-24 18:09
Its the Free bow you get from unlocking hunter i /dumped everyone's errored bow and crafted a new one and it seems fine waiting to test damage / repair of a crafted bow.

**Comment by bruteman** [comment] 2018-03-25 07:21
Version: 0.7.3.0 beta staging-1c5d112f

**Comment by bruteman** [comment] 2018-03-25 16:00
Repairing a Road tool also throws a exception and corrupts the save file

**Comment by MarjieAVolk** [comment] 2018-03-26 22:10
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6494 (I always feel a little bad closing the older bug as a duplicate :P)

**Closed by MarjieAVolk** 2018-03-26 22:10 UTC
