### ISSUE TITLE
USER ISSUE: All pipes tier 0

### ISSUE THREAD

**Issue by werkrat** [StrangeLoopGames/EcoIssues#10129] opened 2018-11-25 23:55 UTC
**Version:** 0.7.8.5 beta

All pipes are tier 0. I don't know if it's intentional or not, but copper should be 1, iron 2, steel tier 3... imo

**Comment by D3nnis3n** [comment] 2018-11-26 02:50
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9393

**Closed by D3nnis3n** 2018-11-26 02:50 UTC
