### ISSUE TITLE
User timing out as inactive when logging in

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7773] opened 2018-05-14 23:03 UTC
User times out at 52% loaded everytime, in a large world.

In general clients should never time out when the client thread is active in some operation.  The timeout detection should require that the thread is responsive.

**Comment by metachronism** [comment] 2018-05-14 23:54
dupe of lots of other issues already posted

**Closed by metachronism** 2018-05-14 23:54 UTC
Labels: High Priority
