### ISSUE TITLE
Stomach contents not appearing

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#415] opened 2016-07-02 02:02 UTC
icons not working

**Comment by noblackthunder** [comment] 2016-07-04 00:11
there seems to be a general bug with icons depending on the server. on my localy hosted server i cant see text or icons while on my win2012r2 server everything is fine . tested it, and i can change back and forward without closing the game, still the same. one server is fine the other one makes my UI buggy and not working as intended

**Closed** 2017-03-21 22:30 UTC
