### ISSUE TITLE
Server crashes when claiming

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2566] opened 2017-10-18 20:33 UTC
Hello! This issue is caused in the **latest build**.

Server crashes when claiming land. Though only for one specific user and not for anyone else..

The message recieved was: 
Caught exception: Object reference has not been specified to an instance of an object.

_I had another message earlier telling me that the file was already used by another instance._

Crash logs:

- --BEGIN DUMP--
- Dump Time
- 10/18/2017 19:41:16
- 
- Exception
- System.IO.IOException: Processen kan inte komma åt filen D:\Spel\Eco\Servers\EcoServer_v0.6.0.1-alpha-staging-296b2a9a\Dump\ClientUpdateException 10184116.ecodmp eftersom den används i en annan process.
-    vid System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
-    vid System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
-    vid System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
-    vid Eco.Core.Utils.ExceptionExtensions.Dump(Exception exception, String dumpType)
-    vid Eco.Plugins.Networking.Clients.Client.<.ctor>b__50_1()
-    vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
-    vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
-    vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
-    vid System.Threading.ThreadHelper.ThreadStart()
- 
- --END DUMP--

- --BEGIN DUMP--
- Dump Time
- 10/18/2017 19:39:49
- 
- Exception
- System.IO.IOException: Processen kan inte komma åt filen D:\Spel\Eco\Servers\EcoServer_v0.6.0.1-alpha-staging-296b2a9a\Dump\ClientUpdateException 10183949.ecodmp eftersom den används i en annan process.
-    vid System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
-    vid System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
-    vid System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
-    vid Eco.Core.Utils.ExceptionExtensions.Dump(Exception exception, String dumpType)
-    vid Eco.Plugins.Networking.Clients.Client.<.ctor>b__50_1()
-    vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
-    vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
-    vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
-    vid System.Threading.ThreadHelper.ThreadStart()
- 
- --END DUMP--

- - --BEGIN DUMP--
- - Dump Time
- - 10/18/2017 19:41:16
- 
- Exception
- System.IO.IOException: Processen kan inte komma åt filen D:\Spel\Eco\Servers\EcoServer_v0.6.0.1-alpha-staging-296b2a9a\Dump\ClientUpdateException 10184116.ecodmp eftersom den används i en annan process.
-    vid System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
-    vid System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
-    vid System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
-    vid Eco.Core.Utils.ExceptionExtensions.Dump(Exception exception, String dumpType)
-    vid Eco.Plugins.Networking.Clients.Client.<.ctor>b__50_1()
-    vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
-    vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
-    vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
-    vid System.Threading.ThreadHelper.ThreadStart()
- 
- --END DUMP--

**Comment by wiloxe** [comment] 2017-10-19 10:19
By latest version do you mean staging version or current version?

**Comment by wiloxe** [comment] 2017-10-19 10:49
Ah, Missed that part. Yeah, this is the staging version.
The 6.0.1 staging version is not the latest build, the latest build is the current version right now so I recommend you use that for now.

**Comment by ZebZ** [comment] 2017-10-19 11:08
Well isn't staging version like a test version?

**Comment by wiloxe** [comment] 2017-10-19 18:05
When they move from staging to current they keep the old staging and make the current one the latest. You have to wait for staging version number for an example 6.0.1 to be greater than that of the current.
That's how I've seen it from past versions.

**Comment by ZebZ** [comment] 2017-10-21 13:00
hmm okey. Thanks :)

**Comment by MarjieAVolk** [comment] 2017-10-23 20:30
Do you have the complete stack trace from the crash itself?  Also is the whole server crashing, or is the player being kicked from the server?

**Comment by ZebZ** [comment] 2017-10-24 01:45
The whole server crashes/stops responding as of files already being run by something else. Where can i find the stack trace?

**Comment by MarjieAVolk** [comment] 2017-10-24 17:34
Yeah, if you have more logs with the crash error message, that's what I'm looking for

**Comment by ZebZ** [comment] 2017-10-24 18:09
```
--BEGIN DUMP--
Dump Time
10/16/2017 22:00:18

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on ToolbarInventory!

Objektreferensen har inte angetts till en instans av ett objekt.


Stack:
   vid Eco.Gameplay.Items.InventoryChangeSet.MoveStacks(ItemStack source, ItemStack destination)
   vid Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)



Stack:
   vid Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   vid Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   vid Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

   vid Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   vid Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   vid Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   vid Eco.Shared.Networking.NetPort.ProcessBuffer()
   vid Eco.Shared.Networking.NetPort.Update()
   vid Eco.Plugins.Networking.Clients.Client.<.ctor>b__50_0()

--END DUMP--
```

**Comment by ZebZ** [comment] 2017-10-24 18:18
That should be all :)

[ClientNetworkException 10160018.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411956/ClientNetworkException.10160018.txt)
[ClientNetworkException 10170745.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411957/ClientNetworkException.10170745.txt)
[ClientNetworkException 10173232.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411958/ClientNetworkException.10173232.txt)
[ClientNetworkException 10182604.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411959/ClientNetworkException.10182604.txt)
[ClientNetworkException 10182756.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411960/ClientNetworkException.10182756.txt)
[ClientNetworkException 10183949.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411961/ClientNetworkException.10183949.txt)
[ClientNetworkException 10184116.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411962/ClientNetworkException.10184116.txt)
[ClientUpdateException 10182756.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411963/ClientUpdateException.10182756.txt)
[ClientUpdateException 10182757.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411964/ClientUpdateException.10182757.txt)
[ClientUpdateException 10182852.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411965/ClientUpdateException.10182852.txt)
[ClientUpdateException 10183949.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411966/ClientUpdateException.10183949.txt)
[ClientUpdateException 10184116.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411967/ClientUpdateException.10184116.txt)
[Crash 10162135.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411968/Crash.10162135.txt)
[Crash 10183949.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411969/Crash.10183949.txt)
[Crash 10184116.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411970/Crash.10184116.txt)
[Crash 10213243.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411971/Crash.10213243.txt)
[Crash 10213336.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1411972/Crash.10213336.txt)

**Comment by MarjieAVolk** [comment] 2017-10-24 18:33
Okay looks like you've got some null refs here (this would happen when dragging items around, so that's a separate issue):
```
   vid Eco.Gameplay.Items.InventoryChangeSet.MoveStacks(ItemStack source, ItemStack destination)
   vid Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)
```

And some null refs here (that would be the property claim one):
```
   vid Eco.Gameplay.Property.PropertyManager.ClaimAtomicAction.<TryApply>b__5_0(KeyValuePair`2 x)
   vid System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   vid Eco.Gameplay.Property.PropertyManager.ClaimAtomicAction.TryApply()
   vid Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   vid Eco.Gameplay.Items.PropertyClaimItem.TryPlaceObject(Player player, Vector3i position, Quaternion rotation)
   vid Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass13_0.<OnActRight>b__0(BSONObject response)
```

Oh and there's also a few null refs here (also property related):
```
   vid Eco.Gameplay.Property.PropertyPlot.ToBson()
   vid Eco.Gameplay.Minimap.MinimapManager.GetPropertySince(Double time)
   vid Eco.Gameplay.Minimap.MinimapManager.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   vid Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   vid Eco.Plugins.Networking.Clients.Client.Update()
   vid Eco.Plugins.Networking.Clients.Client.<.ctor>b__50_1()
```

And then you've got some mod and IO exceptions, which I'm assuming are from you messing around with mods / moving files around.

Okay, so taking a look at those exceptions

**Comment by MarjieAVolk** [comment] 2017-10-24 18:43
Okay so I'm guessing that you've got a property that has no owner - which is not supposed to happen.

You said that this bug happens every time for one specific user?  I'm wondering, is the bug actually happening only for a specific place in the world?  If someone else tried to claim the same land, will they also see this bug?

Attaching the save file might be helpful; although in this case, if I'm correct, the bug is that a property somehow lost its owner, which presumably happened a while ago and isn't still happening.

**Comment by MarjieAVolk** [comment] 2017-10-24 18:58
In fact, this is probably related to https://github.com/StrangeLoopGames/EcoIssues/issues/2599

**Comment by ZebZ** [comment] 2017-10-24 19:48
I have not touched a single mod, all files are clean :)

and the bug did not occur when another user claimed it for the "specific user" to prevent any griefing. After this the "specific user" have not logged on until now. As i ccidentally removed the Storage folder we have reset the entire server. I will come back if we can reproduce the bug. Most of my users are pretteeyh good at finding bugs and reproducing them....

**Comment by TheMathewNorman** [comment] 2017-10-25 02:56
I've also been experiencing this issue.

I can confirm it was also present in 6.0.0 before the 6.0.1 update. Thus far I've only experienced it with a single player at a time. That's to say, other players can place land claims anywhere where land is unclaimed except the player affected.

I'm currently experiencing this issue again on 6.0.1 with another one of my players.
All server installs are vanilla, no mods.
I can also provide crash dumps for both the 6.0.0 and 6.0.1 too if required.

**Comment by MarjieAVolk** [comment] 2017-10-25 17:35
Okay, sounds like it's not quite what I thought then.  A game save would be really helpful.

**Comment by ZebZ** [comment] 2017-10-25 21:13
Thats gona be hard for me.. That save is gone xp

**Comment by MarjieAVolk** [comment] 2017-10-26 17:29
I do think this is the same thing as https://github.com/StrangeLoopGames/EcoIssues/issues/2599

We found that this error is due to corrupt deeds.  If the person who sees the error removes any deeds that say 'Unnamed Area' from their inventory, that should allow them to claim property again.  We're still investigating what causes deeds to get corrupted.

**Comment by ZebZ** [comment] 2017-10-26 19:49
Well  i just placed a cart and i was never given a deed. I can not even take control of the cart. Nothing happens at all when pressing E. Though the inventory works. I do have a world file now :)

**Comment by ZebZ** [comment] 2017-10-26 19:53
Well i just stepped on to the problem about deeds. I placed a cart (literaly just made it). Got not deed. Checked inside the cart and there was the deed. Unnamed and with no owner..

**Comment by MarjieAVolk** [comment] 2017-10-26 20:02
Oooooh that gives me some ideas

**Comment by metachronism** [comment] 2017-11-01 18:32
dupe of #2599

**Comment by MarjieAVolk** [comment] 2017-11-01 19:24
Yeah it is, I think I'll close that one

**Closed** 2017-11-10 23:35 UTC
Labels: High Priority

**Comment by Yorkforce** [comment] 2017-12-17 00:37
@MarjieAVolk 
Sorry to drag up an old issue, I can make a new one if required.

We are still experiencing this in 6.2.0, we have had 2 players get the 'Unnamed Area' deed bug which continues to crash the server with a Object Reference not found error. They are able to claim again if they remove the offending deed from thier inventory.

https://pastebin.com/5GJk3zj0
