### ISSUE TITLE
7.1.1 Server Crashing over and over

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#4642] opened 2018-02-16 17:00 UTC
I ran into this problem previous on a 7.0 staging build. I submitted a ticket, #3805, about it then. I'm opening a new ticket to report the issue again. Our server is not usable at this point because 2 or 3 minutes after launching it, when whatever crafting job finishes that is causing this issue, it crashes. I have included the dump and a worldsave.
Game Save: https://1drv.ms/u/s!AtWN_MtzJ9-Gy2XrIjrt7k9NuOk5
--BEGIN DUMP--
Dump Time
02/16/2018 11:16:48

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.WorkOrder.set_UncraftedQuantity(Int32 value)
   at Eco.Gameplay.Items.WorkOrder.UpdateCrafted()
   at Eco.Gameplay.Items.WorkOrder.set_Progress(Double value)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-14 23:02
Okay, I finally got around to looking at this - sorry that took so long.  And it looks like in the save you gave me, there is a work order that belongs to a player who doesn't exist.  As far as I know, this should only happen if you have manually deleted user files out of the game save (which is not always safe to do, for reasons such as this).  So I think that is the error.  Seeing as how we have no other reports of this, closing as working as intended, since save doctoring is not always safe.

**Closed by MarjieAVolk** 2018-03-14 23:02 UTC
Labels: High Priority
