### ISSUE TITLE
USER ISSUE: [Dedicated Win 7.2.3]Fen seed planting: Planted seed take seconds to appear on ground

### ISSUE THREAD

**Issue by lefavilla** [StrangeLoopGames/EcoIssues#5827] opened 2018-03-10 10:39 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. prepare ground with wood hoe
2. set fen seed on it

**Expected behavior:**
It should appear instant or fast

**Actual behavior:**
Instead it takes seconds to appear on ground.

**Comment by lefavilla** [comment] 2018-03-10 10:41
Has nothing to do with hardware. Server runs at an very strong server with just 5 player on it :)

**Comment by MarjieAVolk** [comment] 2018-03-12 23:14
Going to close as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5829, sounds like the same deal.

**Closed by MarjieAVolk** 2018-03-12 23:14 UTC
