### ISSUE TITLE
Missing chunks

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#10854] opened 2019-01-23 22:38 UTC
@mirasrael I filed this bug based on the comments you left after playing 8.0 tonight. Can you flesh it out with the details?

**Comment by elfl0rd** [comment] 2019-01-23 22:42
(staging) maybe fix from master is not merged?

**Comment by mirasrael** [comment] 2019-01-24 09:58
Seems this problem is random. I wasn't able to reproduce it after relog.
![image](https://user-images.githubusercontent.com/475445/51670446-af3dbf80-1fd7-11e9-8d6b-666c8d6c3681.png)

Also on my stream record (at 1:19:30):
https://www.twitch.tv/videos/368532410

**Comment by mirasrael** [comment] 2019-01-24 10:00
Save: https://drive.google.com/file/d/1X3eCkaD3-dfGJXpTDB3u4UsXGMP7sLsM/view?usp=sharing

**Comment by elfl0rd** [comment] 2019-01-24 10:30
maybe refers to https://github.com/StrangeLoopGames/EcoIssues/issues/10289

**Comment by elfl0rd** [comment] 2019-01-24 22:31
still happens at staging branch

**Comment by elfl0rd** [comment] 2019-01-26 09:15
![20190125235311_1](https://user-images.githubusercontent.com/4980243/51785111-138d8a00-2164-11e9-9777-9d5c2f27bfae.jpg)
but this is client-side, not server.

**Comment by Ruined1** [comment] 2019-01-26 20:54
v0.7.8.9

Happens while mining too with single blocks:
![image](https://user-images.githubusercontent.com/1514573/51792677-b05f2000-2182-11e9-97dd-a6d308e40bf1.png)
(Found by The_Revanchist)

**Comment by TheGreatRevanchist** [comment] 2019-01-26 21:01
Yeah and it just gets worse as we mine around the area....
![image](https://user-images.githubusercontent.com/10445672/51792725-72163080-2183-11e9-899c-f5edf22761fa.png)

Walking into it teleports you up to the surface of where you are
Not a clue what the cause is however

**Comment by Ruined1** [comment] 2019-01-27 02:09
> Yep, seems absolytely random.
> But terribe, i hate it.

when I dug into the other side of the chunk, same thing happened, so at least it's not an error of random blocks not showing up, but the actual entire chunk. That should help narrow it down.

**Comment by redwyre** [comment] 2019-01-27 08:59
Do you have a world save where it's reproducible?

**Comment by mirasrael** [comment] 2019-01-27 09:02
@redwyre  I believe it reproducible on any save, but it is a random issue. It may happen, you relog or restart server and you will not see it on the same place, but later you may see it in another place. Or you can go away, then return and see it on same place where it was ok 10 minutes ago.
I have attached the save above on which I observed this issue.

**Comment by elfl0rd** [comment] 2019-01-31 20:37
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2818924/output_log.txt)
![20190131222738_1](https://user-images.githubusercontent.com/4980243/52083679-27484e80-25b1-11e9-90dd-7185875b8b3c.jpg)
![20190131223913_1](https://user-images.githubusercontent.com/4980243/52083687-2dd6c600-25b1-11e9-8785-5e608c690c17.jpg)

**Comment by redwyre** [comment] 2019-01-31 21:56
This is the relevant error:
```
NullReferenceException: Object reference not set to an instance of an object.
  at ChunkRender.ForceGroupUpdate (System.Single priority) [0x00000] in <00000000000000000000000000000000>:0 
  at World.SetBlock (Eco.Shared.Math.Vector3i worldPos, System.UInt16 blockID, System.Byte extraByte, System.Boolean track) [0x00000] in <00000000000000000000000000000000>:0 
  at PredictBlockChange.SetBlock (Eco.Shared.Math.Vector3i pos, System.UInt16 blockID, Eco.Shared.Items.InteractionInfo info, System.Byte extraByte) [0x00000] in <00000000000000000000000000000000>:0 
  at InteractionManager.SendInteraction (Eco.Shared.Items.InteractionMethod method) [0x00000] in <00000000000000000000000000000000>:0 
  at PlayerHeldObject.ProcessInput () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)
```

**Closed** 2019-02-01 18:39 UTC
Labels: Fixed, High Priority, Investigate
