### ISSUE TITLE
USER ISSUE: Fishing

### ISSUE THREAD

**Issue by Vcari** [StrangeLoopGames/EcoIssues#5065] opened 2018-02-25 04:03 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I started to fish and once caught the fish reeled it in and the fish had not appeared in my inventory mainly to fix it I would usually have to relog its a small bug but just making sure you guys know of it 
Thanks

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-26 21:57
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

**Closed by MarjieAVolk** 2018-02-26 21:57 UTC
