### ISSUE TITLE
USER ISSUE: Duplicate Character Model on Self hosted server

### ISSUE THREAD

**Issue by renatokuipers** [StrangeLoopGames/EcoIssues#24772] opened 2024-02-16 21:34 UTC
\
**User Id: (slg38768)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
1. Create own Dedicated server2. Join the server with friend and play3. leave the server and join server again4. Enjoy having a double character model that uses double as much resources.....
5. Other players don't have this issue, only my, who is playing on the same PC as where the server is running on.

**Expected behavior:**
It should only have 1 character model....

**Actual behavior:**
After some time (unknown why exactly) when I join the server again after a few hours of pause, I spawn with a double character model which also uses each resource and food or arrows for each model....

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yeah, I have mods installed, and it also happens without mods or even if I try to start a private world.... (so without a dedicated server)...Also tried to reinstall Eco, but this doesn't solve the issue. Also cleared everything in appdata and in the registry, but no luck... this is a VERY annoying bug, that is already in this game for... what.... 4 years??? Please solve this issue ASAP since this will ruin the gameplay experience.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14316224/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14316225/Player-prev.log)

**Comment by renatokuipers** [comment] 2024-02-16 21:36
Please don't come with a "Duplicate of bla bla" section, since this will not solve the issue... those threads are DEAD...
Please revive this tread instead and try to come up with a solution for this most annoying issue/bug.

**Comment by D3nnis3n** [comment] 2024-02-17 15:11
Well, we can instead merge the issue this is a duplicate of into this, if you prefer that.

It unfortunately doesn't change anything about the fact that the issue is not reproducible with the provided steps and we need a reproduction case to be able to fix it. Without being able to reproduce we cannot fix it.

**Comment by D3nnis3n** [comment] 2024-02-26 12:38
For the meanwhile, one user on Steam found something that helped them fix the problem. Could you try to reproduce the steps and see if it helps for your case as well?

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/f5287b41-7dce-4c8d-b6e1-6c77ccf2d9de)

**Comment by ShallowTeal** [comment] 2024-04-14 20:22
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14971996/Player.log)
I'm running nearly minimal settings and I haven't tested this on other servers but it persists every time I log in and sometimes copies my playermodel twice so I end up seeing 3 models. 

Any further questions and I will happily answer

**Comment by Daniel-Magulado** [comment] 2024-04-15 12:02
@ShallowTeal What server are you connecting to?
How frequent it is happening for you?

**Comment by ShallowTeal** [comment] 2024-04-15 12:20
> @ShallowTeal What server are you connecting to? How frequent it is happening for you?

Third Rock eco server High collab and it is happening quite literally the entire time I play.

**Closed** 2024-04-22 09:55 UTC
Labels: Status: Needs Information, Status: Not reproduced
