### ISSUE TITLE
[High Priority] Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoIssues#4245] opened 2018-02-10 13:28 UTC
This issue is happening quite a lot for a lot of people since the latest patch, and has been reported by multiple.

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.

Stack:
bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
bei Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
bei Eco.Plugins.Networking.Clients.Client.ShouldSelectUser()

http://steamcommunity.com/app/382310/discussions/0/1699416432420796112/

**Comment by MarjieAVolk** [comment] 2018-02-13 05:18
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4413.  You can track the issue progress there.

We already have a fix for this, which will go out in the next update.  Unfortunately, until then you may not be able to play on this server.  You should be able to play on other servers.

**Closed by MarjieAVolk** 2018-02-13 05:18 UTC
