### ISSUE TITLE
USER ISSUE: Mining Crash

### ISSUE THREAD

**Issue by halldorr** [StrangeLoopGames/EcoIssues#5761] opened 2018-03-09 12:33 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Mining underground and picking up stone

**Expected behavior:**
Not crashed

**Actual behavior:**
Caught exception:

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>

**Comment by MarjieAVolk** [comment] 2018-03-09 20:04
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496

**Closed by MarjieAVolk** 2018-03-09 20:04 UTC
