### ISSUE TITLE
USER ISSUE: Storage input/output

### ISSUE THREAD

**Issue by JohnyBro** [StrangeLoopGames/EcoIssues#24110] opened 2023-12-03 11:21 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-275

**Steps to Reproduce:**
Open a crafting table with many storage linked
Go to the storage tab
Clic on the global input/output buttons

**Expected behavior:**
Toggle all inputs/outputs

**Actual behavior:**
Clunky

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-06 16:17
Not sure what the problem is unfortunately, closing due to too little information.

**Closed by D3nnis3n** 2023-12-06 16:17 UTC
