### ISSUE TITLE
USER ISSUE: Fast breeding

### ISSUE THREAD

**Issue by GonRock** [StrangeLoopGames/EcoIssues#5606] opened 2018-03-07 18:14 UTC
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
You plant any tree or plant.
Then you log out and Back in , everything is fully grown
I play in one Player server

**Expected behavior:**
It should not grow that fast

**Actual behavior:**
It is to fast

**Comment by Thyriel** [comment] 2018-03-07 20:44
I can confirm that and it seems to happen with almost all plants.
MaturityAgeDays is correct in ecosim.eco and the soilsampler shows correct growing time but when you relog near plants / trees that are just a couple minutes old you see them as if they are mature and can harvest them as if they where. Oir farmer got a couple hundred beans from a small 7x7 field after 5mins of growing while the soil sampler still showed 19hours to grow

**Comment by MarjieAVolk** [comment] 2018-03-08 19:51
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4003

**Closed by MarjieAVolk** 2018-03-08 19:51 UTC
