### ISSUE TITLE
USER ISSUE: separator cannot be entered

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9827] opened 2018-10-22 03:23 UTC
**Version:** 0.7.8.0 beta master-b293b18a debug
Store interface allow me use only dot (.) but dot disappears.
Correct separator is comma (,) but comma cannot be entered...
![r](https://user-images.githubusercontent.com/4980243/47275001-25cfb900-d5b4-11e8-8aee-daf5f2761949.gif)

Only ctrl+click allow set a fractional number...
![r](https://user-images.githubusercontent.com/4980243/47276834-dfce2180-d5c2-11e8-8cc6-d2b510113663.gif)

**Comment by D3nnis3n** [comment] 2018-10-22 11:00
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9210, https://github.com/StrangeLoopGames/EcoIssues/issues/9374, https://github.com/StrangeLoopGames/EcoIssues/issues/9811, https://github.com/StrangeLoopGames/EcoIssues/issues/9251

**Comment by D3nnis3n** [comment] 2018-10-22 11:01
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9210, https://github.com/StrangeLoopGames/EcoIssues/issues/9374, https://github.com/StrangeLoopGames/EcoIssues/issues/9811, https://github.com/StrangeLoopGames/EcoIssues/issues/9251

**Closed by D3nnis3n** 2018-10-22 11:00 UTC
