### ISSUE TITLE
Camera frozen after meteor sequence

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22193] opened 2021-06-11 18:57 UTC
overfix this please, it keeps breaking

**Comment by TwixterZ** [comment] 2021-07-06 10:04
Issue tested on 0.9.4 Staging-2045 and unable to reproduce . 

Closing this issue for now, to open issue with video or steps to reproduce when happens again

**Closed by TwixterZ** 2021-07-06 10:04 UTC
Labels: Regression, Status: Investigate
