### ISSUE TITLE
[SERVER ISSUE] Something here made the CPU usage go to 100% and stay there, major ping issues

### ISSUE THREAD

**Issue by Ekkelus** [StrangeLoopGames/EcoIssues#5578] opened 2018-03-07 13:02 UTC
Server machine:
Intel Xeon CPU E3-1265L V2 @2.50Ghz
16 GB Ram
Dedicated

World size: 2,07km²
Dimension: 144 x 144

Using 7.2.1 and after 1 hour of being up players started to report me of major ping issues and this is what I could gather from the dumps. Also this was a possible memory leak, the CPU usage stayed at 100% even after the players had left. I had problems even turning the server off due to this.

```
--BEGIN DUMP--
Dump Time
03/07/2018 11:18:41

Exception
System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--
```

```
--BEGIN DUMP--
Dump Time
03/07/2018 11:28:47

Exception
System.Exception: Caught exception invoking RPC SetTag on ChatManager!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Systems.Chat.ChatManager.SetTag(ChatTagSetting chatTagSetting, Int32 playerID)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

```

```
--BEGIN DUMP--
Dump Time
03/07/2018 12:19:12

Exception
System.InvalidOperationException: Invalid Query - Query never existed or was already processed
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--
```

**Comment by Thyriel** [comment] 2018-03-07 14:49
We suffer from the same issue after 1-2 hours. CPU usage going unusally high and ping for everyone increasing to unplayable amounts.

**Comment by Thyriel** [comment] 2018-03-07 15:58
Deactivating serverstatistics in stats.eco seems to have made it a lot better now for us

**Comment by Ekkelus** [comment] 2018-03-07 17:16
> Deactivating serverstatistics in stats.eco seems to have made it a lot better now for us

We tried that but it was still leaking. Now we're using a memory cleaner and that makes it a bit better.

**Comment by Thyriel** [comment] 2018-03-07 19:50
With "a lot better" i did not ment that it would be somewhere close to 7.1 perfomance but at least we're not getting 5000+ pings now. Still needs a restart every now because it suddenly stops letting people connect (timeout - while those still online play fine) and crashed 2 times so far in only a couple hours.
But maybe it just helped us with the CPU issue because our world is quite small (1km2)

**Comment by fisele** [comment] 2018-03-07 20:16
We've got the same issue. 
Turned down Backup (4h) and HDD Storing (1h) - yes 1h is a load of work if the server crashes but it seemde like one of both jobs made the cpu go crazy. 
I also changed the backup compressing to zero.

Maybe the backup thread/process has a to high prio?

i7 4770 32gb ram win10 datacenter 
map 4km² 200x200 convertet from 7.1.2

**Comment by fisele** [comment] 2018-03-07 20:18
We also have had multiple instances of the same player on the server. Sometimes 5 instances of one player.  Probably coming with the desync/CPU problem

**Comment by MarjieAVolk** [comment] 2018-03-07 20:30
The first stack trace given is the same as https://github.com/StrangeLoopGames/EcoIssues/issues/5328

**Comment by MarjieAVolk** [comment] 2018-03-08 22:07
We are working on fixes for these performance problems.  I believe some are fixed in 7.2.2, and some are soon to be fixed.  As mentioned, they seem to be related to hunting.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5640

**Closed by MarjieAVolk** 2018-03-08 22:07 UTC
Labels: High Priority

**Comment by Thyriel** [comment] 2018-03-12 00:17
> Deactivating serverstatistics in stats.eco seems to have made it a lot better now for us

Just for info: Yesterday we activated statistics again and with the latest version (dead animal hotfix) it's now even with statistics working without any lag ;)

**Comment by MarjieAVolk** [comment] 2018-03-13 00:31
Yaaaaaaaaay
