### ISSUE TITLE
[CLIENT/SERVER] Unicode Characters not Supported by Web Server

### ISSUE THREAD

**Issue by OfficialNoms** [StrangeLoopGames/EcoIssues#4534] opened 2018-02-14 19:30 UTC
Unicode characters (such as the 💢 symbol) are not being supported correctly by the web server or game, and create mismatch problems when communicating between Client and Web Server.

A specific example of this issue is the fact that I am unable to vote in any election, as it outputs "Voter does not match username"  

Should be an easy fix, just enforce no unicode characters or simply clean usernames yourself on the client and server.

Attached is a screenshot of the specific example I outlined.

![image](https://user-images.githubusercontent.com/7538787/36223644-f7769440-11bc-11e8-8481-ee5d84339954.png)

**Comment by MarjieAVolk** [comment] 2018-02-14 20:07
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4160

Had some other reports of issues with this, we will prioritize fixing this.

**Closed by MarjieAVolk** 2018-02-14 20:07 UTC
