### ISSUE TITLE
USER ISSUE: Models Not Updating After Sleep or /FF

### ISSUE THREAD

**Issue by amilious-ba** [StrangeLoopGames/EcoIssues#21159] opened 2021-03-30 07:35 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Plant crops (this happens in single player)
2. Sleep or use /ff
3. Look at planted crops

**Expected behavior:**
Plants grow and show new models based on the growth. (Bigger models)

**Actual behavior:**
The old sized models are still rendered.  When mousing over the crop the outline will be the correct larger size, but the visible model will still be the smaller size.  This bug also occurs for the self-planted crops.  Of course, if you log out and back in the models are redrawn and the correct size.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![image](https://user-images.githubusercontent.com/13543810/112951082-914ae700-916d-11eb-8534-37e80f0bd04b.png)

**Comment by amilious-ba** [comment] 2021-03-30 07:38
I think this is because you are probably updating the models at the "normal" growth time and this is not executed when speeding up the time by sleeping or ff.

**Comment by TwixterZ** [comment] 2021-03-30 11:43
@amilious-ba thank you for reporting this issue, 

I can confirm this issue.

Tested on tomato and beets:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/7b93ce29-d3ac-4f4c-b698-68be56bfd03b)
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/46240118-0451-4813-b3b4-a7b50d6d337b)

**Comment by IcedForge** [comment] 2021-03-30 12:06
Closing as duplicate of #9057

**Closed by IcedForge** 2021-03-30 12:06 UTC
Labels: Category: Tech, Type: Bug
