### ISSUE TITLE
USER ISSUE: can not give player SP

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4093] opened 2018-02-08 03:48 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
type /giveskillpoints DKNK,1 in chat

attempted with sglID but that didnt work either

**Expected behavior:**
he receives SP

**Actual behavior:**
says "can not find player"

**Comment by ecoemmeck** [comment] 2018-02-08 17:36
This is odd it works fine when I did it this evening.
Is it perhaps something to do with steam players?

**Comment by stormoffires** [comment] 2018-02-08 18:24
Player joined the server with special characters in his name on steam (steam only player)

Tried changing his name and rejoining the server but it still would not work

**Comment by Nanders** [comment] 2018-02-08 18:30
Right now there are a few issues with special characters that need to be fixed. In this case the issue is compounded by the fact that the player's username is assigned as whatever their persona name is when they logged in, and they can't change it.

**Comment by D3nnis3n** [comment] 2019-11-13 15:30
Fixed by userids.

**Closed by D3nnis3n** 2019-11-13 15:30 UTC
Labels: Medium Priority
