### ISSUE TITLE
USER ISSUE: Opening and closing chat window makes the slide bar go back to older text

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8704] opened 2018-07-23 21:02 UTC
**Version:** 0.7.6.2 beta

**Steps to Reproduce:**
have a lot of text in window
slide the slider to the bottom of the window so the latest chat is there, Close Window (C) then open it again (C) the slider then goes back halfway up the window

**Expected behavior:**
the Slider should not move on its own when opening and closing chat window

**Actual behavior:**
as far as i can see what is happeing the Slider bar is quickly showing a FULL bar then deciding to take the exact centre of of the window
![snap2326](https://user-images.githubusercontent.com/29383891/43102504-3f8c4cc4-8ec3-11e8-90e6-14e9556a8c44.png)
![snap2327](https://user-images.githubusercontent.com/29383891/43102505-3fa7d0de-8ec3-11e8-927c-a718839bf5e3.png)

the following picture trys to explain this graphically
![snap2329 edited](https://user-images.githubusercontent.com/29383891/43102816-12a1d1e2-8ec4-11e8-9c1e-a72dd1d9d24a.png)

**Comment by TheeJudge** [comment] 2018-09-09 05:49
I would like to add to this that not only closing and opening it. It happens when a lot of actions are taken as well. I experience this problem the most when I do a lot of work that spams the chat like picking plants or cutting down a tree and picking up the logs. This is still affecting the chat in 7.7.1. It makes it near imposable to play the game and talk to people in chat. This combined with being World Leader and an Admin makes playing the game when I need to chat with people impossible. The more I do things while trying to talk the more the chat jumps around and won't stay scrolled down to the bottom.

**Comment by Conchipedia** [comment] 2018-09-09 10:53
we have had to use a Discord Bot that reads Chat so we don't miss anything

**Comment by Spydarlee** [comment] 2019-03-14 15:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8248?

**Closed** 2019-03-19 18:49 UTC
Labels: Fixed, Pending High Priority
