### ISSUE TITLE
Connecting stove

### ISSUE THREAD

**Issue by Bosken** [StrangeLoopGames/EcoIssues#6331] opened 2018-03-21 04:09 UTC
![foratta namn](https://user-images.githubusercontent.com/37607596/37694250-ea0db4a4-2cc5-11e8-99af-d27495bcc705.png)
got some issues connecting my stove, says connecting point is in the blue square.

**Comment by MarjieAVolk** [comment] 2018-03-21 18:30
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5805

Will be fixed in 7.3.  The actual pipe port is in the wrong place on the Stove.  I believe it is far off to the upper left.

**Closed by MarjieAVolk** 2018-03-21 18:30 UTC
