### ISSUE TITLE
Ramp placement making Yogscast curse our name

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12213] opened 2019-05-07 22:01 UTC
https://www.youtube.com/watch?v=pDn_u7EgPxk&feature=youtu.be&t=3169

**Comment by johnkslg** [comment] 2019-05-07 22:02
Tagged 8.2 but thats probably optimistic...

**Comment by D3nnis3n** [comment] 2019-05-07 22:10
You just need to prevent ramps being able to be placed partially.

**Comment by johnkslg** [comment] 2019-05-07 22:14
That sounds quite easy!

**Comment by metachronism** [comment] 2019-05-07 22:20
dupe of #10554

**Comment by D3nnis3n** [comment] 2019-05-07 22:30
Copied issue state to the other issue, closing this for dup as mentioned by meta.

**Closed by D3nnis3n** 2019-05-07 22:30 UTC
Labels: High Priority
