### ISSUE TITLE
USER ISSUE: grass to dirt due region player activity 

### ISSUE THREAD

**Issue by KosmoLp** [StrangeLoopGames/EcoIssues#6925] opened 2018-04-03 15:46 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. dig until u are surrounded by stone 
2. do something like digging stone or building (in the underground)
3. look at the top over your stone room 

**Expected behavior:**
there should be grass, because i didn't ran over the grass so there should be all fine 

**Actual behavior:**
there is dirt instead of grass, because i think the chunk player activity thinks that i do something on top so the grass is replaced by dirt, even if i wasn't on the grass one time.

**Comment by KosmoLp** [comment] 2018-04-03 16:15
Idea: there should be a testing parameter who is looking forward if i'm going on any type on road or stone/ore it should not be counted as chunk activity...

**Comment by MarjieAVolk** [comment] 2018-04-03 17:59
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5101

**Closed by MarjieAVolk** 2018-04-03 17:59 UTC
