### ISSUE TITLE
USER ISSUE: Black screen on any server

### ISSUE THREAD

**Issue by D3vil787** [StrangeLoopGames/EcoIssues#23526] opened 2022-11-08 04:26 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.6.4 beta release-354

**Steps to Reproduce:**
just connect to any server where i allready playing before update to 9.6.4

**Expected behavior:**
gameplay interface	

**Actual behavior:**
blackscreen only

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by RemonRamy** [comment] 2022-11-08 15:49
Hello @D3vil787,

Are you on Windows as your operating system?

If so, can you try the following steps:

1. Press `Win+R` on your keyboard and type in `regedit`.
![image](https://user-images.githubusercontent.com/15372525/200610797-5cfa9465-4c94-447e-ba96-400f480c7710.png)
3. Navigate all the way to `HKEY_CURRENT_USER\SOFTWARE\Strange Loop Games\Eco`.
![image](https://user-images.githubusercontent.com/15372525/200611059-f4c83713-4132-44ac-859a-41441aee6a18.png)
5. Right click on the `Eco` folder and click `Export`,
![image](https://user-images.githubusercontent.com/15372525/200610738-bb873f6a-5ed9-45ee-9a2e-f5e97704a296.png)
6. It will prompt you to save a registry file, can you send us that file back? I'll help us resolve the issue.
![image](https://user-images.githubusercontent.com/15372525/200611330-1591aa89-4bdd-4353-bf9a-a3cb30d4f211.png)
8. Right click on the same `Eco` folder again and click `Delete`.
![image](https://user-images.githubusercontent.com/15372525/200610770-bcaf680a-a6ec-4260-859c-2b26da6a3f9b.png)
9. Try to play Eco again and check if the problem is fixed.

Cheers,
Remon

**Comment by D3vil787** [comment] 2022-11-09 14:05
Thanks! Your solution resolve my problem. I exported HKEY_CURRENT_USER\SOFTWARE\Strange Loop Games\Eco registry before delete, in attach.
[ecoregistrydata.zip](https://github.com/StrangeLoopGames/EcoIssues/files/9971763/ecoregistrydata.zip)

**Comment by RemonRamy** [comment] 2022-11-09 14:11
Hello again @D3vil787,

Glad it's resolved! Thank you, the data you shared will help us get this resolved for good.

Closing as resolved, internal reference: ECO-25271.

Kind Regards,
Remon

**Closed by RemonRamy** 2022-11-09 14:11 UTC
