### ISSUE TITLE
USER ISSUE: Kicked out of game

### ISSUE THREAD

**Issue by Baldwolf63** [StrangeLoopGames/EcoIssues#3852] opened 2018-02-04 02:28 UTC
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
Broke a mortared stone roof piece moved away and had error message	

**Expected behavior:**
I was bumped out of the game. It was unexpected. :)	

**Actual behavior:**
Caught exception: Nullable object must have a value.

**Comment by Baldwolf63** [comment] 2018-02-04 02:29
This was an updated to an established world. There could simply be a conflict between old world and new version.

**Comment by metachronism** [comment] 2018-02-04 03:27
if you have the old save, can you link it here for download?

**Comment by Baldwolf63** [comment] 2018-02-04 17:06
The server became so buggy that the admin put it up to a vote to restart
and we did. We now have a fresh start.

**Comment by MarjieAVolk** [comment] 2018-02-05 02:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3891

**Closed by MarjieAVolk** 2018-02-05 02:53 UTC
