### ISSUE TITLE
USER ISSUE: items disapeared when transfering

### ISSUE THREAD

**Issue by ybronhaiasi** [StrangeLoopGames/EcoIssues#25176] opened 2024-09-23 17:30 UTC
\
**User Id: (427ac19d-c618-44fd-b853-08dcd72ba347)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
I had a canoe in the water, and a small stockpile just off shore. i had 20logs and 10hewn logs in the canoe and 20logs on my person. and when i accessed the canoe storage from the stockpile, and dragged the 20 logs on my person to trade with the 10hewn logs in the canoe, it put the 20logs into the canoe but the hewn logs disapeared

**Expected behavior:**
hewn logs should have apeared on my person

**Actual behavior:**
hewn logs are no where to be found

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, playing on official server Dusky Robin #6

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ybronhaiasi** [comment] 2024-09-23 17:31
![20240923102429_1](https://github.com/user-attachments/assets/84df0f88-13b1-4a4d-9ff6-88a82a630e70)
![20240923102409_1](https://github.com/user-attachments/assets/9066c631-6097-477f-ad7f-32cccca04dcb)

**Comment by D3nnis3n** [comment] 2024-09-24 15:22
Not reproducible, can you recreate the problem somehow?

**Comment by ybronhaiasi** [comment] 2024-09-26 02:25
I haven’t been able to re create it, sorry. I’ve tried a few times..

**Comment by D3nnis3n** [comment] 2024-09-26 10:07
Closing due to not being reproducible then, there is no hints we could use to investigate, given no logfiles were provided either.

**Closed by D3nnis3n** 2024-09-26 10:07 UTC
Labels: Status: Not reproduced
