### ISSUE TITLE
Mining and logging lags whole server

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2867] opened 2017-11-20 19:30 UTC
![image](https://user-images.githubusercontent.com/3536496/33037355-1c9c1b16-cde6-11e7-96ea-9923f49c7c09.png)

[9:42 AM] ClayC: when for example I hit a block, it gets deleted quickly
[9:42 AM] ClayC: but to spawn the rubble it takes a while sometimes(edited)
[9:42 AM] ClayC: when this happens, I am able to select other blocks and "mine" them but they will remain for a while
[9:42 AM] ClayC: then after a while, it will just mine a few, all or just one, sometimes even none
[9:43 AM] ClayC: we were a total of 8 players online at that time
[9:43 AM] ClayC: I received lagg, and others complained of lagg aswell
[9:43 AM] ClayC: we live ingame a few plots away, by a few I mean atleast 30 plots away

**Comment by MarjieAVolk** [comment] 2017-11-20 19:33
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2731

**Closed by MarjieAVolk** 2017-11-20 19:33 UTC
Labels: Critical Priority
