### ISSUE TITLE
World marker direction indicators do not track smoothly around screen

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3878] opened 2018-02-04 08:41 UTC
They track smooth around the top and bottom of screen, but snap to the left and the right.

**Comment by MarjieAVolk** [comment] 2018-02-05 02:59
Sounds like duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3301?

**Closed by MarjieAVolk** 2018-02-05 02:59 UTC
Labels: Low Priority
