### ISSUE TITLE
USER ISSUE: No server

### ISSUE THREAD

**Issue by ktex** [StrangeLoopGames/EcoIssues#4879] opened 2018-02-20 20:41 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Hello, 

I don't know how it's happen, but I was playing and suddently y game crash, my computer also.
When I reboot Eco see no serveur onlin (and no free server on the bottom)
I downgraded and upgraded Eco
I had reboot
I had uninstall Eco and install again
I had close and reboot Steam
I had change my internet connexion	
and still no server online or can't search one....

thanks

**Expected behavior:**
idk

**Actual behavior:**

**Comment by ktex** [comment] 2018-02-20 20:45
I also was in the parameter of the application in the task gestionnary and I make an analysis of the chain and they told me that "Eco is waiting for an network operation"

**Comment by MarjieAVolk** [comment] 2018-02-23 02:18
This sounds very strange.  One thing that has helped others who see no servers online is to delete the folder C:\Users[username]\AppData\LocalLow\Strange Loop

**Comment by MarjieAVolk** [comment] 2018-02-26 18:08
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4995

**Closed by MarjieAVolk** 2018-02-26 18:08 UTC
