### ISSUE TITLE
USER ISSUE: Solar power works in a cave

### ISSUE THREAD

**Issue by neuromantiker** [StrangeLoopGames/EcoIssues#6408] opened 2018-03-23 14:44 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Build a cave
2. Put the solar power station inside, it'll work.

**Expected behavior:**
Solar Power needs to be on surface

**Actual behavior:**

**Comment by ecoemmeck** [comment] 2018-03-23 18:03
This is a good point which I think has a bug report. ( but as I'm on my phone will be a pain to find)
This should only work at day time and not under ground. And also be dependant of weather conditions e.g. cloudy or storms should have an impact on solar generators and perhaps wind turbines once such things as weather conditions are inputted into the game

**Comment by MarjieAVolk** [comment] 2018-03-23 18:14
Yep duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4433

**Closed by MarjieAVolk** 2018-03-23 18:14 UTC
