### ISSUE TITLE
[0.8.3.1] Server bundled with Linux client is the 0.8.3.0 server

### ISSUE THREAD

**Issue by jthill** [StrangeLoopGames/EcoIssues#14178] opened 2019-12-18 18:54 UTC
ssia, installing the server download itself is 0.8.3.1 so there's an easy workaround

**Comment by D3nnis3n** [comment] 2019-12-18 19:33
Assigned to mirasrael for a re-release.

**Comment by mirasrael** [comment] 2019-12-19 06:52
Actually server shouldn't be bundled with Eco Client on Linux, because it isn't officially supported :)

**Comment by mirasrael** [comment] 2019-12-19 08:51
Just checked it has correct server version for both Steam and Web Site Linux distribution:
![image](https://user-images.githubusercontent.com/475445/71158775-92e0ec00-2255-11ea-850c-625510e78b8a.png)

If you installed game with Steam you can try verify files.

**Closed by mirasrael** 2019-12-19 08:51 UTC
Labels: Investigate

**Comment by jthill** [comment] 2019-12-19 15:11
Not Steam, website. unzip the archive, then 

```
[jthill@gadabout Eco]$ find -name \*.exe -o -name \*.x86_64 -exec chmod +x {} +
[jthill@gadabout Eco]$ ls
Eco.x86_64  Eco_Data
[jthill@gadabout Eco]$ cd Eco_Data/Server
/home/jthill/libexec/Eco/Eco_Data/Server
[jthill@gadabout Server]$ ls
Configs        EcoServer.exe.config  EcoServer32.sh  doc
DefaultWorld   EcoServer.sh          Mods            install.sh
EcoServer.exe  EcoServer32.exe       WebClient
[jthill@gadabout Server]$ mono EcoServer.exe
[07:06:30] Eco Server 0.8.3.0 beta
[07:06:30] Server Initialization... 
[07:06:30] Starting LocalizationPlugin... 
[07:06:30] Starting ModKitPlugin...       Finished in 280.2ms
[07:06:30] Loading mods... 
[07:06:30] Compiling mods... 
```

I just retried it.

**Comment by mirasrael** [comment] 2019-12-20 09:08
If you try `mono ./EcoServer.exe` or `./EcoServer.sh`?

**Comment by jthill** [comment] 2019-12-20 13:37
Still the same, just tried it.  Does WSL not have a mono install? I thought WSL was Ubuntu, it might run like crap but it should still just be a slower version of the same thing.

But really, with a workaround as easy as this one, I'm guessing I'm one of what, half a dozen people? trying to run the server locally.  If you want to wont-fix this because it's so easy to work around I'm happy enough.

**Comment by mirasrael** [comment] 2019-12-20 16:32
Problem not about I don't want to fix it, problem I can't reproduce it with both Steam and site version. So I have no idea how you can get such result. I may only assume Mono makes some magic and uses some cached version of executable.

**Comment by mirasrael** [comment] 2019-12-20 16:42
You can try move Server to another dir an check if anything changed.

**Comment by jthill** [comment] 2019-12-20 16:56
. . . hunh.  Right.  There's some weird caching going on somewhere, or I screwed up twice the same way copying from my unpacked download to my libexec (but but it was a single bulk copy and the client shows 8.3.1?).  Whatever this is, it's my fault. Sorry for the noise.
