### ISSUE TITLE
USER ISSUE: New World - connection error

### ISSUE THREAD

**Issue by leftwrist** [StrangeLoopGames/EcoIssues#14533] opened 2020-01-28 19:06 UTC
[ECO error log 20200128.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4124117/ECO.error.log.20200128.txt)
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
just wanted to create a world - as usual

**Expected behavior:**
playing in a new world - just normal

**Actual behavior:**
the game couldn't connect. i get this msg every time, no matter what i do. pretty annoying

**Do you have mods installed? Does issue happen when no mods are installed?:**
the game couldn't connect. i get this msg every time, no matter what i do. pretty annoying

**Comment by leftwrist** [comment] 2020-01-28 19:07
[leftwrist ECO error log 20200128.docx](https://github.com/StrangeLoopGames/EcoIssues/files/4124132/leftwrist.ECO.error.log.20200128.docx)

**Comment by D3nnis3n** [comment] 2020-01-28 19:29
Please attach the server logs: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by leftwrist** [comment] 2020-01-28 21:37
Problem fixed by deleting the sub-folder "Server" in the game's folder and then doing "Verify Integrity of Game Files" in the properties of Eco in Steam.

**Comment by D3nnis3n** [comment] 2020-01-28 21:38
Well, we're now unable to find the cause of the issue. Probably you would only have needed to restore a backup. :(

Closing the issue, as it's fixed and nothing else we could do any more.

**Closed by D3nnis3n** 2020-01-28 21:38 UTC

**Comment by leftwrist** [comment] 2020-02-02 08:33
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143712/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143713/Player.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4143714/Player.log.copy.txt)


[log_200128072950.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143700/log_200128072950.log)
[log_200128073604.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143701/log_200128073604.log)
[log_200128073652.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143702/log_200128073652.log)
[log_200128074156.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143703/log_200128074156.log)
[log_200128074334.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143704/log_200128074334.log)
[log_200128075125.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143705/log_200128075125.log)
[log_200128080251.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143706/log_200128080251.log)
[log_200128080524.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143707/log_200128080524.log)
[log_200128081723.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143708/log_200128081723.log)
[log_200128072412.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143709/log_200128072412.log)
[log_200128072459.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143710/log_200128072459.log)
[log_200128072845.log](https://github.com/StrangeLoopGames/EcoIssues/files/4143711/log_200128072845.log)

**Comment by D3nnis3n** [comment] 2020-02-02 16:25
Those are the wrong logs, we'd need the server logs that are found in the Server/Logs folder.

**Comment by D3nnis3n** [comment] 2020-02-02 16:27
In your case some mod files got corrupted. This can either happen due to faulty use of mods or a broken steam update. Deleting the mods folder an verifying integrity on Steam would fix this issue. It's not a bug, though. Thanks for the logs!
