### ISSUE TITLE
USER ISSUE: Main Menu doesn't load if Steam is down

### ISSUE THREAD

**Issue by szalkerous** [StrangeLoopGames/EcoIssues#20185] opened 2021-01-27 00:55 UTC
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Steam servers must be down (intentional or incidental)Load the game

**Expected behavior:**
Shown the Main Menu, even if there was a timeout.

**Actual behavior:**
Shows only the Main Menu scene and game logo, no UI elements.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by szalkerous** [comment] 2021-01-27 00:58
`Initialize engine version: 2019.4.15f1 (fbf367ac14e9)
[Subsystems] Discovering subsystems at path D:/Steam/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA TITAN X (Pascal) (ID=0x1b00)
    Vendor:   
    VRAM:     12147 MB
    Driver:   27.21.14.5671
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.372600 ms
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. 
(Filename:  Line: 589)

WwiseUnity: Wwise(R) SDK Version 2019.2.5 Build 7349.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Setting Plugin DLL path to: D:/Steam/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'Camera') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object 'Table') is missing! 
(Filename:  Line: 334)

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
SteamManager:Awake()

[ line 589] 
(Filename:  Line: 589)

Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.UIManager:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead 
(Filename:  Line: 308)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead 
(Filename:  Line: 308)

[07:48:34.429] OnEncryptedAppTicketResponse: Not connected to Steam
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
SteamAuthHandler:OnEncryptedAppTicketResponse(EncryptedAppTicketResponse_t, Boolean)
Steamworks.APIDispatchDelegate:Invoke(T, Boolean)
Steamworks.CallResult`1:OnRunCallResult(IntPtr, Boolean, UInt64)
Steamworks.CallbackDispatcher:RunFrame(Boolean)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
`

**Comment by D3nnis3n** [comment] 2021-01-27 00:59
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues?q=is%3Aissue+is%3Aopen+steam

**Closed by D3nnis3n** 2021-01-27 00:59 UTC
