### ISSUE TITLE
USER ISSUE: Door building timer

### ISSUE THREAD

**Issue by panterzz** [StrangeLoopGames/EcoIssues#6090] opened 2018-03-15 16:23 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1. Build door after training woodworking speed to higher level
2. Reduced speed occurs to all items, except the doors	

**Expected behavior:**
Reduced building time	

**Actual behavior:**
Still has 5 minutes of building time with max woodworking speed skill

**Comment by MarjieAVolk** [comment] 2018-03-16 00:08
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5835

**Closed by MarjieAVolk** 2018-03-16 00:08 UTC
