### ISSUE TITLE
rubble dropping from the sky, sometimes just sits there ##cc778b68

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2099] opened 2017-09-13 19:14 UTC
When loading in game it is taking longer and longer (possibly still due to loading in uncollected rubble and debris?), and we can seerubble dropping from the sky, but as you can see by last snap shot it sometimes still is hanging there

![snap043](https://user-images.githubusercontent.com/29383891/30395944-d2e49b52-98bf-11e7-8658-22e88c5cfa92.png)
![snap044](https://user-images.githubusercontent.com/29383891/30395957-dfb3faee-98bf-11e7-8d35-49dac3de2e34.png)
![snap045](https://user-images.githubusercontent.com/29383891/30395965-e8ed6b0e-98bf-11e7-8888-ff079e0040fd.png)
![snap046](https://user-images.githubusercontent.com/29383891/30395981-f2410468-98bf-11e7-8589-eaba760cc411.png)

**Comment by Conchipedia** [comment] 2017-09-13 19:52
but i do LOVE the new rubble

**Comment by MarjieAVolk** [comment] 2017-09-13 19:54
Do you love it in the air?  Do you love it everywhere?  :P

**Comment by Conchipedia** [comment] 2017-09-14 18:39
i do like being surprised it even ended up inside my building so it cannot have come from the sky so might have popped up from below, or the little Eco Pixies left it for me to trip over :)

**Comment by metachronism** [comment] 2017-09-19 20:26
punting this to beta, this is a sync physics issue, and while annoying, isn't too game-breaking

**Comment by MarjieAVolk** [comment] 2018-01-12 20:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2334

**Closed by MarjieAVolk** 2018-01-12 20:05 UTC
Labels: Medium Priority
