### ISSUE TITLE
[11.0.2] Currency Exchange Disabling After Server Restarts

### ISSUE THREAD

**Issue by Pugpeople** [StrangeLoopGames/EcoIssues#25115] opened 2024-08-28 20:46 UTC
As far as ive seen, there hasn't been any reports of this kind, so i figured id point it out. The steps this usually occurs on is when the currency exchange is on a government owned deed, active and functioning whilist after the server - Any server , it seems to break down.
![afbeelding_2024-08-28_224158537](https://github.com/user-attachments/assets/36a6a266-3f24-4863-b372-b3b865c75482)
The picture linked gives a notification, which triggers immideatly after set server resets, saying 'you do not have acess to the bank account' While its directly owned by government and/or player. the same keeps presisting, The issue effectively renders currency exchange useless on any server that restarts on frequent/timed moments. Ive not been able to test this on singleplayer- due to the lack of knowledge on forming an government witouth any players. I hope this issue can be resolved.

slgid: Pug_people

**Comment by D3nnis3n** [comment] 2024-08-29 07:39
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25098

**Closed by D3nnis3n** 2024-08-29 07:39 UTC
