### ISSUE TITLE
USER ISSUE: Kick out of game

### ISSUE THREAD

**Issue by GazToxic** [StrangeLoopGames/EcoIssues#11437] opened 2019-02-21 00:22 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
I was hunting and i have been kick out without any notice or message

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection timed out
```

**Comment by elfl0rd** [comment] 2019-02-21 06:46
Singleplayer?

**Comment by GazToxic** [comment] 2019-02-21 10:54
Multiplayer

De mon cell

________________________________

**Comment by GazToxic** [comment] 2019-02-21 12:45
I was playing multiplayer, my ping is under 50 (running around 30-45) and I have a lot of disconnect icon appearing in side corner.

________________________________
De : GDragon <notifications@github.com>
Envoyé : 21 février 2019 01:46
À : StrangeLoopGames/EcoIssues
Cc : GazToxic; Author
Objet : Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Kick out of game (#11437)


Singleplayer?

**Comment by D3nnis3n** [comment] 2019-03-03 22:05
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11068

**Closed by D3nnis3n** 2019-03-03 22:05 UTC
