### ISSUE TITLE
USER ISSUE: Crash on picking up old logs

### ISSUE THREAD

**Issue by kshood** [StrangeLoopGames/EcoIssues#5256] opened 2018-03-01 01:50 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Just dropped off hewn wood in a stockpile.
2. Went to pick up logs that had been sitting around ungathered for over a day.

**Expected behavior:**
Let me pick up the logs and not crash.

**Actual behavior:**
The following error message popped up:
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-03-01 02:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-03-01 02:05 UTC
