### ISSUE TITLE
Player cannot see his nutrition circle nor skill - did not skip tutorial, but tutorial does not show so he can't do it

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9020] opened 2018-08-21 07:09 UTC
See the screenshot, the guy is blocked from progress and i have no idea how to fix that.
![20180821085314_1](https://user-images.githubusercontent.com/25908592/44386155-f3f19600-a521-11e8-933c-beb08be453f0.jpg)

**Comment by thereporter42** [comment] 2018-08-21 09:42
Try this Hit the escape key.. ESC then at the bottom part of the screen it says "Restart Tutorial" press that
reset the tutorial then you should see the tutorial again in the top right hand corner of the screen.

Click on the X in the right corner of the tutorial box which should be in the top left corner of your screen by default. it brings up the option "Skip Task" then under it it says (Skip all tutorial)" check that box and then click YES

That should skip the tutorial completely for you.  Give that a try hope it works..

**Comment by D3nnis3n** [comment] 2018-08-21 09:59
That worked for my player. But the tutorial should not just disappear, nevertheless.

Von: thereporter42
Gesendet: Dienstag, 21. August 2018 11:42
An: StrangeLoopGames/EcoIssues
Cc: D3nnis3n; Author
Betreff: Re: [StrangeLoopGames/EcoIssues] Player cannot see his nutritioncircle nor skill - did not skip tutorial, but tutorial does not show so hecan't do it (#9020)

Try this Hit the escape key.. ESC then at the bottom part of the screen it says "Restart Tutorial" press that
reset the tutorial then you should see the tutorial again in the top right hand corner of the screen.
Click on the X in the right corner of the tutorial box which should be in the top left corner of your screen by default. it brings up the option "Skip Task" then under it it says (Skip all tutorial)" check that box and then click YES
That should skip the tutorial completely for you. Give that a try hope it works..

**Comment by elfl0rd** [comment] 2018-08-21 13:48
Version?

**Comment by D3nnis3n** [comment] 2018-08-21 14:42
7.6.3

GDragon <notifications@github.com> schrieb am Di., 21. Aug. 2018, 15:48:

**Comment by elfl0rd** [comment] 2018-08-21 14:53
@johnkslg hm, looks refer https://github.com/StrangeLoopGames/EcoIssues/issues/8458 ...

@D3nnis3n can you repro it?

**Comment by mirasrael** [comment] 2018-08-21 17:25
Can you say name of this player? I'll try to reproduce this on your save

**Comment by D3nnis3n** [comment] 2018-08-21 17:27
Yes, ciRca was his name.

**Comment by mirasrael** [comment] 2018-08-23 05:15
![image](https://user-images.githubusercontent.com/475445/44505937-bec57f00-a6ac-11e8-985e-aa727e40b1ec.png)
was able to reproduce on staging

**Comment by mirasrael** [comment] 2018-08-23 06:26
Was able to fix this
![image](https://user-images.githubusercontent.com/475445/44508343-9773af80-a6b6-11e8-8463-f082334fdf95.png)

**Comment by mirasrael** [comment] 2018-08-23 06:45
With this fix if for some reason tutorial broken it will show UI elements after relog.

**Comment by mirasrael** [comment] 2018-08-23 06:47
It doesn't fixes reason of this problem (because we don't know how to reproduce this and if it exists anymore in latest build), but at least it will not stop you from progress if it happens

**Comment by D3nnis3n** [comment] 2018-08-23 06:51
Great, my players an me thank you.

**Comment by johnkslg** [comment] 2018-08-27 20:59
Merged in, thanks @mirasrael and @D3nnis3n !

**Closed by johnkslg** 2018-08-27 20:59 UTC
Labels: Fix Provided, High Priority
