### ISSUE TITLE
Stacks getting lost when dragging between stockpiles.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6983] opened 2018-04-04 22:43 UTC
"Kiwa: remembered one other major glitch that frequently occured on that first map: when moving items between different stockpiles in quick succession (not chests, only stockpiles), the game would frequently lose stacks - they'ld simply disappear. not sure whether that was fixed in newer versions, I don't think I've heard complaints about that (though most people also don't move as many things, or move them slower)
[3:41:35 PM] Kiwa: iirc, stockpiles <-> carts also was affected sometimes, but mostly stockpile<->stockpile"

https://steamcommunity.com/profiles/76561198014737314/recommended/382310/

**Comment by MarjieAVolk** [comment] 2018-04-04 22:45
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5895

I'll put this stuff over there.

**Closed by MarjieAVolk** 2018-04-04 22:45 UTC
Labels: High Priority, Steam Report
