### ISSUE TITLE
8.0.0 Wrong text on Buttons when choosing yes or no answer

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10742] opened 2019-01-18 09:50 UTC
**Version:** 0.8.0.0 beta master-0d4ca997

![snap3831](https://user-images.githubusercontent.com/29383891/51378945-32f23a80-1b06-11e9-85c9-5c167d747212.png)
when creating this Github also noticed that the buttons are also saying wrong text
![snap3832](https://user-images.githubusercontent.com/29383891/51378986-4f8e7280-1b06-11e9-8c6e-e8ddfddb07b5.png)
also gives same text when Quitting Eco
![snap3833](https://user-images.githubusercontent.com/29383891/51380358-78643700-1b09-11e9-938b-0778bd68fcb5.png)
![snap3834](https://user-images.githubusercontent.com/29383891/51380511-cbd68500-1b09-11e9-858a-b53f4573ed5e.png)

**Comment by elfl0rd** [comment] 2019-01-18 12:19
Duplicate of #10701

**Closed by elfl0rd** 2019-01-18 12:19 UTC
