### ISSUE TITLE
Farming planted beets returns no Beets or seeds

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7408] opened 2018-04-25 23:41 UTC
From Steam:

"I planted a good crop of Beets, sadly, even with fertilizer, most of them died. Some finally reached the stage to harvest, but when I pressed "e" to harvest, the whole crop came up totally empty. not one single beet nor seed. In excess of 50 plants harvested with nothing to show for it. Now my world has almost no beets in it."

**Comment by shadow7412** [comment] 2018-04-28 03:03
Sounds like that user needs one of these: https://eco.gamepedia.com/Soil_Sampler

**Comment by craig-jong** [comment] 2018-05-10 22:54
I need more information on this - it's technically possible for this to happen assuming the planted location is horrific/lacking in nutrients.

I'm closing this at "not a bug" unless we get more information.

**Closed by craig-jong** 2018-05-10 22:54 UTC
Labels: High Priority
