### ISSUE TITLE
USER ISSUE: Tooltip red on new axe when old axe is broken

### ISSUE THREAD

**Issue by InzeNL** [StrangeLoopGames/EcoIssues#5845] opened 2018-03-10 16:02 UTC
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
1. Get an axe to be broken
2. Make a new axe

**Expected behavior:**
The new axe has a blue background because it's not actually broken

**Actual behavior:**
The new axe has a red background (as if it's broken), but it's not actually broken (not in tooltip either)

**Comment by MarjieAVolk** [comment] 2018-03-12 22:42
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5834

**Closed by MarjieAVolk** 2018-03-12 22:42 UTC
