### ISSUE TITLE
USER ISSUE: Trying to use the allocate function in the Treasury

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#8384] opened 2018-07-07 22:13 UTC
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Using a established, backed currency as world leader, try to hit the allocate button.

**Expected behavior:**
Not sure, but probably not a crash.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Original type is Object. Cannot convert from Object to Guid
Source:Eco.Shared

System.Exception: Original type is Object. Cannot convert from Object to Guid
   at Eco.Shared.Serialization.BSONValue.get_GuidValue()
   at Eco.Gameplay.Economy.Currency.<>c.<.cctor>b__45_0(BSONValue v)
   at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type)
   at Eco.Shared.Networking.RPCManager.UnpackArgs(BSONObject bson, RPCMethod[] methods, Object extensionMethodObject, RPCMethod& targetMethod)</size>
```

**Comment by Deantwo** [comment] 2018-07-08 11:15
Duplicate of #8160.
Since it is closed, it should be fixed in next update, so this can likely be closed.

**Comment by BlazeGuy2** [comment] 2018-07-09 18:49
Saw the backlog, fix is in, will take a bit for it to come out.

**Closed by BlazeGuy2** 2018-07-09 18:49 UTC
Labels: Medium Priority
