### ISSUE TITLE
Disconnecting causes freezing/crash

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1440] opened 2017-05-04 21:17 UTC
Sometimes when I hit the disconnect button in the escape menu, unity freezes.  Sean says this happens more often if you hit the button quickly after opening the menu

**Comment by metachronism** [comment] 2017-05-12 19:03
can't repro

**Comment by metachronism** [comment] 2017-05-12 19:21
closing as dupe of #1170

**Closed by metachronism** 2017-05-12 19:21 UTC
