### ISSUE TITLE
USER ISSUE: impossible de charger mon monde

### ISSUE THREAD

**Issue by Unicorns56** [StrangeLoopGames/EcoIssues#23720] opened 2023-02-28 17:44 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.9 beta release-451

**Steps to Reproduce:**
je n'arrive ni à me connecter à une ancienne sauvegarde ni à créer un nouveau monde.
Mais j'arrive à me connecter à un monde que ne n'heberge pas

**Expected behavior:**
me connecté 

**Actual behavior:**
ne me connecte pas

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non aucun

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-02-28 19:42
Please provide your log files for the server: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by Unicorns56** [comment] 2023-03-02 16:24
[log_230301090552.log](https://github.com/StrangeLoopGames/EcoIssues/files/10873526/log_230301090552.log)

**Comment by D3nnis3n** [comment] 2023-03-02 19:44
There seems to be a corrupt config, you can try to remove your configs folder and let Steam redownload it via verify files. Pay attention to restore your difficulty settings if necessary. This is not a bug, though, hence closing this issue. If you need further help, please e-mail support@strangeloopgames.com :)

**Closed by D3nnis3n** 2023-03-02 19:44 UTC
Labels: Status: Needs Information
