### ISSUE TITLE
USER ISSUE that can crash server. Digged cube disappear in hands

### ISSUE THREAD

**Issue by Kastuk** [StrangeLoopGames/EcoIssues#5949] opened 2018-03-12 17:25 UTC
If you dig and in moment of shovel strike will change tool to Scythe of Soil sampler, pile of dirt/tailings/etc just disappear. 
After third-fourth one server may crash.

**Comment by GophTheGreat** [comment] 2019-05-21 04:02
Cannot reproduce, but maybe it'll be easier to reproduce on a low-performance system? Closing anyway for now.

**Closed by GophTheGreat** 2019-05-21 04:02 UTC
Labels: Medium Priority
