### ISSUE TITLE
USER ISSUE: Blank chat messages?

### ISSUE THREAD

**Issue by Quickflash** [StrangeLoopGames/EcoIssues#4540] opened 2018-02-14 22:02 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
When I send a message in chat it instead sends two lines of blank space

**Expected behavior:**
It should have sent a chat Message

**Actual behavior:**
Sends blank space

**Comment by MarjieAVolk** [comment] 2018-02-14 22:06
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4160

This is probably because your username has special characters in it.  Unfortunately you can't change your name once you have joined a server.  As a workaround, if you are playing via steam, you can change your steam nickname and then join a different server.  We will prioritize fixing this.

**Closed by MarjieAVolk** 2018-02-14 22:06 UTC
