### ISSUE TITLE
USER ISSUE: Electric Stamping Press does not have Storage

### ISSUE THREAD

**Issue by netray92** [StrangeLoopGames/EcoIssues#8694] opened 2018-07-23 18:25 UTC
**Version:** 0.7.6.2 beta

**Steps to Reproduce:**
Open up the menu. No storage. Have to collect things yourself

**Expected behavior:**
No storage tab, so it's not connected to chests etc.	

**Actual behavior:**

**Comment by craig-jong** [comment] 2018-07-24 17:32
dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/8547

**Closed by craig-jong** 2018-07-24 17:32 UTC
Labels: High Priority
