### ISSUE TITLE
Crafting didn't auto-take from a finished recipie

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1896] opened 2017-08-18 02:09 UTC
Cooked some Bison then CamasMash, bison finished and then the CamasMash was stuck waiting for lard.

It didn't start until I Unchecked/rechecked my storage chest. (was the first time i fiddled w/ the checkbox but it was clearly checked, maybe that is out of sync)

**Comment by MarjieAVolk** [comment] 2017-08-18 17:48
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1715 -- coincidentally I am fixing this in https://github.com/StrangeLoopGames/Eco/pull/1675

**Closed by MarjieAVolk** 2017-08-18 17:48 UTC
