### ISSUE TITLE
USER ISSUE: Fish doesn't appear in backpack (with fishing pole)

### ISSUE THREAD

**Issue by herzblut** [StrangeLoopGames/EcoIssues#5128] opened 2018-02-26 14:35 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Start fishing with a fishing pole. Pull fish and open inventory (backpack). The fish doesn't show up.
Tested with two different kinds of fish (tuna, trout).

**Expected behavior:**
The fish should be visible in the backpack (and also should stack up properly).

**Actual behavior:**
The fish appears after a re-login within the backpack and is usable. Even if one kind of the fish is already shown in the backpack the next one is also 'hidden' (but becomes visible after re-login too)

**Comment by MarjieAVolk** [comment] 2018-02-26 21:57
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

**Closed by MarjieAVolk** 2018-02-26 21:57 UTC
