### ISSUE TITLE
USER ISSUE: Contract Bug

### ISSUE THREAD

**Issue by Disglin** [StrangeLoopGames/EcoIssues#8402] opened 2018-07-09 06:25 UTC
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Oben Contract Board	,
Make a Custom Contract,
Crash

**Expected behavior:**
Create the Contract

**Actual behavior:**
Wrong number of args passed to method: set_Description.

**Comment by MarjieAVolk** [comment] 2018-07-09 18:34
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8244.  Should be fixed in next release.

**Closed by MarjieAVolk** 2018-07-09 18:34 UTC
Labels: Medium Priority
