### ISSUE TITLE
USER ISSUE: Failed to Connect

### ISSUE THREAD

**Issue by oldspiceland** [StrangeLoopGames/EcoIssues#4092] opened 2018-02-08 03:33 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Try and Connect to a Friend via Steam

**Expected behavior:**
Connected? IDK. Given a reason for the connection failing at least.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-02-08 04:20
Was your friend on the same network as you by any chance?  If so, disabling NAT on the server might fix it.

You might also be able to connect to the server via our server browser, if steam's join game feature isn't working for you.

**Comment by MarjieAVolk** [comment] 2018-02-09 20:04
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4056

**Closed by MarjieAVolk** 2018-02-09 20:04 UTC
Labels: High Priority

**Comment by MarjieAVolk** [comment] 2018-02-09 20:07
Sorry, I realized that the server window has been disabled for local servers, so you can't do this. What you can try though is to select 'Join' and add a server 'localhost:3001'. Hopefully you will be able to connect to that. We are working on a better fix for this.
