### ISSUE TITLE
Alpha.6 [d9d6f47c] very hard to identify something in evening

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2314] opened 2017-09-27 09:07 UTC
![image](https://user-images.githubusercontent.com/1900106/30905048-013e5826-a374-11e7-8a0f-c210b5b2033e.png)

**Comment by Nanders** [comment] 2017-09-27 17:29
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2315

**Closed by Nanders** 2017-09-27 17:29 UTC
