### ISSUE TITLE
 [0.9.0.0 beta staging-stable-8] Unable to enter number in wages

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#17390] opened 2020-07-29 12:39 UTC
Nothing happens when i try to focus the number field for wages and press numbers.

![image](https://user-images.githubusercontent.com/982322/88800976-3fe6f400-d1a9-11ea-9bb0-adc7eab052c3.png)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4994860/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4994861/Player.log)

**Comment by IcedForge** [comment] 2020-07-29 14:16
https://github.com/StrangeLoopGames/EcoIssues/issues/17270 
This is closely related to and possibly same core issue.

**Comment by beastyn** [comment] 2020-07-30 05:35
Thank you for the report.
There was an issue with the numbers in titles. Should be fixed with the next update. 
But It can be more common problem which is under investigation right now (can't reproduce it )

**Closed by beastyn** 2020-07-30 05:35 UTC
