### ISSUE TITLE
USER ISSUE: Titel Bug

### ISSUE THREAD

**Issue by Nisutec** [StrangeLoopGames/EcoIssues#12286] opened 2019-05-14 15:55 UTC
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
1. Create a Titel at the Registrar.
2. Add Titel Holders to the Titel.
3. Create a Law with a condition and test if a user have this titel.
4. The new Law will target Titel Holders and Titel Appointers.

**Expected behavior:**
The Law only target the Titel Holders.

**Actual behavior:**
The Law targets the Titel Holders and Titel Appointers.

**Do you have mods installed? Does issue happen when no mods are installed?:**
I use no mods.

**Comment by D3nnis3n** [comment] 2019-05-14 16:03
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12172

**Closed by D3nnis3n** 2019-05-14 16:03 UTC
