### ISSUE TITLE
Work Parties not allowing players to input items to tables

### ISSUE THREAD

**Issue by Mr-Cakes** [StrangeLoopGames/EcoIssues#24820] opened 2024-03-09 10:17 UTC
Good morning.

There appears to be an issue with adding items to work parties;

Work party is set up for players to add items and labour to jobs on a research table, the roles have been taken (though sometimes players are not seeing the ability to take the role).

Right clicking on the table without UI access is in most cases stating there is no project needing the item in the contract (there is)

Adding a law to allow players to open the table and drag the items into the job has worked as a temporary fix however after each craft this appears to cease functioning.

Opening and closing the research table UI will in some cases allow the right click function to work, though this is "sometimes and not always".

I attach the world save for your consideration.

**Comment by Mr-Cakes** [comment] 2024-03-09 10:22
Save file:

https://drive.google.com/file/d/1HK11GS5gP9nH2AzNrMdaidIN2EQ_sgGG/view?usp=drive_link

**Comment by Arend90** [comment] 2024-03-09 11:54
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/31536813/51d36993-cf95-42a0-bff1-ad11737c3942)

**Comment by D3nnis3n** [comment] 2024-03-09 12:48
Put on hold, as 10.2 has a full refactor for authorization and we didn't see any such issue during QA testing of that.
Playtest starts within the next two weeks, release following after. If the issue appears with 10.2, please let us know then.

**Comment by iuriguilherme** [comment] 2024-03-10 20:21
It's important to add that in order to make it easier for people to add ingredients to those big orders, we changed research paper recipes time to a value close to 5 seconds (0.01f).

But I've seen this erratic behaviour without that change. For example, metallurgy basic papers just don't let you add carried ore with the right click interaction, showing the "no order needs coal/iron ore". You have to open the research table UI and add to the work order, and eventually it's gonna glitch like the screenshot sent, showing wrong ingredients to all work orders in the same table or that white box, refusing to accept ingredients.

Looks like client and server don't agree with the state of work orders, and client won't refresh it after a while (probably because it doesn't make sense to poll the orders states constantly)

**Comment by Mr-Cakes** [comment] 2024-04-16 11:00
Good afternoon. 

This continues to be an issue post 10.2, regardless of the order of the jobs either in the contract board or the table with appropriate work orders. The glitch mentioned above where incorrect or blank ingredients show for the work order continues to be an issue. 

As a workaround I have removed all work parties and replaced them with stores which, as they do not accept tags of items and instead need specific items does not seem to be a very useful work around.

The save game above remains relevant to being able to reproduce the error. This is also the case if you were to run a fresh server install with multiple item putting contracts to the same table from the same board, regardless of any modified settings or otherwise.

**Comment by D3nnis3n** [comment] 2024-04-16 11:29
Thanks for the confirmation, the issue is already internally tracked (and hence has never been closed to begin with).

Do I understand correctly the problem is reproducible with multiple contracts for a single table on a fresh, default world?
Any other cases that in a guaranteed manner lead to the problem?

**Comment by Mr-Cakes** [comment] 2024-04-16 11:51
Yes it is reproducable near enough instantly with the following circumstances;

Vanilla server,
Research Table with skill book + all appropriate papers queued
Contract board with labour seperated from materials
Materials seperated per job (for example Baked Meat + Simmered Meat for Culinary Advanced Meat on a seperate contract to Iron Bar and Copper Bar for Metallurgy Advanced)

Player takes the contracts, the labour part of the contract works with no issues in testing, inputting items however will near enough immediately give a "No job is accepting Copper Bar" (or whatever item they are trying to put in).

If the player is given access to the research table directly they are able to input the items by dragging them to the progress bar, however, when the first run is complete there is a high probability that the job will no longer accept the item they are trying to give and may instead show that the item required is something else from the list of other items queued up (i.e. it may start wanting Raw Crops if it was a metallurgy paper). Adding this new, incorrect, item will not progress the paper either. In some instances this will rather than show the incorrect ingredient will instead show a white blank placeholder which does not give any information when moused over.

If the player is able to successfully input an item via the table UI and they do not experience the error where the incorrect or blank ingredient is shown, they are then able to input ONE run worth of materials via right clicking when the UI is not open. After this one run, they are required to either open and close the research table UI to allow more right clicking of items into the job, or all functionality to put in the item ceases. At this point the only option is for the player to reconnect and the cycle starts again. 

Frustratingly this is not always reproducable and sometimes one player is able to input more than one run worth of materials, but eventually they will definitely not be able to do it.

We thought this may be related to multiple people trying to input items at once, or there being an error related to the Tag of the item, for example someone inputting Ceiba Logs at the same time as someone inputting Fir Logs - in these cases it does appear to be more likely that an error occurs, but this is difficult to test on a solo locally hosted environment.

**Comment by D3nnis3n** [comment] 2024-04-17 04:19
QA has found a problem while going through your steps, but we aren't actually sure it is exactly what you are experiencing.

One good way to describe issues is a simple video of doing it - there is often so much information hidden in a video on what a user does or does not (that they don't even notice themselves), or what is present around that videos are the best way to understand an issue. So if you at any point would have time to catch the issue on tape where we can watch what you have been doing, that might also be helpful. For now we're going to assume the found issue is what you are experiencing.

**Comment by D3nnis3n** [comment] 2024-04-29 02:38
So this was related to a change originally marked as intended that would not allow adding ingredients once a crafting project started together with a creative usage of multiple work parties on same place. After discussion it will be addressed via https://github.com/StrangeLoopGames/Eco/pull/13955 in the next Maintenance Update (not Hotfix!).

**Closed by D3nnis3n** 2024-04-29 02:38 UTC
Labels: Type: Bug
