### ISSUE TITLE
Port 2999 critical issue 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#424] opened 2016-07-03 22:09 UTC
Port 2999 cant be changed. People like commercial server hoster's cant host more than 1 server per physical server because port 2999 creates a non recoverable crash.
![port 2999](https://cloud.githubusercontent.com/assets/1668416/16547863/847a79c4-417b-11e6-9abc-d3f4182c30a9.png)

the Serverbrowser.port is making it impossible. ( see reference issue image)

**Comment by noblackthunder** [comment] 2016-07-03 22:11
internal error message ""Only one usage of each socket address (protocol/network address/port) is normally permitted"

also both applications did run as administrator and where set before start up to different ports

**Comment by metachronism** [comment] 2016-07-05 18:35
this is likely dupe of #347

**Comment by noblackthunder** [comment] 2016-07-05 18:37
no this only happens if you have 2 or more instance on the same machine 
But i think the other one might maybe be the same @pingferfect has when it comes to virtual server .. he gets access denied when the server tries to open and lock a port. seems only to happen on virtual servers for some reason

**Comment by noblackthunder** [comment] 2016-07-05 18:39
the issue above throws an error that this port is already in use and can not be binded again

**Comment by metachronism** [comment] 2016-07-05 18:42
yes its the same issue, easy fix inc

**Closed** 2016-07-05 19:07 UTC
Labels: bug, critical
