### ISSUE TITLE
Error when running /spawneconomy command

### ISSUE THREAD

**Issue by R3ido101** [StrangeLoopGames/EcoIssues#3224] opened 2017-12-30 05:19 UTC
Hi i get error;
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object

Stack:
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <01d3ec13f0784c4d88b3e52330d2fa86>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <01d3ec13f0784c4d88b3e52330d2fa86>:0 
  at Eco.Gameplay.ChatManager.InvokeCommand (System.String commandName, System.Reflection.MethodInfo method, System.String args, Eco.Gameplay.Players.User user) [0x00208] in <3efb6410a2804af180b3a2e45ee271fd>:0 
  at Eco.Gameplay.ChatManager.ProcessAsCommand (System.String text, Eco.Gameplay.Players.User user) [0x000fe] in <3efb6410a2804af180b3a2e45ee271fd>:0 
  at Eco.Gameplay.ChatManager.SendChat (Eco.Shared.Services.ChatMessage msg, System.String text, Eco.Gameplay.Players.User user) [0x00008] in <3efb6410a2804af180b3a2e45ee271fd>:0 
  at Eco.Gameplay.ChatManager.SendChat (System.String text, Eco.Gameplay.Players.User user) [0x0000d] in <3efb6410a2804af180b3a2e45ee271fd>:0 
  at Eco.Gameplay.ChatManager.SendChat (System.String text, System.Int32 playerID) [0x0000d] in <3efb6410a2804af180b3a2e45ee271fd>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <01d3ec13f0784c4d88b3e52330d2fa86>:0 

When trying run this command on the latest 6.3.1 Windows 10 PC; Linux Custom Centos 7 image for server server running under ELSM.

**Comment by R3ido101** [comment] 2017-12-30 05:21
And this is a game breaking bug it WILL kick you from the server before showing error.

**Comment by pamduncan** [comment] 2018-01-02 00:15
did it just kick you but you could log back in or did it kick you and crash the server so the server had to restart?

**Comment by R3ido101** [comment] 2018-01-02 02:00
No it Kicked me as soon as i ran the command @pamduncan then spitted the error out and i can join the server fine after.

**Comment by pamduncan** [comment] 2018-01-02 02:24
This also happens on Windows servers.  It is not just a Linux error

Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.ChatManager.SendChat(ChatMessage msg, String text, User user)

**Comment by MarjieAVolk** [comment] 2018-02-13 22:05
Closing as duplicate of #4391

It seems this problem happens when you try to use a chat command without passing it the parameters it wants. To get around this, for now, you can type /help and the command name in order to figure out how to use the command. If that isn't the issue, please let us know in the other bug.

**Closed by MarjieAVolk** 2018-02-13 22:05 UTC
Labels: Low Priority
