### ISSUE TITLE
USER ISSUE: crash when repairing hoe

### ISSUE THREAD

**Issue by PR3SIDENT** [StrangeLoopGames/EcoIssues#4351] opened 2018-02-11 20:09 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Tried to repair a hoe		

**Expected behavior:**
Hoe should display repair needs	

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Repair on RepairComponent!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.Inventory.TryRemoveItems(ItemStack stack, User user)
   at Eco.Gameplay.Components.RepairComponent.Repair(Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

```

**Comment by MarjieAVolk** [comment] 2018-02-13 02:41
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4358 . You can track the issue progress there.

**Closed by MarjieAVolk** 2018-02-13 02:41 UTC
