### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by genesisx111** [StrangeLoopGames/EcoIssues#22416] opened 2021-06-30 04:24 UTC
Yesterday I was able to play it but now I cant

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6738008/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6738009/Player-prev.log)

**Comment by Ry4ndrew** [comment] 2021-06-30 04:37
Duplicate of #21382

**Closed by Ry4ndrew** 2021-06-30 04:37 UTC
