### ISSUE TITLE
[8.1.4] Real Estate Desk denies buying a deed.

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#12312] opened 2019-05-16 04:31 UTC
I wanted to buy back deeds from a friend, I have 190 of his personal credits and a deed costs 50, however when I tried to buy it I got the Error:
"You can't afford to buy this deed for $50 Mazze Credit. you only have $190 Mazze Credit." Which is obviously wrong.

When he bought them from me for his own currency it worked fine.

![RET bug](https://user-images.githubusercontent.com/5678451/57826600-42c41780-77a4-11e9-9f4f-1d885f1b9510.JPG)

**Comment by SlayksWood** [comment] 2019-06-06 10:34
A lot of time has passed. But I need some information:
1. Can you provide screenshots of Economy viewer- Your accounts.
2. Does your nickname "Xavia"?
We found a like problem when buying from a not personal account. But you have in the screenshot shows what you bought from a personal account. Maybe this is not your personal account? but just someone else's personal account to which you have access.

**Comment by SlayksWood** [comment] 2019-06-06 11:15
merged with #12490

**Comment by otting** [comment] 2019-06-06 12:46
I don't understand what kind of screenshot you need from the economy viewer? The world this happened in does no longer exist. My nickname is in fact Xavia, and the amount of 190 MazzeCoins is what was in my personal account at the time.

**Comment by SlayksWood** [comment] 2019-06-06 12:48
@otting 
Need information about your accounts
![image](https://user-images.githubusercontent.com/45708377/59033881-80333680-8872-11e9-9513-f09a196e2a5f.png)

**Comment by otting** [comment] 2019-06-06 12:53
**This is from the same account on another Server as the old world no longer exists**

![Unbenannt](https://user-images.githubusercontent.com/5678451/59034177-c1274d00-886a-11e9-9661-cd0207dab845.JPG)

**Comment by otting** [comment] 2019-06-06 12:57
I had no additional accounts

**Comment by SlayksWood** [comment] 2019-06-06 13:04
@otting 
Then the last questions:
Were there any land sales where this real estate desk is located?(Did "Werkstatt" sale before?)
Did you have this situation a second time? maybe more?

**Comment by otting** [comment] 2019-06-06 13:23
Yes the desk was part of the land that was sold.
The problem appeared again when I tried to buy for my own currency.

**Comment by beastyn** [comment] 2019-06-07 09:19
The problem is with the bank account. Your friend has bought the land from you and when he has created new sale for this land he used your bank account by default. We wil have this issue fixed in 0.9 release.

Your friend just need to check which account he uses when creating the sale.
<aim issue #12361

**Closed by beastyn** 2019-06-07 09:19 UTC
Labels: Investigate, Needs Information
