### ISSUE TITLE
USER ISSUE: Stockpile Trap

### ISSUE THREAD

**Issue by heimskringla** [StrangeLoopGames/EcoIssues#5122] opened 2018-02-26 12:08 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
drop items on non-empty stockpile while standing in the bottom left corner of it

**Expected behavior:**
dropped items where I wasn't standing

**Actual behavior:**
dropped them on me immobilising me. When I picked up the items, other items in the stockpile were dropped on me.

**Comment by fame1991** [comment] 2018-02-26 22:28
Have the same problem

**Comment by MarjieAVolk** [comment] 2018-02-26 23:37
For now, you will just need to use /unstuck to get out.

**Comment by MarjieAVolk** [comment] 2018-03-01 18:24
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4113

**Closed by MarjieAVolk** 2018-03-01 18:24 UTC
Labels: Suggestion
