### ISSUE TITLE
USER ISSUE: Can't use (small) wood carts

### ISSUE THREAD

**Issue by jlfbuijssen** [StrangeLoopGames/EcoIssues#24686] opened 2024-01-24 10:59 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
Whenever I try to use a wood cart or small wood cart, it takes me about 10 seconds to walk from the tile I'm standing on to the next tile.
I have sufficient food to move a cart. It occurs regardless of the load of the cart. Others can still use it fine when I give them permission. I can pick it up and put it back down, nothing changes. This started happening after the updated last Thursday. I tried verifying my files which didn't help, nor did re-starting the dedicated server I'm playing on.

**Expected behavior:**
I'd expect normal walking speed.

**Actual behavior:**
I walk extremely slowly, looking down at my legs, I only take extremely tiny steps. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14037201/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14037202/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-01-24 18:52
Do you have a controller connected to your PC?

**Comment by D3nnis3n** [comment] 2024-02-05 03:59
Closing due to not reproducible and no further information provided.

**Closed by D3nnis3n** 2024-02-05 03:59 UTC
Labels: Status: Needs Information
