### ISSUE TITLE
USER ISSUE: Work order not functional

### ISSUE THREAD

**Issue by Daronius** [StrangeLoopGames/EcoIssues#25030] opened 2024-08-14 21:55 UTC
\
**User Id: (slg230235)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Add a work order to any workstation

**Expected behavior:**
Show the work order with the correct icon, amount, labour and added items

**Actual behavior:**
It looks like an dummy work order. (see attached image)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

![grafik](https://github.com/user-attachments/assets/78e3f9e6-fb04-493b-91f5-defd6bcf78f1)

**Comment by D3nnis3n** [comment] 2024-08-15 07:17
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24886

**Closed by D3nnis3n** 2024-08-15 07:17 UTC
