### ISSUE TITLE
5.4 Chat issue, active chat, green field

### ISSUE THREAD

**Issue by Lostinthesofa** [StrangeLoopGames/EcoIssues#1084] opened 2017-02-11 02:28 UTC
When i click the channel in the chat it removes the green marker field around the that chat room. To reaply it i need to click the x and hide the channel and then unhide it. i cant click it directly to make it green or active again.

**Comment by MarjieAVolk** [comment] 2017-02-14 19:03
That's odd, I have never seen that behavior.  When hovering with your mouse over a deselected chat room, do you see a grey marker on the room name?

**Comment by MarjieAVolk** [comment] 2017-02-14 19:03
Checking on the chat log ui here, and I still don't see this problem

**Comment by Lostinthesofa** [comment] 2017-02-14 20:24
when i am hovering over i get hte gray box but hen i click it goes gray not green

**Comment by MarjieAVolk** [comment] 2017-02-14 20:34
Any chance you could send me some gifs or screenshots?

**Comment by Lostinthesofa** [comment] 2017-02-14 20:34
sure send on here then or? not sure how i put htem in here xD

**Comment by Lostinthesofa** [comment] 2017-02-14 20:43
![publc is deseleceted](https://cloud.githubusercontent.com/assets/25699214/22948356/74d4c882-f2fe-11e6-94df-bf842c1ccfb1.jpg)
Here i have deselected the channel

![hovering mouse over publc](https://cloud.githubusercontent.com/assets/25699214/22948348/63c2e9fc-f2fe-11e6-8e08-ff4074b4e1da.jpg)
Here i am hovering over

![clicked and removed mouse from publc](https://cloud.githubusercontent.com/assets/25699214/22948366/7e5bc392-f2fe-11e6-8a1e-8b0ba2719bef.jpg)
Here i have clicked it and removed my mouse from the channel

**Comment by Lostinthesofa** [comment] 2017-02-14 20:50
![clicked the x hiding hte channel then clicking the little o readding the channel and its green](https://cloud.githubusercontent.com/assets/25699214/22948619/8192f57a-f2ff-11e6-8438-0546d2b94dc0.jpg)
clicked the x hiding the channel while the channel was gray. Then clicking the little o readding the channel and its green

**Comment by MarjieAVolk** [comment] 2017-02-14 20:53
Ah you figured out how :P Great, thank you.  I'm guessing from this that what's going on is that an exception is getting thrown when you try to change chat room selection, because your chat is in a bad state.

I see that you have a chat room called "@#Crafting", which used to be a valid name but is not any longer... so I'm guessing that could be what's causing it.  I'll see if I can make this backwards compatible for the next release.

**Comment by Lostinthesofa** [comment] 2017-02-14 21:05
awesome :)

**Comment by MarjieAVolk** [comment] 2017-02-16 22:53
Hey again, unfortunately I haven't been able to identify what is causing this yet.  Any chance you would be able to send me the Game.eco save file for your server?  You can email it to me at marjie@strangeloopgames.com if you aren't able to attach it here.

**Comment by Lostinthesofa** [comment] 2017-02-16 23:22
If this is a file thats in the server not on the client then i cannot send
you it. I am playing on the european offcial server. Think noblackthunder
on eco discord is admin there. If its a file i got on my client then i can
send you it after work.

16. feb. 2017 11:53 p.m. skrev "MarjieAVolk" <notifications@github.com>:

**Comment by MarjieAVolk** [comment] 2017-02-16 23:24
No, it would be on the server.  Okay, I'll see if I can get a hold of it, thanks

**Comment by Lostinthesofa** [comment] 2017-02-16 23:26
Okay i can try and contact noblackthunder about it when i get off work if
you cannot get hold of him :) sadly im on nightshift so whont be until
morning at the earliest =\

17. feb. 2017 12:24 a.m. skrev "MarjieAVolk" <notifications@github.com>:

**Comment by MarjieAVolk** [comment] 2017-02-16 23:27
Seems he saw this thread and is sending the file to me now :P

**Comment by noblackthunder** [comment] 2017-02-16 23:29
yea send to marjie !

**Comment by Lostinthesofa** [comment] 2017-02-16 23:30
Haha awesome :p he probably have a radar for his name goimg off :) just ask
if you need anything more off me btw :)

17. feb. 2017 12:27 a.m. skrev "MarjieAVolk" <notifications@github.com>:

Seems he saw this thread and is sending the file to me now :P

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/StrangeLoopGames/EcoIssues/issues/1084#issuecomment-280498014>,
or mute the thread

**Comment by MarjieAVolk** [comment] 2017-02-17 00:14
Well this is strange, I got your save file and still cannot reproduce this issue, I don't know how to explain what's going on

**Comment by Lostinthesofa** [comment] 2017-02-17 00:37
Hmm will you need some system information then?

17. feb. 2017 1:14 a.m. skrev "MarjieAVolk" <notifications@github.com>:

**Comment by noblackthunder** [comment] 2017-02-17 00:39
I think some system information would be helpful, like are you using Mac os or linux or windows ( if its windows it is even stranger i suspect ) and maybe info about Gpu and driver versions could also give some pointers

**Comment by Lostinthesofa** [comment] 2017-02-17 00:41
Okay so a dxdiag then ? Using a windows pc. Windows 10 i assume its the
same way as before just run dxdiag to get it up ? :)

17. feb. 2017 1:39 a.m. skrev "noblackthunder" <notifications@github.com>:

**Comment by noblackthunder** [comment] 2017-02-17 00:42
Yea .. Dx diag works fine .. if you can mail that to marjie directly i think its better since github is public

**Comment by Lostinthesofa** [comment] 2017-02-17 00:43
Okidoki will do that when im off work :) whont be for another 6 hours thou

17. feb. 2017 1:42 a.m. skrev "noblackthunder" <notifications@github.com>:

**Comment by Lostinthesofa** [comment] 2017-02-17 01:44
I got curious and i have downloaded the game to my laptop at work and
tested it there and i get same thing here :s the channel box becomes gray
but never green unless i remove it and readd it. Also tried with 32bit
version just to have done it. I know for a fact my laptop is running old
drivers, of probably everything hehe

17. feb. 2017 1:14 a.m. skrev "MarjieAVolk" <notifications@github.com>:

**Comment by MarjieAVolk** [comment] 2017-10-13 00:02
Well I never did figure this out, and haven't gotten any more complaints about it all this time, so closing for now

**Closed by MarjieAVolk** 2017-10-13 00:02 UTC
