### ISSUE TITLE
USER ISSUE: cannot pull from stockpile

### ISSUE THREAD

**Issue by mark9976** [StrangeLoopGames/EcoIssues#6163] opened 2018-03-16 21:56 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
goto stock pile and attempt to remove item into carrying location.	

**Expected behavior:**
I expect that the item moves to my carrying location.	

**Actual behavior:**
the icon will get stuck in the middle of the screen and stay there.  The item is no longer in my stock pile and will require that I restart the game in order to get the item back.

**Comment by MarjieAVolk** [comment] 2018-03-20 23:03
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

This seems to be related to double clicking.  Sometimes this is caused by a specific mouse, so for now if you have the option to use a different mouse, that might help prevent this issue.

**Closed by MarjieAVolk** 2018-03-20 23:03 UTC

**Comment by Gringar** [comment] 2018-03-21 14:44
See my comment in #3841. It's more of a Windows 10 compatibility issue. Running Eco in Compatibility Mode for Windows 7 fixes it for me. It's been multiple days and it hasn't happened a single time where normally I fought with this issue over a dozen times per day.
