### ISSUE TITLE
Law that prevented placing blocks, resulted in phantom blocks

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3396] opened 2018-01-14 23:11 UTC
I placed a dirt block, which was prevented by a law.  The law prevention message came up, but the block got placed and didn't disappear after a number of seconds.  I tried to log out and back in, and when I logged out the server threw a bunch of exceptions from NetPort and NetBuffer, but then recovered and didn't crash.  When I logged back in, the block I illegally placed was indeed gone again.  This happened every time I tried and was easily repeatable.

**Comment by MarjieAVolk** [comment] 2018-01-14 23:14
Realized this client side exception is related - get's thrown when I place said block:

```
Exception: Could not find matching method RewindPredictions on type NetObjComponent taking 1 parameters.
Eco.Shared.Networking.RPCManager.InvokeOn (Eco.Shared.Serialization.BSONObject bson, System.Object controller, System.String methodname)
Eco.Shared.Networking.RPCManager.HandleReceiveRPC (INetClient client, Eco.Shared.Serialization.BSONObject bson)
NetworkManager.ReceiveEvent (INetClient client, NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) (at Assets/Scripts/Networking/NetworkManager.cs:390)
Eco.Shared.Networking.NetObject.ReceiveEvent (INetClient client, NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson)
Eco.Shared.Networking.NetPort.ProcessBuffer ()
Eco.Shared.Networking.NetPort.Update ()
NetworkManager.Update () (at Assets/Scripts/Networking/NetworkManager.cs:339)
```

**Comment by metachronism** [comment] 2018-01-15 19:02
dupe of #3404

**Closed by metachronism** 2018-01-15 19:02 UTC
Labels: High Priority
