### ISSUE TITLE
[0.8.1.0] The vehicle doesn't move when fuel is added after you get into it.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11920] opened 2019-04-08 09:49 UTC
1. Put the truck.
2. Give rights to another person.
3. Don't add fuel.
4. Get into the truck.
5. Another person adds fuel.
6. The fuel is displayed in the fuel supply. But you can't move.
7. Get out of the truck / get into the truck. This helps solve the problem.

**Comment by mirasrael** [comment] 2019-04-08 10:07
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11886

**Closed by mirasrael** 2019-04-08 10:07 UTC
Labels: Medium Priority, Quality Assurance
