### ISSUE TITLE
USER ISSUE: No Icons, no players

### ISSUE THREAD

**Issue by Shejtana** [StrangeLoopGames/EcoIssues#24585] opened 2024-01-10 22:08 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Starting Game

**Expected behavior:**
Want to see Icons of worktables and shops and Player Icons.

**Actual behavior:**
Dont see Icons and PlayerIcons

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods on Client Side, Mods on Server in Internet

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-11 01:52
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24131

**Closed by D3nnis3n** 2024-01-11 01:52 UTC
