### ISSUE TITLE
USER ISSUE: Inventory search bar sometimes does not work

### ISSUE THREAD

**Issue by SilverjetPlane** [StrangeLoopGames/EcoIssues#25232] opened 2024-10-31 16:17 UTC
\
**User Id: (0a0a79a8-6ba0-4fca-bec1-08dcbd51a712)**
**Version:** 0.11.1.1 beta release-758

**Steps to Reproduce:**
Start game, right-click on any container or crafting table. Switch to inventory(?) tab ("Speicher"). 

**Expected behavior:**
When filling out the search bar, it should filter the available inventory.

**Actual behavior:**
Sometimes the last search term is still in the field, but even if not, inventory is not getting filtered even if typing something new. 
It should be noted there is something like a not updating char in it, when removing it the x for deleting the query also vanishes, when typing something it first does not show, but typing further updates the search box, but without actually filtering the inventory. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files.**
[Player.log](https://github.com/user-attachments/files/17590274/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17590276/Player-prev.log)

**Comment by SilverjetPlane** [comment] 2024-10-31 16:20
May be a duplicate of #25230

**Comment by D3nnis3n** [comment] 2024-10-31 21:46
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25230.

**Closed by D3nnis3n** 2024-10-31 21:46 UTC
