### ISSUE TITLE
USER ISSUE: [Art] [Low Priority] Stone and and odd shape Ore Bumps appear and still show through Ramps

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5651] opened 2018-03-08 02:39 UTC
**Version:** 0.7.2.2 beta

![snap1932](https://user-images.githubusercontent.com/29383891/37129827-a8610c6a-2278-11e8-921d-d3b2ec751db0.png)
![snap1933](https://user-images.githubusercontent.com/29383891/37129978-67bdb3ec-2279-11e8-98cc-7d13e83f479b.png)
![snap1934](https://user-images.githubusercontent.com/29383891/37129984-70fbdf92-2279-11e8-9094-347fd5bfdc88.png)
![snap1935](https://user-images.githubusercontent.com/29383891/37129998-82fa480a-2279-11e8-98e6-f3dd1fd6df8a.png)
![snap1936](https://user-images.githubusercontent.com/29383891/37130012-93ad4666-2279-11e8-909d-6d0fa1a85142.png)

@keegan-o Depending on where the Bumps are and in which order Ramps are placed they react in different ways as far as i can tell they dont react badly to Carts or vehicles just make the ramps look horrible

**Comment by MarjieAVolk** [comment] 2018-03-08 21:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2033

**Closed by MarjieAVolk** 2018-03-08 21:40 UTC
