### ISSUE TITLE
[0.9.0 Staging - 1494] Windows do not turn corners

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15550] opened 2020-04-04 14:28 UTC
Windows, as a technical wall block do not turn corners yet glass can. This should be possible, you can build a window frame to turn a corner realistically so the windows in game should be able to do it, hell its even possible to do this in minecraft so it should be doable in a more powerful engine like unity.
![20200404081121_1](https://user-images.githubusercontent.com/1329717/78453326-978bad80-7656-11ea-84dc-2381344d9c4c.jpg)
![20200404081118_1](https://user-images.githubusercontent.com/1329717/78453327-98bcda80-7656-11ea-83df-93460b0df122.jpg)

**Comment by elfl0rd** [comment] 2020-04-04 19:02
Not an issue, can be a suggestion.
Also if you want to use window in this behavior, you can use "WindowWall" (e.g. in composite lumber)
![изображение](https://user-images.githubusercontent.com/4980243/78459182-eb7eac80-76bf-11ea-907d-525c95f59a5a.png)

**Comment by Sarah-Graesyn** [comment] 2020-04-04 20:10
Issue being that in order for that to work you have to get to tier 4 materials, it should also work with lower tier (e.g. Lumber/Mortared Stone)

**Comment by Engimage** [comment] 2020-04-08 10:16
Windows on the edges were always an issue for me. I kind of fix this by building "floor" type blocks on intersections but this is definitely lacking atm. Windows tend to turn to random directions if there are no window blocks to the sides which is a real bummer. Seeng how it is implemented in Glass made me wonder why.

**Comment by keegan-o** [comment] 2020-04-13 19:47
Old sets will eventually be updated with better window wall forms like we have on composite lumber. the double window form also turns corners currently. Part of why I haven't rushed to do so is because there will be more fundamental refactoring to forms in the future and they'll just have to be done again once that happens (and icons that would have to be made for some forms to work now will become useless later, so it'd also be wasted work).

**Comment by keegan-o** [comment] 2020-06-12 22:42
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3480

**Closed by keegan-o** 2020-06-12 22:42 UTC
Labels: Category: Art, Priority: Low
