### ISSUE TITLE
USER ISSUE: Crash when cutting a tree

### ISSUE THREAD

**Issue by SrPeterr** [StrangeLoopGames/EcoIssues#5355] opened 2018-03-04 00:37 UTC
**Version:** 0.7.2.0 beta staging-adf7002a

**Steps to Reproduce:**
1.Cut down a tree
2.Went back to house, placed stones on stockpile
2.Went back to cut in pieces the tree
3.Crash

**Expected behavior:**
Cut the tree

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by SrPeterr** [comment] 2018-03-04 00:39
---More---
Every time I join the world again and try to cut it, it crashes.

**Comment by MarjieAVolk** [comment] 2018-03-05 23:19
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-03-05 23:19 UTC
