### ISSUE TITLE
USER ISSUE: Error Message whilst collecting wood

### ISSUE THREAD

**Issue by Advocata** [StrangeLoopGames/EcoIssues#5302] opened 2018-03-02 15:17 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Went back and picked up a flying piece of wood from where I had been chopping a tree down earlier.

**Expected behavior:**
I should have just been able to add the wood to my carrying inventory.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-03-02 18:42
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-03-02 18:42 UTC
