### ISSUE TITLE
Easy click to transfer items into the box being currently opened by the player

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3163] opened 2017-12-19 01:54 UTC

**Comment by stormoffires** [comment] 2017-12-19 02:15
my hero!!!

**Comment by MarjieAVolk** [comment] 2018-05-14 22:58
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4280, since that has more discussion on this.

**Closed by MarjieAVolk** 2018-05-14 22:58 UTC
Labels: Suggestion
