### ISSUE TITLE
Something broke with localization

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10773] opened 2019-01-19 19:40 UTC
![image](https://user-images.githubusercontent.com/3536496/51431527-f8100580-1bde-11e9-8877-38ce1d51329d.png)
May have happened after your PR @craig-jong

**Comment by johnkslg** [comment] 2019-01-19 19:40
See if you can revert whatever it was?

**Comment by elfl0rd** [comment] 2019-01-19 19:59
Duplicate of #10701

**Closed** 2019-01-19 20:11 UTC
Labels: High Priority
