### ISSUE TITLE
Error causing players to be ejected from game

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6125] opened 2018-03-16 02:25 UTC
--BEGIN DUMP--
Dump Time
03/15/2018 20:33:02

Exception
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: arrayIndex
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-20 22:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5527

**Closed by MarjieAVolk** 2018-03-20 22:32 UTC
