### ISSUE TITLE
Saguaro Cacti

### ISSUE THREAD

**Issue by Thineboot** [StrangeLoopGames/EcoIssues#6340] opened 2018-03-21 17:17 UTC
EcoPC_v0.7.3.0-beta-staging-eb6e4ece
Seed: 1367431573
Default setting

Some cacti are not created properly. Best example at 585,42,531
![ecosaguaro](https://user-images.githubusercontent.com/4364842/37725027-4a7b1810-2d32-11e8-9932-a8aa6c32185a.png)

Unless I'm missing something there seems to be no seed for SaguaroCactus yet.

Started another world before with a big chunk of SaguaroCactusYieldPotential but not a single one was spotted flying above the whole area. Most of the area was under water...

**Comment by MarjieAVolk** [comment] 2018-03-21 18:05
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6164

**Closed by MarjieAVolk** 2018-03-21 18:05 UTC
