### ISSUE TITLE
alpha staging 68ea8201- Trees not falling down

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1650] opened 2017-06-13 12:22 UTC
so I have cut down five trees in a row and none of them will fall down they all stood straight up even cut the roots under them with the  axe and they will not budge, can not even push them down like you use to be able to do when this would happen.   - now some trees do fall but at this point for me its about half ratio.
![20170613071945_1](https://user-images.githubusercontent.com/15990789/27082083-04686fb4-5009-11e7-8d8f-74d7cb96a2a9.jpg)
![20170613071949_1](https://user-images.githubusercontent.com/15990789/27082088-071a051a-5009-11e7-8633-a756eefc6e1d.jpg)

**Comment by REPOSEECO** [comment] 2017-06-13 15:20
With me also but not so often

**Comment by MarjieAVolk** [comment] 2017-06-15 20:01
Closing as a duplicate of StrangeLoopGames/EcoIssues#1452

**Closed by MarjieAVolk** 2017-06-15 20:01 UTC
