### ISSUE TITLE
USER ISSUE: Plant Already Exists Here

### ISSUE THREAD

**Issue by Kirbiez** [StrangeLoopGames/EcoIssues#5983] opened 2018-03-13 02:52 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
I planted my farm and logged back in the next day, some plots were blank, no dead or live plant but still plowed. I tried to plant a new plant and was told "Plant Already Exists Here". I tried digging out the dirt and replowing it as well as droping dirt on top of it and picking it back up to no affect.

**Expected behavior:**
Should have planted a new plant on the plowed land.

**Actual behavior:**
Displayed error stating "Plant Already Exists Here."

**Comment by MarjieAVolk** [comment] 2018-03-13 23:07
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5607

**Closed by MarjieAVolk** 2018-03-13 23:07 UTC
