### ISSUE TITLE
[0.9.0 staging-1285] Web: action counting for graphs

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14009] opened 2019-12-04 13:24 UTC
I see that graphs filters had changed. I can't see particular peopla statistic for example.

And. check action counting please.
I was digging, placing, pickuping... and nothing on stats.
![bandicam 2019-12-04 18-18-48-857](https://user-images.githubusercontent.com/27898520/70146075-46c57180-16c3-11ea-9eb5-b52eb24c6da3.jpg)

**Comment by Alteraner** [comment] 2020-04-07 11:22
Several statistics are not working in the webfrontend:
all Climate:
![image](https://user-images.githubusercontent.com/47274045/78663525-8cdd4c80-78d2-11ea-9757-c17bd041a6cc.png)
all Player Action:
![image](https://user-images.githubusercontent.com/47274045/78663597-b4341980-78d2-11ea-8644-2ebccce815c6.png)
Plants/Trees/Animals working fine.
tested on 0.9.0.0 beta staging-1501

**Comment by denysaw** [comment] 2020-04-17 19:23
All Climate stats work good:
![image](https://user-images.githubusercontent.com/5720101/79606126-6b117000-80f1-11ea-845a-2972fa3d6665.png)

And all PlayerAction stats are coming from server empty, maybe because of user really did nothing or maybe some wrong filtering on GameServer side. Putting `Status: Fixed` for issue to be re-tested and assigning it to @Quadbro in a case of re-opening (if PlayerAction really should be filled with data), he'll check the server side. Thank you ;)

**Comment by beastyn** [comment] 2020-04-21 11:32
Yeap, still an issue, action stat is not working.
But @denysaw I don't see climate graphs.
It seems that there is kind of response [0.0,2.105927]
![bandicam 2020-04-21 16-29-01-617](https://user-images.githubusercontent.com/27898520/79861333-b081b600-83ed-11ea-8e6b-3cf64ac37a34.jpg)

**Comment by mirasrael** [comment] 2020-04-21 13:35
https://github.com/StrangeLoopGames/EcoIssues/issues/15861
@beastyn climate stats fixed for this issue (old stats won't be repaired)

**Comment by denysaw** [comment] 2020-04-21 18:24
It's me assigned again 😺 
@Quadbro can you, please check is it ok, that Player Actions are empty in that world? Cuzz mine is kinda world start I think it's totally ok Player has no actions yet.
If you'll agree it's not a client issue, please unassign me ;) Thanx

**Comment by beastyn** [comment] 2020-04-22 07:21
Yeap, Climate is fine now.

**Comment by Alteraner** [comment] 2020-04-22 09:20
Yes, i can confirm. Climate is working right now.

Player Action is still not working. Even a further bug came in. While clicking on one of the player actions, it is been listed in the graph legend, but the respective item is not colored in the list any more. Besides that still no values been seen on the graph. I have tested it with a server running for a while and did some actions which had to be seen on the graph.

**Comment by beastyn** [comment] 2020-04-30 10:25
@Alteraner thank you
@Quadbro check this too, I had problems with actions:
Demographic change
Claim or Unclaim
Vote
Start Election
Character Level up
Contstruct ot deconstruct
Place or pickup
Play 
First Login

**Comment by beastyn** [comment] 2020-05-01 05:04
moving #16068

**Closed** 2020-06-01 06:36 UTC
Labels: Category: Web, Priority: Medium
