### ISSUE TITLE
USER ISSUE: Objects disappearing + Icon stuck

### ISSUE THREAD

**Issue by PrincessCady** [StrangeLoopGames/EcoIssues#5423] opened 2018-03-05 17:54 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Putting the icon of objects/materials in another chest, stockpile etc. 1/10 times this happens.

**Expected behavior:**
Object should be in chest (example: 100 corn) 

**Actual behavior:**
Object disappears (example: 100 corn) and icon of corn gets stuck rather randomly on screen. (Can be solved between chests and stockpiles by using another chest/stockpile to access object)

**Comment by MarjieAVolk** [comment] 2018-03-05 19:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

A workaround is to minimize the game and reopen it - this should reset any stuck icons.  Several people have observed that this bug is specific to certain mice - a mouse that sends duplicate click events for example is more likely to have this problem.

**Closed by MarjieAVolk** 2018-03-05 19:29 UTC
