### ISSUE TITLE
Lag bug from user

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18963] opened 2020-10-28 17:41 UTC
my name is Arthur. Im a big Eco Fan and im hosting the world "Grimms Ecotopia".
First of all sorry for the inconvenience at all, but we seem to have an issue we cant solve with our knowledge. The world is loading but feels unstable, having lag-spikes we didnt experience before. And the log files get huge, because this error is being spammed a couple of times per second into the log. Since 30h all my savegames and backups have this error in them (repeating thousands of times):

[17:39:19.976] [5] [ Info] [Eco] Initializing IntegrationTestsPlugin...  
[17:39:21.005] [5] [ Info] [Eco] Saving world...  
[17:39:21.161] [44] [Error] [Eco] Error inserting stat of type ItemCraftedAction into databaseSystem.ArgumentException: An item with the same key has already been added. Key: 65535 (Parameter 'key')
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at LiteDB.Engine.BasePage.Defrag()
   at LiteDB.Engine.BasePage.InternalInsert(UInt16 bytesLength, Byte& index)
   at LiteDB.Engine.BasePage.Insert(UInt16 bytesLength, Byte& index)
   at LiteDB.Engine.DataPage.InsertBlock(Int32 bytesLength, Boolean extend)
   at LiteDB.Engine.DataService.<>c__DisplayClass3_0.<<Insert>g__source|0>d.MoveNext()
   at LiteDB.Engine.BufferWriter..ctor(IEnumerable`1 source)
   at LiteDB.Engine.DataService.Insert(BsonDocument doc)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.<>c__DisplayClass20_0.<Record>b__0()
   at Eco.Stats.LiteDbService.WithTransaction(Action action, Int32 timeout)
   at Eco.Stats.Stats.Record(IStat obj)

I really hope not to bother you to much with this question. Keep up the amazing work you and your team do. We enjoy being a part of it!

**Comment by D3nnis3n** [comment] 2020-10-28 18:37
I removed the e-mail address for privacy purposes.

**Comment by D3nnis3n** [comment] 2020-10-28 18:37
Actually looks like the DB broke.

**Comment by mirasrael** [comment] 2020-10-29 09:12
Unfortunately we can't repair DB, so only way to fix the issue is restore from last working DB backup or re-create it from scratch. It will erase all stats and can make some demographics/laws start working improperly, but won't corrupt game itself.

**Comment by D3nnis3n** [comment] 2020-10-29 09:21
That's what i told the user and what he has done, so closing this issue.

**Closed by D3nnis3n** 2020-10-29 09:21 UTC
Labels: Status: Investigate
