### ISSUE TITLE
USER ISSUE: Excavator deceleration on ramps

### ISSUE THREAD

**Issue by dmb1996** [StrangeLoopGames/EcoIssues#4925] opened 2018-02-22 01:46 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.Drive an Excavator
2.Start to go down a stone or asphalt ramp
3.Attempt to stop
4.Dont
5.Crash into something or fly off a cliff or become a fish

**Expected behavior:**
It should be able to at least slow down for control while going down a ramp.

**Actual behavior:**
Instead, depending on how many ramps, you cant stop for at least 10 or so blocks.

**Comment by MarjieAVolk** [comment] 2018-02-23 23:11
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4436

**Closed by MarjieAVolk** 2018-02-23 23:11 UTC
Labels: Medium Priority
