### ISSUE TITLE
USER ISSUE: odd visual bug

### ISSUE THREAD

**Issue by TheLostTex** [StrangeLoopGames/EcoIssues#19862] opened 2020-12-28 18:02 UTC
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
new player log in
enable dev fly ccommand
fly aroun 5-10 secs

**Expected behavior:**
nothing abnormal

**Actual behavior:**
visual distortions, debris coulds and shadows are black unrednered pixiliated clouds

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods, pure vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment] 2020-12-29 13:30
Thank you for reporting.
This is a duplicate of #14042 and what it does is known as breaking the shaders, it will currently happen if you teleport, fly very quickly etc.

**Closed by IcedForge** 2020-12-29 13:30 UTC
