### ISSUE TITLE
Check the Hoe's  one of them need only 1/5 Nutrion and iron you cant't see in window

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2563] opened 2017-10-17 20:04 UTC
![grafik](https://user-images.githubusercontent.com/26040573/31734878-5fb2f74a-b440-11e7-9356-9f3ced643cc9.png)
I hop this explain it :-)

**Comment by MarjieAVolk** [comment] 2017-10-17 20:50
I don't understand what you are saying

**Comment by MarjieAVolk** [comment] 2017-10-23 20:16
Okay, so I think there are 2 issues being reported here - one, that the different hoes have the same icon, and two that one or more of the hoes use much fewer calories than they should.

I went and looked at the hoes, and it looks like only the legacy hoe (just "Hoe" with no material first) is the one that has the low calorie cost, which I believe is fine since that should no longer be available in the game on a new save file.

@keegan-o Could you create different temporary icons for the various hoes, like the other tools have?  Also, I noticed some of the hoes have no model when being used.  Would it be difficult to copy the original hoe model/animation for the others, for now?

**Comment by MarjieAVolk** [comment] 2018-01-12 20:47
Closing this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2478

**Closed by MarjieAVolk** 2018-01-12 20:47 UTC
