### ISSUE TITLE
Housing items get randomly re-ordered on server restart.

### ISSUE THREAD

**Issue by Splutty** [StrangeLoopGames/EcoIssues#5633] opened 2018-03-08 00:01 UTC
When restarting the server, housing items get randomly re-ordered, which causes housing efficiency to drop like a rock when you have items of different values in most/all of your rooms.

**Comment by MarjieAVolk** [comment] 2018-03-08 20:09
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4583

**Closed by MarjieAVolk** 2018-03-08 20:09 UTC
