### ISSUE TITLE
USER ISSUE: Failed to Connect

### ISSUE THREAD

**Issue by tenpigs** [StrangeLoopGames/EcoIssues#11544] opened 2019-03-02 18:19 UTC
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
Start the game

**Expected behavior:**
It should connect to the game

**Actual behavior:**
I get the 'failed to connect' message

**Do you have mods installed? Does issue happen when no mods are installed?:**
I get the 'failed to connect' message

**Comment by D3nnis3n** [comment] 2019-03-03 21:27
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11548

**Closed by D3nnis3n** 2019-03-03 21:27 UTC
