### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by bigapples99** [StrangeLoopGames/EcoIssues#6215] opened 2018-03-18 01:24 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
```
Caught exception:

<size=60.00%>Value cannot be null.
Parameter name: item


Stack:
  at System.Collections.Immutable.ImmutableHashSet`1[T].Contains (T item) [0x00000] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at Eco.Core.Utils.ThreadSafeHashSet`1[T].Contains (T item) [0x00000] in <253a2607346749769956a6a449ee4298>:0 
  at Eco.Core.Controller.ControllerInstanceInfo.TryBind (Eco.Shared.Networking.INetClient client) [0x00006] in <253a2607346749769956a6a449ee4298>:0 
  at Eco.Core.Controller.ControllerManager.TryBindController (Eco.Core.Controller.IController controller, Eco.Shared.Networking.INetClient boundClient) [0x00054] in <253a2607346749769956a6a449ee4298>:0 
  at Eco.Core.Controller.ControllerManager.PackageController (Eco.Core.Controller.IController controller, Eco.Shared.Networking.INetClient boundClient) [0x00000] in <253a2607346749769956a6a449ee4298>:0 
  at Eco.Gameplay.Objects.WorldObject.SendInitialState (Eco.Shared.Serialization.BSONObject bsonObj, Eco.Shared.Networking.INetObjectViewer viewer) [0x0000d] in <71aea58a8e7643ecb2cf55a32b967729>:0 
  at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates (System.Collections.Generic.IEnumerable`1[T] newObjects, Eco.Shared.Networking.INetObjectViewer viewer, System.Collections.Generic.ICollection`1[T] monitored) [0x00032] in <e4e46f3a65d54122a8b353a81ca58447>:0 
  at Eco.Plugins.Networking.Clients.Client.Update (System.Diagnostics.Stopwatch timer) [0x000b9] in <d7c4587bc24f4e958b2e3f6662a4aa90>:0 
  at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1 () [0x00012] in <d7c4587bc24f4e958b2e3f6662a4aa90>:0 
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-20 17:31
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6292

**Closed by MarjieAVolk** 2018-03-20 17:31 UTC
