### ISSUE TITLE
USER ISSUE: Frozen Elk

### ISSUE THREAD

**Issue by rpsiv** [StrangeLoopGames/EcoIssues#5933] opened 2018-03-11 23:52 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Elk looked like it could not move from one tile to another. It was shaking back and forth quickly.  I hit it with arrows, and I believe at the amount it would have died the game crashed

**Expected behavior:**
Elk should have fell over

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC Hit on ArrowEntity!

Object reference not set to an instance of an object.


Stack:
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Simulation.Agents.Animal.Damage(Single amount, DeathType damageSource)
   at Eco.Gameplay.Animals.AnimalEntity.TryApplyDamage(INetObject damager, Single damage, InteractionContext context)
   at ArrowEntity.Hit(NetObjAttachInfo hitAttachInfo, Vector3 position)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-20 00:54
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4860 (seems like this can happen from animals getting killed in a variety of ways).

**Closed by MarjieAVolk** 2018-03-20 00:54 UTC
Labels: Medium Priority
