### ISSUE TITLE
7.7.0 Render Scale/Resolution Issue with Server Display Windows

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8991] opened 2018-08-17 09:03 UTC
Resolution is 1920X1080/Fullscreen

Render Scale is 60%

Interface Scale is 60%

Unable to read names of the servers and other information in the Server Display Windows.  I tried resetting scale and then one window I was on would come fully into the window but the others did not and when I slid out of the one taht was fixed it lost its focus again:

[![Screenshot from Gyazo](https://gyazo.com/9ac5b10a3a9cb4fa3c47f66e1c9afd78/raw)](https://gyazo.com/9ac5b10a3a9cb4fa3c47f66e1c9afd78)

**Comment by BlazeGuy2** [comment] 2018-08-17 15:50
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/8897, was fixed on latest bleeding_edge update.
![fixedscreenshot](https://user-images.githubusercontent.com/35509188/44275813-8e886700-a1fa-11e8-9123-470f91d04e28.PNG)

**Closed** 2018-08-17 15:52 UTC
