### ISSUE TITLE
USER ISSUE: Crashing client on tree chopping

### ISSUE THREAD

**Issue by gknedo** [StrangeLoopGames/EcoIssues#4698] opened 2018-02-17 10:58 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Found a chopped tree on ground
2. Each hit on tree my client crash

**Expected behavior:**
client dont crash
wood given to my inventory

**Actual behavior:**
client crashed
wood given to my inventory on login

The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-22 19:57
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-22 19:57 UTC
