### ISSUE TITLE
Arrow's not going where u aim

### ISSUE THREAD

**Issue by Snooy** [StrangeLoopGames/EcoIssues#2809] opened 2017-11-12 13:36 UTC
Staging Alpha 6.1.0 #E401a76d

Arrow's do not go where you aim, They shoot ALL over the place.. and no i am not a bad shoot, it just seems like the arrow's randomly go all over the screen.

**Comment by wiloxe** [comment] 2017-11-12 13:43
Already fixed in latest.
(If you are on same server)
Dupe of #2787

**Closed** 2017-11-12 13:46 UTC
