### ISSUE TITLE
[0.8.1.2] Bad IP validation

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11964] opened 2019-04-11 06:16 UTC
Maybe we should check bad IP on a client side?
"111" is obviously not IP nor ID, so why try to connect.

![bandicam 2019-04-11 11-15-35-790](https://user-images.githubusercontent.com/27898520/55934805-3bf93080-5c4b-11e9-8dd2-3241f1596aec.jpg)
![bandicam 2019-04-11 11-11-44-817](https://user-images.githubusercontent.com/27898520/55934807-3e5b8a80-5c4b-11e9-8a50-5dec54b1a510.jpg)

**Comment by D3nnis3n** [comment] 2019-04-11 06:36
That would be a regression as that worked earlier. I believe that happens because of server-ids, probably.

**Comment by mirasrael** [comment] 2019-04-11 11:36
@D3nnis3n Don't think it is regression. It still shows error for something like `asdsad`, but 111 seems 
like a valid address for lib we are using for resolving ip addresses (111 -> 0.0.0.111).

**Closed** 2019-04-11 17:05 UTC
Labels: Fixed, Low Priority, Quality Assurance
