### ISSUE TITLE
USER ISSUE: /testcranes truck sound glitch

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#8157] opened 2018-06-27 01:29 UTC
**Version:** 0.7.5.0 beta

**Steps to Reproduce:**
1. use the admin crane testing command.
2. Load the adjanced truck with hewn logs
3. Pick up and place hewn logs in, check the inventory (probably not so much of a required step)
3. enter the vehicle, while not fuelling it up

**Expected behavior:**
It shouldn't emit it

**Actual behavior:**
It emits the wood cart sound while sitting on a driver seat without fuel

**Comment by GophTheGreat** [comment] 2019-05-24 04:38
Could not reproduce. Closing for now.

**Closed by GophTheGreat** 2019-05-24 04:38 UTC
Labels: Medium Priority
