### ISSUE TITLE
USER ISSUE: Placing Objects also Produces Ghost Tent

### ISSUE THREAD

**Issue by TinkerYellowmane** [StrangeLoopGames/EcoIssues#22875] opened 2021-12-29 09:10 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.4 beta release-273

**Steps to Reproduce:**
Take any object that is placable in the world (dirt, stone, crafting stations, ect) and walk around

**Expected behavior:**
Most likely, it should produce a 'ghost' of whatever one is holding in one's hand.

**Actual behavior:**
The game will produce a 'ghost' of one's starter tent.  This 'ghost' remains in game until another object is held in hand

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No - that game is vanilla install and start.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment] 2021-12-30 18:40
Hello @TinkerYellowmane ,

Thank you very much for your feedback, Your report has clearly caught our attention. I would like to ask you some questions.

- Can you reproduce this issue again?
- What are your PC specs?

We would really appreciate if you could share your save file and your logs.

Thank your for your time.

**Comment by D3nnis3n** [comment] 2022-07-18 10:08
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)

**Closed by D3nnis3n** 2022-07-18 10:08 UTC
Labels: Status: Needs Information
