### ISSUE TITLE
(6.1.0 #4e325355) - Wrong Username gets announced at notification.

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2646] opened 2017-10-28 16:51 UTC
Hello again! The wrong username was given when chrismoh added iron to one of his projects. As seen in the chat it was correct in the first action but the second time it gives out another user (the user is online).

![weird stuff](https://user-images.githubusercontent.com/32855684/32136593-baf28512-bc10-11e7-8d3e-0c76c6011328.png)

I have also seen this happen when giving out points by command. Instead of saying the username i gave it to it says my own username. As shown below:

![note](https://user-images.githubusercontent.com/32855684/32136612-00ec881a-bc11-11e7-8fa4-584a8a1a4478.png)

I gave that point too Tooxic, that was shown in the last image.

**Comment by MarjieAVolk** [comment] 2017-10-30 18:09
The skill point one will be an easy fix.

As for contributing to a project - did Chrismoh use different methods to contribute to the project for each of those 2 messages?  I'm guessing for 1 they dragged it directly into the table, and for the second they added it to a chest (maybe a chest that belonged to Tooxic)?

**Comment by ZebZ** [comment] 2017-10-30 18:23
That i do not know. The project might have been started by tooxic but i do not think he used something that belongs to tooxic.

**Comment by MarjieAVolk** [comment] 2017-10-30 18:27
Aha, project started by Tooxic.  Okay I will look into it, see what I can find.  It has been a fight to get the users right for adding things to projects, since there are lots of ways to do so, which can involve property belonging to lots of players

**Comment by ZebZ** [comment] 2017-10-30 21:04
Yeah i spoke to chrismoh now and he did not think that he was mixing around with tooxic's property.

**Comment by MarjieAVolk** [comment] 2017-11-02 19:25
I have tested out lots of different ways of adding things, and haven't been able to reproduce this.  All I can think would be if both Chrismoh and Tooxic modified the same stockpile at the same time (Chrismoh to put the iron ore in and Tooxic doing something else)?

**Comment by ZebZ** [comment] 2017-11-03 11:53
Could be that they were linking the same stockpile as we have 3 town stockpiles. But it was so random and unmonitored so hard tp know. Mostly just me who try to reproduce stuff =)

**Comment by MarjieAVolk** [comment] 2017-11-03 17:45
Okay if there were communal stockpiles involved, I'm going to assume for now that that's what happened - because of some technical issues, if two people modified the stockpile in the same game tick, then whoever did so last will get credit for all of the modifications.  It would be pretty complicated to fix that and doesn't seem like that big of an issue, so I'm thinking I'll call won't fix on this one >>  (I did fix the give skillpoints one)

But if you see the issue a lot, or see it in another context, feel free to reopen or file another bug.

**Closed by MarjieAVolk** 2017-11-03 17:45 UTC
