### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#307] opened 2016-06-16 21:27 UTC
http://ecoforum.strangeloopgames.com/topic/598/framerate-game-using-100-cpu

i also note that i have a 4 gen Core i/ 4930 and a 980 ti and i get pretty low fps ( starts at 20) goes down to 5 and less after a wile.

this is way to low for a high end gaming rigg.

**Comment by metachronism** [comment] 2016-06-17 16:38
dupe of #261

**Closed by metachronism** 2016-06-17 16:38 UTC
