### ISSUE TITLE
Server Crash when placing the Constitution table

### ISSUE THREAD

**Issue by E39LP** [StrangeLoopGames/EcoIssues#24358] opened 2023-12-22 08:50 UTC
I place the Constitution table and my Linux Server Crashing. 

I have testet with Local Windows Server, but its Crash when in place the Constitution table. 

Error:  [114] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.ConstitutionComponent.InitializePersistentData()
   at Eco.Gameplay.Objects.TrackPlacementComponent.Initialize()
   at Eco.Gameplay.Components.ConstitutionComponent.Initialize()
   at Eco.Gameplay.Objects.WorldObject.InitializeComponents()
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, WrappedWorldPosition3 position, Quaternion rotation)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.ConstitutionComponent.InitializePersistentData()
   at Eco.Gameplay.Objects.TrackPlacementComponent.Initialize()
   at Eco.Gameplay.Components.ConstitutionComponent.Initialize()
   at Eco.Gameplay.Objects.WorldObject.InitializeComponents()
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, WrappedWorldPosition3 position, Quaternion rotation)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[16:32:33.999] [114] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.ConstitutionComponent.InitializePersistentData()
   at Eco.Gameplay.Objects.TrackPlacementComponent.Initialize()
   at Eco.Gameplay.Components.ConstitutionComponent.Initialize()
   at Eco.Gameplay.Objects.WorldObject.InitializeComponents()
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, WrappedWorldPosition3 position, Quaternion rotation)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.ConstitutionComponent.InitializePersistentData()
   at Eco.Gameplay.Objects.TrackPlacementComponent.Initialize()
   at Eco.Gameplay.Components.ConstitutionComponent.Initialize()
   at Eco.Gameplay.Objects.WorldObject.InitializeComponents()
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, WrappedWorldPosition3 position, Quaternion rotation)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by D3nnis3n** [comment] 2023-12-22 15:58
Settlements enabled or disabled?

**Comment by E39LP** [comment] 2023-12-22 17:59
Settlements enabled and disabled 
I have try with Dedicated Linux Server, Lokal Windows Server and Ingame Server. With different Settings.

**Comment by E39LP** [comment] 2023-12-23 13:12
I have in Featurs.eco this Config make: {
  "RentEnabled": true,
  "VoiceChatEnabled": true,
  "FoodVarietyMultiplierEnabled": true,
  "FoodTastinessMultiplierEnabled": true,
  "EducationEnabled": true,
  "SettlementSystemEnabled": false,
  "CultureEnabled": true,
  "AllowFaceTrackingOnServer": true,
  "AchievementsEnabled": true,
  "CameraModeEnabled": true,
  "InitialSpawnSelection": true
}

Now i can place it.

**Comment by D3nnis3n** [comment] 2023-12-31 14:25
You cannot change the settings for SettlementSystemEnabled during a world. Whenever you change it you must make a new world or your current one will corrupt. I'm not able to reproduce this with a fresh world and the respective settings.

**Comment by E39LP** [comment] 2023-12-31 14:48
Thanx for Answer, but i have change the Settings befor create a world. Now its the Problem on a Local world too. Its same to befor or after create a World on change the Settings. 

Reages.

**Comment by D3nnis3n** [comment] 2024-01-02 02:27
You cannot place a constitution in a settlements on world, they only exist on settlements off. Local servers started via the client always have settlements on, no matter what you configure in the configs. Looks like it works correctly on worlds that have settlements disabled, hence closing the issue. The crash itself is already addressed in a future update to be replaced with a message stating it cant be placed with these settings.

**Closed by D3nnis3n** 2024-01-02 02:27 UTC
Labels: Status: Needs Information, Status: Not reproduced
