### ISSUE TITLE
Server won't start and chunk-loading problems

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7497] opened 2018-04-30 19:44 UTC
From the support queue:

"I have the problem that our Eco-server does not start anymore.
If I can see that correctly in the server console then there seems to be a problem with the garbage manager.
I've linked all the important and necessary information to a Zip archive on Dropbox so you can better handle this problem.

Further information:

- No modifications were used
- Eco Version 7.4.0 Staging
- All further information in the Zip Archive

Another problem that has long been on my mind is the loading of the chunks.
Unfortunately, Eco can not play well without laggs at all.
I have tried all graphics options and possibilities and the week after week but the problem seems to be the code.
Most of the problem seems to occur in stockpiles and boxes or where much was built.
Another graphics card and processor could not solve the problem.
A softer load of chunks would solve or improve this problem.
I know that Eco is a lot of work and there is an enormous pressure on them so I would like to meet them with the information to make their job easier.

Thank you for the 295 hours of playing time I had fun with Eco.

If this message arrives and they can help me, I thank you in advance.

ZIP Password: ecostaging
Dropbox Link: https://www.dropbox.com/s/ixya75o043aqvkc/Bug%20Report%20Informations.zip?dl=0"

**Comment by SeanAtr0n** [comment] 2018-05-01 01:18
seems like several issues here... the garbage thing might be resolved though? 

I'm trying to load it now but it takes a very long time to load

**Comment by SeanAtr0n** [comment] 2018-05-01 01:41
it loaded on the latest staging build so I guess you could tell them that... although I didn't use their config files so maybe they need to update one of their config files if it doesn't load for them

**Comment by Steam-Kenn32** [comment] 2018-05-01 08:33
This problem with the garbage does not always seem to crop up.
As you can see in the picture, there seems to be a problem with the garbage.
The loading of the world takes a long time since it is 9 square kilometers.
I hope this problem with the next versions no longer appears.
I can not say exactly why.

However, the problem with loading the chunks always exists.
I do not think it is because of my system because other players have the same problem.

**Comment by SeanAtr0n** [comment] 2018-05-01 17:41
Yeah loading chunks will likely continue to be a problem near complex city centers, thats more of a general performance problem. I'll leave the bug open but it sounds like the main problem of the world not loading at all is resolved

**Comment by metachronism** [comment] 2018-05-03 19:27
closing this per earlier discussions
perf issue is a dupe of other issues, something we are always looking into

**Closed by metachronism** 2018-05-03 19:27 UTC
Labels: Medium Priority
