### ISSUE TITLE
[8.2] Crash from voice system

### ISSUE THREAD

**Issue by quequiere** [StrangeLoopGames/EcoIssues#12610] opened 2019-06-20 17:31 UTC
Got this crash:
--BEGIN DUMP--
Dump Time
06/20/2019 19:28:27

Exception
Exception: SocketException
Message:A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 50.112.72.195:443
Source:System
NativeErrorCode:10060
ErrorCode:10060

System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 50.112.72.195:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

--END DUMP--

**Comment by D3nnis3n** [comment] 2019-06-20 17:56
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12533

**Closed by D3nnis3n** 2019-06-20 17:56 UTC

**Comment by redwyre** [comment] 2019-06-20 18:03
@quequiere what makes you think this is voice related?

**Comment by quequiere** [comment] 2019-06-20 20:28
I "voice" in log :S but i restarted before save the log sry :S
