### ISSUE TITLE
SpecialtyExperienceDivisor used in config, server control panel and in custom profile (starting new world from client) but looks unused

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15721] opened 2020-04-11 20:11 UTC
Can someone take a look?

**Comment by WeaselDog** [comment] 2020-04-12 01:27
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11296

**Closed by WeaselDog** 2020-04-12 01:27 UTC
