### ISSUE TITLE
Temperature Issues

### ISSUE THREAD

**Issue by Bazzi89** [StrangeLoopGames/EcoIssues#18697] opened 2020-10-11 22:00 UTC
On our world the temperature in each biom raised ~2°C, there is no way to farm several plants... seems like an bug, is there a workaround via config?

4km² World, Industry is in Desert and a lil bit in other biomes...

at day one, all seems okay

**Comment by ThePiachu** [comment] 2020-10-12 02:09
Probably the temperature was raised because of industry air pollution. Did you recently get started with the Oil processing? That usually is the big CO2 producer. Check your CO2 levels. The temperatures should return to normal once the CO2 levels go down. If not, this might be a bug.

**Comment by SlayksWood** [comment] 2020-10-12 05:44
@Bazzi89 Follow @ThePiachu advice. Ground pollution appears near your craft stations, temperatures rise across the planet. So seems that's intended behavior, but I want to check it full. So provide information from status bar of any craft station with pollution (e.g. Blast Furnace or Oil refinery):
![image](https://user-images.githubusercontent.com/45708377/95709342-219c7a80-0c67-11eb-86f8-cf7e9aa6a7f2.png)

**Comment by Bazzi89** [comment] 2020-10-17 12:13
![20201013122607_1](https://user-images.githubusercontent.com/36135677/96336859-b7c70b00-1082-11eb-8995-4775db561566.jpg)

sorry for late answer, but thats one of my blast furnace

**Comment by SlayksWood** [comment] 2020-10-19 09:04
What about your temperature now?
Maybe you had some kind of technological bang? And you made a lot of pollution?
Can you prodice save file to investigate? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
If you don't want to make it public, you can send to my mail kirill@strangeloopgames.com or in Discord Kirill (Slayks)#6251

**Comment by IcedForge** [comment] 2020-11-05 10:47
Will close this as it has been over 2 weeks with no reply, i will assume this issue has been resolved.
If you are still experiencing this problem please reopen and inform us about it so we can further investigate this issue.

**Closed by IcedForge** 2020-11-05 10:47 UTC
Labels: Status: Needs Information
