### ISSUE TITLE
[0.9.0 staging-1424] Shop buy and sell not working for quantity

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#14859] opened 2020-02-25 20:52 UTC
Hello,
 we have tested to buy and sell some stuff on the shop. For some reason some of the entrys are not possible to change or as buyer you cannot modify the quantity's.

Screen by the seller
![image](https://user-images.githubusercontent.com/47274045/75286420-cffac900-5818-11ea-8ac2-dd9976de67df.png)

Screen by the Buyer
![image](https://user-images.githubusercontent.com/47274045/75286431-d426e680-5818-11ea-90ee-3a1dc79bbfc2.png)

**Comment by D3nnis3n** [comment] 2020-02-27 06:29
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14877

**Closed by D3nnis3n** 2020-02-27 06:29 UTC
