### ISSUE TITLE
[0.8.2.0] Staging -4 Login Problems

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12237] opened 2019-05-09 16:05 UTC
You can´t login in Eco with the current Version.

Probably because of the change from yesterday StrangeLoopGames/Eco#4390 

![grafik](https://user-images.githubusercontent.com/37456949/57468481-cf427780-7284-11e9-8c2a-e681d458f7e4.png)

You can´t change the Auth back.  Then you can login the game but the Server has a Crash.
![grafik](https://user-images.githubusercontent.com/37456949/57468546-f39e5400-7284-11e9-9692-139398201ecb.png)

**Comment by redwyre** [comment] 2019-05-09 16:15
Yep, that's correct. If you set the auth back you will need to set the VoiceManager.TokenComesFromAuthServer to false in BOTH the server and client.

**Comment by Sekor2600** [comment] 2019-05-09 16:36
hi,

did change the following:
![grafik](https://user-images.githubusercontent.com/37456949/57470407-0b77d700-7289-11e9-91cd-a31bbc39c6cd.png)
![grafik](https://user-images.githubusercontent.com/37456949/57470425-1599d580-7289-11e9-860e-ec4f531ddcef.png)
![grafik](https://user-images.githubusercontent.com/37456949/57470444-1df21080-7289-11e9-81a9-3e906142eff2.png)

But Server is still crashing with
![grafik](https://user-images.githubusercontent.com/37456949/57470502-437f1a00-7289-11e9-996a-b5e395356f31.png)

**Comment by redwyre** [comment] 2019-05-09 17:09
What is that error in English? Are you able to get it in the debugger?
If you're on discord you can message me

**Comment by D3nnis3n** [comment] 2019-05-09 18:06
Not a bug as the auth server just need to be updated later on, therefore closing, feel free to discuss further on the issue, though.

**Closed by D3nnis3n** 2019-05-09 18:06 UTC

**Comment by redwyre** [comment] 2019-05-10 12:43
Ah sorry, already got him sorted, forgot to close the issue
