### ISSUE TITLE
USER ISSUE: Anti-gravity log!

### ISSUE THREAD

**Issue by RoboGenius** [StrangeLoopGames/EcoIssues#4356] opened 2018-02-11 20:57 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1: chop down tree
2: leave logs uncollected for some time (unsure how long)
3: leave game and rejoin

**Expected behavior:**
logs should stay on the ground

**Actual behavior:**
one log became an object that could not be collected or chopped, when reloading the game it launched from the ground, bounced off a tree, and now stays hovering above my homstead.

**Comment by MarjieAVolk** [comment] 2018-02-13 02:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668 - You can continue tracking issue progress there.

We have had a number of reports of this.  We are still looking for a solution.

**Closed by MarjieAVolk** 2018-02-13 02:29 UTC
