### ISSUE TITLE
7.2.0 Cart authorization checks land deed instead of cart ownership

### ISSUE THREAD

**Issue by fezhub** [StrangeLoopGames/EcoIssues#5555] opened 2018-03-07 06:54 UTC
1) Drive owned cart onto unauthorized land 
2) Attempt to PUT items into cart
3) 'You are not authorized to put items into that'

NOTE: Take works, use works and UI opens. Dragging from player inventory to cart also fails.

**Comment by MarjieAVolk** [comment] 2018-03-07 22:39
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5229

**Closed by MarjieAVolk** 2018-03-07 22:39 UTC
