### ISSUE TITLE
[Suggestion] Doors self close after a period of time

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2947] opened 2017-11-30 08:04 UTC
Would be nice to have doors self close after a period of time for those times when you share your deed and those people don't close the door behind them (especially handy if you have tables that you have forgotten to Inherit and have left public) or you don't want people seeing what you have been doing in your super secret Hideout ㊙️

**Comment by MarjieAVolk** [comment] 2017-11-30 18:09
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2679

**Closed by MarjieAVolk** 2017-11-30 18:09 UTC
