### ISSUE TITLE
Truck bugged? 

### ISSUE THREAD

**Issue by elcid82** [StrangeLoopGames/EcoIssues#7808] opened 2018-05-18 08:35 UTC
Hi,

I played Eco for several days now, always using the standard version (not opted in to any of the other versions), so it should be 0.7.4.5 right now.

I play Eco on my localhost server. I have a Win7Pro 64bit PC, 32GB RAM, AMD PhenomII X6 (3.2GHz), GeForce GTX 960.

I finally got to build all the vehicles, but it seems to me, that the Truck is bugged:
While in-game, there doesn't seem to be any problem when you build the Truck. I could drive around with it, load and unload it and so on. Then I stopped the game and server and after some hours I started both again. While I tried logging in to my server, the game finally got stuck at the "Entering World ..." screen. I could still hear the birds and the wind, but otherwise the game just froze, so I had to stop the process via the taskmanager. Since there was no error message I even let the game sit at the "Entering World..." screen for around half an hour before stopping it manually.

I tried relogging to the server at least two times, but it didn't work. Then I let Steam verify the game cache and it found 6 missing files. After downloading them I tried relogging again, but still no luck. After that I checked the storage directory of the server, made a backup of the current save and put one of the older backups (where I hadn't build any vehicle yet) in the storage folder. Relogging then worked, so I played on with this save.

At this time I had no idea what caused the freeze, so I built the Truck again. The next day, I tried relogging again and the above mentioned problem repeated. I googled a bit for a fix of this problem and found a workaround:

I edited my registry so that the chatlog wouldn't be loaded when you start the game.

_Here is the workaround I found:_
go to:
**HKEY_CURRENT_USER\Software\Strange Loop Games\Eco**

**or** if you can't find this key (I had to use the one below, maybe it is different on different Windows versions):

**HKEY_USERS\S-1-5-21-2911842374-3805089114-3363064554-1003\Software\Strange Loop Games\Eco**

find the string:

**GUIS/ChatLog/open_h4152787235**

double click the string and change the value from 1 to 0

(this keeps the chatlog closed upon entering the game)

After that, the game loaded again. But when I hit 'C' to open the chatlog, the game freezes again. And to add to the Truck issue... my truck has completely vanished from the game, except for the deed. But even the deed doesn't seem to know where the corresponding Truck is:

![truck_missing1](https://user-images.githubusercontent.com/31385244/40224035-412fcd48-5a85-11e8-90cc-498a8db7dd8f.jpg)
Here you can see how it should be on a deed. The deed shows the name of the vehicle and while hovering over the link, the current location of the object.

![truck_missing2](https://user-images.githubusercontent.com/31385244/40224043-45b81226-5a85-11e8-86c1-1857d38712f2.jpg)
Thats the Truck deed. No vehicle name, no link, no location. Just as if the truck isn't there at all (and since  I couldn't find the truck at or around the place I parked it prior to exitting the game, I believe it just vanished.)

I uploaded the zipped world files to dropbox. Here is the link:
https://www.dropbox.com/s/1q7abm8iba14tzt/Storage.zip?dl=0

If you need further information just ask.

Thanks for an otherwise great game! ;)

**Comment by SeanAtr0n** [comment] 2018-05-18 22:59
Looks like the truck is really gone, don't see any trucks on the server.

We can probably do something about the chat crash though... I was able to reproduce by opening the chat log in unity

**Comment by MarjieAVolk** [comment] 2018-05-18 23:07
The chat issue is a duplicate ofhttps://github.com/StrangeLoopGames/EcoIssues/issues/7736

But I have not been able to reproduce it so, @SeanAtr0n if you can, I would love to see that.

**Closed by MarjieAVolk** 2018-05-18 23:07 UTC
Labels: High Priority

**Comment by SeanAtr0n** [comment] 2018-05-19 01:09
Thanks for the save file, very helpful for reproducing the chat bug... also cool area you built :)

**Comment by elcid82** [comment] 2018-05-21 16:16
Thanks ;) I hope you can find the bug. I also have another save from prior the missing truck. If you want that too, just tell me.
