### ISSUE TITLE
USER ISSUE: Movement

### ISSUE THREAD

**Issue by DrNanfran85** [StrangeLoopGames/EcoIssues#24475] opened 2023-12-31 07:34 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Walk in 3rd person.

**Expected behavior:**
Should have a walking animation in motion when in 3rd person.

**Actual behavior:**
Floating as if standing still.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
There are mods on this server but this has happened on my blank server as well. I'm on "Retirement Home" server now.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-31 14:15
Cannot reproduce, got a video?

**Comment by D3nnis3n** [comment] 2024-01-11 18:21
Closing due to no further information provided.

**Closed by D3nnis3n** 2024-01-11 18:21 UTC
Labels: Status: Needs Information, Status: Not reproduced
