### ISSUE TITLE
Closing world object UI with escape leaves cursor enabled AND returns camera control

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18750] opened 2020-10-13 23:14 UTC
![animx22.gif](https://images.zenhubusercontent.com/5ecc5c35b608cc220cfb5b6d/d0f1b176-403e-4ec4-b1e7-f39b9e46e90b)

We've had quite a few recurring problem cases with escape + cursor behavior.  In addition to fixing this bug, can you test dialogs in the game to make sure everything works properly?  Cursor should go away after closing the last blocking dialog if there are no other big dialogs on screen, regardless of whether you close it with escape or X or clicking out of it, or some other way. 

Ensure these dialogs are all properly going through the escape/close manager, dont let them get away with handling their own escapes and closings willy-nilly.  Wrangle them up.

**Comment by SlayksWood** [comment] 2020-10-14 07:03
@gzatravkin and I can't reproduce it. But I found another issue when try, at first I wanted to post here, but there are steps there, so I decided to open a new one #18754

**Comment by Daniel-Magulado** [comment] 2021-07-08 12:09
Closing, updated on Clickup.

**Closed by Daniel-Magulado** 2021-07-08 12:09 UTC
Labels: Priority: Low, Squad: Wild Turkey, Status: Fixed
