### ISSUE TITLE
[9.3] Stockpile throws error when trying to add stack larger than 20

### ISSUE THREAD

**Issue by Chrescerya** [StrangeLoopGames/EcoIssues#21389] opened 2021-04-15 15:19 UTC
TEST:
- fill skid steer with sandstone
- try dump content from driving steer into large lumber stockpile
NOTICE: empty error is thrown and resources remain in skid steer

TEST:
- fill skid steer with sandstone
- go to storage tab of skid steer
- try shift+drag sandstone into large lumber stockpile
NOTICE: empty error is thrown and resources remain in skid steer

**Comment by WeaselDog** [comment] 2021-04-15 22:26
Thanks for alerting us to this issue. This will be fixed in our next hotfix.

**Comment by SlayksWood** [comment] 2021-04-16 14:59
Still an issue, but when I use command, but early it was not a problem with command. Possible we have steps without command too. So step to reproduce:
- place Large Lumber stockpile
- /give Sandstone 200 (any number which is bigger than 20)
- try to place Sandwtone to Large Lumber Stockpile:
![image](https://user-images.githubusercontent.com/45708377/115043658-6ab2dd00-9edd-11eb-94e6-5d6231dcf4dc.png)
- you can't. But I don't have any problem to place this sandstone to Stockpile.

@ptitducanh Can you check it again?

**Comment by Daniel-Magulado** [comment] 2021-04-17 09:02
The issue is also happening with other types of vehicles such as **Steam Tractor** as well as with its Modules. Tested on 0.9.3.1 Release-204.
Here are related user reports:
- #21424
- #21434

**Closed** 2021-04-20 08:15 UTC
Labels: Priority: Critical, Regression, Squad: Wild Turkey, Status: Reopen
