### ISSUE TITLE
USER ISSUE: Stone Road and Asphalt Road is too high cannot enter doorway

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4184] opened 2018-02-09 15:56 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
make stone road next to a door then try walking IN, you can walk out onto stone road but not in

**Expected behavior:**
allow	both in and out of door

**Actual behavior:**
cannot get in through door as player now too high

![snap1605](https://user-images.githubusercontent.com/29383891/36036394-a79c9ba4-0db1-11e8-93d3-2edc7669c9ea.png)
![snap1606](https://user-images.githubusercontent.com/29383891/36036395-a7c11966-0db1-11e8-9ef5-69e8d12c3207.png)
![snap1607](https://user-images.githubusercontent.com/29383891/36036397-a7df1786-0db1-11e8-8b13-34320a10965b.png)
![snap1608](https://user-images.githubusercontent.com/29383891/36036685-6754d84e-0db2-11e8-80f0-1b84f34a7499.png)

**Comment by Huntermeign** [comment] 2018-02-09 16:48
I mentioned this in #3582

**Comment by MarjieAVolk** [comment] 2018-02-09 19:17
Ah, hm didn't realize it was actually blocking doors.  Closing this one as a duplicate of #3582 - I will up the priority of that a bit

**Closed by MarjieAVolk** 2018-02-09 19:17 UTC
