### ISSUE TITLE
USER ISSUE: Animals & Carts

### ISSUE THREAD

**Issue by mreil617** [StrangeLoopGames/EcoIssues#5180] opened 2018-02-27 15:24 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Animal runs into cart (or excevator)	

**Expected behavior:**
not sure...

**Actual behavior:**
vehicle gets thrown

**Comment by MarjieAVolk** [comment] 2018-02-27 18:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2729

**Closed by MarjieAVolk** 2018-02-27 18:25 UTC
