### ISSUE TITLE
USER ISSUE: Bug de Connexion

### ISSUE THREAD

**Issue by LaSantaMilbur** [StrangeLoopGames/EcoIssues#23348] opened 2022-08-15 10:55 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
1.Lancer le jeux
2.Cliker sur Héberger un Monde
3. cree un monde

**Expected behavior:**
Je devrais pouvoir rejoidre mon monde sans problem.

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Les informations de connexion n'ont pas pu être vérifiées. Nos serveurs d'authentification peuvent être en panne.

<size=60,00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non je n'ais pas de mod

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-08-22 22:33
Hello LaSantaMilbur,
this is not a bug but caused by Eco being unable to reach our master servers.

Typically this happens when security software or firewalls block the access and can be resolved by exempting Eco in any antivirus software. You can also test by using a VPN.

In Eco authentication is done by the server, hence when you play on a online server you're likely not seeing the problem, as those servers have no issues connecting to our master server, while when you play a local game, a local server is run that has the issue.

Further information can be received at [support@strangeloopgames.com](mailto:support@strangeloopgames.com).

**Closed by D3nnis3n** 2022-08-22 22:33 UTC
