### ISSUE TITLE
USER ISSUE: attempt to log in on 10.1 server

### ISSUE THREAD

**Issue by randomO9** [StrangeLoopGames/EcoIssues#24640] opened 2024-01-18 21:11 UTC
\
**User Id: (slg228299)**
**Version:** 0.10.1.0 beta release-576

**Steps to Reproduce:**
update from 10.0.4 to 10.1.0

**Expected behavior:**
it should log in

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.UserHelpers.UserAccounts.<UpdateClaimableSettlements>g__Iter|21_0()+MoveNext()
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other, MutationInput origin)
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 items, Boolean avoidWithComparer)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T,TArg](T& original, TArg arg, Func`3 apply)
   at Eco.Core.Utils.ControllerHashSet`1.<>n__3(IEnumerable`1 e)
   at Eco.Core.Utils.ControllerHashSet`1.<>c__DisplayClass21_0.<SetInternal>b__0()
   at Eco.Core.Utils.TrackedCollecti</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-18 21:41
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24634

**Closed by D3nnis3n** 2024-01-18 21:41 UTC
