### ISSUE TITLE
USER ISSUE: Repeating Contracts Not Repeating

### ISSUE THREAD

**Issue by Groveinator** [StrangeLoopGames/EcoIssues#4683] opened 2018-02-17 05:38 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Create a contract to place items into a storage bin. (In this case: 20 logs into a stockpile for 20 currency)
2. Make repetitions infinite by changing to 0.
3. Upon completing contract, currency is awarded as normal and contract remains on board.
4. Items required for contract completion are removed from contract, making it invalid.

**Expected behavior:**
Keep the contract as-is to allow players to complete it over and over to gain currency.

**Actual behavior:**
It deletes the item requirement, forcing the contract owner to manually add the item requirement back  for each repetition.

**Comment by Therandus93** [comment] 2018-02-17 17:52
Can confirm this is an issue. makes it so you have to reset supposed 'repeatable contracts'.

**Comment by MarjieAVolk** [comment] 2018-02-23 21:34
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4161

**Closed by MarjieAVolk** 2018-02-23 21:34 UTC
