### ISSUE TITLE
USER ISSUE: Objects are gone in specific area

### ISSUE THREAD

**Issue by twsgermany** [StrangeLoopGames/EcoIssues#7974] opened 2018-06-04 23:43 UTC
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
I dont know, it happens random and not to all objects. Just to ramps and vehicles til now	

**Expected behavior:**
Ramps and Vehicles are visible

**Actual behavior:**
Ramps and Vehicles are gone. (You can run through the places where they should be). BUT: I can access to the inventory of the truck if I access to a chest near to the last known position of the truck. 

<details>
<summary>Log File</summary>(...previous log truncated...)

df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

Couldn't find mapping for object 'StorageClosetObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'StorageClosetObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'StorageClosetObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

CheckResources () for Camera (WaterDistort) should be overwritten.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'StorageClosetObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by BlazeGuy2** [comment] 2018-06-05 01:08
Duplicate of #7957.  Closing this thread, but referencing it in the other.

**Closed by BlazeGuy2** 2018-06-05 01:08 UTC
