### ISSUE TITLE
USER ISSUE: Uncorrect roof placement

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7550] opened 2018-05-02 17:15 UTC
**Version:** 0.7.4.0 beta staging-518a927f

**Steps to Reproduce:**
see screenshot
![default](https://user-images.githubusercontent.com/4980243/39538451-8bf6cdd2-4e45-11e8-8c59-c8df77389826.png)

**Comment by keegan-o** [comment] 2018-05-10 22:30
Closing as duplicate of other bugs for bad roof behavior.

**Closed by keegan-o** 2018-05-10 22:30 UTC
Labels: Medium Priority
