### ISSUE TITLE
Log Levitation

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#4329] opened 2018-02-11 15:32 UTC
After restarting the server and logging in next to chopped logs, they can be observed floating upwards into the sky until they reach a certain altitude. I have seen this behavior in versions 7.0.4 to 7.1.0 staging.

**Comment by Quicksilv3r710** [comment] 2018-02-11 20:44
Can confirm. Don't try to interact with them as they are floating away, or else you might be booted from the server =)

**Comment by MarjieAVolk** [comment] 2018-02-13 02:37
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668 - You can track the issue progress there.

We are looking into this, but have been unable to reproduce it (despite many people reporting it).  If you have additional information about how to reproduce, or if you have a save file where you consistently see this, that would be a huge help.

**Closed by MarjieAVolk** 2018-02-13 02:37 UTC

**Comment by Kastuk** [comment] 2018-02-16 09:00
My lumber are flied away with low gravity ascending after cutting little piece of old log on the slope (edge of cliff). Slighty tilted before cut. Little part dropped back after ~30 m of flying. Other's – after server restart.
![20180214225801_1](https://user-images.githubusercontent.com/36314945/36299983-6b0081e2-1310-11e8-9d92-e837f299ad02.jpg)
