### ISSUE TITLE
USER ISSUE: Picking up Tree

### ISSUE THREAD

**Issue by SlaskoCZ** [StrangeLoopGames/EcoIssues#4127] opened 2018-02-08 19:36 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. got 12 wood
2. pickup already cutted tree (maybe someone already picked it up)

* after log into the game, the log dissapeared so something wrong with client sync

**Expected behavior:**
get more wood to my hand

**Actual behavior:**
The following error message popped up:
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-08 20:02
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

It seems this is related to logs floating in the air, but unfortunately that is all I know right now!

**Closed by MarjieAVolk** 2018-02-08 20:02 UTC
