### ISSUE TITLE
USER ISSUE: Stock pile blocks appear invisible

### ISSUE THREAD

**Issue by 1Jamster1** [StrangeLoopGames/EcoIssues#4555] opened 2018-02-15 01:27 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Place wood pillar next to full stock pile

**Expected behavior:**
Render in the adjacent block in the stock pile

**Actual behavior:**
Causes the stock pile block to go invisible. Even though it can be fully seen.

Screenshots:
![20180215112815_1](https://user-images.githubusercontent.com/1897011/36236728-6e4efe14-1243-11e8-85df-9bb76d4d8eb5.jpg)
![20180215112819_1](https://user-images.githubusercontent.com/1897011/36236729-6e7e5178-1243-11e8-8bb6-1a8e798fd247.jpg)

**Comment by MarjieAVolk** [comment] 2018-02-24 00:38
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4616

**Closed by MarjieAVolk** 2018-02-24 00:38 UTC
