### ISSUE TITLE
USER ISSUE: Error on chop/pick up of tree piece entity

### ISSUE THREAD

**Issue by murl** [StrangeLoopGames/EcoIssues#5096] opened 2018-02-25 21:34 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
While trying to harvest/chop large tree piece, it busted into multiple pieces on one chop and received error message. "Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
"

**Expected behavior:**
Allowed user to pick up entity or chop.

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-26 19:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-26 19:11 UTC
