### ISSUE TITLE
[0.9.0.5 br-100] The game needs better support for group activities

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18931] opened 2020-10-26 23:43 UTC
I've been playing with a proper collab group on White Tiger recently, and I've ran into a few issues I think need fixing to help with the "group" playstyle (whether it's two or twenty people working together).

First of all, there is a bit of an issue with inventory juggling. Since every player can link any inventory to a work table AND those links are player-specific ( #15644 ) you have to bother people to re-link inventories whenever you say, change stockpiles to lumber stockpiles, add something new, etc. You can't stop someone else's work order from eating resources from stockpiles you don't want them to ("this crushed limestone is for quicklime, not for roads!"), dumping into wrong stockpiles ("nails go into chests not stockpiles!"), etc.

I understand why this restriction is in place (so you'd have more control of your workbenches and people couldn't steal from your production in public workstations by linking to their inventories, etc.). However, I feel the benefits of this approach are never used in comparison to the benefits you'd have of everyone authorised to be able to link the stockpiles for group tables.

Secondly, the issue also creates problems for stores:

![image](https://user-images.githubusercontent.com/964559/97239283-6ddbd480-17a8-11eb-8278-c2d3493b29b3.png)

if I want to add some items for sale, I'm not sure who needs to link the stockpiles, but I can have listings I added and linked that display as "sold out, yours: 60". This makes managing a shared store a problem and probably stems from the same issue.

Thirdly, there is an issue if a workbench owner can't cancel orders being done on the workbench. It's a bit related to https://github.com/StrangeLoopGames/EcoSuggestions/issues/1263 , but even for private group workbenches it can be an issue - if you want to move a workbench you have to ask everyone that has something queued to cancel it before being able to move it. This can be a problem when you have multiple people creating multiple orders (say, in a Research Table). It would be nice if the workbench owner could cancel the orders even if they are not theirs.

Number 4 - ownership. At the moment to make a proper group you need a Registrar, which requires some expensive materials and T2 room, so that puts it squarely in "stuff you do on day 3ish". While it would be nice for that to be tweaked (https://github.com/StrangeLoopGames/EcoSuggestions/issues/1056), even if you get it things don't get much easier.

It's a bit hard to make that shared group ownership a default (as per https://github.com/StrangeLoopGames/EcoSuggestions/issues/1250 ), meaning everyone has to remember to re-assign the ownership each time they place a cart, etc. A bit inconvenient, but whatever.

Even if you do have the shared ownership set up, you still can't do everything. I set up a group for my shared corporation on WT, then I changed land ownership to the group corp. Then I needed to move some claims around and it turned out I wasn't allowed to change that, even though my group was the owner, and I was both the manager of that group and a member of it. The only way to change that is to reassign ownership of the land back to me, do the change, and assign it back to the corp - not ideal.

Setting up a corp shared bank account and so on is another small issue that https://github.com/StrangeLoopGames/EcoSuggestions/issues/1056 would address.

----

So yeah, all things considered, there are a number of small problems to running a corporation that ought to be improved to really help that side of the gameplay. It would be a good QoL improvement the more dedicated ECO players would greatly benefit from, as well as something that would help new groups get into the game together.

**Comment by SlayksWood** [comment] 2020-10-27 06:43
Thank you for the report
1. You can create suggestion about it.
2. Store problem (and other craft station will be fixed too) is here #18530

3. >It would be nice if the workbench owner could cancel the orders even if they are not theirs.

You can't do it just like that, because we have public craft stations. So I'd have watched how you came, started an order on someone else's table, and the table owner immediately canceled the order, took your resources, and you also paid money for it.
We have system that owner can cancel the order after 12 hours:
![image](https://user-images.githubusercontent.com/45708377/97265399-a4146500-1837-11eb-85c5-08c50136cf83.png)
4. You created suggestion and we thought about it too.
5. Unclaiming problem here #18537

I am closing this issue as it is not a bug. For most of the points, either there is already an issue, or there are already suggestions. If I missed something, you can create a separate bug / suggestion. It looks more like a big review than a bug report.

**Closed by SlayksWood** 2020-10-27 06:43 UTC
