### ISSUE TITLE
property names with special chars can mess up webserver

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2996] opened 2017-12-04 22:35 UTC
[29:51] The '=' character, hexadecimal value 0x3D, cannot be included in a name. Line 1, position 12.

**Comment by MarjieAVolk** [comment] 2017-12-05 19:52
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/2760 - is using the web server what causes that?

**Comment by SeanAtr0n** [comment] 2017-12-05 20:05
yes, while making a law w/ conditions it looks up the property names

**Comment by MarjieAVolk** [comment] 2017-12-05 20:06
Well, that's good to know.  So is this a dupe of that then?

**Comment by MarjieAVolk** [comment] 2017-12-07 22:17
Okay closing as duplicate

**Closed by MarjieAVolk** 2017-12-07 22:17 UTC
