### ISSUE TITLE
USER ISSUE: Custom Clause

### ISSUE THREAD

**Issue by pjuskr** [StrangeLoopGames/EcoIssues#8385] opened 2018-07-07 22:19 UTC
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Go to contract and make a Custom Clause.
Add any text to the text box.
Hit enter or click outside the text box

**Expected behavior:**
The text stays and the contract can be started

**Actual behavior:**
Disconnected from the server with an exeption error
Message:Wrong number of args passed to method: set_Description
Sourse.Eco.Shared

**Comment by Deantwo** [comment] 2018-07-08 11:17
Duplicate of #8244.
Since it is closed, it should be fixed in next update, so this can likely be closed.

**Comment by MarjieAVolk** [comment] 2018-07-09 18:34
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8244.  Should be fixed in next release.

**Closed by MarjieAVolk** 2018-07-09 18:34 UTC
