### ISSUE TITLE
USER ISSUE: Missing store item

### ISSUE THREAD

**Issue by murderinspree** [StrangeLoopGames/EcoIssues#23009] opened 2022-02-26 03:21 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
search fish stew in store selling list

**Expected behavior:**
it should show fish stew

**Actual behavior:**
does not show fish stew to sell to players

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment] 2024-04-14 18:50
Hi! Thank you for taking the time to report this however the Fish Stew is only an alternative recipe and the product it outputs is Meaty Stew IE you cant search for it in the list because it doesn't exist as a unique individual item.
Will close the issue as working as intended.

**Closed by IcedForge** 2024-04-14 18:50 UTC
