### ISSUE TITLE
USER ISSUE: Inactivity caused by crafting too large quantity

### ISSUE THREAD

**Issue by DodgeEco** [StrangeLoopGames/EcoIssues#5687] opened 2018-03-08 17:17 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Crafting any object with quantity larger than 400-500

**Expected behavior:**
put the object in queue

**Actual behavior:**
logged out of server for inactivity

**Comment by MarjieAVolk** [comment] 2018-08-03 22:21
Fixed in 8.0.  This huge slowdown was caused by doing a legality check for each item all at once.  In 8.0 it will check legality for each item only as it is crafted.

**Closed by MarjieAVolk** 2018-08-03 22:21 UTC
Labels: Medium Priority
