### ISSUE TITLE
[8.1.0] Elevator issue

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#11883] opened 2019-04-05 10:56 UTC
When moving the elevator the mesh is not moving with it.

Say if you press the down button, the model goes down as expected, but you will remain in place (in air) as the mesh is not moving.

**Comment by D3nnis3n** [comment] 2019-04-05 10:59
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11870, all having the same cause.

**Closed by D3nnis3n** 2019-04-05 10:59 UTC
