### ISSUE TITLE
USER ISSUE: Successfully Fishing did not add fish into my inventory

### ISSUE THREAD

**Issue by MrBennG** [StrangeLoopGames/EcoIssues#5252] opened 2018-02-28 22:57 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Successfully reel in a fish
2. Observe that the fish is not in your quickbar or backpack
3. disconnect and reconnect to the server
4. Observe fish is now in inventory

**Expected behavior:**
After reeling in a fish it should have been added to my inventory	

**Actual behavior:**
Fish did not appear in my inventory until I disconnected and reconnect to the server

**Comment by MarjieAVolk** [comment] 2018-02-28 23:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

This should be fixed on the current staging release.

**Closed by MarjieAVolk** 2018-02-28 23:16 UTC

**Comment by MrBennG** [comment] 2018-03-01 09:28
Thanks for the prompt response!
