### ISSUE TITLE
Entering World crashes

### ISSUE THREAD

**Issue by user-na** [StrangeLoopGames/EcoIssues#11287] opened 2019-02-12 22:07 UTC
Hope this is not a duplicate, but I did not find anything comparable here.

At least since 0.8.0.1 Update I cannot join any game anymore. Updated from something like 0.6.X. when I try to join any server, everything works fine until "Entering World..". 
Then the window freezes. If I let it run a pop-up window will appear and I will get thrown back to Steam emidiatelly.  
I've already tried reinstalling and restarting the computer.

**Comment by user-na** [comment] 2019-02-13 06:11
Is there anything I can provide to help investigating?
Is there a log which might be useful?

**Comment by elfl0rd** [comment] 2019-02-13 06:24
Try mirasrael workaround from https://github.com/StrangeLoopGames/EcoIssues/issues/11125 ?
also client logs is not bad ;)

**Comment by user-na** [comment] 2019-02-13 16:22
Ok, so it somehow looks like the issue in #11125 . But I definetly get past the 90%.
Tried to run the game with the options mentioned in #11125 - no change in behavior.
I too currently have a poor onboard graphics card (Intel HD Graphics 4600 ) in use.

[Here it the output_log](https://github.com/StrangeLoopGames/EcoIssues/files/2861182/output_log.txt)

**Comment by user-na** [comment] 2019-02-13 19:24
Ok, so I updated the video card driver to the current version and installed the 8.0.0.2 update. Now it crashed at 86% of loading world.

**Comment by mirasrael** [comment] 2019-02-14 10:23
Duplicate of #11125

**Closed by mirasrael** 2019-02-14 10:23 UTC
Labels: High Priority, Investigate
