### ISSUE TITLE
[USER ISSUE] Tried to open smal cart

### ISSUE THREAD

**Issue by mcenderdragon** [StrangeLoopGames/EcoIssues#5255] opened 2018-02-28 23:42 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I digged dirt and got kicked. After I logged in again and tried to open a woodkart the server crashed. Also I noticed I sayd I was last logged in an 1h ago (wrong I got kicked a few secinds ago) and had a negative skillpoint increse (but the points were still right, only the delta got mixed up because the timeshift)

**Expected behavior:**
It should not crash...

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   bei Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   bei Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   bei Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-03-03 00:40
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4222

**Closed by MarjieAVolk** 2018-03-03 00:40 UTC
Labels: High Priority
