### ISSUE TITLE
http 500

### ISSUE THREAD

**Issue by Arranoa-jolasten** [StrangeLoopGames/EcoIssues#25071] opened 2024-08-18 19:09 UTC
![image](https://github.com/user-attachments/assets/36e04474-c9c5-4014-99dd-9f698c0f69c3)

**Comment by D3nnis3n** [comment] 2024-08-18 20:15
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25062

**Closed by D3nnis3n** 2024-08-18 20:15 UTC
