### ISSUE TITLE
Large amount of work orders create huge lag on the server and breaking it in the end 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1358] opened 2017-04-09 10:26 UTC
This causes huge lag even though there is not allot cpu usage and can break the world

**Comment by Stephenw92-git** [comment] 2017-04-09 14:18
-Carts, both carts have issues the longer into a world and the more server activity there is. anywhere up to and beyond 10 minutes waiting after interacting with a cart before you can actually move. 

-crafting, the timers become delayed to register, stopping and skipping. orders can take several minutes to register and start. orders become delayed to register missing items being added and eventually it becomes so delayed that multiple items will complete at the same time before the timer seems to pause again.

-moving items/stacks in the inventory. either between inv slot or from your inventory into another storage object becomes so delayed and bugged it takes a long time for the item to move. on more than one occasion i've moved items out of my inventory and left the area before finding out the items i took out, were still in my inventory.

all of the above seem plagued by the same bug because as time goes on and the delay becomes minutes, you'll find that the crafting feed in chat gets briefly spammed and carts start moving at exactly the same time. once a cart is moving it keeps moving like nothing is wrong until you leave it and it freezes again. crafting seems to skip time as the chat gets spammed and then pause again

**Comment by Stephenw92-git** [comment] 2017-04-11 13:27
Also noticed a small bug that seems linked with this is after moving items in my inventory or accessing a workbench, i'll walk away and my mouse pops back up on screen. switching me from movement to the interface.

**Comment by Stephenw92-git** [comment] 2017-04-12 15:55
After watching whats been happening in the server for a while longer, crafting queues have a direct impact on the running quality, if players queue large numbers of items for extended periods it immediately seems to degrade the server. when large orders are placed, the delays with interaction and cart movement become exacerbated.
Moving multiple large stacks in your inventory seems to have the same, temporary, impact and moving 3-4 stacks of wheat can be enough to cause a disconnect and "inactivity" error for the player.

**Comment by metachronism** [comment] 2017-05-12 19:16
dupe of #1346

**Closed by metachronism** 2017-05-12 19:16 UTC
Labels: High Priority
