### ISSUE TITLE
Stuck when exiting vehicle

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#8768] opened 2018-07-27 09:30 UTC
If you park vehicle (tractor in this case) with a stockyard directly on the right of the vehicle, when you exit you get stuck between the vehicle and the building, because it seems you always exit the vehicle on the right...
/unstuck would not unstuck me

**Comment by GophTheGreat** [comment] 2019-05-30 08:22
Even with a full stockpile I get placed atop it instead of stuck between the vehicle and stockpile now. Cannot reproduce, closing.

**Closed by GophTheGreat** 2019-05-30 08:22 UTC
Labels: Medium Priority
