### ISSUE TITLE
Server "Unable to Reconnect"

### ISSUE THREAD

**Issue by LipkeGu** [StrangeLoopGames/EcoIssues#9680] opened 2018-10-11 16:07 UTC
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Open a server (remote)
2. connect to it.
3. disconnect and reconnect!

**Expected behavior:**
It should be able to reconnect to the Game	

**Actual behavior:**
No response from remote Host!n
**Do you have mods installed? Does issue happen when no mods are installed?:**
No response from remote Host!

**Comment by Nicolausi113** [comment] 2018-10-11 16:51
Yes, I have experienced too, but very random, Continue does not always work! As work around, joining the server via browser or Your Worlds works.

**Comment by Nicolausi113** [comment] 2018-10-13 11:05
This problem happened once again, the loading screen did not progress and I stoke escape. An error message popped up and I copied the text, maybe it’s helpful.
I noticed in the log file: “Initialized touch support”. My machine doesn't have any touch devices ?? 

![failed connection](https://user-images.githubusercontent.com/38510829/46904622-8a6d8280-cee7-11e8-90fb-1d49c9923cab.jpg)



Log File:
Initialize engine version: 2018.2.0f2 (787658998520)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 750 (ID=0x1381)
    Vendor:   
    VRAM:     963 MB
    Driver:   23.21.13.9135
Begin MonoManager ReloadAssembly
- Completed reload, in  0.127 seconds
<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.
UnloadTime: 1.648715 ms
Client version: 0.7.7.2 beta
Tuesday, September 11, 2018 12:08 PM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

**Comment by LipkeGu** [comment] 2018-10-13 19:04
I exoerienced also when i see my Server and click "Join" it will join another Server like "timlukas" :(

**Comment by Nicolausi113** [comment] 2018-10-15 17:46
I meanwhile have a strong suspicion, that it has to do with shortening the long load sequence of Main Screen by clicking in the screen!

**Comment by SlayksWood** [comment] 2019-09-12 06:17
Still an issue in 0.9.0 master and previous version. But you can't reproduce it 100%. It happens sometimes. Low priority until we understand why it happens

**Comment by TwixterZ** [comment] 2022-12-05 05:55
Hello, @LipkeGu & @Nicolausi113 I will proceed to close this issue as multiple updates have landed for ECO since then, if you however face this issue on a recent builds, please let us know.

**Closed by TwixterZ** 2022-12-05 05:55 UTC
Labels: Priority: Low
