### ISSUE TITLE
[staging] Out of bounds in TMP from navmesh??

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#15168] opened 2020-03-17 13:25 UTC
```
IndexOutOfRangeException: Index was outside the bounds of the array.
  at TMPro.TMP_Text.FillSpriteVertexBuffers (System.Int32 i, System.Int32 index_X4) [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.OnPreRenderCanvas () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.Rebuild (UnityEngine.UI.CanvasUpdate update) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AI.NavMesh+OnNavMeshPreUpdate.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception, Object)
UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
UnityEngine.AI.OnNavMeshPreUpdate:Invoke()
```

No idea where this is coming from.

Here's another one:
```
NullReferenceException: Object reference not set to an instance of an object.
  at UnityEngine.RectTransform.get_sizeDelta () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis (System.Int32 axis, System.Boolean isVertical) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityAction`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.LayoutRebuilder.PerformLayoutControl (UnityEngine.RectTransform rect, UnityEngine.Events.UnityAction`1[T0] action) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.LayoutRebuilder.PerformLayoutControl (UnityEngine.RectTransform rect, UnityEngine.Events.UnityAction`1[T0] action) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.LayoutRebuilder.PerformLayoutControl (UnityEngine.RectTransform rect, UnityEngine.Events.UnityAction`1[T0] action) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.LayoutRebuilder.PerformLayoutControl (UnityEngine.RectTransform rect, UnityEngine.Events.UnityAction`1[T0] action) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.LayoutRebuilder.Rebuild (UnityEngine.UI.CanvasUpdate executing) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AI.NavMesh+OnNavMeshPreUpdate.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
UnityEngine.AI.OnNavMeshPreUpdate:Invoke()
```

**Comment by mirasrael** [comment] 2020-04-20 13:42
@serpopov recently updated TMPro to new version, probably this problem is gone. Since it is hard to reproduce this and seems it happens randomly I'm closing it for now. Re-open if it happen again with new TMPro version.

**Closed by mirasrael** 2020-04-20 13:42 UTC
Labels: Priority: Medium, Week Task
