### ISSUE TITLE
workorders auto-taking from campfire power supply

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2220] opened 2017-09-20 23:36 UTC
![image](https://user-images.githubusercontent.com/774628/30672530-da6fbdd6-9e21-11e7-8e03-c9fe86b97512.png)

**Comment by SeanAtr0n** [comment] 2017-09-20 23:37
Also I dropped em in there but John got credit

**Comment by MarjieAVolk** [comment] 2017-09-20 23:38
So the problem is that the linked inv settings turn power supplies on by default right?  Not that the linked inv settings were not working as advertized?

**Comment by SeanAtr0n** [comment] 2017-09-20 23:39
Seems like power supplies should be one-way

**Comment by MarjieAVolk** [comment] 2017-09-20 23:42
I was trying to ask, it's a feature request right?  Not a bug?  Like you had the power supply checked in the linked inv window?

I agree that having stuff take from power supplies is bad and we should do it less lol

**Comment by johnkslg** [comment] 2017-09-20 23:56
I checked it in the storage system yep
add-only permissions would be good

**Comment by SeanAtr0n** [comment] 2017-09-21 02:29
Maybe power supplies should be different type of linked inventory.

You will probably never want stuff taken out of fuel supplies automatically and very rarely want to craft anything directly into a fuel supply. Ideally you want fuel supplies to actively pull player specified fuel from chests/stockpiles when empty and operating. (Logs yes, boards/fences/roofs no!)

Alternatively just make them un-linkable and keep em in the list for dragging convenience.

**Comment by MarjieAVolk** [comment] 2017-09-22 20:24
Okay so there isn't actually a bug here, and this feature is potentially tied in with https://github.com/StrangeLoopGames/EcoIssues/issues/2200 so I'm moving this to beta

**Comment by MarjieAVolk** [comment] 2018-08-16 17:49
I'm actually going to close this as a duplicate of the new bug https://github.com/StrangeLoopGames/EcoIssues/issues/8977, because that one is more clear

**Closed by MarjieAVolk** 2018-08-16 17:49 UTC
Labels: Feature
