### ISSUE TITLE
Problem Icons stuck on HUD

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#2955] opened 2017-11-30 22:45 UTC
Went to repair bench took pick axe from tool belt moved repair bench icon froze on screen so i disconnected  and logged back pick axe was in repair slot but also frozen on screen tried to move repaired pick axe back to tool belt but froze on HUD Logged out AGAIN upon return pick axe was fixed and in my tool belt but also still stuck on screen NOW same thing just happened trying to fix shovel  The icons stay in view wwhere ever you go using version 6.1.2
![01b2851bc29b641d845c4e5057edcf560360e44ca9](https://user-images.githubusercontent.com/33184586/33458948-d4934d98-d5ed-11e7-8ab2-04abfaa85390.jpg)

**Comment by MarjieAVolk** [comment] 2017-11-30 22:47
:O Never seen anything like that.  Got any client error logs?

**Comment by cuda70** [comment] 2017-11-30 23:11
It never gave a error message the icons are always visible no matter where you go or what ever you are doing Even if you quit and sign back in again

**Comment by MarjieAVolk** [comment] 2017-11-30 23:12
I mean your output_log.txt file, should be in the same directory as your Eco installation.

**Comment by MarjieAVolk** [comment] 2017-11-30 23:12
Wait, quit and sign back in?  You mean leave the server, or exit the game completely?

**Comment by cuda70** [comment] 2017-11-30 23:14
leave the server

**Comment by cuda70** [comment] 2017-11-30 23:16
What is the file name you want lots of files in that folder

**Comment by cuda70** [comment] 2017-11-30 23:24
output_log.txt not in folder Eco_Data/Managed or Eco_Data/Mono or  Eco_Data/Resources these are the only folders under my Eco folder ??

**Comment by MarjieAVolk** [comment] 2017-11-30 23:28
I thought it was in Eco_Data itself.  It is different on different operating systems though I think, what OS are you on?  Might it be in C:\Users(username)\AppData\LocalLow\Strange Loop Games\ECO?

**Comment by cuda70** [comment] 2017-12-01 02:10
Thanks located it on C:
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1520172/output_log.txt)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1520173/error.log)

**Comment by MarjieAVolk** [comment] 2017-12-01 19:32
That output logs looks very short - I think it gets reset each time you run the game?  Now that you know how, could you try sharing that file again right after you experience this problem?  Thanks, sorry it's been so much work!

**Comment by brad992** [comment] 2017-12-03 16:32
I've had this before twice. Annoying but not that bad, goes away after restarting the game for me

**Comment by MarjieAVolk** [comment] 2017-12-05 19:41
@Conchipedia:
![image](https://user-images.githubusercontent.com/23460210/33627072-3c2ad98c-d9b1-11e7-8901-92c489cee0e9.png)
This has happened in previous Versions, at last managed to get a decent recording to show how its behaving (as this is almost impossible to describe) sometimes you can just get an icon like this that just sits there, disconnecting and logging back in normally does NOT solve this, totally quitting Eco will. The number 4 its moving is not always the same (cannot even remember What i was moving to suddenly get this happening)
and its not always a storage chest it an also happen in a stockpile as well and not always the top left one, it can be ANY slot

**Comment by TreeNuts** [comment] 2017-12-10 22:27
https://youtu.be/-q8hH0HdMCA

If the game looses focus everything glittched will return to their original slots but their quantity will show as if there is only 1 item. That's solved by moving the item to a new slot.

**Comment by TreeNuts** [comment] 2017-12-10 22:39
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1546149/output_log.txt)

I cleared the log file, loaded in, and got the glitch to trigger twice, and logged out (using ESC>Quit).

**Comment by MarjieAVolk** [comment] 2017-12-11 23:38
Holding an item for a long time huh?  That sounds like a good explanation for it... something you experience more because you use the game differently.  Will try it out

**Comment by TreeNuts** [comment] 2017-12-12 20:47
I usually don't hold them item for a long time. Just did it to see if it would act up :P

**Comment by MarjieAVolk** [comment] 2017-12-12 22:56
Oh sad day, I though you were just really indecisive :P

**Comment by TreeNuts** [comment] 2017-12-19 13:36
UPDATE:
I believe the issue has to do with my mouse. Specifically, that the microswitch is going out and double-left-clicking (one click on the down, one click on the release). Just tested the mouse out on another PC that runs the game fine and the problems followed it. Tried testing the issue with a working mouse by left-clicking as I dropped the item and, though hard to reproduce, I was able to get the UI to lock up. Looks like the poor mouse is going out for repairs :(   :P

@cuda70:
I suggest you try another mouse and see if that solves any issues.

**Comment by MarjieAVolk** [comment] 2017-12-28 21:52
http://ecoforum.strangeloopgames.com/topic/3088/item-split-stack-bug-6-3

"I have noticed this seems to trigger when click-dragging an icon gets interrupted (loose focus, connection hiccup at exactly wrong time, etc)"

**Comment by Conchipedia** [comment] 2018-01-04 21:26
same thing on 6.3.1 but this time threw up following error

Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveSomeItems on AuthorizationInventory!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.Inventory.GetMaxAccepted(Item item, Int32 currentQuantity)
   at Eco.Gameplay.Items.InventoryChangeSet.ModifyStack(ItemStack stack, Int32 delta, Item newItem, Boolean updateComponents)
   at Eco.Gameplay.Items.Inventory.MoveSomeItems(ItemStack sourceStack, ItemStack targetStack, Int32 quantity, Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by MarjieAVolk** [comment] 2018-01-13 01:40
That sounds like a slightly different issue, I can fix that one :P

Still no dice with this... can't repro by clicking rapidly while dragging, or by alt tabbing while dragging, or by hitting tab to hide the cursor while dragging...

**Comment by Conchipedia** [comment] 2018-01-13 18:28
i still can't work out how to reproduce it either and i see it happen occasionally and have no idea how or why it does it, if i ever do you will be the first to know

**Comment by MarjieAVolk** [comment] 2018-01-15 23:02
Funny story, I was working on new art for the toolbar, on my home computer, and suddenly I am able to repro this consistently.  Looks like unity is sending another start drag event while already dragging, which is causing this.  Soooo guess that means I can fix it now lol

**Comment by MarjieAVolk** [comment] 2018-01-15 23:08
Wait a sec, no it's because something is putting multiple Draggable scripts on it!

**Comment by MarjieAVolk** [comment] 2018-01-15 23:15
Okay this might or might not be the same issue

**Comment by cuda70** [comment] 2018-01-16 00:02
Lol i am still having this happen but not as often

**Comment by MarjieAVolk** [comment] 2018-01-16 00:06
Yeah it might be because of my computer or mouse, like @TreeNuts said about their problems.  Since I'm on a different computer today than I normally work on.  My optimistic guess is that there were things that had multiple Draggable scripts on them occasionally, and also that only affected certain people because of the order unity's events were called in.  And if that is the case... then maybe I will have fixed it.  So probably gonna close this bug via that PR ^ and you guys will have to let me know if that worked

**Closed** 2018-01-17 01:14 UTC
Labels: Medium Priority
