### ISSUE TITLE
USER ISSUE: Key to Release Cart

### ISSUE THREAD

**Issue by Skelun** [StrangeLoopGames/EcoIssues#5288] opened 2018-03-02 05:38 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Change your interaction key to whatever you want
2. Pick up the cart
3. Try to release it with your new interaction key

**Expected behavior:**
It releases

**Actual behavior:**
It doesn't release, until you press the default key [E]

**Comment by MarjieAVolk** [comment] 2018-03-02 19:03
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4412

**Closed by MarjieAVolk** 2018-03-02 19:03 UTC
