### ISSUE TITLE
USER ISSUE: Eco Blackscreen to windows 10

### ISSUE THREAD

**Issue by DayWalker1991** [StrangeLoopGames/EcoIssues#6587] opened 2018-03-28 21:05 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
hello I have the start of Eco the problem that I have a black screen in the menu because mouse cursor I see more but not I have windows 10

**Comment by MarjieAVolk** [comment] 2018-03-28 22:01
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4834

There is a suggestion there that works for some people:

> I went into Nvidia Control Panel. This is where I changed "Aspect ratio" to "No scaling" on the Adjust desktop size and position page (with "perform scaling on Display"). Suddenly everything was okay again. In DS3 I had options for resolutions. If I started up a Unity game with shift, the Select Monitor was no longer empty, but said "Display 1".
> 
> https://steamcommunity.com/discussions/forum/1/1480982971174752598/

You might want to glance over the rest of the thread there, see if anything can help you.

**Comment by SeanAtr0n** [comment] 2018-03-28 22:20
Could you send us your log file? you can paste this into file explorer to find it
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by DayWalker1991** [comment] 2018-03-28 22:55
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1858074/output_log.txt)

**Comment by SeanAtr0n** [comment] 2018-03-28 23:45
could you try right clicking eco in steam and do properties -> local files -> verify integrity of game files

and re-run to see if that fixes it?

**Comment by DayWalker1991** [comment] 2018-03-29 00:04
the problem is still there windows 10 is synonymous to the latest version

**Comment by DayWalker1991** [comment] 2018-03-29 00:06
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1858198/output_log.txt)
 
this is the version on the aktuell update

**Comment by SeanAtr0n** [comment] 2018-03-29 00:19
There seems to be a problem accessing ecostrings.csv file, maybe @Nanders knows about that?

**Comment by ShaydenMac** [comment] 2018-04-09 17:58
Received another report of this issue via email. 

"When i start Eco then i see only a black screen an hear the sounds, the problem i have since i upgraded to windows 10"

**Comment by MarjieAVolk** [comment] 2018-04-09 18:00
@ShaydenMac Sean has requested that all black screen issues be filed as separate bugs, since it can have a lot of different causes

**Comment by SeanAtr0n** [comment] 2018-04-09 18:01
another thing to check... if their brightness slider is set to 0 it makes everything black

**Comment by ShaydenMac** [comment] 2018-04-09 18:17
@SeanAtr0n If they're just starting the game, why would the slider default to 0? That is a problem in and of itself, no? 

I'll make a new bug report. :)

**Comment by Nanders** [comment] 2018-06-06 23:53
The localization tables loading thing has been fixed as of 7.5

**Closed by Nanders** 2018-06-06 23:53 UTC
Labels: High Priority
