### ISSUE TITLE
Beta 7.0.0 - Kicked due to inactivity everytime I try to interract

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3908] opened 2018-02-05 04:39 UTC
I placed a small wooden cart down on the edge of a stockpile, between two stockpiles and the game kicked me. When I logged back in there were magically two carts there, one on top of the other. Then, when I try to interract with anything with an inventory I get kicked due to being idle. Here's the DUMP

```
--BEGIN DUMP--
Dump Time
02/04/2018 20:20:03

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--

--BEGIN DUMP--
Dump Time
02/04/2018 19:54:33

Exception
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Objects.WorldObjectManager.TryPlaceWorldObject(Player player, WorldObjectItem item, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass13_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()

--END DUMP--
```

**Comment by Senlarus** [comment] 2018-02-05 04:56
Updated to 7.0.1 Beta and I am able to move around now and access inventories. I was able to pickup one of the carts with the hammer, but the "Unowned" cart cannot be picked up.

![image](https://user-images.githubusercontent.com/1503963/35788988-f23f2ffe-0a06-11e8-9c89-e622128b518b.png)

**Comment by MarjieAVolk** [comment] 2018-02-05 18:46
So are you saying your original issue was fixed by the update?

**Comment by MarjieAVolk** [comment] 2018-02-06 00:24
So I'm guessing the issue was caused by double clicking or clicking repeatedly while trying to place the cart.  If that is the case, I may have a fix

**Comment by MarjieAVolk** [comment] 2018-02-06 01:03
Fixed, will be available in next hotfix (should be released today, possibly tomorrow)

**Closed by MarjieAVolk** 2018-02-06 01:03 UTC
Labels: High Priority
