### ISSUE TITLE
 Creating a law on mint-based currency

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7142] opened 2018-04-11 20:29 UTC
Posting on behalf of someone:

Dear strangeloop team,

I just discovered your game a view days ago. I have to say it is great, we bought 5 players licenses at your store.

Now I am thinking of the laws which already start to become more and more important as we make progress in our world. I am thinking of a law to limit a minted currency.

For example:

Each player will get 1000 coins, we are 5 players makes 5000 coins. So I wanted to create a law like: 

"Prevent action: When attempting to Craft where (object is is Mint)

    condition   

        if     numeric comparison    currency    COINS    =     5000

            then     prevent

       otherwise

                allow"

My only problem here is that I can't find the object "Mint" and the currency isn't showing up in the law web page. Probably it will show up once the currency is created (I'm hoping for that :)

But still: Why is there no object named "Mint" but everything else? Is there a possible way to create a law like this or maybe through the government system? Or is the mistake that I'm thinking of it the wrong way?

I really appreciate your help here. It would improve our System a lot.

Best regards

Chris

**Comment by MarjieAVolk** [comment] 2018-04-11 20:37
If you want to send a response to them -

Hey, thanks for the suggestion.  We have already made a note to support preventing minting currency here: https://github.com/StrangeLoopGames/EcoIssues/issues/5428.  The reason Mint doesn't show up on the list is because minting currency is not technically 'crafting' in code.  When we implement this, there will be a separate 'When attempting to Mint Currency' option.  Treating this separately from crafting will also allow us to add currency specific filter options, such as filtering on the backing item or on the currency type.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5428

**Closed by MarjieAVolk** 2018-04-11 20:37 UTC
Labels: Suggestion
