### ISSUE TITLE
USER ISSUE: Can't propose a law

### ISSUE THREAD

**Issue by rvitre** [StrangeLoopGames/EcoIssues#4704] opened 2018-02-17 13:26 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Open Government Panel, Click Propose new law, try to propose any kind of law, submit.

**Expected behavior:**
created a new law proposal

**Actual behavior:**
didn't created it and showing a red error bar in the browser without message. I tried Chrome, Firefox, and multiple kind of scenarios. The Javascript console shows error 500 when submitting.

**Comment by alex-sun** [comment] 2018-02-21 19:15
Try to remove initial law.
```/clearlaws``` by admin

**Comment by rvitre** [comment] 2018-02-22 12:23
Indeed it fixes the problem, we already figure that out, but it happens again after we repeat the steps.
Also, it seems to be random and/or bound to the kind of law we configure...

Hope it'll get fixed soon, it's one the main features 👍

**Comment by MarjieAVolk** [comment] 2018-02-22 20:49
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4094

I believe in these cases, it is usually a legitimate error, except that the error message isn't being displayed to you.  Sometimes closing the page and then re-opening it from the link in game will cause the messages to be displayed again.  If that doesn't work, the most common reasons for being prevented from proposing a law are:
* The default law, as stated above (since stats are disabled right now, the default law is broken.  We will re-enabled stats in the next release)
* Law must have a unique title (deleted and failed law titles count)
* Must enter a title and/or description
* You are not currently logged in and playing the game (Right now you may need to be actually playing Eco to use the web features.  We are planning to change this.)

**Closed by MarjieAVolk** 2018-02-22 20:49 UTC
