### ISSUE TITLE
[0.9.3.4 Beta Release-226] ECO+ Server crashing with error. Message:Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#21966] opened 2021-05-23 19:44 UTC
The host have tried to rollback 30 minutes and 1 hour.
Several restart cycles did nothing, and server crashes after a while.

--BEGIN DUMP--
Dump Time
05/23/2021 11:54:27

Exception
Exception: OutOfMemoryException
Message:Array dimensions exceeded supported range.
Source:System.Private.CoreLib

System.OutOfMemoryException: Array dimensions exceeded supported range.
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, Boolean zeroingOptional)
   at System.GC.AllocateUninitializedArray[T](Int32 length)
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
   at Eco.Shared.Pools.PooledMemoryStream.ReallocateBuffer(Int32 minimumRequired)
   at Eco.Shared.Pools.PooledMemoryStream.EnsureCapacity(Int32 value)
   at Eco.Shared.Pools.PooledMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BinaryWriter.Write(String value)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.SimpleSerializer.SerializeTo(Stream stream, Object obj)
   at Eco.Core.Serialization.PersistenceManager.Persist(ContentAccessor& contentAccessor, IStorage storage)
   at Eco.Core.Serialization.PersistenceManager.ApplyChanges(ContentAccessor& contentAccessor)
   at Eco.Core.Serialization.DataStore.ContentAccessor.ExecuteAsync(ExclusiveAccess exclusiveAccess, DataStoreContentAccessorDelegate action)
   at Eco.Core.Serialization.PersistenceManager.PersistAllAsync(ExclusiveAccess exclusiveAccess, Boolean forceFlush)
   at Eco.Core.Plugins.StorageManager.SaveAndFlushAsync(ExclusiveAccess access)
   at Eco.Core.Plugins.StorageManager.SaveAndFlushAsync()
   at Eco.Server.Startup.StopAsync()
   at Eco.Server.Startup.RunAsync(IHostApplicationLifetime applicationLifetime, StartupInfo startupInfo)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
Outer Exceptions:
One or more hosted services failed to stop. (Array dimensions exceeded supported range.)

--END DUMP--

**Comment by SlayksWood** [comment] 2021-05-24 06:20
@Knigge Thank your for the report. Can you provide save file to investigate it more? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Eavrusm** [comment] 2021-05-25 08:49
[https://drive.google.com/file/d/1uSimsDLCpiJjCvwE8-beYMnSIBmKbjTc/view?usp=sharing](url)

**Comment by herniklanger** [comment] 2021-05-25 12:08
How to recunstuck

go to the thes coordinates 847, 60, 734
fill the area with dirt from North to South

**Comment by herniklanger** [comment] 2021-05-26 23:52
I have tried to delete all rows in the "py" tabel and it didn't stop the crash but it did let me put about twice as many Blocks. Which was expected since the "py" table isn't related to the placement Law. Which is the easiest way to trigger this crash.

**Comment by herniklanger** [comment] 2021-05-27 00:02
The is it passable to make a script there scrubbed the db by fx delating all entres older than 2 dayes.

**Comment by TwixterZ** [comment] 2021-06-05 07:31
Issue tested on 9.3.5 Release 231 and confirmed 

Repro steps using safe file provided :
- /tp 847,60,734
- using devtool to fill area with dirt from north till south (thank you @herniklanger)
- Observe server eventually crashing

**Comment by MishkaFur** [comment] 2021-06-05 19:14
Also getting this error on my server.

Due to the below error and text being highlighted in the console, the server did not crash until the highlighted text was unhighlighted which has caused a 2 day+ roll back

![image](https://user-images.githubusercontent.com/61889138/120902837-86fc0c00-c63a-11eb-8fe1-d67dc10c8a06.png)

**Comment by mirasrael** [comment] 2021-06-07 09:46
The issue related to chat growing too large. @Knigge in your case it happens because on every block action you have such record in chat:
![image](https://user-images.githubusercontent.com/475445/120995243-e28ade80-c78d-11eb-9f7a-b38ddb955c11.png)
In 9.4 chat storage improved and have separate file per game day. So it is less likely that you get 2GB chat file in one day.
To fix your save you can use chat command:
/chat clearhistoryolderthan 5
which will remove all chat history older than 5 days. You can adjust number of days.\
In case of @MishkaFur it is just very long server history which also may be fixed with same command. In 9.4 it should be totally non an issue.

**Comment by mirasrael** [comment] 2021-06-07 10:11
I also opened PR which makes these messages temporary and not saved in history to avoid growing chat history too fast.

**Comment by MishkaFur** [comment] 2021-06-07 14:03
> 
> 
> The issue related to chat growing too large. @Knigge in your case it happens because on every block action you have such record in chat:
> ![image](https://user-images.githubusercontent.com/475445/120995243-e28ade80-c78d-11eb-9f7a-b38ddb955c11.png)
> In 9.4 chat storage improved and have separate file per game day. So it is less likely that you get 2GB chat file in one day.
> To fix your save you can use chat command:
> /chat clearhistoryolderthan 5
> which will remove all chat history older than 5 days. You can adjust number of days.
> In case of @MishkaFur it is just very long server history which also may be fixed with same command. In 9.4 it should be totally non an issue.

I cleared my file down and server went from 14GB ram usage to 8GB, please can you check that longterm wise that it having say 50 files totally 10GB is not going to just cause insane memory usage and performance degradation, as emptying my file (2GB) dropped ram by 6GB..... so if I have 10GB of chat logs is my server going to beed an extra 30GB of ram?

**Comment by TwixterZ** [comment] 2021-06-09 08:34
Fix tested and confirmed as of 9.3.6 Release 234

This fix does not remove the existing large size chat log, this however will prevent it getting worse in the future or to repeat again.

As per misrasel, large size chat log size can be fix by clearing it using command " _/chat clearhistoryolderthan 5
which will remove all chat history older than 5 days. You can adjust number of days._ "

**Closed by TwixterZ** 2021-06-09 08:34 UTC
Labels: Category: Tech, Priority: Critical, Squad: Pumpkin, Status: Fixed, Type: Bug
