### ISSUE TITLE
Server crashing every few hours

### ISSUE THREAD

**Issue by gustafsonsean** [StrangeLoopGames/EcoIssues#6305] opened 2018-03-20 05:09 UTC
I have an active ECO server running with 15-20 people on concurrently during prime time. There is about 150 or so citizens as well.

Every 20-30 minutes the server starts disconnecting people until it eventually crashes. There are a few stack traces being generated. 

```
--BEGIN DUMP--
Dump Time
03/19/2018 23:49:22
 
Exception
System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Players.Player.SendInitialState(BSONObject obj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
--END DUMP--
```

```
--BEGIN DUMP--
Dump Time
03/19/2018 23:49:22
Exception

System.Exception: Caught exception invoking RPC PlayerInteract on Player!
Timeout. Database is locked for more than 00:01:00.
Stack:
   at LiteDB.LockService.Write()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.UsableItemUtils.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   at Eco.Gameplay.Items.ToolItem.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, Single calorieMultiplier, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   at Eco.Mods.TechTree.ShovelItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--
```

```
--BEGIN DUMP--
Dump Time
03/19/2018 23:48:59

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   at LiteDB.LockService.Read()
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Players.WelcomeMessage.<>c.<Get>b__2_4(<>f__AnonymousType15`2 <>h__TransparentIdentifier2)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Systems.Tooltip.TooltipExtensions.FoldoutList(IEnumerable`1 list, String itemNounSingular, Int32 max)
   at Eco.Gameplay.Players.WelcomeMessage.Get(Player player)
  at Eco.Gameplay.Systems.Chat.ChatManager.Eco.Shared.Networking.INetObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--
```

**Comment by neyna** [comment] 2018-03-20 05:33
Have you tried to desactivate stats? We had the same issue and fixed it removing the stats.

**Comment by gustafsonsean** [comment] 2018-03-20 13:58
for the stats.eco, my contents are:

{
  "EnableStatWrites": true,
  "EnableStatReads": true
}

Do i set both of them to false?

**Comment by MarjieAVolk** [comment] 2018-03-20 18:30
You can set both to false.  Probably just disabling writes would work.

For 7.3 we will handle database read/write failures better, and just show an error message in the server instead of crashing the whole server.  We are also trying to fix these timeout issues themselves, but we haven't gotten there yet.

The first dump you listed is https://github.com/StrangeLoopGames/EcoIssues/issues/5328, which we have not figured out yet, however.

**Comment by MarjieAVolk** [comment] 2018-03-20 18:31
Oh, and the database timeouts are duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343, thus closing this one.

**Closed by MarjieAVolk** 2018-03-20 18:30 UTC
