### ISSUE TITLE
SERVER ISSUE: Server failed to full start

### ISSUE THREAD

**Issue by ThatGuyMason** [StrangeLoopGames/EcoIssues#24657] opened 2024-01-19 23:52 UTC
The server does not make it past full start up post V10.1 update (including most recent update to V10.1.1)

All mods are updated:
NidToolbox - Full Pack,
Trade Assistant,
Tailings to Sand Clay or Dirt V0.10.0.1

I have attempted to replace my _Core_ folder from my personal game, along with my eco.settlements

Always the same error. No changes seem to create new errors. Its always this one.

Full latest log below.

```[23:42:31.228] [1] [ Info] [Eco] ]Anonymous app login.[
 
[23:42:31.675] [1] [ Info] [Eco] Eco Server 0.10.1.1 beta release-579
 
[23:42:31.675] [4] [ Info] [Eco] Starting ErrorReportingPlugin                     ...  
[23:42:31.675] [4] [ Info] [Eco] Starting PerformancePlugin                        ...  
[23:42:31.716] [4] [ Info] [Eco] Starting ProfilingPlugin                          ...  
[23:42:31.716] [4] [ Info] [Eco] Starting MaintenancePlugin                        ...  
[23:42:31.731] [4] [ Info] [Eco] Server Initialization                             ...  
[23:42:31.731] [4] [ Info] [Eco] Starting FeaturesPlugin                           ...  
[23:42:31.748] [4] [ Info] [Eco] Starting BalancePlugin                            ...  
[23:42:31.762] [4] [ Info] [Eco] Starting NetworkManager                           ...  
[23:42:31.794] [4] [ Info] [Eco] Starting DifficultySettings                       ...  
[23:42:31.824] [4] [ Info] [Eco] Starting ModKitPlugin                             ...  
[23:42:45.205] [4] [ Info] [Eco] Loading mods                                      ...  
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[23:42:45.222] [1] [ Info] [Eco] Loading TradeAssistant...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.EM.Framework...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.Core...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.ChatTags...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.CleanServer...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.Laws...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.Loggers.ChatLogger...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.Loggers.IpLogger...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.Motd...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.News...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.PlayerManager...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.Rules...
 
[23:42:45.222] [1] [ Info] [Eco] Loading Eco.Nid.TimedMessages...
 
[23:42:45.720] [1] [ Info] [Eco] [NidToolbox] Server loaded mod assemblies. Pre-init stage started. 
[23:42:45.755] [1] [ Info] [Eco] [NidToolbox] Core configuration files loaded. 
[23:42:45.755] [1] [ Info] [Eco] [NidToolbox] Managers assigned. 
[23:42:45.755] [1] [ Info] [Eco] [NidToolbox] Events assigned. 
[23:42:45.755] [1] [ Info] [Eco] [NidToolbox] Compatibility checks done. 
[23:42:46.222] [1] [ Info] [Eco] [NidToolbox] Modules configured. 
[23:42:46.222] [1] [ Info] [Eco] [NidToolbox] Pre init stage completed. 
[23:42:46.222] [4] [ Info] [Eco] Initializing Simulation Types                     ...  
[23:42:46.222] [4] [ Info] [Eco] Starting WorldGeneratorPlugin                     ...  
[23:42:46.222] [4] [ Info] [Eco] Starting BackupPlugin                             ...  
[23:42:46.222] [4] [ Info] [Eco] Starting StorageManager                           ...  
[23:42:46.346] [4] [ Info] [Eco] Initializing items                                ...  
[23:42:46.391] [8] [ Info] [Eco] [EM Framework] Checking for Recipe Overrides from the Config... 
[23:42:46.393] [8] [ Info] [Eco] [EM Framework] Checking for Recipe Overrides from Mods... 
[23:42:56.585] [4] [ Info] [Eco] Initializing skills                               ...  
[23:42:56.614] [4] [ Info] [Eco] Loading mods                                      ... Finished in 11.408 sec
 
[23:42:57.030] [4] [ Info] [Eco] Starting GameDataPlugin                           ...  
[23:42:57.030] [4] [ Info] [Eco] Loading GameData                                  ...  
[23:42:58.519] [4] [ Info] [Eco] Loading WaterCacheData                            ...  
[23:42:58.519] [4] [ Info] [Eco] Starting WorldPlugin                              ...  
[23:42:58.545] [4] [ Info] [Eco] Loading World                                     ...  
[23:43:01.158] [4] [ Info] [Eco] Converting world to new format                    ...  
[23:43:03.689] [4] [ Info] [Eco] Initializing world                                ...  
[23:43:03.759] [4] [ Info] [Eco] Caching world data                                ...  
[23:43:03.759] [4] [ Info] [Eco] Starting ControllerManager                        ...  
[23:43:03.759] [4] [ Info] [Eco] Starting UserManager                              ...  
[23:43:03.759] [4] [ Info] [Eco] Starting EcoObjectManager                         ...  
[23:43:03.759] [4] [ Info] [Eco] Starting TimePlugin                               ...  
[23:43:03.759] [4] [ Info] [Eco] Starting Stats                                    ...  
[23:43:03.759] [4] [ Info] [Eco] Loading Time                                      ...  
[23:43:03.917] [4] [ Info] [Eco] Loading Objects                                   ...  
[23:43:04.049] [4] [ Info] [Eco] Loading ViewTypeData                              ...  
[23:43:04.049] [4] [ Info] [Eco] Loading Users                                     ...  
[23:43:09.251] [4] [ Info] [Eco] Starting MinimapManager                           ...  
[23:43:09.258] [4] [ Info] [Eco] Starting EcoSim                                   ...  
[23:43:09.293] [4] [ Info] [Eco] Loading Plants                                    ...  
[23:43:09.636] [4] [ Info] [Eco] Initializing plants                               ...  
[23:43:10.040] [4] [ Info] [Eco] Starting WorldLayerManager                        ...  
[23:43:10.040] [4] [ Info] [Eco] Starting EconomyPlugin                            ...  
[23:43:10.040] [4] [ Info] [Eco] Starting UserTracker                              ...  
[23:43:10.040] [4] [ Info] [Eco] Starting PausePlugin                              ...  
[23:43:10.040] [4] [ Info] [Eco] Starting ReputationPlugin                         ...  
[23:43:10.040] [4] [ Info] [Eco] Starting PropertyManager                          ...  
[23:43:10.040] [4] [ Info] [Eco] Starting EconomyTracker                           ...  
[23:43:10.040] [4] [ Info] [Eco] Starting RouteProbingPlugin                       ...  
[23:43:10.040] [4] [ Info] [Eco] Starting CivicsPlugin                             ...  
[23:43:10.040] [4] [ Info] [Eco] Starting SettlementsPlugin                        ...  
[23:43:10.040] [4] [ Info] [Eco] Starting InitialSpawnPlugin                       ...  
[23:43:10.040] [4] [ Info] [Eco] Starting RoomPlugin                               ...  
[23:43:10.040] [4] [ Info] [Eco] Starting WorldObjectManager                       ...  
[23:43:10.040] [4] [ Info] [Eco] Starting ObjectivePlugin                          ...  
[23:43:10.050] [4] [ Info] [Eco] Starting SleepPlugin                              ...  
[23:43:10.050] [4] [ Info] [Eco] Starting SpoilagePlugin                           ...  
[23:43:10.050] [4] [ Info] [Eco] Starting HolidayPlugin                            ...  
[23:43:10.050] [4] [ Info] [Eco] Starting AreaBuffManager                          ...  
[23:43:10.050] [4] [ Info] [Eco] Starting GameActionAccumulator                    ...  
[23:43:10.050] [4] [ Info] [Eco] Starting DisasterPlugin                           ...  
[23:43:10.050] [4] [ Info] [Eco] Starting GarbagePlugin                            ...  
[23:43:10.050] [4] [ Info] [Eco] Starting MessagingServer                          ...  
[23:43:10.050] [4] [ Info] [Eco] Starting WeatherPlugin                            ...  
[23:43:10.050] [4] [ Info] [Eco] Starting PowerGridManager                         ...  
[23:43:10.050] [4] [ Info] [Eco] Starting VoiceManager                             ...  
[23:43:10.050] [4] [ Info] [Eco] Starting MemoryManager                            ...  
[23:43:10.050] [4] [ Info] [Eco] Starting DataExporter                             ...  
[23:43:10.050] [4] [ Info] [Eco] Loading EconomyManager                            ...  
[23:43:10.050] [4] [ Info] [Eco] Starting UserTexturePlugin                        ...  
[23:43:10.050] [4] [ Info] [Eco] Starting SpeciesLayeredCatchPlugin                ...  
[23:43:10.050] [4] [ Info] [Eco] Starting EnvVarManager                            ...  
[23:43:10.252] [4] [ Info] [Eco] Loading ChatManager                               ...  
[23:43:10.263] [39] [ Info] [Eco] Loaded the command processor "EMProcessCommand" from handler "EMCustomChatProcessor".
 
[23:43:10.281] [4] [ Info] [Eco] Loading Rooms                                     ...  
[23:43:10.290] [4] [ Info] [Eco] Loading Reputation                                ...  
[23:43:10.290] [4] [ Info] [Eco] Loading Garbage                                   ...  
[23:43:10.333] [4] [ Info] [Eco] Loading Holiday                                   ...  
[23:43:10.333] [4] [ Info] [Eco] Loading Property                                  ...  
[23:43:10.382] [4] [ Info] [Eco] Loading Objectives                                ...  
[23:43:10.382] [4] [ Info] [Eco] Loading Weather                                   ...  
[23:43:10.382] [4] [ Info] [Eco] Loading Pause                                     ...  
[23:43:10.382] [4] [ Info] [Eco] Loading RouteProbing                              ...  
[23:43:10.843] [4] [ Info] [Eco] Loading Sleep                                     ...  
[23:43:10.843] [4] [ Info] [Eco] Loading Disasters                                 ...  
[23:43:10.843] [4] [ Info] [Eco] Loading Layers                                    ...  
[23:43:11.054] [4] [ Info] [Eco] Loading Civics                                    ...  
[23:43:11.054] [4] [ Info] [Eco] Initializing world layers                         ...  
[23:43:11.345] [4] [ Info] [Eco] Loading Settlements                               ...  
[23:43:11.382] [4] [ Info] [Eco] Loading WorldObjects                              ...  
[23:43:12.179] [4] [ Info] [Eco] Loading LargeTextDisplayer                        ...  
[23:43:12.179] [4] [ Info] [Eco] Loading ClimateSim                                ...  
[23:43:12.179] [4] [ Info] [Eco] Loading Notifications                             ...  
[23:43:14.041] [4] [ Info] [Eco] Starting TwitchPlugin                             ...  
[23:43:14.041] [4] [ Info] [Eco] Starting RconPlugin                               ...  
[23:43:14.041] [4] [ Info] [Eco] Starting WebServerPlugin                          ...  
[23:43:14.041] [4] [ Info] [Eco] Starting LawsDirector                             ...  
[23:43:14.041] [4] [ Info] [Eco] Starting NidToolbox                               ...  
[23:43:14.041] [4] [ Info] [Eco] Starting JSONRecipeExporter                       ...  
[23:43:14.041] [4] [ Info] [Eco] Starting BasePlugin                               ...  
[23:43:14.041] [4] [ Info] [Eco] Starting GroupsHandler                            ...  
[23:43:14.050] [4] [ Info] [Eco] Starting EMFoodItemPlugin                         ...  
[23:43:14.050] [4] [ Info] [Eco] Starting EMConfigurePlugin                        ...  
[23:43:14.050] [4] [ Info] [Eco] Starting EMHousingValuePlugin                     ...  
[23:43:14.050] [4] [ Info] [Eco] Starting EMItemWeightPlugin                       ...  
[23:43:14.050] [4] [ Info] [Eco] Starting EMLinkDistancesPlugin                    ...  
[23:43:14.050] [4] [ Info] [Eco] Starting CommandGroupsManager                     ...  
[23:43:14.050] [4] [ Info] [Eco] Starting TimedMessagesDirector                    ...  
[23:43:14.050] [4] [ Info] [Eco] Starting PlayerManagerDirector                    ...  
[23:43:14.050] [4] [ Info] [Eco] Starting NewsDirector                             ...  
[23:43:14.050] [4] [ Info] [Eco] Starting MotdDirector                             ...  
[23:43:14.050] [4] [ Info] [Eco] Starting ActorsPlugin                             ...  
[23:43:14.050] [4] [ Info] [Eco] Starting CleanServerDirector                      ...  
[23:43:14.050] [4] [ Info] [Eco] Starting XMLExporter                              ...  
[23:43:14.050] [4] [ Info] [Eco] Starting GroupsManager                            ...  
[23:43:14.050] [4] [ Info] [Eco] Starting ChatTagsDirector                         ...  
[23:43:14.050] [4] [ Info] [Eco] Starting ChatLogger                               ...  
[23:43:14.050] [4] [ Info] [Eco] Starting IntegrationTestsPlugin                   ...  
[23:43:14.050] [4] [ Info] [Eco] Starting EMCustomsPlugin                          ...  
[23:43:14.050] [4] [ Info] [Eco] Starting IPLoggerDirector                         ...  
[23:43:14.050] [4] [ Info] [Eco] Starting EMStackSizesPlugin                       ...  
[23:43:14.050] [4] [ Info] [Eco] Starting EMStorageSlotsPlugin                     ...  
[23:43:14.050] [4] [ Info] [Eco] Starting EMVehiclesPlugin                         ...  
[23:43:14.050] [4] [ Info] [Eco] Starting ChatBase                                 ...  
[23:43:14.050] [4] [ Info] [Eco] Starting EMRecipesPlugin                          ...  
[23:43:14.050] [4] [ Info] [Eco] Starting SettlementDefs                           ...  
[23:43:14.050] [4] [ Info] [Eco] Starting ChatLogDirector                          ...  
[23:43:14.050] [4] [ Info] [Eco] Starting RulesDirector                            ...  
[23:43:14.050] [4] [ Info] [Eco] Starting TradeAssistantPlugin                     ...  
[23:43:14.050] [4] [ Info] [Eco] Loading TradeAssistant                            ...  
[23:43:14.169] [38] [ Info] [Eco] Removed backup - D:\TCAFiles\Users\masonw\2516676\Storage\Backup\Game-2024-01-19-23.33.20
 
[23:43:14.179] [38] [ Info] [Eco] Backup was forcefully created due to migration.
 
[23:43:14.179] [38] [Error] [Eco] ID already existed in universal id table
 
[23:43:14.179] [38] [Error] [Eco] ID already existed in universal id table
 
[23:43:14.179] [38] [Error] [Eco] ID already existed in universal id table
 
[23:43:14.234] [4] [ Info] [Eco] Initializing registrars for EconomyPlugin         ...  
[23:43:14.238] [4] [ Info] [Eco] Initializing registrars for CivicsPlugin          ...  
[23:43:14.238] [4] [ Info] [Eco] Initializing registrars for SettlementsPlugin     ...  
[23:43:14.238] [4] [ Info] [Eco] Initializing registrars for PropertyManager       ...  
[23:43:14.238] [4] [ Info] [Eco] Initializing registrars for MessagingServer       ...  
[23:43:14.238] [4] [ Info] [Eco] Loading Chat                                      ...  
[23:43:14.277] [4] [ Info] [Eco] Initializing registrars for GameDataPlugin        ...  
[23:43:14.277] [4] [ Info] [Eco] Initializing registrars for InitialSpawnPlugin    ...  
[23:43:14.289] [38] [ Warn] [Eco] 
=================================================
Migration was performed, migrations.log was saved.
=================================================
 
[23:43:14.439] [38] [Error] [Eco] Dictionary deserialization error. Missing reference for value: Eco.Core.Serialization.Internal.UniversalIdReference. It will be ignored, but may cause inconsistency and errors in other entities.
 
[23:43:14.439] [38] [Error] [Eco] Dictionary deserialization error. Missing reference for value: Eco.Core.Serialization.Internal.UniversalIdReference. It will be ignored, but may cause inconsistency and errors in other entities.
 
[23:43:14.439] [38] [Error] [Eco] Dictionary deserialization error. Missing reference for value: Eco.Core.Serialization.Internal.UniversalIdReference. It will be ignored, but may cause inconsistency and errors in other entities.
 
[23:43:16.426] [4] [ Info] [Eco] Initializing GroupsHandler                        ...  
[23:43:16.426] [4] [ Info] [Eco] Initializing DifficultySettings                   ...  
[23:43:16.426] [4] [ Info] [Eco] Initializing CivicsPlugin                         ...  
[23:43:16.426] [4] [ Info] [Eco] Initializing EconomyPlugin                        ...  
[23:43:16.426] [4] [ Info] [Eco] Initializing Stats                                ...  
[23:43:16.527] [15] [ Warn] [Eco] Can't find ecopedia link 'HomesteadSupportClaimItem' (referenced on page 'Settlements')
 
[23:43:16.673] [4] [ Info] [Eco] Initializing WorldGeneratorPlugin                 ...  
[23:43:16.673] [4] [ Info] [Eco] Initializing SettlementsPlugin                    ...  
[23:43:16.675] [4] [ Info] [Eco] Initializing LocalizationPlugin                   ...  
[23:43:16.675] [4] [ Info] [Eco] Initializing ErrorReportingPlugin                 ...  
[23:43:16.675] [4] [ Info] [Eco] Initializing PerformancePlugin                    ...  
[23:43:16.675] [4] [ Info] [Eco] Initializing ProfilingPlugin                      ...  
[23:43:16.675] [4] [ Info] [Eco] Initializing ModKitPlugin                         ...  
[23:43:16.675] [4] [ Info] [Eco] Initializing TimePlugin                           ...  
[23:43:16.675] [4] [ Info] [Eco] Initializing UserManager                          ...  
[23:43:16.675] [36] [ Info] [Eco] ===========================================================
 
[23:43:16.675] [36] [ Info] [Eco] EM Base Takes a little while to load. this is completely natural as it runs a bunch of checks on its systems, Mod Versions and more. We promise your server is still Responding
 
[23:43:16.675] [36] [ Info] [Eco] ===========================================================
 
[23:43:16.697] [4] [ Info] [Eco] Initializing ControllerManager                    ...  
[23:43:17.007] [4] [ Info] [Eco] Initializing MinimapManager                       ...  
[23:43:17.007] [4] [ Info] [Eco] Initializing EcoSim                               ...  
[23:43:17.007] [4] [ Info] [Eco] Initializing UserTracker                          ...  
[23:43:17.007] [4] [ Info] [Eco] Initializing AreaBuffManager                      ...  
[23:43:17.007] [4] [ Info] [Eco] Initializing EnvVarManager                        ...  
[23:43:17.007] [4] [ Info] [Eco] Initializing MemoryManager                        ...  
[23:43:17.007] [4] [ Info] [Eco] Initializing RoomPlugin                           ...  
[23:43:17.007] [4] [ Info] [Eco] Initializing ReputationPlugin                     ...  
[23:43:17.007] [4] [ Info] [Eco] Initializing GarbagePlugin                        ...  
[23:43:17.047] [4] [ Info] [Eco] Initializing HolidayPlugin                        ...  
[23:43:17.056] [4] [ Info] [Eco] Initializing PropertyManager                      ...  
[23:43:17.436] [4] [ Info] [Eco] Initializing WeatherPlugin                        ...  
[23:43:18.336] [4] [ Info] [Eco] Initializing SleepPlugin                          ...  
[23:43:18.409] [36] [ Info] [Eco] EM Framework - Installed Version: 3.5.1-nid 
[23:43:18.544] [27] [Error] [Eco] Moshannon County Court Claim Stake at <218, 74, 748> had no deed found when initializing.
 
[23:43:19.008] [4] [ Info] [Eco] Initializing WorldObjectManager                   ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing MessagingServer                      ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing TwitchPlugin                         ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing RconPlugin                           ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing LawsDirector                         ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing NidToolbox                           ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing PlayerManagerDirector                ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing ActorsPlugin                         ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing ChatTagsDirector                     ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing ChatLogger                           ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing SettlementDefs                       ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing ChatLogDirector                      ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing MotdDirector                         ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing CommandGroupsManager                 ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing NewsDirector                         ...  
[23:43:19.008] [4] [ Info] [Eco] Initializing BasePlugin                           ...  
[23:43:19.019] [4] [ Info] [Eco] Initializing GroupsManager                        ...  
[23:43:19.019] [4] [ Info] [Eco] Initializing IPLoggerDirector                     ...  
[23:43:20.039] [4] [ Info] [Eco] Server Initialization                             ... Finished in 48.306 sec
 
[23:43:20.039] [38] [Error] [Eco] Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.ConstitutionComponent.InitializePersistentData()
   at Eco.Gameplay.Objects.TrackPlacementComponent.Initialize()
   at Eco.Gameplay.Components.ConstitutionComponent.Initialize()
   at Eco.Gameplay.Objects.WorldObject.InitializeComponents()
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass22_0.<Initialize>b__1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)))
One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.))
One or more errors occurred. (Object reference not set to an instance of an object.)
 
[23:43:25.060] [38] [ Info] [Eco] Shutdown finished
 
[23:43:25.060] [38] [Error] [Eco] Errors report:
ID already existed in universal id table
: 204

=================================================
Migration was performed, migrations.log was saved.
=================================================
: 1
Dictionary deserialization error. Missing reference for value: Eco.Core.Serialization.Internal.UniversalIdReference. It will be ignored, but may cause inconsistency and errors in other entities.
: 138
Can't find ecopedia link 'HomesteadSupportClaimItem' (referenced on page 'Settlements'): 1
Moshannon County Court Claim Stake at <218, 74, 748> had no deed found when initializing.
: 1
Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.ConstitutionComponent.InitializePersistentData()
   at Eco.Gameplay.Objects.TrackPlacementComponent.Initialize()
   at Eco.Gameplay.Components.ConstitutionComponent.Initialize()
   at Eco.Gameplay.Objects.WorldObject.InitializeComponents()
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass22_0.<Initialize>b__1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)))
One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.))
One or more errors occurred. (Object reference not set to an instance of an object.)
: 1
 
```

**Comment by D3nnis3n** [comment] 2024-01-20 05:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24644

**Closed by D3nnis3n** 2024-01-20 05:22 UTC
