### ISSUE TITLE
Periodic Server Crashing/repeat error

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4471] opened 2018-02-13 21:25 UTC
```
--BEGIN DUMP--
Dump Time
02/13/2018 15:12:22

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
```

**Comment by MarjieAVolk** [comment] 2018-02-13 22:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368.  You can track the issue progress there.

**Closed by MarjieAVolk** 2018-02-13 22:29 UTC
Labels: High Priority
