### ISSUE TITLE
[0.9.0 staging-1357] Treasury includes removed titles

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14508] opened 2020-01-25 22:48 UTC
The list of titles that can access the Treasury includes removed titles. This only shows up when the Treasury is disabled.

![TreasuryTitles](https://user-images.githubusercontent.com/47330823/73128280-a6cceb80-3f81-11ea-8a08-8f9cccb94c17.png)

**Comment by beastyn** [comment] 2020-01-29 08:00
Something with updates
1. There were two titles with treasury access
![unknown (47)](https://user-images.githubusercontent.com/27898520/73337773-de47da80-4296-11ea-9a07-7b182c679589.png)
2. I've deleted Queen title
![bandicam 2020-01-29 12-57-54-558](https://user-images.githubusercontent.com/27898520/73337825-033c4d80-4297-11ea-8224-482efdf9ae6b.jpg)
3. But treasury looks like this anyway
![bandicam 2020-01-29 12-59-17-800](https://user-images.githubusercontent.com/27898520/73337905-2ebf3800-4297-11ea-8f50-a74e94772c66.jpg)

**Comment by johnkslg** [comment] 2020-02-07 21:52
Added an update when states change

**Comment by beastyn** [comment] 2020-02-10 10:42
Updates with tick. I think we should make some note about tick on the object then?

**Comment by johnkslg** [comment] 2020-02-12 22:44
It should happen instantly, verified this:
Do /civics spawngov
Make a title with treasury privileges
Spawn treasury
Verify it shows title on treasury
Revise title to remove priviliges
Verify title not shown on treasury

In any case lets push, low pri

**Comment by beastyn** [comment] 2020-02-18 09:33
If it should happen instantly, then this still is need to be fixed.
I've created two titles with treasury access, but they did not appear in the treasury info. 
![bandicam 2020-02-18 14-30-31-576](https://user-images.githubusercontent.com/27898520/74722997-a8759080-525b-11ea-9772-521a9c9731c8.jpg)
![bandicam 2020-02-18 14-30-42-411](https://user-images.githubusercontent.com/27898520/74723002-a9a6bd80-525b-11ea-8337-3d4f4e7809a7.jpg)
![bandicam 2020-02-18 14-30-21-757](https://user-images.githubusercontent.com/27898520/74723007-ac091780-525b-11ea-809d-ca99ad1763d4.jpg)

**Comment by WeaselDog** [comment] 2020-02-21 04:26
I am also not able to use the treasury

**Comment by johnkslg** [comment] 2020-02-24 21:42
Pushing this one

**Comment by tuha263** [comment] 2021-04-12 10:03
it works properly now
![Treasury](https://user-images.githubusercontent.com/9598614/114377584-03312080-9bb1-11eb-82d7-0400c0e81c57.png)

**Comment by IcedForge** [comment] 2021-05-17 11:39
There is a caching issue still, I can create title wait for civics tick and it will still not display the title that has permissions.
If i reconnect it displays the titles correctly. Same for removing a title, it will display in the UI until it is cleaned on client disconnect/reconnect.

**Comment by tuha263** [comment] 2021-05-28 03:39
I can't reproduce it on develop https://drive.google.com/file/d/1KcYKr8IlcNRtG_Zt-rSHtRGwMqLN7NlL/view

**Comment by Daniel-Magulado** [comment] 2021-06-02 14:45
Tested on 0.9.4 Staging-2004.

I tried to reproduce the catching issue but I am unable to do so.
I've been testing it by creating, revising, and deleting title that has access to the Treasury.
Treasury gets updated instantaneously.

Closing for now but will keep an eye on this.

**Closed by Daniel-Magulado** 2021-06-02 14:45 UTC
Labels: Category: Laws, Priority: Low, Squad: Mountain Goat, Status: Not reproduced, Status: Reopen, Type: Bug
