### ISSUE TITLE
Crash on chopping dead tree Sapling

### ISSUE THREAD

**Issue by AliveShiro** [StrangeLoopGames/EcoIssues#5783] opened 2018-03-09 16:45 UTC
I just wanted to chop a dead tree sapling and then i got kicked from the server with the following error provided:

```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object


Stack:
  at Eco.Simulation.Agents.Plant.Destroy () [0x0000c] in <c103b57ea82349f8a2dcc541b7507f85>:0 
  at Eco.Simulation.Agents.Tree.Destroy () [0x00000] in <c103b57ea82349f8a2dcc541b7507f85>:0 
  at TreeEntity.Destroy () [0x00076] in <86628401843243d5be00b6dfe5daf91c>:0 
  at TreeEntity.TryApplyDamage (Eco.Shared.Networking.INetObject damager, System.Single amount, Eco.Gameplay.Interactions.InteractionContext context) [0x0001b] in <86628401843243d5be00b6dfe5daf91c>:0 
  at Eco.Gameplay.Items.WeaponItem.OnActLeft (Eco.Gameplay.Interactions.InteractionContext context) [0x00034] in <5a6fe3953ad54612b7e68da0f55f09a8>:0 
  at Eco.Mods.TechTree.AxeItem.OnActLeft (Eco.Gameplay.Interactions.InteractionContext context) [0x0008a] in <86628401843243d5be00b6dfe5daf91c>:0 
  at Eco.Gameplay.Players.Player+<>c__DisplayClass45_0.<PlayerInteract>b__0 (Eco.Gameplay.Interactions.IInteractable inter) [0x00000] in <5a6fe3953ad54612b7e68da0f55f09a8>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions+<>c__DisplayClass0_1`1[T].<ExecuteUntilSuccess>b__1 () [0x00000] in <5a6fe3953ad54612b7e68da0f55f09a8>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess (System.Collections.Generic.IEnumerable`1[T] results) [0x00016] in <5a6fe3953ad54612b7e68da0f55f09a8>:0 
  at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, System.Func`2[T,TResult] resultFunc) [0x0001f] in <5a6fe3953ad54612b7e68da0f55f09a8>:0 
  at Eco.Gameplay.Players.Player.PlayerInteract (Eco.Shared.Items.InteractionInfo info) [0x000df] in <5a6fe3953ad54612b7e68da0f55f09a8>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <9689214c1e4645be91df75196bac3cbb>:0 



Stack:
  at Eco.Shared.Networking.RPCManager.TryInvoke (System.Object controller, System.String methodname, Eco.Shared.Serialization.BSONObject bsonArgs, System.Object& result) [0x00060] in <87b449fa3be548e4a9bca65d2ad34821>:0 
  at Eco.Shared.Networking.RPCManager.InvokeOn (Eco.Shared.Serialization.BSONObject bson, System.Object controller, System.String methodname) [0x00055] in <87b449fa3be548e4a9bca65d2ad34821>:0 
  at Eco.Shared.Networking.RPCManager.HandleReceiveRPC (Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson) [0x0003d] in <87b449fa3be548e4a9bca65d2ad34821>:0 
  at Eco.Plugins.Networking.Clients.ClientManager.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00021] in <cb46936a53a64832a4f16709d80dbff3>:0 
  at Eco.Shared.Networking.NetObject.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <87b449fa3be548e4a9bca65d2ad34821>:0 
  at Eco.Shared.Networking.NetPort.ProcessBuffer () [0x00016] in <87b449fa3be548e4a9bca65d2ad34821>:0 
  at Eco.Shared.Networking.NetPort.Update () [0x0000a] in <87b449fa3be548e4a9bca65d2ad34821>:0 
  at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0 () [0x00012] in <cb46936a53a64832a4f16709d80dbff3>:0 
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-09 21:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5619

**Closed by MarjieAVolk** 2018-03-09 21:25 UTC
