### ISSUE TITLE
USER ISSUE: Cut Tree Falling Through Ground

### ISSUE THREAD

**Issue by Agent-Industries** [StrangeLoopGames/EcoIssues#23669] opened 2023-01-13 09:59 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**
Cut down 6 trees in the same area.
Cut 2 small sections off one tree then walk away for a half hour.
Walk back and start cutting trees.

**Expected behavior:**
Logs should have sat on top of terrain, unmoving without being provoked. When chopping logs, I expect the mesh to line up with the object's hitbox.

**Actual behavior:**
A tree is repeatedly falling through the ground every couple seconds.
When cutting other trees in the area, the hitbox does not line up with the mesh.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. 
Yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10410374/Player.log)

**Comment by Agent-Industries** [comment] 2023-01-13 10:00
Running on:
Intel Core i5 10600K at 4.8GHZ
Asus Nvidia Geforce RTX 2060 12G
32GB DDR4 RAM (3200mhz I think?)

**Comment by Agent-Industries** [comment] 2023-01-13 11:05
If I'm an idiot and I have mods enabled let me know. I'm assuming I don't but only because I didn't play for a long while.

**Comment by D3nnis3n** [comment] 2023-01-13 15:37
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23647

**Closed by D3nnis3n** 2023-01-13 15:37 UTC
