### ISSUE TITLE
Server crash when admin unclaimed plot with station on it

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6013] opened 2018-03-13 22:13 UTC
--BEGIN DUMP--
Dump Time
03/13/2018 17:03:43

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at C5.IntervalHeap1.checkHandle(IPriorityQueueHandle1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap1.Replace(IPriorityQueueHandle1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Gameplay.Components.AnimalTrapComponent.LayerTick()
   at System.Action.Invoke()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerSync.Tick()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.TryTick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by craig-jong** [comment] 2018-03-19 23:32
What is a station?

**Comment by MarjieAVolk** [comment] 2018-03-20 00:51
These days the community seems to call world objects 'stations', that's what I was assuming.  But in either case, stack trace incriminates the fish trap.

**Comment by MarjieAVolk** [comment] 2018-03-20 00:54
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4860 (seems like this can happen from animals getting killed in a variety of ways).

**Closed by MarjieAVolk** 2018-03-20 00:54 UTC
Labels: Medium Priority
