### ISSUE TITLE
USER ISSUE: Chopped Tree Disappeared

### ISSUE THREAD

**Issue by Awesomepro247** [StrangeLoopGames/EcoIssues#6806] opened 2018-03-31 16:16 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Cut down an oak tree
Cut it into little pieces
Take 20 and walk away for around 100m
Put wood into stockpile
Come back to cut tree
Tree is gone

**Expected behavior:**
The tree should have stayed there.

**Actual behavior:**
The tree vanished. I lost the wood.

**Comment by MarjieAVolk** [comment] 2018-04-04 00:46
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5006

**Closed by MarjieAVolk** 2018-04-04 00:46 UTC
