### ISSUE TITLE
[0.9.2.0 beta Staging-1898]Avatar creation disconnect causes ui lock and cannot move until client restart

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20012] opened 2021-01-14 09:48 UTC
Reproduce steps
1. Join world
2. Disconnect before completing character creation (Do not press save)
3. Reconnect and save character now skybox will be missing and you cannot move.

Possible to push this onto a hotfix as a client restart fixes it, but its still a very annoying instance if you would for example lose connection when initially joining  a server or you get that 1/1000 lucky draw of crashing or somesuch on joining a server

**Comment by Daniel-Magulado** [comment] 2021-01-16 10:24
Build: 0.9.2 Staging-1901

Issue: Unable to reproduce. Appears to be fixed.

Resolution: Closing.

**Closed by Daniel-Magulado** 2021-01-16 10:24 UTC
Labels: Category: UI, Priority: High, Squad: Wild Turkey, Status: Fixed
