### ISSUE TITLE
USER ISSUE: Cart causes Black Screen

### ISSUE THREAD

**Issue by Sevidra** [StrangeLoopGames/EcoIssues#6180] opened 2018-03-17 04:43 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Haul a cart.
Cross some boundary in the terrain on a stone road.  I don't know what the boundaries are, but... something.  Long stone roads that I make tend to have one or two across the world.
Boom, black screen.  Still in the game, able to move, just ... black.  Stars, too!  
Log out and back in fixes it. 

**Expected behavior:**
Shouldn't be seeing that screen!  This error only happened once after multiple logout and back in instances to fix THAT bug.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-03-21 19:27
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4370

The borders seem to be the '0' border in both directions, and/or property borders.

**Closed by MarjieAVolk** 2018-03-21 19:27 UTC
