### ISSUE TITLE
USER ISSUE: Unplayable game

### ISSUE THREAD

**Issue by DEX47** [StrangeLoopGames/EcoIssues#11469] opened 2019-02-23 16:43 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Start the game and go to any map or create one.

**Expected behavior:**
Being able to play and see the Eco world.

**Actual behavior:**
I have a visible GUI, full sound, and controls seem to work. Unfortunately there is no world to see, only a black screen.

**Do you have mods installed? Does issue happen when no mods are installed?:**
I have a visible GUI, full sound, and controls seem to work. Unfortunately there is no world to see, only a black screen.

**Comment by D3nnis3n** [comment] 2019-02-25 12:58
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11248

**Closed by D3nnis3n** 2019-02-25 12:58 UTC

**Comment by D3nnis3n** [comment] 2019-02-25 21:04
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053
