### ISSUE TITLE
USER ISSUE: Missing textures created with pillared brick

### ISSUE THREAD

**Issue by ParadoxedHope** [StrangeLoopGames/EcoIssues#6748] opened 2018-03-30 17:50 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Place a solid cube block of brick.
2. Place either a pillar, or the first option of brick, next to the cube.

**Expected behavior:**
It should display the texture on the side of the solid cube.

**Actual behavior:**
The face of the solid cube displays no texture when looked at through the gap on a pillared brick block.

**Comment by MarjieAVolk** [comment] 2018-03-30 19:47
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4286

**Closed by MarjieAVolk** 2018-03-30 19:47 UTC
