### ISSUE TITLE
USER ISSUE: Floating Trees

### ISSUE THREAD

**Issue by Edrein** [StrangeLoopGames/EcoIssues#4321] opened 2018-02-11 14:06 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Cut a floating tree.

**Expected behavior:**
Cut the tree for wood.

**Actual behavior:**
Crashed the server.

**Comment by MarjieAVolk** [comment] 2018-02-13 03:45
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668 . You can track the issue progress there

**Closed by MarjieAVolk** 2018-02-13 03:45 UTC
