### ISSUE TITLE
USER ISSUE: 2nd attempt  picking up coal

### ISSUE THREAD

**Issue by chopperprop** [StrangeLoopGames/EcoIssues#7244] opened 2018-04-16 23:53 UTC
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
So i removed all my items from inventory except iron pick axe

**Expected behavior:**
pick up coal and put in inventory

**Actual behavior:**
Caught exception

<size=60.00%>Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.ClothingInventory.SetUpSuitCallback(User user)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.TryAddItem(Type itemType, User user)
   at Eco.Gameplay.Objects.RubbleObject`1.TryPickup(Inventory inv)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>

**Comment by metachronism** [comment] 2018-04-17 20:32
dupe of #7238

**Closed by metachronism** 2018-04-17 20:32 UTC
Labels: High Priority
