### ISSUE TITLE
USER ISSUE: cant pick up dead animal

### ISSUE THREAD

**Issue by sjeffers95** [StrangeLoopGames/EcoIssues#25026] opened 2024-08-10 07:28 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
kill any animal i cant pick it up

**Expected behavior:**
i should be able to pick up animal when i hit E

**Actual behavior:**
nothing happens, the pick up [E] thing pops up when i hover over it but i cant pick it up, E does nothing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by sjeffers95** [comment] 2024-08-10 07:30
[Player.log](https://github.com/user-attachments/files/16568830/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16568831/Player-prev.log)

**Comment by sjeffers95** [comment] 2024-08-10 07:31
When I go back to main menu and reload the animal disappears.

**Comment by D3nnis3n** [comment] 2024-08-10 16:34
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24726

**Closed by D3nnis3n** 2024-08-10 16:34 UTC
