### ISSUE TITLE
Multiple deeds with 16 plots

### ISSUE THREAD

**Issue by ThomasVV93** [StrangeLoopGames/EcoIssues#25201] opened 2024-10-14 20:31 UTC
When picking up the homestead claim stake and I put it down somewhere else, it makes a new deed with the same name as the frist one, just with an added 2. I tried to change it back to without the number, but then I get the message that the deed already exists. 

So when I hover over my character's name, I can see that I am referenced to both the deeds. When I click the first one, I can click on the edit button, it lets me put down 16 plots for that deed. Now I have to deeds with 16 plots. I can repeat this indefinitely. 

This seems to be a but, not a feature. The old deed is not deleted when picking up the claim stake. 

Anyone else seen this issue?
![20241014223043_1](https://github.com/user-attachments/assets/94bb99d7-9762-4477-84e5-a13442ff069e)

**Comment by Daniel-Magulado** [comment] 2024-10-15 11:27
Hi @ThomasVV93,

Thank you for reaching out and for submitting your bug report!

To help us investigate this further, could you kindly provide a copy of your saved file and config folder? We're currently unable to reproduce the issue on our side, and this information will assist us in resolving it more efficiently.

We appreciate your help!

**Comment by padmanek** [comment] 2024-10-15 11:43
> Hi @ThomasVV93,
> 
> Thank you for reaching out and for submitting your bug report!
> 
> To help us investigate this further, could you kindly provide a copy of your saved file and config folder? We're currently unable to reproduce the issue on our side, and this information will assist us in resolving it more efficiently.
> 
> We appreciate your help!

Its happeninig every time you pick up and place down your homestead. Surprised you can't reproduce.
You dont actually gain multiple 16 plot deeds, it's just that the old deed is not properly removed when you pick up the homestead.

steps to reproduce:

https://github.com/user-attachments/assets/0d768f0d-1af0-4682-8486-8d5301ec4998

**Comment by D3nnis3n** [comment] 2024-10-15 13:48
Then it likely is fixed by https://github.com/StrangeLoopGames/Eco/pull/14456 in staging, can you try on playtest?

**Comment by ThomasVV93** [comment] 2024-10-15 20:06
> > Hi @ThomasVV93,
> > Thank you for reaching out and for submitting your bug report!
> > To help us investigate this further, could you kindly provide a copy of your saved file and config folder? We're currently unable to reproduce the issue on our side, and this information will assist us in resolving it more efficiently.
> > We appreciate your help!
> 
> Its happeninig every time you pick up and place down your homestead. Surprised you can't reproduce. You dont actually gain multiple 16 plot deeds, it's just that the old deed is not properly removed when you pick up the homestead.
> 
> steps to reproduce:
> 
>  Eco_gVzxLTRL5T.mp4

Hi,

Glad you found the problem. Would you still need the save file and config folder?

**Comment by padmanek** [comment] 2024-10-16 23:42
> Then it likely is fixed by [StrangeLoopGames/Eco#14456](https://github.com/StrangeLoopGames/Eco/pull/14456) in staging, can you try on playtest?

It doesn't happen on playtest. Can close this ticket :)

**Closed** 2024-10-17 09:23 UTC
Labels: Status: Needs Information, Status: Not reproduced
