### ISSUE TITLE
USER ISSUE: ECO Game shutsdown incorrectly

### ISSUE THREAD

**Issue by chopperprop** [StrangeLoopGames/EcoIssues#7488] opened 2018-04-30 00:23 UTC
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Quit the game

**Expected behavior:**
Press play button in Steam Library to restart ECO

**Actual behavior:**
Says game is already running so you have to open task manager and close steam-shutdown steam bootstrap then g restart steam and go back to Library to restart game this has been the way I had to start game from beginning after pressing Quit

**Comment by ShaydenMac** [comment] 2018-05-01 19:53
Got this email:

"Hey guys,
 
just read in the new thread about Steam not recognizing that the Game is already closed,
in my case it happened after i've used the Menu that opens in the Browser, so after i've closed Eco, i also needed to close Google Chrome entirely, after that, Steam recognized that Eco wasn't running anymore.
 
Hope that helped,
~GeT~"

**Comment by ShaydenMac** [comment] 2018-05-01 19:59
Email: 

"I had this happen a few times in the past (been almost a month I think since the last one.   The last two times I saw it I was playing single player (very rare for me these days)  Did not have the server running at all.   But an Eco server process was listed on the background processes.  Now I get that you can have multiples of this BUT steam will not consider a game closed until all registered spawn processes have stopped.   When I killed that process Steam stopped saying Eco was running and I was able to relaunch.  I was guessing it was the process that ran the single-player instance.  Either way it was how I fixed the issue."

**Requested log file**

**Comment by chopperprop** [comment] 2018-05-02 00:04
It’s ok I can deal with it just handing out information
I do have two separate servers running but they are completely different IP address
And lately I am playing on Pam’s Big World using Chopperprop my system is a new alien 👽 ware pc 17 inch core i7 32 gb memory with the graphics amplifier so it’s got all the latest good stuff
I would
Like to see a MAC version of the game soon
My other account is AMX dev supporter account
Thanks and appreciate all the hard work you are doing
I have several VM machines to test with if you ever need me to

On May 1, 2018, at 2:59 PM, ShaydenMac <notifications@github.com<mailto:notifications@github.com>> wrote:


Email:

"I had this happen a few times in the past (been almost a month I think since the last one. The last two times I saw it I was playing single player (very rare for me these days) Did not have the server running at all. But an Eco server process was listed on the background processes. Now I get that you can have multiples of this BUT steam will not consider a game closed until all registered spawn processes have stopped. When I killed that process Steam stopped saying Eco was running and I was able to relaunch. I was guessing it was the process that ran the single-player instance. Either way it was how I fixed the issue."

Requested log file

**Comment by ShaydenMac** [comment] 2018-05-03 19:16
Via Email

"I would like to point out i have had this issue with multiple game it is caused when a game crashes and is forced to close via the task manager or when the games close themselves and steam then does not know the game was closed when closed using either of those methods the only fix seems to be to restart steam but as it happens with every steam game that crashes like that it has nothing to do with Eco but with steam not detecting that the game has crashed and force closed."

**Comment by ShaydenMac** [comment] 2018-05-08 01:01
Via Email

"In my experience, this is caused by opening the web view without your browser already running. Because Eco is then responsible for opening the browser, Steam sees the browser process as part of the game. Closing the browser fixes it without restarting steam, and starting the browser manually before opening the game's web view avoids the problem entirely. It's definitely a Steam-side issue"

**Comment by Nanders** [comment] 2018-06-26 16:51
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6464

**Closed by Nanders** 2018-06-26 16:51 UTC
Labels: Medium Priority
