### ISSUE TITLE
[8.0.0 Steam Beta] Registrar has no hitbox

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10368] opened 2018-12-19 16:12 UTC
The new registrar model has no hitbox - you can't open it.

**Comment by elfl0rd** [comment] 2019-01-03 06:15
Duplicate of #10456 (due to already have assignee)

**Comment by elfl0rd** [comment] 2019-01-03 06:16
(Due to already have assignee)

**Closed** 2019-01-03 20:45 UTC
Labels: High Priority
