### ISSUE TITLE
USER ISSUE: Torches do not work anymore

### ISSUE THREAD

**Issue by Bertramo1** [StrangeLoopGames/EcoIssues#6919] opened 2018-04-03 11:49 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
I have two chest torch (48+4). I can not take the torches out of the chests an also do not use the link in torch stand. I tried to break down the chests to get at the torches. This also does not work. The following message appears: Can´t modify an item stack quantity above the items max stack size.

**Expected behavior:**
I want to use the torches and I want to remove the chests as they stand in the way.

**Actual behavior:**
It does not work. I believe that the last update has to do with it. It worked before.

**Comment by MarjieAVolk** [comment] 2018-04-03 18:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6598

**Closed by MarjieAVolk** 2018-04-03 18:13 UTC
