### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by Litschi123** [StrangeLoopGames/EcoIssues#4339] opened 2018-02-11 18:18 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Connect to a server

**Expected behavior:**
Join the server

**Actual behavior:**
Won't connect to server and shows the following error message:
> Connection Failed
> Login info could not be verified. Our auth servers may be down.
> Unexpected character encountered while parsing value: <. Path ", line 0, position 0

**Comment by Litschi123** [comment] 2018-02-11 23:50
Still the same on _0.7.1.0 beta_

**Comment by MarjieAVolk** [comment] 2018-02-13 02:10
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4426

**Closed by MarjieAVolk** 2018-02-13 02:10 UTC
