### ISSUE TITLE
[9.0 Staging 1489] Ecopedia Crafted items - Signs mostly white

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15431] opened 2020-03-30 20:47 UTC
Signs are mostly white, can hover over them and see what they are and it seems to show correct info.

![image](https://user-images.githubusercontent.com/61889138/77960301-f5736a80-72cf-11ea-9efd-879a12f05770.png)

**Comment by WeaselDog** [comment] 2020-03-30 21:03
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/15139

**Closed by WeaselDog** 2020-03-30 21:03 UTC
