### ISSUE TITLE
Trade Store -- Sell 36 Sand, All 36 Sells, 4 remain in cart

### ISSUE THREAD

**Issue by jwmc80** [StrangeLoopGames/EcoIssues#22727] opened 2021-10-05 21:54 UTC
This looks like an "authorization bug" where no authorization exists

Basically what happens is when I sell goods it doesn't place them all into the store, I presume the stock pile is full or something.  So for example I sell 36sand for 3.6 currency and it sells almost all but I end up with a small balance left in my cart in this case 4.  I can sell this sand over and over what is left.  The owner of the shop is not linked to my cart, I am not authorized on any nearby stockpiles, I am not authorized on his store.  Additionally the owner is selling 18 glass, I brought 20 glass with me as a test and as soon as my cart is close enough he is then selling 38 glass.  We swapped carts thinking that was the issue.  New cart that i placed down and his store is still linked to my cart

Cart's and storages available to me at the shop
![image](https://user-images.githubusercontent.com/91993280/136107682-208a2afa-72d1-430c-98b0-f86d44a1b95f.png)

authorization for the cart's
![image](https://user-images.githubusercontent.com/91993280/136107774-cf0a5475-a1a6-4849-8a2d-146319ea755b.png)

Selling 36 sand
![image](https://user-images.githubusercontent.com/91993280/136107793-57d261a7-1190-4390-907b-6cbc23ce919d.png)

36 sand sold confirmation
![image](https://user-images.githubusercontent.com/91993280/136107820-9cb80e12-8b4c-46ad-9370-af5afae642fb.png)

4 sand remaining after I sold ALL my sand
![image](https://user-images.githubusercontent.com/91993280/136107849-85745916-5fe3-47a6-9e95-bd17a7563ddc.png)

0.9.4.3
![image](https://user-images.githubusercontent.com/91993280/136107867-45a093c1-44b1-45c4-9498-d00b0b961723.png)

slg191217

**Comment by D3nnis3n** [comment] 2022-07-18 10:11
Closing issue due to old age and not being able to reproduce. If it reappears, please feel free to create a new issue :)

**Closed by D3nnis3n** 2022-07-18 10:11 UTC
Labels: Status: Needs Information
