### ISSUE TITLE
USER ISSUE: crash on pick up log

### ISSUE THREAD

**Issue by acmcpheron02** [StrangeLoopGames/EcoIssues#6756] opened 2018-03-30 19:13 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
I think I just tried to pick up a log with e? Maybe it was right click? Maybe both at the same time? It all happened so fast...

**Expected behavior:**
get a log

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment] 2018-03-30 19:29
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5595

Looks like we have a potential fix for this... so it might be fixed in the next hotfix.  There is some contention over whether it's a real fix though so... fingers crossed

**Closed by MarjieAVolk** 2018-03-30 19:29 UTC
