### ISSUE TITLE
USER ISSUE: Glitched trees

### ISSUE THREAD

**Issue by TimothyCobussen** [StrangeLoopGames/EcoIssues#23651] opened 2023-01-01 13:36 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**
1. Chop down a tree
2. chop it into pieces (doesnt matter where)

NOTE: it doesn't happen for every tree, only very occasionally

**Expected behavior:**
been chopped up in proper sized pieces which you can pick up.

**Actual behavior:**
sometimes only shows half of the texture. sometimes misplaces the hitbox, so you need to hover over the ground in order to pick up the piece that is laying several meters further

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I do not have mods installed or enabled

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![Eco_oG8cspbpqG](https://user-images.githubusercontent.com/36793977/210172431-ce3bd6f6-ad25-4788-a685-08dca561f9ce.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10328853/Player.log)

**Comment by D3nnis3n** [comment] 2023-01-01 15:36
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23647

**Closed by D3nnis3n** 2023-01-01 15:36 UTC

**Comment by TimothyCobussen** [comment] 2023-01-01 15:43
I didn't check for other reports, but mine also includes the texture not working, is that one also somewhere? or is that part of the collision box as well? (which i dont assume it to be)

**Comment by D3nnis3n** [comment] 2023-01-01 15:44
That's related.
