### ISSUE TITLE
USER ISSUE: Dude where's my car?

### ISSUE THREAD

**Issue by Tzava** [StrangeLoopGames/EcoIssues#11209] opened 2019-02-09 08:29 UTC
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
My associate and I have worked very hard to craft the first 2 steam trucks on the server. But for some reason, our steam trucks have disappeared for no good reason, and we believe it's due to them being in the proximity of each other. Also, we are aware the steam trucks are where we left them because we can access their storage through our steam tractor. It's just that we can't see or drive them. Please help! Thank you!

**Expected behavior:**
Steam Trucks should not disappear.

**Actual behavior:**
Steam Trucks have in fact disappeared.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods. I'm not hosting the server, but I'm pretty sure there are none.

**Comment by elfl0rd** [comment] 2019-02-09 08:36
Duplicate of #11108

**Closed by elfl0rd** 2019-02-09 08:36 UTC

**Comment by elfl0rd** [comment] 2019-02-09 08:37
(this appear back after relogin (not at all time) and after server restart (100%))
fix provided, as i know - included in 8.1 hotfix

**Comment by Tzava** [comment] 2019-02-09 09:03
> 
> 
> (this appear back after relogin (not at all time) and after server restart (100%))
> fix provided, as i know - included in 8.1 hotfix

8.1 hotfix?! Please tell me more
