### ISSUE TITLE
[0.8.1.3] Map loading

### ISSUE THREAD

**Issue by faiith** [StrangeLoopGames/EcoIssues#12053] opened 2019-04-17 14:12 UTC
Version: 0.8.1.3
Mods: None
Localization: German
Map-Size: 100x100
Players: 6

If  we're using Vehicles to move, loading of map-chunks is too slow. Very often we have to stop and wait until the map has been reloaded, otherwise we would fall through the floor. This clearly limits the usefulness of the vehicles, because the bottom line is that I'm faster on foot than with the vehicle, because then I have fewer problems with the reload. Any chance to improve map-loading?

Video: https://www.youtube.com/watch?v=WCNkbKI7e2Y&feature=youtu.be

**Comment by D3nnis3n** [comment] 2019-04-18 00:00
Could you tell the specs of the host computer?

**Comment by faiith** [comment] 2019-04-18 05:55
Dedicated Server-Specs:
![eco_host_specs](https://user-images.githubusercontent.com/40213281/56339523-ec68b680-61ae-11e9-9ad2-05f6b94773dc.png)
Storage: SSD-Raid

If you need more information, i'll provide them, just tell me what you need to know :)

**Comment by faiith** [comment] 2019-04-18 09:27
I tried our world on a different Server-Host (killservers.com, don't know their server specs for eco) to verify if it's related to our own dedicated machine, but the issue remains.

Server-Save: https://drive.google.com/file/d/10ybPpEC2H5SnEhElEKh3ozqm7rvXn7Hl/view?usp=sharing
Output_log.txt: [output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3093675/output_log.txt)

**Comment by ky0uraku** [comment] 2019-04-20 20:37
Same thing outside of vehicle since 8.1.2 or 8.1.3 - chunks loading too slow.
https://mmozg.net/uploads/images/00/08/54/2019/04/16/d8a3d1_origin.png

**Comment by seccombew** [comment] 2019-04-25 22:19
@D3nnis3n could you gather more info please and add it to this issue?

**Comment by seccombew** [comment] 2019-04-25 22:20
Also needs reproduction steps.

**Comment by SeanAtr0n** [comment] 2019-04-25 22:23
repro is basically
/spawnroad 200
/give truck
/give gasoline
drive on the road

**Comment by D3nnis3n** [comment] 2019-04-25 22:40
That's correct.

Sean Ater <notifications@github.com> schrieb am Fr., 26. Apr. 2019, 00:23:

**Comment by D3nnis3n** [comment] 2019-04-25 23:04
Chunk Loading since 8.0 is slow in general, there were no issues driving a truck at full speed before. Afaik Meta is already working on that and the Unity 2019.1 upgrade should also bring improvements as he said. What the cause for this issue is, i can't say. CPU and RAM usage seem fine and it often seems server related, as all people have it, not only some - some have it worse like running through unloaded chunks.

It's not an issue that requires reproduction, though, as it is prevalent on any server out there.

**Comment by johnkslg** [comment] 2019-04-30 23:37
Could make it dependent on velocity?

**Comment by johnkslg** [comment] 2019-04-30 23:38
Crap frame rates will exacerbate the problem

**Comment by johnkslg** [comment] 2019-04-30 23:41
Can also increase chunks loaded per frame when the user is getting closer to the empty chunks

**Comment by Sekor2600** [comment] 2019-05-01 17:54
Yes Chunks are slow since 8.0. You can at most take dirtroads and wooden carts without fear of falling off the map. It will be dangerous on stone roads and Aspahltroads

**Comment by mirasrael** [comment] 2019-05-17 09:23
Have improvements for my local testing: https://youtu.be/lZPUbuTrMxI
Should work better at least on powerful machines.

**Comment by D3nnis3n** [comment] 2019-05-17 16:15
Did you notice all the freezes in that video? Whats the cause for them?

**Comment by mirasrael** [comment] 2019-05-17 16:21
Because I'm running in Unity Editor. Also I found FPS spikes for WaitForGround (fixed in another PR).

**Comment by beastyn** [comment] 2019-05-18 10:58
That how it is. Comparison for Den's cycle-7 in 0.8.1.4 and .0.8.2  staging-10
https://drive.google.com/file/d/11Vn2kJ46cEiqokutjznVjchus30CIVVf/view?usp=sharing

@mirasrael let me hug you

**Comment by D3nnis3n** [comment] 2019-05-18 13:27
Closing, that improvement is great!

**Closed by D3nnis3n** 2019-05-18 13:27 UTC
Labels: Fixed, High Priority
