### ISSUE TITLE
[0.9.3.5] Power grids sometimes disconnect after a server restart

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#22271] opened 2021-06-16 08:28 UTC
We built a big power network on White Tiger and after a server restart it split into a few smaller networks. Some people say it's due to Transmission Poles being a bit iffy at maximum range, or it could be that we used some wood ceiling lamps to light up the city and pass power along. One way or the other, ideally the server would behave the same as you're placing a power pole down as it does after a reset.

**Comment by IcedForge** [comment] 2021-06-17 09:04
Thank you for your report, willl close as duplicate of #19635

**Closed by IcedForge** 2021-06-17 09:04 UTC
