### ISSUE TITLE
Cooking Menu has mixed up Product Names

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12132] opened 2019-04-29 19:01 UTC
(v0.8.1.4)
Projects from Cast Iron Stove get another name and icon as supposed – this is what I figured out:

Exotic Salad  => Basic Salad
Forest Salad         “
Grassland Salad   “
Mixed Salad         “
Rainforest Salad   “

Exotic Fruit Salad  => Fruit Salad
Mixed Fruit Salad         “
Rainforest Fruit Salad   “

Mixed Vegetable Medley  => Vegetable Medley
Mushroom Medley                   “

Only 3 Products are crafted from all that stuff – I’ve seen this in a former version maybe v7.8

![salat1](https://user-images.githubusercontent.com/38510829/56919815-d8338c00-6ac1-11e9-8c9c-865214e7c2d0.jpg)
![salat2](https://user-images.githubusercontent.com/38510829/56919836-e681a800-6ac1-11e9-90cd-56431ac01382.jpg)

**Comment by SlayksWood** [comment] 2019-04-30 06:11
@Nicolausi113 
I don't quite understand what you mean.
We have 5 recipes for Basic Salad: Exotic Salad Recipe, Forest Salad Recipe, Grassland Salad Recipe, Mixed Salad Recipe, Rainforest Salad Recipe.
We have 3 recipes for Fruit Salad: Exotic Fruit Salad Recipe, Mixed Fruit Salad Recipe, Rainforest Fruit Salad Recipe.
We also have 3 recipes for Vegetable Medley: Exotic Vegetable Medley Recipe, Mixed Vegetable Medley Recipe, Mushroom Medley Recipe.
I checked and everything is shown correctly. Can you clarify what is wrong.
Did it embarrass you that there are several different recipes for one item?

**Comment by Nicolausi113** [comment] 2019-04-30 06:53
For me it is misleading and disturbing, it breaks the logic of the crafting system!
If the goal is to have different recipes all leading to one product, I would propose give them all the same project name in the left side and showing the different ingredients at the right side. This would mean, there were 5 projects Basic Salad each with different ingredients.
My expectation is to get what I order.

**Comment by D3nnis3n** [comment] 2019-04-30 09:37
Oh, yes, this is actually working as intended, therefore closing this out.

**Closed by D3nnis3n** 2019-04-30 09:37 UTC
Labels: Medium Priority, QA
