### ISSUE TITLE
SUGGESTION: Saving of Worlds

### ISSUE THREAD

**Issue by SeppDE** [StrangeLoopGames/EcoIssues#5781] opened 2018-03-09 16:40 UTC
Hey there,

how about let the different worlds use their own file in \storage to keep different config files separated?
So that each new world will generate a new set of configs inside the world folder
For Example:

Eco\Eco_Data\Server\Storage\World1\World1.eco | World1.db | \config\
Eco\Eco_Data\Server\Storage\World 2\World2.eco World2.db | \config\

Feel free to ask for additional informations.

**Comment by MarjieAVolk** [comment] 2018-03-09 21:28
Yes, I want to do this.  Closing as partial duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3977, https://github.com/StrangeLoopGames/EcoIssues/issues/3557, and https://github.com/StrangeLoopGames/EcoIssues/issues/3768

**Closed by MarjieAVolk** 2018-03-09 21:28 UTC
