### ISSUE TITLE
USER ISSUE: Stock Piles are Eating Resources

### ISSUE THREAD

**Issue by Spoonfed** [StrangeLoopGames/EcoIssues#5895] opened 2018-03-11 13:37 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Move stuff around in stock piles eventually it will happen. I had a 22 stone. 1 stone in 1 stockpile and a stack of 20 and a stack of 1 in another. Move the 20 ffrom one to the other and now I have 2 stone.

**Expected behavior:**
It should have moved the 20 from one to the other.

**Actual behavior:**
It disappeared. No notification it fed a work table. Nothing being crafted. Just gone.

**Comment by MarjieAVolk** [comment] 2018-04-04 22:45
"Kiwa: remembered one other major glitch that frequently occured on that first map: when moving items between different stockpiles in quick succession (not chests, only stockpiles), the game would frequently lose stacks - they'ld simply disappear. not sure whether that was fixed in newer versions, I don't think I've heard complaints about that (though most people also don't move as many things, or move them slower)
[3:41:35 PM] Kiwa: iirc, stockpiles <-> carts also was affected sometimes, but mostly stockpile<->stockpile"

https://steamcommunity.com/profiles/76561198014737314/recommended/382310/

**Comment by metachronism** [comment] 2018-06-18 19:02
closing this as a dupe of #5090

still devising a solution

**Closed by metachronism** 2018-06-18 19:02 UTC
Labels: High Priority, Steam Report
