### ISSUE TITLE
USER ISSUE: currency report need scrolling and resizing enabled!

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8437] opened 2018-07-11 23:48 UTC
**Version:** 0.7.5.1 beta

If you have lot of players with currency you see this.
![20180712013435_1](https://user-images.githubusercontent.com/4980243/42604964-15044b30-857e-11e8-9fc8-1f59b0cebcae.jpg)

**Comment by MarjieAVolk** [comment] 2018-07-12 18:22
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6056

**Closed by MarjieAVolk** 2018-07-12 18:22 UTC
Labels: Medium Priority
