### ISSUE TITLE
Invisible cactus inside stone ramp

### ISSUE THREAD

**Issue by swi-da** [StrangeLoopGames/EcoIssues#23450] opened 2022-09-13 16:39 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.6.1 beta release-337

**Steps to Reproduce:**
1. Chop down cactus before creating the ramp.
2. Place ramp where the cactus was.
3. Try to walk or drive where the cactus was.

**Expected behavior:**
No cactus present anymore since it was chopped down.

**Actual behavior:**
Invisible cactus still present which prevents you from driving on the ramp. Cactus can be identified if you find the exact spot where the green dot for chopping appears.
Issue persists after multiple server restarts, removing the ramp, removing several blocks of ground below it, trying to chop it.
I have a screenshot and game saves available if that helps for debugging.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9559036/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9559037/Player.log)

**Comment by swi-da** [comment] 2022-09-13 16:40
[20220913181751_1.zip](https://github.com/StrangeLoopGames/EcoIssues/files/9559060/20220913181751_1.zip)
Screenshot of the issue.

**Comment by Ry4ndrew** [comment] 2022-09-20 11:54
Hello @swi-da

Thank you for submitting this bug report, but we're unable to reproduce this on our end.

Do you mind sharing your save file of this world with the issue? It'll help us investigate this issue further. 

Looking forward to your response. Thanks.

**Comment by Ry4ndrew** [comment] 2022-09-21 04:58
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/8cb316f5-5c0d-4fe4-aa5b-649cd1761a38)

The issue seems to be unreproducible as of 9.6.3-release-343 in any new world I've created. I'll be closing this as of now, but do open/reopen the issue if it does happen again in the future.

Thanks.

**Closed by Ry4ndrew** 2022-09-21 04:58 UTC
Labels: Status: Needs Information

**Comment by mov51** [comment] 2022-11-08 01:40
Having this issue too. I can't find any roots though. I'm not sure if I ever cut down a cactus here, it's a new road that I'm build out in this direction. Other than the lack of roots the issue is exactly the same. I can target the cactus and it blocks movement through the area. I haven't been able to find a way to remove it. 

I think the issue I mentioned above is having the same problem too. 
![image](https://user-images.githubusercontent.com/16448318/200452919-3161abd7-d9f0-4814-95e7-44c9253e7f20.png)
