### ISSUE TITLE
USER ISSUE: Log cutting bug

### ISSUE THREAD

**Issue by herp21** [StrangeLoopGames/EcoIssues#4933] opened 2018-02-22 04:57 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Was cutting a tree found on the ground randomly with a stone axe low on calerioes and i got the included error at seemingly random

**Expected behavior:**
Chopped the log into a piece that was carry able

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-22 19:54
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-22 19:54 UTC
