### ISSUE TITLE
USER ISSUE: Server list disapear

### ISSUE THREAD

**Issue by bonwilliam** [StrangeLoopGames/EcoIssues#5884] opened 2018-03-11 07:57 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Click on "Join" to display server list
2. Press ESC to return to menu (no need to wait end of the refresh of all server)
3. Click again on "Join"

**Expected behavior:**
The servers list is displayed

**Actual behavior:**
No server displayed, even after clicking on refresh. Also reproduced after a "Connection error" after trying to connect to a server

**Comment by MarjieAVolk** [comment] 2018-03-13 19:40
After seeing this problem, could you attach your log file? 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

Might be related to https://github.com/StrangeLoopGames/EcoIssues/issues/5292, https://github.com/StrangeLoopGames/EcoIssues/issues/5405, https://github.com/StrangeLoopGames/EcoIssues/issues/4696, or https://github.com/StrangeLoopGames/EcoIssues/issues/4689

**Comment by bonwilliam** [comment] 2018-03-14 06:55
Here is the log,
For this one, I went multiple time in server list, the first time is ok, the next time, servers are not showing. I tried also a refresh with same result
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1809945/output_log.txt)

**Comment by MarjieAVolk** [comment] 2018-03-14 23:31
Okay, it sounds like what you are seeing is https://github.com/StrangeLoopGames/EcoIssues/issues/5292, so closing as a duplicate of that.

Unfortunately I don't really know what the problem is - as I said there, my best guess is that your network can't handle making a whole bunch of server requests at once, so they all time out.

**Closed by MarjieAVolk** 2018-03-14 23:31 UTC
