### ISSUE TITLE
USER ISSUE: Gras to dirt bug

### ISSUE THREAD

**Issue by DubsTheFox** [StrangeLoopGames/EcoIssues#6133] opened 2018-03-16 07:40 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1.Dig a tunnel
2.walk threw the tunnel a couple times and you'll notice that the grass
above you will turn into dirt.
![zeh bug i faund](https://user-images.githubusercontent.com/37247290/37508958-a1ede726-28f5-11e8-9ea3-9fa00bbf94c4.gif)

**Comment by MarjieAVolk** [comment] 2018-03-20 22:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5101

**Closed by MarjieAVolk** 2018-03-20 22:25 UTC
