### ISSUE TITLE
Chat window show old temp notices for a moment when you open it 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16328] opened 2020-05-15 17:05 UTC
![animx22](https://user-images.githubusercontent.com/3536496/82077000-80979c80-9693-11ea-9455-ebdb5df16b18.gif)

**Comment by SlayksWood** [comment] 2020-05-18 04:52
I can't reproduce it in staging-1553

**Comment by gzatravkin** [comment] 2020-05-23 03:25
Reproduced 
(Open chat, create error message, wait for message desappear, reopen chat).

Should be fixed in fixes #6137

**Closed** 2020-05-26 06:07 UTC
Labels: Fix Version: 0.9.0.0, Priority: Low, Status: Fixed, Week Task
