### ISSUE TITLE
Hollow Stockpile

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5724] opened 2018-03-08 22:31 UTC
http://steamcommunity.com/sharedfiles/filedetails/?id=1324601612

As seen on the screenshot, one of my stockpiles displays as being hollow although it's full

**Comment by Ministrator03** [comment] 2018-03-08 23:23
Same here!

![](https://puu.sh/zDxG3/03eb1243d5.jpg)

**Comment by MarjieAVolk** [comment] 2018-03-08 23:55
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4616

**Closed by MarjieAVolk** 2018-03-08 23:55 UTC
