### ISSUE TITLE
Floating placed objects

### ISSUE THREAD

**Issue by The-Father** [StrangeLoopGames/EcoIssues#11175] opened 2019-02-08 14:10 UTC
I have built a house in-game, but it appears that the game has made another one with no collision, and is floating.

![20190208080616_1](https://user-images.githubusercontent.com/47452513/52483165-dae4ac00-2b78-11e9-963b-5b60b3a824b9.jpg)

**Comment by D3nnis3n** [comment] 2019-02-17 10:23
Can you upload your game.eco from your /Storage/ folder to dropbox so we can take a look at this? Also tell us the coordinates, where this is.

**Comment by SlayksWood** [comment] 2019-06-25 06:55
Closing for now due to not being reproducable and no further information available. If it happens again, please reopen and provide log file and save files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Closed by SlayksWood** 2019-06-25 06:55 UTC
Labels: Investigate, Needs Information

**Comment by D3nnis3n** [comment] 2019-06-25 06:58
We actually have such reports every now and then, i also had that lately when i had a lot of black chunks between normal chunks. I assume this is an issue with memory overflow.

**Comment by SlayksWood** [comment] 2019-06-25 07:01
@D3nnis3n 
He has a loaded chunk. I sometimes have that chunk doesn't want to load. But it looks a bit different. There is some other problem.

**Comment by D3nnis3n** [comment] 2019-06-25 07:02
I know, but i tend to get this problem when i have cluttered chunks in the near, then i see floating objects that exist, but somewhere else. Probably i'm only hallucinating ;P
