### ISSUE TITLE
USER ISSUE: repair station bug with road building tool

### ISSUE THREAD

**Issue by Baldwolf63** [StrangeLoopGames/EcoIssues#3575] opened 2018-01-22 02:27 UTC
**Version:** 0.6.4.1 alpha

**Steps to Reproduce:**
1. have stone in carry slot
2. place road building tool in repair station	

**Expected behavior:**
generated required amount of stone to repair tool.

**Actual behavior:**
bumped me out of game (3 attempts)

**Comment by Baldwolf63** [comment] 2018-01-22 02:27
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on ToolbarInventory!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Skills.RequiresSkillAttribute.get_Description()
   at Eco.Gameplay.Components.RepairComponent.RepairSlotChanged(User user)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by Huntermeign** [comment] 2018-01-22 02:58
Repeat of #3555

**Comment by MarjieAVolk** [comment] 2018-01-22 19:10
Duplicate of #3555 / #3485 as stated above

Will be fixed in next staging build for sure, we're talking about whether to hotfix the current release.

**Closed by MarjieAVolk** 2018-01-22 19:10 UTC
