### ISSUE TITLE
Fertilizer types all lost their icons (In Release but not master)

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6682] opened 2018-03-29 18:16 UTC
see titel, minor but noticed it

pulp filler and Phosphate until now

**Comment by keegan-o** [comment] 2018-03-30 00:44
Something happened when fertilizers were moved from tools to items to cause them to loose their icons...

**Comment by styles784** [comment] 2018-03-30 03:49
This sounds like the same issue I reported: https://github.com/StrangeLoopGames/EcoIssues/issues/6709
(it wasn't showing up in the search results when I made my report, although this report appears to be a few hours older than mine)

More important than the icons, though, are the nutrient stats - all fertilizers now show 0.3 across the board

**Comment by MarjieAVolk** [comment] 2018-04-03 23:57
Okay, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6709, thanks

**Closed by MarjieAVolk** 2018-04-03 23:57 UTC
Labels: Medium Priority

**Comment by Mega1981** [comment] 2018-04-16 07:00
it seems to me like the same with the job menu at hunting
![20180416085340_1](https://user-images.githubusercontent.com/38418743/38794181-7ed83e90-4154-11e8-9586-9a41cbd813bf.jpg)
![20180416085405_1](https://user-images.githubusercontent.com/38418743/38794193-8676aca4-4154-11e8-8d45-01dee3669447.jpg)
