### ISSUE TITLE
USER ISSUE: Horrible Holes in water Bug, Unable to fix

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8975] opened 2018-08-15 20:46 UTC
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
place Blocks down at waterlevel then remove them

**Expected behavior:**
water will not leave a hole

**Actual behavior:**
leaves a hole as shown below
![snap2398](https://user-images.githubusercontent.com/29383891/44172213-60a90280-a0d4-11e8-9490-611a39636244.png)

![snap2399](https://user-images.githubusercontent.com/29383891/44172170-4838e800-a0d4-11e8-8483-5afe98f1af27.png)
this is very annoying when making Roads across water, because if you accidently make a mistake there is no way of correcting this (i don't think even an Admin can fix these by placing a waterblock)

**Comment by D3nnis3n** [comment] 2018-12-05 20:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7749

**Closed by D3nnis3n** 2018-12-05 20:43 UTC
Labels: Low Priority
