### ISSUE TITLE
Pipes giving out smoke when nothing is being crafted or connected to any other table #0.6.0.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2461] opened 2017-10-04 19:57 UTC
just made my Blast Furnace and put Coal into power slot ready for when anotehr player can set up it is not crafting anything and is generating smoke and output in pipes as seen by these two snapshots
![snap063](https://user-images.githubusercontent.com/29383891/31196609-4aaf7fbc-a946-11e7-9b02-025250c5fa91.png)
this one shows NO crafting
![snap064](https://user-images.githubusercontent.com/29383891/31196636-5aa57eee-a946-11e7-9b78-3b6237bbb62b.png)
this one shows output in pipes and was getting loads of smoke.

i now connectedand disconnected a pipe (still smoke and output) ONLY way i have found to stop the smoke is to break the room

**Comment by Fank** [comment] 2017-10-04 19:58
Duplicate of #2410

**Comment by Conchipedia** [comment] 2017-10-04 19:58
![snap065](https://user-images.githubusercontent.com/29383891/31196742-bcf907fa-a946-11e7-94bd-1e730a5547e7.png)
showing no crafting and smoke pouring out

**Comment by Conchipedia** [comment] 2017-10-04 19:59
thanks i searched pipes and didn;t see the duplicate

**Comment by MarjieAVolk** [comment] 2017-10-04 20:37
Thanks, closing as duplicate

**Closed by MarjieAVolk** 2017-10-04 20:37 UTC
