### ISSUE TITLE
Small Wood Sign very shiny Giving real-time relection 6.0.3

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2827] opened 2017-11-15 19:50 UTC
this is the view of my Castle Entrance (as seen from the signs view)
![snap161](https://user-images.githubusercontent.com/29383891/32856862-f66120c8-ca3d-11e7-961a-ddd64bc17237.png)
The next two show how the Reflection is trying to update the view of the trees in realtime
![snap159](https://user-images.githubusercontent.com/29383891/32856896-12ddeccc-ca3e-11e7-8f74-1d61678797b1.png)
![snap160](https://user-images.githubusercontent.com/29383891/32856917-1e840dcc-ca3e-11e7-95da-78390e4e44cc.png)

not sure how this will effect the server lag.

**Comment by metachronism** [comment] 2017-11-15 19:55
dupe of #2609, but I'll close mine instead since you added more info

**Comment by metachronism** [comment] 2017-11-15 19:55
actually keegan fixed it

**Closed by metachronism** 2017-11-15 19:55 UTC

**Comment by Conchipedia** [comment] 2017-11-15 19:57
while you are seeing this @metachronism would this actually effect the lag with it drawing in realtime??
