### ISSUE TITLE
9.3 1966 - District map shows 0 plots

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21134] opened 2021-03-28 16:15 UTC
Zoning map which has plenty of plots shows as 0 plots.

Have restarted client, also /civics ticknow incase it takes a while to update.

District has around 2k plots in it.

![image](https://user-images.githubusercontent.com/61889138/112759063-3ab4a000-8fe9-11eb-98f9-5fe7ede85b3d.png)

**Comment by TwixterZ** [comment] 2021-03-29 08:33
@MishkaFur

this function seems to be working correctly. could use more information for us to reproduce

from zoning table
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/784deda3-c080-4eb6-98ed-d7a05765545e)

from map layer
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/8737c515-56b7-41c0-80c4-d316b70a4bb3)

**Comment by MishkaFur** [comment] 2021-03-29 09:22
I made a district map, gave it a load of plots, hit submit, waited for civics tick/did civics ticknow shows 0 plots, reloaded game still 0 plots

I just rebooted the server and the plots are now being counted so appears it might be something only calculated upon server reboot? I added more plots to the map and it did not change number, reboot server again and number changes

Server is remote from my PC to simulate a real server that is on when players are not

**Comment by MishkaFur** [comment] 2021-05-03 18:31
9.3.3 still happening

Made district, exec permissions so insta pass, disconnect reconnect client and still 0 plots showing

![image](https://user-images.githubusercontent.com/61889138/116916464-411be480-ac45-11eb-9276-650249f7e341.png)

Reboot server and it updates but if i edit district the plot count does not change until next server reboot

![image](https://user-images.githubusercontent.com/61889138/116917071-141c0180-ac46-11eb-85a2-6e938ee34a0c.png)

**Comment by TwixterZ** [comment] 2021-05-23 10:33
@MishkaFur I have re-test this in 9.4 Staging 1990 and I could not reproduce the same issue 

Do you still see this happening?

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/f2771217-eee6-434d-a091-790951974570)

**Comment by TwixterZ** [comment] 2021-06-04 08:05
Re-test issue on 9.3.5 Release 231, issue still persist.

District not updated after its passed on zoning office. Relogging client did not help, server reboot required for information to be updated.
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/84aeab45-1e18-45d0-9b33-794202f6a8e1)

This only impact server based games, and not private game.

Repro:
- /civics spawngov
- Use zoning office to plot district
- Pass the motion
- Observe district zone size in map view (it will show as "covers 0 square meters (0 plots)")
- A server reboot will fix this issue.

**Comment by Daniel-Magulado** [comment] 2022-10-06 02:31
Hello,

This is issue is fixed in latest game version. Closing.

**Closed by Daniel-Magulado** 2022-10-06 02:31 UTC
Labels: Priority: Medium, Type: Bug, Category: UI
