### ISSUE TITLE
USER ISSUE: Some basic, missing functions

### ISSUE THREAD

**Issue by erazia123** [StrangeLoopGames/EcoIssues#6365] opened 2018-03-22 11:35 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Hello there!
There is currently no button for depositing and withdrawing things from storage boxes, which leads to a LOT of clicking and dragging after a while, which makes the game sort of uncomfortable. Also, there is no way of removing items you have created, such as deeds, seeds and similar. Please please please implement this as it makes the whole gaming experience crooked

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-03-22 18:17
What do you mean by 'removing items you have created'?

We agree that our inventory management needs work.  In the meantime, do you know about right clicking on chests and stockpiles directly in order to deposit?  Similarly, you can left click on stockpiles while holding various tools in order to quickly pull out specific types of blocks.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4280

**Closed by MarjieAVolk** 2018-03-22 18:17 UTC

**Comment by erazia123** [comment] 2018-03-23 01:41
Im aware of the right clicking while holding the item, however say you have 20 chests in a close vicinity - all linked together. And your backpack is full of things you need to drop into them, for example from farming and similar - you then need to DRAG every item into the chests while having both inventories open. In a similar fashion, say you need to take out 10 stacks of Beans from your chests into your backpack, you then need to DRAG every item to your backpack. A key to simply "Deposit or withdraw" would be very helpful and save a lot of time and simply make the game a lot smoother.


By removing items you have created, i mean that if (for example) you go out in the world and gather cactus fruit you will inevitably end up with Cactus fruit seeds as well. Thats fine in the beginning, but after a while.. Youre sitting there having eaten all the Cactus fruit and you're left with thousands of seeds that you cant destroy - resulting in having to place a lot of chests in game that people simply store things they dont want - because there is no way of deleting them.


________________________________
Från: MarjieAVolk <notifications@github.com>
Skickat: den 22 mars 2018 19:17
Till: StrangeLoopGames/EcoIssues
Kopia: erazia123; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Some basic, missing functions (#6365)


What do you mean by 'removing items you have created'?

We agree that our inventory management needs work. In the meantime, do you know about right clicking on chests and stockpiles directly in order to deposit? Similarly, you can left click on stockpiles while holding various tools in order to quickly pull out specific types of blocks.

Closing as duplicate of #4280<https://github.com/StrangeLoopGames/EcoIssues/issues/4280>

**Comment by MarjieAVolk** [comment] 2018-03-23 19:10
Ah okay.  For getting rid of items, we are working on a garbage feature, which should be available in version 8.0 (so not 7.3, but fairly soon)
