### ISSUE TITLE
Server crash related with pictures

### ISSUE THREAD

**Issue by mgarciamulhacensoft** [StrangeLoopGames/EcoIssues#24340] opened 2023-12-20 21:38 UTC
Sorry but im not willing to make your job,so i probably will not fit all pr requisites, you should have enougth having the entire stacktrace.

[message.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13732791/message.txt)

**Comment by D3nnis3n** [comment] 2023-12-20 22:52
We will need more information to deal with this issue, especially how it was achieved, the trace alone is not sufficient.

**Comment by iuriguilherme** [comment] 2023-12-21 03:08
IIRC the only time you'd make a marked name call is when someone writes something in chat that will link to a picture's name, right?  The trace does not give any information regarding which picture (or if it's a picture item at all) that is causing this server crash, but my guess is that some picture created in specific circumstances is causing that crash, maybe when the picture name would need to be shown in chat, and we can't know it for sure because such message would never make it to the game chat or be sent through the discord link bot.

The server crashed several times out of the blue, all players tried to remember what it could be but no bells ring.

We're sending the save game tomorrow.

**Comment by livingeccles** [comment] 2023-12-21 07:25
Hello,
Whilst I can appreciate the need for as much information as possible this peice of code in PrictureItem seems flawed?

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/130975499/5db3be9f-218c-4fa0-860e-e523cc14bc64)

We shouldn't be checking for null and then ref the exact same object you're null checking for in consequent and not expect null ref exceptions?

Please can we have a fix for this as our servers are suffering terribly with these crashes.

**Comment by MonzUn** [comment] 2023-12-21 08:24
Yeah that definitely looks like a mistake.

**Comment by ZombGuy** [comment] 2023-12-21 08:47
bump

**Comment by Demiden** [comment] 2023-12-21 08:56
> Hello, Whilst I can appreciate the need for as much information as possible this peice of code in PrictureItem seems flawed?
> 
> ![image](https://private-user-images.githubusercontent.com/130975499/292124094-5db3be9f-218c-4fa0-860e-e523cc14bc64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDkwNzksIm5iZiI6MTcwMzE0ODc3OSwicGF0aCI6Ii8xMzA5NzU0OTkvMjkyMTI0MDk0LTVkYjNiZTlmLTIxOGMtNGZhMC04NjBlLWU1MjNjYzE0YmM2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwODUyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmI1NzViNGU3MjYwMDJlMzAzMDNhODg5ZjNjMGE4ODA0NmI1ODE4MDM1NDNjZTFjNjU0YTQzYmJlZTkyMzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MRX8RWx2TmW6FaXCVSIs-6UQcI06Ju8qscCqeNr0yZ0)
> 
> We shouldn't be checking for null and then ref the exact same object you're null checking for in consequent and not expect null ref exceptions?
> 
> Please can we have a fix for this as our servers are suffering terribly with these crashes.

Agreed. Even IDE warns that as "Possible 'System.NullReferenceException'"

**Comment by iuriguilherme** [comment] 2023-12-21 15:42
Traced down to trying to put a picture item in a contract board causes server crash, this is reproducible and can be used to crash servers on purpose.

**Closed** 2023-12-21 19:01 UTC
Labels: Status: Needs Information
