### ISSUE TITLE
USER ISSUE: Cant Log in

### ISSUE THREAD

**Issue by FeniRisin** [StrangeLoopGames/EcoIssues#24253] opened 2023-12-17 14:53 UTC
\
**User Id: (slg124207)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
sign in to world

**Expected behavior:**
Signed into world

**Actual behavior:**
The following error message popped up:
```
Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes 2 can sign in to one other non modded world another gives same message

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-18 17:44
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24143

**Closed by D3nnis3n** 2023-12-18 17:44 UTC
