### ISSUE TITLE
Server encountered an exception after changing Truck ownership to Demographic

### ISSUE THREAD

**Issue by DragonDev1906** [StrangeLoopGames/EcoIssues#24559] opened 2024-01-07 12:32 UTC
# Description
After trying to change ownership of a Truck to a Demographic my game crashed to the main menu with the following message and error log. The server is still running.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/8270201/be6c138b-c248-431e-88d8-c469e330afc7)
[message.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13853418/message.txt)

# Steps to reproduce (I have not tried it a second time, yet)
- Be a citizen in a town (not sure if strictly needed)
- Place a Truck
- Go to Authorization > Open Deed
- Click the gear after Owned By and select a Demographic (I've tried it with "Citizen of MyTown", but it probably works with "Active", too.
- Save the selection

Version: 0.10.0.4 beta release-557

**Comment by D3nnis3n** [comment] 2024-01-07 21:24
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24536

**Closed by D3nnis3n** 2024-01-07 21:24 UTC
