### ISSUE TITLE
Intro does not adjust if meteor config is changed

### ISSUE THREAD

**Issue by gjsmo** [StrangeLoopGames/EcoIssues#11239] opened 2019-02-10 15:32 UTC
This is a minor issue. We have our server set for the meteor to hit after 60 days as opposed to 30 for a more relaxed playthrough, but the intro still says 30 days. It does not affect gameplay but it's a bit confusing to new players.

**Comment by elfl0rd** [comment] 2019-02-10 17:01
Duplicate of #8294

**Closed by elfl0rd** 2019-02-10 17:01 UTC
