### ISSUE TITLE
DevTool Issue Need to Fix soon please

### ISSUE THREAD

**Issue by Geuthur** [StrangeLoopGames/EcoIssues#4741] opened 2018-02-17 22:58 UTC
DevTool need to Remove Cart thats not owned by self to.. !! and remove any items that owned by other so that you can remove some bugged stuff or offline players they are never come back

Please Add this it Very Importat for Multiplayer Server!

Thanks thanks thanks !

**Comment by MarjieAVolk** [comment] 2018-02-23 19:53
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4820

**Closed by MarjieAVolk** 2018-02-23 19:53 UTC
