### ISSUE TITLE
error unknown <3

### ISSUE THREAD

**Issue by Arranoa-jolasten** [StrangeLoopGames/EcoIssues#25062] opened 2024-08-18 17:49 UTC
![Screenshot_20240818_053435_Microsoft_Remote_Desktop](https://github.com/user-attachments/assets/0dfca6fc-14ba-4ba4-94e6-4b12fc31f68a)

**Comment by D3nnis3n** [comment] 2024-08-18 20:16
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25064

**Closed by D3nnis3n** 2024-08-18 20:16 UTC
