### ISSUE TITLE
World markers are getting cutoff on the edges

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8043] opened 2018-06-12 21:45 UTC
![image](https://user-images.githubusercontent.com/3536496/41319010-415c821a-6e4f-11e8-9023-0f1309ab5ba3.png)

**Comment by Nanders** [comment] 2018-06-12 21:49
Duplicate of #6526

**Closed** 2018-06-12 21:49 UTC
Labels: Medium Priority
