### ISSUE TITLE
Small Versions of Icons do not Scale

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#3904] opened 2018-02-05 01:43 UTC
![image](https://user-images.githubusercontent.com/14983165/35785125-e1ef081a-09d2-11e8-8b21-794d976b0ad0.png)

Any Icon we compose out of multiple images scaled differently does not scale to the small version of the icon. I know this has been known about for a long time, but we need to figure out if this can be addable functionality or not, because many many many icons would benefit from this, and if it cannot ever be done then we will have to make tons of new icons that are often repetitions of others.

**Comment by metachronism** [comment] 2018-03-15 23:42
closing as dupe of #2784

**Closed by metachronism** 2018-03-15 23:42 UTC
Labels: Feature, Medium Priority
