### ISSUE TITLE
USER ISSUE: no vision

### ISSUE THREAD

**Issue by NielsRoorda** [StrangeLoopGames/EcoIssues#11412] opened 2019-02-19 16:02 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Start new singleplayer game, wait for it to generate random world

**Expected behavior:**
show the character creation menu and the world

**Actual behavior:**
shows gui/hud with black background and a white dot that kind of looks like a star

**Do you have mods installed? Does issue happen when no mods are installed?:**
shows gui/hud with black background and a white dot that kind of looks like a star

**Comment by elfl0rd** [comment] 2019-02-19 16:30
game restart is not help?

**Comment by NielsRoorda** [comment] 2019-02-19 17:12
Yeah i restarted the game and that 'fixed' it

**Comment by elfl0rd** [comment] 2019-02-19 17:27
Duplicate of #11226

**Closed by elfl0rd** 2019-02-19 17:27 UTC

**Comment by D3nnis3n** [comment] 2019-02-25 21:04
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053
