### ISSUE TITLE
USER ISSUE: glitched through the ground

### ISSUE THREAD

**Issue by lalawunderland** [StrangeLoopGames/EcoIssues#5080] opened 2018-02-25 13:34 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
walked around the world and fell through the ground

**Expected behavior:**
-.- should be clear

**Actual behavior:**

**Comment by Mahsaap** [comment] 2018-02-25 17:42
Note : If your using a custom size world that is not in the recommended list. The world can have tears.

**Comment by MarjieAVolk** [comment] 2018-02-26 19:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4574

**Closed by MarjieAVolk** 2018-02-26 19:12 UTC
