### ISSUE TITLE
Bug with browser-based features (laws, elections, and graphs)

### ISSUE THREAD

**Issue by alexarthur94** [StrangeLoopGames/EcoIssues#9813] opened 2018-10-20 14:47 UTC
When I'm in the game and click on the button for laws or the button for graphs and then press the button to open either of those in the browser, it instead opens the Documents folder on my computer, which does not have anything in it related to Eco. This has happened to me since I started playing the game in June and on all of the several servers I've played on.

Recently, I tried to use a workaround. I had someone else who could access the browser-based features give me the links for the charts and graphs, for the laws, and for elections. Although I can view the map, the graphs, and the cause and effect display in the browser using these links, if I try to use elections, propose laws, or vote, it says I have to access those pages from within the game, which I can't do. I also tried opening these links while the game Eco was open on my computer, but that did not solve the problem.

As another note, on the server I've been playing on recently, out of five of the players, including myself, only one could access the laws and graphs from in the game, although I know that that is probably not the case on most servers.

I'm looking forward to this being fixed so that I can participate in Eco's laws and elections features. Thanks for creating this awesome game for us!

**Comment by Deantwo** [comment] 2018-10-20 17:06
What is your OS and default browser?

**Comment by alexarthur94** [comment] 2018-10-20 20:27
My OS is Windows and my default browser is Google Chrome.

**Comment by Deantwo** [comment] 2018-10-26 00:44
Duplicate of #8942

**Comment by johnkslg** [comment] 2018-11-13 18:53
Failure starting default browser sounds like. See if we can detect it better?  Perhaps add a fail case that notifies the user of the problem and how to fix it.

**Closed** 2018-11-16 22:12 UTC
Labels: Fixed, High Priority
