### ISSUE TITLE
Suggestion: Laws: More options for "When attempting to place..."

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#4720] opened 2018-02-17 17:13 UTC
Currently, when making a law regarding the placement of items - there is only a limited selection of items that can be selected.

![image](https://user-images.githubusercontent.com/2173684/36343558-5fd23f3c-1459-11e8-8068-fa6f2f0a307c.png)

In the above example, I'd like to make a law that taxes a player $10 for cutting down a tree, but gives them the $10 back if they plant a tree to replace it.

However, there's no way for the law to specify "When; Planting a seed; of species; Cedar; Allocate $10".

**Comment by MarjieAVolk** [comment] 2018-02-23 20:14
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4077

You are definitely right O.o

**Closed by MarjieAVolk** 2018-02-23 20:14 UTC
