### ISSUE TITLE
USER ISSUE: 9.0 stable 8

### ISSUE THREAD

**Issue by Danevolent** [StrangeLoopGames/EcoIssues#17404] opened 2020-07-30 09:15 UTC
\
**Version:** 0.9.0.0 beta staging-stable-8

**Steps to Reproduce:**
have modern rock drill, switch items

**Expected behavior:**
stopped making noise

**Actual behavior:**
infinitely there is modern rock drill noise at that point in the world

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment] 2020-07-31 09:04
Thank you for the report. Can't reproduce it.
Can you make a video with the process if its possible?

**Comment by SlayksWood** [comment] 2020-08-24 09:10
merged to #17772

**Closed by SlayksWood** 2020-08-24 09:10 UTC
Labels: Status: Needs Information
