### ISSUE TITLE
USER ISSUE: tree chop quit to main menu

### ISSUE THREAD

**Issue by rainydan** [StrangeLoopGames/EcoIssues#4304] opened 2018-02-11 08:31 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. picked fern in approximately previously fallen trunk area
2. chopped trunk

**Expected behavior:**
chopped end of trunk into logs

**Actual behavior:**
quit to main menu with this stack trace. When I loaded back in and went back to the area, I looked for the trunk. I believe the trunk was gone.

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-12 23:25
Closing as duplicate of #3752 . You can track the issue's progress there.

If you have any additional information about when or why this happens, or what kinds of trees it happens on, it would be very helpful if you posted that on the linked bug ^

**Closed by MarjieAVolk** 2018-02-12 23:25 UTC
