### ISSUE TITLE
USER ISSUE: Problems with loading an existing World

### ISSUE THREAD

**Issue by Mauxschter** [StrangeLoopGames/EcoIssues#5219] opened 2018-02-28 14:17 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.Continue/Load
2.Wait until "Starting WebServerPlugin"
3.The Window minimizes, then tab in again
4.The Window with thw Message "Connection failed" pops up
   ( it already loaded the World a few times, but now it doesnt load the World as much i try)

**Expected behavior:**
Load/Start the World like it did before

**Actual behavior:**
Window with the Message "Connection failed" with an actually working Internet Connection

**Comment by MarjieAVolk** [comment] 2018-02-28 19:45
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/5192

Could you attach any server crash dump files you may have in '[...]\steamapps\common\Eco Server', so I can confirm whether this is the same issue?

**Comment by Mauxschter** [comment] 2018-02-28 20:11
Eco Log Session from 26.02.2018 16:00:04
Eco Server 0.7.1.2 beta
Server Initialization... 
Starting ModKitPlugin... 
Loading mods... 
Initializing items... 
Initializing skills... 
Starting NetworkManager... 
Starting WorldGeneratorPlugin... 
Starting StorageManager... 
Starting GameplayStatsPlugin... 
Starting StatDatabase... 
Starting WorldPlugin... 
Loading World... 
Converting world to new format... 
Initializing world... 
Starting TimePlugin... 
Starting ReputationPlugin... 
Starting PlayerHousingManager... 
Starting UserManager... 
Initializing inventories... 
Starting EcoObjectManager... 
Starting ControllerManager... 
Starting PropertyManager... 
Starting EcoSim... 
Starting ChatServer... 
Starting MinimapManager... 
Starting DisasterPlugin... 
Loading Disasters... 
Starting BackupPlugin... 
Starting WirePlugin... 
Starting DifficultySettings... 
Loading Plants... 
Initializing plants... 
Starting RouteProbingPlugin... 
Loading RouteProbing... 
Starting WorldLayerManager... 
Loading Layers... 
Initializing world layers... 
Starting EconomyTracker... 
Starting WorldObjectManager... 
Starting EconomyPlugin... 
Starting RoomPlugin... 
Starting ObjectivePlugin... 
Starting Legislation... 
Starting WebServerPlugin... 
Failed to start Webserver: Ein Aufrufziel hat einen Ausnahmefehler verursacht.
Starting DiscordPlugin... 
Initializing WorldGeneratorPlugin... 
Initializing WorldObjectManager... 
Initializing RoomPlugin... 
Ticking... 
Compressing... 
Saving world... 
Server Initialization finished in 153.514,4ms

I hope it helps
(If something's not written in English, it is maybe german if you have Translation Problems )

**Comment by MarjieAVolk** [comment] 2018-02-28 20:13
Thank you.  Yeah, it looks like #5192.  Closing as duplicate.  Unfortunately I don't know yet what is wrong, but you can keep following the bug there for any updates.

**Closed by MarjieAVolk** 2018-02-28 20:13 UTC
