### ISSUE TITLE
USER ISSUE: Game crash and Flying Tree

### ISSUE THREAD

**Issue by DANisEVOL** [StrangeLoopGames/EcoIssues#5176] opened 2018-02-27 13:03 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Enter game.
2. Pick up a specfic broken log beside a downed tree that is flying into the sky.
3.Game crashes.

**Expected behavior:**
The log should go to my carry slot and the downed tree should not be flying to the sky.

**Actual behavior:**
1. Tree and a log is slowly floating upwards.
2. Picking up the log on the ground crashes game.

The following error message popped up:

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-02-27 18:42
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-27 18:42 UTC
