### ISSUE TITLE
USER ISSUE: Many plants not visible on Linux

### ISSUE THREAD

**Issue by gepandz** [StrangeLoopGames/EcoIssues#25019] opened 2024-07-28 20:08 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. Have an Ubuntu 22.04 LTS system with an Nvidia graphics card, with up-to-date drivers (nvidia-driver-545), and installed via Steam
2. Start a new game or load into an existing save
3. Observe a few plants, like trees (e.g., Ceiba, Cedar, Palm) and some bushes, Camas, pumpkins, etc.
4. Walk around and realize that there is a LOT of ground-cover, King Ferns, Papaya, Pineapples, and other plants that only appear in occasional flashes of outlines and a floating "[E] to gather" or "Dig" marker (See attached screenshot for an invisible King Fern (name at the top), and that I can Dig it, but I cannot see it; I tried to get the green outline, but it's visible just for one or two frames, so I wasn't able to capture the behavior in a screenshot. I can try OBS or something for video capture, if necessary) ![Eco_missing_King_Fern_20240728124316_1](https://github.com/user-attachments/assets/aaa4a0eb-9012-493e-b01b-b4baa8c46d8c)
5. If you gather the plant, you will see the gathering animation (explosion of leaves, hand- or tool-motion, item appearing and moving toward you, etc.), and the item goes into your inventory
6. Wonder how much of the world you're not seeing :sweat-smile:

This occurs in both offline and online games. Thus far, I've been the host in a solo or LAN game, but I can try joining a public server to see if it affects situations where there's a remote host. Exiting and restarting does not affect this behavior. Turning down graphics settings does not affect this behavior.

**Expected behavior:**
You should see all plants in Eco

**Actual behavior:**
You often miss a bunch of plants that you can only observe via their green interaction outlines

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/16405063/Player.log)

**Comment by gepandz** [comment] 2024-07-28 21:40
Just spotted the version info in the Escape menu, if that helps:

0.10.2.4. beta release-674
2024.05.16 01:49

**Comment by D3nnis3n** [comment] 2024-07-29 20:27
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18422 - that issue is known, but there is no timeframe for when there is resources to work on it, as Linux Clients aren't supported. I heard the issue doesn't appear when using Proton, but I'm not sure - you would need to try.

**Closed by D3nnis3n** 2024-07-29 20:27 UTC

**Comment by gepandz** [comment] 2024-07-29 23:57
I confirm that switching to Proton Experimental started rendering the plants that I wasn't seeing before. Thanks for the tip!
