### ISSUE TITLE
USER ISSUE: Random Items not in stores (cant sell or buy them)

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#7185] opened 2018-04-14 00:00 UTC
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
- Start a fresh server
- make a building with a store
- try to sell gold or copper ingot 
- both items can not be found

Other missing items are : glass, steel, lumber, framed glass .....

If you have modded items on your server, other items will disapear from the shop and all ingots may be present. For example with some mods on our server, i cant find coal and gold ingot but copper ingot can be found.

![image](https://user-images.githubusercontent.com/3091083/38761920-29cb60f4-3f87-11e8-8bc2-46957ad4a613.png)

**Comment by WeaselDog** [comment] 2019-11-12 23:51
This is caused by the items not being invented yet. Iron Bar is not connected to Smelting while Copper Bar and Gold Bar are. 
Pre Smelting:
![NoSmelting](https://user-images.githubusercontent.com/47330823/68720476-33abff80-0564-11ea-95e5-0d8d7c520ab8.png)
Post Smelting Discovery:
![WithSmelting](https://user-images.githubusercontent.com/47330823/68720488-3f97c180-0564-11ea-89f5-81e6b27d893a.png)

Framed Glass, Glass, & Steel also must be invented. For some reason Bricks & Lumber do not need to be researched first.

**Comment by SlayksWood** [comment] 2019-11-13 05:11
merged to #12018

**Closed by SlayksWood** 2019-11-13 05:11 UTC
Labels: Medium Priority
