### ISSUE TITLE
[0.9.0 Staging 1459] Crash when cutting trees in large pieces.

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#15087] opened 2020-03-12 01:31 UTC
Chopping down Old Growth Redwood got an exception from server when chopping and collecting the Logs, when loaded world back in No Giant Redwood
**Version:** 0.9.0.0 beta staging-1459
this is on a Single-player
uploading World and Player.log
[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4321838/Storage.zip)
 World

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4321834/Player.log)

**Comment by Conchipedia** [comment] 2020-03-12 06:20
after a complete shutdown and coming back to game the Old Growth Redwood had appeared back in game

**Comment by Conchipedia** [comment] 2020-03-12 06:40
gave up trying to chop this Tree up after a few More exceptions, as you can see in Player,log
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4322647/Player.log)

**Comment by SlayksWood** [comment] 2020-03-12 10:51
Crash happen when you try to chop any tree not a small pieces.
Step to reproduce:
- chop down tree and clear branches. Try to chop in two same pieces:
![image](https://user-images.githubusercontent.com/45708377/76514125-75907800-6468-11ea-883d-1e749404b7f5.png)

```
System.Exception: Attempting to recycle a BSONSimpleValue multiple times
   at Eco.Shared.Serialization.BSONValue`1.ThrowMultipleRecycleError()
   at Eco.Shared.Serialization.BSONValue`1.Recycle()
   at Eco.Shared.Serialization.BSONObject.TryPerformRecycle()
   at Eco.Shared.Serialization.BSONValue`1.Recycle()
   at Eco.Shared.Serialization.BSONObject.TryPerformRecycle()
   at Eco.Shared.Serialization.BSONValue`1.Recycle()
   at Eco.Shared.Serialization.BSONArray.TryPerformRecycle()
   at Eco.Shared.Serialization.BSONValue`1.Recycle()
   at Eco.Shared.Serialization.BSONObject.TryPerformRecycle()
   at Eco.Shared.Serialization.BSONValue`1.Recycle()
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__61_2()</size>
```

**Comment by mirasrael** [comment] 2020-03-12 16:25
It happens if you're not move out interaction cursor. As workaround until fix to prevent crash you should move highlight out of tree and then return back and chop into pieces.

**Comment by rsdworker** [comment] 2020-03-12 16:37
well no matter how big or short its always crash i had issue which mentioned - maybe both should merge in one issue? because its showstopper regardless where mouse is

**Comment by MishkaFur** [comment] 2020-03-12 19:30
Got the same error down as i hit the bottom of the tree as it fell.

![image](https://user-images.githubusercontent.com/61889138/76559860-dbe0bf00-6497-11ea-832a-1c3a5f2934f3.png)
[log crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4326085/log.crash.txt)

**Comment by rsdworker** [comment] 2020-03-13 12:35
in 1461 the crash still happens (its not known if fixed in 1461 or later?)

**Comment by mirasrael** [comment] 2020-03-13 16:29
1463

**Closed** 2020-03-16 06:51 UTC
Labels: Priority: High, Status: Fixed
