### ISSUE TITLE
USER ISSUE: Game menu won't load when Steam is offline

### ISSUE THREAD

**Issue by janosdebugs** [StrangeLoopGames/EcoIssues#22511] opened 2021-08-04 18:10 UTC
User Id: (Not logged user)
Version: 0.9.3.6 beta release-235

Steps to Reproduce:
Start Steam in offline mode (or have a Steam community outage)

Expected behavior:
Game should load main menu and display mouse cursor.

Actual behavior:
Game shows main screen, but no menu or mouse cursor.

Do you have mods installed? Does the issue happen when no mods are installed?:
No

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6933504/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6933505/Player-prev.log)

**Comment by Daniel-Magulado** [comment] 2021-08-05 17:22
Hi @janosdebugs 

Thank you for writing this report however, Eco cannot be played without an Internet connection.
The game shows a blank UI upon starting it via Steam due to the game trying to connect to Steam and verifying your account. On the logs, it states _OnEncryptedAppTicketResponse: Not connected to Steam_ which indicates that the game is trying to establish connection with Steam.

I'll be closing this report as the response of the game is intended but do not hesitate to write another report if you encounter any bugs or unusually in-game behavior.

**Comment by janosdebugs** [comment] 2021-08-05 17:25
Hey there,

Thanks, but an error message would still be nice. Also, at least having a quit button wouldn't hurt either.

**Comment by Daniel-Magulado** [comment] 2021-08-05 17:51
Hi @janosdebugs 

Sounds great. I'll write a ticket for you so that our development team can look into your suggestion further.
Reopening this ticket as per request.

**Comment by D3nnis3n** [comment] 2021-08-05 20:12
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20156

**Closed by D3nnis3n** 2021-08-05 20:12 UTC
Labels: Priority: Low, Type: Feature
