### ISSUE TITLE
7.2.0 Client Bug Washboard creating Anvil Working Sounds

### ISSUE THREAD

**Issue by MittenMarauder** [StrangeLoopGames/EcoIssues#5538] opened 2018-03-07 05:16 UTC
**Server, Client or Website?** Client

**OS/Web Browser?** Win10

**Detailed Description of Issue:** Placed Washboard makes an Anvil Working Sound

**Reproducible? How difficult is it to reproduce?** Yes. Place Washboard.

**Steps to reproduce bug/issue:** Place Washboard. Sound plays at placement.

**Additional Comments:** N/A

**Client Version?** 7.2.0

**Include recent Crash dump ( get only generated if the server crashes):** N/A

**Comment by MarjieAVolk** [comment] 2018-03-07 22:52
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5498

**Closed by MarjieAVolk** 2018-03-07 22:52 UTC
