### ISSUE TITLE
USER ISSUE: Deposit with right click into a container for a contract don't work, instead we should open the inventory.

### ISSUE THREAD

**Issue by coolfarmer** [StrangeLoopGames/EcoIssues#6077] opened 2018-03-15 07:30 UTC
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1. Create a contract "Put in container" for 1 stone. Container is a wood cart here.
2. Tell your friend to accept the job.
3. You friend take 1 stone and deposit it with right click into the wood cart. The contrat will stay at "Still 1 stone".
4. Instead of right click, open the wood cart and drag and drop the stone into the cart's inventory, boom success, 0 stone left.

**Expected behavior:**
See above	

**Actual behavior:**
See above

**Comment by CreeperLord** [comment] 2018-03-15 15:02
<I AM NOT A DEV>
This is related to https://github.com/StrangeLoopGames/EcoIssues/issues/6050;

Caused by issues with stockpile / chest ownership;
A contract to add an item only gives the other player deposit permissions
UNLESS said player already has auth perms to use. (auth perms is higher than contract perms)

**Comment by MarjieAVolk** [comment] 2018-03-16 00:13
Thanks, closing as duplicate of #6050.  Looks like this will be fixed in the next release :)

**Closed by MarjieAVolk** 2018-03-16 00:13 UTC
