### ISSUE TITLE
USER ISSUE: Having ability to unlearn a wrongly chosen Speciality even if it gave you an object

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3435] opened 2018-01-16 19:22 UTC
**Version:** 0.6.4.0 alpha staging-9e63c2fa

I want to be able to get rid of the wrongly learned Specialities in the Farmer profession, but because they gave you a shovel and a scythe for the specialities i cannot do this 
![snap1119](https://user-images.githubusercontent.com/29383891/35007899-ca33b94e-faf2-11e7-82c5-5bd0829fbea7.png)

we can make those tools on a workbench now anyway and also repair them under Survivalist Profression, so Perhaps just take the Free tool off.

so if a player makes a mistake they are stuck with this for the whole game having useless stuff they don't put points in.

**Comment by MarjieAVolk** [comment] 2018-01-16 20:32
Yes, we are going to change that, but looks like it won't get in until beta.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3382

**Closed by MarjieAVolk** 2018-01-16 20:32 UTC
