### ISSUE TITLE
USER ISSUE: Steel Pipes

### ISSUE THREAD

**Issue by LegionVarus** [StrangeLoopGames/EcoIssues#9231] opened 2018-09-07 00:51 UTC
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
1. Place steel pipe in room that is at least a 2 tier average room.

**Expected behavior:**
The average should still be tier 2.

**Actual behavior:**
Steel pipe causes the average to drop below tier 2.

**Comment by elfl0rd** [comment] 2018-10-01 09:52
Please remove ALL pipes from room tier calculation.

**Comment by elfl0rd** [comment] 2018-10-07 14:34
![default](https://user-images.githubusercontent.com/4980243/46582925-38e07600-ca57-11e8-9df0-13cd63d0b11a.png)

**Comment by Deadpool111** [comment] 2018-10-07 19:08
i built the house 4 blocks high with windows on the 2nd level and the 4th and the smoke did not fill the room and worked fine and adding to blocks of Reinforced Concrete the room will go up 0.02 so it will then be 2.02 hope that helps anyone

**Comment by elfl0rd** [comment] 2018-11-22 16:35
All pipes counts as tier0, please remove it from room calculation.

**Comment by D3nnis3n** [comment] 2018-11-26 06:44
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9393#issuecomment-441534041

**Closed by D3nnis3n** 2018-11-26 06:44 UTC
Labels: Medium Priority
