### ISSUE TITLE
USER ISSUE: Propose a new law: Broken % operator results in NaN

### ISSUE THREAD

**Issue by FoxAviation** [StrangeLoopGames/EcoIssues#9984] opened 2018-11-12 19:43 UTC
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Open Browser and click on 'Propose new law'
Select 'on player action', when attempting to 'buy' 'all'
Select 'tax' and 'calculated value'
Change the operator to '%'
.. no matter what you type in the two operands, the currency will be 'NaN' (Not a number) after the law is passed and the first transaction is completed in a store of your choice.

**Expected behavior:**
The Webgui should only allow for one operand before the '%' operator. And the currency should behave properly (who guessed it)

**Actual behavior:**
After the law has passed and the first transaction is completed in the store, the currency selected during law proposal is 'NaN' (Not a Number). I found no way to save the affected game....n
**Do you have mods installed? Does issue happen when no mods are installed?:**
After the law has passed and the first transaction is completed in the store, the currency selected during law proposal is 'NaN' (Not a Number). I found no way to save the affected game....

**Comment by FoxAviation** [comment] 2018-11-12 19:47
Probably related to  #9510

**Comment by Deantwo** [comment] 2018-11-13 07:54
The `%` is not a percentage function, it is modulus.
See: #8360

The `%` should just be renamed to `modulus` in the interface, so people don't think it is percentage all the time.
Displaying modulus as `%` will only make sense to programmers.
See: https://en.m.wikipedia.org/wiki/Modulo_operation

**Comment by Deantwo** [comment] 2018-11-13 07:54
Duplicate of #9510

**Comment by Deantwo** [comment] 2018-11-13 07:58
@FoxAviation, if you need help with designing a law, you can ask in the #law-examples channel on the [official **Eco** Discord](http://discord.gg/eco) server.

**Comment by Deantwo** [comment] 2018-11-13 07:59
A screenshot of your law might also help figuring out what your issue is. Or at least a copy-paste of it.

**Closed** 2019-02-22 14:51 UTC
Labels: D3nnis3n's List, Semi-High Priority
