### ISSUE TITLE
USER ISSUE: Local Server doesn't want to load after PC crash

### ISSUE THREAD

**Issue by Splin73r** [StrangeLoopGames/EcoIssues#4950] opened 2018-02-22 13:45 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Load saved game, experience connection failed.

**Expected behavior:**
It should  load up and be ok?

**Actual behavior:**
The following error message popped up:
```Connection Failed
Connection Failed
```

**AggregateException 02214734.ecodmp**
--BEGIN DUMP--
Dump Time
02/21/2018 21:47:34

Exception
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ionic.Zip.ZipException: Could not read Storage\Splin73r and D3Syph3R's Nugget.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x00700C1E
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ionic.Zip.ZipException: Could not read Storage\Splin73r and D3Syph3R's Nugget.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x00700C1E
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_0()
   at System.Threading.Tasks.Task.Execute()<---

Inner Exception
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ionic.Zip.ZipException: Could not read Storage\Splin73r and D3Syph3R's Nugget.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x00700C1E
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ionic.Zip.ZipException: Could not read Storage\Splin73r and D3Syph3R's Nugget.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x00700C1E
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_0()
   at System.Threading.Tasks.Task.Execute()<---

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-02-23 21:55
Are you able to play on other servers/saves?  It looks like your save file is corrupted, although I am not sure what broke it.  Were you by any chance trying to use special characters or non-English characters in chat, or in your username?  Or did you maybe change eco versions on this save file a lot?

Would you be able to send over your save file?

**Comment by MarjieAVolk** [comment] 2018-02-23 23:54
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4665

If you have any more information, will still be helpful.

**Closed by MarjieAVolk** 2018-02-23 23:54 UTC
