### ISSUE TITLE
[0.9.3 staging-1931] Wages issue.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20597] opened 2021-02-16 11:41 UTC
- [x] 1. Can't pay wages because players don't have access to bank account:
- player 1 create title with wage:
![image](https://user-images.githubusercontent.com/45708377/108058083-8f691080-7064-11eb-832a-cb59403b250c.png)
- add player 2 and player 3 to users of this title:
![image](https://user-images.githubusercontent.com/45708377/108058121-9c85ff80-7064-11eb-8911-56ad84bd0b2c.png)
- check payment:
![image](https://user-images.githubusercontent.com/45708377/108058171-ae67a280-7064-11eb-8a6d-179e6ebfe351.png)

- [ ] 2. Wage spams a lot now - every 5 seconds. It should send message depending on server settings:
![image](https://user-images.githubusercontent.com/45708377/108058339-f4246b00-7064-11eb-9052-ff438e5f3f8c.png)
![image](https://user-images.githubusercontent.com/45708377/108058641-5bdab600-7065-11eb-9194-b5242492f0dd.png)

**Comment by IcedForge** [comment] 2021-02-23 10:47
Reopening since notification spam was not fixed, original permission fix is working though ( verified in staging 1937 )

**Comment by IcedForge** [comment] 2021-03-09 07:49
Confirmed working as intended and fixed in recent 9.3.0 staging build 1949

**Closed by IcedForge** 2021-03-09 07:49 UTC
Labels: Category: Gameplay, Priority: High, Regression, Squad: Mountain Goat, Status: Fixed, Status: Reopen, Type: Bug
