### ISSUE TITLE
Unplayable and pink world in Linux

### ISSUE THREAD

**Issue by cemeceme** [StrangeLoopGames/EcoIssues#23380] opened 2022-09-01 01:41 UTC
After entering a world, everything except the player character and the menus is solid pink.
In addition, you are in a constant state of falling, as the world as a whole does not render nor functionally exist.
![pink](https://user-images.githubusercontent.com/26171877/187813609-3881400d-2441-40f9-892a-eac2934c0e50.png)
If left in this state for a while, the game will crash to desktop.

Player.log:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9466151/Player.log)

Clean install of Eco version: 9.6.0 with no mods.

OS: Ubuntu 22.04 LTS

**Comment by YagoMello** [comment] 2022-09-01 04:22
Same on OpenSUSE Tumbleweed.

After enabling proton the game is running fine.

**Comment by cgiAlexis** [comment] 2022-09-02 17:02
I tried native, Steam runtime layer and the pink world bug happens regardless
Tried Proton, 7.0-6 crashes at launch and Experimental crashes at the server creation stage

**Comment by hutli** [comment] 2022-09-02 20:12
I am experiencing the same bug.
Eco `0.9.6.1`
Linux Kernel `5.19.5`
Nvidia Proprietary drivers `515.65.01`
![unknown](https://user-images.githubusercontent.com/6594598/188229059-e9879155-9a39-4caa-acc6-47e080f12d77.png)

**Comment by redwyre** [comment] 2022-09-03 17:02
Duplicate of #23334

**Closed by redwyre** 2022-09-03 17:02 UTC
