### ISSUE TITLE
USER ISSUE: cant create and join my own worlds

### ISSUE THREAD

**Issue by fredrik513** [StrangeLoopGames/EcoIssues#24334] opened 2023-12-20 17:22 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
press new game and the world loads but when it comes to connecting it stopes and gives error codeI first tried to make a bigger world as a standard one is super small but when I took it all back to normal nothing worked I have tried also eco server on steam dosent work and also re installed the game about 10 times and also deleted all filed in the game so it all would go back to defult

**Expected behavior:**
it should create a world so I can play :D

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-20 22:55
This is not a bug but caused by Eco being unable to reach our authentication servers.

Typically this happens when security software or firewalls block the access and can be resolved by exempting Eco in any antivirus software. You can also test by using a VPN (or turning an existing one off that may not be able to reach).

In Eco authentication is done by the server, hence when you play on a online server you're likely not seeing the problem, as those servers have no issues connecting to our authetnication server, while when you play a local game, a local server is run that has the issue.

Further information can be received at [support@strangeloopgames.com](mailto:support@strangeloopgames.com).

**Closed by D3nnis3n** 2023-12-20 22:55 UTC
