### ISSUE TITLE
InteractInAir test broken in master

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11417] opened 2019-02-19 17:29 UTC
Any test-breaking that gets past CI I'm making critical, so CI continues to be useful.

testinteractair: Test Failed with 1 exceptions.

=====EXCEPTION 0=====
Exception throw when using item DirtItem - System.NullReferenceException: Object reference not set to an instance of an object.
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Shared

System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Shared.Networking.RPCManager.DoCall(String methodname, INetObject obj, AwaitedQuery query, INetClient target, Object[] args)
at Eco.Gameplay.Tutorial.UserSubTaskOpenUI.Init(User user)
at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
at Eco.Gameplay.Tutorial.UserTask.LoggedIn()
at Eco.Gameplay.Tutorial.UserTaskManager.AddTask(UserTask t)
at Eco.Gameplay.Tutorial.TutorialTasks.<>c__DisplayClass7_0.b__4()
at Eco.Core.Utils.SubscriptionExtensions.<>c__DisplayClass4_0.b__0()
at System.Action.Invoke()
at Eco.Gameplay.Tutorial.UserTaskManager.TaskComplete()
at Eco.Gameplay.Tutorial.UserTask.Completed()
at Eco.Gameplay.Tutorial.UserTask.SubclauseFinished(UserSubTask subtask)
at Eco.Gameplay.Tutorial.UserSubTask.CompleteTask()
at Eco.Gameplay.Tutorial.UserSubTaskSubscribe`1.CheckComplete(Param p1) at System.Action`1.Invoke(T obj)
at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
at Eco.Gameplay.Items.Inventory.Clear(User user)
at Eco.IntegrationTests.Tests.TestItems.TestInteractAir(User user)

**Comment by BlazeGuy2** [comment] 2019-02-19 22:32
Ran tests several times on master, couldn't reproduce it.  This is an issue unique to https://github.com/StrangeLoopGames/Eco/pull/3981.  Either there is a bug in the code there, or the code there has exposed a bug with CI.  Closing as issue isn't on current master.

**Closed by BlazeGuy2** 2019-02-19 22:32 UTC
Labels: Critical Priority, Not reproduced
