### ISSUE TITLE
USER ISSUE: Fell off of the world?

### ISSUE THREAD

**Issue by AlanAu** [StrangeLoopGames/EcoIssues#4162] opened 2018-02-09 05:33 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
During exploration, managed to fall off of a cliffside into the fog and just kept falling.

**Expected behavior:**
Eventually I would expect to have stopped, ideally returned to ground level.

**Actual behavior:**
I'm still falling.

**Comment by MarjieAVolk** [comment] 2018-02-13 23:03
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4167

**Closed by MarjieAVolk** 2018-02-13 23:03 UTC
