### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by MikeUsh** [StrangeLoopGames/EcoIssues#24540] opened 2024-01-05 14:23 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Failed to process a request. Probably the client incompatible with the server.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-05 19:22
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24539

**Closed by D3nnis3n** 2024-01-05 19:22 UTC
