### ISSUE TITLE
USER ISSUE: fertilizer does nothing

### ISSUE THREAD

**Issue by ownyHD** [StrangeLoopGames/EcoIssues#4293] opened 2018-02-11 04:29 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
i put 20 fertilizer into a field but the minerals arent changing. field is almost empty

**Expected behavior:**

**Actual behavior:**

**Comment by LiaungYip** [comment] 2018-02-11 05:23
Duplicate of #4125.

**Comment by ownyHD** [comment] 2018-02-12 16:37
fixed with 7.1.0

**Closed** 2018-02-12 16:36 UTC
