### ISSUE TITLE
USER ISSUE: TaskBar Issues

### ISSUE THREAD

**Issue by Deathuponu** [StrangeLoopGames/EcoIssues#5444] opened 2018-03-05 23:07 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Switching items around in the taskbar slots. 1-9 & 0

**Expected behavior:**
Should be placed smoothly right? Picture should be there, number if you have more than one, and you should be able to pick it back up and move it around again.

**Actual behavior:**
Instead it sometimes, turns invisible not allowing you to move it again. It may fix itself sometimes, but this is really annoying.

**Comment by MarjieAVolk** [comment] 2018-03-05 23:11
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3841?

**Comment by MarjieAVolk** [comment] 2018-03-09 19:14
Okay, closing as duplicate of #3841

**Closed by MarjieAVolk** 2018-03-09 19:14 UTC
