### ISSUE TITLE
Crash on viewing meteor sequence

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21664] opened 2021-04-29 18:19 UTC
This happened as follows:
- Havent opened the meteor tutorial
- Look at meteor, make it show the clock text
- Open meteor tutorial while looking at the meteor (nothing happens. It should start the tutorial after several seconds).
- Look away from the meteor and look back
- Crash

**Comment by SlayksWood** [comment] 2021-04-30 06:07
The game crashes because it considers player a cheater:
```
[09:05:49.481] Injection detected. Please, stop using third-party software for code injections or you will be reported and permanently banned on all servers.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.<>c:<Register>b__1_0(Scene, LoadSceneMode)
UnityEngine.Events.UnityAction`2:Invoke(T0, T1)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)
```
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6403266/Player.log)

**Comment by WeaselDog** [comment] 2021-04-30 15:21
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/21553
Fixed is already in place.

**Closed by WeaselDog** 2021-04-30 15:21 UTC
Labels: Category: Tech, Priority: Critical, Squad: Pumpkin, Type: Bug
