### ISSUE TITLE
When using Low Collab on SP server creating you get 30 specialty stars without doing anything

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10971] opened 2019-01-30 13:04 UTC
![stars](https://user-images.githubusercontent.com/25908592/51982987-dee93d80-2497-11e9-8a61-f922618e699a.png)

GDragon might have already found this, but common search keywords didn't bring anything up.

**Comment by elfl0rd** [comment] 2019-01-30 13:15
Duplicate of #10929

**Closed** 2019-01-30 13:23 UTC
Labels: Quality Assurance
