### ISSUE TITLE
USER ISSUE: Continue Game After Client Update

### ISSUE THREAD

**Issue by TylarJ** [StrangeLoopGames/EcoIssues#5529] opened 2018-03-07 04:26 UTC
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
1) Have server running locally (0.7.1.2 beta).
2) Recieve auto update via Steam for game from previous version (not sure the versions).
3) Launch game.
4) Continue game hosted on server.

**Expected behavior:**
It should have connected to the game and not thrown a null reference exception.

**Actual behavior:**
The following messages popped up in server:
[12:07] Caught network exception from NewClient 10064!  Disconnecting...
[12:07] Disconnecting client [reason: Caught exception: Object reference not set to an instance of an object.]...

The following error message popped up in game:
```
Connection Failed
```
Server

**Comment by MarjieAVolk** [comment] 2018-03-07 23:06
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4267

**Closed by MarjieAVolk** 2018-03-07 23:06 UTC
