### ISSUE TITLE
After logging back into Stuffed elk I got a black screen and couldn't move

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10721] opened 2019-01-17 17:00 UTC
![image](https://user-images.githubusercontent.com/431728/51335133-0bcb4700-1acd-11e9-9145-1d8a8a85ae2c.png)

Esc didn't do anything, so can't disconnect
Can move stuff around in inventory, and eat

**Comment by elfl0rd** [comment] 2019-01-17 17:08
`/unstuck`?

**Comment by redwyre** [comment] 2019-01-17 17:10
Did nothing

**Comment by elfl0rd** [comment] 2019-02-15 09:26
Duplicate of #11226

**Closed by elfl0rd** 2019-02-15 09:26 UTC
Labels: Investigate
