### ISSUE TITLE
USER ISSUE: Character is double

### ISSUE THREAD

**Issue by NymaanE** [StrangeLoopGames/EcoIssues#24831] opened 2024-03-16 10:28 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
When i am in 3 person / 1 person my character is double doing double things. Like cutting wood, stone & placing down blocks.

**Expected behavior:**
.

**Actual behavior:**
.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by NymaanE** [comment] 2024-03-16 10:29
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14623232/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14623233/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-03-17 23:02
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24772, a workaround is available there.

**Closed by D3nnis3n** 2024-03-17 23:02 UTC
