### ISSUE TITLE
USER ISSUE: No Arrows in Inventory

### ISSUE THREAD

**Issue by Adsadafafas** [StrangeLoopGames/EcoIssues#24775] opened 2024-02-18 10:32 UTC
\
**User Id: (Not logged user)** (Not sure why it says this - I play through Steam)
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Have a bow in hand. Have arrows in backpack OR inventory. Try to use the bow. I've tried moving the bow to a different slot; tried repairing it to full durability, tried crafting more arrows; tried moving the arrows back and forth from inventory to backpack. Nothing works!

**Expected behavior:**
I should be able to use my bow.

**Actual behavior:**
I get an error message that says "You have no arrows in inventory".

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. Yes. (I have no mods!)

![arrows not working](https://github.com/StrangeLoopGames/EcoIssues/assets/82122622/da31002b-8046-482b-9a03-b1921e34a2e7)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14322099/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14322100/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-02-18 17:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24184

**Closed by D3nnis3n** 2024-02-18 17:23 UTC
