### ISSUE TITLE
USER ISSUE: tree one sided seeing

### ISSUE THREAD

**Issue by unloveddolphin** [StrangeLoopGames/EcoIssues#11823] opened 2019-04-01 00:11 UTC
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
cut down a tree
walk realy far away from it
come back its gone for u alone
your friend can see it tho

**Expected behavior:**
it should have not vaneshed

**Actual behavior:**
instead it should have stayed there

**Do you have mods installed? Does issue happen when no mods are installed?:**
instead it should have stayed there

**Comment by D3nnis3n** [comment] 2019-04-01 08:08
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11487

**Closed by D3nnis3n** 2019-04-01 08:08 UTC
