### ISSUE TITLE
Playtest Server doesn't start anymore 1498

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15554] opened 2020-04-04 20:57 UTC
> [22:46:49.257] [5] [ Info] [Eco] Loading Users...  
> [22:46:49.428] [16] [Error] [Eco] Failed to load object of type 'User'. It will be ignored, but may cause inconsistency and errors in other entities: System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
>    at Eco.Gameplay.Items.ItemPersistentData..ctor()
>    at lambda_method(Closure , Object[] )
>    at Eco.Core.Serialization.Serializers.ClassSerializer`1.<>c__DisplayClass3_0.<.ctor>b__1()
>    at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
>    at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
>    at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeReferenceableEnumerable(BinaryReader reader, Object decodeTarget, Int32 numElements)
>    at Eco.Core.Serialization.Serializers.EnumerableSerializer.Decode(BinaryReader reader, Object instance)
>    at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
>    at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
>    at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
>    at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
>    at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
>    at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
>    at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream)
>    at Eco.Core.Serialization.EcoSerializer.Deserialize(Stream stream)
>    at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream)

> [22:47:12.914] [42] [Error] [Eco] Failed to load server, Exception was Exception: ArgumentNullException
> Message:Value cannot be null. (Parameter 'key')
> Source:System.Collections.Immutable
> 
> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
>    at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
>    at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
>    at Eco.Core.Utils.ThreadSafeDictionary`2.<>c__DisplayClass22_0.<Add>b__0(ImmutableDictionary`2 x)
>    at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
>    at Eco.Core.Utils.ThreadSafeDictionary`2.Add(TKey key, TValue value)

**Comment by mirasrael** [comment] 2020-04-06 07:53
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/15570

**Closed by mirasrael** 2020-04-06 07:53 UTC
Labels: Priority: Critical
