### ISSUE TITLE
USER ISSUE: Inventory dragging

### ISSUE THREAD

**Issue by bootj93** [StrangeLoopGames/EcoIssues#5383] opened 2018-03-04 19:45 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Drag product from inventory to another inventory spot

**Expected behavior:**
Product should click into new inventory spot

**Actual behavior:**
Product stays floating in the screen and cursor stays a closed hand as if dragging something

**Comment by MarjieAVolk** [comment] 2018-03-06 02:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Comment by MarjieAVolk** [comment] 2018-03-06 02:33
Minimizing the game seems to clear these icons.  Also it seems that this issue happens a lot more for specific mice, so changing to a different mouse might reduce this issue for you, as a workaround.

**Closed by MarjieAVolk** 2018-03-06 02:32 UTC
