### ISSUE TITLE
[0.10.1.3] FPS drops to 1 in the store

### ISSUE THREAD

**Issue by vidok57** [StrangeLoopGames/EcoIssues#24718] opened 2024-02-01 09:12 UTC
After a few hours of playing and visiting several stores, I go into my own, which has about 60 positions for buying and selling. FPS is reduced from 120 to 1. Accordingly, it is not realistic to do it in a store in such a situation. Logging in to the server without closing the game does not help. It only helps to completely close the game and log in again.

It also happens after visiting other people's stores, when entering your store, the interface markup may float or positions from someone else's store may be displayed. It also helps to completely disable and re-enter the game.

FPS also sags heavily near the campfire. It helps a little to turn off the shadows, but the picture becomes terrible.

PC Specifications: R 5800x, RTX3060, 32GB, SSD.

**Comment by D3nnis3n** [comment] 2024-02-01 15:08
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24381

**Closed by D3nnis3n** 2024-02-01 15:08 UTC
