### ISSUE TITLE
server crash caused by unlearning skill

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#2457] opened 2017-10-04 02:41 UTC
[crash 10032404.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1354432/crash.10032404.txt)
[crash 1003804.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1354433/crash.1003804.txt)

player unlearned skill and crashed server.

**Comment by Dreconic** [comment] 2017-10-04 02:44
Went to go unlearn Iron smelting 5 to transfer to gold smelting, Would not unlearn the skill 30 seconds later server crashed kicking everyone. Came back up, confirmed again by trying to unlearn Iron Smelting 5.

**Comment by MarjieAVolk** [comment] 2017-10-04 22:37
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2420

**Closed by MarjieAVolk** 2017-10-04 22:37 UTC
Labels: High Priority
