### ISSUE TITLE
Stone Small Standing and Hanging Signs Issue (not Flush and would be nicer Same Height and width as a normal block)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9036] opened 2018-08-22 00:53 UTC
**Version:** 0.7.6.3 beta
![snap2474](https://user-images.githubusercontent.com/29383891/44436487-5e034d00-a5ad-11e8-9f2f-d48c6e4e6ec3.png)
![snap2475](https://user-images.githubusercontent.com/29383891/44436488-5e034d00-a5ad-11e8-80a5-02c25d66c22e.png)

I have just made a Glass Elevator, and i need the Shaft to be Exactly the Right size due to cart sometimes moves a fraction if too big (and can bounce upside down), this works great with the Wall Blocks, But because i want Numbers for Each Floor i cannot use Hanging Signs as they do not sit Flush against the Wall as can be seen in Next Snapshot
![snap2477](https://user-images.githubusercontent.com/29383891/44436507-812dfc80-a5ad-11e8-839c-707d2036cd20.png)

so i cut out One Block as i have a room Behind the shaft for Each floor and can get away with a window Hole so i place the Small Standing Sign in it, but as you can see it doesn't look Very Pretty
![snap2476](https://user-images.githubusercontent.com/29383891/44436591-f6013680-a5ad-11e8-9f92-249eb975a574.png)
![snap2478](https://user-images.githubusercontent.com/29383891/44436592-f6013680-a5ad-11e8-9c8c-59c6df59fed2.png)

Haven't tried with the Other signs from the other skills, but i think they are all exactly same size and issue, just a Different Material

**Comment by seccombew** [comment] 2018-08-22 17:53
Dupe of other world object placement issue.

**Closed by seccombew** 2018-08-22 17:53 UTC
