### ISSUE TITLE
Unstuck wont help in this case

### ISSUE THREAD

**Issue by ludovi71** [StrangeLoopGames/EcoIssues#11211] opened 2019-02-09 08:50 UTC
This was pretty rare situation but anyway, i was stuck on a cave stairs because of piece of sandstone that was stuck there,
i was trying to /unstuck myself right under the sandstone, multiple times, unsuccessfully.
Photo attached.
![yrnz](https://user-images.githubusercontent.com/4980243/52522881-19bf5280-2c9c-11e9-972e-76d9bee8ddec.png)

**Comment by elfl0rd** [comment] 2019-02-09 08:51
no screenshots.

**Comment by redwyre** [comment] 2019-02-09 11:31
I fixed the link

**Comment by elfl0rd** [comment] 2019-02-09 15:57
Duplicate of #9390

**Closed by elfl0rd** 2019-02-09 15:57 UTC
