### ISSUE TITLE
Tool tips still sticking after 7.7.1

### ISSUE THREAD

**Issue by RebelWisp** [StrangeLoopGames/EcoIssues#9266] opened 2018-09-08 14:36 UTC
I still have problems with the tool tip info on an item staying up, preventing efficient movement of stacks. In the attached photo you can see the click/hold and drag stack of hewn logs over top of the tooltip, no longer near where the origin was. Movement to the far edge of the screen or outside of the storage window does not make the tool tip overlay go away.
![20180908093235_1](https://user-images.githubusercontent.com/32402712/45255346-af9c2d80-b34a-11e8-8d25-54a741e3b8c0.jpg)

**Comment by Conchipedia** [comment] 2018-09-08 16:14
same here, its getting very annoying

**Comment by elfl0rd** [comment] 2018-09-08 17:14
attach old - https://github.com/StrangeLoopGames/EcoIssues/issues/9132

**Comment by MarjieAVolk** [comment] 2018-09-10 19:00
Okay, I am going to close this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9132 anyways - but let me know if you have a log file or more information.  I am not able to easily reproduce this issue here.

**Closed by MarjieAVolk** 2018-09-10 19:00 UTC
Labels: Investigate
