### ISSUE TITLE
USER ISSUE: System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state.

### ISSUE THREAD

**Issue by alexandrage** [StrangeLoopGames/EcoIssues#4822] opened 2018-02-19 11:51 UTC
**Version:** 0.7.1.2 beta
--BEGIN DUMP--
Dump Time
02/19/2018 06:54:44

```
Exception
System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state.
  at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal (System.Boolean throwOnInvalid) [0x00244] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Items.InventoryChangeSet.Apply () [0x00000] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Items.Inventory.Modify (System.Action`1[T] callback, Eco.Gameplay.Players.User user) [0x0000f] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Components.StockpileComponent.TryUpdateInventoryFromWorld () [0x002ba] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Components.StockpileComponent.Tick () [0x00000] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Objects.WorldObject+<>c.<TickComponents>b__171_0 (Eco.Gameplay.Objects.WorldObjectComponent x) [0x00000] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00024] in <2e7c1c96edae44d496118948ca617c11>:0 
  at Eco.Gameplay.Objects.WorldObject.TickComponents () [0x00006] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Objects.WorldObject.Tick () [0x00000] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Gameplay.Objects.WorldObjectManager.TickObject (Eco.Gameplay.Objects.WorldObject worldObject) [0x00032] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Shared.Utils.EnumerableExtensions.ForEach[T] (System.Collections.Generic.IEnumerable`1[T] enumeration, System.Action`1[T] action) [0x00010] in <3551df3dd5dd40258c668f8123c4fd50>:0 
  at Eco.Gameplay.Objects.WorldObjectManager.Run () [0x00104] in <caaa70cd4e5147e186ad0903763e4c6e>:0 
  at Eco.Server.PluginManager+<>c__DisplayClass18_0.<StartPlugins>b__0 (System.Object x) [0x00000] in <b4b94cd2c5cd4d04b63c8ec9d80be5c8>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in <2e7c1c96edae44d496118948ca617c11>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <2e7c1c96edae44d496118948ca617c11>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <2e7c1c96edae44d496118948ca617c11>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <2e7c1c96edae44d496118948ca617c11>:0 
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x0000f] in <2e7c1c96edae44d496118948ca617c11>:0 
```

--END DUMP--

**Comment by alexandrage** [comment] 2018-02-19 11:59
The world where the error occurred
https://cloud.mail.ru/public/4qDa/Dx9shnwa8

**Comment by MarjieAVolk** [comment] 2018-02-20 20:18
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4473

I will share your save file link over there, thank you!

**Closed by MarjieAVolk** 2018-02-20 20:18 UTC
