### ISSUE TITLE
USER ISSUE: Iron Hammers and Iron Axes sharing Durability.

### ISSUE THREAD

**Issue by 3DBlacksmith** [StrangeLoopGames/EcoIssues#23123] opened 2022-04-30 05:00 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
Some of our smiths are making iron hammers and axes and selling them. When I use my hammer, the durability goes down for not only myself but for a few other players.

**Expected behavior:**
Only my tools should go down in Durability not others players as well.

**Actual behavior:**
Iron Axe and Iron Hammer sharing durability with other players tools.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
It maybe the Whetstones mod, that's the main mod that may mess around with the tool itself.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by 3DBlacksmith** [comment] 2022-04-30 05:04
Update* 

On this server we have silo able to hold everything (not just seeds and foods), it seems when the tools stack, they become the same ip of tool. Sharing Durability, this happened now after the 9.5 patch.

**Comment by Daniel-Magulado** [comment] 2022-04-30 13:44
Hello @3DBlacksmith 

Thank you for submitting this report however, we are unable to reproduce this issue.
This could be caused by the mod you mentioned which may not be functioning well with the latest version of the game. We recommend testing this issue without the mods and verifying if it's still happening. Additionally, if it's alright with you, we can do some more testing if you can provide us your save file.

**Comment by 3DBlacksmith** [comment] 2022-04-30 13:47
That's ok Daniel, we think it does have to do with the mods. Thank you for your time and help there Daniel!

**Comment by D3nnis3n** [comment] 2022-05-02 11:19
This is a known issue with specific mods from earlier versions, so closing this.

**Closed by D3nnis3n** 2022-05-02 11:19 UTC
Labels: Status: Needs Information
