### ISSUE TITLE
[0.9.3.0 beta staging 1971]District map renaming wont take effect

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21277] opened 2021-04-06 20:31 UTC
Renaming and updating a district map will not take effect, it will keep adding increments 
![Screenshot_108](https://user-images.githubusercontent.com/24981362/113774122-27ab7980-9727-11eb-9b15-a6bceb0432db.jpg)

If i rename "Another Name 4" into "Blip Blop"
on changing this and enacting/voting for it this will
rename itself to "Another Name 5".

Reproduction
1. Create world, setup prefab capitol+zoning office and add a map
add a district or a few and name them something. Vote and enact , force civic ticks to avoid oddities
2. revise map, change names completely and enact. Observe it ignoring changes and reverting and adding incremental.

**Comment by IcedForge** [comment] 2021-04-06 20:41
Need to verify this in 9.4 as this pr
https://github.com/StrangeLoopGames/Eco/pull/8172
touched on it.

**Comment by DanielKispert** [comment] 2021-04-10 14:54
this one is also occurring in 9.2.4

**Comment by Daniel-Magulado** [comment] 2021-05-17 08:03
Tested on 0.9.4 Develop-287.
Unable to reproduce. Appears to be fixed due to the PR for #20287
Closing for now. We will keep an eye on this if anyone of us encounters it.

**Closed by Daniel-Magulado** 2021-05-17 08:03 UTC
Labels: Category: Laws, Priority: High, Squad: Mountain Goat, Status: Not reproduced, Type: Bug
