### ISSUE TITLE
Loan Contracts Fatal Bug

### ISSUE THREAD

**Issue by Thiritin** [StrangeLoopGames/EcoIssues#18541] opened 2020-10-01 10:23 UTC
Version Beta 9.0.3
Server OS: Linux

**Expected Behavior:** The Starts Normally
**Actual Behavior:** Server Crashes with a Null Pointer Exception (Directly after Server Init finished in Start Process.)
Used Mods: Nid-Toolbox Light, Elixr Mods (Only Server-Side Administration Mods). They are not the cause of the issue.

**Steps to Reproduce the Issue (Unconfirmed yet, will try out later. This is what most likely caused it.):**
1. Setup Eco Server
2. Build Bank and Create a Bank Account
3. Create a Loan Contract (Set it to give out from your Bank Account)
4. Someone else accepts the Contract
5. Delete the Bank Account behind the Loan
6. Server crashes now with a Null Pointer exception

**Crash Report:**
[crashreport.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5311195/crashreport.txt)

**Comment by beastyn** [comment] 2020-10-01 12:46
Could not reproduce. Account was deleted and money was transferred to nowhere with repayment (will make separate issue).
So it can be Linux issue or mod issue. Need to check it further.

**Comment by Thiritin** [comment] 2020-10-01 13:11
Please also take a look at my Database File. Maybe trough this you can investigate more.
https://drive.google.com/file/d/1SOr0zXCVALg8b6TEoc7mtsKO-6DmSVWO/view?usp=sharing
I could also provide a Working Database file one hour before the incident.

**Comment by beastyn** [comment] 2020-10-02 04:48
@Thiritin Thank you for the details. It would be great if we can use your .eco file from before the crash. If it contains some private information you can use my e-mail (anna@strangeloopgames.com).

**Comment by Thiritin** [comment] 2020-10-03 01:29
> @Thiritin Thank you for the details. It would be great if we can use your .eco file from before the crash. If it contains some private information you can use my e-mail ([anna@strangeloopgames.com](mailto:anna@strangeloopgames.com)).

Hi, I sadly cannot offer the file from before the crash. Just one Hour after the Crash.
The Backups are sadly already deleted. So it's waay back. I could only provide a full savegame file 8 hours after it.

**Closed** 2021-06-24 07:42 UTC
Labels: Status: Investigate
