### ISSUE TITLE
Repair Station - Staging alpha 6.0.0 #4c5f6bda

### ISSUE THREAD

**Issue by Senbotsu** [StrangeLoopGames/EcoIssues#1961] opened 2017-08-25 00:43 UTC
Repair Station does not repair stone tools. (Don't know about higher tiers)  32% durability on stone axe before repair, 32% after repair.

**Comment by Senbotsu** [comment] 2017-08-26 05:08
Update: Staging alpha 6.0.0 #e34aa2e5 - Stone Shovel is repairable but stop at 83%, stone axe and pick do not gain any durability when repaired.  They also now lose their durability bar when dragged back into player inventory after a repair.

**Comment by MarjieAVolk** [comment] 2017-08-31 18:10
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1920

**Closed by MarjieAVolk** 2017-08-31 18:10 UTC
