### ISSUE TITLE
SERVER ISSUE: Dump\ClientNetworkException Exception 02170028.ecodmp

### ISSUE THREAD

**Issue by yankeejim** [StrangeLoopGames/EcoIssues#4728] opened 2018-02-17 18:46 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
--BEGIN DUMP--
Dump Time
02/17/2018 03:00:28
 
Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!
 
Object reference not set to an instance of an object.
 
 
Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
 
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()
 
--END DUMP--

**Expected behavior:**
Dont know	

**Actual behavior:**
Umm un sure

**Comment by MarjieAVolk** [comment] 2018-02-22 19:56
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-22 19:56 UTC
