### ISSUE TITLE
[7.7.0] Log claims these items are missing icons and objects

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8916] opened 2018-08-09 22:00 UTC
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2276037/output_log.txt)

```
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following icons: CraneItem, RubberWheelItem, SmallWoodCartItem, SteelAxleItem, SteelGearItem, SteelPlateItem, SyntheticRubberItem
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject
 ```

**Comment by BlazeGuy2** [comment] 2018-08-09 22:02
An unclean log is now a fail condition for the QA pass.

**Comment by metachronism** [comment] 2018-08-10 17:45
dupe of other bug

**Closed by metachronism** 2018-08-10 17:45 UTC
Labels: Needs Triage
