### ISSUE TITLE
USER ISSUE: creating and loading into a new world

### ISSUE THREAD

**Issue by gravestristen** [StrangeLoopGames/EcoIssues#4020] opened 2018-02-07 05:05 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
new (in main menu)
world name Brittney <3
setting no collaboration 1-3 players
option Allow friends to join yes
option generate new yes
start

**Expected behavior:**
created a new world and loaded me into it

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment] 2018-02-07 22:21
Closing as duplicate of #4056

We have been getting many reports of connection problems; we are working to resolve these as quickly as we can. Hopefully it will be hotfixed today.

**Closed by MarjieAVolk** 2018-02-07 22:21 UTC
