### ISSUE TITLE
[7.6.3]Bug With Cactus

### ISSUE THREAD

**Issue by NeonGreeny** [StrangeLoopGames/EcoIssues#8842] opened 2018-08-03 19:22 UTC
I found that looking at a cactus seems to bug things out I'm not sure if it is a 1 off kind of thing or a staying bug. (It only happens when holding a axe.)

![20180803211216_1](https://user-images.githubusercontent.com/42076022/43661639-4caee4e0-9763-11e8-92c7-2dfedd38f86a.jpg)

**Comment by Nanders** [comment] 2018-08-13 23:43
This is an art bug, no?

**Comment by GophTheGreat** [comment] 2019-05-30 08:38
Could not reproduce. Closing.

**Closed by GophTheGreat** 2019-05-30 08:38 UTC
Labels: Low Priority
