### ISSUE TITLE
USER ISSUE: Flying Wood.

### ISSUE THREAD

**Issue by jaredalwyn** [StrangeLoopGames/EcoIssues#4108] opened 2018-02-08 09:40 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Chop tree laying on ground.

**Expected behavior:**
Wood breaks into sections to pick up.

**Actual behavior:**
Tree trunk flew into air as if there was no gravity.

**Comment by MarjieAVolk** [comment] 2018-02-13 23:11
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668.

**Closed by MarjieAVolk** 2018-02-13 23:11 UTC
