### ISSUE TITLE
Unable to annex with embassy desk - "Unable to consume needed resources, annex not performed"

### ISSUE THREAD

**Issue by BadMojo11** [StrangeLoopGames/EcoIssues#24729] opened 2024-02-03 18:32 UTC
Ongoing issue where a country meets all the requirements to annex a town but gets error message stating "unable to consume resources, annex not performed".  This has been reported several times in the official discord.  

Embassy desk has access to required resources.  Country meets all requirements for annexation.  Message on embassy desk says "annexation possible at any time".  But when you click annex it says "unable to consume resources, annexation not performed"

**Comment by D3nnis3n** [comment] 2024-02-05 02:30
Please provide the save file and note which settlement is trying to annex which settlement.

**Comment by BadMojo11** [comment] 2024-02-05 02:40
Hello! Thanks for the reply.  This is on a multiplayer server so I do not have access to the save file.  It may be worth noting:

- I have triple checked the embassy desk has access to the stockpile properly. 
- The resources are in the stockpile. 
- The embassy desk sees the stockpile. 
- I am the leader attempting the annex. 
- This is a country attempting to annex a town.
- All conditions are met to annex the town.   
- There are other users in the official Eco discord that have been reporting the same issue happening to them (all of them on MP servers)

**Comment by BadMojo11** [comment] 2024-02-05 02:41
> Please provide the save file and note which settlement is trying to annex which settlement.

Hello! Thanks for the reply. This is on a multiplayer server so I do not have access to the save file. It may be worth noting:

- I have triple checked the embassy desk has access to the stockpile properly.
- The resources are in the stockpile.
- The embassy desk sees the stockpile.
- I am the leader attempting the annex.
- This is a country attempting to annex a town.
- All conditions are met to annex the town.
- There are other users in the official Eco discord that have been reporting the same issue happening to them (all of them on MP servers)

**Comment by D3nnis3n** [comment] 2024-02-05 03:04
We are unfortunately only able to investigate this with the save game. You may be able to request the administrator to provide one.

**Comment by BadMojo11** [comment] 2024-02-05 03:08
I messaged the administrator of the server and am waiting for their response.  Thanks.

**Comment by superbjorn09** [comment] 2024-02-05 06:53
[Backup](https://eco.superbjorn.de/game.zip)

**Comment by BadMojo11** [comment] 2024-02-05 07:01
Dennis, post above should hopefully help. If you have any additional questions I'd be happy to answe them. To answer one of your previous requests, the country is Unified Econesian Islands and the town is Dustpeak. I know of two other servers having the same issue and I could get their contact information to you in discord if you need.

**Comment by D3nnis3n** [comment] 2024-02-05 12:32
> [Backup](https://eco.superbjorn.de/game.zip)

The town "Dustpeak" in this save is in a corrupted state and hence not annexable. Unfortunately the savegame doesn't help with figuring out why that is.

We'll need more cases of this with savegame and instructions to see if all of them are due to corrupted settlements or if this is a one off and there could be other reasons.

**Comment by D3nnis3n** [comment] 2024-02-05 12:39
Yes, that is the cause. You cannot annex settlements that are corrupted.

If anyone else is having the same issue, please redirect them here to provide savefile + which settlement tries to annex which settlement as well.

**Comment by D3nnis3n** [comment] 2024-02-05 12:44
You can try to use the /resettle command to repair the settlement, **but make a backup before that.**
The usage should be explained when entering it, it should take a settlement and the force parameter that can be set to "true", which might be necessary here.

**Comment by D3nnis3n** [comment] 2024-02-13 13:28
Fixed in 10.1.4.

**Closed by D3nnis3n** 2024-02-13 13:28 UTC
Labels: Status: Needs Information

**Comment by BadMojo11** [comment] 2024-02-13 15:34
I saw it in the patch notes. Can confirm it’s working. Thanks so much! You
and your team are awesome.
