### ISSUE TITLE
Crafting progress gets stuck at 100%

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3240] opened 2018-01-03 03:23 UTC
https://imgur.com/FiXZ7kq

**Comment by MarjieAVolk** [comment] 2018-01-03 03:27
That looks like expected behavior for a project that someone else created

**Comment by MarjieAVolk** [comment] 2018-01-03 03:27
(if there is no inventory space for the output and someone else started the project)

**Comment by johnkslg** [comment] 2018-01-03 04:00
ah that could be.  Perhaps it should communicate when its not your project

**Comment by MarjieAVolk** [comment] 2018-01-03 05:05
yeah could have different coloring or something... be a bit greyed out

**Comment by Huntermeign** [comment] 2018-01-03 14:23
No this is something that happens to my own projects as well. This sometimes happens after a restart or if there is no storage linked to the item where normally there is a 'collect' button but doesnt appear, or if the item is blocked mid-progress due to lack of items and then the items become available to finish queue.

**Comment by MarjieAVolk** [comment] 2018-01-03 18:41
When that happens, do you still see the project listed as yours in the project tooltip?

**Comment by Huntermeign** [comment] 2018-01-09 13:45
I'll let you know when I encounter the problem again

**Comment by Huntermeign** [comment] 2018-01-10 05:07
![bug](https://user-images.githubusercontent.com/4082137/34756619-386f38ec-f59a-11e7-9d03-23ffaeaaf26e.png)

**Comment by Huntermeign** [comment] 2018-01-10 05:08
As you can see, I started the quarry. Even though its 100% complete it just... stays. There is empty stockpiles nearby, and there is no collect button. If I cancel it I do get I think 1 stone back.

**Comment by Huntermeign** [comment] 2018-01-10 05:11
Also, the project does not appear in the economy viewer under tables. No audible noises from the project either.

**Comment by MarjieAVolk** [comment] 2018-01-10 19:05
Thanks for all the details, okay that is definitely wrong O.o

**Comment by Conchipedia** [comment] 2018-01-11 22:06
![snap1013](https://user-images.githubusercontent.com/29383891/34849761-710c46cc-f71b-11e7-8191-243f7ba0df1a.png)
![snap1014](https://user-images.githubusercontent.com/29383891/34849804-8e96e878-f71b-11e7-8213-6ae3b4b2156f.png)
starting to see this occasionally as well on tables, nobody but me crafts on them and as you can see plenty of space for it to go

**Comment by Conchipedia** [comment] 2018-01-16 15:46
Version: 0.6.4.0 alpha staging-ca25d17a
![snap1101](https://user-images.githubusercontent.com/29383891/34997369-44ccc854-fad4-11e7-80d8-b7c8630b7458.png)
Still getting this happen even in the latest Staging (loads of storage space and i queued this on my table on my land)

**Comment by pmeyerson** [comment] 2018-03-02 19:21
FYI, I had this issue happen when I was the only player on a local game (from #5305).

**Comment by andbruu** [comment] 2018-03-02 21:34
Was doing a bug report when I was pointed to this issue, so ill paste it here instead. Seems as if it is the same.

Server, Client or Website?
..Singleplayer server, launched from folder. Never runs for more than 24h (mostly 8-12h)

OS/Web Browser?
..Windows 10

Detailed Description of Issue:
..The issue happens all the time when producing mortared stone at a masonry, but I have noticed it at other times too when producing building blocks, or other large items.

Reproducible? How difficult is it to reproduce?
..Easy, as it all the time with mortared stone.

Steps to reproduce bug/issue:
..Go to masonry table, check for connected stockpile and chest holding stone and pitch, and with enough space for finished product.
..Start production of mortared stone (20+ usually).
..Play epic game of Eco, waiting for stone to complete.
..Check masonry table. Production completed, one product remains. Mark it - no collect button appear - cancel to move on.

Additional Comments:
..Only played since launch on steam (a few days after), and i am not sure it happened before the first update on steam.
..Have seen it with other products, but not all the time. I might have missed a few "successful" productions without the bug - but I dont think so.

Client Version? [Alpha .01 for example]
..Newest on steam as of today. 02-03-2018 (DD-MM-YYYY)

Include recent Crash dump ( get only generated if the server crashes)
..no crash (single player is super stable)

**Comment by spool1** [comment] 2018-03-13 22:12
A recent revelation we had is that the order is actually being completed. No resources lost, it just gets stuck on 'done' and doesn't clear the job from the window at the bottom leading everyone to think it failed somehow. All the resources should be outputted. It there was anything to claim it will say "X items to claim" and the job creator can claim it just fine in that case.

So, overall. No issue other than the job not removing itself correctly when it is done.

**Comment by MarjieAVolk** [comment] 2018-03-13 23:46
:O Really?  Well, yeah I am really thinking this is some kind of rounding/float comparison issue, will investigate soon.

**Comment by MarjieAVolk** [comment] 2018-03-14 22:52
Hey all, can anybody give me a save file where this is currently happening?

**Comment by metachronism** [comment] 2018-03-22 18:54
marjie fixed this

**Comment by MarjieAVolk** [comment] 2018-04-02 21:39
Okay, I guess it is still not fixed :'(  Got another report of it.

**Comment by MarjieAVolk** [comment] 2018-05-15 00:42
I don't think we've gotten another report of this since then... so I'm thinking my fix works like 90% of the time.  Reducing priority.

**Comment by GophTheGreat** [comment] 2019-05-09 02:35
Closing unless it pops up again.

**Closed by GophTheGreat** 2019-05-09 02:35 UTC
Labels: Medium Priority

**Comment by Demosthenexx** [comment] 2020-03-01 18:36
Win 64 0.8.3.3 w/ server Linux Mono 5.20.0, had same issue.

Using /targetowner $admin on the butcher table stuck at 100% reset the orders and I was able to remove it.
