### ISSUE TITLE
Game Crashes Upon Server List Loading 7.3

### ISSUE THREAD

**Issue by ianzm** [StrangeLoopGames/EcoIssues#6699] opened 2018-03-29 22:15 UTC
The game crashes every time, since 7.1 when I boot the server list.  It'll load in, then immediately crash.

I've tried disabling my firewall, I've tried deleting the UserApp folder, checking the file integrity of the game on steam, downloading a version directly from the Eco website, stopping the server list before it completely reloads, and of course turning everything on and off again.  

The game functions fine in single player, but the game was designed for multiplayer, and I'd like to enjoy the full experience.

Here's my spec list:

OS:  Windows 10
Processor:  Intel i5-4670K
Memory:  8gb
GPU:  AMD Radeon RX 580 8gb

**Comment by MarjieAVolk** [comment] 2018-03-29 22:20
Okay, you've tried all my usual suggestions.  Other than maybe doing ALL OF THOSE THINGS AT ONCE.

But you are the only report of this thus far, so what is different about your machine 🤔

**Comment by MarjieAVolk** [comment] 2018-04-02 23:11
So I've got one weird trick, which is to make sure Windows Explorer is closed when you start up the game.  Let me know if that has any effect.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6821

**Closed by MarjieAVolk** 2018-04-02 23:11 UTC
Labels: High Priority
