### ISSUE TITLE
USER ISSUE: Roots stay when tree demolished with road building tool

### ISSUE THREAD

**Issue by CCJordan** [StrangeLoopGames/EcoIssues#11915] opened 2019-04-07 16:18 UTC
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
Demolish a tree with the road building tool, try to dig out the patch from the road building tool.

**Expected behavior:**
It should have been posible to dig the soil out.

**Actual behavior:**
Instead the error "roots are too strong" appeared. 

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods.

**Comment by D3nnis3n** [comment] 2019-04-08 00:11
Duplicate of #10550

**Closed by D3nnis3n** 2019-04-08 00:11 UTC
