### ISSUE TITLE
USER ISSUE: Change onwer of a vehicule, make a crash

### ISSUE THREAD

**Issue by Moriedroc** [StrangeLoopGames/EcoIssues#24526] opened 2024-01-03 22:47 UTC
\
**User Id: (slg188608)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Change deed in a steamtruck and woodcard make a crash game

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumer</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No full vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-04 04:25
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24521

**Closed by D3nnis3n** 2024-01-04 04:25 UTC
