### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Malaras** [StrangeLoopGames/EcoIssues#4651] opened 2018-02-16 18:29 UTC
Started up the game then it crashed when going to server select.

Github don't seem to support .dmp files added it to my google drive.

https://drive.google.com/drive/folders/1IciJMMilPzIIaIOacgUJtS_v7GrJW1QO?usp=sharing

**Comment by MarjieAVolk** [comment] 2018-02-24 00:11
Most people have reported that deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO fixes this.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4791

**Closed by MarjieAVolk** 2018-02-24 00:11 UTC
