### ISSUE TITLE
USER ISSUE: Elk

### ISSUE THREAD

**Issue by lv01magikarp** [StrangeLoopGames/EcoIssues#4319] opened 2018-02-11 13:59 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Hunting elk with a bow
Server seemed to lag	

**Expected behavior:**
Teleporting elk and delayed arrows shooting

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC Hit on ArrowEntity!

Object reference not set to an instance of an object.


Stack:
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Simulation.Agents.Animal.Damage(Single amount, DeathType damageSource)
   at Eco.Gameplay.Animals.AnimalEntity.TryApplyDamage(INetObject damager, Single damage, InteractionContext context)
   at ArrowEntity.Hit(NetObjAttachInfo hitAttachInfo, Vector3 position)

```

**Comment by MarjieAVolk** [comment] 2018-02-22 22:45
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4860

**Closed by MarjieAVolk** 2018-02-22 22:45 UTC
Labels: Medium Priority
