### ISSUE TITLE
USER ISSUE: Old torches are not usable post-patch

### ISSUE THREAD

**Issue by dadaly** [StrangeLoopGames/EcoIssues#6858] opened 2018-04-01 21:18 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Have torches crafted pre-patch in your inventory
2. Attempt to move them within inventory, to a chest, etc. Nothing happens.

**Expected behavior:**
Torches should be useable, moveable, etc

**Actual behavior:**
Torches are not useable, moveable, etc

**Comment by MarjieAVolk** [comment] 2018-04-03 18:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6598

**Closed by MarjieAVolk** 2018-04-03 18:13 UTC
Labels: Medium Priority
