### ISSUE TITLE
USER ISSUE: Shovel wont open Door

### ISSUE THREAD

**Issue by TheLostOne21** [StrangeLoopGames/EcoIssues#3868] opened 2018-02-04 05:24 UTC
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Put  Wooden Shovel in Hand
Try to open door

**Expected behavior:**
Opened door

**Actual behavior:**
doesnt register

**Comment by g1franc** [comment] 2018-04-12 06:42
Still in 0.7.3.2

**Comment by MarjieAVolk** [comment] 2018-04-12 19:07
Just took a look at this - @SeanAtr0n the interact event isn't even getting sent to the server in this case.  And it does only happen with wooden shovel while not carrying anything, other shovels work.

**Comment by Ruthgar** [comment] 2018-07-27 07:58
This happening with wooden shovel to me only when i use it to move dirt. 1 piece is enough. 
Take shovell, take\place dirt, try to open door - not working. Switch to other tool and back to shovel - all ok.

**Comment by torchdragon** [comment] 2018-09-28 19:45
Still an issue on 7.7.2.

**Comment by GophTheGreat** [comment] 2019-05-11 04:28
Seems to work now. Reopen if necessary.

**Comment by SlayksWood** [comment] 2019-07-15 05:50
8.2.9 release-preview still an issue. Step to reproduce:
- spawn building with door.
- select shovel at toolbar. You can open door with RMB
- pick up Dirt, place Dirt. Try to open door (shovel still in hands). You can't open door

**Comment by SlayksWood** [comment] 2019-12-17 10:53
0.9.0 staging-1299 still an issue

**Comment by TimoNuernberg** [comment] 2020-12-31 12:02
9.1.9 problem still there, but it changed a bit.
after login, you can not open with an equipped shovel a door.
If you open the door without a shovel, then you can open/close (only this one) with an equipped shovel.

**Comment by Daniel-Magulado** [comment] 2021-02-24 00:50
Tested on 0.9.4 Develop-192.

Appears to be fixed. Tested all commented scenarios where it triggers the issue but could not reproduce.

Closing.

**Closed by Daniel-Magulado** 2021-02-24 00:50 UTC
Labels: Category: Gameplay, Priority: Low, Squad: Otter, Status: Fixed
