### ISSUE TITLE
Stuck in starting new singleplayer game

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8492] opened 2018-07-14 00:51 UTC
**Version:** 0.7.6.0 beta
Still here...
Full client reinstall help one time.
![default](https://user-images.githubusercontent.com/4980243/42719068-d955d152-8718-11e8-8112-92fd9f87c0c5.png)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2194527/output_log.txt)

(closed by alt+f4, esc not work)

**Comment by elfl0rd** [comment] 2018-07-14 01:55
Restart PC helped

**Comment by johnkslg** [comment] 2018-07-16 18:45
Have you seen this since reinstalling the client?

**Comment by johnkslg** [comment] 2018-07-16 19:17
Sean if you can help investigate this

**Comment by johnkslg** [comment] 2018-07-16 19:59
Reinstalling Eco fixed it.  Resolving as dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/8560

**Closed by johnkslg** 2018-07-16 19:59 UTC
Labels: Critical Priority
