### ISSUE TITLE
USER ISSUE: Sand not being produced 

### ISSUE THREAD

**Issue by TaylorACrock** [StrangeLoopGames/EcoIssues#4666] opened 2018-02-17 01:01 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I place all the ingredients (stone) on the masonry table to grind to sand and it says Ingredients 100%, Time 0%.

**Expected behavior:**
Produce sand

**Actual behavior:**
Nothing is made. Stuck at "Ingredients 100% Time 0%" perpetually

**Comment by MarjieAVolk** [comment] 2018-02-23 23:15
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4667

**Closed by MarjieAVolk** 2018-02-23 23:15 UTC
