### ISSUE TITLE
USER ISSUE: Frames drop significantly when facing a certain direction.

### ISSUE THREAD

**Issue by FroZenEscape** [StrangeLoopGames/EcoIssues#24969] opened 2024-06-03 21:33 UTC
\
**User Id: (slg234754)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
when i walk away from where i spawned and face a certain direction frames drop significantly, frames drop from 170+ to 26 and dont move unless i look away, it also seems to drop my frames down to about 40fps, after 30 minutes of playing.

**Expected behavior:**
no frames should drop 

**Actual behavior:**
frames drop when facing a spacific direction restart does not help, and frames decrease after 30 minutes of play

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO MODS, and a NEW random world, SOLO, no buildings. (consistant through new worlds)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-06-04 05:41
Please provide the necessary data as outlined here, so we can investigate the cause of the problem:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/e60e2f63-90e8-4052-aed1-f05129f3b428)

**Comment by D3nnis3n** [comment] 2024-06-11 07:39
Closing due to necessary information not provided, please feel free to open a new issue if you are able to provide the required information.

**Closed by D3nnis3n** 2024-06-11 07:39 UTC
Labels: Status: Needs Information
