### ISSUE TITLE
USER ISSUE: Fell trough the land

### ISSUE THREAD

**Issue by SirKahvi** [StrangeLoopGames/EcoIssues#4574] opened 2018-02-15 09:06 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. build on desert biome
2. chop bugged cactuses
3. move around desert biome :p

**Expected behavior:**
You fall trough the ground where ever and go in to a lightspeed fall.

**Actual behavior:**
Yes, actually I don't believe it is lightspeed. But fast AF. The screen goes yellow after awhile and the object in hand begins to warp and glow :O

**Comment by SirKahvi** [comment] 2018-02-15 09:07
Still falling.. Now the object in my hand is blue XD

**Comment by SirKahvi** [comment] 2018-02-15 09:09
Ok. Disconnecting and resuming fixed my situtation.

**Comment by metachronism** [comment] 2018-03-16 18:20
closing as dupe of other chunk building issues

**Closed by metachronism** 2018-03-16 18:20 UTC
Labels: High Priority
