### ISSUE TITLE
Blast Furnace and Bloomery produce same amount of Tailing in Result

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9649] opened 2018-10-05 14:53 UTC
Version: v0.7.7.2-beta

Steps to reproduce:
- order a project of 50 iron bar at blast furnace (smelting fully skilled)
- link a cart for the output

Expected behavior:
should result in 50 iron bar and 25 tailing

Actual behavior:
results in 50 iron bar and 50 tailing (same as bloomery)

![taling2](https://user-images.githubusercontent.com/38510829/46542597-13b8ff80-c8bf-11e8-873e-09cfeb1e011e.jpg)

**Comment by Nicolausi113** [comment] 2018-10-07 09:42
@D3nnis3n  Where do I get the fixed code from? 
I've downloaded the client again and is still the same!

**Comment by D3nnis3n** [comment] 2018-10-07 09:46
It was planned to be released in a hotfix, as it's just a workaround for now, but that one did not appear yet.

You can use my own fix until then, you need to replace the files in the download attached on your SERVER. (Mods/AutoGen/Recipes) Please notice that i do not take any warranty. Backup your own files before. It changes the recipes so that you can only craft 2 iron ingots at a time and get 1 tailing output. Resource usage and time have been doubled to balance it correctly.

[fix.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2453778/fix.zip)

**Comment by Nicolausi113** [comment] 2018-10-07 09:52
@D3nnis3n  Great -I'll try out (on my risk) – Thanks :)

**Comment by D3nnis3n** [comment] 2018-10-07 13:09
Everything went okay?

**Comment by Nicolausi113** [comment] 2018-10-07 15:30
For the first not, the server crashed at restart and I had very less time to go back online with the restored backup. But I try it again on a second machine more calm – so don’t worry, it was surly my mistake somewhere and I’m convinced that it worked for you!  So Thanks again!

**Comment by Nicolausi113** [comment] 2018-10-07 17:06
@D3nnis3n 
Now I can state a little more accurate to the fix, first it works, but should be taken with care, a crash can happen. And the Result may be confusing first time, an order of 2 peaces iron bar gives 4 iron bar and 2 tailings – a tailings project as mentioned earlier :)
The server has started without problem, but logging in client crashed the server first time.
An error message appeared: “Unity crashed, display driver has now been restored” (something in this sense). After this crash all runs now pretty!
Well, we got it – Thanks!

**Comment by D3nnis3n** [comment] 2018-10-30 13:07
Duplicate of #9867

**Closed by D3nnis3n** 2018-10-30 13:07 UTC
Labels: Medium Priority
