### ISSUE TITLE
USER ISSUE: Standing Glass Sign doesnt work

### ISSUE THREAD

**Issue by SkypeHiker** [StrangeLoopGames/EcoIssues#25027] opened 2024-08-12 21:03 UTC
\
**User Id: (bff58396-da9b-43d8-7034-08dc8d11157e)**
**Version:** 0.11.0.0 beta playtest-498

**Steps to Reproduce:**
Place a Standing Glass sign and try to write on it.

**Expected behavior:**
Text on the sign

**Actual behavior:**
No text on the Sign

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-08-12 22:45
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24957

**Closed by D3nnis3n** 2024-08-12 22:45 UTC
