### ISSUE TITLE
Shortcut for last used command / last chat message

### ISSUE THREAD

**Issue by lordmampf** [StrangeLoopGames/EcoIssues#3267] opened 2018-01-06 02:09 UTC
It would be great if you can press arrow up or something similar to change the current text in the 
"chat writing box" to the last used command or last chat message.

**Comment by MarjieAVolk** [comment] 2018-01-06 02:20
Yes we would like to add this eventually.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2585

**Closed by MarjieAVolk** 2018-01-06 02:20 UTC
