### ISSUE TITLE
USER ISSUE: Waterwheel produces power if placed mid air on a mountain

### ISSUE THREAD

**Issue by Juksefantomet** [StrangeLoopGames/EcoIssues#19886] opened 2021-01-01 13:40 UTC
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Create a waterwheel, find a tiny hilltop and shave one side of it.
place wheel so it overlaps with 1x layer of any type of block at the bottom.

**Expected behavior:**
It should not produce power as there is no water there

**Actual behavior:**
It produces 200mw

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2021-01-03 20:16
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2105

**Closed by D3nnis3n** 2021-01-03 20:16 UTC
