### ISSUE TITLE
USER ISSUE: FLoating logs

### ISSUE THREAD

**Issue by TwitchDrone** [StrangeLoopGames/EcoIssues#5024] opened 2018-02-24 02:59 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. I loaded the game
2. the logs were floating when i tried to pick them up they gave me this error

**Expected behavior:**
I WANTED MY LOGS ;-;

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-26 18:49
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-02-26 18:49 UTC
