### ISSUE TITLE
Mac Driver issues 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#429] opened 2016-07-04 00:59 UTC
http://ecoforum.strangeloopgames.com/topic/127/textures/45 ( read last post's)

might never be fixed since this could be an issue on apples side ?

**Comment by capnslipp** [comment] 2016-07-04 04:55
This seems to happen only on certain graphics cards, and AFAIR all are [the notorious Intel integrated chipsets(https://twitter.com/slowb1rd/status/747218433503174656) (occasionally causing issues for even 1st-party games).  @noblackthunder may be correct that some of these issues can't just be fixed, but I think it's less likely that they're buggy drivers and more likely that either:

* The cards don't support certain features which Eco's shaders are using, or
* The shader stage is taking too long for these cards and aborting, a potential product of the tile-based deferred rendering some of these cards use.

The first would be easier to solve; a lower-quality fallback shader should do the trick, assuming Unity can accurately detect missing card features.  The second, if the culprit, would be more difficult to solve.

Suggestion: For testing during the beta period, could we have a switch that changes all the shaders to basic Gouraud/Blinn–Phong/vertex shading?  That would certainly confirm for those having issues that the issue is part of the shader pipeline, and make the game still playable in worst-case scenerios.  It would also be handy for multiplayer testing in that it would allow us with a couple of 5-10 year old computers sitting around to drop the quality and play the game with friends using those too.

**Comment by Jrjungemann** [comment] 2016-12-01 16:22
This seems to still be an issue for me. Right now, stone is showing up properly but sand and grass are not. Any chance for a workaround?

**Comment by metachronism** [comment] 2016-12-06 22:30
the variant of the shader some cards use causes the shader to fail to compile, due to too many instructions being used.

Sean sort of had a handle on this, any further idea sean?

**Comment by noblackthunder** [comment] 2016-12-23 08:06
I have a person still having this issue for quite some time now on mail support still having this issue on several different computer configurations. I try to get some log files so that the cause of this issue can be tracked down. I attached some images he send us.
![unnamed 1](https://cloud.githubusercontent.com/assets/1668416/21449585/08801166-c8ef-11e6-9a16-a326764476b0.png)
![unnamed 2](https://cloud.githubusercontent.com/assets/1668416/21449583/087ff244-c8ef-11e6-9ac8-791dc8a99d44.png)
![unnamed 3](https://cloud.githubusercontent.com/assets/1668416/21449586/0883bbfe-c8ef-11e6-93df-788913e1f528.png)
![unnamed](https://cloud.githubusercontent.com/assets/1668416/21449584/087fff46-c8ef-11e6-8437-edde93b1c3f3.png)

**Comment by Incendius2016** [comment] 2016-12-23 13:59
Hey guys,

here are the files (logs) in question. Hope this helps, but I'm not sure if the importance of it is understood well enough? ;)

If so... thank you for that!


[Mac Screens & Logs 2.zip](https://github.com/StrangeLoopGames/EcoIssues/files/670880/Mac.Screens.Logs.2.zip)

**Comment by noblackthunder** [comment] 2017-01-02 05:48
http://ecoforum.strangeloopgames.com/topic/1242/ground-not-rendering

**Comment by SeanAtr0n** [comment] 2017-01-02 19:06
I submitted a fix for this last week, should be in the next client build. (a few days)

**Comment by noblackthunder** [comment] 2017-01-03 23:52
@Incendius2016 version 5.2 is out .. can you confirm it works?

**Comment by Incendius2016** [comment] 2017-01-04 03:39
Sorry... it doesn't. There seem to be ground textures rendered now... so you can't look through the ground any longer, but most of the textures are still messed up (mostly black) like before.
I will make some new screens and post them together with the unity logs of the different machines (Macs)... but this will take me a day or two.

I have to say that I'm somewhat disappointed... how can someone claim that a fix for something was submitted if it wasn't even understood, tested and confirmed? And why is a thread closed before the problem is really solved? I know... questions no one wants to hear and address. 

Please take a look at the picture and tell me that this is not what a couple of thousand kids, students and other paying customers are supposed to see when they take a look at Eco for the first time!?

![mac client 5_2](https://cloud.githubusercontent.com/assets/24733210/21630813/11f8377e-d235-11e6-9ce4-2f51942146e8.png)

@noblackthunder: I will include the specs in the screens like before... so you may get an idea where those textures go wrong, if you actually can find someone interested in looking? And just to cancel out the obvious excuse... the Windows client on the same machine works just fine... no messed up textures.

**Comment by noblackthunder** [comment] 2017-01-04 03:41
thanks ... its a step in the right direction though .. its something .. thanks for your help !

**Comment by SeanAtr0n** [comment] 2017-01-04 04:22
The change fixed issues on my 2010 macbook air in the editor. I'll check out the 5.2 client to see whats up

**Comment by SeanAtr0n** [comment] 2017-01-04 05:22
The title scene looks correct on my 2010 macbook air, however I can't join a server as it doesn't have enough memory to actually play the game.

Have you been able to join any servers? Your screenshot looks a lot like what the game could look like in early morning, it might look correct if you can get in to a server

**Comment by Incendius2016** [comment] 2017-01-04 05:47
@SeanAtrOn: Dude... give me some credit... you hopefully do not believe I would bother doing screenshots of the title scene without checking the actual game? I chose the title screen because its always the same and you can clearly see (at least thats what I thought) whats wrong or not wrong with the textures and/or shaders on the different machines. If you take the time to look at ALL the screens I posted and actually compare them, you might see the differences ... btw. is there a an early morning title screen? Try to take a look at the top two scan lines of the screens, those seem to be like they should be... but after that the rendering goes bad.

Btw.: I will pretend that you did not just told me that checking the Mac client on an 2010 MacBook Air that cannot even actually run the game made you come up with any conclusions regarding the state of the Mac client at all. Because that would be completely ridiculous and pathetic!

Please go to your boss and ask him to order some Macs today (maybe an actual iMac from the AppleStore and another slightly older one from ebay or craigslist?)! 

As the Queen would say: "I am not amused!"

**Comment by SeanAtr0n** [comment] 2017-01-04 06:13
@Incendius2016 I was able to reproduce the original problem and fix it on my outdated hardware... seems pretty reasonable to ask if it also fixed your problem. Usually we close bugs when we think they are fixed and reopen them if necessary. Looks like we found a new problem that I can't reproduce on this hardware so we will probably need to find another mac for testing. Also, please consider giving us some credit... I spent 2 days over the holidays fixing the first issue.

**Comment by SeanAtr0n** [comment] 2017-01-04 22:23
Adding John, we may need to get a mid-high end mac for testing.

I tested on the low-end iMac we have in the office and couldn't reproduce the black-screen.

**Comment by SeanAtr0n** [comment] 2017-01-09 19:59
Tested on a 2016 macbook w/ Intel HD Graphics 515 over the weekend, issue wasn't present. We are looking into options for testing w/ other graphics cards.

Based on which screenshots show black trees above I'm guessing the darkness bug is present in:
2011 Renderer: AMD Radeon HD 6970M OpenGL Engine
2008 Renderer: ATI Radeon HD 5770 OpenGL Engine

It'd be helpful if we could get a confirmation of which systems are fixed and which are too dark.

**Comment by Jrjungemann** [comment] 2017-01-31 16:16
I have a late 2016 iMac with AMD Radeon R9 M390. It is working for me in 5.3.

**Comment by SeanAtr0n** [comment] 2017-02-04 03:20
Upside down tools should be fixed in 5.4, i'm not sure about the darkness issue... would be good to get more info if anyone can reliably reproduce it.

**Comment by Incendius2016** [comment] 2017-02-06 20:25
![screen shot 2017-02-06 at 21 18 13](https://cloud.githubusercontent.com/assets/24733210/22664857/c4d33b86-ecb2-11e6-9168-4fd829560961.png)

**Comment by SeanAtr0n** [comment] 2017-02-06 20:33
Thanks Incendius! Is it always like this for you or does it turn black at certain times? If you log-in to a server do the colors still look black?

**Comment by noblackthunder** [comment] 2017-02-26 12:41
http://ecoforum.strangeloopgames.com:4567/topic/1780/graphic-problems-on-mac/3

**Comment by peternightingale** [comment] 2017-07-17 10:08
If it's helpful, on the last build everything was rendering perfectly on my 2 macs, but since the update to 0.5.6 I have been having this issue. So if something changed between the two builds, it made the problem worse.  The graphics cards in my macs are an Intel HD Graphics 4000 and an Intel Iris Pro.

If I run the windows client on these Macs, everything renders perfectly.

**Comment by SeanAtr0n** [comment] 2017-09-28 23:52
It seems these issues are resolved, closing.

**Closed by SeanAtr0n** 2017-09-28 23:52 UTC
Labels: Critical Priority, High Priority
