### ISSUE TITLE
Resolution can't exceed 1280x720

### ISSUE THREAD

**Issue by jeffstaples1982** [StrangeLoopGames/EcoIssues#13963] opened 2019-12-01 23:54 UTC
It was 1920x1080 when I first launched and played, went to increase the graphics settings and it defaulted back down to 1280x720.  Running on a Gigabyte Nvidia GTX 1080

![Capture](https://user-images.githubusercontent.com/2830144/69922651-218af600-146c-11ea-90d0-b2e6b0695b1f.PNG)

![20191201184315_1](https://user-images.githubusercontent.com/2830144/69922596-a295bd80-146b-11ea-9edd-6504f7e616bb.jpg)

**Comment by D3nnis3n** [comment] 2019-12-02 09:28
Can you attach a screenshot of your display resolution settings in Windows and probably also from the NVIDIA settings?

**Comment by jeffstaples1982** [comment] 2019-12-02 10:00
![Windows](https://user-images.githubusercontent.com/2830144/69949602-d8fd2800-14bf-11ea-86c2-2c68cca1ae73.PNG)

![Capture](https://user-images.githubusercontent.com/2830144/69949686-fb8f4100-14bf-11ea-8cac-6c4a13c598e7.PNG)

![Captureq](https://user-images.githubusercontent.com/2830144/69949697-fe8a3180-14bf-11ea-9a96-9b3630b2489d.PNG)

I did notice while doing this that my main monitors native resolution is 1280x720 but I force 1920x1080 on it and never had an issue with any game underperforming, nor have I had any issues with any games not having 1920x1080 as a selectable option.

I did make my smaller Sceptre the main monitor to see if I can get 1920x1080 on that one and the option *did* come up in the settings.  I set the graphics to 1920x1080, saved it, the made the Sanyo the main monitor and the graphics retained the 1920x1080 resolution and everything is fine now.

**Comment by D3nnis3n** [comment] 2019-12-02 10:17
Doesn't sound like an actual issue to me if the native resolution of the other monitor is just 1280x720, then it's supposed to only display that. If you can force it via other means or not is not really the business of Eco. I'm closing this issue therefore, but am glad that you found a way to get what you wanted :)

**Closed** 2019-12-02 10:17 UTC
Labels: Investigate

**Comment by jeffstaples1982** [comment] 2019-12-02 10:30
Every other game Ive ever played I can select 1920x1080 from the graphic settings screen on the Sanyo, I don't have to do this weird switch around like I have to do with Eco...does seem like Ecos business to me if it cant adjust to what the actual resolution of the main monitor is rather than falling back on a monitors native resolution as the max resolution allowed...many monitors has native resolutions less than what they can actually run at...but whatever you say.

**Comment by D3nnis3n** [comment] 2019-12-02 10:42
Eco is currently not very multi-monitor friendly, but that's a different reported issue. In this case it does what it is supposed to do. The issue is more that it doesn't actually understand it's on a second monitor, but using native resolution of the main monitor.
