### ISSUE TITLE
USER ISSUE: Grass growing on tilled soil

### ISSUE THREAD

**Issue by aurirules** [StrangeLoopGames/EcoIssues#5821] opened 2018-03-10 04:59 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Till a field
2. Let time pass
3. Grass will grow on tilled squares
4. Unable to remove grass by re-tilling the soil (using the hoe). Must instead first dig up the soil with the shovel, and then re-till the land.

**Expected behavior:**
Remove the grass by re-tilling the soil directly, which is how it acts when you first till a new field.	

**Actual behavior:**
You must first use the shovel to dig up the square, return the soil, then you can till the soil again.

**Comment by MarjieAVolk** [comment] 2018-03-12 23:33
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4185

**Closed by MarjieAVolk** 2018-03-12 23:33 UTC
