### ISSUE TITLE
USER ISSUE: Number of Poeple Alowed On Server

### ISSUE THREAD

**Issue by Firestar000** [StrangeLoopGames/EcoIssues#9610] opened 2018-09-30 15:59 UTC
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Deafult settings for server public-yes ; password- " "  ; max connections 5

**Expected behavior:**
Allowy my friends to connect to my server.

**Actual behavior:**
No one can join, the server shows up, but it only allows 1 person total to be on the map.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
No one can join, the server shows up, but it only allows 1 person total to be on the map.

**Comment by Spydarlee** [comment] 2018-10-09 15:29
Haven't had any luck reproducing this yet. Did you restart the server between changing the max connections value?

**Comment by Firestar000** [comment] 2018-10-09 20:50
I tired restarting it and not restarting it.
I am using both the server from steam tools and the server from
strangeloops websight.  On one I'll restart it.  On the other I won't
restart it.  I did try that.

**Comment by Spydarlee** [comment] 2018-10-11 13:48
Hmm, okay thank you. I still cannot reproduce this issue, so I have a few questions if you don't mind!

- If you reset the max connections to -1 do you still have the same issue?
- Have you tried any other builds, e.g. 'Staging' or 'Bleeding Edge'?
- Have any of your friends tried hosting the server and you joining theirs? Do they get the same issue?

**Comment by Firestar000** [comment] 2018-10-12 06:44
When I reset max connections to -1 I still have the issues.
I have not tried other buildings.
And I will try letting them host the server instead.

Sent from Mail for Windows 10

**Comment by D3nnis3n** [comment] 2019-03-03 21:43
Closing, because not reproducable. Reopen if it still occurs on the most recent version.

**Closed by D3nnis3n** 2019-03-03 21:43 UTC
Labels: Investigate, Not reproduced
