### ISSUE TITLE
[8.0.0 bleeding edge] Massive frame rate drop when logging or mining

### ISSUE THREAD

**Issue by Mosseman** [StrangeLoopGames/EcoIssues#11043] opened 2019-02-02 15:50 UTC
When harvesting anything in 8.0.0, I notice a very large frame rate drop when chopping down trees, gathering wood pulp or mining rocks. It seems to occur when the new "no skill points gained" notification popup appears in the bottom left corner of the screen.

I do not have the relevant logging or mining skills. Will test to see if they make a difference.

**Comment by Mosseman** [comment] 2019-02-02 18:50
I've picked up the mining skill and can confirm that having the skills results in this bug not presenting.

**Comment by SlayksWood** [comment] 2019-04-24 13:37
I can't reproduce. Do you have this problem now?
If it happens again, please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment] 2019-04-29 08:11
merged with #11473

**Closed by SlayksWood** 2019-04-29 08:11 UTC
Labels: Investigate, Needs Information
