### ISSUE TITLE
Some Skills might not be working as intended.

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#10174] opened 2018-12-02 12:10 UTC
Looking at skills to make modules for the wiki I have noticed a few things that might not be working the way that was intended.

Bow Efficiency: 
The calories burned by using a bow is currently coded to use the hunting skill. Only 1 level of Bow efficiency is currently required to unlock Bow Damage. Therefore the rest of the level unlocks for this skill are useless. 

Hunting:
Level 1 hunting allows you to reduce the calorie cost of using a bow by 14%. This probably should be on bow efficiency not hunting.

Clothes Making Speed:
It looks like no Recipes use Clothes Making Speed to improve their craft time. 

:)

**Comment by Deantwo** [comment] 2018-12-09 21:45
Duplicate of #8241

**Closed** 2019-01-07 05:48 UTC
