### ISSUE TITLE
Players with empty nicknames go to the server.

### ISSUE THREAD

**Issue by alexandrage** [StrangeLoopGames/EcoIssues#4568] opened 2018-02-15 07:25 UTC
**Version:** 0.7.1.2 beta
Players with empty nicknames go to the server.

**Comment by alexandrage** [comment] 2018-02-15 07:27
http://dl3.joxi.net/drive/2018/02/15/0008/0303/545071/71/f4eecd7545.jpg

**Comment by MarjieAVolk** [comment] 2018-02-24 00:30
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4160

I will paste your screenshot in there.

**Closed by MarjieAVolk** 2018-02-24 00:30 UTC
