### ISSUE TITLE
8.0.7: Tailings tooltip misleading

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#11816] opened 2019-03-30 19:28 UTC
As the image shows, the tooltip implies that tailings can safely be contained within buildings when they actually are best stored as deep as possible. 

Additionally, tailings IRL are a waste product from separating ores from stone during **mining** rather than **smelting**. Since tailings count as a block I reckon it'd be a hard thing to create extra debris which forms as a block upon placement. I would therefore suggest renaming Tailings to Slag

Suggested text: Waste product from smelting. When left on soil the run-off will create pollution; killing nearby plants and seeping into the water water supply, Bury _deep_ in rock to neutralize.

For reference, compare these two articles:
https://en.wikipedia.org/wiki/Tailings
https://en.wikipedia.org/wiki/Slag

![20190330201723_1](https://user-images.githubusercontent.com/841990/55280662-f96d5500-5328-11e9-903a-72016d2e346a.jpg)

**Comment by WeaselDog** [comment] 2019-03-31 14:48
You are right that tooltip is misleading, but tailing are created when the ore is processed through an extraction process not currently in Eco. Mining itself does not create tailing. Overburden is the waste product from mining.

**Comment by redwyre** [comment] 2019-03-31 14:57
There are changes coming for this in 8.2, in the near future.

**Comment by D3nnis3n** [comment] 2019-04-01 08:14
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9427

**Closed by D3nnis3n** 2019-04-01 08:14 UTC
