### ISSUE TITLE
USER ISSUE: Cannot create a new local game without generating new

### ISSUE THREAD

**Issue by dlouwers** [StrangeLoopGames/EcoIssues#6916] opened 2018-04-03 11:28 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Start a new world with the _Geberate New_ box unticked.

**Expected behavior:**
Started a new Game.

**Actual behavior:**
The following error message popped up:
```
Could not create save file: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data\Server\Storage\DefaultWorld is a directory
```
Extra info: I did create a directory there. If it isn't there but DefaultWorld.db and DefaultWorld.eco are there it will say that it cannot find DefaultWorld with the same path. This is suggesting that it doesn't look for the extension.

**Comment by MarjieAVolk** [comment] 2018-04-03 22:17
Yes you are right - it looks for a file named DefaultWorld with no extension.  That should be what you get in that folder.  Is that not the case?  Have you tried steam's verify integrity of game files?

Also, are you on Linux?

**Comment by MarjieAVolk** [comment] 2018-04-06 21:27
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6930

**Closed by MarjieAVolk** 2018-04-06 21:27 UTC
