### ISSUE TITLE
Linux issue: No main menu

### ISSUE THREAD

**Issue by LiamDawe** [StrangeLoopGames/EcoIssues#6145] opened 2018-03-16 14:09 UTC
The game on Ubuntu 17.10 from Steam doesn't seem to actually give me a main menu. I get the music and the background and a mouse cursor, but no actual menu so I can't do anything.

Here's my player log file: https://gist.github.com/LiamDawe/c0c03a9289f807bd3828b1db6016e050

**Comment by MarjieAVolk** [comment] 2018-03-20 22:15
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4281 - Unfortunately, I don't think we have a workaround right now.

**Closed by MarjieAVolk** 2018-03-20 22:15 UTC

**Comment by MarjieAVolk** [comment] 2018-03-26 18:13
@Sebi-M thanks for the information!  I will copy this suggestion into the currently open bug for the main menu issue.

**Comment by Sebi-M** [comment] 2018-03-26 18:32
I mixed something up here; this is the issue I'm currently having as well. Before I had #6158, which I worked around here.
Do I have the possibility to get a debug build or sth. like that? Are you on discord?

**Comment by MarjieAVolk** [comment] 2018-03-26 18:39
Oh lol, well oh well the comment in #6158 will be unhelpful I guess.

Yeah, we are mostly all in office / on discord right now.  You want like source code access?
