### ISSUE TITLE
USER ISSUE: Fishing - Invisible Fish in Inventory

### ISSUE THREAD

**Issue by Trin-Tragula** [StrangeLoopGames/EcoIssues#5223] opened 2018-02-28 14:57 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Fish (fish will not appear in inventory)
2. try moving stuff in empty slots
3. Fish appears but is buggy

**Expected behavior:**
Fish should have appeared in Inventory when catching fish.

**Actual behavior:**
Instead it appears an invisible buggy item.

**Comment by MarjieAVolk** [comment] 2018-02-28 19:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

This will be fixed in the next staging build.

**Closed by MarjieAVolk** 2018-02-28 19:16 UTC
