### ISSUE TITLE
USER ISSUE: Kiln Tier2?

### ISSUE THREAD

**Issue by Msgt-Joe** [StrangeLoopGames/EcoIssues#4178] opened 2018-02-09 13:31 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Can not operate kiln, because it states it needs a tier2 room, but without a kiln i can't get any of those.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-09 19:32
This issue should be fixed as of 7.0.5.  It's possible that existing kilns might not be migrated correctly - If you pick up your kiln and place it back down, does this fix it?

**Comment by Msgt-Joe** [comment] 2018-02-09 19:35
No, tried it multiple times, with no luck.

**Comment by MarjieAVolk** [comment] 2018-02-09 20:23
We got another report of this, so closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4173

You aren't on the same server as this other person, are you?

**Closed by MarjieAVolk** 2018-02-09 20:23 UTC
