### ISSUE TITLE
USER ISSUE: Gravity don't move water

### ISSUE THREAD

**Issue by ReiParasita** [StrangeLoopGames/EcoIssues#23222] opened 2022-05-30 04:30 UTC
User Id: Rei_Parasita
Version: 0.9.5.2 beta release-315

Steps to Reproduce:
Create a tunnel that leads underneath a lake.

Expected behavior:
Gravity should push water into the tunnel.

Actual behavior:
The water doesn't move at all.

Do you have mods installed? Does the issue happen when no mods are installed?:
No

Footage of the happening:

https://user-images.githubusercontent.com/25543840/170917352-bbcc6f2a-149b-41ba-a253-f244c922ca90.mp4

![Eco_Issue_09](https://user-images.githubusercontent.com/25543840/170917489-9180ae4a-af59-4810-b5e9-429f880a12ab.png)

**Comment by D3nnis3n** [comment] 2022-05-30 07:34
Not a bug, we currently don't have water physics, duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9971.

**Closed by D3nnis3n** 2022-05-30 07:34 UTC
