### ISSUE TITLE
USER ISSUE: dc when edit plot [wtplaytest]

### ISSUE THREAD

**Issue by LarkPlayz** [StrangeLoopGames/EcoIssues#24103] opened 2023-11-28 03:16 UTC
\
**User Id: (slg200418)**
**Version:** 0.10.0.0 beta playtest-267

**Steps to Reproduce:**
wt play test, hit edit claim, get booted.

**Expected behavior:**
allowed me to edit my claim

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.DeedEditingUtil.CanClaimAtPos(User user, Settlement claimingSettlement</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-01 22:44
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24106

**Closed by D3nnis3n** 2023-12-01 22:44 UTC
