### ISSUE TITLE
USER ISSUE: unable to connect

### ISSUE THREAD

**Issue by malro57** [StrangeLoopGames/EcoIssues#19935] opened 2021-01-07 14:55 UTC
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
try to join my last game

**Expected behavior:**
connect

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Login info could not be verified. Our auth servers may be down.

<size=60,00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2021-01-07 14:58
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19936

**Closed by D3nnis3n** 2021-01-07 14:58 UTC
