### ISSUE TITLE
Regular Crashes of the game.   

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#24913] opened 2024-04-29 16:07 UTC
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15151803/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15151804/Player-prev.log)

I have similar issues to the people who posted recently.  My game seems to crash after about 20 minutes of game play.   After the first crash it seems to crash at an increasing rate, until my computer crashes all together, getting the BSOD (blue screen of death)   Once it reboots from the BSOD, it seems to start the cycle over with about 20 minutes of game play, then 10, then 5ish(those are estimates).    I am aware that it very well may not be the game, but my PC Rig, but I cannot really tell what is going on from reading the files.  If someone could point me in the right direction, that would be great.   

When it crashes, I receive the UNITY Crash popup similar to what was shared in this post.   https://github.com/StrangeLoopGames/EcoIssues/issues/24911

Thank you in advance for all the help!  I love this game, but it is frustrating when it constantly crashes.   I don't usually have issues with other games, unless my drivers get out of date.

**Comment by D3nnis3n** [comment] 2024-04-30 18:30
Could you please attach the crash dumps saved on your PC for Eco?

To do so, open the program "run", enter "%UserProfile%\AppData\Local\Temp\Strange Loop Games\Eco" and package the contained .dmp files, uploading them here.

**Comment by sirPattrick** [comment] 2024-04-30 21:58
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/15171487/crash.dmp)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15171488/Player.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15171490/Player.log)
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/15171491/crash.dmp)
Here are my most recent DMP files from 4/28.  One at 2:06, and another at 2:11 PM.  I will be playing again today, and will upload any Dmp files from today as well.

**Comment by sirPattrick** [comment] 2024-04-30 23:30
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15172170/Player.log)
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/15172188/crash.dmp)

**Comment by sirPattrick** [comment] 2024-05-01 01:04
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/15172548/crash.dmp)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15172549/Player.log)

**Comment by sirPattrick** [comment] 2024-05-01 02:14
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/15172843/crash.dmp)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15172844/Player.log)

**Comment by sirPattrick** [comment] 2024-05-01 02:51
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/15173026/crash.dmp)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15173027/Player.log)

**Comment by sirPattrick** [comment] 2024-05-01 02:57
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/15173048/crash.dmp)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15173049/Player.log)
Hopefully last one for the night.

**Comment by sirPattrick** [comment] 2024-05-01 22:00
Do you want me to keep adding new dump files to this?

**Comment by sirPattrick** [comment] 2024-05-01 22:31
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15181930/Player.log)
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/15181931/crash.dmp)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15181933/Player.log)
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/15181934/crash.dmp)

**Comment by gzatravkin** [comment] 2024-05-01 22:45
So it seems to be hardware/driver issue, GPU specifically. Several crash dumps points to nvwgf2umx, by example 
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/53317567/de1d5396-4592-4798-8dbb-cc09ba678c57)

You can check this link https://answers.microsoft.com/en-us/windows/forum/all/game-crash-faulting-module-name-nvwgf2umxdll/5c6171b0-92df-483c-be83-86219ab8d17a

**Comment by sirPattrick** [comment] 2024-05-01 23:26
I looked at that link, and didn't really find anything too helpful.   I downloaded Furmark and ran the P1080 benchmark and got the below results, and had no issues running the benchmark.   
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/36024353/7b88cdde-2499-4c83-b7b0-a9ac4d4f5941)

**Comment by sirPattrick** [comment] 2024-05-01 23:34
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/15182206/crash.dmp)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15182207/Player.log)

**Comment by D3nnis3n** [comment] 2024-05-02 14:46
What my colleague tried to say is that this crash is not caused by Eco and as such we can't do anything to resolve it.

nvwgf2umx.dll is from NVIDIA - the cause can vary from overclocking, hardware issues, driver incompatibility with anything else on the PC and cannot be diagnosed by us. We only can say for sure there is no Eco related code in the dumps.

Users on the internet have suggested a variety of things that fixed their issues (and the link Grigoriy posted was just one of many, try searching for "nvwgf2umx.dll crash" - uninstalling the NVIDIA drivers with DDU and reinstalling in safe mode, replacing their graphics card, reinstalling Windows (sometimes a broken Windows Update seems to have caused it), removing NVIDIA 3D Vision if installed and more. It's not really possible for us to say what exactly will help in your case and only you'll be able to figure out yourself what the exact problem in your case is.

As such I am closing this issue, as there is no measures we can take to address the problem. Please feel free to note if you found out what was the precise cause, so other users could find it.

**Closed by D3nnis3n** 2024-05-02 14:46 UTC

**Comment by sirPattrick** [comment] 2024-05-04 03:27
Using the DDU to uninstall the driver seems to have cleared up the issue, just so you all know.

**Comment by sirPattrick** [comment] 2024-05-06 15:47
The DDU seemed to help for about a day or two, and now it is crashing regularly again.   Guess I need to do more digging.   Thanks for the help though.

**Comment by sirPattrick** [comment] 2024-08-18 16:36
Hello All after a lot of trouble shooting, it appears that the Intel Chip situation was affecting my PC, after reflashing(installing) the newest BIOS for my ASUS motherboard, it appears that the game is much more stable.
