### ISSUE TITLE
[Client] 7.2.2 Drag and drop into chests Bug

### ISSUE THREAD

**Issue by kroovysteph** [StrangeLoopGames/EcoIssues#5670] opened 2018-03-08 11:01 UTC
**When?**
When drag and drop items from your inventory into storage chests.

**What?**
In the process of dragging, the item disappears from the cursor. It leaves it's icon on the screen.
The item is not transfered into the storage chest.

![drag_and_drop](https://user-images.githubusercontent.com/8964376/37147523-7c961e1e-22c7-11e8-9cfb-94c4d950b806.png)

**Comment by ArmandVestibule** [comment] 2018-03-08 18:16
#3841 has confirmation of this bug and progress is being followed there. It has a workaround of alt+tabbing to re-render the UI.

**Comment by MarjieAVolk** [comment] 2018-03-08 22:32
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-03-08 22:32 UTC
