### ISSUE TITLE
USER ISSUE: Fishing

### ISSUE THREAD

**Issue by alchemican** [StrangeLoopGames/EcoIssues#4902] opened 2018-02-21 15:23 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. catching fish

**Expected behavior:**
fish is to find in Inventory

**Actual behavior:**
Fish did not appear. After server restart fish apears in inventory

**Comment by MarjieAVolk** [comment] 2018-02-22 19:48
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

**Closed by MarjieAVolk** 2018-02-22 19:48 UTC
