### ISSUE TITLE
Staging 7.2.0 server-Client not updating blocks well, if at all at times.

### ISSUE THREAD

**Issue by Malaras** [StrangeLoopGames/EcoIssues#4996] opened 2018-02-23 15:06 UTC
I'm running a server from home, i hit a block(stone) and it's not updating the client for what ever reason. It's gone cause i can't hit it again. Just not updating.

**Comment by Malaras** [comment] 2018-02-23 15:19
![screenshot 2018-02-23 10 17 03](https://user-images.githubusercontent.com/1544846/36601377-fd3550c0-1882-11e8-9ef3-4d3ee573a3cb.png)

**Comment by MarjieAVolk** [comment] 2018-02-23 23:30
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3897

**Closed by MarjieAVolk** 2018-02-23 23:30 UTC
