### ISSUE TITLE
USER ISSUE: crash picking up falling log that was floating in sky

### ISSUE THREAD

**Issue by projdarkmoon** [StrangeLoopGames/EcoIssues#5268] opened 2018-03-01 16:49 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. falling log from sky
2. picked up falling log from sky

**Expected behavior:**
picked up the log

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment] 2018-03-01 18:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Closed by MarjieAVolk** 2018-03-01 18:32 UTC
