### ISSUE TITLE
USER ISSUE: Server automatic restart not disable

### ISSUE THREAD

**Issue by D3vil787** [StrangeLoopGames/EcoIssues#24347] opened 2023-12-21 16:10 UTC
\
**User Id: (slg205740)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Auto shutdown hour = -1

**Expected behavior:**
server don`t restart

**Actual behavior:**
server restart at previous scecific time

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no. yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-21 16:59
The integrated function only turns the server off, it does not restart it - for that you need something else. This works as inended.

**Comment by D3vil787** [comment] 2023-12-22 04:41
Ticket about argument -1 don`t disable shutdown, not about restart.

**Comment by D3nnis3n** [comment] 2023-12-22 15:59
Cannot reproduce, this config does not shutdown the server:

> {
>   "AutoShutdownHour": -1,
>   "AutoShutdownMessage": "Automatic Restart",
>   "ReasonForAutoShutdown": "Restart",
>   "CountdownStart": 30,
>   "CountdownIntervals": [
>     60,
>     45,
>     30,
>     15,
>     5,
>     3,
>     1
>   ]
> }

**Comment by D3vil787** [comment] 2023-12-23 08:33
На моем сервере проблема проявляется так:
1. Ставлю время выключения, например 10.
2. Хочу отменить запланированное выключение, ставлю -1
3. Сервер все равно перезагружается в 10.

**Comment by D3nnis3n** [comment] 2023-12-23 23:10
We're not able to reproduce that, once the config has been adjusted to -1 the reboot does no longer happen.
You sure your config looks like above?

**Comment by D3nnis3n** [comment] 2023-12-31 14:23
Closing due to no reproduction case and no further information available.

**Closed by D3nnis3n** 2023-12-31 14:23 UTC
Labels: Status: Not reproduced
