### ISSUE TITLE
Can't use chat commands on my server.

### ISSUE THREAD

**Issue by geministorm8** [StrangeLoopGames/EcoIssues#4344] opened 2018-02-11 18:45 UTC
Whenever I attempt to use the chat commands, I get booted out of the server, and have to relog, accompanied by this report:
______________________________

Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Value cannot be null.
Parameter name: key

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)
_____________________________________________

What can I do to circumvent this?

**Comment by ZeelNightwolf** [comment] 2018-02-13 22:00
A user on our Server is also having this issue. He receives the same error. I have had him reinstall the SLG client clean but it did not help.

**Comment by MarjieAVolk** [comment] 2018-02-13 22:03
It seems this problem happens when you try to use a chat command without passing it the parameters it wants.  To get around this, for now, you can type /help and the command name in order to figure out how to use the command.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4391

**Closed by MarjieAVolk** 2018-02-13 22:03 UTC
Labels: Medium Priority
