### ISSUE TITLE
USER ISSUE: Can't type in properly in order to login

### ISSUE THREAD

**Issue by petarvasilev91** [StrangeLoopGames/EcoIssues#8629] opened 2018-07-19 11:34 UTC
**Version:** 0.7.6.1 beta

**Steps to Reproduce:**
When I type in letters for my username the letters are repeated, the same happens even when I try to copy the username. I am running Ubuntu 16.04

**Expected behavior:**
Be able to type in and login without issues

**Comment by SeanAtr0n** [comment] 2018-07-21 00:13
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3580

there are various ways to make it work mentioned in that thread

**Closed by SeanAtr0n** 2018-07-21 00:13 UTC
Labels: High Priority, Needs Triage
