### ISSUE TITLE
Crash in repair attributes

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3571] opened 2018-01-21 19:01 UTC
![screenshot_20180120-183551](https://user-images.githubusercontent.com/3536496/35197830-70e6f38c-fe9a-11e7-84e8-9f8e0795ac2f.png)

**Comment by metachronism** [comment] 2018-01-21 22:53
dupe of #3564 and #3555 ?

**Comment by MarjieAVolk** [comment] 2018-01-22 19:11
Looks like it

**Closed by MarjieAVolk** 2018-01-22 19:11 UTC
Labels: High Priority
