### ISSUE TITLE
USER ISSUE: Sickle triggers animation without interacting

### ISSUE THREAD

**Issue by FireByTrial** [StrangeLoopGames/EcoIssues#24272] opened 2023-12-19 04:48 UTC
\
**User Id: (slg167222)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
Have a stone stone sickle equipped, look at arctic willow

**Expected behavior:**
no animation until clicking on "reap"

**Actual behavior:**
just looking at the arctic willow triggers the animation

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-19 11:10
Cannot reproduce, needs more information.

**Comment by D3nnis3n** [comment] 2024-01-11 18:29
Closing due to not being reproducable and no more information provided.

**Closed by D3nnis3n** 2024-01-11 18:29 UTC
Labels: Status: Needs Information, Status: Not reproduced
