### ISSUE TITLE
Got exception at processing message

### ISSUE THREAD

**Issue by Arranoa-jolasten** [StrangeLoopGames/EcoIssues#25066] opened 2024-08-18 18:16 UTC
[16:44:26.171] [327] [Error] [Eco] Got exception at processing message from Woolsy:                         [Ping: 39 ms]   [CPU: 0.6 ms]   [In: ∞ k/s]     [Out: ∞ k/s]    . Exception: System.Exception: Don't know elementType = 101
   at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeObject(MemoryStream stream, BSONObject obj)
   at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
   at Eco.Shared.Networking.NetMessage.DecodePacket(ReadOnlySpan`1 message)
   at Eco.Plugins.Networking.NetworkServer.HandleIncomingDataMessage(UdpDataMessage& message). The message length is: 69 and text representation is idރmethodViewRPCargs��
14600args��y  
query�

**Comment by D3nnis3n** [comment] 2024-08-18 20:15
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25063

**Closed by D3nnis3n** 2024-08-18 20:15 UTC
