### ISSUE TITLE
USER ISSUE: boat fly

### ISSUE THREAD

**Issue by borodac** [StrangeLoopGames/EcoIssues#24148] opened 2023-12-13 00:27 UTC
\
**User Id: (El_Boroda**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
steer the boat

**Expected behavior:**
swim on surface water

**Actual behavior:**
boat(litle canoe) start soon fly if sail boat under building bridge to line

**Do you have mods installed? Does the issue happen when no mods are installed?:**
clear

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment] 2023-12-14 18:58
Hi @borodac , thank you for your report. I have however unable to reproduce as per your description. 
would you be able to share a video of this happening? or can you show me via discord (pm me: TwixterZ)

**Comment by borodac** [comment] 2023-12-15 07:25
the question is closed, you have banned building over the sea

**Comment by bobbah** [comment] 2023-12-18 00:42
This behavior can be seen if you dig a canal tunnel, until a server reboot occurs it seems that there are areas where boats are no longer impacted by gravity

**Comment by DragonDev1906** [comment] 2024-01-10 23:34
I've had this happen, too, and have seen it happen to others. I don't know if it is related to server restarts, my current guess is that it has something to do with the heightmap. I've just tried it in one of our canal tunnels (long after it has been built).

It is especially noticeable in long tunnels or on water slopes (see screenshots).

Another thing that might help: While in this state there seems to be no friction. If you stop holding `W` you'll just continue gliding/sliding/flying forward.

If the reason is due to specific blocks those would have to include normal terrain blocks AND some building blocks like hewn logs.

### Tunnels and Bridges where I've seen it happen
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/8270201/07858229-463c-40c2-85d1-712c08160b2c)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/8270201/dad3f228-629e-4204-9aa4-ba2524528221)

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/8270201/eb4ebbae-20af-4e33-b8a8-118b6bd432e3)

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/8270201/dd49eae4-3a62-45af-a3dc-cf5c844a7eaa)

### Screenshot of the first time it happened
![IMG_0295](https://github.com/StrangeLoopGames/EcoIssues/assets/8270201/02b20817-e1c8-4653-af6f-4f4ec8a71233)

### Screenshots I've just made, long after the canal has been built and after multiple server restarts
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/8270201/ec81c05c-8723-4255-bd34-195b0edd11d5)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/8270201/bba70467-cac6-45e3-8ae8-628453dccf4d)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/8270201/e81b5e13-e268-4001-880d-81ac21514539)

**Comment by TwixterZ** [comment] 2024-06-26 07:31
we have created a fix for this issue to be released in upcoming patch, if similar problem persist moving forward. please let us know.

**Closed by TwixterZ** 2024-06-26 07:31 UTC
Labels: Status: Needs Information
