### ISSUE TITLE
USER ISSUE: Blackscreen on returning to server

### ISSUE THREAD

**Issue by Paularius1** [StrangeLoopGames/EcoIssues#24192] opened 2023-12-14 00:47 UTC
\
**User Id: (slg234682)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
I logged back into the server. I can see the Hud, i can press escape to go to the menu. I can press tab to free the mouse and move it around. Open things with hot keys. But my game screen is black and my character cant be moved or does anything.

**Expected behavior:**
I should be able to see the game and move around.

**Actual behavior:**
I can see the Hud, i can press escape to go to the menu. I can press tab to free the mouse and move it around. Open things with hot keys. But my game screen is black and my character cant be moved or does anything.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Paularius1** [comment] 2023-12-14 00:50
Forgot to upload the files. 

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13667043/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13667044/Player-prev.log)

This is a screenshot of what i see

![20231214002242_1](https://github.com/StrangeLoopGames/EcoIssues/assets/153783606/1afe74c7-3366-4fbb-bb72-3d0fad87b3d2)

**Comment by Paularius1** [comment] 2023-12-14 21:26
I have a small update. A friend who was on the server before had the same issue.

To test it further i saved the world files and then remade a fresh world. At first it was fine and it worked but when i logged out and logged back in i got the same black screen. I did this process again and i got the same issue.

For a third time i went and changed the world height setting from 180 back to 160 then refreshed the world. I could log out and log back in with no issues several time.

So i feel the issue is tied to a custom world height value.

**Comment by D3nnis3n** [comment] 2023-12-15 12:53
Caused by invalid height settings, closing. We're looking internally for limiting it, but that may take a while, as its not really supported by the system and noone has for ages tried to change that anymore. Sorry for the experience!

**Closed by D3nnis3n** 2023-12-15 12:53 UTC
