### ISSUE TITLE
[9.0 Staging-1477] Random Crashes

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15272] opened 2020-03-23 17:37 UTC
Not entirely sure what is causing it but what looks like some form of error reporter loader flashes up for a second, loads and then the entire client crashes out and nothing else comes up no matter how long you wait.

This occurs about every 30-45 minutes for me.

**Comment by redwyre** [comment] 2020-03-23 18:01
After a crash, can you get your log files: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daelmaron** [comment] 2020-03-23 18:04
Of course, will grab that on the next crash

**Comment by SlayksWood** [comment] 2020-03-23 18:11
It's Unity Crash like we have with Sand before #12873
![unknown](https://user-images.githubusercontent.com/45708377/77348617-d1051480-6d4a-11ea-9e02-ea0e27946df6.png)

**Comment by Daelmaron** [comment] 2020-03-23 18:18
thats the loader that pops up, yep.

I am attaching my log files now.

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371195/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371196/Player.log)

**Comment by Daelmaron** [comment] 2020-03-23 19:05
Crash #6 - Hour mark. This time I shifted over to answer someone in discord and then went to go back and found it crashed.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371410/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371411/Player-prev.log)

**Comment by ScottEco** [comment] 2020-03-23 19:09
Crashed a second time while placing stone roads
[crash.dmp.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371429/crash.dmp.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371430/error.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371431/Player.log)

**Comment by redwyre** [comment] 2020-03-23 19:28
@Quadbro Looks like crashes related to WWise

**Comment by Daelmaron** [comment] 2020-03-23 20:18
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371717/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371718/Player-prev.log)

Seventh Crash - was picking up mortared stone that I had placed

**Comment by MishkaFur** [comment] 2020-03-23 20:19
Crashed at same time as Daelmaron, I was actually afk ingame, Eco was full screen nothing else happening on PC

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371728/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371729/Player.log)

**Comment by MishkaFur** [comment] 2020-03-23 21:17
Another crash :D me and Sarah at same time again.

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371958/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371959/Player.log)

**Comment by Daelmaron** [comment] 2020-03-23 21:17
Mishka and I crashed at the same time, two different areas of the world, doing two different things. I was approaching a Steam Truck.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371962/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371963/Player-prev.log)

**Comment by revtje** [comment] 2020-03-23 21:18
Before the crash it starts to stutter and then it locks up for a while and the game exits

[Player - Copy.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371966/Player.-.Copy.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4371967/Player-prev.log)

**Comment by MishkaFur** [comment] 2020-03-23 21:21
Server exception this time, was just chatting ingame.

[server exception 21.20 GMT 23.03.20.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4371980/server.exception.21.20.GMT.23.03.20.txt)

**Comment by MishkaFur** [comment] 2020-03-23 21:23
Seems to happen when around 10 players are on the server

**Comment by revtje** [comment] 2020-03-23 22:03
Crash while digging dirt

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4372128/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4372129/Player-prev.log)

**Comment by Engimage** [comment] 2020-03-23 22:21
Random crash doing nothing specific
[Crash_2020-03-23_221607306.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4372183/Crash_2020-03-23_221607306.zip)

**Comment by Engimage** [comment] 2020-03-23 22:36
Server exception, right after posting a message in #general chat

**Comment by Daelmaron** [comment] 2020-03-23 23:04
Just now had 4-6 people crash to desktop at the exact same time including for myself.

Personally I was tabbed out typing a message on Discord and looking at the Github issues to update another one of them.

Dropping logs below just in case they are helpful.

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4372292/Player-prev.log)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4372290/Player.log)

**Comment by revtje** [comment] 2020-03-23 23:05
[Crash_2020-03-23_230253163.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4372295/Crash_2020-03-23_230253163.zip)

**Comment by MishkaFur** [comment] 2020-03-23 23:17
Seems to be when around 10 players are on the server, seems to often crash a few players at the same time

**Comment by Daelmaron** [comment] 2020-03-24 01:02
Crashed again: to desktop.

I was mining, carrying iron ore in my hands and I accidentally clicked to pick up a chunk of sandstone and then immediately got the unity loader and then crashed to desktop.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4372583/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4372584/Player-prev.log)

**Comment by Quadbro** [comment] 2020-03-24 04:46
Thanks for such detailed info, will look asap

**Comment by Quadbro** [comment] 2020-03-24 06:06
yes, all crashes are caused by the same issue with AK::MusicEngine, that's weird, will try to investigate why

**Comment by Quadbro** [comment] 2020-03-24 07:10
Hope audio branch sync will help, but i'm not sure. Marking as fixed.... if it will continue in next build (after pr merge) - i'll resume to looking at wwise engine deeply

**Comment by MishkaFur** [comment] 2020-03-24 10:10
Just had crash to desktop, was not doing anything ingame just AFK. 

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4374563/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4374565/Player-prev.log)

**Comment by elfl0rd** [comment] 2020-03-24 10:28
From my closed issue

(just playing local, and server still work after client crash)
[Crashes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4362751/Crashes.zip)

**Comment by revtje** [comment] 2020-03-24 11:11
Crashed to desktop when shift+click moving papayas from my steam truck to a storage chest


[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4374864/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4374865/Player-prev.log)
[Crash_2020-03-24_110941001.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4374866/Crash_2020-03-24_110941001.zip)

**Comment by Daelmaron** [comment] 2020-03-24 14:40
crashed to desktop when typing and I accidentally fat thumbed the right side of my spacebar and caught multiple keys at the same time while attempting to answer someones question.

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4375856/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4375858/Player.log)

**Comment by MishkaFur** [comment] 2020-03-24 15:07
I have crashed in SP whilst AFK from keyboard, was just on a small world staring at a masonry table

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4376027/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4376028/Player-prev.log)

**Comment by elfl0rd** [comment] 2020-03-24 17:51
Everybody who had a crashes, did you update the nvidia game ready driver?
I have a theory, this is fresh driver issue.

**Comment by Daelmaron** [comment] 2020-03-24 18:27
Crashed while driving up a hill after loading two kilns and iron ore into the back of my steam truck.

@elfl0rd I have not updated my Nvidia driver in about a month and a half so if its an issue with the new driver it wouldn't be affecting me.

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377024/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377025/Player.log)

**Comment by Daelmaron** [comment] 2020-03-24 19:46
Crashed while sitting in a anvil looking at a recipe

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377334/Player-prev.log)

**Player Log** _this was suddenly MASSIVE and would not upload here_ https://www.mediafire.com/file/p4pnimw819o8lp4/Player.log/file

**Comment by Daelmaron** [comment] 2020-03-24 20:27
Stepped away to replace a lightbulb that tried to explode. I think I was looking at the carpentry table interface.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377507/Player.log)

**Comment by revtje** [comment] 2020-03-24 20:28
My game crashed then got stuck at loading for 30 minutes. At 96% loading world it crashed. This is the first time i've got a crash during loading world so maybe interesting

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377505/Player.log)
[Crash_2020-03-24_202346679.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4377510/Crash_2020-03-24_202346679.zip)

**Comment by Daelmaron** [comment] 2020-03-24 20:33
Relaunched the game.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377547/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377548/Player-prev.log)

**Comment by Daelmaron** [comment] 2020-03-24 22:11
Crashed in single player after putting an item in chat (I am thinking that these crashes are somehow related to chat in game)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377873/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377874/Player-prev.log)

**Comment by Quadbro** [comment] 2020-03-25 04:24
guys, you all have one similar crash issue, related to sound engine. thanks for logs, we are working on this issue

**Comment by Quadbro** [comment] 2020-03-30 06:04
Do you stiil have these crashes after 1490 ?

**Comment by ScottEco** [comment] 2020-03-31 21:15
Just had a ECO global crash again.
Don't know if linked or not to same issue. Putting logs.
[Player-prev.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4411639/Player-prev.zip)

**Closed** 2020-04-07 07:32 UTC
Labels: Category: Audio, Priority: Critical, Status: Fixed, Week Task
