### ISSUE TITLE
(Suggestion) Make Status Tab open if table doesn't meet room requirements

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4684] opened 2018-02-17 05:57 UTC
so as the title say make the status tab open first if the table is missing some of its room requirements

**Comment by Huntermeign** [comment] 2018-02-17 21:20
agreed. avoids the newbies questioning why their table doesn't work

**Comment by ecoemmeck** [comment] 2018-02-18 03:03
The whole I put all my resources in but it's not working is getting tiresome to say the least

**Comment by Sirisma** [comment] 2018-02-18 17:39
I think instead of opening the tab it should put like a red exclamation point next to the tab and while in the crafting tab mention to check the status tab. If it just outright opens the status tab it will annoy people that prebuild or that queue projects while rebuilding around the table.

**Comment by ecoemmeck** [comment] 2018-02-19 03:44
Well it should only open the status tab if the table doesn't meet the required room specifications.

This would help a lot of the noobish questions as to why their table isn't working.

Currently the red light in the top left corner of the window isn't getting their attention so something drastic needs to be done so the notice

**Comment by Sirisma** [comment] 2018-02-19 03:47
Yeah I get that, I only just noticed it after 40 hours of playing. My point is just that the game should give you clues but shouldn't drag you around by your ear and throw your face into the problem until you see it xD

**Comment by ecoemmeck** [comment] 2018-02-19 03:59
yes but then the admins like myself have to deal with 100 questions a day as to why their tables aren't working

**Comment by MarjieAVolk** [comment] 2018-02-20 21:15
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4466

We have been getting a lot of bug reports about this also, so we are working on improving this.  This particular suggestion has already been implemented, and will be available in the next release.

**Closed by MarjieAVolk** 2018-02-20 21:15 UTC
