### ISSUE TITLE
USER ISSUE: Objects omitted while rendering the landscape

### ISSUE THREAD

**Issue by GeertJanVanDerWolf** [StrangeLoopGames/EcoIssues#23345] opened 2022-08-11 17:55 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
No clue as to why this is happening. Nothing to do with what I do in this situation.

**Expected behavior:**
I expect all the placed items, whatever they are to be in the place that I placed them. Everytime I visit that part of the world.	

**Actual behavior:**
Item is omitted during rendering. Chests become invisible. On the available storage location they stay visible. Accessible even. A stampmill however disappears enterily. Trying to place something in the spot where the stampmill is placed, set up nothing else can be placed. The system says something is located there.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9310806/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9310808/Player-prev.log)

**Comment by D3nnis3n** [comment] 2022-09-06 10:51
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19797

**Closed by D3nnis3n** 2022-09-06 10:51 UTC
