### ISSUE TITLE
Sign letters don't display underwater

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21246] opened 2021-04-04 09:06 UTC
The signs have issues displaying characters underwater / through water:

![image](https://user-images.githubusercontent.com/964559/113504005-3eb15800-94ea-11eb-8f92-cf47e84ac348.png)

![image](https://user-images.githubusercontent.com/964559/113503999-39eca400-94ea-11eb-9331-ec85704a564e.png)

**Comment by MishkaFur** [comment] 2021-04-04 10:59
Might be related to #19248

**Comment by redwyre** [comment] 2021-04-11 10:12
Duplicate of #19248

**Closed by redwyre** 2021-04-11 10:12 UTC
Labels: Category: Tech, Priority: Low
