### ISSUE TITLE
USER ISSUE: Server Timeout

### ISSUE THREAD

**Issue by Shinji170981** [StrangeLoopGames/EcoIssues#16626] opened 2020-06-11 14:59 UTC
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
The server times out from time to time, even though there are only 2 people on the server.
The server is emulated on a linux server.
[log file.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4765621/log.file.txt)

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```

one mod is installed: https://eco.mod.io/taking-out-trash
```
Connection timed out
```

**Comment by Shinji170981** [comment] 2020-06-12 12:26
[Logfile 2.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4770734/Logfile.2.txt)
Another logfile from just now.

**Comment by SlayksWood** [comment] 2020-06-15 13:49
@Shinji170981 Thank you for the report and sorry for waiting.
1. Are you having this issue with every server?
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. Does server ownerhave external IP address and did he use it in config file?

**Comment by Shinji170981** [comment] 2020-06-15 15:23
Hello,

i can see the servers in the overview with ping, user count and description.

Connected to the "Sea Otter" server to test this and it doesn't seem to lag.
Here are the log files.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4781212/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4781213/Player-prev.log)

I am running Malwarebytes and Windows Defender behind a router, so only the standard Windows Firewall which allows Eco access to the internet.

My internet connection is 120Mbps down and 40Mbps up.

System Specs are as followed:
CPU Intel i7-3770 @ 3.40 to 3.90 GHz
Geforce nVidia GTX 580
16 GB RAM DDR3
Windows 10 64 Bit

For the server i am playing on, we are using a domain name to connect but it is also possible to connect via IP to the server.
What he did in the config file, i am not aware but i can ask him and update this thread accordingly.

**Comment by LiaraAlis** [comment] 2020-06-15 15:38
I will add the information for @Shinji170981.
The lags and timeouts usually occur simultaneously with us.

The server runs in a data center.
At the moment in the config file there is this:
```
  "IPAddress": "0.0.0.0",
  "RemoteAddress": "",
```

I can not find any information in the wiki about this two config values. What is the best value? I think in `IPAddress` I should enter the remote ip address of the server. But for what is `RemoteAddress`?

**Comment by mirasrael** [comment] 2020-06-17 06:31
RemoteAddress is address to be used for connection by clients (IPAddress is address to use by server for binding). It is recommended to set RemoteAddress to external IP address so it will always provide correct value for connecting clients. It may be used together with port:
I.e.: "RemoteAddress": "222.222.123.212:3000"

**Comment by LiaraAlis** [comment] 2020-06-17 17:27
@mirasrael Thanks for answer. I set the `RemoteAddress` to the external ip address of the server.
But I think this is not the cause for the lags. But we will be watching.

**Comment by LiaraAlis** [comment] 2020-06-19 10:49
As I suspected it doesn't change the lag and timeout problems. :(

**Comment by Shinji170981** [comment] 2020-07-11 11:33
> @Shinji170981 Thank you for the report and sorry for waiting.
> 
> 1. Are you having this issue with every server?
>    Can you try to connect to official servers (Sea Otter and Giant Tortoise) and provide log files?
>    Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
> 2. Can you see servers in list normally? With ping and server info?
> 3. Do you have Firewall or Antivirus enabled?
> 4. Which kind of internet connection are you using?
> 5. Please provide your PC specification (include Operating System).
> 6. Does server ownerhave external IP address and did he use it in config file?

Do you still need more info?

**Comment by D3nnis3n** [comment] 2022-07-18 09:41
Closing this issue due to being old and never reproduced. If a similar issue pops up again, please create a new issue.

**Closed by D3nnis3n** 2022-07-18 09:41 UTC
Labels: Status: Needs Information
