### ISSUE TITLE
Staging: too many tailings

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9867] opened 2018-10-26 04:48 UTC
**Version:** 0.7.8.0 beta staging-52b819ac debug
Refers to - https://github.com/StrangeLoopGames/Eco/pull/3523
@craig-jong 

No efficiency
**Expected behavior:**
![default](https://user-images.githubusercontent.com/4980243/47544899-f68db480-d8f1-11e8-9c79-e1baab2e363a.png)
10 bar, 25 tailings from 100 ores

**Actual behavior:**
![default](https://user-images.githubusercontent.com/4980243/47545022-bc70e280-d8f2-11e8-90d1-7afe0649f299.png)
10 bar, 30 tailings from 100 ores.

Max efficiency
**Expected behavior:**
![default](https://user-images.githubusercontent.com/4980243/47545117-2a1d0e80-d8f3-11e8-852c-463f81a77bd5.png)
10 bar, 5 tailings from 20 ores

**Actual behavior:**
![default](https://user-images.githubusercontent.com/4980243/47545165-6e101380-d8f3-11e8-8406-6bc725efdc6b.png)
10 bar, 10 tailings from 20 ores

**Comment by D3nnis3n** [comment] 2018-10-30 13:04
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9649
Also Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9649

**Comment by D3nnis3n** [comment] 2018-10-30 13:07
I'll close it the other way round since this has been mentioned in a pull request.

**Comment by elfl0rd** [comment] 2018-10-30 15:02
Not duplicate, this is result of playtesting Craig fixes.

**Comment by D3nnis3n** [comment] 2018-10-30 15:08
Well, it's the same problem in both issues. If this one is fixed, the other
one is, too.

>

**Comment by D3nnis3n** [comment] 2018-10-30 19:34
Aye!

**Comment by johnkslg** [comment] 2018-11-13 18:50
Closing, fixed!

**Closed by johnkslg** 2018-11-13 18:50 UTC
Labels: High Priority

**Comment by elfl0rd** [comment] 2018-11-13 19:13
@johnkslg it's merged into master?
