### ISSUE TITLE
USER ISSUE: Some problem with mouse

### ISSUE THREAD

**Issue by Arkadia3** [StrangeLoopGames/EcoIssues#4346] opened 2018-02-11 19:16 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
While playing, my mouse has stopped working partially. I could chop tree or choose direction of moving, but I couldn't click on skill points; couldn't see statistic on bar with hunger  

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-13 03:05
So when you clicked on the skill points button, nothing happened?  Could you open other windows, eg the minimap or backpack?

Could you attach any client error logs you have?  These are located in C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by Arkadia3** [comment] 2018-02-13 15:18
When bug repeats, I will do it as you write.

**Comment by MarjieAVolk** [comment] 2018-02-21 23:48
Hey actually - does this sound like what you saw? https://github.com/StrangeLoopGames/EcoIssues/issues/4115

**Comment by Arkadia3** [comment] 2018-02-27 17:26
Hi. :) 
 Yes, similar. I could use the mouse to control the direction of movement, but I could not take anything from the backpack, I could not look at the nutrition and after pressing esc, I could not click anything (I closed the game alt + f4)

**Comment by MarjieAVolk** [comment] 2018-02-27 18:11
Okay closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

I believe this has to do with some combination of pressing escape while entering text into a text box.

**Closed by MarjieAVolk** 2018-02-27 18:11 UTC
Labels: Medium Priority
