### ISSUE TITLE
USER ISSUE: Mouse not lock into the game screen	

### ISSUE THREAD

**Issue by maxtas** [StrangeLoopGames/EcoIssues#25212] opened 2024-10-27 01:31 UTC
\
**User Id: (f7e4a5a4-dde1-4650-d827-08dce294c1e5)**
**Version:** 0.11.1.0 beta release-750

**Steps to Reproduce:**
1. grab a tool.
2. look around.
3. try to use tool like mining.
4. mouse clicks outside of game and screen.
5. frustrated

**Expected behavior:**
The mouse should have lock in the game screen while using a tool. when the Tab button is pushed, the mouse unlocks to move freely.

**Actual behavior:**
Instead, the mouse is moving freely behind the game and starts clicking outside of the game and using a tool (mining).

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-10-28 12:54
That issue is unfortunately not reproducible for me. The mouse stays locked in the game as it should be.
Please provide additional information on how the issue can be recreated, we unfortunately cannot address it without reproduction .

**Comment by D3nnis3n** [comment] 2024-11-02 05:41
Closing due to not being reproducible and no further information provided. Please feel free to reopen if you can provide reproducible steps.

**Closed by D3nnis3n** 2024-11-02 05:41 UTC
Labels: Status: Needs Information, Status: Not reproduced
