### ISSUE TITLE
USER ISSUE: Items not showing up in inventory after crafting

### ISSUE THREAD

**Issue by Dubie7910** [StrangeLoopGames/EcoIssues#24967] opened 2024-06-03 09:49 UTC
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Often there is a long lag between when items are finished crafting and when they show up in the inventory - reproduce by crafting often enough to see it happen.	

**Expected behavior:**
Showed up in inventory upon completion of crafting	

**Actual behavior:**
Did not show up until about half an hour later

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't know and I don't know

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-06-03 12:04
Looks like a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23628, can't reproduce exactly, but if items appear later, they were likely invisible.

**Closed by D3nnis3n** 2024-06-03 12:04 UTC
