### ISSUE TITLE
Weird movements if adjusting a window size

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#7953] opened 2018-06-01 11:03 UTC
v07.3.3 – 0.7.4.6  (0.7.2.5 is clean)
If adjusting a window size for example the minimap, unexpected and weird movements occur. If the object is released, the window jumps anywhere on screen. This was noticed for minimap, crafting table, skill menu – apparently it occurs for all others.

**Comment by BlazeGuy2** [comment] 2018-06-04 22:10
Duplicate of #6344, fix is currently been implemented and in the QA phase.

**Closed by BlazeGuy2** 2018-06-04 22:10 UTC
