### ISSUE TITLE
7.8 Law condition on periodic action won't allow no 'else' condition

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#9933] opened 2018-11-02 20:47 UTC
I wanted to make a law to tax a specific demographic, but it wants there to be an 'else' clause, even when I dont need it.  Eg

if (you are a 'Cool Dude')
  then tax 1 dollar

but I had to set it up as

if (you are a 'Cool Dude')
  then tax 1 dollar
else
  tax 0 dollar

**Comment by Deantwo** [comment] 2018-11-03 09:47
Duplicate of #8670.

**Comment by D3nnis3n** [comment] 2018-11-05 08:17
I ... dare to close this as duplicate, as it clearly is one and the other also already has given labels. If you don't want that - reopen, lol.

**Closed by D3nnis3n** 2018-11-05 08:17 UTC
Labels: Laws
