### ISSUE TITLE
Election not working

### ISSUE THREAD

**Issue by Excalibur80** [StrangeLoopGames/EcoIssues#15222] opened 2020-03-19 16:46 UTC
if we press L in game people can press vote but when we go to the website its just a greenscreen with no elections | if i do run for office it will add my name i can see that in-game but we cant see current elections so people cant vote see screenshots

i did /leader and set myself as a leader to overwrite the current election this worked but now if we go to the previous election you see winner : no winner and when we click on that we just get a blank website shown in the screenshots

![](https://cdn.discordapp.com/attachments/421479620479680523/690225831032782916/unknown.png)

![](https://cdn.discordapp.com/attachments/421479620479680523/690229303211851783/unknown.png)

![image](https://user-images.githubusercontent.com/13395303/77091787-4a2e0000-6a09-11ea-8a07-dcaccf130b2d.png)

![image](https://user-images.githubusercontent.com/13395303/77090971-36ce6500-6a08-11ea-9b5a-e28db575d5cb.png)

**Comment by SlayksWood** [comment] 2020-03-20 07:17
@Excalibur80 
Do you have this problem if you add another election for world leader?
This should be fixed with 0.9.0

**Comment by D3nnis3n** [comment] 2020-03-20 08:29
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/13707

**Closed by D3nnis3n** 2020-03-20 08:29 UTC
Labels: Status: Investigate
