### ISSUE TITLE
Steel Hammer not showing in hand

### ISSUE THREAD

**Issue by zonta** [StrangeLoopGames/EcoIssues#2602] opened 2017-10-24 17:55 UTC
I just want to let you know that the steel hammer is not showing in hand (V 6.0.2)

**Comment by MarjieAVolk** [comment] 2018-01-12 20:51
closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2478

**Closed by MarjieAVolk** 2018-01-12 20:51 UTC
