### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Emposa** [StrangeLoopGames/EcoIssues#4877] opened 2018-02-20 20:08 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Open a container or crafting bench of any kind and close it too fast and you get stuck and can't move or open the bench again.

**Expected behavior:**
Not made the player stuck

**Actual behavior:**
Renders the player unable to do anything but move the camera.

**Comment by MarjieAVolk** [comment] 2018-02-23 02:18
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

**Closed by MarjieAVolk** 2018-02-23 02:18 UTC
