### ISSUE TITLE
6.3 Newtwork Exception Clothing inventory Issue causing repeated client crashing

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3191] opened 2017-12-22 00:27 UTC
https://www.dropbox.com/s/872qd67qfy7rxyg/ClientNetworkException%20Exception%2012212330.zip?dl=0

**Comment by MarjieAVolk** [comment] 2017-12-29 00:41
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3171

**Closed by MarjieAVolk** 2017-12-29 00:41 UTC
