### ISSUE TITLE
[0.9.1 staging-1816] Change link for 'Host in Cloud' button

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18875] opened 2020-10-22 09:35 UTC
Step to reproduce:
- start client from folder, press host a world:
![image](https://user-images.githubusercontent.com/45708377/96853437-07328000-1463-11eb-969f-c453ab2f8d91.png)

- [ ] Release: It has this link https://accounts.strangeloopgames.com/hostedworlds and then you will be redirected to https://play.eco/cloudworlds. 

need immediately use this link https://play.eco/cloudworlds. 

- [ ] Staging use /hostedworlds instead of /cloudworlds and I have 404 not founded:
![image](https://user-images.githubusercontent.com/45708377/96853009-84a9c080-1462-11eb-8845-8f77650f8aee.png)
we can change it too.

**Comment by gzatravkin** [comment] 2020-12-04 00:42
Well 
1) It's kinda glued to implement it. 
As I see constants, we have a version of the account page for staging/release, but not of https://play.eco.
So I can't do something like accountsSite+"/cloudworlds", it would be accounts site for staging and play.eco for release.

@denysaw any feedback on that? Do we have staging version for play.eco? 
@SlayksWood why exactly redirection is problem here? 

2) is already fixed as I see. Link works fine

**Comment by denysaw** [comment] 2020-12-04 01:10
> 
> 
> Well
> 
>     1. It's kinda glued to implement it.
>        As I see constants, we have a version of the account page for staging/release, but not of https://play.eco.
>        So I can't do something like accountsSite+"/cloudworlds", it would be accounts site for staging and play.eco for release.
> 
> 
> @denysaw any feedback on that? Do we have staging version for play.eco?
> @SlayksWood why exactly redirection is problem here?
> 
>     1. is already fixed as I see. Link works fine

Sure, Kirill mentioned it in this issue :) IT's  https://accounts.strangeloopgames.com/

**Comment by gzatravkin** [comment] 2020-12-15 20:22
Ok, seems be already fixed then.
https://github.com/StrangeLoopGames/Eco/blob/release/Server/Eco.Shared/Networking/Common.cs - at release it already uses 
play.eco/cloudworlds.

Link is 
WebPageHelper.OpenURL($"{Constants.AccountsServerAddress}/hostedworlds"));

Marking as Can't reproduce for now, please attach exact build version and where to download it if it still occur.

**Closed** 2020-12-17 05:41 UTC
Labels: Category: Web, Priority: Low, Status: Not reproduced
