### ISSUE TITLE
USER ISSUE: Map rotation bug

### ISSUE THREAD

**Issue by TGGQCC** [StrangeLoopGames/EcoIssues#23612] opened 2022-12-04 23:12 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.7.3 beta release-391

**Steps to Reproduce:**
1. Open map
2. Zoom with scroll wheel 
3. click and drag to rotate just after zooming

**Expected behavior:**
The map should rotate.

**Actual behavior:**
Some layers of the map rotate but the actual map doesn't right after zooming

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2022-12-05 09:23
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23607

**Closed by D3nnis3n** 2022-12-05 09:23 UTC
