### ISSUE TITLE
[0.8.3.3] Animals spawning over house

### ISSUE THREAD

**Issue by lagonnebula** [StrangeLoopGames/EcoIssues#16077] opened 2020-04-30 21:42 UTC
Hello,

Sometimes I have animal that spawn on roof's house for no reason and try to escape but they can't go down. 
They is no way for them to come from the ground.

**Comment by elfl0rd** [comment] 2020-05-01 06:05
Duplicate of #14892

**Closed** 2020-05-01 06:44 UTC
