### ISSUE TITLE
USER ISSUE: server crash, database locked

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#5912] opened 2018-03-11 17:03 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
--BEGIN DUMP--
Dump Time
03/11/2018 17:50:47

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   at LiteDB.LockService.Read()
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   at Eco.Stats.ContinuousPlayerStatManager`1.RecordAction(T action)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Players.User.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Players.UserManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Expected behavior:**

**Actual behavior:**

**Comment by pamduncan** [comment] 2018-03-12 05:16
We have had this issue and worked around it by change compression to 'best speed and disabling stats:  See #5881

**Comment by MarjieAVolk** [comment] 2018-03-12 17:37
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343

**Closed by MarjieAVolk** 2018-03-12 17:37 UTC
