### ISSUE TITLE
USER ISSUE: Renaming Chests

### ISSUE THREAD

**Issue by ShadowBlade72** [StrangeLoopGames/EcoIssues#4723] opened 2018-02-17 17:27 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Enter a chest.
2. Select to rename the chest and hit enter.
3. Press escape to get out of the chest.

**Expected behavior:**
Chest should be renamed and you should be able to freely move.

**Actual behavior:**
Chest is renamed but you are unable to move or interact with objects.

**Comment by Palette75** [comment] 2018-02-21 09:33
This issue is occuring on all input text area.
If you interact with a text area, then you press escape, this will result in a keyboard freeze (cause the focus of the keyboard stay in the text area).
You can avoid this issue by leaving your interraction with your mousse, hitting the little cross to close the window (so don't use your ESC key)

**Comment by MarjieAVolk** [comment] 2018-02-22 23:33
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

**Closed by MarjieAVolk** 2018-02-22 23:33 UTC
