### ISSUE TITLE
Contract: Clause: Put Items in Container

### ISSUE THREAD

**Issue by Regitus** [StrangeLoopGames/EcoIssues#2883] opened 2017-11-21 22:54 UTC
Version 6.1.1

The items of the clause are lost after a restart and the contract is listed as invalid.

**Comment by Regitus** [comment] 2017-11-25 14:09
I have one thing to add here.

There is no Butchery Table in the list for this clause.
![butcherytable](https://user-images.githubusercontent.com/33863615/33231287-9f76b298-d1f2-11e7-8e33-462539880172.PNG)

**Comment by MarjieAVolk** [comment] 2017-11-27 23:10
Butchery Table appeared for me on a save with everything researched.  I'm guessing you don't have Butchery researched in your save?

**Comment by Regitus** [comment] 2017-11-29 21:24
At the moment of the screenshot the book was in the making(as you can even see in the screenshot). I need to take another look now.

**Comment by MarjieAVolk** [comment] 2017-11-29 21:36
So yeah you didn't have it researched, so that's expected behavior

**Comment by MarjieAVolk** [comment] 2017-11-29 21:37
Gonna delete unrelated comments

**Comment by LiaungYip** [comment] 2018-03-12 13:53
Duplicate of #4129, which has since been fixed and closed.

**Comment by MarjieAVolk** [comment] 2018-03-13 19:01
Thanks, closing in that case.

**Closed by MarjieAVolk** 2018-03-13 19:01 UTC
Labels: Medium Priority
