### ISSUE TITLE
USER ISSUE: log crash

### ISSUE THREAD

**Issue by lilibat** [StrangeLoopGames/EcoIssues#5648] opened 2018-03-08 02:27 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Went to collect a log that had been there for a while.

**Expected behavior:**
I should have picked up the log

**Actual behavior:**
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

**Comment by MarjieAVolk** [comment] 2018-03-08 21:43
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5595

**Closed by MarjieAVolk** 2018-03-08 21:43 UTC
