### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by jovi066** [StrangeLoopGames/EcoIssues#4064] opened 2018-02-07 21:25 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
Take 5s when you first time open workbench-A, second time it becomes normal.
But if  you open another workbech-B, it will take 5s again.
and take 5s to reopen bench-A 

**Expected behavior:**
i have 3 saves, only this save have this BUG

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-07 22:05
The first time you open a window for an object, it will take longer.  After that it is loaded, so it can be faster.  That will always be the case.

5 seconds is a very long time though.  If it is really taking that long, could you send me the .eco save file for the save that has the issue?

**Comment by MarjieAVolk** [comment] 2018-02-21 23:49
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3110

**Closed by MarjieAVolk** 2018-02-21 23:49 UTC
Labels: Medium Priority
