### ISSUE TITLE
Can't Paid Extremely Small Amount of Debt (9.2.4)

### ISSUE THREAD

**Issue by MystLeissa** [StrangeLoopGames/EcoIssues#21282] opened 2021-04-07 06:34 UTC
After starting a fresh game on a local server I ran into an issue with the economy (seems to be the nail in the screws with Eco). If you accept a contract that has a /very/ small decimal on the interest to the debt (<=0.009 Currency/Credit) The Economy Viewer Won't Let you pay your debt off. This is on top of the fact that the Economy Viewer won't let you auto-select "pay all debt" instead of paying it back in part (the "Send" Button is greyed out and unclickable). I included some screenshots to display what I'm running into.
[screenshots.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6269438/screenshots.zip)

**Comment by MystLeissa** [comment] 2021-04-07 06:41
At this point I have 2 Suggestions on how to fix this which could potentially work in tandem:

1. A "Convince" pay-all button to instantly settle your debt when paying back a loan/bond when you have enough currency to cover the cost.
2. If the debt to be settled is less than 0.01 then the debt should be considered cancelled, as no self-respecting normal transaction is going to go to the third decimal, and even if they wanted to the game doesn't support it and rounds up in many places.

**Comment by MystLeissa** [comment] 2021-04-07 06:45
Should've mentioned I'm on 9.2.4

**Comment by IcedForge** [comment] 2021-04-12 13:51
Thank you for reporting. Will close as duplicate of #8649

**Closed by IcedForge** 2021-04-12 13:51 UTC
