### ISSUE TITLE
[0.9.0.3] Old Growth Redwood Baby tree spawns

### ISSUE THREAD

**Issue by iflounder** [StrangeLoopGames/EcoIssues#18488] opened 2020-09-26 16:47 UTC
In 9.0.3 we chopped down a Old Growth Redwood this event triggered a baby old growth to spawn near by (happened to be in an unplanted farm). It spawned with the hitbox and skin of a full Old Growth Redwood but with 1 swing it disappeared like a baby tree would.

**Comment by beastyn** [comment] 2020-09-28 07:48
@iflounder thank you for the report
Yeap, that should be fixed here. They should not grow at all.
https://github.com/StrangeLoopGames/EcoIssues/issues/12125
Maybe caused by the last plants changes.

**Closed** 2020-09-30 12:36 UTC
Labels: Category: Gameplay, Priority: Medium, Type: Regression
