### ISSUE TITLE
USER ISSUE: paintings cause issues

### ISSUE THREAD

**Issue by bubblingangel** [StrangeLoopGames/EcoIssues#24344] opened 2023-12-21 12:01 UTC
\
**User Id: (slg237037)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
make an art gallery with 40 painting in a 2x2 claim room
have some paintings on your hot bar
then log out
and try to log back in

**Expected behavior:**
should allow me to join the server

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:


<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Mods.TechTree.PictureItem.UILinkContent()
   at Eco.Gameplay.Systems.TextLinks.UILinkExt...

Check log file to see full message.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2023-12-21 17:01
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24340

**Closed by D3nnis3n** 2023-12-21 17:01 UTC
