### ISSUE TITLE
USER ISSUE: Electric Lathe doesn't work

### ISSUE THREAD

**Issue by Tomuro86** [StrangeLoopGames/EcoIssues#9040] opened 2018-08-22 15:12 UTC
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Select a Electric Lathe in your house
2. Try to watch the crafting tab
3. The posible items for create doesn't appears

**Expected behavior:**
It shoud have electronic items to create

**Actual behavior:**
Instead it, "craft" options in this machine is empty

**Comment by Tomuro86** [comment] 2018-08-22 16:07
Thanks @Deantwo , I've compared between the room with the Electric Lathe and without it, but the result is the same, the Electric Machinist Table has same craft items. I've attached an screenshoot.

![image](https://user-images.githubusercontent.com/42614662/44475705-0a891180-a636-11e8-8dfb-c9563896ff5f.png)
 Thank you!

**Comment by Deantwo** [comment] 2018-08-22 17:03
The **Electric Machinist Table** requires an **Electric Lathe** in the same room before it can make an **Electric Planer**.
![image](https://user-images.githubusercontent.com/2676134/44478380-d0bc0900-a63d-11e8-9545-9d5625214a32.png)

**Comment by Deantwo** [comment] 2018-08-22 17:06
Anyway, this is a duplicate of #8800.

**Comment by Deantwo** [comment] 2018-08-22 17:43
It does not look like the **Electric Lathe** has any other use.
It will likely be fixed in the next update.

**Comment by seccombew** [comment] 2018-08-22 17:51
Dupe

**Closed by seccombew** 2018-08-22 17:51 UTC

**Comment by elfl0rd** [comment] 2018-11-12 15:46
https://github.com/StrangeLoopGames/EcoIssues/issues/8547
