### ISSUE TITLE
Kicked with Error on GetWorkOrderTooltip

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9815] opened 2018-10-20 15:21 UTC
**Version:** 0.7.7.2 beta

Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.
Source:Eco.Shared

System.Exception: Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname, Type& resultType)
   at Eco.Plugins.Networking.Client.ViewRPC(INetClient client, Int32 id, String methodname, BSONObject bson)</size>

![snap3057](https://user-images.githubusercontent.com/29383891/47257155-3253f480-d482-11e8-8232-c0d90f0c2246.png)

[output_log_copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2498259/output_log_copy.txt)

Tracked the Above Error down to Hovering Cursor over **either** empty box under crafting Column

**Comment by D3nnis3n** [comment] 2018-10-21 16:15
Probably duplicate of the less-good described issue https://github.com/StrangeLoopGames/EcoIssues/issues/9685

**Closed as completed** 2018-10-22 21:24 UTC
