### ISSUE TITLE
9.2.1 Tutorial not correct resolution.

### ISSUE THREAD

**Issue by BloodyMikey** [StrangeLoopGames/EcoIssues#20252] opened 2021-01-29 22:35 UTC
Hello i have a problem with my tutorial resolution the first one was correct now the rest is like in the video showing me trying to fix it. but nothing works for me.

[Youtube](https://youtu.be/DMmS-HqBXkE)

Server [log ](https://pastebin.com/nqfusGnY)
Player [log ](https://pastebin.com/dGzjRu02)

And my slgiid is  User ID: slg29043

**Comment by SlayksWood** [comment] 2021-02-01 09:47
I set resolution 3360x1050 and I don't have it at all. The arrow was appeared, but I don't have text:
![image](https://user-images.githubusercontent.com/45708377/106441447-1c1fa600-648b-11eb-93a9-005b38ff4181.png)
![image](https://user-images.githubusercontent.com/45708377/106441561-3fe2ec00-648b-11eb-8909-efaa38d1f368.png)
If you don't have this issue, skip tutorial and restart it again.

**Comment by mloftis** [comment] 2021-02-19 22:08
Just chiming in with a "me too" , ultrawide display, native resolution 3440x1440

**Comment by SlayksWood** [comment] 2021-02-23 06:11
> **User Id: (Not logged user)**
> **Version:** 0.9.2.4 beta release-156
> 
> **Steps to Reproduce:**
> Start game, follow Tutorial, all Tutorials on screen already work fine, but once a new one enters the game, the description rather than being a normal rectangle will be very thin and very tall, often so bad the bottom is offscreen and unreadable. This can be corrected by disconnecting and recommecting at which time all ones on the screen already work fine, but noew ones will have the same issue. I suspect this has something to do with the odd screen resolution I have of 3840x1600
> 
> **Expected behavior:**
> Be readable
> 
> **Actual behavior:**
> Off Screen
> 
> **Do you have mods installed? Does the issue happen when no mods are installed?:**
> No mods, vanilla
> 
> **Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6018881/Player-prev.log)
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6018882/Player.log)
> ![Eco-Tut-Issue](https://user-images.githubusercontent.com/12549279/108643323-1f012b80-7478-11eb-99c8-1907e64ba75d.PNG)

**Comment by Daniel-Magulado** [comment] 2021-04-29 21:26
Tested on 9.4 Develop-270.

Tested on 2 monitors. First has a native resolution of 2560 x 1080 with 21:9 ratio. Second is also an ultrawide monitor with 3440 x 1440 reso.
Tested with starting new accounts on 3 trials.
Total of 6 test.
Did not encounter this issue.
Closing.

**Closed by Daniel-Magulado** 2021-04-29 21:26 UTC
Labels: Category: UI, Priority: Medium, Squad: Otter, Status: Fixed, Type: Bug

**Comment by gnomishperson** [comment] 2021-05-02 20:06
This still appears to be a bug, running at 5120x1440 the tutorials seem to be completely bork:
![20210502130355_1](https://user-images.githubusercontent.com/772337/116826091-25321900-ab47-11eb-9780-45ba9f8c3a7a.jpg)

**Comment by Daniel-Magulado** [comment] 2021-05-02 20:42
Hi @gnomishperson,

Thank you for sharing a screenshot of the issue you encountered.
However, yours appears to be a different issue than what is reported here.
We're also aware of the issue that you are referring to.
You can add your concern here #13632.

Thank you.

**Comment by gnomishperson** [comment] 2021-05-02 22:37
No, I get the FOV thing; That's pretty common, but I cannot get the tooltip windows to pop up for the tutorials. I had to downscale to 2560x1440 to see the tools tips (so I knew what I had to do) in order to complete the tutorials. Sorry it's hard to tell in the screenshot.

**Comment by Daniel-Magulado** [comment] 2021-05-02 23:37
Hi @gnomishperson,

Thank you for providing more information about this.
I'll open a new ticket for you. I've tested it on a resolution of 5120 x 1440 and 5120x1080. I can confirm that the tooltip for tutorials is not showing up.
You can follow it here #21734 21734

**Comment by war4peace** [comment] 2021-05-28 15:13
Hello,

I just bought the game today, vanilla, no mods, resolution is 3440x1440, Borderless Windowed.
Tutorial windows are very narrow. Is there any workaround?

![image](https://user-images.githubusercontent.com/6294884/120005286-5f74c600-bfe0-11eb-8728-aa57550cfd4b.png)

**Comment by D3nnis3n** [comment] 2021-05-28 19:13
Yes, just set your resolution to a non-widescreen one for the duration of the tutorial. The issue is already fixed and the fix will be part of the next regular update, 9.4.
