### ISSUE TITLE
USER ISSUE: Item Stuck

### ISSUE THREAD

**Issue by ApocalypticFlame** [StrangeLoopGames/EcoIssues#5074] opened 2018-02-25 10:50 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Drag item into slot.

**Expected behavior:**
Item should have been inserted into the slot.

**Actual behavior:**
Icon stays floating in the air, even after leaving the GUI of the container (Campfire, storage chest).
Cursor icon gets stuck in contracted hand.
I am still able to drag other items and drop them successfully in a slot, but the initial icon remains in the same place.

**Comment by MarjieAVolk** [comment] 2018-02-26 20:02
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

Others have found that minimizing the game and reopening it will clear the stuck icons.  This may also be related to your mouse, as it seems to be caused by rapid clicking.

**Closed by MarjieAVolk** 2018-02-26 20:02 UTC
