### ISSUE TITLE
USER ISSUE: game unexpectedly crashed

### ISSUE THREAD

**Issue by AnneJulieT** [StrangeLoopGames/EcoIssues#22940] opened 2022-01-15 02:28 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.4.5 beta release-278

**Steps to Reproduce:**
I was just walking around in the jungle. I got disconnected from the server and I saw the error message down below, then when I reconnected it crashed again and I got the same message. This happenned 3 times. As soon as I log in, I get expelled 

**Expected behavior:**
no crash

**Actual behavior:**
The following error message popped up:
```
Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes lots of mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment] 2022-01-17 15:55
Hello @AnneJulieT ,

Thank you very much for your report. Could you please send the log files? Also, have you been able to reproduce this issue on another server?

**Comment by D3nnis3n** [comment] 2022-07-18 09:58
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)

**Closed by D3nnis3n** 2022-07-18 09:58 UTC
Labels: Status: Needs Information
