### ISSUE TITLE
9.7.2 skillbook research price increased without being obvious the cause

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#23577] opened 2022-11-25 15:33 UTC
Skillbook research cost has increased due to them using the "EndgameCraftCost" vairable for expensive or normal recipe.

Due to the name of this difficulty setting it is >NOT< at all obvious this will affect research ie you crafting Farming skill book which is not endgame.

This should use its own cost flag ie "SkillbookCost" so it can be different from endgame (Lab and Lasers)

**Comment by TwixterZ** [comment] 2022-11-25 16:17
@MishkaFur Thank you for reporting this to us, I have forwarded your issue to our developer to look into

Issue ref : ECO-25692

**Comment by D3nnis3n** [comment] 2022-11-29 09:07
Not a bug, hence closing. Kept as feedback internally, though I prefer renaming the variable if need be instead of a second one.

**Closed by D3nnis3n** 2022-11-29 09:07 UTC
