### ISSUE TITLE
USER ISSUE: Cart cant be interacted with

### ISSUE THREAD

**Issue by cvetlicni** [StrangeLoopGames/EcoIssues#20468] opened 2021-02-09 23:07 UTC
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Place a cart down somewhere far from home (distance seems to play a role)

**Expected behavior:**
Be able to both access its contents and pick it up

**Actual behavior:**
It can't be interacted with

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, at least not clientside

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment] 2021-02-10 07:30
@cvetlicni Thank you for the report. Can you provide log files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment] 2021-02-10 07:31
Seems need to merge to this one #20414

**Comment by JestinJae** [comment] 2021-02-11 22:10
I had a similar issue, I could interact with the cart in certain areas and not others, it also happened with other objects as well, such as rocks after they were mined.  It appears to be a client-side bug because restarting the client fixed it.  This was with a hosted server, not on a local save.

for some of it, the cart was interactable only on certain points, but not others where it should be.  Sadly I don't have reproduction steps because I don't know what caused it, but I have uploaded my log files here. I only attached the "prev" log because the current one was empty.
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5968713/Player-prev.log)


videos: https://youtu.be/hjB85EhsvaI , https://youtu.be/-amqI3D3z48 , https://youtu.be/KjVAStsgPqo , https://youtu.be/y3mbwLEcVJ8 , https://youtu.be/Jw5Yt4KtaQg , https://youtu.be/dNnWNJ1JiBo

**Comment by IcedForge** [comment] 2021-02-18 09:00
Closing this as they are combined over at #20414

**Closed by IcedForge** 2021-02-18 09:00 UTC
Labels: Status: Needs Information
