### ISSUE TITLE
Crash when breaking down dirt

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#6177] opened 2018-03-17 03:50 UTC
From the support queue: 

Hey Guys, 
I play Eco, super cool game.
Unfortunately I have since the update yesterday a problem. Whenever I want to break down dirt comes this message: 
Caught exception: 
<size=60,00%>Caught exception invoking RPC PlayerInteract on Player! 
Cannot insert duplicate key in unique index '_id'. The duplicate value is '421'. 

Stack:
   bei LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   bei LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   bei LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   bei LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   bei LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   bei LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   bei LiteDB.LiteCollection`1.Insert(T document)
   bei Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Gameplay.Items.UsableItemUtils.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   bei Eco.Gameplay.Items.ToolItem.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, Single calorieMultiplier, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   bei Eco.Mods.TechTree.ShovelItem.OnActLeft(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info) 
Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size> 
  
An error checking on Steam I have already done, but unfortunately brings nothing.

**Comment by MarjieAVolk** [comment] 2018-03-20 17:30
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5611.  We believe this is fixed in 7.3 ( still verifying).

**Closed by MarjieAVolk** 2018-03-20 17:30 UTC
