### ISSUE TITLE
exhaustion times wont refresh if server time zone is changed

### ISSUE THREAD

**Issue by grandpaSam** [StrangeLoopGames/EcoIssues#25238] opened 2024-11-03 20:56 UTC
We found this weird issue with our server save. The time zone on the server got switched due to some automatic program. 

The in game times for when exhaustion will refresh are all accurate but when the timer hits zero the box will say "exhaustion will refresh in next tick" 

It will stay like that until the next refresh time is closer than 12 hours. 

I shut down the server and set the timezone back to what it was before. But the problem still persists as if the save has now been set wrong or something.

**Comment by D3nnis3n** [comment] 2024-11-04 03:24
What was the timezone before and after the switch, e.g. how many hours difference in which direction?

The exhaustion system relies on the server time that should never change beyond DST changes the system is prepared to handle. It's absolutely possible this broke internal counters as it either had to skip a notable amount of time or went through it again (which is worse). You could try to simulate the same problem again while the server is running, but into the other direction, and see if that helps getting it back to before. Otherwise the only option would be to restore a backup of the save before the issue happened.

**Comment by D3nnis3n** [comment] 2024-11-11 06:24
Closing due to no further information provided, the issue is likely caused by the change in server time that shouldn't happen to be gin with.

**Closed by D3nnis3n** 2024-11-11 06:24 UTC
Labels: Status: Needs Information
