### ISSUE TITLE
USER ISSUE: World Gen - Huckleberry not found on Planet

### ISSUE THREAD

**Issue by pStuetz** [StrangeLoopGames/EcoIssues#5926] opened 2018-03-11 21:38 UTC
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Have to find Huckleberry for the "Forage For Food" Quest but can't find any. Checked the heatmap for Huckleberry but it doesn't display any

**Expected behavior:**
Huckleberry on the map.	

**Actual behavior:**
No Huckleberry found, even on mapview 'm'

**Comment by MarjieAVolk** [comment] 2018-03-13 00:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

Unfortunately, you may just have to generate a different world, if you started without any of a certain plant.

**Closed by MarjieAVolk** 2018-03-13 00:12 UTC
