### ISSUE TITLE
USER ISSUE: just a proposition

### ISSUE THREAD

**Issue by Unclerein** [StrangeLoopGames/EcoIssues#4915] opened 2018-02-21 22:27 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
it would be nice to transfer a pile of item by just double left clicking on it instead of click and drag

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-22 19:52
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4280

We would like to add something like this, but are still discussing exactly how to implement it.  Double click is an interesting idea.  If you have any more opinions, feel free to comment on the other bug ^

**Closed by MarjieAVolk** 2018-02-22 19:52 UTC
