### ISSUE TITLE
Alpha 6 - Connection Failed Invalid login token - no one can join server

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#2434] opened 2017-10-02 13:05 UTC
As stated above, last night everyone could connect and play fine. This morning no one can connect or play (new or old users). 

attempted restarts several times of the server no luck. Tried new players joining, old players joining all received the same error.  really hoping you all can provide insight as there are no dump files being generated. 

below is our game.eco file hopefully it makes more sense to yall :D

https://drive.google.com/open?id=0B7I4FfX-IJY9cFREUXNHd0RGSUU

**Comment by noblackthunder** [comment] 2017-10-02 13:17
User feedback suggest that this issue is becoming a large and larger issue

**Comment by noblackthunder** [comment] 2017-10-02 13:18
woops ! .. Dupe! for https://github.com/StrangeLoopGames/EcoIssues/issues/2434

**Comment by stormoffires** [comment] 2017-10-02 14:58
How is this a dupe? #2427 is store related? This posting does not have any stores in the game.eco and is not giving error files?

**Comment by Fank** [comment] 2017-10-02 16:16
Do you mean something stuck at 2% loading world? Because some of our players got that issue

**Comment by noblackthunder** [comment] 2017-10-02 17:34
ohh ok my bad!

**Comment by stormoffires** [comment] 2017-10-02 19:06
Thanks again for opening this up NOT. Players are reporting they can rejoin the server now. I saw on discord that authentication servers had issues this morning?

**Comment by noblackthunder** [comment] 2017-10-02 19:23
i am not aware of issues.. though there could have been DNS issues .. if its working now i close it for now since the issue is resolved

**Comment by noblackthunder** [comment] 2017-10-02 21:53
issue again

**Comment by stormoffires** [comment] 2017-10-02 23:53
host service, pingperfect
seems to be going in and out of authentication issues, got kicked for "token used elsewhere" then tried to login and got "invalid token" but after a little bit it let me back in again. same with a few other folks on the server. No error logs are generating and the server is visible via favorites. unknown if its host server, game file or authentication server. seems to just go in waves. 
not sure if any of this is helpful but wanted to pass on all information :) thanks!

**Comment by rainfarmer** [comment] 2017-10-02 23:59
Hey, I just tested your account, and was able to login to another server. 
I couldn't find "mediocre at best"

So you probably were just kicked, by me logging in, sorry about that.

**Comment by metachronism** [comment] 2017-10-04 17:33
this was an issue with ping perfect that we have resolved -

**Closed by metachronism** 2017-10-04 17:33 UTC
Labels: High Priority

**Comment by stormoffires** [comment] 2017-10-04 17:39
thank you meta! this confirms we are pulling chalks with pingnotsoperfect :)
