### ISSUE TITLE
USER ISSUE: Glass Bug

### ISSUE THREAD

**Issue by heimskringla** [StrangeLoopGames/EcoIssues#6991] opened 2018-04-05 11:56 UTC
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
None needed

**Expected behavior:**
Glass should be buildable with the hammer like lumber or bricks

**Actual behavior:**
Is represented by gray untextured block when placed in the world.
(This has been an issue since 7.3 and I'm afraid has not been resolved with 7.3.2)

**Comment by MarjieAVolk** [comment] 2018-04-05 18:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6799

**Closed by MarjieAVolk** 2018-04-05 18:13 UTC
