### ISSUE TITLE
USER ISSUE: Negitive Treasury Allocation

### ISSUE THREAD

**Issue by zahnee** [StrangeLoopGames/EcoIssues#9673] opened 2018-10-09 13:56 UTC
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Allocate negitive money from the treasury to a specific player.

**Expected behavior:**
Negitive allocations should not be allowed.

**Actual behavior:**
Takes another players money and places it into the treasury.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
Takes another players money and places it into the treasury.
![image](https://user-images.githubusercontent.com/18610605/46674233-a2709980-cba9-11e8-9367-a91203e921bf.png)

**Comment by elfl0rd** [comment] 2018-10-09 14:00
this is feature, allowing leader to penalty player.

**Comment by Deantwo** [comment] 2018-10-09 15:53
Duplicate of old closed issue.
Here: #7201

See also: StrangeLoopGames/EcoSuggestions/issues/447

**Comment by D3nnis3n** [comment] 2018-10-10 21:47
While i cannot do what you can - e.g. i have no possibility to allocate negative values, i STRONGLY WISH that this is possible in the feature. So please DO NOT fix this. It's a very useful tool to give out fines for lawbreakers as in reallife and allows to deal with administrative actions in a way that does not require banning people. PLEASE!

**Comment by Deantwo** [comment] 2018-10-11 05:34
This is a stupid bug, plain and simple. The allocation window and messages still looks like the allocation is giving money.

It would be better to have a separate and more logical way to take money from people. Such as one-time taxes and a way for people to donate tobthe treasury.

Again see: StrangeLoopGames/EcoSuggestions/issues/447

**Comment by D3nnis3n** [comment] 2018-10-12 01:36
I disagree. It's at the right place even though not obvious to use. Why
should there be any other menu, when you can do it where you should - at
the treasury.
One could change the text so it does not show "allocated", yes, but that is
an oversight of which type there are more in the game - so rather fix that.

Bank Accounts should cover for donating to treasury i suppose.

**Comment by Deantwo** [comment] 2018-10-12 05:28
I never said it shouldn't be done at the treasury, I just think a second button to open a "one-time tax" dialog would be more obvious than using negative number in the "allocation" dialog.

**Comment by D3nnis3n** [comment] 2018-10-12 21:23
Sure it would, just sounded like you'd rather have that "bug" fixed with no replacement - as this will probably happen. And that's not good. Then at least keep this "bug" until it get's a better way.

**Comment by D3nnis3n** [comment] 2018-11-15 18:21
Fixed in 7.8

**Comment by elfl0rd** [comment] 2018-11-15 18:45
without adding ability to tax players? :(

**Comment by D3nnis3n** [comment] 2018-11-15 18:46
Unfortunately yes, but it is planned to come with the government update in a fitting fashion.

**Comment by D3nnis3n** [comment] 2018-11-15 19:05
How did you put it in? We tried around, couldn't find a a way to get a "-" in?

**Comment by elfl0rd** [comment] 2018-11-15 19:13
use buttons, not keyboard :D

**Comment by D3nnis3n** [comment] 2018-11-15 19:14
Great "fix" then, lol.

**Comment by Deantwo** [comment] 2018-12-18 21:51
Bump.
When this is fixed, will we get an actual tax option added to the treasury menu? Or is the functionality just gonna be removed with no alternative?

See: https://github.com/StrangeLoopGames/EcoSuggestions/issues/447

**Comment by D3nnis3n** [comment] 2019-02-14 10:47
A tax option has been added to the treasury, moving this to where it belongs.

**Closed by D3nnis3n** 2019-02-14 10:47 UTC
Labels: Semi-High Priority, outsource
