### ISSUE TITLE
USER ISSUE: holes in the Ground

### ISSUE THREAD

**Issue by dphotograph** [StrangeLoopGames/EcoIssues#4965] opened 2018-02-22 22:06 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
accedential stepping in an hole, an area on the map on there is no terrain generated

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-23 19:15
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3897

**Closed by MarjieAVolk** 2018-02-23 19:15 UTC
