### ISSUE TITLE
E drops cart even when 'interact' is rebound

### ISSUE THREAD

**Issue by squished-01** [StrangeLoopGames/EcoIssues#4479] opened 2018-02-13 22:56 UTC
Steps to reproduce:  bind forward to E. bind interact to W.  grab cart.  Turn around so you just see the handles.  Push E to go forward.   Character incorrectly drops the cart

**Comment by Dr-Hardware** [comment] 2018-02-13 22:59
Relates to #4412

**Comment by MarjieAVolk** [comment] 2018-02-13 22:59
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4412

It seems that dropping the cart doesn't get remapped properly with the other controls.  We will fix that.  In the mean time, you will have to map your key to something else so you can use E to drop the cart.

**Closed by MarjieAVolk** 2018-02-13 22:59 UTC
