### ISSUE TITLE
USER ISSUE: Playercrash

### ISSUE THREAD

**Issue by viipaR** [StrangeLoopGames/EcoIssues#5031] opened 2018-02-24 10:40 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Nitrado Server
2. Set myself as admin with the adminutils Mod active
3. Wanted to check the current skillrate/changing skillrate

**Expected behavior:**
Should have shown me the current skillrate/change the current skillrate

**Actual behavior:**
I crashed from the server
The following error message popped up:
```
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Value cannot be null.
Parameter name: key


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

```

**Comment by MarjieAVolk** [comment] 2018-02-26 18:41
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4391

**Closed by MarjieAVolk** 2018-02-26 18:41 UTC
