### ISSUE TITLE
USER ISSUE: no work

### ISSUE THREAD

**Issue by angelocheck** [StrangeLoopGames/EcoIssues#5285] opened 2018-03-02 03:50 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.the trees I planted die right away.
2.flour is usually made from seeds, not corn cobs or wheat tops
3.overwhelmed with inventories of unwanted or outdated tools are not removed.
4.does not seem to work the fertilizer

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-03-02 19:10
1. Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4571
2. I am not an expert on flour, but I believe it is in fact made from corn kernels and wheat heads.  Corn and wheat are seeds.
3. We are working on a 'drop items' feature, which should be available in two major releases from now.
4. Could you give some more details about what you tried to do, and what was not working?

**Comment by angelocheck** [comment] 2018-03-05 18:33
3.Hi! Right click on the soil fertilizers, fertilizer amount decreased, and the quality of the soil remained the same.

**Comment by MarjieAVolk** [comment] 2018-03-05 19:07
Okay, thanks.  @craig-jong Is fertilizer working right now?

**Comment by angelocheck** [comment] 2018-03-05 22:46
Right now checked. It's not working. On normal soil and plowed not working. Just wasted. )

**Comment by craig-jong** [comment] 2018-03-09 22:24
Fertilizer works over the course of a few ticks - you will not see immediate results when applying it to land.

We'll be looking into combining the proper seeds/items when we next do a food pass.

**Closed by craig-jong** 2018-03-09 22:24 UTC
Labels: High Priority
