### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by 38949834893** [StrangeLoopGames/EcoIssues#6264] opened 2018-03-19 03:54 UTC
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Cannot insert duplicate key in unique index '_id'. The duplicate value is '312'.


Stack:
   в LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   в LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   в LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   в LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   в LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   в LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   в LiteDB.LiteCollection`1.Insert(T document)
   в Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   в Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   в Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   в Eco.Gameplay.Items.UsableItemUtils.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   в Eco.Gameplay.Items.ToolItem.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, Single calorieMultiplier, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   в Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   в Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   в Eco.Gameplay.Players.Player.PlayerInter

**Comment by MarjieAVolk** [comment] 2018-03-19 20:32
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5611

We believe this will be fixed in the next release, still testing it out.

**Closed by MarjieAVolk** 2018-03-19 20:32 UTC
