### ISSUE TITLE
Better UI management required

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7038] opened 2018-04-07 01:50 UTC
Needing to click and drag 25 times to move from one stockpile to another is a bad workflow.

There should be two buttons. Transfer all and transfer selected. Which do what they say on the tin. With the current click/drag functionality remaining so as to allow single transfers where needed.

**Comment by Baithoven** [comment] 2018-04-07 02:53
Or maybe hold ctrl + leftclick to automaticly move the stack over?

**Comment by ecoemmeck** [comment] 2018-04-07 05:34
Duplicate of #4280

**Comment by MarjieAVolk** [comment] 2018-04-09 22:05
Thanks all, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4280

**Closed by MarjieAVolk** 2018-04-09 22:05 UTC
Labels: Suggestion
