### ISSUE TITLE
USER ISSUE: Mining immpossible

### ISSUE THREAD

**Issue by Exterminator165** [StrangeLoopGames/EcoIssues#5309] opened 2018-03-02 20:33 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Digging in a mountain. Try to mine.

**Expected behavior:**
Blocks should be possible to mine.

**Actual behavior:**
Some blocks can be mined, but don´t disappear. single rocks a falling from the sky and lay on top of the mountain. :-)
it´s raining rocks.

**Comment by fillion07** [comment] 2018-03-02 20:54
Is the problem related to the stone block not being able to be seperated in 4 with a pickaxe Or is it because you are not able to pick up the stone piece from the ground while pressing "E".

**Note:** A stone block contains 4 stone pieces. When you mine the stone block, sometime, it will create the 4 stone pieces at the sametime and in the other cases, when you mine the stone block, it will create **2 stone pieces and 1 stone slab.** The **stone slab cannot be pick up**, you will have to mine it, and it will create 2 stone pieces and then you will be able to pick it up.

**Comment by Exterminator165** [comment] 2018-03-02 21:34
Hi,
no, the blocks seperate as they should in 2 small and one medium blocks. But after that the original stone is still there but no longer mineable. And the small and medium stones disappear and after a second they Rain down on the World.
Sorry, I'm german so it may be difficult to read, sometimes.
Thanks for your quick Feedback!
BR
Michael 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 02.03.18, 21:54, fillion07 <notifications@github.com> schrieb:
Is the problem related to the stone block not being able to be seperated in 4 with a pickaxe Or is it because you are not able to pick up the stone piece from the ground while pressing "E".
Note: A stone block contains 4 stone pieces. When you mine the stone block, sometime, it will create the 4 stone pieces at the sametime and in the other cases, when you mine the stone block, it will create 2 stone pieces and 1 stone slab. The stone slab cannot be pick up, you will have to mine it, and it will create 2 stone pieces and then you will be able to pick it up.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/StrangeLoopGames/EcoIssues","title":"StrangeLoopGames/EcoIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/StrangeLoopGames/EcoIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fillion07 in #5309: Is the problem related to the stone block not being able to be seperated in 4 with a pickaxe Or is it because you are not able to pick up the stone piece from the ground while pressing \"E\".\r\n\r\n**Note:** A stone block contains 4 stone pieces. When you mine the stone block, sometime, it will create the 4 stone pieces at the sametime and in the other cases, when you mine the stone block, it will create **2 stone pieces and 1 stone slab.** The **stone slab cannot be pick up**, you will have to mine it, and it will create 2 stone pieces and then you will be able to pick it up."}],"action":{"name":"View Issue","url":"https://github.com/StrangeLoopGames/EcoIssues/issues/5309#issuecomment-370049486"}}}

**Comment by SeanAtr0n** [comment] 2018-03-02 21:43
Sounds like the chunk renderer stopped updating... seems to happen less often for me in 7.2 but i'm not sure if anything was changed to fix that

**Comment by MarjieAVolk** [comment] 2018-03-03 00:43
Wait, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3469

**Closed by MarjieAVolk** 2018-03-03 00:43 UTC
Labels: High Priority
