### ISSUE TITLE
Crimini Mushrooms Are Missing

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#5788] opened 2018-03-09 18:52 UTC
I know that there were several of these that have been closed but 7.2 is acting about mushrooms much like we had the issue with beans and wheat.  World after world is spawning with 0 mushrooms and they do not appear after time is given for a growth cycle to spane new.    I know that this has been close with 'expected behavior' but not sure if that means there should never be mushrooms  or it was assumed that players did not wait long enough for them to finally show up.  We have had worlds up since 7.2 launched and still 0 Crimini Mushrooms.  Maybe I am ready 0.7 maturity rate as shorter then it is and there just has not been time for them to show up.

**Comment by Thyriel** [comment] 2018-03-09 19:35
https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Comment by MarjieAVolk** [comment] 2018-03-09 20:27
Closing as duplicate of #5568

**Closed by MarjieAVolk** 2018-03-09 20:27 UTC
