### ISSUE TITLE
USER ISSUE: Unable to interact with anything

### ISSUE THREAD

**Issue by collinticer** [StrangeLoopGames/EcoIssues#24563] opened 2024-01-07 18:46 UTC
\
**User Id: (slg204049)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Log into server. Walk up to a world object. It highlights green. I'm also touching the object (so it's not an issue with being too far away). I can't press 'E' to interact. Nothing happens. Logging out and back in several times, and sometimes restarting the game fixes it. No one else seems to have this issue. It also doens't track where I moved to, so if I log out and log back in, any movement I had made wasn't recorded. I'm admin as well if that makes any difference, but there are 2 other admins on this server who don't experience this.

**Expected behavior:**
I should be able to interact without having to log off and back on so many times.

**Actual behavior:**
I have to log off and on many times just to get the game to a point where I can interact with objects.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, we have discordlink. The issue doesn't happen for anyone else, 10+ other players. I have no idea if it happens without this one mod.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment] 2024-01-07 21:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24545.

Please attach logs there, the issue is not reproducable and only seems to affect very few people.

**Closed by D3nnis3n** 2024-01-07 21:43 UTC
