### ISSUE TITLE
Crash: Setting MeteorImpactInDays too high causes server to crash during launch

### ISSUE THREAD

**Issue by Emperor-Q** [StrangeLoopGames/EcoIssues#25171] opened 2024-09-19 16:22 UTC
Bug:
Setting the Meteor Impact In Days while playing the game from the settings panel as an admin to some high value will lower the value to 10^10. However a 32bit integer is apparently used to load this value while the server launches, which is unable to store this value. This causes the server to crash when attempting to load after setting the value and gives the following error message:

Failed to start the server. Exception was Exception: OverflowException Message:Value was either too large or too small for an Int32. Source:System.Private.CoreLib

No crash occurs after setting the value while in the server.

User ID:8c83f65f-4960-4924-cae6-08dcd3649fe
[log_240919050733.log](https://github.com/user-attachments/files/17062795/log_240919050733.log)

**Comment by D3nnis3n** [comment] 2024-09-19 19:20
That is not a bug, the server is intended to crash when invalid values in configs are entered. I have noted it as a improvement suggestion internally instead.

**Comment by Emperor-Q** [comment] 2024-09-19 19:25
> That is not a bug, the server is intended to crash when invalid values in configs are entered. I have noted it as a improvement suggestion internally instead.

The bug is that if I try to set the value to, say, 10^12, it will reduce the value to 10^10.
Note this only applies when trying to set the value in game, it doesn't apply to edits made within the editor.

**Comment by D3nnis3n** [comment] 2024-09-19 19:32
I'm not sure I can follow - what editor do you mean? You reported that there is a crash if a invalid setting is set, that is working as intended, but now you seem to mean something else?

**Comment by D3nnis3n** [comment] 2024-09-19 19:39
Aha, that makes much more sense!

**Comment by D3nnis3n** [comment] 2024-09-19 20:05
So basically the issue is that the ingame menu accepts a value that is invalid, leading to a crash on reboot as the invalid value has been saved to the configs. I could have sworn on the first time I read the task description it didn't note the ingame menu, but that might have been on Steam.

**Comment by Emperor-Q** [comment] 2024-09-19 20:08
> So basically the issue is that the ingame menu accepts a value that is invalid, leading to a crash on reboot as the invalid value has been saved to the configs. I could have sworn on the first time I read the task description it didn't note the ingame menu, but that might have been on Steam.

Yes, that's the issue.

Possibly, I realised about posting here after I made the steam post, though I figured I'd keep that one up in case it wasn't fixed for a while and someone else had the issue.

**Comment by D3nnis3n** [comment] 2024-10-04 16:28
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14514 in staging.

**Closed by D3nnis3n** 2024-10-04 16:28 UTC
Labels: Type: Bug
