### ISSUE TITLE
USER ISSUE: Falling through world

### ISSUE THREAD

**Issue by chmilk1** [StrangeLoopGames/EcoIssues#7148] opened 2018-04-12 01:32 UTC
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
1. find a unloaded chunck
2. jump

**Expected behavior:**
load chunck, or reset pos after -10000000000 blocks under ground

**Actual behavior:**
fall and make loud falling noises

**Comment by MarjieAVolk** [comment] 2018-04-12 01:49
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6881

**Closed by MarjieAVolk** 2018-04-12 01:49 UTC
