### ISSUE TITLE
USER ISSUE: online, realy?

### ISSUE THREAD

**Issue by FrancoisECO** [StrangeLoopGames/EcoIssues#6722] opened 2018-03-30 04:36 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
People who left the game are still considered as "online".
Only a restart of the server clean this status

**Expected behavior:**
Offline people

**Actual behavior:**
Online "Offline" People

**Comment by darkshad9999** [comment] 2018-03-30 07:43
March 30 2018,

Ya I know what you are talking about .... and there is some kind of bug in 0.7.3.0 Beta 
with it showing people online that are not really online at the time.  I can confirm this 
I am playing on a 0.7.3.0 Server and the people were on earlier on in the day but are 
not currently online but yet if you do a /players it will show them as currently being
online when they are not. 

So right now the server I play on shows that there are 17 people currently online at the 
start screen before you click on continue. I log in and I am the only one actually on
there may have been 17 people on the server since the server booted up but this 
server is really quiet and not many active people on it so I know for a fact that there
is not currently 17 people online playing at 1:40 AM MST (GMT-0700) 

It is like people log in but when they log out it never updates the status that the 
person has logged out of the game.

![eco online players bug march 30 2018 ss 1](https://user-images.githubusercontent.com/4023976/38129301-b52d5e9a-33bb-11e8-9f18-f37ae47f53d1.jpg)


![eco online players bug march 30 2018 ss 2](https://user-images.githubusercontent.com/4023976/38129306-bc0de05e-33bb-11e8-8d57-9a90dc04ff8a.jpg)

**Comment by MarjieAVolk** [comment] 2018-03-30 17:48
Fixed in 7.3.1 (#6672)

**Closed by MarjieAVolk** 2018-03-30 17:48 UTC
