### ISSUE TITLE
Mining advanced upgrade faulty?

### ISSUE THREAD

**Issue by Enel300** [StrangeLoopGames/EcoIssues#23324] opened 2022-07-26 08:58 UTC
Hello,

I noticed at the Stamp Mill that the resource costs are not reduced by 50% but remain the same. No matter whether with or without the module. For 400 Crushed Ore I need 2000 Iron Ore. With the module, this should only be 1000, right?

**Comment by Daniel-Magulado** [comment] 2022-07-26 09:11
Hi @Enel300 

Thank you for submitting this report. This is actually intended. If you hover your mouse icon over the required resources, it is indicated in the tooltip that it is of a static value, and module or modifiers will not affect it.
![image](https://user-images.githubusercontent.com/77248866/180969308-19ed3200-d85d-405c-a4f6-e964ecff4cf9.png)

On the other hand, modules reduce the time it takes to craft items for this type of crafting table.

With that, I will be closing this issue as it is not a bug. We do, however, encourage you to report any bugs or unusual things you find in-game. Please do not hesitate to let us know anything you find or encounter in game.

Thank you!

**Closed by Daniel-Magulado** 2022-07-26 09:11 UTC
