### ISSUE TITLE
[7.6.2] Multiple glitches involving ramps when going over the 0 point marker on X axis of map.

### ISSUE THREAD

**Issue by X-ITT** [StrangeLoopGames/EcoIssues#8681] opened 2018-07-22 07:59 UTC
First case:
When driving a cart over a ramp at the 0 point marker (coordinate) on the x-axis of the map, screen goes black. (happens without cart also)
![ezgif com-optimize](https://user-images.githubusercontent.com/11493473/43043425-9e3b525a-8d61-11e8-8061-df678ae6e60d.gif)
Then ramps disappear visually when viewing at certain angles.
![screenshot 7](https://user-images.githubusercontent.com/11493473/43043443-07c27712-8d62-11e8-9c34-33cf5f73672a.png)
Save file for reproduction purposes: [Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2216807/Game.zip)

Second case:
When running on ramps underground on the 0 point marker on the x axis of map, get ported above to ground level. (This might occur without ramps too, but not sure, should be tested.)

Note: I've only seen these glitches happen when the x axis goes to zero, but i'm assuming it could also possibly occur at zero on the y axis.

Current fix for those facing the same issue:
Remove ramp, install platform. Note: Do NOT go into game files and remove all ramps that would be absurd and the dumbest idea i've ever heard in my life.
![screenshot 9](https://user-images.githubusercontent.com/11493473/43043728-5bb72d9a-8d67-11e8-9b13-a0753289f526.png)

**Comment by craig-jong** [comment] 2018-08-17 17:59
Word wrapping issues - this might actually already be fixed with the new blockform ramps, but it might be a good idea to double check.

**Comment by Spydarlee** [comment] 2018-08-22 14:13
Yeah, looks like this has been fixed already! Couldn't reproduce on the latest staging build.

**Closed** 2018-08-22 18:16 UTC
Labels: Medium Priority, Not reproduced
