### ISSUE TITLE
USER ISSUE: Connection failed after creating a new world

### ISSUE THREAD

**Issue by Nobody-x** [StrangeLoopGames/EcoIssues#4513] opened 2018-02-14 12:27 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
1. install the game
2. launch
3. create new world

**Expected behavior:**
Connect me to my new world

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

Server dump
[Crash AggregateException 02143406.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1723982/Crash.AggregateException.02143406.zip)

NB: If I launch the server myself, I can join it.

**Comment by MarjieAVolk** [comment] 2018-02-14 20:58
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4305

**Closed by MarjieAVolk** 2018-02-14 20:58 UTC
