### ISSUE TITLE
USER ISSUE: Missing Thing for Farming Research

### ISSUE THREAD

**Issue by Terrenor1** [StrangeLoopGames/EcoIssues#5092] opened 2018-02-25 19:58 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Build a Research Station
Look at Farming Recipe
Search for Crimini Mushrooms or Spores
Try to find with Map

.....

**Expected behavior:**
There should be Crimini Mushrooms on my Map	

**Actual behavior:**
I cant research farming...

**Comment by MarjieAVolk** [comment] 2018-02-26 18:58
Is the problem that you can't find the crimini mushroom option in the minimap drop down?  Or that there are no crimini mushrooms in your world?

**Comment by Terrenor1** [comment] 2018-02-26 19:04
The Drop down in the map is there, but there are no spots on the map.

I started a new map and there i found them.



Am 26.02.2018 um 19:58 schrieb MarjieAVolk:

**Comment by MarjieAVolk** [comment] 2018-02-26 23:16
Okay, thanks.  It is still possible to spawn a world that has none of a particular species.  It would be nice if we could address that one day.

**Comment by SirTsu** [comment] 2018-03-05 13:41
I´m having the same issue. We started to play with friends and already have spent some time in the game. Then we decided one should go for farming,but thats impossible due to no crimini mushrooms. 
Then I started another game and this this time there were enough mushrooms, but now completely missing the corn in the world, which is another important ingredient for the farming recipe..
Please invest the problem as soon as possible, it really frustrating. Eco is such a great game otherwise..

**Comment by MarjieAVolk** [comment] 2018-03-28 21:18
By the way guys, I learned you can use '/regenlayer CriminiMushroom' to try to bring mushrooms to your world if they are missing.  You can do this with any species.  It will only work if there is an area in the world that is suitable for mushrooms (eg. wetlands), but it might help.

**Comment by Thineboot** [comment] 2018-03-29 09:33
> It will only work if there is an area in the world that is suitable for mushrooms (eg. wetlands)

That's the point. WorldGenerator has to make sure that there are all necessary biome types generated, that all plants and wildlife has a space to live in. Otherwise you may end up in a world were you realize after many hours/days that you can't finish various tasks at all. To top it you need an admin who knows these commands in the first place. And you've proven that even you haven't known it til yesterday ;)

**Comment by MarjieAVolk** [comment] 2018-04-03 00:11
Just offering a workaround, I know it is not a permanent solution.

**Comment by Thineboot** [comment] 2018-04-04 21:11
Could you add a small test when a world is generated and inform the player when there is a rerun necessary?

**Comment by MarjieAVolk** [comment] 2018-04-09 17:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568

**Closed by MarjieAVolk** 2018-04-09 17:12 UTC
Labels: Medium Priority
