### ISSUE TITLE
USER ISSUE: Block when loading game

### ISSUE THREAD

**Issue by plex68** [StrangeLoopGames/EcoIssues#24749] opened 2024-02-07 16:21 UTC
\
**User Id: (slg103069)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
This connect to the game server

**Expected behavior:**
Connect to the game server without being blocked when loading

**Actual behavior:**
The game will freeze at "World loading 100%"

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes words are installed on the server, even without any mod the problem occurs. I'm not the only player on the server experiencing the problem, I uninstalled the game, cleared the cache, file check nothing changed. We noticed that if we wait more than 20 min on loading we can access the server.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by plex68** [comment] 2024-02-07 16:26
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14196544/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14196545/Player-prev.log)

**Comment by D3nnis3n** [comment] 2024-02-08 06:48
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24671

**Closed by D3nnis3n** 2024-02-08 06:48 UTC
