### ISSUE TITLE
Server Crush Dump: Client Network Exception Lite Exception

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [StrangeLoopGames/EcoIssues#6102] opened 2018-03-15 21:20 UTC
Version: 0.7.2.4 beta

Full Stack Trace:
--BEGIN DUMP--
Dump Time
03/13/2018 22:19:10

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   at LiteDB.LockService.Write()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.PropertyClaimItem.TryPlaceObject(Player player, Vector3i position, Quaternion rotation)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass13_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

**Comment by MarjieAVolk** [comment] 2018-03-15 21:21
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343

**Closed by MarjieAVolk** 2018-03-15 21:21 UTC
