### ISSUE TITLE
[7.4] Server Browser Filter settings return to  default 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7268] opened 2018-04-18 03:53 UTC
After setting up the filer you want to use  for loating servers and hit apply there seems to be no other way to 'lock' the  chosen filter so when you disconnect from a  server or logout of the client and then log back in the filters have returned to default and have to be set up again.    Is there no way to save filter settings or are we missing how that is done?

**Comment by pamduncan** [comment] 2018-04-26 13:11
I see a Respond ASAP... but not sure what info is needed

**Comment by MarjieAVolk** [comment] 2018-05-07 22:07
Lol the respond asap tag is meant for us to respond to you asap, which did not happen apparently.  Closing this as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7526

**Closed by MarjieAVolk** 2018-05-07 22:07 UTC
