### ISSUE TITLE
"Roots are too strong"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9005] opened 2018-08-18 14:24 UTC
I get the following error:
No tree, tree stump, debris or whatever in the near. :(

<img width="1522" alt="eco" src="https://user-images.githubusercontent.com/25908592/44300176-080b7c80-a303-11e8-83af-daeed4ff04ba.png">

**Comment by Nicolausi113** [comment] 2018-08-18 14:36
There is an invisible root or stump in the block. Restarting server and game may make it visible, or try to dig it from the side like digging a shrub.

**Comment by D3nnis3n** [comment] 2018-08-19 05:41
Unfortunatley none of your suggested actions did fix the problem :(

**Comment by Nicolausi113** [comment] 2018-08-19 07:16
Pooh – a persistent glitch- sorry.
One last idea: selecting an axe and focusing the block possibly lets you chop out the phantom.

**Comment by D3nnis3n** [comment] 2018-08-19 16:11
Even that does not work :( No marketplace then, lol.

**Comment by johnkslg** [comment] 2018-08-20 19:18
Can you attach the save and advise location of bug?

**Comment by johnkslg** [comment] 2018-08-21 05:28
@D3nnis3n let me know if you can attach the game.eco file

**Comment by D3nnis3n** [comment] 2018-08-21 05:32
I can't attach it, but i will be able to upload it on our page. It's 375 MB - 16 km² world.
Wait a moment.

**Comment by D3nnis3n** [comment] 2018-08-21 05:41
https://godsofwar.de/Game.zip

If you spawn, you'll be in front of a distribution center on a quarter-done marketplace. You'll see the 3x3 patch dirt in it next to the road.

**Comment by D3nnis3n** [comment] 2018-08-21 06:32
Oh well, for game.db file you would need to wait until tonight. Too many players online and can't zip or move that as it's in use, would be corrupted otherwise. Unfortunatley we not had yet a time where no players were online, so i'll do it at least when most are offline.

**Comment by mirasrael** [comment] 2018-08-21 06:54
It looks no need for DB file. Sorry for disturb

**Comment by mirasrael** [comment] 2018-08-21 06:55
Can you provide exact coordinates?

**Comment by D3nnis3n** [comment] 2018-08-21 06:55
Dumb question: Where can i read exact coordinates of where i'm standing on?

**Comment by mirasrael** [comment] 2018-08-21 06:56
![image](https://user-images.githubusercontent.com/475445/44385580-7d0bcb80-a528-11e8-8db4-c83cc77a3f8d.png)

**Comment by mirasrael** [comment] 2018-08-21 06:57
![image](https://user-images.githubusercontent.com/475445/44385631-a4fb2f00-a528-11e8-9789-06a1364e3d18.png)

**Comment by mirasrael** [comment] 2018-08-21 06:57
If it is a right place then I was able to dig it

**Comment by D3nnis3n** [comment] 2018-08-21 07:03
Yeah, it is that place oO

**Comment by mirasrael** [comment] 2018-08-21 07:05
I tested it on master (after 7.7). Now testing in 7.7

**Comment by D3nnis3n** [comment] 2018-08-21 07:12
Well, we are still on 7,6,3 i think?

But you can stop testing it now, i was able to dig that up with no problems some seconds ago - maybe the server crash yesterday fixed it. The restart i did, did not. :/ Sorry to bother you.

It would be good if those invisible stumps wouldn't be there at all, though.

**Comment by mirasrael** [comment] 2018-08-21 07:16
Yes, but 7.7 will be released really soon :) And I also wasn't able to reproduce that on 7.7. So looks like these invisible stomps gone.
Sure, they shouldn't but I have to reproduce it to find them and understand why their appeared.

**Comment by D3nnis3n** [comment] 2018-08-21 07:18
I know. Feel free to close the issue :)

**Comment by D3nnis3n** [comment] 2018-08-21 08:05
Haha, thank you. It would look even better if we didn't get 10 tailings per 10 ore on max efficiency ;)
We really got no idea how to manage treatment of this. I would need two people digging the complete day, every day.

**Comment by johnkslg** [comment] 2018-08-22 18:12
Looks fixed!

**Closed by johnkslg** 2018-08-22 18:12 UTC
Labels: High Priority, Not reproduced
