### ISSUE TITLE
Fir trees don't seem to get completely deleted

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3827] opened 2018-02-03 18:43 UTC
Stump collider never gets removed
Tree object never gets deleted from the server after stump deleted + all logs picked up

Oak might have the same problems

Birch/Cedar work fine

**Comment by Nanders** [comment] 2018-02-03 21:30
Any idea what might cause this? Unfamiliar with how the sim and trees are supposed to interact in this way.

**Comment by Senlarus** [comment] 2018-02-06 22:22
@Nanders On my issue, #3986 it turns out it was a log not a stump. After a server reboot, when I went back to that area I saw a small thin oak log laying flat against the ground. I picked it up into my inventory and placed it in my stockpile and there is no more collision at that spot for me. I guess it wasn't a stump afterall.

**Comment by Nanders** [comment] 2018-06-18 18:46
closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4908

**Closed by Nanders** 2018-06-18 18:46 UTC
Labels: Medium Priority
