### ISSUE TITLE
8.0.0 Skill Windows opens to almost full screen no way to change size

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10751] opened 2019-01-18 12:52 UTC
**Version:** 0.8.0.0 beta master-0d4ca997

![snap3846](https://user-images.githubusercontent.com/29383891/51387952-d4d25100-1b1f-11e9-8077-161aed3ea4c5.png)
as you can see the Skill window opens to a massive size and no option to make it smaller

**Comment by elfl0rd** [comment] 2019-01-18 13:19
Duplicate of #10714

**Closed by elfl0rd** 2019-01-18 13:19 UTC
