### ISSUE TITLE
USER ISSUE: Sea level bug/stuck

### ISSUE THREAD

**Issue by GDCReXes** [StrangeLoopGames/EcoIssues#11553] opened 2019-03-03 09:56 UTC
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
On edit blocks on the beach we noticed a presentation error of the water.
The Water dont flow in the uncovered area.

**Expected behavior:**
No grafik bugs, flow behavior of the water

**Actual behavior:**
Grafikfehler, Kein richtiges ausgleichverhalten beim Wasser
grafik bugs,No correct flow behavior of the water

**Do you have mods installed? Does issue happen when no mods are installed?:**

NO MODS INSTALLED

**Comment by D3nnis3n** [comment] 2019-03-03 11:43
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1424

**Closed by D3nnis3n** 2019-03-03 11:43 UTC
