### ISSUE TITLE
[0.9.3.1] Elections counting votes that became invalid later

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21852] opened 2021-05-11 21:47 UTC
Earlier in the White Tiger run we had a small conundrum - should votes cast by people that later become ineligable to vote still count in the elections. It feels like this should be an option when someone sets up an election.

So say, we have voting for a local Senator based on a District citizenship. One could try exploting this by voting in one district, moving to another district, voting there and so on until they voted everywhere and all of their votes would still count. We ruled that as abuse. It would be good to have an option for the old votes to be discarded when someone moves and can't vote in their original district to make this kind of abuse less useful.

A different scenario was senators voting on a law. During the vote, one of the senators lost their position / was replaced. Their vote still counted. In this scenario you might justify that it's still a valid vote since they weren't doing anything maliciously, but at the same time you could say someone could try maliciously calling a vote that straddles elections to get some extra votes in by replacing the voters mid-vote and getting to vote double.

One way or another, it would be useful to have these scenarios as explicit settings in the election process so people can decide how they want to be governed.

**Comment by IcedForge** [comment] 2021-05-12 13:53
Thank you for reporting. Closing as duplicate of #20085

**Closed by IcedForge** 2021-05-12 13:53 UTC
