### ISSUE TITLE
[0.9.3.1] Unable to edit the name of newly created bank account

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21477] opened 2021-04-20 04:18 UTC
When I created a new bank account, I didn't see the option to edit its name:

![image](https://user-images.githubusercontent.com/964559/115336734-98ee2200-a154-11eb-86f7-01d601512feb.png)

However, when I restarted the game, the option became available. Happaned to me twice, once for a personal and once for a government account.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6340575/Player.log)

**Comment by Daniel-Magulado** [comment] 2021-04-21 10:57
Hi, thank you for making a report about this.
May we asked the things you have first done before opening a new bank account?
If possible, it would help us investigate this further if you could provide us with a recorded video as the issue happens.

The log that you provided contains a lot of _Failed to handle RPC_ and _ArgumentException: The Object you want to instantiate is null_. I'll be moving this ticket to our Investigate section to find a solid reproduction step to trigger this issue.

Thank you.

**Comment by ThePiachu** [comment] 2021-04-23 00:44
I've tried to repo this twice. First time, log in right next to the bank - everything works fine:

https://youtu.be/cbxwJrWNPc8
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6361957/Player-prev.log)

Second time, log in a bit further out, walk to the bank, and then the issue appeared again:

https://youtu.be/MWOiS3w9I3s
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6361959/Player.log)

So it seems the error might be caused by the Bank loading into the world or something?

**Comment by MishkaFur** [comment] 2021-05-06 19:34
Getting the same as well, just does not show the edit pencil icon, had to use /objects edit bank accounts,ID instead

![image](https://user-images.githubusercontent.com/61889138/117355400-7117f180-aeaa-11eb-8e2d-253322431e86.png)

![image](https://user-images.githubusercontent.com/61889138/117355456-812fd100-aeaa-11eb-8626-d266159ce065.png)

**Comment by Daniel-Magulado** [comment] 2021-08-05 19:08
Hi @ThePiachu and @MishkaFur 

Are you both still encountering this issue? I'm still unable to reproduce in 0.9.3.6 Release-235.

**Comment by ThePiachu** [comment] 2021-08-06 06:35
I think I created a few accounts in a newer version of the game and didn't run into this issue.

**Comment by Daniel-Magulado** [comment] 2021-08-06 16:54
Hi @ThePiachu 

Thank you for your reply.
I'll be closing this for now but feel free to reopen if you ever encounter this issue again.
I'm assuming that it's a network/server sync issue that should be fixed now.

Thank you.

**Closed by Daniel-Magulado** 2021-08-06 16:54 UTC
Labels: Status: Investigate
