### ISSUE TITLE
the shadow in the evening is worse than  the night

### ISSUE THREAD

**Issue by Hanan09** [StrangeLoopGames/EcoIssues#2356] opened 2017-09-27 21:49 UTC
between afternoon and evening  is the worst part of the day  for vision 
![ice_screenshot_20170928-000124](https://user-images.githubusercontent.com/31784528/30939615-ac186382-a3e6-11e7-903b-9e953652a6e5.png)
![ice_screenshot_20170927-234854](https://user-images.githubusercontent.com/31784528/30939620-af15516c-a3e6-11e7-89ee-30beb394472e.png)
![ice_screenshot_20170927-234724](https://user-images.githubusercontent.com/31784528/30939628-b2aeb8a4-a3e6-11e7-820a-8bc9ad102c3b.png)
![ice_screenshot_20170927-120955](https://user-images.githubusercontent.com/31784528/30939636-ba0dc41e-a3e6-11e7-81b9-63dadaac3df4.png)

**Comment by MarjieAVolk** [comment] 2017-09-27 22:00
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2349

**Closed by MarjieAVolk** 2017-09-27 22:00 UTC
