### ISSUE TITLE
USER ISSUE: Workbench

### ISSUE THREAD

**Issue by Greatzeus1** [StrangeLoopGames/EcoIssues#9693] opened 2018-10-13 20:50 UTC
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Go to workbench and after leveling up efficency for any items, the workbench is still the same.
The efficency does affect the other tables, just not the workbench.

**Expected behavior:**
changed the items required to a lower amount.

**Actual behavior:**
stays the same value, regardless of leveling or relogging.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
stays the same value, regardless of leveling or relogging.

**Comment by pamduncan** [comment] 2018-10-14 00:31
If what you are trying to craft gets crafted in another table.. you have to use the specialty table to get efficiencies applied.  For example say you want to craft some type of wall block to build you house and its one of the itens the workbench will let you make  btu that block is something that can be crafted in a specialty table, like the crafting table.  If you use the Carpentry table to make the block it will account for an apply your efficiencies.  The workbench, however, as a primitive tool, does not take into consideration as to whether you have efficences and doe not apply them.

I believe this was done with some lower level craftables that would normally be crafted at a specialty table which the person may not be able to make as they are focusing on other specialties.  They still need those walls to build there starter house so need to be able to craft then and they have that opportunity to do so on the work bench at full cost and no efficiencies applied.  If you happen to be taking that skill tree then you would need the crafting table so needing to build it for the bonuses, and not just forever use the workbench in your tent so this encourages you to get the table for your specialty so you have the right bonuses applied.

So the workbench is working as designed and that is its expected behavior.

**Comment by Deantwo** [comment] 2018-10-14 11:41
All recipes in the workbranch don't benefit from efficiency skills.

**Comment by Deantwo** [comment] 2018-10-14 11:48
DlPossible duplicate of: #8666

**Comment by seccombew** [comment] 2018-10-15 17:47
@Greatzeus1 We are redoing efficiency completely in 8.0, so closing.

**Closed by seccombew** 2018-10-15 17:47 UTC
Labels: Needs Triage
