### ISSUE TITLE
Client Bug | Unable to get back to server list after attempting to join white-listed server

### ISSUE THREAD

**Issue by Freakygnome** [StrangeLoopGames/EcoIssues#974] opened 2017-01-04 06:43 UTC
Alpha 5.2 Client (64bit version) on Windows 10 64bit

Bug occurs every time when trying to join a server with "private server" enabled.
If you are not on the white-list you get the error "Connection Failed You are not on the private servers white-list." after clicking to acknowledge the message disappears however the server list does not return.
If you close the game at this point it hangs(Not Responding) for about 30 seconds then closes.

The escape menu still works so you can select logout and then login again to get back to the server list however I have been unable to type in either the username or password box on multiple occasions. 

![eco_2017-01-04_16-57-40](https://cloud.githubusercontent.com/assets/24909516/21633530/f9679b12-d29f-11e6-9858-5879db0fae8f.png)
![eco_2017-01-04_16-57-48](https://cloud.githubusercontent.com/assets/24909516/21633543/0d98b364-d2a0-11e6-9882-cd1c305d3c7a.png)

**Comment by MarjieAVolk** [comment] 2017-04-28 18:51
Just tested this out and I can't reproduce this behavior, so I'm presuming that this is fixed now.  If you are still experiencing it, feel free to reopen.

**Closed by MarjieAVolk** 2017-04-28 18:51 UTC
