### ISSUE TITLE
USER ISSUE: Roots too strong

### ISSUE THREAD

**Issue by bOOmerDK** [StrangeLoopGames/EcoIssues#12505] opened 2019-06-10 08:11 UTC
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Cant dig in dirt

**Expected behavior:**
remove dirt

**Actual behavior:**
instead says roots too strong

**Do you have mods installed? Does issue happen when no mods are installed?:**
instead says roots too strong

**Comment by SlayksWood** [comment] 2019-06-10 08:14
@bOOmerDK 
The tree grows near. Its roots don't allow to dig. You have to chop the tree, then chop the stump. After this you can dig this block of dirt.
If there is no tree near describe the situation, please.

**Comment by bOOmerDK** [comment] 2019-06-10 08:16
There are no trees nearby. Now there are 13 blocks of dirt flowting in the air

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

________________________________
Fra: Kirill <notifications@github.com>
Sendt: Monday, June 10, 2019 10:14:40 AM
Til: StrangeLoopGames/EcoIssues
Cc: bOOmerDK; Mention
Emne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Roots too strong (#12505)


@bOOmerDK<https://github.com/bOOmerDK>
The tree grows near. Its roots don't allow to dig. You have to chop the tree, then chop the stump. After this you can dig this block of dirt.
If there is no tree near describe the situation, please.

**Comment by SlayksWood** [comment] 2019-06-10 08:20
@bOOmerDK 
Please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
And if it possible provide save files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
You can provide a couple of screenshots, it will also help.

**Comment by D3nnis3n** [comment] 2019-06-10 11:52
This is a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10550.

**Closed by D3nnis3n** 2019-06-10 11:52 UTC
Labels: Needs Information
