### ISSUE TITLE
USER ISSUE: Black screen

### ISSUE THREAD

**Issue by TickTaeck** [StrangeLoopGames/EcoIssues#6891] opened 2018-04-02 14:41 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Pulling the Wood Cart

**Expected behavior:**
Normal View

**Actual behavior:**
getting a black screen from time to time

**Comment by MarjieAVolk** [comment] 2018-04-02 21:37
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4370

**Closed by MarjieAVolk** 2018-04-02 21:37 UTC
