### ISSUE TITLE
USER ISSUE: No Tailings glitch

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11550] opened 2019-03-03 01:30 UTC
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
link your blast furnace to a chest, not a stockpile
start a smelting order of iron, with less or the equal amount of iron ore needed for the job.  
link the stockpile for a second to let it pick up the iron ore, unlink quickly after that.
wait until the job is finished.
put something in the chest or move something in it around to update it.
the iron will be put into the chest and the tailings are voided

**Expected behavior:**
tailings has to be pulled out the blast furnace

**Actual behavior:**
they are gone

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods, vanilla multiplayer

**Comment by D3nnis3n** [comment] 2019-03-03 11:44
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10916

**Closed by D3nnis3n** 2019-03-03 11:44 UTC
