### ISSUE TITLE
Server Error: InvalidDataException

### ISSUE THREAD

**Issue by WatSamma** [StrangeLoopGames/EcoIssues#24901] opened 2024-04-21 11:24 UTC
Hello,

the file: https://drive.google.com/file/d/1fPHdcX1h-rlefFCIxW0qZ384rrxFFdwk/view?usp=sharing

the error log:

[04:08:16.490] [25] [Error] [Eco] Errors report:
Failed to start the server. Exception was Exception: InvalidDataException
Message:Error decoding Referenceable
Source:Eco.Core

System.IO.InvalidDataException: Error decoding Referenceable
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeReferenceableEnumerable(BinaryReader reader, Object decodeTarget, Int32 numElements)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeEnumerable(BinaryReader reader, Object decodeTarget)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.EcoSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream)
   at Eco.Core.Serialization.DataStore.<>c__DisplayClass49_1`1.<LoadAsync>b__1()
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Error(s) occurred when loading World (Error decoding Referenceable)
: 1

**Comment by D3nnis3n** [comment] 2024-04-22 03:34
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24900

**Closed by D3nnis3n** 2024-04-22 03:34 UTC
