### ISSUE TITLE
USER ISSUE: Invisible Bloomery

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#9459] opened 2018-09-21 05:19 UTC
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Leave area.
2. Come back to area.

**Expected behavior:**
The bloomery should still be visible.

**Actual behavior:**
The bloomery is invisible, you can still collide with it however and the fire and smoke animation is still visible along with the green outline when selected.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The bloomery is invisible, you can still collide with it however and the fire and smoke animation is still visible along with the green outline when selected.

**Comment by D3nnis3n** [comment] 2018-09-21 12:59
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/9263

**Comment by seccombew** [comment] 2018-09-21 17:46
Dup

**Closed by seccombew** 2018-09-21 17:46 UTC
Labels: Needs Triage
