### ISSUE TITLE
Trees/grass can grow on full stockpiles

### ISSUE THREAD

**Issue by cjAnteka** [StrangeLoopGames/EcoIssues#6902] opened 2018-04-02 23:29 UTC
Should probably stop this from happening.

**Comment by MarjieAVolk** [comment] 2018-04-02 23:31
Same as https://github.com/StrangeLoopGames/EcoIssues/issues/2733 - meta doesn't seem to want to fix it though, so if you are going to then I'll close that one :P

**Comment by ShaydenMac** [comment] 2018-04-02 23:35
[https://clips.twitch.tv/ConfidentDirtyDragonMrDestructoid](url)

**Comment by elfl0rd** [comment] 2018-12-05 16:19
@D3nnis3n can you select one issue from duplicates? this newest, but contain more information...

**Comment by Florian7843** [comment] 2021-09-26 11:31
Dear Gods of SLG,

I hereby ask you to please fix this, because it's annoying like hell. It even seems to be a quite easy fix, because you already are able to tell whether a block is inside a stockpile, as the players get an error message when trying to pick up a block from a stockpile.

I'd even be willing to do this myself if I didn't have to pay for developer tier to get access to src...

**Comment by WeaselDog** [comment] 2022-08-29 00:16
Thank you for reporting this bug! I can confirm this has been fixed in the upcoming 9.6 update

**Closed by WeaselDog** 2022-08-29 00:16 UTC
Labels: Priority: Medium, Status: Fixed, Category: Gameplay, Squad: Otter
