### ISSUE TITLE
USER ISSUE: ghost of naturally regrown firtree

### ISSUE THREAD

**Issue by wodofoto** [StrangeLoopGames/EcoIssues#5668] opened 2018-03-08 10:41 UTC
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
1. cut down firtree, including roots - wait for young firtree to appear.
2. use axe to remove the newly grown tree
3. wait for it to reappear at exact same location
4. use axe to remove it again
5. end playsession (single player world)
6. start game, look around, small firtree is back
7. use axe to remove it (stone or iron axe, both lead to crash)

**Expected behavior:**
regrown firtree should not have been there again so quick. and if it was, it should again be removeable with an axe.

**Actual behavior:**
young firtree was just a ghost. i could dig out the earth underneith it, place dirt ontop of it, but still interact with an axe, what finally lead to the following crash report and me having the 'hologram' of a young firtree in my soon to build house.

The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONOb

**Comment by MarjieAVolk** [comment] 2018-03-08 19:57
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5619

As for the other weird behavior you saw... sounds like it could be related to server lag?

**Closed by MarjieAVolk** 2018-03-08 19:57 UTC
