### ISSUE TITLE
Game not releasing players when they log out.

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6825] opened 2018-04-01 05:21 UTC
Been having issues all day with people unable to reconnect after leaving game.  Screenshot was taken of the serverUI connection list 10 minutes after all players left the server.  None were able to log back in.  had to restart server to disconnect them and make the sever know that the player had left the game.

[![Screenshot from Gyazo](https://gyazo.com/759aedb254e82d28c7ace605b9f608be/raw)](https://gyazo.com/759aedb254e82d28c7ace605b9f608be)

**Comment by Sekor2600** [comment] 2018-04-01 12:15
same Problem here

**Comment by magww** [comment] 2018-04-03 02:20
Same Problem here too :(

**Comment by SofaEco** [comment] 2018-04-03 11:42
we are suffering nearly the same
user online after disconnet 
if they try reconnecting invalid id
server restart leads to instant treee grow an so on

this also somehow affects server to start beeing laggy

mainly this happens to our server after it suddenly kicks randome players wrongly for beeing afk while they are not afk exaple loggging trees and so on

**Comment by THEGOBBLER** [comment] 2018-04-03 18:50
Same, seems to be growing in frequency if anything. Some observations made during the error.

1. Confirming large numbers of players report lag just before it happens.
2. Player progress is frozen at the time the lag begins. They are able to take actions on the server as normal but these actions are not saved when the server restarts.
3. Whilst this is happening, _anyone_ who logs off will not be able to log back on.
4. Whilst this is happening, the server web portal is accessible but no graph data is able to be loaded.

**Comment by Arti-llery** [comment] 2018-04-03 18:57
Have experienced this also, a temporary fix seems to be disabling stats again. Since we disabled stats, no lag, no one getting kicked while queuing up things, or using shops.

**Comment by MarjieAVolk** [comment] 2018-04-03 19:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6668.  This is our first priority right now.

**Closed by MarjieAVolk** 2018-04-03 19:13 UTC
