### ISSUE TITLE
Ability to trash items

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2092] opened 2017-09-11 20:22 UTC
We need an option to throw away items in inventory.    
e.g. if you created a lot of skill scrolls but need space, i want to throw them away instead of creating more storage chest to store them.    
This issue is not a implementation of a Trash bin (object) its for an ui implementation.

**Comment by metachronism** [comment] 2017-11-09 22:54
dupe of #830

**Closed by metachronism** 2017-11-09 22:54 UTC
