### ISSUE TITLE
USER ISSUE: Stockpile Pit

### ISSUE THREAD

**Issue by OrneryIke** [StrangeLoopGames/EcoIssues#9249] opened 2018-09-07 22:04 UTC
![stockpile pit](https://user-images.githubusercontent.com/22848917/45245010-555a8880-b2c8-11e8-9f73-11ba629973dc.png)
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
Dug a 5x5 pit to put a stockpile at the bottom. When I try to place the stockpile it claims it's blocked. This was not an issue before 7.7

**Expected behavior:**

**Actual behavior:**

**Comment by OrneryIke** [comment] 2018-09-08 01:01
UPDATE: I'm placing a floor over the area and it won't let me place a block in one spot. Maybe there's an invisible tree there.

**Comment by Conchipedia** [comment] 2018-09-08 18:09
was there a vehicle/cart in the hole where you were trying to place the Stockpile?
 i had this invisible block problem as well managed to track my problem down to Logging out with a cart in one place moving it when i logged in and then having an invisble block there (this cleared up whejn i logged off for the 2nd time)
Linking my issue just in case this might have been the problem (but it is Invisible block issue which is what this is as well)
#9271

**Comment by BlazeGuy2** [comment] 2018-09-10 23:01
Couldn't reproduce this on my machine.

**Comment by OrneryIke** [comment] 2018-09-11 19:09
I've tried 5 different times in 3 different worlds created since 7.7 and the stockpile has been blocked each time. I did have a cart that I removed but so far logging out and back in has not resolved the problem.

**Comment by Conchipedia** [comment] 2018-09-11 19:52
Just out of curiosity i tried to Duplicate this on my singleplayer World in 7.7.1 (because i had this problem with placed vehicles and did github #9271) these are the steps i did

1: made an area roughly the shape of a stockpile
![snap2796](https://user-images.githubusercontent.com/29383891/45382926-b86a5900-b601-11e8-8cc2-f212c2d34d70.png)
2: placed stockpile in space to make sure it fitted
![snap2797](https://user-images.githubusercontent.com/29383891/45382974-cf10b000-b601-11e8-9940-98fda5d59b8b.png)
3:removed stockpile with hammer, placed cart in space from Toolbar
![snap2798](https://user-images.githubusercontent.com/29383891/45383001-e2238000-b601-11e8-92db-12b9c1fd7cc2.png)
4: dragged cart from space through the hole i left
![snap2799](https://user-images.githubusercontent.com/29383891/45383031-f798aa00-b601-11e8-82dc-30152b024bb9.png)
5: tried to place stockpile (blocked message)
![snap2800](https://user-images.githubusercontent.com/29383891/45383207-742b8880-b602-11e8-8fbe-9440e88a97a3.png)
6: tried again to place stockpile (loads of blocked messages)
![snap2801](https://user-images.githubusercontent.com/29383891/45383085-15660f00-b602-11e8-880d-36d332d9c626.png)
7: disconnected from Singleplayer World, chose continue then tried again to place stockpile and it goes in with no problem
![snap2802](https://user-images.githubusercontent.com/29383891/45383136-3c244580-b602-11e8-86a6-fc79e29b4d50.png)
this was done becuase i had placed trucks and carts and couldnt place a block in #9271 this was on another world i have to test on in singleplayer.

i even did this by digging down 4 blocks
![snap2803](https://user-images.githubusercontent.com/29383891/45383761-0718f280-b604-11e8-99e0-794067af0d99.png)
![snap2804](https://user-images.githubusercontent.com/29383891/45383762-0718f280-b604-11e8-8248-a129103952b1.png)
![snap2805](https://user-images.githubusercontent.com/29383891/45383763-0718f280-b604-11e8-995b-3a766f66da50.png)
![snap2806](https://user-images.githubusercontent.com/29383891/45383764-07b18900-b604-11e8-9730-515158ceaf63.png)
![snap2807](https://user-images.githubusercontent.com/29383891/45383765-07b18900-b604-11e8-93bc-5f7241093a8f.png)
version used for test was downloaded Via Steam
![snap2808](https://user-images.githubusercontent.com/29383891/45383925-77c00f00-b604-11e8-867e-2f96c53a35b2.png)
but i always had this problem stop after i disconnected and then continued

**Comment by BlazeGuy2** [comment] 2018-09-11 21:38
About to release a hotfix for 7.7.2, which addresses an issue where the world doesn't properly remove vehicles when they are picked up, thus preventing stockpile placement.  Once this it out, can you switch to that version and let me know if this bug still persists with a new pit?

**Comment by OrneryIke** [comment] 2018-09-11 22:32
Will do, thank you.

**Comment by OrneryIke** [comment] 2018-09-11 23:27
I now seem to be able to place stockpiles properly. Thanks!

**Closed** 2018-09-11 23:28 UTC
Labels: Low Priority, Not reproduced
