### ISSUE TITLE
ØÆÅ and other country specific characters don't work in eco

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#2944] opened 2017-11-30 00:48 UTC
Ref slack feedback of not wroking non US standard characters.. Because we all wanna say : "sån går nå dagane uten brød i magen =P"  Or "Hvordan er været ?" <--- ABSOLUTE CLASSIC THING TO SAY !

**Comment by MarjieAVolk** [comment] 2017-11-30 00:58
Sounds like duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2656 ?

**Comment by MarjieAVolk** [comment] 2017-11-30 00:58
Or did you not mean in chat?

**Closed by MarjieAVolk** 2017-11-30 00:58 UTC
Labels: Low Priority

**Comment by noblackthunder** [comment] 2017-11-30 01:07
in chat
but yes it is a dublicate !
