### ISSUE TITLE
[0.9.2 staging-1883] Property icon should be visible only when active property layer.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19831] opened 2020-12-23 06:50 UTC
![image](https://user-images.githubusercontent.com/45708377/102967944-0b7f2600-4504-11eb-9a32-6b02fe47de5a.png)

**Comment by gzatravkin** [comment] 2020-12-23 12:01
It's a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19538 which is marked 9.3.
For now there are toggle "Deeds" in minimap objects

**Closed by gzatravkin** 2020-12-23 12:01 UTC
Labels: Category: UI, Priority: Medium
