### ISSUE TITLE
USER ISSUE: Changing Render Scale fucks up minimap

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6754] opened 2018-03-30 19:04 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. open map
2. change renderscale
3. after a few time change again
4. observe coordinates glitching away or planet rendering getting stuck

**Expected behavior:**
1. not get stuck :P

**Actual behavior:**

**Comment by SlayksWood** [comment] 2020-01-16 13:08
![image](https://user-images.githubusercontent.com/45708377/72527668-54e9de80-387a-11ea-9fe9-8f03f35243fa.png)
And if you change scale position icon go away:
![image](https://user-images.githubusercontent.com/45708377/72527511-00466380-387a-11ea-91bc-381707385cbb.png)

**Comment by Daniel-Magulado** [comment] 2021-02-13 17:22
Tested on 0.9.3 Staging-1929.

Resolution: Appears to be fixed. Unable to reproduce on 9.3 staging. Closing.

**Closed by Daniel-Magulado** 2021-02-13 17:22 UTC
Labels: Priority: Medium, Squad: Wild Turkey, Status: Fixed
