### ISSUE TITLE
Crash bye repair from road tool

### ISSUE THREAD

**Issue by BogusCurry** [StrangeLoopGames/EcoIssues#3679] opened 2018-01-28 14:07 UTC
Hi there ;D
When I would repair the road tool, crash Eco 6.4.2.

https://paste.md-5.net/tanofikuhi.avrasm

My System:
Win7 prof. 64 bit Eco Version 6.4.2

Greetings
Bogus

**Comment by Conchipedia** [comment] 2018-01-28 14:10
duplicate of USER ISSUE: Road Tool + Repair Station, Game Crach #3485

**Comment by MarjieAVolk** [comment] 2018-01-29 20:24
Yes, should be fixed in the latest staging build

**Closed by MarjieAVolk** 2018-01-29 20:24 UTC
