### ISSUE TITLE
USER ISSUE: [0.8.0.3] Server World Generated

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#11480] opened 2019-02-25 15:31 UTC
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. Start Eco Server
2. Generate world
3. Start Eco Client
4. Connect to Server
5. Profit

**Expected behavior:**
ECO SERVER does not use any other surface textures except STONE when generating a new world !!! Simply put, every time the world is generated ONLY from WATER and STONE! NO FORESTS, DESERT, TUNDRA, TROPICS, ANIMALS, BIRDS !!! There is nothing ANY STONE !!!

**Actual behavior:**
ECO SERVER does not use any other surface textures except STONE when generating a new world !!! Simply put, every time the world is generated ONLY from WATER and STONE! NO FORESTS, DESERT, TUNDRA, TROPICS, ANIMALS, BIRDS !!! There is nothing ANY STONE !!!

**Do you have mods installed? Does issue happen when no mods are installed?:**
NO MODS . Standart place on Steam.
![20190225182619_1](https://user-images.githubusercontent.com/1098421/53348158-948a9d80-392b-11e9-90d7-8cd8bf5c4697.jpg)
![20190225182737_1](https://user-images.githubusercontent.com/1098421/53348169-9c4a4200-392b-11e9-9eb9-aff213455ebc.jpg)

**Comment by elfl0rd** [comment] 2019-02-25 17:30
Duplicate of #11265

**Closed by elfl0rd** 2019-02-25 17:30 UTC
