### ISSUE TITLE
Cannot set decimal values on Store

### ISSUE THREAD

**Issue by iliasGaming** [StrangeLoopGames/EcoIssues#9811] opened 2018-10-20 09:26 UTC
I cannot set decimal values on Store (eg 0.5).
My cousin that lives in Canada, can set decimal values with not problem.
I live in Greece and I have Greek regional settings on my PC. I think this is the problem.
Let me describe the issue a bit more.
In Store, I cannot type the character "." (dot). So, there is no way to set a decimal value.
I'm able to type the character "," (comma), but this does not help, because it disappears.
For example, I type "0,52" and it turns into "52".

Possible solution 1:
Allow to type a "." (dot), regardless of the regional settings.

Possible solution 2:
Replace the character "," with "." after typing, so the game see it as a decimal point.

Cheers

**Comment by D3nnis3n** [comment] 2018-10-20 11:43
Duplicate of #9210

**Closed by D3nnis3n** 2018-10-20 11:43 UTC
