### ISSUE TITLE
USER ISSUE: Camp despawn

### ISSUE THREAD

**Issue by Aom0ri** [StrangeLoopGames/EcoIssues#10941] opened 2019-01-29 04:28 UTC
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
Tried to place a camp in an area that is already owned. I'm a new player, didn't know otherwise. It deleted my camp, and when someone made me a new campsite, it wasn't counting as my actual camp.

**Expected behavior:**
Camp should have returned to my inventory after failing to place on claimed land.

**Actual behavior:**
Camp was deleted, and my character forever bugged on this server.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Camp was deleted, and my character forever bugged on this server.

**Comment by elfl0rd** [comment] 2019-01-29 10:16
Duplicate of #9337

**Comment by elfl0rd** [comment] 2019-01-29 10:16
Fixed in 0.8 https://github.com/StrangeLoopGames/Eco/pull/3844

**Closed as completed by elfl0rd** 2019-01-29 10:16 UTC
