### ISSUE TITLE
0.8: stockpile highlight - including closest blocks

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10771] opened 2019-01-19 11:01 UTC
![default](https://user-images.githubusercontent.com/4980243/51425859-d587e780-1bf2-11e9-941d-b81063adf28c.png)

**Comment by elfl0rd** [comment] 2019-01-31 15:22
Need to be fixed. No highlight in stockpile, but outside.
![default](https://user-images.githubusercontent.com/4980243/52064213-3addc000-2585-11e9-8e3c-570ebebc4719.png)

**Comment by redwyre** [comment] 2019-01-31 15:37
Does this happen every time? If so could I get the save?

**Comment by elfl0rd** [comment] 2019-11-10 13:29
Still actual in 0.9 master
![изображение](https://user-images.githubusercontent.com/4980243/68544716-46dd9480-03d7-11ea-8a8f-badc0eda51cb.png)

![изображение](https://user-images.githubusercontent.com/4980243/68544725-51982980-03d7-11ea-9339-60093fc016c2.png)

**Comment by SlayksWood** [comment] 2020-01-10 09:57
Can't reproduce in last staging.
@elfl0rd, Can you?

**Comment by SlayksWood** [comment] 2020-03-02 11:28
Closed for now. reopen when you can provide us reprosteps.

**Comment by elfl0rd** [comment] 2020-03-02 11:54
it happens periodically, maybe based at build settings

**Comment by redwyre** [comment] 2020-03-02 14:11
This only happens with 2x2 stockpiles, but in 3 out of the 4 rotations. The highlight area is offset incorrectly because it calculates the center incorrectly for rotating.

**Comment by johnkslg** [comment] 2020-04-15 16:17
Keeping because problem has been identified and its an easy fix.

**Comment by mirasrael** [comment] 2020-04-15 16:57
I assume if it easy to fix and guarantee to not break anything else after fix then it was already be fixed by Simon. I'm personally not sure if it easy and safe to fix.

**Comment by SlayksWood** [comment] 2020-08-18 12:25
This is happen again.

**Closed** 2020-08-21 05:59 UTC
Labels: Category: Tech, Priority: Low, Status: Reopen
