### ISSUE TITLE
Run for office exception

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3033] opened 2017-12-08 22:41 UTC
When running the Eco Server in debug mode - Clicking "Run for office" in the web GUI, I get an unhandled exception:

System.Exception: '<style="Error">Cannot violate law 'Citizenship'.</style> Your Play actions Ever (1.26) is less than 2; Action not allowed.' from Line 80 in ControllerUtil.cs

**Comment by MarjieAVolk** [comment] 2017-12-08 22:43
Actually this is a duplicate of this: https://github.com/StrangeLoopGames/EcoIssues/issues/2994

Copying your comment over there

**Closed by MarjieAVolk** 2017-12-08 22:43 UTC
Labels: Medium Priority
