### ISSUE TITLE
USER ISSUE: still no tree seeds

### ISSUE THREAD

**Issue by ownyHD** [StrangeLoopGames/EcoIssues#4169] opened 2018-02-09 08:47 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
not getting any treeseeds at all

**Comment by Huntermeign** [comment] 2018-02-09 12:04
Repeat af #4121

**Comment by MarjieAVolk** [comment] 2018-02-09 19:38
Is this for all trees, or just oak and fir?

Closing as duplicate of #4121

**Closed by MarjieAVolk** 2018-02-09 19:38 UTC

**Comment by ownyHD** [comment] 2018-02-09 23:11
yes u're right its just oak and fir. but now i cant plant the seeds since they instantly die while match=83%
