### ISSUE TITLE
USER ISSUE: Waypoints

### ISSUE THREAD

**Issue by Wuchst** [StrangeLoopGames/EcoIssues#6441] opened 2018-03-24 06:58 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**

I've created a waypoint, called this home, and colored red. The waypoint is in the middle of my log cabin. I then went out of my cabin for 5 Meters away from the Waypoint 
![screen 1](https://user-images.githubusercontent.com/37729557/37861396-f9456bfe-2f38-11e8-8d59-9dea0c02a867.png)
![screen 2](https://user-images.githubusercontent.com/37729557/37861397-f95e12b2-2f38-11e8-9f5b-c45c89cb2e23.png)
and suddenly the waypoint jumped to the other side of the screen. 
![screen 3](https://user-images.githubusercontent.com/37729557/37861398-f97584ec-2f38-11e8-8c87-d9eb686d2914.png)
Now this is about 700 meters away from me, although the log cabin is directly behind me. I go back to the hut, the waypoint is also back where he should be.

**Expected behavior:**
The waypoint should not jump to the other side of the screen until I'm half the length of my planet's equator from my waypoint

**Actual behavior:**
I have already explained above

**Comment by MarjieAVolk** [comment] 2018-03-28 20:54
Fixed in 7.3

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5056

**Closed by MarjieAVolk** 2018-03-28 20:54 UTC
