### ISSUE TITLE
9.0 1611 - All laws vanished from legislation page

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16827] opened 2020-06-22 20:58 UTC
All laws have seemingly vanished from the legislation page.

Laws still exist and show on the courts (other than the one in the below pic as it bugged out due to a server restart)
![image](https://user-images.githubusercontent.com/61889138/85334192-ba4d9580-b4d2-11ea-884d-5cef79aeaa2d.png)

Legislation page, same is also happening for Rev, this is on the playtest server

![image](https://user-images.githubusercontent.com/61889138/85334240-ccc7cf00-b4d2-11ea-9c4b-c308ea81b9dd.png)

Hovering over "Law Name" does show one of the laws though

![image](https://user-images.githubusercontent.com/61889138/85334304-ec5ef780-b4d2-11ea-8180-fc7aec425c2c.png)

**Comment by SlayksWood** [comment] 2020-06-23 07:05
It can happen not only for laws, but no any steps to reproduce it with 100%
![image](https://user-images.githubusercontent.com/45708377/85371500-fd425400-b538-11ea-9da2-ef3f2c177b37.png)

**Comment by MishkaFur** [comment] 2020-06-23 07:46
I think what it MIGHT be related to is perhaps because im changing the basic election type?

One of the laws runing atm is changing Basic Election Updates to basic Election Updates 2 so could it be related?

**Comment by Dmittry62** [comment] 2020-07-16 12:11
I couldn't reproduce this issue. But it is possible that the problem is in pooling. Maybe it'll be resolved after merging a certain fix.

**Comment by Dmittry62** [comment] 2020-07-16 12:13
I marked this task as dependent on the other one where I've dealt with all pooling issues.

**Comment by mirasrael** [comment] 2020-07-16 12:23
This issue was created before pooling introduced. So most probably not related and probably already fixed.

**Comment by beastyn** [comment] 2020-07-29 09:13
Nope, still here
I have two courts.
Two laws on election and two laws should be active.
![bandicam 2020-07-29 14-10-24-708](https://user-images.githubusercontent.com/27898520/88781083-58eda600-d1a5-11ea-90c3-ee676f581527.jpg)
![bandicam 2020-07-29 14-10-35-757](https://user-images.githubusercontent.com/27898520/88781086-5a1ed300-d1a5-11ea-97c7-a71c8a798a7d.jpg)

But
![bandicam 2020-07-29 14-07-56-769](https://user-images.githubusercontent.com/27898520/88781099-5f7c1d80-d1a5-11ea-9684-ccf678321539.jpg)

Opening legislation ggivw me this error
```
NullReferenceException: Object reference not set to an instance of an object.
  at IconUtils.InstantiateIcon (UnityEngine.GameObject iconPrefab, UnityEngine.Transform parent) [0x00000] in <00000000000000000000000000000000>:0 
  at SplitNameUI.BuildIcons (System.String text) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJavaRunnable.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at SplitNameUI.SyncWithView (Eco.Shared.View.View view, System.String propName) [0x00000] in <00000000000000000000000000000000>:0 
  at ViewExtensions.AutoSetupUI (Eco.Shared.View.View parentView, Eco.Shared.View.ISubscriptions subscriptions, UnityEngine.Transform autogenRoot, System.String propertyPath, System.Action OnChange, System.Boolean allowAutogen, UnityEngine.Transform root) [0x00000] in <00000000000000000000000000000000>:0 
  at AutoViewUI.ViewInited () [0x00000] in <00000000000000000000000000000000>:0 
  at ViewBehavior.InitView (Eco.Shared.View.View parentView, Eco.Shared.View.View view, Eco.Shared.View.ViewMemberInfo propertyInfo, Eco.Shared.Serialization.BSONObject bsonParams, System.Int32 listIndex) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.ViewUIContainer.CreateListEntry (System.Action`1[T] PostInit, System.Int32 index, Eco.Shared.View.View entryView, System.Boolean last) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.ViewUIContainer.CreateNewEntries (System.Collections.Generic.IEnumerable`1[T] enumerable, System.Action`1[T] postInitAction) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.ViewUIContainer.UpdateList (System.Action`1[T] PostInit) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.ViewUIContainer.ListChanged () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJavaRunnable.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at UI.ViewUIContainer.Init (Eco.Shared.View.View view, System.String propertyName, Eco.Shared.Serialization.BSONObject bsonParams, System.Action`1[T] PostInit, AuthComponentView owner, System.String propertyPath) [0x00000] in <00000000000000000000000000000000>:0 
  at RegistrarListUI.Start () [0x00000] in <00000000000000000000000000000000>:0 
```

**Comment by Dmittry62** [comment] 2020-08-01 15:22
Can't reproduse it no matter what I do with courts, laws and elections. I you find another way to reproduce it please describe it here.

**Comment by beastyn** [comment] 2020-08-04 06:01
@Dmittry62 
Check this one #17513 please, maybe related

**Comment by IcedForge** [comment] 2020-08-04 12:12
Also possibly related to this as well. https://github.com/StrangeLoopGames/EcoIssues/issues/16601

**Comment by beastyn** [comment] 2020-08-05 07:22
Should be fixed in the next update

**Comment by Dmittry62** [comment] 2020-08-05 21:06
Looks like this issue should be fixed with this one
https://github.com/StrangeLoopGames/EcoIssues/issues/17513

**Comment by beastyn** [comment] 2020-08-06 10:32
I will close for now as was not able to find it anymore. 
@MishkaFur @IcedForge  Please tell if anyone meet it again.

**Closed by beastyn** 2020-08-06 10:32 UTC
Labels: Category: UI, Priority: High, Status: Fixed
