### ISSUE TITLE
USER ISSUE: black screen

### ISSUE THREAD

**Issue by freschmeet** [StrangeLoopGames/EcoIssues#6861] opened 2018-04-01 23:05 UTC
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
no clue

**Expected behavior:**
not a black screen...

**Actual behavior:**
a black screen...

**Comment by SeanAtr0n** [comment] 2018-04-02 22:52
black screen as in you can't do anything or were you in thirdperson and the camera got blocked?

**Comment by freschmeet** [comment] 2018-04-03 01:35
Hi Sean,

I couldn't see anything at all. I could move around and the friends I was
playing with said I was moving, but I couldn't see a thing.

Thanks,
Mario

**Comment by elfl0rd** [comment] 2019-02-15 09:26
Duplicate of #11226

**Closed by elfl0rd** 2019-02-15 09:26 UTC
Labels: Medium Priority

**Comment by D3nnis3n** [comment] 2019-02-25 21:03
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053

**Comment by freschmeet** [comment] 2019-02-26 12:13
This was months ago, Dennis. I don't play Eco any longer. Best of luck!
