### ISSUE TITLE
USER ISSUE: Items stuck in Campfire

### ISSUE THREAD

**Issue by theoretisch** [StrangeLoopGames/EcoIssues#5837] opened 2018-03-10 12:13 UTC
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
1. Start project (e.g. charred tomato) at campfire
2. Put in needed items
3. Wait for project to complete / do something while waiting
4. Try to pick up / cancel finished Items

**Expected behavior:**
Pick up finished items

**Actual behavior:**
Cannot pick up / cancel finished items. Items stuck forever in campfire. Cannot destroy campfire 'cause there are finished projects in.

**Comment by MarjieAVolk** [comment] 2018-03-12 22:58
Could you show a screenshot of your campfire window?

Are you able to cancel the project by right clicking on it in the campfire window?

**Comment by theoretisch** [comment] 2018-03-14 19:09
I'm sorry, i don't have a screenshot but here's a short gif
![eco_campfire](https://user-images.githubusercontent.com/12891113/37425300-263aada4-27c3-11e8-8a06-15717bdbd7f8.gif)

No, im not able to cancel the project as i mentioned above.

**Comment by MarjieAVolk** [comment] 2018-03-14 19:21
Okay, so it looks like https://github.com/StrangeLoopGames/EcoIssues/issues/3240 except for not being able to cancel.

After trying to cancel the projects, could you send me your log file? 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'  Or alternatively you could just send the whole save file, that might be easier.

**Comment by theoretisch** [comment] 2018-03-14 19:32
Here's the log file. 
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1812750/output_log.txt)
What for a save file do you mean? If it's important: I play on my local server which i had installed via steam.

**Comment by MarjieAVolk** [comment] 2018-03-14 20:49
If you go to steam's 'browse local files' thing for Eco, then to Eco_Data\Server\Storage, you should see a file there called WorldName.eco (where WorldName is the name of your world).  That's the one I want.

I looked through your output log but didn't see anything related.  I did see some errors related to getting off of a vehicle, that's it.

**Comment by theoretisch** [comment] 2018-03-14 21:07
So it's this one... https://www.file-upload.net/download-13029714/Game.zip.html

**Comment by MarjieAVolk** [comment] 2018-03-15 17:41
Okay, so I've realized why you can't cancel the order - it's because it is neither your order nor your campfire.  You must either own the object or have started the order in order to cancel it.  I will add a notification for when this happens.  Other than that, this bug is a duplicate of #3240, so I will use your save to work on that issue now :)  Closing as duplicate of #3240.

**Closed by MarjieAVolk** 2018-03-15 17:41 UTC

**Comment by theoretisch** [comment] 2018-03-16 17:57
The other player (owner of the campfire and starter of the project) can't cancel it neither. Do you want the other player's log file too?

**Comment by MarjieAVolk** [comment] 2018-03-16 18:55
Oh really?  Okay, no that is okay, I will try logging in as that player and see if I can repro.  I'll let you know.

**Comment by MarjieAVolk** [comment] 2018-03-19 21:04
Okay, I logged in as NoobieKiraa on this save, and I was able to cancel the order.  So not sure what is up.
