### ISSUE TITLE
USER ISSUE: Map drop

### ISSUE THREAD

**Issue by draganta316** [StrangeLoopGames/EcoIssues#4508] opened 2018-02-14 10:55 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
i drop from the map

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-14 21:34
I assume you mean you fell through the ground and were falling infinitely?

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4167

**Closed by MarjieAVolk** 2018-02-14 21:34 UTC
