### ISSUE TITLE
USER ISSUE: Carts Disappearing

### ISSUE THREAD

**Issue by knuckl3s0** [StrangeLoopGames/EcoIssues#11231] opened 2019-02-09 21:45 UTC
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
1. Leave a cart small or large in a spot
2. Leave Render Distance
3. Return	

**Expected behavior:**
Visible	

**Actual behavior:**
Invisible, cannot interact with cart at all. Doesn't block walking the cart is just gone. You can check the inventories nearby and see that the cart is still nearby. 

**Do you have mods installed? Does issue happen when no mods are installed?:**
Invisible, cannot interact with cart at all. Doesn't block walking the cart is just gone. You can check the inventories nearby and see that the cart is still nearby.

**Comment by elfl0rd** [comment] 2019-02-09 22:07
Duplicate of #11108

**Closed by elfl0rd** 2019-02-09 22:07 UTC
