### ISSUE TITLE
[7.6.2] Server; LiteDB corruption in game.db save file from migration 7.6.0 to 7.6.2

### ISSUE THREAD

**Issue by guilemouse** [StrangeLoopGames/EcoIssues#8667] opened 2018-07-21 03:15 UTC
**Exception:**
`"Error writing to stat database: InvalidCastException Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'." `

**Reproduction:**
Update server from pre7.6.0 to 7.6.1 to 7.6.2 (Save is below)
Shovel a dirt pile and move it over any block.
Exit the game (or stay, it doesn't matter)
Go to the server's web port 3001
All lined and barred data are now not visible.

**LiteDB's github of issue:** 
https://github.com/mbdavid/LiteDB/issues/641

(unrelated but relevant) Upon deleting the .db file, a new one is generated but lines are not drawn for statistics, only bars are.

**Detailed stack trace:**
When viewing with liteDB via liteDB explorer, after clicking on "PlaceAction", the detailed exception was the following.

`2018-07-20 22:54:05.7874|ERROR:Unhandled exception: System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LinqExtensions.<Batch>d__0`1.MoveNext()
   at LiteDB.LiteEngine.InsertBulk(String collection, IEnumerable`1 docs, Int32 batchSize, BsonType autoId)
   at LiteDB.LiteEngine.Shrink(String password, IDiskService tempDisk)
   at LiteDB.LiteDatabase.Shrink(String password)
   at LiteDB.LiteDatabase.Shrink()
   at LiteDbExplorer.Windows.DatabasePropertiesWindow.ButtonShrink_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at LiteDbExplorer.MainWindow.EditDbPropertiesCommand_Executed(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.UIElement.OnExecutedThunk(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.ExecutedRoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object target)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at System.Windows.Input.RoutedCommand.ExecuteCore(Object parameter, IInputElement target, Boolean userInitiated)
   at System.Windows.Input.CommandManager.TransferEvent(IInputElement newSource, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.UIElement.OnExecutedThunk(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.ExecutedRoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object target)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at System.Windows.Input.RoutedCommand.ExecuteCore(Object parameter, IInputElement target, Boolean userInitiated)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at LiteDbExplorer.App.Main()
`

**Game save:**
https://drive.google.com/file/d/1qo9piMVDsjm-47xNOeQeDwEQi8Wy4Ys1

**Question:**
Is it possible to delete that particular "PlaceAction"?

**Comment by guilemouse** [comment] 2018-07-21 03:19
In addition to this the reply to the litedb issue is:

>Yes, this error may occurs only in 4.1.1... if upgrade to 4.1.2 and database not corrupted yet, it will works fine.

**Comment by guilemouse** [comment] 2018-07-21 06:03
I managed to find a solution for a corrupt collection under LiteDB 4.1.1 and below. You can just rename the collection to something else to avoid it being used and the game will basically ignore that extra collection. (or i hope). Dropping the collection doesn't work and return errors.

`db.PlaceAction.rename.HiddenCollection `

With LiteDB's shell executable will solve my particular problem with the corrupt collection of "PlaceAction". Relaunching the game, and shoveling a block, then voting a new law, returning and refreshing the 3001 port webstat, shows lines and bars. Then restarting the server, it still works too.

I fixed it. But please update your LiteDB to 4.1.2 and above.

**Comment by MarjieAVolk** [comment] 2018-07-24 00:41
Thanks for digging into this.  We are currently on litedb version 4.1.2 - I believe we have been on this version for quite a while.

Migration to 7.6.2 shouldn't have affected the .db file at all, so that is odd.

**Comment by MarjieAVolk** [comment] 2018-07-24 00:46
Oh, I see you found the issue where I was commenting before, nice

**Comment by MarjieAVolk** [comment] 2018-07-24 00:54
Well, I have updated the LiteDB people with this information.  It doesn't looook like the more recent releases of LiteDB would have fixed this issue, so I think we've done all we can on this front for now.  These days it doesn't affect the game nearly as much - just messes up graphs and potentially laws, as you've noticed.  And this is the first report of it we've had in months.  So I'm closing this as won't fix for now.  Thanks for all this information though.

If you don't mind my asking, how did you know which table was the bad one?

**Closed by MarjieAVolk** 2018-07-24 00:54 UTC
Labels: High Priority, Needs Triage

**Comment by guilemouse** [comment] 2018-07-24 15:02
@MarjieAVolk I've found it by opening it on the litedb explorer, but even reading it via litedb shell will crash it. So I figured that's the bad table and tried hide it elsewhere. I hope the game doesn't use something to read the entire game.db's tables cause it might cause a crash on that attempt. 

Unrelated: I also pinged you the discord cause git timed out my login attempts (sorry for the double notification).

**Comment by MarjieAVolk** [comment] 2018-07-24 17:30
Okay, thanks.  We have wrappers around the things that touch the database, to prevent errors like these from crashing the game, since for the most part they are out of our control.  But now if someone else comes with this reports, we can help them doctor their file.

**Comment by guilemouse** [comment] 2018-07-26 01:21
@MarjieAVolk Just an update, today I received the dump file of the similar exception that caused several server crashes. I'm attempting to just migrate the tables into a new game.db instead of reusing the old one. Perhaps to avoid meeting the corrupted and renamed table. This rename method won't work nicely but it works for a few days (for some reason).

**Comment by guilemouse** [comment] 2018-07-26 08:13
After migrating all the non corrupted table to a new game.db, it seems to have fixed the issue of random crashes. At least for today. I'll update if it crashes again. But so far, no problems.

**Comment by MarjieAVolk** [comment] 2018-07-26 17:30
So it's continuing to get corrupted again after fixing the db?  I wonder whether the issue is that the db is still bad, or whether there's some specific circumstance that you happen to keep running in to.  That is, if you deleted the whole .db file completely, would the corruption still come back?

**Comment by guilemouse** [comment] 2018-07-26 17:48
No new tables were corrupted upon transferring the uncorrupted table contents into a new game.db. But the old hidden corrupted table gets found somehow after I renamed it within the game.db, so renaming the table doesn't work for my particular case (for long). 

If I delete the entire game.db file the corruption will not come back (But that loses my saved data on statistics). And since the corrupted database only occurs within db.PlaceAction for my case, and the game seemed to generate new data for PlaceAction, I was able to just migrate all the tables to a new game.db file I've made from litedb shell.exe

The game runs either runs a loop through the collections as a whole or queries for indexes of all the collections in the db. (ie, PlayAction,PlayerAction,BisonPopulation,etc). So hiding tables by renaming them from the inability to drop them due to corruption is not doable. 

So it still finds the renamed corrupt table I've hidden within the db. In this case, "db.OsamaBinLaden" was the renamed db.PlaceAction, was found and causes multiple crashes per day due to some laws we implemented. Initially I was hoping that the game won't run a query through the entire collections, so it'll never get found. 

Hope this information helps, if you need the relevant save and dumps for reference to these crashes as an example, I can upload them to google drive.

**Comment by MarjieAVolk** [comment] 2018-07-26 18:07
Ah yeah, I believe there are some display things that just display all tables that are present.  Strange.  But I wouldn't expect it to cause crashes, since I thought everything was wrapped in try catches.  Do you have crash dumps?

**Comment by guilemouse** [comment] 2018-07-26 18:11
Crash dump is below. 

https://drive.google.com/file/d/1Z58aBeHT54QzqTVH0ckdFFJSL6g_RsY3/

Generally it's just.

`Finished in 650.1ms[05:14:15] Server Initialization finished in 22,911.9ms
 
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.CollectionService.Get(String name)
   at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   at Eco.Stats.StatDatabase.EnsureIndex(String collectionName, IEnumerable`1 fieldNames)
   at Eco.Stats.OrganismStats.<>c__DisplayClass1_0.<GetPopulationStat>b__0()
   at Eco.Shared.Utils.DictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dict, TKey key, Func`1 addFunc)
   at Eco.Simulation.WorldLayers.WorldLayerStats.<>c__DisplayClass0_0.<CollectStats>b__0(Species species)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Simulation.WorldLayers.WorldLayerStats.CollectStats()
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
 
[05:14:15] Error writing to stat database: InvalidCastException Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.IndexPage'.
 `

**Comment by MarjieAVolk** [comment] 2018-07-26 18:19
Oh my, well that's interesting, haha.  That should only be reading species population stats, so not sure why it is interacting with the corrupted table there; but that is indeed a database interaction that's not wrapped in a try catch.  So I will put a try catch around that, which should prevent actual crashes in future releases (just graphs/related laws would be broken).
