### ISSUE TITLE
USER ISSUE: Client crash when attempting to repair

### ISSUE THREAD

**Issue by angelokay** [StrangeLoopGames/EcoIssues#4833] opened 2018-02-19 19:50 UTC
![20180219161818_1](https://user-images.githubusercontent.com/26525866/36394871-2ca737ce-15ae-11e8-920c-ed84ac2a07fb.jpg)
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Repair on RepairComponent!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.Inventory.TryRemoveItems(ItemStack stack, User user)
   at Eco.Gameplay.Components.RepairComponent.Repair(Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

```

**Comment by MarjieAVolk** [comment] 2018-02-26 18:28
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4358

**Closed by MarjieAVolk** 2018-02-26 18:28 UTC
Labels: High Priority
