### ISSUE TITLE
USER ISSUE: Fish traps catch fish when placed on land

### ISSUE THREAD

**Issue by Irawulf** [StrangeLoopGames/EcoIssues#11453] opened 2019-02-21 21:59 UTC
![20190221225632_1](https://user-images.githubusercontent.com/47475999/53204619-5724c800-362c-11e9-9817-bda9a343674f.jpg)
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Place a fish trap on land. 
(Select a place where the map shows fish)

wait a couple of hours (or sleep)

**Expected behavior:**
there should not be any fish on land to be caught on land

**Actual behavior:**
the trap manages to catch fish

**Do you have mods installed? Does issue happen when no mods are installed?:**
the trap manages to catch fish

**Comment by elfl0rd** [comment] 2019-02-21 22:30
Duplicate of #5818

**Closed by elfl0rd** 2019-02-21 22:30 UTC
