### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#4585] opened 2018-02-15 12:47 UTC
Server crashed and it wasn't able to come online as it kept giving this error.
"Exception
System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state.
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user)
   at Eco.Gameplay.Components.StockpileComponent.TryUpdateInventoryFromWorld()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)"
I managed to get it online by using a 11 hour old save. In the period between the latest save and the one back from 11 hours ago there were no changes made to the server files or new mods installed.
Game save:
https://www.dropbox.com/s/lsr1063b8q91c15/Game.eco?dl=0

**Comment by MarjieAVolk** [comment] 2018-02-17 00:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4473

**Closed by MarjieAVolk** 2018-02-17 00:25 UTC
