### ISSUE TITLE
Easy vehicle duping

### ISSUE THREAD

**Issue by Guedez** [StrangeLoopGames/EcoIssues#18713] opened 2020-10-03 18:44 UTC
Have vehicle on inventory and wait for the server to start lagging. Might work even on non lagging servers, but it's trivial if the server is lagging.
1 Place the vehicle on the ground.
2 As soon as the vehicle spawns in the world, esc -> disconnect. You need to do this before the item leaves your inventory, which is why the server lagging helps.
3 As you go back in the world, place the Vehicle on the ground again.
4 Repeat until you finish making all Mechanics and Industry users sad forever. Works with all vehicles, carts, trucks, skid steers, anything.

**Comment by SlayksWood** [comment] 2020-10-13 07:57
The problem is definitely there, I heard from people. I can't reproduce it in any way (and I think I can't make it). Usually happens with servers that are online for a long time without rebooting (about 2 days) and with a lot of online. But I couldn't get the logs(

**Comment by mirasrael** [comment] 2020-10-16 08:36
Seems like a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/17727 which already fixed.

**Comment by Guedez** [comment] 2020-10-17 13:10
This bug was reported the day it was reproduced on a up to date server

**Comment by mirasrael** [comment] 2020-10-21 14:23
Fix in 9.1 version which isn't yet released.

**Closed** 2020-11-11 05:34 UTC
Labels: Category: Gameplay, Priority: High, Type: Exploit
