### ISSUE TITLE
[Enhancement] Continue Server Online/Offline?

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3616] opened 2018-01-25 04:25 UTC
When a server is offline it still shows up when a person logs in the client as the server listed under "Continue" but there is no way for the user to know if that server is still really online.  That means, if it offline and the user clicks 'Continue' they then have a protracted wait until they get the 'connection failure' message.  Is there a way to put a "online/offline" message or symbol next to the server that is under "continue"?

**Comment by MarjieAVolk** [comment] 2018-02-03 22:16
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3619

**Closed by MarjieAVolk** 2018-02-03 22:16 UTC
Labels: Medium Priority
