### ISSUE TITLE
USER ISSUE: Invisible bloomery

### ISSUE THREAD

**Issue by Omegapol** [StrangeLoopGames/EcoIssues#9473] opened 2018-09-21 22:30 UTC
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Place bloomery
2. Walk far away from it.
3. Come back to where it was placed

**Expected behavior:**
It should be rendered again

**Actual behavior:**
Bloomery isn't rendered. Only what is visible is its outline and UI when hovered over it.
**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by D3nnis3n** [comment] 2018-09-21 22:41
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/9263

**Comment by seccombew** [comment] 2018-09-24 18:35
dupe

**Closed by seccombew** 2018-09-24 18:35 UTC
