### ISSUE TITLE
[8.0 Bleeding Edge] WebServer not start

### ISSUE THREAD

**Issue by McSassa** [StrangeLoopGames/EcoIssues#11094] opened 2019-02-06 00:08 UTC
On Windows 10, the EcoServer executable makes this error : 
`[12:21:28] Failed to start webserver: Method Not Found : 'Swashbuckle.Application.SwaggerEnabledConfiguration Swashbuckle.Application.HttpConfigurationExtensions.EnableSwagger(System.Web.Http.HttpConfiguration, System.Action`1<Swashbuckle.Application.SwaggerDocsConfig>)'.`

And of course no web server, so no laws, etc...

When I create a game using the client (same version 8.0 Bleeding Edge), I see no error but webserver doesn't work too.

**Comment by voyagebass** [comment] 2019-02-17 07:31
Same here: Fresh reinstall with 8.0.3, single player
[log_190217080019.log](https://github.com/StrangeLoopGames/EcoIssues/files/2872728/log_190217080019.log)

**Comment by elfl0rd** [comment] 2019-02-17 08:02
Duplicate of #11128

**Closed by elfl0rd** 2019-02-17 08:02 UTC
