### ISSUE TITLE
Weird Storage Icon Behviour (6.2.0 #737b5d74 )

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3012] opened 2017-12-05 19:28 UTC
![weird storage icon behaviour](https://user-images.githubusercontent.com/29383891/33626319-274fc20c-d9f2-11e7-8c12-3e432ec26ed4.gif)

This has happened in previous Versions, at last managed to get a decent recording to show how its behaving (as this is almost impossible to describe) sometimes you can just get an icon like this that just sits there, disconnecting and logging back in normally does NOT solve this, totally quitting Eco will. The number 4 its moving is not always the same (cannot even remember What i was moving to suddenly get this happening)
and its not always a storage chest it an also happen in a stockpile as well and not always the top left one, it can be ANY slot

**Comment by MarjieAVolk** [comment] 2017-12-05 19:41
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2955

Thanks for the video, didn't realize the icon was tied to a specific inventory slot.

**Closed by MarjieAVolk** 2017-12-05 19:41 UTC

**Comment by Conchipedia** [comment] 2017-12-05 20:08
i was lucky i found out which one for this video, when its on a stockpile full of identical stuff then its impossible to see which one it is
