### ISSUE TITLE
USER ISSUE: missing law feature - tree roots harvest

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8386] opened 2018-07-07 23:27 UTC
**Version:** 0.7.5.1 beta
Laws need way to control removing tree roots!

**Comment by MarjieAVolk** [comment] 2018-07-09 18:50
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4722

**Closed by MarjieAVolk** 2018-07-09 18:50 UTC
Labels: Laws, Medium Priority
