### ISSUE TITLE
USER ISSUE: Felled tree near grown tree crashed game when I chopped it

### ISSUE THREAD

**Issue by ChrisLCoray** [StrangeLoopGames/EcoIssues#4432] opened 2018-02-13 02:21 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. Chop a tree down and leave the trunk on the ground - or maybe it died and fell over, not sure
2. Plant a tree within 3 spaces
3. When new tree is grown, go back and chop on fallen tree

**Expected behavior:**
Let me chop up the fallen tree and remove the stump

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-13 02:23
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752 . You can continue tracking the issue progress there.

We have had a number of people reporting this with the same symptoms.  We are looking into it.

**Closed by MarjieAVolk** 2018-02-13 02:23 UTC
