### ISSUE TITLE
Posting a map showing a world layer lost the world layer when submitted

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15047] opened 2020-03-08 14:18 UTC
![image](https://user-images.githubusercontent.com/3536496/76164532-b0ee2680-618a-11ea-9ea9-521b3cc3995f.png)
Should be showing arctic willow population here

**Comment by denysaw** [comment] 2020-04-02 02:02
@johnkslg Can you gimme game save to test with? Cuzz I can't reproduce in my world :(
![image](https://user-images.githubusercontent.com/5720101/78203220-b0e5fb80-7496-11ea-816d-464d1c7e16f7.png)

**Comment by denysaw** [comment] 2020-04-02 14:36
Added `Fixed` label for QA's to re-test and reopen/add repr. steps in case it's still happens.

**Comment by beastyn** [comment] 2020-04-09 09:27
It still happens.
1) Make a law
2) Go the the web site for voting
3) Add comment and choose map with something like bighorn sheep capacity
![bandicam 2020-04-09 14-26-18-845](https://user-images.githubusercontent.com/27898520/78880051-373da700-7a6e-11ea-92d9-ab162ec757af.jpg)
4) Submit comment
![bandicam 2020-04-09 14-26-45-668](https://user-images.githubusercontent.com/27898520/78880065-3dcc1e80-7a6e-11ea-8a51-624922184d21.jpg)

**Comment by denysaw** [comment] 2020-04-09 22:43
Hey @Quadbro ! As I see we've sending everything correct, so probably GameServer issue, but check please F12->Network snapshot, maybe something is wrongly sent from browser and tell me what to change:
![image](https://user-images.githubusercontent.com/5720101/78946754-dd67cc00-7ac3-11ea-8389-9f6c0584e054.png)
Thanx! =) If everything correctly sent, then probably re-assign this issue on yourself. I've noticed doubling layers, I believe they also are coming from server (not hardcoded on a client), and the one with space doesn't work even in preview, so maybe in the Endpoint it changes it to incorrect layer... Dunno :) Check please.

**Comment by SlayksWood** [comment] 2020-04-28 09:13
I have problems with first comment:
![image](https://user-images.githubusercontent.com/45708377/80469657-88440b00-8949-11ea-92ea-578cf38d708e.png)
I added agouti layer on both. but my first comment don't show me it.

**Closed** 2020-06-01 06:12 UTC
Labels: Category: Web, Priority: Medium, Status: Fixed, Week Task
