### ISSUE TITLE
Something blocking view in government window

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17040] opened 2020-07-08 21:28 UTC
![image](https://user-images.githubusercontent.com/3536496/86972162-501a2f00-c127-11ea-8255-26061f976a2d.png)

**Comment by SlayksWood** [comment] 2020-07-13 13:01
Can't reproduce in staging-1657:
![image](https://user-images.githubusercontent.com/45708377/87307292-fe581700-c521-11ea-9303-422148d415ce.png)
@gzatravkin take a look and close if you can't reproduce it too.

**Comment by gzatravkin** [comment] 2020-07-31 21:07
Can't reproduce it neither. Closing (also looks like bug of TMPRo which maybe was solved by TMPRo version changes)

**Closed** 2020-07-31 21:29 UTC
Labels: Category: UI, Priority: Low, Week Task
