### ISSUE TITLE
Ecopedia busted

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18966] opened 2020-10-28 18:53 UTC
![image.png](https://images.zenhubusercontent.com/5ecc5c35b608cc220cfb5b6d/14de023e-dbe7-4898-9957-07fd7c6efa41)
In latest develop

**Comment by SlayksWood** [comment] 2020-10-29 05:46
From release:
> if you collapse all menu, then when you use the link, the active section's frame moves to where the menu item should be in the expanded form, but the menu itself does not expand
> 
> ![2020-10-09](https://user-images.githubusercontent.com/26339332/97490730-4afd1c00-1972-11eb-9787-cfbda7f2524e.png)

Also have problem with this:
![image](https://user-images.githubusercontent.com/45708377/97530339-f0d87700-19c2-11eb-9560-8ec05eacfa77.png)
 when you open animals first time.

**Comment by SlayksWood** [comment] 2020-10-29 05:46
Need to check in localization too.

**Comment by StallEF** [comment] 2020-10-29 11:37
![2020-10-15 (13)](https://user-images.githubusercontent.com/26339332/97563574-4aa56500-19f4-11eb-819c-18b60902150c.png)

**Comment by StallEF** [comment] 2020-10-29 17:42
![Uploading ссылки.png…]()

**Comment by SlayksWood** [comment] 2020-11-11 06:09
check this one after fixing #19260

**Comment by SlayksWood** [comment] 2020-11-13 10:59
Checked in 0.9.2 develop-112, open this one https://github.com/StrangeLoopGames/EcoIssues/issues/19310
but can't reproduce bug with category selector.
Closed for now.

**Closed by SlayksWood** 2020-11-13 10:59 UTC
Labels: Category: UI, Priority: Medium, Status: Fixed

**Comment by StallEF** [comment] 2020-12-04 08:12
@SlayksWood bug with category selector:
1)open page with active link on any page in end category
2)roll up all category
3) use link
