### ISSUE TITLE
USER ISSUE: Clam/Urchin/Kelp not giving patched items

### ISSUE THREAD

**Issue by XsExcess** [StrangeLoopGames/EcoIssues#6379] opened 2018-03-22 20:33 UTC
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Our server (Multiplay) has refused to give the correct materials when harvesting the underwater 'plants', they just either give the raw fish from the previous version, or in the case of kelp, nothing as before.

**Expected behavior:**
Getting Kelp/Urchin/Kelp items

**Actual behavior:**
Raw fish and nothing happens (when you gather kelp) as was the case in previous patches. This isn't the case on client made or steam server tool servers, these produce the expected behavior.

**Comment by craig-jong** [comment] 2018-03-27 01:15
Has your server owner changed EcoSim.eco? That's where the animal items are dropped. Double check that they're using the new configs for that.

You can also check in the server UI under Simulation -> Config -> Species.

**Comment by craig-jong** [comment] 2018-03-27 18:28
I'm going to close this because I'm pretty sure the issue is EcoSim related. If you're using the EcoSim from the latest release, the correct items should be dropped.

If your server owner has made edits to the simulation, this may not be the case. If that's the case, I would recommend just manually switching the species resource items for the water plants.

**Closed by craig-jong** 2018-03-27 18:28 UTC
Labels: High Priority
