### ISSUE TITLE
USER ISSUE: Can't Generate Plant Fibers

### ISSUE THREAD

**Issue by ericlevy67** [StrangeLoopGames/EcoIssues#19882] opened 2020-12-31 16:13 UTC
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Try using my sickle to reap grass, etc. to generate plant fibers.

**Expected behavior:**
placed plant fibers in my inventory

**Actual behavior:**
gave me nothing (sometimes gave me seeds for the plant I just reaped but never the plant fibers)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5757692/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5757693/Player-prev.log)

**Comment by IcedForge** [comment] 2021-01-06 13:08
Thank you for reporting.
Is this only using the sickle? Or is this a reoccuring issue for you with all plant interaction? Shovel for camas bulbs, tractor tools or hand picking as well?


I am seeing a lot of these errors but i'm not sure they are related to material harvest i have seen a bunch when it comes to log/mining debris ? maybe you can take a look @MazonDel 

Exception: Could not find matching method UpdatePhysicsPushPullState on type NetObjComponent taking 1 parameters.
  at Eco.Shared.Networking.RPCManager.InvokeOn (Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson, System.Object target, System.String methodname) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.RPCManager.HandleReceiveRPC (Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.TryReceivePacket () [0x00000] in <00000000000000000000000000000000>:0 
  at ClientPacketHandler.ReceiveWhile (Eco.Shared.Networking.NetworkClient client, TimeLimit timeLimit) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.EntityQueryBuilder+F_E.Invoke (Unity.Entities.Entity entity) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.PlannerGroup.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.FramePlannerSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.LambdaSingleJobDescriptionConstructionMethods+WithCodeAction.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
FramePlanner.PlannerGroup:OnUpdate()
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.WithCodeAction:Invoke()

**Comment by ericlevy67** [comment] 2021-01-06 22:07
It's happened with trying to collect certain items as well, although there does not seem to be any consistency in terms of what cannot be collected. For example, on one solo world, I was unable to collect crabs that I had killed. In another world, I could not collect beets or beans. So it is not just the sickle.
I have not had any issues with shoveling, and I have not advanced enough in any world to use tractors, so I do not know if that has been an issue.
    On Wednesday, January 6, 2021, 07:09:10 AM CST, Jens <notifications@github.com> wrote:  
 
 


Thank you for reporting.
Is this only using the sickle? Or is this a reoccuring issue for you with all plant interaction? Shovel for camas bulbs, tractor tools or hand picking as well?

I am seeing a lot of these errors but i'm not sure they are related to material harvest i have seen a bunch when it comes to log/mining debris ? maybe you can take a look @MazonDel

Exception: Could not find matching method UpdatePhysicsPushPullState on type NetObjComponent taking 1 parameters.
at Eco.Shared.Networking.RPCManager.InvokeOn (Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson, System.Object target, System.String methodname) [0x00000] in <00000000000000000000000000000000>:0
at Eco.Shared.Networking.RPCManager.HandleReceiveRPC (Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0
at NetworkManager.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0
at Eco.Shared.Networking.NetworkClient.TryReceivePacket () [0x00000] in <00000000000000000000000000000000>:0
at ClientPacketHandler.ReceiveWhile (Eco.Shared.Networking.NetworkClient client, TimeLimit timeLimit) [0x00000] in <00000000000000000000000000000000>:0
at Unity.Entities.EntityQueryBuilder+F_E.Invoke (Unity.Entities.Entity entity) [0x00000] in <00000000000000000000000000000000>:0
at FramePlanner.PlannerGroup.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0
at FramePlanner.FramePlannerSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0
at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0
at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0
at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0
at Unity.Entities.LambdaSingleJobDescriptionConstructionMethods+WithCodeAction.Invoke () [0x00000] in <00000000000000000000000000000000>:0
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
FramePlanner.PlannerGroup:OnUpdate()
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.WithCodeAction:Invoke()

**Comment by D3nnis3n** [comment] 2022-07-18 09:43
Closing issue due to old age and bever being reproduced. If a similar issue reappears for you, please feel free to open a new issue.

**Closed by D3nnis3n** 2022-07-18 09:43 UTC
Labels: Status: Investigate, Status: Needs Information
