### ISSUE TITLE
USER ISSUE: Picking up chpped tree log

### ISSUE THREAD

**Issue by ecofriendlyplastic** [StrangeLoopGames/EcoIssues#4334] opened 2018-02-11 16:38 UTC
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
cut trees and chop up, then pick up.  It's rare but does happan every so often. 

**Expected behavior:**
Found a cut tree, tried to pick up the log.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment] 2018-02-13 00:25
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668 . You can track the progress of the issue there.

It seems this happens occasionally, especially with logs that have been sitting around when the game is reloaded.  Hopefully we will fix it soon.

**Closed by MarjieAVolk** 2018-02-13 00:25 UTC
