### ISSUE TITLE
USER ISSUE: Stuck in Celling by door glitch

### ISSUE THREAD

**Issue by OlofMoister** [StrangeLoopGames/EcoIssues#6992] opened 2018-04-05 12:40 UTC
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
Step 1. Open door.

Step 2. Stand in door way.

Step 3. Close door while still in doorway

Step 4. get stuck in celling temporaly or permanetly

**Expected behavior:**
It should have just closed.

**Actual behavior:**
instead it got me permanetly stuck in the celling

**Comment by MarjieAVolk** [comment] 2018-04-05 18:12
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4140

**Comment by MarjieAVolk** [comment] 2018-04-05 18:12
You can use /unstuck to get out

**Closed by MarjieAVolk** 2018-04-05 18:12 UTC
