### ISSUE TITLE
USER ISSUE: connection failed

### ISSUE THREAD

**Issue by bfaltrep** [StrangeLoopGames/EcoIssues#4404] opened 2018-02-12 19:33 UTC
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1.on the menu, clic "New".
2.define a new game without generate a new map.
3.clic "start".
4.during the load, the screen go to the desktop.
5.clic on the game (on the bar).
6.the message "connection Failed" is here.

**Expected behavior:**
it should generate a new game.

**Actual behavior:**
Connection Failed message

**Comment by bfaltrep** [comment] 2018-02-12 19:40
it happend when it said "starting LoadGeneratorPlugin".
When I try to create a game or load a previously created game.

**Comment by MarjieAVolk** [comment] 2018-02-13 04:52
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4305.  You can continue tracking the issue there.

If you generate a new world instead, it may work for you.  If that still doesn't work, you can try launching the Eco Server tool separately and generating the world there.  Other players have reported that that works for them.

**Closed by MarjieAVolk** 2018-02-13 04:52 UTC
Labels: High Priority
