### ISSUE TITLE
USER ISSUE: fell off the world

### ISSUE THREAD

**Issue by alaskanranger** [StrangeLoopGames/EcoIssues#4856] opened 2018-02-20 05:08 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
world wasnt loaded in and walked off now crazy sound. lol going to try to re-log

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment] 2018-02-20 23:44
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861

**Closed by MarjieAVolk** 2018-02-20 23:44 UTC
