### ISSUE TITLE
Cart Linking exception

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2905] opened 2017-11-27 18:55 UTC
I had this same issue as well as my server being completely non-functional now after the cart caused it to crash.

I made the cart, put it in my inventory, chose a place to put it and as soon as i clicked to place it i was ejected from the server. The server runs on my home network so I looked at it and it was at the console, having crashed. I restarted the server but it simply crashed again and will not start up now.

![image](https://user-images.githubusercontent.com/774628/33283638-48fc7af4-d361-11e7-8e3a-38f302994fe8.png)

**Comment by MarjieAVolk** [comment] 2017-11-27 19:34
@metachronism There were two possibilities of which line was being called inside LinkComponent.Relink, but I'm guessing line 120 is the culprit, with the cause being that this.Parent is not initialized yet?

I'm not 100% sure now which fixes are where, but might this have already been fixed by changing the init/add order in WorldObjectManager add?

**Comment by MarjieAVolk** [comment] 2017-11-27 21:04
Marking this as already fixed

**Closed by MarjieAVolk** 2017-11-27 21:04 UTC
Labels: High Priority
