### ISSUE TITLE
USER ISSUE: Tree slice crash

### ISSUE THREAD

**Issue by NightW0lf93** [StrangeLoopGames/EcoIssues#5437] opened 2018-03-05 21:13 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Not sure how this happened, sorry

**Expected behaviour:**
Just cut a tree in two

**Actual behaviour:**
The following error message popped up:
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Objektreferencen er ikke indstillet til en forekomst af et objekt.

Stack:
   ved TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   ved Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   ved Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   ved Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   ved Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

PS. Not sure why some of this is in Danish. But "ved" is "at" or "by". And "Objektreferencen er ikke indstillet til en forekomst af et objekt." google translated is "Object reference is not set to an instance of an object."

**Comment by MarjieAVolk** [comment] 2018-03-05 23:19
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752

**Closed by MarjieAVolk** 2018-03-05 23:19 UTC
