### ISSUE TITLE
USER ISSUE: Game crash after missing drop

### ISSUE THREAD

**Issue by dmb1996** [StrangeLoopGames/EcoIssues#5021] opened 2018-02-24 00:29 UTC
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.Click and drag an item
2.Go to move its spot, accidently miss/miss by a little
3.A whole bunch of glitches occur

**Expected behavior:**
It should have either automatically but it back to the space it was or read what block it was nearet to and go there

**Actual behavior:**
Causes the mouse icon to stay in the "grabbed" state, the icon for the item stays on the screen, and from what I gathered is that everything you do after does not save, or at least inventory wise it will crash.

**Comment by MarjieAVolk** [comment] 2018-02-24 01:08
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Closed by MarjieAVolk** 2018-02-24 01:08 UTC
