### ISSUE TITLE
USER ISSUE: Fell through map

### ISSUE THREAD

**Issue by MorosePeregrine** [StrangeLoopGames/EcoIssues#4499] opened 2018-02-14 06:30 UTC
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
*Random occurance*

**Expected behavior:**
It should have not falled through the map...

**Actual behavior:**
Instead it fell through the map

**Comment by MarjieAVolk** [comment] 2018-02-14 21:34
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4167

**Closed by MarjieAVolk** 2018-02-14 21:34 UTC
