### ISSUE TITLE
game crash when opening the "economy viewer"

### ISSUE THREAD

**Issue by d4nlo3008** [StrangeLoopGames/EcoIssues#1444] opened 2017-05-06 18:19 UTC
as the titel said: the game crashes when opening the 'economy viewer' therefore we cant see the offers of the other players on the server. one of the key features of the game, the trading, becomes difficult now.

crash message:
http://prnt.sc/f4v4nx

**Comment by MGrand3** [comment] 2017-05-08 22:59
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1337

**Comment by MarjieAVolk** [comment] 2017-05-11 18:16
What version are you playing on?  This as well as your other exception (StrangeLoopGames/EcoIssues#1442) sound like bugs that have already been resolved on the most recent version

**Comment by d4nlo3008** [comment] 2017-05-22 17:16
Hello @MarjieAVolk 
I've saw your reply here: Im also on Alpha 5.5.4. These are two different crashes: One, when you want to open the economy viewer. The other (StrangeLoopGames/EcoIssues#1442) when you scroll down in the store list. 

Its already fixed in 0.5.6?

**Comment by MarjieAVolk** [comment] 2017-05-22 17:40
Hm, well if you are on 5.5.4 then it is probably still in 5.6, but it must be dependent on your game state somehow.

**Comment by MarjieAVolk** [comment] 2017-06-07 21:13
I *think* this is good now

**Closed by MarjieAVolk** 2017-06-07 21:13 UTC
Labels: High Priority
