### ISSUE TITLE
Tooltips keep refreshing when mouse is stationary

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20135] opened 2021-01-22 21:36 UTC
![animx22](https://user-images.githubusercontent.com/3536496/105550848-c1ca5c80-5cb6-11eb-9437-54ceb953f8cf.gif)

**Comment by IcedForge** [comment] 2021-02-09 10:19
Make sure to have the ctrl tooltip system enabled, is especially prominent when you mouse over the edge of objects.
![Screenshot_31.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/d7a3bd3d-6c85-4dc3-be25-b73368c554ff)

**Comment by Mattprass** [comment] 2021-02-15 15:08
Going to need explicit steps to reproduce, as I still cannot reproduce this behavior.

**Comment by SlayksWood** [comment] 2021-02-25 08:36
created a new issue ##20736, closed this one.

**Closed by SlayksWood** 2021-02-25 08:36 UTC
Labels: Category: UI, Priority: High, Squad: Wild Turkey, Status: Fixed
