### ISSUE TITLE
USER ISSUE: Item is stuck in backpack, not movable

### ISSUE THREAD

**Issue by thunderbom** [StrangeLoopGames/EcoIssues#6651] opened 2018-03-29 12:06 UTC
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Don't know

**Expected behavior:**
Ability to move stack of 5 torches to other free slot in the backpack or to chest or to stand.

**Actual behavior:**
Not possible to move stack of 5 torches inside backpack to other free backpack slots or somewhere else, torches are not usable and they occupy 1 backpack slot forever. No any errors appear.
![torches](https://user-images.githubusercontent.com/30559770/38087936-bb045d5e-3362-11e8-9804-6373013d9acc.jpg)

**Comment by MarjieAVolk** [comment] 2018-04-03 18:13
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6598

**Closed by MarjieAVolk** 2018-04-03 18:13 UTC
