### ISSUE TITLE
USER ISSUE: Dragging deed from small wood cart

### ISSUE THREAD

**Issue by MrCakeZombie** [StrangeLoopGames/EcoIssues#4200] opened 2018-02-09 23:08 UTC
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. create a small wood cart 2. place down 3. drag small wooden cart deed while near stockpile into stockpile

**Expected behavior:**
(I forgot that stockpiles only accept resources) I expected that the stockpile would not accept the small wooden cart deed and instead place it back in the small wooden cart once I released mouse1

**Actual behavior:**
Instead, the deed item portrait got stuck on the screen in the place I tried to drop it. Cursor icon is stuck as if it was grabbing something.

**Comment by MarjieAVolk** [comment] 2018-02-13 04:27
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841. You can track the issue progress there.

I hadn't heard until today that dragging it into an invalid item slot was related to this issue.  That may be helpful.  If you have any more details to share, every little bit helps!

**Closed by MarjieAVolk** 2018-02-13 04:27 UTC
