### ISSUE TITLE
Suggestion - Can you add in Fir tree seeds and Oak tree seeds?

### ISSUE THREAD

**Issue by Khazul01** [StrangeLoopGames/EcoIssues#4223] opened 2018-02-10 03:53 UTC
Can you add in Fir tree seeds and Oak tree seeds?

**Comment by LiaungYip** [comment] 2018-02-10 11:55
Duplicate of #4121.

**Comment by MarjieAVolk** [comment] 2018-02-13 05:25
Thank you.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4121.  You can track the issue progress there.

**Closed by MarjieAVolk** 2018-02-13 05:25 UTC
