### ISSUE TITLE
Falling though world

### ISSUE THREAD

**Issue by Doombuny** [StrangeLoopGames/EcoIssues#6812] opened 2018-03-31 20:13 UTC
Hello, reporting an issue about falling through map.

My friends and i are falling through the world at random locations that either dont load or glitch out. Disconnecting and reconnecting seems to work but sets you back a distance. I actually ended up getting a cart full of wood duplicated. (Used it all for hewn logs. Then glitched through a block. Then spawned back where i had it full.) Also can see though some blocks underground while digging a tunnel, might be related to unloading blocks and falling through.

**Comment by Epimetheus89** [comment] 2018-03-31 20:48
Seems to be a duplicate of #5917

**Comment by MarjieAVolk** [comment] 2018-04-04 22:31
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5917

**Closed by MarjieAVolk** 2018-04-04 22:31 UTC
