### ISSUE TITLE
[Art][Low Priority] Still no Sound on Hitting large piece of Coal Rubble

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5644] opened 2018-03-08 02:01 UTC
**Version:** 0.7.2.2 beta

Everything other Large Rubble makes sound, just not coal

**Comment by Conchipedia** [comment] 2018-04-09 20:07
still not working 0.7.3.2

**Comment by Nanders** [comment] 2018-06-18 22:21
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4454

**Closed by Nanders** 2018-06-18 22:21 UTC
Labels: Medium Priority
