### ISSUE TITLE
USER ISSUE: Exception in GetOrCreateUser

### ISSUE THREAD

**Issue by amboo515** [StrangeLoopGames/EcoIssues#4083] opened 2018-02-08 02:18 UTC
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
tried to rejoin game

**Expected behavior:**
join the game

**Actual behavior:**
The following error message popped up:
```<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC SpawnPlayer on Client!

Value cannot be null.
Parameter name: key


Stack:
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableDictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Players.UserManager.GetOrCreateUser(String userID, String username)
   at Eco.Gameplay.Players.Player..ctor(String username, String userId, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Clients.Client.SpawnPlayer(Single viewDistance)

<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC SpawnPlayer on Client!

Value cannot be null.
Parameter name: key


Stack:
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableDictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Players.UserManager.GetOrCreateUser(String userID, String username)
   at Eco.Gameplay.Players.Player..ctor(String username, String userId, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Clients.Client.SpawnPlayer(Single viewDistance)

```

**Comment by MarjieAVolk** [comment] 2018-02-08 04:18
So, you had logged in to this server previously, and now you are logging in again.  Have you been playing through steam the entire time?  Or have you downloaded the game from our website?  Do you have an account with Strange Loop, or just a steam key?

**Comment by MarjieAVolk** [comment] 2018-02-08 04:32
Okay, never mind, I think I have found a fix for this.  Closing this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4085 - You can continue tracking the issue progress there if you like

**Closed by MarjieAVolk** 2018-02-08 04:32 UTC
Labels: High Priority
